### PR TITLE
Clarification of the affiliate release procedure

### PR DESCRIPTION
**Pull request by nden**
According to the git documentation pushing tags requires only a remote server name, not a branch.

### CODE REVIEW

**Comment by nden** [comment]
I've been trying to figure out why I am confused about the release instructions.
Is it assumed that the release is done in a fresh clone of the remote upstream repository?

(Retrospectively it's the only thing that makes sense with these instructions but it's not mentioned anywhere. And following the instructions from a regular work environment which follows the astropy workflow creates unforgettable memories.)

I can either close this PR (I understand now it pushes tags and changes) or change it to clarify that it starts from a clone of upstream (assuming this is correct). @astrofrog

**Comment by astrofrog** [comment]
I think that the release should indeed be done in a clean clone to avoid any issues.

I'll defer to @embray for this PR.

**Comment by nden** [comment]
@embray I added a clarification in the release instructions. 
It is stated at the top of the page that these instructions work for git as used by astropy (which means one has a fork of a main repository). All but the last two release instructions work if this assumption is met and if the release is done in a regular working area. However, the last two commands use `origin` and `master` and it is not clear what they point to and in fact they may point to the forked repository.
Feel free to merge or close.

**Comment by hamogu** [comment]
Seems like a fairly unambiguous change to me. Is there any reason this has not been merged for over a year?

**Comment by pllim** [comment]
I think this is @bsipocz 's turf now.

**Comment by bsipocz** [comment]
This indeed seems to be a quite innocent change, though I've never followed this procedure (as I have never released an affiliate). However the title needed to be changed before mergin to have something about the actual content.

**Pull request merged**
