### PR TITLE
Improvements to cache location management and documentation

### PR DESCRIPTION
**Pull request by embray**
Inspired by a [similar feature](https://github.com/astropy/halotools/pull/101) @aphearin recently added for testing halotools, and various other discussions with @cdeil and others around this issue, this PR adds a new helper called `set_temp_cache` which can temporarily set the cache directory used by all functions that access the cache, to a custom location.  `set_temp_cache` can be used either as a decorator or as a context manager (using the "with" statement).  It is accompanied by a similar `set_temp_config` for setting the config directory in a similar manner, though this has less immediate use.  This all works, also, without dorking around with environment variables.

This also adds a `cache_dir` test option that can be set either in the py.test config file (or setup.cfg), or via the command-line.  This sets the cache directory for the entire test run, overriding the default use of a disposable temp dir for the cache.  Any combination of these techniques may be used within a single test suite to control use of the download cache.

A bit of documentation about this has been added to the test writing guidelines, but it's only a mere start to the more comprehensive data management documentation discussed in #700.

### CODE REVIEW

**Comment by embray** [comment]
Acck.  Forgot to add the `astropy.utils.argparse` module I added...

**Comment by embray** [comment]
Rebased, and did a little squashing...

**Comment by aphearin** [comment]
Very nice looking code, @embray . The context manager is especially slick. I think this is exceedingly useful for blackbox testing with "big data" packages. I'll start using this feature more or less right away.

**Comment by embray** [comment]
Thanks for the feedback @aphearin.  I only hope it works that well in practice--if it will make things easier to test I'll merge this ASAP.  I'll be interested to find what works and what doesn't in practice.

**Comment by embray** [comment]
Actually, the tests passed so I will go ahead and merge this now so that it can be tried out.  We'll readjust as needed.

**Pull request merged**
