### PR TITLE
 Fix for--Tables with columns of strings can't be written to hdf5 with python 3 

### LINKED ISSUE #5286: Tables with columns of strings can't be written to hdf5 with python 3
Example using astropy 1.2.1 and python 3.5:

```
In [1]: from astropy.table import Table
   ...: tx = Table()
   ...: tx['x'] = ['a', 'bb', 'cc']
   ...: tx.write('blat.h5', path='blat', overwrite=True)
   ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-b579fbff894e> in <module>()
      2 tx = Table()
      3 tx['x'] = ['a', 'bb', 'cc']
----> 4 tx.write('blat.h5', path='blat', overwrite=True)

/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/astropy/table/table.py in write(self, *args, **kwargs)
   2347         passed through to the underlying data reader (e.g. `~astropy.io.ascii.write`).
   2348         """
-> 2349         io_registry.write(self, *args, **kwargs)
   2350 
   2351     def copy(self, copy_data=True):

/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/astropy/io/registry.py in write(data, *args, **kwargs)
    401 
    402     writer = get_writer(format, data.__class__)
--> 403     writer(data, *args, **kwargs)
    404 
    405 

/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/astropy/io/misc/hdf5.py in write_table_hdf5(table, output, path, compression, append, overwrite, serialize_meta)
    238                                     compression=compression, append=append,
    239                                     overwrite=overwrite,
--> 240                                     serialize_meta=serialize_meta)
    241         finally:
    242             f.close()

/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/astropy/io/misc/hdf5.py in write_table_hdf5(table, output, path, compression, append, overwrite, serialize_meta)
    262                                            compression=compression)
    263     else:
--> 264         dset = output_group.create_dataset(name, data=table.as_array())
    265 
    266     if serialize_meta:

/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    103         """
    104         with phil:
--> 105             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    106             dset = dataset.Dataset(dsid)
    107             if name is not None:

/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
     91         else:
     92             dtype = numpy.dtype(dtype)
---> 93         tid = h5t.py_create(dtype, logical=1)
     94 
     95     # Legacy

h5py/h5t.pyx in h5py.h5t.py_create (/Users/ilan/minonda/conda-bld/work/h5py/h5t.c:16090)()

h5py/h5t.pyx in h5py.h5t.py_create (/Users/ilan/minonda/conda-bld/work/h5py/h5t.c:15924)()

h5py/h5t.pyx in h5py.h5t.py_create (/Users/ilan/minonda/conda-bld/work/h5py/h5t.c:15422)()

h5py/h5t.pyx in h5py.h5t._c_compound (/Users/ilan/minonda/conda-bld/work/h5py/h5t.c:14666)()

h5py/h5t.pyx in h5py.h5t.py_create (/Users/ilan/minonda/conda-bld/work/h5py/h5t.c:15924)()

h5py/h5t.pyx in h5py.h5t.py_create (/Users/ilan/minonda/conda-bld/work/h5py/h5t.c:15883)()

TypeError: No conversion path for dtype: dtype('<U2')
```

Although I understand that hdf5 doesn't have native support for numpy-style 4-byte unicode (is there a name for that encoding?), it would be very handy if Tables with native py3 strings could be written to hdf5.  e.g. consider using `np.core.defchararray.encode()` to convert to bytes for I/O, while keeping as `str` in the `Table`.

### PR DESCRIPTION
**Pull request by ananyashreyjain**
This fix will allow the Tables with native py3 strings  to be written to hdf5.`np.core.defchararray.encode()` is used to convert py3strings to bytes for I/O (as was suggested to fix this issue) which can be then converted to hdf5 format.

EDIT: Fix #5286.

### CODE REVIEW

**Comment by bsipocz** [comment]
@ananyashreyjain - You already have #6998 open. Is this new PR supersedes that one? Also, please try to add a title that summarize the content of a PR rather than referring to an issue number.

**Comment by ananyashreyjain** [comment]
I am extremely sorry i should have upgraded the old PR.

**Comment by bsipocz** [comment]
@ananyashreyjain - No worries, I'll just close that one now as a duplicate.

**Comment by ananyashreyjain** [comment]
I am done with the changes.PR is ready for review

**Comment by ananyashreyjain** [comment]
@bsipocz is this PR fine or does it require some changes?

**Comment by bsipocz** [comment]
@ananyashreyjain - A module maintainer will have to review it, and if they are happy with the approach this will need a test and a changelog. 

I'll have a few code formatting nit picking comments, too but that can wait until the review.

**Comment by taldcroft** [comment]
@ananyashreyjain - this is potentially a good idea, but your implementation is not yet on the right track.

- It should live in `astropy/io/misc/hdf5.py` not in `astropy/table/table.py`.
- The encoding should be specified as `utf-8` (I think!)
- You cannot use `self.replace_column` because that is actually modifying the users table in place.
- Use `dtype.kind == 'U'` for finding unicode columns.

And of course tests.  In general you should not open a PR for a new feature without having new tests that are passing locally on your machine.

**Comment by taldcroft** [comment]
@ananyashreyjain - be sure to start (or rebase) from the latest master.  #7007 which was just merged makes a bunch of changes in `astropy/io/misc/hdf5.py`.

**Pull request closed without merging**
