### PR TITLE
Suppress config loading with ASTROPY_SUPPRESS_CONFIG

### LINKED ISSUE #5899: Suppress configuration file loading
Is it possible to suppress the loading of configuration files?

If not, what would be the best way to implement such functionality?
Would to PR...

### LINKED ISSUE #6511: XDG_CONFIG_HOME failing silently caused confusion
I ran into a group who would have benefited from #5899. However, since that is not yet possible, they tried to set two different directories for different versions of Astropy to run in parallel on the same file system on the same cluster. Otherwise, they run into a problem of `astropy.cfg` getting corrupted by the parallel attempts to write it.

Despite instructions at http://astropy.readthedocs.io/en/latest/config/index.html that says, "... if you’ve set the environment variable `XDG_CONFIG_HOME` and the `$XDG_CONFIG_HOME/astropy` directory exists, it will instead be there," they set `XDG_CONFIG_HOME` that included the "astropy" sub-directory. As a result, the check for `$XDG_CONFIG_HOME/astropy` failed (because it was really looking for `$XDG_CONFIG_HOME/astropy/astropy`) and fell back silently to the default `~/.astropy/config`, which caused a lot of confusion.

Suggestion: If `XDG_CONFIG_HOME` is defined but the desired directory is not found, raise an exception (too much?) or at least emit a warning.

### LINKED ISSUE #7290: Concurrent import of astropy occasionally fails with likely race condition on config files.
When trying to import astropy from an MPI application ( with 128 ranks), the application crashes during first import randomly with a file system error.

It appears that some astropy instances are trying to modify a configuration file while some others are trying to read it. 

```
    from astropy.cosmology import Planck13, Planck15, WMAP5, WMAP7, WMAP9
  File "/dev/shm/local/lib/python3.6/site-packages/astropy/__init__.py", line 286, in <module>
    log = _init_log()
  File "/dev/shm/local/lib/python3.6/site-packages/astropy/logger.py", line 97, in _init_log
    log._set_defaults()
  File "/dev/shm/local/lib/python3.6/site-packages/astropy/logger.py", line 473, in _set_defaults
    self.setLevel(conf.log_level)
  File "/dev/shm/local/lib/python3.6/site-packages/astropy/config/configuration.py", line 273, in __get__
    return self()
  File "/dev/shm/local/lib/python3.6/site-packages/astropy/config/configuration.py", line 396, in __call__
    sec = get_config(self.module)
  File "/dev/shm/local/lib/python3.6/site-packages/astropy/config/configuration.py", line 530, in get_config
    cobj = configobj.ConfigObj(cfgfn, interpolation=False)
  File "/dev/shm/local/lib/python3.6/site-packages/astropy/extern/configobj/configobj.py", line 1228, in __init__
    self._load(infile, configspec)
  File "/dev/shm/local/lib/python3.6/site-packages/astropy/extern/configobj/configobj.py", line 1317, in _load
    raise error
astropy.extern.configobj.configobj.ParseError: Invalid line ('\x00\x00\x00\x00\x00\x00\x00\x00\x00
....
```

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to allow suppressing the loading of `astropy.cfg` when `ASTROPY_SUPPRESS_CONFIG` environment variable is set. This is a revival of #5907 by @funbaker and a little more to account for import-time loading and code changes since that PR was written.

**Side effect:** This suppresses not just loading of `astropy.cfg` but also `.cfg` of all the other packages that uses `astropy.config` configuration system.

**TODO**

- [x] Is side effect acceptable?
- [x] Do we need what's new entry?

Fix #5899 

Close #7290 

Close #6511

### CODE REVIEW

**Comment by saimn** [comment]
I wonder in the first place why we enforce loading a configuration file if it is not there. I mean, there is an easy solution to this: if the config file does not exists, do nothing and just use the default config. That's a common pattern for many software, where config files are optional.

The problem, I think, is that this default config file is used mostly as a mean to document the config items and their default value ? Because this list of config items is built dynamically by each sub-package declaring items, there is no centralized version of it, and it does not appear in the documentation as well. But instead of always creating this default config file, we could have a function creating it on demand, and better documentation of the config items.

**Comment by pllim** [comment]
> why we enforce loading a configuration file if it is not there

The original intent is lost on me, but I guess this is for first time installation, so that the cfg file will be where it is supposed to be and user will only have to edit it for customization? Otherwise, there is this extra manual step of "where am I supposed to copy this file to"?

> if the config file does not exists, do nothing

We could, but this is a breaking change and we cannot backport. It won't solve the problem of people stuck with astropy 4.0.x (or even 4.x) and wants to suppress loading it.

**Comment by saimn** [comment]
Not reading the config file if it doesn't exist would not be a breaking change, since this would be equivalent to reading a config file that was not modified.
What could be a more important change would be to not write this default config file, and instead have a function to create it on demand, at the same place where it is put currently.

**Comment by bsipocz** [comment]
@pllim - at the minimum this needs a rebase, but maybe also some revision now that #10148 is merged

**Comment by pllim** [comment]
Rebased. Although I am not optimistic that this is going to make it to 4.1.

**Comment by mhvk** [comment]
Clearing milestone as this has not converged yet. Not that it wouldn't be good to solve!

**Comment by pllim** [comment]
I agree. Thanks, @mhvk !

**Comment by embray** [comment]
I would say "yes" to the side-effect of not loading other config files being acceptable.  In some sense these package-specific config files are extending the astropy configuration.  The point is to suppress all loading of non-default configurations.

Unless someone else feels strongly about it, I would say "no" to "needs 'what's new' entry".  This is mostly useful for development/testing.  Its main use to "average" users might be to help them debug issues with their personal configuration, but in this case we can tell them about `ASTROPY_SUPPRESS_CONFIG` when the need arises.  It's also in the documentation so I think that's good enough.

**Comment by embray** [comment]
I resolved the latest merge conflicts.  I can mark as approved pending successful CI.

**Comment by mhvk** [comment]
Agreed with the logic.

**Comment by bsipocz** [comment]
@embray - please rebase rather than have master merge commits.

**Comment by embray** [comment]
Since 4.1 is in release candidate stage and already delayed, perhaps I should postpone this to 4.2?

**Comment by pllim** [comment]
Sure!

**Comment by pllim** [comment]
I got rid of the merge commit and rebased. FYI.

**Comment by pllim** [comment]
It's been so long that I don't remember where we stand with this anymore. If there is more code change necessary for this PR, please let me know. Thanks!

**Comment by pllim** [comment]
So, am I correct in my understanding that this PR has been superseded by #10877 , @saimn and @astrofrog ?

**Comment by saimn** [comment]
In my opinion yes, but @astrofrog may think otherwise (see discussion in #10738).

**Comment by pllim** [comment]
Well, in that case, I don't think this is making it into 4.2. Should we move milestone for both the PRs?

**Comment by astrofrog** [comment]
No strong opinions from my side, so close if you like :)

**Pull request closed without merging**
