### PR TITLE
WCS index conversion functions

### PR DESCRIPTION
**Pull request by DanRyanIrish**
### Description

This PR adds util functions to convert between array axis indices, WCS pixel axis indices, and WCS world axis indices based on ```world_axis_physical_types``` and the ```axis_correlation_matrix```.  It also provides functions to determine which WCS axes are dependent.  These are highly useful convenience functions for users and developers alike.

Fixes #<Issue Number>

### CODE REVIEW

**Comment by Cadair** [comment]
FTR this is code that was originally written in sunpy/ndcube#280.

**Comment by Cadair** [comment]
Given this PR has seen no attention in over 3 months, I am going to bump it to 4.3

**Comment by eteq** [comment]
Since this hasn't made the feature freeze cutoff and is not a bug/docfix I'm re-milestoning to 5.0

(but I think it should get reviewed! If @nden or @astrofrog or myself get to this and think it's good as it stands I'd be willing to backport it if there's time before we get 4.3 out)

**Comment by nden** [comment]
Reopening this PR to review it in the near future.

**Comment by astrofrog** [comment]
I am re-milestoning to v5.1 as we've now branched v5.0.x

**Pull request closed without merging**
