### PR TITLE
Bugfix for key error in `fix_inputs` models `input_units_equivalencies` property

### LINKED ISSUE #10319: issue with fix_inputs and default equivalencies
`Model.input_units_equivalencies` crashes when the model is the result of `fix_inputs` operation and the constituent models have no equivalencies set.

```
p = Polynomial1D(1, c0=1, c1=2)
m = p & p
mf = fix_inputs(m, {'x0': 1})
mf.input_units_equivalencies                                                 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-59-92566a4c98dd> in <module>
----> 1 mf.input_units_equivalencies

~/dev/astropy/astropy/modeling/core.py in input_units_equivalencies(self)
   3128         inputs_map = self.inputs_map()
   3129         return {key: inputs_map[key][0].input_units_equivalencies[orig_key]
-> 3130                 for key, (mod, orig_key) in inputs_map.items()
   3131                 if inputs_map[key][0].input_units_equivalencies is not None}
   3132 

~/dev/astropy/astropy/modeling/core.py in <dictcomp>(.0)
   3129         return {key: inputs_map[key][0].input_units_equivalencies[orig_key]
   3130                 for key, (mod, orig_key) in inputs_map.items()
-> 3131                 if inputs_map[key][0].input_units_equivalencies is not None}
   3132 
   3133     @property

KeyError: 'x1'

```
It looks like `fix_inputs` changes the default value of `input_units_equivalencies` of the constituent models from `None` to `{}`. This results in a crash when trying to access the property.
From the above example, accessing the property on the child models gives different results.
```
m.inputs_map()['x1'][0].input_units_equivalencies
None

mf.inputs_map()['x1'][0].input_units_equivalencies
{}
```

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

This PR is an update of PR #10359 by @Iamsoto which was auto-closed. It fixes a key error which arises in `fix_inputs` models when using the `input_unitist_equivalencies` property. See #10359 for details.

Fixes #10319. Closes #10359.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Tagging @nden, these are the same changes you approved in PR #10359 with some minor codestyle changes.

**Review by nden — COMMENTED** [review]
Looks good. A couple minor suggesitons.

**Review by nden — APPROVED** [review]
Ready to be merged after CI pass.

**Comment by pllim** [comment]
I don't see any doc changes, so I guess we don't  have to care that RTD is stuck.

**Pull request merged**
