### PR TITLE
Fixing 4.1 whatsnew typo 

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Good catch. Thanks!

**Comment by bsipocz** [comment]
hmm, what does azure not understand on `skip ci`?

**Comment by bsipocz** [comment]
And I cannot cancel the pipeline....

**Comment by pllim** [comment]
Azure doesn't respect "ci skip" on a PR because it is from a forked branch (not sure why, but that's how it is). It does respect it on merge into `master` (with is opposite of what we are used to). It is also aggravating that they won't fix it even when they claim to support OSS development and all that.

https://developercommunity.visualstudio.com/content/problem/891360/skip-ci-in-pull-request-build.html

**Pull request merged**
