### PR TITLE
Dropping support for numpy 1.17

### PR DESCRIPTION
**Pull request by bsipocz**
Second part of #11934 due to changelog issues , dropping numpy

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Looks good! Obviously, a failure with a matplotlib version test, but otherwise it all looks good. Thanks!

**Comment by bsipocz** [comment]
yes, those tests will be modified in #11934, so I suppose I'll just hack it around here to mimic a passing status and rebase that other PR...

**Comment by pllim** [comment]
@bsipocz , are you sure you don't want to merge this and #11934 back into one PR? I think you mentioned on Slack that you found a workaround for the change log problem?

**Comment by bsipocz** [comment]
@pllim - Yes, I would do that if I were starting it again, but this part can be now merged as is, and the other PR needs more work/wait for the mpl test images. So in the interest of having the trivial part into the codebase sooner, I would suggest to merge this now, and I rebase the other PR on top.

**Review by pllim — APPROVED** [review]
Okay, let's get this in then. Thank you!

**Pull request merged**
