### PR TITLE
RFC: refactor internal usage of copy=False to copy=COPY_IF_NEEDED

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description

~This pull request will be pushed in 5 layers because we need to run CI 5 times to validate it.
I'll edit this message once it's ready.~

> **Update**: actually, 6 times.

This applies the first step described in #16167: making backward compatibility shims introduced in #16142 redundant for internal usage. It is meant to be reviewed commit-by-commit. Particularly, the exit status of devdeps is crucial.
- commit 1 removes compatibility shims -> devdeps fails (this demonstrate their current necessity)
- commit 2 reverts commit 1 -> devdeps succeeds anew
- commit 3 applies internal refactor that should make compatibility shims redundant for internal usage, but *doesn't change any API* (default values `copy=False` are preserved) -> devdeps still succeeds 
- commit 4 removes compatibility shims again -> devdeps fails !
- commit 5 introduces minimal API changes (`copy=False` becomes `copy=COPY_IF_NEEDED` in signatures) -> devdeps succeeds once again !
- commit 6 reverts commit 4

> **Update again**: commit 4 was split out to #16174, but I think keeping the old explanation is maybe less confusing (?) so for now I don't want to edit it further.

By construction, 4 out of 6 commits should cancel out, so squash merging is expected.
Also note that commit 3 is, in itself, a pure refactor, and *could* be backported (but I don't know that it's wanted). Minor API changes from commit 5 are aimed for astropy 6.1, but could also be rerolled in its own PR if requested (its presence in this PR is supposed to help demonstrating that it's needed in the grand scheme of #16167, but maybe that's only making it more confusing ?).

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
A couple missing labels should be added manually:
- coordinates
- modeling

**Comment by neutrinoceros** [comment]
Copying from the today's call notes :
> Consensus is to keep it simple: Astropy shall match whatever the installed numpy version does. Avoid work to put in and later remove again compatibility layers, configuration options etc. 

I'll split out the small signature changes to a separate PR so this one stays a pure refactor and can be merged consensually.
When the refactor part is merged I'll send an update to the dev mailing list to encourage downstream to test it early.

**Review by pllim — COMMENTED** [review]
At a glance, this PR looks reasonable. I will give subpackage maintainers some time to review. Thanks!

**Review by nden — APPROVED** [review]
The changes in modeling look good to me.

**Comment by neutrinoceros** [comment]
I rebased to get around that merge requirements changed after #15603 was merged. As a result, we lost easy access to CI logs that I prepared for reviewers. Hence, I encourage checking out the branch locally and running a fraction of the test suite[^1] against all commits in the branch if you want to check my story.

[^1]: running the tests of the subpackage you're reviewing for is probably enough

**Comment by neutrinoceros** [comment]
closing/reopening to retrigger CI now that pytest-doctestplus was updated

**Review by mhvk — APPROVED** [review]
This looks all good. Your extra commits effectively allowed you to test that this covers everything, correct?

Is the idea to get just the one commit in as well? That would seem fine to me.

**Comment by neutrinoceros** [comment]
> Your extra commits effectively allowed you to test that this covers everything, correct?

that's right. I ran the whole test suite at each step so I'm confident that the interesting commit is complete.

> Is the idea to get just the one commit in as well? 

Squash-merging should be equivalent to dropping the 4 extra commits, but I'm happy to go with any strategy you like best.

**Comment by mhvk** [comment]
Sorry, I wasn't clear: is the idea that now we know this works, we merge this one too so that the other two can be rebased on it? (Happy to squash-merge)

**Comment by neutrinoceros** [comment]
Oh, sorry I didn't get that ! yes, that is the plan !

**Pull request merged**
