### PR TITLE
TST: Use carryforward in codecov

### LINKED ISSUE #13936: TST: Add codecov flags for better coverage math
As suggested by @jdavies-st in https://github.com/astropy/astropy/pull/13928#issuecomment-1296804175

*If you have one CI job that does one subset of tests and another that does some other subset, then you'll want to use codecov flags to label these. That way they can be compared to like "flags" and one subset won't be compared to another.*

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to have codecov math makes more sense by using "carryforward".

Fixes #13936

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
```
codecov/project — 91.19% (+7.29%) compared to 75c5e83
```

Does this mean it works?

**Comment by jdavies-st** [comment]
I don't think this PR is changing anything.  One needs to define flags first, label them as carryforward, and then when the upload happens in CI, make sure the flag is used.  An example from `jwst` package where there are 2 flags, `unit` and `nightly`.

https://github.com/spacetelescope/jwst/blob/f4081ef2afa7f558d93e99ce64e8bac6340a094d/.codecov.yml#L16-L20

`unit` tests are the per-PR CI tests that are run.  `nightly` are the unit tests plus regression tests.  So `nightly` runs have much higher coverage than `unit` alone, and therefore per-PR coverage reports should only compare against previous `unit` coverage, and carryforward the previous night's `nightly` coverage.

They are uploaded like the following:

https://github.com/spacetelescope/jwst/blob/f4081ef2afa7f558d93e99ce64e8bac6340a094d/.github/workflows/ci.yml#L98-L104

and

https://github.com/spacetelescope/jwst/blob/f4081ef2afa7f558d93e99ce64e8bac6340a094d/JenkinsfileRT#L90

**Comment by Cadair** [comment]
I am not sure I fully understand this but I don't think carry forward is relevant to astropy because we run all cov jobs on every commit?

**Comment by pllim** [comment]
Yeah, I don't grok either. I thought this would combine coverage from different jobs in the same commit. We don't run coverage in nightly nor do we use Jenkins.

**Comment by astrofrog** [comment]
Codecov already combines all jobs for a given commit so I agree that this might not be needed.

**Comment by jdavies-st** [comment]
Agree.

**Comment by pllim** [comment]
Then I don't know why there is a 7% increase in coverage. But I also don't have time to pursue the math, so let's just close, huh?

**Pull request closed without merging**
