### PR TITLE
fixed wrong rendered changelog entry and contributor name [skip ci]

### PR DESCRIPTION
**Pull request by MSeifert04**
And I also added myself as contributor. I hope that's okay.

And I really hope ``J. Xavier Prochaska`` is really ``Jason Xavier Prochaska``. Is there any way to find out for sure? I googled for a while and found no GitHub name but some homepages (probably) about him calling him "Jason"

### CODE REVIEW

**Comment by MSeifert04** [comment]
Should I remove the change regarding `J. Xavier Prochaska` so this PR can be merged? Or is there anything controversial?

**Comment by pllim** [comment]
IMHO, if there is no way to verify for sure that J stands for Jason, it is best to keep it as-is.

**Comment by MSeifert04** [comment]
@pllim Ok I've reverted that change. Should I add an issue about it or is there another way to keep sphinx from rendering his initial `J.` as the start of a list?

**Comment by pllim** [comment]
Ah, I see the problem now. I fixed it in #4777.

**Comment by pllim** [comment]
Thanks, @MSeifert04 . I think this is okay to merge, but I am not sure how to milestone it (1.0.10 or 1.1.3), so I am leaving this open until someone can comment on the correct milestone to use.

**Comment by MSeifert04** [comment]
@pllim You could have just told me how to fix it. :smile: This won't cause merge conflicts?

**Comment by bsipocz** [comment]
@MSeifert04 - You can see if it conflicts here: the green check above the comment box changes to a grey one.

**Comment by MSeifert04** [comment]
@bsipocz Thank you. I always had the impression this just determines if there are conflicts with the current master not with other (unmerged) PRs. Thank you for the clarification.

**Comment by bsipocz** [comment]
Ohh, sorry you're right. I somehow assumed that the other PR is already merged...

**Comment by pllim** [comment]
We can always merge this one first and I'll resolve any conflict on the other one. ;)

**Comment by pllim** [comment]
That PR was just me being lazy. I was experimenting with a fix, found it, and just pushed it out as PR. If you use that fix here, I'll just close mine. I apologize for any inconvenience caused.

**Comment by MSeifert04** [comment]
@pllim No problem. I was just surprised.

**Comment by pllim** [comment]
This looks uncontroversial enough, especially given that you're listed as contributor No. 24 in ranking as of this morning. I'm just going to merge this. If someone thinks I tagged the wrong milestone, feel free to change it.

**Pull request merged**
