### PR TITLE
fix: remaining ruff pie790 violations

### PR DESCRIPTION
**Pull request by paverett**
### Description

This pull request is to address violations to Ruff's rule PIE790, which is listed explicitly in issue https://github.com/astropy/astropy/issues/14818. The rest of the modules are addressed in this PR.

Solves part of https://github.com/astropy/astropy/issues/14818.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by mcara — COMMENTED** [review]
My personal opinion is that this is one of the (quite numerous) least useful ruff rules: I do not find those `pass` statements distracting. On opposite, it actually helps me when reading the code. Removing them will not make code run faster or be more readable or more beautiful. Just because language makes something optional does not mean we should remove it.

However, if everyone else finds that non-obligatory `pass` is an eyesore, then I will be happy to approve this PR. For now I will abstain.

**Comment by neutrinoceros** [comment]
I'm neutral about this specific rule, but I note that it was previously excluded via `.ruff.toml`, which we document as "temporary exclusions", and this is a first-time contribution, so I'm worried that rejecting this PR would send off the wrong message.

**Comment by eerovaher** [comment]
Code without needless `pass` statements is more readable because it is shorter. I am in favor of merging this pull request as it is.

**Review by pllim — APPROVED** [review]
There were already other PRs related to this but for specific sub-packages. Might as well. Thanks!

**Comment by mcara** [comment]
> Code without needless `pass` statements is more readable because it is shorter. I am in favor of merging this pull request as it is.

To me it is like reeding sentences without punctuation.

**Comment by eerovaher** [comment]
The whole purpose of `pass` is to allow writing an indented code block where no code should be executed, but if an indented block is already present then `pass` really doesn't contribute anything.

**Pull request merged**
