### PR TITLE
Get rid of `modeling.fitting` warnings and `WCS` `FITSFixedWarning` in RTD

### PR DESCRIPTION
**Pull request by dhomeier**
### Description
Additional cleanup of RTD build to fix the (non-critical) warnings in the modelling section.
Fixes part of #12784 :
1. `RunTimeWarning: Values in x were outside bounds during a minimize step` – silenced by filter as in `fitting.rst`.
I have played around a bit trying to find better bounds or starting values, but without success.
2. `WARNING: The fit may be unsuccessful; check fit_info['message'] for more information` due to the fitter taking 101 iterations to converge; fixed by increasing `maxiter`.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Current main: https://readthedocs.org/api/v2/build/15881757.txt

This PR: https://readthedocs.org/api/v2/build/15884388.txt

It does seem to get rid of a couple of warnings in the log but not as many as I had hoped. Better than nothing though. Thanks!

**Comment by dhomeier** [comment]
Yes; I had not looked into the `UnitsWarning`s here at all, but they are probably due to #12790, which does not affect 5.0.1.

**Comment by pllim** [comment]
Nice. Thanks!

**Comment by dhomeier** [comment]
No warnings in https://readthedocs.org/projects/astropy/builds/15892240/ – thanks for reviewing!

**Comment by pllim** [comment]
My eyes thank you very much! 🙇‍♀️

**Pull request merged**
