### PR TITLE
Handle sorting NaNs and masked values in jsviewer [rebased]

### LINKED ISSUE #2966: Make data types explicit in jsviewer writer
In the jsviewer `Table` writer, at the moment the columns are treated as strings if there is for example a `nan` value or `--` (from a masked column) so we should force the data types on each column, as done in this example:

https://gist.github.com/astrofrog/88be84f3de2575ff0dcc

### PR DESCRIPTION
**Pull request by saimn**
This is a rebased version of #4052, which a few enhancements:
- Use the new dataTable API and remove duplicate/useless options, as proposed in https://github.com/astropy/astropy/pull/4052#r60187025
- Handle sorting NaNs also in `show_in_notebook`
cc @astrofrog , and maybe @taldcroft @eteq ?

EDIT: Close #4052, fix #2966

### CODE REVIEW

**Comment by saimn** [comment]
Also, testing this is mostly manual as it is not possible to test JavaScript code from Python, but I feel like it could be useful to put a test notebook in the git repository. Otherwise each time I have to do a new one. Thoughts ?

**Comment by bsipocz** [comment]
@saimn - This one somehow missed 1.3. Would you mind rebasing again? Do you think it's ready to go or will need one more final review?

**Comment by saimn** [comment]
@bsipocz - Oh yes, I forgot about this one ! I will rebase, should it go to 1.3.1 ? I guess so as it is labelled as bug.

**Comment by bsipocz** [comment]
@saimn - Yes, please.

**Comment by bsipocz** [comment]
Merging as this got the reviews and go ahead in the previous PR.

**Pull request merged**
