### PR TITLE
Manually add an Attributes section for Cutout2D

### PR DESCRIPTION
**Pull request by larrybradley**
This PR also moves the Parameters section to the class docstring.

Addresses #6407.

### CODE REVIEW

**Comment by MSeifert04** [comment]
How does the rendered docstring look like? I had trouble with manual `Attributes` sections when the attribute description was more than one line long. It would be good to know if that's a problem here too.

**Comment by larrybradley** [comment]
@MSeifert04  I don't like the way the docstring is rendered, but it's better than nothing.  Here's a screenshot:

cutout2d_attrib

I could find only 3 (public) instances of a manually-added `Attributes` section in astropy.  Here's one of them (which is formatted even worse with the narrow first column):

http://docs.astropy.org/en/stable/api/astropy.wcs.NoConvergence.html?highlight=noconvergence

I wonder if `astropy-helpers` can be modified to improve the formatting or if this is a `Sphinx` limitation.

**Comment by larrybradley** [comment]
@bsipocz, @astrofrog  The `AppVeyor` tests will not run because this PR is "non-mergeable".  It's non-mergeable because merging is blocked without one approved review.  Is this the new intended review process?  Will the `AppVeyor` test start automatically after an approved review?  As a reviewer, I would prefer to see the results of the CI tests *before* I review.

Also, what does "Merging can be performed automatically with one approved review." mean?  After a reviewer approves, does `AppVeyor` then run, and then if everything passes is the PR is **automatically** merged?

**Comment by astrofrog** [comment]
@eteq - did you mean to require reviews for merging?

**Comment by pllim** [comment]
>  Will the AppVeyor test start automatically after an approved review?

Answer seems to be no. I can restart Appveyor manually but don't have access for CircleCI.

**Comment by pllim** [comment]
Edit: Spoke too soon. I cannot find a link to restart it; i.e., no "Details" link given like the other ones.

**Comment by bsipocz** [comment]
@pllim - circleCI is failing anyway for pytest reasons, this and all other PRs will need a rebase once #6415 is merged.

**Pull request merged**
