### PR TITLE
Don't pass SIP to wcslib -- it can segfault

### PR DESCRIPTION
**Pull request by mdboom**
If a header has a secondary WCS (i.e. has an letter suffix such as `CTYPE1A`, rather than `CTYPE1`) and that header also has SIP keywords, wcslib will crash because it tries to write SIP distortion keywords into an uninitialized struct.

The problem is actually a lot more complicated than this and involves ambiguity around the SIP standard and whether it supports secondary WCSes at all.  That may take some time to resolve on wcslib's end, and in the meantime, I'd prefer to just hedge against it to prevent the segfault (so that this doesn't hold up the next astropy release).

### CODE REVIEW

**Comment by nden** [comment]
@mdboom I think in general the SIP distortion is only one regardless of how many alternate WCSs a header can have. It is specific to the detector, applied to the raw coordinates before any pointing transformations. And as such there can be only one SIP distortion per header which goes with all alternate WCSs.

**Comment by mdboom** [comment]
I discovered this through an HST FITS file that's part of the `sphere` test suite and has SIP coefficients with a secondary WCS specifier.

https://github.com/spacetelescope/sphere/blob/master/spherical_geometry/tests/data/2chipC.fits.gz

It has keys like "A_1_1C" etc.  I can't remember exactly where that file came from, but maybe it's the case that HST files don't do that anymore?

**Comment by nden** [comment]
This is wrong, not sure how the file was created. It may have used an old (unofficial) version of the code. I can recreate those files tonight.

**Comment by mdboom** [comment]
Sure -- I thought that file might be old and out of date.

**Comment by embray** [comment]
:frowning:

**Pull request merged**
