### PR TITLE
Fix failing tests on MIPS and PowerPC

### PR DESCRIPTION
**Pull request by astrofrog**
This fixes a couple of tests that were failing in Debian on MIPS and PowerPC. Neither were critical, but this will hopefully make packaging of the v3.1 release smoother on Debian.

cc @olebole (just FYI)

For the record, the failures were:

```python
=================================== FAILURES ===================================
_____________________________ test_ignore_warnings _____________________________

    def test_ignore_warnings():
        t = table.Table([[np.nan, np.nan]])
        with warnings.catch_warnings(record=True) as warns:
            t.info('stats', out=None)
>           assert len(warns) == 0
E           assert 1 == 0
E            +  where 1 = len([<warnings.WarningMessage object at 0x6fca67d0>])

/usr/local/lib/python3.6/site-packages/astropy-3.2.dev1-py3.6-linux-mips64.egg/astropy/table/tests/test_info.py:239: AssertionError
___________________________________ test_str ___________________________________

    def test_str():
        t = Time(['2000:001', '2000:002'])
        t[1] = np.ma.masked
        assert str(t) == "['2000:001:00:00:00.000' --]"
        assert repr(t) == "<Time object: scale='utc' format='yday' value=['2000:001:00:00:00.000' --]>"
    
        if NUMPY_LT_1_14:
            expected = ["masked_array(data = ['2000-01-01 00:00:00.000' --],",
                        "             mask = [False  True],",
                        "       fill_value = N/A)"]
        else:
            expected = ["masked_array(data=['2000-01-01 00:00:00.000', --],",
                        '             mask=[False,  True],',
                        "       fill_value='N/A',",
                        "            dtype='<U23')"]
>       assert repr(t.iso).splitlines() == expected
E       assert ["masked_arra...type='>U23')"] == ["masked_array...type='<U23')"]
E         At index 3 diff: "            dtype='>U23')" != "            dtype='<U23')"
E         Use -v to get the full diff

/usr/local/lib/python3.6/site-packages/astropy-3.2.dev1-py3.6-linux-mips64.egg/astropy/time/tests/test_mask.py:85: AssertionError
```

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @astrofrog!

**Comment by bsipocz** [comment]
Any of these needs backporting to LTS?

**Comment by pllim** [comment]
I suspect any LTS release already have workaround for these, hence backporting is unnecessary but maybe @olebole can comment.

**Comment by olebole** [comment]
For (upstream) backports, this is not needed; I can pragmatically add the patch to the Debian package of astropy 2.0.9, or just keep these tests disabled.

**Comment by olebole** [comment]
Oh, and thank you @astrofrog for dealing with this!

**Pull request merged**
