### PR TITLE
WIP: Add linwarp warping wrapper to warp all the things

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by embray** [comment]
Is this PR still relevant now with #3905 and whatnot?

**Comment by mdboom** [comment]
It is, but it needs to be revised and updated.  It's sort of low priority -- just adds a wrapper around a new feature in wcslib.  (Of course, it's not going to work well in all cases, because some of the distortions are still handled on the astropy side and this will be ignorant of that).

**Comment by embray** [comment]
Okay, I thought that might be the case, but I wasn't sure of the linwarp wrapper was rolled into any of the other PRs or not (it's hard to skip through these WCSLIB update PRs :)

**Comment by bsipocz** [comment]
Closing this as it hasn't been updated in 2 years and was said to be low priority anyway. Please feel free to reopen/open another PR if you wish to finish it up.

**Pull request closed without merging**
