### PR TITLE
test: move Parameter test mixin classes

### PR DESCRIPTION
**Pull request by nstarman**
While addressing comments in #16847 I needed to move some tests around to test abstract attributes. I'll push a few small PRs that clean up the tests before I return to #16847.

This PR:
1. moves mixin classes from `test_base` to `test_parameters`.
2. Adds some type annotations to the `test_parameters` tests. Purely informative.
3. Changes 1 module docstring.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by neutrinoceros — APPROVED** [review]
I did the same thing (move the tests to a new file) and checked the diff with your commit to verify if anything else was accidentally changed and the only diff I found was that you added type annotations, so, LGTM !

**Comment by pllim** [comment]
Looks like you also specifically requested Eero to review, so I'll wait.

**Comment by nstarman** [comment]
@eerovaher's looked at Cosmology PRs recently, so is familiar with the state of things. But this PR is more infrastructural than anything.

**Review by eerovaher — COMMENTED** [review]
There's a few checks that use `assert u.allclose()`, but it would be better to use [`assert_quantity_allclose()`](https://docs.astropy.org/en/latest/api/astropy.tests.helper.assert_quantity_allclose.html). You could argue that the amount of code being moved is large enough that any additional changes are a needless distraction, but you are also adding type annotations so you are not limiting yourself to minimal changes anyways. I would therefore prefer to make the change now to prevent code churn in the future.

**Review by eerovaher — APPROVED** [review]

**Pull request merged**
