### PR TITLE
ImageNormalize needs to call autoscale_None

### PR DESCRIPTION
**Pull request by ayshih**
`__call__()` for the `ImageNormalize` class does not currently include a call to the inherited `autoscale_None()` to be able to handle when `vmin` or `vmax` is set to `None`.  See the analogous call in matplotlib's `Normalize` class: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colors.py#L913

This omission was not immediately apparent because matplotlib calls `autoscale_None()` behind the scenes when plotting in many – but not all! – cases.

### CODE REVIEW

**Comment by embray** [comment]
Seems fine to me but I'm not totally familiar with the details.  Bug fixes should generally include a regression test that demonstrates the issue.

**Comment by ayshih** [comment]
@embray I've added a test

**Comment by embray** [comment]
Looks good to me! Can you please add a changelog entry for v1.0.5 bug fixes (it looks like there isn't already a section for `astropy.visualization` so you'll need to add one under the section for `astropy.utils`).  Thanks!

**Comment by embray** [comment]
I added the changelog entry and merged. Thanks @ayshih !

**Comment by ayshih** [comment]
@embray I've been out of town for the last two weeks, so thanks for taking care of this

**Pull request merged**
