### PR TITLE
Fixed a WCSAxes bug when overlaying a frame with default units that are not degrees

### PR DESCRIPTION
**Pull request by ayshih**
### Description

This pull request fixes a bug in WCSAxes ticks/labels when overlaying a coordinate frame where a default unit is not degrees (hour angle, arcminutes, etc.).  The WCSAxes internal transformations work in degrees, but `coord_meta` was being loaded as if the internal transformations worked in the default unit.  The result was that the tick labels claim to be in the default units but have values in degree units.

The figure test in this PR overlays ICRS (top and right) on top of ICRS (bottom and left).  Before the fix in this PR:
before

After the fix in this PR:
after

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
One test is failing, but it's not immediately obvious to me if it is legit.

**Comment by ayshih** [comment]
I've fixed that test.

Incidentally, I just dived into the Git history to confirm that I wasn't missing some context for why the code was written that way, and it turns out the context was me!  I introduced the bug myself in #14326 (astropy 5.3).

**Review by astrofrog — APPROVED** [review]
This looks good to me but I'd like @Cadair to have a look too

**Comment by neutrinoceros** [comment]
Just in case: the allowed failures seen here are known and already fixed on main.

**Review by Cadair — APPROVED** [review]

**Comment by pllim** [comment]
Are you interested in submitting a manual backport PR? If not, we have to change the milestone. Please let me know. Thanks!

**Pull request merged**
