### PR TITLE
Fix find_api_page on py 3.x

### LINKED ISSUE #4378: find_api_page fails in py3.x
The `astropy.utils.misc.find_api_page` function's test (`astropy.utils.tests.test_misc.test_api_lookup`) seems to be failing in py 3.x. I suspect this has been long-missed because it's a ``remote-data`` test and only fails in py3.x.

The problem seems to be that ``http.client.HTTPResponse`` (what `urlopen` returns in py3.x) doesn't behave well with `readline`.  If you do a `readline` followed by `read`, you get a `IncompleteRead` error.  Not sure if this is a feature or a bug, but it's pretty straightforward to patch it, so I'll do that shortly.

### PR DESCRIPTION
**Pull request by eteq**
This closes #4378 by re-implementing the innards of `find_api_page` so that it doesn't use `HTTPResponse.readline`, which seems to be incompatible with `read`.

This should be backported to both v1.1.x and 1.0.x

### CODE REVIEW

**Comment by eteq** [comment]
might @astrofrog or @embray be able to do a quick review of this?  I often find myself doing silly things with py 2.x/3.x str/byte related issues, so an extra pair of eye would be helpful (Note that the tests are *not* helpful here b/c it's a remote data-using function)

**Comment by eteq** [comment]
(and if it looks good, any objections to including in v1.1 ?)

**Comment by eteq** [comment]
Will plan on this for 1.0.8 and 1.1.1 (it's not a critical fix so better not to push it into the second RC)

**Comment by eteq** [comment]
@pllim - seeing as how you saw the problem in #4378, can you double-check me here and make sure this fixes it?  If so, I think this is good to merge.

**Comment by pllim** [comment]
Yes, all tests pass now in Python 3.5.1. But since a release is being prepared, I'll let you or @embray do the merge, even though I can see the merge button.

```
6927 passed, 359 skipped, 42 xfailed, 2 xpassed in 395.34 seconds
```

**Pull request merged**
