### PR TITLE
Experimental CCDData file streaming

### PR DESCRIPTION
**Pull request by juliotux**
This pull request implements an experimental feature to make possible stream data from disk in CCDData classes.

Why?
----
CCDData class in the basis of Astropy's `ccdproc` package. However, if you have to process hundreds of images, it's very easy to overflow the computer's memory.

With this changes, it's possible to store the data in a file, which is mutable and allow to change any part of the data without problem.

I had to implement this for a pipeline I'm developing and I think it's a good addition for the community.

How?
----
This commit simply make possible to use the `numpy.memmap` feature to stream only the `CCDData.data` value from a `numpy` array stored in the disk. Accessing and setting values work exactly as in any `numpy.ndarray`. Built-in Numpy functions (like `max`, `min`, etc.) also work in the same way.

This class also handle temporary files creation/deletion.

Performance
-----------
I noted just a small degradation of the performance using this streaming, of ~2% in reading operations. In writing operations, it's very depending on how much data is being written, but not too big performance issues are noted. Enabling the streaming (where all the data is copied to disk) requires some time (~2s for a 40000x4000 float64 array in my sshd disk) if the file is big.

How to use it?
--------------
It's possible to enable the streaming in the `CCDData` instance creation using `stream` and `cache_folder` arguments:
```
>>> c = CCDData(np.random.random((10000, 10000)), unit='adu', stream=True)
```
or
```
>>> c = CCDData(np.random.random((10000, 10000)), unit='adu', stream=True, cache_folder='/home/user/large_cache')
```

It's also possible to enable the streaming in a already created `CCDData`:
```
>>> ccddata.enable_stream(filename='mytest.npy', cache_folder='/home/user/another_cache')
>>> ccddata.disable_stream()
```
Deleting the class or exiting the python automatically delete the streaming files.

Final Considerations:
-----------------
Suggestions on how improve it are very welcome!

I also thought in create a different class, like `StreamedCCDData` to implement this, but, for integration reasons, just upgrade `CCDData` class may be a better way.

### CODE REVIEW

**Comment by pllim** [comment]
A thought: I wonder if there is value to rename `stream` to `memmap` to be consistent with http://docs.astropy.org/en/stable/io/fits/api/files.html#astropy.io.fits.open

**Comment by juliotux** [comment]
Thanks for the comment @pllim . The idea here is a bit different of `fits.HDUList` `memmap`, since this store the working data in disk, not just reading, but the use of `memmap` instead of `stream` is better. I'll do the renaming. Since there is no communication between `CCDData.__init__` and `fits.open`, no API confusion or breaking is expected.

**Comment by MSeifert04** [comment]
Uff, this is a tough one: First implementing `__del__` is tricky, there are some pitfalls that must be avoided (for example Python is not able to clean up cyclic references when `__del__` is involved) to avoid memory-leaks. The more usual approach would be to use context managers. Also there's no guarantee that `__del__` is invoked. See also [the data model documentation](https://docs.python.org/3/reference/datamodel.html#object.__del__).

However I also feel that implementing memmap in/behind CCDData would be the wrong way around. 

Wouldn't it make more sense to just pass in the memmap to the `CCDData.__init__` (btw that's already possible), for example:

```python
# I'm choosing a FITS file but with something similar should already be possible for any memmap.
with fits.open('filexyz.fits', mmap=True) as hdul:
   ccd = CCDData(hdul[0].data)  # <- the data should be a memmap
   ...
```

That makes the cleanup and scope more explicit and much easier to reason about. And it should already work. The example was for a FITS file but something like this should also be possible for a memmap and it should already work.

**Comment by MSeifert04** [comment]
Just in case we actually want to use this approach, then we have to think about the other attributes as well. For example `uncertainty` is likely to be as big as the `data`. `mask` is not as memory-expensive because it's typically `bool` (so typically 2-8 times smaller), however if we had `flags` then that would be as big as the `data` as well. For `wcs` and `header` the streaming would be more complicated (but also less useful because typically they are **much** smaller) because they need coordination because they store linked values.

Indeed this might also be an argument against the implementation inside `CCDData` because a context-manager approach could be tailored to "stream" those values that actually need it (from a user-perspective).

**Comment by juliotux** [comment]
Hello @MSeifert04 . Regarding all problems you addressed:
1 - `__del__` and memory leaking: in the case `__del__` is not called, the main problem of the implementation is to keep the files in cache folder. This is certainly a problem, but a problem faced by any program that creates temporary cache files. If the object deletion not goes well, the files are kept. I don't see how any major memory leaks, at least one that can't be handled by garbage collector, could happen.

2 - `fits.open` context: for reading the data, this idea works fine and creating the `CCDData` with the `hdul[0].data` reference really pass the memmap. However, any change in the data, like `ccd.data += 4` (like the way `ccdproc` perform operations) reads all the data to memory, destroying the memmap.  Of course for working with the FITS memmap, this is the safer way, as the idea is to not modify the source file. But, this implementation have the objective to create a mutable, cache stored, data object on what `ccd.data += 4` do not need to read and keep the entry array in memory.

1 and 2 - A context solution could be:
```
with CCDData(data, unit='adu', memmap=True) as ccd:
    subtract_bias(ccd, bias)
    divide_flat(ccd, flat)
    ccd.writeto('test.fits')
```
But this may not work well if you want to keep 600 processed images objects in a list to perform photometry or combine them in some step after (and without manual cache/save the processed images). I'll think better about this and try to find a better design solution.

3 - I looked to `uncertainty` and `mask` implementations. `mask` is easy to fix, as it's just an array stored and can follow the same logic of `data`. However, `uncertainty` can be more complicated, since custom `NDUncertainty` classes are (apparently) needed. To expand the cache to `uncertainty` I think a refactor of these classes are needed. A possible solution is a class or function decorator that controls the assignment of an array, ensuring caching when needed, like what I did inside `@data.setter`. Regarding `header` and `wcs`, I don't see a practical reason to cache them, as you said, they are **much** smaller.

**Comment by pllim** [comment]
@stscieisenhamer , you got any lessons learned to share from overloading `__del__` in your work?

> 600 processed images objects

Another way around this limit is to process them in smaller batches, saving out intermediate results, and then process those. Had to do it like that for HST CR rejection for a few cases. Not sure if this would work for your use case, but FYI anyway.

**Comment by juliotux** [comment]
I'm working on an alternative way to do this, without re-implement everything. I'm testing a class modifier, that implement the changes to make select class properties cacheble, and a bunch of functions to cache individual properties.

One example of the decorator can be found in [this file](https://github.com/juliotux/astropop/blob/8be9334cd7d33c5571409c6ea0f5415a523a892b/astropop/_ccddata_decorator.py), but some bugs exist now, not really working well. The way this will work is:
```
CCDData = memmapped_arrays(AsCCDData, ['data', 'mask'], fixed_dtype={'mask': bool})
```
But this do not solve the uncertainty problem.

The functions I'm working today will run like:
```
ccd = CCDData(data, mask=mask, unity='adu')
ccddata_enable_data_memmap(ccd)  # Enabling caching only for data
ccddata_enable_mask_memmap(ccd)  # Enabling caching only for mask
ccddata_enable_uncertainty_memmap(ccd)  # Enabling cache only for uncertainty
# Analog things for disabling
```

Both solutions may solve the `__del__` problem addressed before, since they will work directly in the properties. `property` object has `getter`, `setter` and `deleter` functions, so we won't need to overload the class `__del__`, the functions will just set new `setter` and `deleter` functions to the properties.

The last solution also make possible to better handle the uncertainty caching.

What do you think people? Is it a better solution, in the context of Astropy? Or is this big mess I'm doing just out of the scope (I realized I didn't ask this before, sorry)?

**Comment by pllim** [comment]
> What do you think people?

Very interesting! At the very least, it can be over at https://github.com/astropy/astropy-tutorials or somewhere in the core doc (maybe performance section?), even if the implementation itself cannot fit with existing core code.

However, let's wait to see what @mwcraig and @MSeifert04 have to say.

**Comment by saimn** [comment]
Just to clarify a point about `io.fits`'s memmap: it already works with `CCDData.read`, and is used by default. Just to read files, which is different from the aim of this PR.

And as kwargs are passed to `fits.open` it is not a good idea to name the option `memmap`, this prevents using this option to control `fits.open`'s behavior. So I suggest another option name, more explicit about the behavior, maybe something like `use_memmap_backend` ?

I think that the aim of this PR makes sense, `CCDData` can be used to process many images, which can be limited by memory usage, so using a memmap cache for all data operations can be a good solution, with some performance penalty of course.

About the implementation, one possibility could be to use a descriptor for `._data` and `._uncertainty`, to reuse the same behavior for both. I don't know well enough `CCDData` and the `NDData` classes, but that could work well to keep the memmap backend implementation well separated from the current code. I made something similar for mpdaf (https://git-cral.univ-lyon1.fr/MUSE/mpdaf/blob/master/lib/mpdaf/obj/data.py#L52 - though slightly different, the goal here was to delay the data loading with an existing implementation, and making sure that the mask could be computed when loading data or uncertainty). With a similar implementation, checking a `_use_memmap_backend` on the object, you could implement the optional reading or writing of data from the memmap. Cleaning the cache would be done with the descriptor's `__delete__` method.

**Comment by juliotux** [comment]
Hello @saimn , thanks for the comments and commit.

> And as kwargs are passed to `fits.open` it is not a good idea to name the option `memmap`, this prevents using this option to control `fits.open`'s behavior. So I suggest another option name, more explicit about the behavior, maybe something like `use_memmap_backend` ?

I checked possible conflicts. Our `memmap` argument is in `CCDData.__init__` function. This function do not recive any `kwd` argument from `CCDData.read`. So, setting `memmap` in `CCDData.read` will pass this argument directly to `fits.open`, not to `CCDData`. This may become a problem if we modify the `read` method to accept the data caching.

> About the implementation, one possibility could be to use a descriptor for `._data` and `._uncertainty`, to reuse the same behavior for both...
The setting behavior for both is different. `uncertainty` have some additional checks and is stored in a different class type. To really cache the array data of `uncertainty`, we need to modify the uncertainty classes to allow caching for `array` property on them (and pass the needed info).

> ...Cleaning the cache would be done with the descriptor's `__delete__` method.
I'm studying better the possibilities, but setting the `property.deleter` function method seems to be the safer now.

**Comment by saimn** [comment]
@juliotux - Right, sorry about the confusion between `__init__` and `read`. But still I think it's a good idea to have a different argument name ;).

> The setting behavior for both is different. uncertainty have some additional checks and is stored in a different class type.

Ah yes indeed, you could maybe use the descriptor on the `NDUncertainty._array` attribute?

> setting the property.deleter function method seems to be the safer now.

A descriptor is just a custom reusable property, so that's basically the same idea.

**Comment by juliotux** [comment]
> Ah yes indeed, you could maybe use the descriptor on the `NDUncertainty._array` attribute?
Yes, this is the idea. But it is very depending on the design choice. A function could set the correct `NDUncertainty._array` getter/setter, but the `CCDData` reimplementation sould need a reimplementation of `NDUncertainty` too.

**Comment by juliotux** [comment]
Hello everyone,

I made some tests with properties and descriptors and found that, the only way to delete caching files is explicit setting the cached properties to deletion in `__del__` function. `__delete__` instances and `property.deleter` only work for individual data deletion, like `del ccddata.data`.

I improved the code design (I think the current state of class reimplementation is better), incorporating the sugestion of `use_memmap_backend` from @saimn .

I also made a new testing implementation of enabling/disabling caching with functions in [juliotux/astropop](https://github.com/juliotux/astropop/blob/b18f0c329d32bb34ff2a70a1931a4a7702d2a477/astropop/_ccddata_decorator.py#L66). these functions have the only problem that they don't change `__del__` function of `CCDData`, so they need manual disabling for cleaning up.

**Pull request closed without merging**
