### PR TITLE
Ignore `black` formatting commits in blame

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

This PR adds all the `black` related commits to the `.git-blame-ignore-revs` so those changes don't clutter the blame up.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by pllim — COMMENTED** [review]
I'll just have to trust you on this one and let @astrofrog approve. Thanks!

**Comment by astrofrog** [comment]
Thanks for this! It doesn't seem to be working perfectly at the moment - if I look at a random file in astropy.coordinates in your fork in blame view (on this branch) I see:

Screenshot 2022-11-15 at 22 06 51

Example page:

https://github.com/WilliamJamieson/astropy/blame/black/blame_ignore/astropy/coordinates/baseframe.py

**Comment by WilliamJamieson** [comment]
Interesting, though I am not sure what else I can do. @taldcroft do you have any suggestions?

**Comment by astrofrog** [comment]
Oh wait, maybe those are lines that simply didn't exist before?

**Comment by WilliamJamieson** [comment]
That might be the case.

**Review by astrofrog — APPROVED** [review]
I think that's indeed what is going on - will go ahead and merge!

**Pull request merged**
