### PR TITLE
update wcslib to v 5.16

### PR DESCRIPTION
**Pull request by nden**

### CODE REVIEW

**Comment by bsipocz** [comment]
@nden - I guess this is ready to go once CI gives a green light?

**Comment by nden** [comment]
@bsipocz Yes, just need to add a Change log entry.

**Comment by nden** [comment]
@bsipocz Did my last commit kill the Travis tests?

**Comment by bsipocz** [comment]
@nden - Yes, as we use auto cancel, and your original commit was still in the queue. As the last one had `[skip ci]`, it then didn't started up CI again. I see that you or someone else manually restarted the original one since.

**Pull request merged**
