### PR TITLE
Add performance stubs

### PR DESCRIPTION
**Pull request by eteq**
This does the first step of #5753 : adds sections in most of the subpackages for "performance tips".

Note that I decided to *default* to the "include" way.  But all of the stub sections have explicit instructions on how to switch to the "separate page" way.  The idea is that sub-package authors can easily "upgrade" to the separate page approach if the section gets long enough to justify it.

Note also that I did not include a section in `config`, `util`, or any of the "1-module" parts of `io`.  All of those seem like they don't really have enough (or at least the sub-package isn't specific enough) to justify a dedicated section.

cc @astrofrog

### CODE REVIEW

**Comment by eteq** [comment]
Last commit made the changes @astrofrog suggested.

@bsipocz 

> The content of performance.inc files is not picked up by doctest, so this is a no go as is.

Are you sure?  I thought code that gets ``.. include::``ed still gets read by doctest?  (I can check test it if you're not sure, just wanted to check if this is something you've actually checked vs think probably)

> Any reason not to call them rst from the beginning?

Yes - if you do that they get read as .rst files, which is not desirable because if you do that *and* include them, you end up with the same file getting parsed by sphinx twice (and double-errors/warnings for everything). Also, sphinx complains about them not being in any toctree, and if you put ``:orphan:`` on the top I think that confuses the file they are included in (although I admit I didn't check that...).

I would be better if there was a way to do "include" that uses the previously-parsed doctrees instead of actually dropping the text in wholesale.  Then we could do what you suggested.  Could imagine making a plugin for that, but it feels like overkill.

**Comment by mhvk** [comment]
Maybe `*.inc.rst` - that way github also does its "colouring" better.

**Comment by bsipocz** [comment]
> Are you sure? I thought code that gets .. include::ed still gets read by doctest? (I can check test it if you're not sure, just wanted to check if this is something you've actually checked vs think probably)

I wasn't but the checked it locally with adding a dummy `assert 1==0`...

**Comment by eteq** [comment]
OK, I think the changes I just made address @mhvk and @bsipocz concerns - I switched to ``.inc.rst`` as @mhvk suggested but the extra bit was to add those ti the ``exclude_path`` so that sphinx doesn't try to process them directly.  We will see for sure when the tests finish, but it seemed to do the job locally (and still run the doctests as @bsipocz wanted)

**Pull request merged**
