### PR TITLE
Fix memory-leak in NDData with uncertainty.

### PR DESCRIPTION
**Pull request by MSeifert04**
Fixes only parts of the issue: #4825 

also included a small fix that prevents that uncertainties are stolen if assigned as an uncertainty for another NDData object. The initial commit only contains the test cases (the failed fork-build with these tests can be inspected [here](https://travis-ci.org/MSeifert04/astropy/builds/129279059). The second provides the fixes. Unfortunatly these are entangled to some extend since the fix of the one requires the other one.

### CODE REVIEW

**Comment by mwcraig** [comment]
Looks good, could you please add a changelog entry for it?

**Comment by MSeifert04** [comment]
@mwcraig Will commit it but I'll wait until #4868 is merged and tested if there are any overlaps with newly merged #4851. Don't want to be the cause of package-wide test failures again :disappointed:

**Comment by mwcraig** [comment]
@MSeifert04 -- no worries, everyone has a first time when has it happen (don't remember any details of my first, but remember that it happened). All the tests had passed, and the CI system did its job of catching the problem . Plus you fixed it in record time 😀

**Comment by MSeifert04** [comment]
@mwcraig I've included the changelog entry and locally the tests pass before and after merging this PR. So I think this is good to go. Except you have suggestions to improved the changelog entry. Does a memory leak "happen"? :smile:

**Comment by mwcraig** [comment]
Could you also add the issue number #4825? Memory leaks happen to me all the time ;0

**Pull request merged**
