### PR TITLE
Opening FITS files stored in HDFS

### PR DESCRIPTION
**Pull request by luizbg**
With these changes, it is now possible to use the .open() function to open FITS files stored in HDFS (Hadoop Distributed File System). 
When opening files in HDFS, it is necessary to specify the 'hadoop' kwarg as True. Also, the file path needs to be the path in HDFS. (Example of use: .open('HDFS_file_path', hadoop=True)).
The purpose of this change is to facilitate the use of files stored in HDFS through the functions of Astropy, even if, for the time being, it is only possible to open them.

### CODE REVIEW

**Comment by astrofrog** [comment]
@luizbg - thanks for the pull request! My personal feeling is that while this is indeed useful for people using Hadoop, it is too technology platform-specific to belong in the core astropy package, and I don't think enough astronomers use hadoop to justify this being in the core package. In addition it would also be hard to test in the CI. However, if you think this would be useful for others, I would suggest making a small separate package that people could install to facilitate this.

**Comment by drdavella** [comment]
@luizbg thanks for the effort! I agree with @astrofrog that while this is clever, your goals would be better served by a separate wrapper layer around `astropy.io.fits`. I don't think this functionality belongs in astropy itself.

**Comment by luizbg** [comment]
@drdavella @astrofrog - I appreciate your feedback!
Thanks for clarifying your point of view, I agree with it; indeed, it makes more sense for this to be in a wrapper instead of the core package itself. 
Thanks again for the tips!

**Comment by pllim** [comment]
Thanks anyway!

**Pull request closed without merging**
