### PR TITLE
TST: Fix import error from numpy.testing.utils

### LINKED ISSUE #7340: Numpy dev failure: Import from numpy.testing, not numpy.testing.utils
Imports from `numpy.testing.utils` are failing:
https://travis-ci.org/astropy/astropy/jobs/360190874
Due to https://github.com/numpy/numpy/pull/10812

### PR DESCRIPTION
**Pull request by pllim**
Fix #7340 

Note: Check the numpy dev build carefully before merge. Travis CI still shows green even if that build fails.

@bsipocz , does this need to go into 2.x series, or just 3.x? I am unclear on Numpy support policy in Astropy LTS. I'll let you set the milestone. Thanks!

### CODE REVIEW

**Comment by saimn** [comment]
LGTM, and the dev build is green. Thanks for the quick fix @pllim !
Also it should be compatible with older Numpy versions, all supported versions I guess, maybe @mhvk knows better about this ?

**Comment by pllim** [comment]
I was just thinking that if 2.x won't support what this numpy dev release is going to be, there is no need of extra backporting pain. With all the PY2 stuff removed in 3.x, I am not sure how much work is to backport this to 2.x. That's all.

**Comment by mhvk** [comment]
Fix looks good. It is a bit strange that we had all those imports from `numpy.testing.utils` - I think they have been in `numpy.testing` forever. If that's true (am not sure...), then a backport should be possible, and would be good for being able to use LTS with newer numpy (since numpy continues to support python 2 for a bit, this is not too strange a combination).

**Comment by bsipocz** [comment]
> @bsipocz , does this need to go into 2.x series, or just 3.x? I am unclear on Numpy support policy in Astropy LTS. I'll let you set the milestone. Thanks!

the policy as far as I know is to do our best to support new numpy on old branches. So unless it makes a patch extremely complicated (e.g. it's incompatible with the old numpies we still support) we try to backport all numpy-dev related fixes.

**Comment by bsipocz** [comment]
Thanks @pllim!

**Pull request merged**
