### PR TITLE
WIP: Add a simple lookup table model

### PR DESCRIPTION
**Pull request by Cadair**
This model is to support things like:

```python
>>> abs_lookup = ['2011-01-01T00:10:00', '2011-01-01T00:20:00']
>>> t2 = LookupTable(lookup_table=abs_lookup)
>>> print(t2(0.5))
'2011-01-01T00:20:00'
```

I will write tests and docs if the concept of this is approved.

@nden

### CODE REVIEW

**Comment by pllim** [comment]
What about 2D lookup? Does it work?

**Comment by Cadair** [comment]
@pllim no, I would have to copy all the `tabular_model` stuff for creating ND models which support the correct number of inputs.

**Comment by Cadair** [comment]
That's not to say that's not a bad idea!

**Comment by nden** [comment]
@Cadair How does this fit into modeling? Do you need this kind of rounded indexing with numerical lookup tables? If so we can perhaps add a flag to the existing models.
But if it's just for string parameters, and this model can't be combined with other models or fitted, then perhaps it doesn't belong in modeling?
I may be miunderstanding the use case though.

**Comment by nden** [comment]
@Cadair should this be closed and possibly some version of this moved to gwcs?

**Pull request closed without merging**
