### PR TITLE
Updated RTD configuration for older-docs-archive branch

### PR DESCRIPTION
**Pull request by astrofrog**
This is a WIP to try and fix the older-docs-archive branch on RTD, which hosts all the legacy docs.

### CODE REVIEW

**Comment by astrofrog** [comment]
This is an interesting case where the milestone shouldn't actually be set so we can ignore astropy-bot's warning

**Comment by pllim** [comment]
Oh, *now* the bot shows itself.

**Comment by astrofrog** [comment]
Wohoo, it works!

**Comment by astrofrog** [comment]
I'm just merging this myself since this isn't to master and is just a small fix

**Pull request merged**
