### PR TITLE
Windows msvc14 has no useful find_msvcrt() method anymore.

### PR DESCRIPTION
**Pull request by MSeifert04**
Also contained: Trying to pass appveyor python3.5

I hope this doesn't break anything and fixes something (on my computer at least it fixed 15 test failures for windows10 with python 3.5)

### CODE REVIEW

**Comment by MSeifert04** [comment]
This should fix: #4342

**Comment by MSeifert04** [comment]
Does anyone know why this Error happenes in AppVeyor python 3.5:

```
Build started
git clone -q https://github.com/astropy/astropy.git C:\projects\astropy
git fetch -q origin +refs/pull/4792/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
git clone git://github.com/astropy/ci-helpers.git
Cloning into 'ci-helpers'...
powershell ci-helpers/appveyor/install-miniconda.ps1
Installing miniconda latest for -x64 bit architecture to C:\conda 
Downloading Miniconda-latest-Windows-x86_64.exe from http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86_64.exe 
File saved at C:\projects\astropy\Miniconda-latest-Windows-x86_64.exe 
Installing C:\projects\astropy\Miniconda-latest-Windows-x86_64.exe to C:\conda 
C:\projects\astropy\Miniconda-latest-Windows-x86_64.exe /InstallationType=AllUsers /S /AddToPath=1 /RegisterPython=1 /D=C:\conda 
Start-Process : This command cannot be run due to the error: The specified 
executable is not a valid application for this OS platform..
At C:\projects\astropy\ci-helpers\appveyor\install-miniconda.ps1:61 char:5
+     Start-Process -FilePath $filepath -ArgumentList $args -Wait -Passthru
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOp 
   erationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.C 
   ommands.StartProcessCommand
 
Failed to install Python in C:\conda 
Command exited with code 1
```

Exactly the same build runs fine for python 2.7 and python 3.4. Do I need to include something else? I'm actually not very familiar with those test-builds and don't know if that's something I missed or if it's just disabled.

**Comment by pllim** [comment]
This is rebased against the latest master, right? Just want to make sure this is not already fixed somewhere else recently.

**Comment by MSeifert04** [comment]
@pllim I think so. `git diff` only shows this PR as difference between the latest `astropy-master` and this branch. I hope this answers your question, I'm not sure if that was what you wanted to know.

**Comment by pllim** [comment]
I don't know if `git diff` is a sure-fire way to check that. When do you this, do you see things happening on the terminal?
```
git fetch upstream master
git rebase upstream/master
```

**Comment by bsipocz** [comment]
@MSeifert04 - It looks like a transient and restarting (recommitting) usually solves it.

**Comment by bsipocz** [comment]
btw if this fixes all the 3.5 issues, I suggest to remove the allow failures section. And also remove the 3.4 testing from the matrix (as was planned in #4450).

**Comment by eteq** [comment]
After some discussion on gitter the conclusion was that this isn't a bug fix per se but should just serve to suppress some unintended warnings (so doesn't need a changelog entry or backporting)

**Comment by MSeifert04** [comment]
maybe: cc @embray - You mentioned that fixing #4342 would need some refactoring. Could using `ctypes.cdll.msvcrt` lead to difficulties here?

**Comment by embray** [comment]
I don't have strong feelings one way or the other about the changelog entry, but would still classify this as a bug fix and it should have *some* milestone--most appropriately the next 1.1.x patch release.

**Pull request merged**
