### PR TITLE
Fix 4 intertwined coordinates bugs

### LINKED ISSUE #3920: transform_to(AltAz) de-scalarizes if input has a distance
Surprising behavior noted (indirectly) by @bmorris3 :

```
>>> aa = AltAz(location=EarthLocation.from_geodetic(0*u.deg, 0*u.deg, 0),obstime=Time('2015-1-1'))
>>> m=SkyCoord(10*u.deg,3*u.deg)
>>> m.transform_to(aa).shape
()
```
That part makes sense: the input is a scalar so the output is too
```
>>> aa = AltAz(location=EarthLocation.from_geodetic(0*u.deg, 0*u.deg, 0),obstime=Time('2015-1-1'))
>>> m=SkyCoord(10*u.deg,3*u.deg, 1*u.AU)
>>> m.transform_to(aa).shape
(1,)
```
oops!  For some reason it decided to switch to a length-1 array coordinate.  Definitely should still be a scalar.

This is definitely a bug and not at all intended, but changing it is breaking backwards-compatibility.  How do we want to address this?  Deprecation?  Or leave it in for 1.0.x but change it for 1.1.x?  

I'm not sure how used this functionality is right now, so it may not be an issue to slip in the change...

cc @adrn @astrofrog

### LINKED ISSUE #3938: AltAz transformation fails for vector SkyCoord
I'm calling a `coord.transform_to(AltAz(...))` transformation on a vector of coordinates, like this:
```python
from astropy.coordinates import SkyCoord, EarthLocation, AltAz
from astropy.time import Time

# Set up list of targets
vega = SkyCoord.from_name('Vega')
capella = SkyCoord.from_name('Capella')
sirius = SkyCoord.from_name('Sirius')
targets = [vega, capella, sirius]

# Feed list of targets into SkyCoord
combined_coords = SkyCoord(targets)
print(combined_coords)
# Set up AltAz frame
time = Time('2015-01-01 00:00:00')
location = EarthLocation('10d', '45d', 0)
aa = AltAz(location=location, obstime=time)
print(combined_coords.transform_to(aa))
```

and getting the following error:

```
In [12]: run exp
<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, )
    [(279.23473479, 38.78368896, 1.0), (79.17232794, 45.99799147, 1.0),
     (101.28715533, -16.71611586, 1.0)]>
---------------------------------------------------------------------------
UnitConversionError                       Traceback (most recent call last)
/Users/bmorris/git/astroplan/exp.py in <module>()
     22 location = EarthLocation('10d', '45d', 0)
     23 aa = AltAz(location=location, obstime=time)
---> 24 print(combined_coords.transform_to(aa))
     25 
     26 

/Users/bmorris/git/astropy/astropy/coordinates/sky_coordinate.pyc in transform_to(self, frame)
    385         # Do the transformation, returning a coordinate frame of the desired
    386         # final type (not generic).
--> 387         new_coord = trans(self.frame, generic_frame)
    388 
    389         # Finally make the new SkyCoord object from the `new_coord` and

/Users/bmorris/git/astropy/astropy/coordinates/transformations.pyc in __call__(self, fromcoord, toframe)
    918 
    919             curr_toframe = t.tosys(**frattrs)
--> 920             curr_coord = t(curr_coord, curr_toframe)
    921 
    922         # this is safe even in the case where self.transforms is empty, because

/Users/bmorris/git/astropy/astropy/coordinates/transformations.pyc in __call__(self, fromcoord, toframe)
    706 
    707     def __call__(self, fromcoord, toframe):
--> 708         res = self.func(fromcoord, toframe)
    709         if not isinstance(res, self.tosys):
    710             raise TypeError('the transformation function yielded {0} but '

/Users/bmorris/git/astropy/astropy/coordinates/builtin_frames/icrs_cirs_transforms.pyc in icrs_to_cirs(icrs_coo, cirs_frame)
     29         px = 0
     30     else:
---> 31         px = 1 / icrs_coo.distance.to(u.parsec).value
     32     srepr = icrs_coo.represent_as(UnitSphericalRepresentation)
     33     i_ra = srepr.lon.to(u.radian).value

/Users/bmorris/git/astropy/astropy/units/quantity.pyc in to(self, unit, equivalencies)
    619         unit = Unit(unit)
    620         new_val = np.asarray(
--> 621             self.unit.to(unit, self.value, equivalencies=equivalencies))
    622         return self._new_view(new_val, unit)
    623 

/Users/bmorris/git/astropy/astropy/units/core.pyc in to(self, other, value, equivalencies)
    970             If units are inconsistent
    971         """
--> 972         return self._get_converter(other, equivalencies=equivalencies)(value)
    973 
    974     def in_units(self, other, value=1.0, equivalencies=[]):

/Users/bmorris/git/astropy/astropy/units/core.pyc in _get_converter(self, other, equivalencies)
    871         except UnitsError:
    872             return self._apply_equivalencies(
--> 873                 self, other, self._normalize_equivalencies(equivalencies))
    874         return lambda val: scale * _condition_arg(val)
    875 

/Users/bmorris/git/astropy/astropy/units/core.pyc in _apply_equivalencies(self, unit, other, equivalencies)
    862         raise UnitConversionError(
    863             "{0} and {1} are not convertible".format(
--> 864                 unit_str, other_str))
    865 
    866     def _get_converter(self, other, equivalencies=[]):

UnitConversionError: '' (dimensionless) and 'pc' (length) are not convertible
```

As you can see by the `print` statement that does not fail, the `SkyCoord` constructor unpacks the coordinates (which only have RA, Dec) into a vector with distances. What's that about? @eteq @cdeil @adrn

### LINKED ISSUE #3998: get_sun returns vector solution for single time
@eteq : Is this intended behavior? Shouldn't `get_sun` return a scalar sky coordinate for a scalar time?

```python
>>> time = Time.now()
>>> time.isscalar
True
>>> sun = get_sun(time)
>>> sun.isscalar
False
>>> sun[0]
<SkyCoord (GCRS: obstime=2015-07-22 22:39:14.781846, obsgeoloc=[ 0.  0.  0.] m, obsgeovel=[ 0.  0.  0.] m / s):39:14.781846, obsgeoloc=[ 0.  0.  0.] m, obsgeovel=[ 0.  0.  0.] m / s): (ra, dec, distance) in (deg, deg, AU)
    (122.76730836, 20.02852949, 1.01598715)>
```

### LINKED ISSUE #4033: separation fails with recursion error for some coordinates
This is a subtle bug that probably slipped through the tests because it depends on a particular set of inputs.  Specifically, if you ask for the `separation` between two `SkyCoord` objects when *both* have a `distance`, you get a strange error:

```python
>>> alb = SkyCoord.from_name('Albireo')
>>> alb_wdist = SkyCoord(alb, distance=133*u.pc)
>>> de = SkyCoord.from_name('Deneb')
>>> de_wdist = SkyCoord(de, distance=802*u.pc)
>>> aa = AltAz(location=EarthLocation(lat=45*u.deg, lon=0*u.deg), obstime='2010-1-1')
>>> alb_wdistaa = alb_wdist.transform_to(aa)
>>> de_wdistaa = de_wdist.transform_to(aa)
>>> de_wdistaa.separation(alb_wdistaa)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

The particularly curious thing is that this does *not* happen if the one calling has no distance:
```python
>>> deaa = de.transform_to(aa)
>>> albaa = alb.transform_to(aa)
>>> deaa.separation(albaa)
<Angle 22.28621055928645 deg>
>>> deaa.separation(alb_wdistaa)
<Angle [ 22.28621208] deg>
>>> alb_wdistaa.separation(deaa)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```
The second one there is probably related to #3920, so it's quite possible a fix for that will also fix this.

### PR DESCRIPTION
**Pull request by eteq**
This PR addresses a series of quirk/bugs in `astropy.coordinates`, dealing with a mix of specific inputs that result in inconsistent or incorrect outputs.   

Specifically, this closes #3920, closes #3938, closes #3998, and closes #4033.  While the fixes are mostly independent, they do interact enough that a single PR seemed more straightforward (e.g., the fix  for some of the transforms giving vectors when they should give scalars makes writing the regression test for some of the others easier).

The one questionable piece here is about @astrofrog's item from #3920 .  There's a not totally ignorable argument that the change to fix that is backwards-incompatible because the current version (incorrectly) yields an array coordinate when it should be a scalar.  But that's been in since v1.0, so users *may* have written workarounds.  It's still definitely a bug, but the question is whether we want to, say, delay that to v1.1.  @astrofrog asked for a use case that might lead to it:  the simple use case of starting from a scalar `SkyCoord` with a distance and converting to a locat `AltAz` will do that, which is a pretty standard use... So it is possible this is used in the wild.  On the other hand, no one brought it up, and it is *not* what the documentation claims, so maybe that's over-worrying?

cc @embray @bmorris3 @adrn

### CODE REVIEW

**Comment by embray** [comment]
I don't think we should worry about backwards compatibility so much when the previous behavior was a bug (especially if no one has reported the issue).

**Comment by embray** [comment]
I changed the milestone for #3920 to v1.0.4 to reflect this too.

**Comment by embray** [comment]
Looks great--thanks for getting this done in time.  Is there anyone else you'd like to review or should we merge?

**Comment by embray** [comment]
Also were you really working on this at 2 in the morning, or are you in Hawaii right now? :D

**Comment by eteq** [comment]
@embray - In theory it would be nice if someone both reviewed it *and* wrapped their head around it, but that's a pretty tall order because these are all very subtle/complex in actual use.  I think it would be good to hear from @astrofrog about what he thinks re: #3920, but I'm pretty sure from his last comment there that he's ok with it, so if you want to merge to get v1.0.4 out the door that's probably OK.

And yes, it really was 2am.  Given how complex my debugging setup ended up to track these down, I was afraid I'd never reproduce the fixes if I didn't do them all at the same time ;)

**Comment by bmorris3** [comment]
I :clap: your dedication.

**Comment by embray** [comment]
I spent some time yesterday reviewing what was going on in #3938, and so I've partially wrapped my head around this, but I don't fully understand how all the other issues relate.

**Comment by astrofrog** [comment]
:+1:

**Pull request merged**
