### PR TITLE
TST: pin pluggy in image tests to get by future incompatibility with pytest-mpl

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description

This is a quick solution to make image tests work again.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
CircleCI is green again! 👏

**Review by pllim — APPROVED** [review]
This works for now. Can you please take it out of draft so I can merge? Thanks!

**Comment by neutrinoceros** [comment]
there you go !

**Comment by pllim** [comment]
No need to wait for OSX. Seems to be queued a long time.

**Pull request merged**
