### PR TITLE
Updating helpers to v2.0.9

### PR DESCRIPTION
**Pull request by bsipocz**
This now points to the release, so merge away once CI passed (circle py3 32bit is expected to fail, and that's OK).

### CODE REVIEW

**Comment by bsipocz** [comment]
There are some real issues here on the branch, ideally this PR should be rebased at last minute

**Comment by bsipocz** [comment]
@eteq  - `ah_bootstrap.py` is always has to be updated if and when the helpers is updated, it's copied over from there. Also, the CI won't be green on this as circleCI is acting  up and doesn't know how to handle the submodule. Anyway, that's already been OK-ed by @astrofrog and @pllim.

**Comment by eteq** [comment]
@bsipocz - I was just thinking these don't look necessary, but I guess it probably is better to favor keeping it consistent with the helpers version even if it comes at the expense of other "unnecessary" changes, so I'm fine with that.  Just double-checking

**Comment by bsipocz** [comment]
Well, this is what got into that helpers version. I agree that it's a minor update, but it get rid of a few sphinx warnings which easy the mind of a few of us. (I'm not planning to open mass PRs for this helpers version though).

**Comment by bsipocz** [comment]
The docs building job is failing with the link checking, so I go ahead and merge this.

**Pull request merged**
