### PR TITLE
TST: Ignore data server in linkcheck

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address connection timeout for Astropy data server when running linkcheck. I think we'll find out if data server is down even without linkcheck.

Example log with failure: https://travis-ci.org/github/astropy/astropy/jobs/670616894

### CODE REVIEW

**Comment by bsipocz** [comment]
Yes, I suppose it's right that we figure out if the dataserver is down by other means, but what about the case when we link to something in that server that gets removed?

**Comment by pllim** [comment]
Do we link directly to those data in the doc like that? The failure here is caused by this line:

https://github.com/astropy/astropy/blob/e85a7411ff124abab271f7f46e363a842fe18b7e/astropy/tests/runner.py#L466

Would you rather I remove the URL from the docstring instead? Please advise.

**Comment by bsipocz** [comment]
Hmm, you're right, we don't seem to link to any of the individual files. Interestingly the link works well locally, but still fails on travis.

So, while I don't like adding to many exceptions, this one is probably fine and not worth to spend much more time on.

**Comment by pllim** [comment]
We can always revisit if the situation changes too. Thanks for the review and merge, @bsipocz !

**Pull request merged**
