### PR TITLE
DOC: add lomb-scargle to whatsnew

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by jakevdp** [comment]
Sorry for the additional changes. My editor is configured to normalize whitespace on save.

**Comment by astrofrog** [comment]
Thanks @jakevdp!

**Comment by astrofrog** [comment]
@jakevdp - it might be nice to include a very short example + plot. We often try and include visuals in the 'what's new' since this is what people see first for a release. For example:

http://docs.astropy.org/en/stable/whatsnew/1.1.html#algorithms-for-choosing-histogram-bins

Could you add such an example here? (and including a few lines of code is fine).

**Comment by jakevdp** [comment]
Sure – would it be ok to use the example figure from the narrative docs along with a couple lines of example code?

**Comment by astrofrog** [comment]
@jakevdp - that would be perfect!

**Comment by jakevdp** [comment]
For ease of review, here's a relevant documentation build from this PR: http://jakevdp.github.io/astropy/whatsnew/1.2.html#lomb-scargle-periodograms

**Comment by astrofrog** [comment]
Perfect, thanks!

**Pull request merged**
