### PR TITLE
Remove requires_2to3

### PR DESCRIPTION
**Pull request by saimn**
Will need https://github.com/astropy/astropy-helpers/pull/340 or https://github.com/astropy/astropy-helpers/pull/357 first.

### CODE REVIEW

**Comment by astrofrog** [comment]
@saimn - I don't know if the changes to astropy-helpers are needed since this will just get ignored on Python 3 anyway?

**Comment by saimn** [comment]
@astrofrog - Yes it's needed, otherwise `requires_2to3()` is assumed to be True.

**Comment by bsipocz** [comment]
agree with @astrofrog, and locally your branch passes the tests for me...

**Comment by saimn** [comment]
That makes sense, I guess setuptools is clever enough to detect that `requires_2to3` is not needed on Python 3.

**Comment by saimn** [comment]
I removed the `[ci skip]`, let's see.

**Comment by astrofrog** [comment]
Huh, I thought that one had to explicitly set ``use_2to3`` in ``setup.py`` then disable it on a per-package basis using these ``setup_package.py`` functions.

**Comment by astrofrog** [comment]
The confusion might be that the ``setup.py`` option is is called ``use_2to3`` (https://github.com/astropy/astropy/commit/14cb6598b5a56da9e3c016dad425d712e9dc660b#diff-2eeaed663bd0d25b7e608891384b7298) and translates internally into ``skip_2to3`` - I think ``use_2to3`` defaults to ``False`` so then ``skip_2to3`` might default to ``True``? Basically I think we should double check what ``skip_2to3`` is set to as if it's ``True`` then indeed these functions have no effect.

**Comment by bsipocz** [comment]
@astrofrog - ``use_2to3`` from setup.py actually got removed in 6a972b9dab60f15b245bd39d0eb7fd0b500b1332

**Comment by bsipocz** [comment]
Thanks @saimn!

**Pull request merged**
