### PR TITLE
Fixing py2 bug in is_url_in_cache

### PR DESCRIPTION
**Pull request by bsipocz**
This was causing a remote test failure.

### CODE REVIEW

**Comment by mdboom** [comment]
:+1:

As a bugfix, I've milestoned for a point release (though @embray, we could punt to 1.0.6 if 1.0.5 is too close).

This should probably have a CHANGES entry.

**Comment by bsipocz** [comment]
@mdboom - ``is_url_in_cache`` is new in 1.1, so I guess this should go there, too.

**Comment by mdboom** [comment]
Oh -- I missed that.  I'll re-milestone.

**Comment by embray** [comment]
Nice catch, thanks!

**Pull request merged**
