### PR TITLE
make human_file_size accept astropy quantities

### PR DESCRIPTION
**Pull request by keflavich**

### CODE REVIEW

**Comment by embray** [comment]
:+1: I think it should be fine to include this in a patch release--it's a bug by omission :)

**Comment by embray** [comment]
(By which I mean please add a changelog entry in the appropriate section)

**Comment by mhvk** [comment]
@keflavich - while you're editing the changelog, maybe also add to the list of items that is tested in `utils.tests.test_console.test_human_file_size`... Ideally also add a test of an item with the wrong unit.

**Comment by mhvk** [comment]
Looking at languishing PRs, I came across this one. This seems ready to go in, except that, if I understood correctly, @embray asked for the changelog entry in the bug-fix section of 1.1.1.

**Comment by embray** [comment]
I rebased this on master and updated the changlog entry and manually merged in eee1a34d485c8430baa83fba7ac946dc69adf5f8

**Comment by embray** [comment]
And backported to the v1.1.x branch in 7a3a72e

**Pull request closed without merging**
