### PR TITLE
Table/issue 2868

### PR DESCRIPTION
**Pull request by embray**
This finishes up @cherti's original PR at #3055 by rebasing on master and updating to work on master.  I also fixed a few bugs and reformatted the code a bit.  After I submit this PR I'm probably going to rebase again to collapse down some of @cherti's original commits, but will still make sure they get credit.

### CODE REVIEW

**Comment by embray** [comment]
Updated this to work against the current master.  However, I have a question for @taldcroft: I didn't follow most of the `ColumnInfo` development, and it's not clear how the `Column.format` property in this PR interacts with `Column.info.format` and if there's anything more I need to do to fix that up.

Presumably if a column gets its format from its `Column.info` then updating `Column.info.format` should identically test that the format is valid for that column.

**Comment by taldcroft** [comment]
@embray - `Column.info` gets all of `['name', 'unit', 'dtype', 'format', 'description', 'meta', 'parent_table']` from the parent column, so there should be no impact to this PR.  See also:
https://github.com/astropy/astropy/blob/c1030c34e5258c0200334c0036f9fa457cc073a8/astropy/utils/data_info.py#L217

In reviewing this again there are a couple of things that still need to be fixed up:

- Check with `self.pformat(max_lines=1)` independent of dtype
- Raise `ValueError` not `TypeError`

**Comment by embray** [comment]
Thanks for the clarification--upon testing myself it seemed to work fine whether I went through `col.format` or `col.info.format`.  I'll fix up the other things.

**Comment by taldcroft** [comment]
Oh yeah, and so far I have pretty much stuck with the rule of grandfathering `Column` methods to continue using direct attribute access instead of going through `info`.  Any code outside of `Column` classes should use `info` to be mixin-compliant.

**Comment by embray** [comment]
Got it--I think so far this PR sticks with that.

**Comment by pllim** [comment]
Conflicts, incomplete (as I understand from the discussions), and unlikely to be completed. Original issue #2868 is still open.

**Pull request closed without merging**
