### PR TITLE
Rename Redshift model to RedshiftScaleFactor

### PR DESCRIPTION
**Pull request by larrybradley**

### CODE REVIEW

**Comment by embray** [comment]
I'm curious what other people's opinions are about this.  @pllim ?  @nden ?

There seems to have been a lot of confusion surrounding this model, and it's not clear to me whether this alleviates the confusion or not.

**Comment by pllim** [comment]
I am neutral either way. There is not one good name to call this. You can't really call it "RedshiftWavelength" because it also works on frequency, energy, and wave number. But it does not work on a the flux of a spectrum (for that, you need the inverse).

**Comment by pllim** [comment]
@larrybradley, need a few things done before I can merge this:

1. Rebase to latest master.
2. Add a change log under "API changes" for 1.2.
3. Squash all your commits into 1.

**Comment by pllim** [comment]
Note: I asked @larrybradley to retain the old class name for now but issue a `DeprecationWarning`.

**Comment by larrybradley** [comment]
@pllim:  Done!

**Comment by pllim** [comment]
It's been over a year and no one is complaining, so merging. Thanks, @larrybradley !

**Comment by MSeifert04** [comment]
Shouldn't there be a deprecation warning and a temporary "alias" `RedShift = deprecated(RedshiftScaleFactor)` (obviously not correct but you may get the gist of it)?

**Comment by pllim** [comment]
@MSeifert04 , yes, the old `Redshift` is still there and does issue the warning.

**Comment by pllim** [comment]
Here is how it looks like now on dev:

```python
In [1]: from astropy.modeling.models import Redshift

In [2]: r = Redshift(0.6)
WARNING: AstropyDeprecationWarning: The "Redshift" class is now deprecated -- use the "RedshiftScaleFactor" class instead. [astropy.modeling.functional_models]
```

**Pull request merged**
