### PR TITLE
Add ability to read urlopen object in fitsopen

### LINKED ISSUE #4165: Misleading IOError when passing a urlopen object in to fits.open()
Per this SO question: http://stackoverflow.com/questions/32643206/how-do-i-open-a-fits-file-from-a-url-in-astropy

As noted in the answers, one can already pass a URL as a string in to `fits.open()` and that will work fine.  A `urlopen` object has never been supported (intentionally) in the first place.  But it could be supported easily so long as the file is opened in readonly (or denywrite) mode.  It just needs to be handled explicitly.  In any case the error message one gets is also misleading:

```
ERROR: IOError: File-like object does not have a 'write' method, required for mode 'ostream'. [astropy.io.fits.file]
```

This happens despite not explicitly requesting 'ostream' mode.

### PR DESCRIPTION
**Pull request by lingxz**
This pull request fixes #4165 by explicitly checking for a urlopen object. 
I'm not sure if this needs a test though?

### CODE REVIEW

**Comment by embray** [comment]
I think instead `_File._open_filelike` should be fixed to explicitly support reading from the existing request object (rather than making a new request to the same URL).

**Comment by embray** [comment]
And yes, this should include a test.  But the test can just use a `file:///` URL.  There are other examples like that in the test suite.

**Comment by eteq** [comment]
I'm labeling this v1.2 because if my read of #4165 is correct this is actually a *new* feature, as this wasn't necessarily expected/intended behavior before.

**Comment by embray** [comment]
@lingxz Sorry I wasn't able to review this earlier--I was on vacation.  But as it stands this PR is not sufficient--do you have any intention to work on it further?

**Comment by lingxz** [comment]
@embray yes sorry I was busy for the past few days and got distracted, so will work on it ASAP.

**Comment by embray** [comment]
@lingxz It's no hurry! I just wanted to make sure.  Thanks!

**Comment by lingxz** [comment]
@embray how do I construct a relative file:/// object for the test? I couldn't seem to find an example in the test suite. thanks!

**Comment by embray** [comment]
@lingxz See for example https://github.com/astropy/astropy/blob/master/astropy/utils/iers/tests/test_iers.py#L74

**Comment by lingxz** [comment]
@embray to my understanding, the urlopen call only downloads headers, not the entire file, so it is not explicitly making a new request as the original request does not fully download the file. The original fix probably would not have worked as the headers would have been incorrect, I think.

**Comment by embray** [comment]
Right but if a user is passing in an existing `urlopen` result the implication is that they would like the library to read from the existing connection and possibly perform their own handling of the result of that request.  To make an analogy to the `open()` built-in for opening files, a user may open their own file handle and pass that in, because they may be using `fits.open` in the context of a larger application where they're doing their own file handling, and may do other things with the file handle, including close it.

Similarly there's no point of accepting a request object from urllib unless the file contents are read using that request, and astropy is otherwise hands-off.  

`_open_file_like` already should handle this case pretty well.  I think the real problem here is [this line](https://github.com/astropy/astropy/blob/bf0b44b366fb3673b420b06cb2c9028679187bef/astropy/io/fits/file.py#L443) in `_open_file_like`, which surprisingly forces `self.mode = 'ostream'` if the file-like object does not have seek or tell methods.  I think that should probably be removed entirely, as the logic is not correct.  But it should be removed carefully.

**Comment by lingxz** [comment]
Sorry for the delay in fixing this. I have tried removing the part that forces the mode to 'ostream', as you suggested, but that results in an error [here](https://github.com/astropy/astropy/blob/master/astropy/io/fits/hdu/hdulist.py#L869) because without downloading the file, the hdulist appears to be empty, and I'm not sure how to proceed.

**Comment by AMAN3003** [comment]
@embray  I would like to work on this issues could i join

**Comment by pllim** [comment]
Digging through old FITS PRs. I am closing this one for now. If a working solution is found, feel free to re-open or submit a new PR. Thanks for the effort anyway!

**Pull request closed without merging**
