### PR TITLE
Include license file in wheels

### PR DESCRIPTION
**Pull request by saimn**
Ref #7723

See also https://wheel.readthedocs.io/en/stable/#including-the-license-in-the-generated-wheel-file

### CODE REVIEW

**Comment by bsipocz** [comment]
This is probably fine, but I wonder whether we need to include the full licences directory or not?

**Comment by saimn** [comment]
@bsipocz - do you mean in the installed directory ? (it is already included in the sdist archive).

**Comment by bsipocz** [comment]
Yes, in the install. sdist still include many files that eventually never end up with the users.

**Comment by saimn** [comment]
Actually it seems that support for multiple licenses in wheel was added very recently:
https://github.com/pypa/wheel/commit/59976ab294e1b118f42cab404d95df66ed55f7e4

**Comment by bsipocz** [comment]
OK, so let's have this in now, and then I'll update the issue above as a reminder to include all licenses after the new wheel release is out.

**Comment by bsipocz** [comment]
Thanks @saimn!

**Pull request merged**
