### PR TITLE
Add roundtrip test for user-defined unit in ecsv.

### PR DESCRIPTION
**Pull request by mhvk**
This already worked but was not tested. Based on the example in #8897.

@taldcroft - as you can see from the test, if a unit is not recognized, the whole parsing fails. I wonder if instead we should just let it be an `UnrecognizedUnit`? With the logic that one should be generous on input, strict on output.

If you agree, I can change it, either as part of this PR, or in a separate one.

### CODE REVIEW

**Comment by mhvk** [comment]
p.s. Using `UnrecognizedUnit` is a bit closer to what we do for FITS.

**Comment by taldcroft** [comment]
@mhvk - sure, `UnrecognizedUnit` sounds reasonable.

**Comment by taldcroft** [comment]
I thought in #8897 that the issue came up with a `write` then `read` then `write` again sequence.  Does that need testing here for regression?

**Comment by mhvk** [comment]
@taldcroft - OK, `.ecsv` (and all yaml header readers) now use `u.UnrecognizedUnit` as appropriate.  I also added a tip on how to get a real unit in the warning, as you suggested in #9015. Overall, this makes it much better!

Note that the test now is for both `Table` and `QTable`. The difference is that `Column` does not warn for an unrecognized unit.

**Comment by mhvk** [comment]
Note: `mpldev` failure is unrelated; see #9031

**Comment by taldcroft** [comment]
Apparently I can't merge on a phone with failing tests.  Go for it @mhvk.

**Pull request merged**
