### PR TITLE
Fixed tests with latest developer version of Matplotlib

### PR DESCRIPTION
**Pull request by astrofrog**
The latest developer version of Matplotlib is still called 3.1....+... so it's currently not possible to know from the version strings if the developer version is actually 3.2 or 3.3 (normally it's just the next version). I decided to try and fix this by simply treating both 3.1+ and 3.2+ as meaning 3.3. I think the number of users who are likely to want to test with an old developer version of Matplotlib is close to zero, so I think this is the best approach for now and should fix the CI.

### CODE REVIEW

**Comment by astrofrog** [comment]
There's a new failure due to more changes in Matplotlib. Investigating!

**Comment by astrofrog** [comment]
@larrybradley - the current failing test is:

```
    @pytest.mark.skipif('not HAS_MATPLOTLIB')
    def test_imshow_norm():
        image = np.random.randn(10, 10)
    
        ax = plt.subplot(label='test_imshow_norm')
        imshow_norm(image, ax=ax)
    
        with pytest.raises(ValueError):
            # X and data are the same, can't give both
            imshow_norm(image, X=image, ax=ax)
    
        with pytest.raises(ValueError):
            # illegal to manually pass in normalization since that defeats the point
            imshow_norm(image, ax=ax, norm=ImageNormalize())
    
        imshow_norm(image, ax=ax, vmin=0, vmax=1)
        # vmin/vmax "shadow" the MPL versions, so imshow_only_kwargs allows direct-setting
>       imshow_norm(image, ax=ax, imshow_only_kwargs=dict(vmin=0, vmax=1))

astropy/visualization/tests/test_norm.py:239: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
astropy/visualization/mpl_normalize.py:341: in imshow_norm
    imshow_result = ax.imshow(data, **imshow_kwargs)
../../python/dev/lib/python3.8/site-packages/matplotlib/__init__.py:1408: in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
../../python/dev/lib/python3.8/site-packages/matplotlib/axes/_axes.py:5580: in imshow
    im._scale_norm(norm, vmin, vmax)
../../python/dev/lib/python3.8/site-packages/matplotlib/cm.py:200: in _scale_norm
    cbook.warn_deprecated(
../../python/dev/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py:111: in warn_deprecated
    _warn_external(warning, category=MatplotlibDeprecationWarning)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

message = MatplotlibDeprecationWarning('Passing parameters norm and vmin/vmax simultaneously is deprecated. Please pass vmin/vmax directly to the norm when creating it.')
category = <class 'matplotlib.cbook.deprecation.MatplotlibDeprecationWarning'>

    def _warn_external(message, category=None):
        """
        `warnings.warn` wrapper that sets *stacklevel* to "outside Matplotlib".
    
        The original emitter of the warning can be obtained by patching this
        function back to `warnings.warn`, i.e. ``cbook._warn_external =
        warnings.warn`` (or ``functools.partial(warnings.warn, stacklevel=2)``,
        etc.).
        """
        frame = sys._getframe()
        for stacklevel in itertools.count(1):  # lgtm[py/unused-loop-variable]
            if frame is None:
                # when called in embedded context may hit frame is None
                break
            if not re.match(r"\A(matplotlib|mpl_toolkits)(\Z|\.(?!tests\.))",
                            # Work around sphinx-gallery not setting __name__.
                            frame.f_globals.get("__name__", "")):
                break
            frame = frame.f_back
>       warnings.warn(message, category, stacklevel)
E       matplotlib.cbook.deprecation.MatplotlibDeprecationWarning: Passing parameters norm and vmin/vmax simultaneously is deprecated. Please pass vmin/vmax directly to the norm when creating it.

../../python/dev/lib/python3.8/site-packages/matplotlib/cbook/__init__.py:2011: MatplotlibDeprecationWarning
```

The issue appears to be that Matplotlib no longer allows vmin/vmax to be passed directly to ``imshow`` if ``norm`` is also given. What do you think we should do - deprecate ``imshow_only_kwargs``?

**Comment by pllim** [comment]
> deprecate `imshow_only_kwargs`?

FWIW 👍

**Comment by astrofrog** [comment]
Ok so for this PR to be backportable I can't deprecate imshow_only_kwargs here but instead can make the test more robust to recent versions of Matplotlib (>=3.2). We should deprecate imshow_only_kwargs in a separate PR (see https://github.com/astropy/astropy/issues/9861 for an issue to keep track of that)

**Comment by astrofrog** [comment]
The egg info job passed but just didn't report back.

**Pull request merged**
