### PR TITLE
Set arrays writable flag to True before broadcasting

### LINKED ISSUE #8935: TST: Tests failed with Numpy DeprecationWarning about np.broadcast_arrays
Example log from `master` from the `numpy-dev` job: https://api.travis-ci.org/v3/job/552167685/log.txt

```
DeprecationWarning: Numpy has detected that you (may be) writing to an array with
overlapping memory from np.broadcast_arrays. If this is intentional
set the WRITEABLE flag True or make a copy immediately before writing.
```

215 failures total

xref numpy/numpy#12609

### PR DESCRIPTION
**Pull request by pllim**
Fix #8935 

Trying to follow the hint over at numpy/numpy#12609 to explicitly set `arr.flags.writable = True` before passing them into `np.broadcast_arrays`. I am not 100% sure this will work, so need to check the numpy-dev job carefully.

### CODE REVIEW

**Comment by mhvk** [comment]
I *think* this is not needed - see https://github.com/astropy/astropy/issues/8935#issuecomment-506972446

**Comment by pllim** [comment]
Gotcha. Thanks, @mhvk !

**Comment by pllim** [comment]
p.s. Looks like `arr.flags.writable` is incorrect usage anyway. 🤷‍♀ 

```
E   AttributeError: 'numpy.flagsobj' object has no attribute 'writable'
```

**Comment by mhvk** [comment]
That would be worth raising a quick issue: should be `writeable`.

**Comment by bsipocz** [comment]
There was a typo here (that I also made) `writable` vs `writeable` 😅

**Comment by pllim** [comment]
Superseded by #8965 . Ops, my bad on the typo.

**Pull request closed without merging**
