### PR TITLE
Backport PR #14807 on branch v5.3.x (TST: Remove remote call to Danbury, CT)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #14807: TST: Remove remote call to Danbury, CT

### CODE REVIEW

**Review by pllim — APPROVED** [review]

**Comment by eerovaher** [comment]
Why has this not been automatically merged?

**Comment by pllim** [comment]
Hmm maybe it wasn't enabled for backport branches... will have to check.

**Comment by pllim** [comment]
@WilliamJamieson , does https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request not work on backport branches? The setting for this does not appear to be branch specific.

Anyways, I'll manually merge since CI is green. Thanks for the ping!

**Comment by pllim** [comment]
Oh wait, it did auto merge on the other 2 backport branches for the same patch. Maybe it hit the bad GitHub server status period for this one...

**Pull request merged**
