### PR TITLE
upload any codecov in GitHub CI

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

### Description

codecov report is uploaded for any test with the "-cov" flag.

@pllim , you've been testing the GitHub CI, so I'm tagging you here.

no-changelog-needed ?

### CODE REVIEW

**Comment by pllim** [comment]
@nstarman , why this change? There should only be one coverage calculation per build.

**Comment by nstarman** [comment]
For the simple case that the test name can change. I've been setting up my GitHub CI and ran into this. Also, some features that rely on optional dependencies and have conditionals to test for an import. Codecov auto merges coverage reports, so I've taken to uploading 2: one for minimal dependencies, and another for all optional dependencies.

**Comment by pllim** [comment]
Maybe this is more for the template than for core library. cc @astropy/devops-maintainers and @astrofrog

**Review by astrofrog — APPROVED** [review]
I personally think this change makes sense, it protects us against the case where we eg update the python version in the tox env name and forget to update the codecov action. It's also more concise and covers case where we might add one or more additional builds with coverage.

**Review by saimn — APPROVED** [review]
I agree it looks better :+1:

**Pull request merged**
