### PR TITLE
Fix Kernel normalization

### PR DESCRIPTION
**Pull request by larrybradley**
### Description

The documentation for kernels states that the "generated kernel is normalized so that it integrates to 1", but this is not true for many of the kernels.  For example:

```python
>>> from astropy.convolution import Gaussian2DKernel
>>> kernel = Gaussian2DKernel(3, x_size=5, y_size=5)
>>> kernel.array.sum()
0.3570479753738957
```

This PR ensures that the returned kernels are normalized.

This PR also fixes the Kernel `truncation` attribute.  Currently, its value is set in the kernel initializer and thus is not updated after subsequent modifications to the kernel array (e.g., `kernel.normalize(mode='peak')` changes the normalization, but the truncation is not updated).  This PR returns the correct truncation value for the kernel array.

This PR also includes some docstring improvements and some style fixes.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by larrybradley** [comment]
@pllim I re-milestoned to v5.0.5

**Review by keflavich — APPROVED** [review]
This definitely strikes me as an important fix.  I suspect I never encountered it b/c I always make kernels with sizes much larger than the shape being encompassed; a truncated Gaussian is not a good approximation of a Gaussian.

I'm surprised there is only one test hit by this, though.

**Comment by pllim** [comment]
> there is only one test hit by this

Does this mean we need to add more tests to this PR? 😸

**Comment by pllim** [comment]
@larrybradley , for future reference, we need one backport label per backport branch, so I readded the label you removed. FYI.

**Comment by pllim** [comment]
Ops, @larrybradley , maybe v5.0.x backport is impossible after all. If you do not want to manually backport this to v5.0.x, please change the milestone back. I apologize for any inconvenience caused.

**Comment by pllim** [comment]
Oh wait... v5.1.x auto backport failed too. How?

**Comment by pllim** [comment]
Auto backport failed, so I have moved the milestone to v5.2 for now. If you ever get around to manual backports, please update the milestone. Thanks!

**Comment by keflavich** [comment]
Revisiting this for a minute: the new way guarantees that `kernel.array.sum() == 1` (to numerical precision), while the old way properly evaluated the normalized Gaussian function.  We may need to clarify this.

**Pull request merged**
