### PR TITLE
Change ECSV subtype=object to subtype=json

### PR DESCRIPTION
**Pull request by taldcroft**
### Description

Over in https://github.com/astropy/astropy-APEs/pull/68 @mbtaylor requested this change, which seems like a good idea.

@saimn or @pllim - this is an example of a follow-on PR that is really part of #11569. I seem to recall that I am supposed to use the same feature message and this will then put both PR numbers in the change log. Did I get that right?

### CODE REVIEW

**Comment by pllim** [comment]
> Did I get that right?

I think so, but @saimn should confirm.

**Review by pllim — APPROVED** [review]
Looks uncontroversial to me, but someone else from the other PR should also look. I tagged the person who approved the other PR for review.

**Comment by saimn** [comment]
Yep, entries with the same message are merged: https://astropy--11662.org.readthedocs.build/en/11662/changelog.html#astropy-io-ascii

**Review by mhvk — APPROVED** [review]
Nice to see that it is indeed a simple change to implement the suggestion of @mbtaylor!

**Pull request merged**
