### PR TITLE
SEC: replace polyfill.io with Cloudflare equivalent

### PR DESCRIPTION
**Pull request by tnfssc**
### Description

This pull request is to address the usage of `polyfill.io` in `astropy/cosmology/_io/html.py` file. This PR replaces the domain with a Cloudflare equivalent.

> polyfill.io, a popular JavaScript library service, can no longer be trusted and should be removed from websites.

Source: [https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet](https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet)

- [x] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by neutrinoceros — COMMENTED** [review]
Thank you for taking care of this !
Let me ping @astropy/security-team for review

**Comment by pllim** [comment]
I think this only affected a doc example? So I'll defer to @nstarman . Thanks!

**Review by nstarman — APPROVED** [review]
Thanks @tnfssc !

**Comment by nstarman** [comment]
We should definitely not be recommending a supply-chain attack to users 🙅

**Comment by hamogu** [comment]
It should also be backported. Since this PR is already merged, how do we do that?

It also highlights the dangers of supply-chain attacks by using any js library. While the alternative in this PR (cloudflare) is trustworthy, we should keep our attack surface small by avoiding js code that's not absolutely necessary. In this particular case, I see why MathJax is needed, but do we really need polyfill at all? 
If it just gives up some performance is one html code example or compatiblity with some really old browsers, then we might just remove it altogether.
I'm not an html/js expert, but it seems to me that just loading mathjax alone should be sufficient.

**Comment by neutrinoceros** [comment]
Let me give it a try:

@meeseeksdev backport to v6.1.x

**Comment by neutrinoceros** [comment]
I thought so. Well, now you know how to do it @hamogu :)

**Comment by tnfssc** [comment]
@hamogu Adding an `integrity` attribute to the `script` tags usually does the trick (example below). Even there's a supply-chain attack, that maximum damage would be a broken application. Although this wouldn't work in case of `polyfill.io` since the JS it sends back depends on the `User-Agent` header. So the hash would be different depending on the browser :shrug:.

```html
<script
  src="https://example.com/example-framework.js"
  integrity="sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC"
  crossorigin="anonymous">
</script>
```

**Comment by hamogu** [comment]
@meeseeksdev backport to v6.1.x

**Comment by pllim** [comment]
Thanks, @hamogu !

@nstarman , can we remove polyfill ?

**Comment by nstarman** [comment]
@pllim I do think we can remove the link entirely as its only for compatibility with old browsers. https://docs.mathjax.org/en/latest/web/start.html#browser-compatibility

**Comment by pllim** [comment]
I vote to just remove it then. People nowadays can probably debug old browser problem via the power of Internet anyway.

**Pull request merged**
