### PR TITLE
Auto generate referee comments and response

### PR DESCRIPTION
**Pull request by pllim**
For those of you who have to review or write a research paper.

### CODE REVIEW

**Comment by embray** [comment]
:+1: To the concept.  I suggest a larger body of response text and using markov chains though.

**Comment by pllim** [comment]
Why stop at Markov chain?

Turing Bombe

**Comment by bsipocz** [comment]
Hey, it's not the weekend yet. Follow the rules, and no issues before that please! ;)

**Comment by embray** [comment]
Well the tests passed, but without a milestone and associated changelog entry I can't merge this, sorry.

**Pull request closed without merging**
