### PR TITLE
TST: Weekly OSX job to use Python 3.13

### LINKED ISSUE #17140: Reminder: bump weekly cron macos Intel job to Python 3.13
Initially explored in https://github.com/astropy/astropy/pull/17139
currently blocked by the lack of wheels on Pyarrow (and the impossibility to build the latest version from source)
xref https://github.com/apache/arrow/issues/43519

### PR DESCRIPTION
**Pull request by pllim**
### Description

pyarrow 18.0.0 is released with wheel for Python 3.13

xref https://github.com/apache/arrow/issues/43519#issuecomment-2441254999

Fixes #17140

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Linkcheck failure unrelated. Don't really need the "exotic archs" so I cancelled them because they take a long time. The job I was targeting passed.

**Review by neutrinoceros — APPROVED** [review]
LGTM. Thanks !

**Comment by neutrinoceros** [comment]
RTD is red but I can't find the warning that's causing it, though I'm positive it's unrelated.

**Comment by pllim** [comment]
Ah, yes. That is normal for RTD to be red until v7.0 is released now because of the What's New stuff. It is a common problem during release season.

**Comment by pllim** [comment]
Thanks for the quick review!

**Pull request merged**
