### PR TITLE
Update Ruff `pre-commit` hook to v0.3.4

### PR DESCRIPTION
**Pull request by eerovaher**
### Description

The [Ruff rule UP032](https://docs.astral.sh/ruff/rules/f-string/) can automatically convert `str.format()` calls to f-strings. Before v0.3.2 Ruff avoided making changes if the naive conversion produced lines that exceeded the line length limit (88 characters for us), but [now it is more aggressive](https://github.com/astral-sh/ruff/releases/tag/v0.3.2). Updating the `pre-commit` hook manually prevents Ruff from producing overlong lines like it tried to do in #16253.

- [x] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! I see that you milestoned this to v7.0.0, which means we cannot merge until v6.1.x is branched out.

**Review by taldcroft — APPROVED** [review]
Good for io.ascii, time, table.

**Comment by neutrinoceros** [comment]
>  I see that you milestoned this to v7.0.0, which means we cannot merge until v6.1.x is branched out.

Wouldn't this also mean that all bot PRs will be noise until this one is merged ?

**Review by mhvk — APPROVED** [review]
units and utils are fine (not much of an improvement, but also not really worse). Not a rule I feel we should necessarily enforce

**Review by astrofrog — APPROVED** [review]
Looks good to me and will merge to include in v6.1.0 to reduce backport issues.

**Comment by dhomeier** [comment]
> units and utils are fine (not much of an improvement, but also not really worse). Not a rule I feel we should necessarily enforce

Agreed; should perhaps discuss how to deal with cases like
`"a {0:s} b {0:s}c{1:s} 1 {0:s}'2'{0:s} 3.0".format(delimiter, eol)`
where `.format()` is obviously the more efficient construct.

**Pull request merged**
