### PR TITLE
Add documentation for velocity support in coordinates

### PR DESCRIPTION
**Pull request by adrn**
This is a companion to #6219 to add / update the astropy.coordinates documentation to explain how velocities are incorporated. This is mainly just so the files changed in #6219 doesn't get even more out of hand...

### CODE REVIEW

**Comment by eteq** [comment]
Note that I'll also be updating this with docs for #6226

**Comment by eteq** [comment]
Also, this will get the docs for #5752 since that's (indirectly) related work and fits logically in the same doc sections.

**Comment by mhvk** [comment]
Just had a look, and like the initial update. I think we'd need some examples, though, which ideally show some obviously correct transformations (like a PM in pure galactic longitude near the galactic centre, so one sees where it is heading in RA, Dec).

**Comment by adrn** [comment]
Also, as discussed in #6219, clean up mentions of "must be keyword" in `Frame` class docstrings.

**Comment by eteq** [comment]
- [ ] Include "what's new" section on the velocities

**Comment by bsipocz** [comment]
As this is supposed to be docs only I'll go ahead and cut the RC before it. But I'll wait a few more hours in the hope that either @adrn or @eteq wakes up and can rebase this.

**Comment by adrn** [comment]
Right, don't merge yet - we still have some more docs to add!

**Comment by bsipocz** [comment]
OK, this is useful info as well, so I'll go ahead with the RC and will merge this when ready for the actual release.

**Comment by adrn** [comment]
[ ] the `galactocentric.rst` page still needs updating to include information about velocities.

**Comment by eteq** [comment]
@adrn - OK, populated "my sections" from above, so I think it's just the two you noted above.  The "what's new" could maybe use some beefing up, but I'm unsure what to put beyond what's there... open to ideas, but I'm also willing to accept that as it stands here.

**Comment by eteq** [comment]
Oh, but one other thing to add either here or in #6317 (whichever gets merged second):

- [ ] Example of the "easy" differential-choosing from #6317

**Comment by adrn** [comment]
Note: this now contains commits from #6329

**Comment by adrn** [comment]
I added two examples to this PR, but it really could use one more: an example of how to subclass `BaseCoordinateFrame` to implement a position and velocity offset (e.g., shift to the Milky Way-M31 barycenter). Not sure I'll have time to implement this before tomorrow, though...

**Comment by eteq** [comment]
I'm going to go ahead and merge this so that we have this in (if nothing else, for the what's new), but we can definitely still try to squeeze in another example in a separate PR if there's time before the release is finalized, @adrn

**Pull request merged**
