### PR TITLE
Fix bugs in SlicedLowLevelWCS with 1D WCSes

### LINKED ISSUE #9647: Inconsistency behavior in APE14 WCS API implementations
### Description
This issue encompasses a few problems that have cropped up when interfacing with the WCS API wrapper classes (and presumably the APE14 API implementations in GWCS and FITS WCS).

The first issue is in pixel to world values transformation for a sliced wcs (e.g. a wcs wrapped with `SlicedLowLevelWCS` object:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-ccda0c3ea9df> in <module>
----> 1 print(arr_sliced.wcs.pixel_to_world([1, 2]))

~/projects/astropy/astropy/wcs/wcsapi/high_level_api.py in pixel_to_world(self, *pixel_arrays)
    213 
    214         # Compute the world coordinate values
--> 215         world = self.low_level_wcs.pixel_to_world_values(*pixel_arrays)
    216 
    217         if self.world_n_dim == 1:

~/projects/astropy/astropy/wcs/wcsapi/sliced_low_level_wcs.py in pixel_to_world_values(self, *pixel_arrays)
    160                 ipix_curr += 1
    161                 if self._slices_pixel[ipix].start is not None:
--> 162                     pixel_arrays_new.append(pixel_arrays[ipix_curr] + self._slices_pixel[ipix].start)
    163                 else:
    164                     pixel_arrays_new.append(pixel_arrays[ipix_curr])

TypeError: can only concatenate list (not "int") to list
```

It looks to be that it tries to concatenate a `list` and `int` when the pixel values are not passed as an ndarray. Replacing line 162 with

```
pixel_arrays_new.append(list(np.array(pixel_arrays[ipix_curr]) + self._slices_pixel[ipix].start))
```

fixes this issue (presuming that we would want to add the start of slice as an offset to the pixel values).

The second and third problems are a bit more nuanced and have to do with the implementation of `pixel_to_world_values` in GWCS and FITS WCS.

The `pixel_to_world_values` on a gwcs and fits wcs object return different things. For gwcs, it returns a list with a single ndarray containing the world values (e.g. `[array([1, 2])]`), while in fits wcs, it returns just the ndarray (e.g. `array([1, 2])`). This seems to be important because when `SlicedLowLevelWCS` is initialized the pixel dimensions (and world dimensions) to be kept are calculated based on the correlation matrices. In the case of a 1d array wcs, it's just the 0th dimension. This `world_keep` value is applied to the return value of the `pixel_to_world_values` call; in the gwcs case, it correctly gets `array([1, 2])`, but for fits wcs, it returns 1.
Relatedly, applying the index for the kept pixel dimension is done inside a list comprehension, meaning that for gwcs the final returned world values are `[[1, 2]]`. For fits, this means `[1]`.

### Expected behavior
Sliced wcs objects behave consistently.

### Actual behavior
Sliced wcs objects do not behave consistently.

### Steps to Reproduce

The comparison between the gwcs and fits wcs behaviors is demonstrated in this [notebook](https://gist.github.com/nmearl/6ff8b2a239fa017b70bdcd2053b3248d).

### System Details
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.0 (default, Jun 28 2018, 07:39:16)
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.17.4
Scipy 1.1.0
astropy 4.1.dev27003

### PR DESCRIPTION
**Pull request by Cadair**
fixes #9647 

Needs tests.

### CODE REVIEW

**Comment by bsipocz** [comment]
This is affect-dev, right? or have been a bug in 3.2.x?

**Comment by Cadair** [comment]
This was probably also a bug in 3.2.

**Comment by bsipocz** [comment]
If this affects 3.2, @Cadair please add a bugfix changelog entry before we merge it.

**Comment by bsipocz** [comment]
Thanks @Cadair!

**Pull request merged**
