### PR TITLE
Rename inconsistent argument names in docstrings

### PR DESCRIPTION
**Pull request by MSeifert04**
Where the documented argument name wasn't the actual name of the argument

### CODE REVIEW

**Comment by MSeifert04** [comment]
Is there an issue for it? If not it could make sense to create one.

**Comment by pllim** [comment]
Hmm maybe @bsipocz knows. I thought I saw an issue but can't find it here. Maybe it was opened somewhere else in the Astropy project.

**Comment by astrofrog** [comment]
This was something that @drdavella had talked about

**Comment by bsipocz** [comment]
Yes we talked about it with @cdeil a while ago, but hasn't yet set up the infrastructure (and an initial big PR that fixes things). The issue is here https://github.com/astropy/astropy/issues/5504 and the references.

**Comment by drdavella** [comment]
I'm working on a pytest plugin that would check for this kind of thing. It shouldn't take too much longer to have it up and running.

**Comment by MSeifert04** [comment]
Does it need a pytest plugin? I thought numpydoc or pycodestyle would be the better places to hook into it.

**Comment by pllim** [comment]
Two approvals and tests passed, so merging.

**Pull request merged**
