### PR TITLE
Add PEP8 select codes to flake8/pycodestyle config

### PR DESCRIPTION
**Pull request by taldcroft**
### Description

Instead of the instructions (copied below), buried in the PR template, update `setup.cfg` to put the standard PEP8 select codes so that users can see non-compliant code with:
```
flake8 astropy
```

PR template text:
```
Our testing infrastructure enforces to follow a subset of the PEP8 to be
followed. You can check locally whether your changes have followed these by
running the following command:

flake8 astropy --count --select=E101,W191,W291,W292,W293,W391,E111,E112,E113,E30,E502,E722,E901,E902,E999,F822,F823
```

### CODE REVIEW

**Comment by pllim** [comment]
As discussed in a different issue (forgot which one now), this omission was intentional.

**Comment by Cadair** [comment]
Maybe the best answer to this is "tox" because then you could do `tox -e lint` and have it run all the linters. (The CI job could also then run this so it's the same.)

**Comment by bsipocz** [comment]
@taldcroft - We had this, but then removed as it would disable the editors to pick up pep8 issues that we don't fail on with which is undesirable. Last time it was mentioned on #9757 and in  a few discussions on slack: the plan is to move forward and clean up more pep8 and then move ahead with ignore warnings rather  than select, and then that can be added to the config files.

cc @saimn

**Comment by taldcroft** [comment]
OK understood.  Just at this moment it is rather tricky for contributors (especially new ones) to know the right PEP8 settings for checking code locally.  Is there anything we can do today to help out?

**Pull request closed without merging**
