### PR TITLE
[WIP] Adding Exponential and Logarithmic models

### LINKED ISSUE #7792: [Feature Request] Exponential1D model
I found there are polynomial models but not exponential models in [astropy's modeling](http://docs.astropy.org/en/stable/modeling/index.html).

What about including `Exponential1D` and `Exponential2D`?

### PR DESCRIPTION
**Pull request by swapsha96**
Resolves #7792. This PR includes class definitions along with documentation and unit tests for Exponential1D, Exponential2D, Logarithmic1D and Logarithmic2D.

Thanks to @ysBach, @nden, @astrofrog and @eteq.

### CODE REVIEW

**Comment by swapsha96** [comment]
Following is my code for two-dimensional model classes:
```
class Logarithmic2D(Fittable2DModel):
    amplitude = Parameter(default=1)
    r_0 = Parameter(default=1)

    @staticmethod
    def evaluate(x, y, amplitude, r_0):
        return amplitude*np.log((x**2+y**2)/r_0)

    @staticmethod
    def fit_deriv(x, y, amplitude, r_0):
        return None


class Exponential2D(Fittable2DModel):
    amplitude = Parameter(default=1)
    r_0 = Parameter(default=1)

    @staticmethod
    def evaluate(x, y, amplitude, r_0):
        return amplitude*np.exp((x**2+y**2)/r_0)

    @staticmethod
    def fit_deriv(x, y, amplitude, r_0):
        return None
```

I am facing a few problems here:
- How do I return derivative parameters in `fit_deriv`?
- What should be the unit test in these cases?
- How does one write a mathematical equation in the documentation of a class? Any tutorial link for that?

**Comment by pllim** [comment]
Re: test -- See https://github.com/astropy/astropy/blob/master/astropy/modeling/tests/example_models.py

Re: math doc -- See 
https://github.com/astropy/astropy/blob/165dcfd05e5e5dde5e8939d418d4701476f85c3e/astropy/modeling/functional_models.py#L45-L47

**Comment by pllim** [comment]
Example of `fit_deriv` implementation below, although you need to modify the equations to suit your new models

https://github.com/astropy/astropy/blob/165dcfd05e5e5dde5e8939d418d4701476f85c3e/astropy/modeling/functional_models.py#L162-L171

**Comment by swapsha96** [comment]
Also, I get the following graphs when I run this:
```# Generating data
x = np.linspace(0.1, 1., 200)
y = np.linspace(0.1, 1., 200)

model_1 = Logarithmic2D()
z_1 = model_1(x, y)

model_2 = Exponential2D()
z_2 = model_2(x, y)
z_1.shape, z_2.shape

# Plotting
fig = plt.figure(figsize=(12,10))
ax = plt.axes(projection='3d')
ax.scatter(x, y, z_1, '-b')

fig = plt.figure(figsize=(12,10))
ax = plt.axes(projection='3d')
ax.scatter(x, y, z_2, '-b')
'''

![image](https://user-images.githubusercontent.com/14021461/45569044-07232780-b87c-11e8-9c8a-a77d535ef0a5.png)

**Comment by bsipocz** [comment]
@swapsha96 - This will need a rebase (to get rid of the merge commit), and a changelog entry.

**Comment by swapsha96** [comment]
I was trying to calculate parameters to return in `fit_deriv` of `Exponential2D` but I am stuck. Please have a look. I don't think I am going in the right direction. (Please excuse my handwriting.)
img_20180915_003423

**Comment by nden** [comment]
@swapsha96 In this case the derivatives are with respect to parameters, so you will need to calculate the derivative with respect to `amplitude`  and `r_0`. The return should be a list of derivatives with respect to parameters in the same order as `Model.param_names`.

**Pull request closed without merging**
