### PR TITLE
Removed the deprecated astropy.utils.compat.numpy module

### PR DESCRIPTION
**Pull request by bsipocz**
To address part of #8888

### CODE REVIEW

**Comment by bsipocz** [comment]
One could argue to keep the module and only remove the functions, but I foresee that moving forward to have a recent numpy dependency we are less likely to need to host future functionalily like these within astropy.

**Comment by pllim** [comment]
Doc failure seems real?
```
Exception occurred:
  File "/home/circleci/project/venv/lib/python3.6/site-packages/sphinx_automodapi/utils.py", line 78, in find_mod_objs
    __import__(modname)
ModuleNotFoundError: No module named 'astropy.utils.compat.numpy'
The full traceback has been saved in /tmp/sphinx-err-2j8hbbm3.log, ...
```

**Comment by bsipocz** [comment]
Hmm, you're right, I was clumsy. Should we set a big 🔥 or just a small one?

E.g. remove all mentions from the docs, e.g. the notes here at the top http://docs.astropy.org/en/stable/utils/, or just the functions then leaving an empty skeleton of the module?

**Comment by pllim** [comment]
I think we should just make a clean cut. :fire: :fire: :fire: 

What do you think, @mhvk ?

**Comment by mhvk** [comment]
Yes, this never took off, or, rather, for the better, ended up not being needed all that much. I doubt many people rely on it being there, so let's just get rid of it.

**Comment by pllim** [comment]
Let's do this then. Thanks, everyone!

**Pull request merged**
