### PR TITLE
Backport PR #11910: Ensure any .info on Masked instances is propagated correctly.

### PR DESCRIPTION
**Pull request by mhvk**
Manual backport of #11910

### CODE REVIEW

**Comment by mhvk** [comment]
@pllim - I did a manual backport as [requested](https://github.com/astropy/astropy/pull/11910#issuecomment-889148101) but now get a complaint that the PR number does not match. Any suggestion for how to avoid this?

**Comment by pllim** [comment]
According to @saimn at https://github.com/astropy/astropy/pull/11988#issuecomment-888881252 , we can just keep the original change log. I added a label to skip change log check here. 🤞

**Comment by pllim** [comment]
As for the base branch check, it only works properly if it detects the bot or you slap a `skip-basebranch-check` label on the PR *before* you open it. To get that to pass now, you might need to re-push. Sorry.

**Comment by mhvk** [comment]
Hmm, all the remaining failures are false positives, so I'll go ahead and merge this backport.

**Pull request merged**
