### PR TITLE
update changelog for v4.2.1

### PR DESCRIPTION
**Pull request by eteq**
just what it says on the tin...

### CODE REVIEW

**Comment by pllim** [comment]
Do we still need this? I thought we're going with #11279 ? Maybe @saimn knows.

**Comment by saimn** [comment]
We need the updates for 4.2.1, but not the skeleton for 4.2.2 (I can remove it in the other PR if that's easier).

**Comment by eteq** [comment]
I think we want this with the skeleton and remove it in #11279, since if #11279 is delayed for whatever reason, we still want the skeleton to be here.

**Review by Cadair — APPROVED** [review]

**Comment by eteq** [comment]
Normally I wouldn't merge my own PR, but it's in the awkward time of April 1 PR and therefore requires 6 reviewers.  So I'll just hit the button with admin powers.

**Pull request merged**
