### PR TITLE
ENH: Access table column as attribute

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to allow accessing column as table attribute. @barentsen asked about this on Slack and I got curious. Not sure if this is too hacky or not. And somehow an expired leap seconds table prevented me from running tests locally on Windows, so I will have to rely on the CI.

### CODE REVIEW

**Comment by taldcroft** [comment]
I am vigorously opposed to this idea. Using item access improves:

- Readability: if you look at something like `t['name']` you know instantly from the syntax that is a column access operation.  However, `t.name` might be a column or it might be an actual attribute or method.
- Reliability: imagine that we adopt this convention and many codes start using it. There are lots of data tables with common words like `name` or `id`, etc. Then we decide that `Table` should get an attribute `name` or `id`, and this suddenly breaks all those codes. In other words, just because there is not a namespace clash today does not mean there won't be a namespace clash later.

Saving typing four characters is not worth reducing code readability and reliability.

**Comment by dhomeier** [comment]
Looks like you might relatively easily subclass `Table` to get that functionality, but that still leaves the problem of breakage whenever new class attributes are added.

Should the leap second problem sort itself out with time, or will it require action on this side? There was a similar issue on the list, which seemed to solve itself as the day proceeded.

**Comment by pllim** [comment]
We could create a special subclass, yes, but I doubt people would use it much, as `Table` or `QTable` is the advertised usage. Then, it just adds maintenance cost with little return, plus all the breakage that @taldcroft mentioned. Shall we close without merge then?

**Comment by pllim** [comment]
`astropy.utils.exceptions.AstropyWarning: leap-second auto-update failed due to the following exception: IERSStaleWarning('leap-second file is expired.')`

Ah, so it is not just Windows. @mhvk , I forgot how to fix this. Do we need to update the package leap seconds table or something?

**Comment by taldcroft** [comment]
I'm in favor of closing this, having now had the discussion for the record. If people want to make their own subclass that's fine, but I am likewise strongly opposed to having this subclass be part of astropy core.

**Comment by barentsen** [comment]
For background: I raised the question on Slack because we recently refactored the `LightCurve` object in Lightkurve v2.0 to become a subclass of `TimeSeries`, and ended up overriding `__getattr__` to support attribute access to columns for the purpose of backwards-compatibility. (Lightkurve v1.x stored all data in properties, and we didn't want to break all existing code.)

I hear the readability and reliability concerns raised above.  They are valid!

Just to record an argument in favor of attribute access: I think there is value in having the API of `Table` mimic the API of pandas `DataFrame` as much as reasonably possible, to reduce the times a user needs to worry about whether they are using one or the other.

I am personally addicted to the convenience of attribute access, but that may tell you more about the laziness of my fingers than about the wisdom of that design decision.

**Comment by mhvk** [comment]
@pllim - last update was #10617 - I'm surprised it is needed already!?

**Comment by pllim** [comment]
Or maybe this patch broke something in a vague way. Let's wait and see if `master` fails...

**Pull request closed without merging**
