### PR TITLE
Fix segfault with FastCsv and row with too many columns

### LINKED ISSUE #5276: Table.read segfaults on CSV file with missing comma in header
For this `CSV` file with a missing trailing comma in the header line

```
aaa,bbb
1,2,
3,4,
```

I'm getting a segfault from `Table.read`:

```
$ python -c 'from astropy.table import Table; Table.read("test.csv")'
Segmentation fault: 11
```

This is with Python 3.5.2, Numpy 1.11.1 and Astropy 1.2 from Macports on latest Mac OS X.

Here's the crash report:
https://gist.github.com/cdeil/164d4d5ee14b49598e0454873ff0ea04#file-gistfile1-txt-L34

```
1   cparser.cpython-35m-darwin.so   0x0000000111448763 __pyx_pw_7astropy_2io_5ascii_7cparser_7CParser_9read + 1219
```

@mdmueller, @taldcroft or anyone familiar with the astropy.io.ascii cparser: can you reproduce or do you need more info?

### PR DESCRIPTION
**Pull request by saimn**
Adding a check that the currently parsed column number is not greater than the number of columns defined in the header.  (This is already checked in several other places).

Fix #5276. cc @taldcroft @cdeil

### CODE REVIEW

**Comment by saimn** [comment]
Added changelog to 1.0.11, as this can probably be backported.
CircleCI cancelled the first build and is running for the second commit with `[ci skip]` 😢

**Comment by MSeifert04** [comment]
CircleCI doesn't like to be skipped. 😄

**Comment by saimn** [comment]
I found another possibility to make the code segfaults:
```
aaa,bbb
1,2,,
3,4,
```
If you have other ideas of weird cases ...

**Comment by MSeifert04** [comment]
@astrofrog The "rolling builds" on Travis did not work correctly here: it just cancelled the first 5 tests. 

I manually cancelled the others, just wanted to let you know given you just enabled that.

**Comment by taldcroft** [comment]
@saimn - looks good, I think it can be merged if it passes tests.

**Comment by astrofrog** [comment]
@MSeifert04:

> The "rolling builds" on Travis did not work correctly here: it just cancelled the first 5 jobs - 

Can you clarify what you mean here? Was build 13919 cancelled by you or automatically? If you can describe this in a bit more detail, I can pass it on to the Travis team.

**Comment by MSeifert04** [comment]
The jobs marked by the rectangle (+/- 1 don't remember exactly if the OSX one was cancelled) were cancelled before I cancelled the build.

unbenannt

Next time I don't cancel the build so it can be inspected, sorry.

**Comment by astrofrog** [comment]
@MSeifert04 - thanks, this is helpful! Do feel free to cancel next time, but if you can get a screenshot before canceling then I can pass it on to the Travis folk.

**Comment by bsipocz** [comment]
@astrofrog @MSeifert04 - I've seen this travis behaviour occasionally before when manually cancelling a travis job. Somehow, sometimes a few builds survives the cancellation and start testing. I haven't yet found out the reasons or could replicate it.

**Comment by MSeifert04** [comment]
Speaking of cancelling: I stopped the OSX build here. It has been pending for 8 hours.

Might be a bad idea given that this PR changed C code. Feel free to restart that job if it needs to be run here.

**Comment by cdeil** [comment]
> If you have other ideas of weird cases ...

I don't have time today.
Suggest to merge to increase the chance of people trying it out in master.

I've been wanting to do "fuzz testing" for a while:
http://hypothesis.readthedocs.io/en/latest/index.html
https://pypi.python.org/pypi/rstr
This seems like a good application ... before it was possible to input strings of < 10 characters length that cause the crash.
I'm not suggesting to put this in the Astropy tests, just a one-off script to run it now.
If someone else likes the idea and has time, please go ahead.
If no, I'll do it next week.

**Comment by saimn** [comment]
@MSeifert04 - There is nothing fancy in this C code, so it should be fine to skip OSX.

@cdeil - Indeed, some kind of fuzzy testing could be helpful !

**Comment by cdeil** [comment]
Anyone familiar with the ascii CVS reader and interested in fuzzy testing, please have a look and help out here: https://github.com/cdeil/taldcrofts-nightmare

**Comment by pllim** [comment]
@cdeil , perhaps that should be listed as an affiliated package! :wink:

**Comment by bsipocz** [comment]
@pllim - and then start receiving criticism not only for the short description, but the name, too? :)

**Pull request merged**
