### PR TITLE
Revert change to NUMPY_LT_1_24 [ci skip]

### LINKED ISSUE #14131: TST: Test failures in Angle and msort with numpy 1.24rc2
Example log: https://github.com/astropy/astropy/actions/runs/3635473023/jobs/6134601630

Since @mhvk did not catch these while working with numpy dev in https://github.com/astropy/astropy/pull/14128 , does this mean numpy needs to backport more stuff or is this something else? Why did we never see this in the numpy dev job using the "nightly" wheel?

```
______________________________ test_angle_arrays _______________________________

    def test_angle_arrays():
        """
        Test arrays values with Angle objects.
        """
        # Tests incomplete
        a1 = Angle([0, 45, 90, 180, 270, 360, 720.0], unit=u.degree)
        npt.assert_almost_equal([0.0, 45.0, 90.0, 180.0, 270.0, 360.0, 720.0], a1.value)
    
        a2 = Angle(np.array([-90, -45, 0, 45, 90, 180, 270, 360]), unit=u.degree)
        npt.assert_almost_equal([-90, -45, 0, 45, 90, 180, 270, 360], a2.value)
    
        a3 = Angle(["12 degrees", "3 hours", "5 deg", "4rad"])
        npt.assert_almost_equal([12.0, 45.0, 5.0, 229.18311805], a3.value)
        assert a3.unit == u.degree
    
        a4 = Angle(["12 degrees", "3 hours", "5 deg", "4rad"], u.radian)
        npt.assert_almost_equal(a4.degree, a3.value)
        assert a4.unit == u.radian
    
        a5 = Angle([0, 45, 90, 180, 270, 360], unit=u.degree)
        a6 = a5.sum()
        npt.assert_almost_equal(a6.value, 945.0)
        assert a6.unit is u.degree
    
        with ExitStack() as stack:
            if NUMPY_LT_1_24:
                stack.enter_context(pytest.raises(TypeError))
                stack.enter_context(
                    pytest.warns(
                        DeprecationWarning, match="automatic object dtype is deprecated"
                    )
                )
            else:
                stack.enter_context(pytest.raises(ValueError))
    
>           a7 = Angle([a1, a2, a3], unit=u.degree)

.../astropy/coordinates/tests/test_arrays.py:59: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.../astropy/coordinates/angles.py:142: in __new__
    return super().__new__(cls, angle, unit, dtype=dtype, copy=copy, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'astropy.coordinates.angles.Angle'>
value = [array([  0.,  45.,  90., 180., 270., 360., 720.]),
         array([-90., -45.,   0.,  45.,  90., 180., 270., 360.]),
         array([ 12.        ,  45.        ,   5.        , 229.18311805])]
unit = Unit("deg"), dtype = None, copy = True, order = None, subok = False
ndmin = 0

    def __new__(
        cls,
        value,
        unit=None,
        dtype=np.inexact,
        copy=True,
        order=None,
        subok=False,
        ndmin=0,
    ):
...  
>       value = np.array(
            value, dtype=dtype, copy=copy, order=order, subok=True, ndmin=ndmin
        )
E       ValueError: setting an array element with a sequence. The requested array
has an inhomogeneous shape after 1 dimensions.
The detected shape was (3,) + inhomogeneous part.

.../astropy/units/quantity.py:550: ValueError
```
```
_________________________ TestSortFunctions.test_msort _________________________

self = <astropy.units.tests.test_quantity_non_ufuncs.TestSortFunctions object at 0x7fb971acf4c0>

    @pytest.mark.skipif(not NUMPY_LT_1_24, reason="np.msort is deprecated")
    def test_msort(self):
>       self.check(np.msort)

.../astropy/units/tests/test_quantity_non_ufuncs.py:1600: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.../astropy/units/tests/test_quantity_non_ufuncs.py:76: in check
    o = func(self.q, *args, **kwargs)
<__array_function__ internals>:200: in msort
    ???
.../astropy/units/quantity.py: in __array_function__
    return super().__array_function__(function, types, args, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = <Quantity [[0.  , 0.25, 0.5 ],
           [0.75, 1.  , 1.25],
           [1.5 , 1.75, 2.  ]] m>

    @array_function_dispatch(_msort_dispatcher)
    def msort(a):
        """
        Return a copy of an array sorted along the first axis.
    
        .. deprecated:: 1.24
    
           msort is deprecated, use ``np.sort(a, axis=0)`` instead.
    
        Parameters
        ----------
        a : array_like
            Array to be sorted.
    
        Returns
        -------
        sorted_array : ndarray
            Array of the same type and shape as `a`.
    
        See Also
        --------
        sort
    
        Notes
        -----
        ``np.msort(a)`` is equivalent to  ``np.sort(a, axis=0)``.
    
        Examples
        --------
        >>> a = np.array([[1, 4], [3, 1]])
        >>> np.msort(a)  # sort along the first axis
        array([[1, 1],
               [3, 4]])
    
        """
        # 2022-10-20 1.24
>       warnings.warn(
            "msort is deprecated, use np.sort(a, axis=0) instead",
            DeprecationWarning,
            stacklevel=3,
        )
E       DeprecationWarning: msort is deprecated, use np.sort(a, axis=0) instead

.../numpy/lib/function_base.py:3682: DeprecationWarning
```

### PR DESCRIPTION
**Pull request by mhvk**
fixes #14131

cc @pllim.
Not sure if it isn't handier to push this directly to the relevant branches...

### CODE REVIEW

**Comment by pllim** [comment]
Let's do the due diligence and see if daily cron will be green again with this. Thanks!

**Comment by pllim** [comment]
Not sure why CI didn't kick off. Will close/re-open.

**Comment by pllim** [comment]
That is annoying. It won't start. Did Actions flag me as a bot?

**Comment by mhvk** [comment]
No, it is just that I added `[ci skip]` because I thought really it was fine not to run CI...

**Comment by pllim** [comment]
Oh, hah, I missed that. Are you able to amend the commit so at least the daily cron would run? I can cancel the rest (or just let them run).

**Comment by pllim** [comment]
No worries! 😸

**Review by pllim — APPROVED** [review]
Thanks!

**Pull request closed without merging**
