### PR TITLE
Update astropy-helpers to v2.0

### LINKED ISSUE #6323: 2.0rc1: UnicodeDecodeError when documentation built with Python3
When running `python3 setup.py build_docs`, I get the following error:
```
python3 setup.py build_docs
running build_docs
creating /build/python-astropy-2.0~rc1/docs/_build
creating /build/python-astropy-2.0~rc1/docs/_build/doctrees
creating /build/python-astropy-2.0~rc1/docs/_build/html
running build
running build_py
running pre_hook from astropy._erfa.setup_package for build_py command
running pre_hook from astropy.modeling.setup_package for build_py command
running build_ext
running pre_hook from astropy._erfa.setup_package for build_ext command
running pre_hook from astropy.modeling.setup_package for build_ext command
building 'astropy._compiler' extension
gcc -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -O2 -fdebug-prefix-map=/build/python-astropy-2.0~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c astropy/_compiler.c -o build/temp.linux-x86_64-3.5/astropy/_compiler.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -O2 -fdebug-prefix-map=/build/python-astropy-2.0~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/astropy/_compiler.o -o build/lib.linux-x86_64-3.5/astropy/_compiler.cpython-35m-x86_64-linux-gnu.so
Running Sphinx v1.4.9
WARNING: The sphinx_gallery extension is not installed, so the gallery will not be built.  You will probably see additional warnings about undefined references due to this.
loading pickled environment... not yet created
loading intersphinx inventory from http://ipython.readthedocs.io/en/stable/objects.inv...
WARNING: intersphinx inventory 'http://ipython.readthedocs.io/en/stable/objects.inv' not fetchable due to <class 'urllib.error.URLError'>: <urlopen error [Errno 111] Connection refused>
[...]
WARNING: intersphinx inventory 'http://data.astropy.org/intersphinx/numpy.inv' not fetchable due to <class 'urllib.error.URLError'>: <urlopen error [Errno 111] Connection refused>
[autosummary] generating autosummary for: analytic_functions/index.rst, changelog.rst, config/config_0_4_transition.rst, config/index.rst, constants/index.rst, convolution/index.rst, convolution/kernels.rst, convolution/non_normalized_kernels.rst, convolution/using.rst, coordinates/angles.rst, ..., whatsnew/0.1.rst, whatsnew/0.2.rst, whatsnew/0.3.rst, whatsnew/0.4.rst, whatsnew/1.0.rst, whatsnew/1.1.rst, whatsnew/1.2.rst, whatsnew/1.3.rst, whatsnew/2.0.rst, whatsnew/index.rst
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 204, in __init__
    self._init_builder(self.buildername)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 279, in _init_builder
    self.emit('builder-inited')
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 551, in emit
    results.append(callback(self, *args))
  File "/build/python-astropy-2.0~rc1/astropy_helpers/astropy_helpers/extern/automodapi/automodsumm.py", line 250, in process_automodsumm_generation
    lines = automodsumm_to_autosummary_lines(sfn, app)
  File "/build/python-astropy-2.0~rc1/astropy_helpers/astropy_helpers/extern/automodapi/automodsumm.py", line 322, in automodsumm_to_autosummary_lines
    filestr = automodapi.automodapi_replace(fr.read(), app, True, docname, False)
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 407: ordinal not in range(128)
Sphinx Documentation subprocess failed with return code 1
```

### PR DESCRIPTION
**Pull request by bsipocz**
This PR update astropy_helpers to contain the fix required for #6323. Fixes #6323 if CI is passed, though we probably want to keep this PR as a placeholder to update helpers to the final 2.0 release.

Also an RTD fix is piggybacking here, to avoid having to run CI on it (it doesn't have any effect on CI whatsoever).

### CODE REVIEW

**Comment by bsipocz** [comment]
@pllim - Yes, I wonder whether we need to give a grace period for the first check if the PR author is not a maintainer.

**Comment by astrofrog** [comment]
Yes, I've been thinking about adding a grace period, but I need to check how to do that without blocking other requests.

**Comment by bsipocz** [comment]
and then you only want that grace for the first check, later it's nice to have a quick turnaround of the status.

**Comment by bsipocz** [comment]
OK, issue is opened https://github.com/astropy/astropy-bot/issues/5

**Comment by eteq** [comment]
Curious... the doc build failed with an encoding error, but it looks like a *different* encoding error in automodsumm?

**Comment by astrofrog** [comment]
Actually isn't it the sphinx-gallery issue?

**Comment by eteq** [comment]
@astrofrog - I was *guessing* that this is because sometimes the log appears out-of-order, but you might be right...

**Comment by eteq** [comment]
Oh, I missed https://github.com/astropy/astropy/issues/6323#issuecomment-313114639 - now I'm on board...

**Comment by bsipocz** [comment]
Hmm, but the fix in sphinx-gallery has been reverted since, so at the end I guess we cannot yet set the locales yet.

**Comment by astrofrog** [comment]
Well another solution is to remove unicode from the gallery examples!

**Comment by bsipocz** [comment]
@astrofrog - Either way you prefer is fine by me! Let me know and I'll update this PR.

**Comment by astrofrog** [comment]
What are the unicode characters in the gallery actually? Can you easily find them?

**Comment by astrofrog** [comment]
I think if they are substitutable without loss of content, I would prefer that option as the docs will then actually be buildable regardless of locale.

**Comment by bsipocz** [comment]
``grep --color='auto' -P -n "[^\x00-\x7F]"`` finds a few...

**Comment by astrofrog** [comment]
Ha, looks like all of them were not intentional, so they should be removed anyway :)

**Comment by bsipocz** [comment]
There are some unicode left in there :(

**Comment by pllim** [comment]
Wow... those are hard to catch. Great detective work! :+1:

**Comment by bsipocz** [comment]
This PR now contains the update to astropy_helpers v2.0. I've left in a few other the minor cleanup commits, but removed the locale setting to the travis job as it's still failing with sphinx-gallery. I'll open a separate PR for that hoping that we'll find the offending unicode in the examples by 2.0.1

**Pull request merged**
