### PR TITLE
Allow prefixes for units becquerel and curie

### LINKED ISSUE #16526: Missing prefixes for SI-Unit "Becquerel" in astropy.units
### Description

The units **becquerel** (=1/s, SI-Unit for radioactivity) and **curie** (common unit for radioactivity) are defined in `astropy.units.si` without allowing prefixes, see [si.py#L425](https://github.com/astropy/astropy/blob/e969c47734f718458f8b031aead6736f3b8b73ca/astropy/units/si.py#L425). 

According to the [SI brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf) published by the BIPM, 

>  Prefixes may be used with any of the 29 SI units with special names with the exception of the base unit kilogram.

(This includes the unit Becquerel, see Table 4 on page 138). Thus, I would expect astropy.units to allow SI-Prefixes with the units becquerel.

### Expected behavior

I expect astropy.units to allow SI-Prefixes with the units becquerel, i.e. for the error shown below under "how to reproduce" not to occur.

Python script:
```
import astropy.units as u
print(u.MBq)
```

Expected output:

```
Unit("Bq")
```

### How to Reproduce

```
import astropy.units as u
print(u.MBq)
```

Actual output: 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 u.MBq

AttributeError: module 'astropy.units' has no attribute 'MBq'
```

### Versions

```python
import astropy
try:
    astropy.system_info()
except AttributeError:
    import platform; print(platform.platform())
    import sys; print("Python", sys.version)
    import astropy; print("astropy", astropy.__version__)
    import numpy; print("Numpy", numpy.__version__)
    import erfa; print("pyerfa", erfa.__version__)
    try:
        import scipy
        print("Scipy", scipy.__version__)
    except ImportError:
        print("Scipy not installed")
    try:
        import matplotlib
        print("Matplotlib", matplotlib.__version__)
    except ImportError:
        print("Matplotlib not installed")
```
```
Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]
astropy 6.1.0
Numpy 1.26.4
pyerfa 2.0.1.4
Scipy 1.13.0
Matplotlib not installed
```

### PR DESCRIPTION
**Pull request by henrikef**
### Description

This pull request is to address the issue of `astropy.units.si` not allowing prefixes for units of radioactivity (becquerel and curie), see below.

Fixes #16526 

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by neutrinoceros — APPROVED** [review]
prefixes have been excluded from these units forever (at least since astropy 0.3), so it's hard to find back the original reason for this restriction, but I can get behind current recommendations from the standard. Thanks !

**Comment by pllim** [comment]
Originally added back in #1268 -- FYI

**Comment by pllim** [comment]
I think this needs a change log... but I cannot decide which category (feature, api, or bugfix).

**Comment by pllim** [comment]
Also not sure if needs a new test or not... Let's wait for units maintainers to review first. Thanks!

**Review by mhvk — COMMENTED** [review]
No objection. Feels most like a bug-fix to me (but not one we should backport), so indeed good to add a changelog-entry `docs/units/16529.bugfix.rst`.

**Comment by henrikef** [comment]
Changelog added, thank you!

**Comment by mhvk** [comment]
The readthedocs failure is unrelated - @pllim - can you override & squash-merge? A rebase seems overkill. Thanks!

**Comment by pllim** [comment]
Done. Thanks, all!

**Pull request merged**
