### PR TITLE
For YAML < 3.12, ensure AstropyDumper can deal with ndarray.

### PR DESCRIPTION
**Pull request by mhvk**
#5602 noted a problem with the new `yaml` dumper for an older installation. This should be quite common, since it turns out that `ndarray` dumping had a problem in yaml < 3.12, the fix for which --
https://bitbucket.org/xi/pyyaml/issues/64/future-warning-in-saferepresenter-if-numpy -- was released only a few months ago. So, this PR backports the fix to `AstropyDumper` if needed.

@bsipocz - could you check this solves it for you?

@eteq - this would need to make it into 1.3, otherwise we'll likely get many installations with failing tests...

@taldcroft - I know you're away, but just in case, a ping.

### CODE REVIEW

**Comment by bsipocz** [comment]
@mhvk - Yes, the tests now pass with this PR.

**Comment by mhvk** [comment]
@bsipocz - Great!

@eteq - I think this is ready to go in, but am not quite sure how you deal with fixes at this stage, so will leave it to you to do the merge (or tell me what to do).

**Comment by eteq** [comment]
@mhvk -  Happy to merge this, but in the future feel free to merge these yourself, just make sure you set the milestone to "v1.3.0" if it's a fix for 1.3 - as part of the release process we use the milestones to figure out what needs to be backported.

**Comment by eteq** [comment]
backported to v1.3.x in 4eb7fae02ca721b264080f2ddf92b40eef9a2c5e

**Pull request merged**
