### PR TITLE
TST: Increase tolerance for test_custom_frame

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to increase tolerance for `test_custom_frame` due to its flaky nature.

Fixes https://github.com/astropy/astropy/issues/17000

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by larrybradley — APPROVED** [review]

**Comment by neutrinoceros** [comment]
As I noted in https://github.com/astropy/astropy/issues/17000#issuecomment-2345479931, the actual problem is that hash comparison is flaky: RMS may already be 0 and the test still fails in that case. Maybe I'm missing something but I don't see how increasing tolerance (which as far as I understand only affects image comparison and sets a max acceptable RMS value) solves the issue.

**Comment by pllim** [comment]
Does the hash auto-magically also respect the tolerance, @astrofrog ?

**Comment by astrofrog** [comment]
No but if the hash disagrees it then does a full image comparison which then respects the tolerance

**Comment by astrofrog** [comment]
I imagine it's a very small number above zero and is getting rounded

**Comment by neutrinoceros** [comment]
Oh I see. Do you think there's a chance that rounding happens in pytest-mpl itself ? (and wouldn't qualify as a bug ?)

**Comment by pllim** [comment]
@astrofrog , is this good to merge?

**Review by astrofrog — APPROVED** [review]

**Pull request merged**
