### PR TITLE
Example SAMP Tk App updated to work with python3

### PR DESCRIPTION
**Pull request by equant**
### Description

This pull request is to address python3 incompatibility with the example SAMP Tk app in the docs.

EDIT: rebased on master and cleaned up python2 code, ready for review.

~EDIT: Note to maintainers -- DO NOT MERGE this PR. It is opened against `stable` branch, not `master`.~

### CODE REVIEW

**Comment by pllim** [comment]
Thanks, @equant ! Just two small problems:

1. This pull request is opened against `stable` branch, not `master`.
2. `astropy` has no been supporting Python 2 since version 3.0, so the Python 2 compatibility code is unnecessary.

Would you be able to open a new pull request against the `master` branch and only include code for Python 3? We apologize for any inconvenience caused.

**Comment by equant** [comment]
@pllim,

Sure, I'll take care of it and to a new pull request.  Sorry to have gone about it wrong.  Now I know.

**Comment by astrofrog** [comment]
I think we can actually change the base for the PR, let me try...

**Comment by astrofrog** [comment]
@equant - if you like you can rebase and push to this branch as I've now changed the base of the PR to be master - but you'll need to make sure you remove any unrelated commits during the rebase. If it ends up being too messy, you can open a new PR and close this one.

**Comment by bsipocz** [comment]
I've rebased on master and cleaned-up the python2 branch from the patch.

@astrofrog - please review.

**Comment by bsipocz** [comment]
Thank you @equant!

**Pull request merged**
