### PR TITLE
Fix the time difference for the Time object in datetime format (issue #15297)

### LINKED ISSUE #15297: Difference of Time with format 'datetime' returns TimeDelta with format 'jd'
### Description

When computing the difference between two `Time` objects with format `datetime`, the returned `TimeDelta` as format `jd`, which creates accuracy errors in computation.

### Expected behavior

When computing the difference of two `Time` with format `datetime`, the resulting `TimeDelta` objects should have `datetime` format and be exact.

### How to Reproduce

```python
Time(datetime(2023, 7, 1, 8)) - Time(datetime(2023, 7, 1, 6))
# outputs: <TimeDelta object: scale='tai' format='jd' value=0.08333333333333331>
# expected: <TimeDelta object: scale='tai' format='datetime' value=2:00:00>
```

### Versions

```
Windows-10-10.0.19045-SP0
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
astropy 5.3.2
Numpy 1.25.2
pyerfa 2.0.0.3
Scipy 1.11.2
Matplotlib 3.7.2
```

### PR DESCRIPTION
**Pull request by datajungler**
### Description

This pull request is to address the issue #15297 

Fixes #15297 

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! Needs a change log. Time out failures are unrelated.

**Comment by taldcroft** [comment]
@datajungler - thanks for the contribution, we really appreciate the efforts of new contributors!

In this case I'm a little concerned about the special-case handling of `datetime` format inputs. For every other possible combination of `Time` format, the result will have `TimeDelta` format of `jd`. This special case behavior is likely to surprise some users who have come to expect the same consistent behavior over many years. It might even break existing code, for example:
```
>>> t1 = Time(datetime(2000, 1, 1))
>>> t2 = Time(datetime(2000, 2, 1))
>>> dt = t2 - t1
>>> print(f"{dt.value:.0f} days in Jan 2000")
31 days in Jan 2000
```
With this PR this would give:
```
>>> print(f"{dt.value:.0f} days in Jan 2000")
Traceback (most recent call last):
...
TypeError: unsupported format string passed to datetime.timedelta.__format__
```
There are certainly better ways to write that code, but we need to be careful about API changes especially in core functionality like this.

**Comment by datajungler** [comment]
I understand the concern and the rationale behind maintaining 'JD' as the original format now, which indeed makes sense. 

Thank you for bringing it to my attention. Additionally, I agree that surprising the current users and impacting the existing usage behavior are not the desired outcome too.

**Comment by taldcroft** [comment]
@datajungler - OK, I'm closing this. There are still plenty of other issues to tackle, including ones with the `good first issue` label, so hope to see more PR's!

**Pull request closed without merging**
