### PR TITLE
A few modest import-time speedups

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by embray** [comment]
:+1:

**Comment by astrofrog** [comment]
:+1: but since not critical, let's not backport to 1.0 for the final 1.0 release

**Comment by mdboom** [comment]
Yeah -- I agree this shouldn't go on 1.0 at this late date.

**Comment by eteq** [comment]
Do we consider this more in the "bug" category or "new feature"?  That is, should it be milestoned 1.1 or 1.0.1 ?

**Comment by astrofrog** [comment]
Performance only -> 1.0.1?

**Comment by mdboom** [comment]
Yeah -- I think 1.0.1 is fine.  Maybe we merge this now to give it plenty of testing before cutting a 1.0.1 rc.

**Comment by astrofrog** [comment]
@mdboom - can you add a brief changelog entry for 1.0.1?

**Comment by embray** [comment]
@mdboom Could you rebase this one too?  (not sure why it resulted in an apparent coverage decrease, but I'm not worried about that).

**Comment by mdboom** [comment]
Rebased.

**Pull request merged**
