### PR TITLE
Changed the order on which python version is checked.

### PR DESCRIPTION
**Pull request by dpshelio**
Following @astrofog suggestions on [his blog post about python4](http://astrofrog.github.io/blog/2016/01/12/stop-writing-python-4-incompatible-code/).
I've changed the instances where `six.PY3` and `six.PY2` are checked.

There are some places that needs to be updated where the check is:
`if not six.PY3` or `if six.PY3` only.  I imagine these should be changed for:
`if six.PY2` and some additional changes in the code.

To see the ones still missing:
```bash
find ./ -type f -iname '*.py' -exec grep -H 'six.PY3' {} \;
```

### CODE REVIEW

**Comment by pllim** [comment]
Going forward, PY3 is going to be the default for most people, so performance wise, it might be nice to keep check for PY3 on top, like the original code. Just a thought.

**Comment by bsipocz** [comment]
@dpshelio @pllim - What about saying ``if not six.PY2`` in the conditional and put the py3 code on the top? That case both @astrofrog's python4 compatibility, and the performance wise considerations are met.

**Comment by dpshelio** [comment]
@bsipocz that sounds reasonable... I'll make the changes then.  I remember to see some kind of benchmark for astropy, where is it? are these also run to PRs? So I can provide some real numbers when doing the update.

**Comment by astrofrog** [comment]
We have benchmarks here:

https://github.com/astropy/astropy-benchmarks

I seriously doubt that having ``not PY2`` is going to make things faster in any real-life cases here.

**Comment by dpshelio** [comment]
So what's the preference on which way I do it? Also, any suggestion about the `if not six.PY3` OR `if six.PY3` cases by their own? do I change them to the opposite: ie: `if six.PY2` , `if not six.PY2` respectively?

**Comment by astrofrog** [comment]
@dpshelio - the bottom line is that we should probably never actually use ``six.PY3``. I have a preference for:

```python
if six.PY2:
    # python 2 stuff
else:
    # python 3+ stuff
```

over

```python
if not six.PY2:
    # python 3+ stuff
else:
    # python 2 stuff
```

**Comment by mhvk** [comment]
Agreed with @astrofrog - readability counts!  Note also that these clauses are almost invariable executed only at module-loading time; for those, the `if` statement order is really the least of our worries!

**Comment by astrofrog** [comment]
@dpshelio - are there any other changes you want to include here? This looks good so far!

**Comment by dpshelio** [comment]
@astrofrog is good from my side.  There are still 3 `not six.PY3` that I don't know how to solve:
```python
./astropy/units/tests/py3_test_quantity_annotations.py:13:    if not six.PY3:
./astropy/table/table.py:1770:        if python3_only and not six.PY3:
./astropy/io/votable/tree.py:1605:            (not six.PY3 and isinstance(value, six.string_types))):
```
and almost 20 `if six.PY3` by their own which I don't know whether a `not six.PY2` would work better:
```python
./astropy/units/tests/test_logarithmic.py:565:        if six.PY3:
./astropy/units/core.py:507:    if six.PY3:
./astropy/units/core.py:1675:    if six.PY3:
./astropy/units/core.py:1770:            if six.PY3 and isinstance(s, bytes):
./astropy/units/quantity.py:929:    if six.PY3:
./astropy/table/meta.py:168:    if six.PY3 and (type_name.startswith('bytes') or type_name.startswith('str')):
./astropy/table/row.py:200:    if six.PY3:
./astropy/table/table.py:777:    if six.PY3:
./astropy/table/table.py:2496:                if six.PY3:
./astropy/utils/xml/iterparser.py:70:            if six.PY3:
./astropy/wcs/wcs.py:84:if six.PY3 or platform.system() == 'Windows':
./astropy/io/ascii/ecsv.py:147:            if six.PY3 and col.dtype == 'string':
./astropy/io/fits/diff.py:89:    if six.PY3:
./astropy/io/fits/util.py:304:    if six.PY3 and hasattr(f, 'readable'):
./astropy/io/fits/util.py:328:    if six.PY3 and hasattr(f, 'writable'):
./astropy/io/fits/py3compat.py:6:if six.PY3:
./astropy/io/fits/header.py:1977:    if six.PY3:
./astropy/io/registry.py:326:                    if six.PY3:
./astropy/io/registry.py:384:                if six.PY3:
```

**Comment by pllim** [comment]
As for the rest, I would vote for changing `if six.PY3` to `if not six.PY2`, under the assumption that Python4 should follow the logic of Python3 instead of Python2.

**Comment by astrofrog** [comment]
@dpshelio - would you have time to finish this up? I agree with @pllim that ``if six.PY3`` can be changed to ``if not six.PY2``

**Pull request closed without merging**
