### PR TITLE
MNT: cleanup fiduciary comments that are unneeded since Python 3.8 was dropped

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description

ping @hamogu and @nstarman

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by eerovaher — APPROVED** [review]
I can approve for `coordinates`.

**Review by mhvk — APPROVED** [review]
Nice cleanup, thanks!

**Comment by mhvk** [comment]
The failure of the labeler job seems unrelated so merging, but pinging @pllim as the one who might know who might fix this...

**Comment by pllim** [comment]
I think @neutrinoceros already took care of the labeler bot but we won't know until a new PR get opened. 🤞

**Comment by pllim** [comment]
Oh wait, the labeler should have been fixed by the time this was opened, no? The error also looks a bit different:

```
TypeError: Input does not meet YAML 1.2 "Core Schema" specification: sync-labels Support boolean input list: `true | True | TRUE | false | False | FALSE`
```

**Comment by neutrinoceros** [comment]
You're right, this showed my fix didn't work. I'll try again.

**Pull request merged**
