### PR TITLE
MNT: Revive Astropy stalebot in dry-run mode (ported baldrick logic to Action)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is an attempt to revive the good ol' Astropy stalebot logic in [baldrick scripts](https://github.com/OpenAstronomy/baldrick/tree/master/baldrick/scripts) but using GitHub Action. See https://github.com/pllim/action-astropy-stalebot

This supersedes a previous attempt to use `action/stale` (#11760), which just could not handle our policies exactly, even after a few iterations with its devs, who tried to help.

I tested the logic locally in a limited way (pure Python, no Action machinery). I am hoping I can deploy it here in dry-run mode for a bit to squash out remaining bugs before it goes into production.

xref astropy/astropy-bot#125

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]
LGTM, and saw that it works in action (I assume you run the same python scripts earlier yesterday that left the comments)

**Comment by pllim** [comment]
> left the comments

Haha, yes. I ran the revived `stale_issues.py` but only from a local Python session. I am not sure how to run it in Action proper from another repo without jumping through a lot of hoops (also it would be scary to other people to see it even if I did).

**Comment by pllim** [comment]
`stale_pull_requests.py` has a different logic but the pieces are very similar. I did a quick dry-run and didn't see anything amiss.

**Comment by pllim** [comment]
Dry run ran to completion... Need to chew through the logs to see if it actually makes sense... https://github.com/astropy/astropy/runs/3474154697?check_suite_focus=true

**Pull request merged**
