### PR TITLE
Remove NumPy compat functions

### PR DESCRIPTION
**Pull request by MSeifert04**
I'm not sure if the `utils.compat.numpy` module should be deprecated completely so I changed it so that the functions throw the deprecation Warning at runtime.

### CODE REVIEW

**Comment by mhvk** [comment]
This looks good! My only comment would be to be a bit more explicit in the deprecation warning. Something long the lines of: "This function is deprecated, as it is available in all numpy versions that this version of astropy supports."

**Comment by MSeifert04** [comment]
@mhvk I changed the deprecation message.

The failure in the docs build is unrelated (actually #6695 related).

**Comment by mhvk** [comment]
If I understand correctly, master is broken to by the matplotlib link issue, so this can be merged?

**Comment by bsipocz** [comment]
@mhvk - Yes, those 3 warnings are due to #6695

**Comment by MSeifert04** [comment]
@mhvk Yes, the failures are unrelated (and unavoidable currently). But for my part it's ready-to-be-merged 😄

**Comment by bsipocz** [comment]
This got approved and failures are unrelated, so I'm hitting the button. Thanks @MSeifert04!

**Pull request merged**
