### PR TITLE
Update old dataTables version (1.10.12 -> 1.10.25)

### PR DESCRIPTION
**Pull request by Max1mus7**
### Description

This pull request is to address the outdated dataTables.js version being kept within astropy. This simply brings the version of dataTables.js and its associated static files up-to-date.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by nstarman** [comment]
pre-commit.ci autofix

**Comment by neutrinoceros** [comment]
The changelog fragment doesn't meet our requirements, but since the change doesn't affect end users it's not even needed.

**Comment by nstarman** [comment]
@Max1mus7, thanks for the PR. We're pretty wary of changing JS files, and anything with the potential for security vulnerabilities. Can you provide links for where you got all the files from? Thanks!

**Comment by hamogu** [comment]
Thanks a lot for opening this. I think there is only one very small thing to change before we can merge it:

The changelog file needs to be moved or renamed. If it's "other" it needs to be in the root directory. Maybe we should allow "other" in subpackages, too, but we currently don't. This is pretty table specific, so I suggest to keep it where it is and to rename it to "16315.bugfix.rst". It's a bugfix release of dataTables that we are updating, so that fixes whatever bugs are in the datatables version that we currently have.

**Comment by Max1mus7** [comment]
Apologies for the delay, but thanks for checking out this PR!

> @Max1mus7, thanks for the PR. We're pretty wary of changing JS files, and anything with the potential for security vulnerabilities. Can you provide links for where you got all the files from? Thanks!

Absolutely, I copied and pasted straight from [dataTables' official website](https://cdn.datatables.net/1.10.25/).

As for the changelog issue, I've updated the name to have `bugfix` rather than `other`.

**Review by hamogu — APPROVED** [review]

**Review by hamogu — APPROVED** [review]

**Comment by hamogu** [comment]
Thank you @Max1mus7 for seeing this through!

**Comment by hamogu** [comment]
@pllim Apparently, I used the wrong backport labels. I guess, I'm not doing this often enough to be sure which label to match with which milestone, but it looks to me that we're good and I don't have to do anything else because I applied too many and not too few of the backport labels, right?

**Comment by pllim** [comment]
My understanding is that backport to v6.0.x is no longer necessary now that we are about to release v6.1.

`backport-main` is only to forward-port change log during release, it is not for normal use.

Let me try to trigger v6.1.x backport and see.

@meeseeksdev backport to v6.1.x

**Comment by pllim** [comment]
See https://github.com/astropy/astropy/pull/16324 . Thanks, all!

**Pull request merged**
