### PR TITLE
Remove deprecated _recommended_units attribute from Representations.

### PR DESCRIPTION
**Pull request by mhvk**
Part of #8888

### CODE REVIEW

**Comment by bsipocz** [comment]
@mhvk - deprecation removals need to be in the changelog I think.

**Comment by mhvk** [comment]
OK, I'll put it in. I didn't do so because I couldn't find a single instance in `CHANGES.rst` where it said something along the lines of "feature X, deprecated since Y, has now been removed". But I didn't look too carefully.

And it also looks like I should have run the tests...

**Comment by bsipocz** [comment]
Yes, I wish we had kept a better track of versions when features were added, deprecated and then removed, but we don't do it yet. Never too late to start if you think it's useful.

**Comment by bsipocz** [comment]
This needs a rebase.

**Comment by mhvk** [comment]
Thanks for the reminder, now rebased.

**Comment by mhvk** [comment]
Wow, I missed that many...  Though on looking closer, I see the `baseframe` ones should stay: the "recommended" unit now is simply degrees for `Angle`s, and nothing special otherwise.

**Comment by adrn** [comment]
Thanks!

**Pull request merged**
