### PR TITLE
[WIP] Make a cheatsheet for Cosmology

### PR DESCRIPTION
**Pull request by souravsingh**
Added a cheatsheet for Cosmology.Would like to have some views on it.

### CODE REVIEW

**Comment by souravsingh** [comment]
This PR is related to issue #4244

**Comment by astrofrog** [comment]
@aconley and @nhmc can correct me if I'm wrong, but I think #4244 was more to create a list of function in the HTML documentation, not a separate .tex file

**Comment by nhmc** [comment]
Right, my comment in #4244 referred to updating the html docs.

**Comment by souravsingh** [comment]
@crawfordsm mentioned about creating a cheatsheet for the functions.So I made checatsheet in .tex document can be compiled by Sphinx to make a PDF.

**Comment by souravsingh** [comment]
I am sorry if I misunderstood the instructions

**Comment by algerdnazgul** [comment]
@souravsingh Any corrections?

**Comment by souravsingh** [comment]
@algerdnazgul I would like to know if the cheatsheet that I created is what is intended finally or Do I have to mention the cosmology function in the docs?

**Comment by souravsingh** [comment]
Only correction that will be needed for this to work would be to add the TeX file into Sphinx

**Comment by pllim** [comment]
@souravsingh , I think this LaTeX approach is **not** what was requested. Is it possible to make this a RST file that Sphinx can render as HTML?

**Comment by souravsingh** [comment]
I can use ``pandoc`` for making this as a RST file

**Comment by pllim** [comment]
The point is:

1. Remove the LaTeX implementation.
2. Check in the RST version.

**Comment by astrofrog** [comment]
Since this has been inactive, and there is still an issue open for it, I'm going to close this issue. @souravsingh - if you want to continue working on this, you can open a new issue with changes to the RST docs instead of a LaTeX file.

**Pull request closed without merging**
