### PR TITLE
Let Python choose the default SSL protocol for us.

### PR DESCRIPTION
**Pull request by mdboom**
This is a possible fix for #3306.

To summarize: SSLv2 and SSLv3 have been determined to be [unsafe](https://www.openssl.org/~bodo/ssl-poodle.pdf), and so it has been removed from recent versions of OpenSSL (not sure if that's upstream or just as-distributed in many places).  Therefore, recent bugfix release versions of Python have been updated to not provide these protocols when the underlying library does not.  The versions affected are 2.7.9 and 3.4.3.  See Python [22935](http://bugs.python.org/issue22935).  It's not clear if other Python major versions will be updated, since they will shortly stop compiling against OpenSSL.

I thought it best to just move the responsibility of choosing a default SSL protocol to the Python stdlib, rather than maintaining it ourselves.  The defaults may change again in the future if other vulnerabilities are discovered, and I think Python as a whole has a better chance of staying on top of that than we do.  It does mean the protocol used by default depends on the version of Python, and which version of OpenSSL it is linked against.  But the protocols that are even available depends on that, so I don't see much else that we can do.

@embray: If there's going to be another 0.4.x, this is certainly a good candidate for a backport, since the bug is a rather severe "can't import `astropy.vo.samp`" on one of these new Pythons.

### CODE REVIEW

**Comment by embray** [comment]
Yeah, I think this should go in an 0.4.4 release.  I can make that as soon as this is ready (along with any other bug fixes we want to put in there, but I don't think there have been any new ones worth backporting...)

**Comment by embray** [comment]
Otherwise, :+1: thanks for the quick fix.

**Comment by mdboom** [comment]
Ok -- I'll add a CHANGES entry for 0.4.4 then.

**Comment by astrofrog** [comment]
@mdboom - can you remove ``[skip ci]`` from the latest commit to make sure the CI runs?

**Pull request merged**
