### PR TITLE
Standardize import order

### PR DESCRIPTION
**Pull request by astrofrog**
Since we've just merged in #8200 which changes to absolute imports, and will cause a bunch of conflicts with existing PRs, it seems like a good time to also re-order imports. This PR re-orders the imports into:

* Standard library
* Numpy
* Third-party packages
* Absolute astropy imports
* Relative imports

Note that the standard library imports are automatically ordered by isort alphabetically instead of by length so I used a personal fork of it to get the stdlib imports sorted by length. I've opened a feature request to isort to add proper support for sorting just one block by length (https://github.com/timothycrosley/isort/issues/785) and my proposal is that we can turn that on once implemented.

There are a few issues in isort which mean I don't think we can automate the testing of this yet:

* try...except blocks are moved to the bottom of the imports which is not always desired (https://github.com/timothycrosley/isort/issues/421) - unfortunately the response from the isort developers is 'won't fix' so we need to think about how we want to deal with that
* There is a bug that is causing some comments to be dropped (https://github.com/timothycrosley/isort/issues/787)
* isort doesn't deal properly with pytest's importorskip (https://github.com/timothycrosley/isort/issues/786)
* As mentioned above, the sorting of stdlib by length is a feature of my fork of isort, not the main version, but I'll try and open a PR soon.

I've gone through and manually fixed these various issues, but this means that for now, we can't automate the running of isort. However, it's most important I think to get these changes in now and then tweak things later to get most of the changes that would cause conflicts done shortly after the switch to absolute imports.

### CODE REVIEW

**Comment by astrofrog** [comment]
@mhvk - I've tagged you for review in case you want to check that some of the optimizations you made recently still work fine.

**Comment by mhvk** [comment]
@astrofrog - my optimizations changed package or moved imports in-line, so I don't think your changes here can affect them.
Aside: What is against sorting alphabetically? Might as well impose an order where someone can see where to look...

**Comment by astrofrog** [comment]
@mhvk - regarding standard library ordering, I polled people at the coordination meetings and it is a very divisive topic that is split roughly 50:50... Since I opened the PR, I went with my preference. Maybe this is worthy of an APE?

**Comment by eteq** [comment]
I'm 👍 on the general idea, but out-of-band @astrofrog discussed this and agreed it's probably better to split this into a few pieces so it's a more managable review.

**Comment by pllim** [comment]
> it is a very divisive topic that is split roughly 50:50

Not anymore!

import_war

**Comment by pllim** [comment]
Lots of conflicts now. Also, does this really need to be backported?

**Comment by bsipocz** [comment]
Would have made sense with a quick turnaround time to minimize conflicts between the branches, but I agree that now it doesn't need to be backported.

**Comment by astrofrog** [comment]
I'm going to close this. I'll re-open separate PRs for each sub-package.

**Pull request closed without merging**
