### PR TITLE
Create Header instance when _BasicHeader fails

### LINKED ISSUE #9709: astropy.io.fits cannot open any FITS-IDI file
When I try to open any [FITS-IDI](https://fits.gsfc.nasa.gov/registry/fitsidi.html) file using `astropy` 3.2 or newer, the following error occurs:

```
In [1]: from astropy.io import fits

In [2]: hdu_list = fits.open('test.fits')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-29c6c8a8af01> in <module>()
----> 1 hdu_list = fits.open('test.fits')

/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in fitsopen(name, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
    149 
    150     return HDUList.fromfile(name, mode, memmap, save_backup, cache,
--> 151                             lazy_load_hdus, **kwargs)
    152 
    153 

/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in fromfile(cls, fileobj, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
    388         return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
    389                              save_backup=save_backup, cache=cache,
--> 390                              lazy_load_hdus=lazy_load_hdus, **kwargs)
    391 
    392     @classmethod

/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in _readfrom(cls, fileobj, data, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
   1062 
   1063         # Make sure at least the PRIMARY HDU can be read
-> 1064         read_one = hdulist._read_next_hdu()
   1065 
   1066         # If we're trying to read only and no header units were found,

/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in _read_next_hdu(self)
   1137                                 fileobj.seek(offset, os.SEEK_SET)
   1138 
-> 1139                         hdu = _BaseHDU.readfrom(fileobj, **kwargs)
   1140                     except EOFError:
   1141                         self._read_all = True

/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/base.py in readfrom(cls, fileobj, checksum, ignore_missing_end, **kwargs)
    326         hdu = cls._readfrom_internal(fileobj, checksum=checksum,
    327                                      ignore_missing_end=ignore_missing_end,
--> 328                                      **kwargs)
    329 
    330         # If the checksum had to be checked the data may have already been read

/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/base.py in _readfrom_internal(cls, data, header, checksum, ignore_missing_end, **kwargs)
    462                     del new_kwargs[key]
    463 
--> 464         hdu = cls(data=DELAYED, header=header, **new_kwargs)
    465 
    466         # One of these may be None, depending on whether the data came from a

/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/groups.py in __init__(self, data, header)
    275         if len(self._axes) <= 0:
    276             self._axes = [0]
--> 277             self._header['NAXIS'] = 1
    278             self._header.set('NAXIS1', 0, after='NAXIS')
    279 

TypeError: '_BasicHeader' object does not support item assignment
```

At the same time, `astropy` 3.1.2 or older opens such files without any issues.
Test data: `ftp://odin.asc.rssi.ru/outgoing/voitsik/tmp/test.fits`

### System Details
Linux-4.19.82-gentoo-x86_64-Intel-R-_Xeon-R-_CPU_E5-1650_0_@_3.20GHz-with-gentoo-2.6
Python 3.6.9 (default, Dec  2 2019, 12:56:17) 
[GCC 9.2.0]
Numpy 1.17.4
Scipy 1.1.0
astropy 3.2.3

### PR DESCRIPTION
**Pull request by saimn**
Fix #9709 : `_BasicHeader` does not support assignment, with the assumption that HDU classes should not need to modify the header at instantiation. This has been true until now, with one exception (#9193) that has been fixed by another mean.

The problem addressed here is that `GroupsHDU` needs to modify the header to handle some invalid header (#9709). So in this case we fall back to creating a normal `Header` instance. I wanted to avoid this because of the performance penalty but here it is limited to specific cases (e.g. invalid headers). And it was useful to not have this from the start, since it was a good mean to find edge cases like this one :)

### CODE REVIEW

**Comment by MSeifert04** [comment]
The failure `TypeError: buffer is too small for requested array` from CI looks real,

**Comment by saimn** [comment]
The issue is that `fitsdiff` has a test that compares all files in the data directory, which fails because here I'm adding an invalid file:
I tried to move the file in a sub-directory,  but this is still failing when comparing the data directory to itself, because sub-directories are not filtered in this case:
https://github.com/astropy/astropy/blob/61b3a18c73c2dd427cdaf8040a593018fda9c509/astropy/io/fits/tests/test_fitsdiff.py#L226-L228
So I fixed this issue in fitsdiff, even if I'm not too happy with putting another fix in this PR, I don't know how to proceed otherwise.

**Comment by saimn** [comment]
Failure is unrelated (`astropy.utils.data.CacheDamaged: Apparently abandoned files`).

**Comment by pllim** [comment]
Re: CacheDamaged -- FWIW a rebase would get rid of it, as we have temporarily skipped the test.

**Comment by saimn** [comment]
One unrelated failure in the 32 build, after rebasing :
```
______________________ [doctest] docs/io/ascii/index.rst _______________________
[gw3] linux -- Python 3.7.5 /opt/python/cp37-cp37m/bin/python
148   Writing Data Tables as Formatted ASCII Tables
149 
150 The following writes a table as a simple space-delimited file::
151 
152   >>> import numpy as np
153   >>> from astropy.table import Table, Column, MaskedColumn
154   >>> x = np.array([1, 2, 3])
155   >>> y = x ** 2
156   >>> data = Table([x, y], names=['x', 'y'])
157   >>> ascii.write(data, 'values.dat')
UNEXPECTED EXCEPTION: AstropyDeprecationWarning("values.dat already exists. Automatically overwriting ASCII files is deprecated. Use the argument 'overwrite=True' in the future.")
Traceback (most recent call last):

  File "/opt/python/cp37-cp37m/lib/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)

  File "<doctest index.rst[13]>", line 1, in <module>

  File "/tmp/astropy-test-ur8e8wgu/lib/python3.7/site-packages/astropy/io/ascii/ui.py", line 750, in write
    output), AstropyDeprecationWarning)

astropy.utils.exceptions.AstropyDeprecationWarning: values.dat already exists. Automatically overwriting ASCII files is deprecated. Use the argument 'overwrite=True' in the future.
```

**Comment by saimn** [comment]
I think it happens because this is the parallelized build, and `docs/io/ascii/write.rst` also writes a file with the same name (but with `overwrite=True`). And since tests are run in parallel I guess that `write.rst` was run before `index.rst`.

**Comment by saimn** [comment]
So I fixed the changelog, it should be good now. @MSeifert04 seems busy, so maybe @astrofrog or @mhvk you can give it an eye ? :pray:

**Comment by saimn** [comment]
@mhvk - Yes you are right, I will add a comment!

**Comment by saimn** [comment]
@mhvk - Done, please have a look. I skipped the CI since this is just a comment change.

**Comment by mhvk** [comment]
Thanks, I think that is really helpful and clear. Merging...

**Comment by MSeifert04** [comment]
Thanks @saimn and @mhvk

**Pull request merged**
