### PR TITLE
Clarify iers warning message

### LINKED ISSUE #12608: WARNING: Tried to get polar motions for times after IERS data is valid (need clearer message in warning on how to set software default)
Currently, I get:
```
WARNING: Tried to get polar motions for times after IERS data is valid.
Defaulting to polar motion from the 50-yr mean for those.
This may affect precision at the 10s of arcsec level [astropy.coordinates.builtin_frames.utils]
```
raised in:
https://github.com/astropy/astropy/blob/698d2e802ffe163439d6ae0eac6ef76083f6e698/astropy/coordinates/builtin_frames/utils.py#L66

Which files do I need to update (and how) to resolve this warning?

The warning message could be made more user friendly.

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to fix #12608 .

cc @mzechmeister

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Thanks, looks good!

**Comment by mhvk** [comment]
Not sure what's up with readthedocs...

**Comment by pllim** [comment]
`WARNING: py:obj reference target not found: astropy.utils.decorators.wraps`

Wut?

**Comment by pllim** [comment]
Not sure why `astropy.utils.decorators.__all__` includes something that isn't there. I did just released `sphinx-automodapi` 0.14.0. Maybe it includes a fix that catches such things... 🤷

**Comment by pllim** [comment]
Maybe we should  backport...

**Comment by pllim** [comment]
Thanks for the review!

**Comment by mhvk** [comment]
yes, good idea to backport, if only for the second commit!

**Pull request merged**
