### PR TITLE
Make doctests work on Python 2 and 3

### PR DESCRIPTION
**Pull request by embray**
As discussed in #2033 it would be nice to make the doctests work in Python 2 and 3 (though not urgent).

### CODE REVIEW

**Comment by embray** [comment]
Rebased and added a few new fixes.  Now down to 5 failures, most of which are due to #3806.

**Comment by astrofrog** [comment]
@embray - wow, thanks a lot for your work on this!

**Comment by mhvk** [comment]
Thanks from me too; as I develop in python3 exclusively, it would be very helpful indeed if the doctests could be run under it!

**Comment by embray** [comment]
This is so close that I might just try to fix the handful that aren't due to #3806 and then mark the rest as skip for now.

**Comment by mhvk** [comment]
Once this works, we should probably consider doing the travis numpy-dev test under python3 rather than python2.

**Comment by embray** [comment]
Could do both I suppose.

**Comment by embray** [comment]
Updated again to work on the current master.  This PR now depends on #4362 which was needed to get a handful of table and io.ascii tests working properly.

For some of the table tests I punted and added an option to skip some doctests on Python 3 only--these are for tests that print out a table but have different formatting on Python 2 and 3 due to different treatment of string columns.

**Comment by mhvk** [comment]
@embray - this looks great! My one very small comment is that for future understanding it might be better to call the new ones `IGNORE_OUTPUT_PY2` or `IGNORE_OUTPUT_ON_PY2` (and same for `PY3`).  

And the table documentation should use python3 by default... but that's for another PR...

**Comment by embray** [comment]
@mhvk I considered something like that, but I felt it was getting too long.  Figured if someone needs to understand what the flag means a search on the docs will clarify quickly enough.

Definitely :+1: to all the docs using Python 3 by default but as you wrote that's a broader issue (probably more than just the table docs need to be updated).

**Comment by embray** [comment]
Woot--I'm actually kind of amazed all the checks passed, but I did put a lot of work into this in the past.

Since I just merged #4362, this can go ahead in too.  I think I'll aim it for 1.2 though.

**Comment by embray** [comment]
\o/

**Comment by mhvk** [comment]
Great!!

**Pull request merged**
