### PR TITLE
MNT: Enable wheel building for Python 3.9

### PR DESCRIPTION
**Pull request by pllim**
### Description

This PR is to enable Python 3.9 wheels.

- [x] The two TMP commits should be removed prior to merging

This pull request is to help out @astrofrog .

### CODE REVIEW

**Review by bsipocz — COMMENTED** [review]
The wheels are turning, so the it can be wrapped up and then merged away.

**Review by bsipocz — APPROVED** [review]

**Comment by astrofrog** [comment]
Looks like it worked! Have removed the TMP commits.

**Comment by bsipocz** [comment]
No need to wait for CI, none of the diff is tested in any way.

Thanks for both!

**Comment by bsipocz** [comment]
hahh, I cannot merge a "draft"

**Comment by pllim** [comment]
I hope @astrofrog has learned lessons about phone and gravity. 😉

**Comment by astrofrog** [comment]
Yes I have realized the gravity of the situation!

**Pull request merged**
