### PR TITLE
Speedup algorithm used by submodel_names

### PR DESCRIPTION
**Pull request by bernie-simon**
I profiled some code looking for ways to speed up modeling and saw
that a good chunk of time was spent in submodel_names. To speed it up,
I rewrote the code to use a new algorithm that only makes one pass
over the list of names.

Supersede #6115 and #6064

### CODE REVIEW

**Comment by astrofrog** [comment]
@bernie-simon - if possible, please do not re-open new pull requests every time. You should be able to force push to the original branch. We prefer to keep everything in the same pull request to keep the conversation in one place.

**Comment by pllim** [comment]
@bsipocz , I sat down with Bernie, cleaned up his fork, and helped him create this PR, so it should be okay now.

**Comment by pllim** [comment]
@astrofrog , had to refork for him, so force push was not an option. My bad. This should  be the final attempt. Please bear with us. 😄

**Comment by bsipocz** [comment]
I would say that if this is a significant speed-up, a mention of it would be nice in the changelog.

**Comment by pllim** [comment]
@bernie-simon , did you profile before and after?

**Comment by nden** [comment]
There were changes since this work was started. It's best to profile now.

**Comment by bernie-simon** [comment]
Ideally I would have a file with a complex gwcs model to test this. I have several, but they no longer seem to be valid, datamodels crashes when I try to open them. If you have such a file, could you let me know where it is?

**Comment by bernie-simon** [comment]
OK, here are the first results. The script opens and then closes all the reference files I have from crds - twenty times. Timed with the Unix time utility:

Without the change:

* real	2m53.616s
* user	2m4.340s
* sys	0m41.177s

With the change:

* real	2m30.904s
* user	1m56.333s
*  sys	0m34.016s

**Comment by pllim** [comment]
From a user's standpoint, does 2m54s cutting down to 2m31s warrant a change log, @bsipocz and @nden ?

**Comment by nden** [comment]
Is this 2 min 30 sec? That can't be right. Did you use the file I provided?

**Comment by nden** [comment]
Oh, never mind. You are not timing the `Model.submodel_names` but opening and closing reference files?

**Comment by nden** [comment]
Here's my timing of only the change using `timeit Model.submodel_names`  on 109 models.

before:
```
timeit w1.forward_transform.submodel_names
587 ms ± 1.73 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
after
```
timeit w1.forward_transform.submodel_names
588 ms ± 1.59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

```

**Comment by pllim** [comment]
So there is really no speed-up achieved?

**Comment by bernie-simon** [comment]
I'm still testing. Testing was held up yesterday by having an old version of asdf on my machine. The results are naturally going to depend on how much the affected method is called.

**Comment by bernie-simon** [comment]
OK, here is the test case Nadia sent me, run in a loop 20 times:

Original code

* real	1m54.704s
* user	2m5.537s
* sys	0m1.239s

With my change

* real	1m35.054s
* user	1m45.862s
* sys	0m1.243s

**Pull request merged**
