### PR TITLE
added note in wcs.copy() method about deepcopy

### PR DESCRIPTION
**Pull request by MSeifert04**
The text was suggested by @mcara in #4989.

While I added the note I also altered some of the code in ``wcs.__deepcopy__``. I think it makes it more readable but if that's out of scope for this PR I'll remove those changes again.

This may close the above mentioned PR but I'd say the discussion hasn't reached any final conclusion.

### CODE REVIEW

**Comment by MSeifert04** [comment]
No comments? Should I remove the functional changes?

**Comment by mcara** [comment]
I am fine with the changes.

**Comment by pllim** [comment]
@nden , do you want to have a look as well?

**Comment by nden** [comment]
Looks good to me. Should this go in 1.2.2 as simply a documentation change?

**Comment by pllim** [comment]
Sure. Since this has been reviewed and approved, merging.

**Pull request merged**
