### PR TITLE
Add coveralls support for the C code

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by embray** [comment]
Nice! :+1:

**Comment by mdboom** [comment]
Coveralls seems to be uselessly poky today :(  Not entirely sure how this is working, but something about .c files did get posted...

**Comment by embray** [comment]
Happens, sometimes.  Looks like coverage decreased a good bit, which I guess means it's working :)

**Comment by embray** [comment]
Also tracing the C code probably adds some not insignificant runtime overhead.

**Comment by embray** [comment]
Or are you just saying the website is poky?  That certainly seems to be the case.

**Comment by mdboom** [comment]
> Or are you just saying the website is poky? That certainly seems to be the case.

Yeah -- just the website.  The runtime overhead of this seems to be pretty small -- at least locally on my own machine.

**Comment by mdboom** [comment]
> Looks like coverage decreased a good bit, which I guess means it's working :)

Yeah.  Found a couple nasty lurking bugs in `astropy.wcs` this way.

I think in general, it's even harder to get to full code coverage in C code than in Python code.  There are a lot of NULL checks and out-of-memory checks that are pretty hard to reproduce in a test suite but nonetheless are probably good to have in the code.  May want to develop some ignore patterns or something for those kinds of things.

**Comment by embray** [comment]
Memory errors are perfectly easy to test if you compile with your own memory allocator ;)

**Comment by mdboom** [comment]
> Memory errors are perfectly easy to test if you compile with your own memory allocator ;)

:laughing:

**Comment by mdboom** [comment]
Anyway -- this is "working" after a fashion now.  I don't know if we want to eat the 9% coverage decrease and fix it in subsequent PRs or work on it over time.  It ignores everything in cextern and Cython code (which, being generated is just sort of bogus wrt coverage).  But the coveralls "details" link is at least working for reference here in case anyone is curious about where we stand.

**Comment by embray** [comment]
What do you mean that it's ignoring Cython code?  Do you mean it ignores Cython-generated C sources?  Because I am seeing several of those, if not all of them, listed in coveralls.  It's not clear to me how they're being excluded from the coverage report either.  Besides that, one of the other major offenders at the moment seems to be astropy/_erfa/core.c.  Maybe that should be excluded for now too, or at least most of it?

**Comment by mdboom** [comment]
> What do you mean that it's ignoring Cython code? Do you mean it ignores Cython-generated C sources? 

Yes -- that's what I meant.  I just forgot to push a commit that excludes them.  Hopefully after the next Travis CI build they'll be gone.

**Comment by mdboom** [comment]
So, with all of the exclusions properly set (all generated and Cython code) this drops coverage by only 0.2%, which I think is perfectly reasonable.  The time to run the tests seems below the threshold of an accurate measurement.  I'd say this is ready to merge.  (If there's any objections to this in principle, I'd like to merge the coverage improvements and bugfixes independent of making this automatic on Travis).

**Comment by embray** [comment]
@mdboom Are you saying you would prefer to add a separate PR to move the code changes into, and rebase this one to just contain the build script changes?  I'd be fine with that.

**Comment by mdboom** [comment]
I'd prefer to just merge this as-is, unless there are objections to the build script changes (which I haven't heard).

**Pull request merged**
