### PR TITLE
Speed up convolve_fft in a few small ways

### PR DESCRIPTION
**Pull request by keflavich**
As suggested by @jtaylor:
1. Pad to nearest power of 2, 3, 5 (if scipy is available)
2. Allow real ffts, which will use less memory and may be better optimized.  This is awkward to use for now.

WIP - should have feedback before merging is considered

### CODE REVIEW

**Comment by bsipocz** [comment]
ping @keflavich, is this still relevant or shall we close?

**Comment by keflavich** [comment]
Yes, this is still relevant.  I'll rebase it and fix it up; it should probably wait on #5782

**Comment by bsipocz** [comment]
@keflavich - now that #5782 is in, could you rebase this?

**Comment by bsipocz** [comment]
@keflavich - This will need a changelog

**Comment by bsipocz** [comment]
@keflavich - This needs a rebase. Also I wonder whether this can go into RC or rather should be moved to the next milestone? 
Speedups can go into bugfix releases, if they don't change any API, etc, so the next milestone could be either ``2.0.1`` or ``3.0.0``

**Comment by keflavich** [comment]
This is not urgent.  We can put it off to a bugfix release.

**Comment by bsipocz** [comment]
@keflavich - I've moved this to the next milestone as there are a few failures on python2.7 and with the docs. However if you get this merged before tomorrow morning (UT), I'll backport it to the RC.

**Comment by bsipocz** [comment]
@keflavich - this was almost there (especially if we remilestone to 3.0 to drop the failing py27 case), could you please rebase to see whether the issues are gone?

**Pull request closed without merging**
