### PR TITLE
Fix fits import in documentation

### PR DESCRIPTION
**Pull request by saimn**
Minor doc fix: `from fits import Column` is not valid + add missing `from astropy.io import fits`

### CODE REVIEW

**Comment by bsipocz** [comment]
I wonder why this wasn't picked up by the doctests?

**Comment by saimn** [comment]
@bsipocz : Because of `.. doctest-skip-all` ;)
I removed it and skipped only the code-blocks that use a non-existing file.

**Comment by bsipocz** [comment]
Ohh, OK, fair enough :)

**Comment by pllim** [comment]
Looks non-controversial enough. Tagging 1.3 unless people feel like backporting.

**Comment by astrofrog** [comment]
I think it makes sense to backport this since it's a documentation 'bug', so re-milestoning

**Pull request merged**
