### PR TITLE
Add supergalactic coordinate frame

### LINKED ISSUE #3212: Add Supergalactic coordinates to SkyCoord and astropy.coordinates
Supergalactic coordinates are often used in extragalactic work and  are pretty standard. I believe they already exist in other astropy packages (WCS etc). I could add them myself but am more likely to make an error than someone more familiar with the above packages.

### LINKED ISSUE #3722: Adding super galactic coordinates to astropy.coordinates
New function to convert from any coordinate system into super galactic coordinates.
I will implement it

### PR DESCRIPTION
**Pull request by lpsinger**
Closes #3212 and closes #3722

### CODE REVIEW

**Comment by astrofrog** [comment]
Thanks! This addresses https://github.com/astropy/astropy/issues/3212 and https://github.com/astropy/astropy/issues/3722. @AstroMike and @kalgash82, since you opened those issues, maybe you would be interested in helping review the changes here?

**Comment by astrofrog** [comment]
@lpsinger - note that this will need unit tests including if possible a comparison against independently derived values, as well as a changelog and a mention in the documentation.

**Comment by lpsinger** [comment]
Unit tests and changelog entry added.

**Comment by embray** [comment]
Looks good--I think the simplicity of this PR is a testament to how well thought out the coordinates package is :)

**Comment by AstroMike** [comment]
I'm travelling at the moment, but when I return (2+ weeks) I can access some code that I have on an older machine that does some conversions, if this is useful for testing.

**Comment by eteq** [comment]
:+1: from me.  @AstroMike, it would be nice to just make sure this is right from your old code.  If you think you can get to that soon (depending on exactly what the "+" ends up being), would be good to check, but if it will be a while I think it's ok to merge this and you can check it when you get back (and we can fix at that time if needed).

**Comment by AstroMike** [comment]
OK, I'm still away at the moment, but should be back next week.

**Comment by AstroMike** [comment]
OK, I'm back and have located and compiled my old FORTRAN code.

No experience with git though.What is the easiest way to grab and install this test version of astropy?

**Comment by AstroMike** [comment]
With dstndstn's help I managed to grab and test the supergalactic code. I see no issues, agrees with my own.

And for future reference, after all this I remembered that NED also has a coordinate converter which includes supergalactic:

https://ned.ipac.caltech.edu/forms/calculator.html

**Comment by astrofrog** [comment]
@AstroMike - thanks!

@eteq - this is ready for a final review/merging

**Comment by eteq** [comment]
Did a final review and this looks good.  Thanks @AstroMike and @lpsinger , merging!

**Pull request merged**
