### PR TITLE
fix for the ValueError from observing-example-2 #4500

### PR DESCRIPTION
**Pull request by AMAN3003**
please refer to the issue page for additional hints
https://github.com/astropy/astropy/issues/4500

### CODE REVIEW

**Comment by cdeil** [comment]
You change in 6c33b70453b22dbaa41ed0b6105846e407fd6749 is as follows:
```
 -    delta_midnight = np.linspace(-12, 12, 1000)*u.hour
 -    times = midnight + delta_midnight
 +    delta_midnight = np.linspace(-12, 12, 1000)
 +    times = midnight + (delta_midnight)*u.hour
```

To me it looks like that code is equivalent, you just moved the multiplication by `u.hour` to the next line.
I don't think this can fix the issue.

Were you able to reproduce the original error locally?
In this case, that is needed for you to be able to work efficiently on a fix.

**Comment by AMAN3003** [comment]
@cdeil no the original error was gone locally

**Comment by AMAN3003** [comment]
I am explaining you sir how i fixed it 
@cdeil X[0]=start in _axes.py was generating the error because
start contains the xlice[0],y2slice[0] which returns in this case (-12 h,0 ) (sequence)which cannnot be assigned to a array element as xslice[0] has a two elements with space so we should remove the h i.e u*hours

**Comment by AMAN3003** [comment]
@cdeil but removing uhours result in time manipulation error in times = midnight + (delta_midnight) since
delta_midnight should be time so i multiplied it with uhours and the warning was resolved

**Comment by AMAN3003** [comment]
screenshot from 2016-02-06 15 23 20
 proof that ewarning error has gone

**Comment by cdeil** [comment]
@AMAN3003 - You're right. I confirmed locally that your change fixes the issue.

I have a few suggestions that I'll offer now, but ultimately @eteq should review this PR as the Astropy core developer / author of this code.

I think it would be better to leave this code alone ... we want to use quantities as much as possible:
```python
delta_midnight = np.linspace(-12, 12, 1000) * u.hour
times = midnight + delta_midnight
```
To work around the matplotlib issue, you can then change from quantity to numpy array just at the point where it's needed, i.e. do this:
```
plt.plot(delta_midnight.value, sunaltazs.alt, color='y', label='Sun')
plt.scatter(delta_midnight.value, m33altazs.alt, c=m33altazs.az, label='M33', lw=0, s=8)
plt.fill_between(delta_midnight.value, 0, 90, sunaltazs.alt < -0*u.deg, color='0.5', zorder=0)
plt.fill_between(delta_midnight.value, 0, 90, sunaltazs.alt < -18*u.deg, color='k', zorder=0)
```

Whatever fix you apply, it has to be there twice, because that code is duplicated in a `code-block` and a `plot` directive. See here:
https://github.com/astropy/astropy/blame/master/docs/coordinates/observing-example.rst#L95

One last suggestion: move the code from this `plot` directive
https://github.com/astropy/astropy/blame/master/docs/coordinates/observing-example.rst#L108
out into a file `observing-example.py` and change the plot directive to execute that file.
```
.. plot:: observing-example.py
```
That way it'll be easier to run / test that example file than if it's embedded in an RST file.

You can use this command to locally run a clean Sphinx build and check if that docs page still works:
```
python setup.py build_sphinx -l
```

FYI: I'm busy at the moment, so I'm unsubscribing from this GH issue.
@AMAN3003 - Thanks for taking care of this!

**Comment by AMAN3003** [comment]
@cdeil I have made the changes as suggested by you. yo are right we should drop the quantity as its used at many places .

**Comment by AMAN3003** [comment]
@eteq Please review my commit  as you are the core developer of this https://github.com/astropy/astropy/blame/master/docs/coordinates/observing-example.rst

**Comment by taldcroft** [comment]
Closed by Astropy Project Coordinators.

**Pull request closed without merging**
