### PR TITLE
Update IERS Earth rotation and leap second tables (v5.2.x)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to manually update IERS data from the script because automated update cannot be backported. I notice that the filename has also changed in `main`. 🤷

As in #14778 , the diff seems excessive... `+14,343 −14,262`

### CODE REVIEW

**Comment by pllim** [comment]
Yeah, tests are failing. Something isn't right but I dunno what.

**Comment by pllim** [comment]
That is annoying, the dev job failures I think is a mix of numpy-dev ones and maybe stuff from #14382 that didn't get backported.

**Comment by pllim** [comment]
I think the remaining failures are unrelated... 🤞

**Review by mhvk — APPROVED** [review]
I think this looks all good. With hindsight, perhaps we should have backported #14382 after all... It is certainly annoying that essentially the whole file changed.

**Comment by pllim** [comment]
Thanks for the review and approval, @mhvk !

Re: Hindsight -- It was a tough call. There were API changes that turned out to be unnecessary after upstream reverted stuff. 🤷

**Pull request merged**
