### PR TITLE
DOC: Temporary ignore astromatic in link check

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to temporarily ignore astromatic website in link check job until #11538 has a permanent fix upstream. Otherwise, we might miss other broken links.

p.s. I cancelled irrelevant CI.

### CODE REVIEW

**Comment by pllim** [comment]
@mhvk , does this error ring a bell to you?

```
astropy/utils/masked/core.py:docstring of astropy.utils.masked.MaskedNDArray.shape:24:py:obj reference target not found: ndarray.reshape
```

**Review by mhvk — APPROVED** [review]
Makes sense.

**Comment by mhvk** [comment]
@pllim - weird error! Maybe it is because I inherit the shape property from `ndarray`!? I'll check.

**Comment by pllim** [comment]
@mhvk , here's another one:

```
utils/masked/core.py:docstring of astropy.utils.masked.MaskedNDArray.unmasked:16:py:obj reference target not found: filled
```

**Pull request closed without merging**
