### PR TITLE
refactor: ReadOnlyDict as MappingProxyType

### PR DESCRIPTION
**Pull request by nstarman**
Clean up a semi-private API in a way that doesn't change API, e.g. for `isinstance(x, astropy.utils.data.ReadOnlyDict)`.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by neutrinoceros — COMMENTED** [review]
This class isn't used outside this module and isn't part of `__all__`; do we know of any external use case that would justify preserving the name ? Otherwise I would prefer avoiding importing with an alias.

**Comment by nstarman** [comment]
I don't see anything on a GH search. I can change it.

**Review by neutrinoceros — APPROVED** [review]
Looks good now.

**Comment by neutrinoceros** [comment]
Whoops, looks like I still have write access to your fork @nstarman, which means that if I merge your PR from the web interface, my browser extensions will automatically delete your branch. Please let me know if this is fine with you. I don't mind if you want to revoke my access to your fork. Any way, thanks !

**Pull request merged**
