### PR TITLE
Fix asdf test helper to use new resolver

### LINKED ISSUE #9816: TST: ASDF 2.5.0 broke some tests
Our CI is now picking up [ASDF 2.5.0](https://github.com/spacetelescope/asdf/releases/tag/2.5.0), which broke the following tests:

```
____________________________ test_backwards_compat _____________________________
    def test_backwards_compat():
        """
        Make sure that we can continue to read FITS HDUs that use the schema from
        the ASDF Standard.
    
        This test uses the examples in the fits schema from the ASDF Standard,
        since these make no reference to Astropy's own fits definition.
        """
    
        def check(asdffile):
            assert isinstance(asdffile['example'], fits.HDUList)
    
>       run_schema_example_test('stsci.edu', 'asdf', 'fits/fits', '1.0.0', check)
astropy/io/misc/asdf/tags/fits/tests/test_fits.py:55: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/io/misc/asdf/tags/tests/helpers.py:14: in run_schema_example_test
    uri = asdf.resolver.default_tag_to_url_mapping(tag)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
uri = 'tag:stsci.edu:asdf/fits/fits-1.0.0'
    def default_tag_to_url_mapping(uri):
>       warnings.warn("'default_tag_to_url_mapping' is deprecated.", AsdfDeprecationWarning)
E       asdf.exceptions.AsdfDeprecationWarning: 'default_tag_to_url_mapping' is deprecated.
.../asdf/resolver.py:169: AsdfDeprecationWarning
____________________________ test_backwards_compat _____________________________
    def test_backwards_compat():
        """
        Make sure that we can continue to read tables that use the schema from
        the ASDF Standard.
    
        This test uses the examples in the table schema from the ASDF Standard,
        since these make no reference to Astropy's own table definition.
        """
    
        def check(asdffile):
            assert isinstance(asdffile['example'], table.Table)
    
>       run_schema_example_test('stsci.edu', 'asdf', 'core/table', '1.0.0', check)
astropy/io/misc/asdf/tags/table/tests/test_table.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/io/misc/asdf/tags/tests/helpers.py:14: in run_schema_example_test
    uri = asdf.resolver.default_tag_to_url_mapping(tag)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
uri = 'tag:stsci.edu:asdf/core/table-1.0.0'
    def default_tag_to_url_mapping(uri):
>       warnings.warn("'default_tag_to_url_mapping' is deprecated.", AsdfDeprecationWarning)
E       asdf.exceptions.AsdfDeprecationWarning: 'default_tag_to_url_mapping' is deprecated.
.../asdf/resolver.py:169: AsdfDeprecationWarning
```

Example log: https://travis-ci.org/astropy/astropy/jobs/629110036

As a result, the failures caused unrelated push events to fail as well (e.g., https://github.com/astropy/astropy/pull/9780#issuecomment-568782904).

### PR DESCRIPTION
**Pull request by jdavies-st**
### Description

This fixes the DeprecationWarning issue by using the new resolver machinery in `asdf 2.5.0`.

Fixes #9816
Closes #9818

### CODE REVIEW

**Comment by bsipocz** [comment]
@jdavies-st - is this require a change in the minimum asdf version, too? (currently it's >=2.3)

**Comment by jdavies-st** [comment]
That's a good question.  It is only a deprecation warning in `asdf` at the moment, so no bump in version is required for this PR.  I.e. the production code still works and hasn't been removed yet.

And the change here in this PR is only for a testing helper, so no changelog needed I think.

That said, the minimal version of `asdf` required for `astropy 4.0` is probably `asdf 2.5.0` now.  Perhaps @nden can comment?  And perhaps `gwcs` might have changed as well?

**Comment by bsipocz** [comment]
>That's a good question. It is only a deprecation warning in asdf at the moment, so no bump in version is required for this PR. I.e. the production code still works and hasn't been removed yet.

My question is more for the other way around. Would this change work with 3.2?  If not we either need to bump the version, or add an `if/else` depending on the asdf version.

Given that we already released 4.0 with the `3.2` requirement, it probably needs to be an `if/else` on the 4.0.x release branch, but honestly, I'm not sure how strict we need to be with not dropping the asdf versions, @nden and @eteq will know.

**Comment by pllim** [comment]
Thanks, everyone! I also wonder if the job that is allowed to fail should add dev ASDF into the mix. @bsipocz , what do you think?

**Comment by bsipocz** [comment]
> Thanks, everyone! I also wonder if the job that is allowed to fail should add dev ASDF into the mix. @bsipocz , what do you think?

having an all dev cron job would make much sense indeed, something I was thinking about doing for a while but never got to it (e.g. https://github.com/astropy/astropy/issues/8197)

**Comment by jdavies-st** [comment]
The changes in this PR are only needed for `astropy>=4.0.0`.  I bumped `asdf_minimum_version` and the extras require in `setup.cfg`.

**Comment by jdavies-st** [comment]
Whether this change is needed for `astropy 2.3`, I don't know.  Do you have CI on the `astropy 2.3` branch that pulls `asdf 2.5`?  If there are no problems, then it doesn't need it.

**Comment by bsipocz** [comment]
astropy 3.x is not supported any longer. The only remaining question is that is it OK to bump the asdf dependency version requirement in a bugfix release (4.0.1) for an LTS release, or it should go into 4.1.

cc @eteq @astrofrog @taldcroft

**Comment by jdavies-st** [comment]
The new `asdf` version requirement was needed in `astropy 4.0.0`, but because `asdf 2.5.0` was not released yet, there was a chicken/egg problem.  This is the problem with having schemas defined in `asdf-standard` (a submodule of `asdf`) that serialize/instantiate objects in `astropy`.

My preference would be schemas living with the code for the python objects that need them for serialization, but that's a separate topic which I'm sure has been discussed elsewhere.

I think the bump in `asdf` dependency in this PR needs to go in 4.0.1, not 4.1.0.

**Comment by bsipocz** [comment]
Thank you both!

**Pull request merged**
