### PR TITLE
Build doc on RTD with pip (drop conda)

### PR DESCRIPTION
**Pull request by saimn**
Following a similar PR on photutils (https://github.com/astropy/photutils/pull/701), and because installing the conda environment takes a lot of time. 
For instance, with a recent conda build (https://readthedocs.org/projects/astropy/builds/7593162/) the conda setup takes ~500 sec, and 1364 sec for the total (for a build without rst change) - and the limit is 1500 sec.
And for two pip builds on my fork (https://readthedocs.org/projects/astropy-saimn/builds/7595855/ and https://readthedocs.org/projects/astropy-saimn/builds/7596724/), the setup is immediate as RTD seems to keep the env between builds, and the total is ~700 sec.

### CODE REVIEW

**Comment by saimn** [comment]
I canceled some builds since this must be tested directly on RTD.

**Comment by pllim** [comment]
Would be nice to backport if possible...

**Comment by bsipocz** [comment]
@saimn - Yes, this totally should be ported back (some part of the config may need some tweaking, but that's OK. I also go ahead and merge, no need to wait any CI on this...

**Comment by bsipocz** [comment]
Thank you @saimn!

**Comment by pllim** [comment]
:tada: Build took 883 seconds :tada: 

https://readthedocs.org/projects/astropy/builds/7598317/

**Pull request merged**
