### PR TITLE
Make plugins and dependency checking overrideable in the test runner

### PR DESCRIPTION
**Pull request by Cadair**
The idea of the very OTT test runner is there is nothing in there which is astropy specific that can't easily be turned off in a subclass ;)

@drdavella git suggests this code was once yours?

### CODE REVIEW

**Comment by Cadair** [comment]
@bsipocz I would consider this a bug rather than a feature. It's a regression of the functionality I originally implemented so SunPy can pick which bits of the astropy test runner we use. It would be nice if it could find its way into 3.0.z :smile:

**Comment by bsipocz** [comment]
Oh, well, given it's infrastructure code I'm more flexible ;) 

But @drdavella or @astrofrog please override if you think it should be in 3.1

**Comment by mhvk** [comment]
Changes look good to me.

**Comment by pllim** [comment]
Bot is happy, maintainer approved, tests passed. So merging.

**Pull request merged**
