### PR TITLE
Fix IERS error message and upgrade tests

### PR DESCRIPTION
**Pull request by weaverba137**
This PR fixes a problem where an error message in `astropy.utils.iers.iers.IERS_Auto` was improperly formatted.  It also improves the testing of `IERS_Auto`.

### CODE REVIEW

**Comment by bsipocz** [comment]
@weaverba137 - Could you please rebase to drop the all but the last 2 commits those that contain the relevant  changes?

**Comment by bsipocz** [comment]
Also, this PR won't require a changelog entry.

**Comment by weaverba137** [comment]
Just squashed the commits that altered the changelog, mainly so I could practice doing that.

**Comment by bsipocz** [comment]
Sorry @weaverba137 for not getting back sooner, I see that you've nicely managed the rebase since. 

A very brief howto is here in the dev docs http://docs.astropy.org/en/latest/development/workflow/development_workflow.html#revise-and-push-as-necessary, basically using the interactive rebase for all cases (not just for squashing) is the most intuitive `git rebase -i`, so then unrelated commits can be removed straight away. 

This following website has some rather good visualization. Rebasing is introduced in the "Moving work around" section, while rather messy situations are shows how to dealt with in the "Advanced topics" https://learngitbranching.js.org/

**Comment by weaverba137** [comment]
Yes, I had lots of help from @pllim.  Thank you for the additional links.

**Pull request merged**
