### PR TITLE
EXP: Debug devdeps failure with PytestUnraisableExceptionWarning

### PR DESCRIPTION
**Pull request by pllim**
### Description

https://github.com/astropy/astropy/actions/runs/4265444197/jobs/7424786551

### CODE REVIEW

**Comment by pllim** [comment]
Is it related to https://github.com/python/cpython/issues/77894 ? 🤷‍♀️

**Comment by pllim** [comment]
Hmm could the failure only happen in Python 3.11 + numpy-dev combo?

**Comment by pllim** [comment]
I cannot reproduce this with Python 3.11.0 from conda and numpy nightly wheel. The log in CI says it is using Python 3.11.2.

**Comment by pllim** [comment]
Last green devdeps: https://github.com/astropy/astropy/actions/runs/4247771490/jobs/7386198567 (before all the asdf deprecations getting in the way)

```
Full Python Version: 
3.11.2 (main, Feb  8 2023, 08:38:01) [GCC 11.3.0]

Numpy: 1.25.0.dev0+678.g51ecf8401
```

Now with this failure: https://github.com/astropy/astropy/actions/runs/4265444197/jobs/7424786551

```
Full Python Version: 
3.11.2 (main, Feb  8 2023, 08:38:01) [GCC 11.3.0]

Numpy: 1.25.0.dev0+787.g3f142646c
```

**Comment by pllim** [comment]
The diff can be seen in https://github.com/numpy/numpy/compare/51ecf8401..3f142646c but that is too many changes. The nightlies appear to be a week apart according to https://anaconda.org/scipy-wheels-nightly/numpy/files .

**Comment by mhvk** [comment]
Almost certainly https://github.com/numpy/numpy/pull/22924 given the "RuntimeError: Internal error, tried to fetch clear function for the user dtype '' without fields or subarray (legacy support)", which was introduced there...

**Comment by mhvk** [comment]
Our failure looks due to `astropy/io/votable/tests/table_test.py`, specifically `test_binary2_masked_strings`, but it does not raise if one just does the one test -- it requires `test_no_field_not_empty_table` to be run beforehand to cause the problem (all others can be commented out and do not change the result).

Indeed, the latter seems to be the real problem. in a separate `ipython` session, I get
```
In [1]: from astropy.io.votable.tests.table_test import test_no_field_not_empty_table

In [2]: test_no_field_not_empty_table()

In [3]:                                                                                                         
Do you really want to exit ([y]/n)? 
Exception ignored in tp_clear of: <class 'astropy.io.votable.tree.VOTableFile'>
Traceback (most recent call last):
  File "/data/mhvk/venv/numpy-dev2/lib/python3.11/site-packages/IPython/core/displayhook.py", line 317, in flush
    gc.collect()
RuntimeError: Internal error, tried to fetch clear function for the user dtype '' without fields or subarray (legacy support).
```
So, it clearly is something that happens only at clean-up time.

**Comment by mhvk** [comment]
Minimal example to reproduce:
```
In [1]: from astropy.utils.data import get_pkg_data_filename

In [2]: from astropy.io.votable.table import parse

In [3]: votable = parse(get_pkg_data_filename("data/no_field_not_empty_table.xml", package='astropy.io.votable.t
   ...: ests'))

In [4]:                                                                                                         
Do you really want to exit ([y]/n)? 
Exception ignored in tp_clear of: <class 'astropy.io.votable.tree.VOTableFile'>
RuntimeError: Internal error, tried to fetch clear function for the user dtype '' without fields or subarray (legacy support).
```

**Comment by mhvk** [comment]
Digging deeper, I think this may be the dtype causing a problem
```
In [26]: votable.resources[0].tables[0].array
Out[26]: 
masked_recarray(data=[],
                mask=[],
          fill_value=b'???',
               dtype='|V8')
```

This leads to a pure numpy example - see https://github.com/numpy/numpy/issues/23277

**Comment by pllim** [comment]
Fixed upstream. CI is green on main now. Thanks, all!

https://github.com/astropy/astropy/actions/runs/4285566401/jobs/7464036187

**Comment by mhvk** [comment]
Great!

**Pull request closed without merging**
