### PR TITLE
Update copyright years and ReST formatting of licenses

### PR DESCRIPTION
**Pull request by namurphy**
This pull request makes the following changes:
 - Updates the end copyright year in Astropy's license file to 2018
 - Updates the end copyright years in the NumPy, SymPy, and pytest licenses to 2018
 - Changes the reStructuredText (ReST) formatting for several external licenses where indentations were treated as quotations when they shouldn't have been (but without changing the text of the licenses, except as described above)

I did not update the end copyright years for any other licenses yet since I do not know if development has continued, but we could update any other licenses as well.  I'd like to check WCSLIB's licenses in particular to make sure everything is consistent between the different directories.

[skip ci]

### CODE REVIEW

**Comment by namurphy** [comment]
To follow up, right now `WCSLIB_LICENSE.rst` is a copy of the GNU Lesser General Public License (LGPLv3) without a copyright notice.  The copyright notice is in `cextern/wcslib/README`, so everything is consistent as far as I can tell.

**Comment by eteq** [comment]
Thanks for the careful work here @namurphy - I'm inclined to call this good... *but* the question is whether there are some legal reasons why licenses have to be kept in their original form. These all look like they were probably copy-and-pasted from plain text licenses.  I would *think* this kind of cosmetic alteration is still fine since it preserves all the actual content.  But IANAL... I wonder if anyone knows better about this?

@namurphy if you have some idea, let me know, but if not, we'll try to figure it out (or if no one knows, just merge and hope for the best :wink:).  

Other folks who might have context or knowledge about this: @arfon @astrofrog

**Comment by eteq** [comment]
> There's no requirement related to the formatting, as long as the text is reproduced verbatim. This license also has no restrictions on adding explanatory text to the license file, if we wanted to do something like that.

I see your point here. The most questionable one I suppose is the LGPL, which says "Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed."  Is this "changing" it? I'm probably being over-cautious here... But lets give it a ~day or two to see if any others have specific knowledge on this?  If no objections by then I'll go ahead and merge.

And @bsipocz - assuming we merge it in time, yes, good point this could be 3.0 since it's docs-only.  Will adjust that.

**Comment by namurphy** [comment]
For the LGPLv3, the relevant clause is:

> Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

The first clause gives permission to distribute verbatim copies which indicates that the important requirement is that it is verbatim, and I think the second clause refers to changes to non-verbatim changes rather than formatting.  The LGPL is [available in different formats](https://www.gnu.org/licenses/lgpl-3.0.en.html) as well, but it is not available from the GNU website in reStructuredText, unfortunately.  If we're worried about changing the formatting, we could put the [Markdown version of the LGPL](https://www.gnu.org/licenses/lgpl-3.0.md) here instead.

**Comment by eteq** [comment]
> The LGPL is available in different formats as well

I think a reasonable interpretation here is that "verbatim" then means the content, not the details of the formatting.  Further evidence for the "I'm being overly-cautious" :wink:

**Comment by namurphy** [comment]
@eteq - Sounds good!

**Comment by arfon** [comment]
> Other folks who might have context or knowledge about this: @arfon @astrofrog

AFAIK this is fine.

**Comment by astrofrog** [comment]
Just to put this out there, a much less invasive change would be to rename the licenses so that they are not ``.rst`` (since they weren't ResT to start with) and they will then be rendered nicely in a monospace font (as a plain text file) by GitHub. For our license I'm fine with having ``.rst``, but in my opinion we shouldn't rename licenses to ``.rst`` by default.

I'm personally not in favor of these changes as it makes it harder to update the licenses in future if needed, but I'm willing to be overruled.

**Comment by namurphy** [comment]
@astrofrog - Changing the file extension from `.rst` to something else and keeping the same formatting would also be a completely valid fix for the existing license formatting problems.  I had been thinking that ReST formatting was needed for including the licenses as part of a doc build, but I don't see external licenses in the Astropy documentation so I'm guessing we're not constrained by that.  I personally find plain text to be harder to read so I would still vote for `.md` or `.rst`, but honestly anything that fixes the formatting problems would be fine with me!

**Comment by pllim** [comment]
👍 to https://github.com/astropy/astropy/pull/7053#issuecomment-361881231

The less reasons for lawyers to contact us, the better.

**Comment by namurphy** [comment]
I changed the WCSLIB license to the Markdown formatted version of the LGPLv3 that is available on the GNU website since that was readily available.

I would also caution us against being overly cautious, since the formatting fixes I made to the BSD licenses are akin to changing the font from Times New Roman to Helvetica, or moving the license from a text file to a website.  I was very careful to not change any of the text besides updating copyright years.  As long as the text is reproduced faithfully, we are exactly meeting the requirements of the BSD licenses, so I don't think it would be worth the effort to change to a different format.

**Comment by astrofrog** [comment]
I just noticed a lot of these are obsolete, so have opened a PR to remove them: https://github.com/astropy/astropy/pull/7140 - we should merge that then rebase this PR

**Comment by astrofrog** [comment]
Coming back to this - I think a better fix is to rename the licenses that aren't valid rst to omit the rst extension. As mentioned earlier, my main objection is that changing the content of the licenses makes them harder to update (to take @namurphy's analogy, imagine changing a text file into a webpage - if the text file changes, it's a pain to update the website).

**Pull request closed without merging**
