### PR TITLE
Use ctype for an alternate WCS when reading in SIP coefficients

### PR DESCRIPTION
**Pull request by nden**
`WCS._read_sip_kw`  checks for consistent SIP representation in the header. However it checks  `CTYPE` keywords of the primary WCS even if a `key` argument is passed to use an alternate WCS. 
This PR passes the `key` argument to `_read_sip_kw` and checks that `CTYPE`.

### CODE REVIEW

**Comment by pllim** [comment]
Add a change log?

**Comment by nden** [comment]
Change log added.

**Comment by pllim** [comment]
Is a test also needed, or it is already tested by existing tests?

**Comment by MSeifert04** [comment]
I cancelled the OSX build for this PR, it has been pending for 9 hours now.

**Comment by astrofrog** [comment]
@nden - can you move the changelog entry to 1.3? (with ``[ci skip]``)

**Comment by nden** [comment]
Change log moved to 1.3 and PR approved, so merging.

**Pull request merged**
