### PR TITLE
Make sure test collection doesn't crash if there are import errors

### PR DESCRIPTION
**Pull request by astrofrog**
It looks like we now need to specify the ``--doctest-ignore-import-errors`` flag to avoid issues when collecting tests - this is due to a change in https://github.com/astropy/pytest-doctestplus/pull/103/files#diff-ebe8cdb0141ee1407c94011e34737c5dR171-R174 which doesn't add the flag as such (it's a pytest flag) but makes pytest-doctestplus properly take it into account.

@saimn - is this intentional, or should the default still somehow be to skip on import errors? If the fix here is needed, we could use batchpr to automatically update packages that have ``doctest_plus = enabled``.

### CODE REVIEW

**Comment by bsipocz** [comment]
Could we rather have this as a default in pytest-doctestplus and rather opt in into import errors?

**Comment by pllim** [comment]
Tests ran. There is a new error about existing file but at least collection is fine.
```
040     >>> hdu.writeto('test_dask.fits')
UNEXPECTED EXCEPTION: OSError("File 'test_dask.fits' already exists.")
```

**Comment by saimn** [comment]
I saw that too, and pushed a change that should fix it (at least for doctextplus 0.6).

**Comment by bsipocz** [comment]
I think, now I'm more in favour of this (https://github.com/astropy/pytest-doctestplus/pull/108#issuecomment-622180209). After all #10246 seems to be a legit collection of bugs. 

Then we can hope that at some point we'll be able to remove the `--doctest-ignore-import-errors` flag.
Also, I suspect not all doctestplus user needs this as a batchpr, the two others I checked, photutils and astroquery are fine.

**Comment by astrofrog** [comment]
Closing in favor of #10358

**Pull request closed without merging**
