### PR TITLE
Update constant.py to match repr to attributes.

### PR DESCRIPTION
**Pull request by dlenz-bonn**
Rename Error -> Uncertainty and Units -> Unit in the `repr` to match the attributes.
Requested in https://github.com/astropy/astropy/issues/4145

### CODE REVIEW

**Comment by mhvk** [comment]
+1. Note the build failures due to omitting to update the documentation `docs/constants/index.html`. I'll leave it to @embray on whether this needs a changelog entry.

**Comment by pllim** [comment]
It looks like the branch was deleted without merging?

**Comment by dlenz-bonn** [comment]
I messed up the branches, so I created a new pull request, including the changes in the docs. First contribution, please bear with me.

**Comment by pllim** [comment]
@dlenz-bonn , no problem. Can you please link to your new PR as a comment in #4145, so there is a clear cross-reference for reviewers? Thank you for contributing!

**Comment by pllim** [comment]
Ah, never mind. I see the new PR now.

**Comment by embray** [comment]
Next time just let me know--in the vast majority of cases the git issues can be sorted out without creating a new PR.

**Pull request closed without merging**
