### PR TITLE
Move straggling asdf schemas to data dir schemas 

### PR DESCRIPTION
**Pull request by Cadair**
It seems that #8413 and #8337 conflicted with each other in a way that caused issues with loading the asdf schemas. Not really sure why tests didn't catch this.

### CODE REVIEW

**Comment by pllim** [comment]
Good catch. How did you find this?

**Comment by Cadair** [comment]
My tests failed in my dkist package, and I spent almost 2 hours hunting it down lol

**Comment by pllim** [comment]
:scream:

**Comment by pllim** [comment]
Somehow, these two weren't included in the auto schema doc thingy (#8526), maybe that's why it wasn't tested? I can't tell now if they weren't autodoc-ed on purpose or because Dan didn't look in the straggler directory. :woman_shrugging: 

Should we figure out a way to test this to avoid future 2-hr debug blackhole?

**Comment by pllim** [comment]
@saimn might wanna know about this PR, given that he is looking into performance issues with #8526.

**Comment by Cadair** [comment]
I don't understand why there isn't a test using these schemas. I don't have time to look into it today, probably best to merge this and open an issue about making sure it's tested properly.

**Pull request merged**
