### PR TITLE
cosmo: separate out tcmb

### PR DESCRIPTION
**Pull request by nstarman**
Part of #17150
Requires #17151 

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Feature freeze is fast impending. I doubt this is going to make it to v7.0 but we can move the milestone later.

**Comment by nstarman** [comment]
If #17151 gets in, this PR is also very uncontroversial. There's no change to any public API.

**Review by eerovaher — APPROVED** [review]
I don't think I should be reviewing #17150, but I can confirm that this pull request is analogous to #17151, which has already been merged, and it only concerns implementation details, not the public API.

**Comment by nstarman** [comment]
Thanks @eerovaher. Would you be willing to continue reviewing such non-API changing PRs? These are the preliminary steps towards https://github.com/astropy/astropy/issues/17150, but as you point out, are non-cosmological.

**Comment by eerovaher** [comment]
I don't know enough about cosmology to review the public API, but I suppose I can review refactoring implementation details.

**Pull request merged**
