### PR TITLE
Use Python 3.9 for pyinstaller tests

### PR DESCRIPTION
**Pull request by astrofrog**
### Description

As @pllim mentioned in https://github.com/astropy/astropy/pull/12760 - doing this manually instead of backporting https://github.com/astropy/astropy/pull/12760 to see if it works.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Alas, doesn't seem to work. I still see "internal errors". 😿

**Comment by astrofrog** [comment]
Ok clearly this is going to require more investigation, but I don't think it should hold back 5.0.1 - I think it's just a testing thing as opposed to a genuine issue with using astropy in pyinstaller.

**Comment by pllim** [comment]
Also, since I don't use pyinstaller, I agree that this should not hold up 5.0.1. 😸

**Comment by astrofrog** [comment]
Closing in favor of https://github.com/astropy/astropy/pull/12795

**Pull request closed without merging**
