### PR TITLE
Add MCMC sampling to models

### PR DESCRIPTION
**Pull request by karllark**
### Description

This pull request adds MCMC sampling to the modeling package.  It adds `samplers` to the possible solution for fitting.  `Samplers` sample the fitting in comparison to `optimizers` that find the best fit model.  This PR adds the interface to the popular `emcee` package.  Flat priors are supported.  The result of the sampling includes the best fit model, uncertainties, covariance matrix, and the parameter posteriors as astropy.uncertainty distributions.  The full sampler info is included as part of the fit_info.

*In progress PR*

More work needed including tests and documentation.

This is the result of discussion with various people over the last year or more.   In the past, @eteq has expressed interest in contributing to this PR with his work on this topic - especially on how to include more complete support for priors.

### CODE REVIEW

**Comment by karllark** [comment]
All the tests are failing due to the lack of the `emcee` package.  Making astropy depend on this package doesn't seem like the right way to go.  Is there a way to make this package available for the tests while making it an optional dependency for astropy?

**Comment by eteq** [comment]
> All the tests are failing due to the lack of the emcee package. Making astropy depend on this package doesn't seem like the right way to go. Is there a way to make this package available for the tests while making it an optional dependency for astropy?

Yep, you can add a decorator to tests to make them only run if a specific dependency is installed. If you search in the repo for `HAS_SCIPY` or `HAS_MATPLOTLIB` you'll find a bunch of examples of how to implement that in the testing machinery.

**Comment by adrn** [comment]
Hey @karllark -

I suspect you know what I'm going to say, since we've talked about this before :). But, since the last time we chatted, now the context is a bit different because `astropy.modeling` is more stable. In any case, I'm still a bit negative on the idea of merging this into core for a few reasons. Some of my feelings are broader than this PR, and so could probably be discussed elsewhere (fair enough). But I'm happy to be overruled on anything below if there is other consensus. Either way, I don't think this work is wasted, because this certainly belongs either in astropy core, in another package, or in a tutorial, so this is great!

My main objection is something that the class name `EmceeFitter` and the line `optimizer=EmceeSampler` summarize nicely: Pasting this on top of the existing modeling code somewhat perpetuates what I think is confusion about statistics or statistical tools that already seems pretty prevalent in astro. MCMC is not about fitting or optimizing! If all a user wants to do is throw uniform priors on their parameters and get out best fit values and error bars, MCMC is a really bad tool for the job, and I don't think we should be encouraging that. Once you go beyond uniform or simple priors, this quickly starts to feel a lot like a model building language like pymc3 or Stan or tensorflow-probability. So, this triggers me on the broader issue that I really don't want Astropy to turn into a model building language, because there are already fairly good tools for that (which are flexible and extensible and scale well and etc.). 

All of my other comments aside, I do think there could be room in astropy core for easier ways to export astropy models into a way that makes interfacing with more general MCMC samplers (beyond emcee, like HMC in pymc3, or nested sampling like dynesty). But without having to build in explicit support for each sampler. I think the last time we chatted, I said I would write up a tutorial to show how I would combine `astropy.modeling` with pymc3 - I'm sorry that I never delivered on that! I have been using pymc3 a bit more lately, so have more ideas and feelings about that. Anyways, since `astropy.modeling` provides gradient information (I think?), Hamiltonian Monte Carlo methods should be *much* more efficient than Emcee.

So I wonder if, as a first step, we could first write a tutorial that demonstrates how to do combine `astropy.modeling`, pymc3, emcee, and/or dynesty and see if it makes sense to add some more general support for exporting astropy models into a way that makes it easier to interface with these other methods? I suspect that would be useful context for this PR either way.

@dfm may have additional thoughts?

**Comment by karllark** [comment]
> > All the tests are failing due to the lack of the emcee package. Making astropy depend on this package doesn't seem like the right way to go. Is there a way to make this package available for the tests while making it an optional dependency for astropy?
> 
> @karllark - yep, you can add a decorator to tests to make them only run if a specific dependency is installed. If you search in the repo for `HAS_SCIPY` or `HAS_MATPLOTLIB` you'll find a bunch of examples of how to implement that in the testing machinery.

Ok.  I can see how to setup the tests to check if emcee is installed.  But this does not fully solve the issue (at least to me).  How to have the tests setup so that they install emcee so that the new sampler fitter can be tested?  Need to somehow have emcee installed for the testing, but not required for astropy when generally being installed.

**Comment by karllark** [comment]
Or is it as simple as adding emcee to the `[options.extras_require] test =` string in setup.cfg?

**Comment by karllark** [comment]
@adrn - thanks for the insightful comment.  I do appreciate this issue, and I agree there is a need to make it easier to interface astropy models with MCMC samplers.  I find I need such in my research and this attempt is something I've been using.  I do agree that more education/tutorials/etc is desirable to help all better understand and use the results of samplers.  I do think that making it easier to use MCMC samplers is separate from education.

**Comment by bsipocz** [comment]
> Or is it as simple as adding emcee to the `[options.extras_require] test =` string in setup.cfg?

Yes, possibly also for the docs one.
Role of thumb, follow whatever is done for e.g. scipy, add it to that list in setup.cfg, but also if you have code snippets that require doctest, use the same machinery used for scipy in other modules (e.g `doctest-requires`)

**Comment by karllark** [comment]
> My main objection is something that the class name `EmceeFitter` and the line `optimizer=EmceeSampler` summarize nicely

Quick note.  If this PR goes into astropy, I would advocate that the optimizer base class be renamed to something more generic.  I agree that `optimizer=EmceeSampler` is wrong.  Right now, this is done to use the existing machinery.  My thoughts are to see the modeling class have models and different ways to fit them including optimizers and samplers.

**Comment by karllark** [comment]
> Anyways, since `astropy.modeling` provides gradient information (I think?), Hamiltonian Monte Carlo methods should be _much_ more efficient than Emcee

This sounds very exciting.  Anyway I can help?

**Comment by adrn** [comment]
@karllark OK here's a little demo of how I would mash up `astropy.modeling` and pymc3: https://github.com/gist/64b55b17225293ab2d15402f8ff5b09c

This assumes a Gaussian likelihood function, but makes use of the gradients and model evaluation from `astropy.modeling` in the defined theano op so that pymc3 can use the NUTS/HMC sampler. Anyways, this is really just a toy demonstration, but here you can make use of pymc3's implemented distributions (for priors and specifying parameter relationships). The actual implementation is a bit ugly because it requires implementing a custom theano op and etc...which isn't particularly fun or intuitive. 

One thing I could imagine adding support for in astropy.modeling is a more general version of the theano op here that computes the Gaussian log likelihood and gradient...

**Comment by karllark** [comment]
Very interesting @adrn!  I'll look at it in detail next week.  I have definitely stumbled in trying to get theano to work.  Having an interface to theano for astropy models would definitely be useful.

**Comment by pllim** [comment]
Ops, sorry for the double bot post. Hopefully I fixed the bug upstream.

**Comment by karllark** [comment]
> @karllark OK here's a little demo of how I would mash up `astropy.modeling` and pymc3: ~https://gist.github.com/adrn/64b55b17225293ab2d15402f8ff5b09c~
> https://colab.research.google.com/drive/1r-h9WPTtb2or9_ku4IUHyQxyOxLFaXk3?usp=sharing
> 
> This assumes a Gaussian likelihood function, but makes use of the gradients and model evaluation from `astropy.modeling` in the defined theano op so that pymc3 can use the NUTS/HMC sampler. Anyways, this is really just a toy demonstration, but here you can make use of pymc3's implemented distributions (for priors and specifying parameter relationships). The actual implementation is a bit ugly because it requires implementing a custom theano op and etc...which isn't particularly fun or intuitive.
> 
> One thing I could imagine adding support for in astropy.modeling is a more general version of the theano op here that computes the Gaussian log likelihood and gradient...

I finally made the time to look at this demo.  Many thanks.  I can see what you have done and it is partially on the road to what I would envision as a true interface for pymc3 for astropy.modeling.  You use the astropy models, but not the capability to define the "fitter" via astropy.modeling.  One of the great strengths of the astropy.modeling is that it has the models *and* "fitters" setup so that each person doesn't need to learn the specific calling sequence for each "fitter".  "fitter" means optimizer or sampler in this context.  Anyway, my current thoughts.

**Comment by karllark** [comment]
I feel this work may be easier to develop as a separate package.  At a later date, it could go into astropy, but for now I propose to move this work to a separate (astropy affiliated?) package.  @eteq @adrn, ok/make sense?

**Comment by nstarman** [comment]
Hm. This would be very nice.

**Comment by pllim** [comment]
Haha... bot was a little aggressive...

**Comment by pllim** [comment]
I removed the "Close?" label but bot is going to re-add the label again tomorrow and you have 30 days, that is 27 more days than what Ringu gives you.

**Pull request closed without merging**
