### PR TITLE
Backport PR #14566: Disallow the use of quantity input for 'decimalyear' format (v5.0.x)

### PR DESCRIPTION
**Pull request by mhvk**
(cherry picked from commit b40081ff722c5ca0a4ff1578abe4587e44c0eeba)

### Description

This pull request is to backport #14566

### CODE REVIEW

**Comment by mhvk** [comment]
Link check failure unrelated; all optional dependencies failure unrelated (asdf)

@pllim - just to be sure: I can ignore those, right? The one issue is that because of the optional dependencies failure, quite a few other tests didn't run either.

**Comment by pllim** [comment]
Eh... I thought we future-proofed against asdf v3. Did we miss something? I think that should be resolved first so CI can run here.

**Comment by pllim** [comment]
@braingram , any chance you could help fix this asdf failure we see in v5.0.x branch of astropy? Thanks!

*asdf.exceptions.AsdfDeprecationWarning: The property AsdfFile.blocks has been deprecated and will be removed in asdf-3.0. Public use of the block manager is strongly discouraged as there is no stable API*

**Comment by braingram** [comment]
> @braingram , any chance you could help fix this asdf failure we see in v5.0.x branch of astropy? Thanks!
> 
> _asdf.exceptions.AsdfDeprecationWarning: The property AsdfFile.blocks has been deprecated and will be removed in asdf-3.0. Public use of the block manager is strongly discouraged as there is no stable API_

It looks like the v5.0.x branch is still testing the schema which is leading to the error in the CI when run against asdf 2.15 (which introduced the deprecation warning that is causing the failure). Given the extent of the changes in the commit that removed the schema testing I doubt a backport would be preferred:
https://github.com/astropy/astropy/commit/342375723a30f423547d5b48aca5bc4443fc22c4
Removal of the `asdf_schema_root` and `asdf_schema_tests_enabled` lines in `setup.cfg` should remove the error (by removing testing of the schema).
https://github.com/astropy/astropy/commit/342375723a30f423547d5b48aca5bc4443fc22c4#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52L126-L127
That seems like a sensible change to me. However, I'm not familiar with how backporting or changes to older branches are handled in astropy. @plim does removing those two lines from the v5.0.x branch seem like a good option to you? I'd be happy to open a PR but would need to learn what process is used for the non-main branch (so it might be more expedient to have someone else make the changes).

**Comment by pllim** [comment]
@WilliamJamieson , since you are familiar with what is allowed and not allowed for LTS, what do you think of @braingram 's proposal above? Thanks!

**Comment by pllim** [comment]
@braingram , like this? https://github.com/astropy/astropy/pull/14620

**Comment by pllim** [comment]
Just gonna merge this. If things unrelated to asdf fails, I'll deal with it later. I don't think it will since the 5.2.x backport was fine. #yolo

**Pull request merged**
