### PR TITLE
DOC: add a missing doctest-requires directive

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
Extracted from #17053 as suggested by @pllim

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by mhvk — COMMENTED** [review]
I'm still slightly confused why our regular tests passed without this - is it because any time we have `matplotlib` (needed for the figure), we also have `dask` in the environment?

With that, I'm not sure our tests can actually check that this is correct. Don't the pieces after this particular snippet depend on the result? I forget whether they then need their own `doctest-requires` bit (maybe not!?).

**Comment by neutrinoceros** [comment]
This is only run on RTD, where we install `all` optional dependencies, which is why we never see the issue in CI

**Comment by neutrinoceros** [comment]
oh my... now we're seeing other issues on RTD. I can have another look tomorrow but I'm done for today.

**Comment by mhvk** [comment]
> This is only run on RTD, where we install `all` optional dependencies, which is why we never see the issue in CI

I wondered why we do not see issues in our regular `pytest` tests, which run all documentation examples as well...

**Comment by pllim** [comment]
RTD does not run doctest though. It just builds the HTML. 🤔

**Comment by pllim** [comment]
`NameError: name 'model_fit' is not defined`

I think other blocks might also need the same `doctest-requires` as they might be a continuation of the affected code.

**Comment by mhvk** [comment]
> RTD does not run doctest though. It just builds the HTML. 🤔

Well, it does run any that are also `.. plot` directives...

I think I managed to confuse everyone about as much as I'm confused myself!

**Comment by pllim** [comment]
I thought things in plot directive are not doctest-ed? Now I am confused... 🤯 😆

**Comment by pllim** [comment]
Also I don't think we can do `.. plot` and then `.. doctest-stuff` in the same block. You would have to use other forms of directive mentioned in https://github.com/scientific-python/pytest-doctestplus?tab=readme-ov-file#doctest-dependencies

**Comment by mhvk** [comment]
If the `.. plot` are not doctested, then I think this PR is not necessary - things should be solved by simply including all dependencies for docs builds.

**Comment by neutrinoceros** [comment]
Thank you both for your additional insight ! As of my current understanding this is indeed unnecessary (if valid at all), so let's close it !

**Comment by pllim** [comment]
Okay looks like doctest is actually run even when within plot directive. As seen in https://github.com/astropy/astropy/pull/17069

```
182     >>> print(1)
Expected:
    2
Got:
    1
```

But also indeed this patch is unnecessary because the requires is already defined here:

https://github.com/astropy/astropy/blob/5c7c9dda7fcf99eb38952f7944645b8879a39531/pyproject.toml#L243

**Pull request closed without merging**
