### PR TITLE
Avoid errors during implicit type conversion

### PR DESCRIPTION
**Pull request by astrofrog**
Rebased version of https://github.com/astropy/astropy/pull/4783 with additional changes for compressed FITS files.

While this ideally needs regression tests, I don't have time in the immediate future to prepare example files for this. Does anyone else have time to help?

### CODE REVIEW

**Comment by pllim** [comment]
Huh. The first commit says "unrecognized author".

**Comment by astrofrog** [comment]
@mittimithai - what email address do you currently have registered with GitHub?

**Comment by astrofrog** [comment]
This is now ready for review/merging

@embray - if you have a chance to double check this, that would be great - thanks!

**Comment by embray** [comment]
Fine for me.

**Comment by mittimithai** [comment]
Apologies for dropping the ball, I forgot about this.
Looks like the changes are in now?

**Comment by pllim** [comment]
@mittimithai -- yes.

**Pull request merged**
