### PR TITLE
Fixed color_cycle warning

### LINKED ISSUE #4644: matplotlib axes.color_cycle deprecated
Building sphinx, there are numerous warnings that

```
/usr/lib/python2.7/dist-packages/matplotlib/__init__.py:874: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
```

I think this arises from https://github.com/astropy/astropy/blob/master/astropy/visualization/mpl_style.py#L64, but am not sure whether we can issues with older versions of matplotlib if we update.

### PR DESCRIPTION
**Pull request by stbnps**
UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.

Fixes #4644

### CODE REVIEW

**Comment by pllim** [comment]
Travis has Sphinx warnings:
```python
/home/travis/build/astropy/astropy/docs/visualization/index.rst:1: WARNING: py:obj reference target not found: astropy.visualization.cycler

/home/travis/build/astropy/astropy/docs/visualization/index.rst:1: WARNING: py:obj reference target not found: Cycler

<autosummary>:None: WARNING: toctree contains reference to nonexisting document u'api/astropy.visualization.cycler'
```

**Comment by stbnps** [comment]
@pllim I know. I'm researching on the topic.

It seems astropy generates documentation for imported modules.
Since we are using Cycler in the visualization module, it tries to generate docs for it.
This behavior was discussed in [this issue](https://github.com/sphinx-doc/sphinx/issues/1061#issuecomment-83660089) where @embray claims that a proposed fix (for not generating documentation for imported modules) breaks astropy.

Does astropy have any special way of omitting imported modules when generating docs?

Thanks!

**Comment by mhvk** [comment]
I think this would be better done by defining the dictionary completely for the most recent version of matplotlib, and then simply correcting specific items if an older version is used.

**Comment by stbnps** [comment]
The cycler module was created last summer so people that have older versions of matplotlib may not have it.

If we really want to support older versions of matplotlib and keep the code clean an alternative approach would be to only set the desired property inside the version checking if.

**Comment by mhvk** [comment]
Yes, this is what I had in mind -- looks much better. Should there also be a test for the presence of `cycler`? If it is not present (python2??), then one obviously still is better off with using the old path (and getting a deprecation warning rather than an import error).

**Comment by stbnps** [comment]
Cycler is now a dependency of matplotlib so most users having matplotlib >= 1.5 should have cycler.
It may be a good idea to check it just in case.

**Comment by pllim** [comment]
Hmm. This was going somewhere but then closed. What happened?

**Comment by larrybradley** [comment]
@stbnps  Why did you close this PR?  Did it not suppress the `Sphinx` warnings?

**Comment by mhvk** [comment]
I thought we should get something like this in, so build on it in #5569 (it includes a squashed commit from this PR, so @stbnps still gets credit).

**Pull request closed without merging**
