### PR TITLE
fix derivative in example

### LINKED ISSUE #9630: Incorrect derivative in Defining New Model Classes documentation
Hi, maybe I am missing something, but I believe the 'Defining New Model Classes' example (https://docs.astropy.org/en/stable/modeling/new.html) in the documentation has the incorrect derivatives for the 1DGaussian function. This comes under the section 'A step by step definition of a 1-D Gaussian model'.

 For the Gaussian defined as:

amplitude * np.exp((-(1 / (2. * stddev**2)) * (x - mean)**2))

The derivatives should be:

d_amplitude = np.exp((-(1 / (2.*****stddev**2)) * (x - mean)**2))
d_mean = (amplitude *
              np.exp((-(1 / (2.*stddev**2)) * (x - mean)**2)) *
              (x - mean) / (stddev**2))
d_stddev = (amplitude *
                np.exp((-(1 / (2.* stddev**2)) * (x - mean)**2)) *
                ((x - mean)**2) / (stddev**3))

In the online example, the factor of 2 multiplying stddev inside the exponential is missing - for all derivatives. And the factor of two multiplying the amplitude (in d_mean and d_stddev) should not be there. Online version is:

d_amplitude = np.exp((-(1 / (stddev**2)) * (x - mean)**2))

d_mean = (2 * amplitude *
              np.exp((-(1 / (stddev**2)) * (x - mean)**2)) *
              (x - mean) / (stddev**2))

d_stddev = (2 * amplitude *
                np.exp((-(1 / (stddev**2)) * (x - mean)**2)) *
                ((x - mean)**2) / (stddev**3))

### LINKED ISSUE #9638: Documentation bug: Fitting Models to Data last link is circular
### Description

The last link on the "Fitting Models to Data" doc page links back to the same page.
https://docs.astropy.org/en/latest/modeling/fitting.html

### PR DESCRIPTION
**Pull request by nden**
Fixes #9630
Fixes #9638

### CODE REVIEW

**Comment by nden** [comment]
@bsipocz Please change the milestone if necessary

**Comment by pllim** [comment]
cc  @Richardjmorton

**Comment by nden** [comment]
If anyone is available to review this PR it is ready to be merged.

**Comment by bsipocz** [comment]
Thanks @nden!

**Pull request merged**
