### PR TITLE
Use SVG icons for CI badges and change from pypip.in to shields.io

### PR DESCRIPTION
**Pull request by astrofrog**
Looks like pypip.in no longer works: https://github.com/badges/pypipins/issues/37

### CODE REVIEW

**Comment by astrofrog** [comment]
I opened this PR from GitHub and didn't realize it would create the branch in the main repo instead of in my fork... Sorry!

**Comment by mwcraig** [comment]
If this is merged should #3695 be closed (it is partially about the pypi badges)?

**Comment by astrofrog** [comment]
Should be uncontroversial, so will merge now.

**Comment by astrofrog** [comment]
Don't think #3695 should be closed, it's more about gitter.

**Pull request merged**
