### PR TITLE
Upgrade wcslib to 5.x (using wcslib for SIP)

### PR DESCRIPTION
**Pull request by mdboom**
This is now successfully performing the SIP calculations in wcslib and the results match the old results.

There are still some things missing:
- [ ] wcslib doesn't output polynomial header keywords (yet) so we can't round trip SIP anymore (that's a regression)
- [ ] There is no API to access and edit the polynomial coefficients (as there was in astropy prior to this change).  That will have to be rebuilt on top of wcslib.
- [x] Copying wcslib objects doesn't copy the distortions correctly (I think -- now having doubts)
- [x] Somewhat related to the above, calling `set` multiple times will erase distortion coefficients (possibly TPV only)

Despite those shortcomings, I think this may be far enough along for @nden to test this in the Hubble pipeline...

### CODE REVIEW

**Comment by olebole** [comment]
Since this now superceded #3751: Is this one planned for v1.1.0?

**Comment by mdboom** [comment]
@olebole: Tentatively planned for 1.1, yes.  That depends on whether the remaining functionality gets into wcslib by then or not.

**Comment by mdboom** [comment]
It seems there's still an issue in the inverse transform of SIP here.  Haven't got to the bottom of it yet...

**Comment by eteq** [comment]
@mdboom - I'm still not able to get DECam images (It uses TPV, and come from a major NOAO facility instrument) to work correctly with this.  Steps to reproduce:

1. Go to http://www.portal-nvo.noao.edu/search/query and select "CTIO 4m + DECam imager" under Telescope&Instrument, and check "calibrated images" for "Mosaic, NEWFIRM, and DECam".  If you want exactly the file I tested on, you'll also want to choose Program number="2012B-0001", but I don't think that actually matters
2. Hit "search", and then find the first result the search returns that has "Product"="image".  Hit "retreive" on that row and it will download a DECam image.
3. You should see this with that image:
```
>>> f = fits.open('c4d_130831_235507_ooi_g_d3.fits.fz')
>>> w = wcs.WCS(f[1].header)
>>> ra, dec = w.all_pix2world([0,10, 15],[0,10, 20],0)
>>> ra
array([ 301.2065433,  301.2065433,  301.2065433])
>>> dec
array([-50.93399553, -50.93399553, -50.93399553])
```
which is clearly wrong: they should be different ra/dec.

4. But *also*, I see this:
```
>>> ra, dec = w.wcs_pix2world([0,10, 15],[0,10, 20],0)
>>> ra
array([ 300.49796386,  300.49908106,  300.50020568])
>>> dec
array([-49.95258804, -49.95332569, -49.95369924])
```
which looks like it *is* correct - and the only difference is `wcs_pix2world` instead of `all_pix2world`.

So that suggests the problem is in the layers after wcslib - that's weird to me because I thought the point of this PR was that wcslib now supports TPV so nothing else should be needed (but I admit the internals of this package aren't too familiar to me).

**Comment by mdboom** [comment]
@eteq: Thanks for the info.  It seems the issue is that when `set` is called multiple times on a `WCS` object (as it is as a matter of course as values are updated etc.) the distortion coefficient values are erased.  And when you have coefficients of all zeros, the entire linear transformation disappears, which is why you're seeing all the same values in that case.  I'll take this up with the wcslib author.

**Comment by eteq** [comment]
@mdboom - Ah, ok, that explains it. If it looks like it's going to take a while to address this in wcslib, perhaps we should add a workaround at the astropy level? 

Also, what do you think is the timeline for the rest of this?  The two unchecked items in your description are regressions so presumably we don't want that.  Do you want to get those addressed before reviewing/merging this PR, or are you thinking to do that separately later (presumably before 1.1)

**Comment by mdboom** [comment]
> @mdboom - Ah, ok, that explains it. If it looks like it's going to take a while to address this in wcslib, perhaps we should add a workaround at the astropy level?

I'm not certain a less-effort workaround exists, though I am almost inclined to rewrite all this so `SIP` remains *not* handled by wcslib by pre-filtering the FITS keywords...  That may be an easier route to avoiding regressions.  But a non-trivial amount of work, nonetheless.

> Also, what do you think is the timeline for the rest of this? The two unchecked items in your description are regressions so presumably we don't want that. Do you want to get those addressed before reviewing/merging this PR, or are you thinking to do that separately later (presumably before 1.1)

We definitely shouldn't merge this PR with those changes -- these are major regressions, and it's far preferable to remain at status quo.  Not sure on timeline -- this has all turned into a large chunk of completely unexpected work here.  Other than for the users who would like to get TPV in sooner, I think it's best to be conservative and just get this in when it's done, even if that means missing 1.1.

**Comment by eteq** [comment]
@mdboom - should this be closed now that #3878 is in?  Or should it be left open as a reminder to try to get the SIP stuff working with wcslib sometime down the road?

**Comment by mdboom** [comment]
I was planning on leaving it open -- eventually we should be using this approach, but there are still some important missing pieces...

**Comment by bsipocz** [comment]
@nden - I wonder whether we should close this, or there are still relevant pieces in this PR that need to be merged?

**Comment by bsipocz** [comment]
Closing this as a PR and open an issue to remind ourselves to the SIP issue.

**Comment by nden** [comment]
@bsipocz  My impression is that a lot of the work needed for #6030 is actually in this PR. Or am I wrong?

**Comment by bsipocz** [comment]
@nden - That is very possible, I'm not familiar enough with wcs to see into the details. However this PR was opened before github allowed maintainers to overtake abandoned PRs and had tons of conflicts. Thus even if someone takes the work over from here, they need to open a new PR.

**Comment by nden** [comment]
Keep this open as a reference.

**Comment by bsipocz** [comment]
@nden - As a reference I would suggest to open an issue instead, as this PR was opened before github allowed maintainers to take over (thus any work on this needs to be done in a new PR anywy). I've tried to rebase this without the cextern/wcslib updates, but ended up with horrible test failures, so this definitely need to be done by someone knowing the wcs module.

**Comment by nden** [comment]
@bsipocz I don't expect this work to be done by someone who does not understand astropy.wcs, at least not without some help. I keep it open mostly for my own reference. Unfortunately working on this is not high on my priorities list. I could instead create a branch in my own repo with Mike's work and then we can close but no one who understands astropy.wcs will be able to see it. I can't think why an issue would be better. What kind of issue do you have in mind?

**Comment by bsipocz** [comment]
@nden - I just had the "close stale PRs" [e-mail](https://groups.google.com/d/topic/astropy-dev/Lv-rRQc6giM/discussion) of astropy-dev in mind, that we could aim to keep issues open as reminders rather than PRs that can't be finished in their current form. However it's fine to keep this open if you find it more useful as a reminder than either #6030 or #6371. (I don't think that the auto close will get to this any time soon, though).

**Pull request closed without merging**
