### PR TITLE
BUG: declare `np.cumulative_prod` and `np.cumulative_sum` as subclass-safe and test them (fix incompatibility with NumPy 2.1)

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description

[example logs](https://github.com/astropy/astropy/actions/runs/9772796551/job/26977807893)
xref: https://github.com/numpy/numpy/pull/26724

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
I don't think we have been issuing change logs for compatibility with unreleased numpy. This is future-proofing and should not affect typical users.

**Comment by neutrinoceros** [comment]
Ah, but #16640 was merged with changelog fragments included. Should I remove them ?

**Comment by mhvk** [comment]
Oops, how did I miss that? @pllim is right, we normally do not add changelog entries for something where we ensure we *remain* compatible with numpy.

**Comment by pllim** [comment]
> Should I remove them ?

I would say yes but @mhvk did approve it, so let's wait and see what he says. Thanks!

**Comment by neutrinoceros** [comment]
I removed both fragments from this PR and opened #16665

**Review by mhvk — APPROVED** [review]
Thanks, looks all good!

**Pull request merged**
