### PR TITLE
Fix format conversion in the fast writer with plain format strings ('.2f')

### PR DESCRIPTION
**Pull request by saimn**
Plain format strings (`'.2f'`) were not supported by the fast writer, whereas it is by the basic writer: http://docs.astropy.org/en/latest/table/construct_table.html#format-specifier

With the fast writer I get this error:
```
astropy/io/ascii/cparser.pyx in astropy.io.ascii.cparser.FastWriter.write (astropy/io/ascii/cparser.c:18549)()

astropy/io/ascii/cparser.pyx in astropy.io.ascii.cparser.auto_format_func (astropy/io/ascii/cparser.c:20888)()

ValueError: Unable to parse format string .1f
```

The basic writer use `astropy.table.pprint._auto_format_func` to try the different formatting syntaxes. And the fast writer was reimplementing this in `cparser.pyx` (`auto_format_func`). The comment on these function is not so clear about why the function is duplicated (*Mimics pprint._auto_format_func for non-numpy values.*), and the function does less than `astropy.table.pprint._auto_format_func` so this commit just use this function. But maybe there is a good reason for this duplication ?

cc @taldcroft

### CODE REVIEW

**Comment by saimn** [comment]
Hum, the documentation build failed, it seems to be due to `../CHANGES.rst:350: WARNING: py:obj reference target not found: fits2bitmap`.

**Comment by bsipocz** [comment]
Thanks @saimn. #4518 should fix it.

**Comment by saimn** [comment]
Taking another look at this, `auto_format_func` was introduced in https://github.com/astropy/astropy/commit/d4cbc702eee8b5c23fe4811bf47811f7bfed6529 (cc @mdmueller )

The fact that it is defined in `cparser.pyx` may provide some speedup (?), but duplicating the code is problematic because it may have a different behavior as `pprint._auto_format_func` (which is tha case in this issue). So, if speed matters here, another option could be to replace  `pprint._auto_format_func` with `auto_format_func` from `cparser.pyx` (with a fix for plain format strings) ?

**Comment by saimn** [comment]
ping @taldcroft ?

**Comment by taldcroft** [comment]
@saimn - sorry for the delay, I'll try to have a look soon.

**Comment by taldcroft** [comment]
@saimn - I believe that speed was a driver in writing the duplicate code, although just offhand it doesn't seem like much of that code would really Cythonize effectively so I'm not sure.  

If you look at http://astropy.readthedocs.org/en/latest/io/ascii/fast_ascii_io.html#writing and the referenced notebook, you can see some performance testing that was done.  You could try running this notebook using current master and then with your branch to see what changes (if anything) in the plots.

**Comment by saimn** [comment]
@taldcroft : results are here https://gist.github.com/saimn/f143251187f7e95fe57f
I don't really see a difference. At the end of each notebook I added a basic timeit for each function, the python looks actually a bit faster but this should negligible when writing a real table. And the format functions are stored in a cache in `pprint._format_funcs` so `auto_format_func` is not called so often.

**Comment by taldcroft** [comment]
@saimn - awesome!  I love patches that remove unnecessary code and improve things along the way!

All this needs now is a bug fix changelog entry for 1.0.9.  (If you could try cherry picking this PR onto the 1.0.x branch to make sure there is no conflict that would be good).

**Comment by saimn** [comment]
@taldcroft : done, and rebased on master to fix changelog conflicts. It also applies cleanly on 1.0.x and tests pass.

**Comment by saimn** [comment]
Nothing bad, the coverage build failed because of some error with coveralls.io: 

    Submitting coverage to coveralls.io...
    Coverage submitted! 
    Failure to submit data. Response [524]: <!DOCTYPE html> ...

**Comment by taldcroft** [comment]
Thanks @saimn !

**Comment by eteq** [comment]
@saimn @taldcroft - drat.  It looks like this fix doesn't work in py 2.6, revealed when I packported this to 1.0.x and 1.1.x: https://travis-ci.org/astropy/astropy/jobs/112989010 and https://travis-ci.org/astropy/astropy/jobs/112988557

Any thoughts on how to fix this?  Or should we instead re-assign this to v1.2 and just accept it in the 1.1.x and 1.0.x branches?

**Comment by taldcroft** [comment]
@eteq - I would guess that if you change `{:0.1f}` to `{0:0.1f}` in the test then it will pass in Py2.6.

**Comment by saimn** [comment]
@eteq - Sorry about that, I forgot about the need for py2.6 compatibility for old versions. @taldcroft is right, replacing the format string with `{0:0.1f}` should fix it. I can make a PR for this later today if it helps.

**Pull request merged**
