### PR TITLE
Make python setup.py less verbose

### LINKED ISSUE #7511: Output log in circleci too long to read in browser
e.g. https://circleci.com/gh/dstansby/astropy/46?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The output log is *really* long, so long that you have to download it to get to the end. There must be a ~~verbose~~ quiet option that can be thrown in there somewhere to shorten the log.

### PR DESCRIPTION
**Pull request by dstansby**
Should fix #7511. This disables `stdout` when the temporary copy of astropy is compiled and installed, which saves a lot of useless lines from the test output. This leaves `stderr` alone, so compiler warnings etc. still show up during the installation.

### CODE REVIEW

**Comment by dstansby** [comment]
Doing `python setup.py test --verbose-install` now brings back the previous behavior that printed all the installation details to stdout.

**Comment by pllim** [comment]
I definitely like the cleaner log! But I don't understand why the error I encountered in #7500 and #7515 is happening now even without `-t` option.

**Comment by pllim** [comment]
Update: That failure seems transient. It is gone now.

**Comment by bsipocz** [comment]
All green now, with 2 approvals, so I'm merging.

Thanks @dstansby, this is a nice improvement indeed.

**Pull request merged**
