### PR TITLE
Fits section dtype

### PR DESCRIPTION
**Pull request by anntzer**
This builds on top of #3148 to support specification of FITS section indexing return dtype.

### CODE REVIEW

**Comment by embray** [comment]
I don't see what this adds-- the `dtype` attribute associated with a Section object doesn't actually seem to have any impact on the dtype of the returned data.  I can see a use for a `.dtype` attribute but it would probably be best left as a property returning the dtype of data that would be returned.  I think HDUs in general would benefit from such a `.dtype` attribute, in which case `Section.dtype` could just return `self.hdu.dtype`.

**Comment by anntzer** [comment]
Good catch; I actually intended to cast the result of `__getitem__` using `self.dtype` (so that it actually impacts the returned data) but I wrote the wrong tests for that.  I need to fix that...
I have no opinion whether `dtype` should be an attribute or a property, as long as I can change it with `astype`.

PS: Squeezing in an additional feature, the `shape` property, as well.

**Comment by embray** [comment]
But the `.section` object is just in interface for returning slices of the data.  It doesn't have a shape.  The only thing that has a shape is the returned slice which is already a Numpy array.  Likewise I don't see much value in adding an `astype` when that can just be called directly on the Numpy array returned for a slice (there's no less overhead one way or the other).  

In other words, since I just see `.section` as an alternative slicing mechanism for `.data` (and something that should go away eventually anyways) I don't want to clutter it up with additional interfaces beyond the `[]` notation.

**Comment by anntzer** [comment]
My use case is that I want to be able to pass a FITS section instead of an ndarray in cases where the data is too large to be loaded at once; in order to do so I need to "duck-type" the section so that it looks as much as possible like an ndarray.  In practice, `.astype` and `.shape` is what the rest of my code currently uses (regardless of whether I pass an ndarray or a section) before selecting some subslices, so that's what I implemented).
I actually have trouble understanding your last sentence about `.data` specifically representing FITS data rather than a plain ndarray -- do you mean that in fact, you expect `.data` to be a loaded-on-demand array like `.section` currently is?

**Comment by embray** [comment]
> do you mean that in fact, you expect .data to be a loaded-on-demand array like .section currently is?

Exactly, at least in cases where it makes sense to (likely with a flag to enable/disable this functionality).  I'm -1 on anything that involves making Section ducktype as an ndarray.

**Comment by anntzer** [comment]
OK, but doesn't that just mean that you want to remove `.section` and have `.data` return either (what is currently known as) a Section or a real ndarray depending on that flag?

**Comment by embray** [comment]
Neither, really.  I envision a more comprehensive data structure that can represent a FITS array.  This would also include knobs for all the awkward things like turning scaling on/off that are currently handled further away from the data itself.  

By analogy, the plan for table HDUs is to switch them over to using the Astropy `Table` class for their `.data` attribute (or at least a subclass thereof specifically for FITS tables).  A similar structure (probably based on NDData) would be used for images/gridded data.

**Pull request closed without merging**
