### PR TITLE
Revert "Fixed incorrect string representation of floats in Cards"

### PR DESCRIPTION
**Pull request by pllim**
Reverts astropy/astropy#14508 cc @kYwzor

Have to also re-open:

* https://github.com/astropy/astropy/issues/5449
* https://github.com/astropy/astropy/issues/14507

### CODE REVIEW

**Review by keflavich — APPROVED** [review]
I approve, but would be happy to wait for feedback from @saimn and @kYwzor if that's preferred.

**Comment by kYwzor** [comment]
I've never used `wcs` so I'm not familiar with it at all. I dug around a bit, the issue seems to originate here.
https://github.com/astropy/astropy/blob/386b52e980c8fa17e8838bb02a2cf60976f9db73/astropy/wcs/wcs.py#L2910

After this line, `header_string` contains `CDELT1  =        1288.21496879` instead of the expected  `CDELT1  =        1288.2149687900003`. In other words, `self.wcs.to_header` is somehow internally doing the exact same mistake `fits.io` was doing before the PR: that is, `Wcsprm.to_header` is not representing the float value exactly as it was set. This later causes issues with comparisons.

As I understand it, `Wcsprm.to_header` actually calls a wrapper function which in turn calls the `wcshdo` C function.

https://github.com/astropy/astropy/blob/7f69f0211b50bff7ea9cc57771cef424ae1268b4/cextern/wcslib/C/wcshdr.c#L494

This function contains logic for formatting which is likely causing the issue, but I'm not familiar enough with it to say more than this.

Similarly, `Wcsprm.compare` also calls a wrapper function which in turn calls the `wcscompare` C function.

https://github.com/astropy/astropy/blob/7f69f0211b50bff7ea9cc57771cef424ae1268b4/cextern/wcslib/C/wcs.c#L1459

Again, not really familiar with this code base, so I can't give an opinion on this
______

In sum it seems to me that `io.fits` and `wcs` were both inaccurately representing floats, but because the inaccuracies matched perfectly, there was no issue. Now that `io.fits` was changed, there's a mismatch because `wcs` was expecting that inaccuracy.

I would suggest that the issue is instead fixed in the `wcshdo` or `wcscompare` functions, if possible. If that is not possible then of course let's revert the PR and think how we can better approach it.

**Comment by dhomeier** [comment]
I think whatever was broken in radio-astro-tools/spectral-cube#854 is unlikely to be related to the `fits.Card` part of the processing; see also https://github.com/astropy/astropy/pull/14508#issuecomment-1466681283.

**Comment by pllim** [comment]
Okay, thanks for investigating, @dhomeier ! Closing.

**Pull request closed without merging**
