### PR TITLE
Added doc on comments under Writing Tables

### PR DESCRIPTION
**Pull request by ritwickdsouza**
References #5416

### CODE REVIEW

**Comment by pllim** [comment]
There are some Sphinx formatting errors. And the code example is not quite in the correct order.

**Comment by ritwickdsouza** [comment]
@pllim I fixed the order of the example code. But I'm getting a AttributeError :/. Is there anyway to perform these tests offline?

**Comment by pllim** [comment]
Re: Offline test. Yes, it is possible. You just need to run the particular Travis command you are interested in locally.

**Comment by bsipocz** [comment]
@ritwickdsouza - You can e.g. run ``python setup.py test``. 

Also the developer guideline is a nice bedtime read: http://docs.astropy.org/en/latest/index.html#developer-documentation, this one is all about testing: http://docs.astropy.org/en/latest/development/testguide.html

**Comment by ritwickdsouza** [comment]
@taldcroft @hamogu Any suggested changes ?

**Comment by taldcroft** [comment]
@ritwickdsouza - I think you can do the same with less setup in a more prominent place, namely the initial example of writing in the Getting Started section.  Just update the example to:
```
>>> import numpy as np
>>> from astropy.table import Table, Column, MaskedColumn
>>> x = np.array([1, 2, 3])
>>> y = x ** 2
>>> data = Table([x, y], names=['x', 'y'])
>>> data.meta['comments'] = ['First line of comment',
...                          'Second line of comment']
>>> ascii.write(data, 'values.dat')
```
Then replace "The `values.dat` file will then contain:" with "The `values.dat` file will then contain the following.  Note the table comment lines which result from setting `data.meta['comments']` with a list of strings (for more detail see the `comment` parameter in the :ref:`io_ascii_write_parameters` section).".

**Comment by taldcroft** [comment]
Also this is failing doctest:
```
=================================== FAILURES ===================================
______________________ [doctest] docs/io/ascii/write.rst _______________________
147 To write a comment to ASCII file the following should be done.
148 
149     >>> from astropy.io import ascii
150     >>> from astropy.table import Table
151     >>> data = Table({'a': [1, 2, 3],
152     ...               'b': [4.0, 5.0, 6.0]},
153     ...              names=['a', 'b'])
154     >>> data.meta['comments'] = ['First line of comment',
155     ...                          'Second line of comment']
156     >>> ascii.write(data)
Differences (unified diff with -expected +actual):
    @@ -1,4 +1,4 @@
    -#First line of comment
    -#Second line of comment
    +# First line of comment
    +# Second line of comment
     a b
     1 4.0
```

**Comment by ritwickdsouza** [comment]
@taldcroft I will change the example as you said. And the failing doctest was fixed in my last commit.

**Comment by taldcroft** [comment]
@ritwickdsouza - at this point you probably want to just drop the previous commits and effectively start over.  You can do this easily with:
```
git branch meta-comments-instructions-bak  # make a backup
git reset --hard master
```
Then make the doc updates and commit, and finally
```
git push -f origin meta-comments-instructions
```

**Comment by ritwickdsouza** [comment]
@taldcroft Please review.

**Comment by taldcroft** [comment]
> @taldcroft Please review.

@ritwickdsouza - I did review and made the suggestions to move the example into Getting Started and squash down to a single commit.  Those suggestions still stand.

**Comment by taldcroft** [comment]
@ritwickdsouza - sorry, just noticed that you did the squash already.

**Comment by ritwickdsouza** [comment]
@taldcroft My bad. Forgot to move it to Getting Started.

**Comment by taldcroft** [comment]
@ritwickdsouza - looks like you did not include the second part of my suggestion to add an explanatory sentence:
> Then replace "The values.dat file will then contain:" with "The values.dat file will then contain the following. Note the table comment lines which result from setting data.meta['comments'] with a list of strings (for more detail see the comment parameter in the :ref:io_ascii_write_parameters section).".

**Comment by taldcroft** [comment]
@ritwickdsouza - the new change is slightly different from what I said and contains a Sphinx error in the reference that is causing a sphinx docs fail.  Please build docs locally to ensure that it is correct before pushing.

**Pull request closed without merging**
