### PR TITLE
DOC: Update coordinates doctest result

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address doctest failure in remote data cron job that I can reproduce locally. Example log: https://travis-ci.org/github/astropy/astropy/jobs/727302683

```
________________________ [doctest] performance.inc.rst _________________________
097 
098    >>> # transform with interpolating astrometric values
099    >>> t0 = perf_counter()
100    >>> with erfa_astrom.set(ErfaAstromInterpolator(300 * u.s)): # doctest:+REMOTE_DATA
101    ...     crab_altaz_interpolated = crab.transform_to(frame)  # doctest:+IGNORE_WARNINGS +REMOTE_DATA
102    >>> print(f'Transformation took {perf_counter() - t0:.2f} s')  # doctest:+IGNORE_OUTPUT
103    Transformation took 0.03 s
104 
105    >>> err = crab_altaz.separation(crab_altaz_interpolated)  # doctest:+IGNORE_WARNINGS +REMOTE_DATA
106    >>> print(f'Mean error of interpolation: {err.to(u.microarcsecond).mean():.4f}')  # doctest:+ELLIPSIS +REMOTE_DATA
Expected:
    Mean error of interpolation: 0.0167 uarcsec
Got:
    Mean error of interpolation: 0.0198 uarcsec
.../docs/coordinates/performance.inc.rst:106: DocTestFailure
```

Local run:

```python
>>> from astropy.coordinates import SkyCoord, EarthLocation, AltAz 
>>> from astropy.coordinates.erfa_astrom import erfa_astrom, ErfaAstromInterpolator 
>>> from astropy.time import Time 
>>> import numpy as np 
>>> import astropy.units as u
>>> obstime = Time('2010-01-01T20:00') + np.linspace(0, 6, 10000) * u.hour 
>>> location = location = EarthLocation(lon=-17.89 * u.deg, lat=28.76 * u.deg, height=2200 * u.m) 
>>> frame = AltAz(obstime=obstime, location=location) 
>>> crab = SkyCoord(ra='05h34m31.94s', dec='22d00m52.2s')                                
>>> crab_altaz = crab.transform_to(frame)                                                       
>>> with erfa_astrom.set(ErfaAstromInterpolator(300 * u.s)): 
...     crab_altaz_interpolated = crab.transform_to(frame) 
>>> err = crab_altaz.separation(crab_altaz_interpolated)                                        
>>> print(f'Mean error of interpolation: {err.to(u.microarcsecond).mean():.4f}')                
Mean error of interpolation: 0.0198 uarcsec
```

This example was last changed in #10647 by @MaxNoe .

### CODE REVIEW

**Comment by MaxNoe** [comment]
@pllim I forgot the ellipsis in the output. 

You could replace the `0.xxx` with `0...` that should make sure it is still in the sub-microarcsecond range but not care for the exact value.

**Comment by pllim** [comment]
@MaxNoe , so we don't care if the value changes? Why did it change?

**Comment by MaxNoe** [comment]
I don't know why the exact value changed, but it is dependent on remote data, so maybe the IERS data changed slightly?

**Comment by StuartLittlefair** [comment]
Odd that the number changed - I'd be surprised if there was a change in the IERS data for 2010. Still, I agree with @MaxNoe that we don't really care what the actual value is as long as it's less than a micro-arcsecond.

**Review by StuartLittlefair — APPROVED** [review]

**Comment by pllim** [comment]
Remote data failure is unrelated. If you think this is good to go, feel free to merge. Thanks!

**Comment by StuartLittlefair** [comment]
Thanks @pllim

**Pull request merged**
