### PR TITLE
Add logos to badges in readme

### PR DESCRIPTION
**Pull request by larrybradley**
Viewable here: https://github.com/larrybradley/astropy/tree/readme-badge

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @larrybradley!

**Comment by pllim** [comment]
Wait, what's wrong with the existing badges? Now that I look at `master`, Travis and CircleCI badges are shown as such. Is it just me?

badges

**Comment by bsipocz** [comment]
Interesting. The suggestions in Larry's link above looked much better than the ones we had, thus the merge

**Comment by pllim** [comment]
Larry and I discussed this offline. We think the service is being flaky upstream currently. We'll wait and see. If it continues to be flaky, we might consider a revert.

**Comment by larrybradley** [comment]
The badges work, e.g., https://img.shields.io/travis/astropy/astropy/master?logo=travis%20ci&logoColor=white&label=Travis%20CI
but the service was slow today at times.  It worked fine last night.

**Comment by larrybradley** [comment]
It's working again:

Screen Shot 2020-04-02 at 12 00 12 PM

**Pull request merged**
