### PR TITLE
Removing deprecated code from table

### PR DESCRIPTION
**Pull request by bsipocz**
This PR removes code that was deprecated in 0.4 and 1.0:
 * ``data`` property of Row
 * functions ``join()``, ``hstack()``, ``vstack()`` and ``get_groups()`` from ``table.np_utils``

### CODE REVIEW

**Comment by mhvk** [comment]
The failure is just the OS build timing out. I think even by my new APE standards these have had warnings for long enough, so happy to remove!
@taldcroft - last look? I'll merge tomorrow otherwise.

**Comment by bsipocz** [comment]
@mhvk - There's much more stuff for possible removal that were deprecated in later releases, but I've thought it's better to wait for an agreement on the APE for those.

**Comment by mhvk** [comment]
As promised, merging now.  Thanks, @bsipocz

**Comment by taldcroft** [comment]
Belated :+1:, thanks.

**Pull request merged**
