### PR TITLE
sigma_clip expand the dimensions if axis is negative

### PR DESCRIPTION
**Pull request by MSeifert04**
Negative axis parameters don't play well with the current version of `sigma_clip`:

```
from astropy.stats import sigma_clip
import numpy as np
sigma_clip(np.ones((3, 4)), axis=-1)
ValueError: operands could not be broadcast together with shapes (3,4) (3,) 
```
This PR fixes this issue by expanding the dimensions of the reduced center and standard deviation in all cases except when axis=0.

~~and I don't know why it has conflicts, I've created a new branch based on master just before I pushed it.~~

### CODE REVIEW

**Comment by astrofrog** [comment]
@crawfordsm @astronomeralex - should we treat this as a bug fix? If so, we'll need to add the 1.2 milestone (or 1.0.10 if it can be backported there) and a changelog entry.

**Comment by MSeifert04** [comment]
@astrofrog I think this "Bug" doesn't need backporting because the 1.0.x and 1.1.x branch seem to use another way of dealing with the ``expand_dims`` that should work with negative axis:

- https://github.com/astropy/astropy/blob/v1.0.x/astropy/stats/sigma_clipping.py#L124
- https://github.com/astropy/astropy/blob/v1.1.x/astropy/stats/sigma_clipping.py#L173

Although I haven't tested it.

**Comment by astrofrog** [comment]
@MSeifert04 - ok thanks - in that case, this will need a changelog entry in the v1.2.1 section (I'm in the process of getting 1.2 out of the door). I'll add the sections in the changelog soon.

**Comment by MSeifert04** [comment]
I think I've messed something up with the changelog entry. It seems like v.1.3. Could someone correct this or should I open another PR?

**Pull request merged**
