### PR TITLE
doc update to CCDData

### PR DESCRIPTION
**Pull request by SaraOgaz**
tiny doc addition

### CODE REVIEW

**Comment by MSeifert04** [comment]
We never actually used the `flags` seriously that's why we didn't promoted its existence. I have no objections but I'll let @mwcraig decide :)

**Comment by SaraOgaz** [comment]
Ahh, feel free to ignore then...

**Comment by mwcraig** [comment]
@SaraOgaz -- looks like  the test fail is because of trailing white space on line 63...let me know if you want me to push the fix to your branch.

**Comment by mwcraig** [comment]
Thanks, @SaraOgaz!

**Pull request merged**
