### PR TITLE
Include two new warnings/errors in PEP8 checks

### PR DESCRIPTION
**Pull request by astrofrog**
Specifically:

```
W292 - no newline at end of file
W391 - blank line at end of file
```

### CODE REVIEW

**Comment by mhvk** [comment]
+1

It might also be useful to be able to point people to automatic PEP8 checkers in editors/IDEs other than emacs (with the setup provided for emacs, I never have problems any more; quite wonderful!).

**Comment by astrofrog** [comment]
@mhvk - if someone is willing to write that, it should go here: http://docs.astropy.org/en/stable/development/codeguide_emacs.html?highlight=emacs

**Comment by pllim** [comment]
> editors/IDEs other than emacs

Why would anyone use anything other than Emacs?! ;)

**Comment by mhvk** [comment]
> Why would anyone use anything other than Emacs?! ;)

This is why I cannot write it :smiley_cat:

**Comment by bsipocz** [comment]
@astrofrog  - :+1: 
@mhvk - I have to disagree, I can't say I don't have any more pep8 problems since my emacs is set up (following the excellent guide). A new set of problems have risen; e.g. it's sooo difficult not to fix the annoying red lines before starting any of the work one intended to do :) 
(So the annoyance is contagious, it easily spreads over to the person reviewing the PR.)

**Comment by mhvk** [comment]
> e.g. it's sooo difficult not to fix the annoying red lines before starting any of the work one intended to do :) 

Yes, very true; can't bear those wiggly red lines!

**Comment by astrofrog** [comment]
autopep8 to the rescue:

```
autopep8 --ignore=E501,E309
```

(ignores long lines)

**Comment by embray** [comment]
In vim I just have it set up automatically to apply when I open a buffer, so I never see it (unless I'm editing a random file from elsewhere, in which case I have to turn that off before making any other changes to the file).

**Comment by astrofrog** [comment]
Any objections to going ahead and merging this?

**Comment by pllim** [comment]
:+1: for merging

**Pull request merged**
