### PR TITLE
Avoid duplicate code in ``astropy.vo.samp``

### LINKED ISSUE #2029: Refactor _call_, _notify_, and _reply_ in astropy.vo.samp to avoid repeated code
A lot of the code between ``_call_``, ``_notify_``, and ``_reply_`` in ``astropy/vo/samp/hub.py`` is identical and can be factored out.

### PR DESCRIPTION
**Pull request by astrofrog**
Replaces #2219

Fixes #2029

### CODE REVIEW

**Comment by astrofrog** [comment]
@anizami - thanks for the contribution, and sorry for not identifying the issues sooner! After some local testing, I was able to find out what was causing the issue.

**Comment by astrofrog** [comment]
@mdboom - could you review the addition of the configuration item and let me know if this is correct?

**Comment by embray** [comment]
Marked this as "affects release" due to the new config item if nothing else.  I personally have no problem adding a new config option in a patch release, but if you disagree we can change the milestone to 1.1.

**Comment by astrofrog** [comment]
@embray - fine by me - thought just to check, I thought that 'affects-release' just meant that for bugs it was a problem with a released version not just dev? (didn't think we used that for non-bugs?)

**Comment by mdboom** [comment]
Yes -- the new ConfigurationItem definition looks fine.

**Comment by embray** [comment]
It's used for enhancements too--any user-visible change between releases.

**Comment by embray** [comment]
You can read it equivalently to "This needs a changelog entry".  that's one of the main things I use it to check.

**Comment by astrofrog** [comment]
Damn, I think I must have lost the configuration changes when rebasing...

**Comment by astrofrog** [comment]
Recovered thanks to Dropbox. Version control redundancy is good.

**Comment by embray** [comment]
So's `git reflog` ;)

**Comment by astrofrog** [comment]
@embray - thanks, learned something today!

**Pull request merged**
