### PR TITLE
Use int for progress bar units (rebased version of #2721)

### PR DESCRIPTION
**Pull request by astrofrog**
Rebased version of https://github.com/astropy/astropy/pull/2721

### CODE REVIEW

**Comment by astrofrog** [comment]
It turns out there was no unit test in the first place for ``human_file_size``, so have added one.

@mdboom - can you review this?

**Comment by mdhoenig** [comment]
Nice work @astrofrog!

**Comment by astrofrog** [comment]
@mdhoenig - thank you for the original pull request #2721! I decided to go ahead and rebase this to include it in astropy 1.0, but if you have issues with rebasing again in future, I would be happy to provide more instructions!

**Comment by mdboom** [comment]
:+1:  I'm happy to merge once Travis-CI passes.

**Comment by embray** [comment]
:+1:

**Pull request merged**
