### PR TITLE
Allow extending equivalence with `from_format`

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

Cosmological equivalency (``Cosmology.is_equivalent``) can now be extended
 to any Python object that can be converted to a Cosmology, using the new
 keyword argument ``strict_format``.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by mhvk — COMMENTED** [review]
Interesting idea, though I wonder a bit what exactly the use case is. Though there certainly is the analogy with `Unit.is_equivalent`, which happily takes `str` (though that analogy fails in the sense that for units if one passes in anything that can not be understood, one gets a `TypeError`. Should that be the case for `Cosmology` as well?)

One thing I don't like so much is the name of the keyword argument. Could it perhaps be just `format`? I also wonder if the default should be `False`?

**Comment by nstarman** [comment]
> I wonder a bit what exactly the use case is

For me the use case is less tables and dictionaries but classes from other cosmology packages. So a CLASS cosmology object can be equivalent to an Astropy one. CLASS can do full Boltzmann stuff, so it'd be nice to convert from Astropy to CLASS and vice versa. The current ``is_equivalent`` already allows for Cosmology duck types. This just enriches the interoperability.

> One thing I don't like so much is the name of the keyword argument. Could it perhaps be just `format`? 

I'm ambivalent about the kwarg name. I was considering ``strict_type`` or ``any_format`` or ``any_type``, etc.
I'm against plain `format` because elsewhere, e.g. ``from_format``, `format` specifies the data type, while here it means
we're allowing equivalence with a-priori "unknown" data types. So definitely open to a better name!

> I also wonder if the default should be `False`?

In my mind there's a hierarchy of equivalence:
1. Astropy Cosmology objects
2. duck types to the above (has a custom ``__equiv__()`` method).
3. something that must be converted to an Astropy Cosmology.

The first two are currently eligible for equivalence, the latter is not. Comparing a Table to a Cosmology is odd and the two are not interchangeable. Even a CLASS cosmology and an Astropy one are not interchangeable.
To check their equivalence should require explicit instruction.

**Comment by mhvk** [comment]
OK, I'm sold on not auto-converting. On the keyword: at some level you could just pass `format` on to `from_format` - and give `False` a special meaning of not even trying (and perhaps `True` being equivalent to trying without a `format` argument to `from_format`. Or even just allowing `**kwargs` and if present try the conversion (that's probably too much!).

**Comment by nstarman** [comment]
Allowing `format` as a string is excellent. This nicely closes the problem that `yaml` cannot be auto-identified and so was not compatible with ``is_equivalent``. Now it can work with ``instance.is_equivalent(yaml_object, format="yaml")``

**Review by mhvk — APPROVED** [review]
This looks great now!

**Comment by nstarman** [comment]
Thanks for the ``format`` suggestion. Definitely an improvement!

**Pull request merged**
