### PR TITLE
Should astropy work with py2exe?

### PR DESCRIPTION
**Pull request by embray**
This may be outside the scope of the project, but I'm trying to make a standalone Windows application (with py2exe) that uses astropy. I don't get very far, as trying to import astropy triggers complaints about configuration. 

Here's a simple version of the problem:

in main.py:

``` python
import astropy
```

in setup.py

```
import sys
from distutils.core import setup
import py2exe
import numpy

#directory within WinSxS containing MSVCP90.dll - system dependent 
sys.path.append('C:\\Windows\\WinSxS\\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91')

setup(console=['main.py'], 
      options={'py2exe':{'excludes':['zmq']}},
      )
```

This is enough to run `python setup.py py2exe` and create dist/main.exe on my machine, but running it gives:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "astropy\__init__.pyc", line 109, in <module>
  File "astropy\logger.pyc", line 15, in <module>
  File "astropy\utils\console.pyc", line 35, in <module>
  File "astropy\config\configuration.pyc", line 128, in __init__
RuntimeError: Cannot automatically determine get_config module, because it is not called from inside a valid module
```

### CODE REVIEW

**Comment by embray** [comment]
#4418 reminded me I haven't had a look at this in a while, and for the heck of it I decided to try to rebase this work.  Turned out to be more work than I realized--especially implementing the test runner refactoring.

I have no idea if the currently rebased version will work fully in a zipimport context, as I haven't tested that yet.  For now would just like to see if it passes the standard builds.  Might actually be interesting to add a test configuration that tests astropy when imported from a zip file.

**Comment by embray** [comment]
Argh, had to rebase a couple more times after finding typos in the commits I updated in the first rebase attempt.

**Comment by embray** [comment]
As of 7343a60, I now have the tests working again on Python 2 and 3 when Astropy is imported from within a zip file.  I'm going to see about maybe adding a test configuration for this too.

This should go a long way toward getting current versions of Astropy working in an application package, though astropy-specific tweaks to the packager settings are still probably necessary (e.g. a pyinstaller hook).

**Comment by embray** [comment]
Note: This does *not* work if using `bdist_egg --exclude-source`.  Still investigating why that would be...

**Comment by embray** [comment]
Getting a somewhat mysterious test failure that doesn't appear to have anything to do with this PR.

**Comment by embray** [comment]
Rebased again.

**Comment by embray** [comment]
So as @maartenbreddels points out in #4531 the mechanism used for loading the bundled copy of the `six` module does not work within a zip file.  I missed this previously since on my personal system it was always installed.  But if I test in a virtualenv where I've made sure not to install `six` I do get:

```
>>> import sys
>>> sys.path.insert(0, 'astropy-1.1.dev14508-py2.7-linux-x86_64.egg')
>>> import astropy.extern.six
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/astropy/__init__.py", line 116, in <module>
  File "build/bdist.linux-x86_64/egg/astropy/__init__.py", line 104, in _check_numpy
  File "build/bdist.linux-x86_64/egg/astropy/utils/__init__.py", line 15, in <module>
  File "build/bdist.linux-x86_64/egg/astropy/utils/codegen.py", line 15, in <module>
  File "build/bdist.linux-x86_64/egg/astropy/utils/introspection.py", line 15, in <module>
  File "build/bdist.linux-x86_64/egg/astropy/extern/six.py", line 60, in <module>
  File "build/bdist.linux-x86_64/egg/astropy/extern/six.py", line 57, in _import_six
ImportError: Astropy requires the 'six' module of minimum version 1.7.3; normally this is bundled with the astropy package so if you get this warning consult the packager of your Astropy distribution.
```

I'm going to try out the alternative that I mentioned in #4531 and see how that goes.

**Comment by josePhoenix** [comment]
Aw man @embray, what's the word for the sinking feeling where you find one open issue having to do with the thing you're trying to accomplish.. and it's been open for *years*?

Bugret? Featuregret?

Commenting mainly to be nosy on any notifications and to 👍 on Astropy-in-standalone-apps support.

**Comment by maartenbreddels** [comment]
I'd like to add that I didn't need to use any hacks anymore to get astropy working on linux with pyinstaller and on osx with py2app (don't know about py2exe), so for linux and osx it seems to work out of the 'box' now.

**Comment by josePhoenix** [comment]
Interesting! I was using PyInstaller on Mac, which is a combination you didn't name. I have removed the dependency on Astropy for this tool (which turned out to be importing it and not using it) and successfully built an app bundle.

**Comment by embray** [comment]
Marshall and I got this working once aeons ago for webbpsf.  It required a few custom handlers for Astropy plus the tweaks in this branch, but it worked.  This branch is way out of date though and would be a tough problem to rebase.

**Comment by embray** [comment]
This came up again on StackOverflow.  Would like to try to find the time to move it forward again sometime if I can--maybe even add a continuous integration build based on a 'frozen' astropy to keep that working.  Need to rebase again, and also need to incorporate the solution from #4531 or something like it.

**Comment by maartenbreddels** [comment]
FWIW, I set up this repo:
https://github.com/maartenbreddels/frozen_astropy
which (seems to) work with astropy+pyinstaller. The trick I use is to include astropy as a directory, and monkey patch inspect.getabsfile. I use this trick in [vaex](https://github.com/maartenbreddels/vaex) as well.
A similar trick I use for [py2exe in vaex](https://github.com/maartenbreddels/vaex/blob/master/setup.py#L42) where I tell it to not package the astropy package.
Would be good to have this working with travis, and have it execute 'frozen_astropy test'.
I'm not sure py2exe has a future anymore, development seems to have stopped (correct me if I'm wrong).

**Comment by fockez** [comment]
I want to know what's the status now? I try to bundle my pipeline on Windows for specific project using windows, and python is easy to distribute. But I tried py2exe pyinstaller and mainly cx_freeze, no luck. I can skip the "six" error by adding astropy.extern.bundle.six manually to the setup script. But, still face the problem of get_config error.

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
    exec(code, m.__dict__)
  File "timviewer.py", line 17, in <module>
    from astropy.io import fits as pyfits
  File "C:\Python27\lib\site-packages\astropy\__init__.py", line 121, in <module>
    class Conf(_config.ConfigNamespace):
  File "C:\Python27\lib\site-packages\astropy\__init__.py", line 128, in Conf
    'When True, use Unicode characters when outputting values, and '
  File "C:\Python27\lib\site-packages\astropy\config\configuration.py", line 236, in __init__
    module = module.__name__
RuntimeError: Cannot automatically determine get_config module, because it is not called from inside a valid module

I hope this can be solved no matter how.
Thanks.

**Comment by maartenbreddels** [comment]
I did it the same as described above, don't 'pack' it, but make sure astropy gets placed in a directory, I believe it is the `skip_archive` option. Let me know if it worked.

**Comment by fockez** [comment]
I used cx_freeze and all the modules are in directory, not one package. Still no luck.

**Comment by maartenbreddels** [comment]
I believe this can fix that:
https://github.com/maartenbreddels/frozen_astropy/blob/master/frozen_astropy.py#L11

**Comment by fockez** [comment]
if hasattr( sys, "frozen" ):
    sys.path.insert( 2, os.path.join( os.path.dirname( sys.executable ), "astropy" ) )
    old_getabsfile = inspect.getabsfile
    def inspect_getabsfile_wrapper(*args, **kwargs):
        path = old_getabsfile(*args, **kwargs)
        print path
        last_part = re.sub("(.*?yportsa).*", r"\1", path[::-1])[::-1]
        print last_part
        return os.path.join( os.path.dirname( sys.executable ), last_part )
    inspect.getabsfile = inspect_getabsfile_wrapper

add astropy to sys.path[0] may cause io and gzip error, so I change to [2], but still get the same error of get_config.

**Comment by fockez** [comment]
i don't think it's the problem of getabsfile, i found that i can get the right return of getabsfile, but i always get none return of getmodule function.

**Comment by maartenbreddels** [comment]
Are you sure, since what I wrote (I cannot remember all the details):
https://github.com/maartenbreddels/frozen_astropy/blob/master/frozen_astropy.py#L16
> inspect.getabsfile will return /usr/lib/python2.6/site-packages/astropy/__init__.pyc
> and inspect.getmodule will not find that file in sys.modules, so we rewrite path
How I found out is by using the debugger, for windows you can try making a console application, do import pdb; pdb.set_trace(); and from there on set a break on getmodule, and continue.

**Comment by fockez** [comment]
Sorry for the carelessness, I didn't check the whole output including "astropy". Under windows, all module list using lower case and getabsfile return .py not .pyc, but cx_freeze only packing .pyc.
So I change it to :

`if hasattr( sys, "frozen" ):
    sys.path.insert( -1, os.path.join( os.path.dirname( sys.executable ), "astropy" ) )
    old_getabsfile = inspect.getabsfile
    def inspect_getabsfile_wrapper( *args, **kwargs ):
        path = old_getabsfile( *args, **kwargs )
        last_part = re.sub( "(.*?yportsa).*", r"\1", path[::-1] )[::-1]
        if os.path.splitext( last_part )[1] == '.py':
            last_part = os.path.splitext( last_part )[0] + '.pyc'
        return os.path.join( os.path.dirname( sys.executable ), last_part ).lower()
    inspect.getabsfile = inspect_getabsfile_wrapper`

Also add path to the end to avoid path conflicts. This is ugly but can work. I hope this will be resolved permanently in the future. At least using bundled inspect module?

**Comment by embray** [comment]
I think it would be great to include a test in the appveyor build matrix for bundling Astropy with pyinstaller or something, so that we can keep this working in the future.

**Comment by astrofrog** [comment]
@maartenbreddels @embray @fockez @josePhoenix @badders - I think it would be good to understand what the latest status is here. I think all of you used various tools (py2app, py2exe, pyinstaller). Could you report back as to what currently works/doesn't work with the developer version of astropy? Note that the developer version of Astropy doesn't include bundled versions of six or pytest anymore, which were causing issues for some people before.

I think this PR may include some useful things we should incorporate anyway, but it's going to be incredibly difficult to rebase given how old it is and changes in e.g. the testing infrastructure. It might make more sense to just open a new issue and point to this PR in case someone wants to start again (unless, @embray, you want to try rebasing this!).

**Comment by fockez** [comment]
Recently, I switch my code from py2 to py3, and this cause new trouble. Under PyInstaller, it always report when loading built app:
ImportError: Astropy requires the 'six' module of minimum version 1.10; normally this is bundled with the astropy package so if you get this warning consult the packager of your Astropy distribution.
And, with cx_freeze which works under py2 now report:
ValueError: 'm / (s)' did not parse as unit: invalid syntax (generic_lextab.py, line 4).

So, when the 3.0 of astropy will be released or at least beta version, totally no need of six package.

**Comment by fridgerator** [comment]
@fockez I was able to get this to work using PyInstaller with the following `pyinstaller` options `--exclude-module astropy` and `--add-data path_to/astropy:astropy`

**Comment by astrofrog** [comment]
@fridgerator - ok that sounds pretty straightforward. So no need for the changes in this PR?

**Comment by fridgerator** [comment]
@astrofrog Correct, I didn't change anything else or use anything from this PR

**Comment by lzkelley** [comment]
I'm trying to use the exclude/include trick from above.  It got rid of the `ImportError: Astropy requires the 'six' module of minimum version 1.10` error, but now I get:

```
Traceback (most recent call last):
  File "pyapi.py", line 10, in <module>
    import cosmopy
  File "/Users/lzkelley/Programs/cosmo/ve_test/vetest/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/cosmopy/__init__.py", line 9, in <module>
  File "/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/_MEIhGawWS/astropy/constants/__init__.py", line 28, in <module>
    from .constant import Constant, EMConstant
  File "/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/_MEIhGawWS/astropy/constants/constant.py", line 11, in <module>
    from ..units.core import Unit, UnitsError
  File "/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/_MEIhGawWS/astropy/units/__init__.py", line 14, in <module>
    from .core import *
  File "/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/_MEIhGawWS/astropy/units/core.py", line 23, in <module>
    from .utils import (is_effectively_unity, sanitize_scale, validate_power,
  File "/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/_MEIhGawWS/astropy/units/utils.py", line 16, in <module>
    from fractions import Fraction
ImportError: No module named 'fractions'
[2338] Failed to execute script pyapi
```

I'm using a virtualenv named `vetest` in the directory `ve_test`, trying to run with the command:
`pyinstaller -F pyapi.py --exclude-module astropy --add-data /Users/lzkelley/Programs/cosmo/ve_test/vetest/lib/python3.5/site-packages/astropy:astropy`

(the produced executable is also >200MB, is that normal?)

The full output from `pyinstaller` is attached.

[out.txt](https://github.com/astropy/astropy/files/1608048/out.txt)

**Pull request closed without merging**
