### PR TITLE
docs: add nitpicks

### PR DESCRIPTION
**Pull request by nstarman**
Fixes #16481.

There's going to be a lot of nitpicks added. IDK why #15852 seemed to trigger new sphinx complaints.
But more strangely, if you look at the build history of RTD after #15852 was merged it worked just fine. It was only after #16475 was merged that RTD started complaining. But #16475 doesn't appear to be related.

This is a brittle solution.

### CODE REVIEW

**Comment by mhvk** [comment]
Gosh, this is pretty awful. Given the strange build history, is it instead sphinx version dependent? Might it be better to just revert? (I.e., #16481)

**Comment by nstarman** [comment]
> Gosh, this is pretty awful.

Yeah, not great. Maybe more `:noindex:` on the other links from https://github.com/astropy/astropy/pull/15852 would actually fix this. I can investigate later.

> Given the strange build history, is it instead sphinx version dependent? 

Perhaps. How do we see in RTD what it was picking up?

> Might it be better to just revert?

I hope not. What #15852 was doing was good. It would be a shame to revert that because of public API confusion.
In my many repos I have never suffered these issues with Sphinx nor RTD. There are some structural differences: PEP8 compliance and sphinx configuration.
Perhaps we can ameliorate the Sphinx issues by turning `nitpicky` off? Noticed by @eerovaher  in https://github.com/astropy/astropy/pull/15852#issuecomment-2061338694

My suggestion would be to merge this PR then figure out how to revert THIS PR by either `:noindex:` additions or `nitpicky` settings.

**Comment by eerovaher** [comment]
#15852 removed link targets in our documentation (by adding the `:noindex:` instructions), but the documentation build succeeded in the pull request because it could find the link targets in the latest build of `main`. Likewise, the documentation build for 642fbc982ee26dfa619350f27a0330b8d4929c28 could still look up the link targets from the previous build, so it wasn't until the build for 642fbc982ee26dfa619350f27a0330b8d4929c28 had finished that the link targets became inaccessible. Similar problems occurred twice in December (#15698 and #15715). I don't fully understand every detail that contributes to the problem, but it apparently it has something to do with https://github.com/astropy/astropy/blob/f3e40c0931240e6f77a2e8ad8850bbe7982274ff/docs/conf.py#L112-L114

The fix attempted here is not good because the documentation is now lacking links that were there before (compare the [documentation for this pull request](https://astropy--16482.org.readthedocs.build/en/16482/units/ref_api.html) with the [documentation for 6.1.0](https://docs.astropy.org/en/stable/units/ref_api.html)).

@nstarman might have identified the correct fix in #16473, but I don't expect that to be applied quickly, so in the short term we will have to merge #16481.

**Comment by pllim** [comment]
👎 to disable nitpicky. It has been useful in the past to catch real problems. Disabling it would be throwing out baby with the bath water.

**Comment by pllim** [comment]
> Where in RTD can we see what version it was picking up?

You have to click on "raw log" link on the build job page to see everything.

**Pull request closed without merging**
