### PR TITLE
Add graphviz diagrams for compound models

### PR DESCRIPTION
**Pull request by mdboom**
I find this really helps to understand the material.

### CODE REVIEW

**Comment by mhvk** [comment]
Sounds great! Do you have a link to how it looks in practice somewhere?

**Comment by embray** [comment]
Several of these look terribly broken when I build locally.  Especially the last one:

broken-compound-model-graphs

But that wouldn't be the first time I've had issues with the graphviz installed on this machine.  It's probably a very old version.  I'm happy to go ahead and merge this and see how it looks on RTD.

I wonder if it wouldn't be worth having a `to_digraph()` method on compound models, or something to that effect (with an auxiliary method that wraps it and automatically pipes through graphviz as well).  I would like to have more built-in ways to visualize compound models.  I do have some code that prints out an ASCII art of the tree, but it has a few small bugs I haven't gotten around to resolving, so I never shipped it with a release.  The ASCII tree might still be convenient to have.  But something like this is even better, at least for users who have the required dependencies.

**Comment by mdboom** [comment]
Yeah -- I don't see those glitches locally, but it could be something to do with fonts/platform/configuration/phases of the moon.  Most importantly is how it looks on readthedocs.  I'm happy to merge and then fix/revert after.  Worst case we have some ugly diagrams on the development copy of the docs for a while.

**Comment by embray** [comment]
Well, let's find out :D

**Comment by mdboom** [comment]
They look fine to me, but given that they are SVGs, it's possible that YMMV.

**Comment by mhvk** [comment]
Graphs look great for me at least. Very helpful!

**Comment by mdboom** [comment]
> I wonder if it wouldn't be worth having a to_digraph() method on compound models, or something to that effect (with an auxiliary method that wraps it and automatically pipes through graphviz as well). I would like to have more built-in ways to visualize compound models. I do have some code that prints out an ASCII art of the tree, but it has a few small bugs I haven't gotten around to resolving, so I never shipped it with a release. The ASCII tree might still be convenient to have. But something like this is even better, at least for users who have the required dependencies.

Yeah -- I thought all of that would be helpful here, but ultimately didn't want to get bogged down by it just to improve the docs.  There were some non-obvious details necessary to make these look nice, and now at least that knowledge can be transferred to a more automated graphviz output of a model when we do that.  Theoretically it should be possible to implement an IPython display hook for this.  I think someone's already done the heavy lifting there:

https://github.com/tkf/ipython-hierarchymagic

**Comment by embray** [comment]
That would slick.  I'll open a pie-in-the-sky issue for it.

The one graph for `Identity(1)` looks a little funky (the mapping `(0,)` is overlapping the arrow).  But I don't think it's a big deal.  These look great and I especially like how mappings were handled in general.

**Pull request merged**
