### PR TITLE
Default plot labels to wcsapi world_axis_names property

### PR DESCRIPTION
**Pull request by Cadair**
### Description

This PR makes WCSAxes use the new `world_axis_names` property added to the APE 14 API in #9156

### CODE REVIEW

**Comment by Cadair** [comment]
I am going to stick my nose out on this one and argue that it's a bug fix. The main reason is that both the WCSAxes autolabelling and the wcsapi's world_axis_names properties are new in 4.0, and changing the default behavior of the labelling on WCSAxes on two sequential major releases of astropy sounds like a good way to annoy some people.

Also the `HighLevelWCS` fix is definitely a bug fix (but I can split that out if needed)

**Comment by Cadair** [comment]
@astrofrog I think I got there.

**Comment by astrofrog** [comment]
@bsipocz - this should be backported to 4.0. Note that I didn't milestone as 4.0.1 otherwise we'd have had to include a changelog entry there.

**Comment by bsipocz** [comment]
Sounds good. Even if it were milestoned as 4.0.1, I would include it in RC2.

**Pull request merged**
