### PR TITLE
Description of new cache features

### PR DESCRIPTION
**Pull request by aarchiba**
### Description

This pull request is to add some text for the What's New file; see PR #9581 (into which this should presumably be merged).

### CODE REVIEW

**Comment by pllim** [comment]
@aarchiba , I think Tom meant to open this against his PR branch over there? Maybe @astrofrog can confirm.

**Comment by aarchiba** [comment]
Yeah I'm not totally sure how to do that. But at least the text is written so it's just a matter of formatting and git contortions.

**Comment by aarchiba** [comment]
In fact if the text is saying the right things it might be easiest for someone with appropriate permissions to just paste the text into the right places and then ditch this PR.

**Comment by astrofrog** [comment]
I can cherry-pick the commit from here into https://github.com/astropy/astropy/pull/9581

**Comment by astrofrog** [comment]
Thanks for the text!

**Comment by pllim** [comment]
Okay, since @astrofrog is cherry picking, I am closing this without merge then. Thank you, all!

**Comment by bsipocz** [comment]
> Yeah I'm not totally sure how to do that. But at least the text is written so it's just a matter of formatting and git contortions.

Git fuing, and not relevant here any more, but it comes handy in many situations:

you can add others' fork as a remote to your local git clone 
(e.g. `git remote add astrofrog git@github.com:astrofrog/astropy`. Then working against their branches can be done just as you work against astropy/master (e.g. opening a branch with a HEAD from  their branch, etc.)

Then pushing your changes to your github fork, and open a PR just as you would do normally. There is an option then to change the base branch to someone else's fork, there you can select the branch you based your branch on.

**Pull request closed without merging**
