### PR TITLE
Fix missing default during pytest_configure

### PR DESCRIPTION
**Pull request by josePhoenix**
Addresses #5402.

### CODE REVIEW

**Comment by MSeifert04** [comment]
@josePhoenix From what I've seen are the test failures not because of this PR. So you don't need to worry (yet) about these.

I think someone (just semi-randomly pinging @pllim) will restart those tests soon.

**Comment by pllim** [comment]
Restarted.

**Comment by pllim** [comment]
Travis passed but coverage decreased 0.4% (probably unrelated to this PR but due to astropy/astropy#5418).

**Comment by pllim** [comment]
It is kinda a bug fix but not a very visible one. Does this need change log?

**Comment by eteq** [comment]
👍  from me too - thanks @josePhoenix! 

I think it should get a changelog entry, though, as @josePhoenix's case is not necessarily *that* unique. @josePhoenix, can you add this to the 1.2.2 section of `CHANGES.rst` under "Other Changes and Additions"?

(aside: @pllim or maybe @astrofrog - do you know if there's any way I can *add* files with github's new "edit a PR branch" feature?  If there was I could just add the changelog entry myself... I thought someone mentioned this on the astropy-dev thread but don't see a way to do it?)

**Comment by pllim** [comment]
@eteq apparently you can now commit directly to this PR branch. So that's how you add the entry. I tried that feature only once but it failed miserably because i had to rebase and it won't let me push forcefully.

**Comment by josePhoenix** [comment]
Cheers! I'd forgotten I needed to do that.

**Comment by eteq** [comment]
Oh, whoa, that did work!  Of course now the changelog conflicts... but still.  Neat!

@josePhoenix - one other question before I try to merge this fixing the conflicts: can you confirm making this change get py.test working in your package?  Or is there something else that needs changing? (Which it would make sense to bundle in with this).

**Comment by josePhoenix** [comment]
Turns out, there are a bunch more unchecked exception cases in this plugin. This PR needs more attention than I can give it at the moment, I'm afraid. There are also calls to deprecated methods in PyTest that need to be updated.

**Comment by pllim** [comment]
Yes, these other exceptions are a known issue (see #5277). I was under the impression that you only needed this one-liner change to make your own package using Astropy template work.

**Comment by josePhoenix** [comment]
By "unchecked exception cases" I mean cases where the code *could* raise an exception and the exception is *not checked*. For example, the one I fixed in the first commit in this PR. It turns out that there are a lot more of these in `pytest_plugins.py`, which seems more or less orthogonal to the issue you linked to.

**Comment by josePhoenix** [comment]
I've opened #5446 instead, as the docs are currently misleading. Fixing `pytest`-command support seems to be more involved than anticipated. (Once I fixed one missing default, another appeared. And when I fixed that one, another.)

**Comment by eteq** [comment]
Actually, @josePhoenix, I just reopened this, and can you rebase this against Astropy master (the conflicts are just from the changelog)?  It's definitely not *wrong* to include this...

**Comment by eteq** [comment]
Addendum: in an offline chat w/ @josePhoenix it looks like this *might* actually be due to a change to how options are set as defaults. So this might be a *new* aspect of #5277 after all: options now may have to specify defaults, which would be why this change was needed if you try to invoke it from py.test 3.x ...

**Comment by pllim** [comment]
Why, pytest? Why?! :scream:

**Pull request closed without merging**
