### PR TITLE
Fix handling of SkyCoords with N-d frame attributes

### LINKED ISSUE #5889: __repr__ method of BaseRepresentation can fail
The ```__repr__``` method of the ```BaseRepresentation``` class uses a ```numpy``` view to access the values. It is possible to create objects for which this view cannot be taken, i.e (using v1.3.1):

```python
from astropy.coordinates import EarthLocation, SkyCoord, get_moon
import astropy.units as u
from astropy.time import Time
import numpy as np

greenwich = EarthLocation.of_site('greenwich')
times = Time("2017-03-20T12:00:00") + np.linspace(-2,2,3)*u.hour
moon = get_moon(times, location=greenwich)
targets = SkyCoord([350.7*u.deg, 260.7*u.deg], [18.4*u.deg, 22.4*u.deg])
targs2d = targets[:, np.newaxis]
targs2d.transform_to(moon)
```

produces

```python
Traceback (most recent call last):
  File "test_patch2.py", line 11, in <module>
    targs2d.transform_to(moon)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/astropy/coordinates/sky_coordinate.py", line 454, in transform_to
    return self.__class__(new_coord, **frame_kwargs)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/astropy/coordinates/sky_coordinate.py", line 212, in __init__
    kwargs = self._parse_inputs(args, kwargs)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/astropy/coordinates/sky_coordinate.py", line 360, in _parse_inputs
    .format(attr, coord_value, valid_kwargs[attr]))
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/astropy/coordinates/representation.py", line 400, in __repr__
    arrstr = _array2string(self._values, prefix=prefixstr)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/astropy/coordinates/representation.py", line 229, in _values
    axis=-1).view(dtype).squeeze()
ValueError: new type not compatible with array.
```

### PR DESCRIPTION
**Pull request by StuartLittlefair**
This PR adds functionality to fix #5889  and #5890

### CODE REVIEW

**Comment by StuartLittlefair** [comment]
The failure here looks unrelated to my changes, but something to do with remote sites. Perhaps someone with write access can restart that one failing test?

**Comment by bsipocz** [comment]
@StuartLittlefair - So these are from those bugs again that are fixed in master?

**Comment by bsipocz** [comment]
To answer my question, I see both issues on master, too. I'll have a look around whether it's possible to change the base branch of this PR, if not then this should be closed and a new one opened against master.

**Comment by bsipocz** [comment]
Hmm, changing base branch clearly worked, but introduced a lot of unwanted stuff here. I'm going ahead and try to rebase this mess and force push it back to this branch. (@StuartLittlefair - I've made a backup copy of your original as bsipocz/StuartLittlefair-patch-2-copy)

**Comment by mhvk** [comment]
Duh, I should have seen that you had a PR.  I'll close mine and instead make a PR to your branch (since I think my solution is a bit more elegant...)

**Comment by mhvk** [comment]
So, I added 2 commits for the representation. Am still trying to wrap my head around the rest of the PR (might actually be better to keep them separate, sigh...).

**Comment by mhvk** [comment]
I think the solution is not right -- `transform_to` is the problem, in that it doesn't do what it states it does - it should remove attributes before initializing a new class.

**Comment by StuartLittlefair** [comment]
@mhvk, I only really bundled these together because I wasn't smart enough to find a simple regression test for #5889. 

Perhaps the simplest way forward is for me to close this, for you to re-open your PR for #5889 and we'll look again at a separate PR for #5890, which probably does need some careful thought about what exactly ```transform_to``` should be doing?

**Comment by mhvk** [comment]
See #5897 for a simpler fix, which combines all PRs.

**Comment by mhvk** [comment]
OK, it seems like for now this PR probably should be closed (we can reopen if #5897 turns out to be problematic as well).

**Pull request closed without merging**
