### PR TITLE
Better handling of inputs to Mapping models

### PR DESCRIPTION
**Pull request by embray**
This introduces a workaround to the issue raised by @nden in [this comment](https://github.com/astropy/astropy/pull/3297#issuecomment-70105705)

I'm not super happy about it since it introduces a (very slight, on the order of a few milliseconds) performance regression on evaluated models with a scalar input.  This isn't that critical since it's not something that scales with the size of the input.

What bothers me more is that this fix is for compatibility with an undocumented, sort of unintentional assumption that all `Model.evaluate()` implementations will return one or more array of at least 1 dimension, even for simple arithmetic expressions involving all scalars (this is because the framework already promotes all scalar parameters to 1-D arrays before passing them to `evaluate`).  I think the current assumptions are fairly reasonable, but they're not universal (clearly, as the `Mapping` class broke this assumption), and it's all still a little confusing.  This explanation probably doesn't even make sense to anyone but me, which is cause for concern in of itself.

### CODE REVIEW

**Comment by embray** [comment]
Apparently I also need to rebase this, and I'm going to add a regression test as well.

**Comment by embray** [comment]
Rebased and added regression test.

**Comment by embray** [comment]
Once this is merged I will merge #3297 and #3300

**Comment by astrofrog** [comment]
@embray - thanks - once this and #3297 and #3300 are merged, I think we are ready to do a RC for 1.0 :smile:

**Comment by embray** [comment]
I'm writing my "what's new" page entry right now.  That needs to be in there too.

**Comment by astrofrog** [comment]
Ok, thanks!

**Comment by astrofrog** [comment]
@embray - the failing test on AppVeyor is due to the regression test for the 'colon in filename' FITS regression test that was never tested on Windows. So I think this PR can be merged now but we should fix the test failure in a separate PR.

**Comment by embray** [comment]
Hmm.  Oops.  I'll handle that ASAP.

I don't think colons are valid at all in Windows filenames.  The test should be skipped on Windows.  I don't think it's even worth adding a 'known issue' for that or anything since you're just not going to get filenames like that on Windows (unless it's over a network mount or something, though it should work there--obviously there's nothing on the Python end that cares about what the filesystem does or doesn't support)

**Comment by embray** [comment]
Okay, since the only failure on AppVeyor was due to this clearly unrelated test, this can be merged.

**Pull request merged**
