### PR TITLE
Add test of custom reader class that sets col.dtype

### PR DESCRIPTION
**Pull request by taldcroft**
### Description

Related to discussion in #11895 and #11892, this adds a test of the current usage of the `io.ascii.core.Column.dtype` attribute. This attribute is used in `BaseOutputter._convert_vals` to force the data type if defined.

Prior to astropy v4.3, this functionality was tested via testing of the ECSV reader, but after the refactoring in 4.3 there were no remaining tests. This PR fixes that.

cc: @mvhk @hamogu 

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will
review this pull request of some common things to look for. This list
is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] If the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by hamogu — APPROVED** [review]
Using cycle to generate the list of three from an input list of two elements seems like overkill to me, but it's not wrong, just overly complicated, so I'm approving.

**Review by mhvk — APPROVED** [review]
Looks good! Since @hamogu also approved, I'll merge.

**Comment by mhvk** [comment]
Hmm, except the test failure is real - you need to somehow ensure the registry is cleared, otherwise the second run fails.

**Comment by taldcroft** [comment]
> Using cycle to generate the list of three from an input list of two elements seems like overkill to me, 

You're right. I'm not sure why I did that, it was just the first thing that occurred to me to generate some types.

On a more serious note, this is failing the new test on 32-bit and parallel (and two reviewers approved without commenting...). I was a little worried about something like this because it registers a new reader and doesn't back it out. I'm actually not immediately sure what to do about this.

**Comment by hamogu** [comment]
I approved before the tests were run. I as assuming "merge when CI passes".
Anyway, you can do the read test without registering it as a reader. Just get a reader object and monkey-patch in the function that assigns the dtype on that particular object This is a test about dtypes, it's not about "how to use the registry" and the problem is due to the testing environment. In a real environment, we *do* want an error if we register the same reader several times.

**Comment by taldcroft** [comment]
OK 🤞 on the new version that uses `get_reader` without registering the reader. 

I do think that as a matter of process, the primary reviewer should review and click all of the boxes in the description prior to actually approving. If there is a case of not wanting to wait for CI then leaving the "passes CI" box unclicked and labeling as merge-when-ci-passes is OK.

**Comment by hamogu** [comment]
OK, understood.

**Comment by taldcroft** [comment]
I have no idea how code coverage can go down when I just added a test. Anyway, that is definitely ignorable.

**Comment by taldcroft** [comment]
Woohoo, passed CI except code-cov.

**Comment by mhvk** [comment]
Still have to get used to the new checklist - partially it is just a consequence of how github sets up looking at changes as a different page from the page where you see CI results. Anyway, one obviously should check CI before pressing merge, which I did (and was surprised by the error!).

**Comment by pllim** [comment]
Re: coverage -- @jdavies-st found out that the calculations become inaccurate when "cancel duplicate CI" happens in `main`. See spacetelescope/jwst#6137 . Not sure if it is the case here, but if this really bothers you, I can apply that same patch to `astropy`. Lemme know.

**Comment by taldcroft** [comment]
@pllim - I'm not personally too worried about that coverage funny. I was just surprised.

**Pull request merged**
