### PR TITLE
Fixes issue #3550: Clarify whether Gaussian2D.theta is measured from x or y axis

### PR DESCRIPTION
**Pull request by vortex-ape**
#3550

### CODE REVIEW

**Comment by astrofrog** [comment]
@vortex-ape - I would actually re-phrase and say 'from the positive y-axis' because this model can be used in a non-celestial context. Can you update this pull request? (no need to open a new one, just add a new commit to this branch)

**Comment by vortex-ape** [comment]
@astrofrog - Done!

**Comment by embray** [comment]
Is that actually how it's defined though?  I think it should be measured from the positive x-axis.  
Also, why couldn't the NCP just be oriented along the x-axis?  For the purposes of this model it's just a rotation angle--it doesn't have to be a position angle.

**Comment by astrofrog** [comment]
@embray - images are often aligned with the NCP 'up' even though that is arbitrary, so people get confused when dealing with 2D gaussians to represent beams (where PA is measured from y-axis). Anyway, it's good to have this clarified here - thanks @vortex-ape!

**Comment by larrybradley** [comment]
Sorry I wasn't paying closer attention to this PR, but why was the `theta` docstring updated here?  I agree with changing `x/y_stddev` to say "Standard deviation of the Gaussian in x/y before rotating by theta."  But `theta` is simply a rotation of that "initial" Gaussian.  There isn't any preferred reference axis here.  One could say the initial positive y axis is rotated by `theta` or the initial positive x axis is rotated by `theta` (or the initial negative y axis is rotated by `theta`, etc.).  `theta=0` is simply the initial Gaussian with `x_stddev` along x and `y_stddev` along y.  Saying "The rotation angle increases counterclockwise, from the positive x-axis" doesn't make sense.  The rotation angle of *what* from the positive x-axis?

However, if we changed the model to be defined in terms of semimajor/semiminor axis, then we *would* have a reference axis and thus need to specify where `theta` was measured from, e.g. `theta` is the CCW rotation angle of the semimajor axis from the positive x-axis (that's the usual convention).

Anyway, this is a long-winded explanation to say that with the current model definition I think the original `theta` docs were correct (with the updated `x/ystddev` docs):
"Rotation angle in radians. The rotation angle increases counterclockwise."

**Comment by vortex-ape** [comment]
@astrofrog - I've started studying astronomy so I don't feel lost in the discussions :)

**Comment by astrofrog** [comment]
@larrybradley - I see what you mean, but we should then still add a note that explains that for example if people use x_stddev for the major axis, *then* theta is measured from x-axis. I've seen several radio astronomers be confused when trying to emulate beams, so this would be a good thing to include in the notes.

**Comment by astrofrog** [comment]
The 'before rotating by theta' is correct though. @vortex-ape, do you want to try and open a pull request to remove the modification to the theta docstring for now? The additions to ``x_stddev`` and ``y_stddev`` should already be helpful for users.

**Comment by larrybradley** [comment]
If the functionality becomes available to ensure that major axis > minor axis in the model definition, then I would like to change the model definition to use stddev along the semimajor/semiminor axis.

**Comment by embray** [comment]
@larrybradley I agree with you, and that was my initial problem too, although you stated it better.  I think it still clarifies things to specify a convention though which is why I still merged it.  I would welcome a separate PR to redefine the model in terms of semimajor/minor axes though.

**Comment by larrybradley** [comment]
@embray Is there a good way to constrain parameters in the model definition, e.g. param must be > 0 or param1 must be >= param2, etc.?  In general, I can imagine there are models that are valid (or make physical sense) only for some limited parameter range.

**Comment by vortex-ape** [comment]
@astrofrog - I'll open a PR to remove it.

**Pull request merged**
