### PR TITLE
Fix creating SkyCoord from list of SkyCoord objects

### LINKED ISSUE #6597: Cannot create SkyCoord array from list of SkyCoord in certain frames
```python
>>> from astropy.coordinates import SkyCoord
>>> frame = 'galactic'
>>> c1 = SkyCoord(1, 3, unit='deg', frame=frame)
>>> c2 = SkyCoord(2, 4, unit='deg', frame=frame)
>>> sc1 = SkyCoord([c1, c2])
AttributeError: 'SkyCoord' object has no attribute 'ra'
```

This fails for all frames where the `SkyCoord` list items do not have a RA/Dec, e.g. galactic, supergalactic, altaz, etc.

### PR DESCRIPTION
**Pull request by eteq**
As pointed out in #6597, there was a flaw in the implementation of `SkyCoord` that made it fail when you try to pass in non-equatorial frames as a list of multiple `SkyCoord` objects.  It turns out the problem was deeper: it was treating *all* such frames as ICRS, even if you were to have passed in an FK5 or the like.  This PR fixes that flaw.

It thereby fixes #6597

### CODE REVIEW

**Comment by eteq** [comment]
Note that all the tests passed in the previous commit, and this last one just added the missing changelog entry.  So this is read to go once someone else has reviewed it.  cc @larrybradley @adrn @StuartLittlefair ?

**Comment by larrybradley** [comment]
Thanks, @eteq.  LGTM, but I'll let a package maintainer do the official review.

**Comment by bsipocz** [comment]
Merging as it has approvals from a maintainer and passes CI.

**Comment by bsipocz** [comment]
Thanks @eteq!

**Pull request merged**
