### PR TITLE
TST: Ignore files generated by doctest

### LINKED ISSUE #10037: MNT: Ignore or auto clean-up generated files from testing
### Description

Run tests with `pytest --remote-data`.

### Expected behavior

`git status` to report clean state of the repo upon test completion.

### Actual behavior

```
$ git status
On branch ...
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        compressed_image.fits
        my_image.fits
        new.fits
        new1.fits
        new2.fits
        newtable.fits
        newtable2.fits
        out.fits
        rotation.asdf
        table1.fits
        table2.fits
        table3.fits
        test_file.fits
        test_group.fits
        values.dat
        variable_length_table.fits
```

### System Details

Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-redhat-7.7-Maipo
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
Numpy 1.18.1
astropy 4.1.dev756+ge36efa9b9
Scipy 1.3.1

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address files listed as "not tracked" by `git status` after a local test run. This does a brute-force ignore of those files, given that astropy/pytest-doctestplus#68 is unlikely to be fixed any time soon. We can come back and revert this when things are fixed on `pytest-doctestplus` side.

Fixes #10037

### CODE REVIEW

**Comment by bsipocz** [comment]
I would rather not have this workaround, having the files visible is a constant reminder for us to fix the testing infrastructure. I'm afraid if we hide them with gitignore it wouldn't annoy any of us to a point that this actually get fixed ever.

**Comment by pllim** [comment]
I tried fixing it but I got stuck. So, this is the next best thing. Quoting Marten, let's not let perfection be the enemy of good? If we don't ignore them, it is just a matter of time before someone accidentally committing them into version control using a blind `git add .`.

**Comment by mhvk** [comment]
I think if there's no progress at the doctest-plus side, we should rather re-open and merge #9439... That said, perhaps this is just a reminder to actually look at it - #9439 was very simple so really the fix should not be hard!

**Comment by pllim** [comment]
I am okay with the solution at #9439 too. However, is there a chance it won't be compatible with the solution at `pytest-doctestplus` when it finally happens? Still, not a blocker. Just thinking aloud.

**Comment by bsipocz** [comment]
As a workaround, I would also prefer to merge in #9439 temporarily than adding the files to gitignore (I don't want to have the rubbish piling up, even when it's ignored). We can always remove the edits into conftest once the issue gets fixed upstream.

**Comment by pllim** [comment]
Okay. Closing this then.

**Pull request closed without merging**
