### PR TITLE
Use unique configuration variable for astropy cache in pytest plugin

### LINKED ISSUE #7720: Astropy plugin cache_dir option collides with pytest option
The pytest plugin provided in `astropy.tests.plugins.config` provides an option called `cache_dir` that is used for customizing the location of the Astropy cache during test runs.

However, this collides with an option that pytest itself provides that is used for managing its own cache.

This is an unfortunate state of affairs. We really ought to change the option name in our own plugin, but this is a fairly significant API change. Would it be subject to the general rules for deprecation/removal?

This was first reported in https://github.com/astropy/astropy-helpers/issues/401.

### PR DESCRIPTION
**Pull request by drdavella**
This fixes #7720.

### CODE REVIEW

**Comment by pllim** [comment]
I think this warrants a change log since it is a bug fix that requires API change. Just in case. Thanks for the quick fix, Dan!

p.s. It is a little concerning that this is not tested given that this PR does not require changing any test, but that is out of scope here.

**Comment by drdavella** [comment]
This could be tested in principle, but it would be a bit "meta" and I'm not really sure it's worth the effort.

**Comment by pllim** [comment]
@bsipocz , Travis still picked up `pytest` 3.7.1. Will restarting help here?

**Comment by bsipocz** [comment]
@pllim - yes, restart should sort it out.

**Comment by bsipocz** [comment]
restarted

**Comment by bsipocz** [comment]
since this was just a "cosmetic issue" of leaving junk in unexpected places, I totally agree with @drdavella's comment above.

**Comment by saimn** [comment]
> since this was just a "cosmetic issue" of leaving junk in unexpected places

It can be more annoying if you run `pytest --cache-clear`, which happened to me: pytest then deletes its cache directory, which is the astropy directory, including `.git/` !

**Comment by saimn** [comment]
It could be useful to do the same the `config_dir` which is also a generic name that could cause conflicts with pytest or other plugins.

**Comment by pllim** [comment]
> which is the astropy directory, including `.git/` !

😱 Oh noes. I hope you didn't lose any work.

**Comment by saimn** [comment]
By chance I pushed all my branches to github a few days before, which I never do usually, maybe some premonition :slightly_smiling_face:

**Comment by drdavella** [comment]
@saimn wow, that's terrible. I wonder how no one has ever been bitten by this before, since this has been around for a long time.

I agree about changing the `config_dir` option as well. Will push a fix shortly.

**Comment by drdavella** [comment]
It's worth asking: do these options still serve a purpose? Do they justify the maintenance burden of this plugin, and also in the test runner? It seems like the fact that the test runner copies everything to a temporary directory anyway might make these options unnecessary.

**Comment by pllim** [comment]
> do these options still serve a purpose?

I don't know the history but they being there might be historical since this project was set up back when `pytest` was just ONE FILE and might not have these features yet. For backporting, removing them outright might be too controversial but I am not opposed to removing them in 3.1.

**Comment by bsipocz** [comment]
>I don't know the history but they being there might be historical since this project was set up back when pytest was just ONE FILE and might not have these features yet. For backporting, removing them outright might be too controversial but I am not opposed to removing them in 3.1.

I don't know the history either, but OK with doing the backports given that it will fix the issue on the LTS branch, too rather that we ship two different, but equally API changing solutions to the problem.

**Comment by pllim** [comment]
No one is objecting to outright removing them for backport on `astropy-dev` list. Shall we?

**Comment by drdavella** [comment]
Just to clarify my earlier question: I'm really asking whether the configuration plugin is still useful at all, or whether we can just remove it and ignore this issue. I've never used either of these options as part of my testing, but that doesn't mean they aren't useful to anyone else.

**Comment by bsipocz** [comment]
Let's merge this now. The decision to remove it altogether can be done in a separate, follow-up PR, it doesn't need to hold up this one.

On the issue of removal, it seems to be a good idea to me, but it's not a well informed opinion as I have no idea about the usage of the configuration plugin either.

**Comment by bsipocz** [comment]
Thank you @drdavella for the fix!

**Comment by cczhu** [comment]
Thank you @drdavella and everyone who helped troubleshoot this issue!  We'll be sure to update Baseband's dependencies to astropy 2.0.9/3.0.5 once they're released.

**Pull request merged**
