### PR TITLE
DOC: Extends license to 2022

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to extend license max year to 2022.

I mainly want to see how #11844 looks in practice but might as well, though you should not merge this until 2022 is here. 😸 

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will
review this pull request of some common things to look for. This list
is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] If the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by bsipocz** [comment]
> If the milestone set requires a backport to release branch(es), apply the appropriate backport-X.Y.x label(s) before merge.

I would say "at the time of adding the milestone" rather than before merge.

**Comment by astrofrog** [comment]
Do we actually have to include an upper limit to the date? Various discussions I've seen online seem to suggest a copyright just needs to include first date of publication.

**Comment by astrofrog** [comment]
I'm not 100% sure though!

**Comment by pllim** [comment]
🤷

**Pull request closed without merging**
