### PR TITLE
Pickle compound models

### PR DESCRIPTION
**Pull request by embray**
@embray It can be useful to be able to serialize compound models. In my case, I'm using ipython parallel and would like to send them through the network. I'm looking for a way to get the individual models of a compound_model and pickle them and then concatenate them on the other side.

### CODE REVIEW

**Comment by embray** [comment]
@wkerzendorf I've gone ahead and upgraded this issue to a PR, with a proposed fix.
I think this should do it, but I haven't tried it out yet in the context of multiprocessing that you mentioned.  It'd be good if you could give it a try, or at least provide me some sample code for how you're trying to do this with IPython.  The basic pickle example you gave above works now.

**Comment by embray** [comment]
Looks like Python 2.6 didn't like it.  I don't *think* this would be an issue of different pickle protocols, but it may be a Python 2.6-specific bug in pickle.  Need to investigate further...

**Comment by embray** [comment]
Yup, here's where the issue was raised: http://bugs.python.org/issue7689  This is broken before Python 2.7.3.  I'll see if I can find a workaround.

**Comment by embray** [comment]
Well, it looks like this would be very difficult to work around, actually.  For the Python `pickle` module it's a simple enough monkey-patch.  For cPickle, however, (which is widely used) this would be very non-trivial and probably not worth the effort outside a large demand.

I will disable these tests for Python < 2.7.3 and add a known issue.  I can also add something in the code to raise an exception at least when pickling instances of affected objects.

**Comment by wkerzendorf** [comment]
That's great - I'll try it out as soon as possible.

**Comment by wkerzendorf** [comment]
@embray @mdboom works like a charm!! I'm happy for this to merge

**Comment by embray** [comment]
@wkerzendorf Thanks for the confirmation!

**Pull request merged**
