### PR TITLE
Fix #4164 on OSX

### LINKED ISSUE #4164: Overly verbose test result output
A minor annoyance I'm finding since the switch to pytest 2.7.3 in #4027 is that during test running the results for each module list the full path to the module, as found it the temporary test directory, rather than a relative path, like:

```
//tmp/astropy-test-k8ciiv35/lib.linux-x86_64-3.4/astropy/_erfa/tests/test_erfa.py .....
//tmp/astropy-test-k8ciiv35/lib.linux-x86_64-3.4/astropy/analytic_functions/tests/test_blackbody.py ....
//tmp/astropy-test-k8ciiv35/lib.linux-x86_64-3.4/astropy/config/tests/test_configs.py .................
//tmp/astropy-test-k8ciiv35/lib.linux-x86_64-3.4/astropy/constants/tests/test_constant.py ........
...
```

as opposed to

```
astropy/_erfa/tests/test_erfa.py .....
astropy/analytic_functions/tests/test_blackbody.py ....
astropy/config/tests/test_configs.py .................
astropy/constants/tests/test_constant.py ........
...
```

The double slash at the beginning is odd too.  It might in some way be related to a new line showing up at the beginning of the test output that wasn't there before:

```
rootdir: /, inifile:
```

### PR DESCRIPTION
**Pull request by embray**
This is yet another PR for fixing #4164, this time we will ensure that it is fixed on OSX as well.  

The milestone on this PR is v1.1.0, but the fix also needs to be backported to v1.0.x, which I will do with a separate PR.

### CODE REVIEW

**Comment by embray** [comment]
Confirmed this is fixed on OSX: https://travis-ci.org/astropy/astropy/jobs/82977992

One merely cosmetic thing I don't like though, is that this makes the "Running tests in..." part of the test header so verbose as to be unreadable:

```
============================= test session starts ==============================

platform darwin -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.3

rootdir: /private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/astropy-test-NflPiE, inifile: setup.cfg

Running tests with Astropy version 1.1.dev1132.

Running tests in /private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/astropy-test-NflPiE/lib.macosx-10.5-x86_64-2.7/astropy /private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/astropy-test-NflPiE/docs.

Platform: Darwin-13.4.0-x86_64-i386-64bit

Executable: /Users/travis/miniconda/envs/test/bin/python
```

It should be easy to modify the test header though, so that the common rootdir part of each directory in the "Running tests in" line is stripped off.

**Comment by bsipocz** [comment]
:+1 thanks

**Comment by embray** [comment]
Looks like I never actually remembered to backport this.  I'll do that now...

**Comment by embray** [comment]
Well, looks like I *did* backport the relative change in astropy-helpers, but there were also some changes on the astropy side I didn't merge.  I'm not completely sure those changes are necessary though...

**Pull request merged**
