### PR TITLE
BUG: Enable decompression even if format is specified

### PR DESCRIPTION
**Pull request by rosteen**
I noticed while testing https://github.com/astropy/specutils/pull/1113 that the tests to read `xz` files failed if the format for the reader was explicitly set. This minor refactor allows readers to take advantage of the compressed file handling in `get_readable_fileobj` even if the `format` is explicitly set in the `read` call of whatever class is being used, since the check on the input `fileobj` will now always go through `get_readable_fileobj` if a path is input.

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! Would need a test and a change log as well.

**Comment by rosteen** [comment]
> Thanks! Would need a test and a change log as well.

I wasn't 100% sure if this should count as an enhancement or a bug fix, and therefore what version to put the changelog under. Personally I'm leaning toward bugfix that should be backported, but I guess technically this case was never handled.

**Comment by pllim** [comment]
Depends on what "even if format is specified" means? Does all the format support `xz` compression? 🤷

**Comment by pllim** [comment]
If you think it is a bug, feel free to file the change log as bug fix for now and we can go from there. Thanks!

**Comment by rosteen** [comment]
> Depends on what "even if format is specified" means? Does all the format support `xz` compression? 🤷

If you call for example `Spectrum1D.read('tabular_fits_file.fit.xz')`, the code in `registry.core` handles opening the compressed file and then finds the correct format for the result before passing it to the correct reader. However, if you call `Spectrum1D.read('tabular_fits_file.fit.xz', format='tabular-fit')`, then currently the code to open the compressed file gets skipped and the compressed file is sent straight to the `tabular-fits` reader, which fails.

**Comment by pllim** [comment]
OK bug it is!

**Comment by rosteen** [comment]
It seems like this did break a test, I'll look into it tomorrow.

**Comment by pllim** [comment]
`AttributeError: 'CdsData' object has no attribute 'table_name'`

At a glance, looks like `iers.IERS_A.open()` used the wrong reader from registry.

**Comment by pllim** [comment]
It expects `self.table_name` to be pre-populated but that never happened. Hope this helps!

https://github.com/astropy/astropy/blob/62018574e74cda9c4b30b088f4049e01fb403fbd/astropy/io/ascii/cds.py#L215-L217

**Comment by rosteen** [comment]
Unfortunately, clearing that error (on test collection) revealed ~460 actual errors, so this isn't a trivial change and I don't currently have time to work through the farther-reaching implications. I'll try to come back to this if you want to leave it open and perhaps think of a better strategy.

**Comment by pllim** [comment]
That is unfortunate. Do you want to close this PR without merge and open a bug report instead? We have a strict stale bot rule for PRs.

**Comment by pllim** [comment]
In the meantime, is it possible to workaround this problem for your specific use case over at https://github.com/astropy/specutils/blob/main/specutils/io/default_loaders/tabular_fits.py ?

**Comment by rosteen** [comment]
> In the meantime, is it possible to workaround this problem for your specific use case over at https://github.com/astropy/specutils/blob/main/specutils/io/default_loaders/tabular_fits.py ?

Yes, I just removed the `format` specification that was added to the test and caused it to fail. Not a big deal.

**Comment by rosteen** [comment]
> That is unfortunate. Do you want to close this PR without merge and open a bug report instead? We have a strict stale bot rule for PRs.

I couldn't resist continuing to tinker after I said that....leave it open for now 😅

**Comment by pllim** [comment]
Thanks for trying!

**Pull request closed without merging**
