### PR TITLE
Replace use of off_t by size_t in cparser

### LINKED ISSUE #5497: astropy.test() has error Segmentation fault (core dumped)
Hi guys,

After running astropy.test() have the error:
../../usr/local/lib/python2.7/dist-packages/astropy-1.3.dev16418-py2.7-linux-i686.egg/astropy/coordinates/tests/test_funcs.py ..Segmentation fault (core dumped)

Could you recommend something?

### PR DESCRIPTION
**Pull request by saimn**
Should fix #5497, see there for discussion.

### CODE REVIEW

**Comment by MSeifert04** [comment]
hm, why didn't CircleCI pick up this PR?

**Comment by astrofrog** [comment]
@MSeifert04 - ah, there was a setting that needed to be enabled - done now

**Comment by astrofrog** [comment]
Let's see if the good old fashioned close/open triggers it

**Comment by astrofrog** [comment]
Yay \o/

**Comment by saimn** [comment]
@astrofrog - Great, and the tests now pass on CircleCI 😃

**Comment by astrofrog** [comment]
@saimn - great, thanks!

**Pull request merged**
