### PR TITLE
Memory leak reading and copying bin table FITS files with io.fits

### PR DESCRIPTION
**Pull request by embray**
The following code leaks memory when run (on python 2.7, astropy master, OS=linux)

```python
import astropy.io.fits as pyfits

def readfile(filename, checkshape):
    hdus = pyfits.open(filename)
    # Without copy() there is no leak.
    dat = hdus[1].data.copy()
    hdus.close()

    for colname in dat.dtype.names:
        # When checkshape is False there is no leak
        if checkshape:
            dat[colname].shape == 0

# wget http://hea-www.harvard.edu/~aldcroft/tmp/memtest.fits.gz
filename = 'memtest.fits.gz' 
while True:
    print 'Reading'
    readfile(filename, checkshape=True)
```

I'm guessing that accessing the `shape` attribute is not really the problem but presumably it triggers some action that causes the leak.  The workaround I used for this is effectively:
```python
dat = np.array(hdus[1].data, copy=True)
```
(Though I discovered that pyfits is doing some nice magic with a FITS boolean-vector field, so in reality I had to do something a little more complicated).

### CODE REVIEW

**Comment by taldcroft** [comment]
@embray - is this at all relevant any more?  Can I just close this?

**Comment by embray** [comment]
I think it's still relevant--it cuts to the core of Numpy's unicode issues.

**Comment by embray** [comment]
This appears to still be an issue on Python 3.  Haven't tried on Python 2 yet.

**Comment by embray** [comment]
Yeah, definitely still an issue on Python 2 as well :\

**Comment by embray** [comment]
Very interesting.  Without the `.copy()` there is no leak, no objects created in the frame of the function call are left in memory.  *With* the `.copy()` not only are objects sticking around, but in fact there are 25 `FITS_rec` objects.  I don't understand why so many `FITS_rec` objects get created, and it's not obvious what's keeping them around...

**Comment by embray** [comment]
I think I've made some progress on this.  At the very least I've tracked down why so many extra `FITS_rec` objects are being created.  This may have something to do with why reference cycles are being created.  Will know more tomorrow.

**Comment by embray** [comment]
I just pushed an entirely new fix for this issue (which depends on #4514).

Believe it or not, despite the age of this issue, the root problem was essentially the same (and has actually grown more severe, I think).  The issue applies to both Python 2 and 3.  This should fix the issue more thoroughly than my original fix, and without any noticeable performance impacts.

One thing I am still slightly mystified by is the role of `.copy()`.  I feel like this issue should not have depended on it, but I could be wrong.

**Comment by embray** [comment]
Turns out this is actually far from the end of the reference cycles..... :sob:

**Comment by embray** [comment]
Okay, I'll probably merge this and open another issue for the other known memory leak.  Fixing the other one is probably not worth the effort compared to deprecating the old `FITS_rec` / `ColDefs` interface in favor of full replacement with `Table`.

**Comment by embray** [comment]
Oops, I forgot to update the changelog entry again (I saw the changelog entries from #4514 and assumed I had).

**Pull request merged**
