### PR TITLE
Update run-time requirements to exclude Numpy 1.22 and later on i386

### PR DESCRIPTION
**Pull request by astrofrog**
### Description

The wheels builds for i386 currently time out I think because Numpy 1.22 no longer includes wheel for i386. Since we aren't going to be testing against source builds of Numpy 1.22+ on i386 I think the cleanest solution is to actually update our run-time requirements to exclude Numpy 1.22 and later on i386. While this may seem heavy handed, I think it might actually make sense if we aren't really supporting/testing it anyway. But I'm curious what people think?

We might also simply want to drop support for i386 but that decision should be made separately as we still need a fix for 5.0.x.

**Do not merge until temporary commit is removed!**

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Is there any use case where someone would forcefully build numpy 1.22.* from source on 32-bit anyway and then wants to install latest astropy?

**Comment by astrofrog** [comment]
Well in terms of backporting, Numpy 1.22 didn't exist at the time of 5.0 so it's not like we are really removing something that was possible at the time of the 5.0 release. I'm open to better solutions though and I'll continue investigating on my side.

**Comment by saimn** [comment]
I think we should follow Numpy and remove linux 32 bit wheels in 5.1. For 5.0 backporting this PR makes sense.

**Comment by astrofrog** [comment]
Hmm for some reason Numpy 1.22 is still getting picked up in the i386 wheels, so I'll need to dig deeper

**Comment by pllim** [comment]
Since this has temporary commits and pending investigation, I converted this to draft PR for now. Thanks!

**Comment by astrofrog** [comment]
Closing in favor of #12748

**Pull request closed without merging**
