### PR TITLE
Check if the ascii reader locale test pass

### PR DESCRIPTION
**Pull request by saimn**
Related to #4832: check on travis if this test is now run (and fails ?)

### CODE REVIEW

**Comment by saimn** [comment]
Ok, it fails with `assert 'f' == 'f1'`, so now the test is run: https://travis-ci.org/astropy/astropy/jobs/131400890#L1771

**Comment by saimn** [comment]
Hmm, using `str('de_DE')` I managed to get only the os build fail. So I changed to `str('de_DE.UTF-8')` which I think is more correct, and with this all the linux builds are failing on `assert 'f' == 'f1'`, which is good, BUT the os build is now failing on other tests (`test_pformat_roundtrip` and `test_default_missing`) ...

**Comment by pllim** [comment]
@saimn , any chance #4946 can fix some of the failed tests here?

**Comment by saimn** [comment]
@pllim - I would say no, here the issue is during the parsing of the strings, not the printing (and it is only ascii).
The failures on OSX are a consequence of using `'de_DE.UTF-8'` instead of `'de_DE'`, but as it fails on other tests than the one with setlocale, so it must be a side effect of the try/except at the top of the file.

**Comment by pllim** [comment]
Does explicitly import `from __future__ import unicode_literals` change anything? I find it confusing that all the source codes use it but not the tests.

**Comment by pllim** [comment]
Also, I *think* the fix I have changes how parsing works as well, not just printing?

**Comment by saimn** [comment]
Have to go, just a link to the OSX test failures for easier access:
https://travis-ci.org/astropy/astropy/jobs/131433673#L3689

**Comment by saimn** [comment]
@pllim - The test files that have a `# TEST_UNICODE_LITERALS` comment are tested with and without `unicode_literals`, with a magic plugin: 
https://github.com/astropy/astropy/blob/master/astropy/tests/pytest_plugins.py#L648

Your changes on pprint should not affect this, but at this point, I'm quite confused by the side effects of the changes I am making. For instance, I tried to avoid the setlocale calls during import, and move everything in the test itself (https://github.com/astropy/astropy/pull/4955/commits/21cd20d4e5a86a39906767e83a5315673a22bd73), and with this all the tests that read a file in the `t/` subdirectory are failing. WTF, it seems that the current working directory changed ...

**Comment by saimn** [comment]
Ok, found the issue with `t/`, I played with setup/teardown function and forgot to put back the ones imported from `.common`. So I changed the kind from `f1` to `f`, which fixes the `test_non_C_locale_with_fast_reader`. But there is still an issue with `pformat` on OSX.

**Comment by saimn** [comment]
Ok, tests are now passing (AppVeyor failure is unrelated), so here is a quick summary:

- There are two test files that were trying to set a locale at import time to see if locales are available (`io/ascii/tests/test_read.py` and `utils/tests/test_misc.py`). And these tests were not resetting the locale to the original one, so this was having some side effects.
- Locales were sometimes set with `locale.setlocale(locale.LC_ALL, 'de_DE')` and unicode literals, which fails on Python 2 (where `setlocale` expects a str, not unicode). And without encoding, it also fails on Linux.
- Because of the previous point, the `test_non_C_locale_with_fast_reader` (#4832) was probably never run on Travis, which explains why the failure appeared later (in #4832). Once this test is run, fixing it is just a matter of changing the expected `kind` from `f1` to `f`.
- Changes from this PR should also fix #4896, where random German error message are shown, which must be related to the `setlocale` calls (see above).
- Once I removed the `setlocale` calls at import time (only in 2 test files), I starting to have tests failing on the MacOS builds, because `Table.pformat` was truncating its output. [Example](https://travis-ci.org/saimn/astropy/jobs/132484117#L3862) where `setlocale` was removing from `test_misc`. Further investigations [showed](https://travis-ci.org/saimn/astropy/jobs/132403687#L3180) that, for some unknown reason :fearful: , `astropy.utils.console.terminal_size` was returning `(0, 0)` for the terminal size ... I don't know what is the link between the removal of `setlocale` and this change of behavior fron `ioctl`, but finally I ended up handling this `(0, 0)` special case ...

@pllim , @astrofrog - Could you run the tests with this branch to check if it fixes the errors you had locally ?

**Comment by pllim** [comment]
@saimn , my German error message is gone. Thanks!

Re: terminal size. That's perplexing. By default, it extracts terminal size from `stdout`. Maybe because CI has no real terminals or something? Anyway, good investigation!

**Comment by astrofrog** [comment]
@saimn - great investigative work! 🔍 The tests now pass for me, so I'll go ahead and merge and backport.

**Comment by saimn** [comment]
Thanks :)
BTW, #4832 and #4896 can be closed.

**Comment by taldcroft** [comment]
Belated thanks all from me too.

**Pull request merged**
