### PR TITLE
TST: Do not use conda for OSX

### LINKED ISSUE #10868: TST: Get rid of conda for OSX job on Travis CI
When this is done, this repo will not rely on ci-helpers anymore, except for the tox pinning. See https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to stop using `conda` (and hence `ci-helpers`) for Travis CI setup. OSX is the remaining job that uses it.

Since this is a cron job, I skipped CI here. You can see a previous log proving that it works at https://travis-ci.org/github/astropy/astropy/jobs/736163284 . The failure is unrelated.

Fixes #10868

Exciting sequel to #10860

### CODE REVIEW

**Comment by astrofrog** [comment]
I wonder if it would be better to use homebrew via the addons to make sure we control which version of Python is used and to set up the paths etc automatically? You can do:

```
addons:
  homebrew:
    packages:
    - python@3.8
```

I think.

**Comment by pllim** [comment]
@astrofrog , I don't use Mac and don't know what a homebrew is. Do you want to take over?

**Comment by astrofrog** [comment]
I can investigate

**Comment by pllim** [comment]
Looks like Apple really likes Python 2.7. 😬 
```
  File "/Users/travis/build/astropy/astropy/.tox/.tox/lib/python2.7/site-packages/tox_pypi_filter/plugin.py", line 75
    print(f"{venv.name}: Starting tox-pypi-filter server with the following requirements:")
```

**Comment by pllim** [comment]
p.s. If you can't get homebrew to brew something useful, option to revert to my non-brew fix exists, or we can just keep using ci-helpers. 😉

**Comment by astrofrog** [comment]
@pllim - now relies on https://github.com/astropy/ci-helpers/pull/462 - if that is merged I'll then remove the TMP commit here about ci-helpers and make sure it works.

**Comment by embray** [comment]
I'm still not sure why you want to do it without conda.  Using conda would make the CI consistent across all three platforms and reduce maintenance burden.

**Comment by astrofrog** [comment]
@embray - we've had no end of issues with conda in the last few years, https://github.com/astropy/ci-helpers/issues/463 is just the latest one...

**Comment by astrofrog** [comment]
Avoiding conda if possible was discussed at the Socorro coordination meeting in 2019 and the following resolution was unanimously approved by all present:

https://docs.google.com/document/d/1pO0giLKGEle5rJeyxhc33rIARY_e_naLiYprScROP84/edit

> Use pip rather than conda for most CI builds by default: policy on whether CI should include conda builds (basically the question is, would people object to e.g. pip-only CI workflows if it was faster, since really conda packages should get tested during the conda build process, in the same way that e.g. debian packages get tested during debian packaging). Approved

**Comment by pllim** [comment]
@astrofrog , I merged astropy/ci-helpers#462 . Do you want to wrap this up? 🚀

**Comment by astrofrog** [comment]
Yes will wrap this up now - first checking CI passes then will remove last commit.

**Comment by astrofrog** [comment]
@pllim - I think this should be ready

**Comment by pllim** [comment]
@astrofrog , this is still technically my PR, so I cannot approve it. 😆

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
Looks good, so I'm merging

**Comment by pllim** [comment]
Thanks, @bsipocz !

**Pull request merged**
