### PR TITLE
remove clean_parse_tables.py (to be moved to astropy-tools)

### PR DESCRIPTION
**Pull request by eteq**
This PR removes the ``dev/clean_parse_tables.py`` file, as a companion to astropy/astropy-tools#8, which adds it to astropy-tools.

Does this seem reasonable, @mdboom ?  It looks to be like this dev directory was added in #4003 for just this file, and it looks to me like this script fits better with the other tools in astropy-tools as a "script which is useful for developing astropy, but not necessary for the package itself".  Does that sound right, or is there a reason why ``clean_parse_tables.py`` should stay in the core vs astropy-tools?

(Note that I'm milestoning this v1.1 because I think we don't want ``dev`` to appear in the repo and then disappear again later)

### CODE REVIEW

**Comment by embray** [comment]
:+1:

**Comment by embray** [comment]
Perhaps this should be accompanied with a few comments in the relevant source files as to where to get this script, and that it should be run when updating the parser/lexers.

**Comment by eteq** [comment]
@embray - good point - how about the README I just added?

**Comment by eteq** [comment]
@astrofrog - this seems really weird... ``coveralls`` said coverage decreased, but the only change here is *removing* code that definitely was not being tested.  So the denominator should shrink and therefore coverage should have *increased*, right?

Not important for the PR itself, but possibly signifying a coveralls issue?

**Comment by embray** [comment]
The readme isn't too helpful because who would know to go looking for it?  It's not in a place where anyone would look when making updates to the parsers.  Instead it would be good to just have a short comment directly in the code such as in this file: https://github.com/astropy/astropy/blob/master/astropy/units/format/cds.py#L27

**Comment by embray** [comment]
Additionally, mixing our own files with vendored code is confusing.

**Comment by eteq** [comment]
@embray - so you're thinking *everywhere* that there's a lextab/parsetab?

I confess I don't really understand when/how those files are generated, so I could be confused.  If you (or @mdboom) have a specific idea of where this is most likely to be recognized, a PR to my branch might be fastest. 

Or maybe the best solution is for someone (probably shouldn't be me given the above...) to add a developer doc along the lines of "Upkeep of PLY-generated files in astropy"?

**Comment by embray** [comment]
It's only used in a handful of files:

https://github.com/astropy/astropy/blob/c7099d60a1d38b6074801d528ad069f4d06a8202/astropy/units/format/cds.py

https://github.com/astropy/astropy/blob/c7099d60a1d38b6074801d528ad069f4d06a8202/astropy/units/format/generic.py

https://github.com/astropy/astropy/blob/c7099d60a1d38b6074801d528ad069f4d06a8202/astropy/units/format/ogip.py

https://github.com/astropy/astropy/blob/c7099d60a1d38b6074801d528ad069f4d06a8202/astropy/coordinates/angle_utilities.py

Just a copy/pasted comment near the top of all of those files should suffice.

**Comment by bsipocz** [comment]
@eteq - Re ``coveralls``: we saw this before with other PRs, too (e.g. #3628). My best guess was that the issue is somewhat related that the coverage changed between the base of this PR and the top of master, and the change this PR introduces is negative compared to that.

If this right, rebasing this should make the fail go away (given that no change happens in master in the meantime).

**Comment by eteq** [comment]
OK, is this what you mean, @embray (the commit I just pushed up)? Again, I really don't understand what PLY/lex/yacc are doing and where the files get generated, so I just sort of made this up...

**Comment by embray** [comment]
This is fine.

**Comment by eteq** [comment]
Alright, I'll go ahead and merge.

**Comment by eteq** [comment]
backported to v1.1.x in c8f65a04c8fa68977ca84c197b0dd730ff4b7f58

**Pull request merged**
