### PR TITLE
Improve behaviour when cache is in wrong format

### LINKED ISSUE #9607: cache issue: dbm.error: db type is dbm.gnu, but the module is not available
I switched from one Python environment to another (pip-based to conda-based) and ended up with the following error when trying to run a script:

```
WARNING: /home/tom/Code/astropy/examples/io/fits-tables.py failed to execute correctly: Traceback (most recent call last):                                                                             
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage
    out = func()
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__
    exec(self.code, self.globals)
  File "/home/tom/Code/astropy/examples/io/fits-tables.py", line 35, in <module>
    event_filename = get_pkg_data_filename('tutorials/FITS-tables/chandra_events.fits')
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/site-packages/astropy/utils/data.py", line 627, in get_pkg_data_filename
    conf.dataurl_mirror + data_name])
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/site-packages/astropy/utils/data.py", line 1186, in download_file
    pkgname=pkgname)
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/site-packages/astropy/utils/data.py", line 1819, in import_file_to_cache
    with _cache(pkgname, write=True) as (dldir, url2hash):
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/site-packages/astropy/utils/data.py", line 1642, in _cache
    shelve.open(urlmapfn, flag="c") as url2hash:
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/home/tom/miniconda3/envs/py36/lib/python3.6/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available
```

I wonder if this should just be a warning and result in the file being re-downloaded rather than have a hard failure like this? I don't think the average user would realize the best fix is to remove the cache.

cc @aarchiba

### PR DESCRIPTION
**Pull request by aarchiba**
Closes #9607

### Description

This pull request is to handle the situation where the user has an Astropy cache from one python interpreter (usually with the `gdbm` module) but is trying to access it from a python interpreter without the appropriate module (for example `conda` does not package `gdbm`). This PR ensures that `download_file` works, albeit without using the cache, and that a warning explaining the problem and suggesting a fix is emitted.

### CODE REVIEW

**Comment by pllim** [comment]
So, we're at a weird place now that this can either go in 4.0 or 4.0.1. If the former, there is no need of a change log. But for the latter, you will need one. I'll let @bsipocz decide.

@astrofrog , does this fix the problem that you reported?

**Comment by bsipocz** [comment]
Let's go with affects-dev. It this gets merged after 4.0 is out, there is still opportunity to add a changelog.

**Comment by aarchiba** [comment]
We could do more - I could add a config option that selected which format to create new cache shelves in, so that (say) you could make sure no gdbm-based caches were ever created because you wanted to interoperate with conda installations that did not support that.

**Comment by aarchiba** [comment]
PR #9669 has code to demonstrate how choosing the backend upon creation would work. There it is used only in the test suite.

**Comment by pllim** [comment]
@astrofrog , does this fix the problem that you reported?

**Pull request merged**
