### PR TITLE
NDSlicingMixin Refactor

### PR DESCRIPTION
**Pull request by MSeifert04**
Initial try of NDSlicingMixin Refactor. More informations will follow as soon as the splitting is done.

### CODE REVIEW

**Comment by MSeifert04** [comment]
Summary:
``__getitem__``:

- Before the PR this method tried to slice ``wcs``, ``mask``, ``data`` and ``uncertainty`` if not None. Now this method only slices the ``data`` and lets other methods slice the other attributes.

``_slice``:
- This method calls the different slice methods that slice the attributes. This method is mainly for subclasses that have additional properties that should be considered while slicing.

``_slice_*``:
- Each attribute has a seperate slice method that checks if the property should be sliced (and how). Currently there are some hard restrictions on ``wcs``, ``mask`` and ``uncertainty`` because they need to match the ``data`` shape or will not be sliced. This is because each property uses the slice for the data and I don't know if slicing something that has not the same shape as the data makes sense.

Maybe the slicing of the data could be moved outside ``__getitem__`` too, not sure about that though. If the data-slicing is seperated it could allow slicing with wcs-attributes (like ``Cutout2D class`` does) but that's currently more work than gain since I don't know which parts of the refactoring are kept and which dismissed so I've skipped it.

This one is not backwards compatible since it does not allow slicing in all the cases that were previously possible. But the most common cases (where the shapes are equal such as ``NDDataArray`` enforces) are still possible.

**Comment by mwcraig** [comment]
@MSeifert04 -- at last taking a look at this one.

It seems like there are two major changes:

1. Refactoring of slicing of attributes into separate methods. I gather the motivation for separating out some of the slice methods was to make overriding specific slices easier? So a subclass could, e.g., just override `_slice_mask` but inherit the rest? In the current implementation a subclass must re-implement all of the slicing  in [the current mixin](https://github.com/astropy/astropy/blob/master/astropy/nddata/mixins/ndslicing.py#L18) to change any of it. If I understand correctly, this refactor is backwards compatible.

2. Place restrictions on the type and/or shape of attributes for which slicing is permitted. Here I have more questions/comments/concerns. The first is that the type checks seem out of place in the slicing methods. In current NDData no type checking is done when for the attributes when you create the object so it would be surprising to learn at slice time that the type was incorrect. More broadly, my understanding is that there are use cases of masking for example where the mask is not an array and may not have a shape but can slice itself in a sensible way (maybe the mask is a function for example).

Of the set of changes, 1 seems clearly motivated though I'm expecting there will be some comments on the details.

The set of changes in 2 impose some significant new restrictions without it being clear what the need is. Could you clarify that the need/rationale further?

Thanks!

**Comment by MSeifert04** [comment]
@mwcraig: Thanks for reviewing it.

The main reason for splitting ``__getitem__`` it into several methods was to allow modifying the slicing if extra properties are present, such as flags. I had planned or already uploaded (not sure right now) some documentation about subclassing ``NDArithmeticsMixin`` and ``NDSlicingMixin``): In that case a subclass would only need a:
```
class NDDataSubclass1(NDSlicingMixin, NDData):
    def _slice(self, item):
        kwargs = super(NDDataSubclass, self)._slice(item)
        kwargs['flags'] = self._slice_flags(item)
        return kwargs

    def _slice_flags(self, item):
        # Slice the flags
        return sliced_flags
```
On the other hand modifying for different types of properties (this goes to your second point) the person only needs to modify the corresonding slice method like
class NDDataSubclass2(NDSlicingMixin, NDData):

```
class NDDataSubclass2(NDSlicingMixin, NDData):
    def _slice_mask(self, item):
        if isinstance(self.mask, FancyType):
             return self.mask[item]
        # Allow the other types as well:
        return super(NDDataSubclass, self)._slice_mask(item)
```

The idea behind the type checks was, that many things allow slicing especially one dimensional Slicing (tuples, lists, ...) if the type is never checked just trying to slice it would yield some strange results. I faced that with my first 'mask' because I just had a dict (which is not sliceable, but I wanted to keep track why I masked a pixel) and I had to edit the complete ``__getitem__`` method to get rid of that (giving me the idea of seperating the slicing of the properties into different methods). I kept the original idea of ``NDData`` that the mask is not checked (https://github.com/MSeifert04/astropy/blob/nddata_nddatabase/astropy/nddata/nddata.py#L289). 
Other than whitelisting (with typechecks in the slice-method) or a check while setting the mask and/or initializing the mask or a seperate verification method there is no way to predict the outcomes/downsides when other people use it. But I'm also involved in webdesigning and there whitelisting ist the way to avoid security breaches and unexpected results. This may have influenced me here. If you (and/or the others) want a simple ``try ... except ...`` or just ``return self.mask[item]`` I can change it.

Also I'm using an additional method in my personal subclasses that can also slice "broadcastable" (though with a different shape than ``data``) properties. If you would be interested I can add/present it but for starters I wanted to avoid the overhead.

**Comment by MSeifert04** [comment]
In case this might be considered for the 1.2 release I've rebased it and made the slicing less restrictive while keeping the original method-structure.

**Comment by MSeifert04** [comment]
@mwcraig Do you think this PR should be included in 1.2? Or rejected? Or postponed?

**Comment by mwcraig** [comment]
@MSeifert04 I somehow managed to miss the changes you made a couple weeks ago. With those changes the behavior becomes, I think, basically what it was before, with warnings given if the slices fail, and lays the groundwork for stricter checks in the future.

Will do once last quick review, then merge if it looks good.

**Comment by mwcraig** [comment]
@MSeifert04 -- looks good. Am I correct that this does not change the previous slicing behavior (i.e. no changelog), or does it change behavior?

**Comment by MSeifert04** [comment]
@mwcraig Let me test merging this locally. And changelog ... this probably needs a changelog but I fear that will conflict with #4876

**Comment by MSeifert04** [comment]
I also have some narrative documentation and docstring fixes for this PR. If you want to merge it I'd rebase #4876 again and include them there. I have 1 additional (small) change I wanted to do there nevertheless.

**Comment by mwcraig** [comment]
Since the time is late, what if we postpone this to the first bug-fix release and just remove the incorrect parenthetical comment from #4876?

**Comment by MSeifert04** [comment]
@mwcraig Your call. I tested it locally and it passes.

**Comment by astrofrog** [comment]
Documentation fixes and bug fixes are fine after the feature freeze deadline of course and will still make 1.2 :)

**Comment by mwcraig** [comment]
In that case I can finish grading tonight 😬  and review in the morning 😀

**Comment by MSeifert04** [comment]
@mwcraig Now I'm confused. Do you mean reviewing the documentation I have for this PR or reviewing this PR? Should I hurry to find the narrative documentation parts and plug them in or won't it be included in 1.2 and I can do it in a few days?

**Comment by mwcraig** [comment]
I'll get this merged, then will merge the current doc build (rebase if needed).  I don't think this needs extensive narrative docs, but if you want to add done we can do that in a separate small PR  in the next couple of days

**Comment by mwcraig** [comment]
I'm going to merge this, then, if there are no conflicts, the large doc pull request. I'll do a changelog entry in the morning, and we can fix the docs early next week.

**Pull request merged**
