### PR TITLE
Revert "Fix IERS_Auto logic now that IERS-A is bundled"

### PR DESCRIPTION
**Pull request by neutrinoceros**
temporarily revert astropy/astropy#16187
see https://github.com/astropy/astropy/issues/16693 for details

### CODE REVIEW

**Comment by neutrinoceros** [comment]
I'm seeing some surprising (and seemingly related) errors within allowed_failures. I can't take another look before tommorow so please make sure you understand what's happening there if you're going to merge this.
Let me also ping @ayshih for visibility.

**Comment by ayshih** [comment]
I don't understand the failures here, so I'm hoping that a server just happened to be down at the time of the CI runs.  This reversion PR should be mooted by the fixes in #16697

**Comment by pllim** [comment]
Thanks! I would prefer #16697 but let's see how the CI fares over there first.

**Comment by neutrinoceros** [comment]
Yes this one iss definitely not more than a plan B, thanks @ayshih for coming up with an actual fix !

**Pull request closed without merging**
