### PR TITLE
Configure flake8 import ignores for __init__.py

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

This PR is part of breaking apart #13754 into smaller less controversial parts.

This PR fixes all the `flake8` warnings for import issues in `__init__.py` files by ignoring them specifically for `__init__.py` files, instead of adding a large number of `# noqa` comments or making other changes as requested by @astrofrog. 

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
I agree with @nstarman's https://github.com/astropy/astropy/pull/13754#issuecomment-1265403770 about explicit imports. However, that will require considerably more work in the mean time I suggest we move to this global ignore of `*` import warnings for `__init__.py` files. If/when we do what to address making our imports explicit removing `F403` from the [`setup.cfg`](https://github.com/WilliamJamieson/astropy/blob/697d53b382f2a5986be0076ef574c65890731952/setup.cfg#L169) will point very clearly at most of the `*` imports that should be fixed.

**Comment by mhvk** [comment]
Very happy with this intermediate step!

**Review by nstarman — APPROVED** [review]
Looks good! Maybe just open an Issue to flag that these should eventually be fixed and in-ignored?

**Comment by mhvk** [comment]
Let's get this in -- it is a nice step and seemingly was held back only because the label checker had failed for some reason. Rerunning that solved it.

**Pull request merged**
