### PR TITLE
Test: fix using numpy nightlies

### PR DESCRIPTION
**Pull request by saimn**
It seems Numpy nightlies are no more used if the dev job, which could be due to the fact that numpy now uses manylinux_2_17. So we need a more recent version of pip.

### Description

This pull request is to address ...

Fixes #<Issue Number>

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by saimn** [comment]
Nope, it still install numpy==1.22.2 ...

**Comment by saimn** [comment]
Actually their wheels are `manylinux_2_17_x86_64.manylinux2014_x86_64.whl` so still supporting manylinux2014, pip version should not be the issue. Maybe a tox issue ?

**Comment by saimn** [comment]
Found a solution:
```
  Downloading https://pypi.anaconda.org/scipy-wheels-nightly/simple/numpy/1.23.0.dev0%2B782.g1168868df/numpy-1.23.0.dev0%2B782.g1168868df-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 49.3 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.2
    Uninstalling numpy-1.22.2:
      Successfully uninstalled numpy-1.22.2
Successfully installed numpy-1.23.0.dev0+782.g1168868df
```
So `indexserver` is deprecated (in tox), and they plan to remove it (https://tox.wiki/en/latest/example/basic.html#using-a-different-default-pypi-url) but I don't know it stopped working. Their solution with `PIP_INDEX_URL` doesn't work (matplotlib installation was crashing) so I used a `pip install` instead.

**Comment by pllim** [comment]
RTD is stuck again, sigh

**Comment by pllim** [comment]
@meeseeksdev backport to v5.0.x

**Pull request merged**
