### PR TITLE
Report maximum relative and absolute tolerance in FITS diff

### PR DESCRIPTION
**Pull request by astrofrog**
With this PR, the FITS diff infrastructure now reports the maximum relative and absolute differences, as otherwise it's hard to know how different the data really are (this is similar to what ``assert_allclose`` reports):

```
E               b> 185.3959962497532
E            Data differs at [53, 11]:
E               a> 221.78221524621446
E               b> 221.78228090660704
E            ...
E            6104 different pixels found (37.26% different).
E            Maximum relative difference: 4.891022444723928e-07.
E            Maximum absolute difference: 278.7475541463714.
```

@saimn - are you on board with this? If so I can extend to the other HDU types, add a changelog entry and tests.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by astrofrog** [comment]
Very strange! Where is that from?

**Comment by astrofrog** [comment]
Is something checking just the last four lines?

**Comment by pllim** [comment]
* `astropy/io/fits/tests/test_fitsdiff.py::TestFITSDiff_script::test_manydiff`
* `astropy/io/fits/tests/test_fitsdiff.py::TestFITSDiff_script::test_outputfile`
* `astropy/io/fits/tests/test_fitsdiff.py::TestFITSDiff_script::test_rtol_diff`

**Comment by astrofrog** [comment]
Yes it was checking just the last four lines:

```
        assert out.splitlines()[-4:] == [
```

**Comment by astrofrog** [comment]
I think the tests should pass now. I've added a changelog entry. I decided to just focus on Primary/Image HDUs for now and not table HDUs, as the reporting is a little more complex for the latter (it might be we should report maximum differences for each column separately for the results to be meaningful).

**Comment by astrofrog** [comment]
pre-commit.ci autofix

**Comment by pllim** [comment]
LGTM but I'll let Simon approve. Thanks!

**Review by saimn — APPROVED** [review]
Looks good, thanks !

**Pull request merged**
