### PR TITLE
Remove some deprecated things from astropy.coordinates

### PR DESCRIPTION
**Pull request by adrn**
This removes the old frame attribute classes (deprecated since v3.0), and the `EarthLocation` attribute names `longitude`/`latitude` (deprecated since v2.0).

### CODE REVIEW

**Comment by pllim** [comment]
Does this check off a box at #8888 ?

**Comment by adrn** [comment]
@pllim Yep!

**Comment by adrn** [comment]
Cool, rebased

**Comment by bsipocz** [comment]
Thanks @adrn!

**Pull request merged**
