### PR TITLE
Add intersphinx links and cleanup text in 'What's new in 5.0?'

### PR DESCRIPTION
**Pull request by astrofrog**
### Description

Cleanup of the 'What's new in 5.0?' ahead of final release.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
I don't know why two of the contributors at the bottom of this page is indented a little but it is out of scope. LGTM otherwise. Thanks!

https://astropy--12476.org.readthedocs.build/en/12476/whatsnew/5.0.html

**Comment by astrofrog** [comment]
Yeah I have no idea why that is happening!

**Comment by saimn** [comment]
`E.` is interpreted as an enumerated list: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#enumerated-lists
So dots should be escaped I guess.

**Comment by astrofrog** [comment]
@saimn - ah thanks for figuring that out! I've pushed a commit that should fix this.

**Pull request merged**
