### PR TITLE
fix passing of kwargs to optimizers

### LINKED ISSUE #4611: verblevel keyword of SLSQPLSQFitter() unrecognized
In modeling.fitting, the documentation for **SLSQPLSQFitter()** specifies a **verblevel** keyword argument to control the level of console output:

> 0-silent 1-print summary upon completion, 2-print summary after each iteration

However, when **SLSQPLSQFitter()** passes this keyword on to scipy's **fmin_slsqp()**, as in

`fit_ellipse = fitting.SLSQPLSQFitter()`
`ellipse_sol_try1 = fit_ellipse(ellipse_init, xx, yy, thresh_map, verblevel=0, epsilon=0.5)`

will trip an error since the keyword is unrecognized by fmin_slsqp(). Looking up the fmin_slsqp() interface, the correct keyword to set the verbosity level is **disp**:
[http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.optimize.fmin_slsqp.html](http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.optimize.fmin_slsqp.html)

It appears that in at least one old astropy version (v0.3), verblevel was handled properly, since it initializes an intermediate parameter named disp. This coversion to give fmin_slsqp() the disp keyword seems to have been dropped.

In any case, one can get the expected behavior by using the disp keyword directly in the caller:
`ellipse_sol_try1 = fit_ellipse(ellipse_init, xx, yy, thresh_map, disp=0, epsilon=0.5)`

### PR DESCRIPTION
**Pull request by nden**
Closes #4611

### CODE REVIEW

**Comment by bsipocz** [comment]
@nden - Could you please add a changelog entry?

**Comment by nden** [comment]
@bsipocz done and merging

**Comment by ycopin** [comment]
I think these changes somehow break previous behavior, and should therefore be stated more explicitly. I used to propagate the verbosity flag `disp` in the `kwargs` (the one expected by `scipy.optimize.fmin_slsqp`), and this now ends up in error with:
```
  File "/data_sys/ycopin/Dropbox/Science/Euclid/Emilines/statistics.py", line 129, in __call__
    self.objective_function, p0, farg, **kwargs)
  File "/data/ycopin/Softs/local/lib/python2.7/site-packages/astropy/modeling/optimizers.py", line 231, in __call__
    full_output=True, **kwargs)
TypeError: fmin() got multiple values for keyword argument 'disp'
```
One should now use the `verblevel` keyword, as mentioned in the doc. Wouldn't it be more sensible to change the doc to match last version's working behavior?

**Comment by nden** [comment]
@ycopin Sorry, my bad. The goal was to use the same keyword with all fitters but I see that in fixing one problem I created a different one. 
Given the state of things would it be sufficient to allow either `verblevel` or `disp` as input to `SLSQP`?

**Comment by ycopin** [comment]
I think it would be better to simplify the code, by allowing a single well-documented keyword, and stick to it, and letting people know, maybe with a DeprecationWarning. My 2 cents...

**Comment by pllim** [comment]
I think this should be a new issue, otherwise it is buried in a merge PR and hard to find.

**Comment by nden** [comment]
@pllim Agreed. I'll make a PR asap.

**Pull request merged**
