### PR TITLE
Removed some unnecessary list creations

### PR DESCRIPTION
**Pull request by MSeifert04**
This removes some unnecessary list creations in cases like: `for _ in list(six.iter____())` or `any([_ for _ in xxx])`.

### CODE REVIEW

**Comment by MSeifert04** [comment]
@pllim I think the enhancement label is wrong. If anything this could be about performance (even if it's probably not noticable).

**Comment by pllim** [comment]
Ok. But I wonder if we should separate out the bug fix, since bug fix and performance milestones are usually different...

**Comment by MSeifert04** [comment]
I was thinking the same (I just wasn't sure if the function itself is dead code). I'll seperate these because the `signal_number_to_name` is actually used in https://github.com/astropy/astropy/blob/master/astropy/utils/xml/validate.py#L53

**Comment by MSeifert04** [comment]
@pllim Sorry, it's the labels again: The Python3 label seems incorrect now that the python3 bugfix is in #5430.

**Comment by mhvk** [comment]
Looks good to me! (And am happy to merge if this is now ready.)

**Comment by MSeifert04** [comment]
@mhvk I don't know what you mean by ready, but from my part I think it is.

**Comment by mhvk** [comment]
It just seemed changes were still being made, but if it is ready now, it is going in!

**Comment by MSeifert04** [comment]
@mhvk There might be other instances of unnecessary list/tuple/set creations in the code but these were the ones I found using regular expressions.

**Pull request merged**
