### PR TITLE
Change relative import to absolute one

### PR DESCRIPTION
**Pull request by mhvk**
Should fix https://github.com/astropy/astropy/pull/11127#issuecomment-819251611

### CODE REVIEW

**Comment by mhvk** [comment]
@pllim - how do I test that `pyinstaller` works on this?

**Comment by pllim** [comment]
Thanks! I started the cron jobs. Now we just have to wait...

**Comment by pllim** [comment]
pyinstaller is green again! But while we're at it, let's see about those "exotic" archs too.

**Comment by mhvk** [comment]
OK, so just the `extra ci` label. Good to know! (and really nice way to handle it!!!)

**Comment by pllim** [comment]
Yes, it was @Cadair 's idea with that label!

**Comment by pllim** [comment]
Hmm... This is also related maybe but in a different "exotic" arch.

```
__________________________ test_masked_repr_explicit ___________________________

    def test_masked_repr_explicit():
        sa = np.array([(1., 2.), (3., 4.)], dtype='f8,f8')
        msa = Masked(sa, [(False, True), (False, False)])
>       assert repr(msa) == ("MaskedNDArray([(1., ——), (3., 4.)], "
                             "dtype=[('f0', '<f8'), ('f1', '<f8')])")
E       assert "MaskedNDArra...f1', '>f8')])" == "MaskedNDArra...f1', '<f8')])"
E         Skipping 41 identical leading characters in diff, use -v to show
E         - =[('f0', '<f8'), ('f1', '<f8')])
E         ?           ^              ^
E         + =[('f0', '>f8'), ('f1', '>f8')])
E         ?           ^              ^

astropy/utils/masked/tests/test_masked.py:1090: AssertionError
```

**Comment by mhvk** [comment]
Oops, yes, definitely related.... I'll fix that one here too.

**Comment by mhvk** [comment]
@pllim - there are still a lot of failures, but none seem related. I think all but ppc64le may be fixed if I rebase, but I wonder if it is worth it, and if it doesn't make more sense to just merge this, since the changes I made are now tested to be correct.

**Review by pllim — APPROVED** [review]
You can ignore the unrelated failures. Thanks!

**Pull request merged**
