### PR TITLE
Add WCS slicing to nddata slicing mixin.

### PR DESCRIPTION
**Pull request by DanRyanIrish**

### CODE REVIEW

**Comment by MSeifert04** [comment]
I had a quick look but it's really complicated to review this without having additional context:

- What use-case is addressed here?
- Would it be possible to include more in-line comments about *why* the implementation is like that? At some places I'm really confused.

**Comment by mwcraig** [comment]
@DanRyanIrish --my apologies, this is going to end up slipping to the 3.2 release. The good news is that, if I don't get to it sooner, I'll work on it at the astropy coordination meeting in December.

**Comment by bsipocz** [comment]
@mwcraig - Shall we move the milestone to 4.0 or you plan to work on this in the coming 2 days?

**Comment by mwcraig** [comment]
Moving to 4.0 😞

**Comment by bsipocz** [comment]
@DanRyanIrish @mwcraig - Any plan to get this finished for 4.0?

**Comment by mwcraig** [comment]
Yes, on my list for pyastro19....

**Comment by Cadair** [comment]
This has been rather overtaken by events given that #8546 and #8409 now exist, so we probably need to rethink this.

**Comment by mwcraig** [comment]
At a minimum I should make sure all of the nddata tests use an actual WCS for the wcs property.

**Comment by bsipocz** [comment]
Either case, it would be great to eventually  remove the `keep-open` label :)

**Comment by bsipocz** [comment]
@mwcraig - any update on this?

**Comment by mwcraig** [comment]
This should be closed, it has been superceded by  #9067

**Pull request closed without merging**
