### PR TITLE
Use new YAML dumper in ECSV

### LINKED ISSUE #5604: ecsv files fail to write with units in metadata
This code fails because of the units in the metadata:
```
from astropy import table, units as u
t = table.Table()
t.meta = {"foo": 5*u.km, "foo2": u.s}
t["bar"] = [7]*u.km
t.write("test.dat", format="ascii.ecsv")
```
Note that either a quantity or a unit will cause the failure.

This is the end of the error messages I'm getting:
```
~/anaconda3/envs/py2/lib/python2.7/site-packages/yaml/representer.pyc in represent_object(self, data)
    408             reduce = copy_reg.dispatch_table[cls](data)
    409         elif hasattr(data, '__reduce_ex__'):
--> 410             reduce = data.__reduce_ex__(2)
    411         elif hasattr(data, '__reduce__'):
    412             reduce = data.__reduce__()

~/anaconda3/envs/py2/lib/python2.7/copy_reg.pyc in _reduce_ex(self, proto)
     68     else:
     69         if base is self.__class__:
---> 70             raise TypeError, "can't pickle %s objects" % base.__name__
     71         state = base(self)
     72     args = (self.__class__, base, state)

TypeError: can't pickle int objects
```

### PR DESCRIPTION
**Pull request by taldcroft**
Fixes #5604.

### CODE REVIEW

**Comment by mhvk** [comment]
@lauralwatkins, @eteq - do you want to have a quick look? It looks fine to me, and I'll merge later today unless I hear otherwise.

**Comment by eteq** [comment]
Hmm, getting a ``NameError: name 'unicode' is not defined`` ...

**Comment by eteq** [comment]
Oh, it's a py3 thing.  Easy fix, will do myself on this branch (and add a relevant test).

**Comment by eteq** [comment]
Just pushed up a fix and a regression test for #5604 - assuming the test pass this should be good to go.

**Comment by mhvk** [comment]
Hmm, that was really a fix to #5603 -- odd that that one passed all tests!

Anyway, agree that this is good to go if tests now pass.

**Comment by eteq** [comment]
I think for whatever reason, this regression test exercises the code from #5603 but before then it wasn't getting coverage?  Not sure why, but there it is anyway.

**Comment by eteq** [comment]
Looks like this is passing on everything but the OS X travis, and I already ran that locally, so I'm going to go ahead and merge this.

**Comment by mhvk** [comment]
Actually, it does make some sense: the code gets run only when YAML is a bit older, which is not done on travis. And I think the off-line test was done on python2. Anyway, glad to see it fixed!

**Comment by eteq** [comment]
backported to v1.3.x in 029a4f8fc1c86d6ee81d8bcb1df1753f1c278d59

**Pull request merged**
