### PR TITLE
Error handling in io.fits.compression module

### PR DESCRIPTION
**Pull request by anchitjain1234**
For #3118.

### CODE REVIEW

**Comment by anchitjain1234** [comment]
@embray Is this correct? Also, I am not sure how to test these changes.

**Comment by embray** [comment]
@anchitjain1234 Thanks for the fix--I don't have time to review this right now but ping me in a few days or to remind me.

**Comment by anchitjain1234** [comment]
ping @embray.

**Comment by eteq** [comment]
@embray - do you think this looks good?  The tests are passing and this looks right to me, but I admit I don't understand the underlying origin of #3118 ...

**Comment by astrofrog** [comment]
@embray - this is a ping :) Could you briefly review this?

**Comment by pllim** [comment]
I was hoping to squeeze this into 1.3. It is missing a change log but I cannot take over because this was opened before the new GitHub feature. Ah, well!

The changes (adding some checks and error messages) seem uncontroversial to me, but I am not familiar with the C module. Anyone wants to have another look?

**Comment by astrofrog** [comment]
@pllim - I'm not familiar enough with the C code to review this. If this does get merged we can just add a changelog entry directly in master.

**Comment by mhvk** [comment]
Closing in favour of #5775, which builds on this.

**Pull request closed without merging**
