### PR TITLE
Adress Ruff Rule C416 violations in multiple sub-packages

### PR DESCRIPTION
**Pull request by arthurxvtv**
### Description
Currently the selected files violate Ruff rule C416:

- astropy/config/tests/test_configs.py
- astropy/io/ascii/core.py
- astropy/io/ascii/ipac.py
- astropy/io/fits/tests/test_core.py
- astropy/io/fits/tests/test_hdulist.py
- astropy/modeling/tests/test_bounding_box.py
- astropy/modeling/tests/test_polynomial.py
- astropy/nddata/bitmask.py
- astropy/nddata/tests/test_nddata.py
- astropy/table/bst.py
- astropy/table/column.py
- astropy/table/table.py
- astropy/table/table_helpers.py
- astropy/table/tests/test_array.py
- astropy/table/tests/test_index.py
- astropy/table/tests/test_row.py
- astropy/table/tests/test_table.py
- astropy/time/formats.py
- astropy/units/tests/test_physical.py
- astropy/units/tests/test_quantity_array_methods.py

Rule C416 checks for unnecessary dict, list, and set comprehension. Replaced unnecessary dict, list, and set comprehension rewriting the code utilizing "dict()", "list()" and "set()".

This pull request is to address Issue #14818

### CODE REVIEW

**Review by dhomeier — APPROVED** [review]
Thanks for this fix, improves readability and conciseness of the code everywhere I could see!
Numpy-dev failures seem unrelated.

**Review by eerovaher — CHANGES_REQUESTED** [review]
The commit 714aa91b49143205024dd074bf5150dfe0511772 fixes all violations of the rule C416 in `astropy`, but because `.ruff.toml` is not edited then Ruff is still not enforcing that rule: https://github.com/astropy/astropy/blob/714aa91b49143205024dd074bf5150dfe0511772/.ruff.toml#L34
Without removing that line it is possible that a future commit might reintroduce code that violates this rule.

[If `pre-commit` is set up](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit) then the simplest way of enforcing a rule with a Ruff autofix (such as C416) would be to simply remove the rule from the ignore list in `.ruff.toml` and then to make a commit without manually editing any other files. The Ruff `pre-commit` hook will fix the rule violations and the Black hook will fix any code style issues.

If anyone ever wants to know which files were edited by a commit then they can use Git to find that out, e.g.
```
$ git show --name-only 714aa91b49143205024dd074bf5150dfe0511772
commit 714aa91b49143205024dd074bf5150dfe0511772
Author: arthurxvtv <90696992+arthurxvtv@users.noreply.github.com>
Date:   Thu May 18 20:22:59 2023 -0300

    astropy#14818 - Adress Rule C416 violations in multiple sub-packages
    
    Currently the selected files violate Ruff rule C416:
    
    - astropy/config/tests/test_configs.py
    - astropy/io/ascii/core.py
    - astropy/io/ascii/ipac.py
    - astropy/io/fits/tests/test_core.py
    - astropy/io/fits/tests/test_hdulist.py
    - astropy/modeling/tests/test_bounding_box.py
    - astropy/modeling/tests/test_polynomial.py
    - astropy/nddata/bitmask.py
    - astropy/nddata/tests/test_nddata.py
    - astropy/table/bst.py
    - astropy/table/column.py
    - astropy/table/table.py
    - astropy/table/table_helpers.py
    - astropy/table/tests/test_array.py
    - astropy/table/tests/test_index.py
    - astropy/table/tests/test_row.py
    - astropy/table/tests/test_table.py
    - astropy/time/formats.py
    - astropy/units/tests/test_physical.py
    - astropy/units/tests/test_quantity_array_methods.py
    
    Rule C416 checks for unnecessary dict, list, and set comprehension.

astropy/config/tests/test_configs.py
astropy/io/ascii/core.py
astropy/io/ascii/ipac.py
astropy/io/fits/tests/test_core.py
astropy/io/fits/tests/test_hdulist.py
astropy/modeling/tests/test_bounding_box.py
astropy/modeling/tests/test_polynomial.py
astropy/nddata/bitmask.py
astropy/nddata/tests/test_nddata.py
astropy/table/bst.py
astropy/table/column.py
astropy/table/table.py
astropy/table/table_helpers.py
astropy/table/tests/test_array.py
astropy/table/tests/test_index.py
astropy/table/tests/test_row.py
astropy/table/tests/test_table.py
astropy/time/formats.py
astropy/units/tests/test_physical.py
astropy/units/tests/test_quantity_array_methods.py
```
Writing out the full list of edited files in the commit message is therefore not useful.

**Comment by dhomeier** [comment]
> If anyone ever wants to know which files were edited by a commit then they can use Git to find that out, e.g.

Or one of my all-time favourite .gitconfig aliases
`hlog = log --name-status`
:)

**Comment by nstarman** [comment]
Hi @arthurxvtv, it looks like the style CI is failing. It looks like it's all auto fixable, so you can fix it here by commenting "pre-commit.ci autofix" or locally with https://pre-commit.com/#quick-start. Hope that helps!

**Comment by arthurxvtv** [comment]
pre-commit.ci autofix

**Comment by nstarman** [comment]
Thanks @arthurxvtv for addressing the CI. If you squash down to 1 or 2 atomic commits then this looks ready to go in..

**Comment by eerovaher** [comment]
I agree with @nstarman - this can be merged after squashing the commits.

**Comment by eerovaher** [comment]
The `pre-commit.ci` check reports code style violations that were not present in a2163db27cc5f7abc6c5485b5889e18bb14eda52. That commit was authored by the `pre-commit.ci` bot, so it looks like you squashed your local branch without syncing it with the pull request on Github. The code style violations need to be fixed (if you [set up `pre-commit` locally](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit) then this can be done automatically) and the commits squashed again, preferably down to one.

**Review by nstarman — APPROVED** [review]
Thanks @arthurxvtv! This PR LGTM. AFAICT the py3.11 test failure is unrelated, but it would be good to get a 2nd opinion on that before we merge.

**Comment by pllim** [comment]
devdeps and coverage failures are unrelated.

**Comment by pllim** [comment]
@eerovaher requested changed before so he should re-review. Thanks, all!

**Comment by dhomeier** [comment]
The failure looks like a new regression in numpy-dev that also shows up in the latest merge commits.

But the squashed commit still contains the entire PR description, history and file list in its message. As already noted by @eerovaher this is unnecessary, as it is already included in the PR description (the top of this page) and through `git show`/`git log` options, and will unnecessarily clutter the git log.
Also, is 4bf981b still a commit in an active branch? Otherwise I think there is no need to discuss reverting it, as it would never exist in the merged repo. Basically for the commits concise messages are most appropriate like
> Remove Ruff rule C416 exceptions from .ruff.toml and apply it to [subpackages]

(or just "apply to astropy" if there were no other subpackages that had C416 violations).

**Review by bmorris3 — APPROVED** [review]
As `nddata` maintainer, I've only reviewed `astropy/nddata/tests/test_nddata.py`, which looks good. 👍🏻

**Comment by nstarman** [comment]
@taldcroft @mhvk I think table is the most impacted subpackage

**Review by mhvk — APPROVED** [review]
table, time, units are all OK - nice simplifications!

**Comment by nstarman** [comment]
I think we have enough approvals to merge.

Thanks @arthurxvtv for the PR!

**Pull request merged**
