### PR TITLE
Use travis job names

### PR DESCRIPTION
**Pull request by drdavella**
I just noticed this feature and thought it might be useful for us. Feel free to suggest better names than the ones I used, or disagree entirely.

Also feel free to ignore until after the feature freeze 😉.

### CODE REVIEW

**Comment by drdavella** [comment]
For those too lazy to click through to travis:

image

**Comment by bsipocz** [comment]
I found it useful several times to be able to check on the env variables from this line in the build summary page, but if others prefer having a name instead I'm OK with that, too.

**Comment by pllim** [comment]
I don't have strong opinion here but generally :+1: to this. Having proper names make it easier for others to say something like "build such-and-such has something-something".

> check on the env variables 

It is still possible but one more click away.

**Comment by pllim** [comment]
p.s. Are you sure you don't want name them according to https://en.wikipedia.org/wiki/List_of_recurring_Monty_Python%27s_Flying_Circus_characters ?

**Comment by bsipocz** [comment]
> >    check on the env variables
> It is still possible but one more click away.
 
yes, that's my point ;) it's nice to not needed to have that extra click and then needing to scroll through the full log.

**Comment by astrofrog** [comment]
I'm personally 👍 as there are sometimes too many env vars to be useful

**Comment by bsipocz** [comment]
> I'm personally 👍 as there are sometimes too many env vars to be useful

there is a mouseover effect to see all of them...

**Comment by bsipocz** [comment]
What about starting all env with a `NAME`  variable?

**Comment by drdavella** [comment]
I kind of wish travis would just show both the names and the env variables. I just left a comment on the relevant thread: https://github.com/travis-ci/travis-ci/issues/5898

**Comment by drdavella** [comment]
Closing for now. Feel free to reopen if this seems useful in the future.

**Pull request closed without merging**
