### PR TITLE
Fix erfa warning when passing arrays

### PR DESCRIPTION
**Pull request by jwoillez**
These are the warnings:

    astropy/_erfa/core.c:315:42: warning: incompatible pointer types passing 'double *' to parameter of type 'double (*)[3]' [-Wincompatible-pointer-types]
            eraC2ixy(_date1, _date2, _x, _y, _rc2i);
                                             ^~~~~
    cextern/erfa/erfa.h:173:22: note: passing argument to parameter 'rc2i' here
                  double rc2i[3][3]);
                         ^

### CODE REVIEW

**Comment by mdboom** [comment]
:+1: from me.

**Comment by mdboom** [comment]
Process note: this does "affect release" (as labeled), but I don't think it requires a CHANGES entry. It fixes compiler warnings only and otherwise isn't user-facing at all.

**Comment by embray** [comment]
:+1:

**Comment by jwoillez** [comment]
Thanks for the merge!

**Pull request merged**
