### PR TITLE
Revise incorrect equation docs in Sersic2D class

### LINKED ISSUE #10150: Error in documentation for Sersic2D
### Description

The equation 

Γ(2𝑛)=2𝛾(𝑏𝑛,2𝑛)
on 

https://docs.astropy.org/en/latest/api/astropy.modeling.functional_models.Sersic2D.html

is incorrect.  It should be Γ(2𝑛)=2𝛾(2n,𝑏𝑛).  

EDIT: Changed provided URL to point to `latest`.

### PR DESCRIPTION
**Pull request by allardbrain**
### Description

This PR is identical in substance to #10162, but has hopefully been submitted in a way that is now consistent with the Astropy contributing guidelines, which I managed to misread in my previous attempt.

This pull request revises an incorrect equation in the docstring of the `Sersic2D` class. The correct equation is given on this web page:
http://ned.ipac.caltech.edu/level5/March05/Graham/Graham2.html

Screen Shot 2020-04-16 at 9 55 22 PM

Fixes #10150

### CODE REVIEW

**Comment by allardbrain** [comment]
Hello again, @pllim and @bsipocz :-) I believe this is a much cleaner attempt to submit the PR. I used the `[skip travis]` keyword in the commit message as you suggested previously in the other PR. This one-line documentation change probably doesn't warrant a changelog entry, but let me know if you'd like me to create one. I'll await further guidance from you if needed. Thank you!

**Comment by pllim** [comment]
Awesome! Looks good, except I want to confirm with @eteq one more time on whether his comment in https://github.com/astropy/astropy/pull/10162#issuecomment-615462873 was an approval or not.

**Comment by allardbrain** [comment]
Whew! Sounds good! Thanks. :-)

**Comment by bsipocz** [comment]
My original read of the code also came to the conclusion as @eteq in the other PR, that the code is fine. So let's merge this now, right before branching.

**Comment by bsipocz** [comment]
Thank you @allardbrain! Thanks and congratulations on your first contribution to astropy! Hope to see you in future PRs, too.

**Pull request merged**
