### PR TITLE
Change loop variable name to avoid conflict with key= argument to function

### PR DESCRIPTION
**Pull request by astrofrog**
I think that by luck this may actually never cause issues, but this should definitely be fixed anyway.

### CODE REVIEW

**Comment by mhvk** [comment]
Nice catch. I'd merge this straightaway if I just were sure that the labels, etc., are set right. @embray - I just looked through our [maintainer workflow](http://docs.astropy.org/en/latest/development/workflow/maintainer_workflow.html) and am still confused whether or not one needs one of those `affects-release` and `affects-dev`. Could you expand on that? (Or expand here and I'll make a PR.)

**Comment by nden** [comment]
:+1:

**Comment by embray** [comment]
Changelog entry, I guess?

**Comment by mhvk** [comment]
I don't think a changelog entry is needed, since it is not obvious that it actually caused any issues.

**Comment by astrofrog** [comment]
@mhvk - ``affects-dev`` is for bugs that were introduced since the last stable version.

I agree that this doesn't need a changelog entry.

**Comment by mhvk** [comment]
OK, thanks! I'll merge after this, but just to be sure: one should set either of `affects-release` or `affects-dev`, where the former means that code that is already released would/might change behaviour if the new stuff were applied to it (which does not necessarily mean that it will), or that it is only the current development branch that would be affected, because either the released code does not have the piece in question, or is otherwise not affected by it.

**Pull request merged**
