### PR TITLE
Update cfitsio to v3.43: includes critical bug fix (2.0.x series)

### LINKED ISSUE #7272: Security: please update cfitsio
A new version of cfitsio just came out, accompanied with the [following notice from upstream](https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes2.txt):

>The NASA security team requires the following warning to all users of CFITSIO:
>
>_The CFITSIO open source software project contains vulnerabilities that could allow a remote, unauthenticated attacker to take control of a server running the CFITSIO software.  These vulnerabilities affect all servers and products running the CFITSIO software.
> The CFITSIO team has released software updates to address these vulnerabilities.  There are no workarounds to address these vulnerabilities.  In all cases, the CFITSIO team is recommending an immediate update to resolve the issues._

It is still unclear what the exact problem is (see discussion in Debian bug [#892458](https://bugs.debian.org/892458)), but it may be wise to update cfitsio in 3.X and 2.X and to create a new point release.

### PR DESCRIPTION
**Pull request by drdavella**
This fixes #7272 for the 2.0.x series.

Unlike #7274, for this update we needed to backport the infrastructure changes introduced in #6477 as well.

### CODE REVIEW

**Comment by drdavella** [comment]
Travis failures appear to be unrelated. The Appveyor failures are somewhat confusing/disconcerting to me, because the contents of `cextern/cfitsio` are now the same as on v3.0.0 (#7274), which builds just fine on Appveyor. Maybe it has something to do with Py2? But that doesn't make much sense to me either.

**Comment by pllim** [comment]
From @jhunkeler , "astropy master uses the visual studio 2015 runtime, while [this] one uses visual studio 2008 runtime"

**Comment by pllim** [comment]
OK I think @drdavella solved the mystery: https://github.com/astropy/ci-helpers/blob/master/appveyor/windows_sdk.cmd
```
:: To build extensions for 64 bit Python 3.4 or earlier, we need to configure environment
:: variables to use the MSVC 2010 C++ compilers from GRMSDKX_EN_DVD.iso of:
:: MS Windows SDK for Windows 7 and .NET Framework 4 (SDK v7.1)
::
:: To build extensions for 64 bit Python 2, we need to configure environment
:: variables to use the MSVC 2008 C++ compilers from GRMSDKX_EN_DVD.iso of:
:: MS Windows SDK for Windows 7 and .NET Framework 3.5 (SDK v7.0)
```

**Comment by eteq** [comment]
Since the failures are unrelated and #7272 was approved by the fits maintainers, I think this is good to go.  Merging.

**Pull request merged**
