### PR TITLE
Update astropy.coordinates.calculation scraper

### PR DESCRIPTION
**Pull request by eslavich**
### Description

The scraper just needs a little freshening up...

### CODE REVIEW

**Comment by pllim** [comment]
Since you are here, what's up with this error?

```
config = <AsdfConfig
  array_inline_threshold: None
  default_version: 1.5.0
  io_block_size: -1
  legacy_fill_schema_defaults: True
  validate_on_read: True
>
kwargs = {'auto_inline': 64}

    def _handle_deprecated_kwargs(config, kwargs):
        for key, value in kwargs.items():
            if key in _DEPRECATED_KWARG_TO_CONFIG_PROPERTY:
                config_property, func = _DEPRECATED_KWARG_TO_CONFIG_PROPERTY[key]
                warnings.warn(
                    f"The '{key}' argument is deprecated, set "
                    f"asdf.get_config().{config_property} instead.",
>                   AsdfDeprecationWarning
                )
E               asdf.exceptions.AsdfDeprecationWarning: The 'auto_inline' argument is deprecated, set asdf.get_config().array_inline_threshold instead.

../../.tox/py37-test-devdeps/lib/python3.7/site-packages/asdf/asdf.py:1618: AsdfDeprecationWarning
```

**Comment by eslavich** [comment]
Aw, I almost got the PR open before you commented: https://github.com/astropy/astropy/pull/11738

**Review by eteq — APPROVED** [review]
Nice! thanks for the :eyes: on it!

**Comment by eteq** [comment]
(the failures are unrelated)

**Comment by eteq** [comment]
Looks like this needs a backport to 4.3, see re-milestoning and backporting in 198ef0304b7cecf38367e1a7b143ade2fe5f3beb!

**Comment by pllim** [comment]
#priorities

**Pull request merged**
