### PR TITLE
Properly handle FTP socket error

### PR DESCRIPTION
**Pull request by astrojuanlu**
## Description

This pull request address a minor coding error that was unvealed in https://travis-ci.org/github/astropy/astropy/jobs/728533005.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Good catch. Thanks!

**Comment by astrojuanlu** [comment]
Restarting the `--remote-data=any` Travis build to see if I'm lucky with the coverage.

**Comment by pllim** [comment]
The error doesn't pop up too often. If you want, we can leave this open for a bit. Up to you.

**Comment by astrojuanlu** [comment]
If I run this test locally it _covers_ that line, so I still don't understand the Codecov patch failure. I am going to assume that it's some sort of hiccup in the coverage publication and merge straight away, don't think it's worth it to keep this tiny PR open for this reason. Thanks @pllim!

**Comment by pllim** [comment]
Ah.... right. The coverage test doesn't run `--remote-data=any`.

https://github.com/astropy/astropy/blob/042c04ccd20139594709f64f3338ded51df34818/.travis.yml#L124-L131

**Pull request merged**
