### PR TITLE
Make NDDataArray equivalent to pre-1.0 NDData

### LINKED ISSUE #3466: NDData compatibility class not actually identical to pre-1.0 NDData
A pull request to fix this is coming in a moment.

When @crawfordsm tried modifying `ccdproc` last week to work with the compatibility class `NDDataArray` that is advertised as equivalent to pre-1.0 `NDData`  he found it was missing several properties that were present in the old `NDData`.

I ought to have caught this in December, but didn't. Don't know that it is critical for 1.0 because use of NDData to date has been limited.

### PR DESCRIPTION
**Pull request by mwcraig**
Closes #3466 -- see that issue for details.

Almost all of the code in this PR is copied (along with the relevant tests) from the old NDData.

### CODE REVIEW

**Comment by astrofrog** [comment]
@eteq - should this be included in rc2 since it's basically a 1.0 bug?

**Comment by eteq** [comment]
Yes, I suppose so, @astrofrog.  I'm a bit nervous about a substantive last-minute change like this, but it's probably better than breaking `NDData` compatibility.  Will wait for the tests and if the pass should we immediately merge and backport?

**Comment by mwcraig** [comment]
The alternative is a documentation patch: deleting this passage:

    Code that uses the arithemtic methods that used to be included in
    `~astropy.nddata.NDData` and relied on it to behave like a numpy array should
    instead subclass `~astropy.nddata.NDDataArray`; that class is equivalent to
    the original `~astropy.nddata.NDData` class.

Then that passage and the changes in this PR could be bundled into 1.0.1. In `ccdproc` we've already worked around the issue.

**Comment by astrofrog** [comment]
That might be more reasonable at this stage. @eteq - do you agree?

**Comment by eteq** [comment]
Yeah, I think that makes sense.  Can you make a separate PR for the doc change, @mwcraig ?  I'll re-assign this to 1.0.1 now.

**Comment by astrofrog** [comment]
Now that 1.0 is out, how do we want to proceed with this? Shall we merge it? If so, it will need a changelog entry. Alternatively, if people are going to adapt their packages to 1.0 anyway, maybe this isn't needed?

**Comment by mwcraig** [comment]
I'm inclined to keep it in...@crawfordsm, do you have any strong opinion?

**Comment by crawfordsm** [comment]
I'd be inclined to see it merged now.    Merging it now reduces other packages from having to make the same fixes and I think they are things which would be fairly useful or common.   As it helps NDDataArray behave as the previous NDData, I would agree with the earlier comment that it was more of a bug fix than an upgrade.

**Comment by astrofrog** [comment]
Ok, as long as it's included as a bug fix in 1.0.1 then that is fine.

**Comment by astrofrog** [comment]
@mwcraig - can you add a changelog entry? (if you rebase you will see there are now empty sections for 1.0.1 in the changelog)

**Comment by mwcraig** [comment]
Will do, and update the docs.

On Mon, Feb 23, 2015 at 6:12 AM, Thomas Robitaille <notifications@github.com

**Comment by mwcraig** [comment]
@astrofrog -- this is ready to go if tests pass.

**Comment by astrofrog** [comment]
Thanks @mwcraig!

**Pull request merged**
