### PR TITLE
MAINT: Trying to limit pytest version

### PR DESCRIPTION
**Pull request by bsipocz**
This feels so bad on so many levels. 

@astrofrog @Cadair - is hacking the packaging files is the way to limit version now, or could it go into the tox config?

### CODE REVIEW

**Comment by astrofrog** [comment]
If we want to fix globally we should get https://github.com/astropy/ci-helpers/pull/429 in :)

**Comment by pllim** [comment]
I have #10044 for 4.1 that applies the tox command thingy, while this patch here can be applied directly to 4.0.x branch without going in `master`?

**Comment by bsipocz** [comment]
4.0.x should be fine, as there is already the limitation in ci-helpers (and that branch doesn't use tox yet).

**Comment by astrofrog** [comment]
Working on the centralized tox script approach now.

**Comment by bsipocz** [comment]
Thanks @astrofrog!

**Pull request closed without merging**
