### PR TITLE
TST: Relax test_data_at_range_limit warning check

### LINKED ISSUE #10853: Non-deterministic test failure in test_data_at_range_limit
I noticed the following failure when working on #10850 - this seems to happen on manylinux1 64-bit Python. I'll try and provide docker commands to reproduce later.

```
=================================== FAILURES ===================================
______________ test_data_at_range_limit[False-fast_reader1-True] _______________

parallel = False, fast_reader = {'parallel': False, 'use_fast_converter': False}
guess = True

    @pytest.mark.parametrize("guess", [True, False])
    # fast_reader configurations: False| 'use_fast_converter'=False|True
    @pytest.mark.parametrize('fast_reader', [False, dict(use_fast_converter=False),
                                             dict(use_fast_converter=True)])
    @pytest.mark.parametrize("parallel", [False, True])
    def test_data_at_range_limit(parallel, fast_reader, guess):
        """
        Test parsing of fixed-format float64 numbers near range limits
        (|~4.94e-324 to 1.7977e+308|) - within limit for full precision
        (|~2.5e-307| for strtod C parser, factor 10 better for fast_converter)
        exact numbers shall be returned, beyond that an Overflow warning raised.
        Input of exactly 0.0 must not raise an OverflowError.
        """
        # Python reader and strtod() are expected to return precise results
        rtol = 1.e-30
    
        # Update fast_reader dict; adapt relative precision for fast_converter
        if fast_reader:
            fast_reader['parallel'] = parallel
            if fast_reader.get('use_fast_converter'):
                rtol = 1.e-15
            elif np.iinfo(np.int_).dtype == np.dtype(np.int32):
                # On 32bit the standard C parser (strtod) returns strings for these
                pytest.xfail("C parser cannot handle float64 on 32bit systems")
    
        if parallel:
            if not fast_reader:
                pytest.skip("Multiprocessing only available in fast reader")
            elif TRAVIS:
                pytest.xfail("Multiprocessing can sometimes fail on Travis CI")
    
        # Test very long fixed-format strings (to strtod range limit w/o Overflow)
        for D in 99, 202, 305:
            t = ascii.read(StringIO(99 * '0' + '.' + D * '0' + '1'), format='no_header',
                           guess=guess, fast_reader=fast_reader)
            assert_almost_equal(t['col1'][0], 10.**-(D + 1), rtol=rtol, atol=1.e-324)
        for D in 99, 202, 308:
            t = ascii.read(StringIO('1' + D * '0' + '.0'), format='no_header',
                           guess=guess, fast_reader=fast_reader)
            assert_almost_equal(t['col1'][0], 10.**D, rtol=rtol, atol=1.e-324)
    
        # 0.0 is always exact (no Overflow warning)!
        for s in '0.0', '0.0e+0', 399 * '0' + '.' + 365 * '0':
            with pytest.warns(None) as w:
                t = ascii.read(StringIO(s), format='no_header',
                               guess=guess, fast_reader=fast_reader)
            assert t['col1'][0] == 0.0
            assert len(w) == 0
    
        # Test OverflowError at precision limit with laxer rtol
        if parallel:
            pytest.skip("Catching warnings broken in parallel mode")
        elif not fast_reader:
            pytest.skip("Python/numpy reader does not raise on Overflow")
        with pytest.warns(AstropyWarning, match=r'OverflowError converting to '
                          r'FloatType in column col1, possibly resulting in '
                          r'degraded precision'):
            t = ascii.read(StringIO('0.' + 314 * '0' + '1'), format='no_header',
>                          guess=guess, fast_reader=fast_reader)
E           Failed: DID NOT WARN. No warnings of type (<class 'astropy.utils.exceptions.AstropyWarning'>,) was emitted. The list of emitted warnings is: [].

/tmp/tmp.siYQiS1424/venv/lib/python3.6/site-packages/astropy/io/ascii/tests/test_c_reader.py:1181: Failed
______________ test_data_at_range_limit[False-fast_reader1-False] ______________

parallel = False, fast_reader = {'parallel': False, 'use_fast_converter': False}
guess = False

    @pytest.mark.parametrize("guess", [True, False])
    # fast_reader configurations: False| 'use_fast_converter'=False|True
    @pytest.mark.parametrize('fast_reader', [False, dict(use_fast_converter=False),
                                             dict(use_fast_converter=True)])
    @pytest.mark.parametrize("parallel", [False, True])
    def test_data_at_range_limit(parallel, fast_reader, guess):
        """
        Test parsing of fixed-format float64 numbers near range limits
        (|~4.94e-324 to 1.7977e+308|) - within limit for full precision
        (|~2.5e-307| for strtod C parser, factor 10 better for fast_converter)
        exact numbers shall be returned, beyond that an Overflow warning raised.
cibuildwheel-26d88921-1f51-4163-9e4e-f61fe6b3c83b
        Input of exactly 0.0 must not raise an OverflowError.
        """
        # Python reader and strtod() are expected to return precise results
        rtol = 1.e-30
    
        # Update fast_reader dict; adapt relative precision for fast_converter
        if fast_reader:
            fast_reader['parallel'] = parallel
            if fast_reader.get('use_fast_converter'):
                rtol = 1.e-15
            elif np.iinfo(np.int_).dtype == np.dtype(np.int32):
                # On 32bit the standard C parser (strtod) returns strings for these
                pytest.xfail("C parser cannot handle float64 on 32bit systems")
    
        if parallel:
            if not fast_reader:
                pytest.skip("Multiprocessing only available in fast reader")
            elif TRAVIS:
                pytest.xfail("Multiprocessing can sometimes fail on Travis CI")
    
        # Test very long fixed-format strings (to strtod range limit w/o Overflow)
        for D in 99, 202, 305:
            t = ascii.read(StringIO(99 * '0' + '.' + D * '0' + '1'), format='no_header',
                           guess=guess, fast_reader=fast_reader)
            assert_almost_equal(t['col1'][0], 10.**-(D + 1), rtol=rtol, atol=1.e-324)
        for D in 99, 202, 308:
            t = ascii.read(StringIO('1' + D * '0' + '.0'), format='no_header',
                           guess=guess, fast_reader=fast_reader)
            assert_almost_equal(t['col1'][0], 10.**D, rtol=rtol, atol=1.e-324)
    
        # 0.0 is always exact (no Overflow warning)!
        for s in '0.0', '0.0e+0', 399 * '0' + '.' + 365 * '0':
            with pytest.warns(None) as w:
                t = ascii.read(StringIO(s), format='no_header',
                               guess=guess, fast_reader=fast_reader)
            assert t['col1'][0] == 0.0
            assert len(w) == 0
    
        # Test OverflowError at precision limit with laxer rtol
        if parallel:
            pytest.skip("Catching warnings broken in parallel mode")
        elif not fast_reader:
            pytest.skip("Python/numpy reader does not raise on Overflow")
        with pytest.warns(AstropyWarning, match=r'OverflowError converting to '
                          r'FloatType in column col1, possibly resulting in '
                          r'degraded precision'):
            t = ascii.read(StringIO('0.' + 314 * '0' + '1'), format='no_header',
>                          guess=guess, fast_reader=fast_reader)
E           Failed: DID NOT WARN. No warnings of type (<class 'astropy.utils.exceptions.AstropyWarning'>,) was emitted. The list of emitted warnings is: [].

/tmp/tmp.siYQiS1424/venv/lib/python3.6/site-packages/astropy/io/ascii/tests/test_c_reader.py:1181: Failed
=========================== short test summary info ============================

### PR DESCRIPTION
**Pull request by pllim**
### Description

Fix #10853

### CODE REVIEW

**Comment by pllim** [comment]
Failures seem unrelated. Not sure what is going on with codecov.

**Comment by astrofrog** [comment]
@taldcroft should review this as I'm not sure if the lack of warning indicates an issue.

**Comment by pllim** [comment]
I don't know how the lack of warning about degraded precision can be a problem, but I'll wait. 😹

**Comment by taldcroft** [comment]
I'm going to push this off to @dhomeier who is the defacto fast-reader maintainer and might have written this code.

**Comment by eteq** [comment]
I'm noticing this is impacting v4.1.x (just in Azure...?) - @taldcroft or @dhomeier - can you confirm if you think this is mostly a testing vs "live" problem?  And should I consider it a blocker for 4.1 or should I go ahead and release and just ignore these errors in the CI?

**Review by taldcroft — APPROVED** [review]
Full disclosure: I don't fully understand what's going on here and have not dug down into the fast reader C code to investigate. But at a high level it seems plausible that this kind of an overflow warning could be hardware / compiler dependent and that the current test is running into a previously unseen variation.

This test is very much in the far corners of what a user might normally do, so I am not concerned about this impacting users even in the worst case where there is actually degraded precision and no warning gets issues.

Therefore this should not be a blocker for 4.1 and I would say to merge this and release.

**Comment by eteq** [comment]
Alright, following-through on merging/backporting based on @taldcroft's comment. But @dhomeier should feel free to open a new issue if there's a concern we've missed here!

**Comment by dhomeier** [comment]
I seem to remember similar failures to warn, but they might just have been marked skip for the Linux CI. I think this is a case of internally converting at 80 bit or higher precision on hardware that supports this, so should be fine to allow passing without warning.

The only concern is that the values will still be returned in an `np.float64`, so ultimately there _is_ a loss of precision, without emitting a warning in a certain data range. But that is something to fix in the C reader (and I don't have a good idea how to go about it right now), not for the test.

**Comment by dhomeier** [comment]
> This test is very much in the far corners of what a user might normally do, so I am not concerned about this impacting users even in the worst case where there is actually degraded precision and no warning gets issues.

Agreed; if users enter a value as e.g. `np.float64(0.3e-323)` there is no warning either...

**Comment by pllim** [comment]
We can always improve the relaxation of this check and get it into the next 4.0.x release...

**Pull request merged**
