### PR TITLE
TST: fix running array repr tests with an ellipsis on numpy 2.2 (dev)

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
[example logs](https://github.com/astropy/astropy/actions/runs/11763485911/job/32767529277)

xref: https://github.com/numpy/numpy/pull/27482

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
This upstream change also affects 6.1.x so let's maybe backport the patch there too

**Review by mhvk — APPROVED** [review]
Thanks, this looks good!

**Comment by pllim** [comment]
Are you sure we don't want this on v6.1.x just in case?

@meeseeksdev backport to v6.1.x

**Comment by pllim** [comment]
Hmm I guess not.

**Comment by mhvk** [comment]
I think it is OK with 7.0 coming out very soon - one should not expect to run older versions of astropy with the very newest numpy (and, really, in this case it is just that one test will fail, not that actual results are different).

**Comment by pllim** [comment]
Especially since @astrofrog is about to do v6.1.6 anyway, so put the max pin in there?

**Comment by astrofrog** [comment]
Too late, 6.1.6 is building - but anyway this is just about a test failure, astropy 6.1.6 will likely work fine with a number of future numpy versions.

**Comment by pllim** [comment]
Hmm the v6.1.x branch does use `Numpy: 2.2.0.dev0+git20241108.7c0e2e4` so maybe whatever broke here didn't get backported in the first place. 🤷‍♀️

**Pull request merged**
