### PR TITLE
rebase git command had a typo

### PR DESCRIPTION
**Pull request by SaraOgaz**
In th last section of the "How to make a code Contribution" doc: [http://docs.astropy.org/en/stable/development/workflow/development_workflow.html](url)

### CODE REVIEW

**Comment by MSeifert04** [comment]
Good catch on that! :+1: 

I hope you don't mind the noise, but reading "[...] had a typo" and then the next sentence starts with "In th last [...]" made me smile. :smile:

FWIW: For simple documentation changes you can append ``[skip ci]`` (or ``[ci skip]``) to the commit message so you don't run the full test-suite on the PR.

**Comment by bsipocz** [comment]
Maybe it would make sense to do ``git fetch --all`` instead?

**Comment by pllim** [comment]
@bsipocz , there is no need to fetch all, because all you need is the master branch (unless you are backporting).

**Comment by pllim** [comment]
Tagging 1.2.2 for now. Feel free to change.

**Comment by bsipocz** [comment]
@pllim - Yes, I know, but I think it's good practice to do nevertheless.

**Comment by astrofrog** [comment]
I actually just normally do ``git fetch astropy`` or ``git fetch upstream`` - I think the ``--all`` must be implicit? What about simply removing ``master`` from the command?

**Comment by MSeifert04** [comment]
I think in this example it's actually correct just to fetch `master`. No other branch has to be up-to-date for rebasing (ok, the to-be-rebased branch but that should be trivial except someone else made a commit or PR against it).

**Comment by astrofrog** [comment]
@MSeifert04 ah, but it's less typing! 😆

**Comment by SaraOgaz** [comment]
Whoops, missed these extra comments.  I had only seen @bsipocz and changed it to all, although I'm on the side of not using the all part.  Also, did something go wrong with my rebasing?  Why am I author on all the new astropy commits? Is that normal?

**Comment by MSeifert04** [comment]
It seems like you merged the master branch before rebasing. Do you still know how you rebased?

There are also some instructions on http://docs.astropy.org/en/stable/development/workflow/development_workflow.html#rebase-but-only-if-asked?

**Comment by SaraOgaz** [comment]
I think it happened when I was editing my commits, I did a rebase command pulling a bunch of the previous commits, trying to fix it...

**Comment by pllim** [comment]
Looks good now. Merging. Thanks!

**Pull request merged**
