### PR TITLE
Update default locations for doc build in docs

### PR DESCRIPTION
**Pull request by hamogu**
At some point in the past, these must have changed without an update of the narrative prose.

[skip ci]

### CODE REVIEW

**Comment by saimn** [comment]
See #4133 and #5156: the correct path is `docs/_build`, but because of a missing setting it was going to `build/sphinx` before being fixed in #5156. Maybe you have an old build in `build/sphinx` ?

**Comment by hamogu** [comment]
I acutally observed this in an affiliated package and assumed the behaviour came from astropy itself. I'll go back and investigate more.

**Comment by saimn** [comment]
For affiliated packages the `setup.cfg` file must be updated with this change: https://github.com/astropy/package-template/pull/184

**Comment by hamogu** [comment]
Thanks. I'll see that the affiliated package in question is updated and I'll close this.

**Pull request closed without merging**
