### PR TITLE
Removed robots.txt and added an extension to layout.html

### PR DESCRIPTION
**Pull request by dasdachs**

### CODE REVIEW

**Comment by bsipocz** [comment]
Sounds good @astrofrog. I'll do the backports to 2.0.x and 3.0.x but it's not yet clear that how backporting to closed branches should be done.

**Comment by bsipocz** [comment]
also, given that I haven't yet pushed the release to pypi yet, I'll put this in there, too.

**Comment by bsipocz** [comment]
Thank you very much @dasdachs!

**Comment by dasdachs** [comment]
@astrofrog `latest` and `stable` don't have robots meta tags. All other branches should or would have.

For comparison have a look  at the documentation builds of my [fork](https://github.com/dasdachs/astropy) of `astropy`:  [latest](https://astro-docs.readthedocs.io/en/latest) and [2.0](https://astro-docs.readthedocs.io/en/v2.0.x_a/).

But this is easy to change. The `version_slugs` are defined in `html_context` in [conf.py](https://github.com/astropy/astropy/blob/master/docs/conf.py#L166)

**Comment by astrofrog** [comment]
@dasdachs - ah right of course, I wasn't thinking straight :)

**Pull request merged**
