### PR TITLE
update instructions for making maintainence branch

### PR DESCRIPTION
**Pull request by eteq**
Primarily for @astrofrog's perusal as the other release maintainer.

### CODE REVIEW

**Comment by bsipocz** [comment]
I love the new astrobot message :)

**Comment by pllim** [comment]
@astrobot has gained confidence. Did you watch West World (the HBO one)? :scream: :scream: :scream:

**Comment by larrybradley** [comment]
I just hope @astrobot doesn't start calling itself "Wyatt". 😅

**Comment by astrofrog** [comment]
I have no idea what y'all are talking about :-/

**Comment by larrybradley** [comment]
https://en.wikipedia.org/wiki/Westworld_(TV_series)

**Pull request merged**
