### PR TITLE
Fix Cone Search validator parse_cs() crashing on incomplete testQuery

### LINKED ISSUE #4158: Some missing error handling in parse_cs
In the process of investigating #2970 I ran across what I think is an unrelated buglet.

In my testing I ran
```python
check_conesearch_sites(url_list=None)
```
which seems to go on to download a whole bunch of different catalog resources and look up their conesearch test queries (I'm sort of learning how this all works as I go so please correct me @pllim :)  However, in the process it crashed `parse_cs` because at least *one resource*, given by the ID ivo://CDS.VizieR/J/ApJ/780/34 contains a testQuery element with only an `<sr>` parameter specified, and no `<ra>` or `<dec>`.  Based on my reading of [this](http://www.ivoa.net/documents/REC/DAL/ConeSearch-20080222.html), and some of the discussion [here](http://wiki.ivoa.net/bin/view/IVOA/SimpleDALRegExt10RFC) it seems the RA, DEC, and SR parameters *must* be provided for a valid cone search (duh), though the Resource schema itself doesn't make that entirely clear... :(

In any case I think we should:
a) Report the broken resource and
b) Fix the code to catch this kind of error (the code is currently assuming any testQuery will at least have a valid set of parameters).

### PR DESCRIPTION
**Pull request by pllim**
This fixes #4158. Also minor PEP-8 and doc fixes.

I have no plans to add a test or change log. This is because `parse_cs()` is for internal use within the validator. And Cone Search services change from time to time, so there is no point to add a test for this.

@embray , you can manually test this if you wish:
```python
>>> from astropy.vo.validator.tstquery import parse_cs
>>> id = 'ivo://CDS.VizieR/J/ApJ/780/34'
>>> parse_cs(id)
WARNING: Incomplete testQuery for ivo://CDS.VizieR/J/ApJ/780/34, using default [astropy.vo.validator.tstquery]
OrderedDict([(u'SR', u'0.1'), (u'DEC', u'0'), (u'RA', u'0')])
```

### CODE REVIEW

**Comment by embray** [comment]
Yeah, this is what I had in mind :+1:

**Comment by embray** [comment]
This code *could* be changed so that it can read a resource from a file, rather than a URL (perhaps just by a little refactoring, by making `parse_cs` which takes just an ID a wrapper around a more general function that takes an arbitrary path to the resource).  Then we could test this by saving the current XML of that known-bad resource as an XML file in the test suite and testing against that.  Up to you though--otherwise just add a changelog entry for v1.0.5 bug fixes.

**Comment by pllim** [comment]
> This code could be changed...

This code was supposed to be a *temporary* solution. `testQuery` is supposed to be obtainable from the main validation query but etc etc. I am just going to leave it as-is, so in the future if we don't need this anymore, all I have to do is to delete `tstquery.py`.

Okay, I'll add a change log.

**Comment by embray** [comment]
Thanks!

**Pull request merged**
