### PR TITLE
Backport PR #15049 on branch v5.0.x (fix sign of w0wzCDM inv_efuncs pyx)

### PR DESCRIPTION
**Pull request by nstarman**
Backport of #15049

### CODE REVIEW

**Comment by pllim** [comment]
I guess this is a redo of #15223 ?

**Comment by pllim** [comment]
Close/reopen to make bot happy

**Comment by nstarman** [comment]
> I guess this is a redo of #15223 ?

Yeah, I mistakenly opened that PR from a branch intended for v5.3.x

**Comment by pllim** [comment]
CI looks good so far. Why is this draft?

**Comment by nstarman** [comment]
I open every PR as a draft until I circle back and check the CI :)

**Review by pllim — APPROVED** [review]
Thanks!

**Pull request merged**
