### PR TITLE
Add type annotations to `Generic` unit formatter

### PR DESCRIPTION
**Pull request by eerovaher**
### Description

`Generic` is already partially annotated. I'm now adding annotations to the remaining methods and attributes.

- [x] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by nstarman — APPROVED** [review]
LGTM.
As `units.format` gets closer to being typed we should consider static verification.
I don't think this is a region of the code likely to have inexperienced contributors (see the git blame) and the code will benefit from both the extra checks and potentially c-compilation.

**Review by mhvk — APPROVED** [review]
Also happy with this! I do recall it being pointed out the class and module variables do not need to be explicitly typed if their type is obvious (like `Tuple[str, ...]`). Is this a thing?  I don't really care about it one way or another, but brevity can be nice.

I'm also happy for `format` to be the guineapig for some typing tests - as @nstarman notes, it might be a prime candidate for something like mypyc showing some real benefits! (but obviously not for this PR...).

**Comment by eerovaher** [comment]
> I do recall it being pointed out the class and module variables do not need to be explicitly typed if their type is obvious (like `Tuple[str, ...]`).

The Python type system allows for three different possibilities for attributes defined in a class: instance attributes, class attributes and constants. Out of these three instance attributes are considered to be the default, so class attributes and constants must be annotated explicitly (with [`ClassVar`](https://docs.python.org/3/library/typing.html#typing.ClassVar) and [`Final`](https://docs.python.org/3/library/typing.html#typing.Final) respectively).

[Tuple types can be either fixed-length or arbitrary length.](https://docs.python.org/3/library/typing.html#annotating-tuples) At least mypy seems to be always using fixed-length tuples when inferring types automatically.

These two rules together mean that the automatically inferred type for e.g. `Generic._tokens` would be `tuple[str, str, str, str, str, str, str, str, str, str, str, str, str]`, not `ClassVar[tuple[str, ...]]`

**Comment by mhvk** [comment]
Thanks for the explanation!

**Pull request merged**
