### PR TITLE
TST: adapt a test to pytest<8

### LINKED ISSUE #17141: test_parse_strict_noncritical_error_default fails on 3/4 exotic archs with AssertionError: Regex pattern did not match
Example log: https://github.com/astropy/astropy/actions/runs/11240991355/job/31251556253?pr=17139

I think this is caused by one of the OGIP changes that @eerovaher made recently (and @mhvk probably reviewed it). Somehow that change broke a test but only in the matrix of exotic archs job that uses some system libraries (but at a glance I don't see how sys lib can cause this error). This should be resolved before v7.0 is released.

https://github.com/astropy/astropy/blob/eb9894925bd1b0f2037f18a4b0ab0a08bcc849e9/.github/workflows/ci_cron_weekly.yml#L166

```
      def test_parse_strict_noncritical_error_default():
          with pytest.raises(
              ValueError,
              match=(
                  r"^if 'm\(s\)' was meant to be a multiplication, it should have been "
                  r"written as 'm \(s\)'\.\n"
                  "If you cannot change the unit string then try specifying the "
                  r"'parse_strict' argument\.$"
              ),
          ):
  >           assert u.Unit("m(s)", format="ogip")
  
  E       AssertionError: Regex pattern did not match.
  E        Regex: "^if 'm\\(s\\)' was meant to be a multiplication, it should have been written as 'm \\(s\\)'\\.\\nIf you cannot change the unit string then try specifying the 'parse_strict' argument\\.$"
  E        Input: "if 'm(s)' was meant to be a multiplication, it should have been written as 'm (s)'."
  
  astropy/units/tests/test_units.py:263: AssertionError
```

```
  _________________ test_parse_strict_noncritical_error_default __________________
  
  self = <class 'astropy.units.core.Unit'>, s = 'm(s)', represents = None
  format = 'ogip', namespace = None, doc = None, parse_strict = 'raise'
```

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
Follow up to #16892
Fixes #17141

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Thanks! That's probably the fastest solution to get things to pass again...

**Comment by pllim** [comment]
Thanks! Should have run Extra CI though to be sure.

**Comment by pllim** [comment]
Kicked off a run here on `main`: https://github.com/astropy/astropy/actions/runs/11257102100

I'll bug you if the exotic archs don't pass. 😉

**Comment by neutrinoceros** [comment]
> I'll bug you if the exotic archs don't pass.

please  do !

**Comment by pllim** [comment]
They passed.  Thanks again!

**Pull request merged**
