### PR TITLE
Fixing CI on LTS

### PR DESCRIPTION
**Pull request by bsipocz**
There was a syntax mistake in the backport of #8617, but there are also doc build issues so I'm opening this PR to fix everything here rather than pushing directly to the LTS branch.

### CODE REVIEW

**Comment by bsipocz** [comment]
The docs build issue has been solved locally by https://github.com/astropy/astropy-helpers/pull/475, so I'll update the helpers to the 2.0.x branch here (that'll become 2.0.10) once I merge that PR.

**Comment by pllim** [comment]
What about those 32-bit failures?

**Comment by bsipocz** [comment]
> What about those 32-bit failures?

I don't have any good ideas for those :(

**Comment by bsipocz** [comment]
for the python2 failure we run into the same pytest-xdist issue you've fixed in https://github.com/astropy/astropy/pull/8557, but given LTS requires pytest<3.7, I'm just limiting xdist's version, too.

**Comment by bsipocz** [comment]
OK, so all but the already been messed up 32bit_py3 build passed, so I go ahead and merge this now.

**Pull request merged**
