### PR TITLE
Add numfocus badge

### PR DESCRIPTION
**Pull request by eteq**
NumFOCUS recently came out with a badge which seems reasonable to add to our README.  This PR implements that (see https://github.com/eteq/astropy/blob/add-numfocus-badge/README.rst for how it renders)

### CODE REVIEW

**Comment by mhvk** [comment]
In principle OK, but if we're going to effectively thank one organization for support, shouldn't we a bit more general? It would seem STScI and CXC effectively support astropy quite heavily, by contributing developer time. Or am I missing what the support actually is?

**Comment by pllim** [comment]
Thanks for thinking of us, @mhvk . 😄  FYI -- STScI doesn't have a badge like that, but I can ask our Outreach dept if you need one.

**Comment by eteq** [comment]
@mhvk - a good point, but the reasoning here is that astropy has a specific financial relationship with NumFOCUS that it doesn't have with any other organization.  That is, this is not meant to mean"NumFOCUS did all the work", but rather "NumFOCUS is the legal holder of Astropy's $".

Separately, I think there *should* be a "groups that have supported astropy dev" list-of-logos.  But I see that as belonging on the web site rather than in the code repo (in part because of the wider affiliated package stuff).  See astropy/astropy.github.com#166 .  This badge is meant to be only about the formal financial relationship NumFOCUS has.

**Comment by mhvk** [comment]
OK, that makes sense, so :+1: from me too, then.

**Comment by eteq** [comment]
Ok looks like all is set so will merge

**Comment by pllim** [comment]
I'm just going to set milestone to 2.0 but feel free to re-milestone as needed.

**Pull request merged**
