### PR TITLE
remove wcsaxes from pip-requirements-doc because its already included

### PR DESCRIPTION
**Pull request by eteq**
Says just what it does... @astrofrog can you confirm that this is intended? (I.e., no need at all for the external package now or in the future for the doc build?)

### CODE REVIEW

**Comment by larrybradley** [comment]
How is this file used (is it)?  For the RTD builds, we're using `readthedocs.yml` and `.rtd-environment.yml`.

**Comment by eteq** [comment]
@larrybradley - these are for when you want to do ``pip install -r <filename>`` - they're (annoyingly) slightly different format from what RTD wants.  At one point I tried to make one work with the other but couldn't make it work.

It might be that we should just drop these or something, as I generally use conda for most of these anyway.  But the `dev` one, at least, is  a useful way to keep track of what's needed for *building*.

**Comment by larrybradley** [comment]
@eteq  Ah, these are just for convenience.  Thanks for the explanation.

**Comment by eteq** [comment]
backported to v1.3.x in b91fd3f8b7bce2d1ef9b3f440bd66c122d8c59ca

**Pull request merged**
