### PR TITLE
Fix failures in continuous integration

### PR DESCRIPTION
**Pull request by astrofrog**
cc @bsipocz

### CODE REVIEW

**Comment by astrofrog** [comment]
This is specifically for the v1.0.x branch which was showing some failures.

**Comment by bsipocz** [comment]
Many thanks @astrofrog, it's a relieve to see it wasn't a big mess-up.

**Comment by embray** [comment]
Ah, I was confused about this.  I actually fixed both these things directly on the branch before I noticed this PR.

**Comment by embray** [comment]
FYI this is the current branch build including my fixes: https://travis-ci.org/astropy/astropy/builds/101108555

Once it passes (which it looks like it will) we can close this PR.  Sorry for the confusion.

**Comment by embray** [comment]
Is good to go.

**Pull request closed without merging**
