### PR TITLE
TST: Fix pyinstaller CI job

### LINKED ISSUE #12688: TST: Unpin numpy in pyinstaller job
Follow-up of:

* #12682

Remove this pin and make sure CI does not fail for that test no more:

https://github.com/astropy/astropy/blob/3d522ebcbe6903326cb8b44e1ca970d206a4bd73/tox.ini#L150

Currently, with numpy 1.22.0, it complains about `numpy.distutils` but when you add back `--collect-submodules numpy.distutils` removed in #12655 , it complains about `_private`:

```
  File "astropy/units/quantity_helper/function_helpers.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "numpy/lib/recfunctions.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "numpy/testing/__init__.py", line 17, in <module>
NameError: name '_private' is not defined
```

Need someone familiar with `pyinstaller` to investigate and fix.

### LINKED ISSUE #12820: TST: pytest 7.0.0 broke pyinstaller job
Started happening after `pytest` 7.0.0 came out. I reran a previously successful pyinstaller job on `main` and now it fails.

```
Traceback (most recent call last):
  File "run_astropy_tests.py", line 12, in <module>
    import pytest
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pytest/__init__.py", line 3, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pytest/collect.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "_pytest/deprecated.py", line 13, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "_pytest/warning_types.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "_pytest/compat.py", line 36, in <module>
  File "py/_vendored_packages/apipkg/__init__.py", line 157, in __makeattr
  File "py/_vendored_packages/apipkg/__init__.py", line 75, in importobj
ModuleNotFoundError: No module named 'py._path'
[5161] Failed to execute script 'run_astropy_tests' due to unhandled exception!
```

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to follow advice at https://github.com/astropy/astropy/issues/12837#issuecomment-1035462900 .

* Fix #12820
* Fix #12688

Also see:

* pyinstaller/pyinstaller-hooks-contrib#379

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
I'll cancel everything but pyinstaller job for now.

**Comment by pllim** [comment]
Yup yup, pyinstaller job fails now, as predicted. But I have no idea how to fix it.

What I also don't understand is why v5.0.x branch has this same failure even with the metadata stuff still there. 🤯 

cc @astrofrog @EfremBraun @bwoodsend

**Comment by pllim** [comment]
@bwoodsend , is the CI expected to pick up the new pyinstaller release immediately or should I wait a little bit? Thanks!

**Comment by bwoodsend** [comment]
It's not pyinstaller - it's the hooks repo (pyinstaller-hooks-contrib). But yes, it's on PyPI so fire away.

**Comment by bwoodsend** [comment]
[This failure](https://github.com/astropy/astropy/runs/5219298589?check_suite_focus=true#step:6:185) has nothing to do with numpy's metadata though so unless you've addressed that elsewhere it'll still fail in exactly the same place.

**Comment by pllim** [comment]
What does this mean?

```
py/_vendored_packages/apipkg/__init__.py:75: in importobj
    ???
E   ModuleNotFoundError: No module named 'py._code'
```

**Comment by bwoodsend** [comment]
I suppose in the short term it means add `--collect-submodules=py` [here](https://github.com/astropy/astropy/blob/cd730f9f77b70471948c46db07a6861c9445c312/tox.ini#L157). We'll need to fix that our end too.

**Comment by pllim** [comment]
It passed. Thanks! 😸

**Comment by pllim** [comment]
Hmm... should I be more adventurous? Maybe I should see how much of these I can fix here too.

https://github.com/astropy/astropy/issues?q=is%3Aissue+is%3Aopen+pyinstaller

**Comment by bwoodsend** [comment]
Both PyInstaller and NumPy have released fixes for the latest PyInstaller+NumPy issue so that one should work fine.

**Review by astrofrog — APPROVED** [review]

**Pull request merged**
