### PR TITLE
WIP: Rebinning (sub-sampling) of NDData (with or without WCS)

### PR DESCRIPTION
**Pull request by brechmos-stsci**
I added in code that will apply a sub-sample factor to the data passed in to it.  The data can be 2D or 3D and can include or not include the corresponding WCS. If the WCS is included then the reproject_linear function is called (from https://github.com/astrofrog/reproject).  If the WCS is not included then scipy map_coordinates is used.

To Do: 
  * I need to add tests.

RFC @mwcraig

Manual Testing:
image

[runme_test_factor.py.txt](https://github.com/astropy/astropy/files/1438160/runme_test_factor.py.txt)

### CODE REVIEW

**Comment by brechmos-stsci** [comment]
@mwcraig  A couple of questions:
  * Maybe offline, but we should talk about how I should do tests
  * reproject uses map_coordinates, I wanted to use similar, but there are slightly cleaner ways to do it

**Comment by MSeifert04** [comment]
Thank you for the pull request @brechmos-stsci !

Just a very general question: Wouldn't it make more sense to include it in an affiliated package like `ccdproc` instead of astropy itself? It seems like a very special purpose function vs. the very general purpose utilities that are in the nddata-utilities.

**Comment by brechmos-stsci** [comment]
@MSeifert04  I had talked to @mwcraig (and @larrybradley)  about it and he/they said it might fit here (similar to Cutout2D). @mwcraig asked me to post a PR and then we could discuss.

**Comment by eteq** [comment]
We should get @astrofrog's opinion on this, but my first instinct as that this belongs in *reproject*.  Particularly given that it requires reproject to do operations with wcs.

**Comment by pllim** [comment]
p.s. I had to remove and re-apply the milestone to make bot happier. Don't mind me.

**Comment by larrybradley** [comment]
@eteq  What about the case of rebinning *without* a WCS?  That part, at least, seems like a more natural fit for astropy.  However, there should not be two separate rebinning functions (i.e. one with wcs and one without) that live in separate packages, so perhaps `reproject` is the best place.

**Comment by mwcraig** [comment]
@brechmos-stsci -- let's talk offline about the tests. I don't have particularly strong feelings about `map_coordinates` vs something else, but it would probably make sense to be consistent with reproject. 

@astrofrog - let us know what you think about the location of this.

**Comment by crawfordsm** [comment]
Adding the wcs rebinning would be great to have so thanks very much for the contribution @brechmos-stsci !

Maybe I'm missing something, but we also already do have the [block_reduce](https://github.com/astropy/astropy/blob/df04c13a5efd78df21341b0d0ee6fa0603fa014b/astropy/nddata/utils.py#L344) and [block_replicate](https://github.com/astropy/astropy/blob/df04c13a5efd78df21341b0d0ee6fa0603fa014b/astropy/nddata/utils.py#L415) functions as well in `NDData.utils`.  These currently handle the non-wcs example but do not handle wcs, so this is something useful to add.   However, I think we should think a little carefully about how to include this. We have depreciated `rebin` in the past when it was part of `ccdproc`.   I'm not opposed to having a `rebin` function that works in either direction and includes wcs and I'm usually in favor of more convenience functions not less (though I realize I'm often in the minority in that case).  However, under the hood, it would make sense to have one set of codes to support rather than multiple functions doing the same thing.  

As for where, this does look to be an appropriate place for it, but also depends on @astrofrog long term feelings about reproject.

**Comment by astrofrog** [comment]
In my view rebinning (e.g. combining pixels using mean/median/sum/etc) and resampling by interpolation are two different things.

This PR implements resampling - since this essentially depends on reproject, the function here should live in reproject, otherwise it's a bit strange to have a circular dependency between astropy and reproject.

However, astropy.nddata does have a rebinning function: block_reduce, and I think what would be great would be to WCS-enable those. The WCS-enabled version should still live in astropy core.

**Comment by brechmos-stsci** [comment]
@astrofrog and I talked too. What I will do is move this code into reproject and we can close this PR _without_ merge.

**Comment by larrybradley** [comment]
I'll just add that the `block_reduce` handles only integer binning factors (i.e. it doesn't perform interpolation).  Non-integer rebinning may be useful to add too.

**Pull request closed without merging**
