### PR TITLE
Extend wrapping of ERFA functions to AngleOps and SphericalCartesian

### PR DESCRIPTION
**Pull request by jwoillez**
One small step closer to making a full fledge ERFA available to python, somewhat related to #3123.

### CODE REVIEW

**Comment by jwoillez** [comment]
I will continue adding tests to make coveralls happy. However, I have no idea where the sphinx error comes from. Could someone please help me and have a look? Thanks!

**Comment by bsipocz** [comment]
@jwoillez - It looks like that the numpy docs page was down, and the intersphinx reference file couldn't be downloaded, thus all of the cross references were raised as a warning. One should restart the build once numpy is back online.

(On a separate note: @astrofrog @eteq - do you think we should host a back-up intersphinx inventory in ``astropy-data``? Sphinx supports to have multiple location listed in the mapping, and takes the first working one for each inventory).

**Comment by jwoillez** [comment]
@bsipocz - Thanks for the explanation! It look like things are working again.

All, this PR is ready for review. I hope you will spare me the -0.1% of coverage. ;)

**Comment by eteq** [comment]
@jwoillez - I am actually :-1: to this, at least in the astropy core itself.  I could be missing something, but my read of AngleOps and SphericalCartesian is that it's basically a C-level library for angle and vector math.  That's already in `astropy` as part of the `coordinates` package, but implemented in a more pythonic manner.

That said, it might make more sense for this to go into a *dedicated* pyerfa package (which could live in [liberfa](https://github.com/liberfa) as a separate project, but could use the affiliated package template to minmize headaches ).  Astropy would then just treat it as another `extern`.

Or am I misunderstanding the main purpose of these functions?

**Comment by jwoillez** [comment]
@eteq - I don't think I have the time ressources to go all the way to `pyerfa`, but this is a small step in that direction. Would looking at it form this angle be sufficient to accept this PR? We still have erfa in semi private `astropy._erfa`; there is therefore no intent to compete with what `coordinates` already does.  This is just an increase of the exposure of `erfa` to python for those (like myself) who need direct access to `erfa`.

**Comment by eteq** [comment]
@jwoillez - I might see your point here, but I guess I don't understand in what circumstances this is useful on the python side.  Isn't it all available already?  Or are there some functions that have functionality missing from numpy/astropy/whatever?

**Comment by hamogu** [comment]
I have a feeling that @taldcroft would like this. It's probably a lot faster to get angular separations this way than through the coordinates package using compiled C code that's included in astropy already anyway.
See #3908

**Comment by astrofrog** [comment]
I would be interested to see some performance comparisons compared to the Python implementations we already use. For large arrays, there may be some nice performance improvements due to avoiding multiple copies of arrays. If this is faster, then I would be in favor of making use of this internally.

I agree we probably don't want to expose these though the public API, but if they make the code faster internally, why not?

**Comment by mhvk** [comment]
I think eventually one wants all `erfa` functions exposed to python in `liberfa/erfa` itself, maybe via a `pyerfa` subpackage or so, and then access it via something like `astropy.extern.erfa`.  I can see using some of the vector matrix routines internally, although probably only in some performance-critical places, since there is considerable benefit to having the formalae explicitly written out.

**Comment by eteq** [comment]
@mhvk - I've come around to the idea of a ``liberfa/pyerfa`` or something like that, just as you say here.  The downside is that it's yet more release management... But if it's tied to the ``liberfa`` release cycle it's not *that* much overhead.

I'm less sure we want to use this internally, though... I agree with @astrofrog that if there's a sizable performance increase it's worth it, but there is a real virtue in having the code be readable in python, which I think outweighs a *modest* performance increase.

**Comment by mhvk** [comment]
OK, sounds like we all agree on the end goal. The more immediate question is what to do here; my feeling is to merge as is, since it brings `liberfa` closer and in the meantime doesn't really make the code base much larger anyway.

**Comment by taldcroft** [comment]
:+1: from me for going forward with this PR, assuming it stays out of the public API.

I think a big role for a robust pyerfa wrapper is to provide meaningful function names.  From that perspective I would agree that any ERFA functions that are visible currently using the completely cryptic original names should never be made public through astropy.

**Comment by mhvk** [comment]
OK, merging! Thanks, @jwoillez!

**Comment by eteq** [comment]
Oops, shouldn't have merged that yet.  As I said above I felt that this should definitely *not* be merged until we know we're going to use it.  Not an especially big deal at this point, though.  I guess if we end up not using it we can take it out again.

**Comment by eteq** [comment]
In #4664 I created an issue to follow-up on this, so further discussion on actually using this can go there.

**Comment by mhvk** [comment]
@eteq - sorry for being too quick here. My sense was that the path we agreed on was that we *do* want a set of numpy-enabled python wrappers (`pyerfa`) eventually, which would wrap all routines, and that it was fine to merge that here in preparation for eventually moving over to `liberfa`. I don't know that there is any reason to revert: as is, I'd think we already cover quite a few astronomy routines which we end up not using.

**Comment by eteq** [comment]
True enough - and I wasn't communicating too clearly what I was objecting to, so it's not a big deal.  The primary downside is that it adds to the compilation time.  But that might be a very small effect, I didn't look.  Mainly this is my knee-jerk "don't add any more than necessary" attitude.

**Comment by astrofrog** [comment]
@eteq - I'm marking this as 'no-changelog-needed' because it's private API, right?

**Pull request merged**
