### PR TITLE
Revert "Merge pull request #11143 from maxnoe/unix_time_ptp"

### PR DESCRIPTION
**Pull request by taldcroft**
This reverts commit ec983207505a2c1dcaefdb3b32fe0d9f30a2b716, reversing
changes made to 960314366be1bfdc3b2e7488fde0d2f780562f68.

### Description

This pull request is to revert #11143 as part of fixing #11245.

I did this with the following since the GitHub `Revert` button failed:
```
git revert -m 1 ec98320
```

But maybe @pllim knows the best way to do this?

### CODE REVIEW

**Comment by pllim** [comment]
I don't think I have reverted in this repo before, but if the diff looks good to you, then it worked. 😸

**Comment by pllim** [comment]
p.s. Is the diff for the change log missing?

**Comment by mhvk** [comment]
Looks good apart from what @pllim noted: the changelog entry somehow was missed. How bizarre!

**Comment by maxnoe** [comment]
He reverted the commit,  not the pr. The changelog every is in another commit, since it requires knowing the pr number.

**Comment by pllim** [comment]
Hmmm, I thought `-m 1 ec98320` would revert the whole PR merge...

**Comment by pllim** [comment]
That PR only has 1 commit and `git revert 36c0f603f9916100837406c0e3a4934c3685f462` doesn't grab the change log either. 🤯

**Comment by taldcroft** [comment]
> The changelog every is in another commit, since it requires knowing the pr number.

Slightly OT, but check out this gem to get the PR number (*most* of the time) before you make the PR.
https://github.com/astropy/astropy-procedures/blob/master/next_pr_number.py

**Comment by taldcroft** [comment]
That's really really weird. I confirm also that reverting the single commit doesn't catch the change log as well. Maybe there was some kind of conflict and it just silently ignores it??

Anyway I manually fixed the changelog with another commit.

**Review by mhvk — APPROVED** [review]
You're surely right about there being some conflict, but very odd that `git` reversion does not at least warn about that! Anyway, it looks all good now, so approving.

**Comment by maxnoe** [comment]
The test failure seems unrelated. It would be easier to merge this before #11249, because then I don't have to fix the tests for comparing unix with unix_ptp

**Comment by pllim** [comment]
Merged!

**Pull request merged**
