### PR TITLE
Update IERS-B table to Dec 2017.

### PR DESCRIPTION
**Pull request by mhvk**
Strangely, there are a lot of differences, all tiny and small even compared to the errors, but this makes the commit very large.

Despite this, I think it is important to update... And arguably backport, hence the milestone.

### CODE REVIEW

**Comment by mhvk** [comment]
@eteq - i've adjusted tests and docs. The earlier failure in `frames.rst` is a bit puzzling - I'd have though that `FLOAT_CMP` would have resolved that, but apparently it is just a bit too big.

**Comment by mhvk** [comment]
@eteq - shall we merge this?

**Comment by pllim** [comment]
Given that @eteq has approved this before he un-approved it only (seems like) on the grounds of test failure and the failure has since been fixed, I am going to put on my maintainer hat and merge this before feature freeze. Thanks!

**Comment by mhvk** [comment]
Thanks!

**Pull request merged**
