### PR TITLE
DOC: Autoreformat a few files.

### PR DESCRIPTION
**Pull request by Carreau**
Run velin on a few files and cherry-pick the changes that are not purely
blank lines.

---

See #11590 for preceding discussion; 
Let me know and I can also include the blank line changes if subsequents updates.

### CODE REVIEW

**Comment by pllim** [comment]
Still not comletely sold on the `*` and `**` but the rest of the changes are uncontroversial.

**Comment by Carreau** [comment]
> Still not completely sold on the `*` and `**`

Up to you, I can remove, numpydoc reference was recently ammended to [add](https://github.com/numpy/numpydoc/pull/310/files)

> When documenting variable length positional, or keyword arguments, leave the
>  leading star(s) in front of the name::

**Comment by pllim** [comment]
Thanks! I am guessing this supersedes #11590 ? Is there any reason to keep the other one open?

> Up to you

Let's wait and see what others say.

**Comment by saimn** [comment]
Having the `*` / `**` seems useful to emphasize that it's a special parameter, and if that's now standardized in numpydoc then that seems the good solution to me. (Nice tool btw @Carreau , I wish I could have used it in the past!)

**Review by mhvk — APPROVED** [review]
I think all changes are great now! I'm quite happy to go with the numpydoc recommendation of including `*` and `**` (even if @Carreau made the change!), as I think it helps to make clear that these are special.

**Comment by mhvk** [comment]
OK, let's get this in! Thanks, @Carreau!

**Pull request merged**
