### PR TITLE
Allow Ellipse2D and Sersic2D theta to be a quantity

### PR DESCRIPTION
**Pull request by larrybradley**
### Description

This PR allows the ``Ellipse2D`` and ``Sersic2D`` `theta` parameter to be input as an angular quantity.  I'm calling this a new "feature" instead of a "bugfix" (but I can change that).  Technically, there was nothing preventing quantity `theta` inputs, but the `theta` docstrings for `Ellipse2D` and `Sersic2D` only mention "float as radian". Also, for `Ellipse2D` a quantity `theta` would give the incorrect `bounding_box` (there was actually an `Ellipse2D` unit test for quantity theta, but it gives the wrong result).  `Sersic2D` does not define a `bounding_box`, so angular `theta` works as expected, but was not documented.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by WilliamJamieson — CHANGES_REQUESTED** [review]
I only see one small changed to the tests (the fix for the bounding box test on `Ellipse2D`). 

Can you add tests for `Ellipse2D` and `Sersic2D` with `theta` acting both as a "float as radian" and as a "angle quality"?

**Comment by larrybradley** [comment]
The CI failures are unrelated and are coming from VOTable.

**Comment by pllim** [comment]
Looks related to me.  You forgot to mark `skipif`?

```
        if cls._gammaincinv is None:
>           from scipy.special import gammaincinv
E           ModuleNotFoundError: No module named 'scipy'

.../astropy/modeling/functional_models.py:3087: ModuleNotFoundError
```

**Comment by larrybradley** [comment]
Thanks, @pllim .  Indeed, `Sersic2D` requires `scipy`.  I fixed the test.

**Review by WilliamJamieson — APPROVED** [review]

**Pull request merged**
