### PR TITLE
Simplify `codespell` configuration

### LINKED ISSUE #16537: TST: `codespell` to ignore credit file, remove contributor names from ignore list
See https://github.com/astropy/astropy/pull/16536#discussion_r1626254544 by @eerovaher 

*remove all names from the global ignore list in `pyproject.toml`*

### PR DESCRIPTION
**Pull request by eerovaher**
### Description

The first commit removes needless [`codespell`](https://github.com/codespell-project/codespell) ignore list entries.

The second commit spreads out the files and directories `codespell` should skip over multiple lines to make the list easier to read.

The third commit adds `astropy/CITATION` and `docs/credits.rst` to the files to skip. They both contain a large number of names, some of which look like misspelled words to `codespell`. Previously the names `codespell` should ignore were specified individually, but that could lead to genuine typos going undetected and might require maintainer effort in case new names get added or if the `codespell` word list gets updated. It is better to configure `codespell` to ignore the two files instead. This does allow typos there to go unnoticed, but the amount of text in them is very small. Setting up per-line `codespell` ignores is not suitable because the BibTeX entries in `astropy/CITATION` are meant to be copy-pasteable.

The third commit resolves #16537

- [x] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Hmm pre-commit check timed out. Not sure how to restart it without anothe push or close/re-open.

**Comment by neutrinoceros** [comment]
Commenting `pre-commit.ci run` should do it. However there seem to be a problem on their website so I wouldn't bother retriggering it just now.

**Comment by pllim** [comment]
pre-commit.ci autofix

**Review by pllim — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
