### PR TITLE
Add divmod ufunc to supported, and isnat to unsupported ufuncs.

### PR DESCRIPTION
**Pull request by mhvk**

### CODE REVIEW

**Comment by MSeifert04** [comment]
Is it possible that NumPy got a whole bunch of new ufuncs? It seems like once per week you need to add new ones 😄

**Comment by mhvk** [comment]
Yes, they got quite a few, and then there's `__array_ufunc__` too...  (#2583).

**Comment by mhvk** [comment]
all tests passed. as this is relatively simple, I'll merge so I can rebase #2583 and get that tested again.

**Comment by bsipocz** [comment]
@mhvk - I've backported this to 1.3.3 to get one more prerease test pass.

**Pull request merged**
