### PR TITLE
Add an attribute to frame classes to retrieve all component names

### LINKED ISSUE #8373: Add shortcut to get all component names from a coordinate object
Lately, I've had a few use cases where I need to grab all (6 in my case) of the position and velocity components off of a frame or SkyCoord instance. The code to do this is only a few lines, but many characters! So I'm wondering what you think about adding a convenience property that does something like:

```python
@property
def component_names(self):
    names = list(self.get_representation_component_names().keys())
    
    for key in self.data.differentials:
        names += list(self.get_representation_component_names(key).keys())
    
    return names
```

cc @mhvk @eteq

### PR DESCRIPTION
**Pull request by adrn**
This adds a new `.component_names` attribute that returns a list of strings containing all position and velocity component names for a given frame class or `SkyCoord` instance. This also adds support for `which='all'` in both `get_representation_component_units()` and `get_representation_component_names()`, which then return the component units and component name mappings for all components simultaneously.

In the current PR, I also made a slight API change that is worth discussing (before I add a changelog entry, in case I should revert). I noticed a discrepancy in master that:
```python
>>> c = coord.SkyCoord(1*u.deg, 2*u.deg)
>>> c.get_representation_component_units()
OrderedDict([('ra', Unit("deg")), ('dec', Unit("deg"))])
>>> c.get_representation_component_names()
OrderedDict([('ra', 'lon'), ('dec', 'lat'), ('distance', 'distance')])
```

That is, `.get_representation_component_units()` does not return a key for `distance` because that unit is None. In this PR, I've changed the behavior of `.get_representation_component_units()`:
```python
>>> c.get_representation_component_units()
OrderedDict([('ra', Unit("deg")), ('dec', Unit("deg")), ('distance', None)])
```

This fixes #8373

### CODE REVIEW

**Comment by mhvk** [comment]
@adrn - I like the simplification in the implementation, but two questions:
1. For `distance`, I'm not sure I like including it for what really is `UnitSpherical` and thus doesn't really have a distance. If we do include it, should the unit be `dimensionless_unscaled`? Possibly, it is easiest to keep the behaviour the same in this PR and discuss this further in a separate issue.
2. As also asked in https://github.com/astropy/astropy/issues/8373#issuecomment-457208096, is just a list of names actually the most useful? Wouldn't you rather have a `dict` where the values are something useful? E.g., I could see the use of a new `get_representation_components(self, which='base')` and a `components` property that does that one with `which='all'`. (Though this is slightly inconsistent with `Represenatation.components`, which returns a tuple.) But in a way it really depends on what in your code you actually do with those names after getting them...

**Comment by adrn** [comment]
1. OK yes I will move that to a separate issue - I think this is related to the broader discussion of `Spherical`+dimensionless distance vs. `UnitSpherical`, which might be worth revisiting before 4.0.
2. Sometimes I just need the component names, to just read values out of a table I had created. However, other times it would be useful to have the component values as well, so the new method could be useful.

**Comment by mhvk** [comment]
The advantage of an (ordered) `dict` would be that you'd get both the component names, and, if you happen to need it, the values (which of course carry the units as well, so in a way it replaces `get_component_units`). And of course you're just a `tuple(sc.components)` away from getting just the names, if for some reason that matters.

p.s. I must admit that I'm a little unsure why we have all those `get_representation_component_*` functions...

**Comment by adrn** [comment]
@eteq @mhvk While reviving this PR and thinking about whether to include distance or not for a `unitspherical`, I encountered some other things that we have been sweeping under the rug since we added support for velocities.

To summarize, we are a bit sloppy with the way we return and display data to the user when they haven't specified a given component. For example, not passing a distance internally sometimes turns into "distance = 1 dimensionless" but is mostly ignored in display to the user:
```python
>>> c = coord.SkyCoord(15, 22, unit=u.deg)
>>> c
<SkyCoord (ICRS): (ra, dec) in deg
    (15., 22.)>
>>> c.distance
<Quantity 1.>
```

For velocities:
```python
>>> c.radial_velocity
ValueError: Frame has no associated velocity (Differential) data information.
...
>>> c1 = coord.SkyCoord(15, 22, unit=u.deg, radial_velocity=1*u.km/u.s)
>>> c1.pm_ra_cosdec
<Quantity 2.77555756e-17 km rad / s>
```
That is: before a `radial_velocity` is passed in, we throw an error if we try to access any velocity component. But after a `radial_velocity` is specified, other, non-specified velocity components become equivalent to 0.

So, I'm a bit confused now: in the dictionary returned by `.components` or `.get_components`, should it always include all components? Should it only include components with meaningful data (i.e. should we check for close to 0 velocity [not explicitly passed in] and distance = 1 dimensionless )?

**Comment by mhvk** [comment]
Belatedly, what's up with that unit of `pm_ra_cosdec`?

But, yes, given that the only differential in there is a `RadialDifferential`, the proper motions should be 0 and have a sensible unit, be `None`, or raise an error. And probably be absent in any summary (as is the case when one just looks at the `repr`).

**Comment by bsipocz** [comment]
This needs a rebase, and probably a remilestoning.

**Pull request closed without merging**
