### PR TITLE
use cdef double over cdef

### PR DESCRIPTION
**Pull request by nstarman**
From: https://github.com/astropy/astropy/pull/15049

### CODE REVIEW

**Comment by nstarman** [comment]
Is a changelog entry needed? Is this technically a bug fix that should be backported?

**Comment by saimn** [comment]
It was not a bug (a Python object was used instead of a c variable), maybe just a small perf improvement.

**Review by pllim — APPROVED** [review]
Doesn't hurt? I'll let someone who knows Cython to merge.

**Comment by saimn** [comment]
Ok, let's merge then, thanks @nstarman.

**Pull request merged**
