### PR TITLE
Ensure cenfunc and stdfunc scalars are np.float64

### PR DESCRIPTION
**Pull request by larrybradley**
### Description

`bottleneck` returns `float` scalars -- this PR converts them to `np.float64` scalars for consistency.
Addresses https://github.com/astropy/astropy/pull/15065#issuecomment-2103196197

Technically, this is a (minor) API change.  Does it need a change log entry?

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
> Does it need a change log entry?

Doesn't hurt? It is quite a subtle change. However, this will be backported (right?) and so the only option is "bug fix" and not "API change". 🤷‍♀️

**Review by neutrinoceros — CHANGES_REQUESTED** [review]
I would prefer we put the responsability of the return type of `SigmaClip._parse_(cen|std)func` on the functions themselves, especially because in that context, bottleneck is already involved via `HAS_BOTTLENECK` so it's less likely to get out of sync somehow.

**Comment by neutrinoceros** [comment]
And for what it's worth, I'd err on the side of classifying this as a bugfix: the fact that the return type of some function might depend on what I have installed is (I think) never expected.

**Review by pllim — APPROVED** [review]
Thanks!

**Comment by mhvk** [comment]
Belatedly (am travelling) - looks nice!

**Pull request merged**
