### PR TITLE
Resolve str AssertionErrors on ExceptionInfo objects in pytest 5

### PR DESCRIPTION
**Pull request by dhomeier**
Attempt to fix errors of the kind
```
>       assert "A Latitude angle cannot be created from a Longitude angle" in str(excinfo)
E       AssertionError: assert 'A Latitude angle cannot be created from a Longitude angle' in '<ExceptionInfo TypeError tblen=2>'
E        +  where '<ExceptionInfo TypeError tblen=2>' = str(<ExceptionInfo TypeError tblen=2>)
```
that started to appear with pytest 5.0.0 as discussed in #8934.
General remedy is to call `str(excinfo.value)` rather than `str(excinfo)`, but there are a few cases where `excinfo` has no method `value` - see in particular patches to `io` and `table`. Apparently some hand-crafted or derived exceptions like `FileNotFoundError` or `fits.VerifyError` still return a plain string instead of an `ExceptionInfo`, but I could not find any hints in the pytest docs how to properly declare exception classes to better handle this.
Also `excinfo.value` does not contain the exception name, but since this is generally checked against immediately before, I think it can be safely omitted from the string comparison.
On the plus side, `ExceptionInfo` provides its own `match` method, simplifying some `re` comparisons (cf. `test_html.py` and `test_wcsprm.py`).
Tested with pytest 5.0.0 on Python 3.5 and 3.8; 4 unrelated `visualisation.wcsaxes` failures that turn up identically with pytest 3.10.1.

### CODE REVIEW

**Comment by dhomeier** [comment]
Would the changelog entry go under **Bug fixes:** `astropy.tests`?

**Comment by bsipocz** [comment]
@dhomeier - no, this is neither user facing nor has any real behaviour change, so don't need a changelog.

**Comment by bsipocz** [comment]
Thanks @dhomeier!

**Comment by dhomeier** [comment]
@bsipocz - no, definitely no user-relevant changes here, but it might be useful to document for casual developers and contributors - don't know where to best put it though.

**Pull request merged**
