### PR TITLE
Ensure quantity initialization of Column with function units works.

### LINKED ISSUE #8430: Quantity(column_with_log_unit, subok=True) should work
As found in #8424, the following does not currently work:
```
from astropy.table import Column
from astropy import units as u

c = Column([1.,2.,3.], unit=u.dex(u.AA))
u.Quantity(c, subok=True)
# UnitTypeError: Quantity instances require <class 'astropy.units.core.UnitBase'> units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.
u.Quantity(c, c.unit, subok=True)
# <Dex [1., 2., 3.] dex(Angstrom)>
```
There doesn't seem to be a reason for this to happen. Likely all that is needed is to move the `subok` test from early on to a little later, after getting a possible unit from `value` (might also be possible to do this more automatically by using `cls.new_view` instead of taking `.view(cls)`)

### PR DESCRIPTION
**Pull request by mhvk**
As long as ``subok=True``, it now returns the relevant function quantity.

fixes #8430

### CODE REVIEW

**Comment by adrn** [comment]
Sorry for missing this — looks fine to me, once you rebase for the silly changelog conflict!

**Comment by mhvk** [comment]
OK, rebased, and also got rid of a duplicate entry in `CHANGES.rst` (likely from another rebase...)

**Comment by mhvk** [comment]
And rebased again - sigh - though I think it was my own PR that made it necessary.

**Comment by bsipocz** [comment]
Thanks @mhvk!

**Pull request merged**
