### PR TITLE
Improve package description

### LINKED ISSUE #3830: SEO for Astropy
Two current methods for searching for Python packages don't place Astropy very highly.  The first is:

```
$ pip search astronomy
```

which for me currently results in:

```
astropyp                  - Astronomy Pypeline Framework and FITS Viewer
image_registration        - Image Registration Tools for extended images in astronomy.
novas                     - The United States Naval Observatory NOVAS astronomy library
skyfield                  - Elegant astronomy for Python
gammapy                   - A Python package for gamma-ray astronomy
astroobs                  - Provides astronomy ephemeris to plan telescope observations
PyAstronomy               - A collection of astronomy related tools for Python.
astroML                   - tools for machine learning and data mining in Astronomy
Barak                     - A set of astronomy-related routines for generating Voigt profiles from atomic data,
                            reading and writing data, working with SEDs, passbands and dust extinction laws.
astropy                   - Community-developed python astronomy tools
gary                      - Galactic astronomy and gravitational dynamics.
palpy                     - PAL -- A Positional Astronomy Library
python-casacore           - A wrapper around CASACORE, the radio astronomy library
```

(as an aside, are we sure we don't want to name the Astropy distribution "Astropy", i.e. capitalized instead of lowercase?  I think it would stand out more.)

```
$ pip install astrophysics
```

fares even worse:

```
Astropysics               - Astrophysics libraries for Python
BOTEC                     - A simple astrophysics and orbital mechanics simulator
gwpy                      - A package to enable gravitational-wave astrophysics in Python.
```

(although at least we get Astropysics, which points to Astropy in its docs, but Astropy should be searchable under "astrophysics" too IMO).

I'm not sure how pip chooses how to order search results, but I'll look into it and see if we can "game" the system :)

The search bar on PyPI is no better:
astropy-pypi
This at least displays all current versions of Astropy, so it stands out more.  But it's still a bit silly.  It also doesn't rank the versions in any useful way, and in call cases they are given a "Weight" of 3, where according to the site "Weight" is defined by "Occurrence of search term weighted by field (name, summary, keywords, description, author, maintainer)".  PyAstronomy wins out in this case since "astronomy" is right in the name.

Astropy _does_ show up on PyPI with a search for "astrophysics", but with a Weight of 1, below a number of other packages (the term "astrophysics" does appear once in the package description).

### PR DESCRIPTION
**Pull request by zdroid**
An address for #3830. For more details, see there. This should improve the results for `pip search astronomy`, but it probably won't help `pip search astrophysics` at all. Maybe `astrophysics` should be added to description too.

Note: there is a similar description in [astropy/CITATION](https://github.com/astropy/astropy/blob/master/astropy/CITATION), should it be changed as well?

### CODE REVIEW

**Comment by bsipocz** [comment]
I would say to leave this open a for a bit for others to chime in, as any change in the search results won't happen until this is released (I didn't find a way to edit the one liner on pypi). 
E.g. the we could even drop "community" from the summary to have fewer words and thus a higher score. Also we could maybe also tweak the keywords and description.

I think the citation file looks OK, and it should not have any effect on the search results.

(I've edited out the auto closing of #3830, as this may or may not be enough to address it).

**Comment by bsipocz** [comment]
cc @astropy/coordinators whether you have any strong feelings of what the pypi one liner is.

**Comment by mhvk** [comment]
I like the change. Could add `and astrophysics` to bump search engines further? (Though `Time` and `SkyCoord` feel more like astronomy to me; `modeling`, though, goes more in the direction of `astrophysics`).

If we used the same line before elsewhere, it would seem best to change it there too.

**Comment by bsipocz** [comment]
"Core library for astronomy and astrophysics"?

**Comment by bsipocz** [comment]
We certainly need to improve the description, too. It reads well, but that doesn't reflect on the search results, we're even lower now on pypi than we've been a year ago, I add what I see atm for `pip search astronomy`:

https://pypi.org/project/astropy/

```
astronomy (0.0.1)             - Astronomy!
gastropy (0.0dev)             - (g)astronomy
catastropy (0.0dev)           - (cat)astronomy
astromath (1.0.1)             - Library for mathematical astronomy
pykepler (1.0.1)              - Algorithms for positional astronomy
astro-scripts (0.4.0)         - Small scripts for astronomy
intake-astro (0.1.1)          - Astronomy plugins for Intake
celespy (0.0.5)               - Generic astronomy functions
n2-tools (0.0.26)             - tools for astronomy data
skyfield (1.18)               - Elegant astronomy for Python
gary (0.1a)                   - Galactic astronomy and gravitational dynamics.
hips (0.2)                    - Python astronomy package for HiPS
sinistra (0.3.3)              - A collection of astronomy related tools.
acalib (0.1.3)                - Advanced Computing for Astronomy Library
gravpy (0.2.3)                - A sandbox for gravitational wave astronomy.
codex-africanus (0.2.2)       - Radio Astronomy Building Blocks
numina (0.21)                 - Astronomy data reduction library
palpy (1.8.1)                 - PAL -- A Positional Astronomy Library
fidia (0.4rc1)                - Format Independent Data Interface for Astronomy
PyAstronomy (0.14.0)          - A collection of astronomy related tools for Python.
mirapy (0.1.0)                - Python package for Deep Learning in Astronomy
ragavi (0.3.2)                - Radio Astronomy Gain and Visibility Inspector
mclearn (0.1.6)               - Active learning algorithms with application in astronomy.
gammapy (0.17)                - A Python package for gamma-ray astronomy
pyastroschema (0.5.4)         - Standardized specifications for astronomy and astrophysics data.
experimentsLogReader (2.2.2)  - Log file reader for Radio Astronomy
starry-beta (0.3.0)           - Analytic occultation light curves for astronomy.
astrotoyz (0.1.4)             - Astronomy tools built on the Toyz framework
starry (1.0.0)                - Analytic occultation light curves for astronomy.
rainbow-connection (0.0.3)    - Pedagogical tools for light and color in astronomy.
astropy (4.0.1.post1)         - Community-developed python astronomy tools
  INSTALLED: 4.1.dev959+g5034b40c7
  LATEST:    4.0.1.post1
```

**Comment by pllim** [comment]
If you really want to game it, change to "Astronomy!!!!!! Astronomy!!!!" ? 😹

**Comment by bsipocz** [comment]
I don't suggest to troll it, but we can certainly do better than the current one.

**Comment by zdroid** [comment]
How about `Astronomy and astrophysics core library`? Same meaning, but more `astronomy` for pypi. :laughing:

**Comment by zdroid** [comment]
Now I changed the description in `astropy/CITATION` as well.

**Comment by bsipocz** [comment]
I would like to merge this fast, to be included in 4.0.2 to check how things improve. 
Please remove the changes to to the citation file. There we certainly want to keep the mention of Python and it needs a wider agreement anyway, while as the releaser, I can make the call on changing the blurb for pypi.

**Comment by zdroid** [comment]
@bsipocz Makes sense, done.

**Comment by zdroid** [comment]
Gil Scott-Heron - The Revolution Will Not Be Televised

**Comment by bsipocz** [comment]
OK, let's go ahead with this description for 4.0.2, and see how the overall results change when that release is out.

**Comment by bsipocz** [comment]
Thanks @zdroid!

**Pull request merged**
