### PR TITLE
Suppress errors when creating WCS in CCDData reader

### LINKED ISSUE #6499: CCDData without considering WCS
I have been working on reducing [FOCAS data](http://smoka.nao.ac.jp/search?resolver=NONE&object=KISSJ1100%2B4421&instruments=FCS&spectrographs=FCS&obs_mod=all&data_typ=OBJECT&dispcol=default&action=Search&diff=1000&asciitable=Table) for this semester's TA work. 

When I try to read any data with ``CCDData``, I get the following errors
```python
ccd = CCDData.read('FCSA00150629.fits')

WARNING: FITSFixedWarning: PC001001= 1.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: PC001001= 1.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja.
WARNING: FITSFixedWarning: PC001002= 0.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: PC001002= 0.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja.
WARNING: FITSFixedWarning: PC002001= 0.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: PC002001= 0.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja.
WARNING: FITSFixedWarning: PC002002= 1.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: PC002002= 1.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja.
WARNING: FITSFixedWarning: RADECSYS= 'FK5 ' / The equatorial coordinate system 
the RADECSYS keyword is deprecated, use RADESYSa. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: RADECSYS= 'FK5 ' / The equatorial coordinate system 
the RADECSYS keyword is deprecated, use RADESYSa.
WARNING: FITSFixedWarning: 'unitfix' made the change 'Changed units: 'degree' -> 'deg''. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: 'unitfix' made the change 'Changed units: 'degree' -> 'deg''.
WARNING: FITSFixedWarning: 'celfix' made the change 'Unmatched celestial axes'. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: 'celfix' made the change 'Unmatched celestial axes'.
Traceback (most recent call last):

  File "<ipython-input-131-9ba40d7893f2>", line 1, in <module>
    ccd = CCDData.read('FCSA00150629.fits')

  File "/home/aaa/anaconda3/lib/python3.6/site-packages/astropy/nddata/mixins/ndio.py", line 29, in read
    return io_registry.read(cls, *args, **kwargs)

  File "/home/aaa/anaconda3/lib/python3.6/site-packages/astropy/io/registry.py", line 531, in read
    data = reader(*args, **kwargs)

  File "/home/aaa/anaconda3/lib/python3.6/site-packages/astropy/nddata/ccddata.py", line 521, in fits_ccddata_reader
    hdr, wcs = _generate_wcs_and_update_header(hdr)

  File "/home/aaa/anaconda3/lib/python3.6/site-packages/astropy/nddata/ccddata.py", line 406, in _generate_wcs_and_update_header
    wcs = WCS(hdr)

  File "/home/aaa/anaconda3/lib/python3.6/site-packages/astropy/wcs/wcs.py", line 503, in __init__
    self.wcs.set()

InconsistentAxisTypesError: ERROR 4 in wcs_types() at line 2516 of file cextern/wcslib/C/wcs.c:
Unmatched celestial axes.
```

Although it is due to the problem of WCS keywords of SMOKA archive service, I want to just load the data, without checking the validity of the WCS information in the header. 

I cannot proceed to making master bias, etc.

Is there a way to *ignore WCS* when reading FITS files using ``CCDData``?
Alternatively, is there a task similar to WCSRESET of IRAF in astropy?

### PR DESCRIPTION
**Pull request by MSeifert04**
Fixes #6499 

However I'm not sure what I need to do with the Header so it actually fails so I haven't included a regression test.

### CODE REVIEW

**Comment by pllim** [comment]
Is this considered a bug fix or API change?

**Comment by MSeifert04** [comment]
Basically a bug fix because the current code is based on the assumption that `WCS` cannot fail (but it did).

**Comment by MSeifert04** [comment]
*small bump*

**Comment by MSeifert04** [comment]
@bsipocz It's a fairly simple fix and is only missing reviewers. Would it be possible to still include it in 2.0.2?

**Comment by bsipocz** [comment]
I'm in the final stages of testing the release, so I'm afraid this needs to wait for 2.0.3.

**Comment by MSeifert04** [comment]
@bsipocz okay, no worries. Would've been nice to get this in because it's an almost trivial bugfix.

**Comment by MSeifert04** [comment]
@mwcraig @crawfordsm Could you have a look at the fix?

**Comment by crawfordsm** [comment]
Ah this is great to see as I've run into this problem very recently.  It's a pretty straight forward fix that you have put in and I'd agree this is a bugfix as it shouldn't be a problem due to wcs suppose to always be working.  I've check it out and can confirm that it works, so happy to see it merged.   

Thanks @MSeifert04 !

**Comment by bsipocz** [comment]
Thanks @MSeifert04!

**Pull request merged**
