### PR TITLE
Improve performance of bottleneck stat functions

### PR DESCRIPTION
**Pull request by larrybradley**
### Description

The PR improves the performance of bottleneck stat functions when a tuple axis is used by moving the axis keywords to the *last* axis and then combining them so they can be operated on using `axis=-1`.  The current implementation moves the axes to the first axis and then uses `axis=0`, but that operation is slower because the memory is non-contiguous (for the default C-like order).  The performance difference can be significant for larger (or larger ndim) arrays.

Note the tuple axis reordering is necessary because `bottleneck` only allows integer `axis` values.

Simple example show the axis difference:
```python
>>> arr = np.random.rand(500, 500, 500)

>>> %timeit np.nanmedian(a, axis=0)
7.36 s ± 33.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

>>> %timeit np.nanmedian(a, axis=-1)
4.81 s ± 110 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

@mhvk 

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Yes, makes sense! Would be good to add a benchmark for this, but I'm also fine to just get it in, as it should be obvious it is an improvement (the benchmark would just guard against regressions).

**Comment by larrybradley** [comment]
The performance difference doesn't seem to be a big for the `bottleneck` `nan*` functions probably due to some internal optimization, but it's not slower (in principle, `axis=-1` is good practice).

**Comment by mhvk** [comment]
> The performance difference doesn't seem to be a big for the `bottleneck` `nan*` functions probably due to some internal optimization, but it's not slower (in principle, `axis=-1` is good practice).

Ah, it may indeed be that things get copied first or so. Anyway, very much agreed it is good practice to use the last axis!

**Comment by pllim** [comment]
Any plans to manually backport? Do we really need to?

**Comment by mhvk** [comment]
I think we don't really need to backport this either - should have noticed that! Let me change the milestone and remove the backport label.

**Pull request merged**
