### PR TITLE
Reduce the sample size of some tests in stats.spatial

### PR DESCRIPTION
**Pull request by mirca**
cc @bsipocz

### CODE REVIEW

**Comment by bsipocz** [comment]
This is a follow-up on #5712 which tests additions increased our total travis build duration by ~30-50 mins.

Can be merged when passes tests, and has a significantly reduced total travis build time.

**Comment by mirca** [comment]
@bsipocz I'm gonna push a few changes to speed up things, don't merge immediately, please :)

**Comment by bsipocz** [comment]
Don't worry, tests are not expected to pass in the next 3 hours...

**Comment by mirca** [comment]
@bsipocz Oh, good =)

**Comment by bsipocz** [comment]
But the faster this goes in, the faster the other travis builds become. Maybe you could run travis on your fork, so we can merge sooner?

**Comment by mirca** [comment]
@bsipocz Oh yeah, sure!

**Comment by mirca** [comment]
check it out here: https://github.com/mirca/astropy/pull/1

**Comment by bsipocz** [comment]
Merging as it passed on the fork and total run time is back by an hour.

**Comment by larrybradley** [comment]
Thanks, @mirca!

**Comment by saimn** [comment]
For the record, timings of the slowest tests on Travis (which is for instance x4 slower than my laptop!):
https://travis-ci.org/saimn/astropy/jobs/243453986#L2484
The 4 'ripley' tests were tooking ~8 min per jobs:
```
========================== slowest 50 test durations ===========================
125.03s call     lib.linux-x86_64-3.5/astropy/stats/tests/test_spatial.py::test_ripley_modes[points1--10--5]
119.94s call     lib.linux-x86_64-3.5/astropy/stats/tests/test_spatial.py::test_ripley_large_density[points1--1-0]
117.97s call     lib.linux-x86_64-3.5/astropy/stats/tests/test_spatial.py::test_ripley_large_density[points0-0-1]
116.71s call     lib.linux-x86_64-3.5/astropy/stats/tests/test_spatial.py::test_ripley_modes[points0-5-10]
8.54s call     lib.linux-x86_64-3.5/astropy/units/tests/test_units.py::test_compose_fractional_powers
7.87s call     lib.linux-x86_64-3.5/astropy/units/tests/test_units.py::test_compose_cgs_to_si[Fr]
7.74s call     lib.linux-x86_64-3.5/astropy/units/tests/test_units.py::test_compose_cgs_to_si[Bi]
6.76s call     lib.linux-x86_64-3.5/astropy/units/tests/test_units.py::test_compose_cgs_to_si[statA]
5.79s call     docs/units/decomposing_and_composing.rst
5.63s call     lib.linux-x86_64-3.5/astropy/units/tests/test_units.py::test_complex_compose
4.43s call     lib.linux-x86_64-3.5/astropy/wcs/tests/extension/test_extension.py::test_wcsapi_extension
4.11s call     lib.linux-x86_64-3.5/astropy/coordinates/tests/test_angles.py::test_repr_latex
3.32s call     lib.linux-x86_64-3.5/astropy/utils/tests/test_timer.py::test_timer
3.02s call     lib.linux-x86_64-3.5/astropy/vo/samp/tests/test_hub.py::test_SAMPHubServer_run_repeated
3.02s call     lib.linux-x86_64-3.5/astropy/vo/samp/tests/test_hub_script.py::test_hub_script
2.91s call     lib.linux-x86_64-3.5/astropy/io/ascii/tests/test_c_reader.py::test_many_columns[False]
2.66s call     lib.linux-x86_64-3.5/astropy/io/fits/tests/test_image.py::TestCompressedImage::test_open_scaled_in_update_mode_compressed
2.03s call     lib.linux-x86_64-3.5/astropy/io/fits/tests/test_image.py::TestImageFunctions::test_open_scaled_in_update_mode
1.89s call     lib.linux-x86_64-3.5/astropy/io/ascii/tests/test_c_reader.py::test_many_columns[True]
1.88s call     lib.linux-x86_64-3.5/astropy/table/tests/test_pprint.py::TestPprint::test_clip4[False]
1.86s call     lib.linux-x86_64-3.5/astropy/nddata/tests/test_nduncertainty.py::test_for_leak_with_uncertainty
1.78s call     lib.linux-x86_64-3.5/astropy/io/fits/tests/test_hdulist.py::TestHDUListFunctions::test_hdul_fromstring
1.74s call     lib.linux-x86_64-3.5/astropy/io/fits/tests/test_image.py::TestCompressedImage::test_lossless_gzip_compression
1.71s call     lib.linux-x86_64-3.5/astropy/io/ascii/tests/test_read.py::test_read_all_files[False]
1.67s call     lib.linux-x86_64-3.5/astropy/io/ascii/tests/test_read.py::test_read_all_files_via_table[True]
1.63s call     lib.linux-x86_64-3.5/astropy/table/tests/test_index.py::TestIndex::test_multiple_slices[subclass-main_col1-BST0]
1.63s call     lib.linux-x86_64-3.5/astropy/io/fits/tests/test_image.py::TestCompressedImage::test_rewriting_large_scaled_image_compressed
1.63s call     lib.linux-x86_64-3.5/astropy/table/tests/test_pprint.py::TestPprint::test_clip4[True]
1.60s call     lib.linux-x86_64-3.5/astropy/io/ascii/tests/test_read.py::test_read_all_files_via_table[force]
1.60s call     lib.linux-x86_64-3.5/astropy/io/ascii/tests/test_read.py::test_daophot_multiple_aperture2
1.54s call     lib.linux-x86_64-3.5/astropy/table/tests/test_index.py::TestIndex::test_multiple_slices[unmasked-main_col1-BST0]
1.53s call     lib.linux-x86_64-3.5/astropy/io/ascii/tests/test_read.py::test_guess_all_files
1.52s call     lib.linux-x86_64-3.5/astropy/table/tests/test_index.py::TestIndex::test_multiple_slices[unmasked-main_col1-BST1]
1.48s call     lib.linux-x86_64-3.5/astropy/io/ascii/tests/test_read.py::test_read_all_files[True]
1.48s call     lib.linux-x86_64-3.5/astropy/table/tests/test_index.py::TestIndex::test_multiple_slices[masked-main_col1-BST0]
1.45s call     lib.linux-x86_64-3.5/astropy/io/ascii/tests/test_read.py::test_read_all_files[force]
1.41s call     lib.linux-x86_64-3.5/astropy/io/ascii/tests/test_read.py::test_read_all_files_via_table[False]
1.38s call     lib.linux-x86_64-3.5/astropy/table/tests/test_index.py::TestIndex::test_multiple_slices[masked-main_col1-BST1]
1.35s call     lib.linux-x86_64-3.5/astropy/io/ascii/tests/test_c_reader.py::test_many_rows[False]
1.31s call     lib.linux-x86_64-3.5/astropy/coordinates/tests/test_skyoffset_transformations.py::test_skyoffset_functional_ra_dec
1.25s call     lib.linux-x86_64-3.5/astropy/table/tests/test_index.py::TestIndex::test_multiple_slices[subclass-main_col1-BST1]
1.23s call     docs/coordinates/frames.rst
1.10s call     lib.linux-x86_64-3.5/astropy/coordinates/tests/test_celestial_transformations.py::TestHelioBaryCentric::test_heliocentric
1.09s call     lib.linux-x86_64-3.5/astropy/tests/tests/test_socketblocker.py::test_multiprocessing_forkserver
1.05s call     lib.linux-x86_64-3.5/astropy/config/tests/test_configs.py::test_no_home
1.02s call     lib.linux-x86_64-3.5/astropy/io/fits/tests/test_image.py::TestCompressedImage::test_open_comp_image_in_update_mode
1.02s call     lib.linux-x86_64-3.5/astropy/io/fits/tests/test_groups.py::TestGroupsFunctions::test_open_groups_in_update_mode
1.01s call     lib.linux-x86_64-3.5/astropy/vo/samp/tests/test_hub.py::test_SAMPHubServer_run
0.96s call     lib.linux-x86_64-3.5/astropy/io/ascii/tests/test_c_reader.py::test_many_rows[True]
0.95s call     lib.linux-x86_64-3.5/astropy/utils/iers/tests/test_iers.py::TestBasic::test_simple
[33m=============================== warnings summary ===============================[0m
```

**Comment by pllim** [comment]
@saimn, is that timing before or after this PR?

**Comment by bsipocz** [comment]
It was before this PR.

**Pull request merged**
