### PR TITLE
Handle ruff error PLW0129.

### PR DESCRIPTION
**Pull request by draghuram**
### Description

This pull request is to address the  ruff error PLW0129.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by nstarman** [comment]
Definitely good to fix these tests!

**Review by nstarman — APPROVED** [review]
Everything passes and these are obvious test fixes. Let's get this in! Thanks @draghuram

**Comment by draghuram** [comment]
Thanks. Its great that ruff caught these issues.

**Comment by draghuram** [comment]
BTW, thanks for adding more detail to the commit message.

**Comment by pllim** [comment]
Good catch. For once, ruff actually fixes bugs. 😬

**Pull request merged**
