### PR TITLE
Fix setup.py test -t

### LINKED ISSUE #5798: python3 setup.py test -t <filename> does not work any more???
I tend to run tests using single filenames to speed up things, but somehow things like
```
python3 setup.py test -t astropy/coordinates/tests/test_arrays.py
```
now starts to run the full test suite.

Any ideas??

### PR DESCRIPTION
**Pull request by saimn**
Fix #5798

### CODE REVIEW

**Comment by bsipocz** [comment]
Sorry @pllim, I didn't mean to remove labels, but was adding them at the same time as you (apparently github cannot handle simultaneous edits :()

**Comment by pllim** [comment]
No problem. That's what I figured anyway when I saw it. Should we open a bug report to GitHub? :sweat_smile:

**Comment by bsipocz** [comment]
You can report it to them via e-mail, afaik they don't have a public issue tracker.

**Comment by mhvk** [comment]
All but OSX passed, so I'm merging.  Thanks again, @saimn!

**Comment by pllim** [comment]
But this does not add tests to the test system. Do we need a new issue for that?

**Comment by mhvk** [comment]
Yes!

**Comment by pllim** [comment]
@bsipocz , GitHub responded and I recorded it at isaacs/github#885

**Comment by bsipocz** [comment]
Oh, the usual response then ;)

**Pull request merged**
