### PR TITLE
Try to fix example plot not working with matplotlib 3.8

### LINKED ISSUE #15319: matplotlib 3.8.0 breaks a visualization example for the docs.
- [ ] Revert https://github.com/astropy/astropy/pull/15320

<hr/>

https://readthedocs.org/projects/astropy/builds/21934027/ as an example.

These are due to a failure in either:

- https://github.com/astropy/astropy/blob/881710f589d9557a03826a1730e1919097fdbae5/examples/coordinates/plot_obs-planning.py#L142-L144
- or https://github.com/astropy/astropy/blob/881710f589d9557a03826a1730e1919097fdbae5/examples/coordinates/plot_obs-planning.py#L149C1-L149C42

Having either of those lines enabled produces the same traceback as what is listed in the build log linked above.

This seams like a real failure, and is not being caught by the current test suite.

### PR DESCRIPTION
**Pull request by mhvk**
### Description

This pull request is to address the `plot_obs-planning` not working with matplotlib 3.8, because it passes a `Quantity` to the color entry in `plt.scatter` -- see #15319.

Obviously, if readthedocs does not work, this was not good enough!

Fixes #15319

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Thanks, @mhvk ! I pushed a commit to unpin matplotlib so your fix is actually using the latest stable matplotlib. Let's hope it works. I am glad the workaround is simple if it does work. 🤞

**Comment by pllim** [comment]
Tsk tsk... now there are other stuff that pops up. I do run these files through doctest with matplotlib dev. But I guess doctest does not run the code within matplotlib's plot directive, so these fell through the cracks.

```
astropy/modeling/functional_models.py:docstring of astropy.modeling.functional_models.Ellipse2D:91: WARNING: Exception occurred in plotting astropy-modeling-functional_models-Ellipse2D-1
 from docs/api/astropy.modeling.functional_models.Ellipse2D.rst:
Traceback (most recent call last):
  File "matplotlib/sphinxext/plot_directive.py", line 552, in _run_code
    exec(code, ns)
  File "<string>", line 14, in <module>
TypeError: Ellipse.__init__() takes 4 positional arguments but 5 were given
```
```
docs/nddata/index.rst:320: WARNING: Exception occurred in plotting index-3
 from docs/nddata/index.rst:
Traceback (most recent call last):
  File "matplotlib/sphinxext/plot_directive.py", line 552, in _run_code
    exec(code, ns)
  File "<string>", line 23, in <module>
  File "astropy/nddata/utils.py", line 726, in plot_on_original
    patch = mpatches.Rectangle(pos_xy, width, height, 0.0, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Rectangle.__init__() takes 4 positional arguments but 5 were given
```
```
docs/nddata/utils.rst:115: WARNING: Exception occurred in plotting utils-3
 from docs/nddata/utils.rst:
Traceback (most recent call last):
  File "matplotlib/sphinxext/plot_directive.py", line 552, in _run_code
    exec(code, ns)
  File "<string>", line 11, in <module>
  File "astropy/nddata/utils.py", line 726, in plot_on_original
    patch = mpatches.Rectangle(pos_xy, width, height, 0.0, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Rectangle.__init__() takes 4 positional arguments but 5 were given
```

These looks like maybe docstring inherited from `matplotlib` has references that cannot be resolved downstream. So the best bet is to not render those docstring at all or overwrite them?

```
astropy/visualization/wcsaxes/patches.py:docstring of astropy.visualization.wcsaxes.patches.Quadrangle:59: WARNING: py:obj reference target not found: N
astropy/visualization/wcsaxes/patches.py:docstring of astropy.visualization.wcsaxes.patches.SphericalCircle:56: WARNING: py:obj reference target not found: N
matplotlib/artist.py:docstring of matplotlib.artist.WCSAxes.set:7: WARNING: py:obj reference target not found: cycler.Cycler
matplotlib/artist.py:docstring of matplotlib.artist.WCSAxesSubplot.set:7: WARNING: py:obj reference target not found: cycler.Cycler
```

@ksunden , do you know if these changes are intentional upstream or not? 🙏

**Comment by pllim** [comment]
Timeout error in remote data job is unrelated.

**Review by pllim — APPROVED** [review]
I don't like `<` pins so I am going to merge. Thanks, everyone!

If you disagree with my patches, please open follow-up PR(s).

**Comment by pllim** [comment]
(Not going to squash because the commits are atomic to address different parts of compatibility issues.)

**Comment by pllim** [comment]
Meh... Not worth it to manually backport to v5.0.x. We can leave the `matplotlib<3.8` for doc build over there.

**Comment by mhvk** [comment]
@pllim - great that it helped, though it looks like you had to do quite a bit more work to *actually* get things to pass again. Thanks!!

**Comment by ksunden** [comment]
Sorry to belatedly (after you have already resolved them) answer your questions, but:

- The Rectangle changes are intended, they should have been giving a deprecation warning, as we made some additional arguments keyword-only.

- Cycler (and maybe N?) appear to be due to inheriting from our docstring

  - For cycler, adding that to intersphinx in `conf.py` should resolve it and provide a link:

https://github.com/matplotlib/matplotlib/blob/538bd83bf5c5a298d99c13639b7fa87ecd7fd83c/doc/conf.py#L199

- N appears to be in our specification of shapes of NDArrays, so I think ignoring it is probably fine, I don't recall having problems with that attempting to be resolved, but I do know that there are some cases where we have recently made our docstrings more consistent by switching from e.g. `2xN array` to `(2, N) array`, and I guess I can see how under some circumstances that could be parsed as types, just don't think we had to do anything special ourselves.

**Comment by pllim** [comment]
Thanks, @ksunden ! Hopefully https://github.com/astropy/astropy/pull/15341 will make it cleaner.

If Rectangle ever gave a deprecation warning, we must have missed it. We do turn RTD warning into exceptions but I had noticed in the past that not all warnings do that despite the settings. 🤷

**Pull request merged**
