### PR TITLE
Updating the UCD list to upstream version 1.5

### PR DESCRIPTION
**Pull request by msdemlei**
### Description

UCD 1.5 has been endorsed on Jan 25, 2023, but publication was a bit delayed;
cf. https://ivoa.net/documents/UCD1+/20230125/.  This PR updates
astropy's built-in UCD list to what comes with this standard.

The upstream UCD lists now contain hash-style comments, which we now
drop while parsing.

### CODE REVIEW

**Comment by pllim** [comment]
Can you please add a change log? Thanks!

**Comment by msdemlei** [comment]
On Mon, Mar 20, 2023 at 05:30:57AM -0700, P. L. Lim wrote:
> Can you please add a change log? Thanks!

Aw, forgot to add it into the commit.

But adding it I now have file name trouble.  This arguably is a
change within io.votable, so I put a file 14554.other.rst in there --
"other", since it's neither a bugfix, nor a feature, nor an api change.

Except you can only have "other" in the root of docs/changes.

So... do I move move change fragment to root -- or use one of the other
terms in the file name?

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/pull/14554#issuecomment-1476179406

For towncrier stuff, I'll have to defer to @saimn or @Cadair . I wonder if it is okay to just stuff it into "api" just to get it into `io.votable` section. 💭

**Comment by saimn** [comment]
Sounds like `feature`, adding the possibility to use UCD 1.5. If it potentially breaks existing code then `api`, otherwise `feature`. The choice was made to avoid `other` being used too broadly, so it's restricted to the top-level.

**Comment by pllim** [comment]
Re: new UCD -- I won't backport then. Would make any breaking changes less controversial. Is that alright?

**Review by pllim — APPROVED** [review]
The actual code change is only 2 lines and LGTM, so I'll approve, but I'll also not merge yet to give VO people a chance to review. Thanks!

**Review by pllim — COMMENTED** [review]
p.s. Is it possible to add a test for this new UCD 1.5 or is that not applicable here?

**Comment by msdemlei** [comment]
On Tue, Mar 21, 2023 at 07:03:48AM -0700, P. L. Lim wrote:
> @pllim commented on this pull request.
>
> p.s. Is it possible to add a test for this new UCD 1.5 or is that not applicable here?

We could of course test that one of the new UCDs is accepted (e.g.,
stat.skewness) -- but I doubt that is a useful thing to test for;
theoretically, we should get one of these UCD updates per year or so,
so these kinds of tests would accumulate until one fails because a
UCD has been deprecated again.

One *could* argue we should test that comments are actually ignored
when parsing.  But since the parser hasn't been separately exercised so
far either and the parsing will fail if comments are not ignored (so
I'd argue real test coverage is now as it has been before), I'd need
some *serious* encouragement to build proper unit tests for the UCD
parser (though I agree that in principle it would the the Right
Thing™).

**Comment by pllim** [comment]
Thanks, all!

**Pull request merged**
