### PR TITLE
WIP: Add changes to precision from mcalabre

### PR DESCRIPTION
**Pull request by mdboom**
These are the proposed changes from Mark Calabretta to output the maximum precision of floating point values when writing out a wcslib header.  This should give at least one more digit in some cases vs. wcslib 5.9 (current astropy master), and 0-4 more digits than prior to wcslib 5.9.  But hopefully this will fix this once and for all.

Cc: @nden  This should change regression test results by very small amounts yet again, but hopefully for the last time.

**This PR shouldn't be merged -- it's just a preview of wcslib 5.10 which I will make a proper PR for when it comes out.**

### CODE REVIEW

**Comment by embray** [comment]
:+1:

**Comment by nden** [comment]
:+1:  All differences in the regression tests are expected.

**Comment by mdboom** [comment]
Still no wcslib 5.10 release, though Mark Calabretta does report that this solution is sound and will go in the next release.  If this begins to hold up astropy 1.1, I think we should just merge this so we don't hit people with a precision change twice.

**Comment by astrofrog** [comment]
@mdboom @embray - shall we merge this since the 1.1 feature freeze is upon us?

**Comment by embray** [comment]
I don't understand the full background to this.

**Comment by mdboom** [comment]
Background: wcslib 5.9 increased the precision of the float-to-string conversions output to a FITS header.  However, it didn't quite extend it to the maximum available precision in a double.  This does that, and Mark Calabretta claims the same will end up in 5.10.  I'd like to avoid changing the precision in astropy twice, rather than once-and-for-all.  I was hoping that 5.10 would be out be now and we could just vendor a clean upstream wcslib 5.10.  However, it seems that's not the case.  I can send another reminder e-mail...  In the meantime it's just a policy question of whether we want to vendor a patched wcslib.

**Comment by astrofrog** [comment]
@mdboom - thanks for the clarification. Since we're short on time before the feature freeze for 1.1, I talked with @eteq and we decided to proceed with merging this. We think it's ok to vendor a patched WCSLIB like this since the patch is very minor and easily understandable, and it's very likely that it will make it in 5.10. I will merge within the hour if there are no objections.

**Pull request merged**
