### PR TITLE
Fix HDU detection in convenience methods (via _makehdu)

### LINKED ISSUE #8660: Primary HDU checksum data must be np.array?
I have some code which attempts to update the FITS checksums:

     output = "out.fits"
     with fits.open(self.filepath, do_not_scale_image_data=True) as hdus:
             for hdu in hdus:
                   fits.append(output, hdu.data, hdu.header, checksum=True)

For a file which has no data in an HDU (primary),  this code now raises an exception requiring that the data array be an np.array rather than None.

There's a relatively easy "work" around something like this:

         data = hdu.data if hdu.data is not None else np.array([])

but I wasn't positive it's correct.

Since it used to be possible to round trip these HDUs,  I thought I should raise it as an issue and possible bug.

I (think) this problem is exposed with:

astropy                   4.0.0.dev12788+g4166b6a94          py36_0    http://ssb.stsci.edu/conda-dev
numpy                     1.16.3           py36hacdab7b_0  
numpy-base                1.16.3           py36h6575580_0

### PR DESCRIPTION
**Pull request by saimn**
Fix #8660: In 6800eec (EDIT: xref #8502) I removed `_BaseHDU.__new__` because when reading from a FITS file this HDU detection was done twice. Instead of reverting this commit I'm adding a new classmethod which can be used to explicitly call the class detection, which allows to avoid the duplicated detection when reading from a file. 

@MSeifert04 - do you see any drawback with this approach ?

### CODE REVIEW

**Comment by pllim** [comment]
cc @mcara

**Comment by MSeifert04** [comment]
Puh, these are those kind of consequences that make `io.fits` so "interesting" 😕 

I don't have the time atm to do a proper in-depth review. However if it fixes the reported problem and the test suite doesn't complain it seems like a clear improvement.

**Comment by saimn** [comment]
I could also revert the change to `_BaseHDU.__new__`, but given that no test was failing because of this, I think it's a good point to avoid the double detection from the header, and introduce this classmethod for specific cases like this one. Hopefully not having the detection in `_BaseHDU.__new__` should not have other unintended consequences :crossed_fingers:

**Comment by pllim** [comment]
@jaytmiller , can you please confirm that works for you?

**Comment by pllim** [comment]
Well, that's weird. There is a `html-docs` error that I don't see on latest `master`. Maybe rebasing would help? 

```
/home/circleci/project/docs/whatsnew/3.2.rst:98:Inline literal start-string without end-string.
```

**Comment by bsipocz** [comment]
I believe that failure got fixed by #8669

**Comment by astrofrog** [comment]
@saimn - can you rebase? Thanks!

**Comment by saimn** [comment]
@astrofrog - Done.

**Comment by saimn** [comment]
Anyone to review/approve? :pray:

**Comment by jaytmiller** [comment]
Sorry,  I looked this over and was relatively convinced it should work based on the  regression test case.

**Comment by pllim** [comment]
Doc build is still failing after rebase and its log indicates that it went over the max 10 minutes limit.

```
...
reading sources... [ 95%] timeseries/times
reading sources... [ 95%] uncertainty/index
Too long with no output (exceeded 10m0s)
```

Does this PR somehow make the doc build too long? @astrofrog or @Cadair , how do we increase the limit on CircleCI?

**Comment by saimn** [comment]
This PR should not increase the build time, and the error looks similar to the ones with the recent mpl issue. I can try a new rebase to be sure?

**Comment by pllim** [comment]
> I can try a new rebase to be sure?

Feel free to try again. Thanks!

**Comment by saimn** [comment]
All builds pass! Merging since it was approved :)

**Pull request merged**
