### PR TITLE
Modify wcslib version 4.23 or later requirement

### PR DESCRIPTION
**Pull request by migueldvb**
Replace `wcslib version 4.23 or later` requirement by `wcslib version 4.23`.

### CODE REVIEW

**Comment by mdboom** [comment]
Since we don't have a 0.4.x milestone anymore -- just to notate that this *only* goes on the 0.4.x branch (which this PR should do).  Attn: @embray

**Comment by embray** [comment]
I'm not really sure what to do with this.  For it to be useful at all it would go into master too.  I don't really mind editing the changelog after the fact if it makes for more accurate/useful information.

**Comment by migueldvb** [comment]
I think that it does not hurt to include this into master because these lines appears under the 
0.4 (2014-07-16) heading.

**Comment by mdboom** [comment]
I see what you're saying -- that's fine then if it's included in master.  Obviously, however, it no longer applies.

**Pull request merged**
