### PR TITLE
Correct documented default boundary case for convolution.convolve

### PR DESCRIPTION
**Pull request by jamienoss**
Signed-off-by: James Noss <jnoss@stsci.edu>

### CODE REVIEW

**Comment by jamienoss** [comment]
@eteq

**Comment by bsipocz** [comment]
Thanks @jamienoss. 

Before merging, please remove the changelog, pure docs fixes don't need one.

**Comment by jamienoss** [comment]
> Before merging, please remove the changelog, pure docs fixes don't need one.

Under normal circumstance I would totally agree with you, however, a documentation change of a function's default behaviour isn't a normal circumstance. I strongly suggest that this change gets mentioned in the changelog, that it isn't silent, and exists somewhere else other than just the commit log.  This type of change exists in the grey area of API changes, actual vs that documented, and what exists as a user's perception of said function's API/behaviour. This is why I also didn't mark it as [docs only].

**Comment by bsipocz** [comment]
Still, no behaviour was changed just the docs has been fixed to reflect the actual behaviour. We haven't changeloged this kind of changes before, and don't think we need to in the future either.

**Comment by bsipocz** [comment]
Re CI: this change could never trip over the tests as doctests for the docstrings involve the examples only not the text. Given that no links, or any other tricky elements were involved either, even `[skip ci]` would have been totally reasonable.

**Comment by jamienoss** [comment]
@bsipocz 
>Still, no behaviour was changed just the docs has been fixed to reflect the actual behaviour.

Ok, I'll change it, but for the record, I think this is a very foolish idea - for this type of change to be silent. Especially since there is no "harm" in adding it.  Whilst no actual behaviour has changed, the perception of said behaviour has/will. In case I didn't make my point clear before - someone may have been relying on the default being `boundary=None` (that documented) yet they were actually and unknowingly using `boundary='fill'`, when they next check the documentation, they'll find that it's now `'fill'`, they'll think that the actual behaviour has changed and do one of two things, check the changlog or look at the source, when the look at the latter they'll see that the default behaviour _is now_ `'fill'`, so it has been changed because they were unaware that it was this before. There will then be no record of this in the changelog, which will lead to confusion. They'd have to seive through the commit log and or rollback the source diffs etc, they maynot know how to, they may not want to, thy may give up (depending on when in the future they find out), either which way a simple note in the change log would switfly clarify the situation.

> We haven't changeloged this kind of changes before, and don't think we need to in the future either.

This "rings a thousand alarm bells". It should _never_ be the argument to why we don't do something! It's a stale and therefore dangerous mindset to have, preventing growth, adaptation, and course correction.

**Comment by bsipocz** [comment]
Seriously relying on defaults rather than adding the desired options to a call rings bells for bad usage practice, especially when signature and parameter docstrings are in contradiction.

Anyway, I'm not willing to argue any more why 5 changelog lines for every line of doc fix is an exaggeration, pretty sure both of us have better things to do.

**Comment by pllim** [comment]
Why is this PR opened against `v3.0.x` branch? Please rebase against `master`. Also, please remove change log entry.

**Comment by astrofrog** [comment]
@jamienoss - I changed the base of the pull request to ``master``, so this definitely needs a rebase now :) (against master)

**Comment by jamienoss** [comment]
> Why is this PR opened against v3.0.x branch?

Sorry, @eteq asked me to open this against v3.0.x. He and I also discussed the semantic concerns of this being _more_ than just a doc typo.

> Anyway, I'm not willing to argue any more why 5 changelog lines for every line of doc fix is an exaggeration...

I'm totally with you, adding every doc fix to the changelog is crazy! Again though, I was only referring to this instance/PR, which semantically, _is more_ than just a doc fix - it has ramifications. Just food for thought, when something doesn't work as documented, it's normally called a bug.
 
>Seriously relying on defaults rather than adding the desired options to a call rings bells for bad usage practice, especially when signature and parameter docstrings are in contradiction.

$10 says the greater % don't inspect the sig but read and rely only on the docs. Besides, if they had (checked both), this would have been fixed already.

**Comment by eteq** [comment]
> Sorry, @eteq asked me to open this against v3.0.x. He and I also discussed the semantic concerns of this being more than just a doc typo.

Just to clarify here - I did indeed suggest that (in an out-of-band discussion with @jamienoss), but I had been thinking this would be done *after* #7293 which already includes this change (along with a lot of other things). If we just merged #7293 this doc fix wouldn't have gotten backported to v3.0.x (because #7293 has new features), so *this* PR was necessary to get just the doc change into the maintenance branch.  Seeing as how this PR is coming *before* #7293 (assuming the discussion resolves in time) it makes sense to go against master. Sorry I wasn't clear there.

**Comment by eteq** [comment]
> He and I also discussed the semantic concerns of this being more than just a doc typo.

Indeed - as I said there, though, I think this is a bit less of a concern than it might at first appear because the actual [generated docs](http://docs.astropy.org/en/v3.0/api/astropy.convolution.convolve.html#astropy.convolution.convolve) end up giving a conflicting message - the defaults from the signature are correct, but the docstring is in conflict.  If the docstring actually said something wrong like "all convolution kernels are set to a gaussian-tapered 🦄", then I'd agree it needs highlighting in the changelog that the behavior the user assumed is different. But given that this is more in the realm of "clarification" for something an user reading the docs already probably had to look into, I think it's six of one half dozen of the other.

**Pull request merged**
