### PR TITLE
Add FWHM to Gaussian and Moffat models

### LINKED ISSUE #5980: Attribute "FWHM"?
I have realized that `Fittable1DModel` and `Fittable2DModel` (including Gaussian and Moffat) has no attribute of `FWHM`, while quite many of them actually need it for astronomical purposes. 

A built-in function `astropy.stats.gaussian_sigma_to_fwhm` can be used only for Gaussian, while we need much more functions' FWHM values in practice.

I guess it will be very useful if we have something like attribute to calculate FWHM.

### PR DESCRIPTION
**Pull request by pllim**
Fix #5980 by adding FWHM properties to Gaussian and Moffat models (both 1D and 2D).

c/c @nden @ysBach @cdeil @MSeifert04

### CODE REVIEW

**Comment by cdeil** [comment]
Add one-line docstring to the properties?

I don't know Moffat. Someone should check the formula (or if someone knows a good reference there would be a comment pointing to a trusted paper or webpage that has this formula).

Otherwise, 👍  and thanks!

**Comment by pllim** [comment]
@cdeil , there are formulae at http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?psfmeasure (half way down the page) but I am hesitant to link to IRAF documentation...

**Comment by nden** [comment]
Looks good. Thanks.

**Comment by ysBach** [comment]
@cdeil @pllim 
I confirmed the formula (FWHM of Moffat) by myself while preparing for my TA session.

The full note containing the derivation and explanation is given in [this notebook](http://nbviewer.jupyter.org/github/ysbach/AO_2017/blob/master/04_Ground_Based_Concept.ipynb). Following is some important part of it:

-----

moffat

**Comment by pllim** [comment]
I included a ref to @ysBach 's notebook in the docstrings. Since @nden approved (kinda), I'll merge when tests pass.

**Pull request merged**
