### PR TITLE
Fix typo in whatsnew 1.3

### PR DESCRIPTION
**Pull request by mirca**

### CODE REVIEW

**Comment by larrybradley** [comment]
Thanks, @mirca!

**Comment by pllim** [comment]
Shouldn't this be backported to 1.3.0? Setting the milestone to 1.3.1 does not seem to make sense since it has its own section.

**Comment by larrybradley** [comment]
We can't "re-release" `1.3.0`.  `1.3.1` is the next release on that branch.

**Comment by pllim** [comment]
Okay. Thanks for the clarification.

**Pull request merged**
