### PR TITLE
Cosmology property `is_flat`

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

### Description

Add property ``is_flat`` to cosmologies to verify the curvature of the Universe.

It's abstract on `Cosmology`, making it abstract (finally).
On `FLRW` it checks ``Ok0`` and ``Otot0``.
On subclassess of `FlatCosmologyMixin` it's just `True`.

Flatness is a subtle thing. On FLRW cosmologies it's simple, but not in general. So it's abstract on `Cosmology`.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by nstarman** [comment]
I still need to add a what's-new and update some doc, but the code is ready to review.

**Review by mhvk — APPROVED** [review]
Looks good except I would perhaps suggest not to make it an abstract property; it just seems to add quite a bit of boilerplate, especially calling `super` just to get `NotImplementedError` back again. It also makes for a real API break - user-defined classes now have to change. (I've more generally found the concept of these abstract methods a bit less useful than I thought initially; I've not see a clear win with it.)

But really only a suggestion - if you think this is not a real problem, that's fine too.

**Comment by nstarman** [comment]
> it just seems to add quite a bit of boilerplate, especially calling `super` just to get `NotImplementedError` back again. It also makes for a real API break - user-defined classes now have to change.

It does add a bit of boilerplate, but crucially all that boilerplate is in the test code. I cannot find on GH any example of someone directly subclassing `Cosmology`, the base class. `FLRW` is actually the effective base class since all built-in cosmologies  are its subclasses; and `FLRW` is necessarily abstract because of `w(z)`. So we are in this awkward situation where the true base class was useless and not abstract and the useful 'base' class is abstract.
I modeled `is_flat` on `w(z)`, including its slightly odd "double" abstraction: erroring if the method isn't overwritten and raising `NotImplementedError` if called. I actually kind of like this construction. The `abstractmethod` indicates subclasses must define the method, the `NotImplementedError` means one cannot just `super` their way around that. The latter is how the tests are checking that Cosmology is correctly abstract.

> But really only a suggestion - if you think this is not a real problem, that's fine too.

I think I'll keep it as is. Thanks again for the detailed and quick review!

**Comment by nstarman** [comment]
Pushing a small grammar fix.

**Pull request merged**
