### PR TITLE
fitting compound models with units

### PR DESCRIPTION
**Pull request by nden**
This PR fixes issues #7314 and #6816 - issues related to fitting of compound models with units.

### CODE REVIEW

**Comment by perrygreenfield** [comment]
Before I go further with this, I'd like to see the justification for the requested behavior in the above issues. In  #6816 it is implied that simply based on input units that the corresponding parameters will have their units set to be the same as the input units even though the  model was defined without units for the parameters. Nadia tells me that there was discussions about this previously and that use cases were provided. I'd like to hear these written down. I find this behavior quite surprising (I doubt I am alone in this) and wonder if it is documented anywhere. There really should be a very strong use case to justify this, and even then, the behavior needs to be clearly documented.

**Comment by nden** [comment]
@nmearl @astrofrog  My recollection is that the use case was fitting of quantities with a default instance of a model. Can you give more details re @perrygreenfield's question?

**Comment by astrofrog** [comment]
@Cadair @nmearl - I know you both independently needed this, so can you provide @perrygreenfield with example use cases?

**Comment by nden** [comment]
@perrygreenfield What should we do with this one?

**Pull request merged**
