### PR TITLE
Fix #3754: Remove cache if loading it fails

### LINKED ISSUE #3754: Error with get_pkg_data_filename in clean Python 2.7 environment
I created a clean conda environment with Python 2.7 and Astropy 1.0.2 and the following code:

``` python
from astropy.utils.data import get_pkg_data_filename    
get_pkg_data_filename('galactic_center/gc_bolocam_gps.fits')
```

gives the following error:

```
  File "test.py", line 2, in <module>
    get_pkg_data_filename('galactic_center/gc_bolocam_gps.fits')
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/site-packages/astropy/utils/data.py", line 548, in get_pkg_data_filename
    timeout=remote_timeout)
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/site-packages/astropy/utils/data.py", line 948, in download_file
    with _open_shelve(urlmapfn, True) as url2hash:
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/site-packages/astropy/utils/data.py", line 1214, in _open_shelve
    shelf = shelve.open(shelffn, protocol=2)
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/shelve.py", line 239, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/shelve.py", line 223, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb
```

@eteq @embray @mdboom - any ideas?

### PR DESCRIPTION
**Pull request by mdboom**
Edit: Fix #3754

### CODE REVIEW

**Comment by embray** [comment]
I'm not sure if this is really what we want is it?  Since in @astrofrog's case it was just a matter of getting the bsddb module installed, I think silently clearing the cache is a waste.  I'd rather raise a warning, and also go ahead and make bsddb a requirement as discussed in #3754?

**Comment by embray** [comment]
On second thought, maybe the IOError case would be fine, but maybe not the ImportError case.  And still a warning might be nice just so it doesn't happen silently.

**Comment by mdboom** [comment]
Sure, we could resolve this by making `bsddb` an explicit requirement.  But I still don't like the idea of a broken or unreadable cache bringing things down.  The system should be able to recover and move on (though I'm not opposed to a warning).
 
But just to explain -- here's why the `ImportError` matters.

1) User runs astropy in a Python with bsddb, doing something that creates a cache entry
2) User runs astropy in a Python without bsddb.  `anydbm` tries to open the file, sees it's `bsddb` format, and then tries to import `bsddb` and throws an ImportError.

So here, the `ImportError` really means "I can't load this file" (but I could handle the functionality with some other db format handler that *is* installed).

**Comment by embray** [comment]
Okay, but I still foresee complaints with just silently deleting the downloads cache.  Maybe this situation isn't all that common, but clearly it can happen.  Maybe instead of remove it, we rename it with ".old" and display a warning?

**Comment by mdboom** [comment]
I think in the case of an `ImportError` silently deleting it is fine -- that's a real corner case that requires moving between Python versions that have different dbm backends installed.

I think I'm in favor of just letting random `IOError`s bubble out, so I've removed it from the list of accepted exceptions.

**Comment by embray** [comment]
Sorry, totally forgot about this.  Okay--it's a pretty rare corner case, agreed.  But maybe less rare than you'd think, especially considering the number of people I come across who have multiple Python distributions installed and don't know which one they're using half the time.  That's a PEBKAC to be sure, but I think silently deleting potentially large databases of downloaded files is user-hostile IMO.  

There's also the possibility of users trying to switch to Python 3 switching between two Python installs where for whatever reason one of them doesn't have bsddb.

**Comment by embray** [comment]
I'll have a patch in a sec.

**Comment by astrofrog** [comment]
What about having two cache directories, one for bsddb and one without? Using .old doesn't seem user-friendly since they'd have to go in and move things around. But if we simply have two caches, that problem is avoided and it also supports the case where people switch between 2 and 3 and one doesn't have bsddb.

**Comment by embray** [comment]
That might be a bigger change, though I'm not opposed to it.  For now, the patch I'm working at least tells the user where the backup is, and in the odd chance that someone encounters this they can come asking on the mailing list what to do about it (if they care at all).

**Comment by embray** [comment]
I also found in testing this that on Python 3 anyways, I don't get an `ImportError`.  Instead I get a `dbm.error` =_=

**Comment by embray** [comment]
Added a PR in mdboom/astropy#24

**Comment by embray** [comment]
@mdboom Have you had a chance to look at my PR to your PR? :)

I'd like to decide what to do with this issue soon so we can move forward on releasing v1.0.4.

**Comment by embray** [comment]
Ping?

**Comment by mdboom** [comment]
Sorry, missed your PR the first time around.  Doesn't that mean that is you switch between Python versions frequently that it will just start creating a whole bunch of backups of the cache?  I think the only way to really address this is to not use a file format that is Python-version-specific...

**Comment by embray** [comment]
> I think the only way to really address this is to not use a file format that is Python-version-specific...

That much I agree with.

As for "what if you switch between Python versions frequently" I don't think there's a great workaround for that.  I think it's still better to make a backup than to quietly just blow away what could (in principle) a large amount of data.

What if we go ahead and make the filenames for the cache include the DB library that was used to write it?  That would minimize the likelihood for conflict.

**Comment by mdboom** [comment]
Sure -- that makes sense.  Do you want to update you PR and I promise to merge it in a reasonable timeframe this time?

**Comment by embray** [comment]
I'm gonna see what I can come up with.  I may end up just pushing this off for the next release--it's a pretty obscure case albeit an annoying one.

**Comment by embray** [comment]
Also, do you know if all Python installations come with sqlite these days?  That would probably be my choice for the DB but I don't know if that's any more reliably available.

**Comment by mdboom** [comment]
I agree sqlite seems like a good choice.  It's been in the stdlib since Python 2.5, but it's possible some distros distribute it separately.  (It seems that Debian, Fedora and Anaconda all include it in the stock Python package -- or a required dependency thereof).  But I'm fine with saying -- "no sqlite, no cache for you!"

**Comment by embray** [comment]
I think I'm fine with that too.

**Comment by astrofrog** [comment]
+1 from me too

**Comment by embray** [comment]
I don't think I'm going to quite be able to get this done today.  In the interest of getting a release out I'm going to move this off.

**Comment by bsipocz** [comment]
I'm milestoning this again, and aim to pick up and finish for the next bugfix as it seems to be almost ready.

**Comment by pllim** [comment]
This attempted to fix something specific to Python 2, which we no longer support. So, closing.

**Comment by bsipocz** [comment]
Changing the DB and adding some checks are still relevant for python3, but I agree that we needed to close this PR.

**Comment by pllim** [comment]
@bsipocz , okay, I opened #6620 so someone else can pick this up again.

**Pull request closed without merging**
