### PR TITLE
Update v5.1 What's New page

### PR DESCRIPTION
**Pull request by eerovaher**
### Description

I noticed a formatting mistake at https://github.com/astropy/astropy/blob/216ce389b706b9795b7c3168391843ce7ee426d2/docs/whatsnew/5.1.rst#L149
I am fixing that with this pull request, but I am also adding more hyperlinks and making other improvements to formatting. I have not changed the phrasing of the text, with one very small exception.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by pllim — CHANGES_REQUESTED** [review]
Actually... should this be opened against `main` and then backported?

**Comment by pllim** [comment]
@eerovaher , can you please rebase against v5.1.x to pick up #13216 so we can see green RTD here? Thanks!

**Comment by eerovaher** [comment]
I have rebased.
The current 5.1 What's New page: https://astropy--13216.org.readthedocs.build/en/13216/whatsnew/5.1.html
The page in this pull request: https://astropy--13210.org.readthedocs.build/en/13210/whatsnew/5.1.html

**Review by saimn — APPROVED** [review]
Thanks @eerovaher.

**Pull request merged**
