### PR TITLE
Ensure we support the new matmul ufunc in numpy 1.16.

### PR DESCRIPTION
**Pull request by mhvk**
A few less overrides in `Quantity` and ensuring `numpy-dev` passes.

### CODE REVIEW

**Comment by bsipocz** [comment]
can/should this be LTS backported or not necessary to be np 1.16 compatible?

**Comment by mhvk** [comment]
Tests will fail on LTS with numpy 1.16, so, yes, this should be backported. Since this was changed quite a bit, it cannot be done cleanly, but not too difficult to make a new PR for it.

**Comment by pllim** [comment]
The numpy-dev job got stuck. I restarted it. 🤞

**Comment by pllim** [comment]
Still failed. Not sure what is going on: https://travis-ci.org/astropy/astropy/jobs/466696777

**Comment by mhvk** [comment]
Odd. Looking more closely, I see the same travis numpy-dev failure in my negative power PR from yesterday: https://travis-ci.org/astropy/astropy/jobs/466677129. @bsipocz, @astrofrog - any ideas?

**Comment by bsipocz** [comment]
It maybe mpl related rather than numpy? This jobs tests against the dev version of both (we live dangerously, I know...). I suppose @pllim had the good point in another PR to add `pytest-faulthandler` for the testing, it would be super useful to have at least for this job.

**Comment by pllim** [comment]
So the conclusion from #8270 is that the segfault did come from matplotlib dev. However, even getting rid of that, there are failures from `skimage` as well. But we agreed that this PR is good to go despite those unrelated failures (except that change log conflict).

**Comment by pllim** [comment]
@mhvk , please resolve conflict. Otherwise, I think this is good to go.

**Comment by mhvk** [comment]
OK, done!

**Comment by pllim** [comment]
Thanks! Not sure why CI was cancelled, I restarted it. I am tentatively approving this but whoever going to push that merge button please check the numpy dev job first.

**Comment by pllim** [comment]
> not too difficult to make a new PR for it.

@mhvk , any chance you can also make a PR straight to 2.x branch for LTS? :pray:

**Comment by mhvk** [comment]
Travis is timing out. Since it is in `iau_full_stack`, perhaps because of #8304 (IERS server down?).

**Comment by mhvk** [comment]
See #8305 for the v2 backport.

**Comment by mhvk** [comment]
Rebased. Hopefully tests will now run!

**Comment by pllim** [comment]
Let's just merge this since Numpy 1.16 prerelease is out and is causing "not allowed to fail" job to fail. Running the test one more time was  just a formality anyway.

**Comment by mhvk** [comment]
Yes, let's be sure the numpy-rc doesn't break! Thanks, @pllim, for staying on top of this.

**Pull request merged**
