### PR TITLE
Added doc on prefix under Units

### PR DESCRIPTION
**Pull request by ritwickdsouza**
References #5511

### CODE REVIEW

**Comment by pllim** [comment]
Note: There is an alternate PR submitted by someone else as #5647

**Comment by ritwickdsouza** [comment]
No problem, merge the one which you feel is the best. One more thing, why did the Travis test fail ?

**Comment by pllim** [comment]
URL timeouts and Numpy-dev failures are probably unrelated **but** you do need to fix these:
```
/home/travis/build/astropy/astropy/docs/units/standard_units.rst:62: WARNING: Block quote ends without a blank line; unexpected unindent.

/home/travis/build/astropy/astropy/docs/units/standard_units.rst:63: WARNING: Line block ends without a blank line.

/home/travis/build/astropy/astropy/docs/units/standard_units.rst:86: WARNING: Block quote ends without a blank line; unexpected unindent.

/home/travis/build/astropy/astropy/docs/units/standard_units.rst:87: WARNING: Line block ends without a blank line.

/home/travis/build/astropy/astropy/docs/units/standard_units.rst:63: ERROR: Undefined substitution referenced: ":------:".

/home/travis/build/astropy/astropy/docs/units/standard_units.rst:63: ERROR: Undefined substitution referenced: ":-----:".

/home/travis/build/astropy/astropy/docs/units/standard_units.rst:87: ERROR: Undefined substitution referenced: ":------:".

/home/travis/build/astropy/astropy/docs/units/standard_units.rst:87: ERROR: Undefined substitution referenced: ":-------:".
```

**Comment by pllim** [comment]
Thanks. Travis failures seem unrelated now.

**Comment by ritwickdsouza** [comment]
Please see #5654

**Pull request closed without merging**
