### PR TITLE
RTD: Temporarily allow warnings

### PR DESCRIPTION
**Pull request by pllim**
### Description

I think this will let RTD continue to build until upstream issue resolves itself. This temporarily works around https://github.com/astropy/astropy/issues/15428

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by saimn** [comment]
I think we could use https://docs.python.org/3.11/ for the instersphinx URL instead ?

**Comment by pllim** [comment]
@saimn , you mean patch `sphinx-astropy` or just here?

**Comment by pllim** [comment]
I have to step away now but feel free to open an alternate PR with your solution and close this one without merge. Thanks!

**Comment by pllim** [comment]
Superseded by https://github.com/astropy/astropy/pull/15433

**Pull request closed without merging**
