### PR TITLE
Ruff pyi056

### PR DESCRIPTION
**Pull request by nstarman**
Followup to https://github.com/astropy/astropy/pull/15276. 

Plz Squash and Merge.

### CODE REVIEW

**Comment by nstarman** [comment]
pre-commit autofix

**Comment by nstarman** [comment]
pre-commit.ci autofix

**Review by mhvk — APPROVED** [review]
Certainly happy with this (though improvement is only marginal in this case...).

Does something need to get moved to state that this rule is now followed?

**Comment by pllim** [comment]
> Does something need to get moved to state that this rule is now followed?

What does this mean? Is this something to be addressed in this PR?

**Comment by mhvk** [comment]
I thought in most of these cases, a rule was moved from "ignored" to "supported" in some way. @nstarman - is this a new rule?

**Comment by mhvk** [comment]
OK, thanks! Let's get it in, then.

**Pull request merged**
