### PR TITLE
TST: Replace/remove single quotes in travis.yml

### PR DESCRIPTION
**Pull request by pllim**
Co-authored-by: @eslavich 

### Description

This pull request is to address mysterious failure on Travis CI...

```
ERROR: file or package not found: '-v' (missing __init__.py?)

ERROR: InvocationError for command .../astropy/.tox/py36-test-alldeps/bin/pytest --pyargs astropy /home/travis/build/astropy/astropy/docs ''"'"'-v'"'"'' --durations=50 (exited with code 4)
```

and similar looking failures.

### CODE REVIEW

**Comment by eslavich** [comment]
It looks like double quotes are also misbehaving:

image

Travis must be wrapping all environment variables in double quotes automatically now?  If that's the case, our best option might be to drop all quotes from environment variables in the config.

**Comment by pllim** [comment]
> drop all quotes

But how do you drop empty quotes?

**Comment by eslavich** [comment]
I tried the following over on asdf:

```
env:
    global:
        - TESTENV=
```

and weirdly, it worked:

image

**Comment by pllim** [comment]
I think this patch works as is. You can ignore the `mpldev` failures.

**Comment by pllim** [comment]
Actually... Other PRs that were failing are now passing again without this patch. Maybe it was a Travis CI bug after all. I'll close this once the other PRs are shown as definitely passing again.

**Comment by bsipocz** [comment]
Yeah, let's close this one for now, we can always revisit if it comes up again.

**Pull request closed without merging**
