### PR TITLE
Add Planck 2018 cosmology.

### LINKED ISSUE #8006: Add the Planck18 (full mission) cosmological parameters
It looks like no one got around to adding the 2018 Planck mission final results to `cosmology`.  So those should probably be added!

(Ideally for 3.1, although that would require CoCo approval since it's post feature-freeze)

### PR DESCRIPTION
**Pull request by aconley**
Note: unlike Planck 2015, they included massive neutrinos in the
quoted Om0.  So the value used looks slightly different than that
in the paper, even though it is really the same thing.  Noticed
because the ages didn't match the ones in the paper without
subtracting it out.

Fix #8006

### CODE REVIEW

**Comment by bsipocz** [comment]
@aconley - Thanks. Could you please add a changelog entry, as well as fix the pep8 issue?

**Comment by aconley** [comment]
@bsipocz -- done.  I think...  I'm not sure where to look for the PEP8 error, but pycodestyle doesn't complain about anything currently.

**Comment by aconley** [comment]
Yeah, I'm okay waiting for now.  At some point it will get awkward, since Planck 18 probably already has a few hundred citations, but we can revisit that later.

**Comment by pllim** [comment]
I'll add a "keep open" label since we have to update this at some point.

**Comment by bsipocz** [comment]
The paper hasn't yet been accepted, has it?

**Comment by aconley** [comment]
No!  Makes you wonder what is going on, doesn't it?
It was submitted 14 months ago.

**Comment by aconley** [comment]
An updated version was posted on Sep 20th.  Still not accepted, but
at least something seems to be happening.

>

**Comment by bsipocz** [comment]
I would say we should give this a blank card, and merge in to 4.0 even if the paper acceptance came in after feature freezing 4.0.

@eteq @astrofrog, how do you feel?

**Comment by pllim** [comment]
Conflicts need resolving if you want this in by tomorrow. Or this can wait 6 more months.

**Comment by bsipocz** [comment]
I think we're more relaxed with this and have it, I'm inclined to keep it in the milestone and have it merged if the acceptance is happening before RC2.

**Comment by astrofrog** [comment]
I agree that we can merge this post feature freeze if accepted before the final release, since it is a special case. In the mean time, what are we going to call the cosmology if it's accepted soon - is the date in the class name the date of submission, acceptance, or publication? (the latter could be 2020!)

**Comment by bsipocz** [comment]
I'm not a cosmologist, but I think we should stick with 2018 as that's in the title of the paper, and it was the same with the previous versions, too (e.g. 2015 seems to be published in 2016 Oct, etc.)

**Comment by aconley** [comment]
It is referred to as Planck 2018 in common usage -- and by ESA.

The bigger problem is what if it changes before acceptance?
So perhaps we would need something like Planck2018v1,
reserving the Planck2018 for the accepted version.

The current version (v2) includes some new external datasets,
so the cosmology may have changed slightly.

**Comment by bsipocz** [comment]
@aconley - please rebase rather than merge master in

**Comment by aconley** [comment]
Sigh, it's hard to remember how to do this stuff now that I don't use Git
any more for anything.

Any advice how to undo that?

**Comment by bsipocz** [comment]
Don't worry then, I'm happy to do it here.

assuming you have the main repo added remote with the name  'astropy', and your fork as 'aconley'
```
git checkout planck18
git fetch astropy
git rebase astropy/master
git push aconley planck18 --force
```

http://docs.astropy.org/en/latest/development/workflow/development_workflow.html#how-to-rebase

**Comment by bsipocz** [comment]
(bottom line is that the buttons on the github web interface are useless for our workflow, but there is no way to disable them)

**Comment by aconley** [comment]
Well, that went massively, massively wrong somehow.  I now have 1600 files
changed.

**Comment by aconley** [comment]
A little more forced re-writing of history appears to have worked.

Note: I renamed the object to reflect it's preliminary status (Planck2018_arXiv_v2).

**Comment by pllim** [comment]
Thanks, everyone!

**Pull request merged**
