### PR TITLE
DOC: Replace broken RTD links for docs archive

### LINKED ISSUE #10918: DOC: RTD v1.0 missing
### Description

Linkcheck cron job reported a broken link, which I can confirm locally. Turns out RTD build for v1.0 is missing. Why is it missing? Is it intentional?

Example: https://travis-ci.com/github/astropy/astropy/jobs/403619988

```
.../docs/changelog.rst.rst:8078:broken link:
https://docs.astropy.org/en/v1.0/coordinates/index.html#migrating-from-pre-v0-4-coordinates
(404 Client Error: Not Found for url: https://docs.astropy.org/en/older-docs-archive/v1.0/coordinates/index.html)
```

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to replace broken RTD links that linked to very old doc ~with GitHub ones~. ~The info is still there, just not as nicely rendered.~ I don't see this being worthy of backport, but feel free to remilestone if you feel otherwise.

Fixes #10918 

@eteq , this is what we can do if you are unable to get RTD to rebuild for the very old docs. Turns out, not just v1.0 but v0.3 too.

### CODE REVIEW

**Comment by bsipocz** [comment]
Why not use the rendered versions in the docs archive? This is exactly the reason it was kept, rather that removed altogether:

https://docs.astropy.org/en/docs-archive/

**Comment by bsipocz** [comment]
(it's weird why the links stopped working now, when all these were created and cleaned up about 2 years ago)

**Comment by pllim** [comment]
Ah, I vaguely remember some talks about archive but I didn't know where it is. Thanks!

**Comment by bsipocz** [comment]
Yes, looking at the issue it's all down to the rename of `older-docs-archive` to `docs-archive`. I don't know and see when and why, but pretty sure everything is still up there, so it's only the links that need to be changed.

**Comment by pllim** [comment]
Didn't @astrofrog set up a redirect too? I wonder if it is the redirect that is broken.

**Comment by astrofrog** [comment]
The redirects are set up via the RTD interface, I don't have time to check today but if anyone has issues finding it I can try and look in the next few days

**Comment by pllim** [comment]
I found the setting but unfortunately there is no option to edit, only add or remove. I am hoping you have a programmatic way to do this. Looks painful to have to redo the redirects one by one.

**Comment by astrofrog** [comment]
@pllim - yeah I seem to remember no way to edit, I had to do it all by hand!

**Comment by pllim** [comment]
@astrofrog , are you saying that if we fix the redirect, we do not need this PR?

**Comment by astrofrog** [comment]
Probably - I don't think we should merge this PR as-is as those links *should* work (since otherwise it may impact others)

**Comment by astrofrog** [comment]
Anyone know why older-docs-archive was renamed to docs-archive in the first place? Can't we just change the name back?

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/pull/10922#issuecomment-715442229

No idea. I don't remember anyone announcing that it is renamed. Who has the authority to rename it? Maybe ask those people?

**Comment by astrofrog** [comment]
I don't even understand where it is renamed, the branch is still called older-docs-archive: https://github.com/astropy/astropy/tree/older-docs-archive

**Comment by astrofrog** [comment]
I'm re-enabling the older-docs-archive branch on RTD, let's see if it builds: https://readthedocs.org/dashboard/astropy/version/older-docs-archive/ - I don't understand where docs-archive comes from though!

**Comment by pllim** [comment]
RTD build failed: https://readthedocs.org/projects/astropy/builds/12173201/

**Comment by astrofrog** [comment]
Working on it :)

**Comment by astrofrog** [comment]
Ok links like https://docs.astropy.org/en/v1.0/coordinates/index.html#migrating-from-pre-v0-4-coordinates are working again so feel free to close if it works for you too @pllim!

**Comment by pllim** [comment]
Yup. Thanks!

**Pull request closed without merging**
