### PR TITLE
Fix img.scale for scaled integer data (fixes #4600)

### LINKED ISSUE #4600: Exception for FITS extensions where BZERO cannot be implicitly cast to same type as data
Calling `img.scale(bzero=bzero)`, where `img` is an _ImageBaseHDU object fails with a TypeError when `bzero` is non-zero and has a 'higher' type than `img.data`. The [offending line](https://github.com/astropy/astropy/blob/master/astropy/io/fits/hdu/image.py#L442) attempts to add a float to an integer array in-place.  A pull request will be issued and associated with this issue shortly.

The similar code in _ImageBaseHDU._get_scaled_image_data does not suffer from this problem, as the data is cast up to float before applying the scaling.

The FITS standard says that BZERO [should be a float](http://heasarc.gsfc.nasa.gov/docs/fcg/standard_dict.html), so it is not appropriate to change its type to match the data during verification. 

This issue was encountered with in astropy-1.1.1 on Python-2.7.11, when attempting to run `solve_field` from [astrometry.net](https://github.com/dstndstn/astrometry.net)-0.63 by @dstndstn.  The problem is [still present](https://github.com/dstndstn/astrometry.net/blob/master/util/fits2fits.py#L86) in the astrometry.net master branch  It prevents `solve_field` from working on images with integer data and non-zero BZERO.

### PR DESCRIPTION
**Pull request by bamford**
See issue #4600 for an explanation.

### CODE REVIEW

**Comment by MSeifert04** [comment]
In #4565 I also noticed that there is a problem with the ``scale`` method when increasing the ``dtype``. I'm very interested to see if your fix passes the tests.

**Comment by bamford** [comment]
OK, so this breaks the uint test.  I'll try to look at alternative ways to do this while preserving the correct wrapping of uints.  Suggestions welcome!

**Comment by bamford** [comment]
I've had a go at solving this a few different ways, and have found an approach that addresses the issue I encountered while passing the existing tests.

All this pull request does is fix a case that would have previously resulted in an exception: integer data, but a non-zero float BZERO.  It avoids the exception by rounding and casting BZERO to an integer before subtracting it from the data in-place (which is the behaviour implied by the fact that an in-place operation was used in the first place).

I've squashed the commits for neatness, and I think it is ready for merging.

**Comment by marcopigg** [comment]
The `compressed.py` file raises similar issues, when one tries to open an `fpack`ed file (see #4588). The offending line is [here](https://github.com/astropy/astropy/blob/master/astropy/io/fits/hdu/compressed.py#L1407). I think the two issues should be addressed in the same way, i.e.
```
-                data = data + self._bzero
+                if issubclass(new_dtype.type, np.floating):
+                    data += self._bzero
+                else:
+                    data += int(round(self._bzero))
```

**Comment by bamford** [comment]
Yes, it looks like the same issue.  Would you like me to add the same fix to `compressed.py` to this PR?

**Comment by marcopigg** [comment]
Well, since it is essentially the same issue, I'd put them in the same PR, if it is ok for you.

**Comment by mhvk** [comment]
@embray - could you have a look at these? I wonder a bit about keeping data integer when a scale and/or offset are given. I thought the point of this in fits is that one stores the data with a bit better compression, but then when restored, the scale and offset allow one to be out of, e.g., the `uint16` range. If so, this suggests that if any offset/scale is applied, one should just go to `float32`.

**Comment by bamford** [comment]
@mhvk I originally has the same thought and took that approach, but it breaks lots of tests (`checksum` and `uint`).  So I changed tactics and implemented a fix that still satisfies all the existing tests.

I've implemented the same fix in `compressed.py` and I'm just testing it.

**Comment by marcopigg** [comment]
@mhvk this is also what [here](http://docs.astropy.org/en/stable/io/fits/appendix/faq.html#why-is-an-image-containing-integer-data-being-converted-unexpectedly-to-floats) is said should happen when one opens a file with scale and offset.
However, `hdu.data` does not work that way: for uncompressed images with `BITPIX=16`, `BSCALE=1.0` and `BZERO=32768.0`, it returns a `np.uint16` array. For compressed images, it  returns the an array of the same type of the original uncompressed image (i.e. not necessarily a float array).

**Comment by bamford** [comment]
The FITS standard appears to say that BZERO [should be a float](http://heasarc.gsfc.nasa.gov/docs/fcg/standard_dict.html). So taking the approach of upcasting the data to match the type of BZERO should _always_ produce floating point data when BZERO is present in the header (and non-zero?).  However, one of the most common uses of BZERO is to efficiently store unsigned-integer data.  It would therefore seem appropriate to retain the type of the original data when applying BZERO.

**Comment by mhvk** [comment]
@marcopigg - I guess my question was the more general one of whether the current behaviour is correct. Certainly, for the specific case of scale=1, zero=32768, it seems correct to use `uint`, but it is not obvious that the decompression should stick to the BITPIX type if scaling and offsetting is involved. Rather, it would seem one should decompress and then apply whatever the normal logic is (would help deduplicate code too...).  But I should add I never looked in enough detail at the fits code; really, I'm just worrying that this PR papers over what in some situations is a real bug.  For instance, if `BSCALE=0.1`, `BZERO=10.5`, it will now round things to integers, which seems wrong.

**Comment by mhvk** [comment]
@bamford - I guess the easy solution to that is to check whether `int(BZERO)==BZERO`. But we should be sure to do that also for normal, not-compressed HDUs.

I do remain very confused about the current behaviour, at least for the case the BZERO=32768 and BITPIX=16: any in-place addition of 32768 to an `int16` or `uint16` array would lead to overflows for half the values.

**Comment by bamford** [comment]
@mhvk Actually, if you do the addition in-place numpy wraps around (see below), which surprised me too!  I decided that that this was the reason it was done in-place at all.  Note that when BSCALE is applied the data type changes.  So, in your example with `BSCALE=0.1, BZERO=10.5`, I think the resulting array _would_ be float!

```
In [1]: a = np.zeros(3, np.int16)
In [2]: a
Out[2]: array([0, 0, 0], dtype=int16)
In [3]: a += 32768
In [4]: a
Out[4]: array([-32768, -32768, -32768], dtype=int16)
```

**Comment by mhvk** [comment]
Actually, the multiply with a float would give a type error, so I guess nobody has yet dealt with `BSCALE!=1`...
```
In [3]: np.multiply(a, 1., a)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-40b47aaa3564> in <module>()
----> 1 np.multiply(a, 0.1, a)

TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int16') with casting rule 'same_kind'
```

**Comment by marcopigg** [comment]
@mhvk I see your point. It's getting a bit beyond my understanding, but I think this should be fixed somehow, becaused compressed data is not uncommon.
I was also just noting that what it says in the `io.fits` FAQ does not correspond to the actual behaviour of `hdu.data`.

**Comment by bamford** [comment]
But in `image.py` BSCALE is applied [like this](https://github.com/astropy/astropy/blob/master/astropy/io/fits/hdu/image.py#L451)
```
self.data = self.data / _scale
```
So, a new float array is created and self.data changed to point to it.

**Comment by bamford** [comment]
@mhvk Actually, looking at the code some more, I think that when either `BSCALE != 1` or `unit == False`, then self.data is a float array, so this issue doesn't arise.  I haven't worked through it all thoroughly, but it only seems to occur when `unit == True`, which is the default, and `BSCALE == 1`, but `BZERO` is a float (as it technically should be, but probably often isn't).  So my feeling is that this PR is OK.

**Comment by mhvk** [comment]
@bamford - I agree it is probably OK (this is partially why we have many test cases...). I do wonder if it wouldn't be clearer to just make `BZERO` an int whenever that is possible instead of meddling with the in-place addition, i.e.,
```
bzero = int(self._zero) if int(self._zero) == self._zero else self._zero
```
That way the in-place addition will fail if data are integer and bzero is not.

**Comment by bamford** [comment]
As noted in #4639, it seems that for numpy < 1.10 the in-place addition was dropping precision, and just issuing a DepreciationWarning! So, actually this PR preserves the same behaviour for numpy >= 1.10.

**Comment by anntzer** [comment]
Note that neither this patch nor #4639 handles the case of unsigned integer data with a nonzero BZERO: there will be a "same_kind" cast failure from int to uint.
Switching the line to `self.data -= _zero` solves the issue, but it seems that it was written in this way for to fix another issue?

**Comment by bamford** [comment]
@anntzer I'm a bit surprised by this.  Could you create a test that illustrates the problem?  It should be easy to adapt one of the new tests in this PR.  Then I can try to address that case too.

**Comment by anntzer** [comment]
A minimal failing example is
```
from astropy.io import fits
import numpy as np

fits.PrimaryHDU(np.zeros(100, dtype=np.uint16)).writeto("test.fits")
with fits.open("test.fits", mode="update", scale_back=True) as (hdu,):
    hdu.data[:] = 0
```

**Comment by bamford** [comment]
I've added the [test suggested](https://github.com/astropy/astropy/pull/4602#issuecomment-208713748) by @anntzer and addressed this issue in a simple way (again, as suggested by @anntzer), which doesn't break any existing tests.

I've done the same in PR #4639, which I think is the preferred option.

**Comment by mwcraig** [comment]
Closing in favor of #5527.

**Pull request closed without merging**
