### PR TITLE
RFC: auto-fixes from ruff 0.6 (io.ascii)

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
Partially address #16863 for `io.ascii`

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Looks good. But noted that it is actually slower -- will comment about that in the main issue.

**Comment by taldcroft** [comment]
My 2c is that we should ignore PLR1730 (https://docs.astral.sh/ruff/rules/if-stmt-min-max/):
- As @mhvk noted it can be slower.
- There are situations where the intent of the original code is more clear to me, e.g.
```
if count < 0:
    count = 0
# vs
count = max(count, 0)
```

We already ran into this PLR1730 in our Chandra code and it just ended up causing discussions that are distracting and waste time.

**Comment by taldcroft** [comment]
See https://github.com/astropy/astropy/issues/16863#issuecomment-2302519231

**Comment by pllim** [comment]
Benchmark failures seem unrelated? 🤷‍♀️ 

```
| Change   | Before [81432542]    | After [4440822a]    |   Ratio | Benchmark (Parameter)                               |
|----------|----------------------|---------------------|---------|-----------------------------------------------------|
| +        | 45.4±0.1μs           | 70.0±30μs           |    1.54 | units.time_quantity_times_unit                      |
| +        | 247±20μs             | 322±6μs             |    1.31 | units.TimeQuantityOpLargeArray.time_quantity_square |

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE DECREASED.
```

**Review by taldcroft — APPROVED** [review]

**Comment by taldcroft** [comment]
> So I see 2 approvals but also links to comments that this slows things down. Should we still merge?

These changes are not within tight loops so potential sub-microsec changes will have no noticeable impact. Also, one of the cases removes a redundant `len()` call so the execution is not necessarily slower.

**Comment by pllim** [comment]
Thanks, all!

**Pull request merged**
