### PR TITLE
Fix Lorentz1D derivatives

### PR DESCRIPTION
**Pull request by larrybradley**
### Description

This PR fixes the `fit_deriv` in the `Lorentz1D1` model.  The `d_A` and `d_x_0` values are incorrect.

Calculations here:
https://gist.github.com/larrybradley/4dcc41868c81a85754ee917aebe64ca6

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Sounds like a serious bug. 😱 

How did our test suite not catch that? Does this need a new regression test?

**Comment by larrybradley** [comment]
The derivatives are used primarily when fitting models.  There aren't any modeling unit tests that test the *validity* of the derivatives.

**Comment by pllim** [comment]
Should we start adding such a test, maybe starting with this particular case? 👀

**Comment by larrybradley** [comment]
It turns out there are some tests for model fit derivatives.  I added that for `Lorentz1D`, but the default `atol = 0.15` for the derivative test is so large that the test passes on both `main` and this PR.  I made the `Lorentz1D` 
 `atol` much more strict in this PR so that it only passes here and not on `main`.  For reference, the `main` atol=0.0078 with the incorrect derivatives.

**Review by nden — APPROVED** [review]
Looks correct now. Thanks!

**Comment by astrofrog** [comment]
@larrybradley should we be worried about the high ``atol`` for the other models, might we be missing other similar issues?

**Comment by larrybradley** [comment]
@astrofrog I was wondering about that too.  It's possible, but it would take a while to verify the derivates for all of the models.

**Comment by pllim** [comment]
I opened https://github.com/astropy/astropy/issues/16828 as a follow-up issue.

**Pull request merged**
