### PR TITLE
DOC: Fix dev docs in release branch (v6.0.x) TRY 2

### PR DESCRIPTION
**Pull request by pllim**
### Description

Like #15595 but less hacky maybe.

Fixes https://github.com/astropy/astropy/issues/15594

Closes #15595

- [x] Drop TMP commit after checking RTD rendering

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
@saimn , what do you think about the rendered doc here. I hacked the conf.py , so I think this is what you will see in the stable doc going forward. If you okay with this, I will undo the hack and then see what the dev would look like. Alas, I cannot keep the rendered doc for both because each PR only get one preview link from RTD with no version control. So lemme know. Thanks!

**Comment by saimn** [comment]
Looks good to me, thanks !

**Comment by pllim** [comment]
Okay, I removed the temporary hack. Should be ready for final review. The rendered doc now is for unreleased version, not stable.

Annoyingly enough, I do have to touch unrelated What's New entry to pass the pre-commit check. This probably means auto forward port will be impossible but I can do a manual forward port after merge.

Please approve and merge if you are okay with this. Thanks!

**Review by saimn — APPROVED** [review]
Thanks!

**Comment by pllim** [comment]
@meeseeksdev backport to main

**Pull request merged**
