### PR TITLE
ascii SExtractor reader splits column names at '-': astropy pip version 1.1.dev13389

### PR DESCRIPTION
**Pull request by taldcroft**
I'm trying to read in an SExtractor file that has column names with the '-' character in them, e.g. 

    # 1 a
    # 2 a-a
    0 0
    1 1

This file doesn't read in because it thinks that "a" and "a-a" are the same since it's truncating the second column name at the '-'.  Specifically, when I do 

    import astropy.io.ascii as ascii
    ascii.read('dummy_sextractor_file.txt', Reader=ascii.SExtractor)

I get 

    File "/usr/stsci/ssbx/python/lib/python2.7/site-packages/astropy/table/table.py", line 597, in _make_table_from_cols
    raise ValueError('Duplicate column names')

With a long traceback above that.  I've tried specifying in the call to read() 1) the delimiter to be " ",  2) the header_Splitter to be either core.WhitespaceSplitter or the DefaultSplitter with the delimiter set to " ", 3) names =["a", "a-a"].  None of these changed the behavior. 

read() with no Reader specified reads in the table but doesn't use the column names, replacing them with "col<n>".

I'm working on a Mac Pro OS 10.8.5, python 2.7, astropy installed from pip (version 1.1.dev13389), and numpy version 1.9.2.  The astropy install gives the githash as 9ea30c74502f69165055ed38dcfcda10b748d527, if that helps at all.

### CODE REVIEW

**Comment by taldcroft** [comment]
Code attached.

**Comment by hamogu** [comment]
Looks good to me. 
It's the minimal change we can do here. I'm curious now if we get a bug report in a few weeks that says "I have a + in my column names"...
If that happens, we should take the big approach and allow `\S+`, but for now this is fine.

**Comment by astrofrog** [comment]
Looks good to me too.

@taldcroft @hamogu - good to merge?

**Comment by hamogu** [comment]
Good to merge.

**Pull request merged**
