### PR TITLE
Changing the remaining log.warn()s to log.warnings()

### PR DESCRIPTION
**Pull request by bsipocz**
There are still a few ``log.warn()`` show up when one does a grep, but those are different as the given files import ``distutils.log``.

Also note that these are not changed to warnings.warn following @embray's comments from the original issue.

### CODE REVIEW

**Comment by pllim** [comment]
I am just going to link #3495 here for clarity eventhough I see that you linked it in your commit. Thanks!

**Comment by pllim** [comment]
Actually, in the original issue, @astrofrog said:

*For whoever fixes this: we should be using `warnings.warn` and include `AstropyWarning` as the warning type.*

**Comment by bsipocz** [comment]
and the @embray said (as I mentioned above):

_That actually depends. Most of the above cases are in shell scripts where log.warn is being used to write error messages to stderr and is not a code warning.
Likewise the one in astropy.__init__ I think was intentional._

**Comment by pllim** [comment]
Hmm. Okay, sorry for the noise.

**Comment by astrofrog** [comment]
This looks good - thanks @bsipocz!

**Pull request merged**
