### PR TITLE
Fix to HDUList.info() AttributeError

### LINKED ISSUE #5507: HDUList.info() breaks in presence of BZERO
Calling `HDUList.info()` on a dataset which applies a zeropoint from `BZERO` but which `astropy.io.fits` does not think it needs to resize to a new `dtype` results in an AttributeError.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-48ee3b413d82> in <module>()
----> 1 hdul.info()

/Users/jlong/software/astropy/astropy/io/fits/hdu/hdulist.py in info(self, output)
    757         default = ('', '', 0, (), '', '')
    758         for idx, hdu in enumerate(self):
--> 759             summary = hdu._summary()
    760             if len(summary) < len(default):
    761                 summary += default[len(summary):]

/Users/jlong/software/astropy/astropy/io/fits/hdu/image.py in _summary(self)
    787                     (self._orig_bscale != 1 or self._orig_bzero != 0)):
    788                 new_dtype = self._dtype_for_bitpix()
--> 789                 format += ' (rescales to {0})'.format(new_dtype.name)
    790 
    791         # Display shape in FITS-order

AttributeError: 'NoneType' object has no attribute 'name'
```

Example code in this notebook: https://gist.github.com/josePhoenix/1c892db5c460ab1c8a2f5d420f68b8e4

### PR DESCRIPTION
**Pull request by josePhoenix**
My attempt to fix #5507. May be masking further complexities.

CC: @mwcraig @embray

### CODE REVIEW

**Comment by MSeifert04** [comment]
@josePhoenix Thank you. Could you add a test case that fails without the fix and as soon as the PR has a milestone also a Changelog entry?

**Comment by MSeifert04** [comment]
You probably also need to rebase the PR so the circleci passes.

**Comment by josePhoenix** [comment]
```
===================================================== FAILURES =====================================================
____________________________________________ test_bzero_mishandled_info ____________________________________________

tmpdir = local('/private/var/folders/2t/m92rpkyn2ps064ffwv0qxrbm0001dr/T/pytest-of-jlong/pytest-0/test_bzero_mishandled_info0')

    def test_bzero_mishandled_info(tmpdir):
        # Regression test for #5507:
        # Calling HDUList.info() on a dataset which applies a zeropoint
        # from BZERO but which astropy.io.fits does not think it needs
        # to resize to a new dtype results in an AttributeError.
        filename = tmpdir.join('floatimg_with_bzero.fits').strpath
        hdu = fits.ImageHDU(np.zeros((10, 10)))
        hdu.header['BZERO'] = 10
        hdu.writeto(filename, clobber=True)
        hdul = fits.open(filename)
>       hdul.info()

astropy/io/fits/tests/test_image.py:1628:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
astropy/io/fits/hdu/hdulist.py:759: in info
    summary = hdu._summary()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <astropy.io.fits.hdu.image.ImageHDU object at 0x10c0a99d0>

    def _summary(self):
        """
            Summarize the HDU: name, dimensions, and formats.
            """

        class_name = self.__class__.__name__

        # if data is touched, use data info.
        if self._data_loaded:
            if self.data is None:
                format = ''
            else:
                format = self.data.dtype.name
                format = format[format.rfind('.')+1:]
        else:
            if self.shape and all(self.shape):
                # Only show the format if all the dimensions are non-zero
                # if data is not touched yet, use header info.
                format = BITPIX2DTYPE[self._bitpix]
            else:
                format = ''

            if (format and not self._do_not_scale_image_data and
                    (self._orig_bscale != 1 or self._orig_bzero != 0)):
                new_dtype = self._dtype_for_bitpix()
>               format += ' (rescales to {0})'.format(new_dtype.name)
E               AttributeError: 'NoneType' object has no attribute 'name'

astropy/io/fits/hdu/image.py:789: AttributeError
================================= 1 failed, 509 passed, 5 skipped in 21.75 seconds =================================
```

**Comment by pllim** [comment]
What's the milestone for this? 1.0.x?

**Comment by MSeifert04** [comment]
Does it affect 1.0.x? There were so many changes regarding bzero and bscale in the last versions so I really lost track if this is a new "feature" or not.

**Comment by mwcraig** [comment]
@josePhoenix -- thanks very much for fixing this!

@pllim @MSeifert04 -- the header keyword changes in https://github.com/astropy/astropy/pull/5053 were milestoned at 1.2.

As far as I can tell, the lines @josePhoenix is modifying are not present in 1.0.x, so I'd milestone it at 1.3.

**Comment by mwcraig** [comment]
The PR looks fine to me once it is rebased and a changelog is added. 

Just confirmed that the logic that introduced the error was in 1.1.x, so setting milestone to 1.3.

**Comment by MSeifert04** [comment]
@mwcraig Thanks for digging through the versions 👍 

I agree, once this is rebased and CircleCI passes this can be merged (if noone else objects).

**Comment by josePhoenix** [comment]
Circle CI seems to have run out of memory. I don't see any merge conflicts?

**Comment by MSeifert04** [comment]
CircleCI will pass once you rebase (the error was fixed recently).

**Comment by pllim** [comment]
I added a change log, rebased, and squashed for him.

**Comment by josePhoenix** [comment]
Thanks @pllim! 🎉

**Comment by mwcraig** [comment]
@pllim -- so is it correct that we can force push to PR branches too?

**Comment by mwcraig** [comment]
Thanks @pllim, that makes sense. Would have taken me a while to come up with that variation on my own!

**Comment by josePhoenix** [comment]
Pardon my ignorance, but why was it necessary to rebase?

**Comment by pllim** [comment]
To fix Circle CI test failure, as mentioned by @MSeifert04 [above](https://github.com/astropy/astropy/pull/5508#issuecomment-263647805).

**Comment by josePhoenix** [comment]
Ah, I didn't realize it runs with some Circle CI config version in the feature branch. Thanks!

**Comment by bsipocz** [comment]
@pllim @mwcraig - You don't need to fork again, everything can be done from your fork, you just have to specify from where to where to push, e.g. here I'm assuming you're working on HEAD and not in a feature branch, and pushing to @josePhoenix's fitsbug branch. Obviously with a rebase involved you need the -f.

``git push josePhoenix HEAD:fitsbug -f``

**Comment by pllim** [comment]
My fork's HEAD always point to a copy that is in sync with Astropy master. If I were to check out any PR branch, it would have been a feature branch. So don't think your command would work for me, @bsipocz . :slightly_frowning_face:

**Comment by bsipocz** [comment]
@pllim - The meaning of HEAD in git is always the tip of your current branch (https://git-scm.com/docs/gitglossary#gitglossary-aiddefHEADaHEAD). 

When I'm doing some trivial fix for someone else's PR, I don't usually create a branch for that, but check out theirs as a detached HEAD, do the fix, and push from there. 
If you are on a feature branch, the command should work, too, as the HEAD will be the top of that branch. Anyway, using the name of your branch in the same command instead of HEAD should work, too. (There are a few more complicated examples at the bottom of  ``git push --help``).

**Comment by mwcraig** [comment]
Restarted the failed travis job, which errored out partway through the tests.

**Comment by pllim** [comment]
Since @mwcraig approved it and tests passed, merging. Thanks, @josePhoenix !

Also thanks for the `git` instructions, @bsipocz ! I'll try that next time.

**Pull request merged**
