### PR TITLE
TST: unignore `__array__` protocol warning from numpy 2.0

### LINKED ISSUE #16815: TST: Un-ignore __array__ warning when h5py 3.12 is released
Wait till https://github.com/h5py/h5py/pull/2416 is released as part of h5py 3.12, then we can remove this that was added in https://github.com/astropy/astropy/pull/16814:

https://github.com/astropy/astropy/blob/c02979aba6ccaa51e0235537d71019d112d3b013/pyproject.toml#L228-L229

cc @neutrinoceros

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
Fixes #16815 now that h5py 3.12 is available

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Failure should be gone now. Can you please rebase? Thanks!

**Comment by neutrinoceros** [comment]
done !

**Comment by pllim** [comment]
Thanks! Gonna run the optional jobs too, just in case.

**Review by pllim — APPROVED** [review]
All green (linkcheck failure is unrelated). Thanks!

**Pull request merged**
