### PR TITLE
Remove bundled six

### PR DESCRIPTION
**Pull request by saimn**
Time to fully remove the bundled six for 3.2 ? This was kept only in case some package imported from `astropy.extern.six` I think.

### CODE REVIEW

**Comment by bsipocz** [comment]
I doubt that we can do this before 4.0 given packages may still use it, but if usage stats shows that this is not the case I'm not against for an earlier removal.
In either case, we need to make sure that at least the affiliated packages are updated before merging this.

**Comment by saimn** [comment]
It is difficult to filter real matches from github search. There was the same discussion for 3.0 (#6575), I think that it is fine to remove it now as packages that rely on six should really using it as a normal dependency instead on relying on astropy where it is no more used and maintained. 
But if you prefer to wait that's fine by me, and we can close this (I opened the PR because of #8314).

**Comment by pllim** [comment]
👍 for 4.0. And I think this also needs a change log entry.

**Comment by astrofrog** [comment]
What about adding a deprecation warning in 3.2?

**Comment by bsipocz** [comment]
> What about adding a deprecation warning in 3.2?

💯 absolutely, we should have done that a while ago already.

**Comment by bsipocz** [comment]
Also, this is the perfect example for the `keep-open` label, we shouldn't close it just because it will have to wait a half year to be merged.

**Comment by pllim** [comment]
Deprecation PR is opened as #8323 . This one will have to be rebased when that one is merged. FYI.

**Comment by pllim** [comment]
`six` is now deprecated in `master` and will be part of 3.2. 😉

**Comment by bsipocz** [comment]
I've opened PRs to switch from astropy bundled six to standalone for the coordinated packages.

Also, @pllim, this is an excellent issue to open batchissues for the repos that still have any import lines that contain both 'astropy.extern' and 'six' in any combinations :)

**Comment by pllim** [comment]
Can we finally push this one forward? 😍

**Comment by Cadair** [comment]
:fire: :fire: :fire:

**Comment by bsipocz** [comment]
> Can we finally push this one forward?

I suppose, but be prepared that packages will be on fire (if they test against astropy dev, but then they should have been on fire for a while due to the deprecation warnings...)

**Comment by saimn** [comment]
Rebased :).
This should be something easy enough to fix for packages that still use this.

**Comment by bsipocz** [comment]
@saimn - it definitely will need a changelog.

**Comment by pllim** [comment]
> batchissues

If you are serious about it, yeah, we can totally do it. @astrofrog made it so easy with his `batchpr` package. 😄

**Comment by pllim** [comment]
Re: `batchpr`

Wow, so many hits... And these are only three of the variants I can think of...

https://github.com/search?utf8=%E2%9C%93&q=%22from+astropy.extern+import+six%22+extension%3Apy+language%3APython&type=Code&ref=advsearch&l=Python&l=

https://github.com/search?q=%22import+astropy.extern.six%22+extension%3Apy+language%3APython&type=Code

https://github.com/search?q=%22from+astropy.extern.six+import%22+extension%3Apy+language%3APython&type=Code

**Comment by bsipocz** [comment]
@pllim - re batchpr: I never thought of openening batchPRs for repos, just batch issues to highlight the problem that they themselves need to solve.

**Comment by pllim** [comment]
@bsipocz , are you thinking only the affiliated repos? Or all those who got a hit in the searches above?

**Comment by bsipocz** [comment]
@pllim - I'm not sure. Would be nice to do all, but opening 700 issues may be a bit too much. I suppose in the long run we might want to check on a last modified date and only open these for repos that have been touched in the last e.g 12 months?

**Comment by saimn** [comment]
The deprecation warning was just added in 3.2, people are not yet seeing it, so it is not that surprising. Hopefully the number of occurrences should decrease after the 3.2 release.

But that also something to think about codes bundled in `astropy.extern`, maybe this should be private to avoid having other packages relying on it.

**Comment by astrofrog** [comment]
What if we do batch PRs for only repos that have opted in to astropy-helpers updates?

**Comment by bsipocz** [comment]
> What if we do batch PRs for only repos that have opted in to astropy-helpers updates?

PRs still cannot be written up fully automated as six then need to be added to the dependency lists, docs, etc, that's why I suggested doing batchissues instead.

**Comment by bsipocz** [comment]
(But then I agree, we need to fix this for any of the coordinated packages, and packages living under the astropy github org)

**Comment by bsipocz** [comment]
I think we can move forward with this nowish. The only active repo in the astropy org that still imports from the wrong place is halotools, I'm opening a PR to fix it.

Otherwise packages and maintainers I believe got a reminder issue, various emails, and enough time to act on this.

**Comment by astrofrog** [comment]
Agree, let's do this!

**Comment by bsipocz** [comment]
Thank you @saimn! 

Now, everyone, watch out for potential fires downstream...

**Pull request merged**
