### PR TITLE
Update sigma_clipping.py to avoid unnecessary data copy

### PR DESCRIPTION
**Pull request by nparley**
np.expand_dims seems to make a copy of the filtered_data while calculating the functions. This caused me to run into a memory problem. This change passes axis=axis to the cenfunc and varfunc is axis is not None. If axis is None then **axis_arg has no affect and the cenfunc can be defined without needing to accept the axis argument.

### CODE REVIEW

**Comment by embray** [comment]
Thanks. I'm not sure this is the best approach, since in principle there's no guarantee that a user-specified `cenfunc` or `varfunc` accept an axis argument.  Also is expand_dims really the culprit?  It seems to me that it does *not* copy that data (nor would it make sense for it to, since it's just updating the strides).

**Comment by nparley** [comment]
Hi Erik,

No worries just trying to help out :)

"If not `None`, clip along the given axis.  For this case, axis=int will be
passed on to cenfunc and varfunc, which are expected to return an array
with the axis dimension removed (like the numpy functions)."

You are already assuming that axis is being passed to cenfunc and varfunc
if axis is not none and say so in the doc string, so both versions would
have the same assumption? That's how I read that quote anyway. Nether
versions pass axis if axis is None. P.S. I think the use of lambda here
might be against PEP8 if you are following that.

As for the data copying this may be data profiler flagging the wrong line,
though changing this line did enable a data cube to process which had a
memory error before. I had to make more changes to this function to reduce
the memory, but did manage to get it to work without making any copies of
my input data cube in the end which helped me increase the size of my cube
by 2x on my machine. I will upload that as another pull request tomorrow,
although it may affect too many lines to be accepted. ;) Anyway lets close
this one and I upload the new one for you to look at.

Cheers,
Neil

**Comment by embray** [comment]
I see what you're saying now about it already assuming an axis argument, so that's fine.  Something should be done about that; if nothing else it should be documented.  What version of Numpy are you using and how are you profiling?  Because from my point of view this shouldn't have anything to do with `expand_dims`, but I could be wrong.  I haven't investigated this closely or tried to reproduce.

Don't bother opening a separate PR unless it's to address a completely new issue.

**Comment by nparley** [comment]
I am using numpy 1.9.2 and memory profiler. Here is the profile for the original version. As you can see there is an increment of 576 MiB on the first lambda line and 144.0 MiB on the second. Also it seems the function is called again and as the 127 line appears twice in memory profiler and this is where the maximum memory is reported:

```
Line #    Mem usage    Increment   Line Contents
================================================     
   123    809.8 MiB      0.0 MiB       if axis is not None:
   124    809.8 MiB      0.0 MiB           cenfunc_in = cenfunc
   125    809.8 MiB      0.0 MiB           varfunc_in = varfunc
   126   1385.8 MiB    576.0 MiB           cenfunc = lambda d: np.expand_dims(cenfunc_in(d, axis=axis), axis=axis)
   127   1529.8 MiB    144.0 MiB           varfunc = lambda d: np.expand_dims(varfunc_in(d, axis=axis), axis=axis)
   128                             
   129    809.8 MiB   -720.0 MiB       filtered_data = np.ma.array(data, copy=copy)
   130                             
   131    809.8 MiB      0.0 MiB       if iters is None:
   132                                     i = -1
   133                                     lastrej = filtered_data.count() + 1
   134                                     while filtered_data.count() != lastrej:
   135                                         i += 1
   136                                         lastrej = filtered_data.count()
   137                                         do = filtered_data - cenfunc(filtered_data)
   138                                         filtered_data.mask |= do * do > varfunc(filtered_data) * sig ** 2
   139                                 else:
   140   1529.8 MiB    720.0 MiB           for i in range(iters):
   141                                         do = filtered_data - cenfunc(filtered_data)
   142                                         filtered_data.mask |= do * do > varfunc(filtered_data) * sig ** 2
   143                             
   144   1529.8 MiB      0.0 MiB       return filtered_data

Line #    Mem usage    Increment   Line Contents
================================================
   127   2025.8 MiB      0.0 MiB           varfunc = lambda d: np.expand_dims(varfunc_in(d, axis=axis), axis=axis)
```

Changing the code gets ride of the memory usage on those lines but that's not really the problem.

```
   124    809.8 MiB      0.0 MiB       axis_arg = dict()
   125                             
   126    809.8 MiB      0.0 MiB       if axis is not None:
   127    809.8 MiB      0.0 MiB           axis_arg['axis'] = axis
   128                             
   129    809.8 MiB      0.0 MiB       filtered_data = np.ma.array(data, copy=copy)
   130                             
   131    809.8 MiB      0.0 MiB       if iters is None:
   132                                     i = -1
   133                                     lastrej = filtered_data.count() + 1
   134                                     while filtered_data.count() != lastrej:
   135                                         i += 1
   136                                         lastrej = filtered_data.count()
   137                                         do = filtered_data - cenfunc(filtered_data, **axis_arg)
   138                                         filtered_data.mask |= do * do > varfunc(filtered_data, **axis_arg) * sig ** 2
   139                                 else:
   140   1529.8 MiB    720.0 MiB           for i in range(iters):
   141   1385.8 MiB   -144.0 MiB               do = filtered_data - cenfunc(filtered_data, **axis_arg)
   142   1529.8 MiB    144.0 MiB               filtered_data.mask |= do * do > varfunc(filtered_data, **axis_arg) * sig ** 2
   143                             
   144   1529.8 MiB      0.0 MiB       return filtered_data
```

The main problem is the ```do = filtered_data - cenfunc``` line as this is making a copy of the whole data cube when we only need two slices. (Similarly this is making a copy of a whole array when you only need two numbers in 1D). So changing to the next version we get:

```
   123    809.9 MiB      0.0 MiB       axis_arg = dict()
   124                             
   125    809.9 MiB      0.0 MiB       if axis is not None:
   126    809.9 MiB      0.0 MiB           axis_arg['axis'] = axis
   127                             
   128    809.9 MiB      0.0 MiB       filtered_data = np.ma.array(data, copy=copy)
   129                             
   130    809.9 MiB      0.0 MiB       if iters is None:
   131                                     i = -1
   132                                     lastrej = filtered_data.count() + 1
   133                                     while filtered_data.count() != lastrej:
   134                                         i += 1
   135                                         lastrej = filtered_data.count()
   136                                         max_value = cenfunc(filtered_data, **axis_arg)
   137                                         standard_deviations = np.sqrt(varfunc(filtered_data, **axis_arg)) * sig
   138                                         min_value = max_value - standard_deviations
   139                                         max_value += standard_deviations
   140                                         filtered_data.mask |= filtered_data > max_value
   141                                         filtered_data.mask |= filtered_data < min_value
   142                                 else:
   143   1145.9 MiB    336.0 MiB           for i in range(iters):
   144    873.9 MiB   -272.0 MiB               max_value = cenfunc(filtered_data, **axis_arg)
   145    937.9 MiB     64.0 MiB               standard_deviations = np.sqrt(varfunc(filtered_data, **axis_arg)) * sig
   146   1001.9 MiB     64.0 MiB               min_value = max_value - standard_deviations
   147   1001.9 MiB      0.0 MiB               max_value += standard_deviations
   148   1145.9 MiB    144.0 MiB               filtered_data.mask |= filtered_data > max_value
   149   1145.9 MiB      0.0 MiB               filtered_data.mask |= filtered_data < min_value
   150                             
   151   1145.9 MiB      0.0 MiB       return filtered_data
```

The above is for a 4048x4048x9 float 32 data cube. If we define memory needed as ```memory_max - memory_in ``` where memory max is the maximum memory reported during the function by memory profiler and memory in is the memory used at the start of the function. Then we get:

 Data Cube | Memory needed Org | Memory needed New
------------ | ------------- | -------------
4048x4048x9 | 1216 MiB | 336 MiB
4048x4048x18 | 2368 MiB | 495.9 MiB
4048x4048x33 | 4287.3 MiB | 735.9 MiB

So the new version is memory constant plus the extra memory required to hold the mask values. The original version scales with the size of the axis you are sigma clipping over. Hope that helps.

**Comment by mhvk** [comment]
@nparley - just had look, and like your approach; much cleaner! 

The single travis failure seems spurious (related to some web services; they really are problematic), so I restarted it.

**Comment by mhvk** [comment]
Actually, on second thought, I'm a little surprised this works in all cases, since functions like `np.std` remove the axis from the output unless one gives `keepdims=True`. Can you please check that the routine works as expected also if `axis=1` (or any value other than `0`)? [Maybe there is a test case; sorry, I didn't check]

**Comment by mhvk** [comment]
@nparley - this could be resolved if you do `kwargs['keepdims'] = True`, but this will not work for numpy < 1.7, for which case one would still need the original. So, perhaps just keep the original rewriting of the functions? I think that the main memory usage improvement would be in the other changes you made anyway.

p.s.  Please do add a test case for `axis=1`!

**Comment by nparley** [comment]
This is because keepdims is not in the numpy.ma routines and filtered data is a masked array. You can use expand axis I think in this case with out any memory hit because you are expanding an ndarray. The updated version maybe is not quite as clean now.

**Comment by nparley** [comment]
OK sorry for all the messy commits, this now passes the tests but the coverage is missing two lines. There is already an axis=1 test but not for iters=None.

**Comment by larrybradley** [comment]
Note that there were several changes to `sigma_clip` in https://github.com/astropy/astropy/pull/3595.  I think perhaps there are no current merge conflicts because of the work to deprecate `sigma_clip`, but I think this PR should be rebased on the current master.  Of particular note, the `varfunc` keyword is now `stdfunc`, and there are now separate `sigma_lower` and `sigma_upper` keywords to allow for unsymmetric clipping.

**Comment by embray** [comment]
I can try doing the rebase if you need any help with that.

**Comment by embray** [comment]
If you want to just add a changelog entry under v1.0.4 -> Other Changes -> astropy.stats and make a note about performance improvements in sigma_clip (referencing this PR) then I can merge this.

**Comment by nparley** [comment]
Hi embray, there are no entries for v1.0.4 in https://github.com/nparley/astropy/blob/patch-2/CHANGES.rst should I just add the section or is there a way to pull the updated changes into this patch

**Comment by embray** [comment]
Try rebasing this PR on master first.

**Comment by nparley** [comment]
I can't seem to rebase this patch. Probably because I did not follow the instructions in the first place and just edited the file on github, sorry :( If I checkout astropy/nparley patch-2 then there are other commits there that are not in master and are not from me. Then rebasing I get the error:

``
Patch failed at 0001 Merge pull request #3368 from taldcroft/whatsnew-ecsv
``

Which has nothing to do with this. 

However comparing sigma clip in #3595 this patch will not work with those changes. It would require the code to be rewritten to work so it may be better to do this as a new clean feature from the new version in the master.

**Comment by nparley** [comment]
I am just going to close this pull request it has become a mess.

**Comment by embray** [comment]
Normally editing the file on GitHub shouldn't have been the problem.  You can use `git reflog` along with `git reset` to go back to before your botched rebase and try again (or at least get it back to just including the commit that contained the actual change).

**Comment by embray** [comment]
Until you want to either submit a new PR or whatever I'm leaving this one open to document the issue.  It would help if you can at least get it back to the state it was in previously so we can see what the change was.  Then it shouldn't be too much trouble to integrate.

**Comment by nparley** [comment]
I have created a new request #3956 which makes similar changes with the new version of sigma clipping from #3595

**Comment by crawfordsm** [comment]
This has now been closed by merging #3956.

**Pull request closed without merging**
