### PR TITLE
Try ubuntu 20.04

### PR DESCRIPTION
**Pull request by mhvk**
Hopefully this will resolve the core dumps on the other architectures

### CODE REVIEW

**Comment by pllim** [comment]
Alas... 😢 

```
.../uraimo/run-on-arch-action/v2.1.1/src/run-on-arch-commands.sh:
    line 6:  1115 Segmentation fault      (core dumped) python3 -m pytest
Error: The process '.../run-on-arch.sh' failed with exit code 139
```

**Comment by pllim** [comment]
Try to install [pytest-faulthandler](https://pypi.org/project/pytest-faulthandler/) into the two jobs, rerun them, and see if you get anything more useful.

**Comment by pllim** [comment]
Oh wait... "This plugin is now part of pytest core since pytest 5.0, so users should not install this plugin together with that pytest version."

**Comment by saimn** [comment]
faulthandler already gives a traceback :
```
Fatal Python error: Segmentation fault

Thread 0x00000055f11751e0 (most recent call first):
  File "/home/runner/work/astropy/astropy/astropy/samp/client.py", line 180 in _serve_forever
  File "/usr/lib/python3.9/threading.py", line 892 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap

Current thread 0x0000005501317f00 (most recent call first):
  File "/home/runner/work/astropy/astropy/astropy/tests/helper.py", line 432 in generic_recursive_equality_test
  File "/home/runner/work/astropy/astropy/astropy/tests/helper.py", line 457 in check_pickling_recovery
  File "/home/runner/work/astropy/astropy/astropy/units/tests/test_structured.py", line 214 in test_pickle
```
(I guess the samp one is just because the samp thread from previous tests wasn't terminated ?)

**Comment by pllim** [comment]
You have `pytest-xdist` in both jobs, so your pickling must be messing with the SAMP server threading running in the background. I am not sure what is the best solution here. Maybe @astrofrog or @embray can advise. If you can reproduce this locally, maybe it will be faster to isolate the actual bug with some sort of debugging tool (`gdb` or `faulthandler` maybe).

https://github.com/astropy/astropy/blob/2158c36979a5c8e4890a64947cfc631d1e928a72/astropy/units/tests/test_structured.py#L214

https://github.com/astropy/astropy/blob/2158c36979a5c8e4890a64947cfc631d1e928a72/astropy/samp/client.py#L177-L180

**Comment by mhvk** [comment]
In the meantime, should we just skip the tests on other architectures?

**Comment by pllim** [comment]
Re: skip -- I dunno. Maybe @olebole can chime in if such a segfault is ok to ignore.

**Comment by olebole** [comment]
That is probably not related to the segfailt, but I am not sure whether we should continue using the wcslib backport to Debian Buster here. Ubuntu 20.04 was released 2 1/2 years after Buster, and there is no test that the ABI (f.e. to cfitsio or others) is really unchanged.
Instead, it would be better to have a backport of wcslib 7.7 to Ubuntu 20.04, which can be done in a "Personal Package Archive" (ppa).
To have that, I created an ["astropy" team on Ubuntu's launchpad](https://launchpad.net/~astropy) and added a [test-support](https://launchpad.net/~astropy/+archive/ubuntu/test-support) to it; this may also in future serve as a helper repository to enable testing with Ubuntu. The relevant wcslib package for Focal is uploaded as well, with builds on amd64, arm64, armhf, ppc64el, s390x.
To lower the "bus factor" it would be great if we had another team member there.

**Comment by olebole** [comment]
For the segfault, I don't have a good idea... what platform is it (arm64 or s390x)? Maybe, one could retrieve the stack trace somehow?

**Comment by nstarman** [comment]
#12587 should help with some of the errors.

**Comment by pllim** [comment]
@olebole , the wcslib stuff should probably a separate PR. Thanks!

**Comment by pllim** [comment]
Segfault aside, I think it is still a good idea to bump Ubuntu, especially since @olebole already has a follow-up PR to this one. Let's get it in. Thanks!

**Comment by pllim** [comment]
p.s. Cancelling cron, no need to rerun.

**Comment by mhvk** [comment]
Thanks, @pllim, makes sense!

**Pull request merged**
