### PR TITLE
Change LaTeX representation of Angstrom symbol

### LINKED ISSUE #3617: Latex angstrom unit fails in matplotlib by default
The Latex formatting for 'angstrom' fails in matplotlib:

```
import matplotlib.pyplot as plt
from astropy import units as u
ang = u.Unit('Angstrom')
plt.xlabel(ang.to_string(format='Latex'))
plt.show()


Traceback (most recent call last):
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/figure.py", line 1079, in draw
    func(*args)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2092, in draw
    a.draw(renderer)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/axis.py", line 1117, in draw
    self.label.draw(renderer)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/text.py", line 538, in draw
    bbox, info, descent = self._get_layout(renderer)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/text.py", line 320, in _get_layout
    ismath=ismath)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 158, in get_text_width_height_descent
    self.mathtext_parser.parse(s, self.dpi, prop)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/mathtext.py", line 3005, in parse
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/mathtext.py", line 2339, in parse
    six.text_type(err)]))
ValueError:
\mathrm{\overset{\circ}{A}}
        ^
Unknown symbol: \overset (at char 8), (line:1, col:9)
```

Can we just replace it with `\AA`, which (at least on my system) works?  It seems to be supported by matplotlib: http://pythondammit.blogspot.de/2012/08/the-angstrom-symbol.html .  Or is there another acceptable alternative? (e.g., http://pythondammit.blogspot.de/2012/08/the-angstrom-symbol.html)

this came up in https://github.com/pyspeckit/pyspeckit/issues/17

### PR DESCRIPTION
**Pull request by mdboom**
Fix #3617

### CODE REVIEW

**Comment by mhvk** [comment]
Looks good. If you tested with both ipython and matplotlib, it would seem fine to just merge (don't know how we could put tests in for this...).

**Comment by mdboom** [comment]
I should have elaborated: Neither before or after this PR works with the currently released matplotlib.  After this PR wil work in conjunction with this https://github.com/matplotlib/matplotlib/pull/4274 in matplotlib.

It works before and after this PR for both "real" LaTeX and MathJax (i.e. IPython).  So it's not a regression even with an "old/current" matplotlib.

**Comment by mhvk** [comment]
OK, makes sense.

**Comment by mdboom** [comment]
I'm going to milestone this as a bugfix as it, practically speaking, should have no change on the ultimate result after rendering.

**Comment by embray** [comment]
:+1: I didn't even know about "mathring".

**Comment by mdboom** [comment]
Yeah -- it's weird.  There's a half a dozen StackOverflow answers about how to create the Ångström  symbol, all different.  Only `\mathring{A}` seems to produce something that doesn't look totally borked.  Between this and the issues with angstrom in FITS, I think this has the highest issue-to-symbol ratio in Astropy...

**Comment by pllim** [comment]
So much work for a depreciated unit (https://www.iau.org/publications/proceedings_rules/units/) :laughing:

**Pull request merged**
