### PR TITLE
Fix #4361 Resolves Edit on github links leading to 404

### LINKED ISSUE #4361: Some "edit on github" links lead to 404
Look at, e.g. http://astropy.readthedocs.org/en/latest/api/astropy.stats.poisson_conf_interval.html#astropy.stats.poisson_conf_interval

There is a link in the top left saying [edit on github]. This link **does** work.
However, there is also a "edit this page on github" link in the footer at the very bottom of the page. That link does **not** work. Presumably, that's true for all autogenerated API pages.
I don't think it's urgent or really a problem, but I open an issue here, so that we can look at it, if we ever modify the sphinx templates again.

### PR DESCRIPTION
**Pull request by sudheesh001**

### CODE REVIEW

**Comment by embray** [comment]
Have you confirmed that this fixes the issue?  This isn't really something that the automated tests check for.

**Comment by sudheesh001** [comment]
@embray It removes the Edit on github link from the bottom of these pages, since these `.rst` files aren't really available on github, I guess its correct that the link not be present.
For eg. `poisson_conf_interval` present in `docs/api/astropy.stats.poisson_conf_interval.rst` which builds via sphinx at `/build/sphinx/html/api/astropy.stats.poisson_conf_interval.html`
But since `docs/api/astropy.stats.poisson_conf_interval.rst` isn't available it doesn't really point anywhere.

**Comment by embray** [comment]
But the `[edit on github]` link to edit the docstring in the source still works, right?  If I understand the code for the Sphinx extension that should be the case, I'm just trying to make sure.

**Comment by sudheesh001** [comment]
Yes the `[edit on github]` in the function name link directly takes it to the corresponding function in the code on github.

**Comment by embray** [comment]
Great, thanks!

**Pull request merged**
