### PR TITLE
Remove implicit relative import from bundled configobj

### PR DESCRIPTION
**Pull request by jdavies-st**
It looks like this is an overlooked implicit relative import which is not covered by any astropy test coverage, as it's buried in the validate code which astropy does not use.  We picked this up in test coverage over at [jwst](https://github.com/STScI-JWST/jwst/pull/2112).

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! Can you please revert the file permission change reported in diff? `100755 → 100644`

@bsipocz , I'll let you decide on the milestone. I don't know how painful backporting is given that a bunch of PY2 compat code was stripped out of this file based on its history here (which also means that even though this file is in "extern", it has diverged from upstream, as @jdavies-st pointed out offline).

**Comment by pllim** [comment]
@bsipocz , `configobj` seems to have grown a little (i.e., not a single file anymore) -- https://github.com/DiffSK/configobj/ . p.s. The upstream code still use `six` etc to be PY2 compatible. If we want to update bundled version to match what is upstream, might be less painful to make it a formal dependency like we did with `pytest`? I see that @eteq did the original bundling, so maybe he can chime in.

@jdavies-st also pointed out that this bug does not exist upstream (feel free to correct me if I misunderstood).

**Comment by bsipocz** [comment]
yes. The issue is that there is no new upstream release. The last release date is from 2016, but in fact that tag existed in 2014 and probably that's the version we have including this issue here. 

They have issues asking for a new release, but nothing is happening, so I take back my original opinion here, and think we should indeed get this fix for the meantime. Backporting will be easy.

**Comment by jdavies-st** [comment]
Also, they've done some dramatic changes on master at https://github.com/DiffSK/configobj/ recently to the packaging.  They've moved the whole `configobj.py` chunk of code into `__init__.py` (and some other interesting things) to deal with legacy name space issues.  But yeah, without a release, maybe none of that matters.  🙈 🙉

**Comment by astrofrog** [comment]
Is there any way to add a regression test to make sure that we do in fact cover this code in our test suite?

**Comment by bsipocz** [comment]
@astrofrog - Do we really need to cover the external bundles, we already exclude them from the coverage reports.

**Comment by pllim** [comment]
@astrofrog , we only bundled it for `astropy.config` and obviously never used the part that is being patched. I agree with Brigitta that testing bundles is overkill and a very slippery slope.

**Comment by pllim** [comment]
@larrybradley !!!

```
____________________ test_biweight_midcovariance_symmetric _____________________
    def test_biweight_midcovariance_symmetric():
        """
        Regression test to ensure that midcovariance matrix is symmetric
        when ``modify_sample_size=True`` (see #5972).
        """
    
        rng = np.random.RandomState(1)
        d = rng.gamma(2, 2, size=(3, 500))
        cov = biweight_midcovariance(d)
>       assert_array_almost_equal_nulp(cov, cov.T)
E       AssertionError: X and Y are not equal to 1 ULP (max is 3)
astropy/stats/tests/test_biweight.py:215: AssertionError
```

**Pull request merged**
