### PR TITLE
Update ExponentialCutoffPowerLaw1D

### PR DESCRIPTION
**Pull request by sjhannon**
Update description to include Schechter function alias.

EDIT: Supersede #6363

### CODE REVIEW

**Comment by astrofrog** [comment]
@sjhannon - just for info, you don't actually need to open a new PR when rebasing - you can just force push to the same branch (but this is fine for now)

Pull requests should also always be opened against master (not the maintenance branches) but I can fix that now.

**Comment by astrofrog** [comment]
This needs a rebase following the change of base to master - will do that now

**Comment by sjhannon** [comment]
@astrofrog Duly noted, and thanks for the help. I'm new to github, so I still need to learn all the ins and outs of it.

**Comment by bsipocz** [comment]
@astrofrog - We really need to disable the "edit-on-github" on the stable docs (or force it to be against the master branch), as it just bites so many new contributors. 
I'll try to look into it soon, probably during the weekend.

**Comment by astrofrog** [comment]
Maybe we could make the link into a 'Go to latest docs to make edits' when not on latest?

**Comment by larrybradley** [comment]
@sjhannon Upon further review, `ExponentialCutoffPowerLaw1D` is not technically a Schechter function because of the sign on the power-law slope.  `ExponentialCutoffPowerLaw1D` uses `(x / x0) ** -alpha`, but a Schechter function is defined with `(x / x0) ** alpha`.

**Comment by nden** [comment]
Given this discrepancy with the sign, does it make sense to put a note to the effect that if used as a Schechter function, `alpha` needs to be with a negative sign? Or is it better not to mention Schechter function at all? Opinions from any actual users?

**Comment by larrybradley** [comment]
Thanks, @sjhannon.  I'm closing this in favor of #6375.

**Pull request closed without merging**
