### PR TITLE
fix #12322

### LINKED ISSUE #12322: Numpy distutils deprecation failing all PRs
### Description

Just got an error message in a PR : ``DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead`` that will fail all new / rebased PRs.

https://github.com/astropy/astropy/runs/4041136876?check_suite_focus=true

@astropy/testing-infrastructure-maintainers 

### Steps to Reproduce

Run the test suite!

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

Fix #12322

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by saimn** [comment]
There is nothing we can do here, it's on Numpy's side :
```
../../.tox/py310-test-devdeps/lib/python3.10/site-packages/astropy/table/operations.py:25: in <module>
    from . import _np_utils
astropy/table/_np_utils.pyx:11: in init astropy.table._np_utils
    ???
../../.tox/py310-test-devdeps/lib/python3.10/site-packages/numpy/lib/recfunctions.py:16: in <module>
    from numpy.testing import suppress_warnings
../../.tox/py310-test-devdeps/lib/python3.10/site-packages/numpy/testing/__init__.py:13: in <module>
    from ._private import extbuild, decorators as dec
../../.tox/py310-test-devdeps/lib/python3.10/site-packages/numpy/testing/_private/extbuild.py:11: in <module>
    from numpy.distutils.ccompiler import new_compiler
../../.tox/py310-test-devdeps/lib/python3.10/site-packages/numpy/distutils/__init__.py:24: in <module>
    from . import ccompiler
../../.tox/py310-test-devdeps/lib/python3.10/site-packages/numpy/distutils/ccompiler.py:17: in <module>
    from distutils.sysconfig import customize_compiler
/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/distutils/sysconfig.py:58: in <module>
    warnings.warn(
E   DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
```

**Comment by mhvk** [comment]
Ah, thanks! Then presumably they'll get to it...

**Comment by saimn** [comment]
Yes, there is a plan to replace `numpy.distutils` with meson (for Scipy currently, but I guess if it works Numpy would naturally follow the same lead, https://labs.quansight.org/blog/2021/07/moving-scipy-to-meson/). distutils is deprecated with removal planned for Python 3.12 , so there is time.

**Comment by pllim** [comment]
> there is a plan

@saimn , where is this plan document? Is it an issue somewhere in this repo, or do you plan to APE it?

**Comment by saimn** [comment]
A plan for `numpy.distutils` ? We use it only via `numpy.ctypeslib.load_library`, in `convolution`. We could also find another solution, which is related to #8036.

**Pull request merged**
