### PR TITLE
Added zeros class method in ICRS [#10241]

### PR DESCRIPTION
**Pull request by DoctorCronut**
This pull request is to address #10241. I added a class method to the ICRS doc frame
which will eliminate the need to write repetitive code if the 6 arguments used are all
zeros. I have not started on implementing the ICRS random class method as I don't
know the range of values expected as arguments in ICRS. 

Contributes to #10241

### CODE REVIEW

**Comment by pllim** [comment]
Hello and thanks! Needs the following:

* Add docstring.
* Add change log.
* Add unit test.
* Fix CI.

**Comment by nstarman** [comment]
> I have not started on implementing the ICRS random class method as I don't
> know the range of values expected as arguments in ICRS.

The  ICRS frame expects
Spherical: `ra` [0, 360), `dec` [-90, 90], `distance` [0, oo).
Cartesian: `x, y, z` (-oo, oo)
Cylindrical : `rho` [0, oo), `z` (-oo, oo), `phi` (-oo, oo)
    Note that this last one might be a bug and should probably be implemented as [0, 360)

**Review by StuartLittlefair — CHANGES_REQUESTED** [review]
Hi @DoctorCronut 

Since this is milestoned for 4.2 I had a look at the code. What you've added is certainly simple and meets the immediate need raised in the issue.

However, I think it would be a better approach to fix the underlying problem. ICRS is only one frame class of many and I think the better approach would be to implement a ```zeros``` and perhaps a ```ones``` method for all frames. This would involve changing the base classes such as BaseRADecFrame and friends.

Since 4.2 feature freeze is coming up, and this is not an urgent fix, I am going to re-milestone as 4.3

**Comment by eteq** [comment]
(Sorry, this PR should have expired due to lack of activity, but the bot is glitchy right now.  So BEEP BOOP Erik-bot closes this PR)

**Pull request closed without merging**
