### PR TITLE
Document Column's data and value attributes

### LINKED ISSUE #13012: Column.value is not documented
### Description

`Column.value`, an alias of `Column.data`, is not documented.
  https://docs.astropy.org/en/stable/api/astropy.table.Column.html

The alias was introduced back in PR #10962 .

Version: astropy 5.0.3

### PR DESCRIPTION
**Pull request by jerobado**
### Description

This will document the `Column`'s `data` and `value` attributes.

Fixes #13012 

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Please fix broken Sphinx refs. Thanks!

```
table/column.py:docstring of astropy.table.column.Column:84: WARNING: py:obj reference target not found: np.ndarray
table/column.py:docstring of astropy.table.column.MaskedColumn:93: WARNING: py:obj reference target not found: np.ma.MaskedArray
```

**Comment by pllim** [comment]
@orionlee , are you happy with this doc addition ?

**Comment by taldcroft** [comment]
@pllim - any clue why the intersphinx isn't work? I see things exactly like that in other places (see example below).
```
def get_cip(jd1, jd2):
    """
    Find the X, Y coordinates of the CIP and the CIO locator, s.

    Parameters
    ----------
    jd1 : float or `np.ndarray`
        First part of two part Julian date (TDB)
    jd2 : float or `np.ndarray`
        Second part of two part Julian date (TDB)

    Returns
    -------
    x : float or `np.ndarray`
        x coordinate of the CIP
    y : float or `np.ndarray`
        y coordinate of the CIP
    s : float or `np.ndarray`
        CIO locator, s
    """
```

**Comment by pllim** [comment]
It needs to refer to the proper API namespace defined by Numpy (which is defined inside their `objects.inv` in their intersphinx), maybe try something like this?

```
`numpy.ndarray`
```

Also see https://github.com/astropy/sphinx-astropy/blob/6928e75f53f3988e55121da5cd485fadfb2d8455/sphinx_astropy/conf/v1.py#L60

**Comment by pllim** [comment]
@taldcroft , where is this `get_cip`? Maybe they did some funky shortcut... 👀

**Comment by orionlee** [comment]
The doc change looks good, with a possible further enhancement.
- Where is the link of the doc generated by this PR on readthedocs? It'd be more assuring if we can see the actual generated doc as well.
- +1 on spelling out the difference in `MaskedColumn`
- For `MaskedColumn`, I wonder if we should be more verbose, and spell out that to get the `ndarray`, one can call `column.value.item()` / `column.data.item()` .

**Comment by pllim** [comment]
> Where is the link of the doc generated by this PR on readthedocs? 

There wasn't one because RTD was failing on broken refs. I took the liberty to push a commit to fix that just now. When it is done, if successful, you can click on `Details` to the right of the ReadTheDocs CI job to see the rendered doc.

**Comment by pllim** [comment]
@orionlee , `BaseColumn` API doc isn't exposed but you can see the addition at https://astropy--13135.org.readthedocs.build/en/13135/api/astropy.table.MaskedColumn.html . What do you think?

**Comment by orionlee** [comment]
> @orionlee , `BaseColumn` API doc isn't exposed but you can see the addition at https://astropy--13135.org.readthedocs.build/en/13135/api/astropy.table.MaskedColumn.html . What do you think?

Ah, I'm afraid of something like that (changes done in part of the doc that is not exposed) might happen. :-(

On the `MaskedColumn` doc, my earlier comment stands but it's not a show stopper:  

> For MaskedColumn, I wonder if we should be more verbose, and spell out that to get the ndarray, one can call column.value.item() / column.data.item() .

It just reflects that were similar doc were available, it'd have saved me time in figuring out how to get raw `ndarray` when I first dealt with `MaskedColumn`.

**Comment by pllim** [comment]
As I am not familiar with the API design, I'll have to defer to @taldcroft . Thanks for your feedback!

**Review by taldcroft — APPROVED** [review]
Looks good @jerobado thanks!!

**Comment by pllim** [comment]
@meeseeksdev backport to v5.0.x

**Pull request merged**
