### PR TITLE
Backport PR #14671 on branch v5.0.x (Fix numpy 1.25 deprecation warnings)

### PR DESCRIPTION
**Pull request by larrybradley**
Backport PR https://github.com/astropy/astropy/pull/14671 on branch v5.0.x (Fix numpy 1.25 deprecation warnings)

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Thanks!

**Comment by pllim** [comment]
Gonna close/re-open to make bot happy.

**Comment by saimn** [comment]
Tests are failing with
```
DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future
```
Why does this happen only in the v5.0.x backport ?

**Comment by pllim** [comment]
Probably need to patch more because that code was removed in later branches? 😒

**Comment by pllim** [comment]
Ugh looks painful. Should we just pin maxversion of numpy in v5.0.x and be done with it?

**Comment by pllim** [comment]
@WilliamJamieson might follow-up with a patch for the remaining failures. If not, we'll consider pinning a max version of numpy in LTS. Meanwhile, let's just get this in. Doesn't hurt to have either way. Thanks!

**Pull request merged**
