### PR TITLE
DOC: amend gh-17246 changelog to better emphasize user visible changes

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
As [requested by @eerovaher](https://github.com/astropy/astropy/pull/17246#discussion_r1815536021)

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Looks good to me - approving but not yet merging since this was really at the request of @eerovaher. But want to be sure it can get merged if need be.

**Comment by pllim** [comment]
I will just merge now. Eero can propose follow up PR before RC if he feels like it. Thanks, all!

**Comment by eerovaher** [comment]
The fundamental problem remains. If `astropy.units.astrophys` and `astropy.units.si` are public then you are not allowed to move unit definitions around without deprecating. If they are private then they should not be mentioned in the change log at all.

**Comment by pllim** [comment]
Okay, so we should delete the change log fragment altogether?

**Comment by mhvk** [comment]
I think we should keep the essence at least - the behaviour of `.to_system()` changed. I personally think it is fine as is: it just explains why this is the case - how we implement SI and astrophys as modules is at some level irrelevant to it. Anyway, I think we should just leave it as is.

**Pull request merged**
