### PR TITLE
Catch the warning from asdf's deprecation of CustomType

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

ASDF deprecated subclassing `asdf.types.CustomType` in asdf-format/asdf#1359. This PR catches that warning and suppresses it.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Merging asdf-format/asdf#1365 will enable this fix for the allowed failure CI.

**Comment by pllim** [comment]
Can u pls rebase to pick up some other changes and also to rerun the CI? Thanks!

**Review by pllim — APPROVED** [review]
As long as CI is green again. Thanks!

**Comment by pllim** [comment]
@WilliamJamieson , any chance you can help us manually backport this to v5.0.x ? 🙏

**Comment by WilliamJamieson** [comment]
> @WilliamJamieson , any chance you can help us manually backport this to v5.0.x ? 🙏

See #14406

**Pull request merged**
