### PR TITLE
Finalizing changelog for v6.1.0

### PR DESCRIPTION
**Pull request by astrofrog**
Time to release!

### CODE REVIEW

**Review by pllim — APPROVED** [review]

**Comment by pllim** [comment]
close/reopen to make CI happy

**Comment by pllim** [comment]
Hopefully RTD status would turn green when the job passes. The red X is from a previously cancelled run.

**Comment by astrofrog** [comment]
@MeeseeksDev backport to main

**Comment by astrofrog** [comment]
Wonder why this didn't happen automatically. @pllim - any ideas?

**Comment by pllim** [comment]
Not sure... Might be a safeguard because technically "backport to main" does not make sense. I can ask upstream.

**Pull request merged**
