### PR TITLE
Speed up __getitem__ and other representation methods.

### PR DESCRIPTION
**Pull request by mhvk**
Inspired by #3323, which notes that iterating over a `SkyCoord` is very slow, I looked at what happened for representations.  For those, getting an item or slice causes a new representation object to be created, which does a lot of tests on the inputs, which are not necessary, since the input data is known-to-be-good.  By skipping this, we can speed up accessing a single element by a factor of 3 to 4.

E.g.,:
```
import astropy.units as u, numpy as np
from astropy.coordinates import SphericalRepresentation
data = SphericalRepresentation(np.arange(180.)*u.deg, np.arange(-90, 90.)*u.deg, np.arange(180.)*u.kpc)
%timeit for d in data: pass
# 10 loops, best of 3: 70.7 ms per loop
```
With this PR:
```
10 loops, best of 3: 20.9 ms per loop
```

Note: I'm not quite sure this hack for getting a new class item is the right way to go; one might also add a flag to the initializer to skip the checks (or even allow a `copy='nocheck'` or so).

p.s. This will need some benchmarks...

### CODE REVIEW

**Comment by bsipocz** [comment]
@mhvk - There was once #3337 with similar aims and rather good speed ups. Is there any chance of taking that over and finishing?

**Comment by mhvk** [comment]
@bsipocz - yes, I'm aware of it, especially as it was mostly me that stopped that one. I think part of the problem was that it did too many things at once, so I'll leave this PR to do representations only!

**Comment by bsipocz** [comment]
@mhvk - I'm milestoning this into v2.0 to make sure we get these improvements there even if it's not finished up with benchmarks, etc.

**Comment by mhvk** [comment]
While I like these improvements still, I think they should not be done before the proper motion/velocity stuff is implemented, so I'm moving the milestone to 2.0.1 (counting this as a bugfix).

**Comment by mhvk** [comment]
@astrofrog - would it be possible to have astrobot not check PRs that have work-in-progress? In this particular case, I don't really want to add a changelog when I'm not even sure this is the right approach!

**Comment by bsipocz** [comment]
@mhvk - You can always ignore the bot's message, but I'll look into updating the message with something different when the  WIP label  is set.

**Comment by bsipocz** [comment]
This will need a rebase. 

However tests passed before, so should be good to go for a review. @eteq @adrn?

**Comment by mhvk** [comment]
OK, I rebased. The main question I have is whether one is better off with the hack I put in now, or by adding a new flag to `__init__` that bypasses all checks. Note that the hack may break subclasses that do more than setting attributes, while a new value for the copy flag might throw them off as well (though is should be fine if we ensure it evaluates to `False`; e.g., we could use `copy=None`). Or alternatively adjust the meaning of `copy=False` to not check anything.

**Comment by bsipocz** [comment]
@mhvk - Any chance to get this into 2.0.3, or we rather remilestone?

**Comment by mhvk** [comment]
closing since part of #6941

**Pull request closed without merging**
