### PR TITLE
Add --doctest-rst as a default option for pytest

### PR DESCRIPTION
**Pull request by astrofrog**
Previously, to run the code in an rst file in ``docs``, one had to do:

```
pytest --doctest-rst docs/coordinates/index.rst
```

but we could just make that option be set by default as done in this PR, which makes it possible to do:

```
pytest docs/coordinates/index.rst
```

I think the only downside is pytest will crash if pytest-doctestplus isn't installed, I think? If we agree this makes sense, we could add it to the package-template too.

### CODE REVIEW

**Comment by bsipocz** [comment]
We do require `pytest-astropy`, so if someone doesn't have that and it's components installed then no wonder things are not working? 🤷‍♀

**Comment by pllim** [comment]
Why not just do this when we remove helpers? Then we don't have to worry about things crashing.

**Comment by bsipocz** [comment]
The other approach is to roll out everything before removing the helpers, so potholes are already mended by the time everyone has to switch 🤷‍♀ 
(this one shouldn't really break anything)

**Comment by astrofrog** [comment]
Yes I'm with @bsipocz here that we should actually do as much as we can *before* removing astropy-helpers since things like this should already work ideally.

**Comment by astrofrog** [comment]
Not sure what happened to Travis though! 😱

**Comment by bsipocz** [comment]
I've restarted travis, hoping the oldest trick solves it...

**Comment by bsipocz** [comment]
Thanks @astrofrog!

**Pull request merged**
