### PR TITLE
DOC: Fix CI error when file exists

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address failure seen in https://travis-ci.org/github/astropy/astropy/jobs/681574609 when investigating #10242 .

```
______________________________ [doctest] 4.1.rst _______________________________
031 If this is written to disk, the dask array will be computed as it is being
032 written, which will avoid using excessive memory:
033 
034 .. doctest-requires:: dask
035 
036     >>> import dask.array as da
037     >>> array = da.random.random((1000, 1000))
038     >>> from astropy.io import fits
039     >>> hdu = fits.PrimaryHDU(data=array)
040     >>> hdu.writeto('test_dask.fits')
UNEXPECTED EXCEPTION: OSError("File 'test_dask.fits' already exists.")
```

### CODE REVIEW

**Comment by pllim** [comment]
Yes, it was merged, see #9439

**Comment by pllim** [comment]
Maybe this is not needed if we accept @saimn 's 27061122822e165cb0f7e07749bca342667a19d8 in #10242

**Comment by bsipocz** [comment]
Please do rebase. We certainly need this, and it's not yet clear which way to go with the other PR.

**Comment by pllim** [comment]
Rebased.

**Comment by bsipocz** [comment]
Thanks @pllim!

**Pull request merged**
