### PR TITLE
cosmo: move pickling tests

### PR DESCRIPTION
**Pull request by nstarman**
Now the pickle tests are run for every class and an instance of each class.

Requires #12214

Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by nstarman** [comment]
The problem is with units ``pickle.loads(pickle.dumps(cu.redshift)) != cu.redshift``!
Going to need to patch the units problem before this PR can move forward.

**Comment by nstarman** [comment]
See #12214 for a description of the problem.

**Review by mhvk — APPROVED** [review]
Looks all good to me!

**Comment by nstarman** [comment]
@pllim, do you know if there's a fix in the works for the 32-bit test? Could I have an admin merge if not? Thanks!

**Comment by pllim** [comment]
@nstarman , please hold. There is no rush for this, is there? I haven't had a chance to follow up yet. Over 100 notifications to catch up on. Thanks for your patience!

**Comment by pllim** [comment]
Can't blame numpy now for the 32-bit failure... 😬 

```
>           cosmology = _COSMOLOGY_CLASSES[cosmology]
E           KeyError: 'SubFLRW'
```

**Comment by nstarman** [comment]
Good thing we waited! 🤣

**Comment by pllim** [comment]
😅 

It is probably the parallel part that is biting you.

**Pull request merged**
