### PR TITLE
Add fallback option when image file is not in local directory

### PR DESCRIPTION
**Pull request by ADiegoCAlonso**
### Description

This pull request is to address the case where the image is not found in IMAGE_PATH, it will retrieve the image binary from repo.

Motivation: This code is published in other sites (e.g. [here](https://docs.astropy.org/en/stable/generated/examples/io/split-jpeg-to-fits.html)) without a link to the image file. By adding this fallback option, it increases the robustness of the code.

Fixes #<Issue Number>

### CODE REVIEW

**Comment by pllim** [comment]
Thanks, @ADiegoCAlonso ! However, I am a little confused. Under what circumstances would the script not find the input image file? It is version-controlled in the same directory as the script.

Making this example access the internet might complicate our doctest.

**Comment by ADiegoCAlonso** [comment]
@pllim I see your point. Indeed the code and data in the repo is self-contained and the fallback is not needed. The reason I proposed this change is because there is an [external website](https://docs.astropy.org/en/stable/generated/examples/io/split-jpeg-to-fits.html) that includes only the code of this script without a link to the data. An alternative option would be to modify that  website, which belongs to astropy.org.

**Comment by adrn** [comment]
@ADiegoCAlonso Thanks for the pull request! I agree with @pllim here that we should avoid adding a web request in here. I would instead opt for adding a comment above the `Image.open()` command with a link to the data file. However, note that this may all change significantly in the coming months as we are in the process of overhauling the example gallery.

**Comment by ADiegoCAlonso** [comment]
Thank you for the review. 
Based on your comments, I proceed to close this PR.

**Pull request closed without merging**
