### PR TITLE
Table indexing with docstring fix for Windows

### PR DESCRIPTION
**Pull request by taldcroft**
This is just #3915 but rebased to the latest master and with a fix for the docstring test fail on Windows.

### CODE REVIEW

**Comment by astrofrog** [comment]
@taldcroft - looks good :) merge when ready!

**Comment by mhvk** [comment]
Tests passed, so I'm merging.

**Comment by taldcroft** [comment]
Thanks @mdmueller!  :fireworks:

**Comment by embray** [comment]
:confetti_ball:

**Comment by mdmueller** [comment]
And thanks @taldcroft for the docstring fix!

**Comment by taldcroft** [comment]
The windows int32 default is a continual source of fun for me.

**Pull request merged**
