### PR TITLE
(DO NOT MERGE) Allow table columns to be hidden from print output

### PR DESCRIPTION
**Pull request by taldcroft**
I've had occasions where a table contains one or more very wide columns that obscure the print output.  It would be nice to be able to hide those columns selectively.

### CODE REVIEW

**Comment by astrofrog** [comment]
Not 1.1-critical so removing milestone

**Comment by mhvk** [comment]
Looked at this again after a long time (as I was reviewing "ready-for-final-review" PRs), and ended up uncomfortable. Mostly, I feel the state should not be on a `Column` (even if we allow `table[column].hidden  = True`, I think it should set something on the parent table), but this may be a moot point now that we have mixin columns. If we do have it on the table, I would suggest noting the hidden columns by default in `__repr__`. Ideally, we'd also propagate these meta data to `ecsv` files, etc.

Anyway, for now removed the `ready-for-final-review` label...

**Comment by taldcroft** [comment]
@mhvk - I look at this PR (longingly) every so often.  One thing that has changed in the meantime is moving toward encapsulating new column information in `info`.  This is now a natural and easy place to put new column attributes.

The other problem with having `Table` manage the hidden status in a `hidden` dict is that you need to maintain that dict.  Not insurmountable, but if one removes or renames a column then the `hidden` dict needs update.  This just creates a new linkage in the code and a way for things to break.  Having the hidden attribute on the actual column itself is consistent with the way other attributes are handled to this point and keeps them local and tidy.

But anyway, if I ever revive this it will be totally different.  I would like to leave this open for a little longer so I see it occasionally, but this exact PR will never get merged.

**Comment by taldcroft** [comment]
Long live hidden table columns!

**Comment by taldcroft** [comment]
I really need this today -- I have a number of tables with a columns that are complex objects (tables, long dicts) with huge reprs where I need to access the values but never print in a full table.  The solution of just selecting out the "columns I want" every time I look at the table is a pain.

I'm commenting as incentive to myself to first do the `info` overhaul and then this, which will then be easy.  And hopefully @mhvk will come around to the viewpoint that the visibility of a column is something that belongs in `info`, just like name, description, format, meta, etc.  It's just another column attribute after all.

**Comment by Cadair** [comment]
I was hunting for this feature, it would be really useful for sunpy if the default display columns could be changed and then unhidden by the user, or become unhidden if explicitly indexed etc.

**Pull request closed without merging**
