### PR TITLE
Fix D202 - NoBlankLineAfterFunction 

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

This PR targets the pydocstyle error D202 - having blank lines between the docstring and the code in a function.
D202 affects many files so I'm fixing this error code separately from others to make review easier.

As part of pre-commit `ruff` will now auto-fix this error, as part of CI or locally if the contributor has pre-commit installed as a git hook (https://pre-commit.com/#3-install-the-git-hook-scripts).

For reference from discussion below: D202 is part of the numpydoc style, which we try to use. 

https://github.com/numpy/numpydoc/blob/7ea993a6177b5b2186cd1bd96b83ee19d2bd641a/doc/example.py#L125-L129
```
    """
    # After closing class docstring, there should be one blank line to
    # separate following codes (according to PEP257).
    # But for function, method and module, there should be no blank lines
    # after closing the docstring.
```

Why should we do this?

IMO it's easier to stick closer to default settings. Most other python libraries do, which makes our code more similar stylistically and often therefore easier to read. At this point I'm so used to black that it takes me a hot sec to grok non-blackened code.

That said, D202 is definitely a lesser issue and if we choose not to enforce D202, that's alright too!

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by eerovaher** [comment]
The patch looks good, but I'd like `ruff` to be mentioned by name in the commit message.

**Comment by mcara** [comment]
What a nonsense error D202. I do not understand how blank lines **_outside_** of docstrings is of any concern for "pydocstyle".

**Review by taldcroft — APPROVED** [review]
OK for table, io.ascii and time.

**Comment by astrofrog** [comment]
I'm not really a fan of this stylistically as if there are other blank lines in the function afterwards it looks like the first line(s) are squished against the docstring... Do we definitely have to do this or is it a stylistic choice?

**Comment by mcara** [comment]
> Do we definitely have to do this ...

I wonder how the code in `astropy` was even working before. I would say that we simply ignore `D202` in setup.cfg or some other place globally.

**Comment by nstarman** [comment]
> The patch looks good, but I'd like `ruff` to be mentioned by name in the commit message.

I added ``Ruff will autofix this in the future.``

**Comment by nstarman** [comment]
> What a nonsense error D202. I do not understand how blank lines **_outside_** of docstrings is of any concern for "pydocstyle".

I agree it's non-intuitive, but ``pydocstyle`` is concerned with PEP 257 (the docstring PEP) which specifies both how docstrings are formatted and how code should proceed a docstring.

**Comment by mcara** [comment]
From PEP 257 example:
```python
def complex(real=0.0, imag=0.0):
    """Form a complex number.

    Keyword arguments:
    real -- the real part (default 0.0)
    imag -- the imaginary part (default 0.0)
    """
    if imag == 0.0 and real == 0.0:
        return complex_zero
    ...
```
would it be OK to add a blank line before closing `"""` as in:
```python
def complex(real=0.0, imag=0.0):
    """Form a complex number.

    Keyword arguments:
    real -- the real part (default 0.0)
    imag -- the imaginary part (default 0.0)

    """
    if imag == 0.0 and real == 0.0:
        return complex_zero
    ...
"""
????

**Comment by mcara** [comment]
Also, the note _"There’s no blank line either before or after the docstring."_ seems to be explicitly specified for one-line docstring and I do not interpret it as being required of multi-line docstrings. But maybe we need law degrees to read all the PEPs

**Comment by nstarman** [comment]
I believe that's another configuration choice. We use the ``numpy``` docstring style, which is a subset of PEP257.
Looking at https://numpydoc.readthedocs.io/en/latest/example.html#source, the full numpydoc example file, there should not be a new line between the docstring content and closing quote (nor between the closing quote and function start).

**Comment by WilliamJamieson** [comment]
> From PEP 257 example:
> 
> ```python
> def complex(real=0.0, imag=0.0):
>     """Form a complex number.
> 
>     Keyword arguments:
>     real -- the real part (default 0.0)
>     imag -- the imaginary part (default 0.0)
>     """
>     if imag == 0.0 and real == 0.0:
>         return complex_zero
>     ...
> ```
> 
> would it be OK to add a blank line before closing `"""` as in:
> 
> ```python
> def complex(real=0.0, imag=0.0):
>     """Form a complex number.
> 
>     Keyword arguments:
>     real -- the real part (default 0.0)
>     imag -- the imaginary part (default 0.0)
> 
>     """
>     if imag == 0.0 and real == 0.0:
>         return complex_zero
>     ...
> ```
> 
> ????
> 
> What does pydocstyle says about this?

It violates `D210` I think, see http://www.pydocstyle.org/en/stable/error_codes.html

**Comment by WilliamJamieson** [comment]
> This one is more a stylistic choice. PEP 257 doesn't have a specific recommendation for function docstrings, but it does for class docstrings — "Insert a blank line after all docstrings (one-line or multi-line) that document a class". Many docstring linters, including the most common, `pydocstyle`, infer the omission to meaningful, that the default assumption of docstring-then-code applies to functions. We can choose differently! (I'll just change the comment in `pyproject.toml` from `TODO: autofix` to `Don't fix`).

I am also not a fan of not skipping a line after a docstring in a function. The reasoning being due to an omission in PEP 257 seems like reading too much into it.

This being said, I prefer consistency (either no line skip or always line skip) and automated checks enforcing consistency. So I can get over this.

**Comment by dhomeier** [comment]
> It violates `D210` I think, see http://www.pydocstyle.org/en/stable/error_codes.html

That's about "whitespace", not blank lines...
But that would create an even more confusing look than having an isolated line of code sticking to the docstring.
https://peps.python.org/pep-0257/#multi-line-docstrings makes no specific mention of blank lines for functions, only asks for them with classes. Which is understood in the context of class methods also being separated by blank lines, so I guess the corollary is to use blank lines within functions sparingly.
My 2d, does not really look like an improvement to me, but can live with it.

**Review by WilliamJamieson — APPROVED** [review]
Modeling changes look fine

**Review by mhvk — APPROVED** [review]
I like this change, not just for consistency, but because it means there is more code per screen, so one has a better chance that all of a function/method and nearby stuff fits.

Indeed, that is the main thing I still do not like about `black` -- that it wastes vertical screen space. That said, I have to admit I'm getting used to it quite quickly and consistency in the code base is as nice as was advertised by those proposing we adopt `black`. 

Anyway, `constants`, `coordinates` and `units` all OK.

**Comment by mcara** [comment]
How can you get used to the waste of vertical space created by `black` and not to a blank line after a docstring. The later one actually improves readability.

**Review by larrybradley — APPROVED** [review]
`convolution`, `stats`, and `visualization` look fine.

**Comment by mhvk** [comment]
@mcara - it may part be that I use `emacs` - docstrings get shown in a different colour from code, so they stand out well on their own. Plus at least the multi-line docstrings end with just `"""` on a single line, which works well as a separation for me (for single line docstrings, I think the case for not having a space is much less clear).

image

**Comment by nstarman** [comment]
Rebasing to fix conflicts.

**Comment by eerovaher** [comment]
The commit message says `ruff` will autofix all cases of D202 in the future. Why isn't it applying all the autofixes right now?

**Comment by nstarman** [comment]
It is! A recently merged PR introduced merge conflicts. I rebased and ran ruff, auto-fixing all merge conflicts.

**Comment by eerovaher** [comment]
If `ruff` has already applied all the autofixes then why is the commit message talking about fixing D202 in the future?

**Comment by nstarman** [comment]
Future PRs.

**Comment by nstarman** [comment]
Rebased to fix merge conflict from #14273.

**Comment by eerovaher** [comment]
I would find it less confusing if the commit messages was something like
```
`ruff` will guard against violations from now on.
```
The current commit message 
```
Ruff will autofix this in the future.
```
left me with the impression that there is some one-off follow-up action that needs to be taken.

**Comment by nstarman** [comment]
@mcara, @astrofrog, you've both expressed the strongest objections to this style change. Have your concerns been addressed? Does this PR merit further discussion, or are you good to merge?

**Comment by mcara** [comment]
Even though I do not like that `pydocstring` (or the PEP relevant to this) is concerned with one extra line after *doctstring* to better visually separate a docstring from the code, it is what it is. IMO this is non-sense, really. First, because what's happening outside of a docstring should not be of concern for a tool that checks docstrings themselves (but I now understand that this is what PEP wants, though not clearly, IMO),and second, a string is just another line in the code. So, if PEP8 allows:

```python
def f():

    c = 'string'  # one empty line above is OK for flake8

    a = 1

    print(c)
```
or 
```python
def f():
    c = 'string'  # no empty line above

    a = 1

    print(c)
```
then I do not see why replacing `c = 'string'` with a `"""string"""` in the examples above makes things any different.

But my thinking above is all a useless exercise: if most people agree that that is how they want the formatting to be - then I am not going to say "No". So, while I would have liked an optional empty line after a docstring, I am OK with removing this option (though it still feels to me like an arbitrary and excessive measure).

**Comment by mcara** [comment]
Briefly, I do not object (officially) to this PR and the style that it brings.

**Comment by nstarman** [comment]
Rebased to fix merge conflicts.

**Comment by nstarman** [comment]
@eerovaher @dhomeier, updated the commit message to @eerovaher's suggestion.

**Review by taldcroft — APPROVED** [review]
Fine by me.

**Review by dhomeier — APPROVED** [review]
Had another look over `io.ascii` myself; everything there looks acceptable, thanks!

**Comment by nstarman** [comment]
Rebased to fix conflict in ``hdu/compressed.py``.

**Comment by nstarman** [comment]
merge? 7/11 requested reviewers, 7/8 who reviewed.

**Comment by mhvk** [comment]
Yes, let's get it in! Thanks, @nstarman!

**Pull request merged**
