### PR TITLE
Rm affiliated config

### PR DESCRIPTION
**Pull request by nstarman**
### Description

Cleanup of config.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by mhvk** [comment]
I'd just do the first commit and leave the explicit imports to another time. Personally, I'd prefer to do something like the following in all `__init__` -- this ensures that `__all__` is defined inside the file where one actually knows what should be exported (and causing minimum churn with respect to how we've done it so far).
```
from a import *
from b import *

__all__ = a.__all__ + b.__a__
```
Or just ensure `__init__` doesn't define anything else itself, so that what is there is in fact what should be exported.

**Comment by nstarman** [comment]
> I'd just do the first commit and leave the explicit imports to another time. 

Sure.

> Personally, I'd prefer to do something like the following in all `__init__` -- this ensures that `__all__` is defined inside the file where one actually knows what should be exported (and causing minimum churn with respect to how we've done it so far).
> 
> ```
> from a import *
> from b import *
> 
> __all__ = a.__all__ + b.__a__
> ```
> Or just ensure `__init__` doesn't define anything else itself, so that what is there is in fact what should be exported.

While convenient, the problem with this is that the contained modules are not really public, in the sense that we want users to import from the top-level namespace. Inclusion in ``__all__`` is a de facto standard for what is "public". I know that Astropy hasn't been careful about this, but perhaps for v6.0 this would be a good target.
I really like scipy's reference on what is public scoping: https://docs.scipy.org/doc/scipy/reference/index.html#importing-from-scipy

**Comment by pllim** [comment]
Technically speaking, this is still a change to public API. Does it need a change log?

How do we know if nothing downstream is somehow using this? It was put in for a reason, right? Is it too late in the v5.2 cycle to only do this now, right before feature freeze? Should this wait till v6 but go in early in the cycle?

**Comment by nstarman** [comment]
I made #13910

**Review by mhvk — APPROVED** [review]
Since the file was empty, this removal seems fine by me!

**Comment by nstarman** [comment]
I'm fine waiting for v6. It might be worth having a larger discussion on refactoring ``config`` to use https://docs.python.org/3/library/configparser.html instead of relying on an external library. ``ConfigParser`` is very extensible.

**Review by astrofrog — APPROVED** [review]
In the interest of time I pushed a direct commit here removing part of the docstring for astropy.config - then I think we can merge once CI passes. I can't find any direct imports of astropy.config.affiliated on GitHub.

**Pull request merged**
