### PR TITLE
WIP: Units performance

### PR DESCRIPTION
**Pull request by Juanlu001**
This is far from finished, and I expect many tests will fail, but I hope it serves as a starting point for some discussion. I will expand with a profiling results and some rationale later today or tomorrow.

@manodeep @eteq @adrn

### CODE REVIEW

**Comment by pllim** [comment]
Failure seems real, FYI -- https://travis-ci.org/astropy/astropy/jobs/374637529

**Comment by Juanlu001** [comment]
Hey @mhvk, thanks a lot for taking a look at this but it's still a roigh work in progress, so if you don't mind I prefer to answer to your comments above when I have something without test errors, and also so I have time to explain where does this come from.

**Comment by mhvk** [comment]
Just to add to the above: I am very much in favour of trying to speed up and clean up the code. But as noted, this really needs to be done in small pieces (for proper review if nothing else!). So could I ask to close this PR and open new, smaller ones?

Ideally, the separation would include separating PRs that change code from those that change test cases (we want to be sure that no optimization breaks anything, which is easiest to be confident of if no tests are changed). Finally, it would be nice to add benchmarks if relevant ones do not exist already.

**Comment by Juanlu001** [comment]
Maybe we are not understanding each other here, but I do not intend this to be reviewed and merged right away: it's just a dirty hack that I wanted to put together to see "the broad picture" of how could we start accelerating `Quantity`es, what API implications would it have, and what does it break. I also didn't write any description so all the context was lost.

I admit that I'm introducing a bit of noise, so I will close this PR until I have something that I'm happy with.

**Comment by mhvk** [comment]
It may well be that I am misunderstanding your goal, and I'm looking forward to seeing what you have in mind and how much it helps! But I think it was actually very useful to put up now, as a larger PR that touches even more of astropy and introduces new classes would be a true horror to review!

**Pull request closed without merging**
