### PR TITLE
MAINT: Use array-api-strict instead of np.array_api

### PR DESCRIPTION
**Pull request by MridulS**
### Description

This fixes https://github.com/astropy/astropy/issues/16149 
I think we should just add this optional dependency (it's a light python package) instead of skipping the test all together. If we are moving towards an array api astropy future we would need to add this dependency soon enough :)

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Thanks ! I think we can just close #16148 in favor of this one

**Comment by pllim** [comment]
Thanks! Let me run the "exotic archs" also, just in case.

**Comment by pllim** [comment]
devdeps failure is unrelated

**Comment by pllim** [comment]
How important is it to wait for https://github.com/astropy/astropy/pull/16142 to get merged first and then rebase, so you can be sure this works with numpy-dev?

**Comment by neutrinoceros** [comment]
If it helps, I just took out controversial parts from #16142 so it's more lightweight and hopefully backportable now :)

**Review by mhvk — APPROVED** [review]
Looks good, thanks! I agree that we should keep the test, since this was added because of a specific issue. And adding the dependency to `test_all` seems just right.

**Comment by pllim** [comment]
Any new Array API changes are unlikely to be backported anyway, right? Is there a reason why this PR needs to be backported?

**Comment by pllim** [comment]
OK. I'll let you decide when to merge. Thanks, all!

**Comment by mhvk** [comment]
Thanks, @MridulS!

**Pull request merged**
