### PR TITLE
Backport PR #15473: Ensure tables with masked and unmasked columns roundtrip properly (v5.0.x)

### PR DESCRIPTION
**Pull request by mhvk**
Manual backport of #15473 onto v5.0.x

### CODE REVIEW

**Comment by pllim** [comment]
You need the skip basebranch check label. I will close/reopen again.

**Review by pllim — APPROVED** [review]
Thanks!

**Comment by pllim** [comment]
Hmm @mhvk , does pyerfa not provide wheel for this?

```
  Collecting pyerfa>=2.0 (from astropy==5.0.9.dev29+g7efa256707)
    Downloading pyerfa-2.0.1.tar.gz (817 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 817.3/817.3 kB 78.1 MB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
```

**Comment by mhvk** [comment]
Hmm, that's weird, I thought that with our new scheme we have wheels that are good for all python/numpy versions... Maybe this takes some time? I restarted the CI run just in case. @astrofrog, do you know whether there is a delay in `pyerfa` wheel building, or whether they for some reason would not work with astropy 5.0?

**Comment by astrofrog** [comment]
Which job is not using PyERFA wheels?

**Comment by pllim** [comment]
`cp39-manylinux_x86_64 wheels`

**Comment by pllim** [comment]
Maybe it is not compatible with your `abi3` wheels (https://pypi.org/project/pyerfa/2.0.1/#files). This branch still uses `oldest-supported-numpy` and have this pin:

https://github.com/astropy/astropy/blob/8bb0d7d4a0c60d4550f7a00ccba28b4f2b807290/setup.cfg#L31

In the event it cannot find wheel, it tries to build pyerfa from source but now pyerfa needs `numpy>=1.25,<2` to build (https://github.com/liberfa/pyerfa/blob/1903739c3e971938c4b4e0e4994d3e3f6039ba71/pyproject.toml#L6).

Does this mean we need to pin `pyerfa<2.0.1` in this branch?

**Comment by mhvk** [comment]
Maybe we should relax the numpy constraint to build pyerfa from source? Pyerfa itself does not require that at all. If it is there just for wheel-building, then perhaps the constraint should be moved to that part (somehow).

**Comment by mhvk** [comment]
p.s. Given that 5.0 is almost at its end, pinning `pyerfa` may be reasonable too. But personally I prefer to remove the numpy constraint in pyerfa; it build perfectly fine for older numpy.

**Comment by pllim** [comment]
I don't think we can if I understood the conversation here correctly.

* https://github.com/astropy/astropy/pull/14949

**Comment by pllim** [comment]
At any rate, I think this backport should go in. So merging. Thanks!

**Comment by mhvk** [comment]
See https://github.com/liberfa/pyerfa/issues/119 for a place to discuss how to ensure we can at least build pyerfa from source with all supported numpy versions.

**Pull request merged**
