### PR TITLE
Add scatter_contour function to astropy.visualization.

### PR DESCRIPTION
**Pull request by adrn**
This is a port of @jakevdp's `scatter_contour()` function from [astroML](http://www.astroml.org/modules/generated/astroML.plotting.scatter_contour.html#astroML.plotting.scatter_contour) to `astropy.visualization`.

See also astroML/astroML#98.

cc @jakevdp

### CODE REVIEW

**Comment by astrofrog** [comment]
Before I go ahead and review this, I would like to strongly suggest adding this to Matplotlib instead of Astropy. I would suggest only considering it for Astropy if Matplotlib say no.

**Comment by larrybradley** [comment]
I agree with @astrofrog that the ideal home for this is `matplotlib`.

**Comment by adrn** [comment]
@jakevdp How do you feel about the idea of submitting this to matplotlib? I can handle the PR if you want, but since it's your original code just let me know what you'd prefer.

**Comment by adrn** [comment]
I talked to @jakevdp about this at AstroHackWeek. His feeling is that it would need some work before it can be submitted to matplotlib, and it's not clear that he or I have time to do that any time soon. That being said, I think it is useful as-is. So, what do we do?

1. Close this and tell people to install astroml if they want it
2. Put it in `astropy.visualization` as-is
3. Leave this open as a place to point people who might be interested in updating the code and submitting a PR to matplotlib

cc @larrybradley @astrofrog

**Comment by bsipocz** [comment]
Can we identify a mpl maintainer who is willing to take this and add to matplotlib? If not, then either option 1) or 2). Keeping PRs open for an unforeseeable future is not super helpful.

**Comment by larrybradley** [comment]
I'm not opposed to merging this.  Ideally it would go in `matplotlib`, but if that going to take a while we could use it as-is.  I agree with @bsipocz that we shouldn't keep this PR open indefinitely.  @astrofrog, do you oppose merging this?

**Comment by pllim** [comment]
If you merge this and plan to move this upstream, please open a new issue after merge so we don't forget. Thanks!

**Comment by astrofrog** [comment]
I'm still not sure about this - just out of curiosity, what work needs to be done to put it in matplotlib that doesn't need to be done here? I'm worried about putting code into astropy if the original author doesn't have time to maintain it.

An alternative would be to put this in [mpl-scatter-density](https://github.com/astrofrog/mpl-scatter-density), though this would also require some work.

If we do go ahead with this then this definitely needs some image tests (wcsaxes-style) and I would need to review this carefully.

**Pull request closed without merging**
