### PR TITLE
MNT: Remove deprecated Cosmology Parameter fmt

### LINKED ISSUE #13147: MNT: Remove deprecated Cosmology Parameter "fmt"
Cosmology Parameter "fmt" was deprecated in v5.1 in #13072. Remove it in v6.0.

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to fix #13147

### CODE REVIEW

**Review by nstarman — APPROVED** [review]
Great, thanks @pllim

**Comment by saimn** [comment]
@nstarman - Next time please wait for the release branch to be created before merging PRs for the next version.

**Comment by nstarman** [comment]
Sorry. I didn't see to which versions this was going. I thought this was the feature freeze last minute push.

**Comment by pllim** [comment]
Oh, no! Perhaps I should have opened them as draft PRs.

@saimn , did you revert on v5.3.x?

**Comment by saimn** [comment]
No luckily it was the last merged PR so I branched 5.3.x on the commit just before.

**Pull request merged**
