### PR TITLE
Revert "Convolution of astropy models"

### PR DESCRIPTION
**Pull request by keflavich**
Reverts astropy/astropy#6015

### CODE REVIEW

**Comment by keflavich** [comment]
#6015 was merged without being tested against #6273, which led to failures.  We need to revert it to get master back to green, then deal with the new errors.

**Comment by astrofrog** [comment]
@keflavich - since there is not too much activity today, you can also just try and open a PR that fixes the failures, if you can do it today (rather than reverting and re-applying)

**Comment by keflavich** [comment]
I think reverting is best; I'm in and out of the house today.

This failure:
https://travis-ci.org/astropy/astropy/jobs/246564303
is still present, but it was *not* occurring on #6267 before I merged it, and there were no ci-skip shenanigans there (everything was green before the last ci-skip commit).

So something is still amiss, and it is independent of the prematurely-merged #6015

**Comment by keflavich** [comment]
Also I'm very confused - I got an e-mail report from travis saying this PR (build 16078) passed, even though it's saying it did not here.

**Comment by bsipocz** [comment]
@keflavich - This PR was tested twice once as a push (it's not a branch on your fork, but rather one on astropy, a side effect of doing anything as a maintainer via the github web interface, and one of those travis runs had the unrelated urlerror failure.

btw #6267 looks totally fine, but #6015 never passed the tests.

**Comment by keflavich** [comment]
Ah, so this is OK to merge now?  The failure here: https://travis-ci.org/astropy/astropy/jobs/246564303#L2159 is just a URL error?

**Comment by bsipocz** [comment]
If @mirca is around and can pull out a fix soon, I would agree with @astrofrog above to prefer that rather than reverting.

**Comment by mirca** [comment]
@bsipocz I'm around and working on fixes =). Also, see #6274

**Comment by keflavich** [comment]
I think we need to merge the reversion.  There appear to be lots of hidden issues we missed: #6274, #6264.  

Also I remain confused and very worried by the travis failure here, since it is not self-consistent.  I'm not willing to merge this reversion with a failed test, but the failed test makes no sense to me.

**Comment by bsipocz** [comment]
The issue got solved by #6275, thus closing this.

**Pull request closed without merging**
