### PR TITLE
Fix ImportError on Python 3.x with NumPy < 1.7 in numpycompat utils module

### PR DESCRIPTION
**Pull request by MSeifert04**
Supersedes #4510.

### CODE REVIEW

**Comment by bsipocz** [comment]
I'm not sure whether it worth investigating about the unrelated appveyor issue,  I'm inclined to leave it as it unless you want to dig into the version numbers of graphviz, etc and figure out which one worked the last time appveyor passed on this branch.

**Comment by MSeifert04** [comment]
There are a lot of additional failures with numpy 1.12. Mostly because some representations changed (`SkyCoord`) and one about an unclosed file with `Table`. I'm not sure that I really want to dig into those failures. Except for the graphviz failure and the package incompatibilities on `conda` the failures are probably already fixed in the master branch, right?

**Comment by bsipocz** [comment]
Yes, I think we need to figure out which PRs from 1.3 and 1.3.1 we need to backport back to 1.0.x

**Comment by bsipocz** [comment]
I've gone through all the 1.3.1 PRs in order to try to backport them. I don't think I managed to find any that was a clean backport and will fix the np1.12 issues you see here. So probably the solution will be to change the numpy versions from ``stable`` to ``1.11``. 
TBH anyone with a pipeline/setup/etc that survives a numpy update probably can live with an astropy update, too.

**Comment by MSeifert04** [comment]
Given that it's mostly doctests that fail it's not too bad either. 😄

**Comment by bsipocz** [comment]
Well, you're welcome to open another PR against v1.0.x (or part of this one, I don't mind either). 

I believe that we can't backport anything that has been already relesed in 1.3.0 (or in 1.2.2). Is that right @eteq?

**Comment by MSeifert04** [comment]
The representation failures fix was deliberatly **not** backported: https://github.com/astropy/astropy/pull/5423#issuecomment-268451642

So I guess at least that one isn't critical. 

The other failure with the unclosed file reminds me a bit of a failure we encountered in https://github.com/astropy/astropy/pull/5550, unfortunatly the branch was rebased and the CI logs are buried somewhere in the history (is there a good was to search for travis logs linked to a specifc PR or even full-text search?)

**Comment by bsipocz** [comment]
> The representation failures fix was deliberatly not backported: #5423 (comment)

Oh, well I see, that I used the same argument there :)

>The other failure with the unclosed file reminds me a bit of a failure we encountered in #5550, unfortunatly the branch was rebased and the CI logs are buried somewhere in the history (is there a good was to search for travis logs linked to a specifc PR or even full-text search?)

Sadly I don't know a way to do this. Travis has an API (that I've never used), I guess I would start with that to do think like this.

> So if possible I would rather avoid doing too much work here. This is a really minor fix that has been around for almost 2 years and it's not as if I broke the 1.0.x branch (probably)

Fair enough. In this case I suggest to change the default numpy from "stable" to 1.11, so we don't get these failures in our CI, possibly hiding any real issues.

**Comment by bsipocz** [comment]
Well, limiting the numpy version didn't solved all the issues, but we're getting closer. 

I'll play around a bit with the branch to see whether one of the backports messed the branch up. Either way I'm inclined to merge this at the end of the day, the latest.

**Comment by MSeifert04** [comment]
@bsipocz  okay, then I misunderstood you. I thought you were going to limit the travis versions in another PR. 😄

**Comment by bsipocz** [comment]
Thanks again @MSeifert04.

**Pull request merged**
