### PR TITLE
Skycoord to accept more formats

### PR DESCRIPTION
**Pull request by bsipocz**
This is just a dump of the skycoord related commits removed from #2846. This should not be merged as is. First the right place/function need to be found for it as it's representation specific.  Added features:

* acceptance of space separated <6 value format
* support for JHHMMSS.ss+DDMMSS.s format

### CODE REVIEW

**Comment by bsipocz** [comment]
@taldcroft  - I've changed the code according to your comments, but made the edits on github, so ended up having a few PEP8 errors for Travis, and some of the lines may be too long, too. 
I'll fix them tomorrow when I have access to a properly configured editor.

**Comment by taldcroft** [comment]
Looking good @bsipocz thanks.  Now just a doc update and this will be ready.

I think you can show some examples of the extended parsing starting after this sentence in the SkyCoord doc page:  "Note that frame instances with data and SkyCoord instances can only be passed as frames using the frame= keyword argument and not as positional arguments."

So something like:
```
For representations that have ``ra`` and ``dec`` attributes one can supply a coordinate 
string in number of common formats.  Examples include::

  >>> ...
```

**Comment by taldcroft** [comment]
Closes #1115.

**Comment by taldcroft** [comment]
@bsipocz - any progress on the final documentation update to get this finished up?

**Comment by bsipocz** [comment]
@taldcroft - I've just added some examples to the docs, and also support for all the formats listed on the simbad coordinate query page (http://simbad.u-strasbg.fr/simbad/sim-fcoo).

**Comment by astrofrog** [comment]
@taldcroft @eteq - is this ready to merge?

**Comment by taldcroft** [comment]
Looks good to me.  :+1:

**Comment by astrofrog** [comment]
@bsipocz - could you add an entry to the changelog for 1.0?

**Comment by bsipocz** [comment]
Should I add a changelog entry?

**Comment by astrofrog** [comment]
@bsipocz - looks like our messages crossed :smile: - yes please to the changelog entry!

**Comment by astrofrog** [comment]
@bsipocz - can you remove ``[skip ci]`` from the last commit? (otherwise it won't run the CI on the rebased version). Thanks!

**Comment by bsipocz** [comment]
@astrofrog - Sure. I thought the conflict was in the changelog.

**Comment by astrofrog** [comment]
@bsipocz - I'm sure it was, but just want to be on the safe side :)

**Comment by bsipocz** [comment]
@astrofrog - My bad, I missed to add the issue number, thus another change to ``CHANGES.rst``.

**Comment by astrofrog** [comment]
@bsipocz - thanks!

**Pull request merged**
