### PR TITLE
Make it easier to use system version of astropy-helpers

### PR DESCRIPTION
**Pull request by astrofrog**
One of the things I often find myself doing is wanting to use my local developer version of astropy-helpers rather than the submodule or PyPI version. This *is* possible already by changing ``auto_use`` to ``False`` in ``setup.cfg``, but there is no way to do this via command-line flags, and ``auto_use`` is a somewhat cryptic option.

This PR does several things:

* It adds ``--auto-use`` and ``--no-auto-use``as command-line flags
* It adds a ``--use-system-astropy-helpers`` flag which is equivalent to ``--no-auto-use`` but I think should be the recommended flag to use since it is a lot more readable (solves https://github.com/astropy/astropy-helpers/issues/350)
* I have temporarily added two Travis jobs, both with the ``--use-system-astropy-helpers`` flag, but one with and one without installing astropy-helpers, to make sure the one without fails
* I removed other Travis jobs for now to not waste CI time

This should **not** be merged! If we agree on the principle and if it works, I think we need to do the following:

* [x] Make the changes done here in ``astropy-helpers`` instead of here first
* [ ] Update ci-helpers so that it's possible to more easily specify a version of astropy-helpers to install, including a 'dev' option. Just to be clear, we should never install astropy-helpers by default, but I want to be able to do ``ASTROPY_HELPERS=dev`` and have it be opt-in to installing the dev version of ``ASTROPY_HELPERS``.
* [ ] Add two cron job builds for this repo: one that runs the tests with the dev version of astropy-helpers, and one that runs the docs with the dev version. I don't think we should make this run in pull requests since this would affect contributors and would add unnecessary builds.

Before we go ahead, what do people think about this general approach?

cc @bsipocz @eteq

### CODE REVIEW

**Comment by bsipocz** [comment]
Overall I like the plan with some possible modifications to the cron plan. Is there any reason not to do the tests against astropy in astropy-helpers instead? We expect that the helpers modifications would break astropy and not the other way around, and that way we don't need make it possible in ci-helpers to install astropy-helpers, etc.

Btw my workaround for testing the new helpers was always either to hack in the submodule directory, or simply update it to latest dev and make some dummy modifications of the changelog or similar so it comes up as "dirty" disabling to change the version back to the committed version during build time.

**Comment by astrofrog** [comment]
> Overall I like the plan with some possible modifications to the cron plan. Is there any reason not to do the tests against astropy in astropy-helpers instead? We expect that the helpers modifications would break astropy and not the other way around, and that way we don't need make it possible in ci-helpers to install astropy-helpers, etc.

Good idea - note that we don't even have to run all the astropy tests, we can just make sure that the command runs for a given sub-package, so the tests will hopefully not be too time consuming.

However, it might still be worth allowing at least ``ASTROPY_HELPERS=dev`` so that affiliated packages that test against ``ASTROPY=dev`` can also check ``ASTROPY_HELPERS=dev`` in the same build (might as well)

**Comment by bsipocz** [comment]
> However, it might still be worth allowing at least ASTROPY_HELPERS=dev so that affiliated packages that test against ASTROPY=dev can also check ASTROPY_HELPERS=dev in the same build (might as well?)

OK, that makes sense.

**Comment by astrofrog** [comment]
I'm going to close this, as this was implemented in astropy-helpers. I think doing the changes to ci-helpers might be nice, but I don't feel strongly about it, so I'll close this for now and we can see if the need for the CI testing comes up.

**Comment by bsipocz** [comment]
@astrofrog - Currently I think it would be quite complicated to set up the astropy-helpers-dev testing. Hardly any of the packages are switching to 3.0, so what is dev in that sense, 2.0.x or 3.0.x?

**Comment by astrofrog** [comment]
@bsipocz - yes, let's not worry about that for now.

**Pull request closed without merging**
