### PR TITLE
Fix bug with writing FITS diffs to files in Py3

### PR DESCRIPTION
**Pull request by drdavella**
This is a "backport" to 2.0.x. There's not a test for this case currently. It would be easy enough to add one, but it would need to be "forward" ported.

@saimn, @MSeifert04 let me know if you want me to add a unit test.

### CODE REVIEW

**Comment by MSeifert04** [comment]
Wasn't there a similar issue with another script where we changed `'wb'` to `'w'`?

But it should have a unit-test, otherwise we never know if it's a cross-platform thing.

**Comment by MSeifert04** [comment]
Okay, I don't really understand why this targets 2.0.x. Is it fixed in master already?

**Comment by saimn** [comment]
Oh yes I already fixed this in #6621 but missed that this should have been backported to 2.0. Not sure if the full PR could be backported, so maybe it's easier to just add a test here (you can take the one I wrote in https://github.com/astropy/astropy/pull/6621/files#diff-4037eb68198cc8e5468baabe4fb7503aR90)

**Comment by bsipocz** [comment]
@saimn - I can try to backport, adding more tests perfectly fits into the vision of a bugfix release.

**Comment by saimn** [comment]
@bsipocz - ok, thanks!

**Comment by bsipocz** [comment]
@saimn - backport is done, let's see whether the tests pass on python2.

**Comment by bsipocz** [comment]
So the backport took care of the code fix, but that PR didn't contained a changelog. Do we need that, whas this reported as a bug somewhere?

**Comment by bsipocz** [comment]
Anyway, I'm closing this, and we can push the changelog directly on the branch if needed, as it should contain the number of the other PR anyway, and the bot won't like us doing it in a PR.

**Comment by saimn** [comment]
Yes, ci passed (for reference: https://travis-ci.org/astropy/astropy/builds/287302614) :sweat_smile: 
I added the changelog entry with 5f7f61300.

One thing I was not sure about is the pytest import: for v2.0 is it supposed to be imported directly or from `tests.helper` ? The two are used currently, but I think pytest should be imported directly (there are one 6 imports from helpers):
```
~/dev/astropy v2.0.x
❯ grep -ir "helper import pytest"
docs/development/testguide.rst:    from ...tests.helper import pytest
astropy/convolution/tests/test_convolve_models.py:from ...tests.helper import pytest
astropy/modeling/tests/test_quantities_fitting.py:from ...tests.helper import pytest, assert_quantity_allclose
astropy/modeling/tests/test_quantities_parameters.py:from ...tests.helper import pytest, assert_quantity_allclose
astropy/modeling/tests/test_quantities_evaluation.py:from ...tests.helper import pytest, assert_quantity_allclose
astropy/stats/tests/test_spatial.py:from ...tests.helper import pytest
```

**Comment by saimn** [comment]
Most of these imports are also on master, probably old PR that were not updated (it's easy to miss).

**Comment by bsipocz** [comment]
@saimn - re pytest: the PR that removed the bundled pytest also changed the imports, I guess all of these got merged from PRs that were already open at the same time. So yes, they need to be backported.

**Pull request closed without merging**
