### PR TITLE
Added new Tabular1D model

### PR DESCRIPTION
**Pull request by pllim**
Added a new model called `Tabular1D` to sample 1D discrete data points. I want use it in `pysynphot` to handle spectrum read in from FITS or ASCII tables.

Is it too optimistic to hope for v1.2 on this one?

TODO:
- [ ] Add change log when milestone is set.

### CODE REVIEW

**Comment by nden** [comment]
@pllim Does spacetelescope/gwcs#28 do what you need? It's a bit more general and my goal is to put it eventually in modeling. It needs a few minor changes which I can work on next week.

**Comment by pllim** [comment]
@nden, if you can get that PR in soon, I can just close this one. Thanks!

**Comment by pllim** [comment]
Closing in favor of the implementation in spacetelescope/gwcs#28 whenever @nden can get around to it.

**Comment by nden** [comment]
@pllim It can be considered ready as it is.
However, @embray suggested rewriting it as a factory function. This has the advantage of allowing to use it in combining classes, not just instances of classes. I personally do not intend to use it this way but some may find it useful (not sure). Another disadvantage (in my view) of a factory function is that I will have to use two calls instead of one to instantiate a model. 

I'll get to it this week.

**Comment by pllim** [comment]
Whatever you think is best. What would be easier to subclass? Because I will need to subclass it for `pysynphot`.

**Pull request closed without merging**
