### PR TITLE
Allow major formatter to be a callable in WCSAxes

### PR DESCRIPTION
**Pull request by astrofrog**
This makes it possible to override completely the formatter to use in WCSAxes, using public API.

cc @Cadair @ayshih

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by astrofrog** [comment]
This should be tested out by @Cadair to see if it is suitable for sunpy's use case of weird latitudes :laughing:

**Comment by pllim** [comment]
Failures look real.

**Comment by neutrinoceros** [comment]
remaining failures are unrelated and already resolved, but given @pllim's most recent message I'd still recommend rebasing so as to avoid confusing reviewers.

**Comment by astrofrog** [comment]
@pllim @neutrinoceros - rebased!

**Comment by pllim** [comment]
Tom, maybe you can take a train over to @Cadair 's house and make him review this.

**Comment by astrofrog** [comment]
Rebased

**Review by Cadair — APPROVED** [review]

**Comment by Cadair** [comment]
I tested this out with the inciting code from sunpy, and it [seems to work](https://github.com/sunpy/sunpy/pull/7803/files#r1804939171).

**Comment by pllim** [comment]
Thanks, all!

**Pull request merged**
