### PR TITLE
Add Lorentz2D model

### PR DESCRIPTION
**Pull request by larrybradley**
### Description

This PR adds a `Lorentz2D` model, analogous to the existing `Lorentz1D` model.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Does a new model (2D nonetheless) warrant a what's new entry? 🤔  I'll defer to modeling maintainers. Thanks!

**Comment by nden** [comment]
Do you want to add it to the page with predefined models?
https://astropy--16800.org.readthedocs.build/en/16800/modeling/predef_models2D.html

**Comment by larrybradley** [comment]
@nden Yes, thanks. I just added it to the predefined models page.

**Comment by pllim** [comment]
@nden , do we also need What's New?

**Comment by larrybradley** [comment]
I added a "What's New" entry.

**Review by nden — APPROVED** [review]
LGTM

**Comment by nden** [comment]
The failing Windows job cannot import h5py. Is this a known issue?

**Comment by larrybradley** [comment]
Tests are passing on `main`.  This PR doesn't touch anything with `h5py`, so I restarted that test hoping it was just a transient failure.

**Comment by larrybradley** [comment]
Tests are all passing now.  Thanks!

**Comment by pllim** [comment]
This might fail our integration testing until https://github.com/astropy/asdf-astropy/issues/243 is resolved.

@nden , who maintains asdf-astropy nowadays?

**Pull request merged**
