### PR TITLE
Add --color to sphinx linkcheck in ci

### PR DESCRIPTION
**Pull request by maxnoe**
### Description

Should make it much easier to spot what links failed.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Full output might be useful sometimes, no?

Thanks! I added "Extra CI" label to have linkcheck run here.

**Comment by pllim** [comment]
RTD failure is unrelated (due to RC period).

**Comment by pllim** [comment]
Oooo nice colors!

Actually... the broken link got swallowed in colorful log and only appears in B&W raw log, which kinda defeats the purpose of adding colors. Do you want to try the `-q` option here too? Thanks!

**Comment by maxnoe** [comment]
@pllim I see a red colored 404, what do you mean with swallowed?

**Comment by pllim** [comment]
> what do you mean with swallowed?

When I search for "broken" in the colorful log, nothing matched. But I could find it in raw log.

**Comment by maxnoe** [comment]
https://github.com/astropy/astropy/actions/runs/8558827347/job/23454200051?pr=16273#step:7:3355

**Pull request merged**
