### PR TITLE
Added broadcasting example to performance section of Coordinate docs

### LINKED ISSUE #7749: DOC: Broadcasting example for coordinates
As kindly provided by @StuartLittlefair via performance survey:

https://gist.github.com/StuartLittlefair/18a5c5271b099945a00a03454d9c34c2

Now that there is a performance section in the docs (#7592), this can go there.

### PR DESCRIPTION
**Pull request by SG004**
Fix #7749

### CODE REVIEW

**Comment by SG004** [comment]
According to the ci/circileci , appveyor and travis-ci, my  pull fails because "name 'u' is not defined"'

name u is no defined

Should I  just add the import statement: 'from astropy import units as u' ?

 The link in #7749 did not include it.

**Comment by pllim** [comment]
> Should I just add the import statement: 'from astropy import units as u' ?

Sounds about right. Yes, please try that. Thanks!

**Comment by SG004** [comment]
I've been trying to get this to work, but now the error is that 'lapalma' is not a site in EarthLocation.  What should I do now?

**Comment by pllim** [comment]
@SG004 , to avoid internet connection in that example, try do this instead:

```python
>>> # This is the same as EarthLocation.of_site('lapalma')
>>> lapalma = EarthLocation.from_geocentric(
...     5327448.9957829, -1718665.73869569, 3051566.90295403, unit='m')
>>> aa_frame = coord.AltAz(obstime=times[:, np.newaxis], location=lapalma)
```

**Comment by astrofrog** [comment]
@eteq - I thought some sites would work without a connection to the internet?

**Comment by drdavella** [comment]
I'm seeing html-docs failures in #7814 as well, so I wonder if something broke? It looks like it might be an issue with mpl.

**Comment by pllim** [comment]
> docs/visualization/wcsaxes/ticks_labels_grid.rst

@astrofrog ?

**Comment by astrofrog** [comment]
If you rebase, the docs issue should go away now

**Comment by SG004** [comment]
To be quite honest, I am fairly new at git/github. I most of the basic commands, but how would I go about rebasing? do i need to update my fork before rebasing or do I just rebase my branch to my remote master?

**Pull request closed without merging**
