### PR TITLE
Replace scipy.special.factorial with math.factorial and np.cumprod in _scipy_kraft_burrows_nousek

### LINKED ISSUE #5064: poisson_conf_interval broken on older versions of scipy
The test for `poisson_conf_interval` added in #4622 fails for me because my scipy version 0.13.2, which is admittedly a bit old but not *that* old either, does not have `scipy.special.factorial`.

At the very least this function should have a version check for scipy with an appropriate error message, and the test skipped.  I looked in the docs and we don't actually specify a minimum scipy version, so for now we're stuck with it.

### PR DESCRIPTION
**Pull request by MSeifert04**
This closes #5064 and supersedes #5271

I wasn't sure if I should've commented on #5271 instead of creating a seperate PR. But the approach in this PR is radically different.

As noted in the comments of the original issue the `factorials` are evaluated on an array, which makes it impossible to replace it with `math.factorial` (at least in `eqn8`) but fortunatly it's evaluated on an `np.arange`. So the factorials can be calculated by using `np.cumprod` (except for the first element). 

The second time factorial is used the value is a scalar so it's possible to replace it with `math.factorial`.

This PR also includes some performance optimizations (nothing fancy though):
- The result of eqn8 and factorial(N) are calculated once and then just reused (on my computer this yields a speedup of a factor 10).
- The second change is that `math.exp` is used (`math` is already imported because of `factorial`) instead of `np.exp`.

Since `exp7` is called hundreds of times the time difference is enormous:

The runtime for the command (taken from the tests) `%timeit funcs._scipy_kraft_burrows_nousek(5., 2.5, .99)`:
Before: `10 loops, best of 3: 124 ms per loop`
With this PR: `100 loops, best of 3: 4.69 ms per loop`

If it was wrong to open another PR for the issue please close this again.

### CODE REVIEW

**Comment by MSeifert04** [comment]
Now that #5271 is merged this PR is now a follow-up to make the function work faster and on SciPy < 0.14. :smile:

cc @hamogu

**Comment by MSeifert04** [comment]
@pllim Sorry to bother you but you are the only other participant here and you tagged it "Affects-dev": 

Does this need a Changelog regarding the performance improvement and that this function can now be used with SciPy < 0.14?

**Comment by pllim** [comment]
Maybe @mhvk knows since he merged #5271, which this follows up on, and the other one is *missing* a change log...

**Comment by crawfordsm** [comment]
I'd suggest adding a changelog to highlight the improvement (and also that it now works with earlier versions of scipy).   Nice speed up on the performance @MSeifert04 !

**Comment by mhvk** [comment]
Oops, does this mean we should revert #5271?

**Comment by MSeifert04** [comment]
I've included a changelog entry ("Other changes" section because of the performance aspect).

@mhvk I don't know. :-(

**Comment by mhvk** [comment]
I guess the easiest is to rebase on master and remove things no longer needed.

**Comment by hamogu** [comment]
This is a clever way to approach this. I'm glad to see that this little function generates so much interest of developers. I only hope that users find it equally interesting  ;-)

**Comment by MSeifert04** [comment]
> I guess the easiest is to rebase on master and remove things no longer needed.

This is already covered here. Maybe @mirca could have a look if I forgot something?!

**Comment by mirca** [comment]
@MSeifert04 I think you didn't forget anything, looks great :)

**Comment by MSeifert04** [comment]
Anyone wanting to do a final review?

**Comment by pllim** [comment]
@larrybradley ?

**Comment by crawfordsm** [comment]
I think everything is taken care of -- I'll give it one last look and then merge if there are no problems.

**Comment by larrybradley** [comment]
:+1:  Looks good to me.  Thanks, @MSeifert04.

**Comment by MSeifert04** [comment]
oh, that was fast. Thank you!

**Pull request merged**
