### PR TITLE
Fix Ellipse2D model

### PR DESCRIPTION
**Pull request by larrybradley**
This PR fixes the `Ellipse2D` model to be inclusive (`<=` instead of `<`) as documented and consistent with `Disk2D`.  This is my bug from when I originally added `Ellipse2D` in #3124.  Sorry!

This PR also turns off the `imshow` interpolation when plotting the example to not give the impression that pixels can be partially in the ellipse (they are either 1 or 0).

### CODE REVIEW

**Comment by larrybradley** [comment]
Can someone please restart `travis` test 9273.9?

**Comment by embray** [comment]
Should this be a bug fix for 1.0.3 instead?

**Comment by larrybradley** [comment]
@embray Yes.  I've moved the changelog entry.

**Comment by embray** [comment]
Cool thanks!.

**Pull request merged**
