### PR TITLE
Fixes issue #3122 of filenames being taken as URL

### LINKED ISSUE #3122: FITS reader thinks some filenames are URLs
I have had trouble opening files with certain names.  In the below example, `blah.fits` and `APEXHET.2014-04-01T15:18:01.000.fits` are the same file (`blah` is a hardlink).  

```
In [1]: f = fits.open('blah.fits')

In [2]: f = fits.open('APEXHET.2014-04-01T15:18:01.000.fits')
Traceback (most recent call last):
  File "<ipython-input-2-ebc6bf24211f>", line 1, in <module>
    f = fits.open('APEXHET.2014-04-01T15:18:01.000.fits')
  File "/Users/adam/repos/astropy/astropy/io/fits/hdu/hdulist.py", line 119, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, **kwargs)
  File "/Users/adam/repos/astropy/astropy/io/fits/hdu/hdulist.py", line 251, in fromfile
    save_backup=save_backup, **kwargs)
  File "/Users/adam/repos/astropy/astropy/io/fits/hdu/hdulist.py", line 768, in _readfrom
    ffo = _File(fileobj, mode=mode, memmap=memmap)
  File "/Users/adam/repos/astropy/astropy/io/fits/file.py", line 114, in __init__
    self.name, _ = urllib.request.urlretrieve(fileobj)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/urllib.py", line 205, in open
    return self.open_unknown(fullurl, data)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/urllib.py", line 217, in open_unknown
    raise IOError, ('url error', 'unknown url type', type)
IOError: [Errno url error] unknown url type: 'apexhet.2014-04-01t15'
```

The problem is that the filename apparently looks like a URL in line 113 of `file.py`:
`len(urllib.parse.urlparse(fileobj).scheme) > 1): # This is an URL` 

cc @embray

### PR DESCRIPTION
**Pull request by rashoodkhan**
I have added more checks to verify that given fileobj is an url by checking the scheme. The scheme is returned by urllib.parse.urlparse(urlfile).scheme - which contains the protocol for urlfile. For a valid URL, the scheme could be HTTP, HTTPS or FTP, hence anything else returned apart from this should not be treated as URL and should be treated as File.  Fixes #3122

### CODE REVIEW

**Comment by saimn** [comment]
Is there anything blocking this ? It would be great to have this fix in 1.0 (currently I patched my astropy git version, but all our file names contains colons so it will be a major issue if the fix is not in 1.0).

**Comment by astrofrog** [comment]
No, I was just waiting for @embray to merge https://github.com/astropy/astropy/pull/3167 :)

**Comment by barentsen** [comment]
Just to add that I too think this patch should really be in 1.0, because several ESO telescopes have colons in the filename convention.

**Comment by astrofrog** [comment]
@barentsen - I've just marked #3167 for the 1.0 milestone since it's ready to go. I think @embray wanted to add a regression test.

**Comment by barentsen** [comment]
:+1:

**Comment by rashoodkhan** [comment]
Awesome! :smile:

**Comment by embray** [comment]
Yeah, adding the test will just take me a few minutes.  This will be fixed for 1.0 at the latest.

**Comment by rashoodkhan** [comment]
If you can point me relevant resource for writing regression test, I will
add them. Thanks!

--
Rashid Khan
http://www.imrashid.com

**Comment by embray** [comment]
Superseded by #3167.

**Pull request closed without merging**
