### PR TITLE
Return False on update if there is no default configuration file.

### LINKED ISSUE #2841: 0.4.1: test_unedited_template fails
Hi,

when building on Debian (unstable; x86_64), I get the following:
```
___________________________ test_unedited_template ____________________________

    def test_unedited_template():
        # Test that the config file is written at most once
        config_dir = os.path.join(os.path.dirname(__file__), '..', '..')
        configuration.update_default_config('astropy', config_dir)
>       assert configuration.update_default_config('astropy', config_dir) is False
E       assert None is False
E        +  where None = <function update_default_config at 0x7f84e56d10c8>('astropy', '/tmp/astropy-test-PVRjx7/lib.linux-x86_64-2.7/astropy/config/tests/../..')
E        +    where <function update_default_config at 0x7f84e56d10c8> = configuration.update_default_config

astropy/config/tests/test_configs.py:334: AssertionError
```
Python version is 2.7

### PR DESCRIPTION
**Pull request by olebole**
Closes #2841 (seems to be forgotten?)

If there is no default configuration file, the update function should do nothing, which means it should return `False` (and not `None`).

However, for me this still looks not perfect: formally, the patch fixes the problem and the function behaves as described in its doc. But we have now three cases:

* default config available, first call --> update and return `True`
* default config available, subsequent calls --> no update **but write an alternative file** and return `False`
* no default config available --> no update, just return `False`

So, if the return value is really used as indicator whether something was updated, then it is fine.
But when it factically is used to determine whether there is an alternative file, the it will fail:
```
if assert configuration.update_default_config('astropy', config_dir) == False:
  # force updating
  os.rename('astropy.{1}.cfg'.format(astropy.__version__, 'astropy.cfg')
```
it will fail if the default file does not exist. I, however, do not understand why the error is not raised here anymore -- updating the configuration of a package that has no template is IMO nothing that should just pass through.

I also fixed the documentation (since the missing default does not raise the `ConfigurationDefaultMissingError` anymore); however it now becomes clear that the choice of this error class for the remaining case (missing version number of the package) is not really fortunate...

### CODE REVIEW

**Comment by astrofrog** [comment]
cc @mdboom

**Comment by embray** [comment]
It seems to me maybe there should be a couple different Configuration exceptions for the two different exceptional conditions, and that they should be handled as separate cases.

**Comment by olebole** [comment]
Maybe just don't catch the AttributeError if package.__ver__ is accessed? AttributeError in this case seems reasonable to me.

**Comment by mdboom** [comment]
@olebole: Yes, I think what you're suggesting (to not trap the AttributeError around package.__ver__) makes sense.  With that, I think this is good to merge.

**Comment by olebole** [comment]
@mdboom I still don't understand the reason of your  commit 5fdd508 which basically removed the `ConfigurationDefaultMissingError` but instead silently returns if the template could not be found. Is this really what a user expects when he calls `update_default_config()`? Trying to update the default configuration while there is none seems a good reason for an error.

**Comment by mdboom** [comment]
Some affiliated packages are not using the configuration system.  These packages then wouldn't have a template configuration file.  This is not an error, it's just that they aren't using the configuration system.  The user shouldn't be calling `update_default_config()` directly -- it is called on import of astropy or an affiliated package.

**Comment by olebole** [comment]
So I think this is ready to merge?

**Pull request merged**
