### PR TITLE
MNT: Remove CITATION symlink

### LINKED ISSUE #8299: Bad hardlink in 3.1 source tarball
Thanks for all the work put into this version; unfortunately I did not have time to test the release candidates. Unpacking the source (on Linux) results in the following error:
```
> tar xf astropy-3.1.tar.gz
tar: astropy-3.1/astropy/CITATION: Cannot hard link to `astropy-3.1/CITATION': Operation not permitted
tar: Exiting with failure status due to previous errors
```
Everything except for the link in `astropy/` is present, so `setup.py build` subsequently fails with
```
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    import astropy
  File "/beegfs/home/hd/hd_hd/hd_qc666/build/python/astropy-3.1/astropy/__init__.py", line 274, in <module>
    __citation__ = __bibtex__ = _get_bibtex()
  File "/beegfs/home/hd/hd_hd/hd_qc666/build/python/astropy-3.1/astropy/__init__.py", line 267, in _get_bibtex
    with open(citation_file, 'r') as citation:
FileNotFoundError: [Errno 2] No such file or directory: '/beegfs/home/hd/hd_hd/hd_qc129/build/python/astropy-3.1/astropy/CITATION'
```
This requires manually running ` ln -s ../CITATION` from the `./astropy/` subdir before the build proceeds.

### LINKED ISSUE #9658: Environment error when pip installing astropy from git repository on Windows
Happens for conda and "normal" CPython installations with Python 3.7:

```
pip                 19.3.1
setuptools          41.6.0
wheel               0.33.6
```

```
python -m pip install . -vv
Created temporary directory: ...\Temp\pip-ephem-wheel-cache-idteu68j
Created temporary directory: ...\Temp\pip-req-tracker-e9_xdn9u
Created requirements tracker '...\\Temp\\pip-req-tracker-e9_xdn9u'
Created temporary directory: ...\Temp\pip-install-tl7132cx
Processing d:\gitrepos\astropy\astropy
  Created temporary directory: ...\Temp\pip-req-build-8dww0lt5
ERROR: Could not install packages due to an EnvironmentError.
Traceback (most recent call last):
  File "...\lib\site-packages\pip\_internal\commands\install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "...\lib\site-packages\pip\_internal\legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "...\lib\site-packages\pip\_internal\legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "...\lib\site-packages\pip\_internal\legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "...\lib\site-packages\pip\_internal\operations\prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "...\lib\site-packages\pip\_internal\download.py", line 452, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "...\lib\site-packages\pip\_internal\download.py", line 387, in unpack_file_url
    _copy_source_tree(link_path, location)
  File "...\lib\site-packages\pip\_internal\download.py", line 367, in _copy_source_tree
    shutil.copytree(source, target, **kwargs)
  File "...\lib\shutil.py", line 368, in copytree
    raise Error(errors)
shutil.Error: [('...\\astropy\\CITATION', '...\\Temp\\pip-req-build-8dww0lt5\\CITATION', 'symbolic link privilege not held')]
Cleaning up...
Removed build tracker '...\\Temp\\pip-req-tracker-e9_xdn9u'
```

But it works using Python 3.8 (conda and normal Python installation).

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address the pain caused by symbolic link of the upper level CITATION file that surfaces from time to time. This PR removes the symlink and instead put URL to the real file in the file.

Fixes #9658, fixes #8299, xref #7718 

cc @dhomeier

### CODE REVIEW

**Comment by bsipocz** [comment]
Nitpicking, but what about making it a markdown, so the link would be rendered when opening the file on github?

**Comment by pllim** [comment]
I am neutral on the format, so I'll change to markdown if there is a consensus.

**Comment by MSeifert04** [comment]
I'm pretty certain this will fix the installation issue. However I will do a check later.

**Comment by MSeifert04** [comment]
Since this fixes an issue that makes it a bit troublesome for me (and maybe other windows users) I'm going to merge this.

Further refinement (if necessary) can also be done in a future PR.

Many thanks @pllim and @bsipocz

**Pull request merged**
