### PR TITLE
Address ruff's rule PIE790 in io submodule

### PR DESCRIPTION
**Pull request by hfcpeixoto**
This pull request is to address violations to Ruff's rule **PIE790**, which is listed explicitly in issue https://github.com/astropy/astropy/issues/14818. Only submodule `io` is addressed.

This is part of a series of PRs split from https://github.com/astropy/astropy/pull/15239, following suggestions by @nstarman.

Solves part of #14818.

### CODE REVIEW

**Comment by eerovaher** [comment]
There's a merge conflict that needs to be resolved.

**Comment by hfcpeixoto** [comment]
Actually, it seems that changes in this PR have already been merged into `main` in another PR. 

I am closing this. Thanks, for the ping @eerovaher .

**Comment by hfcpeixoto** [comment]
Actually, it seems that changes in this PR have already been merged into main in another PR.

I am closing this. Thanks, for the ping @eerovaher .

**Comment by pllim** [comment]
Thanks anyway, @hfcpeixoto . Much appreciated!

**Comment by hfcpeixoto** [comment]
The changes had not been inserted into `main`, indeed. Thanks for noticing this, folks. I have opened https://github.com/astropy/astropy/pull/15446, as Github did not allow me to reopen this one. Most probably because I force-pushed into my fork's branch to update conflicts upon rebasing.

**Comment by eerovaher** [comment]
I should point out that my previous comment didn't give the best advise. `--isolated` tells Ruff to ignore all configuration files, so the `extend-per-file-ignores` settings in `.ruff.toml` are ignored and `ruff check` can actually find violations. But it is better to use `--config=pyproject.toml`, because that also tells Ruff to ignore `.ruff.toml`, but differently from `--isolated` it ensures that the settings in `pyproject.toml` are respected. I have of course updated #14818 accordingly.

**Pull request closed without merging**
