### PR TITLE
update PyFITS to FITS

### LINKED ISSUE #5062: Warning message mentioning PyFITS
The ``astropy.io.fits.verify`` (https://github.com/astropy/astropy/blob/ffc0a89b2c42fd440eb19bcb2f93db90cab3c98b/astropy/io/fits/verify.py#L112) appends a message saying that ``PyFITS`` uses "zero-based indexing". Is this some historical artifact or is it common to refer to astropy.io.fits as pyfits?

### PR DESCRIPTION
**Pull request by gastronomyk**
Removed the word PyFITS from the message

Warning message mentioning PyFITS #5062 

EDIT: Closes #5132, fixes #5062

### CODE REVIEW

**Comment by pllim** [comment]
Seems similar to #5132 but without any change to license info.

**Comment by crawfordsm** [comment]
Yes, it is actually fixing the warning message in #5062.  This is @gastronomyk first PR

**Comment by pllim** [comment]
I actually prefer this one. :+1:  We'll worry about licenses later.

**Comment by bsipocz** [comment]
I agree with @pllim that this is a duplicate. 
Also pyfits should be called ``astropy.io.fits`` rather than ``FITS`` as in #5132.

**Comment by eteq** [comment]
yeah, I think I agree with @bsipocz that `astropy.io.fits` is better... or did you mean you preferred it this way, @pllim ?

And just so we're all on the same page... is the point of this to address #5062 now so that we can have more discussion about the license in #5132 ?  If so, then this should *not* close #5132.

**Comment by pllim** [comment]
@eteq , sorry for the confusion. I meant I like that this PR does not try to change the license info. I have no problem with the verbiage using `astropy.io.fits`. IMHO, licensing should be a completely separate discussion, not attached to a PR like this, as in #5132, so I am still in favor of closing #5132 and just open a fresh issue focusing on the general policy of license transfer in Astropy (not just for PyFITS).

**Comment by pllim** [comment]
p.s. Appveyor error is fixed in another PR, right? Maybe a rebase would resolve the currently failed test.

**Comment by bsipocz** [comment]
Yes, appveyor is fixed. Since this can't fail the tests, one can merge it with failing appveyor, the merge commit will pass. But this still needs either an amended commit to change ``FITS`` -- > ``astropy.io.fits``, or  a rebase+squash the two separate commits.

**Comment by gastronomyk** [comment]
`FITS` has now been replaced with `astropy.io.fits`

**Comment by eteq** [comment]
Alright looks great now.  Merging!

**Pull request merged**
