### PR TITLE
rename X_test to test_X in io/votable/tests

### PR DESCRIPTION
**Pull request by nstarman**
As is customary.

### CODE REVIEW

**Comment by eerovaher** [comment]
[`pytest` is happy either way](https://docs.pytest.org/en/stable/explanation/goodpractices.html#conventions-for-python-test-discovery), but filenames following the pattern `*_test.py` are faster to tab-complete.

**Comment by nstarman** [comment]
And easier for our configuration, which matches on `test_`.

**Comment by nstarman** [comment]
> [pytest is happy either way](https://docs.pytest.org/en/stable/explanation/goodpractices.html#conventions-for-python-test-discovery), but filenames following the pattern *_test.py are faster to tab-complete.

This is one of the few set of test files in Astropy that are named `*_test`. IMO consistency is best. If we ever wanted to switch to `*_test` it could be done globally in 1 PR.

**Comment by pllim** [comment]
👎 on renaming everything to `*_test` format just so someone can tab complete faster.

**Review by pllim — APPROVED** [review]
The old names borderline annoyed me for a long time, so I am just going to merge this. Thanks!

**Pull request merged**
