### PR TITLE
Update matchsep.rst

### PR DESCRIPTION
**Pull request by richardgmcmahon**
adding some more links an explanation to catalog matching section

This is work in progress and my first attempt at the sort of thing.

My goal is add inline links to the docs that describe match_coordinates_sky and match_to_catalog_sky

http://docs.astropy.org/en/stable/api/astropy.coordinates.match_coordinates_sky.html#astropy.coordinates.match_coordinates_sky

http://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord.match_to_catalog_sky

### CODE REVIEW

**Comment by eteq** [comment]
@richardgmcmahon - to get the links you want to see, you'll want to do put something like this in the : `` :meth:`~astropy.coordinates.SkyCoord.match_to_catalog_sky`  ``  - if you look a ways further up in the documentation you'll see something similar to this.  The `:meth:` is, strictly speaking, unnecessary, because Sphinx is usually smart enough to figure out that `match_to_catalog_sky` is a method.  The `~` part is also optional, but it has a very important effect: it hides the `astropy.coordinates.SkyCoord` part in the actual output documentation.  So in the sphinx docs, `` `~astropy.coordinates.SkyCoord.match_to_catalog_sky`  `` will get you [match_to_catalog_sky](http://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord.match_to_catalog_sky), but `astropy.coordinates.SkyCoord.match_to_catalog_sky` gets you  [astropy.coordinates.SkyCoord.match_to_catalog_sky](http://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord.match_to_catalog_sky) .

All that said, I don't understand why you want to make the particular change you're making here: the sentence that you've changed is saying that the `ra1` and `dec1` are loaded from some *other* file, which has nothing to do with `match_to_catalog_sky` - `match_to_catalog_sky` works after you've created the `SkyCoord`...?

**Comment by richardgmcmahon** [comment]
I was  trying to make links to the api docs since I found it a little bit confusing that there is a function and a method that do the same thing. I am a user and the api docs are every helpful and helped. Maybe examples that show both the usage of the function and method could be provided. I am working with multicolumn tables and use the returned  idx to subset the inputs and then hstack to create a joined
table.

**Comment by eteq** [comment]
@richardgmcmahon - were you still planning to update this to make the added changes you've mentioned here?  If not, I'll close this.

**Comment by richardgmcmahon** [comment]
OK, closing this for now; I might return to it, thanks

**Pull request closed without merging**
