### PR TITLE
attempt to fix issue 11780

### PR DESCRIPTION
**Pull request by keflavich**
See Issue #11780 

This is a very simple attempt to fix the bug introduced in https://github.com/astropy/astropy/commit/e541cef2cffbd4d18b02847d6d1418b3b9d86d98 in which `in_observer_velocity_frame` is not defined.  I'm not 100% sure this is the right method to use.  I am also not sure what tests are needed and why the original bug (assuming it is a bug) wasn't covered.

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! Does this completely fix #11780?

**Comment by keflavich** [comment]
I don't know!  I saw a user's failing test and tried what looked like the logical fix, but I can't reproduce the error myself directly - I'm just pretty certain that, unless there is some auto-generated code I can't find, this _is_ a real bug and the issue is simply that the wrong method name was used.

**Comment by keflavich** [comment]
(to clarify: it's not that I can't reproduce the error, but that I haven't tried to - that requires setup I haven't done)

**Comment by astrofrog** [comment]
This should be in v4.3 or v4.3.1 as it is a bug - I will try and write a regression test tomorrow.

**Comment by keflavich** [comment]
See also https://github.com/astropy/astropy/pull/11281

**Comment by astrofrog** [comment]
I am planning to push a commit with tests shortly

**Comment by astrofrog** [comment]
I've added a regression test and fixed a few more issues.

**Comment by astrofrog** [comment]
I have removed myself as a reviewer since I've now edited this PR but as far as I know this should be good to go and important enough to get into 4.3

**Review by mcara — APPROVED** [review]
LGTM based on my limited understanding.

**Review by eteq — APPROVED** [review]
If I'm remembering/understanding right, this was a re-naming-after-we-wrote it problem, so LGTM!

I'm going to go ahead and merge so I can backport it to v4.3 for rc

**Pull request merged**
