### PR TITLE
Some polynomial model refactoring (WIP?)

### PR DESCRIPTION
**Pull request by embray**
This is some work I've started on changing how polynomial models are implemented, so that they end up a little more like any other model.

Most models have a set of `Parameter` descriptors defined in their class bodies that specify the parameters that the model takes.  But for polynomial models the parameters (in this case the coefficients) always depended on the degree of the polynomial which could be arbitrary, and which was only specified when instantiating a polynomial model (e.g. `Polynomial1D(degree=3)`).

To make this work, the previous implementation defined a `__getattr__` method that generated the appropriate `Parameter` lookups.  This worked well enough, but it still made polynomials very different from other models.  It was also awkward to define other polynomial-like models (see for example the [`BSplineModel`](https://github.com/astropy/specutils/blob/master/specutils/models/BSplineModel.py) in specutils--to my knowledge this is the only implementation of a "polynomial-like" Model subclass outside the Astropy core.  It contains a bunch of boilerplate that had to be copied over from `PolynomialBase`, and various other awkward elements.  So a goal here was to try to make it a little? easier to define new classes of polynomial models.  I'm not _sure_ if this succeeds in that.  But it does make polynomial models more similar to other models.

The main difference this has over the previous implementation is that it no longer relies on `__getattr__` to supply the coefficient parameters.  Instead, when you instantiate a `Polynomial1D` (or any other subclass of `PolynomialBase`) it looks at the degree of the polynomial and creates a new subclass specifically for that degree and instantiates that instead.  For example `Polynomial1D(3)` returns an instance of a `Degree_3_Polynomial1D`.  This generated subclass is just like any other `Model` and has all the coefficients pre-defined at the class-level as `Parameter` descriptors.

The `PolynomialBase` class also has several methods that can be overridden by subclasses to control how the terms in the polynomial are enumerated and indexed, as well as how the coefficients to those terms are labeled.  With the exception of `coefficient_template` (which isn't even a method) these methods have underscore names, since they are not meant to be used directly.  But authors of `Model` subclasses may override them:
- [`coefficient_template`](https://github.com/embray/astropy/blob/246fdd679dea00ba72794c6aa347ae38fecd47d7/astropy/modeling/polynomial.py#L163) - This is just a string formatting template that is used to generate the coefficient names.  The arguments to the template are any indices used to label terms in the polynomial.  In the basic 1D case these are just the exponents 0, 1, 2, ... _d_.
- [`_get_degree_attrs`](https://github.com/embray/astropy/blob/246fdd679dea00ba72794c6aa347ae38fecd47d7/astropy/modeling/polynomial.py#L238) This just returns the names of attributes on the class that specify the degree of the polynomial.  In the generic case this is just `'degree'`.  However, if you look at [`OrthoPolynomialBase`](https://github.com/embray/astropy/blob/246fdd679dea00ba72794c6aa347ae38fecd47d7/astropy/modeling/polynomial.py#L728) in that case there are two "degrees" used to indicate terms--`x_degree` and `y_degree`.  I've thought of renaming this one to something a little more generic than "degree".  For example in the case of [`_SIP1D`](https://github.com/embray/astropy/blob/246fdd679dea00ba72794c6aa347ae38fecd47d7/astropy/modeling/polynomial.py#L1088) this also returns `coeff_prefix`.  Really these are any properties used to distinguish polynomials within a given class.
- [`_term_powers`](https://github.com/embray/astropy/blob/246fdd679dea00ba72794c6aa347ae38fecd47d7/astropy/modeling/polynomial.py#L251) - This actually enumerates the terms of the polynomial.  For a 3 degree 2D polynomial for example this lists `(0, 0), (1, 0), (0, 1), (1, 1), (2, 1), (1, 2)` corresponding to `1 + x + y + xy + x^2y + xy^2`.  As in `_get_degree_attrs`, the term "powers" here is used loosely.  In the basic case it does correspond to exponents, but it can really be any tuple of indices used to index terms of the polynomial.
- [`_coefficient_name`](https://github.com/embray/astropy/blob/246fdd679dea00ba72794c6aa347ae38fecd47d7/astropy/modeling/polynomial.py#L265) - Given a tuple returned from `_term_powers`, returns the name of the corresponding coefficient parameter.  In the base implementation this just passes them to `coefficient_template`, but this is allowed to be overridden entirely.
- [`_make_coefficient_parameter`](https://github.com/embray/astropy/blob/246fdd679dea00ba72794c6aa347ae38fecd47d7/astropy/modeling/polynomial.py#L280) - This actually returns an instance of `Parameter` for a given coefficient (given its name as returned by `_coefficient_name`, as well as the associated index tuple).  This is used when building the degree-specific subclass.  Usually there's no reason to override this, but it is there so that subclasses may override it if they want to do anything special with the parameters (provide default constraints, for example) that they would normally do by defining parameters in the class body, but that polynomial models don't allow.

An alternative to all this, which has been discussed before, is some kind of `ParameterSet` or `ParameterTemplate` that generates a sequence of parameters.  This might still be worth considering in the future.  But the approach here maintains backwards compatibility and solves some of the problems I had with dealing with the existing polynomial models.

### CODE REVIEW

**Comment by embray** [comment]
@wkerzendorf might be interested?

**Comment by embray** [comment]
I have a set of related changes on top of this that should also speed up evaluation of the `OrthoPolynomialBase` subclasses that use the modified multivariate Horner algorithm.

**Comment by embray** [comment]
Something's going awry with the appveyor builds.  I'll investigate more tomorrow.  Some of the tests are still failing on Python 2 due to `__repr__` changes that I think I'll try to reverse.

**Comment by wkerzendorf** [comment]
@embray thanks for taking care of this. I still can't subclass though:

```python
class myp(Legendre1D):
    pass

In [5]: myp(degree=5)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-4098cdbfbe5a> in <module>()
----> 1 myp(degree=5)

/Users/wkerzend/anaconda3/envs/extract/lib/python2.7/site-packages/astropy-1.1.dev13168-py2.7-macosx-10.5-x86_64.egg/astropy/modeling/core.py in __init__(self, degree, c0, c1, c2, c3, c4, c5, domain, window, fixed, tied, bounds, eqcons, ineqcons, n_models, model_set_axis, name, meta)
    378             new_init = make_function_with_signature(
    379                     __init__, args, kwargs, varargs=varargs,
--> 380                     varkwargs=varkwargs)
    381             update_wrapper(new_init, cls)
    382             cls.__init__ = new_init

/Users/wkerzend/anaconda3/envs/extract/lib/python2.7/site-packages/astropy-1.1.dev13168-py2.7-macosx-10.5-x86_64.egg/astropy/modeling/core.pyc in __init__(self, *params, **kwargs)
    371 
    372             def __init__(self, *params, **kwargs):
--> 373                 return super(cls, self).__init__(*params, **kwargs)
    374 
    375             args, kwargs, varargs, varkwargs = mcls._get_init_signature(

TypeError: __init__() got an unexpected keyword argument 'fixed'

```

**Comment by embray** [comment]
@wkerzendorf No, subclasses of *existing* concrete models aren't expected to work yet for reasons described in #4035 (having nothing to do specifically with polynomial models).  Instead, to create your own polynomial model you would subclass one of the abstract classes (basically the ones with no `evaluate` already defined) like `PolynomialBase`.

However, your example above looks like an outright bug.  That should have worked.

**Comment by wkerzendorf** [comment]
@embray tried to subclass from polynomialbase, but it doesn't like `degree`. 

Also, is there an easy way to fix the bug?

**Comment by embray** [comment]
Probably, I just haven't looked into it yet.  I don't know what you mean by "it doesn't like degree".

**Comment by wkerzendorf** [comment]
@embray there is no `__init__` in `PolynomialBase` that would take `degree`

**Comment by embray** [comment]
Yeah there is--if you subclass `PolynomialBase` it will require that the first argument to initialize the subclass is a degree.  That's what the `_get_degree_attrs` method mentioned in this PR is for.  However that alone won't work because you still have to implement an `evaluate`, etc.

**Comment by pllim** [comment]
Too many conflicts now.

**Pull request closed without merging**
