### PR TITLE
Adding custom CI skipping tags to contributing guideline

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by mhvk** [comment]
This looks very good! Merging...

**Comment by pllim** [comment]
So, this particular page is only accessible via GitHub file browser? I can't find this rendered on RTD.

**Comment by bsipocz** [comment]
Hmm, I'm not sure whether it's linked to anywhere. I was just grepping for previous mentions for ``[skip ci]``, and added the addition to the same place.

**Comment by pllim** [comment]
Seems a bit confusing to me there are so many places for "how to contribute" but that is out of topic here:

* This file.
* http://www.astropy.org/contribute.html
* http://astropy.readthedocs.io/en/latest/#contributing

**Comment by bsipocz** [comment]
And now #6155 adds a section into readme as well...

**Pull request merged**
