### PR TITLE
override Cosmolology new signature for Sphinx

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

Sphinx picks up on ``__new__(*args, **kwargs)`` so ``__init_subclas__`` now does ``cls.__new__.__signature__ = cls._init_signature``, which Sphinx can pick up on. The signature does not affect the operations of the actual class method.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by nstarman** [comment]
In many ways I wish ``make_function_with_signature`` used this code pattern, instead of mimicking ``getfullargspec``.  The ``inspect.Signature`` object allows for easy and exact control of an intended signature. There's no reason ``make_function_with_signature`` couldn't be extended to accept a parameter ``signature``, with edits under the hood to leverage the signature object. I could try sometime after v5.0 feature freeze...

**Comment by nstarman** [comment]
This PR is a little ugly in what is required to copy and modify a function, but it's functional and completely private, so should be uncontroversial.
I hope in v5.1 to eliminate the ``Cosmology.__new__``, which will also allow this PR to be undone.

**Comment by taldcroft** [comment]
@nstarman - this looks plausible, but I don't know enough of the details to really say. Can you provide examples that this is doing the intended fix? I.e. show some screenshots of before/after signatures in Sphinx and an IDE that were wrong before and now correct. Along with the existing unit tests, that would be enough for me to approve.

**Comment by taldcroft** [comment]
Never mind, I did this myself and I see the change from `...(*args, **kwargs)` to something useful. Nice!
image

**Review by taldcroft — APPROVED** [review]
Looks good, very clever!

**Pull request merged**
