### PR TITLE
CLN: cleanup an unused `tick_out` argument

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description

Randomly discovered by reading this class

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by astrofrog — COMMENTED** [review]
Thanks for spotting this! In fact, ``Ticks`` is not meant to be public API, at least not the initializer (that is, users should never have to call ``Ticks(...)``. Could you check if we actually make use of passing ``tick_out`` to the initializer, and if not, we can just remove it?

**Comment by neutrinoceros** [comment]
It looks like it's never used anywhere (phew), let's try dropping it then !

**Review by astrofrog — APPROVED** [review]

**Comment by astrofrog** [comment]
@pllim any idea why the changelog check is failing?

**Comment by neutrinoceros** [comment]
(might want to add a backport label if this is meant to go to version 6.1.4)

**Comment by pllim** [comment]
> changelog check is failing

It looks green to me.

That said, if you want to backport, it is technically a bug, right? So needs a change log?

But then again, this technically changes the function signature, so API change, do we really want to backport?

**Comment by neutrinoceros** [comment]
my two cents: the change is only internal, it *should* not affect downstream, so it doesn't seem worth backporting to me.

**Comment by pllim** [comment]
OK let's not backport then. Thanks!

**Pull request merged**
