### PR TITLE
Only upload artifacts for PRs

### PR DESCRIPTION
**Pull request by bsipocz**
Tiny optimization, situation is still far from ideal.

### CODE REVIEW

**Comment by bsipocz** [comment]
Cancelling all but the html CI build

**Comment by bsipocz** [comment]
The first half of this PR works, but can't test the second half before merging...

**Comment by Cadair** [comment]
I am going to borrow this... :grin:

**Comment by Cadair** [comment]
Actually, this isn't the upload step, it's just the step that prints the artifact path. The upload step is this: https://github.com/astropy/astropy/blob/master/.circleci/config.yml#L130

I think you might need a step before that which runs a bash script and deletes that dir, so there are no artifacts to upload.

**Comment by pllim** [comment]
So, how do we move forward from here? Merge this first and then look at #9432 or ...?

I don't do much CircleCI, so I would defer to others' expertise here.

**Comment by bsipocz** [comment]
Yes, I think we go ahead with the other PR instead, and once that is merged, we comment it out temporarily for this week.

**Comment by bsipocz** [comment]
Superseded by #9432

**Pull request closed without merging**
