### PR TITLE
MNT: Add CodeQL to catch security issues

### PR DESCRIPTION
**Pull request by pllim**
### Description

I am curious if CodeQL is useful for us. Once merged, it would report at https://github.com/astropy/astropy/security/code-scanning . Also see https://github.com/github/codeql

I am going to cancel Actions CI.

**TODO**

- [x] Squash commits if we decide to merge.
- [x] Remove temporary code to test in this PR.

### CODE REVIEW

**Comment by pllim** [comment]
Got it to run. Takes 10 minutes. Not very useful until merged.

**Comment by embray** [comment]
I'm a little confused about what this is doing.  Does "cpp" language support include C?  Also it doesn't look like it ran any analysis on the Python code.

I've encountered a few corner cases with CodeQL on Python before, but mostly just in unusual stuff with metaclasses.

**Comment by pllim** [comment]
As for how useful this really is for this package, I can't say. I just thought maybe it doesn't hurt to include anyway for best practices, but if there are objections, I am okay with closing this without merge too.

> Does "cpp" language support include C?

I think so, given they lumped C and C++ together in this doc at https://codeql.github.com/codeql-query-help/cpp/ ?

**Comment by pllim** [comment]
I added the ability to skip/cancel CodeQL (also see #11168) given that its run time isn't insignificant.

**Comment by saimn** [comment]
I'm not sure how useful this would be for something like astropy. But if there is no way to see before merging in master, maybe the best is to try ?

**Comment by pllim** [comment]
> way to see before merging in master

I enabled it on a fork. It actually found 34 things: https://github.com/kali-maa/astropy/security/code-scanning

**Comment by saimn** [comment]
@pllim - I get a 404 - Page not found with your link ?

**Comment by pllim** [comment]
I updated the YAML to only run this check weekly as cron job. I'll remove temporary code to test on this PR once I can prove to myself that it can still run.

**Comment by pllim** [comment]
As for the check results, I think GitHub lock down the results to people with write access to the repo. In the case of this unmerged PR, write access to my fork. But once merged, anyone with write access to `astropy/astropy` should be able to view the report, theoretically.

**Comment by pllim** [comment]
p.s. If you dig into the log, here is the [link to report](https://github.com/astropy/astropy/security/code-scanning?query=ref%3Arefs%2Fpull%2F11191%2Fmerge+tool%3ACodeQL) but not sure who can see it.

**Comment by pllim** [comment]
There are a few from `astropy/wcs` (not extern) if you squint a little. 😸

**Comment by embray** [comment]
> However it seems warnings concern only cfitsio and wcslib 

I was going to remark on this as well--they are all minor issues though it would be worth fixing, and maybe submitting the fixes upstream.

**Review by saimn — APPROVED** [review]
Looks good to me, running this once a week seems a good compromise :+1:

**Comment by pllim** [comment]
Thanks, all!

**Pull request merged**
