### PR TITLE
Fix ASDF tag versions in transform type classes

### PR DESCRIPTION
**Pull request by eslavich**
### Description

This pull request updates tag versions in the ASDF serializer classes that are lagging behind ASDF Standard 1.5.0.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
What milestone should this be in? Definitely needs a change log.

p.s. Aren't you taking them out completely?

**Comment by eslavich** [comment]
We are going to take them out in v5.0, but I thought this might be worth having in earlier versions?

**Comment by pllim** [comment]
> earlier versions?

Are you thinking 4.0.x or 4.3.x?

**Comment by eslavich** [comment]
I think of this as a bug, since it's causing ASDF to write out files with tag versions that don't match the ASDF Standard version declared at the top of the file.

**Comment by eslavich** [comment]
> Are you thinking 4.0.x or 4.3.x?

4.3.x only, I think -- 4.0.x seems to be best aligned with one of the older ASDF Standards, and there are a lot more version updates we'd have to make if we wanted to catch it up.

**Review by nden — APPROVED** [review]
lgtm

**Pull request merged**
