### PR TITLE
Support positive ufunc (new in numpy 1.13).

### PR DESCRIPTION
**Pull request by mhvk**
The title says it all.

EDIT: the travis failure for sphinx is unrelated.

### CODE REVIEW

**Comment by bsipocz** [comment]
This seems rather trivial, so I wonder whether we could merge this soon, to get the master build pass again?

**Comment by mhvk** [comment]
OK, I think this is indeed sufficiently trivial that I can just merge myself.

**Comment by mhvk** [comment]
@bsipocz - to fix the failure, you need https://github.com/astropy/astropy/pull/6090/commits/6dd66616655fd3f17a50eaf618ba75e07d1c3844

**Comment by mhvk** [comment]
which makes me wonder if I shouldn't just make that a separate PR, to fix the release candidate, while keeping -dev failing.

**Comment by mhvk** [comment]
@bsipocz - see #6116

**Comment by bsipocz** [comment]
Thank you. I haven't realized this is the same one we have on master.

**Pull request merged**
