### PR TITLE
MNT: Pin sphinx to avoid very slow doc build on RTD

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to see what is causing RTD doc build to take so long.

Also see readthedocs/readthedocs.org#7648 #10807 #10998

Note: Cancelled CI on purpose as I don't think they are needed.

### CODE REVIEW

**Comment by pllim** [comment]
@saimn , I don't see the timing. Is simply adding the extension not enough? Is there something else I need to do? The documentation is pretty bare. https://www.sphinx-doc.org/en/master/usage/extensions/duration.html

**Comment by saimn** [comment]
Yes, you just need to add the extension, but it doesn't seem to work on RTD (I noticed the same thing in #10795).

**Comment by saimn** [comment]
Also, having a look at the builds on RTD, I don't see what could have changed on Astropy side to explain the the build takes more than twice longer. 2 weeks ago sphinx-build was taking 500-600 seconds.

**Comment by pllim** [comment]
I guess I will have to diff the logs if we still have access to logs from 2 weeks ago. Perhaps a version bump somewhere upstream did some funky things.

**Comment by pllim** [comment]
I have my suspects...

| | Older log (faster) | New log (slower) |
| --- | --- | --- |
Build ID | [12228280](https://readthedocs.org/api/v2/build/12228280.txt) | [12305403](https://readthedocs.org/api/v2/build/12305403.txt) |
Build date | 2020-10-30 | 2020-11-10 |
sphinx-build duration (s) | 536 | 1345 |
Sphinx | 3.2.1 | 3.3.0 |
Matplotlib font message | -- | "Matplotlib is building the font cache; this may take a moment." |
cached-property | 1.5.2 | -- |
attrs | 20.2.0 | 20.3.0 |
kiwisolver | 1.2.0 | 1.3.1 |
numpy | 1.19.3 | 1.19.4 |
scipy | 1.5.3 | 1.5.4 |
sortedcontainers | 2.2.2 | 2.3.0 |
toml | 0.10.1 | 0.10.2 |

**Comment by pllim** [comment]
I think the culprit is Sphinx 3.3.0 (released 2020-11-02) but I don't know if this is Sphinx bug or our `sphinx-astropy` isn't playing well with new Sphinx release.

**Comment by pllim** [comment]
I wonder if I should open an issue over at Sphinx but I wouldn't know how to isolate the problem for them.

**Comment by bsipocz** [comment]
Hmm, even just reporting them this table and the logs might be useful enough for them. 

(I also wonder whether the mpl font building also has any effects, I recall it was an issue in the past?)

**Comment by pllim** [comment]
@bsipocz , font building seems to add about 30-ish seconds but definitely was not the cause.

**Review by saimn — APPROVED** [review]
Sounds good, thanks @pllim for the investigation ! 
I guess we could merge this soon ?

**Comment by pllim** [comment]
> I guess we could merge this soon ?

Yes, please!

**Pull request merged**
