### PR TITLE
Description and workaround of Spyder UMR conflict in known_issues

### PR DESCRIPTION
**Pull request by dhomeier**
Added a brief description of the issue and instructions for disabling `astropy` reloading to `known_issues.rst`.

### CODE REVIEW

**Comment by pllim** [comment]
Thank you for the contribution! Since this is specifically addressing Python 2 but Python 2 is no longer supported in 3.x and `master`, maybe this is better off as a PR against v2.0.x branch. What do you think, @bsipocz ?

**Comment by bsipocz** [comment]
@pllim - I agree that this shouldn't go into master. 
And looking at the current content of the known issues, I feel that this doesn't belong there either but in the Spyder documentation.

**Comment by pllim** [comment]
@bsipocz , okay then, let's see what Spyder devs say over at spyder-ide/spyder#6962 :crossed_fingers:

**Comment by pllim** [comment]
Looking at spyder-ide/spyder#6962, it seems that this is being addressed over there, so I am closing this without merge. I apologize for the extra work here, @dhomeier !

**Comment by dhomeier** [comment]
Thanks for moving the forward to the Spyder devs, @pllim, I think the proposed fix should take care of this for future Spyder releases.
I can't quite follow how this does not qualify as a `know_issue` though -

- It is an incompatibility raising an `AttributeError` in `logger.py`, making it likely IMO that people will turn to the Astropy docs for advice.

- It seems to me other issues cover quite similar incompatibilities e.g. with various IPython versions - including `ipython < 0.13.2`, which is not supported beyond Python 3.3(!).

As long as #7363 turns up in a general search for the exception, maybe that's enough, though the instructions for the workaround there could be clearer...

**Pull request closed without merging**
