### PR TITLE
Refactor time to a few less monstrously big files

### PR DESCRIPTION
**Pull request by mhvk**
In #3224, @taldcroft wondered:
> Slightly OT, I wonder if it would be possible to factor things out so we don't just have a monster core.py file.

And I agreed, with the following suggestion:
> I think we could have the different time formats separately (`formats.py`?) and move the double-precision routines to an `utils.py` or so. That would leave just the top-level `Time` and `TimeDelta` classes, plus stuff related to time scales.

### CODE REVIEW

**Comment by mhvk** [comment]
@taldcroft - back from holidays and thought I'd get this out of the way. In part, this is a prelude to trying to split off the ndarray-like methods in a mixin class, as suggested by @embray in #4096.

**Comment by mhvk** [comment]
Note that while `utils.py` is clean, the new `formats.py` now needs quite a few inline imports from `.core` (to prevent circular imports). I tried going the other way around, but ended up feeling that local imports in `Time` and `TimeDelta` themselves were uglier.

**Comment by embray** [comment]
Heh, I was just about to comment on that.  We can probably leave the in-line imports as is for now, but I'd be curious to see if they have any impact, for example, on the performance of formatting large lists of times.

**Comment by taldcroft** [comment]
Splitting out the formats into `formats.py` is always how I imagined this would be done.
 
I'm not sure if it's a real win, but in theory one could inject the `Time` class into the `_time` format object either by a new `__init__` kwarg.  That would reduce some of the inline imports.  Or alternatively I wonder if it is bad form / confusing to inject `Time` into the `formats.py` module after import:
```
class Time(object):
    ...

from . import formats
formats.Time = Time
del formats
```
To prevent my editor from complaining, and also for clarity, one might put the following into `formats.py`:
```
# Time gets set to the Time class reference by core.py after Time is defined.
# This is done to avoid circular and inline imports.
Time = None
```

**Comment by embray** [comment]
> Or alternatively I wonder if it is bad form / confusing to inject Time into the formats.py module after import:

You can do exactly this by putting imports at the end of a module.  Just write:
```
from .core import Time
```
but place it at the end of the module, and you'll be fine.

**Comment by embray** [comment]
I wonder if [`_get_time_fmt`](https://github.com/mhvk/astropy/blob/time-refactor2/astropy/time/core.py#L261) shouldn't also be moved out of astropy.time.core, and can just be made into some kind of factory function for time formats (the new factory function would need to take precision as well as in/out subformats as arguments as well)

**Comment by taldcroft** [comment]
> I wonder if _get_time_fmt shouldn't also be moved out of astropy.time.core, and can just be made into some kind of factory function for time formats ...

Maybe it's best to limit this PR to just shuffling things around.

**Comment by mhvk** [comment]
@taldcroft, @embray - does either of you understand the failure in the sphinx build? (just after "writing output"). The claim is that a reference to `astropy.time.formats.TimeUnique` cannot be found. Now `TimeUnique` is not in `__all__` there, but before it wasn't exported either...

**Comment by embray** [comment]
This must be some sort of automodapi issue.  To this day I'm confused as to exactly how it goes about resolving references like that.

Maybe I can try debugging later.  Best to try building the docs locally, with the setting enabled (I forget what it is off the top of my head) to save the outputs from automodapi so we can inspect them.

**Comment by mhvk** [comment]
I looked again, and figured it was almost certainly an oversight not to export `TimeUnique` in the first place (correct, @taldcroft?), so I now just include it in `__all__`; this solves the sphinx problems...

**Comment by mhvk** [comment]
@taldcroft - I also added a missed change in `Time.__getitem__` (which should use `_replicate`). I realise it is not strictly relevant for this PR, but couldn't bother making a new one... (I'll remove it from #3922, where it made no sense whatsoever).

**Comment by taldcroft** [comment]
Assuming that tests pass this looks good to me.  Thanks!

**Comment by mhvk** [comment]
> Assuming that tests pass this looks good to me. Thanks!

OK, tests passed, so I'll merge.

**Pull request merged**
