### PR TITLE
Doc improvements related to masked tables

### PR DESCRIPTION
**Pull request by taldcroft**
In response to #4061.

### CODE REVIEW

**Comment by mhvk** [comment]
@richardgmcmahon - could you have a look, and see whether you think this would have put you on the right track?

**Comment by richardgmcmahon** [comment]
Tt would be useful to a person like me, to have an example of how to get the row number of the 
masked cell. This is due to my non-boolean way of thinking. I am still learning about masks.

**Comment by taldcroft** [comment]
@richardgmcmahon - to get the row numbers you would do `np.where(t['a'].mask)[0]`.  The trailing `[0]` because `np.where` returns a tuple where the first element is the row numbers.  I'll put this in.

**Comment by mhvk** [comment]
@taldcroft - back from holidays, I looked at stuff assigned to me while i was away: this PR looks good, but the appveyor error looks real. I'm puzzled that it didn't turn up in travis, though... Maybe it is another one of those 32 vs 64 bit issues.

**Comment by taldcroft** [comment]
@mhvk - likely related to the default integer in Windows being 32 bit.  Or something like that.  I just skipped the doc test.

**Comment by mhvk** [comment]
OK, makes sense.

**Pull request merged**
