### PR TITLE
Remove fractions compatibility layer since we now no longer support Python 2.6

### PR DESCRIPTION
**Pull request by astrofrog**

### CODE REVIEW

**Comment by mhvk** [comment]
@astrofrog - this looks good, except that you missed the documentation -- see
`docs/units/combining_and_defining.rst` (I think `OrderedDict` is fine in this respect).

**Comment by astrofrog** [comment]
@mhvk - ah yes, good catch - thanks! (this was also the case for argparse)

**Comment by mhvk** [comment]
Looks all OK, so merging.

**Comment by embray** [comment]
:dancers:

**Pull request merged**
