### PR TITLE
Added Docker integration for Dev Container

### PR DESCRIPTION
**Pull request by JaydenB0**
### Description

This pull request is to address the lack of docker integration and this commit allows developers to set up a development environment in VSCode quickly.

### CODE REVIEW

**Comment by pllim** [comment]
Hello and thank you for your interest in contributing! Unfortunately, this PR is out of scope for the core library, as it opens up a can of worms of what other configs we should store if we accept this (e.g., Dockerfile for other dev environments, `.emacs`, AWS config, etc). This would introduce a path to extra maintenance burden on top of the core maintainers, who are already stretched very thin. 

However, I wonder if a new section in dev docs about using Docker is a good alternative. cc @astrofrog @saimn @astropy/devops-maintainers

**Comment by JaydenB0** [comment]
Hey! Glad to be contributing to an amazing project like this (this is actually my first contribution to an open source library). I agree with your concerns regarding the possibility of new configs. Should I push a commit for the docs adding a section regarding how to set up a dev container with Docker using the provided code instead?

**Comment by pllim** [comment]
@JaydenB0 , let's wait a bit and see what other core maintainers think. Given the holiday season followed by American Astronomical Society meeting thereafter, this might take a while. Thank you for your patience!

**Comment by embray** [comment]
I'm not so sure.  The problem with putting things like this in the documentation is it tends to fall out of date before long if no one is paying attention, and we don't even have a particular section in the docs for setting up different development environments (i.e. different IDEs) perhaps in part for this reason.  It is kept fairly generic.

Furthermore, there doesn't seem to be much in this configuration that is particularly unique to Astropy; if there was some particular challenge, e.g., to creating a Docker image that can build and run Astropy that might be a little different.

However, I wouldn't object to creating a wiki page for things like this.

**Comment by JaydenB0** [comment]
@embray I like your suggestion of a wiki page and I think a section for using Docker would be suitable under the ["For Developers"](https://github.com/astropy/astropy/wiki#for-developers) section. However, I think an addition to the [virtual environments section](https://docs.astropy.org/en/stable/development/workflow/virtual_pythons.html#virtual-envs) of the documentation might seem more appropriate as the Dockerfile essentially creates a virtual environment under Docker. Regarding different configurations, getting rid of the .devcontainer file in this commit will keep it generic for most IDEs. What are your thoughts on placing information about the Dockerfile in the virtual environment section?

**Comment by pllim** [comment]
Ops, sorry for the double bot post. Hopefully I fixed the bug upstream.

**Comment by pllim** [comment]
I think the decision is to document this in Wiki instead of commiting a docker file.

**Pull request closed without merging**
