### PR TITLE
Install dependencies via setup tools. 

### PR DESCRIPTION
**Pull request by cmccully**
This change would automatically install dependencies specified by the install_requires and tests_require via setuptools. This implements to astropy/astropy-helpers#212

### CODE REVIEW

**Comment by embray** [comment]
I think this should be made more clear (particularly in the changelog message).  This would install runtime + test dependencies *specifically* when running the `./setup.py test` command.

Other than the nitpick about how this is documented, I think this is probably fine.

**Comment by cmccully** [comment]
Thanks @embray. Does this look better? Should we print a warning to the user when they run setup.py test? I might suggest not, but this is the behavior that I would expect when I run setup.py test so I am open to suggestion.

**Comment by mhvk** [comment]
I'm trying to understand whether this might be annoying along the lines of @eteq's https://github.com/astropy/astropy-helpers/issues/212#issuecomment-194962675 -- does astropy actually require anything for testing, or would this (at present) only download possible installation dependencies?

**Comment by cmccully** [comment]
I don't believe it should be annoying. I cannot imagine a use case when someone would not want to run python setup.py install, but only wants to run setup.py test. My thought is that to actually run the unit tests in the code, the installation dependencies are often necessary, if nothing more than to have all of the import statements in the code not throw errors. So very likely even if the tests don't require any external dependencies, one would need to run python setup.py install before running python setup.py test. This would remove the need to run python setup.py install. This would be nice when running things like travis. The travis.yml wouldn't necessarily need to have all of the external dependencies (which it currently does), removing duplication. The extra added functionality is that we now implement the tests_require keyword in setup.py. Sometimes tests require extra dependencies, e.g. mock. astropy/astroscrappy, for example, requires scipy to crosscheck results in the tests, but is not needed for the rest of the code. That is a large dependency that I don't want to include in the installation. However, if you were to run python setup.py test currently, it would crash saying no module named scipy. Then one would have to go back to the docs and look at what is required for testing and install the deps by hand. This circumvents this and installs everything that is necessary automatically. This mimics the default behavior of setuptools (which is actually where these lines were derived).

**Comment by mhvk** [comment]
@cmccully - It does makes sense to me to install everything that one needs to run astropy and to do the basic test suite, but less so to also install, e.g., `scipy`, which is explicitly not a dependency of `astropy`.

Anyway, as I understand this PR, the only thing it enables currently is (1) that installation requirements are automatically installed also for tests; and (2) that it will become possible to give an additional list of packages required for testing. It does not actually decide on what should be in that list.  Is that correct? If so, I'm all in favour.

Following up on this, I'm not in favour of including all packages possibly used in tests by default, but it would be nice to have the option of doing so (say, a `complete_tests_requires` and use that in `travis`).

**Comment by cmccully** [comment]
@mhvk Ah. I think I understand the issue. A key point is that this change does not only affect astropy itself. Anything that uses astropy_helpers and the package-template use this same code because it overrides the setuptools testing suite to use py.test. At some point, it might make sense to refactor this whole module into astropy-helpers to emphasize this, but that is beyond the scope of this current PR.

I am not advocating installing extra dependencies. In the setup.cfg file in astropy/package-template you can include a list under tests_require that is package specific. This PR doesn't put anything into that list by default. 

I'm not sure I follow your last comment. The tests_require list would include all deps needed to run
python setup.py test. Under this PR, the test requirements are only installed if the user tries to run the test suite, in which case I would expect that all of the testing deps are necessary. I'm not sure when you would not include dependencies that are required for testing when you are running the test suite explicitly. Can you give me an example use case that illustrates your concern?

**Comment by mhvk** [comment]
@cmccully - OK, agreed on its use.

On the last comment: as it is, by default `./setup.py test` does *not* run all the tests: e.g., all tests marked with `remote_data` are skipped unless I explicitly enable them by passing on `--remote-data`. Similarly, tests of code requiring `scipy` or `matplotlib` are skipped if I do not have those packages installed. Indeed, this holds for all packages but `numpy`, since only `numpy` is a strict dependency of astropy. 

Anyway, if I understand correctly how the future would look like, for `astropy` proper we'd have an empty `test_requires` (since `numpy` is already listed elsewhere). The remaining question [outside of scope of present PR] then would be whether it would be useful to define another flag one could pass on (say, `--optional-dependencies`), which would add to `test_requires` all the other packages that are at times used in `astropy`.

**Comment by cmccully** [comment]
Ah. That makes sense @mhvk. Based on that, I would agree that the tests_require for astropy should currently be empty. Perhaps something like the "extras_require" keyword would be useful for that. @embray would something like the functionality of "extras_require" be useful for the case described by @mhvk? That could be a separate PR.

**Comment by mhvk** [comment]
OK, good!  But I'll leave merging this to @embray or someone else who understands the process well enough: @bsipocz, @astrofrog?

**Comment by astrofrog** [comment]
This looks good to me!

**Pull request merged**
