### PR TITLE
Whatsnew static figures

### PR DESCRIPTION
**Pull request by bsipocz**
See discussion in #9268

### CODE REVIEW

**Comment by MSeifert04** [comment]
Just out of interest: Why are we keeping the old "What's new" entries?

**Comment by bsipocz** [comment]
> Why are we keeping the old "What's new" entries?

I'm not sure, but one good reason coming to my mind is to keep the links in the release announcements working.

**Comment by pllim** [comment]
Adding static PNGs does increase the repo size. :thinking:

**Comment by bsipocz** [comment]
Yes, and also obscure regarding the source code for such images.

What about linking to these images in the main docs instead? Or not having images in the what's new at all?

**Comment by pllim** [comment]
If we were to keep the old what's new, personally, I would prefer for the plots to be in main doc, yes. But that's just my personal opinion.

**Comment by bsipocz** [comment]
OK, so now the consensus with @pllim is that we keep the changes as this PR does, but without the images:
 - the plot directive is some of the cases provides the source code, these are now moved to the what's new pages, but
 - the images are not rendered, nor included.

I feel this is a nice compromise for neither bloating up the codebase with png files, that are kind of black boxes as their source code is not provided, nor having to render plots with sometimes outdated API. 

For doing forward, we can have images (rendered from source code) in what's new for better advertizement for the new features, but they will be removed when they are not for the very latest release. I don't think it should need to go in the release procedure (that procedure is basically for the release coordinator, while this is for all maintainers who write the what's new), but an e-mail to astropy-dev wouldn't hurt.

What do you think @mhvk (or anyone else having an interest in this question)?

**Comment by MSeifert04** [comment]
> one good reason coming to my mind is to keep the links in the release announcements working.

Well, just add a link from the "What's new" page in stable/dev to the "What's new" page in the according RTD version. With a note that they are attempting to view an outdated entry because there have been releases in between...

E.g. https://docs.astropy.org/en/v3.2.1/whatsnew/3.2.html for What's new 3.2, https://docs.astropy.org/en/v3.1.2/whatsnew/3.1.html for 3.1, ...

Everything in these pages **should** be covered in more detail in the narrative docs or docstrings, so it's just duplicated maintenance burden, isn't it?

**Comment by bsipocz** [comment]
> Well, just add a link from the "What's new" page in stable/dev to the "What's new" page in the according RTD version

Hmm, I very much like this idea. This would mean our docs is not self contained, but frankly it already has thousands of external links, so I feel it's very reasonable to do this.

**Comment by mhvk** [comment]
:+1: to reducing repo size and to making life easier...

**Comment by bsipocz** [comment]
OK, so how does this look like now?

(there are only two tricky versions, 3.1 and 0.1. The latter didn't seem to have a rendered docs available any more, so I linked to the what's new in 0.2, and for 3.1 the docs doesn't build any more on RTD, so the link points to 3.1.2, but I think that's OK for now.).

**Comment by bsipocz** [comment]
(added bonus that this change should cut back a little bit on the total build time of the docs, too).

**Comment by pllim** [comment]
`+19 −3,215` !!! Me likey.

**Comment by bsipocz** [comment]
32bit (it doesn't matter here, but I haven't see this status before): 
Screen Shot 2019-09-23 at 19 41 00

**Comment by pllim** [comment]
LoL... "circle bug"... wut?

**Comment by bsipocz** [comment]
The only point where I diverted from @MSeifert04's excellent idea that I kept the very latest what's new as is (now the 4.0). Once the branching/release is done, it can be also moved to be a link.

As a side effect, now there is an empty line between that version and the rest, what I see as a feature, but if needed can try to dig up some sphinx magic to remove it.

**Comment by bsipocz** [comment]
> LoL... "circle bug"... wut?

The weird thing is that the job is running. So 🤷‍♀

**Comment by MSeifert04** [comment]
Very nice.

It's a bit different from what I thought. I thought we keep the rst files and replace their content with a link (and optional a note that it may be outdated). Otherwise the link in the announcement mails (e.g. https://groups.google.com/forum/#!topic/astropy-dev/lMSQVlf-ZOQ) won't work because it explicitly references the resulting HTML: `.../stable/whatsnew/3.2.html`.

**Comment by MSeifert04** [comment]
I wonder if this change should be discussed with the coordination committee?

**Comment by bsipocz** [comment]
ouch. Now I'm angry at our past selves to use the `stable` link rather than being explicit. It was too good to be working...

**Comment by MSeifert04** [comment]
> I'm angry at our past selves

Guess that's what past selves are for 😄 

> use the stable link rather than being explicit

If we had used the explicit link then the whole problem would be moot because (almost) no one would've visited the (outdated) what's new pages on stable/dev anyway?!

**Comment by bsipocz** [comment]
> I wonder if this change should be discussed with the coordination committee?

@astropy/coordinators do you have opinions about the what's new pages?

**Comment by pllim** [comment]
Do we even care about past email announcements?

**Comment by bsipocz** [comment]
🙈

**Comment by bsipocz** [comment]
OK, so I've amended this now so that the versioned pages remain to keep the links alive, while the content is still removed. I consider this horse beaten long enough already, so merge away if you're happy with it.

**Comment by astrofrog** [comment]
I think it'd be good to get approval from @eteq, @taldcroft, or @kelle  on this too, to have another CoCo vote :)

**Comment by pllim** [comment]
Four approvals! ✔️

**Pull request merged**
