### PR TITLE
Increase auto_max_age from 30 to 300

### LINKED ISSUE #14756: Consider making iers.Conf.auto_max_age longer and bunding IERS-A with astropy
### What is the problem this feature will solve?

Users and other institutional users report continued problems related to attempted auto-downloads of the IERS-A file for doing calculations that require these data (e.g. predictive UT1 time calculations). The upstream site(s) are still not as reliable as we would like.

### Describe the desired outcome

One proposal we converged on during a breakout session at the Astropy Coordination meeting 2023 is two-fold:

- Bundle the IERS-A file with the astropy release.
  - For consideration: update with bug-fix releases as well as minor (6-month) feature releases.
  - Question: bundle this and the IERS-B as gzipped files and unzip to cache? These files compress by a factor of 5 or more,
- Change `utils.iers.Conf.auto_max_age` to a value around 300 days (TBR).
  - This ensures that if a user stays up to date with the latest astropy release then they never need to download IERS-A.

This does change the promised accuracy of astropy with regards to time/coordinates that depend on predictive IERS-A values. Instead of the IERS-A always being recent to within 30 days, it might be as much as 300 days.

cc: @eteq @tepickering @weaverba137 @mhvk @tomdonaldson 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to increase the default value of `auto_max_age` from 30 days to 300 days. The main goal is to reduce network hit from IERS related lookups.

I cannot tell if this needs updating (I did not touch it in the initial commit):

https://github.com/astropy/astropy/blob/e27b22432d1582f20dc15135afb116e5b3a1a165/astropy/utils/iers/iers.py#L1130

Fixes #14756 

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by mhvk** [comment]
I worry about 300 days being too long - see comment in #14756.

You are right that the line for the leap-second file has to be changed. With a value larger than 180, the code will assume that even leap second files that are expired are "good enough"  -- and then give a warning because the file is expired at the end. Offsets smaller than 0 should definitely not be allowed.

**Comment by pllim** [comment]
From the new discussions in https://github.com/astropy/astropy/issues/14756 , sounds like I should just close this without merge while you all debate somemore?

**Comment by pllim** [comment]
> I think the people bothered by the short update time should find a solution

The people who are bothered are the service providers, unfortunately. Users can opt to turn download off (we have a whole section of doc dedicated to that) but providers cannot control who requests their files.

**Comment by pllim** [comment]
I also proposed this but was rejected:

* https://github.com/astropy/astropy/issues/15248

**Comment by pllim** [comment]
Anyway, let's move the discussion back to the original issue. Thanks!

**Pull request closed without merging**
