### PR TITLE
DOC: Update convolution narrative docs

### PR DESCRIPTION
**Pull request by larrybradley**
### Description

The convolution narrative docs are outdated.  In particular scipy.ndimage convolve does support
N-D convolutions and has many options for treating edges.

This PR also make some other improvements and fixes, including the plot labels and legends, and removing unnecessary display of code

### CODE REVIEW

**Comment by keflavich** [comment]
I'll need to have a closer look by running the code.  Could you drop in an image?  does it look the same as in the current docs?

**Comment by larrybradley** [comment]
The rendered docs from this PR are here:  https://astropy--14616.org.readthedocs.build/en/14616/convolution/index.html

**Comment by pllim** [comment]
@keflavich , are you able to review this by feature freeze?

**Review by keflavich — COMMENTED** [review]
Looks good.  For consistency, though, maybe the other code examples below should also be changed from `:include-source:` to `:show-source-link`?

**Comment by larrybradley** [comment]
I updated the other plots on that page to use `:show-source-link`.  I also just fixed the first example description of the default boundary behavior and updated the line colors of the second figure.

**Comment by pllim** [comment]
We're having problem with RTD: https://github.com/readthedocs/readthedocs.org/issues/10256

😿

**Review by keflavich — APPROVED** [review]

**Comment by pllim** [comment]
I restarted the RTD build. 🤞

**Comment by larrybradley** [comment]
RTD passed.  :tada:

**Pull request merged**
