### PR TITLE
Deprecate setting and getting pixels in a WCSAxes Spine

### PR DESCRIPTION
**Pull request by dstansby**
### Description
When using Matplotlib, it is generally only safe to calculate pixel coordinates of artists at draw time, as that is when the figure DPI is set in stone. Calculating the pixel coordinates before drawing can lead to issues like https://github.com/astropy/astropy/issues/12568.

This PR fixes this issue for `WCSAxes` `Spine`s by ensuring that pixel calculations are done at draw time. It also deprecates getting and setting pixel coordinates.

This pull request is to partly address https://github.com/astropy/astropy/issues/12568. Before that issue can be fully resolved I think there is also a fix required on the Matplotlib side.

Fixes #<Issue Number>

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Why half the change log entries point to #12630 ?

**Comment by saimn** [comment]
Moving the milestone to 5.2 since it seems more work is needed (and there are some conflicts).

**Comment by dstansby** [comment]
> Why half the change log entries point to #12630 ?

Sorry, this depends on #12630, which I've just rebased and taken out of draft. I'll stick this PR in draft until that one is sorted.

**Comment by pllim** [comment]
If you rebase anyway, it will give you a bit more time before the bot complains again. FYI.

**Pull request closed without merging**
