### PR TITLE
Add log_a as an argument to simple_norm

### PR DESCRIPTION
**Pull request by tcjansen**
Addresses issue #8432

### CODE REVIEW

**Comment by bsipocz** [comment]
There has been a PR (https://github.com/astropy/astropy/pull/8436) opened to address this issue already that is basically ready to be merged but held up with some unrelated issues.

**Comment by eteq** [comment]
(sorry I think my comment above collided with @bsipocz's, hence the feedback at the same time as the duplicate tag)

**Comment by tcjansen** [comment]
> There has been a PR (#8436) opened to address this issue already that is basically ready to be merged but held up with some unrelated issues.

Yeah that's my mistake, I didn't see that a PR was already made on this issue. I don't mind if you go ahead with the previous PR since it looks like quite a bit of work has gone into it, but I do want to follow up with my PR just to show that I can, since I am applying for a GSoC position :) .

**Comment by bsipocz** [comment]
@tcjansen - If the whole purpose is GSoC, then we rather you pick another issue to address as there is nothing to show here (the other PR started with the exact same content).

**Pull request closed without merging**
