### PR TITLE
Clean up local sites json

### PR DESCRIPTION
**Pull request by bsipocz**
This may be controversial, so @eteq if you don't like it, please close without merging.
As per your comment in https://github.com/astropy/astropy/pull/4042#issuecomment-145677709 the local copy is just for demonstration purposes. However it's still a bit weird that it contains small observatories, even already closed ones while a few big ones with 8m class telescopes are missing.

So in this PR I've cleaned up the local version added a few super big ones, and only kept the 20 most significant obs in here (with a still operating preferably ~4m meter class telescope). 
(There'll be a sibling PR to astropy-data, but I just realized I did the modifications in a cloned astropy version rather on a fork, so it may take some time to iron it out.)

### CODE REVIEW

**Comment by bsipocz** [comment]
@eteq, @astrofrog - Can this get into 1.1? So only the cleaned up built-in list gets released?

**Comment by astrofrog** [comment]
I'm milestoning it as 1.1 to make sure someone familiar with coordinates checks whether we should merge it before 1.1 is released.

**Comment by eteq** [comment]
@bsipocz - I'm going to close this in favor of the solution in #4321, but we'll definitely want astropy/astropy-data#7, which will then be more "real" post-#4321

**Comment by bsipocz** [comment]
:+1:

**Pull request closed without merging**
