### PR TITLE
Test astropy-helpers v0.4.8 release against astropy

### PR DESCRIPTION
**Pull request by embray**
No milestone for this unless later there is a need to release a new v0.4.x version for Astropy.

### CODE REVIEW

**Comment by embray** [comment]
*sigh* apparently the import of matplotlib causes havoc in the docs build :\

**Comment by embray** [comment]
Updated to a new version that I think might work around the docs build issue.

**Comment by embray** [comment]
*sigh* nope, somehow that didn't fix it.  I'll probably have to wait 'til Monday to resolve this.

**Comment by embray** [comment]
Giving this yet another try, finally  I took a look at the plot directive sphinxext to see what it does.  Seems like just setting `matplotlib.use('Agg')` should get around this.  I don't see any reason any package should want to use any other matplotlib backend during *installation*.  @mdboom ?

**Comment by astrofrog** [comment]
@embray - just out of curiosity, what was the error before?

**Comment by embray** [comment]
Trying to import matplotlib (or probably more specifically matplotlibpyplot) was causing the documentation build to blow up since it was trying to use the Qt backend :(

**Comment by mdboom** [comment]
Yes -- forcibly setting the Agg backend during installation seems fine.

**Comment by embray** [comment]
This is all just to get around matplotlib/matplotlib#4165.  Fortunately this is an obscure case.  It sucks but I don't see any other way right now (and fortunately ISTM importing matplotlib doesn't really add much overhead).

**Comment by embray** [comment]
*whew* Well that seems to have done the trick.  I can release this and v1.0.1 later today.

**Comment by embray** [comment]
Oops. I just realized this failed to include the ah_boostrap script which was somewhat important in this case.  I will just make a new PR :(

**Pull request merged**
