### PR TITLE
fits convenience functions close open file objects

### PR DESCRIPTION
**Pull request by embray**
This is actually a pretty bad bug, but I marked it "Priority-low" since I don't think it's come up much before.  I feel like I've heard of this bug before actually, but I couldn't find an open ticket for it.

The issue is that the "convenience" functions in `astropy.io.fits` like `getheader`, `getdata`, and the like, when passed an *open* file object they close that file object when they're done with it.  They should not be assuming that it's safe for them to close the given file object (that's kind of the point of passing around file objects).

By contrast, when passed a filename, they open the file and then close it when they're done with it, correctly.  This is probably the far more common use case which is why this hasn't come up before.

### CODE REVIEW

**Comment by embray** [comment]
@astrofrog This is really a regression so I think if it's merged before the next release it can be marked "Affects-dev" and won't need a changelog entry.  Otherwise I'll have to add that later.

**Comment by embray** [comment]
If it holds up the release feel free to change.

**Comment by saimn** [comment]
@embray - But here you are not closing files when a filename is passed, which was the purpose of #4786. So the test added in #4786 should fail.
Before, both filename and fileobj were not closed, and after both are closed, so we need to close only for filenames.

**Comment by embray** [comment]
Hm, well it looks like I re-broke the regression test of #4786 (I should have tested this on Python 3).  Will need a closer look...

**Comment by embray** [comment]
Oops, I forgot to include the actual change to `fileobj_closed` to the commit.  I'll do that and rebase.

**Comment by astrofrog** [comment]
@embray - it looks like you included an unrelated commit?

**Comment by astrofrog** [comment]
@embray - #4786 was included in 1.0.10 (just released yesterday) so I think you need to milestone this as 1.0.11 and add a changelog entry there.

**Comment by embray** [comment]
That's tricky then...this should be merged into master (so it will be 'fixed' in 1.2) but this will still have to be backported to 1.0.11?  And what about 1.1.x?  Or is that not getting new patch releases due to not being LTS?

**Comment by astrofrog** [comment]
@embray - we've already branched 1.2.x so it will need to be backported to 1.2.x and 1.0.x, and we are not doing any more 1.1.x releases.

**Comment by embray** [comment]
@astrofrog Once the tests pass then you can merge this one as is and backport to the 1.2.x branch.  Then I'll backport it to 1.0.x with a changelog entry.

**Comment by astrofrog** [comment]
@embray - there's a small PEP8 issue, can you fix it and commit with ``[ci skip]``?

**Comment by eteq** [comment]
I went ahead and fixed the PEP8 issue, as all the other tests are passing.  This seems to include a commit from #5035, too, though, so I rebased to remove that and then merged into master in 8d1faddc543404854d8a23cd99653ce4ff0ded14.  Because of the rebase github isn't recognizing it as a "merge", so I'm closing this, but I promise it did actually get merged.

**Comment by eteq** [comment]
backported to v1.2.x in ce2a8a8ff1825b0b1986110ea5553f1e8782740e and backported to v1.0.x (with an added changelog entry) in df14071f232df9c398ab119e084f8aff99167ced

**Comment by embray** [comment]
Not sure how the other commit got in there--this was based on the latest master.  Anyways thanks for taking care of it.

**Pull request closed without merging**
