### PR TITLE
Finalizing changelog for v6.1.7

### PR DESCRIPTION
**Pull request by astrofrog**
- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by saimn — APPROVED** [review]

**Comment by pllim** [comment]
@meeseeksdev backport to main

**Comment by pllim** [comment]
Hmm I guess not.

**Comment by saimn** [comment]
7.0.0 was already backported so there must be a conflict with the deleted file. But would be great to backport so v6.1.7 appears in the changelog for future versions.

**Comment by pllim** [comment]
> would be great to backport

How?

**Comment by pllim** [comment]
I think you might have to manually copy paste the rendered section from CHANGES directly.

**Comment by saimn** [comment]
I cherry-picked the commit on main (93b6e8fc72) and v7.0.x (874fc6e5c5).

**Pull request merged**
