### PR TITLE
Adjust example headings in NDData

### PR DESCRIPTION
**Pull request by lglattly**
### Description

This pull request is to adjust the hierarchy of some example headings I previously added to the nddata sub-package as part of the example gallery project in PR #9312 . Some of the example headings were the same hierarchy as the section headings they were under, which looked odd rendered, so I've changed them to the next level down.

### CODE REVIEW

**Comment by bsipocz** [comment]
@lglattly - could you squash the commits together? No need to keep separate ones on the file level.

**Comment by bsipocz** [comment]
This is a very straightforward improvement, so I take the liberty and merge this now.

**Comment by bsipocz** [comment]
Thanks @lglattly!

**Comment by lglattly** [comment]
Thanks!

**Pull request merged**
