### PR TITLE
Add 'build' before 'sdist' in docs for releasing affiliated packages

### PR DESCRIPTION
**Pull request by larrybradley**
For #3267.

### CODE REVIEW

**Comment by embray** [comment]
I would like to add some text explaining what the `build` step is there for.  I think probably many people have not seen multiple commands in a single `./setup.py` call before either.  I consider this an interim solution so it's worth explaining in that context as well.  If you'd like I can provide some text.

**Comment by larrybradley** [comment]
Sure, thanks @embray.

**Comment by eteq** [comment]
@embray - if you can find the time, can you try to do this (provide the additional text) before 1.0?  Or we can just merge this so people reading the 1.0/stable docs have the information there, and the additional clarification can be added later.

**Comment by embray** [comment]
I added the text in question and manually merged in 41295ac.

**Pull request closed without merging**
