### PR TITLE
add units to rotations

### PR DESCRIPTION
**Pull request by nden**
Adds units to rotations.
Previously rotations accepted only deg, angles were represented internally in rad but presented to the user in deg. This was done through a `getter` and `setter` function. 
Now angles are always represented in rad - internally and also reported back to the user.
The output units always match the input units.

### CODE REVIEW

**Comment by nden** [comment]
The tests that fail involve compound models created with class composition when one of the classes is a rotation, for example:
```
model_class = Shift & Scale | Rotation2D
model = model_class(offset_0=1, factor_1=2, angle_2=90)
```
Because there are no class level parameter getter/setter function, the angle is not converted to rad.

**Comment by astrofrog** [comment]
@nden - just to make sure I understand why did you did to remove the getters and setters? (``np.rad2deg`` and ``np.deg2rad`` work fine with quantities so they would do the right thing). When @Cadair and I worked on making the projections unit-aware, the changes were quite minimal:

https://github.com/astropy/astropy/pull/4855/files#diff-e64cfea9de8722ddfc5104ec6ec2e26c

We left all the getters/setters in place and just added ``input_units`` and ``output_units`` to all classes.

**Comment by nden** [comment]
@astrofrog `np.rad2deg` and `np.deg2rad` work with quantities. However, the modeling code passes only the value of a parameter to the getter and setter. It doesn't pass the quantity as a whole or the unit. 
So when a model is initialized with an angle in `rad`, since only the value is passed it converts it again to rad. For example for the Euler rotations, printing the value of angles passed to `EulerAngleRotation.evaluate`:

```
# converts correctly numerical values
model = EulerAngleRotation(0, 90, 0, 'zxz')
model(0, 90)
phi, theta, psi [ 0.] [ 1.57079633] [ 0.]
Out[8]: (1.5707963267948966, 6.123233995736766e-17)

# with Quantities as parameters
model = rotations.EulerAngleRotation(0*u.rad, (90*u.deg).to(u.rad), 0*u.rad, 'zxz')
model(0, 90)
phi, theta, psi [ 0.] rad [ 0.02741557] rad [ 0.] rad
Out[21]: (89.99999999999987, 88.42920367320511)
```
A solution would be to modify `Parameter.create_value_wrapper` to use the unit of a Parameter.
However changes will need to be made to `Model._initialize_parameter_values`.

Given the time constraint I am concerned that if we take that route there won't be enough time to test the changes which touch on the core of modeling. Another option is to postpone units in rotations (possibly some projections) until the next release.
What do you think?

**Comment by astrofrog** [comment]
I see - I'll try and think about it a bit more. In any case I agree, there is no rush, we can simply add it for the next version. We clearly say on the modeling units page that not all models support units yet.

**Comment by nden** [comment]
Closing this. See #6235.

**Pull request closed without merging**
