### PR TITLE
Fix a typo in coordinates/angles.py

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by adrn** [comment]
Thanks @felixonmars!

**Comment by pllim** [comment]
@adrn , why is this milestoned to 3.1 and not bug fix? Does it only affects the dev version?

**Comment by adrn** [comment]
@pllim This is a typo in a non-public function, so I didn't think it was pressing to include in 3.0.4. But feel free to re-milestone!

**Comment by pllim** [comment]
Ah, thanks for the clarification. I'll leave the decision for @bsipocz then. :smile:

**Pull request merged**
