### PR TITLE
Update astropy_helpers submodule for Astropy v1.0.x

### PR DESCRIPTION
**Pull request by embray**
to change prepared to be released astropy-helpers v1.0.3
I will push a similar PR to update the astropy-helpers version in master to the current astropy-helpers master associated with this release.

### CODE REVIEW

**Comment by embray** [comment]
Appveyor failed due to a seemingly? random failure--test exited for no apparent reason.  Rebuilding.

Travis failed due in part to #3957, the workaround to which hasn't been backported yet, and in part due to the issue #3954 is meant to fix.  I hadn't planned on backporting that fix, but I could backport a limited version of it that explicitly excludes /etc/hosts.

**Comment by embray** [comment]
Fixed the relevant issues in v1.0.x branch and rebased this PR.

**Comment by embray** [comment]
Okay, same failure on appveyor...  Maybe it wasn't random after all, but it certainly is silly.

**Comment by mwcraig** [comment]
I have a bad feeling this is related to the (never resolved) underlying issue in #3871, papered over in #3882

No reason for thinking so other than that the fail happens in the same place and quick googling suggests that `Code 1` can occur because of permission issues, which were the types of issues reported in #3871.

**Comment by embray** [comment]
Ah, thanks for that @mwcraig.  That may be it.  No idea why it started happening on this PR when it wasn't a problem before.  I'm going to try to reproduce locally.

**Comment by mwcraig** [comment]
Remember that appveyor is now using a little out-of-date version of the HDF package to get those builds going again.

**Comment by embray** [comment]
Well, I guess I won't get astropy-helpers 1.0.3 out today like I was hoping.  Just in the course of looking into what might have caused this I noticed that astropy/astropy-helpers#173 needs a teensy bit more work too.

**Comment by embray** [comment]
Plus I have no idea how to work around this for now...

**Comment by mwcraig** [comment]
Are you able to reproduce it locally? I was never able to with the older issue. Thinking about contacting Appveyor support....

**Comment by embray** [comment]
@mwcraig I haven't tried with this case yet, but the other problem you were having, where it was showing up with the convolution Cython modules, is one I've had trouble before locally.  I don't think the issue is with AppVeyor specifically.

**Comment by embray** [comment]
Huh. GH updated the CI integration UI.Nothing super significant, but I like it.

**Comment by embray** [comment]
Come to think, this PR is against the v1.0.x branch, but I don't think I've backported the fix in #3882 to that branch yet.  Let me see if that helps at all *sigh*

**Comment by embray** [comment]
Good.

**Comment by mwcraig** [comment]
Good news! I was dressing trying to chase down another Windows problem...

**Pull request merged**
