### PR TITLE
Fix a Python2-only test in Header.update

### PR DESCRIPTION
**Pull request by saimn**
Following https://github.com/astropy/astropy/pull/5310#discussion-diff-77907968

### CODE REVIEW

**Comment by MSeifert04** [comment]
@pllim This is actually a problem with Python3 (not Python2).

@saimn Without this change any dictionary got into the next branch - because that tests for `.keys` - does this affect coverage?

**Comment by saimn** [comment]
@MSeifert04 - Good point. With this change, the `.keys` is no more tested. Not sure when this is useful, as dict-like objects will have both .tems and .keys, but I can add a test with a custom object to test this branch.

**Comment by MSeifert04** [comment]
I appreciate the test! 👍 

But I would suggest we also put a deprecation-warning into that `elif hasattr(..., 'keys')` and remove it in the future. I don't think that branch is actually needed!

**Comment by saimn** [comment]
It possible that it was there to support updating the header from an object with the old API, probably `CardList` which had a `.keys` method:
https://github.com/astropy/astropy/pull/5310/files#diff-d558565c8ea8f81e6d832f2f33cf72c6L150
Maybe @embray can confirm ?

**Comment by MSeifert04** [comment]
good point, I only thought about Python data types. 😅 

But I'd really like to know if there's anything going into that branch.

**Pull request merged**
