### PR TITLE
Add new (2.0) string ufuncs in np.char to UNSUPPORTED_UFUNCS

### PR DESCRIPTION
**Pull request by dhomeier**
### Description
Additional ufuncs in `np.char` not yet covered by `units.quantity_helpers`; added to `UNSUPPORTED_UFUNCS` as none of them make sense for quantities.

Fixes part of #15690 – actually the above were not mentioned there or showed up in any test agains numpy-2.0 since `TestUfuncHelpers.test_coverage` is skipped with scipy installed.

Tagging @neutrinoceros

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by dhomeier** [comment]
@neutrinoceros you're right, this is a separate failure that is not actually covered by CI, see updated comment above; you should be able to reproduce it in your setup by running `pip uninstall scipy` and then `test_quantity_ufuncs`.

**Comment by neutrinoceros** [comment]
Oh I see, indeed that's a separate problem, so I see no harm in keeping our PRs separate. Thank you !

**Comment by neutrinoceros** [comment]
Indeed I see a difference when running `pytest astropy/units/tests/test_quantity_ufuncs.py::TestUfuncHelpers::test_coverage -vvv` against main:

```
E       AssertionError: assert {<ufunc '_rstrip_whitespace'>, <ufunc '_lstrip_chars'>, <ufunc 'startswith'>, <ufunc '_strip_whitespace'>, <ufunc 'isdecimal'>, <ufunc 'isnumeric'>, <ufunc 'endswith'>, <ufunc '_rstrip_chars'>, <ufunc '_lstrip_whitespace'>, <ufunc '_strip_chars'>, <ufunc 'find'>, <ufunc 'str_len'>, <ufunc 'isdigit'>, <ufunc 'count'>, <ufunc 'rfind'>, <ufunc 'isspace'>} == set()
E         Extra items in the left set:
E         <ufunc '_rstrip_whitespace'>
E         <ufunc '_lstrip_chars'>
E         <ufunc 'isnumeric'>
E         <ufunc 'endswith'>
E         <ufunc '_lstrip_whitespace'>
E         <ufunc '_strip_chars'>
E         <ufunc 'isspace'>
E         <ufunc 'startswith'>
E         <ufunc '_strip_whitespace'>
E         <ufunc 'isdecimal'>
E         <ufunc '_rstrip_chars'>
E         <ufunc 'find'>
E         <ufunc 'str_len'>
E         <ufunc 'isdigit'>
E         <ufunc 'count'>
E         <ufunc 'rfind'>
E         Full diff:
E         - set(,
E         - )
E         + {
E         +  <ufunc '_lstrip_chars'>,
E         +  <ufunc '_lstrip_whitespace'>,
E         +  <ufunc '_rstrip_chars'>,
E         +  <ufunc '_rstrip_whitespace'>,
E         +  <ufunc '_strip_chars'>,
E         +  <ufunc '_strip_whitespace'>,
E         +  <ufunc 'count'>,
E         +  <ufunc 'endswith'>,
E         +  <ufunc 'find'>,
E         +  <ufunc 'isdecimal'>,
E         +  <ufunc 'isdigit'>,
E         +  <ufunc 'isnumeric'>,
E         +  <ufunc 'isspace'>,
E         +  <ufunc 'rfind'>,
E         +  <ufunc 'startswith'>,
E         +  <ufunc 'str_len'>,
E         + }
```

and with this branch
```
E       AssertionError: assert {<ufunc '_lstrip_chars'>, <ufunc '_rstrip_whitespace'>, <ufunc '_strip_whitespace'>, <ufunc '_strip_chars'>, <ufunc '_lstrip_whitespace'>, <ufunc '_rstrip_chars'>, <ufunc 'str_len'>, <ufunc 'count'>} == set()
E         Extra items in the left set:
E         <ufunc '_lstrip_chars'>
E         <ufunc '_rstrip_whitespace'>
E         <ufunc '_strip_whitespace'>
E         <ufunc '_strip_chars'>
E         <ufunc '_lstrip_whitespace'>
E         <ufunc '_rstrip_chars'>
E         <ufunc 'str_len'>
E         <ufunc 'count'>
E         Full diff:
E         - set(,
E         - )
E         + {
E         +  <ufunc '_lstrip_chars'>,
E         +  <ufunc '_lstrip_whitespace'>,
E         +  <ufunc '_rstrip_chars'>,
E         +  <ufunc '_rstrip_whitespace'>,
E         +  <ufunc '_strip_chars'>,
E         +  <ufunc '_strip_whitespace'>,
E         +  <ufunc 'count'>,
E         +  <ufunc 'str_len'>,
E         + }
```

but the test fails in all cases ! Do you know what's going on here ? (I rebuilt numpy dev from source right before I wrote this reply)

**Comment by dhomeier** [comment]
Yes, just reproduced that after I force-rebuilt numpy from git main to test your branch
(https://pypi.anaconda.org/scientific-python-nightly-wheels/simple gave me something like 2.0.0.dev0+git20231111.9340fca, maybe "nightly" refers to the lunar night...).
So those must also have been added since; `count` and `str_len` are also in `np.char`, but the `_strip*` ones sit in umath only – wondering if they should be explicitly added to `UNSUPPORTED_UFUNCS` as they are obviously private.

**Comment by dhomeier** [comment]
> but the `_strip*` ones ([numpy/numpy#25152](https://github.com/numpy/numpy/pull/25152)) sit in umath only – wondering if they should be explicitly added to `UNSUPPORTED_UFUNCS` as they are obviously private.

Well, they are the only private ones except one so far:
```python
>>> [u for k, u in np._core.umath.__dict__.items() if isinstance(u, np.ufunc) and k.startswith('_')]
[<ufunc '_ones_like'>, <ufunc '_strip_whitespace'>, <ufunc '_lstrip_whitespace'>, <ufunc '_rstrip_whitespace'>, <ufunc '_strip_chars'>, <ufunc '_lstrip_chars'>, <ufunc '_rstrip_chars'>]
```
and `_ones_like` has a helper function.

**Review by neutrinoceros — APPROVED** [review]
Please merge away ! devdeps CI won't go merge until we get this *and* #15691 in (and as we saw it may not be enough still), but as I'll need to rebase mine anyway I'm happy to go in second !

**Comment by dhomeier** [comment]
Thanks for the reviews! Thought about waiting over the weekend for the _strip functions to get in, but since they are not tested anyway it does not matter.

**Comment by pllim** [comment]
@dhomeier , please remember milestone and backport label next time. Thanks!

**Comment by pllim** [comment]
@meeseeksdev backport to v6.0.x

**Comment by dhomeier** [comment]
Ow, specifically did not set one initially as I did not recall the backport rules for numpy-2 fixes, but then forgot to go through the checklist, sorry.

**Pull request merged**
