### PR TITLE
DOC: Update matplotlib doc base URL

### LINKED ISSUE #12698: Matplotlib documentation base URL has moved
### Description
It seems the base URL of the docs has changed at some point from https://matplotlib.org/ to https://matplotlib.org/stable/.
Intersphinx links to the old addresses are automatically redirected, but apparently stripped of the section references (the `..#matplotlib.widgets.EllipseSelector` part) in the process.
I could not find any cases of references directly into a section down a page in the core docs (the links still being redirected, but not losing relevant information), but a downstream example together with a fix is presented at https://github.com/astropy/regions/pull/392#issuecomment-1008090707.
So I propose to update the link in `docs/conf.py`

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to fix #12698 . Also see astropy/regions#392 . Goes with:

* astropy/sphinx-astropy#52

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Thanks!

**Review by dhomeier — APPROVED** [review]
Checked that the `regions` doc build with astropy/sphinx-astropy#52 creates the correct links now; not sure now actually where the URLs from `docs/conf.py` are used (the `readthedocs` build here still pulls the old path from `sphinx-astropy`).

And incidentally the first link I checked in our own docs happened to have a hardcoded version path in
https://github.com/astropy/astropy/blob/2984fa2ea5f3604b71df8ca687c59d34913e62f1/docs/visualization/matplotlib_integration.rst#L60
– not sure if that was required by some doctest comparisons, but that version definitely is not quite up to date.

**Comment by pllim** [comment]
> the readthedocs build here still pulls the old path from sphinx-astropy

It will do that until a new release of `sphinx-astropy` is out.

Good catch on the hardcoding! Maybe I should fix that too.

**Comment by dhomeier** [comment]
> It will do that until a new release of `sphinx-astropy` is out.

Yes, expected that, but I wasn't sure which of the two would take precedence in the end. :)

> Good catch on the hardcoding! Maybe I should fix that too.

🚀

**Comment by pllim** [comment]
I enabled cron jobs just for the link check. I'll cancel the irrelevant cron jobs. I think I got all the outdated Matplotlib links this time? Please re-review. Thanks!

**Comment by pllim** [comment]
"Allowed failure" job's failure is an unrelated socket timeout.

**Comment by mhvk** [comment]
Even better now!

**Comment by dhomeier** [comment]
Could not find any other references either; there does not seem to be a straightforward way to get the Gallery through an intersphinx reference either.

**Comment by pllim** [comment]
Thanks for the reviews!

**Comment by dhomeier** [comment]
Thanks for the fixes!

**Pull request merged**
