### PR TITLE
Renaming MexicanHats to RickerWavelets

### PR DESCRIPTION
**Pull request by bsipocz**
After some out of band discussion there was a consensus to rename and deprecate the more informal names.

### CODE REVIEW

**Comment by karllark** [comment]
Can the reason for renaming this function be included in this PR for reference?  

Also, it would be useful to include in the docstring that the RickerWavelet has also been known as a MexicanHat in the past.  Just so that people searching for it can find it.

**Comment by mhvk** [comment]
Hmm, coming from the outside, this does not seem great, changing the name to something that no longer any bearing on how the function looks, but rather relies on knowing who posited what. Rather the wrong way to go if one wants to help newcomers to a field. 

p.s.  I will admit to a bit of a hangup about calling things after people, e.g., calling something the Brunt-Vaisala frequency instead of just using the very descriptive "buoyancy frequency".

**Comment by bsipocz** [comment]
cc @astrofrog @adrn @keflavich

**Comment by adrn** [comment]
The reasoning that came out of some discussion on Slack was that (1) the name "Mexican hat" is very informal, (2) could be perceived as offensive, and (3) seemed to be regional, as in non-US or even non-southern-US folks seemed to be unfamiliar with the name (my physics courses called it as 2nd degree Hermite polynomial, not a Mexican Hat).

I tend to agree with @mhvk about using names for mathematical functions or quantitities, but some are too ubiquitous (Gaussian, Laplacian, ...etc). To float some other options: 
- Gaussian2ndDeriv
- RadialHermite2Wavelet or RadialHermite2, since I believe it is functionally equivalent to a [2nd-order Hermite polynomial](https://en.wikipedia.org/wiki/Hermite_polynomials#Hermite_functions) (although even better I guess would be to have something like `RadialHermiteWavelet(order=2)` or something)

**Comment by bsipocz** [comment]
(Reasoning to go with `RickerWavelets` as it's also called `ricker` in scipy.

**Comment by mhvk** [comment]
Well, I heard of Mexican hat as a non-US citizen, but I must admit that I had no precise notion of what it was. And obviously we also have `Moffat`, which is very astro-centric.  Since scipy calls it 'ricker` as well, let me just drop my objection. Though perhaps it should then just be `Ricker`? Where does the wavelet come in?

**Comment by bsipocz** [comment]
Well, it's also ricker wavelet, but the  name is only `ricker`  there: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.ricker.html

I don't have strong opinions, just went with the more specific name

**Comment by astrofrog** [comment]
If we rename it I think also just ricker would be fine but not a strong opinion

**Comment by nden** [comment]
I think names should not be changed lightly as this causes unnecessary pain. There should be a good reason for the change and a consensus on the new name. It sounds like there's no one well recognized name.

At some point in my life I knew both names/functions. But I had forgotten about `RickerWavelet`. Yet when I hear `Mexican hat` I know exactly what it is. There's value in names which bring immediate understanding. 

On being offensive ... There are many mathematical concepts [named after places](https://en.wikipedia.org/wiki/List_of_mathematical_concepts_named_after_places) , though I realize this is not an argument. I wholeheartedly condemn offensive language and believe we should fight unconscious bias. But I also think we have to be careful labeling things as "offensive" and going too far in that direction. What about the `Sombrero galaxy`? 

That said I have no strong opinion about the name in the sense that if it was called something else initially I would be fine with that too. I guess I don't understand why it is important to change the name after 6 years.

**Comment by keflavich** [comment]
I share Nadia's concern about changing variable names unnecessarily, and I have seen no evidence or argument presented that the name is offensive.  At the first sign that it is, then we should change it.  The other arguments, that the word is region or informal, don't seem like enough to justify the change to me; we use a `TopHat` kernel that is just as regional and informal, no?

However, I'm in favor of adding the `Ricker` name so that we have the same namescheme as scipy available.

**Comment by astrofrog** [comment]
What about adding the ricker name to be consistent with scipy as @keflavich suggests but keeping the current names as silent non deprecated aliases hidden from the docs? It wouldn’t be much code to do this right?

**Comment by kelle** [comment]
I'm not super familiar with the details of implementation but I strongly think that we should eliminate  the phrase "MexicanHat" from our code base. I think a deprecation warning now followed by removal. I am not in favor of a hidden alias. 

From my perspective, there is not a problem with the "Sombrero Galaxy" or "SombreroModel". I actually like SombreroModel more than RickerWavelets because it does indeed describe the shape.

For those of you interested in the cultural problems with the MexicanHat language, here's an article: https://www.wfae.org/post/what-makes-sleeping-mexican-so-divisive#stream/0
Also, as a Mexican-American who grew up in San Antonio, TX, I find the "MexicanHat" to describe the shape of a sombrero offensive and problematic. Thanks to all of you for doing the work necessary to change the name of this model.

**Comment by nden** [comment]
Thanks @kelle for sharing the link, it was interesting to read and understand some of the history and controversy behind the "Sleeping Mexican". As someone who has not lived in Southern US this story actually makes me feel respect to Mexicans. I think the proposed PR is totally the wrong response to the problem which is why I am taking myself off as a reviewer.

**Comment by nden** [comment]
Just to be clear:  I am OK with leaving it as it is. I am also OK with changing it if that's what the majority wants.

**Comment by pllim** [comment]
My 2 cents: If *some* of us feel uncomfortable, imagine how many out there feel the same way too but just didn't dare to speak up. So, my vote if to rename with a clear deprecation.

**Comment by bsipocz** [comment]
Re `SombreroModel`: there seems to be some usage of sombrero as function name out there, and all the cases I found use it for something else rather than this wavelet function, so that's a no go here.

**Comment by cdeil** [comment]
I'm -1 on this change.

There's pros and cons to different options for the name, but generally I think the bar to change a name in Astropy should be *very* high.  This name was chosen ~7? years ago and other projects using Astropy will have to update, causing extra work for astronomy colleagues, and undermining the reputation of Astropy as a stable base package (like Python itself, or Numpy).

Some of the arguments made, like consistency with scipy, or the name being too informal, or to be only recognised in the US, are IMO not even close to warrant a name change. If I recall correctly, when we chose the name Mexican hat, we also considered other options, but overall Mexican hat was the term that seemed most-used in astronomy. It's used in CIAO wavedetect (see https://arxiv.org/abs/astro-ph/0108429) and several well-known astronomy papers I know (a full-text search would probably reveal dozens or hundreds of papers dating back at least 30 years). It's not just astronomy, there's https://www.mathworks.com/help/wavelet/ref/mexihat.html and  https://en.wikipedia.org/wiki/Mexican_hat_wavelet .

Which IMO mainly leaves the concern mentioned by @kelle and @adrn that it's an offensive term. If it is very offensive, than OK, we should change, even if it's a pain for developers and users relying on Astropy stability.

I don't understand why "mexican hat" is offensive, especially if "sombrero" is fine.
https://en.wikipedia.org/wiki/Mexican_hat says "a Mexican hat is a sombrero" and https://en.wikipedia.org/wiki/Sombrero says "Sombrero in English refers to a type of wide-brimmed hat from Mexico". So they are the exact same think, one is the spanish word, the other the english?
If there's a difference, and "mexican hat" is offensive, then I think it would be useful to explain it on https://en.wikipedia.org/wiki/Mexican_hat (which I'm sure 100s of more people see than the Astropy class name)!

I read https://www.wfae.org/post/what-makes-sleeping-mexican-so-divisive#stream/0 and also found https://www.nybooks.com/daily/2016/09/19/the-trouble-with-sombreros-shriver-cultural-appropriation/ -- hmm, not sure what to make of this. My guess would be that the astronomers and wavelet people calling the shape "mexican hat" or the Galaxy "sombrero" used the term either as descriptive, or in admiration. I couldn't find the PR that made the original addition to Astropy, but if it was me, I can assure you: I think sombreros are great! Thus my +1 to keep the name, because stability, and descriptive, and something I like.

Sorry for the long comment -- in the end, OK, fine to change if most feel it's better. I mainly wanted to make the point for stability in Astropy - IMO the bar for breaking changes should be set a bit higher than it is at the moment.

**Comment by keflavich** [comment]
I generally agree with @cdeil and @nden's sentiment that we should have a very high bar to change, and that bar should get higher with age of the package.  This change meets that bar, though.

The point that `MexicanHat` is commonly used in astronomy means that we should have an explicit reference to this discussion (i.e., why we've deprecated and eventually removed the function, assuming we go that route) in the documentation to make it easier to understand the old literature.

It may make sense to keep the `MexicanHat` name in the codebase, permanently deprecated, with a pointer to this discussion.  That solution solves the problem of stability (everything still works forever, just with additional warnings) while raising awareness that the name being used is problematic and should be avoided.

**Comment by eteq** [comment]
I basically agree with this sentiment from @keflavich:

> It may make sense to keep the MexicanHat name in the codebase, permanently deprecated, with a pointer to this discussion. That solution solves the problem of stability (everything still works forever, just with additional warnings) while raising awareness that the name being used is problematic and should be avoided.

There is a long-standing precedent in Astropy for deprecating things long-term.  I think the question of "permanently" versus "for a while" can be dealt with later, based on whether we get significant feedback that the warning is disruptive for users.  If so, we can consider leaving the "alias" in permanently (with the deprecation warning) but if not we can remove it in a future version as @kelle suggested, following our standard procedure for deprecations.


That said, I agree with the underlying points by @cdeil and @nden that removing it may create unnecessary pain for some users, and contribute to the perception that they can't rely on stability. So that's why I'm hedging a bit above on whether to truly remove vs long-term/semi-permanent deprecation.  But when it comes right down to it, being an inclusive project *requires* considering the point @pllim made that there's probably a lot more people just not willing to say anything about this that would otherwise just quitely be put off by it. So to me this cost is out-weighted by the potential for including more members on the team.

**Comment by pllim** [comment]
By the way, I noticed that `astropy.modeling.models import MexicanHat1D` now gives `ImportError` but `from astropy.modeling.functional_models import MexicanHat1D` works. I don't see any deprecation warning, so the `ImportError` might come as a surprise to some people. FYI.

**Comment by astrofrog** [comment]
We should definitely fix ``from astropy.modeling.models import MexicanHat1D``

**Comment by bsipocz** [comment]
Ahh, I suppose there is an `import *` somewhere in there, and thus MexicanHats are not picked up.
Fixing the imports were on my list for this release, may still happen before RC, but I don't have very high hopes...

**Comment by astrofrog** [comment]
We definitely need to fix this for the RC, I can try and work on it tomorrow morning

**Comment by cdeil** [comment]
> We definitely need to fix this for the RC

Yes, please. 

https://travis-ci.org/gammapy/gammapy/jobs/605240363#L1653

**Comment by keflavich** [comment]
Just FYI for anyone who ends up here, the Sombrero Function (https://en.wikipedia.org/wiki/Sombrero_function) is something completely different that looks kinda similar on some scales.

**Comment by amitsg7505** [comment]
when I enter the following line in my code:
from astropy.convolution import RickerWavelet2DKernel 

I got an error saying that, can't import RickerWavelet2DKernel.
Any help will be appreciated.

**Comment by pllim** [comment]
@amitsg7505 , please open a new issue using the "bug report" template and provide all the requested information. Thanks.

**Pull request merged**
