### PR TITLE
Prevent pytest from rewriting asserts in display plugin

### PR DESCRIPTION
**Pull request by jdavies-st**
### Description

This resolves the following warning when running the `astropy` package unit tests:
```
/Users/jdavies/miniconda3/envs/astropy/lib/python3.7/site-packages/_pytest/config/__init__.py:545
  /Users/jdavies/miniconda3/envs/astropy/lib/python3.7/site-packages/_pytest/config/__init__.py:545: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: astropy.tests.plugins.display
    self.import_plugin(import_spec)
```

### CODE REVIEW

**Comment by pllim** [comment]
Huh, I thought we're moving this plugin out altogether? I'll let @astrofrog review this one.

**Comment by jdavies-st** [comment]
Oh cool.  Then maybe this is not needed.

It is the quick fix for the current warning though.

**Comment by bsipocz** [comment]
Yes, I suggest  to move this PR into the new repo.

**Comment by jdavies-st** [comment]
Because the new `pytest-astropy-header` plugin is accessed via `entry_points`, this is no longer an issue.  Closing.

**Pull request closed without merging**
