### PR TITLE
remove C as cgs base but also add CGS electric units

### LINKED ISSUE #4354: Electric charge base unit in cgs should not be Coulomb
The following example returns a unit of Coulomb-centimeter, but Coulomb is an SI unit:

```
In [1]: from astropy import units as u

In [2]: u.debye.decompose(bases=u.cgs.bases)
Out[2]: Unit("3.33333e-28 C cm")
```

### PR DESCRIPTION
**Pull request by eteq**
This closes #4354 by removing C as a cgs base (which was incorrect) while at the same time adding the CGS ESU/EMU charge and current as distinct physical types.  This fixes #4354 by changing it so that this behavior happens:

```
>>> u.debye.decompose(bases=u.cgs.bases)
UnitConversionError: Unit A can not be decomposed into the requested bases
```

Which is now more consistent with the behavior that happens when you try to convert CGS E&M units to their SI equivalents:
```
>>> u.statcoulomb.to(u.coulomb)
UnitConversionError: 'Fr' (electrical charge (ESU)) and 'C' (electrical charge) are not convertible
```
And that's what we *want*, because the different CGS E&M systems actually have really different physical interpretations. The [relevant wikipedia arcticle section](https://en.wikipedia.org/wiki/Centimetre%E2%80%93gram%E2%80%93second_system_of_units#Derivation_of_CGS_units_in_electromagnetism) is good for background on this for any looking at this that isn't particularly up on their E&M.

### CODE REVIEW

**Comment by eteq** [comment]
Oh, and I'm marking it for 1.1 as it's probably fair to consider this a bug (i.e. #4345).

**Comment by mhvk** [comment]
+1.  I realise I actually don't know how cgs works in this respect (and maybe I should see this just as another reason to stick to SI!), but would it, at least in principle, be possible to pick a given system and then allow conversion?  I.e., something like
```
with u.set_em_system(u.cgs.emu):
    ...
```
and within this system charge per second would correspond to the relevant current?

**Comment by eteq** [comment]
@mhvk - yes, actually that's probably a much better approach. I'd say that's definitely in the realm of "new feature", though, so maybe make a new issue for that and tenatively slate it for 1.2? (And we can merge this now for 1.1)

The one catch is that then you have to figure out how to deal with the constants... Right now it's basically taken as "you can't do direct SI-to-cgs E&M conversions of the constants themselves so as to not make assumptions".  That could be made cleverer... Or just left as-is and assumed that the user has to actually use the right constants in the right places.

**Comment by mhvk** [comment]
Agreed to keep it separate -- see #4359.

**Comment by mhvk** [comment]
p.s. The appveyor test seems spurious -- yet another one of these VOtable failures.

**Comment by eteq** [comment]
Agreed - I think the test are indeed passing in reality.  If this is OK with @astrofrog I think we can go ahead and merge it (and backport to 1.1)

**Comment by astrofrog** [comment]
Looks good to me, I've restarted AppVeyor to check

**Comment by embray** [comment]
I think this is fine--it was a mistake to have C in the cgs bases.

**Comment by eteq** [comment]
OK, appveyor is now happy, will merge and backport.

**Comment by eteq** [comment]
backported to 1.1.x in c87aaa80f3ad4b02a48e2ffa11b9b8cd48213237

**Pull request merged**
