### PR TITLE
Limit doc build to use matplotlib < 3 

### PR DESCRIPTION
**Pull request by pllim**
See if this fixes the `html-doc` CircleCI failure first before a more permanent fix can be made.

### CODE REVIEW

**Comment by astrofrog** [comment]
I'd say let's just put that in 3.1 for now since it's a temporary fix until I or someone fixes WCSAxes, and we can then backport that fix and unpin Matplotlib.

**Comment by bsipocz** [comment]
I wonder whether we need to pin this in travis, too. We don't yet see failures as it still uses v2.0.2.

**Comment by pllim** [comment]
Is the `mpl202` failure related?

**Comment by pllim** [comment]
> whether we need to pin this in travis

Is that done on the `ci-helpers` side? Given that a more permanent fix is going to be done by @Cadair soon, probably unnecessary at this point unless things start to fail on Travis as well?

**Comment by bsipocz** [comment]
> Is the mpl202 failure related?

@pllim - I don't think so, I've restarted the build.

**Comment by pllim** [comment]
`html-docs` passed FWIW

**Comment by bsipocz** [comment]
Thanks @pllim!

**Pull request merged**
