### PR TITLE
DOC: Fix ref link for KingProjectedAnalytic1D

### LINKED ISSUE #11845: DOC: KingProjectedAnalytic1D reference link broken
https://github.com/astropy/astropy/blob/9819e926cb49fbc36019f5e641b563975e56d57c/astropy/modeling/functional_models.py#L2662

https://articles.adsabs.harvard.edu/pdf/1962AJ.....67..471K now gives `ERR_CONNECTION_TIMED_OUT`. Should we replace this link with something else or just remove it? If replacing, with what?

This model (and doc) was added by @nluetzge in #9084 . cc @nden and @astrofrog , who reviewed it.

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to point the ref to link that is not broken. Fix #11845

I will let CI run but I really only need the linkcheck in the cron job. I will cancel those that are not needed.

Probably want a backport unless you are okay with broken links in released branches.

### CODE REVIEW

**Comment by pllim** [comment]
Update: linkcheck and RTD jobs passed. The rest are irrelevant, so I cancelled them.

**Review by mwcraig — APPROVED** [review]
Looks good --I suppose updating the extension documentation for asdf is an asdf issue not an astropy one.

**Comment by pllim** [comment]
Re: extension documentation for asdf -- I think @eslavich and his Scrum Team are on it.

**Comment by eslavich** [comment]
Is something broken at asdf.readthedocs.io?  Or is the documentation for astropy's asdf extension?

**Comment by pllim** [comment]
@eslavich , the latter; i.e., the "legacy" way of doing things should be replaced by the new way of doing things.

**Comment by pllim** [comment]
FWIW, I opened up a follow-up issue regarding ASDF extensions: #11899

**Pull request merged**
