### PR TITLE
Added initial layout for “What’s new in 1.2?”

### PR DESCRIPTION
**Pull request by astrofrog**
Should we just merge this in and then have people do PRs to master? (since not everyone might be familiar with doing PRs to other branches?)

### CODE REVIEW

**Comment by MSeifert04** [comment]
I think I've done a PR against a PR before but I can't remember where and how it's done anymore. Is it just adding your repo to the remotes, fetch and activate this branch and commit/push as usual?

**Comment by astrofrog** [comment]
@MSeifert04 - yes, and when it comes to opening the PR, make sure you open it against my branch.

**Comment by astrofrog** [comment]
I'm going to go ahead and merge this so that people can do PRs directly to master.

**Comment by pllim** [comment]
@astrobot , you're awesome!

**Pull request merged**
