### PR TITLE
TST: Revert some tolerance changes from cos/sin changes in numpy 1.25.dev that have been reverted

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to revert some changes due to upstream changes that have been reverted:

* https://github.com/numpy/numpy/pull/23933

These changes were from different PRs:

* #14718 
* #14771 
* #14777 

xref https://github.com/astropy/astropy/pull/14777#issuecomment-1590288671

### CODE REVIEW

**Comment by pllim** [comment]
Maaaaybe they didn't revert *everything*...

```
FAILED test_quantity_ufuncs.py::TestQuantityTrigonometricFuncs::test_testcases[tc5] - AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 3 (33.3%)
Max absolute difference: 1.11022302e-16
Max relative difference: 1.57009246e-16
 x: array([1.000000e+00, 7.071068e-01, 6.123234e-17])
 y: array([1.      , 0.707107, 0.      ])
FAILED test_quantity_ufuncs.py::TestQuantityTrigonometricFuncs::test_testcases[tc9] - AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 4 (25%)
Max absolute difference: 2.22044605e-16
Max relative difference: 2.22044605e-16
 x: array([ 0.000000e+00,  1.000000e+00, -1.000000e+00, -1.224647e-16])
 y: array([ 0.,  1., -1.,  0.])
==== 2 failed, 29319 passed, 249 skipped, 1142 xfailed in 758.71s (0:12:38) ====
```

**Comment by mhvk** [comment]
Has it entered nightly yet?

**Comment by pllim** [comment]
The wheels were uploaded after the merge but I cannot really tell beyond the timestamps. Maybe I should ask them.

https://anaconda.org/scientific-python-nightly-wheels/numpy/files

**Comment by pllim** [comment]
Well, that makes no sense. I thought my 4th commit patched the remaining 2 failures but now I see 6 failures. Maybe indeed it is picking up older wheels at random?!

**Comment by pllim** [comment]
Reply from `seberg`: numpy/numpy@cf95a31 is the last commit on the `maintenance/1.25.x` branch, and is a backport of numpy/numpy@6cd60bd on `main`. That commit unfortunately landed after numpy/numpy@2a243e6, which is the last tag on the uploaded wheel.

So I guess we have to wait a few days?

**Comment by mhvk** [comment]
Yes, good to wait till those reverts are in!

**Comment by pllim** [comment]
I don't understand. They are just not going away, not even with the numpy 1.25.0 that just came out. I would have thought they would revert the cos/sin thing before the release. Are these differences not related to cos/sin? I thought they are. 🤯

**Comment by mhvk** [comment]
Annoyingly, I cannot reproduce the failures (with numpy 1.25.0)...

**Comment by pllim** [comment]
@mhvk , I figured out what was wrong with the numpy stable failures (it was my bad, I missed reverting atol to a proper old value). But I still see some failures in numpy-dev, do you have any idea about these? 

https://github.com/astropy/astropy/actions/runs/5324760647/jobs/9644536347?pr=14946

**Review by mhvk — APPROVED** [review]
Great, let's just get this in then!

**Comment by pllim** [comment]
@meeseeksdev backport to v5.3.x

**Pull request merged**
