### PR TITLE
Add kessel_run unit

### PR DESCRIPTION
**Pull request by pllim**
Add new unit for Kessel Run.

### CODE REVIEW

**Comment by MSeifert04** [comment]
Shouldn't it be an imperial unit?

**Comment by pllim** [comment]
@mwcraig , yes, all good points. I had a hard time figuring out how to make it a time unit without violating the law of physics.

@MSeifert04 , never! If you want it to be in a proper module, perhaps `rebels.py` or `smugglers.py` but *never* imperial!

Anyway, due to the confusing definitions (even more confusing than `u.emu`!), closing this.

**Comment by bsipocz** [comment]
@pllim - Ohh, I just had this *brilliant* special day idea of moving u.emu to the bird units :)

**Comment by pllim** [comment]
@bsipocz , save that for next year! Although it should really be `deprecated_birds.py`. :wink:

**Pull request closed without merging**
