### PR TITLE
Update citation file with Paper 3 information

### PR DESCRIPTION
**Pull request by adrn**
### Description

This updates the repository `CITATION` file to include the new paper. I tried to simplify the language and instructions, and updated the standard acknowledgement to reflect the fact that people may want to cite Astropy beyond just usage of the core package.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Since this was about v5.0 LTS release, we have to backport?

**Review by pllim — APPROVED** [review]
I don't grok the bibtex syntax but I am all for keeping citation file up to date. Thanks!

Not sure if you want more people to review or not, so I won't click merge.

**Comment by pllim** [comment]
`13588/docs/changelog.rst:7: WARNING: render_fragments() got multiple values for argument 'top_underline'`

I saw this in a different PR too but I don't understand why.

**Comment by adrn** [comment]
Thanks for looking @pllim! I guess the changelog issue is being addressed in https://github.com/OpenAstronomy/sphinx-changelog/pull/14 ? I'll post this in the Slack channel to see if anyone else wants to take a look.

**Comment by adrn** [comment]
It looks like the sphinx-changelog fix is released, so I'll rebase for completeness. It doesn't seem like anyone else is going to take a look, so with your approval I think we can merge this @pllim :).

**Review by pllim — APPROVED** [review]
No point not merging. The paper is out. Thanks!

**Pull request merged**
