### PR TITLE
Add physical type aliases for angular speed

### PR DESCRIPTION
**Pull request by adrn**
"angle / time" is also commonly referred to as an [angular frequency](https://en.wikipedia.org/wiki/Angular_frequency). I added "angular velocity" as another alias because for a length/time we support "speed" or "velocity".

### CODE REVIEW

**Review by nstarman — APPROVED** [review]

**Comment by adrn** [comment]
(docs failure unrelated, I believe)

**Comment by pllim** [comment]
Yeah, looks like upstream problem:

```
intersphinx inventory 'http://docs.h5py.org/en/stable/objects.inv' not fetchable
due to <class 'requests.exceptions.HTTPError'>: 502 Server Error:
Bad Gateway for url: http://docs.h5py.org/en/stable/objects.inv
```

**Review by mhvk — APPROVED** [review]
Yes, now that we can have aliases so easily, we should use them!

**Comment by mhvk** [comment]
doc build failure is unrelated (but related to a PR I was involved in, sigh...), so merging!

**Pull request merged**
