### PR TITLE
Relax tolerance of some tests for numpy 1.22

### PR DESCRIPTION
**Pull request by mhvk**
Most likely as a consequence of numpy now supporting the faster but slightly less precise Intel Short Vector Math Library (SVML), some of our tests are failing, in ways that are not really interesting.  So, up the tolerance slightly. 

Note that I cannot reproduce the failures locally, so this may need some trial and error.

* See numpy/numpy#19478
* Avoids numpy/numpy#20699

* Close #12684
* Close #12685

- [ ] Open follow-up issues.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Seems uncontroversial enough. Thanks!

**Comment by pllim** [comment]
I cannot tell if the mpl311 failures are related or not.

**Comment by mhvk** [comment]
The python3.9 windows failure seems also related to the new numpy - and may be a bug...

I'm also unsure about the matplotlib failure - that might well be numpy related too, and thus need a new baseline image, but don't know how to investigate that... Maybe to get things going again it is an idea to pin numpy for those for now?

**Comment by mhvk** [comment]
For the win32 failure, I think this really is a numpy problem so raised an issue at https://github.com/numpy/numpy/issues/20699

**Comment by pllim** [comment]
Thanks for looking into this!

Hmm. Should we wait for numpy/numpy#20699 to be resolved before proceeding?

**Comment by pllim** [comment]
Also, did `numpy.distutils` creep back into a new release (1.22.0)?

I removed it in #12655 and the CI passes. But now it is failing in `main`.

**Comment by mhvk** [comment]
On looking more closely, I now also wonder about the test case that failed: there is actually a huge difference in parameters:
```
E       AssertionError: 
E       Not equal to tolerance rtol=0.15, atol=0
E       
E       Mismatched elements: 1 / 6 (16.7%)
E       Max absolute difference: 1549800.82273902
E       Max relative difference: 0.99999981
E        x: array([9.999454, 4.999725, 5.000437, 4.000786, 3.999523, 0.30056 ])
E        y: array([9.999455e+00, 4.999673e+00, 5.000516e+00, 4.000724e+00,
E              3.999598e+00, 1.549801e+06])
```

**Comment by mhvk** [comment]
Annoyingly, I cannot reproduce that result...

**Comment by mhvk** [comment]
Possibly, this is because Gaussian2D's theta was not actually initialized. :crossed_fingers:

**Comment by pllim** [comment]
CircleCI just not playing nice...

`ImportError: numpy.core.multiarray failed to import`

**Comment by pllim** [comment]
FYI: I rebased and see if some of the failures will go away.

**Comment by pllim** [comment]
@mhvk , I took the liberty to also try to fix all the other failures that cropped up over the holiday weekend here. Hope you don't mind!

**Comment by mhvk** [comment]
@pllim - of course fine to push further attempts, thanks! 

It does look like in the modelling something really changed, allowing `theta` to wander off (of course, it is module 2pi that counts, but it is strange that the angle goes so much further off than before!). Were you able to confirm any of these on your own machine?

**Comment by pllim** [comment]
> Were you able to confirm any of these on your own machine?

No, I am doing other work while the CI churns away. The most curious thing is not all  jobs are failing, so something specific is triggering it. I wonder if @WilliamJamieson has any idea...

**Comment by pllim** [comment]
Really don't know what is going on with modeling. I don't see this failure on main and I don't see how this patch can trigger this failure. I pushed a commit to just skip it on Windows to see if other jobs even have the same failure or not.

**Comment by pllim** [comment]
@mhvk ... regarding `test_deriv_2D` failing on Windows with numpy 1.22.0, do you think there is a chance this is caused by some underlying incompatibility between scipy 1.7.3 and numpy 1.22.0 on Windows? Are you aware of any existing issues like that?

If not, I guess me or someone with native Windows access can try to reproduce this error locally by unskipping that test... 🤷

**Comment by mhvk** [comment]
I've not seen similar reports, but I find it very suspicious that the tests are all failing on windows.  It would indeed be good if someone could check on windows to see if there is an issue, and ideally check what is the underlying reason... Regardless, it is beginning to look like we may have to skip numpy 1.22.0, at least on windows...

**Comment by pllim** [comment]
Maybe we don't need this patch if #12684 works... 👀

**Comment by pllim** [comment]
@WilliamJamieson is investigating if he can rewrite the offending modeling test to be more robust.

**Comment by pllim** [comment]
I also see this warning in a local install when I do a `pip install numpy -U` to upgrade to 1.22. Should we be worried about this?

```
oldest-supported-numpy 0.15 requires numpy==1.17.3; python_version == "3.8" and(platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "aarch64" and platform_machine != "s390x" and platform_python_implementation != "PyPy", but you have numpy 1.22.0 which is incompatible.
Successfully installed numpy-1.22.0
```

**Comment by pllim** [comment]
p.s. I am unable to reproduce the modeling failure on Windows 10 locally.

**Comment by mhvk** [comment]
I tried to follow all the experiments, but fear it just left me super-confused! In particular of course not being able to actually reproduce the failures...

**Comment by pllim** [comment]
Hmm. Looks like we don't have to touch most of the tests if we go with #12685 . What do you think?

**Comment by mhvk** [comment]
Ideally, we run our tests as users would, so without setting environment variables. I don't mind relaxing the constraints, but the changes in modelling are really worrying.

So, perhaps the best is to use #12685 for now, so that the tests pass again and we can continue to merge new stuff, but raise an issue to remind us to try to find out what is causing the modelling problems - we don't want users to get wrong results if they don't have that variable set!!

**Comment by WilliamJamieson** [comment]
@mhvk I suspect that the "modeling problem" is just a case of equivalent parameter sets. This is because the only parameter that is "wrong" is the rotation angle of the `Gaussian2D` model, this parameter is technically periodic with period 2pi. My theory is that the [`scipy.optimize.leastlsq`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.leastsq.html#scipy.optimize.leastsq) method is just wandering to a different "equivalent" parameter. At some point we should consider switching over to using [`scipy.optimize.leaset_squares`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html#scipy.optimize.least_squares), which is now the recommended method.

Note that the test changes I suggested for #12684, are passing for the `Gaussian2D`, this change compares the outputs of the two models over many test points, demonstrating that the two models seem to be arriving at the same results. This type of test is indifferent to "equivalent" values for parameters. The concerning problem to me is that this seems to only happen in a specific environment.

**Comment by pllim** [comment]
> we run our tests as users would, so without setting environment variables

That is a good point as well. Now I am torn... We have two options:

1. If we decide we do not want to rely on magic env var, we go with this PR but first I need to cherry-pick @WilliamJamieson 's fixes from #12684 .
2. If we decide we do not want to adjust tests, we go with #12685 .

**Comment by saimn** [comment]
Not using the env var seems better since it's hard to ensure that it's always set, e.g. when running pytest directly. So as it seems we now have a solution for the various tests that are failing, adjusting the constraints, I would go with that.

**Comment by mhvk** [comment]
@WilliamJamieson - thanks, that makes sense. As you say, the weird thing is that it depends on environment. But as long as one gets a fit that actually works, it does not matter too much.

**Comment by mhvk** [comment]
I also would tend to go with this PR, i.e., not using the environment variable. I have some hope that over at numpy improvements will be made so that the tolerance becomes better again, but really for our purposes the matches are still amply good enough.

**Comment by pllim** [comment]
Okay, I cleaned up this PR. Hopefully tests will pass now. I still don't understand why pyinstaller fails with numpy 1.22 but I have pinned it to 1.21.* for now.

**Comment by pllim** [comment]
"Allowed failure" failure is an unrelated socket timeout.

**Comment by pllim** [comment]
Thank you, everyone!

**Pull request merged**
