### PR TITLE
Update "naxisx" attributes when slicing the WCS

### LINKED ISSUE #4498: wcs.WCS.slice() does not modify NAXISj values
The current implementation of WCS slicing appropriately modifies the CRPIX and CDELT values but does not modify the NAXIS values.  Consequently the sliced WCS is not valid for the correspondingly sliced data array; the NAXIS values do not match the dimensions of the data.  Example:

```
In [5]: image = fits.getdata(path)

In [6]: w = wcs.WCS(fits.getheader(path))
WARNING: FITSFixedWarning: 'datfix' made the change 'Changed '' to '2014-10-17'' [astropy.wcs.wcs]

In [7]: image.shape
Out[7]: (2883, 4279)

In [8]: w
Out[8]: 
WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN'  'DEC--TAN'  
CRVAL : 12.56281278668  -25.916806236839999  
CRPIX : 2141.0  1450.5  
CD1_1 CD1_2  : -0.00097191601525989998  0.0  
CD2_1 CD2_2  : 0.0  0.00097191601525989998  
NAXIS    : 4279 2883

In [9]: image[100:500,250:850].shape
Out[9]: (400, 600)

In [10]: w[100:500,250:850]
Out[10]: 
WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN'  'DEC--TAN'  
CRVAL : 12.56281278668  -25.916806236839999  
CRPIX : 1891.0  1350.5  
CD1_1 CD1_2  : -0.00097191601525989998  0.0  
CD2_1 CD2_2  : 0.0  0.00097191601525989998  
NAXIS    : 4279 2883
```

This is a problem for code that attempts to use slicing to trim an image with WCS, e.g. astropy/ccdproc#281

### PR DESCRIPTION
**Pull request by MSeifert04**
Fixes https://github.com/astropy/ccdproc/issues/281 and Fixes #4498

This PR adds a `_naxis1` and `_naxis2` property (mostly for backwards-compatibility) but the `_naxis` is now saved internally as `list`. This allows to support more than 2 axis, especially if someone wants to expand the `calculate_footprint` method.

Of course it also updates the `_naxis` attribute when being sliced.

### CODE REVIEW

**Comment by MSeifert04** [comment]
Unfortunatly python2's `xrange` cannot be `sliced` with a `slice`. 

Does anyone know a "pretty" way to calculate the sliced `naxis`?

**Comment by MSeifert04** [comment]
cc: @nden @mcara

**Comment by nden** [comment]
@MSeifert04 This looks good to me. Have you looked at the tests? Perhaps add a slicing test or modify it (if there's one). 
Ping @keflavich since he implemented slicing.

**Comment by MSeifert04** [comment]
Yeah, totally forgot about the test. 😅 I modified an existing test.

**Comment by astrofrog** [comment]
Did this functionality exist in 1.0.x? If so, this will need to be re-milestoned as 1.0.x and the changelog entry updated.

**Comment by MSeifert04** [comment]
How do I check that? The 1.0.x files look as if the functionality existed there and it seems the change could be applied there as well. But I just looked at the files, I haven't tried to backport it.

**Comment by nden** [comment]
Looks like `WCS.slice()` was added in 0.4. Are we still supporting 0.x versions?

**Comment by MSeifert04** [comment]
@astrofrog Thank you. I've moved the Changelog to the 1.0.11 section. 👍

**Comment by pllim** [comment]
Since this is approved, merging.

**Comment by saimn** [comment]
This PR breaks our code as it forbid setting a value to `_naxis1`/`_naxis2`. These variables are private, but there are also the only way to deal with the shape of a WCS object (so I guess this will be an issue for other packages). And it was possible before ;-). Any objection to adding setters for the new properties ? (@nden @MSeifert04)

**Comment by MSeifert04** [comment]
I didn't add setters because these are private variables and providing explicit setters clearly violates the python principles about variables with one leading underscore - these are implementation details and should never be relied upon. 

But I didn't want to break existing code and I wouldn't mind if they get setters 😄 I just never thought about adding these when I made the PR.

**Comment by MSeifert04** [comment]
@saimn Is it public code that broke?

**Comment by astrofrog** [comment]
@nden and I have discussed the idea before of having a sub-class of WCS that does have image size information, since this is a common use case, and maybe that is the one that should support slicing (not the actual WCS class, which could then come completely size-agnostic)

**Comment by saimn** [comment]
@MSeifert04 - yep, code is here: https://git-cral.univ-lyon1.fr/MUSE/mpdaf/blob/master/lib/mpdaf/obj/coords.py#L590

> these are implementation details and should never be relied upon. 

In theory yes, but these ones are used everywhere I think, as there is no other way. Another example with a quick search on github: https://github.com/spacetelescope/stwcs/blob/master/stwcs/distortion/utils.py#L58

**Comment by saimn** [comment]
@astrofrog - It would be nice indeed.

**Comment by MSeifert04** [comment]
@saimn One workaround would be to use:

```
wcs = WCS()
wcs._get_naxis({'NAXIS1': n1, 'NAXIS': n2})
```

that should also set the naxis attributes but it's just another private method.

> I have discussed the idea before of having a sub-class of WCS that does have image size information

@astrofrog That would be 🎉

**Comment by saimn** [comment]
@MSeifert04 - I can fix the code in many ways, but I prefer if I don't have to fix it ;-). I mean the

**Comment by saimn** [comment]
@MSeifert04 - I can fix the code in many ways, but I prefer if I don't have to fix it ;-). These attributes are used, and there is no gain here to remove this possibility. And no real alternatives (your solution also use a private method and a `_get...` to set a value ... ).

**Comment by mcara** [comment]
@saimn A long discussion on the issue of private naxis is here: https://github.com/astropy/astropy/issues/4669

In my opinion, there are two distinct approaches: either WCS lives by itself and does not care about the size of the image, or WCS is ties to an image and thus it is natural that a WCS object knows the dimensions of the image. In the later case, I have argued that ``naxis1`` and ``naxis2`` be made public. This is especially important due to the following https://github.com/astropy/astropy/pull/5411#issuecomment-258022122 by @saimn :

> In theory yes, but these ones are used everywhere I think, as there is no other way.

If so,  ``naxis1`` and ``naxis2`` must be made public. It makes no sense in keeping these two attributes private when everybody is *relying* on them!

**Comment by MSeifert04** [comment]
@saimn As I said, I have no objections to setters for those attributes, I just haven't realized they were actually used. And the workaround: Just if you need the code working right now.

The change also broke some stuff in `astroquery` because it cannot handle floats anymore. This definitly needs some regression tests and further patching. I'll submit a new PR the next days - if nobody else wants 😄

**Comment by astrofrog** [comment]
These used to be public in Astropy FYI and were removed because it was felt the WCS class should be as close to the standard as possible. But I do believe we need ``BoundedWCS`` or something similar, which would be a WCS sub-class with an explicit size. Then we give people a choice.

**Comment by saimn** [comment]
@MSeifert04 - No problem, I didn't want to re-launch a huge discussion on WCS :laughing: (thanks @mcara for pointing it !), but I just submitted #5454 to add the setters, before going to bed ;).

**Comment by mcara** [comment]
I kind of like the idea of ``BoundedWCS`` by @astrofrog but I also think that could be achieved with the existing WCS class if we:

- make ``naxis``, ``naxis1``, etc. public;
- allow ``naxis`` values to be ``None`` for "unbounded" WCS;
- provide a convenience property such as ``bounded`` to test if a WCS is bounded.

**Comment by astrofrog** [comment]
@nden - what is your thought on the best approach - just allow WCS to be optionally bounded to an image, or have a separate class? Either way, I think we should get a solution in for 1.3 and then deprecate the private use of ``_naxis1``/``_naxis2``.

**Comment by nden** [comment]
I am not too enthusiastic about a separate class. If I have to implement the WCS for an instrument I'd always use the one with `naxisj` because it's good to have them for use in applications. So I see the main `WCS` class being used very rarely in that case, if ever. I think in this case practicality should trump purity and we should make `naxis` public again. 
I also think the argument for not having them in the main `WCS` object is too theoretical for a typical user to care about it and having two classes may become confusing. :+1: from me on making them public.

**Pull request merged**
