### PR TITLE
Add summary of changes

### PR DESCRIPTION
**Pull request by eteq**
As @astrofrog suggested in #3451, we should add something summarizing the number of bugs fixed in 1.0 (and possibly go back and do the same for 0.4).  I'll try to locate the script I did this with before and we can do it just before release to make sure we have the latest numbers.

### CODE REVIEW

**Comment by eteq** [comment]
Ah, this actually came from the script I put up at https://github.com/astropy/astropy-tools/blob/master/gh_issuereport.py .  I'm attaching a PR here that includes the numbers for 0.4 -> 1.0.

**Comment by eteq** [comment]
(i killed appveyor simply because it's pointless for it to run on a pure doc change)

**Comment by astrofrog** [comment]
Ok, this looks good to me.

**Comment by eteq** [comment]
bakcported to v1.0.x in 3650b11d39c5892978008594a1ac01469ff074f7

**Pull request merged**
