### PR TITLE
Eliminate compatibility mode from HDF5 I/O

### PR DESCRIPTION
**Pull request by matteobachetti**
As per #8888 

- [x] Eliminate compatibility mode writing
- [x] Changelog etc.

@taldcroft, @pllim, @astrofrog, @bsipocz et al.: is there a use case for being able to still _read_ the old format?

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! I don't use HDF5, so I cannot comment. 😬

**Comment by bsipocz** [comment]
Please remove changes to the helpers.

I don't use hdf5 files so don't know how widely the old formats are used, and what the actual issue with it. Naively I would say we should be able to read in as many types of files as possible, but should not write non standard or obsolete versions of them.

**Comment by matteobachetti** [comment]
Oh, sorry for the helpers thing. Done

**Comment by matteobachetti** [comment]
@bsipocz the main problem I see is that the old reader now remains untested because we have no way to write old-format files. Besides that, I would also prefer to keep as many formats as possible

**Comment by pllim** [comment]
Re: testing old format reader -- Is it possible to write it out now while we can and store it as a test data file (either remote or local depending on file size and your philosophy about data files).

**Comment by astrofrog** [comment]
@matteobachetti - could you rebase, to get rid of the merge commits?

**Comment by matteobachetti** [comment]
@astrofrog: done, but  32-bit tests are falling and I'm not sure why

**Comment by matteobachetti** [comment]
Oh, I see the likely problem with the 32-bit build: #8934

**Comment by bsipocz** [comment]
@matteobachetti - yes, failures should be unrelated. Given that this needs a rebase anyway due to the unrelated commit, I would say rebase after #8945 (or alternative) is merged.

**Comment by matteobachetti** [comment]
Oh, I wonder why that commit is there at all. I already rebased in theory O_o. 
Anyway, the plan sounds good. Waiting for solution for 32 bits, then rebase. Thanks!

**Comment by bsipocz** [comment]
@matteobachetti - the workaround in merged, so you can rebase. You can manually remove the commit if you rebase in interactive mode.

**Comment by matteobachetti** [comment]
@bsipocz rebased and dropped commit.

**Comment by bsipocz** [comment]
Thanks @matteobachetti

**Pull request merged**
