### PR TITLE
Document the math behind projections

### PR DESCRIPTION
**Pull request by mdboom**
I'm adding the zenithal and cylindrical projections to ASDF over here: https://github.com/spacetelescope/asdf-standard/pull/69

and thought it would be worth elaborating on what the projections are in astropy as well.

### CODE REVIEW

**Comment by embray** [comment]
Thanks.  A little while back *someone* (I forget who, might have been @astrofrog, might have even been you) asked me about these and I wasn't really sure except that they were WCS related.  I've also thought of renaming this with less FITS-WCS-y names (though they could still be aliased to the existing names too).  What do you think?

**Comment by mdboom** [comment]
Yeah: I'd be all for using something more descriptive than the 3-letter FITS WCS names (and that's what I've done over on the ASDF side).  I can add that to this PR if everyone agrees that makes sense.

**Comment by embray** [comment]
:+1:

**Comment by embray** [comment]
Either way a not in the docstring mentioning which FITS WCS projection it pertains to makes sense though.

**Comment by mdboom** [comment]
I think I'll do the rename/deprecation as part of a separate PR -- that way this doc-only fix can go on 1.0.x, and the rest, I suppose, would have to go on 1.1.x.

**Comment by mdboom** [comment]
And -- ugh -- the AZP equation is wrong here.  Updating...

**Comment by mdboom** [comment]
I think this is ready to merge.  Low risk, as it's documentation-only.

**Comment by embray** [comment]
:+1:

**Pull request merged**
