### PR TITLE
Added Hermite 1d and 2d polynomial models

### PR DESCRIPTION
**Pull request by adelave1**
Followed Chebyshev 1D and 2D polynomial models.

### CODE REVIEW

**Comment by pllim** [comment]
Before this can be properly reviewed, something needs to be done on the indentations of your codes. Please make sure each indentation level is *four spaces* (no tabs).

**Comment by larrybradley** [comment]
@adelave1 It looks like your editor has converted 4 spaces to a Tab character everywhere in the file.

**Comment by nden** [comment]
@adelave1 This looks good. I think it only needs an entry in CHANGES.rst under `New Features` in 1.3 and can be merged. Thanks.

**Comment by adelave1** [comment]
@nden, I've added an entry to CHANGES.rst. Please let me know what you think. Thanks!

**Pull request merged**
