### PR TITLE
Avoid deprecation warning in wcsaxes doc

### LINKED ISSUE #11458: TST: matplotlib 3.4.1 warnings broke CI and RTD
You will see this error on CircleCI for `mpldev` and in the dev job of Actions:

```
INTERNALERROR> ValueError: Key backend: '' is not a valid value for backend; supported values are
['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo',
'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo',
'pdf', 'pgf', 'ps', 'svg', 'template']
```

You will see these warnings on RTD:

```
MatplotlibDeprecationWarning:
The validCap attribute was deprecated in Matplotlib 3.4 and will be removed two minor releases later.
  return getattr(obj, attr, *defargs)
MatplotlibDeprecationWarning:
The validJoin attribute was deprecated in Matplotlib 3.4 and will be removed two minor releases later.
  return getattr(obj, attr, *defargs)
```

`pandas` saw something similar for the warning and their fix is pandas-dev/pandas#32444

### PR DESCRIPTION
**Pull request by nstarman**
### Description

- Temporary fix to https://github.com/matplotlib/matplotlib/issues/19839,
- from https://github.com/astropy/astropy/pull/11118,
- closes https://github.com/astropy/astropy/pull/11464

🤞Address the RTD part of #11458 (EDITED)

Co-authored-by: @pllim
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

### CODE REVIEW

**Comment by pllim** [comment]
Hmm... still running... Not sure if that's good or bad. Let's see. I hope it doesn't time out.

**Comment by nstarman** [comment]
@pllim It's still running! but RTD is still bringing up the warning.
```
The validCap attribute was deprecated in Matplotlib 3.4 and will be removed two minor releases later.
  return getattr(obj, attr, *defargs)
```

I don't know what the difference is between #11118 and this, but it looks like https://github.com/astropy/astropy/pull/11464 might still be necessary. 😰.

**Comment by pllim** [comment]
As long as RTD doesn't fail, I don't really care if the warnings are there or not anymore. I feel like we have wasted too much time on this... 😅

**Comment by pllim** [comment]
FWIW, I have been playing with different directives from Sphinx `autodoc` and our own `sphinx-automodapi` but these warnings are very hard to get rid of. I have a feeling that [sphinx_automodapi/autodoc_enhancements.py#L71](https://github.com/astropy/sphinx-automodapi/blob/f66e58254e58220f49a30b6c66280d8e2d940c9e/sphinx_automodapi/autodoc_enhancements.py#L71) happens before all the skipping stuff.

**Comment by pllim** [comment]
I think RTD is stuck and there is no way for me to manually restart it. Might need another push. Maybe just amending the existing commit and do a force push would work. 🤞

**Comment by nstarman** [comment]
@pllim @eteq , RTD compiles 🥳

**Review by pllim — APPROVED** [review]
Thank you very much!

**Comment by pllim** [comment]
Manual backport for this is #11465 and hopefully we won't need anymore backports given this is a temporary solution.

**Comment by nstarman** [comment]
@pllim, is this something I should do? how does one PR a backport?

**Comment by pllim** [comment]
@nstarman , don't worry about the backports. The release managers take care of that and we have helper scripts. 😄  Thanks again for your fix!

**Comment by pllim** [comment]
I think we need to backport this. I see the same warnings on RTD build for LTS, causing it to fail.

**Pull request merged**
