### PR TITLE
MNT: Remove build_sphinx from setup.cfg

### PR DESCRIPTION
**Pull request by pllim**
We don't need it anymore, right?

### CODE REVIEW

**Comment by bsipocz** [comment]
I suppose it can go (yet I still using it all the time given that that's the default way for sphinx rather than our  `build_docs`  workaround).

**Comment by pllim** [comment]
@bsipocz , doesn't hurt to keep around if it is still being used. Just didn't want it to linger if not used. I can close this without merge if you don't feel comfortable about it. Your call!

**Comment by bsipocz** [comment]
I mean I can change my habits, but maybe there are others out there, too who use the sphinx "standard" way of doing things rather than the user friendly way.

**Comment by pllim** [comment]
OK let's just close then. We can revisit in the future if needed. Or maybe if @astrofrog procrastinate a bit more with that doc builder, we won't even need `setup.cfg` anymore. 😉

**Comment by bsipocz** [comment]
I wanted to 😱  as a reaction but couldn't...

**Pull request closed without merging**
