### PR TITLE
Fix use of quantize level parameter for CompImageHDU

### LINKED ISSUE #5969: RICE compression options ignored in io.fits.CompImageHDU?
I was trying to compress some FITS images using astropy and found that quantize_level seems to be ignored when using RICE compression.

e.g., some minimal code (which, warning, will write some files im1.fits, im2.fits, and im3.fits...):
```python
from astropy.io import fits
import scipy, numpy
im1 = scipy.misc.ascent() + numpy.random.randn(512, 512)*10
fits.ImageHDU(im1).writeto('im1.fits')
fits.CompImageHDU(im1, compression_type='RICE_1', quantize_method=1, quantize_level=-1, dither_seed=5).writeto('im2.fits')
fits.CompImageHDU(im1, compression_type='RICE_1', quantize_method=1, quantize_level=-100, dither_seed=5).writeto('im3.fits')
im2 = fits.getdata('im2.fits')
im3 = fits.getdata('im3.fits')
numpy.all(im2 == im3)  # True, but expected False?
```
My impression is that im3.fits should be much smaller than im2.fits, and that im2 and im3 should be quite different, one having been quantized with a step size of 100 and the other having been quantized with a step size of 1.  Instead the images are identical.  Compressing with fpack -q -100 and fpack -q -1 indeed produces images with very different sizes.

Relatedly, if I change the compression_type to GZIP_1, quantize_method has an effect, and one sees clearly smaller images with quantize_level = -100 than with quantize_level = -1.  

So as far as I can tell, the quantize_level argument is not being properly processed for RICE compression.

### PR DESCRIPTION
**Pull request by saimn**
Seems to fix #5969

### CODE REVIEW

**Comment by saimn** [comment]
Note that I don't know how to test if the result is more correct than previously ;-).

**Comment by bsipocz** [comment]
@saimn - This will need a milestone assigned and changelog added.

**Comment by pllim** [comment]
Don't you guys sleep in Leiden?!

**Comment by bsipocz** [comment]
Hacking and getting @eteq to finish up PRs in the bar...

**Comment by eteq** [comment]
@schlafly - can you check if this fixes your use case from #5969 ? And is it possible to roll in a regression test for this using some small version of that, @saimn ?

**Comment by saimn** [comment]
@bsipocz - Right, milestone set (I'm used to having someone doing this for me !), and I will add the changelog.

@pllim - I'm not in Leiden, and should definitely go to sleep ;)

@eteq - The [current test](https://github.com/astropy/astropy/blob/master/astropy/io/fits/tests/test_image.py#L1061) doesn't really test the result, so the only thing I see currently is to test that the file size is smaller 😕 . Also the file size is consistent with the result from fpack, which is already a good point.

**Comment by schlafly** [comment]
The procedure is to download some recent version of astropy, apply this commit, reinstall astropy, and run this test?  Sorry---I'm just not very familiar with the routine.

The only thing I'd mention is that you should be able to see the effect of the quantization pretty clearly.  If you plot a histogram of the differences between im1 and im2 or im3, im1-im2 should be uniformly distributed between -0.5 and 0.5, and im1-im3 should be uniformly distributed between -50 and 50.  If that's the case, then quantization is definitely working.

I wish I had a better test to recommend than "uniformly distributed," but there's a pseudo-random algorithm in there that makes it hard to predict what any particular bit should be.

**Comment by bsipocz** [comment]
@saimn - In times like this when travis is traffic jammed, you don't need to use ``[skip ci]`` as we use the auto cancel feature anyway, and only the last commit of a PR gets tested (however nothing gets cancelled if the build is already started, thus this illogical logic).

**Comment by pllim** [comment]
@schlafly , the procedure is to clone @saimn 's fork, check out his feature branch associated with this PR, run "python setup.py install", and use the installed Astropy to run your code. If you use `conda`, it is best to do this in a new `conda env`.

**Comment by saimn** [comment]
@schlafly - Thanks for the useful explanation, which makes it possible to write a real test (just testing the bounds of the distribution seems good enough) and confirm that this PR fixes the issue. It's still welcome if you want to test by yourself.
The test I added is almost exactly from your issue report (with the optional scipy dependency, so it will not be run on all configurations) : https://github.com/astropy/astropy/pull/6029/commits/f8745a708d7aaf2a4c318b2b7f1051206332a416

@bsipocz - Interesting, thanks for the reminder about the auto-cancel feature.

**Comment by schlafly** [comment]
Great, thanks!  I might step the tolerances back a factor of 10 or so; because of the randn() eventually you're going to get a case where the test fails due to chance, and it looks to me like the current tolerances only expect ~3 values within 1e-3 or 1e-5.

**Comment by saimn** [comment]
@schlafly - Good point, thanks. I will update the values and maybe also set the seed to avoid having a non-deterministic test.

**Comment by embray** [comment]
Good catch, LGTM.

**Comment by bsipocz** [comment]
Thanks @saimn for the fix and @embray for reviewing. 

And with this merged, we're down to 💯

**Pull request merged**
