### PR TITLE
Add support for fill_values functionality with ascii html format

### PR DESCRIPTION
**Pull request by tylfin**
Fixes https://github.com/astropy/astropy/issues/5354 according to http://docs.astropy.org/en/v0.2.1/io/ascii/read.html#id1

### CODE REVIEW

**Comment by taldcroft** [comment]
@tylfin - thanks for digging in to this!  I wonder if you spent time trying to figure out how to re-use the existing fill-values machinery in `core.py` instead of making an independent implemention that is custom to HTML.

**Comment by tylfin** [comment]
@taldcroft I looked into it, but I believe the fill_values logic happens in `core.BaseData` and the html writer doesn't utilize this functionality.

**Comment by pllim** [comment]
Side note: It is generally not recommended to issue PR from your own master branch.

**Comment by tylfin** [comment]
Closing for https://github.com/astropy/astropy/pull/5379 per @pllim's comment

**Comment by pllim** [comment]
Note: Superseded by #5379.

**Comment by pllim** [comment]
Ops... my note was unnecessary. Ah, well. Thanks, @tylfin !

**Pull request closed without merging**
