### PR TITLE
DOC: simplify changelog entry for #16903

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
Follow up to #16903 as requested by @eerovaher (https://github.com/astropy/astropy/pull/16903#discussion_r1745861020)

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Looks good to me.

**Comment by eerovaher** [comment]
Maybe we should have a look at all the new change log entries and not just this one?

**Comment by mhvk** [comment]
> Maybe we should have a look at all the new change log entries and not just this one?

That seems like a separate project... And not sure that is worth the effort - in principle, someone has reviewed the messages already, and it is not like many people will really do more than scan them...

**Comment by pllim** [comment]
Thanks!

**Pull request merged**
