### PR TITLE
Make ndarray Parameters read-only

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

More immutability protections.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by mhvk — COMMENTED** [review]
Not quite sure about this: is it really worth the extra effort to stop people from fiddling with this? If you think it is, is it then OK to just change an input argument? It feels like an unwarranted side effect. (Though of course one goal here is to prevent someone changing the argument after passing it in...) Or should a copy be made? My overall sense would be just not to worry...

**Comment by nstarman** [comment]
> is it really worth the extra effort to stop people from fiddling with this?

It's more that ``@property`` prevents whole-sale replacement, but not in-place modification of arrays. For something that's meant to be immutable, it's a failing. Currently this really applies to ``m_nu``, but I'm envisioning when cosmologies can be array-valued and all the parameters will be similarly susceptible.

> is it then OK to just change an input argument? It feels like an unwarranted side effect.... Or should a copy be made?

A good point about changing input arguments. A copy should probably be made. OTOH for large arrays that can be wasteful. A kwarg ``copy`` might be warranted. But that's probably better tackled in a later PR when it's more relevant.
I'll copy the parameter before setting the writeable flag.

**Comment by nstarman** [comment]
Now the parameters are copied before being validated.

**Comment by nstarman** [comment]
ping @mhvk. I made the copy as you suggest. It's definitely an improvement and makes it more likely that a Cosmology's parameters are not mutated after its instantiated. I think the read-only setting is similarly beneficial.

**Comment by nstarman** [comment]
gentle ping @mhvk. I think this is ready to go in.

**Review by mhvk — APPROVED** [review]
Code looks good. Still not completely convinced this is necessary, but happy to go with your choice - and we do generally copy inputs also in other classes, so that argues you are right!

**Pull request merged**
