### PR TITLE
Backport PR #11986 on branch v4.3.x (Fix ASDF tag versions in transform type classes)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #11986: Fix ASDF tag versions in transform type classes

### CODE REVIEW

**Comment by pllim** [comment]
@eteq @saimn @bsipocz -- Looks like the bot is working again! Don't think the Azure failures are related.

Though, the change log checker is complaining because the original PR number is mentioned, not this one. Do we just ignore change log check in a backport PR?

**Comment by bsipocz** [comment]
I think it would not hurt to list both PR numbers, after all, strictly speaking it's the backport PR that gets to the release. Is there an easy way to do that @saimn @Cadair?

**Comment by saimn** [comment]
Having both PR numbers would require a second fragment file, same content but with the new number. But I think having only the original PR number is fine, the backport will be referenced there if needed.

**Comment by pllim** [comment]
Re: change log check -- There are two ways we can handle it (I don't think the bot can add label that did not exist in the original PR):

1. Have the reviewer manually slap the `skip-changelog-check` label. We can remind people by updating the PR check list; *or*
2. I can add a special logic into the change log checker to not check at all when upstream branch is not `main`.

Any preference?

**Comment by bsipocz** [comment]
Or 2.1: special logic to not check when the pr author is the bot. That would cover the rare case of genuine pr that's against the LTS or bug fix branch.

**Comment by saimn** [comment]
2 seems OK, or 2.1 if checking the PR author is easy enough.

**Comment by pllim** [comment]
Re: change log check -- OK, done. `Skipping towncrier changelog check for backport bot "meeseeksmachine"`

Doesn't solve the problem for @mhvk 's manual backport though, but maybe for manual backports, it is sufficient to require reviewer to still manually use the `skip-changelog-check` label.

**Comment by saimn** [comment]
So maybe 2 is better, most of the time we should not deal with changelogs in backport branches, the only branch where the check is important is `main`.

**Comment by bsipocz** [comment]
I would disagree. If a manual backport is needed, at least in the case of substantial patching, I would think the backport should be the one in the changelog. So either labeling, or updating the fragment file

**Comment by mhvk** [comment]
@pllim - for the manual backport, I think adding `skip-changelog-check` label manually is fine. Could you add that to the instructions that are provided when an auto-backport is not possible (by the way, I found those instructions *very* helpful, thanks!!)

**Review by pllim — APPROVED** [review]

**Pull request merged**
