### PR TITLE
No longer require LaTeX for docs

### PR DESCRIPTION
**Pull request by astrofrog**
Replaces https://github.com/astropy/astropy/pull/6696 - there were issues with GitHub yesterday and I'm not able to re-open that PR or add commits to it.

### CODE REVIEW

**Comment by bsipocz** [comment]
There are two new docs warnings, but they also seem unrelated to this PR. 

```
/home/travis/build/astropy/astropy/build/lib.linux-x86_64-3.6/astropy/stats/bayesian_blocks.py:docstring of astropy.stats.FitnessFunc:7: WARNING: Unknown target name: "scargle2012".

/home/travis/build/astropy/astropy/build/lib.linux-x86_64-3.6/astropy/stats/bayesian_blocks.py:docstring of astropy.stats.FitnessFunc:26: WARNING: Unknown target name: "scargle2012".
```

**Comment by mhvk** [comment]
Really nice!

**Comment by astrofrog** [comment]
So do we think the warnings are unrelated?

**Comment by MSeifert04** [comment]
Could these be numpydoc related? I've seen there have been changes in astropy-helpers.

**Comment by astrofrog** [comment]
@MSeifert04 - ah yes of course! So it is related

**Comment by bsipocz** [comment]
Oh, nice catch @MSeifert04!

**Comment by bsipocz** [comment]
One more thing. Since this PR is tagged for backporting, we cannot really update the helpers to be the latest dev version, but it needs to be the 2.0.x branch from there.

**Comment by astrofrog** [comment]
Looks like Numpy renamed the scargle reference to ``Scargle20123839``. Go figure.

**Comment by bsipocz** [comment]
Updated the helpers version to the latest v2.0.2 release. When CI passes, this is good to get merged.

**Comment by mhvk** [comment]
OK, in it goes! Thanks, @astrofrog.

**Pull request merged**
