### PR TITLE
Updating spinner API, keeping enum

### LINKED ISSUE #11004: Outdated documentation for Spinner
### Description

The current docstring in the [Spinner](https://github.com/astropy/astropy/blob/ab1a1d3c776ff636b844be6799c1c9b91b32a21f/astropy/utils/console.py#L855) class demonstrates using `s.next()` to update the spinner.  But this is a Python 2-ism that no longer exists for iterators in Python 3.  Instead the correct documentation would be `next(s)`.

Additionally, I think it's confusing that the API for `Spinner` is so different from `ProgressBar` and `ProgressBarOrSpinner`.  In the latter two cases, their `__enter__` method (when using `with ProgressBar(...) as bar:` returns the `ProgressBar(OrSpinner)` instance itself, which is iterable itself.  It also provides an `update()` method which can be called to update the progress bar.  Whereas `with Spinner(...) as s:` does not return the `Spinner` instance itself, but rather a generator.

It should be easy to update the API for `Spinner` (make it iterable, make `__enter__` return the `Spinner` instance, and add an `update()` method) so that it is more like `ProgressBar`.

I would suggest making the updates to `Spinner` and fixing the documentation at the same time.

### PR DESCRIPTION
**Pull request by Iamsoto**
Updating the spinner API, keeping the original enum.
See #11015  for the alternative method (removing the enumerator)

Fixes #11004

### CODE REVIEW

**Comment by embray** [comment]
LGTM; can you please also add the change from https://github.com/astropy/astropy/pull/11015/files#diff-582a94e0a0f7293634d5bb6531b7bdf8a847ecd2a380ec691a65bac8beaff546L1040 ?

There's also the issue I raised on your other PR about the interpretation of the `step` argument maybe actually being buggy.  If you agree with me there should be a separate issue opened for that though.

**Comment by Iamsoto** [comment]
> LGTM; can you please also add the change from https://github.com/astropy/astropy/pull/11015/files#diff-582a94e0a0f7293634d5bb6531b7bdf8a847ecd2a380ec691a65bac8beaff546L1040 ?
> 
> There's also the issue I raised on your other PR about the interpretation of the `step` argument maybe actually being buggy. If you agree with me there should be a separate issue opened for that though.

Done!
Yeah, I just thought it would be better ettiquete to not needlessly modify code XD

**Comment by Iamsoto** [comment]
Ah! I just read your comment in the other PR about the bug in Step!
I don't mind making that another issue. Should I create the issue and resolve it before we merge this PR?

**Comment by embray** [comment]
@Iamsoto Sorry for the late reply.  Yes, let's open a separate issue for that.

**Comment by pllim** [comment]
Ops, sorry that this feel through the cracks. I'll just clean this up (i.e., fix the change log) and get this in. I also opened a follow-up issue at #11656.

**Comment by pllim** [comment]
Re-reading https://github.com/astropy/astropy/pull/11046#issuecomment-733225534 -- @embray , should we get this in, or move the milestone. Is #11656 blocking this PR?

**Comment by eteq** [comment]
Since this hasn't made the feature freeze cutoff and is not a bug/docfix I'm re-milestoning to 5.0

**Comment by embray** [comment]
I think it would be fine to address #11656 in a follow-up.  It's a nice "beginner" issue.

**Review by pllim — APPROVED** [review]
I don't think the failures were related.

**Comment by pllim** [comment]
@embray , I'll let you do the merge since I haven't seen any formal approval from you yet.

**Comment by pllim** [comment]
Actually, the timeout might be real. `main` now consistently times out after the merge of this PR. We need a follow-up patch or revert.

**Comment by embray** [comment]
Wow....hard to imagine why

**Comment by pllim** [comment]
Could be a coincidence though I restarted the build a few times and it is consistently timing out. Maybe I'll ping @astrojuanlu to make sure this is not a server-side problem...

**Comment by embray** [comment]
If anything it would be due to #11690 which I also just merged.

**Comment by pllim** [comment]
But the first incident happened with this merge, according to https://readthedocs.org/projects/astropy/builds/

**Comment by embray** [comment]
Yes, and RTD built that PR fine...

**Pull request merged**
