### PR TITLE
Fixes issue #3551: Improve documentation of WCS.calc_footprint

### PR DESCRIPTION
**Pull request by vortex-ape**

### CODE REVIEW

**Comment by astrofrog** [comment]
@vortex-ape - why did you close this?

**Comment by vortex-ape** [comment]
I had some problems with branching, yesterday I pushed a third commit to #3552 and it ended up in this pull request. Sorting it out right now.

**Comment by embray** [comment]
If you add a commit to the wrong branch and then accidentally push it upstream you can usually correct that.  On your local repository just use the `git reset` command to move your branch back to a previous commit (i.e. before the commit you added by mistake).  Then you can push up to your fork on GitHub using `git push --force origin <name-of-branch>`.  I don't advocate use of `--force` in most cases, but it when it's just going to your own fork of some other repository it can't hurt anything else.

It's very easy to make mistakes in git, but it's also very forgiving of mistakes (short of `rm -rf`ing your repository) and most mistakes can be corrected.  You can always ask here or in the dev mailing list if you run into something (I also need to start advocating the IRC channel again...)

**Comment by vortex-ape** [comment]
I knew basic git and was new to branching etc, so didn't branch and instead pushed the commit from the master branch. But after much googling, I resolved it somehow. :smile:

**Comment by embray** [comment]
Ah, yeah, making a PR from your master is a problem.  I think that's why we encourage new committers to just delete their master branch entirely ;)  That can be worked around too by making a new local branch that tracks upstream master, but whatever.  It's no problem.

**Pull request closed without merging**
