### PR TITLE
BUG: fix size of rotated ticks in plots using WCS projection

### LINKED ISSUE #7964: Improve tick label positioning when ticks are at an angle
The following example from the test suite (``test_tick_angles_non_square_axes``) illustrates a problem which is that the vertical position of the ticks is related to where the tick intercepts the spines:

test_tick_angles_non_square_axes

but it should probably instead be related to where the end of the tick is. This is especially clear when the ticks are long, as above. I'm labelling this as a bug but it's probably a borderline case.

If anyone wants to dig into this, I think the code to modify will be in ``tick_labels.py``.

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
Fixes #7964

I expect this will take a couple more iterations as CI might uncover some edge cases I haven't thought about, and divide-by-zero errors also need to be handled.
I'll avoid committing a changelog fragment at first because it's not 100% clear whether this qualifies as a bug fix or a small feature. Feedback on this point would be appreciated.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
doc builds are timing out. I haven't been able to pin down exactly why, but I suspect that this solution isn't viable and that the problem it's trying to solve may be best left alone. See my comment in the issue https://github.com/astropy/astropy/issues/7964#issuecomment-1900001035

I'll keep this PR around as a draft for now, but my current recommendation is to close it alongside the issue.

**Comment by pllim** [comment]
The PR would auto-close by a bot if it goes stale. The issue, however, would need input from @astrofrog .

**Comment by neutrinoceros** [comment]
Let's try again: @astrofrog, any inputs ? :)

**Review by astrofrog — COMMENTED** [review]
I think the issue described in https://github.com/astropy/astropy/issues/7964 is not really to do with the ticks but the tick labels - that is I don't think we should change the size of the ticks depending on rotation, as the ticks might get *realllly* long if the grid lines are almost parallel to an axis. I think it would be better to be smarter about the tick location.

**Pull request closed without merging**
