### PR TITLE
Add removestar

### LINKED ISSUE #15270: Add remove-star pre-commit
### What is the problem this feature will solve?

Ensure only `__init__.py` files have `import *`

### Describe the desired outcome

Enforce this with pre-commit.

I opened an issue in the repo https://github.com/asmeurer/removestar/issues/33 asking if this tool could add a pre-commit hook. Unfortunately this repo is not actively maintained. Thankfully someone noticed my issue and forked the
repo — https://github.com/Saransh-cpp/rmstar/ — and is working on a pre-commit hook.
When it's ready we should add it to pre-commit.

### Additional context

Adding / removing from pre-commit is very easy and if something breaks it only affects CI, not the actual code, so the stakes are low to add hooks.

### PR DESCRIPTION
**Pull request by Saransh-cpp**
### Description

Added `removestar` as a pre-commit hook.

Fixes #15270 

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Please ignore star import in `docs/conf.py`.

**Comment by nstarman** [comment]
CleanShot 2023-09-05 at 22 56 19

Glad to see everything passing! It would be great if it the verbose output was only if something fails.

**Comment by Saransh-cpp** [comment]
Done! I'll mark this as ready for review as soon as I make a new release for removestar.

**Comment by Saransh-cpp** [comment]
I think everything is working now!

**Comment by nstarman** [comment]
This looks great to me! Thanks @Saransh-cpp for all the hard work. Let's get another maintainer to approve before merging.

Ping @pllim @WilliamJamieson :)

**Review by nstarman — APPROVED** [review]

**Review by WilliamJamieson — APPROVED** [review]

**Comment by nstarman** [comment]
Awesome! No more star imports, except where we specifically allow. Thanks @Saransh-cpp.

**Pull request merged**
