### PR TITLE
Fixed mixed tabs and spaces ascii reading

### LINKED ISSUE #6770: Table with mixed whitespace and tabs worked in 2.0.2, but fails now
The following code works in 2.0.2:
```
from astropy.table import Table
tabtxt = ['1 2\t3','1 2\t3']
Table.read(tabtxt, format='ascii.no_header', names=['a','b','c'])
```
but fails in the current master.
Git bisect lead me to this commit: https://github.com/astropy/astropy/commit/1d14eff6756371f12970b3a6f8939d752cb2b793 but I can't quite figure out why that caused the change.

In any case, I think this is a significant API change which was probably unintentional.

@bsipocz made that commit as part of a larger python2/3 cleanup
@taldcroft

### PR DESCRIPTION
**Pull request by MSeifert04**
fixes #6770 

I seriously have no idea where I should put the test. But it worked locally with the sample in the bug report.

### CODE REVIEW

**Comment by bsipocz** [comment]
I can't see why this would work but not the original, but if works, sure.

For the test, I would guess either test_rst or test_read? both has differently formatted input.

**Comment by MSeifert04** [comment]
Because it permanently changed `self.delimiter` - while this approach just uses a different delimiter which is used by `csv.reader`.

**Comment by hamogu** [comment]
Wow, you are fast. Looks totally good to me (except for the test that @bsipocz ) already mentioned. I found this because one of the packages I develop for a local laboratory setup worked for ASTROPY=stable, but failed for the development version. I just walk into out group meeting and when I come back out there is already a PR for it!

**Comment by bsipocz** [comment]
ohh, ok, a few lines above this there is one of 
``line = _replace_tab_with_space(line, self.escapechar, self.quotechar)``, and with my hack, it didn't get run.

Thanks @MSeifert04 for the fix, and @hamogu to catch it before a release.

**Comment by bsipocz** [comment]
I actually very much like that there is more and more feedback from downstream packages that they run into issue during the dev testing. This is so useful to catch these while they are yet out to the wild.

**Comment by hamogu** [comment]
It's like having hundreds of extra unit tests for free. Never thought of it that way before.

**Comment by bsipocz** [comment]
Lately I'm thinking a lot about how we could make sure this feedback is getting back to us. Probably the only viable route is to make sure the maintainers report them back, but would be good to brainstorm a bit on this next time a lot of us are in the same room (virtually or otherwise).

**Comment by MSeifert04** [comment]
ok, I added the test and the CI passed.

**Comment by bsipocz** [comment]
Thanks @MSeifert04!

**Pull request merged**
