### PR TITLE
MNT: Remove BLS and LS from stats API

### LINKED ISSUE #10349: Remove duplicated API references
Both LS and BLS are still listed in the stats API references generated by automodapi while there have been moved to timeseries and deprecated from the stats namespace.

A well placed `__all__` would probably be enough to avoid this.

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to hide deprecated APIs in `stats` that have been moved over to `timeseries`.

**Note to reviewer:** Please check rendered doc carefully and also the remote data test job that is allowed to fail.

Fixes #10349

### CODE REVIEW

**Comment by pllim** [comment]
Remote data tests passed.

And I think unwanted API doc is gone? https://68547-2081289-gh.circle-artifacts.com/0/docs/_build/html/stats/index.html#reference-api

**Comment by bsipocz** [comment]
Unfortunately this is not working as expected, the following import should still work in the deprecation period:
```
from astropy.stats import LombScargle 
```

**Comment by bsipocz** [comment]
An alternative solution is here, branched from the same place as this your branch here: https://github.com/bsipocz/astropy/tree/pllim_ls_bls_api

It's a tiny bit verbose, but with the added benefit of being unambiguous, too.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/pull/10350#issuecomment-651640976

Nice trick in extending the `__all__`, @bsipocz ! My only comment is to add a note to undo that when we remove the deprecated stuff. Do you want to open a PR with that branch and I can close this one *without* merge? If not, I can cherry-pick your commit and open a new PR with it too but that is more work for me. Thanks!

**Comment by bsipocz** [comment]
Or do this explicitly for all the submodules  Currently there is a certain kind of mess all around, I would not be surprised if e.g. numpy is being exposed a dozen times in wild imports...
(Cleaning up namespaces was on my todo list for a while)

**Comment by pllim** [comment]
> Or do this explicitly for all the submodules

Interesting idea, but that would be out of scope of this PR.

So, how do you wish to proceed with this one? Please advise. Thanks!

**Comment by bsipocz** [comment]
I'll go ahead and open a PR, I think that's slightly less effort.

**Comment by pllim** [comment]
Okay, I'll close this one then. I am sorry this patch does not solve the problem. Thanks!

**Pull request closed without merging**
