### PR TITLE
Speed up Column.__getitem__ in general

### PR DESCRIPTION
**Pull request by embray**
Alternative to #3930--speed up `Column.__getitem__` using Cython base classes.  This eliminates most of the overhead associated with calling pure-Python `__getitem__`, and speeds up the body of the method as well.

This is a more general solution than the one in #3930--I think this could be useful for #3915.  Checking whether the indices need to be updated adds only a trivial amount of overhead, so we can perform that check in the actual `__getitem__` without incurring additional overhead.  So unless we still want to be able to use `table[slice]` without incurring index adjustment overhead, the `get_item` methods won't be necessary.

### CODE REVIEW

**Comment by embray** [comment]
The one thing I don't like about this is the duplicate code in `_ColumnGetitemShim` and `_MaskedColumnGetitemShim`.  I really tried to find a workaround to that, but anything I could come up with added noticeable overhead.

**Comment by taldcroft** [comment]
This looks good to me, and hurts my brain less, as long as it's fast!

**Comment by embray** [comment]
I'll try to get some performance results up on this PR.  From my rough testing though this adds < 1% overhead compared to the base `__getitem__`.

**Comment by embray** [comment]
Added a regression test proving that this PR also fixes #4098--also rebased this on top of #4099 so that the test I added can pass.

**Comment by embray** [comment]
Would be good to merge this sooner rather than later since it fixes #4098.  However, I'm not sure what impact that will have on #3915.  I don't want to introduce too many merge conflicts (though I don't think any such conflict will be too difficult to overcome...)

**Comment by embray** [comment]
Updated to incorporate #3915 / #4202.

As I noted previously, this makes the 'copy_on_getitem' index mode is now a no-op since that's the default behavior.  We could still change this so that it's not the default behavior, if we prefer, or add a no_copy_on_getitem mode instead.  @taldcroft ? @mdmueller ?

**Comment by embray** [comment]
(To clarify, we could still make the default behavior be to *not* copy the indices on a slice. I wasn't sure which way is preferable, and if the current *non-copy* default was just chosen to not slow down `__getitem__` of columns with no index.)

**Comment by taldcroft** [comment]
@embray - the current *non-copy* default was more chosen to not slow down `__getitem__` of columns *with* an index.  The idea was that normally if you are slicing an individual column that happens to be an index in the table, you don't usually want the index to come along for the ride.  This re-indexing can be pretty slow.

**Comment by embray** [comment]
Okay, I wondered about that.  In that case I'll restore the original default.  This PR should still speed things up in either case since it does away with the penalty of having a `__getitem__` in Python.

**Comment by taldcroft** [comment]
Sounds good, thanks.

**Comment by embray** [comment]
Okay, I restored the original default behavior.  In order to get this working right without sacrificing performance I went back on some of @mdmueller's original implementation, or at least something that looks like it (but still without any need for the `get_item` methods).  But this still keeps the performance benefits of my original code as well.

**Comment by embray** [comment]
Apparently I suck at testing on Python 2...

**Comment by taldcroft** [comment]
@embray - I don't have time this weekend for detailed review on this, but I'm trusting that the table testing is sufficiently complete.  Have you done some simple %timeit performance testing comparing this to master?

**Comment by mhvk** [comment]
@embray - this looks good, and cleaner than before (though I cannot judge the cython very well). What seems to be missing, though, are some comments that explain why we are doing this at all. The original shim class had relevant comments; maybe put those either in the `pyx` file or below the `Column` class definition (to explain why it is subclassing the shim). Otherwise, I worry that a few years from now we have no clue anymore why this is being done...

**Comment by mhvk** [comment]
p.s.  I even wonder if we should have a section in the developer docs with "tips & tricks", where we summarize these types of speed-ups and their rationale.  Indeed, my shape-changing mixin would be another good addition...

**Comment by embray** [comment]
I'll add some better explanatory comments before merging.

@taldcroft Concerning timing this adds a tiny slowdown compared to the stock `ndarray.__getitem__`, solely due to the dimension check which is adding like a handful of instructions.  So we're dabbling in difference of a nanosecond or two if that--really less than a timer can measure accurately anyways.

**Comment by taldcroft** [comment]
@embray - that's definitely in the noise, so no problem!  Thanks for working on this.

**Comment by astrofrog** [comment]
@embray - could you add the comments in the next hour or so? It would be nice to get this in 1.1 if possible.

**Comment by astrofrog** [comment]
I'm going to branch v1.1, but we can consider merging this in after since it's just a performance fix.

**Comment by embray** [comment]
Oh, this is still open...  let me add those aforementioned comments and then merge.

**Comment by taldcroft** [comment]
:+1:

**Pull request merged**
