### PR TITLE
Update references.txt

### PR DESCRIPTION
**Pull request by demitri**
Updating broken link for wcslib.

### CODE REVIEW

**Comment by pllim** [comment]
Seems uncontroversial enough. Except I am not sure what to milestone this to -- 1.1.3 for "bug fix", or 1.2 (next major release)?

**Comment by demitri** [comment]
I can't imagine anyone would object to this being pulled ASAP.

**Comment by bsipocz** [comment]
@pllim - As I recall the milestone guidelines for docs fixes are that they should go in asap, unless the change is affect-dev only.

**Comment by pllim** [comment]
So, does this mean 1.1.3?

**Comment by bsipocz** [comment]
I guess yes. 
(Ideally it should go into 1.0.10, but since there are only two version aliases of the docs "stable" and "latest", I think we can avoid at least one of the backporting.)

**Comment by pllim** [comment]
I don't see any reason not to merge now, so I am merging this. Someone else can come back and change the milestone if I put the wrong one there...

**Pull request merged**
