### PR TITLE
remove unused import of copy

### PR DESCRIPTION
**Pull request by fchapoton**

### CODE REVIEW

**Comment by pllim** [comment]
Looks like it was introduced in #8252 . Good catch! `html-docs` failure is unrelated.

**Comment by pllim** [comment]
@Cadair , is there a reason why you needed this `import copy`?

**Comment by nden** [comment]
This may be my fault. Isn't there a flake8 job/check that catches these? It's not needed. Thanks, 
 @fchapoton .

**Comment by bsipocz** [comment]
@nden - our flake8 job is still too forgiving, I agree that it should be checking these (and more).

**Comment by bsipocz** [comment]
Thanks @fchapoton!

**Pull request merged**
