### PR TITLE
Ruff: more pydocstyle

### PR DESCRIPTION
**Pull request by nstarman**
I think the only controversial one here is D412 vs D410. If it's too controversial I can drop that from this PR and we can tackle that separately.

D410: Missing blank line after section
D412: No blank lines allowed between a section header and its content

As a note: NumPyDoc, which we have as as our docstring standard, uses D412. That's why I've chosen to implement D412 in this PR.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by nstarman** [comment]
RTD failure is real. Darn.

**Review by mhvk — APPROVED** [review]
Looks good to me! I'm in favour of not having the extra blank line; the set of dashes makes it all clear enough (and I like to see more of things in one screenful).

Approving modulo of course any fixes needed to make sphinx happy again.

**Comment by nstarman** [comment]
Sphinx is happy.

**Comment by dhomeier** [comment]
> Looks good to me! I'm in favour of not having the extra blank line; the set of dashes makes it all clear enough (and I like to see more of things in one screenful).

Personally I find it less readable without the separation (and a poor compensation for all the extra lines dumped in by black anyway), but if those are the current pydocstyle rules, can live with it.
@nstarman could you put in links to what "D412" and "D410" are? Would make it a lot easier than for every reviewer having to dig out the pycodestyle, flake8 or ruff docs.

**Comment by nstarman** [comment]
> @nstarman could you put in links to what "D412" and "D410" are? Would make it a lot easier than for every reviewer having to dig out the pycodestyle, flake8 or ruff docs.

Done!
Also I noted that numpydoc (which we try to stick to) uses D412.

**Comment by nstarman** [comment]
Basically, just avoid having a 1-line sentence fragment exactly match the reserved name for a section.

```
Example:
```

looks like an improperly formatted

```
Example
————-
```

while

```
For example:
```

does not.

**Comment by dhomeier** [comment]
I guess I am struggling to figure out where e.g.
https://github.com/astropy/astropy/blob/eccdccfdf332ecb9b3889cc14fb798f79eadd379/astropy/io/misc/parquet.py#L87
would be a section name with missing underline, and where a poorly phrased heading, but that's probably what the auto-formatters are there for.

**Review by mcara — APPROVED** [review]
Absolutely perfect from WCS perspective!
Many thanks!

**Review by WilliamJamieson — APPROVED** [review]
These changes are fine with me.

@nstarman when do you want to set the `pydocstyle` convention: https://github.com/charliermarsh/ruff#does-ruff-support-numpy--or-google-style-docstrings?

**Pull request merged**
