### PR TITLE
MNT: Pin pyerfa maxversion in LTS

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to pin pyerfa maxversion in LTS because pyerfa 2.0.1 does not provide wheels for combo that is compatible with requirements in this branch and it cannot be built from source because it needs numpy>=1.25 to build because it dropped oldest-supported-numpy, but LTS here pinned numpy<1.25 for other reasons.

xref https://github.com/astropy/astropy/pull/15481

This makes https://github.com/astropy/astropy/pull/15478 kinda unnecessary but does not hurt to keep it.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
The wheel passed now. RTD failure is unrelated (it confused itself so maybe it will pass again when the active build that is running actually phones home to the PR?). But let's wait for the rest of CI.

**Review by mhvk — APPROVED** [review]
I dislike that because of changes in how we build things, we are now forced to exclude package versions; that seems a plain regression.

 But practically, given that LTS will not be around much longer, I don't see much harm in just doing the simple thing for now.

**Comment by pllim** [comment]
Should I keep this open to see where https://github.com/liberfa/pyerfa/issues/119 discussions go?

**Comment by pllim** [comment]
p.s. Can ignore the OSX failure; it is unrelated.

**Comment by mhvk** [comment]
It is annoying if backports fail just because of this, but maybe a few more days?

**Comment by astrofrog** [comment]
Ok so I investigated this, and the issue is related to manylinux versions. First, if we look at the installation of the test dependencies in the wheel build, we see:

```
  Collecting numpy<1.25,>=1.18 (from astropy==5.0.9.dev29+g6288c8520c)
    Downloading numpy-1.24.4.tar.gz (10.9 MB)
...
  Collecting pyerfa>=2.0 (from astropy==5.0.9.dev29+g6288c8520c)
    Downloading pyerfa-2.0.1.tar.gz (817 kB)
...
              ../../meson.build:30:4: ERROR: Problem encountered: NumPy requires GCC >= 8.4
```

Numpy itself is being installed from source as a dependency of astropy so this is not an issue specific to PyERFA. The reason this is happening is because the builds for Python <=3.9 use manylinux2010 which is a very old version. Since Numpy 1.22, numpy wheels are only available for manylinux2014. Similarly, PyERFA only has manylinux2014 wheels.

Installing Numpy from source as a test dependency works (because it is installing 1.24). However, installing Numpy as a build dependency for PyERFA is failing because it is trying to install 1.26 but GCC 8 is needed.

Note that in practice there is no bug as such in terms of users and nothing to fix or pin in general. This will only affect users who have old versions of Linux that won't accept manylinux2014 wheels which will be pretty rare. Those users will see source packages instead of wheels being used, and if a user does not have a recent enough gcc, the error message when installing astropy from source should be clear - they need to install a more recent gcc.

There are two possible fixes here:

* Install gcc8+ in the wheel building image - this will ensure that we continue to build manylinux2010 wheels for Python <= 3.9 for astropy LTS, which will then avoid the possibility of users having to install things from source.

* Upgrade manylinux for Python <=3.9 to 2014 as we did in ``main``

I'll open PRs for both options since both should be easy enough. I don't really have a strong opinion either way, and this will be moot soon once 6.0.0 is released!




The issue here is not *really* that PyERFA is being downloaded from source, but more that Numpy 1.26 cannot be

**Comment by astrofrog** [comment]
The first option (upgrading the compiler) is a bad idea in fact since it changes the compilation environment of manylinux2010 in a way that might not end up making 'real' manylinux2010 wheels. The next best solution is to stop using manylinux2010 for our wheels.

Note that actual *users* who have an old OS can upgrade compilers without any issues because they are just building wheels for themselves. We just can't upgrade the compiler to distribute the 'public' manylinux2010 wheels.

**Comment by pllim** [comment]
Okay... though we already max pinned several things in LTS. So unless the new pyerfa fixes a critical bug that would crash telescopes, I don't see the big deal since this branch is dying in a couple of months. Let's try it your way then. Thanks!

**Pull request closed without merging**
