### PR TITLE
Fixed failing VO Cone Search tests

### PR DESCRIPTION
**Pull request by pllim**
Fixed failing VO Cone Search tests by removing flaky service or replacing it with hopefully a more stable one. This needs to be merged so @embray can proceed with #2970.

This update goes hand-in-hand with a change in http://stsdas.stsci.edu/astrolib/vo_databases/conesearch_simple.json . This means, affected remote-data test(s) for *older* version of Astropy that used to pass will now fail.

All tests passed (with 1 `xfail`) when I do the following in Python 2.7.5:
```python
>>> import astropy
>>> astropy.test('vo', remote_data=True)
```

I did not test it in Python 3 but I did not make changes where the Python version would matter anyway.

### CODE REVIEW

**Comment by astrofrog** [comment]
@embray - marked this as 1.1, but should it be 1.0.5? (or maybe not since not critical)

**Comment by pllim** [comment]
If you want a fully successful remote data test result, you will need this.

**Comment by astrofrog** [comment]
I'm going to go ahead and merge this since we'll want it in 1.1 and it can then also be backported to 1.0.6 if needed.

**Comment by embray** [comment]
Cherry-picked to 1.0.x branch:  861d065

**Pull request merged**
