### PR TITLE
Prevent warnings about HIERARCH with CompImageHeader class

### LINKED ISSUE #11403: Trying to set a HIERARCH keyword in a FITS Header warns about needing to use HIERARCH
### Description

I would like to set a HIERARCH keyword in a FITS header without being told that I need to use HIERARCH.

### Expected behavior

No warning to be issued.

### Actual behavior

There is a warning.

### Steps to Reproduce

```python
>>> import astropy.io.fits as fits
>>> filename = fits.util.get_testdata_filepath('compressed_image.fits')
>>> hdul = fits.open(filename)
>>> hdul[1].header["HIERARCH ASTRO METADATA FIX"] = 42
WARNING: VerifyWarning: Keyword name 'ASTRO METADATA FIX' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]
```

My guess is that setting a HIERARCH key in `Header` strips the `HIERARCH` from the name and then constructs a `Card` without it and that complains.

### System Details

```python
>>> import platform; print(platform.platform())
macOS-10.16-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:12:38) 
[Clang 11.0.1 ]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.20.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.3.dev680+gc5369e660.d20210319
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.6.0
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.3.4
```

### PR DESCRIPTION
**Pull request by timj**
### Description

Compressed image headers warn when you try to assign a HIERARCH keyword but normal image headers don't.

The underlying problem is that `Card.keyword` strips the HIERARCH and CompImageHeader tries to reconstruct a Card from the keyword of that card. I fix it by checking if the Card itself starts with HIERARCH already and reapply it.

This pull request is to address #11403 

Fixes #11403

### CODE REVIEW

**Comment by timj** [comment]
I'm not entirely sure how to test for "this thing did not warn". There are plenty of examples for warnings being issued. Do I do something like:

```
with assertWarns:
    run code that does not warn
    issue a warning myself

assert that I only got the warning I issued
```
?

**Comment by pllim** [comment]
The global warning config for `pytest` is here:

https://github.com/astropy/astropy/blob/aed5138bc5d22a89caa956bcdff641673b43dede/setup.cfg#L115-L141

With this setup, if you do nothing, all unexpected warnings, except those globally ignored, will turn into an exception. So, if you want to test that something should not raise a warning, no special code is needed. But be careful if the warning you are interested in is already ignored by `pytest` above.

If you want to make sure your code is raising the correct warning, use `pytest.warns`. More info at https://docs.pytest.org/en/stable/warnings.html . Hope this helps!

**Comment by timj** [comment]
I've pushed a test. The failure is the samp one again.

**Comment by pllim** [comment]
Don't worry about the `samp` failure. If it keeps happening across the PRs, I'll think of something. Thanks for letting us know!

**Comment by saimn** [comment]
In that case I think it's better to test explicitly that no warning were raised, which can be done with `pytest.warns(None)` (you can find examples in astropy if you need).

**Comment by timj** [comment]
I've updated the test as requested above. I assume the documentation failure is nothing to do with this change.

**Comment by pllim** [comment]
Yeah, matplotlib 3.4.0 release last night broke RTD.

**Comment by embray** [comment]
Thanks for the fix.  Looks good to me!

**Comment by saimn** [comment]
Looks good to me too. @timj - could you rebase on master and add a changelog entry as described in https://github.com/astropy/astropy/blob/master/docs/changes/README.rst ? Thanks.

**Comment by timj** [comment]
I've rebased and added a change log entry.

**Review by saimn — APPROVED** [review]
Thanks @timj!

**Pull request merged**
