### PR TITLE
Changed 1st modeling example to be fitting a line

### LINKED ISSUE #9132: Write a better starting example in the modeling documentation
The example should show model evaluation and fitting.

### PR DESCRIPTION
**Pull request by karllark**
A better 1st example for the main modeling page is a linear fit to data with noise.  More general case so should be of interest to more users.

Closes #9132

### CODE REVIEW

**Comment by nden** [comment]
`asdf 2.4.1` was released yesterday. `asdf` uses `SpecItem` from `semantic_version`. A new version of `semantic_version` was released today and it raises the `DeprecationWarning` which breaks tests in astropy.

**Comment by nden** [comment]
@karllark The problem with asdf is now fixed and Travis tests passed. The flake8 tests are failing

https://travis-ci.org/astropy/astropy/jobs/578431008#L526

It's not something you changed, so could you fix those two lines or rebase.

**Comment by karllark** [comment]
Rebase done.

**Comment by karllark** [comment]
Rebase did not fix the flake8 error in table.py.  Fixed it manually.

**Pull request merged**
