### PR TITLE
Update CircleCI configuration in v2.0.x

### PR DESCRIPTION
**Pull request by astrofrog**
This backports the recent PRs that update the CircleCI configuration to v2.0.x. I'm doing this as part of a PR to have a chance to make sure it actually works because I had to fix some conflicts and some changes were not relevant to v2.0.x. I also enabled Python 2.7 32-bit testing.

@bsipocz - there are no changelog entries involved, so do we need to do anything special in terms of the backports scripts to make sure this doesn't cause issues? Maybe I should remilestone #7126 and #7150 as 2.0.5?

### CODE REVIEW

**Comment by astrofrog** [comment]
@mhvk - see the latest commit - do you have any idea why this fix would only be required for Python 2.7? (it doesn't seem to be needed with Python 3.x which is why we didn't see it in Astropy master)

**Comment by mhvk** [comment]
@astrofrog - you mean the `einsum` one, correct? There was another bug where on python2 a wrong isinstance was done: https://github.com/numpy/numpy/issues/10369. I'm guessing that caused the problem; it is also solved by `optimize=False`, since then the C path is taken, which doesn't suffer from the problem (and is faster, so it is good on python3 too).

**Comment by astrofrog** [comment]
@mhvk - yes, that's what I meant. Does this mean I should 'forward-port' the fix here to master too?

**Comment by mhvk** [comment]
Yes, let's. I doubt many people will be using numpy 1.14.0 but we might as well prevent unnecessary slow-down.

**Comment by astrofrog** [comment]
Ok, PR forthcoming

**Comment by astrofrog** [comment]
@mhvk - see https://github.com/astropy/astropy/pull/7187 - let's merge that one then I'll backport it to this PR instead of the existing commit.

**Comment by astrofrog** [comment]
This should not be merged as we should push the backports directly to v2.0.x, but I'm using this to check the CI.

**Comment by astrofrog** [comment]
@bsipocz - I actually merged this manually

**Comment by astrofrog** [comment]
@eteq - did you remove Work in Progress manually or do you have a bot?

**Pull request merged**
