### PR TITLE
Added a Quadrangle patch for WCSAxes

### PR DESCRIPTION
**Pull request by ayshih**
This PR adds a new patch (`Quadrangle`) for plotting with WCSAxes.  A [quadrangle](https://en.wikipedia.org/wiki/Quadrangle_(geography)) has edges that lie on lines of constant longitude and constant latitude.  Unlike `matplotlib.patches.Rectangle`, the edges of this patch will render as curved lines if appropriate for the WCS transformation.  Also, `Quadrangle` accepts `Quantity` inputs.

- [x] Add tests
- [x] Add documentation

## Example using `Quadrangle` from this PR
I use SunPy for the example because the benefit is readily apparent.  Here's a quadrangle that spans 15 degrees in heliographic longitude and 60 degrees in heliographic latitude.
```python
import matplotlib.pyplot as plt

from astropy import units as u
from astropy.visualization.wcsaxes import Quadrangle

import sunpy.map
from sunpy.coordinates import HeliographicStonyhurst
from sunpy.data.sample import AIA_171_IMAGE

# Typical SunPy plot
aiamap = sunpy.map.Map(AIA_171_IMAGE)
ax = plt.subplot(projection=aiamap)
aiamap.plot(clip_interval=(1, 99.9)*u.percent)
aiamap.draw_grid()

# Add a `astropy.visualization.wcsaxes.Quadrangle`
heliographic_frame = HeliographicStonyhurst(obstime=aiamap.date)
q = Quadrangle((50, -10)*u.deg, 15*u.deg, 60*u.deg,
               edgecolor='blue', facecolor='none', linewidth=2,
               transform=ax.get_transform(heliographic_frame))
ax.add_patch(q)

plt.show()
```
Quadrangle

## Using `matplotlib.patches.Rectangle` instead
```python
from matplotlib.patches import Rectangle

# Typical SunPy plot
ax = plt.subplot(projection=aiamap)
aiamap.plot(clip_interval=(1, 99.9)*u.percent)
aiamap.draw_grid()

# Add a `matplotlib.patches.Rectangle`
r = Rectangle((50, -10), 15, 60,
              edgecolor='red', facecolor='none', linewidth=2,
              transform=ax.get_transform(heliographic_frame))
ax.add_patch(r)

plt.show()
```
Rectangle

### CODE REVIEW

**Comment by Cadair** [comment]
This looks awesome and is much easier than I thought it would be! It's a shame it doesn't have a way to access the unit of the frame in the constructor.

**Comment by ayshih** [comment]
Here's an (artificial) example that doesn't use anything from SunPy.  I have used `SkyOffsetFrame` to define a coordinate frame for the rectangle where the north pole is in the field of view:

```python
import matplotlib.pyplot as plt

import astropy.units as u
from astropy.coordinates import Galactic, SkyOffsetFrame
from astropy.io import fits
from astropy.utils.data import get_pkg_data_filename
from astropy.visualization.wcsaxes import WarpableRectangle
from astropy.wcs import WCS

# Plot the stock Galactic image
filename = get_pkg_data_filename('galactic_center/gc_msx_e.fits')
hdu = fits.open(filename)[0]
wcs = WCS(hdu.header)
ax = plt.subplot(projection=wcs)
ax.imshow(hdu.data, vmin=-2.e-5, vmax=2.e-4, origin='lower')

# Define a coordinate frame with the north pole in the field of view
sof = SkyOffsetFrame(origin=Galactic(5*u.arcmin, 1*u.arcmin - 90*u.deg))

# Plot the gridlines for this other coordinate frame
overlay = ax.get_coords_overlay(sof)
overlay.grid(color='white', ls='dotted')

# Add the rectangular patch (155 degrees by 6 arcmin)
wr = WarpableRectangle((-15, 89.6)*u.deg, 155.*u.deg, 6*u.arcmin, edgecolor='red', facecolor='none',
                       transform=ax.get_transform(sof))
ax.add_patch(wr)

plt.show()
```
sof

**Comment by astrofrog** [comment]
Very nice! So just to be clear this is different from if we were to implement a rectangle by connecting the four vertices by great circles right? (was trying to think whether the different naming convention compared to SphericalCircle was an issue)

**Comment by ayshih** [comment]
Yes, this is different because two of the edges are lines of constant latitude (i.e., parallels).  I'd call a rectangle with all four edges aligned with great circles to be a "spherical rectangle", but this is something else.  One term I see used is "latitude-longitude quadrangle".

Brainstorming alternative names for `WarpableRectangle`:
* `LonLatQuadrangle`
* `CartographicRectangle`
* ?

**Comment by ayshih** [comment]
I decided to change the name to `Quadrangle`, but I'm open to other suggestions.

**Comment by ayshih** [comment]
Here's a cleaner example that compares `Quadrangle` and `Rectangle` for an `ICRS` quadrangle (100 deg by 20 deg) on `Galactic` axes.

```python
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

import astropy.units as u
from astropy.coordinates import Galactic, ICRS
from astropy.io import fits
from astropy.utils.data import get_pkg_data_filename
from astropy.visualization.wcsaxes import Quadrangle
from astropy.wcs import WCS

# Use the WCS information from the stock Galactic image
filename = get_pkg_data_filename('galactic_center/gc_msx_e.fits')
hdu = fits.open(filename)[0]
wcs = WCS(hdu.header)

# Set the plot around the ICRS south pole
ax = plt.subplot(projection=wcs)
ax.set_xlim(0, 10000)
ax.set_ylim(-10000, 0)

# Overlay the ICRS coordinate grid
overlay = ax.get_coords_overlay(ICRS())
overlay.grid(color='black', ls='dotted')

# Add a quadrangle patch (100 degrees by 20 degrees)
q = Quadrangle((255, -70)*u.deg, 100*u.deg, 20*u.deg,
               label='Quadrangle', edgecolor='blue', facecolor='none',
               transform=ax.get_transform(ICRS()))
ax.add_patch(q)

# Add a rectangle patch (100 degrees by 20 degrees)
r = Rectangle((255, -70), 100, 20,
               label='Rectangle', edgecolor='red', facecolor='none', linestyle='--',
               transform=ax.get_transform(ICRS()))
ax.add_patch(r)

plt.legend(loc='upper right')
plt.show()
```
comparison

**Comment by ayshih** [comment]
I've added an image test, so I'm calling this PR ready for review

**Comment by ayshih** [comment]
For convenience, here's a link to the latest build of the docs write-up: https://astropy--10862.org.readthedocs.build/en/10862/visualization/wcsaxes/overlays.html#quadrangles

**Comment by astrofrog** [comment]
I'll review this shortly, thanks!

**Review by Cadair — APPROVED** [review]
Looks good to me, everything I can think of to make it "better" involves it being attached to the axes!

**Review by astrofrog — APPROVED** [review]
Looks great and happy with the patch name - thanks!

**Pull request merged**
