### PR TITLE
Added known issue for #3587, and add high-level categories to the known issues page

### PR DESCRIPTION
**Pull request by embray**
This issue has come up so many times it's worth noting in the docs (see #3587, #3278, #3237, #3536, #3387, also [here](https://github.com/astropy/astropy/pull/3255#issuecomment-68449966) and [here](https://github.com/astropy/astropy/pull/3316#issuecomment-70694704), and possibly others).

Hopefully this will help a little.

### CODE REVIEW

**Comment by embray** [comment]
While we're in here, there might be some items we can removed from Known Issues since they no longer apply, at least not in the current version.  But I'm not entirely sure either.

* [This one](http://docs.astropy.org/en/stable/known_issues.html#some-docstrings-can-not-be-displayed-in-ipython-0-13-2) only pertains to pretty old versions of IPython--some people might still have those lying around so maybe it's worth keeping, but eventually maybe we can recommend a minimum version of IPython instead...

* [This one](http://docs.astropy.org/en/stable/known_issues.html#id12) is only barely relevant, since the minimum Numpy version is 1.6.0.  Some users could have 1.6.0 or 1.6.1, but really they should upgrade to the latest 1.6.x if indeed they have any reason to be on 1.6.x at all.

* Do we still care about [this one](http://docs.astropy.org/en/stable/known_issues.html#id18), or is it possible it could still affect users upgrading from a much older Astropy?

**Comment by mhvk** [comment]
+1 to adding the new issue.  I'd advocate splitting the known issues in two groups:
1. "real" issues -- like quantities losing their units -- which require one to adapt one's code to work around them.
2. installation issues, and issues using older versions of other packages, which can be solved by reinstalling or upgrading.

One could think of the split also as being between problems for which there is or is not an open issue on github.

One advantage of this split is that there would be a good place to point people to who wish to contribute by solving some known issue.

**Comment by embray** [comment]
@mhvk I agree--I'll see if I can split known issues into those categories and add sub-headings for them.

**Comment by embray** [comment]
@mhvk I added something like your suggestion in 81b9d4e, and I think it looks pretty good.

This deviates somewhat from the original purpose of this PR, so if anyone cares I'll split it into a separate PR.  Seemed easy enough to piggyback though as long as we're updating the known issues page.

**Comment by taldcroft** [comment]
Thanks @embray this looks great (just focusing on the `Time` problem).

**Comment by mhvk** [comment]
Looks good!

**Pull request merged**
