### PR TITLE
Update fitsheader.py

### PR DESCRIPTION
**Pull request by mromanie**
### Description

Add a command-line argument (-r/--replace_spaces) to replaces spaces in keyword values. The new functionality only applies to output in tabular format, i.e. f/--fitsort or -t/--table. The scope of the change is to make the output easier to handle as space-separated ascii columns.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
I have some questions:

1. Doesn't removing spaces from values actually change their meanings? 
2. What are you replacing the spaces with?
3. Why does it have to be exposed via command line? You can probably sanitize the data on your end using Python scripts and such without this patch?
4. Is the unified IO via `Table.read` not working for you as-is?

**Comment by pllim** [comment]
Thanks for your response, @mromanie . Let's step back a little; what do you do with the terminal output from fitsheader ? What is your end goal here? Perhaps this is easier to accomplish in a Python session or using existing astropy functionality without having to introduce a new option into the CLI.

**Comment by mromanie** [comment]
I guess you're right that anything I might want to do with the output can be easily done in python session, but I like the convenience of not having to open one, and use the convenience of the command-line tool, instead (which I guess it's why it's there in the first place).

Concrete example: run fitsheader, pipe the result into a file to send to a collaborator who has an easy way to treat the columns individually.

**Comment by tomdonaldson** [comment]
My sense is that `fitsheader` is not the best place for custom adjustments to the keyword values.  If the goal is to avoid getting into the python scripting, then shell scripting may be another good option.  

There are several unix commands that can help.  `awk` is powerful so can be tweaked quite a bit.  As a quick example, if `fitsheader myfile.fits --table` would output this:
```
|    filename | hdu |  keyword |                                                             value |
| myfile.fits |   0 |   SIMPLE |                                                              True |
| myfile.fits |   0 |   BITPIX |                                                               -32 |
| myfile.fits |   0 |    NAXIS |                                                                 2 |
| myfile.fits |   0 |   NAXIS1 |                                                               512 |
| myfile.fits |   0 |   NAXIS2 |                                                              1024 |
.
.
.
```

then piping that through an `awk` command which identifies the columns by `|` and substitutes spaces in the keyword values with underscores would look like the command below.  Granted it's a little cryptic, but not too bad to digest.  The `OFS=FS` just forces the output to use the `|` separator.  The `gsub()` substitutes the underscore for spaces in the 5th column, and the `print $0` just outputs the original columns with the substitutions:
```
fitsheader myfile.fits --table |  awk -F "|" 'BEGIN {OFS = FS} {gsub(" ", "_", $5); print $0}'
```
and would output:
```
|    filename | hdu |  keyword |_____________________________________________________________value_|
| myfile.fits |   0 |   SIMPLE |______________________________________________________________True_|
| myfile.fits |   0 |   BITPIX |_______________________________________________________________-32_|
| myfile.fits |   0 |    NAXIS |_________________________________________________________________2_|
| myfile.fits |   0 |   NAXIS1 |_______________________________________________________________512_|
| myfile.fits |   0 |   NAXIS2 |______________________________________________________________1024_|
.
.
.
```

**Comment by mromanie** [comment]
Many thanks to both!

I see the reasons not to have `fitsheader` mess with the content of the headers, but just to display it. I'd suggest the following:

- Add a column separator, e.g. |, to the `fitsort` output as well, to allow for shell manipulation like the one mentioned above. Side note: since the goal is to replace the spaces in the keyword values, but not the ones added by the formatting, the `awk` line would probably look something like: `awk 'BEGIN{FS=OFS="|"}{gsub(/^[ \t]+/,"",$5);gsub(/[ \t]+$/,"",$5)}1' | awk -F "|" 'BEGIN {OFS = FS} {gsub(" ", "_", $5); print $0}'`.
- Have the `main` of `fitsheader.py` return the table is created, for convenient manipulation directly in python. Or, @pllim,  did you have a different mechanism in mind for it?

**Comment by pllim** [comment]
> convenient manipulation directly in python

You can try this in a Python session without any changes to the `astropy` code:

```python
from astropy.io.fits.scripts import fitsheader

filename = 'jbt7a3020_drz.fits'  # Replace with your filename
extensions = [0, 1]  # This grabs the first 2. If you only want primary header, use [0]; and so on

formatter = fitsheader.TableHeaderFormatter(filename)
tbl = formatter.parse(extensions=extensions)
```

`tbl` is a proper `astropy.table.Table` instance, so you can manipulate it as documented in https://docs.astropy.org/en/stable/table/index.html .

Admittedly, I got that snippet by code-diving `fitsheader.py`. The Python interface is not really documented in the rendered HTML documentation, though the docstring is pretty informative. Also, it is no way as cool as Tom's AWK incantation.

https://github.com/astropy/astropy/blob/d9446df90939b513dd7a5e20812beace873c8f6f/astropy/io/fits/scripts/fitsheader.py#L116-L140

**Comment by saimn** [comment]
I agree the current proposed change is not desirable, `fitsheader` should not modify the keyword values. 

The non-`fitsort` mode (`--table`) already accepts a format parameter, set to `ascii.fixed_width` by default. It should be easy to add this feature to the `fitsort` mode as well. It would allow to use csv for example.
Another possibility would be to expose `print_headers_as_comparison` and similar functions in the top-level API, which would also be easy (just matter of using proper arguments instead of passing `args`).

**Comment by mromanie** [comment]
I've edited `fitsheader.py` along the lines indicated by @saimn above (added a format parameter for `fitsort` option, return the table from `main`). I'm not sure how to proceed to submit these changes for review (it also requires a minimal change to `fitsheader`). Thanks!

**Comment by saimn** [comment]
@mromanie - you should push your changes to your branch (https://github.com/mromanie/astropy/tree/patch-1), or use the github editor on that branch.
But I see that there various points that could be improved in the `fitsheader` code to simplify things a bit and share options between --table and --fitsort. I can try to have a look at that.

**Comment by mromanie** [comment]
@saimn

I have uploaded the revised `fitsheader.py` and `test_fitsheader.py`. Anything else I should do at this stage?

BTW, the proposed changes are not backwards compatible, in that they change the output format of the `fitsort` option. Is that an issue?

**Pull request closed without merging**
