### PR TITLE
Updated astropy-helpers to 1.1rc1

### PR DESCRIPTION
**Pull request by astrofrog**
1.1rc1 isn't out yet so this is the current master. I'm checking that this passes, and if so, will release astropy-helpers 1.1rc1 and will then update this PR (and rebase the commit so it really is 1.1rc1)

cc @eteq @embray

### CODE REVIEW

**Comment by astrofrog** [comment]
This has been updated to the actual 1.1rc1

**Comment by embray** [comment]
Okay, but there are still a few open issues for astropy-helpers v1.1:

https://github.com/astropy/astropy-helpers/milestones/v1.1

(in particular astropy/astropy-helpers#205 and astropy/astropy-helpers#76 are pretty worthwhile.  astropy/astropy-helpers#76 should also be accompanied by an update to the setup.py script; astropy/astropy-helpers#172 is less important for the short term....)

**Comment by eteq** [comment]
@embray - all of those look to me to be "would be nice to have" rather than "must have for v1.1", right?

So if fixes for them can get in within a week, we can have a quick second RC, but @astrofrog and I agree this should not delay the release unless it turns out it affects a bunch of people.

**Comment by embray** [comment]
Well, I just merged astropy/astropy-helpers#76.  astropy/astropy-helpers#205 fixes a really annoying regression though.  Should have the fix in as soon as the builds pass (and the only reason the last build failed, I think was because of the stupid graphviz download problem).

The Sphinx problem is more nice-to-have-fixed and not a blocker.  But it is pretty annoying.  I'm working on it now.

**Comment by eteq** [comment]
OK, sounds like we should definitely plan on an rc2, then on Monday to roll in these updates and make sure they don't disrupt something unexpected, but I think most testers are unlikely to encounter those situations anyway.  So I don't think we need to delay release plans on those issues' account

(And @embray - see my comment on the sphinx one - I'm not sure there's actually a sphinx/extension bug there at all.)

**Comment by embray** [comment]
This is true.

**Pull request merged**
