### PR TITLE
repr method for WCS objects (Issue #3604)

### PR DESCRIPTION
**Pull request by bmorris3**
My earlier PR had patches for two issues (sorry about that!). I've separated them into their own branches, and I'm resubmitting them in separate PRs. 

For Issue #3604, I wrote a repr method based on the pre-existing printwcs() method. I also updated printwcs() to simply print the result of the repr method to reduce redundant code, at @mdboom 's suggestion.

### CODE REVIEW

**Comment by embray** [comment]
One of the Travis builds crapped out unexpectedly, so I've restarted it.  It looks like this may have to be rebased though since it's not showing as mergeable anymore.

**Comment by bmorris3** [comment]
@embray Let me know if/when I should get on that.

**Comment by mdboom** [comment]
Go ahead and rebase this.  Once that's done, I think this is ready to merge.

**Comment by bmorris3** [comment]
I could use some practice at rebasing, but looks like I got it.

**Comment by astrofrog** [comment]
@bmorris3 - as you can see there are a couple of unrelated commits that have sneaked in. If you go on https://gitter.im/astropy/astropy I can try and help you fix this in real time.

**Comment by bmorris3** [comment]
After botching the rebase and getting help from @astrofrog , we should be good to go now. Thanks again @astrofrog !

**Comment by embray** [comment]
I'm extremely confused, because I thought this was already merged.  That's why I added 849b10f  Was I just losing my mind when I did that?

**Comment by embray** [comment]
Oh I see now, that was because of #3624, which I think shouldn't have been merged?  Or should it have?  Oh well, no matter.

**Pull request merged**
