### PR TITLE
Update local ERFA to include 2016-Dec-31 leap second

### PR DESCRIPTION
**Pull request by pao**
Following the pattern of https://github.com/astropy/astropy/pull/3794. Test written but not actually tested.

### CODE REVIEW

**Comment by pllim** [comment]
Travis is still running but Appveyor already failed. Also this will need a change log once milestone is set.

**Comment by pao** [comment]
@pllim if you have the appropriate Travis permissions you can probably kill the first build from the queue.

**Comment by mhvk** [comment]
I thought leap seconds were not intended to be added by hand, but rather by updating erfa to match the latest sofa version (which has happened) and then starting to use it (#5234). I still think that would be better, but if it is not happening, we should at least do this. @eteq, could you have a look? If there are instructions on how to do it, maybe pass those on? (Or write them...)

**Comment by pao** [comment]
I'm sure that's the correct approach, but nothing I was going to attempt in a drive-by. Either way, Bulletin C has been out for a few months and the leap is only a few more away, so for those of us using Astropy to do UTC-TAI/GPS conversions (hi!) a stopgap table update is better than missing the event entirely.

**Comment by mhvk** [comment]
See #5418 for an update to the latest version of erfa, which includes the leap second.

**Comment by mhvk** [comment]
Closing this, since it is superceded by #5418. Nevertheless, thanks for helping ensure we're covered for the leap second, @pao!

**Comment by pao** [comment]
Thanks, looking forward to the next release!

**Pull request closed without merging**
