### PR TITLE
MNT: Remove Azure pipelines

### LINKED ISSUE #13197: MNT: Replace Azure with Actions for release workflow
Blocked by:

* #13348

Release workflow already available in Actions over at https://github.com/OpenAstronomy/github-actions-workflows . 

* Close #13194 
* Maybe should revisit #11400 to see if it magically goes away

This should be done by or in collaboration with people who hold the keys to Azure side of things to ensure a smooth transition. cc @astrofrog and @Cadair

### PR DESCRIPTION
**Pull request by pllim**
Remove Azure pipelines because it has been replaced by GitHub Actions workflows.

### Description

This pull request is to remove the redundant Azure pipeline run. This is a follow-up of #13251 .

@astrofrog said he still needs to do these before we can merge:

- [x] check the wheels being uploaded to anaconda are ok
- [x] update the actions config to upload stable releases on tagging
- [x] update the docs about getting the dev wheels

Close #13197

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by astrofrog — CHANGES_REQUESTED** [review]
Could you also remove Azure from the README.rst and the azure filename from the ``labeler.yml`` config? Also mentions of Azure will need to be removed/updated from the ``releasing.rst`` docs.

**Comment by pllim** [comment]
@astrofrog , done. Good catch!

**Comment by pllim** [comment]
@astrofrog , with https://github.com/astropy/astropy/pull/13431 in, we can finally do this?

Will this PR be the last thing we need to close #13197 or is there something else?

**Comment by pllim** [comment]
Ooops... I might not be very consistent in backporting the Azure removal stuff and I realized we do need this in release branches. Please go backport your other Azure -> Action PRs as needed before we merge this , @astrofrog . Thanks!

**Comment by astrofrog** [comment]
Ok will do tomorrow once back at work :)

**Comment by astrofrog** [comment]
I think everything that should be backported has been? (hopefully)

**Review by astrofrog — APPROVED** [review]

**Pull request merged**
