### PR TITLE
Improve error wording in validate_physical_type

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by pllim** [comment]
Please fix test and squash commits. Thanks!

**Review by astrofrog — CHANGES_REQUESTED** [review]
Looks good to me but some tests need fixing

**Comment by pllim** [comment]
Well, I guess I'll clean this up so it can go in. The actual change is uncontroversial enough.

**Review by pllim — APPROVED** [review]

**Comment by pllim** [comment]
RTD is stuck but this change doesn't affect the docs, so merging. Thanks, all!

**Pull request merged**
