### PR TITLE
Fix test runner: allow single doc paths to be tested again

### LINKED ISSUE #8030: Cannot run doctests on a single rst file with --test-path option
I used to be able to run the doctests in a single `rst` file using the test runner `-t` (`--test-path`) option, e.g.:

`python setup.py test -t docs/overview.rst`

Unexpectedly, this command now runs *all* of the doctests.  The `-t` option still works as expected for a single python module.

Also, the `-t` option states that it "May also be an absolute path".  When I used an absolute path to an `rst` file, I got "ERROR: not found (no name '`<fullpath>`' in any of [])".  When I used an absolute path to a `py` file, I got two `KeyError`s from `pytest`.

### PR DESCRIPTION
**Pull request by drdavella**
This fixes #8030.

Not sure whether this requires a change log update or not.

### CODE REVIEW

**Comment by pllim** [comment]
Usually for the testing related stuff, we don't ask for change log, but I could be overruled. @larrybradley , do you want to see if it works for you with this patch?

**Comment by drdavella** [comment]
I think it was inadvertently introduced in https://github.com/astropy/astropy/pull/7767.

**Comment by eteq** [comment]
> I think it was inadvertently introduced in #7767.

Ok, so then it was "public" in 3.0.x, so a quick changelog entry is probably desirable, @drdavella.

**Comment by bsipocz** [comment]
Yes, sorry it was indeed was introduced in #7767.

**Comment by bsipocz** [comment]
I've added the changelog, and merging this now. 

Thank you @drdavella for fixing the mess I create.

**Pull request merged**
