### PR TITLE
Fix CI configuration to run tests twice in the same Python session

### PR DESCRIPTION
**Pull request by astrofrog**
In the Travis configuration, we have a ``DOUBLE_PLAY`` option which, if true, runs the tests twice. The original intent was to catch cases where the tests changed something in the global state, which would cause them to fail when run a second time. However, the implementation in the Travis configuration isn't quite right, because it runs the tests twice in two different processes. This PR changes this to instead run the ``test()`` function twice *in the same Python session*. I also moved this to CircleCI because it was easier to code up this kind of custom behavior there.

There are currently failures, which are due precisely to the state problem. I haven't had a chance to investigate yet, but if anyone fancies taking a look, feel free to push commits directly to my branch!

### CODE REVIEW

**Comment by astrofrog** [comment]
I'm milestoning this as v4.0.1 as I think we'll want to backport this, as a CI 'bug'

**Comment by astrofrog** [comment]
For anyone interested, here are the failures:

```
=================================== FAILURES ===================================
____________________________ test_minimal_subclass _____________________________

    def test_minimal_subclass():
        # Basically to check what we document works;
        # see doc/coordinates/representations.rst
>       class LogDRepresentation(BaseRepresentation):

astropy/coordinates/tests/test_representation.py:1033: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'astropy.coordinates.tests.test_representation.test_minimal_subclass.<locals>.LogDRepresentation'>
name = 'LogDRepresentation'
bases = (<class 'astropy.coordinates.representation.BaseRepresentation'>,)
dct = {'__module__': 'astropy.coordinates.tests.test_representation', '__qualname__': 'test_minimal_subclass.<locals>.LogDRe...d', <class 'astropy.units.function.logarithmic.Dex'>)]), 'from_cartesian': <classmethod object at 0x7f6f31e62990>, ...}

    def __init__(cls, name, bases, dct):
        super().__init__(name, bases, dct)
    
        # Register representation name (except for BaseRepresentation)
        if cls.__name__ == 'BaseRepresentation':
            return
    
        if 'attr_classes' not in dct:
            raise NotImplementedError('Representations must have an '
                                      '"attr_classes" class attribute.')
    
        repr_name = cls.get_name()
        # first time a duplicate is added
        # remove first entry and add both using their qualnames
        if repr_name in REPRESENTATION_CLASSES:
            DUPLICATE_REPRESENTATIONS.add(repr_name)
    
            fqn_cls = _fqn_class(cls)
            existing = REPRESENTATION_CLASSES[repr_name]
            fqn_existing = _fqn_class(existing)
    
            if fqn_cls == fqn_existing:
                raise ValueError(f'Representation "{fqn_cls}" already defined')
    
            msg = (
                'Representation "{}" already defined, removing it to avoid confusion.'
                'Use qualnames "{}" and "{}" or class instaces directly'
            ).format(repr_name, fqn_cls, fqn_existing)
            warnings.warn(msg, DuplicateRepresentationWarning)
    
            del REPRESENTATION_CLASSES[repr_name]
            REPRESENTATION_CLASSES[fqn_existing] = existing
            repr_name = fqn_cls
        # further definitions with the same name, just add qualname
        elif repr_name in DUPLICATE_REPRESENTATIONS:
>           warnings.warn('Representation "{}" already defined, using qualname "{}".')
E           UserWarning: Representation "{}" already defined, using qualname "{}".

astropy/coordinates/representation.py:445: UserWarning
____________________________ test_multiple_aliases _____________________________

    def test_multiple_aliases():
        # Define a frame with multiple aliases
        class MultipleAliasesFrame(BaseCoordinateFrame):
            name = ['alias_1', 'alias_2']
            default_representation = SphericalRepresentation
    
        # Register a transform, which adds the aliases to the transform graph
        tfun = lambda c, f: f.__class__(lon=c.lon, lat=c.lat)
        ftrans = FunctionTransform(tfun, MultipleAliasesFrame, MultipleAliasesFrame,
                                   register_graph=frame_transform_graph)
    
        coord = SkyCoord(lon=1*u.deg, lat=2*u.deg, frame=MultipleAliasesFrame)
    
        # Test attribute-style access returns self (not a copy)
        assert coord.alias_1 is coord
        assert coord.alias_2 is coord
    
        # Test for aliases in __dir__()
>       assert 'alias_1' in coord.__dir__()
E       AssertionError: assert 'alias_1' in ['T', '__abstractmethods__', '__bool__', '__class__', '__delattr__', '__dict__', ...]
E        +  where ['T', '__abstractmethods__', '__bool__', '__class__', '__delattr__', '__dict__', ...] = <bound method SkyCoord.__dir__ of <SkyCoord (MultipleAliasesFrame): (lon, lat) in deg\n    (1., 2.)>>()
E        +    where <bound method SkyCoord.__dir__ of <SkyCoord (MultipleAliasesFrame): (lon, lat) in deg\n    (1., 2.)>> = <SkyCoord (MultipleAliasesFrame): (lon, lat) in deg\n    (1., 2.)>.__dir__

astropy/coordinates/tests/test_sky_coord.py:1575: AssertionError
______________________ test_call_keyword_mappings[model0] ______________________

model = <Identity(2)>

    @pytest.mark.parametrize('model',
                             [models.Identity(2), models.Mapping((0, 1)),
                              models.Mapping((1,))])
    def test_call_keyword_mappings(model):
        """
        Test calling a model with positional, keywrd and a mixture of both arguments.
        """
        positional = model(1, 2)
>       assert_allclose(positional, model(x0=1, x1=2))

astropy/modeling/tests/test_input.py:944: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/modeling/core.py:921: in __call__
    new_args, kwargs = self._get_renamed_inputs_as_positional(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Identity(2)>, args = (), kwargs = {}
_keyword2positional = <function Model._get_renamed_inputs_as_positional.<locals>._keyword2positional at 0x7f6f633d23b0>
n_args = 0, new_inputs = {'x0': 1, 'x1': 2}, n_all_args = 2, new_args = []
k = 'r'

    def _get_renamed_inputs_as_positional(self, *args, **kwargs):
        def _keyword2positional(kwargs):
            # Inputs were passed as keyword (not positional) arguments.
            # Because the signature of the ``__call__`` is defined at
            # the class level, the name of the inputs cannot be changed at
            # the instance level and the old names are always present in the
            # signature of the method. In order to use the new names of the
            # inputs, the old names are taken out of ``kwargs``, the input
            # values are sorted in the order of self.inputs and passed as
            # positional arguments to ``__call__``.
    
            # These are the keys that are always present as keyword arguments.
            keys = ['model_set_axis', 'with_bounding_box', 'fill_value',
                    'equivalencies', 'inputs_map']
    
            new_inputs = {}
            # kwargs contain the names of the new inputs + ``keys``
            allkeys = list(kwargs.keys())
            # Remove the names of the new inputs from kwargs and save them
            # to a dict ``new_inputs``.
            for key in allkeys:
                if key not in keys:
                    new_inputs[key] = kwargs[key]
                    del kwargs[key]
            return new_inputs, kwargs
        n_args = len(args)
    
        new_inputs, kwargs = _keyword2positional(kwargs)
        n_all_args = n_args + len(new_inputs)
    
        if  n_all_args < self.n_inputs:
            raise ValueError(f"Missing input arguments - expected {self.n_inputs}, got {n_all_args}")
        elif n_all_args > self.n_inputs:
            raise ValueError(f"Too many input arguments - expected {self.n_inputs}, got {n_all_args}")
        if n_args == 0:
            # Create positional arguments from the keyword arguments in ``new_inputs``.
            new_args = []
            for k in self.inputs:
>               new_args.append(new_inputs[k])
E               KeyError: 'r'

astropy/modeling/core.py:963: KeyError
______________________ test_call_keyword_mappings[model1] ______________________

model = <Mapping((0, 1))>

    @pytest.mark.parametrize('model',
                             [models.Identity(2), models.Mapping((0, 1)),
                              models.Mapping((1,))])
    def test_call_keyword_mappings(model):
        """
        Test calling a model with positional, keywrd and a mixture of both arguments.
        """
        positional = model(1, 2)
>       assert_allclose(positional, model(x0=1, x1=2))

astropy/modeling/tests/test_input.py:944: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/modeling/core.py:921: in __call__
    new_args, kwargs = self._get_renamed_inputs_as_positional(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Mapping((0, 1))>, args = (), kwargs = {}
_keyword2positional = <function Model._get_renamed_inputs_as_positional.<locals>._keyword2positional at 0x7f6f19657050>
n_args = 0, new_inputs = {'x0': 1, 'x1': 2}, n_all_args = 2, new_args = []
k = 'r'

    def _get_renamed_inputs_as_positional(self, *args, **kwargs):
        def _keyword2positional(kwargs):
            # Inputs were passed as keyword (not positional) arguments.
            # Because the signature of the ``__call__`` is defined at
            # the class level, the name of the inputs cannot be changed at
            # the instance level and the old names are always present in the
            # signature of the method. In order to use the new names of the
            # inputs, the old names are taken out of ``kwargs``, the input
            # values are sorted in the order of self.inputs and passed as
            # positional arguments to ``__call__``.
    
            # These are the keys that are always present as keyword arguments.
            keys = ['model_set_axis', 'with_bounding_box', 'fill_value',
                    'equivalencies', 'inputs_map']
    
            new_inputs = {}
            # kwargs contain the names of the new inputs + ``keys``
            allkeys = list(kwargs.keys())
            # Remove the names of the new inputs from kwargs and save them
            # to a dict ``new_inputs``.
            for key in allkeys:
                if key not in keys:
                    new_inputs[key] = kwargs[key]
                    del kwargs[key]
            return new_inputs, kwargs
        n_args = len(args)
    
        new_inputs, kwargs = _keyword2positional(kwargs)
        n_all_args = n_args + len(new_inputs)
    
        if  n_all_args < self.n_inputs:
            raise ValueError(f"Missing input arguments - expected {self.n_inputs}, got {n_all_args}")
        elif n_all_args > self.n_inputs:
            raise ValueError(f"Too many input arguments - expected {self.n_inputs}, got {n_all_args}")
        if n_args == 0:
            # Create positional arguments from the keyword arguments in ``new_inputs``.
            new_args = []
            for k in self.inputs:
>               new_args.append(new_inputs[k])
E               KeyError: 'r'

astropy/modeling/core.py:963: KeyError
______________________ test_call_keyword_mappings[model2] ______________________

model = <Mapping((1,))>

    @pytest.mark.parametrize('model',
                             [models.Identity(2), models.Mapping((0, 1)),
                              models.Mapping((1,))])
    def test_call_keyword_mappings(model):
        """
        Test calling a model with positional, keywrd and a mixture of both arguments.
        """
        positional = model(1, 2)
>       assert_allclose(positional, model(x0=1, x1=2))

astropy/modeling/tests/test_input.py:944: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/modeling/core.py:921: in __call__
    new_args, kwargs = self._get_renamed_inputs_as_positional(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Mapping((1,))>, args = (), kwargs = {}
_keyword2positional = <function Model._get_renamed_inputs_as_positional.<locals>._keyword2positional at 0x7f6f19457830>
n_args = 0, new_inputs = {'x0': 1, 'x1': 2}, n_all_args = 2, new_args = []
k = 'r'

    def _get_renamed_inputs_as_positional(self, *args, **kwargs):
        def _keyword2positional(kwargs):
            # Inputs were passed as keyword (not positional) arguments.
            # Because the signature of the ``__call__`` is defined at
            # the class level, the name of the inputs cannot be changed at
            # the instance level and the old names are always present in the
            # signature of the method. In order to use the new names of the
            # inputs, the old names are taken out of ``kwargs``, the input
            # values are sorted in the order of self.inputs and passed as
            # positional arguments to ``__call__``.
    
            # These are the keys that are always present as keyword arguments.
            keys = ['model_set_axis', 'with_bounding_box', 'fill_value',
                    'equivalencies', 'inputs_map']
    
            new_inputs = {}
            # kwargs contain the names of the new inputs + ``keys``
            allkeys = list(kwargs.keys())
            # Remove the names of the new inputs from kwargs and save them
            # to a dict ``new_inputs``.
            for key in allkeys:
                if key not in keys:
                    new_inputs[key] = kwargs[key]
                    del kwargs[key]
            return new_inputs, kwargs
        n_args = len(args)
    
        new_inputs, kwargs = _keyword2positional(kwargs)
        n_all_args = n_args + len(new_inputs)
    
        if  n_all_args < self.n_inputs:
            raise ValueError(f"Missing input arguments - expected {self.n_inputs}, got {n_all_args}")
        elif n_all_args > self.n_inputs:
            raise ValueError(f"Too many input arguments - expected {self.n_inputs}, got {n_all_args}")
        if n_args == 0:
            # Create positional arguments from the keyword arguments in ``new_inputs``.
            new_args = []
            for k in self.inputs:
>               new_args.append(new_inputs[k])
E               KeyError: 'r'

astropy/modeling/core.py:963: KeyError
____________________________ test_simple_celestial _____________________________

    def test_simple_celestial():
    
        wcs = WCS_SIMPLE_CELESTIAL
    
        # Low-level API
    
        assert wcs.pixel_n_dim == 2
        assert wcs.world_n_dim == 2
        assert wcs.array_shape is None
        assert wcs.pixel_shape is None
        assert wcs.world_axis_physical_types == ['pos.eq.ra', 'pos.eq.dec']
        assert wcs.world_axis_units == ['deg', 'deg']
        assert wcs.pixel_axis_names == ['', '']
        assert wcs.world_axis_names == ['', '']
    
        assert_equal(wcs.axis_correlation_matrix, True)
    
        assert wcs.world_axis_object_components == [('celestial', 0, 'spherical.lon.degree'),
                                                    ('celestial', 1, 'spherical.lat.degree')]
    
        assert wcs.world_axis_object_classes['celestial'][0] is SkyCoord
        assert wcs.world_axis_object_classes['celestial'][1] == ()
>       assert isinstance(wcs.world_axis_object_classes['celestial'][2]['frame'], ICRS)
E       assert False
E        +  where False = isinstance(<FK5 Frame (equinox=2010.0)>, ICRS)

astropy/wcs/wcsapi/tests/test_fitswcs.py:135: AssertionError
______________________________ test_spectral_cube ______________________________

    def test_spectral_cube():
    
        # Spectral cube with a weird axis ordering
    
        wcs = WCS_SPECTRAL_CUBE
    
        # Low-level API
    
        assert wcs.pixel_n_dim == 3
        assert wcs.world_n_dim == 3
>       assert wcs.array_shape is None
E       AssertionError: assert (50, 40, 30) is None
E        +  where (50, 40, 30) = WCS Keywords\n\nNumber of WCS axes: 3\nCTYPE : 'GLAT-CAR'  'FREQ'  'GLON-CAR'  \nCRVAL : 10.0  20.0  25.0  \nCRPIX : 30.0  ... \nPC2_1 PC2_2 PC2_3  : 0.0  1.0  0.0  \nPC3_1 PC3_2 PC3_3  : 0.0  0.0  1.0  \nCDELT : -0.1  0.5  0.1  \nNAXIS : 30  40  50.array_shape

astropy/wcs/wcsapi/tests/test_fitswcs.py:235: AssertionError
_____________________ test_caching_components_and_classes ______________________

    def test_caching_components_and_classes():
    
        # Make sure that when we change the WCS object, the classes and components
        # are updated (we use a cache internally, so we need to make sure the cache
        # is invalidated if needed)
    
        wcs = WCS_SIMPLE_CELESTIAL
    
        assert wcs.world_axis_object_components == [('celestial', 0, 'spherical.lon.degree'),
                                                    ('celestial', 1, 'spherical.lat.degree')]
    
        assert wcs.world_axis_object_classes['celestial'][0] is SkyCoord
        assert wcs.world_axis_object_classes['celestial'][1] == ()
>       assert isinstance(wcs.world_axis_object_classes['celestial'][2]['frame'], ICRS)
E       assert False
E        +  where False = isinstance(<FK5 Frame (equinox=2010.0)>, ICRS)

astropy/wcs/wcsapi/tests/test_fitswcs.py:839: AssertionError
__________________________ test_sub_wcsapi_attributes __________________________

    def test_sub_wcsapi_attributes():
    
        # Regression test for a bug that caused some of the WCS attributes to be
        # incorrect when using WCS.sub or WCS.celestial (which is an alias for sub
        # with lon/lat types).
    
        wcs = WCS_SPECTRAL_CUBE
        wcs.pixel_shape = (30, 40, 50)
        wcs.pixel_bounds = [(-1, 11), (-2, 18), (5, 15)]
    
        # Use celestial shortcut
    
        wcs_sub1 = wcs.celestial
    
        assert wcs_sub1.pixel_n_dim == 2
        assert wcs_sub1.world_n_dim == 2
        assert wcs_sub1.array_shape == (50, 30)
        assert wcs_sub1.pixel_shape == (30, 50)
        assert wcs_sub1.pixel_bounds == [(-1, 11), (5, 15)]
        assert wcs_sub1.world_axis_physical_types == ['pos.galactic.lat', 'pos.galactic.lon']
        assert wcs_sub1.world_axis_units == ['deg', 'deg']
>       assert wcs_sub1.world_axis_names == ['Latitude', 'Longitude']
E       AssertionError: assert ['', ''] == ['Latitude', 'Longitude']
E         At index 0 diff: '' != 'Latitude'
E         Use -v to get the full diff

astropy/wcs/wcsapi/tests/test_fitswcs.py:876: AssertionError
==== 9 failed, 12234 passed, 1110 skipped, 32 xfailed in 236.37s (0:03:56) =====
```

**Comment by astrofrog** [comment]
@adrn @eteq - there are a couple of coordinates failures - could you investigate?

@nden - there are a few modeling failures - could you investigate?

I can try and tackle the APE 14 WCS ones!

**Comment by nden** [comment]
Just fyi, I won't be able to look at this until some time next week (after asdf and gwcs are released).

**Comment by astrofrog** [comment]
@nden - no rush!

**Comment by pllim** [comment]
Ops, my bad! If this replaces the one in Travis, `.travis.yml` should be updated too.

**Comment by astrofrog** [comment]
I've managed to fix most issues but one remains in coordinates:

```
____________________________ test_multiple_aliases _____________________________

    def test_multiple_aliases():
        # Define a frame with multiple aliases
        class MultipleAliasesFrame(BaseCoordinateFrame):
            name = ['alias_1', 'alias_2']
            default_representation = SphericalRepresentation
    
        # Register a transform, which adds the aliases to the transform graph
        tfun = lambda c, f: f.__class__(lon=c.lon, lat=c.lat)
        ftrans = FunctionTransform(tfun, MultipleAliasesFrame, MultipleAliasesFrame,
                                   register_graph=frame_transform_graph)
    
        coord = SkyCoord(lon=1*u.deg, lat=2*u.deg, frame=MultipleAliasesFrame)
    
        # Test attribute-style access returns self (not a copy)
        assert coord.alias_1 is coord
        assert coord.alias_2 is coord
    
        # Test for aliases in __dir__()
>       assert 'alias_1' in coord.__dir__()
E       AssertionError: assert 'alias_1' in ['T', '__abstractmethods__', '__bool__', '__class__', '__delattr__', '__dict__', ...]
E        +  where ['T', '__abstractmethods__', '__bool__', '__class__', '__delattr__', '__dict__', ...] = <bound method SkyCoord.__dir__ of <SkyCoord (MultipleAliasesFrame): (lon, lat) in deg\n    (1., 2.)>>()
E        +    where <bound method SkyCoord.__dir__ of <SkyCoord (MultipleAliasesFrame): (lon, lat) in deg\n    (1., 2.)>> = <SkyCoord (MultipleAliasesFrame): (lon, lat) in deg\n    (1., 2.)>.__dir__

astropy/coordinates/tests/test_sky_coord.py:1588: AssertionError
==== 1 failed, 12242 passed, 1110 skipped, 32 xfailed in 232.01s (0:03:52) =====
```

@eteq @adrn - any ideas?

**Comment by ayshih** [comment]
Uh oh, I wrote that!  I don't immediately see why it'd fail, though.  Hmm...

**Comment by ayshih** [comment]
@astrofrog The bug is because the test class lingers in the transform graph even after the sole transform is unregistered from the graph (because there's apparently no code that clears out classes with zero transforms).  An easy fix for the test is to add
```
assert frame_transform_graph._graph.pop(MultipleAliasesFrame) == {}
```
at the end of the test.

**Comment by astrofrog** [comment]
@ayshih - thanks! Just to check, do you think this is a real bug that should be resolved though?

**Comment by ayshih** [comment]
Yes, I'd consider it a bug.  I'd expect that `CoordinateTransform.unregister()` – that is, `TransformGraph.remove_transform()` – should revert the graph to the state prior to `add_transform()`.  In implementation, it should delete a sub-dictionary from the graph if the transform being removed was the only transform in that sub-dictionary.

However, maybe there are folks who want to be able to have a frame node in the transform graph with zero transforms in or out of that frame (including loopback transforms), but I don't know what such a frame would be used for.  If that ability is desired, there ought to be a public API for adding/removing nodes rather than messing with the private graph directly.

**Comment by astrofrog** [comment]
The issue is that the 32 bit build is also already the parallel build and that makes the tests run in different processes, which would mess up the double testing.

**Comment by bsipocz** [comment]
Oh, OK, I suppose that's true. Is there an option to run that from cron on circleCI? Or move the full job over from travis rather than double run it? (Also, originally the double run was a cron job, is that possible to do that on circleCI, or we should wait until move over to Actions/Azure?)

**Comment by pllim** [comment]
> we should wait until move over to Actions/Azure?

I wouldn't hold my breath for Azure transition. I still find its features lacking for OSS.

**Comment by astrofrog** [comment]
Going back on what I said before, we could make part of the 32 bit test do this since we actually test three python versions with 32 bit

**Comment by astrofrog** [comment]
Thanks for reviewing @bsipocz and @nden!

Most of the changes in coordinates are trivial, the only one that isn't is a workaround that will be properly solved by https://github.com/astropy/astropy/pull/9815. Since that is still awaiting review, and in the interest of not having this PR go stale (and not introducing more bugs in other PRs), I'll go ahead and merge this, and then https://github.com/astropy/astropy/pull/9815 should remove the line at the end of ``test_multiple_aliases`` (cc @ayshih)

**Pull request merged**
