### PR TITLE
Prevent PLY to overwrite its generated files.

### LINKED ISSUE #5726: SkyCoord
When I run the default example for SkyCoord on Astropy Doc page.
```python
>>> from astropy import units as u
>>> from astropy.coordinates import SkyCoord
>>> c = SkyCoord('00:42.5 +41:12', unit=(u.hourangle, u.deg))
```

I get the error 

> WARNING: Couldn't write lextab module u'angle_lextab'. [Errno 13] Permission denied: u'/usr/lib64/python2.7/site-packages/astropy/coordinates/angle_lextab.py'
WARNING: Couldn't create u'angle_parsetab'. [Errno 13] Permission denied: u'/usr/lib64/python2.7/site-packages/astropy/coordinates/angle_parsetab.py'

This was absent when I was using 1.2.1. Recently upgraded to 1.3. Is this a bug?

### PR DESCRIPTION
**Pull request by saimn**
Ref #5581, fixes #5726.

After #5526 updated PLY to 3.9, some files were re-generated at runtime
(astropy/coordinates/{angle_lextab.py,angle_parsetab.py}). This is because of
this line https://github.com/dabeaz/ply/blob/master/ply/lex.py#L901 which
assumes that the lextab parameter in `lex.lex` is a str only, not unicode, which
leads to some surprise when unicode_literals is used on Python 2 ! Then the 
module is not imported, so it is regenerated.

So this commit just wraps the lextab value to make sure that a str is always
passed to `lex.lex`. And it also reverts #5563 as wrapping in a try/except is no 
more necessary.

cc @bsipocz @eteq @mhvk

### CODE REVIEW

**Comment by mhvk** [comment]
Great find! I was very confused indeed by why we needed the `try/except`. Could you add a comment for each of the lines? Something along the lines of
```
# PY2: need str() to ensure we do not pass on a unicode object.
```
This will also remind us we can remove this work-around for astropy 3.0...

**Comment by mhvk** [comment]
@bsipocz - Could you have a look too? You understand this better than I do...

**Comment by pllim** [comment]
Also need a change log.

**Comment by bsipocz** [comment]
Great investigating @saimn, thanks! It looks good to me.

**Comment by saimn** [comment]
@mhvk - Done ! Also added the changelog entry.

**Comment by mhvk** [comment]
OK, all looks great now, so merging (sorry for the bit of a delay).

**Comment by bsipocz** [comment]
This can probably be backported to 1.0.12, but it's not a clean cherry-pick, so I leave as is for now.

**Pull request merged**
