### PR TITLE
add workflow to comment on a pull request with diff coverage

### PR DESCRIPTION
**Pull request by zacharyburnett**
### Description

as a follow-on to #16619, this workflow downloads coverage artifacts and comments on the triggering PR with a diff coverage report. Unfortunately, the permissions required to comment on a PR make it very difficult to have this job in the main test workflow without introducing vulnerabilities for outside collaborators to run arbitrary code with elevated permissions.

Fixes #<Issue Number>

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by zacharyburnett** [comment]
possible solution to the PR commenting issue that would not necessitate a separate workflow: https://github.com/mshick/add-pr-comment-proxy

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/pull/16642#issuecomment-2200091300

Not sure about that. The README pointed to https://github.community/t/github-actions-are-severely-limited-on-prs/18179/4 that does not exist. 🧐  Can we be sure it is 100% secure?

**Comment by zacharyburnett** [comment]
> Re: [#16642 (comment)](https://github.com/astropy/astropy/pull/16642#issuecomment-2200091300)
> 
> Not sure about that. The README pointed to https://github.community/t/github-actions-are-severely-limited-on-prs/18179/4 that does not exist. 🧐 Can we be sure it is 100% secure?

the code https://github.com/mshick/add-pr-comment-proxy/blob/master/app.js seems to do exactly what it says it does, as far as I can tell

**Comment by pllim** [comment]
That `app.js` might be okay now, but we cannot guarantee it. And if we pin by hash, we might miss future critical updates. If we do not, we have to re-verify every time someone modifies it. Why risk it?

**Comment by zacharyburnett** [comment]
> That `app.js` might be okay now, but we cannot guarantee it. And if we pin by hash, we might miss future critical updates. If we do not, we have to re-verify every time someone modifies it. Why risk it?

that is fair; we do not necessarily need PR comments at the moment enough to introduce these complexities, especially since we currently still have that functionality with Codecov

**Pull request closed without merging**
