### PR TITLE
Fix ``Moffat1D`` and ``Moffat2D`` derivatives. [#8094]

### LINKED ISSUE #8094: Moffat1D and Moffat2D derivatives
The derivatives in Moffat1D are wrong:

https://github.com/astropy/astropy/blob/2b8fe1305b2689d8b2715f98985e36f2c7d5c0d9/astropy/modeling/functional_models.py#L2223

They should be replaced by:
```
    @staticmethod
    def fit_deriv(x, amplitude, x_0, gamma, alpha):
        """One dimensional Moffat model derivative with respect to parameters"""

        fac = (1 + (x - x_0) ** 2 / gamma ** 2)
        d_A = fac ** (-alpha)
        d_x_0 = (2 * amplitude * alpha * (x - x_0) * d_A / (fac * gamma ** 2))
        d_gamma = (2 * amplitude * alpha * (x - x_0) ** 2 * d_A /
                   (fac * gamma ** 3))
        d_alpha = -amplitude * d_A * np.log(fac)
        return [d_A, d_x_0, d_gamma, d_alpha]
```

In Moffat2D:

https://github.com/astropy/astropy/blob/2b8fe1305b2689d8b2715f98985e36f2c7d5c0d9/astropy/modeling/functional_models.py#L2301

only derivative wrt gamma is wrong. It should be
```
        d_gamma = 2 * amplitude * alpha * d_A * rr_gg / ((1 + rr_gg) * gamma ** 3)
```

### PR DESCRIPTION
**Pull request by ycopin**
fixes #8094

### CODE REVIEW

**Comment by bsipocz** [comment]
This will definitely need tests, or fixes to the current tests to make them fail on the previous version.

**Comment by nden** [comment]
Thanks @ycopin ! I will be able to look at this in a couple of days.

**Comment by nden** [comment]
@bsipocz  I think this is failing because there's no section for 3.1.1 in `CHANGES`. How should this be handled? Should I make one?

**Comment by nden** [comment]
I think the tests for derivatives did not fail because of the specific values used in the tests - `gamma=1, x_0=0, y_0=0`. While those tests are OK, we should add a more general one.

**Comment by bsipocz** [comment]
@nden - don't worry about the changelog, I'll sort it out once the release is really out. Since this is a bugfix, I suppose it can land in RC2 once you merge it.

**Comment by nden** [comment]
I guess the bot is then confused because there is a changelog entry and it has the correct PR number.

**Comment by bsipocz** [comment]
The PR number in the changelog is incorrect (it has to be the PR's number not the issue's it fixes), but I can fix it while doing the release, feel free to merge whenever this is ready.

**Comment by ycopin** [comment]
@nden thanks for the review.

To test the derivatives, 0s and 1s are always susceptible to be special values...  Just systematically take 0.5 or 2 or whatever else!

**Pull request merged**
