### PR TITLE
WIP : turn on numpydoc `numpydoc_validation_checks`

### PR DESCRIPTION
**Pull request by nstarman**
See https://numpydoc.readthedocs.io/en/latest/validation.html#docstring-validation-during-sphinx-build for how to get RTD to do some extra docstring validation.
Can't be implemented until numpydoc is updated.

TODO:

- [x] solve: why doesn't this seem to be running?  **requires numpydoc 1.2**!
- [ ] uncomment more validation flags.

### CODE REVIEW

**Comment by nstarman** [comment]
#not_v4.3

**Comment by nstarman** [comment]
@Carreau. Your velin app uses the numpydoc backend. Do you have any insight into why `numpydoc_validation_checks` aren't working on Astropy's sphinx builds?

**Comment by Carreau** [comment]
I'm not too sure; I don't use the validation part of numpydoc, I simply parse and try to reconstruct the docstring using the parsed data.

**Comment by nstarman** [comment]
Oh darn. This is a puzzler. Thanks regardless.

**Comment by nstarman** [comment]
When sphinx-astropy has numpydoc v1.2 then this can be turned on.
https://github.com/astropy/sphinx-astropy/blob/0e35fd0c4a3d08009e51cc940f44b8e640098be8/setup.cfg#L27

@pllim, tag keep-open? I'm not going to touch this PR until the numpydoc version bump.

**Pull request closed without merging**
