### PR TITLE
Update WCSLIB to 7.6 with fix for unwanted 'datfix' warnings

### LINKED ISSUE #11385: New unnecessary warning with updated wcslib
On the current development version of astropy, the simple script below is raising a new warning:
```python
WARNING: FITSFixedWarning: 'datfix' made the change 'Success'. [astropy.wcs.wcs]
```
This was probably introduced by https://github.com/astropy/astropy/pull/11260.

When code is running fine, I don't think any warnings should be raised to indicate this, and I think this is related to some downstream issues we are having with sunpy tests (https://github.com/sunpy/sunpy/issues/5073).

```python
from astropy.wcs import WCS
header = {
    'CRVAL1': 0,
    'CRVAL2': 0,
    'CRPIX1': 5,
    'CRPIX2': 5,
    'CDELT1': 10,
    'CDELT2': 9,
    'CD1_1': 0,
    'CD1_2': -9,
    'CD2_1': 10,
    'CD2_2': 0,
    'NAXIS1': 6,
    'NAXIS2': 6,
    'CUNIT1': 'arcsec',
    'CUNIT2': 'arcsec',
    'CTYPE1': 'HPLN-TAN',
    'CTYPE2': 'HPLT-TAN',
}
WCS(header)
```

### LINKED ISSUE #11408: ANN: New WCSLIB 7.5 released
New WCSLIB release found.

Version: 7.5 (2021/03/20)

#### Change log

WCSLIB version 7.5 (2021/03/20)
-------------------------------

The C code in WCSLIB is moving piecemeal to the C99 standard.  In fact,
various indispensible C99 constructs have been used in WCSLIB for many
years: the long long int data type (in fitshdr() only); stdint.h,
inttypes.h, and the use of PRI formatting control (in wcsprintf(), which
is widely used by the library); and the C99-extended library function
vsnprintf() (used by wcserr for a decade).  Flex-generated C code also
uses C99 extensions, though with workarounds if they are not available.

Except in the header prologues, which are formatted in a special way for
generating the user manual, comments were changed en masse to C99 style
in release 7.3.1, and variable declarations in code that I have occasion
to modify will transition to the more general placement allowed by C99.
However, I have no plans to use any of the more esoteric features of
C99.

* C library

  - New function, wcsccs(), changes the celestial coordinate system of a
    wcsprm struct, for example, from equatorial to galactic coordinates.
    The parameters that define the spherical coordinate transformation
    must be provided.  This allows WCSLIB to provide this functionality
    without needing to know anything about specific celestial coordinate
    systems, and has the advantage of making the routine completely
    general.  Requested by Mohammad Akhlaghi.

    Modified test program twcsfix also to test wcsccs().

  - Fixed a problem common to all of the Flex code (fitshdr, wcsbth,
    wcspih, wcsulex, and wcsutrn) that made it thread-unsafe.  Reported
    by Cyril Richard.

    Added a new test program, tpthreads, to test thread safety.  It is
    only used for code development, and not exercised as part of the
    standard test suite.

  - In fitshdr(), fixed a problem that potentially could arise on
    systems where sizeof(long long int) is greater than 8 (64 bits).

* Fortran wrappers

  - Match changes to the C library: added a wrapper for wcsccs(), and
    modified twcsfix.f.

  - Because null addresses cannot be passed to functions in Fortran,
    wcssub_() now interprets *nsub == -1 && *axes == -1 as a signal to
    do a deep copy of one wcsprm struct to another.

* Utilities

  - New utility, sundazel, computes the local time of the Sun's passage
    through the specified apparent longitude or latitude in a user-
    defined coordinate system.  It can also perform several other Solar
    related calculations.  (It is unrelated to FITS WCS, and does not
    use WCSLIB.)

* Installation

  - Added an 'uninstall' rule to the makefiles.  Suggested by
    Cyril Richard.

(For complete change log information, see https://www.atnf.csiro.au/people/mcalabre/WCS/CHANGES .)

### PR DESCRIPTION
**Pull request by dhomeier**
### Description
Opening this as a sort of stub to make sure it's in before 4.3 feature freeze (although it probably counts as a bugfix).

Will hopefully fix #11385 by removing the `'datfix' made the change 'Success'` warnings introduced in 7.4 (and of course close #11408).
Mark Calabretta has confirmed that this new warning was indeed not intended; my mail came a bit too late for the last WCSLIB release, but he is planning to release version 7.6 already next week.
Not so sure actually about sunpy/sunpy#5073, ejeschke/ginga#938, since they refer to a different 'datfix' warning where a change to `MJD-OBS` is in fact made, so that warning may remain (and seems legitimate).

For now, updating the tests to accommodate the warnings expected from the new version, with the new library to be added in `cextern` once it is released.
Also pinging #9018

### CODE REVIEW

**Comment by dhomeier** [comment]
Added a commit with 7.5 just for testing against it once. I see no reason to merge this version, but in principle people may get to link against it with `ASTROPY_USE_SYSTEM_WCSLIB`.
Though for the 4.3 release we should perhaps require 7.6 as minimum version for the external library.

**Comment by dhomeier** [comment]
Don't know what to make of the MSVC error (seems to be the same failure as for #11549)
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DECHO -DWCSTRIG_MACRO -DASTROPY_WCS_BUILD -D_GNU_SOURCE -DNDEBUG -DYY_NO_UNISTD_H -D_CRT_SECURE_NO_WARNINGS -D_NO_OLDNAMES -DNO_OLDNAMES -D__STDC__ -UDEBUG -IC:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2nijm74f\overlay\Lib\site-packages\numpy\core\include -Icextern\wcslib\C -Iastropy\wcs\include -ID:\a\astropy\astropy\.tox\py38-test-alldeps\include -Ic:\hostedtoolcache\windows\python\3.8.8\x64\include -Ic:\hostedtoolcache\windows\python\3.8.8\x64\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tccextern\wcslib\C\wcsfix.c /Fobuild\temp.win-amd64-3.8\Release\cextern\wcslib\C\wcsfix.obj
1639
  wcsfix.c
1640
  cextern\wcslib\C\wcsfix.c(1230): error C2057: expected constant expression
1641
  cextern\wcslib\C\wcsfix.c(1230): error C2466: cannot allocate an array of constant size 0
1642
  cextern\wcslib\C\wcsfix.c(1230): error C2133: 'mapto': unknown size
1643
  cextern\wcslib\C\wcsfix.c(1420): error C2057: expected constant expression
1644
  cextern\wcslib\C\wcsfix.c(1420): error C2466: cannot allocate an array of constant size 0
1645
  cextern\wcslib\C\wcsfix.c(1420): error C2133: 'dtmp': unknown size
1646
  cextern\wcslib\C\wcsfix.c(1431): error C2057: expected constant expression
1647
  cextern\wcslib\C\wcsfix.c(1431): error C2466: cannot allocate an array of constant size 0
1648
  cextern\wcslib\C\wcsfix.c(1431): error C2133: 'ctmp': unknown size
1649
  cextern\wcslib\C\wcsfix.c(1442): error C2057: expected constant expression
1650
  cextern\wcslib\C\wcsfix.c(1442): error C2466: cannot allocate an array of constant size 0
1651
  cextern\wcslib\C\wcsfix.c(1442): error C2133: 'itmp': unknown size
1652
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```
– I have replaced the `--std=gnu99` compiler flag with `--std=c99` for non-unix builds, but now don't see the flag at all in the build log. But the error seems to raise on the new `wcspcx` function, which is declaring a dynamic array in
https://github.com/astropy/astropy/blob/22e7e3f57f3153da9cd1a5a8049c923e0d252894/cextern/wcslib/C/wcsfix.c#L1185-L1230

Need some Windows assistance here, I'm afraid – @pllim?

**Comment by pllim** [comment]
@dhomeier , it seems like you and @mcara both stumbled upon the same problem with Windows and luckily for me, he already found out the reason when I woke up... 😅 

https://github.com/astropy/astropy/pull/11549#issuecomment-819282986

**Comment by dhomeier** [comment]
Closing in favour of #11549

**Pull request closed without merging**
