### PR TITLE
Make convolve() accept Kernel as tuple

### PR DESCRIPTION
**Pull request by jamienoss**
_c.f._

 * https://github.com/astropy/astropy/pull/7503#issuecomment-396637649
 * https://github.com/astropy/astropy/pull/7503#issuecomment-396655622
 * https://github.com/astropy/astropy/pull/7503#issuecomment-396674077
 * https://github.com/astropy/astropy/pull/7503#issuecomment-396675606

Signed-off-by: James Noss <jnoss@stsci.edu>

### CODE REVIEW

**Comment by jamienoss** [comment]
If you want a changelog entry, let me know which version and I'll add one - I doubt anyone is dependent on the previous type exception (unwise).

**Comment by pllim** [comment]
Great. Please add a change log under 3.1 for "API change". You may add `[ci skip]` to your new commit message as there is no need to rerun the whole CI for a change log entry. Thank you!

**Comment by jamienoss** [comment]
@pllim Sorry, I didn't really add much explanation in this PR, I'll add a link in the description.

It's one of those odd ones, on the fence of an API change but not at the same time. The function API hasn't changed and no one should be reliant on it throwing when passed a tuple  (because that would be silly) so it could just be a bug fix but only since the input arrays can already be tuples.

I just hunted and found this https://github.com/astropy/astropy-APEs/blob/master/APE2.rst, regarding our version semantics - it's not very clear to me though - if you do consider this to be an API change such that it gets recorded as one in the changelog, doesn't this make it a major version bump?

**Comment by bsipocz** [comment]
@jamienoss - v3.1 is our next major feature release (followed by 3.2), then 4.0 will be the next LTS. Release calendar of major releases is here: https://github.com/astropy/astropy/wiki/Release-Calendar

**Comment by jamienoss** [comment]
Download fail - can someone restart the test, please, thanks.

**Comment by pllim** [comment]
Merging. Thanks!

**Pull request merged**
