### PR TITLE
Quantity numpy ufunc additions: ufunc.at, reduce, reduceat, accumulate, outer

### PR DESCRIPTION
**Pull request by mhvk**
This follows on the introdoction of `__numpy_ufunc__` in #2583 (so only look at last commit), adding support to `Quantity` for ufunc methods [1]: `ufunc.at`, `reduce`, `reduceat`, `accumulate`, and `outer`. It think it will be useful, though one problem is that I do not know how to support this without `__numpy_ufunc__`; thus, it will only work in numpy >=1.10.

[1] http://docs.scipy.org/doc/numpy/reference/ufuncs.html#methods

### CODE REVIEW

**Comment by mdboom** [comment]
I think this is fine, but it's sort of a documentation issue -- people may write code with Numpy 1.10 and be surprised when it doesn't work with earlier versions.  Don't know how best to communicate that, though.

**Comment by mhvk** [comment]
@mdboom - indeed, the problem is that with previous numpy versions, there is no way to interact with these `ufunc` methods, so also no way to warn users that it doesn't work. Obviously, I'll add to the documentation once #2583 is in and this PR can be considered by itself.

**Comment by mhvk** [comment]
Rebased to use the new converters instead of scales. Of course, still needs #2583 to be merged first.

**Comment by mhvk** [comment]
Closing since this is now part of #2583

**Pull request closed without merging**
