### PR TITLE
pre-commit isort

### PR DESCRIPTION
**Pull request by nstarman**
Let there be `isort`!
Followup to #11945

1. moved `isort` config to `pyproject.toml` (preferred location) and modified to auto-skip `extern`
1. ran `isort`
2. for files causing a circular import I added a ``# isort: skip_file`` or ``# isort: split`` so it can be dealt with later
3. moved a few comments that were causing issues.
4. added 1 space in setup.cfg

668 modified files is a lot to review... so if it helps I pinky promise the above steps were all I did. 

Pros:
1. regularized and easy-to-read imports
2. easier detection when circular import magic is happening. This is generally necessitates a `isort` flag like `skip` or `split`

Cons:
1. Probably need to add a short explanation to the dev docs.
2. More contributor burden: OTOH we already run pre-commit, so contributors who want to check a commit locally will need pre-commit. This is just another reason. And isort auto resorts imports, so it's super easy. Also pre-commit can be configured to automatically run with every commit!

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by saimn** [comment]
> PEP 517 and 518 essentially ensure the slow demise of setup.cfg in favor of a toml file.

No, they specify a way to use different build systems, with a new config file. Again, setuptools is not deprecated, `setup.cfg` is also not, and many tools don't support `pyproject.toml`. Things may be different in a few years.

**Comment by hamogu** [comment]
In my opinion (which may not be relevant here), we are making things too complicated. I'm not opposed to @nstarman running isort locally and opening a bunch or PRs. However, I'm opposed to any sort of magic like pre-commit hooks. For new and also occasional contributors, that's a significant source of confusion. Why does the file look different on GH than locally? Why do I get merge-conflicts when I do X locally and then Y in the GH webinterface and then pull my own branch (not tested, but I bet that can happen)? What does this comment `# isort: skip_file` that I see mean? Can I delete it? What is a pre-commit hook anyway?
Even as occasional contributor, I feel like the new guy every time I try to do something - and that also means I can't help anyone with their PRs. 

I suggest that the Astropy community decides what is really important. Running CI to make sure tests pass is important. Sorting imports is nice to have, but really just a minor convenience in most cases (almost all files that I've looked at recently have <= 5 imports, so easy to read in any order) and I would argue that having a few files where imports are not sorted "correctly" is a small price to pay to have an easier-to-understand setup for everyone. And, if someone really cares, they can run isort locally and PR the changes, just like it's done here.

**Comment by nstarman** [comment]
@hamogu. Thanks for the detailed input. I think there may be confusion happening on how ``pre-commit`` works server-side as part of CI.

> In my opinion (which may not be relevant here), we are making things too complicated. I'm not opposed to @nstarman running isort locally and opening a bunch or PRs. However, I'm opposed to any sort of magic like pre-commit hooks. For new and also occasional contributors, that's a significant source of confusion. Why does the file look different on GH than locally? Why do I get merge-conflicts when I do X locally and then Y in the GH webinterface and then pull my own branch (not tested, but I bet that can happen)? What does this comment `# isort: skip_file` that I see mean? Can I delete it? What is a pre-commit hook anyway? Even as occasional contributor, I feel like the new guy every time I try to do something - and that also means I can't help anyone with their PRs.

Pre-commit *hooks* can be installed client-side, by the user, to automatically correct pushes. That's fine because that's their choice and they set it up.
The normal use case for `isort` server-side is to just check correctness, not change files. On our side, adding `isort` to `pre-commit` is a bit of a misnomer since it's really post-commit! The user has already pushed commits and we are just checking the commit.
The pre-commit tool is a nice way to bring together a bunch of linters and code checkers, etc. Also, users with `pre-commit` installed can run our CI locally either with `tox` or with the bash command `pre-commit run ...`. Without automatic hooks, pre-commit is conceptually similar to `tox` and `pytest`.

So this PR and #11945 do NOT add pre-commit *hooks*. Here `isort` is run like `tox codestyle` is run. It's just a check for import order correctness. No files are changed, except by the user.

It was suggested in https://github.com/astropy/astropy/pull/12276#issuecomment-952819258 that the server-side (CI) usage of `pre-commit` could be changed to automatically fix PRs. I'm personally a fan of it, but your concerns are well founded and maybe it's best not to automatically fix PRs. Perhaps there's a middle ground where it opens a review and suggests changes. That's worth looking into.

> I suggest that the Astropy community decides what is really important. Running CI to make sure tests pass is important. Sorting imports is nice to have, but really just a minor convenience in most cases (almost all files that I've looked at recently have <= 5 imports, so easy to read in any order) and I would argue that having a few files where imports are not sorted "correctly" is a small price to pay to have an easier-to-understand setup for everyone. And, if someone really cares, they can run isort locally and PR the changes, just like it's done here.

I certainly agree that we should make the path to submission as easy as possible. But we already employ `pre-commit` as a CI check for file endings and whitespaces (see #11945). I think the way to make submission easy(ier) is very clear documentation on what is required to set up astropy in a development environment:  conda env, forking and cloning a repo, installing build, runtime, and test dependencies, building in development mode, etc.

``pre-commit`` is really a test dependency and should be installed with the other test tools, like ``pytest``. One of the nice things about ``pre-commit`` is that all component tools, like ``isort``, are *automatically installed* when ``pre-commit`` is run for the first time. So just having ``pre-commit`` ensures an easy setup. Adding ``isort`` doesn't impact the current difficulty of setup.

On a more conceptual note, I think adding tools like ``isort`` are important for Astropy to fit within the development of the larger python ecosystem. These tools have become fairly ubiquitous as python matures. Fairly soon I think it will be strange that Astropy *doesn't* have standardized imports, a consistent code style (``black`` or something else) and type hints for static code analysis and more performant compilation.
As I see it, our task is to both have all this AND make it easy to contribute.

**Comment by astrofrog** [comment]
Before moving too far ahead I wonder if this is something that should be discussed at the next developer telecon unless it has already been discussed? It seems it should be something that should be decided as a group?

**Comment by pllim** [comment]
I see that you have done this in pieces, so I am closing this. Thanks!

**Comment by nstarman** [comment]
@pllim, this PR does something that the other pieces will not: add isort to the pre-commit CI

**Comment by pllim** [comment]
Then what about conflicts?

**Comment by nstarman** [comment]
They should disappear as I spin off PRs from this one and rebase.

**Comment by nstarman** [comment]
Just for the record while this PR was closed we do use pre-commit & isort (ruff edition). Everything was done in smaller, more focused PRs.
Configuring in a `pyproject.toml` file is significantly better than spreading out configurations over multiple files. We are less than pleased with tools that insist on using legacy configuration infrastructure and cluttering our repo.

**Pull request closed without merging**
