### PR TITLE
Avoid `inspect.isclass()`

### PR DESCRIPTION
**Pull request by eerovaher**
### Description

In Python 3 (but not in Python 2) [`inspect.isclass(x)`](https://docs.python.org/3/library/inspect.html#inspect.isclass) produces the same result as [`isinstance(x, type)`](https://docs.python.org/3/library/functions.html?highlight=isinstance#isinstance), but the latter does not require importing `inspect`:
https://github.com/python/cpython/blob/1528b420b33ae5c636b6016ce6c6afb0b09e7694/Lib/inspect.py#L73-L79

A single use of `inspect.isclass` in a `filter()` call remains because avoiding it there would not simplify the code: https://github.com/astropy/astropy/blob/e9ef294ddb8a47e212f0465645250238e7120d7c/astropy/utils/masked/tests/test_function_helpers.py#L1438

### Approvals by sub-package
 - [x] coordinates https://github.com/astropy/astropy/pull/14967#pullrequestreview-1488908087
 - [x] cosmology https://github.com/astropy/astropy/pull/14967#pullrequestreview-1488646171
 - [x] modeling
 - [x] table https://github.com/astropy/astropy/pull/14967#pullrequestreview-1488908087
 - [ ] tests

### CODE REVIEW

**Review by nstarman — APPROVED** [review]
Cosmology LGTM!
Also, this should be a ruff rule. Do you want to open an issue there?

**Review by mhvk — APPROVED** [review]
OK for coordinates and table! I find it slightly less clear but the benefit of not importing `inspect` would seem to outweigh that.

**Comment by nstarman** [comment]
ping @astropy/modeling  :)

**Review by WilliamJamieson — APPROVED** [review]
Modeling changes look good.

**Pull request merged**
