### PR TITLE
fix up some rst formatting in ui.py

### PR DESCRIPTION
**Pull request by hamogu**
@taldcroft 
@astrofrog

### CODE REVIEW

**Comment by embray** [comment]
Granted, the original PR could just as well have been merged into the v0.4.x branch and then ported to master. I don't mind doing that *shrug*.  That's going to be typical for doc edits through the website anyways.  I don't think a new PR was necessary, but now that it's here let's just keep it.

**Comment by taldcroft** [comment]
This is failing the sphinx build test.  I believe 
```
:class:`ascii.Basic`
```
should be 
```
`~astropy.io.ascii.Basic`
```
except I don't remember in this case if the `~` is needed.

**Comment by hamogu** [comment]
@astrofrog was deninitely right to have me run it through Travis. The correct way is

    :class:`Basic`

as can be seen in Line 49 of that file. I don't understand where exactly the right import for that happens, but it seems to work. Let's see if I got it right this time.

**Comment by astrofrog** [comment]
@hamogu - thanks!

**Comment by astrofrog** [comment]
@hamogu - I think if you are referring to a class in the file where the docstring is, you can use the short version.

**Pull request merged**
