### PR TITLE
Fix a minor typo in a docstring in quantity.py

### PR DESCRIPTION
**Pull request by cgobat**
### Description

Found a small typo in the docstring of `Quantity._set_unit()`. What should have been "initializer" was previously spelled "initilizer". This PR corrects that.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Every small improvement is welcome!

**Comment by pllim** [comment]
Didn't @lpsinger add a spellchecker? How did this get through?

**Comment by pllim** [comment]
@meeseeksdev backport to v5.0.x

@meeseeksdev backport to v5.2.x

**Comment by lpsinger** [comment]
> Didn't @lpsinger add a spellchecker? How did this get through?

Did I? I don't see any references to sphinxcontrib.spelling in the astropy or sphinx-astropy repos. Maybe I suggested it but didn't make a PR?

**Comment by pllim** [comment]
Ooops, I pinged the wrong person. It was @namurphy from #13985 . Sorry for the confusion. I should have checked.

**Comment by namurphy** [comment]
Yes, we added [codespell](https://github.com/codespell-project/codespell).  Codespell works by looking through a dictionary of common misspellings, so it's going to miss words that aren't in its dictionary.  This strategy leads to few false positives (high priority for spellchecking code via CI!) with the tradeoff that it sometimes misses less common misspellings like this one.

**Pull request merged**
