### PR TITLE
[EXP] Add UnitSystem class to support custom unit systems

### LINKED ISSUE #703: Add "extragalactic" and "galactic" unit systems
#579 added the `to_system` functionality to `units`.  This provides an easy way to convert units between `cgs` and `si`.  A nice addition would be to also support `galactic` and `extragalactic` unit systems.  These systems would be like `cgs`, but with the natural length scale in `kpc` or possibly `Mpc` for `extragalactic` and `pc` for `galactic`, and with `km/s` the natural velocity scale.

This _may_ require more work, because `km/s` is not an irreducible unit.  But I haven't looked closely enough to know how one might do this with the `to_system` logic.

cc @mdboom

### PR DESCRIPTION
**Pull request by adrn**
This is a port of a `UnitSystem` object that I use in [gala](http://gala.adrian.pw/en/latest/units.html) for handling custom systems of units. The basic idea behind a system of units is, at minimum, a set of irreducible bases that all other units can be composed of. However, this class lets you override  default composite units for easy conversion. The use case I have is that I often want to transform to a "Galactic" unit system where we represent lengths as `kpc`, times as `Gyr` or `Myr`, but velocities as `km/s`. The unitsystem can also be accessed like a dictionary, where the keys are the physical types. The following would work with this PR:

```python
>>> usys = UnitSystem(u.kpc, u.Gyr, u.radian, u.Msun, u.km/u.s)
>>> v = 0.2 * u.kpc/u.Gyr
>>> v.to(usys)
<Quantity 0.1955584443346257 km / s>
>>> usys['length'] / usys['time']
Unit("kpc / Gyr")
>>> usys['speed']
Unit("km / s")
```
There are many details about the implementation that we might want to discuss (do we want singleton classes? do we want to require [length, time, mass, angle] unit bases? etc.).

This would provide a way to fix #703.

At minimum, still needs documentation and a changelog entry...

### CODE REVIEW

**Comment by mhvk** [comment]
@adrn - this looks very nice! Two somewhat related higher-level questions:
1. Could this be made as an extension of the existing type of "unit systems" (`si` and `cgs`);
2. Would it be better to have a corresponding method `to_system` instead of repurposing `to`; it does seem one is asking something different: convert to a new unit (which may or may not be possible), or convert to a preferred unit in a given system (which generally will be possible). Note that `Unit` already has a `to_system` method, so it doesn't seem strange to propagate that to `Quantity`.

**Comment by adrn** [comment]
@mhvk Thanks for taking a look at all of my PR's that are flying your way :)

1. I'm not sure. I never really grokked the implementations of `si` and `cgs`. To me, they just look like python modules with defined base units. That is, there is no concept of a "preferred representation" of a given physical type that could be different from a composition of bases (as we would want for, at least, the Galactic example above). But if you have an idea for how this PR could be unified with those, I'd love to hear!

2. Ah, yes, that would be fine by me.

**Comment by eteq** [comment]
Since we haven't had time to discuss implementation details, I guess this will have to await 3.0 ...

**Comment by astrofrog** [comment]
@adrn - this does seem useful, so maybe worth re-opening/rebasing?

**Comment by adrn** [comment]
Yea

**Comment by astrofrog** [comment]
Ok sounds good - note that this will auto-close again in a week probably (next time the bot runs) unless you rebase or add the 'keep-open' label.

**Comment by adrn** [comment]
Ok - will rebase!

**Comment by bsipocz** [comment]
@adrn - is this still on the table maybe for 4.0?

**Comment by pllim** [comment]
I deleted all the bot comments about closing the PR and see if the bot would behave properly and issue a "gonna close this" warning again next time it kicks off.

**Comment by adrn** [comment]
I would like it to be on the table for 4.0! But I'm not sure where we are with this...I guess @mhvk and I are supposed to discuss?

**Comment by nstarman** [comment]
Having the unit system as a ScienceState and everything, even constants, derive their unit representation from the choice of unit system would be fantastic.
I recently ran into something like this in [SymPy](https://docs.sympy.org/latest/modules/physics/units/index.html) which has a cool implementation of unit and dimension systems.

Also, it would be amazing to have a symbolic version of units, constants, and quantities for numerical - symbolic interoperability.

**Pull request closed without merging**
