### PR TITLE
Use list of keywords instead of generator (py3 fix)

### PR DESCRIPTION
**Pull request by Xarthisius**
On Python 3 header.keys() will iterate instead of return a list, and
we're modifying the dictionary inside the loop. See also:
https://github.com/spacetelescope/PyFITS/issues/74 https://github.com/astropy/astropy/commit/6d4552e450129a003842af9fafd7184b2c788fe8#commitcomment-15453711

### CODE REVIEW

**Comment by embray** [comment]
Thanks @Xarthisius .  I'd be interested to see if by some miracle this also fixes #4460 .

**Comment by embray** [comment]
@Xarthisius While you're on this, could you please change the regular expression to this simplified version:

https://github.com/astropy/astropy/issues/4460#issuecomment-171683935

And add a changelog entry: v1.1.2 -> Bug Fixes -> `wcs` -> "Fixed possible exception in handling of SIP headers that was introduced in v1.1.1. [#4492]"

This is actually bad enough of a bug that I might put out a patch release for it as soon as it's fixed.  It has a somewhat indeterminate nature which is probably why it wasn't caught before.

**Comment by saimn** [comment]
Actually `.keys()` always return a list, even on Python 3 (I had also the same idea this morning while looking at #4460): https://github.com/astropy/astropy/blob/master/astropy/io/fits/header.py#L934

**Comment by embray** [comment]
@saimn You missed this: https://github.com/astropy/astropy/blob/master/astropy/io/fits/header.py#L1977

(Which should probably be closer to the actual methods; also needs to be changed as part of #4477)

**Comment by saimn** [comment]
Ouch, Ok ! 

> (Which should probably be closer to the actual methods; also needs to be changed as part of #4477)
Yes, definitely.

**Comment by embray** [comment]
Ah, it looks like I forgot to update the master changelog after I released v1.1.1.  I'll do that now, then merge this manually.

**Comment by embray** [comment]
Merged in 72d864bde5bd0c304515c4168ced45a0e47dcc72.  Will backport now to v1.1.x branch.

**Pull request closed without merging**
