### PR TITLE
Explicitly require setuptools, astropy/tests/helper.py and astropy/tests/runner.py imports pkg_resources

### PR DESCRIPTION
**Pull request by hrnciar**
### Description

Some files have runtime dependency on setuptools because of importing `pkg_resources` module. In Fedora, we build the package using setuptools, but we ship it to users potentially without it. I suggest explicitly list this requirement.

### CODE REVIEW

**Comment by pllim** [comment]
Hasn't been a problem with other distros. @olebole , are you able to advise? Thanks!

**Comment by olebole** [comment]
In Debian, we have [python3-pkg-resources](https://packages.debian.org/sid/python3-pkg-resources) separately, so we don't need to install the whole setuptools package. python3-astropy (the binary package) doesn't depend on pkg_resources directly (and also not on setuptools), but implicitly via python3-numpy.

So, on Debian, there is no need to install setuptools for the use of Astropy, as long as python3-pkg-resources is installed. A short rgrep however suggests that pkg_resources is rarely used, and seems optional anywa, like here: https://github.com/astropy/astropy/blob/ef31833d826374721a727ad9c427124ffaf693d2/astropy/modeling/fitting.py#L41-L46

**Comment by saimn** [comment]
Yes pkg_resources is optional though it should still be listed as an optional dependency.
This will be fixed by #11091 which replaces the uses of pkg_resources by importlib.metadata.

**Comment by pllim** [comment]
Shall we close this *without* merge in favor of #11091 ?

**Comment by pllim** [comment]
Superseded by #11091 . Thanks anyway; much appreciated!

**Pull request closed without merging**
