### PR TITLE
MNT: Deprecate composition of model classes

### LINKED ISSUE #8234: deprecate composition of model classes
The new code in 4.0 won't allow this.

### PR DESCRIPTION
**Pull request by pllim**
Fix #8234

I am trying to do this in the laziest way I can think of; hopefully no significant performance hit. Suggestions welcome.

### CODE REVIEW

**Comment by pllim** [comment]
@nden , what do you think about this? Should this make it to 3.2 or not?

**Comment by nden** [comment]
It should, I'll get to it before Friday.

**Comment by nden** [comment]
Thanks @pllim !

**Comment by pllim** [comment]
On hindsight, I did not add a test... Let me know if you want a new test and I can issue a follow-up PR.

**Comment by nden** [comment]
I tested it locally and decided it's not worth putting a test to be removed later. But may be we need an issue to remove the warning in 4.0.

**Comment by pllim** [comment]
> may be we need an issue 

Do we? Won't the warning be naturally removed with @perrygreenfield 's refactoring effort?

**Pull request merged**
