### PR TITLE
Fix bugs with evaluating models that accept no inputs.

### PR DESCRIPTION
**Pull request by embray**
Fixes an issue pointed out by @wkerzendorf, where models with zero inputs did not work.  Incidentally the fix is almost exactly the one he put in temporarily.  Just fixed it in another case as well.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
I now get a problem with
```
2294                 outputs[idx] = np.asscalar(output)
```
and output is an array. I wonder if these are related.

**Comment by embray** [comment]
Ah, I thought I had that case covered, but it turns out I didn't.  I've extended the test to check more possibilities, and fixed the issue.

**Comment by wkerzendorf** [comment]
that did it! thanks @embray

**Comment by wkerzendorf** [comment]
it's quite a bit slower than my solution - I'll checkout what is going on.

**Comment by embray** [comment]
Could you quantify that?  What exactly is slower and by how much?  There's nothing about this change that is at all computationally expensive unless you have some enormous number of outputs.

**Comment by wkerzendorf** [comment]
@embray nevermind, must have been something on my side! Anyways, thanks a lot this is great and from my side definitely ready to be merged.

**Pull request merged**
