### PR TITLE
Apply `black` to `astropy.io.misc`

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

Apply `black` to `astropy.io.misc` according to the process laid out by [APE 20](https://github.com/astropy/astropy-APEs/blob/main/APE20.rst).

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by matteobachetti — APPROVED** [review]
It doesn't look like there are any blatant instances of undesirable formatting (e.g. https://github.com/astropy/astropy-APEs/blob/main/APE20.rst#undesirable-formatting), and in general the code reads well (set aside personal preferences). LGTM

**Comment by matteobachetti** [comment]
Milestone? I read somewhere to set 5.3, or was it unrelated?

**Comment by WilliamJamieson** [comment]
> Milestone? I read somewhere to set 5.3, or was it unrelated?

I believe it will go into 5.2 at the end of the `black` freeze. @astrofrog or @saimn may know better.

**Comment by saimn** [comment]
Yes the black PRs will go in 5.2
precommit is failing here though, @WilliamJamieson ?

**Comment by WilliamJamieson** [comment]
> Yes the black PRs will go in 5.2 precommit is failing here though, @WilliamJamieson ?

Per APE 20, we are supposed to do an initial review with the changes made by `black --skip-string-normalization`, which won't normalize the `"` vs `'` style (this will limit the volume of the lines to review). Once everyone is happy, I'll run pre-commit which will normalize all the string and push those changes.

So pre-commit will fail until I do this.

**Comment by WilliamJamieson** [comment]
@matteobachetti I just pushed the commit (07e38d1) normalizing strings. You may want to review that commit separately from the previous ones. It should just be converting (when possible) from using `'` to using `"` for strings.

**Review by matteobachetti — APPROVED** [review]
I went through all the changes in the string formatting commit, and I didn't find any additional changes so LGTM

**Pull request merged**
