### PR TITLE
Re-update IERS B, to be sure it is the correct file.

### PR DESCRIPTION
**Pull request by mhvk**
It seems I did something wrong with #4933 (or there was something wrong with the files at that time), since the latest IERS B seems inconsistent with what I uploaded at the time from 19 May 2015 onwards. For this one, I checked that the various links we found give the same result:
http://hpiers.obspm.fr/iers/eop/eopc04/eopc04_IAU2000.62-now
http://datacenter.iers.org/eop/-/somos/5Rgv/latest/214

### CODE REVIEW

**Comment by mhvk** [comment]
If it is easier to make this commit relative to an earlier version of astropy (e.g., so we can revert #4933), let me know.

**Comment by eteq** [comment]
:+1: to this, *except* I think maybe we should just wait to do this until right before the 1.2 release candidate?  That way we'll have the most up-to-date version. (I added last-before-release on that theory)

Or we can merge this now, and then make a separate last-before-release issue to update it a second time.

**Comment by mhvk** [comment]
I'd prefer to merge now, since currently the values in master are incorrect.

**Comment by mhvk** [comment]
"incorrect" is of course only by very small amounts, but still.

**Comment by mhvk** [comment]
@eteq - I'll merge this now since current master is off, and then put up a new issue to redo it just before 1.2 release. Actually, should that latter one be backported to 1.0.x?

**Pull request merged**
