### PR TITLE
Fix structured units deserialization

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

### Description

See #12586

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by nstarman** [comment]
Starting by reproducing the error.

**Comment by nstarman** [comment]
Darn. Changing the test didn't address the problem, so it appears to be more deeply rooted. I don't understand how this segfaults astropy/samp.
@mhvk, maybe `__reduce__` will fix this. That takes priority over `__getnewargs__`, right?

**Comment by mhvk** [comment]
@nstarman - I think it is a numpy issue mostly, independent of adding the new stanza, but just testing pickling. Though it does seem specific to big-endian (or perhaps the Debian version? I'll see if I can try this on my office computer, which also runs Debian stable)

**Comment by pllim** [comment]
Thanks!

1. Please squash.
2. Is there a numpy issue upstream we can cross-link?
3. We also need a follow up issue to revisit this when upstream bug is fixed.

**Comment by pllim** [comment]
p.s. @saimn did mention at the infrastructure tag up today that the SAMP server error is a red herring.

**Comment by nstarman** [comment]
> 1. Please squash.

✅ 

> 2. Is there a numpy issue upstream we can cross-link?

Maybe #17833. There've been a fair number of PRs.

> 3. We also need a follow up issue to revisit this when upstream bug is fixed.

It actually is fixed! When numpy > v1.21, then pickling should work.

**Review by mhvk — COMMENTED** [review]
I guess ideally we would *know* that the pickle problems are indeed solved in numpy 1.21.1 also for big-endian (after all, on little-endian it seems to have been fine also for oldest numpy we test at).  But I haven't had time yet to set up a qemu session for those...  

I think, though, a first-order item is simply to get the tests working properly again, so am fine with merging this in principle and then backporting.

But: would be good to update the changelog entry for pickling to note that it fails for bigendian with older numpy, and to raise a new issue reminding us that we should test on bigendian with recent numpy.

**Comment by pllim** [comment]
OK, I'll wait for the change log but I have no objection to merging this after either.

**Comment by pllim** [comment]
In the interest of unblocking other PRs, I'll wrap this up.

**Review by pllim — APPROVED** [review]

**Comment by pllim** [comment]
The cron jobs already passed in a previous commit, so there is no need to rerun CI. But I will wait for RTD to make sure I didn't mess up the docs.

**Comment by nstarman** [comment]
> In the interest of unblocking other PRs, I'll wrap this up.

Thanks! I'm AFK for the moment.

**Review by mhvk — APPROVED** [review]
Thanks, @pllim, that looks all OK!

**Comment by pllim** [comment]
Hrmmm RTD server seems stuck.

**Comment by pllim** [comment]
I am going to try the close/re-open trick. If it still doesn't work, might just have to YOLO it.

**Pull request merged**
