### PR TITLE
Fix conflict between WCSHDO_SIP and the WCSHDO_P* precision keywords

### LINKED ISSUE #5162: Specifying precision in wcs.to_header() does not work
Using `wcs.to_header(relax=WCSHDO_P17)` seems to have no effect, I get the same output if I don't use `relax` (with a default precision to `WCSHDO_P14`).
This was added in #4616, cc @nden 

I think there is a conflict with the default value for `WCSHDO_SIP`, though 81b9e94540bbcfd771a581874d3fb5ac338da639 was trying to avoid that.

### PR DESCRIPTION
**Pull request by saimn**
Fix #5162, cc @nden

### CODE REVIEW

**Comment by pllim** [comment]
This will need a change log before merging. FYI.

**Comment by saimn** [comment]
Added changelog in 1.2

**Comment by nden** [comment]
@saimn Thanks for catching and fixing this!

Looking at `to_header()` again, there's another bug. It's obscure and the case that would expose it is very rare. This [line](https://github.com/saimn/astropy/blob/192d45d0680fb9598ed91cab73802be5849d166b/astropy/wcs/wcs.py#L2515) calculates the composition of flags to be passed to `wcslib`. Currently it is incorrect when `relax=True`. A possible fix is to add the following two lines immediately before the composition line:

```
if relax is True:
    relax = WCSHDO_all
```
If you think this is a solution could you add them to your PR. The bug affects only data saved as pixel lists to tables and I don't have a test case. Alternatively I can open a separate PR.

`to_header()` turned into a complex function and it's hard to understand the logic. It's probably best if it's refactored and simplified in the future .

**Comment by saimn** [comment]
@nden - Indeed, but the same apply to `relax=False`, no ? Should be `WCSHDO_safe` in this case ?

**Comment by saimn** [comment]
@nden - Something like ab4b4c31d8394148195170015feb059281091062 ?

**Comment by nden** [comment]
When `relax=False` (since `False` in python is always 0), `relax = precision | False` is always equal to `precision`, right?
I like what you did in ab4b4c3 but I think it needs to be `WCSHDO_none`, to get the equivalent of `relax=False`. The definition of `WCSHDO_safe` is a composition of a few flags (definitions [here](https://github.com/astropy/astropy/blob/master/cextern/wcslib/C/wcshdr.h#L1182)).

**Comment by saimn** [comment]
Indeed, using `WCSHDO_none`  would give the same result as before (`relax=False`), but it is more explicit. I changed this in the last commit.

I used `WCSHDO_safe` before because it seems to match the docstring (*`False` (default): Write all extensions that are considered to be safe and recommended.*)

**Comment by saimn** [comment]
Actually I'm still confused:
http://docs.astropy.org/en/latest/wcs/relax.html#header-writing-relaxation-constants
> If **False (default)**, write all extensions that are considered to be safe and recommended, equivalent to **WCSHDO_safe** (described below).

**Comment by nden** [comment]
@saimn Ah, you are right, `relax=False` means that `WCSHDO_safe` is passed ( [actual code](https://github.com/astropy/astropy/blob/master/astropy/wcs/src/wcslib_wrap.c#L1914)).

**Comment by saimn** [comment]
Ok ! So since the use of `precision | relax` something is broken here for both cases (True and False), and we need to use `WCSHDO_all` or `WCSHDO_safe` in the Python code (last commit switch back to using `WCSHDO_safe`).

**Comment by nden** [comment]
Thanks @saimn.

**Comment by saimn** [comment]
Thanks :)

**Pull request merged**
