### PR TITLE
WIP: Support masked arrays in LinearLSQFitter

### PR DESCRIPTION
**Pull request by jehturner**
Candidate solution for #4824 & #6819 for linear fitting. Currently this adds support for masked arrays in `modeling.fitting.LinearLSQFitter`.

### CODE REVIEW

**Comment by jehturner** [comment]
This would require some TBD changes to `modeling.fitting.FittingWithOutlierRemoval`. I think that's straightforward except for how to distinguish whether or not  a given fitter supports masked arrays. @mirca is welcome to propose something.

**Comment by nden** [comment]
@jehturner Sorry, I haven't had time to look at this issue. So the solution here is to iterate over each model? Can you add a test/example with a masked array?

**Comment by jehturner** [comment]
Yes, of course, the test(s) and change log entry are still pending (good point about an example). I (or @mirca) still have to change `FittingWithOutlierRemoval`, but thought I'd show you both what this looks like first. This iterates over each model only when given a masked array with one or more bad pixels, otherwise it does them all at once like before. It could perhaps be improved a bit further by grouping models with the same bad pixels (eg. bad columns or rows with no rejection), but at least it shouldn't significantly slow down anything that worked before. This is still far from optimal, but it works and I think we would have to replace `np.linalg.lstsq` with some other compiled code to do better.

**Comment by nden** [comment]
Thanks! I still haven't convinced myself there's no some math trick that can do this without iteraion but this is a start.

**Comment by jehturner** [comment]
Right, I hadn't *completely* convinced myself either, but I have trouble seeing how the problem could be represented in the matrix equation expected by `np.linalg.lstsq` (which only works with 2D inputs). At least I think `lstsq` would need to be aware of what to do with masked points (on the RHS only), omitting certain terms when calculating the Euclidian norm. I'll be happy if someone can prove me wrong...

**Comment by jehturner** [comment]
Aside from that, I think the main decision now is how to tell `FittingWithOutlierRemoval` whether a given fitter supports masked arrays or it should mask points itself (as it does now for single models). I was not planning to tackle the other fitters now, especially when they can't handle model sets anyway. We could add a `supports_masks` boolean attribute to fitters or simply make `FittingWithOutlierRemoval` try to pass a masked array when given a model set (but that could silently fail to apply the mask if a future fitter supports model sets but not masking).

**Comment by jehturner** [comment]
Sorry, this got closed automatically when I reverted a couple of commits after getting my local repo out of sync with github. I'm re-opening it with a squashed commit...

**Comment by jehturner** [comment]
I've only recently become aware of the code freeze deadline and have had to work on other things... Since I'm still figuring out how to finish modifying `FittingWithOutlierRemoval`, I have completed the documentation, changelog entry and a couple of tests for `LinearLSQFitter` masked array support in the meantime, in the hope that we can get this into 3.0? This is really the core change, as it's easier to support outlier removal directly in user code than it is to replace the linear fitter.

I've amended the title of this PR accordingly.

Thanks!

**Comment by jehturner** [comment]
Drat, adding ``+FLOAT_CMP`` didn't fix the remaining doctest difference on some platforms, presumably because the column header formatting (eg. number of dashes) changes along with the number of decimal places... I suppose I'll just have to change the doctest to print the coefficients explicitly instead of the model's ``__str__()``.

**Comment by jehturner** [comment]
I think this is ready for review if @nden or someone gets a chance. It doesn't solve everything from #4824 & #6819 yet, but I think it's useful as it stands.

**Comment by nden** [comment]
@jehturner Thanks for all the work on this. This looks good.
I think it's probably good to backport it to the 2.x versions so I'm setting the milestone as 2.4. Could you move the change log entry to 2.4? 

I think using `_support_masked_input` or some similarly named attribute is fine.

Have you tried this with 2D models?

**Comment by jehturner** [comment]
Moved changelog entry to 2.0.4 and squashed the commits again. I'm not sure why this is still complaining about the astropy-bot check. I've just noticed that the changelog section I added this to (the only one) is entitled "bug fixes". Does that seem like the right place for it, or shall I create "other changes and additions"?

I did consider and play around with 2D models but perhaps I should add a test for them...

**Comment by mwcraig** [comment]
>  I've just noticed that the changelog section I added this to (the only one) is entitled "bug fixes". Does that seem like the right place for it, or shall I create "other changes and additions"?

My $0.02 would be bug fix. The previous behavior was to accept masked array input but to silently ignore the mask.

**Comment by jehturner** [comment]
Everything is fixed now but I'm about to add a 2D test (sorry for the noise in my last comment).

**Comment by jehturner** [comment]
Just remembered I should add `supports_masks` or `_support_masked_input` now, rather than when changing `FittingWithOutlierRemoval`. Do you think this should be a private attribute, @nden, bearing in mind that people may write their own fitters and `FittingWithOutlierRemoval` will need to know what to do with them?

**Comment by nden** [comment]
@jehturner Yeah, you are right, public is better.

**Comment by jehturner** [comment]
OK, I'll go with `supports_masked_input` (as in your suggestion, but I think the plural will be more descriptive as written and this is similar to, say, `model._supports_unit_fitting` elsewhere).

**Comment by jehturner** [comment]
@bsipocz: circleci is failing (twice) with this, just FYI. I think the PR is ready otherwise.
```
Pulling repository docker.io/astropy/astropy-py35-32bit-test-env
Tag 1.10 not found in repository docker.io/astropy/astropy-py35-32bit-test-env
```

**Comment by nden** [comment]
Thanks @jehturner !

**Comment by jehturner** [comment]
Great, thanks for looking over it quickly. Now I just need to find a spare moment to do the same for @mwcraig...

**Comment by bsipocz** [comment]
Hmm, is this really a bug fix? We can't really change behaviour that users expect in the LTS branch. @eteq?

**Comment by jehturner** [comment]
We have votes for the v2 branch from @nden and @mwcraig, but I can revert it to 3 and/or describe it differently in the change log if you want. I would also prefer it in 2.0.x, however, as I'm still stuck on Python 2 for now and will have to patch the code myself otherwise...

**Comment by bsipocz** [comment]
@jehturner - Well, everything can stay as is, no need to revert or change anything (this is currenly on master only as the backporting is done separately). 

Sadly the LTS stability is a separate question from convenience, so I need the confirmation back on that question before doing the backport.

**Comment by jehturner** [comment]
OK. The argument is that the fitters should not have silently ignored masked values in the first place, but it's always a fair question about changing the behaviour. Only the linear fitter now handles masks properly, but it's now documented that the others don't, which arguably makes it not a bug any more 😜.

**Comment by nden** [comment]
I think you can go either way. To me the important thing is that it does not change how the code worked in the previously supported use casses but adds something which will be good to have in the LTS version.

**Comment by eteq** [comment]
This is a rather difficult corner case.  I agree that the fitter shouldn't have been silently ignoring the masks, *but* it is definitely a change of behavior without warning, and in general we promise not to do this in an LTS.

So here is what I propose:
1) re-milestone this to 3.0 and not backport it
2) create a new issue (with milestone 2.0.4) that summarizes this concern
2) make a PR against 2.0.x (*only*, not master) that checks for a mask and generates a *warning* that says something like "masks are being silently ignored.  If you upgrade to 3.0 they will be accounted for in the fitter.  If you feel strongly that this should or should not be included in the 2.0.x branch of Astropy, please leave your thoughts in <link from the previous step here>"

That way we fix the bug of "silently ignoring mask" (it's no longer silent) while not introducing an actual behavior change in a bugfix version.

Sound reasonable, @nden @jehturner @mwcraig @bsipocz ?

**Comment by mwcraig** [comment]
That works, though I think the current 2.x behavior is incorrect. It is definitely not the right thing to do to silently ignore masks. The only behavior change would be that masks are not ignored, which I would guess most people would want.

That said, I don't feel that strongly about it, and I could see an argument for waiting until it is also fixed for the non-linear case.

**Comment by jehturner** [comment]
Sounds reasonable. I think there are other cases where more helpful messages could be added pending fixes, eg. when trying to fit a model set with the existing `LinearLSQFitter` (though at least that case fails outright), but it's a start...

It looks like this has indeed been merged into the 3.0.x branch (and not 2.0.x) but that `CHANGES.rst` and `.. versionadded:: 2.0.4` in the documentation still need updating to reflect that? What do you want to do about that? Thanks.

**Pull request merged**
