### PR TITLE
Fix error in example usage of z_at_value()

### PR DESCRIPTION
**Pull request by MDAddario**
Call to np.interp() passes arguments in wrong order, the grid data points for the dependent variable were mixed up with the grid data points for the independent variable

### Description

This pull request is to address an incorrect code example present in the z_at_value() documentation. The call to numpy's interpolate function mixes up the order of the two grids that need to be passed in.

### CODE REVIEW

**Comment by pllim** [comment]
Hmm. This example is all the way back from #1909

**Comment by pllim** [comment]
I'll let the reviewers decide if the change log is really necessary here.

**Comment by bsipocz** [comment]
> I am inclined to think it shouldn't be in the changelog though,

a change in the docstring example is definitely not a changelog entry

**Comment by bsipocz** [comment]
(CI failures are unrelated, thus this can be merged once the changelog entry is removed. Thanks @MDAddario for catching this!)

**Comment by MDAddario** [comment]
I removed the changelog entry, glad to help!

**Pull request merged**
