### PR TITLE
API: allow lengths of non-scalar frames without data

### PR DESCRIPTION
**Pull request by mhvk**
In #16831, we ran into the problem that frames without data do not have a length, even though the can have a shape. This means they cannot easily be stored in a `Table` without changing how mixin columns work in tables.

More generally, it is strange that something that has a shape cannot be iterated over in normal ways (`for i in range(len(frame)): <do something with frame[i]>`.

So, I here suggest to change the API so that for any frame, with or without data, it is true that `len(frame) == frame.shape[0]` (or a `TypeError` is raised if the frame is scalar).

It turns out that *no* tests actually relied on the existing behaviour! So, perhaps the API break is not very large. Furthermore, the changes just mean removing the definitions of `__len__` and `isscalar` -- i.e., instead relying on definitions from the `ShapedLikeNDArray` superclass.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by mhvk** [comment]
Just an extra note: I'll happily add text fixing the new behaviour once there is agreement this change is fine!

**Comment by eerovaher** [comment]
As far as I can tell the two methods that are being removed here served some purpose before #15121, but don't seem to be needed anymore. It would be a good idea to check if this pull request is relevant for #15415.

**Comment by mhvk** [comment]
> As far as I can tell the two methods that are being removed here served some purpose before #15121, but don't seem to be needed anymore. It would be a good idea to check if this pull request is relevant for #15415.

Yes, indeed, pre #15121 there was even more of an attempt to have the `shape` just be that of the data, and attributes just had to broadcast with it, while in #15121 proper broadcasting of the data was introduced. It might have been logical to change `__len__` and `isscalar` at that time...

#15415 is not directly relevant - that is really more of an implementation detail for `Attribute` that only depends on `shape`.

**Comment by eerovaher** [comment]
The change seems reasonable to me, but it would be better if there was a test that would document that the difference between old and new behavior is intentional.

**Comment by mhvk** [comment]
> The change seems reasonable to me, but it would be better if there was a test that would document that the difference between old and new behavior is intentional.

Yes, I definitely will add tests - just want to be sure people agree the change is OK first!!

**Comment by mhvk** [comment]
@eerovaher - I went ahead and added tests, since you seemed to think the general idea is good, and I have not yet heard from others -- @StuartLittlefair and @adrn - do comment if you think giving frame-less data a length is a bad idea.

**Comment by mhvk** [comment]
p.s. I added the tests as an extra commit, so that one can see that before there were *no* tests that relied on frame-less data not having `len()` -- the tests passed already.

**Comment by adrn** [comment]
I think this change is fine. But of course this gets me thinking about discussions we have had about making frames inherently data-less, but that is not really relevant for this PR...!

**Review by adrn — APPROVED** [review]

**Comment by StuartLittlefair** [comment]
Like @adrn i approve the change.

**Comment by mhvk** [comment]
OK, great, thanks both! Since @eerovaher already said he was OK, I'll merge so that I can rebase my `.info` PR on it and frames can become part of tables...

p.s. I do like the idea of data-less frames only, but it will probably need a deprecation crutch where, if data is passed in, a `SkyCoord` is returned...  Anyway, for another time...

**Pull request merged**
