### PR TITLE
module pandas has no attribute 'compat'

### PR DESCRIPTION
**Pull request by embray**
While testing Astropy 1.1rc2 on MacOS X with Python 3.5, I ran into the following errors:

```python
_______________________________________________________________ ERROR collecting table/tests/test_index.py ________________________________________________________________
miniconda3/envs/astropy-test-3/lib/python3.5/site-packages/astropy/table/tests/test_index.py:4: in <module>
    from .test_table import SetupData
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
_pytest.assertion.rewrite:171: in load_module
    ???
miniconda3/envs/astropy-test-3/lib/python3.5/site-packages/astropy/table/tests/test_table.py:22: in <module>
    import pandas
miniconda3/envs/astropy-test-3/lib/python3.5/site-packages/pandas/__init__.py:7: in <module>
    from pandas import hashtable, tslib, lib
pandas/tslib.pyx:4789: in init pandas.tslib (pandas/tslib.c:107900)
    ???
pandas/tslib.pyx:4736: in pandas.tslib.TimeRE.__init__ (pandas/tslib.c:78940)
    ???
pandas/tslib.pyx:4773: in pandas.tslib.TimeRE.pattern (pandas/tslib.c:79853)
    ???
miniconda3/envs/astropy-test-3/lib/python3.5/re.py:325: in _subx
    template = _compile_repl(template, pattern)
miniconda3/envs/astropy-test-3/lib/python3.5/re.py:312: in _compile_repl
    p = sre_parse.parse_template(repl, pattern)
miniconda3/envs/astropy-test-3/lib/python3.5/sre_parse.py:919: in parse_template
    DeprecationWarning, stacklevel=4)
E   DeprecationWarning: bad escape \s
_______________________________________________________________ ERROR collecting table/tests/test_table.py ________________________________________________________________
miniconda3/envs/astropy-test-3/lib/python3.5/site-packages/astropy/table/tests/test_table.py:22: in <module>
    import pandas
miniconda3/envs/astropy-test-3/lib/python3.5/site-packages/pandas/__init__.py:42: in <module>
    import pandas.core.config_init
miniconda3/envs/astropy-test-3/lib/python3.5/site-packages/pandas/core/config_init.py:13: in <module>
    import pandas.core.config as cf
miniconda3/envs/astropy-test-3/lib/python3.5/site-packages/pandas/core/config.py:57: in <module>
    import pandas.compat as compat
E   AttributeError: module 'pandas' has no attribute 'compat'
```

This is with the following version of pandas:

```python
In [2]: pandas.__version__
Out[2]: '0.17.1'
```

and the test header is

```python
platform darwin -- Python 3.5.1 -- py-1.4.30 -- pytest-2.7.3
rootdir: /Users/tom/miniconda3/envs/astropy-test-3/lib/python3.5/site-packages/astropy, inifile: 

Running tests with Astropy version 1.1rc2.
Running tests in /Users/tom/miniconda3/envs/astropy-test-3/lib/python3.5/site-packages/astropy.

Date: 2015-12-08T12:02:48

Platform: Darwin-12.5.0-x86_64-i386-64bit

Executable: /Users/tom/miniconda3/envs/astropy-test-3/bin/python

Full Python Version: 
3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55) 
[GCC 4.2.1 (Apple Inc. build 5577)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.10.1
Scipy: 0.16.0
Matplotlib: 1.5.0
h5py: 2.5.0
Using Astropy options: remote_data.
```

Note that we should add pandas to the test header.

### CODE REVIEW

**Comment by embray** [comment]
@astrofrog Thoughts?

**Comment by embray** [comment]
Upstream fix in https://github.com/pydata/pandas/pull/11798

**Comment by astrofrog** [comment]
:+1: from me. I personally think that only critical bug fixes should be backported at this stage so this should really go in 1.1.1, but I'll leave the final decision with you.

**Comment by embray** [comment]
I think it's a problem insofar as it can cause the existing test suite to fail.

**Pull request merged**
