### PR TITLE
Upgrade to WCS 5.9 (take two)

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by nden** [comment]
@mdboom Please hold on merging this. I am trying to track down some very small numerical differences in the local tests with this version.

**Comment by nden** [comment]
@mdboom I see differences of the order of 10**-11 in CRVAL when I read in a WCS and print it back with `to_header`. A minor difference but given that we use double precision everywhere it's not quite negligible. Looking at the changes in wcshdr.c (which I don't understand) I wonder if the precision was somehow decreased and whether this was intentional. Here's how you can reproduce what I see:

```
f=fits.open('j94f05bgq_flt.fits')
w=wcs.WCS(f[1].header, f)
w.to_header()['CRVAL*']
Out[10]: 
CRVAL1  =        5.63056810618 / [deg] Coordinate value at reference point      
CRVAL2  =      -72.05457184279 / [deg] Coordinate value at reference point      

f[1].header["CRVAL*"]
Out[11]: 
CRVAL1  =        5.63056810618 / first axis value at reference pixel            
CRVAL2  =   -72.05457184278998 / second axis value at reference pixel           
CRVAL1O =        5.63056810618                                                  
CRVAL2O =       -72.0545718428                                                  

# with alternate WCS
wo=wcs.WCS(f[1].header, f, key='O')
wo.to_header()['CRVAL*']
Out[13]: 
CRVAL1O =         5.6305681062 / [deg] Coordinate value at reference point      
CRVAL2O =       -72.0545718428 / [deg] Coordinate value at reference point    
```

Interestingly, if I save the output of `to_header` and repeat the above, it works as expected.

```
hdr=w.to_header()
w2 = wcs.WCS(hdr, f)
w2.to_header['CRVAL*']
w2.to_header()['CRVAL*']
Out[24]: 
CRVAL1  =        5.63056810618 / [deg] Coordinate value at reference point      
CRVAL2  =      -72.05457184279 / [deg] Coordinate value at reference point      

hdr['CRVAL*']
Out[25]: 
CRVAL1  =        5.63056810618 / [deg] Coordinate value at reference point      
CRVAL2  =      -72.05457184279 / [deg] Coordinate value at reference point      
```
I would think this is a bug as I don't expect initializing a WCS and writing the header out should change any values. What do you think?

**Comment by mdboom** [comment]
A couple of things:

- I see the same behavior on master as on this branch.  Though the calculation of the output precision has changed here -- which I think is just to avoid printing unnecessary decimal points -- it has the same net effect (the calculated format string is the same as the old hard-coded one).

- The result of `w.to_header_string()` exactly matches the value in the file.

- The value output from the FITS Header object is *not* exactly the same as what's in the file.  But as far as I can tell `astropy.io.fits` has done this for a long time (at least back to astropy 0.4).

So, something puzzling here -- but because I'm not seeing a difference between master and this, I don't know if this exactly is the source of the change in results you're seeing...

**Comment by nden** [comment]
Yeah, you are right - master behaves in the same way. There's something else going on.

**Comment by nden** [comment]
:+1: to merge from me.

**Comment by mdboom** [comment]
Cool.  Did you ever get to the bottom of the numerical differences -- or was it just in the display?

**Comment by nden** [comment]
It's a real difference in the regression tests. I confirmed the new wcslib version is causing it and that it's not accumulating. My guess is a string is converted somewhat differently in wcslib. But I'm not going to lose sleep over this.

**Comment by keflavich** [comment]
@mdboom this change has broken a test in astroquery that I suspect is related to the numerical differences you and @nden were discussing.  

https://travis-ci.org/astropy/astroquery/jobs/72349789#L1150

To get around this in astroquery, I'll need to have a different numerical check for different astropy versions.  Is that what I should do?

**Comment by mdboom** [comment]
@keflavich: Before you write a different test for different versions, let's try to get to the bottom of the differences.  I don't think that any changes here were *intentional*, so ideally we'd get things straightened out before the next release of astropy.

Can you provide a self-contained example that shows the change?

**Comment by nden** [comment]
Here's an example from me (there must be a better one) which gives differences when run with 5.9 and 5.7. 

```
f = fits.open('j94f05bgq_flt.fits')
w1 = wcs.WCS(f[1].header, f)
hdr1 = w1.to_header()
 w11 = wcs.WCS(hdr1)
```

With 5.9:

```
w1.all_pix2world(2000, 4000, 1)
Out[7]: [array(5.685588356421345), array(-72.09136016769364)]

w11.all_pix2world(2000, 4000, 1)
Out[12]: [array(5.686165384816638), array(-72.092436087654)]
```

With 5.7

```
w1.all_pix2world(2000, 4000, 1)
Out[14]: [array(5.685588356421345), array(-72.09136016769364)]

w11.all_pix2world(2000, 4000, 1)
Out[15]: [array(5.686165384816642), array(-72.09243608764382)]
```
`to_header` returns slightly different values. In this example the `PC` values were different. In the regression tests I see some of the CRVALs are also different.
Another way to see the problem is to read in a primary WCS and write it out as an alternate WCS.

**Comment by mdboom** [comment]
@nden: I can reproduced your results, but they are inverted: i.e.: I get what you get for wcslib 5.7 with wcslib 5.9 and vice versa.  Is is possible you just copied them over incorrectly?

**Comment by mdboom** [comment]
Here's what I can gather.  The `PC1_1` value is stored in the file as `CD1_1` with a value of

`1.29055156973602E-05`

With wcslib 5.8, it spits it back out as:

`1.29055156974E-05` (i.e. the last 3 digits have been dropped and rounded up)

With wcslib 5.8, it spits it out as:

`1.2905515697360E-05` (i.e. it's still dropping one digit, but it's overall closer to the original)

That's still not perfect.  With the following patch:

```diff
@@ -1673,9 +1673,9 @@ void wcshdo_format(
     sprintf(format, "%%20.%df", precision);
 
   } else {
-    precision = nsig - 1;
+    precision = nsig;
     if (precision < 1)  precision = 1;
-    if (13 < precision) precision = 13;
+    if (14 < precision) precision = 14;
     sprintf(format, "%%20.%dE", precision);
   }
 }
```

I can then finally get the entire input number back out.

Therefore, there is definitely a change in behavior, but it's hard to argue that that change isn't more accurate and for the better.  Annoying for us, of course, because it breaks some regression tests.

@keflavich: I haven't investigated your specific problem yet.  Does it involve parsing WCS headers with `astropy.wcs`, writing them out and reading them in again?  If you're not doing that, it's likely a different problem than @nden is having.

**Comment by mdboom** [comment]
@keflavich: https://github.com/astropy/astroquery/issues/561 definitely involves outputting the header as a string and reparsing it (because it seems that's what pyregion works with and requires).  I'm not sure how best to address that, but it does seem you are getting more accurate (i.e. matching the input file) than before, though of course, this is worrisome:

```
>       assert d.sum() == 314 # approximately pi
E       assert 313 == 314
```

since 313 is more different from pi than 314.  I don't know enough about what the test is trying to do to say...

**Comment by keflavich** [comment]
@mdboom I think this test is drawing a circle on a FITS figure, making a mask, and counting the pixels - so it is OK if it's off by +/- a few pixels, I think.  There are bugs in pyregion anyway (0.5 pixel offsets).

**Comment by nden** [comment]
@mdboom Sorry, my examples were inverted.

**Comment by keflavich** [comment]
@mdboom this is also affecting `spectral_cube` now, since we were testing string comparisons between two different WCSes, and they go through a read/write cycle:
https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/73340794#L566

should I just remove or somehow modify this test to work?  I think wcstools 5.9 is here to stay...?

**Comment by mdboom** [comment]
You can get the version of wcslib in use by doing:

```
from astropy.wcs import _wcs
_wcs.__version__
```

Then I would update the test to act accordingly depending on version.

Despite this being a change in behavior, it's clearly an improvement as it is preserving more digits of precision in the output.  This will only be on the next *major* release of astropy for that reason, and there is an API changes warning in the changelog.

And just another heads up as if this weren't enough: It turns out this change is still not sufficient.  It's still missing the very final digit (in some situations).  I've reported this to Mark Calabretta and he agrees we should fix this "all the way" and I suspect will be releasing a 5.10 with this change in the coming days.  You may want to wait on updating the test in order to not have to do it twice.  Note that does mean that wcslib 5.9 will never be in an official astropy release, so I don't need to write your test to handle 5.9, just 4.x and 5.10.

**Comment by keflavich** [comment]
@mdboom: thanks for the clarification & heads up.  I will wait for the next version to drop.

**Pull request merged**
