### PR TITLE
Fix problem using round() with astropy Quantities

### PR DESCRIPTION
**Pull request by alfiopuglisi**
### Description

This pull request is to address this error when using the Python built-in round() function with an astropy Quantity argument:

```
>>> import astropy.units as u
>>> value = 10.2 * u.s
>>> round(value)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type Quantity doesn't define __round__ method
>>> 
```

This because the round() built-in delegates the work to a __round__() dunder method and astropy Quantities, even if they have a round() method, do not define the dunder method.
This PR adds a Quantity.__round__() method that calls Quantity.round() to do the work.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by nstarman** [comment]
> This is not an issue for Quantity, where only floats make sense (integer Quantity are bad!).

We support sensible integer Quantities, like `count`, for Poisson statistics.
Importantly the dtype promotion rules means integer arrays will easily become float arrays again.
Given that I would say that for Quantity it makes sense to support `__round__` with

```python
Array[dtype, ...]

@overload
def __round__(self[Any], ndigits: None) -> Self[integer]: ...

@overload
def __round__(self[Any], ndigits: Literal[0]) -> Self[integer]: ...

@overload
def __round__(self[Any], ndigits: int) -> Self[floating]: ...
```

**Comment by mhvk** [comment]
Sorry, but definitely no way, I'd rather stick with no `__round__` at all (which is not something one should typically do). I really regret ever making integer quantities even possible; it is just not physical.

**Comment by nstarman** [comment]
> it is just not physical.

Anything intrinsically discretized, like many quantum systems, which appear not infrequently in astronomy.

**Comment by mhvk** [comment]
> > it is just not physical.
> 
> Anything intrinsically discretized, like many quantum systems, which appear not infrequently in astronomy.

Where unit conversions are still useful? Really? Please give an example! Rarer even than complex quantities, I think.

Anyway, let's please not distract a simple PR! I think we should either go with this simple one or decide to wait what numpy does and then just use that.

**Comment by alfiopuglisi** [comment]
Hello all,
the reason I sent this PR is because I noticed that some unit tests
using unittest.TestCase.assertAlmostEqual() were failing, because that
method uses round() internally. Upon investigating, the test was
extracting a single element from an array, and in this case, the current
behaviour is different from numpy. Compare these two snippets:

>>> a = np.array([2.3])
>>> round(a[0])
2

>>> b = np.array([2.3]) * u.s
>>> round(b[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type Quantity doesn't define __round__ method

Because extracting an element from numpy gives a built-in float, while a
Quantity remains a Quantity. So at the moment it would need a special
treatment.
Also round() is not just used to round to integer, it has an argument for
the number of digits (assertAlmostEqual in fact uses it)

Alfio

**Comment by nstarman** [comment]
I'm not a QM astro person (e.g. some radiation stuff), but a [cursory search for the buzzwords here](https://ui.adsabs.harvard.edu/search/filter_database_fq_database=AND&filter_database_fq_database=((database%3Aastronomy%20OR%20database%3Aphysics))&filter_database_fq_database=database%3A%22astronomy%22&fq=%7B!type%3Daqp%20v%3D%24fq_database%7D&fq_database=(((database%3Aastronomy%20OR%20database%3Aphysics))%20AND%20database%3A%22astronomy%22)&q=%20abstract%3A%22discrete%22%20%20full%3A%22units%22%20full%3A%22quantum%22&sort=date%20desc%2C%20bibcode%20desc&p_=0) turned up many examples. Just on the [first](https://ui.adsabs.harvard.edu/abs/2024AnPhy.46869739A/abstract) we find creation and annihilation operators for photons. This is discrete and in integers.

**Comment by nstarman** [comment]
> Anyway, let's please not distract a simple PR! I think we should either go with this simple one or decide to wait what numpy does and then just use that.

But yes, I'm also fine with us punting to numpy / or a seperate conversation in a dedicated Issue and doing ``__round__() -> .round() `` for now!

**Comment by mhvk** [comment]
@nstarman - Then they wouldn't need `round` anyway :smiley_cat: Anyway, we could decide that in the case where 2 different developers feel the obvious "guess" is different, then one should refuse the temptation to guess. Which means leaving things as they are. I'm fine with that. Indeed, the same was suggested in the [numpy discussion](https://github.com/numpy/numpy/issues/6248#issuecomment-1334590148) because many floats cannot be represented as an `int64` (of course, never going to `int` prevents that pitfall).

@alfiopuglisi - you're analysis is indeed correct; numpy makes an exception for scalars, converting those to python float, and then doing usual `round`.

**Comment by alfiopuglisi** [comment]
An example from AO systems: take a bunch of detector frames, with unit u.adu (naturally integer), average them obtaining a floating point, and convert (round) them back to integer before uploading to the real time computer as dark/background maps to be subtracted. Often done in order to keep the result expressable in adu as well.

**Comment by mhvk** [comment]
> But yes, I'm also fine with us punting to numpy / or a seperate conversation in a dedicated Issue and doing `__round__() -> .round() ` for now!

Great, so @alfiopuglisi, please go ahead and add a changelog entry! I think that really is all that is missing.

**Comment by alfiopuglisi** [comment]
> Great, so @alfiopuglisi, please go ahead and add a changelog entry! I think that really is all that is missing.

Ok, done!

**Review by mhvk — APPROVED** [review]
Thanks, this looks all good to me now; let's get it in!

**Pull request merged**
