### PR TITLE
Check if outfile is an instance of io.TextIOWrapper

### PR DESCRIPTION
**Pull request by sahmed95**
Added a condition to check if the file like object is an instance of io.TextIOWrapper

### CODE REVIEW

**Comment by mdboom** [comment]
Is this the right thing to do?  TextIOWrapper generally has an encoding and wouldn't work for a binary format like FITS.  I think generally a TextIOWrapper *should* be rejected.

**Comment by embray** [comment]
I think I might be okay with it in principle.  I've been in the process of making a similar set of changes, actually.  The idea here is that a "typical" user is unaware of opening a file in text mode versus binary mode.  My ideal preference would be to raise an error and not allow it, but since it's easy enough to access the underlying raw buffer I think it's nicer to just go ahead an use that and assume the user's intent (maybe issuing a warning in the process).

I might not make the specific change here though.  @sahmed95, was there a specific issue that motivated this change?

**Comment by sahmed95** [comment]
@embray My bad, this is concerning issue #3427. Should've mentioned that in the commit message

**Comment by embray** [comment]
Oh I see--thanks.  As I wrote earlier I think this general approach might be okay, but I need to give it a little more thought.

**Comment by pllim** [comment]
Digging through old FITS PRs. @embray , are you still somehow thinking about this?

**Comment by bsipocz** [comment]
I'm going to close this due to lack of activity.

@sahmed95  - please feel free to reopen if you plan to wrap this up.

**Pull request closed without merging**
