### PR TITLE
Update IERS B table for inclusion in 1.0

### PR DESCRIPTION
**Pull request by mhvk**
Hopefully the last time that it is done by hand! (Note that it is slightly disconcerting that there are actual *changes*, however small, in this file; from the documentation, I had understood it is always meant to be the definitive version.)

### CODE REVIEW

**Comment by embray** [comment]
Which is to say, it never contains predictions?  If so, that is disconcerting that there were changes...

**Comment by mhvk** [comment]
Indeed, IERS B is the one that should contain final values, IERS A the one with predictions. That said, the differences are all in the last digit of X, so presumably it is some rounding/format error that doesn't matter much in practice (I tried finding a rationale, but couldn't). But it makes it all the more important to do checksums when we implement doing any partial updates.

**Comment by embray** [comment]
*sigh* :frowning:

**Comment by eteq** [comment]
My understanding is that this table is actually generated from a fairly complex fit to the actual observed time series of EOPs (which isn't necessarily at regular intervals).  So maybe these small deviations are just slight tweaks to the best-fit solutions based on newer data, and that's why they changed a tiny bit despite not being predictions?

Anyway, as @mhvk said, it's small, so I think this is fine.  Merging!

**Pull request merged**
