### PR TITLE
joining two tables using differring column names

### PR DESCRIPTION
**Pull request by bsipocz**
This is to add the workaround discussed in #3752.

### CODE REVIEW

**Comment by taldcroft** [comment]
Thanks, this is helpful!

Since the join section is starting to get long, I would suggest adding two subsections:

New subsection `Different join options` just before `The table joins so far are known as "inner" joins and represent the strict intersection of the two tables on the key columns.`

New subsection `Non-identical key column names` before the new stuff you added.  Then start with a sentence like "The |join| function requires the key column names to be identical in the two tables.  However, in the following case one table has a `name` column while the other has an `obj_id` column".

While you are in there, can you change the section `Identical keys` to `Identical key values`?  As I was just looking there I think that `Identical keys` is confusing.

**Comment by bsipocz** [comment]
@taldcroft - I've done your suggestions. I'm sorry it took so long.

**Comment by taldcroft** [comment]
@bsipocz - No problem on the delay, looks good now.  I'll be merging this, but I just want to confirm that you did run `build_sphinx` locally to make sure there isn't some teeny sphinx error that neither of us notice (since you did `[skip ci]`).

**Comment by bsipocz** [comment]
Yes, I made a local build, and travis passed on the first commit, too.

**Comment by embray** [comment]
Missing milestone; changelog entry.

**Comment by taldcroft** [comment]
@embray - this is a pure doc update, and I thought that historically those don't get a changelog entry.

**Comment by embray** [comment]
Oh, sorry, it's fine then.  I misremembered what this PR was, since I thought I remembered @bsipocz or possibly someone else taking a stab at implementing joins of differently named columns.

**Comment by bsipocz** [comment]
@embray - You're right, there was some talk in #3752 about implementing it, but then it was decided against given that the current API is complex enough already and the workaround is quite simple anyway.

**Pull request merged**
