### PR TITLE
Fix PR template

### PR DESCRIPTION
**Pull request by pllim**
Follow-up of #9297 to fix the problem of the PR template not showing up when a new PR is created. Many thanks to @bsipocz for advice.

### CODE REVIEW

**Comment by bsipocz** [comment]
Well, it's a guess not an advice. Let's see whether it works...

**Comment by pllim** [comment]
Hey, hey, I think it works now. Solid advice after all! 😄

**Comment by bsipocz** [comment]
There is a good phrase for this, but typically I can't remember it now. Something about fools and their luck 😏

**Comment by pllim** [comment]
You are too humble!

**Pull request merged**
