### PR TITLE
Table init from objects with __astropy_table__ method

### PR DESCRIPTION
**Pull request by taldcroft**
This defines an interface method to allow an arbitrary object to initialize a `Table` subclass if it has an `__astropy_table__` method.

To do:

- [ ] Documentation in Table narrative docs
- [ ] Changelog

Supercedes and closes #4740.

cc: @astrofrog @TallJimbo @eteq

### CODE REVIEW

**Comment by astrofrog** [comment]
:+1: so far

**Comment by taldcroft** [comment]
@astrofrog can you restart appveyor?

**Comment by astrofrog** [comment]
@taldcroft - done

**Comment by MSeifert04** [comment]
Could you please elaborate why you choose this approach? I'm very interested in how you intend to make it work along subclasses, especially with regard to some possible similar functionality in `nddata`. 

For example why don't you return "the most appropriate `Table` object (subclass)" (appropriate is meant here as "most likely/compatible")?

For example I had some fun time testing how ``__array__`` works and it seems like it should return the most specialized possible subclass and let the constructor determine how this needs to be up/downcast:

```
import numpy as np
from astropy.units import Quantity

class Fun(object):
    def __array__(self):
        # properties named in a way that prohibits duck-typing these names.
        if getattr(self, 'theunit', None) is not None:
            # return a masked array this will be downcast if the constructor 
            # calling it only supports plain ones.
            return Quantity(self.thevalue, unit=getattr(self, 'theunit'))
        elif getattr(self, 'themask', None) is not None:
            # return a masked array this will be downcast if the constructor 
            # calling it only supports plain ones.
            return np.ma.array(self.thevalue, mask=getattr(self, 'themask'))
        
        return np.asarray(self.thevalue)

a = Fun()
a.thevalue = 10
a.themask = True

np.array(a)
# array(10)

np.ma.array(a)
# masked_MaskedArray(data = --,
#                    mask = True,
#              fill_value = 999999)

np.asanyarray(a)
# masked_array(data = --,
#              mask = True,
#        fill_value = 999999)

a.theunit = 'm'
np.array(a)
# array(10)

np.ma.array(a)
# masked_Quantity(data = 10.0 m,
#                mask = False,
#          fill_value = 1e+20)

np.asanyarray(a)
'<Quantity 10.0 m>'
```

That may not be appropriate or possible here but I wasn't part of earlier discussions and would appreciate a bit more explanation.

**Comment by TallJimbo** [comment]
If I have a class that implements the current interface, and an instance of that class is passed to the `QTable` constructor, does that construct a working `QTable`?

If so, that's an important distinction between the current interface and the more direct one @MSeifert04 suggested; it lets users decide whether they want a `Table` or a `QTable`.  Given what I know about the distinction between them (which I think is quite different from the distinction between `nddata` subclasses), I think that's desirable?

**Comment by taldcroft** [comment]
@MSeifert04 - the point @TallJimbo is on the mark.  

Assume that `ft` is an "foreign table" object that implements the `__astropy_table__` method.  Then if a user does `QTable(ft)` they are guaranteed to get a `QTable`, and likewise `Table(ft)` will return a `Table` object.  This distinction is important because of the fundamental behavioral difference between `QTable` and `Table`.  Thus the subclass of `Table` is fully specified by what the user code says and by design to a lesser degree by what is in `ft.__astropy_table__`.

The decision to have `__astropy_table__` return a list of columns and not a `Table` subclass of its choosing is one of simplicity and reduction.  A list of column objects and table meta is fundamentally all there is to a table in terms of *data*.  The rest is all *behavior*.  Repackaging that as a `Table` subclass chosen by `__astropy_table__` only to have that undone / overrridden by the user-specified subclass doesn't really make much sense.

Finally, you talk about "the most appropriate Table object (subclass)", but "most appropriate" can easily have a different definition depending on the user or application.  Instead the intent is something more deterministic, which is that the foreign table should simply return a list of `Column`, `MaskedColumn`, or `Quantity` objects.  This makes it straightforward to implement and to guess what will come out.  Note that even if `__astropy_table__` returns a list of all `Quantity` objects, if a user requests a `Table` from that object then they will all get transformed to ordinary `Column`s.

**Comment by taldcroft** [comment]
As I was writing the above I realized there is an issue that is actually obvious from the new tests in this PR.  Here is a demo of the problem:
```
In [2]: c = [1, 2] * u.m
In [3]: c.info.name = 'a'

In [5]: QTable([c]).colnames
Out[5]: ['a']

In [6]: Table([c]).colnames
Out[6]: ['col0']

In [9]: print(Column(c).name)
None

In [10]: print(Column(c).unit)
m
```
So QTable knows about existing names in Quantity objects, but Table does not.  I think this needs to be fixed in order to allow for `__astropy_table__` to return Quantity objects.  Right now we could just declare that `__astropy_table__` has to return only `Column` subclasses (which includes `MaskedColumn`).  Any `Column` with units gets automatically transformed to `Quantity` within a `QTable`.  But hopefully it isn't too hard to fix the issue with Table or Column dropping the Quantity name attribute.  (Though maybe there was a reason it was this way, I forget...)

**Comment by MSeifert04** [comment]
@taldcroft Thank you for the explanation.

**Comment by mhvk** [comment]
I initially shared @MSeifert04's confusion, but guess it got a bit clearer given the examples. But the name still seems somewhat wrong: it does suggest one gets out a table rather than input suitable for constructing a table (and indeed it is clear everybody, including @taldcroft, thought the same in the thread linked to by @astrofrog: https://groups.google.com/d/topic/astropy-dev/19IIxn-_zaQ/discussion). I think it would be better to have something else.

More relevant than the name is the API, which seems somewhat arbitrary: might it be an idea to assume the method returns arguments that would initialize a table? Right now, from the test case, the method seems to require possibly useless construction of column objects: `Table` already knows how to do that! So, could one perhaps require that it produces a tuple or perhaps better a `dict` that can initialize a table, i.e., `QTable(myobject)` would be equivalent to `QTable(**myobject.__astropy_table_init__())`.  I think this has the advantage that we are not defining yet another API: it is just the one for table initialisation. (In principle, one could still allow the user to pass on keyword arguments to the table initialisation, which could override whatever is produced by the method. E.g., any passed in `meta` should probably have priority over that returned by the method.)

As yet another alternative, one could think of an `__astropy_table_state__` that returns the information that is used in `Table.__setstate__`. But I like this less, as I think I'd much rather be beholden to the API defined by the public initialiser than by something we do to ensure pickling works.

**Comment by taldcroft** [comment]
@mhvk - At first I actually wrote "Great idea!".  But then I started thinking about what happens by making the API totally open ended -- "just return any dict that will initialize a `Table` subclass".  I think there is more room for potential problems down the line.  One immediate issue is that there exists the possibility for conflicts between:

- What the user supplies for a kwarg in the original call to `Table`
- What `__astropy_table__` provides as a dict kwarg

Think of the `name` attribute as an example.  Right now there are clear rules for handling this (kwargs to `Table()` win in general).  There are also lots of tests of those potential conflicts.  But with the possibility that `__astropy_table__` can return its own values for any `Table` kwarg, I think there might be more ambiguity.  For every kwarg I think you'll need code that checks whether the user supplied a value or `__astropy_table__` supplied a value and then choose accordingly.  Also because we are not leveraging existing interface functionality (suppling a list of columns), it will require much more extensive testing.

This is all possible, but then we are not looking at an extremely simple **3 line implementation** and then potentially a slip into astropy 1.3 :frowning:.  So I would say that by imposing this restricted but simple API that overall everything is going to be simpler and more reliable.

**Comment by MSeifert04** [comment]
> Right now there are clear rules for handling this (kwargs to Table() win in general).

But wouldn't that rather strengthen the proposal to return an actual `Table` or `QTable` object when `__astropy_table__` is called? So the same rules apply?

**Comment by taldcroft** [comment]
> But wouldn't that rather strengthen the argument to return an actual Table or QTable object when __astropy_table__ is called? So the same rules apply?

But then you are forcing `__astropy_table__` to deal with the whole `Table` API.  You would also need to pass the class of the parent table being created into `_astropy_table__`, and make an intermediate table only to throw it away when creating the actual table that gets returned to the user.   Note that if you don't pass in the class, then `__astropy_table__` would need to assume `Table`, so that if there were any `Quantity`s those would get temporarily converted to `Column` and then possibly back to `Quantity` if the user is creating a `QTable`.

It is already slow enough creating Tables, so I don't want to build in all this useless conversion to and fro just to make the API seem slightly simpler on the outside.  As @mhvk pointed out, a list of columns and a meta object are exactly what is pickled, and that is the therefore the minimal representation of table data.  It therefore makes *more* sense to me now that `__astropy_table__` would return exactly that (plus the `copy` arg which is a subtlety that we realized when thinking about this in the LSST context).

**Comment by mhvk** [comment]
@taldcroft - I think I agree with @MSeifert04 here: if you are going to force the package down the line to construct `Column` objects, they might as well construct a `QTable` directly; after all, then changing to a `Table` should presumably work! This case is also very easy to implement; just replace the current
```
if isinstance(data, Table):
   ...
```
with
```
if hasattr(data, '__astropy_table__'):
    data = data.__astropy_table__()
    init_func = self.__init_from_table
    ...
# and add somewhere further down the line
def __astropy_table__(self):
    return self
```
(Defining this allows chaining via `super` which often becomes remarkably useful. May also want to keep options for expansion open by allowing `**kwargs` in the definition, which any implementation can look at but also can ignore if they wish.)

Overall, I think I actually prefer the above over my other suggestion, as I think it is clearer what is expected, and as I agree that by passing table input things could get messy. Though for that case one could also insist that if an object with `__astropy_table_init__` is passed in, no other arguments can be given. Or treat it as if it passed through a table, i.e., one would do
```
cls(cls(**object.__astropy_table_init__()), *args, **kwargs)
```

**Comment by mhvk** [comment]
p.s. Thinking more just after commenting: I think it is not unimportant that a package that wants to implement `__astropy_table__` gets to pick a subclass that best suits them.  In this respect, it would then echo the behaviour of `__array__`, and perhaps we should have an `asanytable` class method or a `subok=True` keyword argument. But none of this is that important for the case at hand.

**Comment by TallJimbo** [comment]
Thinking about the first non-test implementation of this interface, I have to admit I *liked* not having to choose between `Table` and `QTable`.  If we go with a method that has to pick one, is there a general recommendation for Astropy users which one they should use that I could just adopt?

I think comparing this debate to `__array__` vs. `__array_interface__` (or the buffer protocol) is probably fair, and I think that suggests there may be use cases for both designs.  And I think my ambivalence about `Table` vs `QTable` suggests that it's the latter that is more appropriate for views to LSST tables.  Maybe we could add `__astropy_table_columns__` with @taldcroft's original API now, and reserve `__astropy_table__` for the future?

**Comment by mhvk** [comment]
@taldcroft - for simplicity, I think your current test case suggests that creating columns is not any easier than making a table; you have to import `astropy.table` anyway. The alternative of passing appropriate arguments avoids the import, but is perhaps a bit silly: if you can construct those, you can also do the call to `Table` on it. 

You are right about the overhead of creating a table and then recreating this, but I think this is a solvable probleme (e.g., using the `subok=True` option or the class method). Also, the nice thing about making a table directly is that it can easily include grouping information, etc.

**Comment by mhvk** [comment]
@TallJimbo - I think for tables without masked columns, `QTable` is generally preferred as columns with units behave exactly like quantities, i.e., units are respected (not true in all cases for columns; e.g., np.sin(column)` assumes column is in radians).

So, the only issue is when one has quantities with units and masks.  Unfortunately, `MaskedArray` has many flaws... (note that masked time, etc., are not possible in either table format).

**Comment by mhvk** [comment]
p.s.  I think we can still get this right now, so we do not have to support two ways to communicate!

**Comment by TallJimbo** [comment]
> I think for tables without masked columns, QTable is generally preferred...

That actually makes me feel a lot better about going with an interface that just creates a table (if the constructor complexity concerns @taldcroft raised are indeed addressed; I'm not qualified to comment usefully on that).  I'm fairly ambivalent about `Quantities`, but I know many of our potential users will want to use them, and I want nothing to do with `MaskedArray`.

**Comment by taldcroft** [comment]
@mhvk - can you give some specific example(s) of useful functionality that could be achieved by returning a `Table` that cannot be done with the current implementation?

And can you suggest exactly how we would avoid the unnecessary double-table instantiation penalty?

Note that it doesn't really matter what each implementation of `__astropy_table__` chooses in terms of `Table` or `QTable`.  The subclass that the user instantiates with is going to be outputted anyway, with all the necessary (inefficient) conversions that are required to make that happen.  (Unless the class is provided as an arg to `__astropy_table__`).

**Comment by mhvk** [comment]
@taldcroft - I don't know that this is fair, but is there an advantage to your approach beyond the extra overhead? (which shouldn't matter that much since the operation that should be rare.)

Anyway, I think the main advantage really is the simplicity of something doing what its name suggests, and not adding another API.  I think the discussion on astropy-dev was instructive in that regard. It certainly makes me feel we should pick something that would trivially extend to `nddata`, etc. (Though of course the latter argument does not exclude returning a dict/tuple with all arguments that can initialize an instance; this idea still looks very similar to yours, just a bit more general).

Anyway, I can see some cases where just returning a table is better:
1. The other class has a compatible way of grouping data. With your approach, this cannot be passed on (actually, looking at the code: are groups actually kept if a table is entered as `data`?).
2. The other class uses another astronomy package that has a nice `Table` subclass with extra functionality.

Now both items suggest that if `__astropy_table__` is present, there should be a way (perhaps even done by default) of just returning the instance it creates rather than creating a new instance (just like for `__array__`). My preference would be a `Table.__new__`, which can return a table subclass (either using a new keyword or just for `copy=False`).

**Comment by mhvk** [comment]
@TallJimbo, @taldcroft - as I was not part of the initial discussions, I'm actually a bit unsure about the final goal here. For `__array__`, it is quite obvious: one would like the user to be able to use numpy functions on their data array. But is it really so much better for the user to be able to do `Table(lsst_object)` instead of `lsst_object.to_astropy_table()`? Or `Table(**lsst_object.astropy_table_data())`.

In principle, I can see the advantage of a table interface (i.e., something akin to `__array_interface__`), but I don't see much point unless there has been some real effort to also involve, e.g., `pandas` and other table packages in the discussion.

Just to be sure: I do *really* want LSST and astropy to interoperate well! But that goes to the extent that I think if there is functionality missing in `Table` that LSST needs, perhaps we should just add it.

**Comment by TallJimbo** [comment]
I actually have no problem with an interface like `lsst_object.to_astropy_table()`, and that was actually my first proposal when we started discussing this.  And if this discussion doesn't converge soon, I'll probably just add something of that nature to the LSST objects, at least temporarily.  The only thing I don't like about that is how the user would specify the table subclass they want; `lsst_object.to_astropy_table(cls=QTable)` would certainly work, but it feels a bit clunky.

I've actually always found it strange that "overloaded" constructors like the one in `Table` (but also the one in `dict` and any number of Python built-ins) that have multiple ways of interpreting their arguments are so common in Python, given that the language makes implementing overloading so hard.  But it is a pattern users frequently expect to work.

**Comment by mhvk** [comment]
@TallJimbo - I would not worry to much about the specific class that people want; `Table` and `QTable` work mostly identically. If you have quantities with units and no masked data, I think `QTable` is the obvious "correct" one.

And, yes, agreed on the overloading. I find it perplexing that people seem to think, e.g., that every numpy function should be able to handle lists, etc., which has the consequence that any input gets turned into an array in every function, adding needless overhead and at the same time preventing the use of a well-constructed subclass like `Quantity`.

**Comment by mhvk** [comment]
@TallJimbo - all this said, is there anything specific missing in `Table` that prevents it from being used directly?

**Comment by MSeifert04** [comment]
I've played around with `NDData` and something along the lines of `__astropy_nddata__` and have some things I realized:

- Doing anything complex inside `__astropy_nddata__` will really slow down the code if subclasses are involved and each subclass at some point wants to check something from `__astropy_nddata__`. So it will be accessed once per subclass. So more than returning a `dict` (with arguments that could be used to create an instance) or a `namedtuple` (that quacks like a NDData) will be a performance killer, especially if one sets something up that copies (even if it's just `list` -> `np.ndarray`).

- Actually the `namedtuple`-thing worked really well with `NDData`. You can check the arguments that you need and ignore the other and since it's a namedtuple one can in theory access it like a `NDData` object. Haven't checked if that's possible with `Table`. The downside here is that it looks like a `Table` without being one. That could be confusing for user.

I like the idea of `.to_astropy_table()`. At least if the class doesn't already have 10+ `to_***` methods.

**Comment by TallJimbo** [comment]
> @TallJimbo - all this said, is there anything specific missing in Table that prevents it from being used directly?

Nope, nothing missing.  I could add `to_astropy_table()` to my LSST tables today with no difficulty (given our current naming conventions, it'd probably be `asAstropy()`, since we're still doing things CamelCase and the table-ness is implicit).  Eventually I would like to get support for our bit-packed boolean columns into Astropy, but that's a separate issue, #4741 (and one on my plate), and in the meantime I can just copy them to bools (and @taldcroft and I have already discussed the right semantics for copying / not copying at length).

**Comment by taldcroft** [comment]
About `to_astropy_table()`...  would the plan be to have `to_astropy_qtable()`?  Obviously not, so you are already getting to an API `to_astropy_table(table_class)`, so the call would be `lsst_table.to_astropy_table(Table)` or `lsst_table.to_astropy_table(QTable)`.  That seems really inelegant compared to `QTable(lsst_table)`.

BTW, my plan was to open a PR on pandas to add an `__astropy_table__` method.  They might not object to having a small hidden method like that to improve interoperability, but I can definitely see them objecting to a new special-purpose *public* method on their DataFrame.

**Comment by taldcroft** [comment]
@TallJimbo - can you remind me of the case we discussed that required passing back the `copy` flag?  I recall it was related to LSST columns that cannot be passed by ref (e.g the bit-packed bools like you mentioned) and must be copied.  

It seems that if `__astropy_table__` is responsible for ensuring that columns are copied if `copy is True` then the rest of the table initialization could always use `copy=False`.  I think that some original code was going to raise an exception if the user passed `copy=False` but that wasn't possible, which still sounds fine.

(All of this holds true whether the columns are sent back as a plain list or bundled in an astropy Table).

**Comment by taldcroft** [comment]
@mhvk - Maybe we're talking across each other, but remember that `Table` does not have the equivalent of a `subok` option, so if you ask for `Table(other_table)`, it does not matter if `other_table` is a Table subclass with nice stuff on it, you are going to get a plain `Table`.  This is by design to make it easy to convert from a QTable to the equivalent Table with `Table(qtable)`.

Your proposal will still have an API, just a slightly different one from the current implementation.  I agree that in the end it might allow some additional flexibility, so in the interest of getting convergence I will give that a try with code and see what people think.

**Comment by mhvk** [comment]
@taldcroft - great! I'm obviously not sure I'm right either, but a previous similar discussion got us `info`, which I think is much better than anything either of us had dreamed up beforehand!

**Comment by taldcroft** [comment]
>  If you have quantities with units and no masked data, I think QTable is the obvious "correct" one.

Unrelated to this PR, but just to let you know that this opinion is not universal.  :smile:

**Comment by TallJimbo** [comment]
> Can you remind me of the case we discussed that required passing back the copy flag?

Your recollection matches mine.  We have some fields for which we can't create a Column without copying (mostly the bit-packed booleans, but we also have some more complex objects that we might want to make available as a `dtype=object` `Column`).  So we had to leave it to the `__astropy_table__` method to do that copying; once we did that, we decided it was easier to just make it do all the copying that was requested, since we'd otherwise need to define some way to communicate what had already been copied (or live with copying some things twice).

That reminds me of a potential advantage of having a public method on the LSST table to return an Astropy object: it lets me add a `copy` argument to that method for which`"as-needed"` could be accepted in addition to `True` and `False`, which would only copy columns for which views are unavailable.  I actually think that's what most users would use.

**Comment by astrofrog** [comment]
This was superseded by https://github.com/astropy/astropy/pull/4885, which is now merged

**Pull request closed without merging**
