### PR TITLE
BUG: fix an incompatibility with numpy 2.0 (np.round_ was removed)

### PR DESCRIPTION
**Pull request by neutrinoceros**
see https://github.com/numpy/numpy/pull/24477

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
tests hit an unrelated error:
```python-traceback
AttributeError: module 'IPython.lib.pretty' has no attribute '_deferred_pprinters'. Did you mean: '_deferred_type_pprinters'?
```
which I assume is due to usage of private IPython API, which was supposedly changed in IPython 8.15.0 (released on Sept 1st).
I'll open this for review even with failures when I'm confident that what I'm fixing is dealt with.

**Comment by neutrinoceros** [comment]
in fact the other error is from `hypothesis`, not astropy. See report upstream https://github.com/HypothesisWorks/hypothesis/issues/3731

**Comment by dhomeier** [comment]
Thanks for the PR and investigating the hypothesis failure!
There is already a fix addressing the `np._round` removal in #15266 (I recommend to search existing issues first to avoid duplicating work), but if we choose to use this one, I'd run the extra CI here first.

Fix for hypothesis has already been merged, so I'd perhaps just wait if they make a bugfix release soonish.

**Comment by neutrinoceros** [comment]
Sorry I didn't think of checking first, I'll close this as a dup then !

**Comment by pllim** [comment]
Thanks anyway! 

I don't see the hypothesis error anymore.

**Comment by neutrinoceros** [comment]
Yes, it's been resolved upstream !

**Pull request closed without merging**
