### PR TITLE
TST: Add back --open-files to one job

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to investigate if we can still use `--open-files`.

This is a follow up of #10388

### CODE REVIEW

**Comment by pllim** [comment]
Seems to work but I just don't know if adding `--open-files` to the job that also measures duration will mess up the latter. What do you think, @astropy/devops-maintainers @astrofrog @saimn et al?

**Comment by astrofrog** [comment]
Yeah it definitely doesn't make sense to have the one that mesures durations be the same one.

**Comment by pllim** [comment]
@astrofrog , any idea where is the next best place to put it without creating a new job just for it? We don't want it to miss too many tests and we know it doesn't work for `oldest-deps` and probably unwise to put it under Windows (not sure about OSX).

**Comment by astrofrog** [comment]
What about adding open files to the 'Python 3.8 with all optional dependencies' on Linux and measuring durations on the MacOS X and Windows equivalent ones?

**Comment by pllim** [comment]
Like this, @astrofrog ?

**Review by astrofrog — APPROVED** [review]
Yes that's fine by me :)

**Comment by pllim** [comment]
Gah... It uses `openfiles-0.5.0` and took 1.5 hours. I thought I pinned it but apparently not. Too many actions.

**Pull request merged**
