### PR TITLE
Updating bundled version of six to v1.10.0

### PR DESCRIPTION
**Pull request by bsipocz**
I'm going through the external packages to see which ones can be updated in the new release. This update of ``six`` contains a few enhancements and fixes since 1.7.3, so probably worth to update.

### CODE REVIEW

**Comment by pllim** [comment]
:+1:  Do you think this can get in for 1.3? Will need a change log, right?

**Comment by bsipocz** [comment]
I've added the changelog. Unless it breaks the tests, my intent was to get this into 1.3.0

**Comment by MSeifert04** [comment]
Do we need to update the real `six` minversion then: https://github.com/astropy/astropy/blob/master/astropy/extern/six.py#L11?

**Comment by bsipocz** [comment]
@MSeifert04 - I though we don't need to update that, but based on the discussion in the previous update it seems that we better update that, too. Thanks for catching it.

**Comment by astrofrog** [comment]
Thanks @bsipocz!

**Comment by saimn** [comment]
In the same vein as #5509 , is there still a need to bundle six ? I guess at some point it was useful to have a recent enough version, but now six is pretty stable. And while this PR set the minimum version to 1.10.0, the code is currently compatible with 1.7.3+ at least.

**Pull request merged**
