### PR TITLE
TST: Fix doctest of to/from_pandas 

### LINKED ISSUE #8331: TST: from_pandas and to_pandas doctests fail in OSX job (cron)
Example log: https://travis-ci.org/astropy/astropy/jobs/475948905

```
_______________ [doctest] astropy.table.table.Table.from_pandas ________________
2857 
2858           >>> import pandas as pd
2859           >>> from astropy.table import QTable
2860 
2861           >>> time = pd.Series(['1998-01-01', '2002-01-01'], dtype='datetime64[ns]')
2862           >>> dt = pd.Series(np.array([1, 300], dtype='timedelta64[s]'))
2863           >>> df = pd.DataFrame({'time': time})
2864           >>> df['dt'] = dt
2865           >>> df['x'] = [3., 4.]
2866           >>> df
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,5 @@
    -        time       dt    x
    -0 1998-01-01 00:00:01  3.0
    -1 2002-01-01 00:05:00  4.0
    +        time ...     x
    +0 1998-01-01 ...   3.0
    +1 2002-01-01 ...   4.0
    +<BLANKLINE>
    +[2 rows x 3 columns]
.../astropy/table/table.py:2866: DocTestFailure
________________ [doctest] astropy.table.table.Table.to_pandas _________________
2734           >>> from astropy.coordinates import SkyCoord
2735 
2736           >>> q = [1, 2] * u.m
2737           >>> tm = Time([1998, 2002], format='jyear')
2738           >>> sc = SkyCoord([5, 6], [7, 8], unit='deg')
2739           >>> dt = TimeDelta([3, 200] * u.s)
2740 
2741           >>> t = QTable([q, tm, sc, dt], names=['q', 'tm', 'sc', 'dt'])
2742 
2743           >>> t.to_pandas(index='tm')
Differences (unified diff with -expected +actual):
    @@ -1,4 +1,6 @@
    -              q  sc.ra  sc.dec       dt
    -tm
    -1998-01-01  1.0    5.0     7.0 00:00:03
    -2002-01-01  2.0    6.0     8.0 00:03:20
    +              q   ...          dt
    +tm                ...
    +1998-01-01  1.0   ...    00:00:03
    +2002-01-01  2.0   ...    00:03:20
    +<BLANKLINE>
    +[2 rows x 4 columns]
.../astropy/table/table.py:2743: DocTestFailure
```

cc @taldcroft

### PR DESCRIPTION
**Pull request by pllim**
Follow up of #8332 , which does not appear to fix the failing cron job (https://travis-ci.org/astropy/astropy/jobs/479833790). This time, I am going to temporarily run that cron job as part of the PR, with the intention of reverting that commit before merge, if things pass.

Fix  #8331

### CODE REVIEW

**Comment by pllim** [comment]
Setting `'display.width'` does not do anything on the OSX job. I have asked upstream at pandas-dev/pandas#24787

**Comment by pllim** [comment]
This might work... I'll look in detail tomorrow.

**Comment by pllim** [comment]
This was proven to work on OSX job -- https://travis-ci.org/astropy/astropy/jobs/480074759

So that affected cron job would pass again once this is merged.

**Comment by bsipocz** [comment]
Thanks @pllim!

**Pull request merged**
