### PR TITLE
Fix 4082

### LINKED ISSUE #4082: astropy.coordinates.search_around_sky breaks on storekdtree=False
astropy.coordinates.search_around_sky doesn't seem to respect a boolean for storekdtree.  This looks inconsistent with the docs.  This following code example works fine if I don't include the storekdtree option and accept the default.

```
cat = SkyCoord([10.076,10.00455], [18.54746, 18.54896], unit='deg')
search_around_sky(cat[0:1], cat, seplimit=astropy.units.arcsec * 60, storekdtree=False)

in search_around_sky(coords1, coords2, seplimit, storekdtree)
    333     kdt1 = _get_cartesian_kdtree(ucoords1, storekdtree)
    334 
--> 335     if hasattr(coords2, storekdtree):
    336         #just use the stored KD-Tree
    337         kdt2 = getattr(coords2, storekdtree)

TypeError: hasattr(): attribute name must be string

```

### PR DESCRIPTION
**Pull request by eteq**
This implements a regression test for and closes #4082.

In #4082 @embray suggested the change ``storedkdtree`` -> ``stored_kd_tree``. I like that change, *except* that it's breaking backwards compatibility.  So definitely we should merge this as a bugfix (which then can also go into 1.0.5), but should there also be a PR to do the name change?  Or is it worth it at all given that it's a change to the API?

### CODE REVIEW

**Comment by embray** [comment]
I wasn't going to accept any more changes for 1.0.5 so that I could release it today.  But if this build passes then I'll merge :)

**Comment by embray** [comment]
If you like the change of name (as do I, obviously) we could do that as a separate PR.

**Comment by eteq** [comment]
@embray - yeah, I agree a separate PR for the name change makes sense.

Last one had a foolish mistake (missing import of pytest) because I was in a hurry, but this *should* do the trick now...

**Comment by embray** [comment]
Ok, thanks!

**Pull request merged**
