### PR TITLE
Fix latex repr for function units

### PR DESCRIPTION
**Pull request by larrybradley**
This PR fixes a bug in the latex represention in the juypter notebook of function units (e.g. mag, dex) where the left and right parentheses are not rendered in math mode.  For example, `u.mag(u.ct)` renders as `"mag\left(ctight)"`.

### CODE REVIEW

**Comment by larrybradley** [comment]
CC: @mhvk

**Comment by mhvk** [comment]
Yes, there was a missing `\\` in the original, and ordering was rather illogical -- this looks good!  I do think it would be useful to add a test case. Also, this is a bug fix, so might as well have an appropriate entry in the change-log.

**Comment by larrybradley** [comment]
I added a changelog entry under `1.1.2`.  Let me know if I should also add it in `1.0.9`.

**Comment by mhvk** [comment]
@larrybradley - sorry for the delay in getting back (things have been hectic) -- as you mentioned, 1.0, I realised that, yes, indeed, this should be for 1.0.9, so do repeat the change-log entry.

Also, I do like test cases for regressions: could you add just the example you have above in `units/tests/test_logarithmic.py` in the `TestLogUnitStrings` class? (Or just adjust one of the test cases to use `to_string(format='latex')`). Thanks!

**Comment by larrybradley** [comment]
@mhvk I've added a regression test and updated the changelog.  Thanks!

**Comment by mhvk** [comment]
Great!  Merging...

**Comment by eteq** [comment]
I changed this back to v1.1.2, because while trying to backport this to v1.0.9, I realized that the functional units don't seem to exist in v1.0.x.  Let me know if I'm mis-understanding, though, @mhvk.

**Comment by mhvk** [comment]
@eteq - argghh, yes, functional units missed 1.0. Thanks!

**Comment by eteq** [comment]
backported to v1.1.x in f26d08bb8112d2ec844f032e2f677b32bde2b121

**Pull request merged**
