### PR TITLE
MNT: Removed vectorize_if_needed and inf_like from cosmology.utils

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address the `cosmology` portion of #14664

### CODE REVIEW

**Review by nstarman — APPROVED** [review]
🎉

**Comment by nstarman** [comment]
Failure is unrelated.

**Comment by nstarman** [comment]
@pllim. Towncrier check is preventing merge.

**Comment by pllim** [comment]
@nstarman , sorry for the confusion, but it is meant for v6.0, so not to be merged before branching.

@saimn , did this accidentally make it to v5.3.x too?

**Comment by pllim** [comment]
Ah, sorry, I just noticed that it was @saimn who did the merge, so probably okay. 😌

**Comment by saimn** [comment]
Yeah it's ok, v6.0 PRs can be merged now :)

**Pull request merged**
