### PR TITLE
Update cfitsio to 4.1.0

### LINKED ISSUE #12961: Upstream release of dependency: cfitsio
This is a message from an automated system that monitors `cfitsio` releases.

Version 4.1.0 - Feb 2022
                   
  - Calls to the zlib inflate() function in zcompress.c now handle
    the Z_BUF_ERROR return value rather than exiting.

  - The SUBTRACTIVE_DITHER_2 option has been removed when using the
    HCOMPRESS algorithm.  
    
  - Updated fits_get_version function to return a float calculated
    from 3 version fields.
                       
  - Added handling of SBYTE_IMG and ULONGLONG_IMG types to the
    fits_resize_img function.
    
  - Updates made to C/Fortran interfacing in cfortran.h and f77_wrap.h
    specifically driven by new Mac/ARM architecture.
    
  - Fix to the fits_insert_col functions to handle columns with
    TULONGLONG data.

(For complete changelog information, consult the package changelog file in cfitsio/doc/changes.txt)

Reposted from spacetelescope/hstcal#564

### PR DESCRIPTION
**Pull request by saimn**
Closes #12961.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Do we backport cfitsio to LTS? 👀

**Review by pllim — APPROVED** [review]
Thanks!

**Comment by saimn** [comment]
@pllim - Yes, probably useful since we may have to backport other releases in the future.

**Comment by pllim** [comment]
Hmm... what happened here?

`<unknown>:48: WARNING: py:obj reference target not found: astropy.io.fits.connect.read_table_fits`

**Comment by saimn** [comment]
Hmm weird, I don't see how this could be triggered by this PR ...

**Comment by pllim** [comment]
You wanna try rebase and see if it magically goes away?

**Comment by saimn** [comment]
It's already on the latest main so closing/reopening to trigger a new build.

**Comment by saimn** [comment]
Hmm so it seems the issue comes from the changelog entry of #11843, which contains a reference to `read_table_fits`, but this PR was merged some time ago and no other PR has been failing because of that ...

**Comment by pllim** [comment]
That is so weird. Glad you fixed it. Thanks!

**Comment by saimn** [comment]
Yes, I will do a separate PR :+1:

**Comment by pllim** [comment]
I merged #12976 , please rebase. 😸

**Comment by pllim** [comment]
Thanks, @saimn !

**Pull request merged**
