### PR TITLE
WIP: Make WCSAxes recognize more rcParams

### PR DESCRIPTION
**Pull request by astrofrog**
I need to go through and systematically check which rcParams are relevant for WCSAxes and currently are being ignored, so this is a work in progress.

### CODE REVIEW

**Comment by pllim** [comment]
Since this is still WIP, I am moving it to 3.1.

**Comment by bsipocz** [comment]
@pllim - the next bugfix is 2.0.5 or 3.0.1 ;)

**Comment by astrofrog** [comment]
Note to self: I also need to make ``tick_params`` work

**Comment by astrofrog** [comment]
There was a bug in the bot, it should not have been closed without the warning so re-opening.

**Pull request closed without merging**
