### PR TITLE
TST: Move Windows build from Appveyor to Travis

### LINKED ISSUE #9061: TST: Appveyor build failing on master
The Appveyor build failed on my PR (https://github.com/astropy/astropy/pull/9057) after rebasing.  

The Appveyor build showed successful after the last commit on master 3 days ago.  When I triggered a new build Appveyor build on master, and it failed in the same way as on my PR. The failure comes quite early in the environment setup process.

The build log is here:  https://ci.appveyor.com/project/Astropy/astropy/builds/26318884

### PR DESCRIPTION
**Pull request by pllim**
Close #9061 

I am guessing we have to backport this all the way to 2.x unless you feel like debugging the Powershell script over at `ci-helpers`, but feel free to re-milestone if I was mistaken.

### CODE REVIEW

**Comment by bsipocz** [comment]
Music to my eyes, or something along those lines 😆, the best hack happened so far on pyastro :)

**Comment by bsipocz** [comment]
The only downside of this PR is that the windows build takes 22 minutes to finish. Workarounds:
- try to pip install instead of conda
- move that build (along with numpy dev as that one is allowed to fail anyway) to a third stage, so we only run it if everything else is absolutely fabulous.

**Comment by bsipocz** [comment]
Thanks @pllim!

I'll cancel the rest of the runs, no need to rerun it as it already passed yesterday and the restaged config got recognized without issues.

**Comment by pllim** [comment]
@bsipocz , I moved Windows dependencies from `conda` to `pip` too. I'll keep an eye on the `master` build. Thanks for the review and merge!

**Pull request merged**
