### PR TITLE
Ruff fix isort

### PR DESCRIPTION
**Pull request by nstarman**
Apparently we made a mistake in the isort -> ruff transition and stopped enforcing isort properly!

BTW, I approve the cosmology corrections 😆

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Looks uncontroversial enough. Thanks!

**Comment by pllim** [comment]
Do we at least want to backport to v5.3.x to lower risk of backport conflicts?

Once the milestone is sorted out (pun?), we can merge.

**Comment by nstarman** [comment]
> Do we at least want to backport to v5.3.x to lower risk of backport conflicts?

Agreed!

**Comment by pllim** [comment]
@meeseeksdev backport to v5.3.x

**Comment by pllim** [comment]
Argh, I guess not. @nstarman , are you interested in a manual backport? If not, we can move the milestone back. Thanks!

**Comment by nstarman** [comment]
I'll give it a look.

**Comment by pllim** [comment]
👀  Well, if you find out that fixing `.ruff.toml` isn't easy in v5.3.x branch, then we don't have to. Though... we just cut v5.3.x not that long ago. Has it diverged from `main` that much already?!

**Comment by nstarman** [comment]
We split `.ruff.toml` out from `pyproject.toml`, so it's really only diverged at that point.

**Comment by pllim** [comment]
@nstarman , I am just going to change the milestone, since v5.3 is already released. Thanks!

**Pull request merged**
