### PR TITLE
ENH: Very fast welcome message for first contributors

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to deploy the `first-interaction` Action that does not use Docker, thus speeding it up from 20-25 s to 1 s.

If actions/first-interaction#39 ever gets merged, we can go back to using the canon version; but looking at the lack of repo activities over there, I am not optimistic.

@Cadair also expressed desire to have the Action to post a PR comment instead of PR review (see the current behavior at #11295). If there is consensus to do this, I can also make this change to my feature branch; it is a one-liner.

- [ ] Do you want this puppy? 🐶 
- [ ] If yes, please help me test it out over at https://github.com/kali-maa/astropy -- The catch is you cannot have posted issue/PR there before.

This is a direct follow-up of #11253 .

### CODE REVIEW

**Comment by pllim** [comment]
Silence means no, I guess. No biggie.

**Comment by embray** [comment]
Not "no", just didn't seem urgent.  Actually I think it's a really nice idea.  I find it weird that the attention to the official "actions" repositories is so sparse.  I can't reopen the PR though since the branch was deleted...

**Comment by pllim** [comment]
I re-opened it... GitHub makes it easy now from my end. 😬

**Comment by pllim** [comment]
If you need more time, feel free to move the milestone.

**Review by nstarman — APPROVED** [review]

**Comment by nstarman** [comment]
Tested it at https://github.com/kali-maa/astropy/issues/69. Definitely faster.

**Comment by nstarman** [comment]
@Cadair @pllim. What are the relative merits of a request over review?

**Comment by pllim** [comment]
> What are the relative merits of a request over review?

I am not sure if I understand this question. Sorry, been context switching a lot.

**Comment by nstarman** [comment]
I should've quoted the line from the opening comment.

> @Cadair also expressed desire to have the Action to post a PR comment instead of PR review (see the current behavior at #11295). If there is consensus to do this, I can also make this change to my feature branch; it is a one-liner

**Comment by pllim** [comment]
Re: comment vs review -- Doesn't matter much to me. They appear almost the same on the UI. I'd rather we stick with the default behavior out of the box, but others might feel strongly one way or another. 🤷

**Comment by pllim** [comment]
Let's move the milestone. This is not a blocker.

**Comment by nstarman** [comment]
@pllim, the RTD failure is unrelated. Is this still GTG?

**Comment by pllim** [comment]
> Is this still GTG?

I think @embray was uncomfortable about using my branch.

**Comment by nstarman** [comment]
Ah. Fair enough. Strange how slow official repository is. They must not have a staff member assigned.

**Pull request closed without merging**
