### PR TITLE
Sigma clipping fixed for fully-masked input MaskedArray

### LINKED ISSUE #9973: sigma_clipped_stats: Use of numpy.nanfunctions incompatible with masked arrays
### Description

`astropy.stats.sigma_clipping.sigma_clipped_stats` may be inappropriately using `numpy.nanfunctions` when masked arrays are involved.

A typical issue that has arisen is spacetelescope/jwst#4451, where the error is

```
ValueError: output array is read-only
```

During investigation, a numpy issue, numpy/numpy#12283 was found which is directly related to the above issues. The discussion implies that the `numpy.lib.nanfunctions` are not intended to be used with masked arrays and is what is leading to the error situation.

This issue is intended to open up the discussion of whether `sigma_clipped_stats`, and any other functions that are using the `nanfunctions`, should switch to the standard, non-nan, functions when masked arrays are involved.

### Expected behavior

No error.

### Actual behavior

ValueError: output array is read-only

### Steps to Reproduce
Execute the following:

```python
from astropy.stats import sigma_clipped_stats
import numpy as np

arr = np.zeros(2)
sigma_clipped_stats(arr, mask_value=0.)
```

### System Details

macOS-10.13.6-x86_64-i386-64bit
Python 3.8.1 (default, Jan  8 2020, 16:15:59) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.18.1
astropy 4.0
Scipy 1.4.1

### PR DESCRIPTION
**Pull request by larrybradley**
This PR fixes two sigma-clipping issues with inputs that are fully-masked `MaskedArray`.

For `sigma_clipped_stats`, the mask was ignored (even though it was all `True`):

```python
>>> from astropy.stats import sigma_clipped_stats
>>> arr = np.ma.MaskedArray(np.arange(10), mask=True)
>>> sigma_clipped_stats(arr)  # very wrong output since there are no valid input values!
(4.5, 4.5, 2.8722813232690143)
```

After this PR:
```python
>>> sigma_clipped_stats(arr)
(masked, masked, masked)
```

`np.ma.masked` is the expected output for fully-masked arrays, e.g.:
```python
>>> np.ma.mean(arr)
masked
```

This PR also fixes an issue in `sigma_clip` and `SigmaClip` where a `MaskedArray` was returned instead of a plain `ndarray` when the `masked` keyword was set to `False` (for a fully-masked `MaskedArray` input):

```python
>>> from astropy.stats import sigma_clip
>>> arr = np.ma.MaskedArray(np.arange(10), mask=False)
>>> sigma_clip(arr, masked=False)
masked_array(data=[--, --, --, --, --, --, --, --, --, --],
             mask=[ True,  True,  True,  True,  True,  True,  True,  True,
                    True,  True],
       fill_value=999999,
            dtype=int64)
```

After this PR:
```python
>>> sigma_clip(arr, masked=False)
array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
```
which is the expected result.

I also updated the docstrings some to clarify the expected outputs.

Fix #9973

### CODE REVIEW

**Comment by pllim** [comment]
@stscieisenhamer , please review. Thanks!

**Comment by jdavies-st** [comment]
Running the bit of code from #9973 using this branch:

```
In [1]: from astropy.stats import sigma_clipped_stats
   ...: import numpy as np 
   ...:  
   ...: arr = np.zeros(2) 
   ...: sigma_clipped_stats(arr, mask_value=0.)                                                                                          
/Users/jdavies/dev/astropy/astropy/stats/sigma_clipping.py:770: RuntimeWarning: Mean of empty slice
  mean = np.nanmean(data_clipped, axis=axis)
/Users/jdavies/miniconda3/envs/astropy/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1115: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,
/Users/jdavies/miniconda3/envs/astropy/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1666: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
Out[1]: (nan, nan, nan)
```
I think that's what we would expect, right?

**Comment by stscieisenhamer** [comment]
👍

**Comment by larrybradley** [comment]
@jdavies-st I forget to address the `mask_value` keyword in this PR.  For consistency with numpy statistics ufuncs, I think that in the case of full-masked arrays `sigma_clipped_stats` should always return `(masked, masked, masked)`, instead of `(nan, nan, nan)`.  It doesn't yet because I need to make a quick change.

**Comment by larrybradley** [comment]
I've updated this PR so that completely-masked arrays are handled consistently:

```python
# masked-array mask is all True
>>> arr = np.ma.MaskedArray(np.arange(10), mask=True)
>>> result = sigma_clipped_stats(arr)
(masked, masked, masked)

# `sigma_clipped_stats` `mask_value` masks all values
>>> arr = np.ma.MaskedArray(np.zeros(10), mask=False)
>>> result = sigma_clipped_stats(arr, mask_value=0.)
(masked, masked, masked)

# `sigma_clipped_stats` `mask` is all True
>>> arr = np.ma.MaskedArray(np.arange(10), mask=False)
>>> mask = arr < 20
>>> result = sigma_clipped_stats(arr, mask=mask)
(masked, masked, masked)
```

**Pull request merged**
