### PR TITLE
MRT metadata input and subsequent writing [GSoC21c]

### PR DESCRIPTION
**Pull request by Suyog7130**
### Description

This Pull Request is part of the 2021 Google Summer of Code work I am doing together with mentors @aaryapatil and @hamogu.
It is a continuation of the modifications in #11897 and #12027 which primarily aims to address issue #11257.

Note that the count appended at the end of the PR title, **[GSoC21a]**, **[GSoC21b]** and so on, denote the sequence in which rebasing has been (will be) done to the commits. It is preferred if the merging also takes place in this order. Also, because the previous PRs are not merged yet, the later ones contain numerous unrelated commits at the time of opening the PR.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by Suyog7130** [comment]
Changes pertaining to this PR start after the commit titled **add changelog for #12027**

**Comment by Suyog7130** [comment]
Brief summary and some comments:

- [x] Global notes can be passed using a direct `notes` keyword for the `Cds` class.
- [x] If a `SkyCoord` column has any notes, then all its component columns after extraction should have the same note with the same note number appended in the column description.
- [x] Same note should not be repeated for two columns, instead all the columns having same note should reference the same note number.
- [x] Global notes should be at the end of the notes section in the ReadMe. **Column description should not reference the Global notes!**
- [x] Add feature to add authors from a list of authors.
- [ ] Should there be a separate keyword for the primary author?
- [ ] Should the author name be sorted according to First/Last name, like it is done in BibTex?
- [ ] What if the reference column for repeated notes is a column with mix-in values? Since the original column is not used then, will `col.meta.notes` or `col.note_ref` attributes be available?
- [ ] Edit the docstring of `Cds` class to list out the metadata keywords.

- Have used `Note (G)` for global notes in the ReadMe, since CDS decrees something similar. MRT doesn't have any particular opinion about this, so CDS must be followed for these optional attributes.

- Global notes are important specially for the cases when a single file has numerous Byte-By-Bytes. Like given here: https://cdsarc.unistra.fr/viz-bin/ReadMe/IX/22?format=html&tex=true
But our case is only for a single table, thus containing a single Byte-By-Byte in the ReadMe.
     - [ ] Maybe I should write about this in the documentation too.

**Comment by Suyog7130** [comment]
Have done a clever trick of using the column name in `col.meta.notes` to inform that any particular column's note will be the same as that of another column. Voila! A `col.note_ref` attribute is used internally for this purpose.

The above would **not work** when the reference is made before the notes for the previous column have been defined.
So, it should be clear in the documentation that when one wants to repeat a note for multiple columns, the first such column should the note defined, while the following ones referencing it.

Else, the notes will be repeated in the ReadMe even if the `col.meta.notes` are same.
Also, catching the `AttributeError` in these cases, doesn't automatically repeat the note. It puts the name of the reference col in the notes instead.

**Comment by Suyog7130** [comment]
Notes and notes referencing doesn't work for mix-in columns because they are not `Column` objects and thus do not have the `meta` attribute. So, `col.meta.notes` cannot be assigned. They can be converted to `Column` objects beforehand by the user, if notes for them are required. The Notes should work then for columns that are `Column` objects but have `coord` values, after splitting into the component cols is done.
However, the writing should work for tables that have notes and have mix-in columns as well.

**Comment by Suyog7130** [comment]
A further point about note-taking in MRT/CDS,
- CDS provides two options for it, that of prefixing `*` to the Explanations column of Byte-By-Byte when a note is present or suffixing a number in parentheses for the same. (http://vizier.u-strasbg.fr/doc/catstd/catstd-3.5.htx)
- Whereas MRT simply chooses latter of these as the fixed standard, which is exactly what this PR does as well. (https://journals.aas.org/mrt-explanation/#notes)

**Comment by hamogu** [comment]
@Suyog7130 Do you think you'll have time to continue this (and the other PRs)? If now, should @aaryapatil and I see if we can take it over? We'd love you to be a regular contributor to astropy, but it would also be bad to see this PR just closed and the work that already went into it forgotten. We've gone so far already with the first PRs you did, I'd love to see these finished, too.

**Comment by hamogu** [comment]
@Suyog7130 Shoudl we re-open this?

**Comment by Suyog7130** [comment]
Yes, that would be great. I will push new commits to the PR soon.

**Pull request closed without merging**
