### PR TITLE
Getting errors while fitting polynomial model with tied  parameters

### PR DESCRIPTION
**Pull request by embray**
Hi! Found two different errors, one for each kind of syntax suggested by the documentation (http://astropy.readthedocs.org/en/latest/modeling/fitting.html), while trying to get 'tied' parameters to work while fitting a model.

I'm using Python 3 in Fedora 21 (therefore Astropy 0.3.2-2.fc20).

I can fit without the ties using NonLinearLSQFitter over a model Polynomial2D, using:

```python
from astropy.modeling import models
from astropy.modeling.fitting import NonLinearLSQFitter as LevMarLSQFitter
Polynomial2D_model = models.Polynomial2D ( degree = 2 )
LevMarLSQFitter_fit = LevMarLSQFitter ( )
polynomial_fit = LevMarLSQFitter_fit ( model = Polynomial2D_model, x = iia_x_dimension, y = iia_y_dimension, z = self.__ffa_unwrapped )
```

But this modified code fails:

```python
def tied_c2_0 ( o_model ):
  o_c2_0 = o_model.c0_2
  return o_c2_0

Polynomial2D_model = models.Polynomial2D ( degree = 2, tied = { 'c2_0' : tied_c2_0 } )
LevMarLSQFitter_fit = LevMarLSQFitter ( )
polynomial_fit = LevMarLSQFitter_fit ( model = Polynomial2D_model, x = iia_x_dimension, y = iia_y_dimension, z = self.__ffa_unwrapped )
```
```
Traceback (most recent call last):
  File "./eg_highres_pipeline.py", line 111, in <module>
    unwrap_phase_map ( )
  File "./eg_highres_pipeline.py", line 40, in unwrap_phase_map
    f_scanning_wavelength = 6616.895 )
  File "/home/nix/cloud_essential2/tuna/github/tools/phase_map/high_resolution.py", line 112, in __init__
    ffa_unwrapped = self.unwrapped_phase_map )
  File "/home/nix/cloud_essential2/tuna/github/tools/models/parabola.py", line 80, in fit_parabolic_model_by_Polynomial2D
    o_parabola.create_model_map_by_Polynomial2D ( )
  File "/home/nix/cloud_essential2/tuna/github/tools/models/parabola.py", line 36, in create_model_map_by_Polynomial2D
    tied = { 'c2_0': tied_c2_0 } )
  File "/usr/lib64/python3.3/site-packages/astropy/modeling/polynomial.py", line 672, in __init__
    param_dim=param_dim, **params)
  File "/usr/lib64/python3.3/site-packages/astropy/modeling/polynomial.py", line 131, in __init__
    self._validate_params(**params)
  File "/usr/lib64/python3.3/site-packages/astropy/modeling/polynomial.py", line 183, in _validate_params
    assert(len(params) == numcoeff)
AssertionError
```
The other syntax also is problematic:

```python
def tied_c2_0 ( o_model ):
  o_c2_0 = o_model.c0_2
  return o_c2_0

Polynomial2D_model = models.Polynomial2D ( degree = 2 )
Polynomial2D_model.c2_0.tied = tied_c2_0
LevMarLSQFitter_fit = LevMarLSQFitter ( )
polynomial_fit = LevMarLSQFitter_fit ( model = Polynomial2D_model, x = iia_x_dimension, y = iia_y_dimension, z = self.__ffa_unwrapped )
```
```
Traceback (most recent call last):
  File "./eg_highres_pipeline.py", line 111, in <module>
    unwrap_phase_map ( )
  File "./eg_highres_pipeline.py", line 40, in unwrap_phase_map
    f_scanning_wavelength = 6616.895 )
  File "/home/nix/cloud_essential2/tuna/github/tools/phase_map/high_resolution.py", line 112, in __init__
    ffa_unwrapped = self.unwrapped_phase_map )
  File "/home/nix/cloud_essential2/tuna/github/tools/models/parabola.py", line 80, in fit_parabolic_model_by_Polynomial2D
    o_parabola.create_model_map_by_Polynomial2D ( )
  File "/home/nix/cloud_essential2/tuna/github/tools/models/parabola.py", line 46, in create_model_map_by_Polynomial2D
    z = self.__ffa_unwrapped )
  File "/usr/lib64/python3.3/site-packages/astropy/modeling/fitting.py", line 465, in __call__
    full_output=True)
  File "/usr/lib64/python3.3/site-packages/scipy/optimize/minpack.py", line 369, in leastsq
    _check_func('leastsq', 'Dfun', Dfun, x0, args, n, (m,n))
  File "/usr/lib64/python3.3/site-packages/scipy/optimize/minpack.py", line 30, in _check_func
    raise TypeError(msg)
TypeError: leastsq: there is a mismatch between the input and output shape of the 'Dfun' argument '_wrap_deriv'.
```
At least one other person on the user ML can reproduce these errors.

### CODE REVIEW

**Comment by embray** [comment]
Attached fix addresses the first part of the issue, that instantiating a polynomial model with constraints wasn't working.  Still working on a fix to the second issue.

**Comment by rcbrgs** [comment]
I have tested the proposed fix and it does solve my application's issue, using both syntaxes.
Thank you @embray !

**Comment by embray** [comment]
I'll just add a changelog entry then merge--thanks for testing the fix @rcbrgs

**Comment by embray** [comment]
Rebased on master and added changelog entries.

**Pull request merged**
