### PR TITLE
Fix use of pytest xdist

### PR DESCRIPTION
**Pull request by saimn**
Related to #6556 : updating CircleCI to run on Python 3 caused pytest-xdist to fail when collecting tests. This is because a few tests use set for parametrized values, and the set order is random. (see https://github.com/pytest-dev/pytest-xdist/issues/63).
So the simple fix here is to use a fixed order for the tests. (Note I took the updated CircleCI config from #6556, it was split in multiple commits so I just copied the files, but credits goes to @bsipocz  and @astrofrog :wink: )

### CODE REVIEW

**Comment by saimn** [comment]
It works for parametrized tests, but there are issues with a few doctests. I think it's related to metaclasses with use dict to store classes. One option is to set PYTHONHASHSEED, but not sure if it's a good idea to use this globally.

**Comment by MSeifert04** [comment]
What about using Python 3.6? There the order of dictionaries is preserved (at least CPython and at least currently).

**Comment by MSeifert04** [comment]
You could also **try** to make `REPRESENTATION_CLASSES` and `DIFFERENTIAL_CLASSES` in `coordinates.representations.py` use `OrderedDict`s. If that works we at least know what's responsible.

**Comment by saimn** [comment]
Yes python 3.6 is another option, but let's try first with `Orderedict` (good point !).

**Comment by MSeifert04** [comment]
Yeah, but doesn't seem to work. There's still a difference with coordinates.

**Comment by MSeifert04** [comment]
Looks good. But if we're going to use `HASHSEED` we probably should document it as requirement for `python-xdist` and we can revert the `OrderedDict`s and `sorted` stuff.

**Comment by saimn** [comment]
Yes, I tried HASHSEED to be sure that it fixes the issues but it's not the best solution. It can be a temporary solution until switching to python 3.6 (not sure if there is a reason why you use 3.5 @astrofrog ?). I will remove the `OrderedDict` but I will the "sorted set" one will still be useful with python 3.6 (not sure?).

**Comment by MSeifert04** [comment]
> I will the "sorted set" one will still be useful with python 3.6 (not sure?).

Yes, sets remain unordered.

**Comment by bsipocz** [comment]
Thanks @saimn. I'm merging this now to keep the ball rolling on the other PRs, put please feel free to open follow-up PRs if needed.

(I feel it's ok to run circle with py35, it's for 32bit anyway...)

**Comment by saimn** [comment]
Ok thanks @bsipocz, but I should at least remove the `OrderedDict` commit, I will open a follow-up PR.
And you will need to rebase  #6556 and remove the commits related to CircleCI :wink:

> (I feel it's ok to run circle with py35, it's for 32bit anyway...)

The issue py35 versus py36 but the fact that using HASHSEED make the tests less representative of real usage. This could hide bugs, but as it is also tested on Travis I think it's ok for now.

**Comment by saimn** [comment]
Oh @MSeifert04 was faster than me :racehorse: ! (Thanks Michael!)

**Comment by MSeifert04** [comment]
> The issue py35 versus py36 but the fact that using HASHSEED make the tests less representative of real usage. This could hide bugs, but as it is also tested on Travis I think it's ok for now.

Yes, I think in the long-term this either needs to be documented that `pytest-xtest` requires `PYTHONHASHSEED` or we should make the tests independant of hash-randomization for strings. Is it worth opening an issue about that?

> Oh MSeifert04 was faster than me ! (Thanks Michael!)

Yeah, I was just fetching the new changes anyway so it wasn't really complicated. 😄

**Comment by bsipocz** [comment]
(oops, sorry for the premature merge, these printing days fills up my notifications, and just wanted to get rid of the trivial looking open ones...)

**Pull request merged**
