### PR TITLE
Remove distracting quotation marks form `UnknownSiteException` messages

### PR DESCRIPTION
**Pull request by eerovaher**
### Description

It is not necessarily good practice to require `pytest.raises()` to match error messages exactly in all tests, but it is still good to test full error messages in dedicated tests. When implementing such tests for `UnknownSiteException` I noticed that the messages contain distracting quotation marks (see the diff for the test file between the two commits of this pull request). One of them was a typo, the others I got rid of by implementing `UnknownSiteException.__str__()` instead of constructing the message in `UnknownSiteException.__init__()` and passing it to `super().__init__()`.

- [x] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Overwriting `__str__` seemed a bit annoying, but looking up why this was needed, I found that the definition for `KeyError_str` in CPython is: https://github.com/python/cpython/blob/59630f92d8223f80993e3646b0f734d27f4b8dd4/Objects/exceptions.c#L2632-L2647

Note: "The downside is that if KeyError is raised with an explanatory string, that string will be displayed in quotes.  Too bad."!

So, hurray for your solution!

**Comment by mhvk** [comment]
Docs had a build failure, which seems unrelated (some installation problem). @pllim - can this be restarted or overridden?

**Comment by eerovaher** [comment]
I don't see how the code changes could have possibly been the cause of the documentation build failure, so I force-pushed to trigger another build.

No other error messages are affected by this quirk of `KeyError` because `UnknownSiteException` is the only error class we have that inherits from it (based on `git grep 'class.*KeyError'`).

**Comment by mhvk** [comment]
OK, hopefully readthedocs will pass now - I enabled auto-merge. Thanks!

**Pull request merged**
