### PR TITLE
TST: pyinstaller does not like matplotlib in quotes

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is a follow-up of https://github.com/astropy/astropy/pull/15886 because it fails in pyinstaller.

Example log: https://github.com/astropy/astropy/actions/runs/7910507405/job/21593211569

p.s. I tried to do `pre-commit run` locally but does not work in Python 3.12 and I don't have time to deal with that. I will just fix it with bot of my style is not up to the golden standard.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
pre-commit.ci autofix

**Comment by neutrinoceros** [comment]
> p.s. I tried to do pre-commit run locally but does not work in Python 3.12 and I don't have time to deal with that.

when you have a minute, I'd be happy to take a look at whatever pre-commit prints on your machine. I don't have any issues running it on Python 3.12 myself but I'm curious. Anyway, thanks a lot for patching this so promptly !

**Comment by pllim** [comment]
devinfra and linkcheck failures are unrelated

**Comment by pllim** [comment]
Re: pre-commit traceback (WSL2/Ubuntu on Windows 11)

```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('.../.cache/pre-commit/repof0lpn1aj/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 2
stdout: (none)
stderr:
    ERROR: Exception:
    Traceback (most recent call last):
      File ".../site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
        status = run_func(*args)
                 ^^^^^^^^^^^^^^^
      File ".../site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
        return func(self, options, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../site-packages/pip/_internal/commands/install.py", line 326, in run
        session = self.get_default_session(options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../site-packages/pip/_internal/cli/req_command.py", line 98, in get_default_session
        self._session = self.enter_context(self._build_session(options))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
        session = PipSession(
                  ^^^^^^^^^^^
      File ".../site-packages/pip/_internal/network/session.py", line 343, in __init__
        self.headers["User-Agent"] = user_agent()
                                     ^^^^^^^^^^^^
      File ".../site-packages/pip/_internal/network/session.py", line 175, in user_agent
        setuptools_dist = get_default_environment().get_distribution("setuptools")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../site-packages/pip/_internal/metadata/importlib/_envs.py", line 188, in get_distribution
        return next(matches, None)
               ^^^^^^^^^^^^^^^^^^^
      File ".../site-packages/pip/_internal/metadata/importlib/_envs.py", line 183, in <genexpr>
        matches = (
                  ^
      File ".../site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
        for dist in self._iter_distributions():
      File ".../site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
        for dist in finder.find_eggs(location):
      File ".../site-packages/pip/_internal/metadata/importlib/_envs.py", line 144, in find_eggs
        yield from self._find_eggs_in_dir(location)
      File ".../site-packages/pip/_internal/metadata/importlib/_envs.py", line 111, in _find_eggs_in_dir
        from pip._vendor.pkg_resources import find_distributions
      File ".../site-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
        register_finder(pkgutil.ImpImporter, find_on_path)
                        ^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

Upgrading this and that (as found on online forums) didn't help. Also answers like https://github.com/pre-commit/pre-commit/issues/3054#issuecomment-1794802856 are not very helpful.

**Comment by pllim** [comment]
pyinstaller is green, along with everything. Failures unrelated. So merging.

**Pull request merged**
