### PR TITLE
Change default of cache arg for parallel download and warn if False

### PR DESCRIPTION
**Pull request by MSeifert04**
This still does not resolve issue #6662 but it changes the default so that it will work (windows) and work as expected on Linux.

cc: @saimn @drdavella

### CODE REVIEW

**Comment by pllim** [comment]
To me, this is more of an API change than a bug and hence should be in v3 instead. What do you think, @bsipocz ?

**Comment by MSeifert04** [comment]
Yes, it's definitely an API change. But one that works around a bug on windows and raises awareness (that it's cached even if it was specified as not-caching) for other systems. I wouldn't mind 3.0 given that the function is probably unused and it seems like I'm the only intentional Windows-astropy-user (and I use `master`).

**Comment by pllim** [comment]
Yeah, I feel more comfortable inserting this in v3. Shall we?

**Comment by saimn** [comment]
Maybe v2.0 could get at least the warning for Windows users ?

**Comment by MSeifert04** [comment]
I'll wait a bit for someone else to weigh in before I move the changelog. No use in moving it around multiple times if opinions differ. I hope you don't mind @pllim

**Comment by pllim** [comment]
Yeah, no problem, @MSeifert04 . Let's give this some time. Thanks for your patience!

**Comment by MSeifert04** [comment]
okay, if no one else wants to weight in (e.g. @bsipocz 😄 ) I'll move the changelog entry to 3.0.x later :)

**Comment by bsipocz** [comment]
I have no strong opinion on this, happy to backport if that's the decision (yes, a very minor API change, but fixes a bug), but on the other hand having it in v3.0 is the cleaner approach.

**Comment by pllim** [comment]
I still prefer the cleaner route (i.e., v3). If they want the warning, they can upgrade. 😉

**Comment by MSeifert04** [comment]
Okay, rebased and changed to 3.0.x :) 

Thanks for your feedback!

**Comment by MSeifert04** [comment]
Just a note for the person finally hitting the merge-button: The test is only run in the "allowed failures" tests, so probably should be checked if it worked there.

**Comment by MSeifert04** [comment]
okay, it has passed: https://travis-ci.org/astropy/astropy/jobs/285616756#L2768

**Comment by bsipocz** [comment]
OK, less failures than before, and non in utils, so I'm merging this now. Thanks @MSeifert04!

**Pull request merged**
