### PR TITLE
BUG: Fix test_plt_scatter_masked matplotlib check that broke pyinstaller job

### PR DESCRIPTION
**Pull request by pllim**
### Description

The check was originally modified in https://github.com/astropy/astropy/pull/16820 but that caused other tests to be skipped when they are not supposed to when matplotlib is not installed (can't say I grok why at the time of writing this). So https://github.com/astropy/astropy/pull/16843 was done but it caused pyinstaller job to fail with `E   KeyError: 'matplotlib'` during test collection. This PR is an attempt to skip only `test_plt_scatter_masked` when matplotlib conditions are not satisfied *and* to not break pyinstaller job doing that.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
This looks good - I'm approving, though obviously the real test is in the tests...

**Comment by pllim** [comment]
Log from minimal deps job:

```
astropy/utils/masked/tests/test_masked.py . [ 93%]
........................................................................ [ 93%]
........................................................................ [ 94%]
........................................................................ [ 94%]
........................................................................ [ 94%]
........................................................................ [ 94%]
........................................................................ [ 95%]
........................................................................ [ 95%]
........................................................................ [ 95%]
...........................s                                             [ 95%]
```

Log from all deps job:

```
astropy\utils\masked\tests\test_masked.py . [ 92%]
........................................................................ [ 92%]
........................................................................ [ 93%]
........................................................................ [ 93%]
........................................................................ [ 93%]
........................................................................ [ 93%]
........................................................................ [ 94%]
........................................................................ [ 94%]
........................................................................ [ 94%]
............................                                             [ 94%]
```

Log from pyinstaller:

```
astropy_tests/utils/masked/tests/test_masked.py ........................ [ 92%]
........................................................................ [ 93%]
........................................................................ [ 93%]
........................................................................ [ 93%]
........................................................................ [ 93%]
........................................................................ [ 94%]
........................................................................ [ 94%]
........................................................................ [ 94%]
........................................................................ [ 95%]
.....                                                                    [ 95%]
```

**Comment by pllim** [comment]
Link check failure unrelated.

**Comment by mhvk** [comment]
Thanks! Happy to have that one behind us...

**Pull request merged**
