### PR TITLE
BUG: fix integer roundoff corner case in Lomb-Scargle

### LINKED ISSUE #4954: stats.lombscargle failures with Numpy-dev
Some of the tests for the ``stats.lombscargle`` sub-package are failing with the latest developer version of Numpy, e.g.:

```
____________________________________________________________________________ test_all_methods[psd-True-False-True-True-chi2] _____________________________________________________________________________

data = (array([ 10.97627008,  14.30378733,  12.05526752,  10.89766366,
         8.47309599,  12.91788226,   8.75174423,  17.8...84375,  0.68619301,  1.44437239,  1.2395508 ,
        0.99045881,  0.72741463,  0.75435648,  0.55802916,  0.93441663]))
method = 'chi2', center_data = True, fit_mean = True, with_errors = False, with_units = True, normalization = 'psd'

    @pytest.mark.parametrize('method', ALL_METHODS_NO_AUTO)
    @pytest.mark.parametrize('center_data', [True, False])
    @pytest.mark.parametrize('fit_mean', [True, False])
    @pytest.mark.parametrize('with_errors', [True, False])
    @pytest.mark.parametrize('with_units', [True, False])
    @pytest.mark.parametrize('normalization', NORMALIZATIONS)
    def test_all_methods(data, method, center_data, fit_mean,
                         with_errors, with_units, normalization):
        if method == 'scipy' and (fit_mean or with_errors):
            return
    
        t, y, dy = data
        frequency = 0.8 + 0.01 * np.arange(40)
        if with_units:
            t = t * units.day
            y = y * units.mag
            dy = dy * units.mag
            frequency = frequency / t.unit
        if not with_errors:
            dy = None
    
        kwds = dict(normalization=normalization)
        ls = LombScargle(t, y, dy, center_data=center_data, fit_mean=fit_mean)
        P_expected = ls.power(frequency, **kwds)
    
        # don't use the fft approximation here; we'll test this elsewhere
        if method in FAST_METHODS:
            kwds['method_kwds'] = dict(use_fft=False)
        P_method = ls.power(frequency, method=method, **kwds)
    
        if with_units:
            if normalization == 'psd' and not with_errors:
                assert P_method.unit == y.unit ** 2
            else:
                assert P_method.unit == units.dimensionless_unscaled
        else:
            assert not hasattr(P_method, 'unit')
    
>       assert_quantity_allclose(P_expected, P_method)

astropy/stats/lombscargle/tests/test_lombscargle.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/tests/helper.py:480: in assert_quantity_allclose
    **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x_id = array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,...,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False], dtype=bool)
y_id = array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,...,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True], dtype=bool)
hasval = '+inf'

    def chk_same_position(x_id, y_id, hasval='nan'):
        """Handling nan/inf: check that x and y have the nan/inf at the same
            locations."""
        try:
            assert_array_equal(x_id, y_id)
        except AssertionError:
            msg = build_err_msg([x, y],
                                err_msg + '\nx and y %s location mismatch:'
                                % (hasval), verbose=verbose, header=header,
                                names=('x', 'y'), precision=precision)
>           raise AssertionError(msg)
E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=0
E           
E           x and y +inf location mismatch:
E            x: array([  5.379997e-01,   9.984607e-01,   2.911666e+00,   3.905607e+00,
E                    2.454666e+00,   2.022995e-01,   1.302772e+00,   6.637232e+00,
E                    1.201750e+01,   1.447837e+01,   1.600839e+01,   1.972033e+01,...
E            y: array([ inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,
E                   inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,
E                   inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,
E                   inf,  inf,  inf,  inf,  inf,  inf,  inf])

/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/numpy-1.12.0.dev0+cd96464-py3.5-macosx-10.5-x86_64.egg/numpy/testing/utils.py:677: AssertionError
```

@jakevdp - do you have time to investigate this?

### PR DESCRIPTION
**Pull request by jakevdp**
EDIT: Fixes #4954

### CODE REVIEW

**Comment by jakevdp** [comment]
Hopefully this will fix the allowed test failures on the numpy-dev build.

**Comment by jakevdp** [comment]
Test failure looks unrelated to this PR: appears a VM died mid-way through the test run.

The good news is that the previously failing numpy-dev test is now passing!

**Comment by crawfordsm** [comment]
@astrofrog I'm happy for this to be merged but I am currently traveling and it will need to be merged onto the 1.2 branch as well.

**Comment by mhvk** [comment]
I'm still puzzled why it raised errors before. It seemed in all the tests `dy=1`, so what would go wrong?
...
...
Hmm, this is clearly a bug in numpy (now at https://github.com/numpy/numpy/issues/7649)
```
np.array(1, dtype=int) ** -2
# 0
np.array(1, dtype=float) ** -2
# 1.
```
but this also suggests a simpler fix for now: just set `dy = 1.` (i.e., add the dot) for the default `dy=None` case. This would seem good practice anyway.

**Comment by astrofrog** [comment]
I was thinking that this was a bit weird, so glad to hear it is a Numpy bug!

**Comment by jakevdp** [comment]
>  just set dy = 1. (i.e., add the dot) for the default dy=None case.

That would do nothing in the case of a user passing an integer. The solution in this PR should work in all cases, and is much cleaner than trying to enforce ``dy`` to be a float everywhere.

**Comment by jakevdp** [comment]
Oh, and I opened a numpy issue for this last night: https://github.com/numpy/numpy/issues/7648 :smile:

**Comment by mhvk** [comment]
good point. though I might then do 1./dy**2. But really this is a numpy bug, so I labelled it as such. If numpy is quick about, I'd use their fix...

**Comment by mhvk** [comment]
But perhaps I'm being silly: it certainly doesn't hurt to merge this as is either.

**Comment by pllim** [comment]
I agree with @mhvk . Adding a ".0" will not hurt performance or anything, right? So, might as well.

**Comment by mhvk** [comment]
No, the `.0` doesn't matter, though just doing `1/a**2` is faster:
```
a = np.ones((100000,), dtype=int)
%timeit a ** -2
# 100 loops, best of 3: 7.21 ms per loop
%timeit a ** -2.0
# 100 loops, best of 3: 7.29 ms per loop
%timeit 1./a**2
1000 loops, best of 3: 1.1 ms per loop
```
But I doubt any of these differences matter compared to the overall runtime.

**Comment by mhvk** [comment]
This is now fixed upstream, so I'm just closing this; it is better if code just works without having to worry about whether a power is float or integer!

**Comment by jakevdp** [comment]
No, please don't close this! This needs to be merged. The upstream fix will not affect old numpy releases, and there is still the possibility for this to break things here.

Again, this PR needs to be merged, and I can't think of any good reason not to.

**Comment by astrofrog** [comment]
Is this not an issue only with the developer version of Numpy though?

**Comment by MSeifert04** [comment]
Not necessarily, the problem is that ``array(integer) ** -2`` can be zero because numpy doesn't follow the coercion rules that ``int ** int`` could be a float. It's like python2 behaviour with ``int / int = int``. :smile:

**Comment by jakevdp** [comment]
I believe there are platforms on which failures would occur due to numpy's int-casting issues. I don't think any of the Travis platforms happen to have the right combination of features to show that failure.

**Comment by jakevdp** [comment]
Really, though, this PR changes an int to a float in a case where we expect a cast to happen... I'm not sure this volume of discussion is necessary before merge :smile:

**Comment by jakevdp** [comment]
I pushed another PR that tests all methods to make sure integer and float inputs yield the same results: #4965.

**Comment by jakevdp** [comment]
This *might* fail on 32-bit machines without the fix from #4950. It depends on the particular architecture that travis uses.

**Comment by mhvk** [comment]
@jakevdp - there are no older versions of numpy that have this bug (the PR that caused it has not been in any released version), and numpy itself now has a test to ensure this doesn't recur.

**Comment by mhvk** [comment]
@MSeifert04 - ah, yes, you're right: we're not safe for `dy = 2` in user input.

**Comment by jakevdp** [comment]
@mhvk – there are two different bugs. The one you're talking about was only in dev, the one I'm talking about is in all current releases. For example:
```
>>> np.int64(2) ** -2
0.25
>>> np.int32(2) ** -2
0
```

**Comment by MSeifert04** [comment]
This Bug really messes with my head...

NumPy integer don't always follow the normal python3 coercion rules (with power-operations) and NumPy raises now Exceptions when dividing by 0. This means the Bug wasn't even cleanly recognizable before because it just issued a Warning... and even the fix still has some problems with special cases?

I tried the example @jakevdp gave and got different results (same version on windows 64 bit python3)
```
np.__version__    # 1.10.4
np.array(2) ** -2 # 0
np.array(2).dtype # int32
np.int32(2) ** -2 # 0.25
np.int64(2) ** -2 # 0.25
2 ** -2           # 0.25
```
I'm not sure if that's relevant for this discussion but @mhvk: did they fix this difference?

**Comment by jakevdp** [comment]
@MSeifert04 – it's a subtle issue having to do with the casting rules used in binary ufuncs, and the result is highly platform dependent. See the discussion in the numpy PR: https://github.com/numpy/numpy/pull/7459

**Comment by mhvk** [comment]
OK, while I would have done the cast to real differently, that is really nitpicking, and it seems this may still avoid real issues. So, let me just merge this.

**Comment by mhvk** [comment]
@astrofrog - not quite sure about changelog since this hasn't gone in anywhere -- this should get backported to 1.2 though!

**Pull request merged**
