### PR TITLE
Guard against ncoord=0, zero malloc size in pipeline_pix2foc() & pipeline_all_pixel2world()

### LINKED ISSUE #7804: WCS: missing error check for zero coordinates (ncoord)
[src](https://github.com/astropy/astropy/blob/master/astropy/wcs/src/pipeline.c#L101-L108)
```c
int
pipeline_all_pixel2world(
    pipeline_t* pipeline,
    const unsigned int ncoord,
    const unsigned int nelem,
    const double* const pixcrd /* [ncoord][nelem] */,
    double* world /* [ncoord][nelem] */) {

...

if (has_wcs) {
    buffer = mem = malloc(
        ncoord * nelem * sizeof(double) + /* imgcrd */
        ncoord * sizeof(double) +         /* phi */
        ncoord * sizeof(double) +         /* theta */
        ncoord * nelem * sizeof(double) + /* tmp */
        ncoord * nelem * sizeof(int)      /* stat */
        );

    if (buffer == NULL) {
      status = wcserr_set(
        PIP_ERRMSG(WCSERR_MEMORY), "Memory allocation failed");
      goto exit;
    }
...
```

Shouldn't there be a check for ``ncoord > 0`` before being used for allocation size? ``malloc`` can still accept a zero size so I'm not sure if this intentional or a bug? _c.f._ https://en.cppreference.com/w/c/memory/malloc

> _"If size is zero, the behavior is implementation defined (null pointer may be returned, or some
non-null pointer may be returned that may not be used to access storage, but has to be passed to free)."_

This trips up in the subsequent call to ``wcsp2s`` [here](https://github.com/astropy/astropy/blob/master/astropy/wcs/src/pipeline.c#L144)  with the following error ([src](https://github.com/astropy/astropy/blob/master/cextern/wcslib/C/wcs.c#L2645-L2649)):
```c
...
/* Sanity check. */
  if (ncoord < 1 || (ncoord > 1 && nelem < wcs->naxis)) {
    return wcserr_set(WCSERR_SET(WCSERR_BAD_CTYPE),
      "ncoord and/or nelem inconsistent with the wcsprm");
  }
...
```

Inspecting the values a this point for my example ``ncoord == 0``. (BTW: it's a good idea for errors to print values and boundaries.)

This is a similar error as reported in https://github.com/astropy/astropy/issues/4973 _"Don't raise an error if passing zero coordinates to WCS"_, excpet that it is in ``wcsp2s`` and not ``wcss2p``.

```
InconsistentAxisTypesError: ERROR 4 in wcsp2s() at line 2647 of file cextern/wcslib/C/wcs.c:
ncoord and/or nelem inconsistent with the wcsprm.
```

### PR DESCRIPTION
**Pull request by jamienoss**
Resolves #7804

Signed-off-by: James Noss <jnoss@stsci.edu>

### CODE REVIEW

**Comment by jamienoss** [comment]
FYI: I'm not sure if ``WCSERR_BAD_COORD_TRANS`` is correct usage. Feel free to suggest a better error message.

**Comment by jamienoss** [comment]
BTW: I'm cool with just an ``assert(ncoord)`` if everyone else is? ``nelem`` is asserted in the 2nd func.

**Comment by nden** [comment]
@jamienoss Sorry, one more thing - can you add an entry to the change log under 2.0.9. Thanks!

**Comment by jamienoss** [comment]
@nden back to you.

**Pull request merged**
