### PR TITLE
fix w0wz de_density_scale

### LINKED ISSUE #14975: Error in distance calculations for w0wz Cosmologies
### Description

I believe that the equation used to calculate the de_density_scale in `w0wzcdm.py `is incorrect. 

Line 205 has `return zp1 ** (3.0 * (1.0 + self._w0 - self._wz)) * exp(-3.0 * self._wz * z)`

### Expected behavior

After manually calculating the integral/checking wolfram, I don't think it should be a negative in the exponent and should read: `return zp1 ** (3.0 * (1.0 + self._w0 - self._wz)) * exp(3.0 * self._wz * z)`

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

### PR DESCRIPTION
**Pull request by nstarman**
EDIT: Fix #14975

TODO:
- [x] changelog

### CODE REVIEW

**Comment by pllim** [comment]
@RyanCamo , if you are okay with this fix, please approve. Thanks!

**Review by aconley — APPROVED** [review]

**Review by pllim — APPROVED** [review]
aconley approved so I am approving by proxy. Thanks, everyone!

**Comment by pllim** [comment]
@nstarman , any chance you can manually backport this to v5.0.x or is that not applicable?

**Comment by pllim** [comment]
Too much refactoring, making backport to v5.0.x too confusing for me. But this bug is so subtle that I think we should still try to fix up v5.0.x. @nstarman , please do a manual patch to v5.0.x. Thanks! 🙏 

```
You are currently cherry-picking commit 7c3025269.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Changes to be committed:

        new file:   docs/changes/cosmology/14991.bugfix.rst

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

        deleted by us:   astropy/cosmology/flrw/tests/test_w0wzcdm.py
        deleted by us:   astropy/cosmology/flrw/w0wzcdm.py
        both modified:   astropy/cosmology/tests/test_core.py
        both modified:   astropy/cosmology/tests/test_utils.py
```

**Comment by nstarman** [comment]
Will do. I have a dev branch for this, but the tests are quite different.

**Pull request merged**
