### PR TITLE
Pin Numpy to <1.15.3 for now due to Numpy bug

### PR DESCRIPTION
**Pull request by astrofrog**
Since this week is going to be busy PR wise, I think it'd make sense to pin the Numpy versions on CircleCI temporarily while figuring out https://github.com/astropy/astropy/pull/7946

### CODE REVIEW

**Comment by astrofrog** [comment]
@pllim - can you already add a commit to undo it in your PR with the bug fixes?

**Comment by pllim** [comment]
> can you

Yes.

**Comment by pllim** [comment]
Appveyor still failed. FYI.

**Comment by bsipocz** [comment]
fyi: I've directly cancelled the travis run on the last commit

**Comment by astrofrog** [comment]
@bsipocz - is this good to go now? The travis failure is expected, right?

**Comment by bsipocz** [comment]
@astrofrog - actually I've restarted  travis as in a separate PR the numpy failure started to show there, too (originally I've cancelled it as passed here, but that has most probably changed in the past 3 hours...)

**Comment by astrofrog** [comment]
I think we need to change stable to 1.15.2 in .travis.yml - want to add a commit?

**Comment by bsipocz** [comment]
Travis is misbehaving now as well, so see https://github.com/astropy/ci-helpers/pull/331 for the workaround.

**Comment by astrofrog** [comment]
We still need the CircleCI change, so I'll re-open this and keep just that commit.

**Comment by astrofrog** [comment]
I'll just merge, since that commit passed originally (and is still passing)

**Comment by bsipocz** [comment]
Good point, I've forgot about circleCI.

**Pull request merged**
