### PR TITLE
update wcslib to 5.18

### PR DESCRIPTION
**Pull request by nden**
@bsipocz I set the milestone to 3.1 but feel free to change it if there's a better one.

The release notes are below:

WCSLIB version 5.18 (2018/01/10)
------------------

* C library

  - New routines introduced to preclude altering the global variables
    NPVMAX, NPSMAX, and NDPMAX, which determine how much memory to
    allocate for storing PVi_ma, PSi_ma, DPja, and DQia keyvalues:
    wcsinit(), lininit(), lindist(), and disinit().  These are now used
    by various WCSLIB routines, such as the header parsers, which
    previously temporarily altered the global variables, thus posing a
    thread hazard.  Testing and feedback on thread-safety issues, with
    patches, from Rodrigo Tobar Carrizo.

  - The Flex scanners, fitshdr(), wcsbth(), wcspih(), wcsulexe(), and
    wcsutrne(), have been rewritten as thin wrappers (with the same API)
    over scanners that were modified (with changed API) as required to
    use Flex's "reentrant" option.  Consequently, they are now reentrant
    and should be thread-safe.  That also passes through to the
    deprecated wrappers, wcsulex() and wcsutrn().

  - Fixed memory leaks in lindist() and lincpy() uncovered by valgrind.

  - Test programs tfitshdr, tpih1, tpih2, and ttab3 are now careful to
    free all allocated memory before exit to defeat spurious reports of
    memory leaks by valgrind.

* Fortran wrappers

  - New wrappers for wcsinit(), lininit(), lindist(), and disinit().

* Installation

  - configure now recognises the value of ARFLAGS obtained from the
    environment.

* User manual

  - Updates and amendments in line with the above changes.

  - Documentation generation moved to doxygen 1.8.14 (was 1.8.13).

### CODE REVIEW

**Comment by nden** [comment]
This needs an approval by a core developer.
I would normally wait and update wcslib before a release but looking at the release notes I thought it may be beneficial to update it now to provide access and more testing time in outside astropy aplication code.

**Comment by bsipocz** [comment]
@eteq - can we still have this in 3.0?

**Comment by eteq** [comment]
Adding this in 3.0 will necessitate an RC2 since it's a substantial change.  I'm not necessarily against that (as we might need an RC2 anyway).  

@nden - looking at the changelog it's not clear to me that any of this is especially user-facing, though.  Or is the key item that it's now thread-safe so can be used in certain places it may not have before?

**Comment by nden** [comment]
@eteq My only consideration is that it will be 6 months before there's another chance to update wcslib. Other than that I don't think it's critical to get this version in the release. I'd still want it in master so it gets used and tested this way.

**Comment by bsipocz** [comment]
OK, so let's merge this now. I remilestone it to 3.0.0 to make sure I won't forget to backport it if we have an RC2 anyway due to the other fixes, otherwise will change the milestone back to 3.1.

**Pull request merged**
