### PR TITLE
update iers for 4.3 release

### PR DESCRIPTION
**Pull request by eteq**
this updates the IERS file for what will hopefully be the copy to go into a 4.3 release.

Note as discussed more in https://github.com/astropy/astropy/commit/3aaad2220b0c0f85a7c526396b8c63bf154a1f87#comments it's a bit ambiguous if this should go into `main`, given that #9911 and  #1697 both go in the direction of it being something that's associated with release, which doesn't *necessarily* make it something that goes into `main`.  But given the fact that the leap second at least is generally 6-12 mo, maybe we should shoot for just doing this every major release in `main`?  Or just *never* updating it in `main` after this one, since it all gets auto-downloaded if you have an internet connection...  Maybe @mhvk has an opinion there?

### CODE REVIEW

**Review by pllim — APPROVED** [review]
I don't see why `main` should lag behind the release, but I don't work with leap seconds much. 🤷 

As far as 4.3 release is concerned, this patch LGTM.

**Comment by pllim** [comment]
The backport bot did not open a new PR from the label!

**Comment by mhvk** [comment]
Belatedly, to me it seems easiest to just always update in main as well. Ideally, this gets done just before branching, which would then be "good enough".

**Comment by Carreau** [comment]
One of the comiter can try to mention the bot like so:

@meeseeksdev backport to v4.3.x

It will not do it with me as I'm not a committer, but if one of you say that it will backport.

I _should_ have fix the label backport issue – or at least added a workaround.

**Pull request merged**
