### PR TITLE
Update WCSLIB to version 7.2

### PR DESCRIPTION
**Pull request by mcara**
This PR updates WCSLIB to version 7.2. For a complete list of changes, see https://www.atnf.csiro.au/people/mcalabre/WCS/CHANGES. This release includes the temporary fix implemented in https://github.com/astropy/astropy/pull/9845 and thus it replaces that fix.

CC: @MSeifert04 @nden @pllim 

Fixes https://github.com/astropy/astropy/issues/9846

### CODE REVIEW

**Comment by pllim** [comment]
#9845 was milestoned for 4.1 but #9846 for 4.0.2, so I am not sure what to milestone this to. I'll defer to others.

**Comment by nden** [comment]
This is a bug fix release which replaces the custom patch we have in wcslib so I think it should got in 4.0.1. @bsipocz feel free to change the milestone if you disagree.

**Comment by nden** [comment]
The current, v4.0.0 release, has wcslib 7.1.

**Comment by mcara** [comment]
@nden How? https://github.com/astropy/astropy/pull/9829

**Comment by nden** [comment]
@mcara Please update the version string in `wcs/setup_package.py`.

**Comment by bsipocz** [comment]
4.0.1 looks fine assuming it doesn't cause any API changes compared to 4.0 (my understanding that 7.1 didn't cause any, thus it could end up in 4.0.1).

**Comment by mcara** [comment]
@nden - done. @bsipocz v7.2 does not have any API changes compared to v7.1

**Comment by pllim** [comment]
It is unrelated. Merging then. Thank you!

**Pull request merged**
