### PR TITLE
Manual Backport for PR 11700 and PR 11712

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address half of #11857 .

Manual backport of both #11700 and #11712 (they go together).

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will
review this pull request of some common things to look for. This list
is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] If the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
(Force push to skip basebranch check.)

**Review by mhvk — APPROVED** [review]
Looks good and tests seem to pass (the failure is unrelated, and seems more like a rounding problem - the only question there is why it was not noticed before!?)

**Comment by mhvk** [comment]
@pllim - I presume we should just merge, but leaving that to you in case that's not the right procedure...

**Comment by pllim** [comment]
If you agree that this is the correct patch to backport, then I don't see why it shouldn't be merged. 🤷

**Comment by mhvk** [comment]
OK, done! Thanks!!!

**Pull request merged**
