### PR TITLE
change votable output() to use utf-8 to address #6836

### LINKED ISSUE #6836: UnicodeDecodeError Saving votables from astroquery searches
I am encountering `UnicodeDecodeError`s while attempting to write `astroquery` results to votables. An example query which fails upon trying to save to votable format is:

```
from astroquery.alma import Alma
import astropy.units as u
res = Alma.query_object('PKS1830-211', 1 * u.arcmin)
res.write('PKS1830-211.xml', format='votable')
```

The resulting error is:
```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-7-1afec7db28b5> in <module>()
----> 1 res.write('PKS1830-211.xml', format='votable')

/usr/lib/python3.6/site-packages/astropy/table/table.py in write(self, *args, **kwargs)
   2548         passed through to the underlying data reader (e.g. `~astropy.io.ascii.write`).
   2549         """
-> 2550         io_registry.write(self, *args, **kwargs)
   2551
   2552     def copy(self, copy_data=True):

/usr/lib/python3.6/site-packages/astropy/io/registry.py in write(data, *args, **kwargs)
    579
    580     writer = get_writer(format, data.__class__)
--> 581     writer(data, *args, **kwargs)
    582
    583

/usr/lib/python3.6/site-packages/astropy/io/votable/connect.py in write_table_votable(input, output, table_id, overwrite, tabledata_format)
    160
    161     # Write out file
--> 162     table_file.to_xml(output, tabledata_format=tabledata_format)
    163
    164

/usr/lib/python3.6/site-packages/astropy/io/votable/tree.py in to_xml(self, fd, compressed, tabledata_format, _debug_python_based_parser, _astropy_version)
   3484                 for element_set in element_sets:
   3485                     for element in element_set:
-> 3486                         element.to_xml(w, **kwargs)
   3487
   3488     def iter_tables(self):

/usr/lib/python3.6/site-packages/astropy/io/votable/tree.py in to_xml(self, w, **kwargs)
   3176                                 self.resources):
   3177                 for element in element_set:
-> 3178                     element.to_xml(w, **kwargs)
   3179
   3180     def iter_tables(self):

/usr/lib/python3.6/site-packages/astropy/io/votable/tree.py in to_xml(self, w, **kwargs)
   2753                 with w.tag('DATA'):
   2754                     if format == 'tabledata':
-> 2755                         self._write_tabledata(w, **kwargs)
   2756                     elif format == 'binary':
   2757                         self._write_binary(1, w, **kwargs)

/usr/lib/python3.6/site-packages/astropy/io/votable/tree.py in _write_tabledata(self, w, **kwargs)
   2778                 tablewriter.write_tabledata(
   2779                     w.write, array.data, array.mask, fields,
-> 2780                     supports_empty_values, indent, 1 << 8)
   2781             else:
   2782                 write = w.write

/usr/lib/python3.6/site-packages/astropy/io/votable/converters.py in output(self, value, mask)
    354             return ''
    355         if not isinstance(value, str):
--> 356             value = value.decode('ascii')
    357         return xml_escape_cdata(value)
    358

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 211: ordinal not in range(128)
```

A temporary workaround for me has been to exit `votable/converters.py` to all decode to `utf-8` instead of `ascii`, but I am not sure this is a robust fix. I saw there were some other issues relating to UnicodeDecodeErrors, but not seemed to specifically address this. But if I've missed a known fix or workaround, please let me know.

My software versions are:
* python: 3.6.3
* astropy: 2.0.2
* numpy: 1.13.3

### PR DESCRIPTION
**Pull request by privong**
EDIT: Fix #6836

### CODE REVIEW

**Comment by bsipocz** [comment]
@pllim - are you happy with fixing this in core, or would rather do it in downstream applications?

**Comment by pllim** [comment]
I am nervous about this change. This was added way back in #146 by @mdboom, so I am not familiar with the original intend. There is another `encode('ascii')` in the code right above this one, which is now inconsistent.

Also, some of the failures in https://travis-ci.org/astropy/astropy/jobs/301736761 seems related. I restarted the other failed one but I expect to see the same failures.

**Comment by pllim** [comment]
Side note: It is generally not recommended that you put your patch in your own `master` branch. FYI.

**Comment by pllim** [comment]
UPDATE: The local tests didn't pick up anything, so I need to understand why `vo_tests` fail only on Numpy dev (restarted it, just in case). I also need to dig into the VO standards and see if they address anything on special characters.

**Comment by pllim** [comment]
Looking at the VOTable standards at http://www.ivoa.net/documents/VOTable/20130920/REC-VOTable-1.3-20130920.pdf (Section 2.1), "char" datatype handles ASCII, while "unicodeChar" handles Unicode.

Therefore, if I interpreted the standards correctly, the change here is incorrect because you are forcing `Char` class to behave like "unicodeChar", not "char".

What is the equivalent search of this over at http://almascience.nrao.edu/aq/ ? (I have never done a search there before.) I would like to see the "raw" output from their service before deciding what to do next.

**Comment by bsipocz** [comment]
I would also bring @keflavich to this discussion as he is fairly familiar with the alma api

**Comment by privong** [comment]
@pllim Okay, thanks for the tip on patches.

**Comment by pllim** [comment]
Based on my findings at https://github.com/astropy/astropy/pull/6846#issuecomment-344372845 , I am closing this pull request. Feel free to re-open should you wish to re-visit this. I still think this is best addressed downstream but I may be convinced otherwise if there are some good reasons to fix this here. Thank you!

**Pull request closed without merging**
