### PR TITLE
Deprecate `coordinates.matrix_utilities.matrix_product()`

### PR DESCRIPTION
**Pull request by eerovaher**
### Description

`matrix_product()` was meant to improve readability of long matrix products, but is not needed anymore because Python 3.5 implemented [PEP 465](https://peps.python.org/pep-0465/). See also the docstring of the deprecated function.

~~`coordinates.matrix_utilities` is not a part of the public API, so the function can be removed immediately without deprecating it first.~~
EDIT: It looks like it is better to deprecate the function before removing it.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by Cadair** [comment]
SunPy was still using this (https://github.com/sunpy/sunpy/pull/6376) so I would rather we deprecate it. Other than that :+1: on eventually getting rid of it.

**Comment by astrofrog** [comment]
I think this is a good reminder that we should probably anything that is not preceded by a ``_`` as being 'public API' as opposed to relying on what is in the API docs (as many people might just discover functionality via 'tab' rather than docs).

**Comment by mhvk** [comment]
:+1:, but indeed looks like we should deprecate. I'd guess that here the usage is really from just adjusting astropy's own coordinate transformation code in sunpy's context -- a leading `_` would be very unlikely to have made a difference.

Should deprecation ideally be starting at the next LTS?

**Comment by WilliamJamieson** [comment]
I agree, this should be depreciated.

**Comment by eerovaher** [comment]
I have deprecated the function instead of removing it. The introduction of the function was not recorded in the change log, so I don't see why the deprecation would have to be announced there either.

I have rebased the pull request to incorporate the newly merged patch that prevents the tests with `matplotlib` development version from failing.

> Should deprecation ideally be starting at the next LTS?

@mhvk, what would be the advantage of delaying the deprecation until the next LTS version?

**Comment by mhvk** [comment]
@eerovaher - actually, I think I as wrong on deprecating on next LTS. The general idea is that, typically, downstream projects will need to support LTS up to current, so if one deprecates something like a keyword argument that means they will have to perhaps make switches depending on astropy version, which we should avoid. If one deprecates at an LTS, and then removes one version later, one avoids this problem.  But it is really important only for explicit API (like the `clobber` keyword argument that triggered this thinking), not for a semi-hidden function like `matrix_product`.

**Comment by mhvk** [comment]
OK, looks all good now. I briefly wondered about a changelog entry, but since this was an undocumented function, I think it is not needed. So, merging!

**Pull request merged**
