### PR TITLE
MNT: matplotlib 3.4.0 broke plot_obs-planning.py

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address broken RTD builds caused by `matplotlib` 3.4.0 release last night.

```
WARNING: .../examples/coordinates/plot_obs-planning.py failed to execute correctly: Traceback (most recent call last):
  File ".../sphinx_gallery/scrapers.py", line 333, in save_figures
    rst = scraper(block, block_vars, gallery_conf)
  File ".../sphinx_gallery/scrapers.py", line 149, in matplotlib_scraper
    fig.savefig(image_path, **these_kwargs)
  File ".../matplotlib/figure.py", line 2959, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File ".../matplotlib/backend_bases.py", line 2255, in print_figure
    result = print_method(
  File ".../matplotlib/backend_bases.py", line 1669, in wrapper
    return func(*args, **kwargs)
  File ".../matplotlib/backends/backend_agg.py", line 508, in print_png
    FigureCanvasAgg.draw(self)
  File ".../matplotlib/backends/backend_agg.py", line 406, in draw
    self.figure.draw(self.renderer)
  File ".../matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File ".../matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File ".../matplotlib/figure.py", line 2734, in draw
    mimage._draw_list_compositing_images(
  File ".../matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File ".../matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File ".../matplotlib/_api/deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File ".../matplotlib/axes/_base.py", line 2925, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File ".../matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File ".../matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File ".../matplotlib/legend.py", line 614, in draw
    self._legend_box.draw(renderer)
  File ".../matplotlib/offsetbox.py", line 368, in draw
    c.draw(renderer)
  File ".../matplotlib/offsetbox.py", line 368, in draw
    c.draw(renderer)
  File ".../matplotlib/offsetbox.py", line 368, in draw
    c.draw(renderer)
  [Previous line repeated 1 more time]
  File ".../matplotlib/offsetbox.py", line 694, in draw
    c.draw(renderer)
  File ".../matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File ".../matplotlib/collections.py", line 1009, in draw
    super().draw(renderer)
  File ".../matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File ".../matplotlib/collections.py", line 380, in draw
    len(facecolors) == 1 and len(edgecolors) == 1 and
TypeError: object of type 'NoneType' has no len()
```

I opened bug report upstream at matplotlib/matplotlib#19779 . @eteq , pretty sure 4.2.1 release will be affected and probably 4.0.5 too. I tentatively milestoning to 4.0.6 for now, but feel free to move milestone as needed.

### CODE REVIEW

**Comment by pllim** [comment]
This did fix RTD. You can ignore the codecov complain.

**Review by saimn — APPROVED** [review]
We should probably remove the pinning for `all` when a bugfix release of matplotlib is available, since astropy itself is not incompatible with matplotlib 3.4, it's only a problem with the docs build. But for now since the readthedocs config uses `all` it's the best way to solve the failures on RTD.

**Comment by tacaswell** [comment]
I expect there to be a mpl 3.4.1 very soon (there is also a show-stopping bug in axes3D), I think pinning `'!=3.4.0'` in 'all' is sensible.

**Comment by pllim** [comment]
Thanks for the update, @tacaswell ! I see that matplotlib/matplotlib#19816 was merged. I'll have to be sure we pick up 3.4.1 when it comes out.

**Pull request merged**
