### PR TITLE
BUG: declare private str ufuncs as unsupported (np._core.umath._expandtabs*)

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
Quick follow up to #15699

xref https://github.com/numpy/numpy/pull/25891

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Thanks! This looks good. Note that there are more to come...

**Comment by neutrinoceros** [comment]
> Note that there are more to come...

One byte at a time 😄

**Comment by mhvk** [comment]
I've merged this despite the`-dev` job not passing since this is quite obviously correct, and we know where the trouble is with `-dev`.

**Comment by neutrinoceros** [comment]
@mhvk I think you forgot the backport label. I'll do it manually.

**Comment by pllim** [comment]
Is there a follow-up issue for the current numpy-dev failure?

```
astropy/units/quantity.py:829: in _new_view
    obj = np.array(obj, copy=False, subok=True)
E   ValueError: Unable to avoid copy while creating an array.
```

**Comment by neutrinoceros** [comment]
yeah, I naively thought the patch would be trivial so I didn't open an issue for it. Now that the situation is clearer, I'm planning to open a long term issue for what's next !

**Pull request merged**
