### PR TITLE
Backport PR #11787 on branch v4.3.x (Fix MaskedInfo class so table operations work)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #11787: Fix MaskedInfo class so table operations work

### CODE REVIEW

**Comment by saimn** [comment]
@pllim - It seems we need a few more adjustments before backporting PRs:
- The " Mandatory checks before CI " job is failing because the PR is opened against v4.3.x, we should find a solution for this. 
- I guess we should backport first the PR to pin Sphinx until we have a better solution ?
- The wheel jobs are running on every commit, which was useful I guess when a bunch of backports were pushed together but may not be the best option now.

**Comment by pllim** [comment]
Ugh, why didn't the label work? Can the bot auto-add `skip-basebranch-check` label on open?

**Comment by pllim** [comment]
Re: pin Sphinx -- yes, we should unless @astrojuanlu has updates.

Re: wheels -- I dunno, that is the turf of @astrofrog and @Cadair . I don't have access to the Azure Pipelines.

**Comment by astrojuanlu** [comment]
Yep, unfortunately we'll still have to pin Sphinx, sphinx-automodapi still gives a warning with Sphinx>4 https://github.com/astropy/sphinx-automodapi/issues/130 (investigation ongoing)

**Comment by pllim** [comment]
Let's wait a bit... If we can't get the bot to auto apply labels, I might have to revert the basebranch check from production.

**Comment by pllim** [comment]
I am going to try a slightly different workflow on this backport, so I am closing this without merge.

**Pull request closed without merging**
