### PR TITLE
Fix example in astropy.table.unique docstring

### PR DESCRIPTION
**Pull request by evertrol**
Related: https://stackoverflow.com/questions/47402881/astropy-table-unique-not-working

### CODE REVIEW

**Comment by astrofrog** [comment]
The bigger question here is why this wasn't caught by the test suite? The doctests should be run (unless that is broken...)

**Comment by saimn** [comment]
Because `unique` is defined in this file I guess.

**Comment by astrofrog** [comment]
Yeah, it must be that. Ok, well let's leave that as a 'thing that needs to be improved in doctest in future'

**Comment by evertrol** [comment]
Indeed: `unique` is already in the namespace of the doctest.
Though a quick browse through the pytest documentation and a general search didn't show me a way to explicitly handle this; hence only the documentation fix.

**Comment by bsipocz** [comment]
We run into this very recently in #6746. Doing a quick search then showed that we have quite many docstrings where the examples are not full standalone examples, but really build on the fact that everything in that given files namespace is already been available.
There need to be an issue opened as a reminder if we want to change them, and also would need a hack probably in pytest-doctestplus that somehow will run the docstrings separately.

**Comment by bsipocz** [comment]
Otherwise, this is being approved and trivial, so I'm merging now.

**Pull request merged**
