### PR TITLE
BOT: Fix author check logic for labeling bot

### LINKED ISSUE #12054: BUG: label bot still buggy
It is supposed to ignore backport bot but it is not. The author check must not be working as expected. Need to investigate more. See #12053 for proof of bad behavior.

https://github.com/astropy/astropy/blob/ace7db5e9bacc9ce98fb74ab6c7190f46ab4b241/.github/workflows/open_actions.yml#L17

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is a direct follow-up of #12004 . That PR made the wrong assumption that PR event would have `issue` entry, since GitHub treats PR event as subclass of issue event in most cases. This PR corrects that logic.

p.s. No proof until this is merged and the backport bot runs after.

Fixes #12054

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by nstarman** [comment]
Good diagnosis (if it works :p). I'm not seeing anything in the GH Actions API about this. Their docs definitely need an improved gallery of good examples.

**Comment by pllim** [comment]
I inspected the event context in another repo, so this will definitely give you the PR author username. But we will never know for sure until it is in production. 😬

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
This looks good, and with the note above should be merged to be sure about it.

**Comment by pllim** [comment]
Ugh... It just occurred to me that the backport PRs run workflows defined in the old branches, so we actually need to backport this for it to work. Doh! 🤦

**Comment by pllim** [comment]
I added 01e82b6 to v4.3.x (I guess it qualifies as manual backport...). There is no label bot in v4.0.x branch.

**Pull request merged**
