### PR TITLE
EXP: Run test suite with dev pytest-doctestplus

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to see if astropy/pytest-doctestplus#174 broke anything here.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by lpsinger** [comment]
Why not permanently add this to devdeps?

**Comment by pllim** [comment]
I guess we could... Will add it to infrastructure agenda.

**Comment by pllim** [comment]
Failure looks related. But what do we do?

```
______________________________ [doctest] arctan2 _______________________________
EXAMPLE LOCATION UNKNOWN, not showing all tests of that example
??? >>> np.arctan2([0., 0., np.inf], [+0., -0., np.inf])
Expected:
    array([ 0.        ,  3.14159265,  0.78539816])
Got:
    array([0.        , 3.14159265, 0.78539816])

.../astropy/units/quantity_helper/helpers.py:None: DocTestFailure
```

**Comment by lpsinger** [comment]
The failing doctest is [in Numpy itself, here](https://github.com/numpy/numpy/blob/main/numpy/core/code_generators/ufunc_docstrings.py#L514-L515). This is proof that we are now locating tests in ufunc! 🤣 

The question is, why is pytest discovering tests in Numpy?

**Comment by lpsinger** [comment]
#12858 should fix this.

**Comment by lpsinger** [comment]
Hmm, there are several Astropy modules that have `from scipy.special import ...` in them.

**Comment by lpsinger** [comment]
But `astropy.cosmology.flrw` is the only module in which the import is at global rather than function scope.

**Comment by pllim** [comment]
So having this new pytest-doctestplus plugin means we have to be real careful of imports? I think this should be documented in the dev docs then. When to import globally and when not to.

**Comment by mhvk** [comment]
@lpsinger - the fact that most imports are local is almost certainly because scipy is not (yet) a required dependency for most of astropy. But for cosmology it is, hence the imports on top.

I'm starting to wonder a bit if the gain is worth the pain... Maybe after all there should be a switch on doctestplus to turn off ufunc doc tests?  Of course, really the ufuncs should expose the module they are defined in!

**Comment by lpsinger** [comment]
OK, try #12861 and astropy/pytest-doctestplus#175.

**Comment by saimn** [comment]
> I'm starting to wonder a bit if the gain is worth the pain... Maybe after all there should be a switch on doctestplus to turn off ufunc doc tests? Of course, really the ufuncs should expose the module they are defined in!

Agreed. And instead of having to have `__doctest_skip__` in every module where some ufunc is imported, we should probably do the opposite, i.e. define a `__doctest_ufunc__` that would allow to activate doctesting ufuncs on a case by case basis ?

**Comment by lpsinger** [comment]
> > I'm starting to wonder a bit if the gain is worth the pain... Maybe after all there should be a switch on doctestplus to turn off ufunc doc tests? Of course, really the ufuncs should expose the module they are defined in!
> 
> Agreed. And instead of having to have `__doctest_skip__` in every module where some ufunc is imported, we should probably do the opposite, i.e. define a `__doctest_ufunc__` that would allow to activate doctesting ufuncs on a case by case basis ?

Or we could make the ufunc doctest discovery an opt-in using a `--doctest-ufunc` option to pytest-doctestplus, which was in my original draft.

**Comment by saimn** [comment]
Yes, so at least now we found the drawback of activating it by default ;). The problem with the global switch is that we would face the same issue if we want to use it in Astropy. So, since ufunc can be doctested only if imported in another module (I think ?), maybe a module level directive (e.g. `__doctest_ufunc__`) is a better approach ?

**Comment by lpsinger** [comment]
I agree; I like `--doctest-ufunc`. My original application is in a coordinated package with _lots_ of ufuncs, so I'd rather not list them all out explicitly in `__doctest_ufunc__`. I'll add the `--doctest-ufunc` option back to this PR.

**Comment by pllim** [comment]
Rebased and dropped the cherry-picks. 🤞

**Comment by nstarman** [comment]
21/21 = 💯    🎉

**Comment by pllim** [comment]
For those interested:

* #13080

**Pull request closed without merging**
