### PR TITLE
Apply `black` to `astropy.io.fits`

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

Apply `black` to `astropy.io.fits` according to the process laid out by [APE 20](https://github.com/astropy/astropy-APEs/blob/main/APE20.rst).

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by saimn** [comment]
@WilliamJamieson - This is now ready for string normalization, thanks.

**Comment by WilliamJamieson** [comment]
@saimn it looks like after string normalization there is a couple of places where there are now `"foo " "bar"` like strings. `--preview` suggests some changes that will fix those and a few other things, but it suggests other changes that you appear to have undone. I suggest you review glance through the normalization changes and see if there is anything left that you want to change/fix, before I squash it.

**Comment by WilliamJamieson** [comment]
> @saimn it looks like after string normalization there is a couple of places where there are now `"foo " "bar"` like strings. `--preview` suggests some changes that will fix those and a few other things, but it suggests other changes that you appear to have undone. I suggest you review glance through the normalization changes and see if there is anything left that you want to change/fix, before I squash it.

If this PR is ready to move forward please move it to the "Ready for Squash" column in https://github.com/orgs/astropy/projects/10.

**Comment by saimn** [comment]
Hmm it seems `--preview` mostly changes simple quote strings to double quote ones with escaping, e.g.
```
-            '"ascii.fixed_width" (can be "ascii.csv", '
-            '"ascii.html", "ascii.latex", "fits", etc)'
+            "\"ascii.fixed_width\" (can be \"ascii.csv\", "
+            "\"ascii.html\", \"ascii.latex\", \"fits\", etc)"
```
which is not great ... so I guess we will skip the second pass with `--preview`. I did the concatenation manually for the cases where that was possible, so I think it's OK now.

**Comment by astrofrog** [comment]
@saimn - are you happy with this?

**Comment by saimn** [comment]
@astrofrog - Yes, the PR is ready.

**Review by saimn — APPROVED** [review]

**Pull request merged**
