### PR TITLE
2.0.x: Add support for matmul as a ufunc (new in numpy 1.16).

### PR DESCRIPTION
**Pull request by mhvk**
Backport of #8264

### CODE REVIEW

**Comment by pllim** [comment]
CircleCI failure seems unrelated:

* Error parsing config file: yaml: unknown anchor 'apt-install' referenced
* Cannot find a job named `build` to run in the `jobs:` section of your configuration file.
If you expected a workflow to run, check your config contains a top-level key called 'workflows:'

@astrofrog ?

**Comment by mhvk** [comment]
Tests are stalling here too... #8033 may need a backport after all...

**Comment by mhvk** [comment]
It doesn't look like the `numpy-dev` travis run actually did anything - not sure why.

**Comment by pllim** [comment]
> not sure why.

The one that passed was a false positive (a cron job). The actual numpy dev job failed, as expected.

**Comment by mhvk** [comment]
Would seem good to check that all tests in fact pass... Happy to rebase once #8308 is in and backported.

**Comment by pllim** [comment]
Test result from `master` (https://travis-ci.org/astropy/astropy/builds/471015933) is looking good! I am confident that after the backport stuff is done for IERS_A_URL_MIRROR, this would pass beautifully. 🦄

**Comment by pllim** [comment]
The failure looks familiar. I think it went away after someone restarted the build for that other PR. @astrofrog

**Comment by bsipocz** [comment]
There are several issues with the circleCI builds, but totally unrelated to this PR. So I would rather go ahead and merge this, and fix the issues separately.

**Comment by bsipocz** [comment]
Thank you @mhvk!

**Comment by mhvk** [comment]
Thanks, @bsipocz, indeed best to keep concerns separate.

**Pull request merged**
