### PR TITLE
add public modules to use direct import first stage like 'import astr…

### PR DESCRIPTION
**Pull request by celik-muhammed**
… 'import astropy.stats as st'

### Description

This pull request is to address ...

Fixes #<Issue Number>

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Hi ! Could you explain your motivation for this change ? Unfortunately, exposing more public API paths comes with a very high maintenance cost so I must say it's unlikely we'd accept it. Maybe we could offer a better solution if you told us what the problem was ?

**Comment by celik-muhammed** [comment]
Thanks for explanation, 
for new users for this lib like me try to use sample stats lib via 'import astropy.stats as st'.
documentation also define use 'from astropy import stats' but ı think this import style just suggest.

**Review by pllim — CHANGES_REQUESTED** [review]
Hello. Unfortunately I do not understand what this is actually trying to solve. Even without this patch, `import astropy.stats as st` already works.

**Comment by celik-muhammed** [comment]
Yes, it works without this patch; I checked it.

In my specific scenario, where the internet is not available for some time, 
I need the stats library for searching. I have an older version 6.1.6 installed, so I tried:

import astropy
dir(astropy)

The stats module is not present, so I assume it was added in a later version. 
Currently, I haven’t checked other versions or the online documentation.

I want to emphasize that when working offline, having the available submodules listed in the result of the dir function or including them in the docstring would be much more useful.

**Comment by pllim** [comment]
I see. Thank you for bringing this to our attention, I agree that the top level namespace could be cleaned up. I have opened https://github.com/astropy/astropy/issues/17589 as a follow-up issue for discussion and we can always revisit this PR in the future once consensus is reached. Thanks again!

**Pull request closed without merging**
