### PR TITLE
update integer type in cython lombscargle to prevent compiler warnings

### PR DESCRIPTION
**Pull request by jakevdp**
Responding to #4904

### CODE REVIEW

**Comment by jakevdp** [comment]
The appveyor error seems to be unrelated to this PR: it's some kind of DLL load error in any test that requires importing scipy.

**Comment by MSeifert04** [comment]
I think the failure is because conda "released" mkl 11.3.3.  Some local testing showed that mkl 11.3.1 (most recent mkl version for windows until yesterday) works but 11.3.3 cannot load some dlls needed for scipy, no idea if that's an mkl problem or problem of the related new numpy/scipy builds.

Thank you for the quick response to the issue. :+1: I hope @astrofrog or @eteq (or someone else) knows how to proceed with this AppVeyor problem.

**Comment by bsipocz** [comment]
Too bad that we don't have any machinery to limit versions in appveyor (unlike for travis).

**Comment by bsipocz** [comment]
Anyway, I see two ways to work around this:
 - manually we can add mkl v11.3.1 to the ``CONDA_DEPENDENCIES``
 - or hardwire the usual ``conda install nomkl`` for the appveyor installs in ci-helpers.

@astrofrog @eteq which one do you prefer? I can open a PR for either of them asap.

**Comment by MSeifert04** [comment]
Why not put a `mkl=11.3.1` in Conda dependencies and add another allowed-failure build without specifying mkl. So we immediatly see when the most recent mkl works but don't let it fail the tests?

**Comment by bsipocz** [comment]
Definitely :-1: on adding another build as it is only a waste of CI resources and recreates a bottleneck of day long queues on appveyor. Since some affiliates also depends on scipy, I'm more inclined towards the second option, but would need comments before merging any such changes in ci-helpers.

**Comment by MSeifert04** [comment]
what about poking the guys from the responsible package? It's either mkl, scipy or conda/anaconda? Maybe they know how to fix it upstream.

**Comment by mhvk** [comment]
@MSeifert04 - is it possible to test for you whether this PR resolves the issues you have with current master? If so, I think we could go ahead and merge -- the appveyor discussion is somewhat orthogonal to the purpose of this PR...

**Comment by MSeifert04** [comment]
@mhvk Sorry. 

The compiler warnings about precision loss are gone but I can't check if the tests pass, I have some problems downgrading mkl locally :smile:

**Comment by jakevdp** [comment]
I've found the conda team to be pretty responsive to this kind of issue in the past, for what it's worth.

**Comment by bsipocz** [comment]
Yes, there is an issue for it already ContinuumIO/anaconda-issues#792
We were just unlucky that their version upgrade happened on the same day as the feature freeze.

**Comment by mwcraig** [comment]
I'd go with the `nomkl` option for now to get the appveyor builds running again.

**Comment by bsipocz** [comment]
@mwcraig - Sadly ``nomkl`` doesn't exist for windows, so I had to hardwired the 11.3.1 version number into ``ci-helpers`` for now, and watch out for the conda issue to see when it gets fixed upstream.

**Comment by bsipocz** [comment]
Also, restarted a couple of PRs on appveyor, including this one.

**Comment by mhvk** [comment]
OK, this now seems all fine, so merging! Thanks @jakevdp and @bsipocz!

**Pull request merged**
