### PR TITLE
Fix Ruff PIE790 (extraneous pass statement) in nddata

### PR DESCRIPTION
**Pull request by hfcpeixoto**
This pull request is to address violations to Ruff's rule **PIE790**, which is listed explicitly in issue https://github.com/astropy/astropy/issues/14818. Only submodule `nddata` is addressed.

This is part of a series of PRs split from https://github.com/astropy/astropy/pull/15239, following suggestions by @nstarman.

Solves part of #14818.

### CODE REVIEW

**Comment by eerovaher** [comment]
@hfcpeixoto, you have addressed quite a few of the Ruff rules listed in #14818 as suitable for first-time contributors, so you should already be familiar with our workflow and the tools we use. I suggest you consider addressing some of the more challenging Ruff rules now, particularly those that Ruff cannot automatically fix.

**Comment by nstarman** [comment]
😆. A good suggestion @eerovaher. We of course appreciate any PRs that improve astropy, but yes tackling hard problems is a great benefit.

**Comment by hfcpeixoto** [comment]
Do you folks suggest any rule in particular? Maybe even another issue not related to ruff's violations.

**Comment by nstarman** [comment]
Perhaps a good starting set of issues are the  flake8-datetimez (DTZ) codes in Ruff. We've been putting off fixing the timezone issues, but it's important to get it fixed before the next few Python releases.

**Review by nstarman — APPROVED** [review]
Thanks @hfcpeixoto!
Ping @mwcraig if you want to take a look.

**Review by mwcraig — APPROVED** [review]

**Comment by pllim** [comment]
p.s. How do you tell if a PR was merged using "create a merge commit" or "squash and merge"? I cannot tell from the GitHub history for a PR. It always say "someone merged commit some-hash into astropy:main".

**Comment by nstarman** [comment]
> p.s. How do you tell if a PR was merged using "create a merge commit" or "squash and merge"? I cannot tell from the GitHub history for a PR. It always say "someone merged commit some-hash into astropy:main".

I don't know of a reliable way. Graphical renders of the branches generally shows if commits within a branch end up in `main`, but that's all visual inspection.

**Comment by nstarman** [comment]
GH should record the merge type on this PR page! That would be nice.

**Comment by pllim** [comment]
Re: GH -- OK, I asked at https://github.com/orgs/community/discussions/66139 🤞

**Comment by hfcpeixoto** [comment]
> Perhaps a good starting set of issues are the flake8-datetimez (DTZ) codes in Ruff. We've been putting off fixing the timezone issues, but it's important to get it fixed before the next few Python releases.

Nice, I will give them a go. Thanks for the suggestion.

**Pull request merged**
