### PR TITLE
Added fix for #16245

### LINKED ISSUE #16245: Multi-threading issue in WCSLIB even if input data is copied
In https://github.com/astropy/astropy/issues/16244 I mentioned a multi-threading issue that is due to the input array being passed through to the WCS C extension and being subsequently modified in-place. There is however another issue that occurs even if the input data is copied, and is illustrated by the following example:

```python
import numpy as np
from astropy.wcs import WCS
from multiprocessing.pool import ThreadPool

wcs = WCS(naxis=2)
wcs.wcs.crpix = [-234.75, 8.3393]
wcs.wcs.cdelt = np.array([-0.066667, 0.066667])
wcs.wcs.crval = [0, -90]
wcs.wcs.ctype = ["RA---AIR", "DEC--AIR"]
wcs.wcs.set()

N = 1_000_000

pixel = np.random.randint(-1000, 1000, N * 2).reshape((N, 2)).astype(float)


def repeated_transforms(pixel):
    world = wcs.wcs.p2s(pixel.copy(), 1)['world']
    wcs.wcs.lng  # this access causes issues, without it all works
    pixel = wcs.wcs.s2p(world, 1)['pixcrd']
    return pixel


pool = ThreadPool(8)
results = pool.map(repeated_transforms, (pixel,) * 8)

for pixel2 in results:
    print(
        f"Mismatching elements: {np.sum(~np.isclose(pixel, pixel2))}"
    )
```

In this case I am using ``p2s`` and ``s2p`` but the issue can be seen also with ``wcs_pix2world`` and ``wcs_world2pix`` – the reason for using ``p2s`` and ``s2p`` directly is just to try and simplify the problem as much as possible to use just calls to the WCS C extension. The above example gives:

```
Mismatching elements: 92
Mismatching elements: 102
Mismatching elements: 116
Mismatching elements: 70
Mismatching elements: 106
Mismatching elements: 48
Mismatching elements: 88
Mismatching elements: 96
```

One of the weird things is that the line just accessing:

```
wcs.wcs.lng
```

appears to be required to trigger this issue. Calling ``wcs.wcs.lat`` also works, but *not* for example ``wcs.wcs.equinox``.

@manodeep and I have been discussing this and he is investigating (but if anyone else has ideas feel free to chime in!)

### PR DESCRIPTION
**Pull request by manodeep**
### Description

This pull request fixes #16245 

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by manodeep** [comment]
Ideally the test python code (in #16245) should also be included with this fix.

**Comment by astrofrog** [comment]
This fix looks good but I can investigate the test failure tomorrow. Looks puzzling at first glance!

**Comment by astrofrog** [comment]
The failure is related, it seems to be related to the fact if e.g. crval is modified in place then flag doesn't get reset. I need to look more closely to understand why set() would change results in that case though.

**Comment by manodeep** [comment]
Huh - that's weird. `set_crval()` calls [`note_change()`](https://github.com/astropy/astropy/blob/main/astropy/wcs/src/wcslib_wrap.c#L2523), and the getter-setters are set to [`set_crval()`](https://github.com/astropy/astropy/blob/main/astropy/wcs/src/wcslib_wrap.c#L4037)

**Comment by astrofrog** [comment]
I think this specific example changes one element of the array in-place so I'm not sure if the setter gets called?

**Comment by manodeep** [comment]
Based on this [SO post](https://stackoverflow.com/questions/35783418/property-setter-for-a-single-list-element) (and a couple of others I read) seems that the setter does not get called if an element of the array is modified in-place. The only way that functionality could happen is through adding `__setitems__` for each "property" - which seems unnecessarily complex and overkill in this case. 

One option is to add the change back to `wcs_types()` - both locally within astropy and upstream (if Mark agrees)

**Comment by mcara** [comment]
In comments:

> Therefore, if `x.flag == WCSSET`, there is no need to call `wcsset()` and we can return immediately.

I really would like to know Mark's opinion on this. Why wasn't this check implemented in `wcsset()` itself as this function is quite expensive. I wonder whether there is a reason not to do it. Could someone reach out to Mark?

**Comment by manodeep** [comment]
> In comments:
> 
> > Therefore, if `x.flag == WCSSET`, there is no need to call `wcsset()` and we can return immediately.
> 
> I really would like to know Mark's opinion on this. Why wasn't this check implemented in `wcsset()` itself as this function is quite expensive. I wonder whether there is a reason not to do it. Could someone reach out to Mark (on this and the other - `wcs_types` issue)?

Yeah agreed. In an email with Tom and me, Mark said that such `if` conditions exist within other functions that call `wcsset`. However, he also said that `wcsset` can be called by other functions without setting `wcs->flag = 0`. Here's the relevant part of Mark's email from last night (responding to a broader query about visibility of the `WCSSET` symbol and the proposed fix):

```
On the face of it, if wcsset() looked at wcsprm::flag and returned early
if set (to WCSSET), I believe that would fix the problem.  However, I
can't do that because there may be applications that use wcsset() to do
force majeur resetting of the wcsprm struct (i.e. without setting
wcsprm::flag = 0) - indeed, such code exists within WCSLIB.

There are also many instances within WCSLIB code of the following:

  if (wcs->flag != WCSSET) {
    if ((status = wcsset(wcs))) return status;
  }

which is pretty much what you want.  However, rather than expose WCSSET
(and the others), I think it may be better to provide an enquiry
function, wcsisset(), which just returns wcs->flag == WCSSET.  Would
that do the trick for you?  Alternatively, just testing wcsprm::flag
for a non-zero value should be quite reliable.
```

Moving the fix to `wcs_types()` would solve the immediate issue but would still (potentially) leave other memory race issues for the various `lin/prj/` etc structs within `struct wcsprm`.

**Comment by mcara** [comment]
BTW, the unit test that's failing, `test_get_coord_range_nan_regression`, is an example of a bad way of setting CRVAL.

**Comment by manodeep** [comment]
> BTW, the unit test that's failing, `test_get_coord_range_nan_regression`, is an example of a bad way of setting CRVAL.

That's good to know! I do not have the context to know that :)

**Comment by mcara** [comment]
context is exactly the same as in https://github.com/astropy/astropy/pull/16279#issuecomment-2043541877: "setter does not get called if an element of the array is modified in-place". This was brought up numerous times in the past although I cannot find past discussions.

Related to the failing test, I am not sure that changing

```python
wcs.wcs.crval[0] = 0
```

to 

```python
wcs.wcs.crval[0] = 0
wcs.wcs.set()
```
OR
```python
wcs.wcs.crval = [0, *wcs.wcs.crval[1:]]
```

would solve the failure.

**Comment by mcara** [comment]
Probably if this PR is merged, something like this will not work:

```python
w = WCS()
w.wcs.ctype = ['RA---TAN', 'DEC--TAN']
w.wcs.ctype[1] = 'GLON--TAN'
w.wcs.ctype[0] = 'GLAT--TAN'
assert w.wcs.lattyp == 'GLAT'
```
Now one will have to call `w.wcs.set()` before `assert` for this to work.

**Comment by manodeep** [comment]
> context is exactly the same as in [#16279 (comment)](https://github.com/astropy/astropy/pull/16279#issuecomment-2043541877): "setter does not get called if an element of the array is modified in-place". This was brought up numerous times in the past although I cannot find past discussions.
> 
I meant I lacked the context for what would be considered reasonable user behaviour (and not the code context). 

> Probably if this PR is merged, something like this will not work:
> 
> ```python
> w = WCS()
> w.wcs.ctype = ['RA---TAN', 'DEC--TAN']
> w.wcs.ctype[1] = 'GLON--TAN'
> w.wcs.ctype[0] = 'GLAT--TAN'
> assert w.wcs.lattyp == 'GLAT'
> ```
> 
> Now one will have to call `w.wcs.set()` before `assert` for this to work.

This PR should not be merged at this stage. We need to develop a better fix that allows the user to update individual items.

**Comment by manodeep** [comment]
After some digging around, I see that [these lines](https://github.com/astropy/astropy/blob/main/cextern/wcslib/C/wcs.h#L1137-L1162) within `wcslib` state that `wcs->flag` needs to be set to 0 whenever any of the named `wcsprm` members are modified.

```
*   int flag
*     (Given and returned) This flag must be set to zero whenever any of the
*     following wcsprm struct members are set or changed:
*
*       - wcsprm::naxis (q.v., not normally set by the user),
*       - wcsprm::crpix,
*       - wcsprm::pc,
*       - wcsprm::cdelt,
*       - wcsprm::crval,
*       - wcsprm::cunit,
*       - wcsprm::ctype,
*       - wcsprm::lonpole,
*       - wcsprm::latpole,
*       - wcsprm::restfrq,
*       - wcsprm::restwav,
*       - wcsprm::npv,
*       - wcsprm::pv,
*       - wcsprm::nps,
*       - wcsprm::ps,
*       - wcsprm::cd,
*       - wcsprm::crota,
*       - wcsprm::altlin,
*       - wcsprm::ntab,
*       - wcsprm::nwtb,
*       - wcsprm::tab,
*       - wcsprm::wtb.
```

Since the setters are not invoked when changing a single element, `wcs->flag` can't be reset to 0 with the existing call to `note_change()` from the setters. It seems to me that setting individual elements within these specified struct elements violates the software contract of `wcslib`. At the same time, there is no obvious/easy way of fixing the single-element change and resetting wcs->flag (outside of keeping an internal (deep?)copy of `wcs` and then comparing *all* the relevant fields).

**Comment by manodeep** [comment]
One way to detect whether any field has changed could be to store a hash value of the contents of the relevant fields (and ignoring memory addresses). If a change is detected, then `wcs->flag` could be reset to 0, and the fields would be reset/updated correctly.

Another option could be to allow user access to `wcs->flag`, where the user could manually update the flag to 0 after changing any relevant single element (but that puts the onus on the user to get the correct behaviour, something I tend to avoid doing as much as possible)

**Comment by astrofrog** [comment]
Another option on the astropy side might be to use a numpy array subclass to store the wcsprm elements so that we can correctly set the flag if individual items are set?

**Comment by manodeep** [comment]
Noting the reproducer here as well: https://gist.github.com/manodeep/23e5a2cc037752ce861bdb2998314137

**Comment by manodeep** [comment]
> Another option on the astropy side might be to use a numpy array subclass to store the wcsprm elements so that we can correctly set the flag if individual items are set?

That is beyond my python / astropy expertise.

**Comment by manodeep** [comment]
@astrofrog Based on the updates that Mark has done, I am not sure this fix is required any more. What do you think?

**Comment by astrofrog** [comment]
I think https://github.com/astropy/astropy/pull/16411 might be the correct fix now - that PR is still waiting for a bugfix WCSLIB release (have pinged Mark about it) but once that's done I think we will be able to merge that PR? I'll close this one.

**Pull request closed without merging**
