### PR TITLE
DOC: Fix `bounds` parameter documentation

### LINKED ISSUE #7492: Inconsistent documentation of `bounds` parameter in modeling classes
Currently to set `bounds` parameter in `Lorentz1D` class takes a dictionary with parameter name as key and min, max as _both_ tuple and list. But in docs, it is not mentioned clearly. The detail is also different in its base class. I have put the sections below:

screen shot 2018-05-23 at 23 23 13
**Description in `Lorentz1D1 doc page**

screen shot 2018-05-23 at 23 23 58
**Desctription in base class**

As @astrofrog suggested, it should be either `{parameter_name: (min, max)}` or `{parameter_name: value}`

@pllim suggested adding example(s) for the same in the documentation.

I would like to work on this.

**Note:** I used the parameter and it supports both tuple and list as value.

### PR DESCRIPTION
**Pull request by swapsha96**
Resolves #7492.

### CODE REVIEW

**Comment by pllim** [comment]
This was #7495 that was closed by accident, partly my bad.

**Comment by bsipocz** [comment]
I'm not sure what happened in #7495, but this one still need a rebase and squash given that now even unrelated commits are picked up.

**Comment by bsipocz** [comment]
@swapsha96 - If you need help with that, there is a git channel in the astropy slack, I can walk you though it.

**Comment by swapsha96** [comment]
@bsipocz I actually messed up during rebase and squash process which led to the closing of the previous PR (by mistake). @pllim agreed to help me out in squashing.

Looks like ci failed for some other reason:
screen shot 2018-05-30 at 01 28 37

**Comment by pllim** [comment]
OK done. @swapsha96 please have a look and see if I accidentally messed up your diff.

**Comment by swapsha96** [comment]
@pllim Looks good to me!

**Comment by pllim** [comment]
@nden and @crawfordsm , please see if the update examples make sense for your subpackage docs, respectively. Thanks!

**Comment by pllim** [comment]
Thanks everyone!

**Pull request merged**
