### PR TITLE
Allow un-setting aux WCS parameters

### LINKED ISSUE #11041: Allow in-place un-setting of WCS.wcs.aux
https://github.com/astropy/astropy/pull/10333 added support for auxiliary parameters on a WCS object, accessed by WCS.wcs.aux. However, once set these are currently immutable. It would be nice if they could be modified in place, which we have a use case for in sunpy. At the moment we have to convert a pre-existing WCS to a header, modify the aux fits keywords, and then create anew WCS.

### PR DESCRIPTION
**Pull request by mcara**
Fixes #11041

### CODE REVIEW

**Comment by pllim** [comment]
@astrofrog , what's up with the SAMP failures? I saw that in cron jobs too; thought they were transient but apparently not?

**Review by astrofrog — APPROVED** [review]
Looks good to me!

@mcara - can you rebase so that https://github.com/astropy/astropy/pull/11167 gets picked up and fixes the CI?

**Review by Cadair — COMMENTED** [review]
Thanks for the fix @mcara 🎉

**Comment by mcara** [comment]
Thanks for reviewing!

**Comment by mcara** [comment]
> Looks good to me!
> 
> @mcara - can you rebase so that #11167 gets picked up and fixes the CI?

@astrofrog I am sorry, I forgot about this!

**Comment by mcara** [comment]
I have absolutely no idea

**Pull request merged**
