### PR TITLE
use f-strings

### PR DESCRIPTION
**Pull request by ikamensh**
This PR changes most simple occurrences of older formatting styles to f-strings. It's derived by running a tool, `flynt astropy`.

I was not sure if this is within scope of CHANGES.rst.

Few stats:
```
Files modified:                            160
Character count reduction:                 10272 (0.10%)
F-string expressions created:              514
```

### CODE REVIEW

**Comment by taldcroft** [comment]
Thanks @ikamensh! This looks generally good, though we need to get at least one brave soul to scroll through all the changes and make sure they look reasonable.

I milestoned this for 4.3 so that it could be merged after the 4.2 feature freeze / branching. That will prevent merge conflict problems with PRs for 4.2.

**Comment by pllim** [comment]
I thought we already went through this in #8958 . I wonder why these weren't done back then.

**Comment by taldcroft** [comment]
I think the original update code used a very conservative strategy that misses these ones.

**Comment by ikamensh** [comment]
Many changes are multiline format statements - pyupgrade doesn't  change them.

**Review by pllim — CHANGES_REQUESTED** [review]
Need to undo the changes in `extern`. Those files are bundled.

**Comment by ikamensh** [comment]
reverted all changes to `astropy/extern/`

**Review by pllim — COMMENTED** [review]
Missed some in `samp/hub.py` (beyond "code suggestion" range) but given astropy/pyvo#239 , don't worry about it. `utils/timer.py` will be removed soon too, but since the changes are already made, might as well accept them.

I'll apply my own review and wrap this up. Thanks for your contribution!

**Review by pllim — APPROVED** [review]

**Pull request merged**
