### PR TITLE
Make AffineTransformation2D fittable

### PR DESCRIPTION
**Pull request by embray**
#2269 (yet to be merged) introduced a new `AffineTransformation2D` model.  It was suggested in that PR that it would be good to make instances of this class fittable.  Unfortunately this would _currently_ require making it a type of `ParametricModel`, which is currently broken for models that require multi-dimensional parameter values (such as the transformation matrix used by `AffineTransformation2D`).

Implementing this requires some combination of #2149 and/or #2276 to be merged first. So I decided to create a separate issue for this so that it isn't forgotten.

### CODE REVIEW

**Comment by astrofrog** [comment]
@embray - this will likely not be done in time for 1.0, is that right? If so, feel free to remove the 1.0 milestone.

**Comment by embray** [comment]
It would be nice--I really wanted to have my fitter refactoring done.  But other things have taken too much time.

**Comment by pllim** [comment]
@nden , is this still relevant?

**Comment by nden** [comment]
I think AffineTransform will need a new fitting algorithm. Since there's not much in this PR, I'm closing it.

**Pull request closed without merging**
