### PR TITLE
Try debugging html-docs code

### PR DESCRIPTION
**Pull request by kakirastern**
Removing `:include-all-objects:` from astropy/docs/units/index.rst file to see if html-docs tests are passed...

### CODE REVIEW

**Comment by mhvk** [comment]
@kakirastern - what is the rationale for these trials? The `include-all-objects` is needed to ensure things `STmag` are included in the list (which is neither a function nor a class, the types usually included). In fact, I changed the documentation generation code specifically to make this possible! (Obviously, this suggests a comment in the .rst files may be helpful...)

**Comment by kakirastern** [comment]
@mhvk Sorry about the confusion... I am trying to see if there are alternatives to using `:include-all-objects:` as there have been some bugs turning up in its presence that would disappear in its absence. I noticed that you added this to the docs about 2 months ago.

**Comment by kakirastern** [comment]
I keep getting warnings like `WARNING: toctree contains reference to nonexisting document 'api/astropy.units.function.logarithmic.m_bol'` and `WARNING: py:obj reference target not found: astropy.units.function.logarithmic.m_bol` and `WARNING: toctree contains reference to nonexisting document 'api/astropy.units.function.logarithmic.m_bol`... Just trying to figure out where the problem is... My apologies for any inconvenience.

**Comment by kakirastern** [comment]
According SunPy docs, this could be the following:

> WARNING: toctree references unknown document ‘…’ / WARNING: toctree contains reference to nonexisting document

>This pair of errors is due to the way numpydoc scrapes class members.

**Comment by kakirastern** [comment]
Will close this PR about now...

**Comment by mhvk** [comment]
Sure, I understand now what you are trying to do. Fear that I'm not sure that I can help directly, though I feel I have seen the problem before...

**Comment by kakirastern** [comment]
Thanks @mhvk! I read somewhere that you can also achieve a similar effect with the `__all__` variable. Not sure if that applies to our case and whether that can be implemented without breaking anything. But now I suspect that there must be some confusion between `m_bol` and `M_bol`... I worry somewhere along the line the system becomes case-insensitive and confuses the two. Errors are only thrown for `m_bol` for some reason to be determined though. I checked it and your fix worked perfectly well, except for `m_bol`.

**Comment by kakirastern** [comment]
Your fix did pick up everything else like `STmag`...

**Comment by mhvk** [comment]
Yes, that is strange that `STmag` works fine. I suspect the upper/lower case is a red herring, though you could try swapping the definitions around to see if that changes anything.

**Comment by bsipocz** [comment]
So just to reiterate this one last time. Did you see this failures here on CI or locally? I couldn't find a build with it on circleCI, but arguably I only looked into a few (it's super annoying that the full log needs to be downloaded). 

Anyway, if it's a local only issue, my suspicion is that you may have a generated file somewhere that causes it, it might have been a remnant from another branch, etc.
Cleaning up your repo may solve the issue. 
To do that, you can do `git clean -dfx`. But be careful before you do this, as it will remove everything that is not part of the git repo. E.g. if you keep note file or anything those should be exempted before running the command. E.g. I dump all sort of stuff into a "notes" directory, so I say: `git clean -dfx -e notes`.

**Comment by kakirastern** [comment]
@bsipocz I think you are right about the issue being a local one. I have checked the Circle CI log, and both `m_bol` and `M_bol` are indeed there. So the only problem with broken html-docs build has to do with the link checker only. But I wanted to find out to make sure. 

@mhvk Yup, you are right about the issue of ordering... `M_bol` does indeed come before `m_bol` in the API docs.

**Comment by kakirastern** [comment]
Looks like two GitHub server errors are to blame regarding PR's #996 and #968...

**Comment by kakirastern** [comment]
@bsipocz I did `git clean -dfx` as you have suggested, but the 9 local warnings regarding `m_bol` persist. Must be my machine: It's a MacBook Air running on macOS Mojave Version 10.14.3...

**Comment by mhvk** [comment]
@kakirastern - I'll try to build the docs locally as well (but not now); I've definitely had similar problems and it would be good to document how to get rid of them (I think sometimes I've had to just start with a clear virtual environment as well).

**Comment by kakirastern** [comment]
@mhvk That would be great! Good to know I am not the only one with such problems... Maybe I could help out with some documentation if help is needed in this regard. (I will try with a new virtual environment from scratch too. Thanks for the suggestion!)

**Comment by pllim** [comment]
Why Python version are you using locally? Dictionary is ordered by insertion but only for Python >= 3.6

**Comment by kakirastern** [comment]
I use Python 3.6 or 3.7, depending on the virtual environment.

**Comment by bsipocz** [comment]
for what it's worth, I'm not able to build docs locally. I halts until cancelled, consistently at 95% of generating the example references.

**Comment by kakirastern** [comment]
@bsipocz That's weird, I have been building docs locally and almost continuously for the past few hours to debug the menubar. I think the current repo is fine... At least that's what I can confirm. (Have been using Python 3.7 instead of 3.6 though, not sure if this has anything to do with it.)

**Comment by bsipocz** [comment]
Oh, the repo is definitely fine I'm not worried about it, it passes on CI in a clean environment. It's just my local issue :)

**Comment by kakirastern** [comment]
Hope you can get it sorted out pretty soon...

**Pull request closed without merging**
