### PR TITLE
[WIP] NDData 1.2 documentation [skip ci]

### PR DESCRIPTION
**Pull request by MSeifert04**
# Do not merge this PR
This PR represents a branch containing all merged and still open PRs regarding NDData and the changed documentation regarding narrative documentation and class/function docstrings. It's huge and probably hard to review so I've build the RTD documentation myself so that you can compare it to the final result:

- [nddata.index.rst](http://astropy-mseifer.readthedocs.io/en/tmp_nddata_final/nddata/index.html)
- [nddata.nddata.rst](http://astropy-mseifer.readthedocs.io/en/tmp_nddata_final/nddata/nddata.html)
- [nddata.mixins.index.rst and all pages linked there](http://astropy-mseifer.readthedocs.io/en/tmp_nddata_final/nddata/mixins/index.html)
- [nddata.subclassing.rst](http://astropy-mseifer.readthedocs.io/en/tmp_nddata_final/nddata/subclassing.html)

Included PRs:
- [x] #4787
- [x] #4789
- [x] #4797
- [ ] #4799
- [ ] #4827 
- [x] #4851
- [x] #4862
- [ ] #4271 
- [x] #4879
- [ ] #4876 (contains the documentation assuming #4799, #4827 and #4271 will not be merged until freeze)

Not relevant for documentation:
- [x] #4809
- [x] #4828 

Crossed items mean that the PR is already merged.

I didn't remove the code-changes since that would take more time than I currently have. If really necessary I'll do it in the next days.

Based on the issue: #4538

### CODE REVIEW

**Comment by mwcraig** [comment]
As a review strategy, I'll review the RST docs as part of this PR, and the docstrings in the separate PRs. It ought to be possible once the other PRs are merged to separate out the narrative document bits from the rest.

Review coming Wednesday...

**Comment by MSeifert04** [comment]
@mwcraig I'll clean it up as soon as I know which PRs will be merged.

Would this also need a "Whatsnew in 1.2" entry?

**Comment by mwcraig** [comment]
I lean towards yes for a "What's New" entry. I think everything except #4827 (added setters, agreed to postpone for now), and maybe #4799 (fits reader/writer) will make it in. Will ask a couple for the FITS folks for opinions on the reader/writer (easier to review now that the memory leak stuff is separate).

**Comment by MSeifert04** [comment]
@mwcraig Does the list update itself or are you editing? 

I've just checked and #4789 could be merged without breaking stuff. The other two are postponed so I didn't check them. Altough I'll rebase #4799 to pass the tests afterwards.

**Comment by mwcraig** [comment]
@MSeifert04 -- I've been editing :)

**Comment by MSeifert04** [comment]
Ok, that's great.

Did you remove #4271 from the list or did I forget to include it? The PR isn't really important but it belongs to the PRs for NDData. So I'll let you decide if you want another one or postpone it too :)

Thanks you very much for all the reviews. :+1: Didn't thought I'd so many of them merged before friday :smile:

**Comment by MSeifert04** [comment]
@mwcraig since #4876 contains the updated (ok, rather downgraded since I removed the parts concerning unmerged PRs) documentation should I close this PR?

**Pull request closed without merging**
