### PR TITLE
Fix incorrect WCS after slicing or making image cutouts when WCS has SIP

### PR DESCRIPTION
**Pull request by mcara**
This PR addresses the issue of large errors produced by either sliced `WCS` objects or image cutouts (see `nddata.Cutout2D`) when original `WCS` contains `SIP` distortion corrections. This issue was described in detail in https://github.com/astropy/astropy/issues/7550.

Fundamentally, if you look at the last parameter in the [`Sip` class](http://docs.astropy.org/en/stable/api/astropy.wcs.Sip.html), you will notice that`Sip` class has its own `crpix` parameter. `Sip.crpix` is independent from `WCS.wcs.crpix`. This is not in the `FITS WCS` standard (or, required by the standard): `Sip.crpix` is never written to the header. Instead this is a feature of how `astropy.wcs` implements `SIP` corrections. So, when `WCS.wcs.crpix` is modified (as it is when slicing or making cutouts) the two `crpix`es get out of sync.

In this PR I add code to adjust `Sip.crpix` in addition to adjustment of `WCS.wcs.crpix` so that both values are in sync.

Without this synchronization, SIP corrections are computed relative to the old `CRPIX` and depending on the position of the cutout/slice relative to original `CRPIX`, this can lead to very large errors: tens of pixels for HST ACS/HRC image and probably larger for ACS/WFC images.

CC: @larrybradley @keflavich @pllim

### CODE REVIEW

**Comment by pllim** [comment]
Thanks, Mihai!

Huh, that's weird... `RemovedInPytest4Warning` is back in CircleCI. Was this PR built on latest `master` (that is, did you `git rebase upstream/master` before you created this)?

p.s. Not sure how much refactoring was done for `nddata` between 2.x and 3.x, so if backporting to 2.x is not possible, please re-milestone for 3.x bug fix.

**Comment by mcara** [comment]
hm... maybe I didn't update my fork... What do I need to do now? rebase?

**Comment by pllim** [comment]
Try this:
```
git fetch upstream master
git rebase upstream/master
```
Then, resolve conflicts, if necessary.

Optional: Sacrifice a lamb.

**Comment by bsipocz** [comment]
Yes, the base of this is rather old, the rebase should fix the errors. Also, please move the changelog down to the 2.0.8 section.

**Comment by mcara** [comment]
Sacrificing the lamb.

**Comment by pllim** [comment]
:scream: :sheep:

**Comment by larrybradley** [comment]
@mcara Are you going to submit a new PR?

**Comment by mcara** [comment]
Yes, working on it right now.

**Comment by bsipocz** [comment]
ohh, no 😭 

poor 🐑

**Pull request closed without merging**
