### PR TITLE
MNT: Make yaml import truly optional in io.misc.yaml

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address the `yaml` import error mentioned in #10246 .

```
_______________________________________ ERROR collecting astropy/io/misc/yaml.py _______________________________________
astropy/io/misc/yaml.py:81: in <module>
    import yaml
E   ModuleNotFoundError: No module named 'yaml'

During handling of the above exception, another exception occurred:
astropy/io/misc/yaml.py:83: in <module>
    raise ImportError('`import yaml` failed, PyYAML package is required for YAML')
E   ImportError: `import yaml` failed, PyYAML package is required for YAML
```

With this patch, without PyYAML installed:
```python
>>> from astropy.io.misc import yaml  # No more error
>>> a = yaml.AstropyLoader()
ImportError: `import yaml` failed, PyYAML package is required for YAML and must be 3.12 or later
```

**TODO**

- [ ] If this is acceptable, add a change log after milestone is set.

### CODE REVIEW

**Comment by pllim** [comment]
> Is the min 3.12 requirement new?

Not really. It is already in the docstring and I am just making the implementation consistent. This line was added in #5486 by @taldcroft .

https://github.com/astropy/astropy/blob/f2092fa0652f90685c8fd0034896d0fc5a7386d2/astropy/io/misc/yaml.py#L23-L25

**Comment by bsipocz** [comment]
Oh, the the 32bit failure is related

**Comment by pllim** [comment]
Re: 32-bit -- I think the failure is not so much 32-bit but the parallel part. Maybe `__doctest_requires__ = {'*': ['yaml']}` doesn't work well with `pytest-xdist`. I'll have to ponder this.

**Comment by bsipocz** [comment]
ugly workaround just for this, but what if we run the 32bit tests with alldeps? I would generarly feel a bit better to have alldeps the default to make sure we run as many tests as possible for a setting, and only have one run with the mandatory only, rather the other way around.

**Comment by pllim** [comment]
I am a little afraid that adding `alldeps` to 32-bit will open a can of worms but why not try it?

**Comment by bsipocz** [comment]
yeah, I wouldn't be surprised by the tiny monster 🐛 crawling out from their hides

**Comment by pllim** [comment]
Yup... Can o' worms:
```
    src/checkdep_freetype2.c:9:22: fatal error: ft2build.h: No such file or directory
     #include <ft2build.h>
                          ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

I'll think of a way to just do a custom skip on that doctest...

**Comment by pllim** [comment]
I think I addressed all the comments. Had to move the docstring to RST though to use the doctest directive that we know would work. I successfully ran all the tests locally without `yaml` installed with this patch. Let's see what the CI says... 🤞

**Comment by bsipocz** [comment]
I don't think this needs a changelog, nothing really changed on for the users.

**Comment by bsipocz** [comment]
Thanks @pllim for taking care all these import issues.

**Comment by pllim** [comment]
I hope it works. I think I must have missed something but I think @mhvk fixed it somewhere else. I am sorry!

**Comment by mhvk** [comment]
Yes, fixed elsewhere. And, overall, very nice to have those imports be truly optional! It would be even nicer if there was some way of bailing from module loading (with `__all__` empty), but I don't think that's possible.

**Pull request merged**
