### PR TITLE
Fix frame.separation_3d() when frames have velocity data

### PR DESCRIPTION
**Pull request by adrn**
At present, `separation_3d()` doesn't work when a frame has velocity data attached. This fixes the method to drop the differentials before doing the representation arithmetic.

cc @eteq @mhvk

### CODE REVIEW

**Comment by mhvk** [comment]
I didn't look in any detail, but do make sure that if differentials are attached, and an `obstime` is present, this doesn't just work, i.e., the transformation should be done to the other frame before dropping the differentials.

**Comment by adrn** [comment]
The changes we made happen *after* the transformation, so I can confirm that if `obstimes`'s are present it doesn't work:

```python
icrs = coord.AltAz(az=15*u.deg, alt=61*u.deg, distance=21*u.pc,
                   pm_az_cosalt=-21*u.mas/u.yr, pm_alt=150*u.mas/u.yr,
                   radial_velocity=100*u.km/u.s, obstime=Time('J2015'))

icrs2 = coord.AltAz(az=15*u.deg, alt=61*u.deg, distance=21*u.pc,
                   pm_az_cosalt=-21*u.mas/u.yr, pm_alt=150*u.mas/u.yr,
                   radial_velocity=100*u.km/u.s, obstime=Time('J2000'))

icrs.separation_3d(icrs2)
```

raises:
```
ERROR: NotImplementedError: You cannot transform a frame that has velocities to another frame at a different obstime. If you think this should (or should not) be possible, please comment at https://github.com/astropy/astropy/issues/6280 [astropy.coordinates.baseframe]
```

**Comment by adrn** [comment]
@bsipocz I don't think this needs a changelog entry - this fixes a bug based on functionality that only exists in master.

**Comment by bsipocz** [comment]
@adrn - Agreed. Basically none of the ``Affects-dev`` PRs need a changelog entry by default (except when it's good to have an update on the entry of the original implementation).

**Pull request merged**
