### PR TITLE
RFC: prefer vars() over __dict__ attribute

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
This is a simple refactor proposed by @eerovaher and extracted from #16630

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by mhvk** [comment]
I guess the advantage of `vars()` over `.__dict__` is to not rely on what in principle is an implementation detail? A bit like `type()` vs `.__class__`?

Note that `vars(u)` takes 40ns on my machine while `u.__dict__` takes 18 ns.  I suspect the one-liner discussed here will be slower more generally, since now a new dict is created rather than just a few items added.  But since this is in a class creation routine, it will hardly matter.

I guess the more general question is whether we should have a preference. A quick "git grep" suggests we use the `__dict__` way 202 times, while `vars\(` is used 22 times. Similarly, `__class__` is used 631 times, while `\ type\(` is used 447 times (where the space is added to avoid `dtype`, etc.). Unsurprisingly, different submodules are written one way or the other (with `type()` most often used in tests).

Overall, my conclusion is to let this be -- quite a bit of churn for no tangible benefit.

**Comment by neutrinoceros** [comment]
> Overall, my conclusion is to let this be -- quite a bit of churn for no tangible benefit.

fine by me. I'll drop this one. Thank you !

**Comment by eerovaher** [comment]
Since Ruff 0.5.0 the rule [PERF403 (manual-dict-comprehension)](https://docs.astral.sh/ruff/rules/manual-dict-comprehension/) suggests making the replacement
```patch
-         for k, v in cls.__dict__.items():
-             if isinstance(v, Attribute):
-                 frame_attrs[k] = v
+         frame_attrs |= {
+             k: v for k, v in cls.__dict__.items() if isinstance(v, Attribute)
+         }
```
With `vars(cls)` instead of `cls.__dict__` the dictionary comprehension fits on a single line. So what I suggested in #16630 was not about replacing accessing `__dict__` with calling `vars()` in general, it was about replacing 3 lines of code with a one-liner (and with the one-liner we don't really need the empty lines around it either). But when this change was moved to a separate pull request all that context was lost and that just made reviewing harder.

**Comment by mhvk** [comment]
Indeed, that context was lost!

Though the text from the link does not explain why first creating a `dict` and then updating another is better (apart from brevity, which is definitely worth something!)

**Pull request closed without merging**
