### PR TITLE
WIP: convolve_fft memory & execution time profiling

### PR DESCRIPTION
**Pull request by keflavich**
See https://github.com/astropy/astropy/pull/4366

This implements a profiling tool and a plotter.  It does not compare convolve_fft to convolve, which is an obvious next step.  As interesting as this all is, though, I can't dedicate much more time to it.

### CODE REVIEW

**Comment by keflavich** [comment]
...this clearly needs a rebase.

**Comment by keflavich** [comment]
Here are some plots from an example run.  They're a bit confusing; the tables are a little easier to parse.  The timing is not monotonic with size because FFTs are faster for 2^n sizes.

psfffftf
psfffftt
psftfftf
psftfftt

**Comment by keflavich** [comment]
These figures are a little more readable and show the interesting spikes you can get without `fft_pad`.  I used a finer grid of image sizes for this.

psfffftf
psfffftt
psftfftf
psftfftt

**Comment by keflavich** [comment]
This one should be very useful:

time_vs_mem


I'll try to populate it with a bigger parameter space, but I'm a little worried about crashing my computer.

**Comment by keflavich** [comment]
Well, my tests worked, but my ipython session did eventually crash.  Still, recovered the results:
psfffftf
psfffftt
psftfftf
psftfftt
time_vs_mem

So the rule of thumb is: always fft_pad if you can, but sometimes you can't!  In the True,True case, the green line cuts off early because I did not run the tests when the 1GB array size warning was raised.

**Comment by keflavich** [comment]
@embray would you prefer these plots in the docs, on the wiki, or somewhere else?  I think they're useful.  They've been run on a late 2013 macbook pro with 16 GB RAM; it would  be interesting to run them elsewhere.  Also, it would be really interesting to see if there's any difference in performance with the type of fft used (np.fft, fftw3, etc.).

**Comment by bsipocz** [comment]
@keflavich - This will need a changelog entry, too.

**Comment by keflavich** [comment]
This won't make the 2.0 release; I've removed the milestone.  This PR is really just a tool to assess convolution speeds.  It is useful, but it needs to be incorporated into the docs.

**Comment by bsipocz** [comment]
OK, sorry. I saw that you've just rebased it, thus the assumption.

**Comment by keflavich** [comment]
The rebase was to see if it could be included.  Upon further review, nope!

This would be a cool student project if anyone were ever inclined... it's not of the scale of a GSoC, but maybe a good 1-week "learn about convolution" project.

**Comment by bsipocz** [comment]
I've cancelled the osx build.

**Comment by bsipocz** [comment]
There seems to be genuine issues with the optional dependencies that needs to be addressed, so I've cancelled some travis jobs.

**Comment by keflavich** [comment]
The built docs will appear [here](http://keflavich-astropy.readthedocs.io/en/convolve_fft_profiling/) eventually.

**Comment by keflavich** [comment]
This is one of those perpetually-too-low-priority projects.  It would have been appropriate to finish it for the astropy paper, but if this gets autoclosed, it's OK.

**Comment by saimn** [comment]
Btw, I was recently comparing performance for cubes convolution with scipy and pyfftw (which is multi-threaded but not so easy to use), and found that numpy caches the computed ffts (less than 100Mb and 32 items). Did you take this into account for your time measurements ? (Looking quickly at the code, it seems not).

**Comment by bsipocz** [comment]
Arguably v3.1 will be about performance, so ultimately it would be an ideal release for this.

**Comment by keflavich** [comment]
Apparently I built the docs associated with this a few years ago:

https://keflavich-astropy.readthedocs.io/en/convolve_fft_profiling/convolution/performance.html

**Comment by bsipocz** [comment]
@keflavich - if you have time to resurrect this for 3.2, I suppose it would be more than welcome improvement.

**Pull request closed without merging**
