### PR TITLE
Coordinate matching fails for unit-less distances

### PR DESCRIPTION
**Pull request by eteq**
The Problem this PR is trying to solve is most easily shown in this snippet:
```python
from astropy.coordinates import ICRS, CartesianRepresentation, match_coordinates_sky
i1 = ICRS([[1], [2], [3]], representation_type=CartesianRepresentation)
i2 = ICRS([[1], [2], [4, 5]], representation_type=CartesianRepresentation)
i, sep, sep3d = match_coordinates_sky(i1, i2)
```
yields ``astropy.units.core.UnitTypeError: Distance instances require units equivalent to 'm', so cannot set it to ''.``.  

The problem is: it seems counter-intuitive in that it fails only in `match_coordinates_sky` and not in the `ICRS` constructor or similar. The root cause is really `separation_3d`, which fails if the inputs are dimensionless because the "3d" part of coordinates matching uses `Distance`, which is supposed to be, well, a distance (and have appropriate units).  Given we are now allowing dimensionless distances in the frame classes, arguably we should allow it in `separation_3d`... But that's sort of an API change (albiet a "relaxing" one) - should we allow this "3d distance" to sometimes be dimensionless?

One could argue this is a bug... but I'm not sure it is, so I'm not sure if this is a bugfix, or new feature, or "shouldn't do", so have not yet flagged it bug, milestoned it, or changelogged it.

Also marking as a WIP because there's question above whether we really want to do this or not. The code itself I think is done, but the "discussion" part is not.

cc @mhvk @adrn

### CODE REVIEW

**Comment by mhvk** [comment]
@eteq - the PR looks OK, but should we really allow 3-D distances for coordinates for which the distance is explicitly not known? (maybe easiest is just to allow it)

**Comment by mhvk** [comment]
p.s.  I think if we go this route, it is fixing a bug.

**Comment by adrn** [comment]
I'm happy with treating this as a bugfix!

**Comment by bsipocz** [comment]
This definitely need a rebase to make sure tests are still happy.

**Comment by mhvk** [comment]
@eteq - I think both @adrn and I were happy enough with this - even if not super-enthusiastic. I'm fine with putting it in if you're willing to revive it (needs rebase plus changelog entry in right place).

**Pull request closed without merging**
