### PR TITLE
Catch TypeError during FITS_rec deletion

### LINKED ISSUE #4912: "Exception TypeError ... ignored" when using astropy.io.fits.getdata() in astropy/1.1.2
Data obtained from an `astropy.io.fits.getdata()` call throws an ignored exception when the script is shut down.  For example:

```
Exception TypeError: "'NoneType' object is not callable" in <bound method FITS_rec.__del__ of FITS_rec([({some data}], dtype=(numpy.record, [{some types that are only integers & floats}]))> ignored
```

The immediate cause of the exception being *ignored* [is well known](https://docs.python.org/2/reference/datamodel.html#object.__del__).  The concern is that this appears in 1.1.2 but not 1.1.1, and only for FITS_rec objects returned by `astropy.io.fits.getdata()`.

Is it possible that #520 or #4539 changed the order in which objects are garbage collected or otherwise deleted such that garbage collection at script shutdown time tries to reference an object that no longer exists?

For completeness, this message appears with python/2.7.11, numpy/1.10.4 *or* numpy/1.11.0, astropy/1.1.2.

### PR DESCRIPTION
**Pull request by pllim**
Fixes #4912 as per [this comment](https://github.com/astropy/astropy/issues/4912#issuecomment-221191001) by @embray. I was at a stage where I could reproduce the problem consistently (running `test_spectrum.py` for spacetelescope/stsynphot_refactor#16. I find that this makes those pesky messages disappear at least for my case.

@weaverba137, can you please give this a spin?

See also: #4690, #4694, #4948

### CODE REVIEW

**Comment by embray** [comment]
Looks fine to me.  One might be able to come up with other exceptions that could be raised, as `__del__` methods run during interpreter shutdown are in dangerous waters.  But `AttributeError` and `TypeError` are certainly the most likely.

You know, in Python 3 there's a `contextlib.ignored`--a context manager that lets you ignore certain exceptions.  Very handy (and backported in `astropy.utils.compat`!)  I don't think you'd save much by using it here, but just pointing out that it exists.  Actually the reason I bring it up is it made me think: In this case the entire method is ignoring those exceptions--it would be nice if `ignored()` also worked as a decorator for cases like that, but I don't think it currently does.  Something to bring to Python-Ideas.....

**Comment by pllim** [comment]
Good to know about `contextlib`. I have no problem switching to that instead of `try-except` if that's the general consensus. I am neutral either way since it's just another way of doing the same thing.

It has been renamed to `contextlib.suppress`, right? See https://pymotw.com/3/contextlib/ .

**Comment by embray** [comment]
Huh, I don't know when it was renamed `suppress`.  It definitely used to be `ignored`.  Maybe it was renamed before the 3.4 release.  I've still just been using `ignored` all this time.  Maybe that should be updated in `astropy.utils` as well.  Anyways I wouldn't bother changing anything wrt this PR I was just musing off topic sorry.

**Comment by embray** [comment]
This ought to be merged before v1.2.0 is released, and also backported to the next v1.1.x patch release.

**Comment by astrofrog** [comment]
@embray - ok, will include it in 1.2rc1 - thanks!

**Comment by astrofrog** [comment]
@pllim - sorry I mean it should be under 1.0.11 since we are going to backport this to 1.0.x

**Comment by pllim** [comment]
@astrofrog, my emails told me that I missed your various pleas to add a change log entry. Sorry, I just woke up. That's the problem of Earth being round and spinning and all...

**Comment by astrofrog** [comment]
@pllim - not a problem at all! I deleted the messages because I wasn't sure if it was going to backport cleanly, so I figured I'd just do it all manually and add it in the changelog depending on whether it could be backported :)

**Comment by pllim** [comment]
Thank you!

**Pull request merged**
