### PR TITLE
Fixing PEP8 whitespace

### PR DESCRIPTION
**Pull request by bsipocz**
MERGE ONLY ONCE THE BIG PRs ARE IN!

This PR fixes only the whitespaces without adding these error codes to the setup.cfg file to require via CI. We already had some open ended discussions on how strict we should be on CI about formatting issues, so I'll leave it to others to decide whether to add these there, or not.

However [I would suggest](https://github.com/sunpy/sunpy/pull/2038#issuecomment-286416049) to set up a bot that will comment on PRs about PEP8 issues using a broader list of errors and warnings.

### CODE REVIEW

**Comment by mhvk** [comment]
I'm not sure what is presently available, but for whitespace in particular, might it be possible to have a bot that not only checks what is wrong, but actually makes a PR to the relevant branch to correct it?

**Comment by bsipocz** [comment]
@mhvk - yes, that could be an option, though I'm not sure how confusing it will be to the new contributors to see PRs opened against their PRs. 

Anyway I plan to keep this open for a little longer to gather more PEP8 related changes (and until I figure out how to ignore cases nicely where not following PEP8 makes sense).

**Comment by bsipocz** [comment]
Damn, this PR was indeed a suitable one for 1st of April. I think it's better to start again from scratch, and thus will push back the whtespace fixes on a submodule bases rather than in one massive commit.

**Comment by adrn** [comment]
Yea, it might be safer to wait until all v2.0 PR's are merged (oops...) and then try?

**Comment by bsipocz** [comment]
@adrn - Yes, I definitely wanted to leave coordinates alone while you're still working on the big PRs... :)

**Comment by adrn** [comment]
@bsipocz Phew, and thanks 😄

**Comment by eteq** [comment]
@bsipocz - I think it's ok to wait until after the RC if you want to still do this for 2.0, right?  Since it doesn't actually touch any real code...

**Comment by bsipocz** [comment]
I plan to finish this off tomorrow morning when the coordinates chances are in, too. If tests pass will merge it if that's OK with you, as I think this should not have any actual effect on the code.

**Comment by bsipocz** [comment]
Then we may consider switching on pep8speaks here, too with the limited set of these errors and the ones we tests for on travis.

**Comment by bsipocz** [comment]
Passed, so merging.

**Comment by eteq** [comment]
This PR has single-handedly made @bsipocz appear in most of the file version histories :wink:

**Comment by bsipocz** [comment]
Ouch, that wasn't the aim, it screws up @dpshelio's bus factor estimations...

**Pull request merged**
