### PR TITLE
EXP: Test OpenAstronomy/github-actions-workflows PR 199 downstream (Coverage: Upload as separate step)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to test https://github.com/OpenAstronomy/github-actions-workflows/pull/199 . This should never be merged.

There is now a new job called `CI / tests / Upload Coverage (pull_request) `.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by Cadair** [comment]
Looking at this: https://app.codecov.io/gh/astropy/astropy/commit/e04d63729675357d61279d01a563fb413a5f3884 this seems to not have registered properly on codecov? I only see uploads from circleci?

**Comment by Cadair** [comment]
I suspect this isn't working correctly due to the significant loss in project coverage, and the many many indirect coverage changes. Going through the logs, this line isn't very encouraging: https://github.com/astropy/astropy/actions/runs/9010438438/job/24756918848#step:3:86

**Comment by pllim** [comment]
We just turned off project coverage for PR. Would it be useful to rebase and try again?

Also, can you please elaborate what you see in that line of the log that is not very encouraging?

Thanks.

**Comment by Cadair** [comment]
It says it only uploads one file's worth. It looks like the lack of project coverage could well be a real bug here?

**Comment by pllim** [comment]
The line you pointed to still makes no sense to me but I see what you are saying. Lemme see if I can tweak the settings so it sees both files. Good catch!

```
2024-05-09T00:51:15.1586956Z Found 2 artifact(s)
...
2024-05-09T00:51:19.9914280Z info - 2024-05-09 00:51:19,991 -- Found 1 coverage files to report
2024-05-09T00:51:19.9915876Z info - 2024-05-09 00:51:19,991 -- > coverage/coverage.xml
```

**Comment by pllim** [comment]
Noooo... how did this happen?

```
Run ls -R
.:
coverage

./coverage:
coverage.xml
```

**Comment by pllim** [comment]
OK I think I figured it out, @Cadair 

```
2024-05-17T21:02:12.1264188Z info - 2024-05-17 21:02:12,126 -- Found 2 coverage files to report
2024-05-17T21:02:12.1265408Z info - 2024-05-17 21:02:12,126 -- > coverage/coverage_py312-test-cov/coverage.xml
2024-05-17T21:02:12.1266969Z info - 2024-05-17 21:02:12,126 -- > coverage/coverage_py310-test-oldestdeps-alldeps-cov-clocale/coverage.xml
```

**Pull request closed without merging**
