### PR TITLE
TST: Temporarily pin numpy<1.18 for Windows

### PR DESCRIPTION
**Pull request by pllim**
This is a stop-gap solution for #9871 . This should be reverted when that issue is resolved upstream.

### CODE REVIEW

**Comment by bsipocz** [comment]
Cancelled all but windows build.

normally I would prefer the numpy versions to be explicit, but since this is a temporarily workaround, <1.18 should be fine.

**Comment by bsipocz** [comment]
apparently the `<` is not OK, so I go ahead and make the changes to get this in asap.

**Comment by bsipocz** [comment]
(all, but the windows build is cancelled, merge away once that's passing)

**Comment by astrofrog** [comment]
This CI issue will actually be fixed when https://github.com/astropy/astropy/pull/9726 is merged, so can we hold off maybe so as not to create conflicts? I think @eteq was planning to have one last look at that PR before merging.

**Comment by astrofrog** [comment]
Just to be clear I'd still advocate keeping this open though in case https://github.com/astropy/astropy/pull/9726 gets delayed beyond a couple of days.

**Comment by bsipocz** [comment]
@astrofrog - I would rather merge this away, normalizing having failing CI sets a bad precedent (it's already too bad that we had expected failures for a couple of weeks now with the other jobs), and this conflict would be a rather trivial one for #9726 to resolve (besides this may need to be backported, depending on how long it takes to get the upstream fix).

**Comment by astrofrog** [comment]
Ok sounds good - let's do it!

**Comment by bsipocz** [comment]
> Ok sounds good - let's do it!

Thanks @astrofrog!

**Comment by mhvk** [comment]
Thanks all, I think this is an excellent solution, especially as the comment in `.travis.yml` makes very clear what we're doing.

**Pull request merged**
