### PR TITLE
Table sort with a tuple of keys

### PR DESCRIPTION
**Pull request by saimn**
Currently `Table.sort` works only with a list of keys, so I changed the test to include the possibility to pass a tuple:
```
t.sort(('a', 'b'))
```
This is a simple fix for a simple issue, but I wonder if it makes sense to support any kind of iterable (with `utils.isiterable`), or to do the same as `Table.argsort` (which is called by `sort`), i.e. changing the test to convert the argument to a list if it is a string (and btw it supports any iterable) ?

cc @taldcroft

### CODE REVIEW

**Comment by astrofrog** [comment]
+1 to allowing any iterable

**Comment by saimn** [comment]
@astrofrog - I changed the test to allow any iterable, the same as `Table.argsort`.

**Comment by saimn** [comment]
Appveyor failed to install conda, restarting the build.

**Comment by saimn** [comment]
Up, @astrofrog @taldcroft ?
Seems straightforward ;)

**Comment by pllim** [comment]
Needs a change log -- perhaps under "new feature" for 1.2?

**Comment by taldcroft** [comment]
@saimn - you should update the doc strings for `sort` and `argsort` to indicate that `key` can be a string, list or tuple.  But for instance a numpy array of column names doesn't work.  

In theory one could make the input side a bit more tolerant by doing `key = list(key)` after the check for `key` being a string.  That's your call, I'm never sure how far to go with allowing any kind of sequence as an input (including e.g. a dict) since that might mask a bug in the calling code.

**Comment by saimn** [comment]
@taldcroft - About the docstring, it seems redundant to specify 'tuple of str'. The current 'str or list of str' seems enough to me. 
Otherwise I agree with you it is sometimes difficult to know where to put the limits (i.e. should we try to convert to list ?), the important being to be consistent, and to follow common usages: in this case tuple and list are very similar, `numpy.sort` allows both (and its docstring mentions only 'str or list of str') but not ndarray, `Table.argsort` rely on `Table.__getitem__` which will allow only tuple and list. So I would stay with the current changes, which seems to be the good compromise.

**Comment by saimn** [comment]
Added changelog in 1.2 as suggested by @pllim

**Comment by taldcroft** [comment]
@saimn - fair enough.  Thanks!

**Pull request merged**
