### PR TITLE
Add support for np.float16

### PR DESCRIPTION
**Pull request by sarikj93**
Could be of use to some!

### CODE REVIEW

**Comment by pllim** [comment]
I am not sure why anyone would use `float16`. Is it even in the FITS standards?

**Comment by MSeifert04** [comment]
Is float16 covered by the fits standard and can other fits programs graciously deal with -16? If not we probably shouldn't add this because from the PoV of other programs we would produce invalid or corrupted fits Files then.

**Comment by saimn** [comment]
This is not in the standard:
capture d ecran de 2018-04-18 12-28-25

**Comment by pllim** [comment]
Since it is not in the standards, I am sorry that we cannot accept this one. Thanks anyway!

**Comment by sarikj93** [comment]
AH I see. No problem!

**Pull request closed without merging**
