### PR TITLE
Use custom exception for io.registry errors

### LINKED ISSUE #4831: Use higher-level error type for io.registry
The use of `Exception` as the error class in `io.registry` (e.g. [here](https://github.com/astropy/astropy/blob/ea043f497c139c17608f85ff2871aff32bdbd816/astropy/io/registry.py#L285)) means catching these errors and not everything else is harder than it could be.

Is it possible to use a higher-level exception class for this, perhaps `TypeError` or a custom `RegistryError`?

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR fixes #4831 by replacing use of `Exception` with a new custom `IORegistryError` inherited from `ValueError`.

### CODE REVIEW

**Comment by pllim** [comment]
I think this needs a change log for "API change" under 1.2.

**Comment by taldcroft** [comment]
I haven't checked, but presumably there are some tests of the existing `Exception`s being raised, so those should be modified.

**Comment by duncanmmacleod** [comment]
@taldcroft, yes I just spotted that now, will push another commit shortly.

**Comment by astrofrog** [comment]
What is the rationale for inheriting from ``ValueError`` rather than from ``Exception``?

**Comment by duncanmmacleod** [comment]
@astrofrog, inheriting from `ValueError` means that users can `except ValueError` to catch this, as well as importing and catching the custom exception class, rather than `except Exception`, which is a bit vague.

**Comment by astrofrog** [comment]
@duncanmmacleod - I guess what I mean is that ``IORegistryError`` isn't an error related to a specific value necessarily though (in the same way that it wouldn't make sense to inherit from ``KeyError``). I think it would make more sense to inherit from ``Exception`` directly. If you do end up wanting to catch both ``ValueError`` and ``IORegistryError``, I think you could then just do ``except ValueError, IORegistryError``?

**Comment by duncanmmacleod** [comment]
@astrofrog - I have updated the patch as you suggest. I have no strong opinions either way, so am happy to do whatever is simplest/clearest, which is probably a direct inheritance from `Exception`.

**Comment by astrofrog** [comment]
@duncanmmacleod - thanks! Could you add a changelog entry in the 1.2 section? (in ``CHANGES.md``)

**Comment by astrofrog** [comment]
Thanks @duncanmmacleod!

**Pull request merged**
