### PR TITLE
Wcs data size

### PR DESCRIPTION
**Pull request by nden**
This PR addresses #5461 and adds properties for all `NAXISj` keywords in a header. It's a bit of a kludge because it adds the properties in the `__init__`  method. If anyone knows of a better method that does not involve rewriting the entire `WCS` class and adding a metaclass, I'd like to know it.

I also renamed `_naxis` to `_naxis_size` and defined it in the `__init__`. The reason is there's an attribute `WCS.naxis` which stores the number of WCS axes and it's confusing to have a private variable with the same name but different meaning. Since `_naxis` was added only recently this is not an API change and hopefully will not cause much trouble.

This PR deprecates the properties for the private `_naxisj` attributes. Note that there are no private attributes now as the new properties work with the `_naxis_size` list. 
(Accessing the deprecated attributes prints [__main__], not sure why.)

@astrofrog @MSeifert04 @saimn

### CODE REVIEW

**Comment by nden** [comment]
I'm fine with this going into 1.3 if someone can review it in time.

**Comment by MSeifert04** [comment]
@nden 
I've installed your remote branch and there are some weird behaviours:

```
>>> from astropy.wcs import WCS
>>> from astropy.io import fits
>>> wcs_n3 = WCS(fits.Header([('naxis1', 10), ('naxis2', 20), ('naxis3', 30)]))

>>> wcs_n2 = WCS(naxis=2)
>>> # I would expect an AttributeError when accessing "naxis3" on this 2 axis WCS
>>> wcs_n2.naxis3
    228         # convert to 0-based index
    229         idx = int(self.name[-1]) - 1
--> 230         return naxis_data[idx]
    231 
    232     def __set__(self, obj, val):

IndexError: list index out of range
```

This is because the descriptors permanently alter your `WCS`. 

However it also contains the problem that `IndexError`s should be catched and converted to `AttributeErrors`.

Then a funny (unrealistic one):

```
>>> wcs_n15 = WCS(fits.Header([('naxis{}'.format(idx), idx*10) for idx in range(1, 15)]))
>>> wcs_n15.naxis13  # would expect 130
30

>>> wcs_n15.naxis10  # I would expect 100
140
```

Using the last value of the attribute-name only works for integers < 10. This won't happen in any realistic scenario, but I must admit I can't resist the urge to break things. 😄 

```
>>> # new session!
>>> from astropy.wcs import WCS
>>> from astropy.io import fits
>>> wcs_n3 = WCS(naxis=3)
>>> wcs_n3.naxis3
AttributeError: 'WCS' object has no attribute 'naxis3'

>>> wcs_n3._naxis_size
[0, 0]
```

This is quite weird but it seems that the `naxis` parameter alone doesn't create a 3-element list and it doesn't create a descriptor for `naxis3`.


The solution for problem 1 is quite simple even if it somewhat hides the implementation: Using `__getattr__`, `__setattr__` and `__delattr__` could replace the descriptors. Maybe it's best demonstrated by a small example:

```
class Fun(object):
    def __init__(self, values):
        self._naxis_size = values
        
    def _naxis_idx_from_attribute_name(self, attr_name):
        # This exception message should be the same as the default
        # Python message
        exc_message = ("'{}' object has no attribute '{}'"
                       "".format(self.__class__.__name__, attr_name))
        
        # We only want __getattr__ to handle naxisj attribute access
        if not attr_name.startswith('naxis'):
            raise AttributeError(exc_message)
            
        # The j in NAXISj must be convertable to integer
        try:
            idx = int(attr_name.lstrip('naxis')) - 1
        except ValueError:
            raise AttributeError(exc_message)
            
        # If it's out of bounds don't bubble up the IndexError
        if idx >= len(self._naxis_size):
            raise AttributeError(exc_message)
            
        return idx
        
    def __getattr__(self, attr_name):
        return self._naxis_size[self._naxis_idx_from_attribute_name(attr_name)]
    
    def __setattr__(self, attr_name, value):
        try:
            idx = self._naxis_idx_from_attribute_name(attr_name)
        except AttributeError:
            super(Fun, self).__setattr__(attr_name, value)
        else:
            self._naxis_size[idx] = value
            
    def __delattr__(self, attr_name):
        # Fail with an AttributeError in case we don't expect NAXISj to exist
        idx = self._naxis_idx_from_attribute_name(attr_name)
        # If it exists fail with a custom error
        raise TypeError("cannot delete '{}' attribute.".format(attr_name))
```

```
>>> f = Fun([10,11,12])
>>> f.naxis1
10
>>> f.naxis2
20
>>> f.naxis3
30
>>> f.naxis4
AttributeError: 'Fun' object has no attribute 'naxis4'
```

But it has the same disadvantage as using dynamic descriptors: It's not picked up by sphinx so we need to manually add them to the `Attributes`-section of the docstring. Also something like ipython autocompletion doesn't care about `__getattr__` so it won't show up if one uses my alternative.

**Comment by nden** [comment]
@MSeifert04 Thanks for installing and finding the silly mistakes. I also don't like that creating properties this way changes the class. Using `WCS.naxis_shape` instead is OK with me. We will need to change our software and this will require a long deprecation process.
However, I think the original problem was that other institutions also use the `naxis<j>` attributes so this will need to be agreed on by others as well. 
@saimn , can you comment on having  `WCS.naxis_shape` and removing `naxisj` after some deprecation time?

**Comment by saimn** [comment]
Maybe a bit silly but I had not really realized that #5411 introduced a list of naxis but with attributes only for `naxis1` and `naxis2` 😮 . So, indeed the need to add a property for each axis makes the code more complicated than it should be. 
To summarize the possible solutions:
- Using a list `WCS.naxis_shape`: would be coherent the other WCS attributes, but would break many codes.
- Using "dynamic" properties:  using `__getattr__`/`__setattr__` would be a better solution than a descriptor I think, without the need to create the descriptors at instantiation. The main drawback is that the attributes will be missing in code completion. 
- Stay with a list and only `naxis1` and `naxis2`: it may seem incoherent, but WCS is probably used mostly for images. (I have 3D wcs for cubes, but we split the spatial and spectral axes as it is not pratical to work with both at the same time). But it is not ideal. 

I have no strong opinion, but option 2 (`__getattr__`) seems the best compromise.

**Comment by astrofrog** [comment]
Have ``naxis1`` and ``naxis2`` been public for long though? If they were private, it's ok to break code using them? (after deprecation if absolutely needed)

**Comment by saimn** [comment]
@astrofrog - Actually it's `_naxis1` and `_naxis2`, so not really public (!) but present since quite a long time. It's hard to say if it is widely used, a Github search gives a few examples:
https://github.com/search?utf8=%E2%9C%93&q=_naxis1&type=Code&ref=searchresults
It would be easy to update but a deprecation period would certainly be useful.

**Comment by MSeifert04** [comment]
> Using a list WCS.naxis_shape: would be coherent the other WCS attributes, but would break many codes.

I don't agree, we're breaking no existing code (if we only deprecate `_naxis1`, `_naxis2`) or we break all existing code (if we just remove them) that used these two attributes. This is true for all approaches not just the first one.

Btw: Just to refine that idea: `shape` is not used as attribute/method right now, so that could be used instead of the previously proposed `naxis_shape`.

But one question I haven't raised before: How are image-less WCS differentiated from WCS with image? Am I correct that for a WCS without attached image the shape should be all zero? Should we provide a convenience function for this case?

**Comment by MSeifert04** [comment]
unfortunatly this needs a rebase because of #5455.

**Comment by nden** [comment]
It's clear this PR is not going forward, I will just close it once we agree on something.

None of the other two approaches is ideal too. I wonder if a combination between the two would be better.

- Turn the current `WCS._naxis_size` list attribute into a `WCS.shape` list and have `__getattr__` and `__setattr__` create the properties. In this way code can check `len(wcs.shape)` for the number of `naxisj` attributes in a WCS object.

As for dataless WCSs it would make sense to return `None` but this again will break code. So may be we should stick with returning 0.

**Comment by saimn** [comment]
> @MSeifert04 : we're breaking no existing code (if we only deprecate _naxis1, _naxis2)

Actually I think I like the idea of a `WCS.shape` attribute. 
From the moment where we want a better solution that the semi-private _naxis1, _naxis2, all solutions means an API change (with deprecation), so the distinction I made previously between the 3 solutions was not justified. So 👍 for the list, and using `shape` seems good !

**Comment by nden** [comment]
@MSeifert04 Do you want to create a PR?

**Comment by MSeifert04** [comment]
Ah, totally forgot about this. 😅 

I'll see if I can allocate some time to make a PR.

**Comment by nden** [comment]
I think this should be closed. The issue is described in #5461.

**Pull request closed without merging**
