### PR TITLE
Remove deprecated functionality from astropy.modeling

### PR DESCRIPTION
**Pull request by astrofrog**
There is a fair amount of deprecated code in astropy.modeling, so I've removed everything that was deprecated in 1.0 (I've left some things that were deprecated in 1.1)

### CODE REVIEW

**Comment by pllim** [comment]
This makes sense. c/c @nden in case she is interested.

**Comment by astrofrog** [comment]
@nden - do you have any objections to this? (I'd like to make sure we merge this by Friday)

**Comment by nden** [comment]
@astrofrog I want to look at this before merging. I'll try to do it today.

**Comment by nden** [comment]
OK, looks good. I need to make one change in `asdf` but this can be merged.

**Comment by astrofrog** [comment]
@nden - thanks!

**Pull request merged**
