### PR TITLE
Add astropy.help for searching online documentation

### PR DESCRIPTION
**Pull request by mdboom**
Possible implementation in response to https://github.com/astropy/astropy/pull/3629#issuecomment-87096858

### CODE REVIEW

**Comment by embray** [comment]
That was fast :D

Eventually we should add search of affiliated package docs too, but it's a start.

**Comment by hamogu** [comment]
Looks almost good to me. Should it have a test?

Also, I wonder if `help` is the right name, or if that will lead to confusion with the python `help` function that work offline and can be used on astropy functions, too. Maybe call it `online_help `?

**Comment by mdboom** [comment]
That makes sense.  I have no objections to renaming this `online_help`.

**Comment by mdboom** [comment]
I think this is ready -- not sure how to test it without going to the lengths of installing a puppet web browser on Travis-CI.

**Comment by embray** [comment]
I see no reason to hold this up, though I would want to open an issue about extending the functionality of this later.  Elsewhere I've noted that we should have doc links in the registry of affiliated packages (along with a flag indicating whether or not the docs use Sphinx--which they would in most cases).  Using this it would be possible to search across all affiliated packages as well.  This would be a more extensive addition though which could be put off for later (it's a decent sprint project).

**Comment by astrofrog** [comment]
Thanks @mdboom!

**Pull request merged**
