### PR TITLE
Ignore BeautifulSoup4 DeprecationWarnings on Python 3.4

### PR DESCRIPTION
**Pull request by mdboom**
Partial fix for #3405, along with #3406.

BeautifulSoup4 uses some deprecated kwargs to the stdlib html module.  There's not much we can do to work around them until BeautifulSoup updates itself, so we just add these to the list of warnings to ignore.

This was missed because we only test optional dependencies on Travis on Python 3.3, not 3.4.  This also update `.travis.yml` to use Python 3.4 instead.  @astrofrog, @embray: is that good enough, or should we do optional dependencies on both 3.3 and 3.4?

### CODE REVIEW

**Comment by mdboom** [comment]
FWIW, this issue also exists on 0.4.x -- don't know if we're still maintaining that.

**Comment by astrofrog** [comment]
This is a much better fix than what I was trying to do in https://github.com/astropy/astropy/pull/3238 - thanks!

I think we should just update the optional dependency build from 3.3 to 3.4, the idea was to always be testing the latest from 2.x and 3.x anyway.

**Comment by migueldvb** [comment]
Thanks, I will try running the tests with this fix.

**Comment by migueldvb** [comment]
The DeprecationWarnings are gone when I run the tests on the same machine with these changes.
Also the computer was idle and there was a MemoryError in the convolve test. I have put the output of the tests here:
http://sprunge.us/aVTQ

**Comment by astrofrog** [comment]
Works for me too - thanks for the fix @mdboom!

**Pull request merged**
