### PR TITLE
Finalizing changelog for v5.3.4

### PR DESCRIPTION
**Pull request by saimn**
### Description

This pull request is to address ...

Fixes #<Issue Number>

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Thanks!

**Comment by pllim** [comment]
Gonna close/reopen for bot

**Comment by saimn** [comment]
yes, but I'm waiting for the wheels to be built and uploaded, to be sure the release is done.

**Comment by saimn** [comment]
@MeeseeksDev backport to main

**Pull request merged**
