### PR TITLE
Avoid dirty index with RTD

### PR DESCRIPTION
**Pull request by saimn**
The version number generated by setuptools_scm for tags is not clean (e.g. Astropy v5.4.dev0+g2739197e6.d20230522 instead of v5.3) because RTD modifies some files:
https://docs.readthedocs.io/en/stable/build-customization.html#avoid-having-a-dirty-git-index

### Description

This pull request is to address ...

Fixes #<Issue Number>

### CODE REVIEW

**Comment by saimn** [comment]
The build didn't start (and same on main at the same time) so hopefully just a random RTD error. I restarted it.

**Comment by pllim** [comment]
Well, I encountered https://github.com/readthedocs/readthedocs.org/issues/10343 on latest... Hopefully it goes away soon. 😿

**Comment by saimn** [comment]
The build passed ;).

**Review by pllim — APPROVED** [review]
I cannot tell if it is really working or not because it is showing dev tag on a PR as it is supposed to. I guess we won't know until the next release? 🤷‍♀️ 

Thanks!

**Pull request merged**
