### PR TITLE
Fix problem reading a zero-length ECSV table with a bool type column

### LINKED ISSUE #5009: Error opening ECSV table with empty boolean column
Hi,

I am experiencing an annoying bug with the Table class.
When I save an empty Table with an arbitrary number of columns, where at least one column is of boolean type, with the ascii.ecsv format, re-opening this table will result in the following error: "ValueError: Column column_name failed to convert".
This does not happen if there is no column of type 'bool'.

### PR DESCRIPTION
**Pull request by taldcroft**
Fixes #5009.

### CODE REVIEW

**Comment by taldcroft** [comment]
This should be backported to 1.0.x.

**Comment by astrofrog** [comment]
@taldcroft - I think the changelog entry is in the wrong section.

**Comment by taldcroft** [comment]
@astrofrog - yes, I was thinking 1.2 at the time of writing.  Will fix.  I started thinking about the improved changelog system.  The current one drives me batty and I'm motivated to fix this.

**Comment by astrofrog** [comment]
@taldcroft - sounds great - in the mean time, I have a bot that would have chased you up if you had merged the pull request as-is :)

**Comment by taldcroft** [comment]
@astrofrog - done.  If you want to look at this and merge then great, otherwise I assigned @hamogu as the io.ascii deputy.

**Comment by mhvk** [comment]
Looks good to me, so might as well merge.

**Pull request merged**
