### PR TITLE
EXP: Use pytest-faulthandler to track possible segfault

### PR DESCRIPTION
**Pull request by pllim**
**DO NOT MERGE**

See if this uncovers why numpy dev job is hanging.

### CODE REVIEW

**Comment by mhvk** [comment]
Nice try, but no luck...

**Comment by pllim** [comment]
Nope. Any other ideas? Can't be the MPL backend this time since astropy/ci-helpers#361 has been done upstream?

**Comment by bsipocz** [comment]
Try to remove `MATPLOTLIB_VERSION=dev`. If that solves it, report upstream ;)

**Comment by bsipocz** [comment]
(however the circleCI mpldev image testing passes, so I'm a bit puzzled)

**Comment by pllim** [comment]
> circleCI mpldev image

How often is the image updated? 🤔

**Comment by bsipocz** [comment]
Well, it suppose to install the latest master of matplotlib, it's not part of the image. I'm not sure how often the generated images need updating, hopefully not too often, mpl is actually pretty good with consistency.

**Comment by pllim** [comment]
Removing MPL dev did not change anything.
```
Installed /home/travis/build/astropy/astropy/.eggs/psutil-5.4.8-py3.6-linux-x86_64.egg
/tmp/astropy-test-n0ioc5xg/lib/python3.6/site-packages/astropy/conftest.py:43: MatplotlibDeprecationWarning: 
The examples.directory rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2. In the future, examples will be found relative to the 'datapath' directory.
  matplotlibrc_cache.update(matplotlib.rcParams)
```

**Comment by bsipocz** [comment]
Oh, well, then it must be numpy, resulting my wisdom to come to an end.

**Comment by pllim** [comment]
Ops, I might have modified the wrong job! Trying again... 🤞

**Comment by pllim** [comment]
Update: Okay, looks like it might be matplotlib after all. The numpy dev job is failing at the different spot now:
```
Searching for pytest-doctestplus>=0.2.0
Reading https://pypi.org/simple/pytest-doctestplus/
Download error on https://pypi.org/simple/pytest-doctestplus/: '' -- Some packages may not be found!
Couldn't find index page for 'pytest-doctestplus' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for pytest-doctestplus>=0.2.0
error: Could not find suitable distribution for Requirement.parse('pytest-doctestplus>=0.2.0')
```

@drdavella ?

**Comment by drdavella** [comment]
Restarted, now there are actually test failures.

**Comment by bsipocz** [comment]
Ahh, we got into an infinite loop then. The `np.asscalar` deprecations have been fixed in mpl dev, but here we cannot use that version for TBD reason.

So, if we ignore that and the skimage failure, there is only one remaining, and I believe #8264 fixes that.
https://travis-ci.org/astropy/astropy/jobs/467202080#L1980

**Comment by pllim** [comment]
Sigh, so there is nothing we can do to fix the numpy dev build without much pain?

**Comment by bsipocz** [comment]
well, we can report the mpl segfault upstream and hope it's something critical for them ;)

**Pull request closed without merging**
