### PR TITLE
Revert 7186664e, which broke the old config API.

### PR DESCRIPTION
**Pull request by mdboom**
This was a performance enhancement only, so should have no other negative effects.

### CODE REVIEW

**Comment by mdboom** [comment]
@keflavich: I've confirmed that this fixes the tests on astroquery master.

**Comment by keflavich** [comment]
Thanks.  I'll test against this branch for now, but I'll still need to wait for the merge to get travis green again.

**Comment by embray** [comment]
:+1:

**Comment by mdboom** [comment]
I understand there's some urgency for this on the astroquery end, so I'll probably merge this immediately after Travis passes.

**Comment by embray** [comment]
Do we need to release v1.0.2?

**Comment by mdboom** [comment]
This breaks configuration items for affiliated packages that use configuration items anywhere but at the top-level.  I don't know how many affiliated packages that falls into.  I can try to answer that question.  astropy/package-template#122 will help for any affiliated packages in that boat, but of course that's decidedly inelegant.

**Comment by mdboom** [comment]
It only affects astroquery, and as there is a monkey-patch workaround for astroquery (astropy/astroquery#503), I'd say a 1.0.2 isn't urgent.

**Pull request merged**
