### PR TITLE
Adding python 3.7-dev to the travis matrix

### PR DESCRIPTION
**Pull request by bsipocz**
The release is almost out, so adding this now won't hurt. If it fails I'll move it to the allowed to fail section

### CODE REVIEW

**Comment by saimn** [comment]
Looks like h5py is not yet compatible. Shall we run tests with fewer dependencies?

**Comment by bsipocz** [comment]
@saimn - Yes, I'm removing any that is not yet available.

**Comment by saimn** [comment]
It seems that many packages are not yet ready:

>  Failed building wheel for pyyaml
  Failed building wheel for pandas
  Failed building wheel for bintrees
  Failed building wheel for scikit-image
  Failed building wheel for scipy
  Failed cleaning build dir for scipy

**Comment by bsipocz** [comment]
@saimn @pllim - I'm not sure how to proceed here, put it into allowed to fail and wait for fixes in follow-up PR, or do those PR against this one and merge once everything passes?

**Comment by pllim** [comment]
IMHO we can just wait until `conda` catches up. I doubt everyone is going to suddenly upgrade to Python 3.7 the day it comes out. I would even be so bold to propose a 2-week window *after* Python 2.7 release to do any remaining compatibility work on our side (they would be high priority then, of course). What do you think?

**Comment by saimn** [comment]
Maybe we can wait until the first release candidate ? This should come at the end of may: https://www.python.org/dev/peps/pep-0537/#id5

**Comment by saimn** [comment]
Python 3.7.0rc1 is available, and final version scheduled to 2018-06-27, so it would be good to test in the coming weeks. Not sure if it is available with conda though.

**Comment by pllim** [comment]
Thanks for the update @saimn . FWIW I restarted the Travis CI build here. :crossed_fingers:

**Comment by pllim** [comment]
Still failed. FYI https://travis-ci.org/astropy/astropy/jobs/373754558

**Comment by bsipocz** [comment]
Some of the failures we see look the same that @saimn has reported upstream (https://github.com/cython/cython/issues/2043) and that has hopefully been addressed in the latest cython release.  (Failures were seen with 0.27.3)

**Comment by pllim** [comment]
Your pinning didn't work? From https://travis-ci.org/astropy/astropy/jobs/392732161
```
Cython: 0.27.3
```

**Comment by pllim** [comment]
Python 3.7 was released today. FYI

**Comment by pllim** [comment]
(Sorry, press wrong button, hence the accidental closing.)

**Comment by mhvk** [comment]
@bsipocz - the conflict is because of the numpy>=1.13 merge, which adjusted `.travis.yml`. Possibly a good excuse to double-check that you like the changes I made.

**Comment by pllim** [comment]
I was about to rebase and push it back out here.

**Comment by pllim** [comment]
Update: I changed my mind and opened #7607 instead. I went the lazy route and squashed commits and moved things around, so I'd rather we have multiple PRs than losing history here.

**Comment by pllim** [comment]
My attempt over at #7607 did not get very far. It looks like we might have to give the world a few weeks to make packages available here and there.

**Comment by mhvk** [comment]
You mean https://github.com/numpy/numpy/issues/11418?

**Comment by mhvk** [comment]
@bsipocz - #7617 should have fixed at least the astropy-related problems, so maybe worth reviving this one! Note that I removed the `no-changelog-needed` label since somewhere we should mention that we now support 3.7, and this PR seemed as good as any - though I'm quite happy to have a new issue for that if that works better.

**Comment by saimn** [comment]
Sadly Travis support for Python 3.7 is not ready yet: https://github.com/travis-ci/travis-ci/issues/9815
Any idea for the conda side ? I think I read that they now have Python 3.7, though the scientific packages are maybe not yet ready.

**Comment by bsipocz** [comment]
closing in favour of #7617

**Pull request closed without merging**
