### PR TITLE
BUG: Ensure |jd2|<=0.5 

### LINKED ISSUE #9533: Time scale conversion violates |jd2|<=0.5
### Description

Upon construction, all Time objects contain two double-precision values, `jd1` and `jd2`. These satisfy, and are tested to satisfy, the invariant that `jd1` is an integer, `abs(jd2)<=0.5`, and if `abs(jd2)==0.5` then `jd1` is even. This is enforced by application of the not-publicly-documented function `day_frac`. 

When a Time object is converted from one timescale to another, though, under some circumstances `abs(jd2)>0.5`. 

```python
>>> from astropy.time import Time
>>> t = Time(2441316.5, 0, scale='tai', format='jd')
>>> t.tcb.jd2
0.500344155968967
```

This was revealed by #9532 .

### Expected behavior

`t.tcb.jd2` should be made less than 0.5 by calling `day_frac`.

### Actual behavior

The value violates the invariant.

### System Details

```python
$ python
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-5.0.0-31-generic-x86_64-with-Ubuntu-19.04-disco
>>> import sys; print("Python", sys.version)
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.17.1
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.3.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.0.dev26770
>>>
```

### PR DESCRIPTION
**Pull request by aarchiba**
### Description

Ensures format conversion leaves abs(jd2)<=0.5

EDIT: Fix #9533

### CODE REVIEW

**Comment by bsipocz** [comment]
test failures are related

**Comment by mhvk** [comment]
This looks good, though I'm a bit puzzled at the error - maybe it is just a matter of increasing `atol` in this case... I think we also need a test case that checks that the PR does what it intends to (can just be the example you found in #9533)

cc @taldcroft - this PR ensures abs(jd2)<=0.5 always - this was not something we ever guaranteed though we definitely have been trying to make it true, at least on input, on addition/subtraction, etc. Here, it adds a bit of time to every scale change; on balance, I think this is worth it, but would be good to have your input as well.

**Comment by aarchiba** [comment]
> This looks good, though I'm a bit puzzled at the error - maybe it is just a matter of increasing `atol` in this case... I think we also need a test case that checks that the PR does what it intends to (can just be the example you found in #9533)

No, that's not it. You'll notice that the difference being raised is between -0.4999... and +0.5. The problem is that the code there (as in many other places) assumes that jd1 is an integer and jd2 the fractional part, and does the comparison on jd2 only. (jd1_a-jd1_b) + (jd2_a-jd2_b) would be fine - but I'm not sure that the rest of the test will still work, because it may well rely on assumptions about jd1 and jd2. I'll chase it down but it demonstrates the sort of way people build in assumptions about the possible values for jd1 and jd2 - so whether we actually made the guarantees or not, people - us! - have built them into code that uses astropy. So allowing scale conversion to subtly violate the conditions on jd2 is just asking for trouble. It is only efficiency concerns, and other assumptions about sharing of data, that keep me from wanting to make day_frac part of the jd1/jd2 validation applied to all time formats.

**Comment by aarchiba** [comment]
Should this have a changelog entry?

**Comment by mhvk** [comment]
I don't think a changelog entry is needed - I'm happy to move this direction but perhaps best to keep it an "implementation detail" for now.

**Comment by mhvk** [comment]
@taldcroft - are you OK with this?

**Pull request merged**
