### PR TITLE
For convolve(boundary=None) raise exception if kernel larger than array

### LINKED ISSUE #7310: convolve boundary=None segfaults with kernel larger than array
The following code segfaults.
```python
import faulthandler
import astropy.convolution
import numpy as np

faulthandler.enable()

image = np.random.random(11)
ker = astropy.convolution.Gaussian1DKernel(20,x_size=41)

astropy.convolution.convolve(image, ker, boundary=None)
```
This is due to the following code ([src](https://github.com/astropy/astropy/blob/6e433c62d4714238c186cdd1d45eabbe9c3b77c5/astropy/convolution/boundary_none.pyx#L33-L43)):
```cython
...
cdef  unisgned int i, ii
...
for i in range(wkx, nx - wkx):
...
```
Since `i` is unsigned `nx - wkx` yields a very large and positive number for `wkx > nx`. If `i` were signed this would not be a problem and no iteration would occur and the func would simply return an empty array. However, `unsigned` is totally needed here since it is used to access `conv[i]`.

This is fixed by #7293 by adding a check in [convolve](https://github.com/jamienoss/astropy/blob/e11e8b2e28aa86fb6d1d83cd9f06dc338d90aac8/astropy/convolution/convolve.py#L253-L265):
```Python
...
    # For boundary=None only the center space is convolved. All array indices within a
    # distance kernel.shape//2 from the edge are completely ignored (zeroed).
    # E.g. (1D list) only the indices len(kernel)//2 : len(array)-len(kernel)//2
    # are convolved. It is therefore not possible to use this method to convolve an
    # array by a kernel that is larger* than the array - as ALL pixels would be ignored
    # leaving an array of only zeros.
    # * For even kernels the correctness condition is array_shape > kernel_shape.
    # For odd kernels it is:
    # array_shape >= kernel_shape OR array_shape > kernel_shape-1 OR array_shape > 2*(kernel_shape//2).
    # Since the latter is equal to the former two for even lengths, the latter condition is complete.
    if boundary == None and not np.all(array_shape > 2*pad_width):
        raise KernelSizeError("for boundary=None all kernel axes must be smaller than array's - "
                              "use boundary in ['fill', 'extend', 'wrap'] instead.")
...
```
and the [C code for boundary=None](https://github.com/jamienoss/astropy/blob/e11e8b2e28aa86fb6d1d83cd9f06dc338d90aac8/astropy/convolution/boundary_none_direct.c#L159-L161):
```c
...
const unsigned _wkx = _nkx / 2;
if (!(_nx > 2*_wkx))
       return;
...
```

### PR DESCRIPTION
**Pull request by jamienoss**
Resolves #7310

Signed-off-by: James Noss <jnoss@stsci.edu>

### CODE REVIEW

**Comment by jamienoss** [comment]
I'm wondering whether you'll like this, more C'ish than Python'ish. The check could have been added into `convolve()` and remained as pure Python, however, the Cython functions can be called independently, in which case, checks within these functions are required anyhow.

**Comment by bsipocz** [comment]
@keflavich - I've milestoned it to the LTS, but if it only affected 3.0, please move it to 3.0.2

**Comment by jamienoss** [comment]
@bsipocz & @keflavich 
This affects [v2.0.5](https://github.com/astropy/astropy/releases/tag/v2.0.5). I've moved the changes in `CHANGES.rst` to the relevant 2.0.6 section.

**Comment by jamienoss** [comment]
Do you guys need me to open another PR against the correct base or do you prefer to backport?

**Comment by bsipocz** [comment]
@jamienoss - This is fine as is, the normal way is to do backports and we only open PRs to the bugfix branches when they are unavoidable for some reason.

**Comment by pllim** [comment]
Since this is approved and tests passed, merging. Thank you for the fix!

**Pull request merged**
