### PR TITLE
Use Python/C API instead of Cython for ERFA wrappers

### PR DESCRIPTION
**Pull request by mdboom**
This updates #3164 to use the new division of labor between Python and Cython, so the C side is even smaller now.

### CODE REVIEW

**Comment by embray** [comment]
Looks good to me.  I'm still hoping to complete #3181 at some point too once I have a chance to figure out a bytecode caching workaround.  But I don't think it will conflict terribly with these changes.

**Comment by mhvk** [comment]
Like the approach, but cannot really judge the implementation. Just to be sure something silly doesn't get passed by: numpy `c` code is full of `Py_INCREF` and `Py_DECREF` -- does the `NPYITER` stuff automatically take care of that for these purposes?

**Comment by mdboom** [comment]
The only `PyObject` involved here is what's passed in (`args`) which is a borrowed reference (i.e. it doesn't need to be `DECREF'd` on exit.  `NpyIter` is not a `PyObject`, so doesn't have a reference count.

**Comment by embray** [comment]
I think this is pretty uncontroversial at this point.  I see no reason not to merge.

**Pull request merged**
