### PR TITLE
Fix EarthLocation latex repr

### LINKED ISSUE #4542: Ipython Notebook and EarthLocation representation warning/error
I tried to get the ``EarthLocation`` and print the representation of it and it works (it returns the correct representation) but it also raises an Error:

```
from astropy.coordinates import EarthLocation
a = EarthLocation.of_site('Paranal Observatory')
a
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Programming\Anaconda\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    339             method = _safe_get_formatter_method(obj, self.print_method)
    340             if method is not None:
--> 341                 return method()
    342             return None
    343         else:

C:\Programming\Anaconda\lib\site-packages\astropy\units\quantity.py in _repr_latex_(self)
   1030                                               style=Latex.format_exponential_notation,
   1031                                               max_line_width=np.inf,
-> 1032                                               separator=',~')
   1033                 latex_value = latex_value.replace('...', r'\dots')
   1034             finally:

C:\Programming\Anaconda\lib\site-packages\numpy\core\arrayprint.py in array2string(a, max_line_width, precision, suppress_small, separator, prefix, style, formatter)
    439         if isinstance(x, tuple):
    440             x = _convert_arrays(x)
--> 441         lst = style(x)
    442     elif reduce(product, a.shape) == 0:
    443         # treat as a null array if any of shape elements == 0

C:\Programming\Anaconda\lib\site-packages\astropy\units\format\latex.py in format_exponential_notation(cls, val)
    103             The value in exponential notation in a format suitable for LaTeX.
    104         """
--> 105         if np.isfinite(val):
    106             m, ex = utils.split_mantissa_exponent(val)
    107 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
<EarthLocation (1946618.261025452, -5467645.090548764, -2642488.447714588) m>
```

I'm using astropy 1.1.1, numpy 1.10.1.

### PR DESCRIPTION
**Pull request by eteq**
This fixes #4542 by making a custom `EarthLocation._repr_latex_` that handles the situation for just that class.

I thought about doing a more general fix in `Quantity._repr_latex_` for structured arrays of many sorts, but after thinking about it realized we probably don't want to typically do this anyway, so better to just special-case `EarthLocation`.

cc @mhvk 

This is a straightforward bug fix, so I've put it in for 1.2.0, but is not critical so if it doesn't seem ready by release time that's fine too and can be pushed to 1.2.1 (@astrofrog)

### CODE REVIEW

**Comment by eteq** [comment]
not sure why the "many" test is different locally vs on travis (maybe some kind of rounding?), but I think it's not worrying too much because all the travis builds seemed to agree.  The values aren't really what matter anyway, so I changed it to check for all the key elements.

**Comment by mhvk** [comment]
@eteq - with this, the representation becomes quite different from the normal `__repr__`. I don't think that is a bad idea as such, but if we are changing it, would it not make more sense to make representations in any style more like `CartesianRepresentation`? Ideally, at some point that will become the superclass... Sadly, though, the latter does not have `_repr_latex_` yet...

My suggestion is for now to just ensure that `EarthLocation._repr_latex_()` works, without worrying about exponential notation (which generally is not needed anyway, at least not in the default units of m or km) -- see #5068.

**Comment by astrofrog** [comment]
Sorry, I missed this when preparing 1.2rc1 (which is now out). Can you rebase?

@eteq - is this release critical, or can it now be delayed till 1.2.1? (just to determine where the changelog entry should go)

**Comment by eteq** [comment]
Closing this in favor of the approach in #5068

**Pull request closed without merging**
