### PR TITLE
Use weak references in modeling

### PR DESCRIPTION
**Pull request by nden**
This is an attempt to make `Parameter._model` a weak reference with the goal to reduce memory usage. The circular references Model --> Parameter --> Model do not allow memory to be cleaned.
Implementing `Parameter._model` as a weakref helps and memory is now released. 

This PR stops support for inheriting constraints in compound models when the submodels are classes (not instances of models) and removes a test for this.

### CODE REVIEW

**Comment by pllim** [comment]
I like this in principle. Did you ever get to solve the `model[1].mean` problem?

**Comment by nden** [comment]
@pllim Yes, accessing submodels by indexing the compound model is resolved now. There's one failing use case which I tend to think we should not support. It's the case of a compound model initialized by model classes (not instances of models) and then trying to change parameters on the component members.

**Comment by nden** [comment]
Oh , and whil ethis resolves the cyclic references I can't see that it makes the improvement in memory release that I was hoping for. Especially on py 3.6 memmory seems to be released anyway. I need to look more into this.

**Comment by astrofrog** [comment]
There was a bug in the bot, it should not have been closed without the warning so re-opening.

**Comment by bsipocz** [comment]
@nden  - is this still  on the table? The bot didn't behave correctly and now it may have been unnoticed having the `keep-open` label and also the future milestone.

**Comment by pllim** [comment]
Probably superseded by @perrygreenfield 's refactoring over at #8769 ?

**Comment by nden** [comment]
Not needed after the refactoring

**Pull request closed without merging**
