### PR TITLE
Another fix for #4164

### PR DESCRIPTION
**Pull request by embray**
For some reason I botched #4178 in that it did not include a version of astropy-helpers that actually addressed #4164 (I was simultaneously testing other, unrelated updates to astropy-helpers, and probably confused myself at some point along the line).

I have no rebased astropy/astropy-helpers#190 on the master branch of astropy-helpers, and this PR points the astropy-helpers submodule to the correct commit so that it includes those fixes.

### CODE REVIEW

**Comment by embray** [comment]
OK, confirmed that this fixes the issue on master--both locally and in the CI builds the issue reported in #4164 is worked around.

**Comment by bsipocz** [comment]
I still see it on the quasi current master (Astropy version 1.1.dev13549 as it keeps changing very quickly today). The helper is at c1e28c72168461b530a909ce928e786551b0034f

**Comment by embray** [comment]
@bsipocz You might be confusing this with a slightly different issue.  There is still an issue where the `--verbose-results` flag is on by default--see astropy/astropy-helpers#192--but that's actually completely unrelated to this issue.

**Comment by bsipocz** [comment]
@embray - Yes, but I still see the super long paths, etc like this:

```
//private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/astropy-test-hybNYh/lib.macosx-10.10-x86_64-2.7/astropy/units/tests/test_format.py::test_cds_grammar_fail::[10] <- private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/astropy-test-hybNYh/lib.macosx-10.10-x86_64-2.7/astropy/tests/helper.py PASSED
//private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/astropy-test-hybNYh/lib.macosx-10.10-x86_64-2.7/astropy/units/tests/test_format.py::test_cds_grammar_fail::[11] <- private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/astropy-test-hybNYh/lib.macosx-10.10-x86_64-2.7/astropy/tests/helper.py PASSED
```

**Comment by embray** [comment]
@bsipocz Okay, sorry for doubting you.  It looks like this might still not be fixed on OSX for some reason. I don't know why it would be any different on OSX but apparently it is?

**Pull request merged**
