### PR TITLE
What's new in 1.1?

### PR DESCRIPTION
**Pull request by astrofrog**
Things to add to 'What's new in 1.1?':

* Table import/export from/to Pandas DataFrame https://github.com/astropy/astropy/pull/3504

### CODE REVIEW

**Comment by astrofrog** [comment]
I have added preliminary sections for some of the new features here.

@eteq - can you crunch the numbers again for contributors, etc.?

For now, anyone can open pull requests against my branch to make any fixes, or add any new sections.

This doesn't have to be merged before the feature freeze, but the sooner we do it the better.

**Comment by mhvk** [comment]
Numpy 1.10 has just been released -- I really hope we can support that in our 1.1. Only issue holding it up is #3854, for which I think @embray knew what to do, but hasn't gotten around to it. (It is really a bug fix, so should not be affected by the feature freeze.)

**Comment by eteq** [comment]
I agree with @mhvk that numpy 1.10 support is probably critical (as long as it isn't going to take weeks to figure out)

**Comment by astrofrog** [comment]
I agree, it should be a top priority to fix and we really want it in 1.1.

**Comment by embray** [comment]
I should be able to get the last kinks with Numpy 1.10 worked out by today or tomorrow.

**Comment by taldcroft** [comment]
What about a section on Table indexing?  @mdmueller - do you have time to put in a short PR?  Maybe just a short example showing creating an index on string column (maybe a table of source names?) and then selecting with `loc`.

**Comment by mdmueller** [comment]
@taldcroft Sure! I'll send out an email on the mailing list about indexing as well.

**Comment by eteq** [comment]
@astrofrig - I just submitted a PR to this branch updating the stats (and with one minor fix)

**Comment by eteq** [comment]
@mdmueller - can you try to get a PR against @astrofrog's branch for the table indexing? (Or @taldcroft ?)

**Comment by eteq** [comment]
@astrofrog - should probably add mention of support for wcslib 5.x as @mdboom suggested above - the key thing that adds is support for WCS paper IV distortion descriptions.

@mhvk - do you think you can make a quick PR to @astrofrog's branch here adding mention of the FITS Time stuff? (Or is just "Time now supports FITS-style strings" is enough?)

**Comment by mhvk** [comment]
@eteq - I think the one sentence is enough for now; more would be good if we support all FITS time structures (i.e., also as table columns, etc.; i.e., all of #3000)

**Comment by astrofrog** [comment]
@eteq @mhvk - just to check, there isn't anything currently in this PR (not even one sentence) for the FITS format in Time. Do you mean that we don't need to add anything here and the main docs are enough?

**Comment by mhvk** [comment]
@astrofrog - I meant that @eteq's suggested single sentence "Time now supports FITS-style strings" was indeed enough.

**Comment by astrofrog** [comment]
@mhvk - I'm not sure if it's worth adding a whole section in the what's new just for one sentence, so maybe we can just leave this one out?

**Comment by mhvk** [comment]
@astrofrog - I agree, without full support for fits tables it is fine to leave this out of the highlights.

**Comment by taldcroft** [comment]
FYI made a PR on @astrofrog's branch for Table indexing: https://github.com/astrofrog/astropy/pull/56

**Comment by astrofrog** [comment]
@mdboom @mhvk @eteq - I've added notes on WCSLIB 5.x and the FITS-formatted time strings

**Comment by mhvk** [comment]
@astrofrog - great, just about the right amount of call-out!

**Comment by taldcroft** [comment]
Maybe the initial list of new features should go in an itemized list now?  It's getting a bit long.

**Comment by astrofrog** [comment]
Yes, let me tidy up the initial list now so we can go ahead and merge it.

**Comment by astrofrog** [comment]
@eteq - done, feel free to merge once Travis passes

**Comment by eteq** [comment]
Backported to v1.1.x in 241120f

**Pull request merged**
