### PR TITLE
TST: do not ignore numpy warnings in votable tests

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
I was curious to see if reverting #13343 was safe now (it seems to, at least locally). Let's see if CI explodes if I remove those context managers...

note: even if it does work, I'll need to finish the cleanup. For now I just did that one file.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
seems to be doing okay, let's clean the rest of them

**Comment by pllim** [comment]
Let's run the cron jobs too, just in case...

**Comment by taldcroft** [comment]
@neutrinoceros - I took myself off the review requests and added VOtable maintainers (from https://www.astropy.org/team.html). I know nothing about this package! :smile:

**Comment by pllim** [comment]
The warnings are still in the "exotic" archs. I don't think this is worth our time pursuing.

**Comment by neutrinoceros** [comment]
Agreed. Might as well close it now then. Thanks for checking !

**Comment by pllim** [comment]
Thanks for trying!

**Pull request closed without merging**
