### PR TITLE
Replace relative import in docstring

### PR DESCRIPTION
**Pull request by hamogu**
### Description
Relative imports in the docstring are not helpful when reading the
rendered docs. Furthermore, it seems that this particular import
is not even used, so this PR replaces is with an absolute import.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
LGTM. Good catch, thanks!

**Comment by hamogu** [comment]
I have no idea how this failure could have anything to do with my changes. Any suggestion how to get rid of it?

**Comment by pllim** [comment]
You can ignore the plotting failures. astropy/astropy#11267

Merging. Thanks!

**Comment by astrofrog** [comment]
Updating milestone as the relative import was not in LTS

**Pull request merged**
