### PR TITLE
Fix hard-to-debug import issues.

### PR DESCRIPTION
**Pull request by mhvk**
Fixes the very annoying import of all of coordinates when just wanting to load `io.ascii`, which in turn led to `Time` being updated, etc.

Thanks @taldcroft for figuring this out (and again apologies for causing the issue in the first place).

### CODE REVIEW

**Comment by mhvk** [comment]
Merge only when also CI 32 bit passes!

**Comment by mhvk** [comment]
Good, that got rid of two problems! Now if only I hadn't caused them in the first place...

**Comment by mhvk** [comment]
@taldcroft - out of curiosity, how will the custom attributes help? Maybe open an issue about it so we know to do it?

**Comment by taldcroft** [comment]
In Python 3.7 you can have a module-level `__getitem__`.  So that means `__construct_mixin_classes` can be an on-demand attribute of the module that only gets evaluated when it is needed.  At first glance it seems like that would reduce some of the circular import problems, though to be honest I haven't followed the logic enough to be sure.

**Comment by taldcroft** [comment]
I think we will support only Python 3.7+ for the first astropy release that is supported beyond 2021-12-23, which is the Python 3.6 end of support.  So that is probably the Fall 2021 release.

**Comment by mhvk** [comment]
Ah, yes, I had see that - but had not realized it could (or at least should) work for things like this.

**Comment by bsipocz** [comment]
I think the switch is earlier than end of 2021, at least there was some vague agreement to follow NEP29 which drops 3.6 this summer (so we can practically start cleaning up the code in the middle of the summer in prep for 4.2).

**Pull request merged**
