### PR TITLE
BLD: Do not use setuptools 71.0.0 or 71.0.1

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to see if pinning setuptools would resolve mysterious CI failures.

xref #16745

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Well, CI is green so far... 🤷‍♀️

**Comment by pllim** [comment]
One exotic arch passing is enough, no need to wait for all of them, I don't think.

**Review by neutrinoceros — CHANGES_REQUESTED** [review]
The problem is with importing setuptools at runtime, so we shouldn't bake those constraints into our build time dependencies. Furthermore, Astropy itself doesn't depends on setuptools at runtime, so if anything, this should be added as a constraint or a requirement in test deps.
Fortunately, it seems that the release of setuptools 71.0.2 resolved the issue, which is why CI is green here.

**Comment by pllim** [comment]
Thanks for the update. Closing without merge then!

**Pull request closed without merging**
