### PR TITLE
Redo: split pytest plugins into individual modules

### PR DESCRIPTION
**Pull request by drdavella**
I took @cadair's work from #5770 and rebased it on the current `master`. The tests pass for me locally in both Python 2.7 and 3.6, but maybe integration testing will reveal some issues that I missed. It might be good to consider this WIP for the moment.

### CODE REVIEW

**Comment by drdavella** [comment]
I think @pllim and @bsipocz are already aware, but for selfish reasons I would eventually like to see the testing module split out into a separate package.

**Comment by bsipocz** [comment]
Splittig out the test was the plan with #5770 and the gsoc project idea, so definitely a 👍 from me.

**Comment by Cadair** [comment]
Thanks for picking this up @drdavella !

**Comment by astrofrog** [comment]
Note that the flake8 failure is real:

```
astropy/tests/pytest_doctestplus.py:341:1: W391 blank line at end of file
```

**Comment by bsipocz** [comment]
@Cadair - you've never rebased it. We since removed np1.7, the coverage test failure seems to be passing in fact, and the third one might have been fixed by the removal of the bundled pytest version...

**Comment by Cadair** [comment]
ah bundled pytest. I am going to go ahead with the self-reinforcing belief that that was what it was ;)

**Comment by drdavella** [comment]
I don't think this PR needs to be considered WIP anymore.

**Comment by astrofrog** [comment]
Thanks @drdavella and @Cadair!

**Pull request merged**
