### PR TITLE
Fix TDISP parsing for floating numbers

### LINKED ISSUE #16006: Some FITS table columns are displayed incorrectly: float numbers shown as as integers
### Description

In some cases, float column data in a FITS file is displayed as integers.

### Expected behavior

_No response_

### How to Reproduce

The Phase column is displayed as integers in the following example.

```python
from astropy.table import QTable

# Source: https://cdsarc.cds.unistra.fr/viz-bin/VizieR-5?-ref=VIZ65c404d1191e98&-out.add=.&-source=J/A%2bA/617/A32/list&recno=3013
tab = QTable.read("https://cdsarc.cds.unistra.fr/viz-bin/nph-Cat/fits?-plus=-+&J/A%2BA/617/A32/lc/d1679016.dat")

print(tab[:2])  # Phase displayed as rounded to 0 or 1

print(tab["Phase"][0])  # the actual value is correct

print(tab["Phase"].dtype, tab["Phase"].format)  # the display format is incorrect
```

```python
      HJD          LST         mag       e_mag      Phase    
       d            h          mag        mag                
--------------- ---------- ----------- --------- ------------
2457056.7444790 13.5554768   0.0354285 0.0058704            0
2457056.7481729 13.6443657   0.0463362 0.0060671            0

0.0497846909

float64 {:12.0f}
```

### Versions

Windows-10-10.0.22621-SP0
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:01:37) [MSC v.1935 64 bit (AMD64)]
astropy 6.0.0  , also on that latest `main`
Numpy 1.26.3
pyerfa 2.0.1.1
Scipy 1.11.4
Matplotlib 3.8.2

### PR DESCRIPTION
**Pull request by saimn**
Fix #16006. (cc @orionlee)

### Description

This pull request is to address ...

Fixes #<Issue Number>

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by neutrinoceros — APPROVED** [review]
I was just about to post the same exact fix, well done !

**Review by pllim — APPROVED** [review]
Thanks!

**Comment by orionlee** [comment]
Format `ES`/ `EN` has the same problem. Should it be fixed in another PR?

https://github.com/astropy/astropy/blob/fe0366367a0145681e7ebffeeec6209247e8311e/astropy/io/fits/column.py#L114-L116

**Comment by pllim** [comment]
Yeah sorry if I merged it too fast. Please open a follow-up PR. Thanks!

**Pull request merged**
