### PR TITLE
clarify the state of the ipython astropy.test() failures

### LINKED ISSUE #717: Exception logging tests failing in ipython
On both Astropy master and on the v0.2.x branch, when I run `astropy.test()` from an IPython prompt I get failures in the `test_exception_logging` and `test_exception_logging_origin` tests.

Based on what I can tell from the debugging I've done so far, upon first import the exception logging hook _does_ get installed properly through the IPython exception handling mechanisms.  But somewhere in the course of the tests (and this happens even when just testing the 'tests' package) `sys.excepthook` is being reset to the original built in hook.

### PR DESCRIPTION
**Pull request by eteq**
This is pretty trivial of a change, but makes it in line with the known issues, and much more importantly, closes #717

### CODE REVIEW

**Review by pllim — APPROVED** [review]
LGTM. Thanks!

**Comment by dhomeier** [comment]
Are the 4 "problematic" warnings in readthedocs the mpl-dev related ones as well?

**Comment by pllim** [comment]
RTD -- I only saw the `MatplotlibDeprecationWarning` that is unrelated to this PR.

**Comment by dhomeier** [comment]
It's always unclear which warnings cause it to fail, since it is also printing all the WCSLIB `datfix` warnings (which should be ignored currently); but there are 4 of the `MatplotlibDeprecationWarning`s, which fits...

**Comment by pllim** [comment]
> It's always unclear to me which warnings cause it to fail

Yes, I don't understand it completely myself either, but this time, I am pretty sure it is `matplotlib`.

**Pull request merged**
