### PR TITLE
Make footprint_to_file more useful

### PR DESCRIPTION
**Pull request by saimn**
I discovered `WCS.footprint_to_file` recently while looking for a similar method, but found a few issues that I attempt to fix here:

- The default coordinate system was 'linear', which was not working with aplpy/pyregion. Instead I changed to use by default the one from `wcs.radesys` (typically ICRS or FK5) and added a new parameter to allow to overwrite this coordinate system. See the [supported coordinate systems](http://ds9.si.edu/doc/ref/region.html#RegionFileFormat), is it useful to add a check that the value is correct ?

- When using the method multiple times, the new string were appended to the old ones,  with the global parameters written multiple times. So I changed to overwrite the file ('w' instead of 'a'). I thought about adding a parameter for this, but ideally in append mode this would need to detect if the global parameters are already there to not write them again.

cc @nden

### CODE REVIEW

**Comment by nden** [comment]
@saimn I actually never used this method so I don't know if it's any useful.
Regarding `RADESYS`: it's probably the right approach but there may be cases when it is an empty string, e.g. when CTYPE is `LINEAR`. Should a warning be raised (or perhaps an exception)?

**Comment by saimn** [comment]
It is useful instead of having to do it manually with `calc_footprint`. But indeed I'm not sure that `RADESYS` gives always a valid value for the region coordinate systems, I will add a check and raise an error if the value is not supported.

**Comment by nden** [comment]
LGTM. Merging.

**Comment by saimn** [comment]
Thanks !

**Comment by eteq** [comment]
(this is a new feature/behavior change and hence can't be backported to 1.0.x)

**Pull request merged**
