### PR TITLE
Shorten `astropy/coordinates/angles/__init__.py`

### PR DESCRIPTION
**Pull request by eerovaher**
### Description

I am very much in favor of explicitly defining `__all__`, _except_ in `__init__.py` files. My reasoning is that if all the other files properly define `__all__` (like they do in `angles`) and `__init__.py` files only define a docstring and perform `from ... import *` (like it does in `angles`) then managing `__all__` in `__init__.py` is nothing but boilerplate code.

- [x] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
@nstarman added this in #15220 so maybe he should review?

**Comment by nstarman** [comment]
How does this play well with typing?

**Comment by eerovaher** [comment]
This shortening doesn't seem to be causing any problems for `mypy`, it can still find things defined in `angles`. In fact, the reason I even looked at this file was that I managed to make `mypy` complain that it couldn't figure out the type of `__all__` there.

**Comment by nstarman** [comment]
That's because all should be

```
__all__: list[str] = []
__all__ += ...
```

The angles module is public, right?

**Comment by mhvk** [comment]
> The angles module is public, right?

`astropy.coordinates` follows standard behaviour, so nothing below it is public. I think `__all__` in `__init__.py` maybe simply replaces the original `__all__` when `angles.py` was a single file. It perhaps makes the `from .angles import *` one level up easier, not sure (I see @eerovaher's argument that it is not needed as well).

**Comment by eerovaher** [comment]
@mhvk, do you think you'll have time to review this?

**Review by mhvk — APPROVED** [review]
I'm happy with this, as it shortens it without loss of clarity, but was mostly waiting to see for @nstarman's opinion after your note that mypy does not object.

**Comment by mhvk** [comment]
OK, following @pllim's prompt, let me just merge this, as the style is certainly more consistent with that of the rest of astropy, and we can revisit if we get to a useful end of the discussion of how to use `__all__` more consistently.

**Pull request merged**
