### PR TITLE
Fixed has_celestial and wcs_to_celestial_frame when celestial axes were correlated with other axes

### PR DESCRIPTION
**Pull request by astrofrog**
This also affected the high-level WCS API.

Fixes https://github.com/astropy/astropy/issues/8416

### CODE REVIEW

**Comment by nden** [comment]
This looks good. The only question I have is about the milestone. Can it be ported to 2.x? Or does it have to be ported to the first release with the high level APE14 API?

**Comment by astrofrog** [comment]
This will have to be backported manually to 2.0.x, because the addition of the test in ``test_fitswcs.py`` is not back-portable to 2.0.x (but all the rest is)

**Comment by bsipocz** [comment]
@astrofrog - do you prefer to open a separate PR to 2.0.x? If the complication is only about leaving trivial stuff out from the backport I feel it can be done the usual way anyway, but it's your call.

**Comment by astrofrog** [comment]
I think it can just be done the usual way, it's just one file that needs to be removed, not a particularly complicated backport thankfully.

**Pull request merged**
