### PR TITLE
DOC: Make What's New more discoverable

### LINKED ISSUE #16271: What's new pages are hidden away in docs
With the refactoring of the docs, the what's new pages have become a lot harder to find. I think we should include the latest What's New page under Useful links on the docs front page.

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address make What's New more discoverable as suggested by mhvk.

Fixes #16271

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by mhvk** [comment]
I think this would work - but would be good to check and sadly readthedocs failed...

**Comment by pllim** [comment]
Yes, alas... Will have to get https://github.com/astropy/astropy/pull/16304 in first.

**Review by mhvk — COMMENTED** [review]
Now it passed.

But oddly the links just go to `project details` anyway. It seems everything in the box just goes there, ignoring the links you added...

Two options, I think: somehow turn that off (or give links preference or so), or just change the text without adding links - at least it is much more obvious what to find there...

**Comment by pllim** [comment]
Tsk tsk, a bit annoying that intersphinx does not work as intended in the card... Thanks for the suggestions. Will push out a follow-up commit soon.

**Review by mhvk — APPROVED** [review]
I'm fine with just getting this in!

**Comment by pllim** [comment]
Thanks for the review!

**Comment by astrofrog** [comment]
Maybe we can backport this for 6.1.0?

**Comment by pllim** [comment]
I never know what milestone to use between rc and release... Feel free to re-adjust. Thanks!

@meeseeksdev backport to v6.1.x

**Pull request merged**
