### PR TITLE
Move private tiled compression module to astropy/io/fits/hdu/compressed/

### PR DESCRIPTION
**Pull request by astrofrog**
@saimn - as you suggested 😄 

- [x] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by astrofrog** [comment]
pre-commit.ci autofix

**Comment by saimn** [comment]
Actually I was thinking about removing the `_tiled_compression` layer and putting everything directly in `hdu/compressed/` ;). I mean `hdu.compressed` is also about tile compression, so now that it has been splitted in a subpackage, we can just put everything about tile compression there.

**Comment by astrofrog** [comment]
@saimn - that makes a lot of sense, have done this instead here now.

**Comment by astrofrog** [comment]
@saimn - I had forgotten to update the nitpick exception for the Codec class. Should be fixed now.

**Review by saimn — APPROVED** [review]
LGTM, thanks @astrofrog !

**Pull request merged**
