### PR TITLE
Fixed wrong line terminator issue with csv and ecsv writing

### PR DESCRIPTION
**Pull request by katipallya**
By adding newline='' parameter to file open in io.ascii.

### CODE REVIEW

**Comment by katipallya** [comment]
Just realized newline ='' cannot be used as a fix for Python 2.7 runtime. Fixing this.

**Comment by saimn** [comment]
So this addresses #5299.
@katipallya - This will need a unit test to show the issue and prove that your fix is correct.

**Comment by katipallya** [comment]
Right. Will do.

**Comment by katipallya** [comment]
@saimn How should the unit test show incorrect output if the code is already fixed? This is my first contribution to an open source project so I'm still new to this.

**Comment by pllim** [comment]
> How should the unit test show incorrect output if the code is already fixed?

First you need the test to actually fail without the fix on Windows. Then, you need to make sure the same test passes with the fix on Windows. Of course, you also have to make sure the rest of the tests are not affected (i.e., you did not introduce a new bug).

**Comment by katipallya** [comment]
Okay makes sense. @pllim Do I need to provide some sort of proof that the test fails without the fix through a screenshot or something?

**Comment by pllim** [comment]
> Re: proof.

Theoretically, reviewer can check by running the test in your PR on latest master. But to actually show it in this PR, you can apply the test first as the first commit, wait for CIs to run (and fail), and then apply your fix as second commit (and wait for CIs to pass). Theoretically, only Appveyor will show failure.

**Comment by katipallya** [comment]
I'll do the latter, that makes sense to me. Thanks for the help.

**Comment by katipallya** [comment]
@pllim so my solution works fine for when not using the fast writer but not with the fast writer. do you have any advice for how to work with the fast writing functionality?

**Comment by pllim** [comment]
Sorry, no. But maybe @taldcroft can help?

**Comment by katipallya** [comment]
Also not sure why those builds are failing. What I've changed has nothing to do with what i see in the buildlog.

**Comment by pllim** [comment]
Which log are you talking about exactly? Link to an example please.

**Comment by katipallya** [comment]
Nevermind, I just pushed again and it worked.

**Comment by katipallya** [comment]
https://ci.appveyor.com/project/Astropy/astropy/build/1.0.7283/job/y9qfgyqkpj526yda

Here's the log for the relevant example. Python 3.6, fast_writer being true makes my testcase fail.

**Comment by astrofrog** [comment]
@katipallya - is there a reason you closed this?

**Comment by katipallya** [comment]
@astrofrog 
Still new to github and I messed up by using my master branch here - I plan to reopen this with the correct branch once I have the time. Do you have any ideas on the fast_writer problem?

**Comment by saimn** [comment]
@katipallya - For the fast_reader case, it's probably in the Cython code [here](https://github.com/astropy/astropy/blob/master/astropy/io/ascii/cparser.pyx#L991).

**Pull request closed without merging**
