### PR TITLE
Alias the 3-letter FITS WCS names for projections with longer names

### PR DESCRIPTION
**Pull request by mdboom**
This is on top of #3581, which can go into a point release, but this can't (because it's deprecating a public API).

### CODE REVIEW

**Comment by nden** [comment]
I'm not opposed to this change but also am not sure what is its purpose. Is the purpose only to to "de-FITS-ify" the names but keep the celestial context in them? If so we need a mapping between the FITS codes (`projcodes` in the module) and the new class names. If the purpose is to have general projection names, then why keep the `Pix` and `Sky` part in the names? If we don't keep those, then we get into the differences between what is considered "forward" and "backward" direction of a projection in astronomy and in general.

All I'm saying is that the names sound like FITS but this defines the context in mathematical sense. As a minimum, with the names in this PR we'll need a mapping to the FITS projection codes. However, if we claim these to be truly general, someone has to go over the math and make sure it's really general and does not use simplifications due to the nature of the problem it describes (as was the case with Euler angles).

**Comment by mdboom** [comment]
Yes -- the purpose is to just use more meaningful names since we aren't limited to three characters.  I don't intend to make the projections themselves any more general than what's in FITS, and indeed intend to keep them "FITS-WCS-compatible", in that they do exactly what the FITS paper says, including any errata that are implemented in wcslib/wcstools and elsewhere.

No objection to adding a mapping, of course, that could be used by tools that read and then act on FITS WCS keywords.

**Comment by embray** [comment]
Mappings to the FITS projection codes could go into code specifically related to FITS WCS.  It doesn't need to go here.  We're just talking a dict right?

**Comment by embray** [comment]
Otherwise this is indeed all I had in mind *for now*.  If there are some generalizations of these one which the FITS WCS can later be built that's fine, but maybe also overkill.  I mostly just meant that the names don't have to be cryptic.

**Comment by nden** [comment]
@embray The origin of this module is FITS WCS but it's applicable to WCS in general. Longer names are fine but since most science files are in FITS I'd rather have the mapping in this module than make every code which deals with WCS create its own mapping.

**Comment by mdboom** [comment]
I've added a mapping function for getting a projection class from a FITS WCS projection code.

Having done that, though, I wonder if it wouldn't be simpler to just not *deprecate* the short names, but leave them as aliases to the longer names (i.e. they would be a permanent part of the interface instead).  Seems like less potential for things getting out of sync that way.

**Comment by embray** [comment]
But only code specifically that deals with FITS WCS needs these mappings.

**Comment by nden** [comment]
These mappings are needed by any WCS code which gets as input a FITS file, not only FITS WCS code. What exactly is the problem with keeping the mappings in this module?

**Comment by embray** [comment]
>  needed by any WCS code which gets as input a FITS file

Which is evaluated according to the FITS WCS standard.  Is there something I'm not understanding where there is a distinction?

It's already there now so I'm not going to make a further stink about it.  It just seems out of place to me--that it should be closer to WCS-specific code.

**Comment by eteq** [comment]
This looks like it's still waiting for the change you proposed in your last comment, @mdboom - are you thinking you want to do that still? (I.e., change from deprecation to just "aliasing"?)

**Comment by mdboom** [comment]
I've updated this to merely alias the names with longer ones, not deprecate the short names.  I feel like that's a good compromise to meet everyone's needs.

**Comment by mdboom** [comment]
This is ready for final review.

**Comment by embray** [comment]
:+1:

**Pull request merged**
