### PR TITLE
Feat/get moon

### PR DESCRIPTION
**Pull request by manikantareddyd**
Implementing get_moon using SOFA Library.
A lot of work is to be be done in coordinating the Fundamental arguments of moon.
I made this pull request as per your guidelines to apply for GSOC.

### CODE REVIEW

**Comment by pllim** [comment]
Some comments:

* Add a mention of which issue number this is addressing
* Add change log 
* Add test

**Comment by eteq** [comment]
Also, this is definitely not correct.  It appears you're interpreting the output of `faf03` as the latitude in GCRS.  this is definitely not right, as `faf03` outputs "mean longitude of the Moon minus mean longitude of the ascending node".  That's not the GCRS latitude, it's a longitude.

I suggest you have a look at [the wikipedia article on orbital elements](https://en.wikipedia.org/wiki/Orbital_elements), and maybe also the [IERS standards document](ftp://tai.bipm.org/iers/conv2003/tn32.pdf) (although that is admittedly very dense)...

**Comment by eteq** [comment]
cc @bmorris3, as he has a partial (or maybe complete?) version of `get_moon` in astroplan - not the same implementation, but still useful for comparison.

**Comment by eteq** [comment]
See the discussion in https://github.com/astropy/astropy/pull/4736#issuecomment-202531664 for a bit more on how this might be fixed.

**Comment by bsipocz** [comment]
This can be closed since #4890 is merged.

**Comment by mhvk** [comment]
Indeed, will close this. Thanks @manikantareddyd for the trial.

**Pull request closed without merging**
