### PR TITLE
Remove unhelpful helper usage from a test file

### PR DESCRIPTION
**Pull request by eerovaher**
### Description

`io.ascii` tests define a few helper functions that apparently provided compatibility with `nose`, but are not needed anymore (as reported in #15782). This pull request removes their usage from one test file. It also serves as an example how these (now-)useless helpers should be replaced in other files.

- [x] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
I see lots of open PRs linked to https://github.com/astropy/astropy/issues/15782 . Those probably would be outdated after this one is merged and should be closed?

**Comment by eerovaher** [comment]
All the other pull requests addressing #15782 seem to be abandoned. If there was any reasonable hope that any of them would be finalized then there would have been no need to open this example pull request.

**Review by taldcroft — APPROVED** [review]
LGTM

**Comment by pllim** [comment]
Thanks, all!

**Comment by dhomeier** [comment]
I think we had an extensive discussion especially within #15782 in which cases `numpy.testing.assert_equal` would provide more helpful diagnostics than `assert x == y`. Would have been a good opportunity to add these, but we should probably keep a reference to it.

**Comment by eerovaher** [comment]
The replacements that are suggested in the issue and applied here are simple and never make the tests worse. It is true that in some cases more extensive edits could improve our tests even more, but the issue has proven to be confusing enough for new contributors (I don't understand why, but empirically it is clear that it is so), therefore it is good to keep instructions and examples simple. More sophisticated follow-up can be done separately.

**Pull request merged**
