### PR TITLE
Updates to coordination committee membership

### PR DESCRIPTION
**Pull request by eteq**
This PR updates the list of coordination committee members based on the changes proposed in https://groups.google.com/forum/#!topic/astropy-dev/A6g8n5RQL00

### CODE REVIEW

**Comment by pllim** [comment]
Just a thought -- Should we keep a list of previous committee members somewhere (and the years they served)? Maybe in the project Wiki?

**Comment by astrofrog** [comment]
@pllim - yes, I think this would be a great idea!

**Comment by pllim** [comment]
When is the "beginning" of Astropy?

**Comment by astrofrog** [comment]
Depends how you define beginning :) See the discussion in astropy-dev about the 4th anniversary. Also there should be a message on astropy@scipy.org or astropy-dev about the coordination committee elections.

**Comment by pllim** [comment]
Okay, let's just say 2011 then.

**Comment by pllim** [comment]
I started a page at https://github.com/astropy/astropy/wiki/Past-Committee-Members . Feel free to edit.

**Pull request merged**
