### PR TITLE
Update IERS Earth rotation and leap second tables (v5.0.x)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to manually update IERS data from the script because automated update cannot be backported. I notice that the filename has also changed in `main`. 🤷 

See https://github.com/astropy/astropy/pull/14779 for similar updates but to v5.2.x

### CODE REVIEW

**Comment by pllim** [comment]
The diff seems excessive... `+14,343 −14,262`

**Comment by pllim** [comment]
Is the failure in https://github.com/astropy/astropy/actions/runs/4902558436/jobs/8754475629?pr=14778 related? I cannot tell.

Maybe we missed another backport somewhere. 🤪

**Comment by saimn** [comment]
Probably related to #14382.

**Comment by pllim** [comment]
That is annoying, the dev job failures I think is a mix of numpy-dev ones and maybe stuff from #14382 that didn't get backported.

**Review by mhvk — APPROVED** [review]
As in #14779, looks good. Hopefully we get fewer of these types of problems without LTS and with a new `astropy-iers` package...

**Pull request merged**
