### PR TITLE
ExpressionTree should be a new-style class

### PR DESCRIPTION
**Pull request by fchapoton**
otherwise __slots__ and @property do not work.

suggested by lgtm

### CODE REVIEW

**Comment by pllim** [comment]
Wait, I thought this makes no difference in Python 3.

**Comment by bsipocz** [comment]
We don't support python2 any more, so the way it's done in master used consistently all over the code. Why do you suggest it's not working properly?

**Comment by fchapoton** [comment]
ok, I understand. Then forget about it.
This was suggested by lgtm.com here:
https://lgtm.com/projects/g/astropy/astropy

**Comment by pllim** [comment]
OK, closing then. Thanks anyway!

**Comment by bsipocz** [comment]
Ohh, I think we didn't know about that tool. Thank you for looking into issues it picks up on. 
I suppose they would need to update to recognize if a codebase is python3 only and thus everything is new-style class by default without explicitly inheriting from `object`.

**Pull request closed without merging**
