### PR TITLE
fixed serialization of orthonormal polynomials

### LINKED ISSUE #9809: ASDF serialization of polynomial models missing domain (causing incorrect evaluation)
When saving & reloading a polynomial model, the `domain` information gets lost (also `window`?), causing the reloaded model to produce different results from the original one.

```python
>>> import numpy as np
>>> from astropy.modeling import models, fitting
>>> import asdf

>>> x = np.arange(0, 9)

>>> model = models.Chebyshev1D(1, c0=2.35, c1=2.25, domain=(0,9))
>>> model.inverse = models.Chebyshev1D(1, c0=4.5, c1=4.5, domain=[0.1, 4.6])

>>> af = asdf.AsdfFile({"model" : model})
>>> af.write_to("testdom.asdf")

>>> newmodel = asdf.open("testdom.asdf")['model']

>>> print('Fwd before {}, after {}'.format(model.domain, newmodel.domain))
Fwd before (0, 9), after None

>>> print('Inv before {}, after {}'.format(model.inverse.domain,
>>>                                        newmodel.inverse.domain))
Inv before [0.1, 4.6], after None

>>> print('y before:', model(x))
y before: [0.1 0.6 1.1 1.6 2.1 2.6 3.1 3.6 4.1]

>>> print('y after:', newmodel(x))
y after: [ 2.35  4.6   6.85  9.1  11.35 13.6  15.85 18.1  20.35]
```

See also #9795.

Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0]
Numpy 1.17.3
Scipy 1.3.1

### PR DESCRIPTION
**Pull request by perrygreenfield**
### Description

This pull request is to address the fact that previously orthonormal polynomials were not serialized with necessary information about domain or window if those attributes were not the defaults

Fixes #9809

### CODE REVIEW

**Comment by pllim** [comment]
@perrygreenfield , please move change log entry to 4.0.1 since this is a bug fix.

p.s. Not sure why tests failed. If you haven't already, please try rebase on top of latest `master`. Thanks!

**Comment by jehturner** [comment]
Do I also need to update anything else to go with this (where does the schema come from again)? Thanks.

**Comment by perrygreenfield** [comment]
@jehturner That's a fair question about schemas. It turns out (I believe) that there aren't any schemas for bounding_boxes or things like that. So any errors in specifying the value in ASDF that way won't be caught by using the schema machinery, but rather by the object machinery in Python (preferably in creating the object, but it possible in some cases if they are assigned to non-property attributes the error will only arise in using the object). It is something that I think deserves a small schema eventually (i.e., defining a rectangular region)

**Comment by jehturner** [comment]
Thanks a lot for this @perrygreenfield. The following code (and hence my real `gwcs` serialization test) fails for me with a long `jsonschema` validation error (only when the `domain` is defined):
```python
from astropy.modeling import models
import asdf

fwcal = models.Chebyshev1D(2, c0=500.075, c1=0.05, c2=0.001, domain=(0, 9))
wavtrans = fwcal & models.Identity(1)

af = asdf.AsdfFile({"model" : wavtrans})
```
It looks like this is probably the pertinent line:
```jsonschema.exceptions.ValidationError: mismatched tags, wanted 'tag:stsci.edu:asdf/transform/domain-1.0.0', got 'tag:yaml.org,2002:int'```

**Comment by perrygreenfield** [comment]
Hmmm, that may be a versioning error since domain was supposedly deprecated. @nden, do you understand how this may have happened, offhand?

**Comment by nden** [comment]
@perrygreenfield Could you try adding `version = 1.2.0` to the `CompoundType` tag? I have it working locally but I also have other changes which may not be needed. I'm thinking this may be the minimal change needed. I can't test it because I need to reinstall everything now.

**Comment by jehturner** [comment]
:+1: That seemed to fix the failure I was seeing from `AsdfFile`.

I'm still seeing an error from the domain comparison in my test because the `domain` is a tuple when the model is instantiated in my example above, but it becomes a list after the model is reloaded (at L225). Wouldn't it be better if it were always converted to one type or the other? Thanks.

**Comment by perrygreenfield** [comment]
@jehturner Good point, but before fixing this I'd like a little more detail on how the model is instantiated in your example. In my quick look, it appears that the current polynomial models don't enforce anything about domain or windows so that however one sets those values, there is a possibility that ASDF will return an inconsistent value. That can be changed, and I would agree that tuple is the natural form they should take and keep.

**Comment by jehturner** [comment]
I was doing this:
```python
>>> fwcal = models.Chebyshev1D(2, c0=500.075, c1=0.05, c2=0.001, domain=(0, 9))
>>> fwcal.domain
(0, 9)
```
whereas with a list it does this:
```python
>>> fwcal = models.Chebyshev1D(2, c0=500.075, c1=0.05, c2=0.001, domain=[0, 9])
>>> fwcal.domain
[0, 9]
```
Is that what you were asking?

It turns out that one can even do this:
```python
>>> fwcal = models.Chebyshev1D(2, c0=500.075, c1=0.05, c2=0.001, domain='fred')
>>> fwcal.domain
'fred'
```
So indeed I think the model should enforce something like a tuple (presumably converting whatever sequence of numbers you give it into one), in which case your tag code should do the right thing automatically -- so perhaps this is really a separate issue from this PR, come to think of it.

**Comment by perrygreenfield** [comment]
Right! I was just looking at what it should do to enforce permitted values (None complicates it a bit). Might as well fold that in.

**Comment by eteq** [comment]
I got here by way of #9795 and I'm a bit confused: Wasn't @jehturner's suggestion in  https://github.com/astropy/astropy/issues/9809#issuecomment-568078984 to have this come from `OrthoPolynomial1D` instead of `hasattr`?  I think I like that suggestion more because it gives a way to address the point from #9795 that this is not just ASDF but *other* use cases.

**Comment by jehturner** [comment]
Contrary to my thinking in #9809, @eteq, it turns out that Perry's solution here uses neither `hasattr` nor `OrthoPolynomial1D`, because it only involves changes to the "tag" code. For better or worse, the tag classes are structured differently from the model hierarchy itself and enumerate the supported/applicable models (in this case `Legendre1D, Legendre2D, Chebyshev1D, Chebyshev2D, Hermite1D, Hermite2D`) -- so the code can simply assume that 1D models have `domain` & 2D models have `x_domain` & `y_domain`. If someone wanted to add another `PolynomialModel`, they'd have to write or adapt a tag to do the right thing, so there's no forward compatibility problem in that sense if they add one with no `domain`, though this scheme does imply some guaranteed extra work to add new models.

**Comment by jehturner** [comment]
This raises the point that the `PolynomialType` tag also needs changing, doesn't it @perrygreenfield, since those models have `domain` & `window` too? I know that wasn't in my issue title but still :wink:.

**Comment by perrygreenfield** [comment]
@jehturner Yes they would. The more I looked into this, the more surprises jumped out at me. I was thinking of tackling all this at once, but given the issues regarding domain/window in general, perhaps the quick solution here should be done and more thought and input on object interface issues done without rushing.

**Comment by nden** [comment]
To clarify a bit on the implementation. It follows the implementation of polynomials in numpy in having `domain` and `window`. Their purpose is mostly to support fitting. And yes, general `Polynomial` models define the defaults as they are in order to provide the identity transform
but also provide the option to use a different transform. And an attempt to summarize all opinions in the several issues:

- Modify the `__init__` signature of all polynomials to define `domain` and `window` as None and if so set the defaults in the `__init__` to their current default values. (4.0.1)
- Serialize `domain` and `window` (4.0.1)
- Improve the documentation to better explain what they are. (4.0.1)
- Fix `repr` and `str` (4.1)

Am I missing something?

**Comment by perrygreenfield** [comment]
To possibly add to the @nden list: provide an alternate interface for defining the transformation of the input value. Given all the involved issues, this is likely non-trivial and would go into 4.1 or 5.0 if done at all. The main motivation is to make it clearer what is going on since I think many find the existing terminology misleading (even if numpy is using it).

**Comment by jehturner** [comment]
> Am I missing something?

I think also converting the `domain` & `window` arguments from whatever sequences the user provides to 2-tuples in the corresponding attributes (which will also fix their type changing from a tuple to a list after serialization, such that the pre/post-serialized models don't quite match).

**Comment by jehturner** [comment]
I wonder whether you might prefer to make the `domain` & `window` attributes lists rather than tuples though, since that's what the documentation currently says the arguments should be? Either way.

So where are we with this particular PR? I think it's OK, except that `domain` & `window` still need adding to `PolynomialType` as well. If you want, I could probably do that now I have an example (I suppose by submitting another PR to Perry's branch, or is that getting too silly?).

**Comment by perrygreenfield** [comment]
@jehturner The fix is awaiting changes being made to fix lint issues and I will then base the fix on that PR. I'm not sure of the consequences of lists vs tuples other than if explicitly in the default of an argument list, the tuple is much preferred since it isn't mutable, but I'll have to see in the context of other changes.

**Comment by perrygreenfield** [comment]
This will be done as a new PR. I'll provide the number when it is ready to submit.

**Comment by perrygreenfield** [comment]
replaced py PR  #9941

**Pull request closed without merging**
