### PR TITLE
Temporary __repr__ implementation for WCS objects (Issue #3604) and improvised regex solution for __bibtex__ (Issue #3114)

### PR DESCRIPTION
**Pull request by bmorris3**
Meant as a temporary solution, part of my GSoC 2015 application.

### CODE REVIEW

**Comment by bmorris3** [comment]
I've also made a temporary solution for a [Vanderplas-style](https://twitter.com/fperez_org/status/525096002831646721?s=09) `__bibtex__` variable, using regex to extract the BibTeX reference from the citation file.

**Comment by mdboom** [comment]
Thanks for the contribution!

I think the bibtex thing is different and independent enough that it should be a separate PR.  There's already been some discussion of that idea in #3114.

As for the WCS __repr__ -- any chance we could reduce the code duplication there, by having `__repr__` call `printwcs` or vice versa?  Seems not so great to have two methods that do (almost) the same thing.

**Comment by bmorris3** [comment]
I agree. I didn't want to touch the existing code for the purposes of the GSoC PR, but in order to return a string instead of printing a series of strings, I created an adaptation of the `printwcs` method that returns a string, first. If we were to adopt this `__repr__` method, I would probably make the `printwcs` method call `__repr__`.

**Comment by mdboom** [comment]
I'd go ahead and make the changes to `printwcs` to call `__repr__`.  Don't worry about modifying existing code -- we won't press the merge button unless it all looks right :wink:

**Comment by eteq** [comment]
Just to be clear, @bmorris3, it's ok  to change this branch to remove your implementation for #3114 and move that to another branch/PR - the comments will indicate that you did both things so it we'll recognize both efforts, I promise!

You could also open a separate PR for the citation stuff (although see my comment in #3114 which might have impact there).

**Comment by embray** [comment]
Is this PR superseded now by #3696 and #3697 ?

**Comment by embray** [comment]
Please don't merge PRs without at least suggesting a milestone first :)

**Pull request merged**
