### PR TITLE
Revert "cosmo: add type annotations to `astropy.cosmology.units.py`"

### PR DESCRIPTION
**Pull request by pllim**
Reverts astropy/astropy#15852

Close #16482

to see if RTD would be green again. It currently fails on `main`.

### CODE REVIEW

**Comment by nstarman** [comment]
I think this might just need another addition to [nitpick-exceptions](https://github.com/nstarman/astropy/blob/main/docs/nitpick-exceptions). We've had to clobber every problem with Sphinx by just ignoring it using this file.

**Comment by pllim** [comment]
@nstarman , are you able to open a follow-up PR with nitpick then? Thanks!

Also I wonder why #15852 did not catch this...

**Comment by pllim** [comment]
Thanks to @eerovaher explaining why it didn't fail before on the other PR. Given https://github.com/astropy/astropy/pull/16482#issuecomment-2124899734 , I am taking this out of draft for serious consideration.

**Comment by nstarman** [comment]
The problem with reverting is it a major roadblock to any attempt to improve cosmology by adding type annotations. I don't like the precedent of preventing enhancement PRs because we aren't fixing deeper structural problems.  I don't encounter these issues in my repos with docs so it's something Astropy-side, either in automodapi or because of PEP 8 or something similar. Regardless, we should be addressing the cause not the effect.
Now we need to get the docs working, so a temporary reversion might be necessary. But given discussions related to doc fixes there's little reason to believe this is actually temporary. And that's the source of my opposition to this PR.

**Comment by pllim** [comment]
From my POV though, type annotation is cosmology is a smaller fire than RTD giving big red X for everything else.

**Comment by pllim** [comment]
I think we both agree that reverting it as temporary solution is ok?

I just dunno how to make sure RTD doesn't break again when you reintroduce it.

**Review by mhvk — APPROVED** [review]
Agreed both that we should first of all ensure that everything else can work, and that we need to fix the larger problem since sphinx should not block typing (or other) efforts.

**Comment by pllim** [comment]
Thank you for your understanding!

**Pull request merged**
