### PR TITLE
Change models to one doc section

### PR DESCRIPTION
**Pull request by eteq**
In the current master, the models from `astropy.modeling` are each documented in their own section (e.g. `astropy.modeling.polynomial`, `astropy.modeling.powerlaws`, etc.).  This strikes me as less than ideal, because it leads to people doing things like `from astropy.modeling.polynomial import Chebyshev1D`, while what we really want is for people to do `from astropy.modeling.models import Chebyshev1D`, so that they don't have to worry about the internal organization of the `modeling` package. This PR corrects that by changing it so that just `astropy.modeling.models` is documented, which contains all the same classes, but makes it clearer that it's intended that they use `astropy.modeling.models`.

There's a bunch of changes in `astropy.sphinx.ext`  because it turns out enabling this required some rather substantial changes to how `automodapi` finds modules.  The details are not terribly important unless you're interested, but even if we end up leaving the `modeling` doc the way it is, the _rest_ of this should be included, as it contains some bug fixes.

cc @nden

### CODE REVIEW

**Comment by nden** [comment]
@eteq Just going over some old issues. As far as I can tell this is almost (if not cpompleteley) identical to the current docs. Should we close this PR? I think the modeling documentation is due for another round of updates but perhaps it should be started from scratch?

**Comment by pllim** [comment]
Closing as @nden suggested.

**Comment by bsipocz** [comment]
Wow @pllim, you did a lot of closing while we were having dinner over here.

**Comment by pllim** [comment]
Must... achieve... goal... 😉

**Comment by bsipocz** [comment]
Brilliant, I hoped that I could get you on board :)

**Comment by pllim** [comment]
110 is my personal best today. I can do no more... 😢

**Pull request closed without merging**
