### PR TITLE
Always convert arrays to native order before passing to pandas

### PR DESCRIPTION
**Pull request by astrofrog**
This should fix https://github.com/astropy/astropy/issues/1156

@cdeil - can you confirm this works for you?

### CODE REVIEW

**Comment by cdeil** [comment]
:+1: 

(all I checked was that the example in https://github.com/astropy/astropy/issues/1156#issuecomment-96283269 now works)

**Comment by astrofrog** [comment]
@taldcroft - I've assigned this for you to merge (adopting the new system of assigning we discussed a few weeks ago)

**Comment by taldcroft** [comment]
Looks good.

**Comment by embray** [comment]
:+1:

**Pull request merged**
