### PR TITLE
Backport PR #12509 on branch v5.0.x (Support structured quantity, including scalars.)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #12509: Support structured quantity, including scalars.

### CODE REVIEW

**Comment by pllim** [comment]
@mhvk @nstarman @taldcroft , this backport of #12509 seems to have real failure. Do you know what is going on here?

**Comment by pllim** [comment]
Maybe we should not backport this one?

**Comment by mhvk** [comment]
Hmm, this would need #12492 to be backported as well (which allowed structured units to be serialized). I think there certainly is a case to be made that it should be -- a bit bad to have structured units but not be able to store them! -- and I'm willing to do it, but I'll wait others opinions.

**Comment by nstarman** [comment]
I agree that it would be a good thing to backport. The structured units are a great addition and serialization should be part of the feature.

**Comment by mhvk** [comment]
OK, I tried invoking the magic meeseek stanza in #12492 - will see if for that the tests pass, merge if so.

@pllim: if that works, would it then be best to rebase this PR, or just close it and retry in #12509? (Happy to experiment if you don't know!)

**Comment by pllim** [comment]
I find that closing the outdated backport PR and then ask the bot to open another one is the easiest way that is equivalent to rebasing the backport. So let's do that. Thanks!

**Comment by mhvk** [comment]
OK, closing this iteration then!  Thanks!!

**Pull request closed without merging**
