### PR TITLE
WCS: Add a test checking that CRVAL and CDELT do not get truncated

### PR DESCRIPTION
**Pull request by keflavich**
Related to #4612 and #4613

WIP!  This seems to fail (1) in a different way than 4612 (CDELT instead of
CRVAL getting truncated) and (2) it still fails on master!  However, I need to
re-test with a clean build.

### CODE REVIEW

**Comment by keflavich** [comment]
I'm still getting failures on the first test even on master, despite the bug apparently being fixed for the test header I had been working on (see #4612).  Apparently there are combinations of WCS parameters that still lead to problems.  I suspect it has something to do with mixing celestial and non-celestial parameters in the first test.  The second test should fail on 1.1.1 in principle.... the first fails everywhere.

**Comment by eteq** [comment]
Just to make things even more confusing, I noticed some additional surprising behavior.  If I try the *first* test here, but do ``w.wcs.crval=[2.409303333333E+02,50,2.12345678e11]`` instead of ``w.wcs.crval=[50,50,2.12345678e11]``, in astropy v1.1.1 the output header has ``CRVAL1=240.9``.  But If I instead do ``w.wcs.crval=[2.409303333333E+02,50,2.409303333333E+02]``, I get ``CRVAL1=240.9303333333``!

So the CRVAL1 precision seems to depend on the *value* of CRVAL3 :open_mouth:  Does that make any sense to you, @nden or @keflavich ?

**Comment by keflavich** [comment]
@eteq: my understanding is that the precision of the largest number affects the smallest.... so for frequencies 2e11, a precision of 12 digits goes to 1e-1, and that is the precision applied to everything.  Does that seem sensible?  ....is it actually a correct interpretation of what's happening?  This is my assumption based on not actually reading the code.

**Comment by astrofrog** [comment]
I'm removing the milestone - this was never merged directly but was included in #4616

**Pull request merged**
