### PR TITLE
Improve subpackage naming

### PR DESCRIPTION
**Pull request by adrn**
I often get confused about the subpackage names in astropy because they contain so many useful utilities. So I thought we could rename them all to reflect their utility! I'm currently thinking:

- config -> confutils
- constants -> constutils
- convolution -> convutils
- coordinates -> coordutils
- cosmology -> cosmoutils
- io -> ioutils
- modeling -> modelutils
- nddata -> ndutils
- samp -> samputils
- stats -> statutils
- table -> tableutils
- time -> timeutils
- units -> unitutils
- utils -> utilutils
- visualization -> vizutils
- wcs -> wcsutils

Thoughts?

### CODE REVIEW

**Comment by eteq** [comment]
:trollface:

**Comment by taldcroft** [comment]
I fail to see the utility in this PR.

**Comment by pllim** [comment]
(Aww man, adding a label changed the bot message. I am especially sorry since I loved that message.)

**Comment by pllim** [comment]
(I will send in a request to GitHub to recover previous comment edits ASAP)

**Comment by larrybradley** [comment]
We should adopt this for affiliated packages too!  I'll put a PR in for:

* photutils -> photutilsutils
* specutils -> specutilsutils

**Comment by pllim** [comment]
:cry:

**Pull request closed without merging**
