### PR TITLE
Move coverage test to python 3.5.

### PR DESCRIPTION
**Pull request by mhvk**
Since that has become faster than 2.7: see https://github.com/astropy/astropy/issues/4826#issuecomment-245037954

### CODE REVIEW

**Comment by mhvk** [comment]
closes #4826.

**Comment by pllim** [comment]
Did you indeed confirm my claim that Python 3 is now faster? Good to have more data points. :sweat_smile:

**Comment by pllim** [comment]
Ah, never mind, just saw [your comment over there](https://github.com/astropy/astropy/issues/4826#issuecomment-245050266). :+1:

**Comment by mhvk** [comment]
Yes, and as a final check we can compare how long the coverage takes here with a recent one using python2; e.g., 13m18s in https://travis-ci.org/astropy/astropy/builds/157914668

**Comment by mhvk** [comment]
Hmm, so this does not look great: the time travis needed for coverage was 22m21s, i.e., well more than the reference 13m18s mentioned above.

**Comment by pllim** [comment]
I did a clean install on both Python 2 and 3 environments. But I did *not* clear Astropy cache. I wonder if my timing was skewed by that. I ran Python 2 first.

**Comment by mhvk** [comment]
checking the logs
```
               install1+2  main_cmd test-output
python3   97s         1170s       1092s
python2   74s          483s        422s
```
so everything seems substantially slower, though the main difference is simply running the tests. I'll restart just to get another data point, in case there is much difference between the virtual machines.

**Comment by mhvk** [comment]
> I did a clean install on both Python 2 and 3 environments. But I did not clear Astropy cache. I wonder if my timing was skewed by that. I ran Python 2 first.

My tests were nowhere near that fancy; I ran the tests in the git source directory, and ignored the additional dependencies (though I have `scipy` installed, so that gets picked up). I also did not mimick the compiler flags that are given in .travis.yml... I did try multiple times, though, so if a cache is important, it would have been present for both python2 and python3.

What I mostly do not understand is why the coverage adds that much extra time: the python3 no-coverage tests with all dependencies were nowhere near as slow.

**Comment by astrofrog** [comment]
> What I mostly do not understand is why the coverage adds that much extra time: the python3 no-coverage tests with all dependencies were nowhere near as slow.

Indeed, that was what confused me in https://github.com/astropy/astropy/issues/4826 - I still don't know what could be causing that. I think it could be that the coverage is very sensitive to e.g. the number of function calls or the depth of the stack, and maybe some tests stress that more?

**Comment by mhvk** [comment]
OK, the restart took 26m, so this is definitely not solved. I think we should move discussion back to #4826...

**Comment by MSeifert04** [comment]
@mhvk Could you try using `coverage=4`? I dimly remember some problems with their C-speed parser on python3. Maybe it's worth a try.

**Comment by pllim** [comment]
I can't find the coverage version in https://travis-ci.org/astropy/astropy/jobs/157970322 . How do I find out?

**Comment by MSeifert04** [comment]
@pllim Line 651 (you need to open the install-commands in the log). And it's fixed in https://github.com/astropy/ci-helpers/blob/393f32cba0a91ef0055eaddbf2dabe738ac0eed4/travis/setup_dependencies_common.sh#L306.

It's a bit unfortunate but I wasn't able to overwrite this for a test run.

**Comment by pllim** [comment]
Thanks, @MSeifert04 . I don't see why that version fixing is needed anymore as the issue referenced is closed. So I guess this actually requires an upstream fix.

**Comment by mhvk** [comment]
So, is there a way to unfix coverage for astropy? I ran all the tests on both python2 and 3 with 4.2, so that one should work at least for astropy.

p.s. @pllim - Am confused why this is an "upstream fix required" -- you mean in the sense that we should fix `ci-helpers`?

**Comment by pllim** [comment]
From what @MSeifert04 posted, it seems that coverage version is fixed in `ci-helpers` explicitly, specifically in `setup_dependencies_common.sh`. So, yes, I think the real fix to the timing issue might be in `ci-helpers`. Did I misunderstand?

**Comment by mhvk** [comment]
OK, we both agree; I just wasn't sure which "upstream" you meant!

**Comment by mhvk** [comment]
Superceded by #5401.

**Comment by bsipocz** [comment]
Ohh, I'm sorry @mhvk, I didn't notice this PR when opened the other one.

**Comment by mhvk** [comment]
No problem! More important is to have fixed the slowdown!

**Pull request closed without merging**
