### PR TITLE
Fix WCSAxes output with Matplotlib 2.x

### PR DESCRIPTION
**Pull request by astrofrog**
**Before:**

test_mpl2

**After:**

test_mpl2

I think this should be treated as a bug fix and included in 1.3.1

### CODE REVIEW

**Comment by astrofrog** [comment]
I will add reference images for Matplotlib 2.x and WCSAxes in a separate PR

**Comment by astrofrog** [comment]
@MSeifert04 - I've included your fix here since I needed it locally when doing some testing

**Comment by MSeifert04** [comment]
Is the difference between the images really that obvious? I can't spot any differences between the two images.

btw: no problem with the commit, I didn't expected that it would take so long for the travis 3.6 tests to be merged - in the end either PR is fine.

**Comment by astrofrog** [comment]
@MSeifert04 - huh, the difference is pretty big, i.e. the ticks on the bottom image face outwards (Matplotlib 2.x style) and the frame is thinner (it was too thick originally). Maybe GitHub is not showing the images correctly for you?

**Pull request merged**
