### PR TITLE
Fix Parameter.clone link

### LINKED ISSUE #12540: TST: broken link: astropy.cosmology.Parameter.clone ()
@nstarman , do you know what this is about?

https://github.com/astropy/astropy/runs/4349983149?check_suite_focus=true

```
.../docs/cosmology/dev.rst.rst:143:broken link: astropy.cosmology.Parameter.clone ()
```

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

Fixes #12540

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Hmm. @nstarman , can you please remove `[ci skip]` from your commit message?

**Comment by pllim** [comment]
I cancelled irrelevant jobs. Though I just realized linkcheck might choke on noao site being down first. We'll see...

**Comment by pllim** [comment]
Anyways... I don't see why this diff would fail if that API is publicly documented. Merging, thanks!

**Comment by pllim** [comment]
Eh... Has `main` and `v5.0.x` diverged that much already, @nstarman ? Are you up for doing a manual backport?

**Comment by nstarman** [comment]
Ahh... an issue! I don't think ``clone`` is in 5.0!
Just looking to make sure....

**Comment by pllim** [comment]
Gotcha. Thanks for checking!

**Comment by nstarman** [comment]
That would explain the manual backport.

**Pull request merged**
