### PR TITLE
Replace 'the the' by 'the' in the documentation

### PR DESCRIPTION
**Pull request by DougBurke**
While 'The The' are my favourite band, I don't think they need to be referenced here ;-)

### CODE REVIEW

**Comment by embray** [comment]
Thanks!

By the way, when making trivial grammatical changes in the docs please use "[skip ci]" in the commit message to prevent it from running continuous integration tests on the changes.

**Comment by DougBurke** [comment]
Ta - I remembered about the 'skip ci' part *just* after hitting the commit
button!

**Comment by embray** [comment]
No prob. I forget it all the time.

**Comment by embray** [comment]
(You can also change the commit message using `git commit --amend`).

**Pull request merged**
