### PR TITLE
TST: Allow Windows CI to fail for now

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to temporary allow Windows CI job to fail until we can do one of the following:

* Have time and/or expertise to fix the obscure failure on Travis CI
* Move the CI to Azure (#8445)
* Move the CI to Actions (#10388)

Close #10842
Close #10844

### CODE REVIEW

**Comment by pllim** [comment]
Hmm, Travis CI didn't kick off. Trying the close-open method.

**Comment by pllim** [comment]
I cancelled CircleCI because it is not necessary. Travis CI somehow didn't report back but it is running at https://travis-ci.org/github/astropy/astropy/builds/735410532

**Review by eteq — APPROVED** [review]
The PR itself looks good, but just to be clear, but I don't think this actually closes #10842 since we still *might* want to fix it, right?

**Comment by pllim** [comment]
Let's wait a bit though. @Cadair might just have a revelation.

**Comment by pllim** [comment]
Still broken, so I'll push ahead with this after a rebase.

**Comment by adrn** [comment]
Oops I just replied on slack, but I'll post here too. I don't think this is a travis-specific issue: I run windows tests for an affiliated package (gala, based on the package template) using github actions and am seeing the same error. It seems to have started ~1–2 weeks ago. Tox just had a new release a few days ago, so I thought that it could be the culprit, but even pinning tox doesn't seem to fix it. Mentioning this here in case that's useful for debugging! For example: https://github.com/adrn/gala/pull/190 and a failure: https://github.com/adrn/gala/runs/1249214462?check_suite_focus=true

**Comment by pllim** [comment]
@Cadair did trace it to `could not satisfy requires PackageNotFoundError('tox-pypi-filter')` but not sure why it is happening.

**Comment by pllim** [comment]
Merging this for now.

**Pull request merged**
