### PR TITLE
Fix removal of units from CompoundModel with * or / and fix fitting of these models

### PR DESCRIPTION
**Pull request by astrofrog**
This fixes a bug that caused compound models created via ``CompoundModel.without_units_for_data`` to be incorrect if the compound expression included ``*`` or ``/``, because the top-level parameters were decoupled from the parameters of the constituent models (see examples in https://github.com/astropy/astropy/issues/16675). The safer route is to instantiate a new ``CompoundModel`` rather than copy and modify. Example of incorrect behavior:

```python
In [1]: from astropy.modeling.models import Gaussian1D

In [2]: from astropy import units as u

In [3]: g1 = Gaussian1D(amplitude=2 * u.Jy, stddev=4 * u.nm, mean=1000 * u.nm)

In [4]: g2 = Gaussian1D(amplitude=1 * u.Jy, stddev=2 * u.nm, mean=500 * u.nm)

In [5]: gg = g1 * g2

In [6]: gg
Out[6]: <CompoundModel(amplitude_0=2. Jy, mean_0=1000. nm, stddev_0=4. nm, amplitude_1=1. Jy, mean_1=500. nm, stddev_1=2. nm)>

In [11]: gg_nounit = gg.without_units_for_data(x=1 * u.nm, y=2 * u.Jy ** 2)[0]

In [13]: print(gg_nounit)
Model: CompoundModel
Inputs: ('x',)
Outputs: ('y',)
Model set size: 1
Expression: [0] * [1]
Components: 
    [0]: <Gaussian1D(amplitude=2., mean=1000., stddev=4.)>

    [1]: <Gaussian1D(amplitude=1., mean=500., stddev=2.)>
Parameters:
    amplitude_0 mean_0 stddev_0 amplitude_1 mean_1 stddev_1
    ----------- ------ -------- ----------- ------ --------
            2.0 1000.0      4.0         1.0  500.0      2.0

In [14]: gg_nounit.amplitude_0=5

In [15]: print(gg_nounit)
Model: CompoundModel
Inputs: ('x',)
Outputs: ('y',)
Model set size: 1
Expression: [0] * [1]
Components: 
    [0]: <Gaussian1D(amplitude=5., mean=1000., stddev=4.)>

    [1]: <Gaussian1D(amplitude=1., mean=500., stddev=2.)>
Parameters:
    amplitude_0 mean_0 stddev_0 amplitude_1 mean_1 stddev_1
    ----------- ------ -------- ----------- ------ --------
            5.0 1000.0      4.0         1.0  500.0      2.0

In [16]: gg_nounit.left.amplitude
Out[16]: Parameter('amplitude', value=2.0)

In [17]: gg_nounit.right.amplitude
Out[17]: Parameter('amplitude', value=1.0)
```

As you can see, ``gg_nounit.left.amplitude`` was actually incorrect, as it should be 5 now. This is now fixed with this PR.

A more serious issue that this caused was that fitting was in fact completely broken for compound models with units and with a * or / - the fitting simply returned the same model as the original unfit one. There were several tests of the fitting which were incorrectly written and assumed the fit and unfit output should be the same, which it should not be, so I have now adjusted those tests so that they pass again.

Fixes https://github.com/astropy/astropy/issues/16675

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by astrofrog** [comment]
@perrygreenfield probably not, but I wanted to avoid changing the tests too much since they do work as long as we don't look at the degenerate parameters values?

**Comment by perrygreenfield** [comment]
I'd be happier with replacing these but someone else thinks they are OK, I can go with that. Otherwise I didn't see any other problems.

**Comment by astrofrog** [comment]
I'll have a think whether there is a way to rewrite the tests that would preserve their essence, and fail on main to make sure they act as a regression test.

**Comment by astrofrog** [comment]
What if we checked the values of combination of parameters? For example if and and b are degenerate, I might still be able to check the value of a*b?

**Comment by perrygreenfield** [comment]
Can we just fix one of the intercept values? That should remove the degeneracy shouldn't it?

**Comment by astrofrog** [comment]
Good idea about fixing one or more of the parameters, will investigate! (Might need to fix more than one for the compound models formed of four sub-models)

**Comment by astrofrog** [comment]
@perrygreenfield - ok I've now gone and fixed parameters - due to the nature of the model we need to fix all but two of the parameters, but I think this is fine and still tests what we need to test. There are no longer any degeneracies so we can check the parameter values.

**Comment by pllim** [comment]
devdeps failure unrelated, so merging. Thanks, all!

**Pull request merged**
