### PR TITLE
Use CircleCI for 32-bit builds

### PR DESCRIPTION
**Pull request by astrofrog**
This is an attempt to set up 32-bit builds using CircleCI based on the discussion on astropy-dev

https://groups.google.com/forum/#!topic/astropy-dev/lWu07LYYMbc

Here's an example run:

https://circleci.com/gh/astrofrog/astropy/22

I did this by setting up a docker image, for which the recipe can be found here:

https://github.com/astrofrog/astropy-32bit-docker

I tried to do it without docker, but some packages weren't available when using apt through CircleCI for some reason, so this was easier. I'm pretty sure the Python is 32-bit, but I think it would be nice to have a way to verbosely show this in the log - at the moment I print out ``sys.maxsize``, but maybe the astropy py.test header should do this to make sure?

If we think this is a good approach, I will move the docker recipe to the astropy org, make an astropy account on the docker hub, and update the config here.

CircleCI will finish before Travis and AppVeyor, so there's no real downside to this - except that we can't use CircleCI for anything else (but we weren't using it anyway, so...). Total runtime is around 8 minutes. In principle, we could even make this build the latest Numpy dev, but not sure if we really want to do that.

Note that if any command in the docker container fails, the build fails (I checked).

This would fix https://github.com/astropy/astropy/issues/5426

cc @mhvk @MSeifert04 @juliantaylor since you were discussing this in #5426

### CODE REVIEW

**Comment by juliantaylor** [comment]
the container needs `linux32` as `ENTRYPOINT` so the kernel reports a 32 bit identity, e.g. in case something uses `uname`

**Comment by astrofrog** [comment]
@juliantaylor - I'm not familiar with how to do this - could you by any chance open a PR to the Dockerfile or explain how to do this? Thanks!

**Comment by juliantaylor** [comment]
Just add:

    ENTRYPOINT ["linux32"]

Then the container should run everything with linux32 prefixed. E.g.

    echo "uname -a"  | sudo docker run -i --rm container bash

should then print something with i686 instead x86_64

**Comment by astrofrog** [comment]
Ok, this should now be working fine, and I believe it is truly testing Astropy on 32-bit

@astropy/astropy-core-maintainers - any objections? If not, I'll move the docker image to an astropy channel on the docker hub and update this PR, before we merge it (and of course I'll enable CircleCI on this repo instead of my fork)

**Comment by mwcraig** [comment]
👍 to more testing!

**Comment by eteq** [comment]
👍 , although with the reservation that adding another CI system is more maintenance burden... But if its easy, maybe we switch to all-circle down the road...?  But science is all about experiments!

**Comment by astrofrog** [comment]
We can't switch to all-circle at the moment, because it doesn't support build matrices... But maybe in future!

**Comment by cdeil** [comment]
@astrofrog - Thanks!

I have two suggestions:

1. Put the Dockerfile in the Astropy or an existing repo for test stuff (like ci-helpers), so that all people working on Astropy testing / CI can help maintain it.
2. Add some docs, i.e. a README or section in the Astropy dev docs that explains that this exists, where it is, and give the command how to build and start the Docker container locally. This is useful if there is a fail on circle-ci and some dev wants to help debug / fix it.

**Comment by astrofrog** [comment]
@cdeil - ah, the link in the PR description is outdated, I have put the Dockerfile here:

https://github.com/astropy/astropy-32bit-docker

so it's there for anyone to contribute to :)

I agree about the local debugging instructions, will add.

**Comment by bsipocz** [comment]
@astrofrog - I've cancelled travis and appveyor for this.

**Comment by cdeil** [comment]
In the past I've had fails on travis-ci that I wan't able to reproduce and debug on any machines I have access to.
So I created a Docker file (64-bit, Ubuntu, as similar to travis-ci machines as possible)
https://github.com/gammapy/gammapy/tree/master/dev/docker
and used that successfully to debug the issues locally.

If you're OK, I'd like to clean that up and move that Dockerfile from Gammapy -> Astropy.

I.e. my suggestion here would be to not name the repo just `astropy-32bit-docker`, but to expand the scope a little to `astropy-docker`. Actually, I don't understand why a new repo for a few files is helpful. Why not just have a `docker` folder in the `ci-helpers` repo, where people will find it more easily?

**Comment by astrofrog** [comment]
@cdeil - an ``astropy-docker`` repo sounds good, I'll go ahead and rename it and reorganize the file. For now I'd like to keep it separate from ci-helpers in the sense that for ci-helpers, it takes a while to get PRs in because of the extensive testing, which doesn't need to apply to the docker images. But maybe once we're pretty happy with them, we could move them to ci-helpers, if they are not astropy-specific.

**Comment by astrofrog** [comment]
@cdeil - see https://github.com/astropy/astropy-docker now

**Comment by astrofrog** [comment]
If there are no objections to this, I'll merge it by the end of the day :)

**Comment by bsipocz** [comment]
👍 +1 to move this into ``ci-helpers`` on the long term, there were requests to support circle ci, e.g. https://github.com/astropy/ci-helpers/issues/112

However I agree with @astrofrog, it's a bit of pain to develop there anything as we are quite cautious, so moving it in when it's proved to be working is a good idea.

**Comment by astrofrog** [comment]
Just to clarify (for @cdeil), the ci-helpers is not just a collection of scripts - because it's actually cloned in production, we have to be extremely careful with it, so we have very extensive tests, and we've disabled pushing to master, and all tests have to run to make changes. So that's why it makes sense to keep the docker files separate.

**Comment by cdeil** [comment]
OK, but still, IMO the common use case for this will be:

There's a failing test on travis-ci or circle-ci that a dev / maintainer doesn't see on their machine.
The great thing about this Docker image is that it let's everyone reproduce and debug the fail locally, by pulling the Docker image and running it.

So what I'm looking for is a mention of the existence of this option, and the two or three commands to do it, e.g. here: http://astropy.readthedocs.io/en/latest/#developer-documentation

And I still think putting the `Dockerfile` and the `.run_docker_tests.sh` file you're adding here in the same repo would be simpler / easier to use and maintain.

@astrofrog - I guess you're thinking of this differently, i.e. for now this is only for CI and only one or two experts have to know how it works in detail, not a good and common way to debug issues locally that's used more widely?

**Comment by bsipocz** [comment]
@astrofrog - Before merging this, would enable CircleCI on the main repo rather than on your fork?

**Comment by eteq** [comment]
I agree with @cdeil that this should be documented in the dev docs. I can see the arguments about which repo to put it in either way, though... I guess one unasked question is: might the docker file be used in some context other than CI? If so it shouldn't live in the helpers, but perhaps the script should. But if this docker is specifically for testing, it's going to be easier long term to keep it in ci-helpers.

**Comment by astrofrog** [comment]
Just to clarify, I'm not debating the general usefulness of this (not just CI) and I'm all for mentioning it in the docs, but not putting it in ci-helpers is just a pragmatic preference, given how much (deliberate) trouble it is to update things in that repository. For the user that wants to use the docker images, which repo the dockerfile is in is irrelevant to some extent since they just need to pull the image from docker.

**Comment by astrofrog** [comment]
@eteq @cdeil - I've added documentation in this PR. Note that I've only added a section about 32-bit Docker. @cdeil, maybe you could then add a section about 64-bit Docker for the Travis environment?

I didn't include/mention the script included in this PR because that script is very specific to just running the tests on CircleCI but the average developer just needs a single command to try this out locally (as explained in the docs).

**Comment by cdeil** [comment]
@astrofrog - Thanks!

I get this `astropy-helpers` issue when I try to follow the instructions to run the Astropy tests in the Docker image: https://gist.github.com/cdeil/a70a5fd3ba3608be0be4153210338bb3

Please don't wait for the 64-bit Docker image with this PR. I've put it on my TODO list and will make a separate PR with the Dockerfile and instructions when I have some time.

**Comment by astrofrog** [comment]
@cdeil - huh, any idea why it's using ``astropy_helpers-0.4.8``? Is this an old version of Astropy you are running the tests for?

**Comment by astrofrog** [comment]
@cdeil - are you still seeing this issue? It shouldn't be using such an old version of the helpers...

**Comment by astrofrog** [comment]
Since there are no objections, I'll go ahead and merge this! (will be good to get 32-bit testing running ahead of the 1.3 release)

**Comment by astrofrog** [comment]
No reason this can't be backported, since it will allow us to properly test the LTS release on 32-bit systems.

**Pull request merged**
