### PR TITLE
MNT: Replace distutils.log with astropy logger

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to replace the use of `distutils.log` with our own logger.

This is a direct follow-up of #10571 .

### CODE REVIEW

**Comment by pllim** [comment]
Remote failures unrelated.

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
Thanks @pllim!

**Comment by astrofrog** [comment]
@bsipocz This is what is causing the CI to fail in LTS since it means the testing command needs astropy to be installed, which it isn't when ``python setup.py test`` is first run. So I'll change the milestone to v4.1 since this is when we stopped using the astropy test runner for astropy core itself.

**Comment by pllim** [comment]
I am sorry...

puss_in_boots_sorry

**Pull request merged**
