### PR TITLE
Adding NUMPY_LT_1_10_4 to utils.compat

### LINKED ISSUE #5077: 1.2rc1 test failure in astropy.units
This is an unused version of python on this computer, thus the dependencies are far from being up to date. However I think the tests should not fail.
I'm updating numpy to see whether this go away.

```
=========================================================================================================== test session starts ============================================================================================================
platform linux2 -- Python 2.7.6, pytest-2.8.3, py-1.4.30, pluggy-0.3.1

Running tests with Astropy version 1.2rc1.
Running tests in /home/gkovacs/.local/lib/python2.7/site-packages/astropy.

Date: 2016-06-12T13:31:50

Platform: Linux-3.16.0-71-generic-x86_64-with-Ubuntu-14.04-trusty

Executable: /usr/bin/python

Full Python Version: 
2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]

encodings: sys: ascii, locale: UTF-8, filesystem: UTF-8, unicode bits: 20
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.10.1
Scipy: 0.16.0
Matplotlib: not available
h5py: not available
Pandas: not available
```

```
================================================================================================================= FAILURES =================================================================================================================
__________________________________________________________________________________________________ TestQuantityStatsFuncs.test_trace_func __________________________________________________________________________________________________

self = <astropy.units.tests.test_quantity_array_methods.TestQuantityStatsFuncs object at 0x7f81dedaeb50>

    @pytest.mark.xfail(NUMPY_LT_1_10, reason="Numpy 1.10 or later is required")
    def test_trace_func(self):
    
        q = np.array([[1.,2.],[3.,4.]]) * u.m
>       assert np.trace(q) == 5. * u.m
E       assert 5.0 == (5.0 * Unit("m"))
E        +  where 5.0 = <function trace at 0x7f81fd820230>(<Quantity [[ 1., 2.],\n           [ 3., 4.]] m>)
E        +    where <function trace at 0x7f81fd820230> = np.trace
E        +  and   Unit("m") = u.m

/home/gkovacs/.local/lib/python2.7/site-packages/astropy/units/tests/test_quantity_array_methods.py:366: AssertionError
==================================================================================== 1 failed, 10747 passed, 241 skipped, 43 xfailed in 152.41 seconds =====================================================================================
```

### PR DESCRIPTION
**Pull request by bsipocz**
to be able to xfail the test in units that require np >=v1.10.4

fixes #5077

cc @mhvk

### CODE REVIEW

**Comment by bsipocz** [comment]
This is weird, I'm not sure why all these failures are popping up here. This has something to do with the fact that the beta version is picked up for numpy from astripy-ci-extras (1.9.0b1) rather than a normal released version from the default conda channel. I wonder whether @astrofrog has any idea for it.

(Actually this fix should not have any effect on travis, as none of the conbination picked up the failure of #5077, but the PR was tested locally and passed with np 1.10.2)

**Comment by pllim** [comment]
I marked this as 1.2 since it is related to 1.2rc1 testing, but feel free to change.

**Comment by mhvk** [comment]
Thanks for the PR! The travis failure is indeed unrelated -- currently, all runs are failing for the same reason; @astrofrog, @eteq? I'll nonetheless hold off a bit on merging...

**Comment by MSeifert04** [comment]
There was a ``conda`` and ``conda-env`` update yesterday, maybe that's causing some trouble.

**Comment by bsipocz** [comment]
@mhvk - This is an issue for ``ci-helpers``, yesterday I hoped to see it go away, but since it didn't the quick workaround for now is in https://github.com/astropy/ci-helpers/issues/97. 
I can't merge it before the tests are run, but feel free to restart any of the failing builds once it's done.

**Comment by astrofrog** [comment]
Ah, is it related to this? https://github.com/conda/conda/issues/2675

**Comment by eteq** [comment]
Am I right in thinking someone restart the builds and that's why they're now passing despite all the comments indicating failures?  If so, this looks good to merge (and then I or @astrofrog will backport to 1.2)

**Comment by mhvk** [comment]
@eteq - yes, I restarted the build, and was planning to merge if it succeeded...  So, I'll do that now and you can backport...

**Comment by astrofrog** [comment]
Backported to v1.2.x. in 3f4b4f11a68573267ad808713bab05175aa45d95

**Pull request merged**
