### PR TITLE
Quantity latex repr change to ensure EarthLocation can be done

### PR DESCRIPTION
**Pull request by mhvk**
This is a simpler alternative to #5049 which allows `EarthLocation._repr_latex_()` to work by not changing any exponentials. This mainly to avoid introducing a new representation which is different from both `Quantity` and  `CartesianRepresentation`.

As a side effect, it ensures complex numbers are now not mangled up (but exponentials are still in`e+??` form).

### CODE REVIEW

**Comment by eteq** [comment]
@mhvk - I see your point here (and in https://github.com/astropy/astropy/pull/5049#issuecomment-225279931), so I'm fine with this instead of #5049.  But can you expand the regression test to include the non-scalar case? I.e., 5ea12a97c0d604da1a5d97ec5526826718f32eef + c7c27c89ab40d6b0b63bbea47936223a8c7faf2a + maybe  a5fac4e4e32469d71866aab27edf768493ad787a. (I included those because an earlier experiment I made with that would have cause some surprising failures in the array case, which would be good to catch if this stuff is ever altered again.)

**Comment by eteq** [comment]
Oh, and this needs a changelog entry (again, feel free to grab 9d11df696fc0d9692d5758bfffab32dee25decf9 and just update the number ;)

**Comment by mhvk** [comment]
OK, I added an array case. I decided not to test the actual representation since I think we should change that anyway -- probably best for it to be like `CartesianRepresentation`.

**Comment by eteq** [comment]
Alright, I merged this in its present form, and backported to 1.2 in 047e9384187b020da96bf5a82ffc8f551cf93e99 (as it was ready before the RC and not including it was just an oversight)

**Pull request merged**
