### PR TITLE
[EXP] Increase default remote timeout 

### PR DESCRIPTION
**Pull request by pllim**
Increase default remote timeout to see if that helps with remote tests being flaky. This was part of #5997 but then taken out.

Related discussion: #5994 

c/c @mhvk @bsipocz 

TODO:
- [x] Add milestone.
- [x] Add change log. (Not needed.)

### CODE REVIEW

**Comment by bsipocz** [comment]
@pllim - This looks good to me given the assumption this will help the tests pass. If they become unstable again, we can revert the default again.

I don't think this need a changelog, and milestone doesn't matter much as the bugfix branch will only have a few CI runs before release.

**Comment by pllim** [comment]
Well... Look at that... Remote tests failing even here! Maybe this is not the correct solution after all. 🤔

**Comment by bsipocz** [comment]
@pllim - let's hope it was a fluke, only one of the remote ones were failing  (now restrted) while previously it was all of them.

**Comment by pllim** [comment]
That test passed now. Remaining failures unrelated.

**Comment by bsipocz** [comment]
There are a few timeouts again, so I'm merging this in the hope it will have have some positive effect for those.

**Comment by pllim** [comment]
FWIW https://travis-ci.org/astropy/astropy/builds/229908432 is all green except the ufunc thingy.

**Comment by mhvk** [comment]
Lovely, I'll add `divmod` shortly.

**Comment by pllim** [comment]
Ops, and also this but we'll see if it is consistent or transient. 
```python
EarthLocation.of_address('1002 Holy Grail Court, St. Louis, MO') 
```

**Comment by mhvk** [comment]
Afraid it didn't help: https://travis-ci.org/astropy/astropy/jobs/230159642

**Comment by pllim** [comment]
@mhvk , did you post the wrong link? It shows green with
```
8985 passed, 121 skipped, 80 xfailed, 3 xpassed, 1 pytest-warnings in 394.27 seconds 
```

**Comment by mhvk** [comment]
Ah, I hadn't realised that if one restarts a test, the old log gets overwritten...

**Pull request merged**
