### PR TITLE
update ctype only if it's present in the original header

### PR DESCRIPTION
**Pull request by nden**
This fixes a [problem](https://github.com/astropy/astropy/pull/4814#issuecomment-219764329) reported by @keflavich and is an amendment to #4814. It covers the case of a WCS having more axes than the number of `CTYPE` keywords.
Also fixed an oversight - the log.info message is printed only when`wcs.sip is not None`.

### CODE REVIEW

**Comment by nden** [comment]
@eteq @astrofrog This is one more corner case in #4814. The Windows build failed from reasons unrelated to the PR and I can't restart it. Can this be included in 1.2?

**Comment by keflavich** [comment]
@nden a related issue: I now see this warning:
```
        Warning: to_header() was invoked without ``relax=True``: stripping all SIP
        coefficients from output header, and stripping "-SIP" from output CTYPE
        if it was originally present.

        Therefore astrometry obtained for output image may be different from
        original image because SIP is no longer present.

        Please inspect the headers of input and output images to verify, and
        modify the headers if necessary.
```

every time I do `to_header` (I think) - it is showing up far too often.  Perhaps it should also be restricted  to cases in which SIP coefficients are found?

**Comment by nden** [comment]
@keflavich I thought I fixed this in this PR (not merged yet). Are you seeing this with master or this PR?

**Comment by keflavich** [comment]
@nden on master.  Sorry, I haven't updated to this PR yet.  I didn't realize by browsing the code change that it would also hide the warnings.  I guess you said that in your original message, but I didn't parse it correctly.  Sorry!

**Comment by nden** [comment]
@keflavich No problem. I'm going to merge this so it can be easier to test before porting it to the 1.2 branch.

**Comment by nden** [comment]
@astrodsg @eteq This PR can be considered part of #4814. Should I port it to the 1.2 branch or is this not a good time?

**Comment by astrofrog** [comment]
@nden - since this is just a bug fix, no need to backport it yet, we'll backport all the 1.2.0 PRs in one go before the release candidate.

**Comment by nden** [comment]
Excellent!

**Pull request merged**
