### PR TITLE
Update development workflow doc

### PR DESCRIPTION
**Pull request by larrybradley**
The test runner now requires keyword arguments.

### CODE REVIEW

**Comment by parejkoj** [comment]
Would it be worth also mentioning in this doc that you can run the tests via e.g. `pytest astropy/units/tests/test_quantity.py`?

**Comment by larrybradley** [comment]
That can be fragile in a fresh source checkout (e.g. Cython modules won't be compiled).  The preferred method is to use `setup.py test -t <path>` or `setup.py test -P <package>`:

http://docs.astropy.org/en/stable/development/testguide.html?highlight=test%20-P#running-parts-of-the-test-suite

**Comment by parejkoj** [comment]
Granted. Could be useful to mention that or link to that from this part of the development workflow as well: being able to run a set of tests from the commandline is generally more useful than from within a python session (since one has to `reload()` code that was changed).

**Comment by pllim** [comment]
:scream: When did that happen?

**Comment by larrybradley** [comment]
@pllim It looks like this change occurred in https://github.com/astropy/astropy/pull/5505.

**Comment by pllim** [comment]
:+1:  Oh, okay. Does not look like an unintentional side effect from that PR. Thanks!

**Comment by bsipocz** [comment]
We need to retrospect mentioned it in the changelog for #5505 in the section of 1.3  that the keyword is mandatory from now on. Would you mind doing it in here?

**Comment by larrybradley** [comment]
@parejkoj I added examples of running the tests from the command line to the workflow doc.  I also linked to the testing guidelines from there.

@bsipocz I added a changelog entry for the #5505 API change.

**Comment by bsipocz** [comment]
Thanks again @larrybradley!

**Pull request merged**
