### PR TITLE
MNT: Remove defunct astropy-bot settings

### PR DESCRIPTION
**Pull request by pllim**
### Description

Heroku's greed killed the bot. We either use Actions or Giles now, so this setting is dead code and should be removed.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
naive question: is still related or expected ?
Screenshot 2024-06-06 at 10 58 38

**Comment by pllim** [comment]
That is a different bot at https://github.com/scientific-python/action-towncrier-changelog

Sometimes it does that. I think the event was lost somewhere over the Internet.

**Review by neutrinoceros — APPROVED** [review]

**Review by mhvk — APPROVED** [review]
Looks good! I won't merge since I'm not 100% sure about what astropy-bot even was, but I confirmed there is no other mention of it in the repository, so if you're happy, just go ahead and merge.

**Review by mhvk — APPROVED** [review]
Looks good! I won't merge since I'm not 100% sure about what astropy-bot even was, but I confirmed there is no other mention of it in the repository, so if you're happy, just go ahead and merge.

**Comment by pllim** [comment]
It is https://github.com/astropy/astropy-bot but has not been working for a long time.

**Comment by pllim** [comment]
Thanks, all!

**Pull request merged**
