### PR TITLE
Remove newline characters from header file 3d_cd.hdr

### LINKED ISSUE #10487: 4.1rc1: test_wtbarr_print fails during test
### Description

When I compile and and test 4.1rc1 for Debian (i.e. with an external wcslib; version 7.2), I get a failure during the build time test.

### Expected behavior

All tests pass

### Actual behavior

The following failure appears:

```
______________________________ test_wtbarr_print _______________________________

tab_wcs_2di = WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAB'  'DEC--TAB'  
CRVAL : 1.0  1.0  
CRPIX : 1.0  1.0  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : 1.0  1.0  
NAXIS : 150  200
capfd = <_pytest.capture.CaptureFixture object at 0x7f86e08ef190>

    def test_wtbarr_print(tab_wcs_2di, capfd):
        tab_wcs_2di.wcs.wtb[0].print_contents()
        captured = capfd.readouterr()
        s = str(tab_wcs_2di.wcs.wtb[0])
        lines = s.split('\n')
>       assert captured.out == s
E       AssertionError: assert '\n\n\n\n\n\n...: 0x49e43b8\n' == '     i: 1\n  ...: 0x49e43b8\n'
E         - 
E         - 
E         - 
E         - 
E         - 
E         - 
E         - ...
E         
E         ...Full output truncated (39 lines hidden), use '-vv' to show

astropy/wcs/tests/test_wtbarr.py:51: AssertionError
= 1 failed, 14395 passed, 440 skipped, 53 xfailed, 12 xpassed in 307.52 seconds =
E: pybuild pybuild:352: test: plugin distutils failed with: exit code=1: cd '/build/astropy-4.1~rc1/.pybuild/cpython3_3.8/build'; python3.8 -m pytest 
dh_auto_test: error: pybuild --test --test-pytest -i python{version} -p 3.8 returned exit code 13
```

### Steps to Reproduce

Build and test astropy on Debian sid, with  `ASTROPY_USE_SYSTEM_ALL=1`.

### System Details

```
Python 3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-5.4.0-4-amd64-x86_64-with-glibc2.29
>>> import sys; print("Python", sys.version)
Python 3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.18.4
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.4.1
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
```
wcslib is 7.2

### PR DESCRIPTION
**Pull request by mcara**
My hope is that this might fix #10487 

EDIT: Close #10544 

CC: @pllim @bnavigator

### CODE REVIEW

**Comment by pllim** [comment]
So, does this supersede #10544 ?

**Comment by mcara** [comment]
If it works.

**Comment by bnavigator** [comment]
Okay, I tried it out. Yes, the new file lets `Wcsprm()` not print out the newlines. The tests pass.

So, has the "original" 3d_cd.hdr an invalid format with the newlines or is this allowed by the specification?

**Comment by mcara** [comment]
I think this should be merged regardless of #10487

**Comment by mcara** [comment]
@bnavigator Many thanks!

I think so. Headers do not have `'\n'` at the end of the line. Lines are supposed to be 80 character long and one can compute the number of lines as `len(header)/80`.

When I tried to create a header from this `3d_cd.hdr` file, I get:

```
In [110]: hdr = fits.Header.fromfile('/.../astropy/wcs/tests/data/3d_cd.hdr', endcard=False, padding=False)
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:

CD1_3   =                    0                                                  [astropy.io.fits.card]
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:

CD1_1   =            -4.12E-05                                                 [astropy.io.fits.card]
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:

CUNIT3  = 'nm      '                                                          [astropy.io.fits.card]
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:

CUNIT2  = 'deg     '                                                         [astropy.io.fits.card]
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:

CTYPE1  = 'RA---TAN'                                                        [astropy.io.fits.card]
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:

NAXIS   =                    3                                             [astropy.io.fits.card]
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:

CTYPE3  = 'AWAV    '                                                      [astropy.io.fits.card]
```

**Comment by mcara** [comment]
> So, has the "original" 3d_cd.hdr an invalid format with the newlines or is this allowed by the specification?

FITS standard does not allow `'\n'` at the end of the lines. However, in principle, there is nothing preventing `WCVSLIB` or `astropy` being able to deal with this kind of string if they wanted to support non-standard strings. My guess is that `WCSLIB` follows standard because it uses `CFITSIO`.

**Comment by pllim** [comment]
This file wasn't touched for 9 years. It was moved from `pywcs` to `astropy` by Mike D. 🤷‍♀️

**Comment by pllim** [comment]
Also, you can remove the warning catch now. 😄 
```
 Failed: DID NOT WARN. No warnings of type (<class 'astropy.utils.exceptions.AstropyUserWarning'>,)
```

**Comment by bnavigator** [comment]
And it doesn't create a problem with the bundled wcslib. Only with system provided one. Although the source for wcslib 7.3 is 100% identical between the openSUSE package and the cextern/wcslib after #10433 (minus trim_wcslib.sh) directory. Maybe the compiler flags?

**Comment by mcara** [comment]
So, if `'\n'` was left in the header as it was here, it was practically the 81st character and it was shifting every (next) line by a character. This creates a mess in the header. For example, with the header created above in https://github.com/astropy/astropy/pull/10545#issuecomment-655723185 if you tried to access keywords defined in `3d_cd.hdr`, you would get:
```
In [121]: list(hdr.keys())
Out[121]:
['CD1_2',
 'CD1_3',
 'CD1_1',
 'CUNIT',
 'CUNI',
 'CTY',
 'NA',
 'C',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '']

In [122]: print(hdr['CD1_2'])
     ...: print(hdr['CD1_3'])
     ...: print(hdr['CD1_1'])
     ...: print(hdr['CUNIT1'])
-3.72e-05
 =                    0
  =            -4.12E-05
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-122-e9219e73fae0> in <module>
      2 print(hdr['CD1_3'])
      3 print(hdr['CD1_1'])
----> 4 print(hdr['CUNIT1'])
KeyError: "Keyword 'CUNIT1' not found."
```

**Comment by bnavigator** [comment]
What about sub-segfault.hdr?
https://github.com/astropy/astropy/blob/9afd551f1246da2eaf9a63aa0500f96aa298434a/astropy/wcs/tests/data/sub-segfault.hdr#L1-L28

**Comment by mcara** [comment]
@bnavigator That one works fine because header is created using `fits.Header.fromtextfile` as opposite to `fits.Header.fromfile`

**Comment by pllim** [comment]
I tried digging a bit with help from @jhunkeler but didn't any new info. I think the file has been "wrong" since the beginning.
```
plnott> svn log 3d_cd.hdr
------------------------------------------------------------------------
r2176 | stsci_embray | 2011-07-01 18:57:30 -0400 (Fri, 01 Jul 2011) | 1 line

Merging the setup_refactoring branch into trunk.  This should only affect pysynphot, pywcs, stsci_python, and coords at this point
------------------------------------------------------------------------
r2135 | stsci_embray | 2011-06-17 15:36:39 -0400 (Fri, 17 Jun 2011) | 1 line

Merging up to r2127 from trunk.  This brings the branch up to date with the current trunk.
------------------------------------------------------------------------
r2091 | stsci_mdroe | 2011-05-27 10:09:56 -0400 (Fri, 27 May 2011) | 1 line

Adding missing file
------------------------------------------------------------------------

```

**Comment by nden** [comment]
I agree this is the solution. The error was hidden by the `with` statement. Removing it shows the file does not create a valid header. Thanks all for figuring it out!

**Pull request merged**
