### PR TITLE
Updating astropy_helpers to 3.2

### PR DESCRIPTION
**Pull request by bsipocz**
Trivial minor change due to tagging the helpers release. Please do approve but leave the merging to me, so I can be sure it's merged when the release is pushed to pypi.

### CODE REVIEW

**Comment by pllim** [comment]
Hmmm... `mpldev` failure:

```
E           RuntimeError: latex was not able to process the following string:
E           b'lp'
E           
E           Here is the full report generated by latex:
E           This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=latex)
E            restricted \write18 enabled.
E           entering extended mode
E           (/root/.cache/matplotlib/tex.cache/1acea6f6c115d0ec7a634ed0529287b9.tex
E           LaTeX2e <2016/02/01>
E           Babel <3.9q> and hyphenation patterns for 3 language(s) loaded.
E           (/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
E           Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
E           (/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
E           (/usr/share/texlive/texmf-dist/tex/latex/type1cm/type1cm.sty)
E           
E           ! LaTeX Error: File `type1ec.sty' not found.
E           
E           Type X to quit or <RETURN> to proceed,
E           or enter new name. (Default extension: sty)
E           
E           Enter file name: 
E           ! Emergency stop.
E           <read *> 
E                    
E           l.5 \usepackage
E                          {type1ec}^^M
E           No pages of output.
E           Transcript written on 1acea6f6c115d0ec7a634ed0529287b9.log.
```

Would installing some extra stuff like what https://stackoverflow.com/questions/11354149/python-unable-to-render-tex-in-matplotlib says fix this?

**Comment by bsipocz** [comment]
But then I don't understand why this is not failing for the other PRs.

**Comment by pllim** [comment]
I don't understand either. Might just be a coincidence... Let me start a fresh dummy PR and see.

**Comment by pllim** [comment]
Yeah, it is indeed not failing in other PRs... 🤔

**Comment by pllim** [comment]
How could possibly updating helpers break mpldev on CircleCI? Does that action somehow clear matplotlib texcache? Makes no sense! 🙏 @astrofrog 🙏

**Comment by bsipocz** [comment]
@pllim reminded me that circleCI always had issues with updates for the submodule, so we should probably go ahead and merge this and then see whether the issues magically disappears just as they appeared.

**Comment by bsipocz** [comment]
Merging as circleCI is known not to work well with submodule updates. Merging with the hope that it will work in master (there is no reason to suspect that the failures are related to changes here and master is OK atm).

**Pull request merged**
