### PR TITLE
astropy test framework's disable_internet is incompatible with python 3.4 multiprocessing forkserver

### PR DESCRIPTION
**Pull request by embray**
Attn @embray, @mdboom, @josephoenix - 

Here's another case of the astropy test framework customizations having unintended consequences for packages using the affiliated package template. 

For [poppy](https://github.com/mperrin/poppy) on Python 3.4 when doing multiprocess parallelized calculations I just switched it to use the new (as of Python 3.4) `forkserver` method for starting additional processes. (See https://github.com/mperrin/poppy/issues/23 and https://github.com/numpy/numpy/issues/5752 for the reasons why).   The code works as intended in normal operations, but under testing it gets blocked by `astropy/tests/disable_internet.py`. Here's the tail end of the exception traceback:

```python
/Users/mperrin/software/macports/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/forkserver.py:108:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<socket.socket [closed] fd=-1, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>, '/var/folders/wj/p62fp78j0z1b4xyr2yql1prw00042w/T/pymp-g72qatlv/listener-paqlzej6')
kwargs = {}, hostname = 'peregrine.stsci.edu', fqdn = 'peregrine.stsci.edu', valid_hosts = ('localhost', '127.0.0.1', '::1')

    def new_function(*args, **kwargs):
        hostname = socket.gethostname()
        fqdn = socket.getfqdn()

        if isinstance(args[0], socket.socket):
            host = args[1][0]
            valid_hosts = ('localhost', '127.0.0.1', '::1')
            if host in (hostname, fqdn):
                host = 'localhost'
                args = (args[0], (host, args[1][1])) + args[2:]
        else:
            host = args[0][0]
            valid_hosts = ('localhost', '127.0.0.1')
            if host in (hostname, fqdn):
                host = 'localhost'
                args = ((host, args[0][1]),) + args[1:]

        if any([h in host for h in valid_hosts]):
            return original_function(*args, **kwargs)
        else:
>           raise IOError("An attempt was made to connect to the internet "
                          "by a test that was not marked `remote_data`.")
E           OSError: An attempt was made to connect to the internet by a test that was not marked `remote_data`.

```

So for some reason `forkserver` is using the fully qualified domain name of my computer instead of "localhost" and thus it's getting blocked. 

Not sure what the best solution here is. I'd sort of like to be able to decorate that test function and say "please run this anyway; it's allowed to use network sockets even if remote_data is off". It feels slightly kludgy to turn on `remote_data` for this because it truly does not access any data remotely.  Also it's not obvious to me how one would set remote_data from the command line, in particular for our Travis CI build matrix. 

```
 > python setup.py test --remote_data
error: option --remote_data not recognized
```

What do you think is the best approach?

### CODE REVIEW

**Comment by embray** [comment]
@mperrin @josephoenix When you get a chance, would it be possible for one of you to try out the attached fix and confirm that it takes care of the issue?

**Comment by josePhoenix** [comment]
I seem to be missing the test case @mperrin was using, but I wrote a dummy one

```python

def square_this_int(this_int):
    return this_int ** 2

def test_removeme_multiprocessing():
    import multiprocessing
    ctx = multiprocessing.get_context('forkserver')
    pool = ctx.Pool(4)
    result = pool.map(square_this_int, [1,2,3,4,5])
    pool.close()
    pool.join()
```

I verified that it produced the `OSError: An attempt was made to connect to the internet by a test that was not marked remote_data` message with the released version of astropy (1.0.2), and it does not produce this error with @embray's branch.

**Comment by josePhoenix** [comment]
Ah, I couldn't find the test case because I was looking in webbpsf instead of POPPY. This patch definitely fixes it, once we remove the `@remote_data` decorator.

**Comment by embray** [comment]
Cool, thanks for testing it.  I'll merge this in a bit.

**Comment by josePhoenix** [comment]
Thanks!

For regression test writing, I should mention that the `forkserver` option and the context object are only available on >=3.4. It looks like this issue doesn't appear in 2.7, however.

**Comment by embray** [comment]
Oops, I totally bungled the logic in the skipif decorator first time around.  Fixed now.

**Pull request merged**
