### PR TITLE
Allow specifying parse_strict for units when reading FITS tables

### PR DESCRIPTION
**Pull request by maxnoe**
### Description

This pull request is to address the first half of #11842, so we can get unit warnings / errors when reading FITS files.

### CODE REVIEW

**Comment by maxnoe** [comment]
I suspect that the wcs plotting test failures are unrelated...

**Comment by pllim** [comment]
Ignore mpldev failure -- See #11841

**Comment by astrofrog** [comment]
I am re-milestoning to v5.1 as we've now branched v5.0.x

**Comment by saimn** [comment]
@maxnoe, could you rebase and add the changelog entry ? Thanks.

**Comment by maxnoe** [comment]
@saimn Yes, will do.

How would you feel about changing the default to `warn`?

I guess most people would not discovery this setting but an invalid unit should raise a warning as the undefined unit is not that easy to discovery, which is what lead me to create this PR.

Aldingen a new warning is not a breaking change regarding to the astropy conventions, right?

**Comment by saimn** [comment]
Using `warn` seems indeed a good idea.

**Comment by maxnoe** [comment]
Rebased, changed default to warn and added a changelog. Please have a look again.

**Comment by maxnoe** [comment]
There are actually quite a lot test files with invalid units. Are any of those under our control or are these all external resources?

See where I had to add the `with pytest.warns(UnitWarning)` in the tests and `+IGNORE_WARNINGS` in the docs

**Comment by saimn** [comment]
The new warnings seem normal to me, some are from tests using non standard units, some from external files (https://github.com/astropy/astropy-data/tree/gh-pages/timeseries). So I think it's all good, thanks @maxnoe !

**Review by saimn — APPROVED** [review]

**Pull request merged**
