### PR TITLE
Update lombscargle.rst

### PR DESCRIPTION
**Pull request by ivezic**
A tiny fix...

### CODE REVIEW

**Comment by ivezic** [comment]
I think the fix was correct.

**Comment by pllim** [comment]
@ivezic , did you intentionally close this PR?

**Comment by ivezic** [comment]
I did - it was only a single character change, but it looks more and more
like the astropy crew will be after me with pitchforks…
        Z.

**Comment by pllim** [comment]
I am sorry you feel that way. If it is indeed a valid fix, there is no reason you shouldn't submit the fix. We had merged similar PRs before. Feel free to re-open if you change your mind.

**Comment by ivezic** [comment]
Are you saying that I aborted that fix somehow? I thought it was merged…
       Z.

**Comment by ivezic** [comment]
I totally misunderstood what was happening - reopening...

**Comment by astrofrog** [comment]
@ivezic - what might have happened, which happens from time to time to all developers, is that you may have clicked 'close and comment' instead of comment. I do that surprisingly often...

**Comment by astrofrog** [comment]
@jakevdp - can you confirm this is correct? Thanks!

**Comment by pllim** [comment]
@jakevdp , could you have a look, please? Thanks!

**Comment by jakevdp** [comment]
Thanks for the correction @ivezic – the change looks good to me!

**Comment by bsipocz** [comment]
@pllim - Travis has serious issues with the OSX infrastructure, so I've cancelled that job (and that was quite irrelevant for this change, as it only affects the docs build). 

As it's approved, I'm merging now.

Thanks @ivezic!

**Pull request merged**
