### PR TITLE
Add furlong to units

### PR DESCRIPTION
**Pull request by PBarmby**
Trying out the workflow while not breaking anything important. Permits conversion of velocities into u.furlong/u.fortnight !

### CODE REVIEW

**Comment by embray** [comment]
I could have sworn we had furlong...

**Comment by mdboom** [comment]
Looks fine to me, except the commit hash of astropy_helpers is inadvertently changed...  Here's how I would fix it (there's multiple ways as always with git).

```
git rebase -i   # Interactively edit the commits on this branch
```

This *should* open up a list of commits in your editor.  For the first one "initial definition of furlong", change the work `pick` to `edit` and save the file and exit the editor.

Then

```
git checkout -- astropy_helpers
```

which will revert any local changes to astropy_helpers.

Then

```
git add astropy_helpers
git commit --amend
git rebase --continue
```

**Comment by mdboom** [comment]
Reminds me of visiting the CN Tower just this past weekend.  They have everything in funny units up there like: "this glass floor can hold 35 moose".  Is that a metric or imperial moose?

**Comment by PBarmby** [comment]
Canadian moose are some strange hybrid of imperial and metric (as well as being bilingual).

When I try `git rebase -i` I get:
```
noop

# Rebase 45050f2..45050f2 onto 45050f2
```
which doesn't seem to go with what you had above? Sorry, rebasing is a bit beyond my current experience!

**Comment by pllim** [comment]
Maybe a spherical moose?

**Comment by mdboom** [comment]
Hmm...  I've never seen that before.  Are you on the right branch?  Does doing: `git checkout add-furlong` first help?

**Comment by PBarmby** [comment]
Yes, I was on the right branch. When I did the initial commit on the branch I added astropy_helpers (it was showing up as changed) as well as imperial.py.
Should I just make a new branch and try again but this time ignoring astropy_helpers?

**Comment by pllim** [comment]
Usually `git submodule update` works for me.

**Comment by astrofrog** [comment]
@pllim - indeed that works too, but in order to remove an existing change to ``astropy-helpers`` from a previous commit, rebasing is required.

@PBarmby - can you try ``git rebase -i upstream/master`` instead of just ``git rebase -i``?

**Comment by PBarmby** [comment]
I think the combination of @astrofrog & @mdboom's suggestions worked, thanks both! For other newcomers to this, I'll note that you need `git rebase -i astropy/master` (if you set up the remote the way the [docs](http://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#set-upstream-master) suggest, and you need `git push -f`to push after rebasing.

**Comment by astrofrog** [comment]
@PBarmby - for some reason, ``astropy_helpers`` is still being changed. Did you have any issues when trying the commands @mdboom provided for amending the first commit?

**Comment by Cadair** [comment]
:+1:

**Comment by PBarmby** [comment]
No issues; pretty sure I followed his commands exactly. Wonder if I have messed up my copy of `astropy_helpers` somehow?

**Comment by mdboom** [comment]
I just tried myself with a copy of your branch.  TL;DR git submodules are tricky and even trip up all of us "git veterans" it seems...

I did:

```
git rebase -i upstream/master
```

I changed the first line to start with `edit`.

Then:

```
git submodule update  # <-- new step
git commit --amend
git rebase --continue
```

Then to update github's copy:

```
git push -f origin add-furlong
```

**Comment by PBarmby** [comment]
Nope, adding `submodule update` and rebasing still resulted in `astropy_helpers` noted as being changed. I don't want to waste everyone's time messing about with this, so I just made a new branch with the same changes (but without touching `astropy_helpers`) and it does seem OK -- see #3529.

**Comment by mdboom** [comment]
Ok.  Sorry we weren't able to help.  `git` can be inscrutable at times.

**Comment by astrofrog** [comment]
@mdboom @embray - this might be a weird solution, but how about we add astropy-helpers to .gitignore? That way it will never let users commit it by default, and one would always have to force a commit which would ensure no accidental updating? The sort of issue above happens a lot.

**Comment by mdboom** [comment]
Yeah -- I think the only person that ever *means* to update it is @embray...

Unfortunately, I don't think adding it to `.gitignore` has any effect, since `astropy_helpers` is already in the repo.  I think `.gitignore` just affects non-source-controlled files and directories.

**Comment by embray** [comment]
Hey, I'm not the only one who's ever updated it ;)

The real problem is using `git commit -a` which I think should be recommended against *in general* (I almost never do it unless I've made sure to review the diff of my commit first).  I'll look into whether there's a way to exclude certain paths from `git commit -a`.

**Comment by embray** [comment]
Running
```
$ git update-index --assume-unchanged <file>
```
will basically make git ignore changes to a specified file.  However, this needs to be set manually on a per-clone basis.  What there ought to be, and what there is not, is a way to specify this in the `.gitattributes` file.  BRB patching git...

**Comment by embray** [comment]
(Also one shortcoming I've noticed in --assume-unchanged is that *really* means it--`git status` won't even tell you that the file is changed, which could be immensely confusing.  There really ought to be a way to show that a file has been changed, but to always exclude changes to that file from commits by default.)

**Pull request closed without merging**
