### PR TITLE
Update broken and permanently redirected links

### PR DESCRIPTION
**Pull request by astrofrog**
Running ``make linkcheck`` revealed a bunch of links that were broken or permanently redirected! (I ignored non-permanent redirects). Some of them are just http -> https but since they are permanent redirects I'd like to fix them to avoid warnings when running linkcheck in future.

@crawfordsm @larrybradley - I could not find what the new URL for this one is:

```
api/astropy.stats.akaike_info_criterion.rst:72: [broken] http://myweb.uiowa.edu/cavaaugh/ms_lec_2_ho.pdf
```

Could you let me know what this should be instead?

Ah the joys of linking to academic websites 😆

### CODE REVIEW

**Comment by larrybradley** [comment]
@astrofrog I was able to find a replacement link (and added a commit).

**Comment by astrofrog** [comment]
@larrybradley - thanks!

**Comment by astrofrog** [comment]
I just noticed another link where it's not immediately obvious what it should be:

http://homepage.stat.uiowa.edu/~kcowles/s166_2009/lect11.pdf

(at least for me it says 'Forbidden')

**Comment by larrybradley** [comment]
I can't find an update for that link.

BTW, I think you clobbered my earlier commit.  :)

**Comment by bsipocz** [comment]
I wonder whether we should add running ``make linkcheck`` as well as running spell check as a box to tick before major releases? (I don't mean as part of the release, but shortly after feature freeze?)

**Comment by larrybradley** [comment]
For the second stats link, I think we should just add a link to the wikipedia page: 
 https://en.wikipedia.org/wiki/Jackknife_resampling

**Comment by astrofrog** [comment]
@bsipocz - yes I think this would be good to add to the checklist of things before release (certainly not something to add to the CI)

**Comment by astrofrog** [comment]
@larrybradley - oops! Didn't mean to do that... Can you add it back? (I don't think I have it locally)

**Comment by larrybradley** [comment]
@astrofrog Done.  I also replaced the broken `jackknife` link.

**Comment by astrofrog** [comment]
Since @bsipocz already approved this, I'll go ahead and merge

**Pull request merged**
