### PR TITLE
DEP: drop support for numpy 1.x

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
NumPy 2.0.0rc1 is here, and new is better, so let's just onboard our users onto the hype train and just pull the bandaid immediately !
- better promote all the hard work that went into numpy 2.0
- improved performance for end users ...
- ... and cheaper CI for everyone dowstream of us !
- better science (?)!

in short: WCGW ?

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
CI failure seem irrelevant, could anyone force-merge this ?

**Comment by astrofrog** [comment]
Sounds reasonable, I think all users should be on Numpy 2.0.0rc1 by now anyway!

**Comment by pllim** [comment]
> I think all users should be on Numpy 2.0.0rc1 by now anyway

I don't understand this. Pipelines need time to adapt. Building with numpy 2.0 is one thing, but to _require_ numpy 2.0 to run is a little extreme at this point?

**Comment by MridulS** [comment]
> but to require numpy 2.0 to run is a little extreme at this point?

I think users would need to make a hard choice between numpy 1.x and 2.x. This is almost
like py2 vs py3 in my head and I think it's perfectly reasonable to force min numpy 2.0 ASAP.

Also this cleans up our codebase a lot!

**Comment by neutrinoceros** [comment]
@pllim @MridulS this was my April's fools PR, hope you don't mind that I close it now :-)

**Comment by pllim** [comment]
You got me there! 👏

**Comment by MridulS** [comment]
Nooo!

**Pull request closed without merging**
