### PR TITLE
Use conda to install dependencies on RTD

### PR DESCRIPTION
**Pull request by astrofrog**
This is a work in progress - I need to do a test build to make sure this works correctly

### CODE REVIEW

**Comment by astrofrog** [comment]
It seems to work fine: http://astropy-test.readthedocs.org/en/latest/

However, for now I've got the PDF and EPUB builds disabled. Do we actually need these?

**Comment by cdeil** [comment]
@astrofrog - Sweet! I didn't know RTD supported conda.

There's this error for this PR!?
https://travis-ci.org/astropy/astropy/jobs/106807279#L4259

> for now I've got the PDF and EPUB builds disabled. Do we actually need these?

I've actually put the EPUB version on my ipad years ago and used it a bit.
But probably there's very few people that use PDF or EPUB, so it it's hard to make it work it might be OK to drop it.

**Comment by bsipocz** [comment]
@cdeil - The error unrelated, that build should pass after restart.

**Comment by cdeil** [comment]
@bsipocz - I restarted that build and it failed with the same error:
https://travis-ci.org/astropy/astropy/jobs/106807279

**Comment by cdeil** [comment]
travis-ci builds all passed now.

:+1:

**Comment by Cadair** [comment]
lgtm

**Comment by astrofrog** [comment]
I'm going to go ahead and merge this since it seems to be running fine on RTD.

**Pull request merged**
