### PR TITLE
Ensure that a masked array is returned when sigma clipping fully masked data

### LINKED ISSUE #5635: sigma_clip fails for fully masked data
If one passes in an empty or fully masked array to sigma clip, one gets a rather uninformative error:
```
sigma_clip(np.ma.MaskedArray([1.], mask=[True]))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-390a3ff2b18a> in <module>()
----> 1 sigma_clip(np.ma.MaskedArray([1.], mask=[True]))

/usr/lib/python3/dist-packages/astropy/stats/sigma_clipping.py in sigma_clip(data, **kwargs)
     28                           'Please use the "stdfunc" keyword instead.')
     29 
---> 30     return _sigma_clip(data, **kwargs)
     31 
     32 

/usr/lib/python3/dist-packages/astropy/stats/sigma_clipping.py in _sigma_clip(data, sigma, sigma_lower, sigma_upper, iters, cenfunc, stdfunc, axis, copy)
    206     else:
    207         for i in range(iters):
--> 208             perform_clip(filtered_data, kwargs)
    209 
    210     # prevent filtered_data.mask = False (scalar) if no values are clipped

/usr/lib/python3/dist-packages/astropy/stats/sigma_clipping.py in perform_clip(_filtered_data, _kwargs)
    177                 min_value = np.expand_dims(min_value, axis=axis)
    178                 max_value = np.expand_dims(max_value, axis=axis)
--> 179         _filtered_data.mask |= _filtered_data > max_value
    180         _filtered_data.mask |= _filtered_data < min_value
    181 

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Of course it is not always possible to take into account all weird combinations of data one can get, but it would probably be good to test whether `max_value is masked`, and return appropriately. (`np.ma.median` returns `masked` for the 1-d case, and, oddly, unmasked `np.nan` for the >1-d case)

### PR DESCRIPTION
**Pull request by mirca**
Does this suffice to close #5635?

cc @mhvk @larrybradley @crawfordsm

### CODE REVIEW

**Comment by mhvk** [comment]
Thinking a bit more about it, I'm not all that sure we want an error after all... This partially because for the multi-D case, we will not raise an error either, but rather just returns fully masked data:
```
In [26]: data = np.ma.MaskedArray(data=[[1., 0.], [0., 1.]], mask=[[True, True], [True, True]])

In [27]: sigma_clip(data, axis=1)
Out[27]: 
masked_array(data =
 [[-- --]
 [-- --]],
             mask =
 [[ True  True]
 [ True  True]],
       fill_value = 1e+20)
```

So, perhaps we should just ensure we return fully masked/clipped data for the no-axis-passed-in case as well? I would do this very simply:
```
if max_value is np.ma.masked:
    max_value = np.ma.MaskedArray(np.nan, mask=True)
```

And then adapt the test to ensure that it indeed returns fully masked data.

**Comment by larrybradley** [comment]
@mhvk beat me to it, but I also don't think we want to raise an error and simply return the fully-masked array.

**Comment by mirca** [comment]
@mhvk @larrybradley So, should we throw a friendly warning and return the fully masked array?

**Comment by mhvk** [comment]
I think I would not even give a warning. In some sense, if you put in a fully masked array, I think the expectation would be to get back a fully masked one.

**Comment by larrybradley** [comment]
I also don't think a warning is needed.

**Comment by crawfordsm** [comment]
I'd agree that no-warning is needed.

**Comment by mirca** [comment]
@mhvk further thoughts here? :)

**Comment by mhvk** [comment]
@mirca - this all looks OK. It is a bit out of scope for this PR, but would you be able to add a test for an empty array (which should return an empty array)? Also, do add an entry in `CHANGES.rst`.

**Comment by mhvk** [comment]
Sorry to ask for yet more, but while you are at it, also check an empty normal array?

**Comment by mirca** [comment]
@mhvk 

```
>>> x = np.array([])
>>> sigma_clip(x)
/Users/jvmirca/anaconda3/envs/py35/lib/python3.5/site-packages/numpy-1.13.0.dev0+32ade3a-py3.5-macosx-10.6-x86_64.egg/numpy/ma/core.py:5060: RuntimeWarning: Mean of empty slice.
  dtype=dtype, **kwargs)[()]
/Users/jvmirca/anaconda3/envs/py35/lib/python3.5/site-packages/numpy-1.13.0.dev0+32ade3a-py3.5-macosx-10.6-x86_64.egg/numpy/core/_methods.py:73: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/Users/jvmirca/anaconda3/envs/py35/lib/python3.5/site-packages/numpy-1.13.0.dev0+32ade3a-py3.5-macosx-10.6-x86_64.egg/numpy/ma/core.py:5138: RuntimeWarning: Degrees of freedom <= 0 for slice
  ddof=ddof, **kwargs)[()]
/Users/jvmirca/anaconda3/envs/py35/lib/python3.5/site-packages/numpy-1.13.0.dev0+32ade3a-py3.5-macosx-10.6-x86_64.egg/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/Users/jvmirca/anaconda3/envs/py35/lib/python3.5/site-packages/numpy-1.13.0.dev0+32ade3a-py3.5-macosx-10.6-x86_64.egg/numpy/core/_methods.py:125: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
masked_array(data = [],
             mask = [],
       fill_value = 1e+20)
```

also:
```
>>> np.mean(x)
/Users/jvmirca/anaconda3/envs/py35/lib/python3.5/site-packages/numpy-1.13.0.dev0+32ade3a-py3.5-macosx-10.6-x86_64.egg/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/jvmirca/anaconda3/envs/py35/lib/python3.5/site-packages/numpy-1.13.0.dev0+32ade3a-py3.5-macosx-10.6-x86_64.egg/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
nan
```

**Comment by mhvk** [comment]
OK, never mind, this is getting too far from the original point. Just add an entry to `CHANGES.rst` and I think this is done! (with `[skip ci]` to avoid burning unnecessary time on travis, etc.)

**Comment by mhvk** [comment]
@mirca -- I must admit I have no idea why the tests pass on some numpy versions and not others, but I think I just made a bad judgement call in asking for any tests on empty arrays...  Two choices: add a line just returning the input when `input.size == 0` and then also add a test for a regular empty arry, or remove the last commit; the way I would do the latter:
```
git rebase -i upstream/master
# remove the last commit in the editor, and save
git push -f
```

**Comment by mhvk** [comment]
p.s. Don't forget the changelog entry!

**Comment by mirca** [comment]
@mhvk done

**Comment by crawfordsm** [comment]
Looks good and thanks @mirca !

**Pull request merged**
