### PR TITLE
Backport PR #15892 on branch v6.0.x (units: remove vestigial cosmo imports)

### PR DESCRIPTION
**Pull request by nstarman**
Backport PR #15892 on branch v6.0.x

### CODE REVIEW

**Review by mhvk — APPROVED** [review]

**Comment by pllim** [comment]
Wait a minute. Why does this warrant a backport?

**Review by eerovaher — APPROVED** [review]
This is a follow-up to 43ba76f63aeb2488d4dc8c30810e1feb79457928 and is removing functionality that doesn't work in 6.0 anyways. The aforementioned commit removed the ability to import `littleh` from `units.astrophys` and `with_H0` from `units.equivalencies` together with the tests that checked that those imports were deprecated. What that commit missed was that it was also possible to import `littleh` and `with_H0` from `units`. This was partially because there were no tests for that, and partially because `littleh` and `with_H0` are still available from `cosmology.units`, so grepping for them will reveal many matches and nobody went through all them to see if they should have been removed at the time.

**Comment by pllim** [comment]
But... isn't this still technically API change in a bug fix even though it was an oversight? 🤔 

xref https://github.com/astropy/astropy/pull/15514

**Comment by pllim** [comment]
But since there are two approvals, I guess it's fine? 🤷‍♀️ 

Going to close/reopen to make bot happy.

**Comment by mhvk** [comment]
@pllim - with or without this PR people get an AttributeError if they try to use `u.littleh`, so it's definitely not an API change. It just seems cleaner to remove the cruft also in 6.0!

**Pull request merged**
