### PR TITLE
Fix PLW0120 warnings in Astropy library

### PR DESCRIPTION
**Pull request by Maia-jp**
This pull request addresses multiple instances of the PLW0120 warnings in the Astropy library. The PLW0120 warning indicates the presence of an else clause on a loop without a break statement, which can lead to code readability issues. To resolve this, the else clauses are removed, and the code inside them is properly de-indented.

The affected files and line numbers are as follows:
- astropy/coordinates/representation/base.py:1355
- astropy/io/ascii/ipac.py:167
- astropy/io/ascii/latex.py:87
- astropy/io/ascii/ui.py:601
- astropy/io/fits/header.py:1403
- astropy/io/registry/core.py:153, 332
- astropy/modeling/bounding_box.py:1255
- astropy/table/index.py:677
- astropy/time/core.py:612
- astropy/time/formats.py:1510

Fix: #14908

### CODE REVIEW

**Comment by nstarman** [comment]
Thanks @Maia-jp for the PR!
2 things (in this order):

1. Please edit the `.ruff.toml` file, removing PLW0120, so that ruff, through pre-commit, will continue to check that PLW0120 is fixed.
2. Can you please amend your last commit after running `pre-commit run -a` on your machine. Then the Pre-commit CI should pass and we can assess this PR.

Thanks!

**Review by nstarman — APPROVED** [review]
Thanks @Maia-jp for the PR!

**Review by nstarman — CHANGES_REQUESTED** [review]
Look a like some of the fixes are triggering other cleanup. Please run `pre-commit run -a` on you machine and amend the commit. The PLW0120 stuff all looks good.

**Comment by nstarman** [comment]
Thanks @Maia-jp. If you could squash your commits, then I think this PR would be ready to merge. IMO, removing extraneous `else` statements increases code readability, so I'm happy to see this go in.

**Comment by dhomeier** [comment]
Not sure if I can follow the logic of the rule or the fix here – it refers to loops without a break, but at least the `io.ascii` cases I have looked at here have _implicit_ breaks in the form of `return` statements in the preceding loop cases. So in that case the `else` should still never be reached either way, but it looks rather a bit different from the example https://beta.ruff.rs/docs/rules/useless-else-on-loop/#useless-else-on-loop-plw0120
To me, the `else` rather makes the code structure clearer by indicating the block as the alternative to the preceding cases, but maybe being able to de-indent the remainder of the code outweighs this...
Anyway since this is not the place for discussion whether the ruff rule is put in effect, I won't object to this if the other maintainers are fine with it.

**Comment by eerovaher** [comment]
> Not sure if I can follow the logic of the rule or the fix here – it refers to loops without a break, but at least the `io.ascii` cases I have looked at here have _implicit_ breaks in the form of `return` statements in the preceding loop cases...

`break` statements and `return` statements are not the same.

**Comment by dhomeier** [comment]
> `break` statements and `return` statements are not the same.

Obviously not. Nevertheless it does not fulfil the _always terminates "normally"_ condition from
https://beta.ruff.rs/docs/rules/useless-else-on-loop/#why-is-this-bad

> If a loop always terminates "normally" (i.e., does not contain a break), then the else clause is redundant, as the code inside the else clause will always be executed.

– if one of the `return` conditions is met, that code will not be executed.
Again, functionally it should make no difference, as it will not be executed here either way, I just do not agree that the change better represents the code structure.

**Comment by eerovaher** [comment]
This pull request had become stalled, so I squashed and rebased it myself.

**Review by pllim — APPROVED** [review]
Thanks!

**Pull request merged**
