### PR TITLE
TST: Relax project coverage threshold

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to relax project coverage threshold in CI so it does not almost always fails. The number in this PR was originally proposed during dev telecon on 2022-05-10 .

https://docs.codecov.com/docs/common-recipe-list#ease-target-coverage

Example screenshot taken from #13239 of the problem this PR is trying to solve:

Screenshot 2022-05-10 125339

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by dhomeier — APPROVED** [review]
Seems not even necessary now that coverage change is at 0.00 % 😆
(note that previously it was failing on "<0.01%", so maybe just needed _some_ threshold at all... currently some 66600 tracked lines are reported, so 0.02 % would allow up to 13 misses).
IOW I have a feeling this would even work with setting it to 0.01% as typically there seem to be up to 2-3 lines with randomly un/covered statements.

**Comment by pllim** [comment]
@dhomeier , do you want me to try to reduce it to 0.01% ?

**Comment by hamogu** [comment]
Sure, I think 0.01 % would also work. Any small number will do, I hope...

**Comment by pllim** [comment]
OK changed to 0.01%

**Comment by dhomeier** [comment]
Tried to test this on a real-world example in #13239 with 2 changed and 2 added lines without any tests; this is still passing `project` at < 0.01 %, but duly failing in `patch` (so the default values there seem to be strict enough).
So, looks good now!

**Comment by pllim** [comment]
Do you want to approve and merge? 😸

**Comment by dhomeier** [comment]
Thanks for getting that off our backs!

**Comment by pllim** [comment]
@meeseeksdev backport to v5.0.x

**Comment by pllim** [comment]
@meeseeksdev backport to v5.1.x

**Pull request merged**
