### PR TITLE
Use parametrize instead of yield for tests in units and io.votable

### PR DESCRIPTION
**Pull request by mhvk**
This follows on #5678 in ensuring that we do not use `yield` for running series of tests, but rather use `pytest.mark.parametrize`, as the former is deprecated in pytest >=3. With #5678 taking care of `wcs`, this should remove all usage in astropy. 

Note: I labelled it as a bug and set the milestone to 1.3.1 since recent versions of astropy should work with pytest >=3.

@kelle - would you be able to have a quick look?

### CODE REVIEW

**Comment by kelle** [comment]
I've never done proper code review before, but this looks good to me!

**Comment by mhvk** [comment]
OK, thanks! @pllim - great if you can have a second look; it should be ready.

**Comment by mhvk** [comment]
I'm convinced enough by this to go ahead and merge, so that at least our test suite is pytest 3.x compatible.

**Comment by mhvk** [comment]
@pllim - no apologies needed - it really is just my impatience (and trying to minimize the number of things "something should be done with").

**Pull request merged**
