### PR TITLE
Fix biweight_midvariance

### PR DESCRIPTION
**Pull request by larrybradley**
This fixes a slight regression introduced in #5127.

cc: @crawfordsm

### CODE REVIEW

**Comment by pllim** [comment]
I am not sure whether #5127 made it to 1.2 or not, so I just put "affects dev" tag here. Feel free to change it if I am wrong.

**Comment by bsipocz** [comment]
@pllim - ``affects dev`` is right, it didn't make it to the release.

**Comment by larrybradley** [comment]
Could someone please merge this PR?  This bug is causing `photutils` tests to fail.

**Comment by pllim** [comment]
Done.

**Pull request merged**
