### PR TITLE
Access subdtypes of structured Distributions

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

### Description

Structured distributions do not allow access to the underlying structure, while remaining a Distribution.
This PR fixes this problem.

Already allowed:
```python
>>> from astropy.uncertainty import Distribution

>>> x = np.array([(0, 0, 0.6), (0.1, -0.01, 0.59)], dtype=[("nu1", float), ("nu2", float), ("nu3", np.float128)])
>>> f = Distribution(x)
>>> f
NdarrayDistribution([(0. ,  0.  , 0.6 ), (0.1, -0.01, 0.59)],
      dtype=[('nu1', '<f8'), ('nu2', '<f8'), ('nu3', '<f16')]) with n_samples=2
```

Added:
```python
>>> f["nu1"]
NdarrayDistribution([0. , 0.1]) with n_samples=2
```

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by eteq — CHANGES_REQUESTED** [review]
I like this in concept, @nstarman ! I think it still needs two things, though:
1. A test - basically copy-and-paste what's in your description should do the trick.
2. A mention in the narrative docs (and maybe the API, although honestly I'm not sure where).  I'm pretty sure no one will know about it if there isn't an example shown, since it doesn't appear in any obvious docstring.

I also think it's more a new feature than a bug, as you *could* do this manually (i.e. ``Distribution(self["samples"]['thesubdtypeyouwant'])``, it's just awkward. (will re-label accordingly).

**Comment by nstarman** [comment]
Views are weird. I've put into the test that the view can't influence the original array, but the reverse isn't true. I'd like it to be bi-directional!

**Comment by mhvk** [comment]
See https://github.com/astropy/astropy/issues/12909#issuecomment-1060610493 about a general question of whether the samples should be structured or each element of the structure should have samples.

**Comment by nstarman** [comment]
I now strongly think the latter (each element of the structure should have samples), so I'm closing this PR.

**Comment by nstarman** [comment]
I now strongly think the latter (each element of the structure should have samples), so I'm closing this PR.

**Comment by pllim** [comment]
Never knew you close close a closed issue. 👀 

Screenshot 2022-03-14 114038

**Pull request closed without merging**
