### PR TITLE
change RST links to get ride of redundant “astropy” in links

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

I changed the links and then modified line breaks according to the line length.

tags: no-changelog-entry-needed ?
request review: @embray 

Fixes https://github.com/astropy/astropy/pull/11690#discussion_r637108775

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Looks good to me, so approving, though it would be best for @embray to have a quick look too.

Also, the readthedocs build has been problematic yet for something like this we want to be sure it passed. Did you try locally?

**Comment by ayshih** [comment]
Oof, I get why this is being done, but can there be a deprecation period where the old anchors still exist for a while?  SunPy docs has links to a couple of places in Astropy docs, and I think it'd make our lives a little easier when dealing with this change.

Actually, looking through our docs, we specifically link to:

- `astropy-coordinates`
- `astropy-coordinates-representations`
- `astropy-coordinates-transforming`

However, while each of the above are also used as link targets within Astropy docs (see below), none of these have been "fixed" by this PR.  Is that an oversight?  Or do I not understand why only certain links/anchors were changed?

Examples:
https://github.com/astropy/astropy/blame/91bb666ca4d3a89423075a91a528ff85477bbe2e/docs/io/asdf-schemas.rst#L18
https://github.com/astropy/astropy/blame/91bb666ca4d3a89423075a91a528ff85477bbe2e/docs/coordinates/frames.rst#L158
https://github.com/astropy/astropy/blame/91bb666ca4d3a89423075a91a528ff85477bbe2e/docs/coordinates/skycoord.rst#L615

**Comment by ayshih** [comment]
Oh, I think I get it now.  However, if you're going to do this, you really should change *all* potential link targets to maintain consistency, and not change solely the ones that are currently being used by docstrings/examples.

**Comment by mhvk** [comment]
Oops, that is something we should have thought about, that our docs may be linked to. Maybe this is not quite worth the hassle?

**Comment by nstarman** [comment]
That could well be the case. I think I'll close this PR.

**Comment by pllim** [comment]
Thanks for trying! At least now we have a record that we tried for future reference. 😸

**Comment by embray** [comment]
That's what I meant by "if at all" because I worried that changing this could break existing intersphinx links in other docs.

**Pull request closed without merging**
