### PR TITLE
Add working to method to distribution class

### PR DESCRIPTION
**Pull request by eteq**
It turns out Quantity `Distribution`s' `to` method wasn't working quite right (thanks @astrofrog for pointing this out!), because it was implicitly using the `Quantity` `to` instead of one that was distribution-aware.  This PR adds an explicit implementation of `to` to `Distribution` (for the Quantity and sub-classes case, at least).  

One could debatably see this as a bug, but it's not really clear that this was originally intended, so I'm categorizing it as a new feature (and therefore can go into 4.0 without any backports)

cc @astrofrog

### CODE REVIEW

**Comment by bsipocz** [comment]
> One could debatably see this as a bug, but it's not really clear that this was originally intended, so I'm categorizing it as a new feature (and therefore can go into 4.0 without any backports)

even if it's a bug, there won't be any more backporting (except for the odd critical issues).

**Comment by bsipocz** [comment]
@eteq - does this override https://github.com/astropy/astropy/pull/8865?

**Comment by eteq** [comment]
Yes it does replace #8865, @bsipocz - should have closed that! (will do now).

**Comment by eteq** [comment]
One thing to note re: the changes examining #8865 reminded me of: I opted *not* to allow `to_value` because it's ambiguous whether the user is asking for the distribution (i.e., the MC samples) or some summary statistic.

The challenge is that this nominally breaks the goal of a "drop-in" replacement.  But to really be a drop-in, I think `to_value` would need to be a summary statistic and we have to then decide the "right" summary statistic. So I think we avoid that for now to make this PR tight (and potentially get it in for 4.0...)

**Comment by mhvk** [comment]
@eteq - for my own `Measurement` class I've been trying a new approach, which perhaps might work better here too, of ensuring that the `Measurement` class always sits just above `ndarray`, not above whatever ndarray subclass. This means that it no longer has to worry about supporting `Quantity` methods, but a consequence is that `.value` and `to_value` are always regular array distributions.
(This is something we perhaps can discuss in person now that you are in Toronto.)

**Comment by eteq** [comment]
@mhvk - hmm, interesting. I guess I see that as a bug not a feature, because I see it as desirable that `to` yield a new distribution (that was @astrofrog's original request), but `to_value` should *not* (nor should `value`) because we want the user to have to say what they mean. (But yes can discuss more in person.)

**Comment by eteq** [comment]
In some out-of-band discussion, @mhvk and I concluded actually `to_value` should yield a *ndarraydistribution*, so I added that change here.  @mhvk is also going to experiment with using this branch's *tests* for an alternate implementation (but we'll aim to merge this if that doesn't work).

Note, @mhvk, the tests are scattered over 3 commits I'm realizing - be72173, 452f8f3, and 2055d21 .  You might just want to cherry-pick those in order (the rebase turns out to be non-trivial...)

**Comment by bsipocz** [comment]
I go ahead now and merge approved PRs. Here there seems to be complete agreement.

Thanks @eteq!

**Comment by mhvk** [comment]
Sorry, this is NOT OK!!  @eteq and I are still discussing what the better approach is, and I feel quite strongly it is the one in #9442!!

**Comment by bsipocz** [comment]
Oh, my bad, I'm sorry. I interpreted https://github.com/astropy/astropy/pull/9429#issuecomment-545142517 that you were happy with this. :(

**Comment by mhvk** [comment]
No worries, I guess I can rebase and ensure #9442 just overrides - just want to be sure this isn't a defacto decision between the two...

**Comment by mhvk** [comment]
OK, I think I see you reverted - let @eteq and I work this out in #9442

**Comment by bsipocz** [comment]
It wasn't me who reverted, and that actually brings in more confusion I think.

**Comment by bsipocz** [comment]
Oh, I think @saimn clicked on the revert here on the PR. That opened a branch on astropy, but it doesn't do anything else, I think. 

So I would suggest to close and delete that branch, and you rebase #9442 on the current master that still contains this PR, but not the revert (as that one hasn't been PRed yet).

**Comment by saimn** [comment]
Oups, I was just curious to see what the button does ...

**Comment by bsipocz** [comment]
github buttons don't do much good :trollface:

**Comment by mhvk** [comment]
OK, that makes sense, I'll rebase on top and just remove the code (but not the tests) that @eteq added.

**Pull request merged**
