### PR TITLE
Backport PR #12636 on branch v5.0.x (Add cosmology units to ECSV reading)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #12636: Add cosmology units to ECSV reading

### CODE REVIEW

**Comment by nstarman** [comment]
@pllim. Test failures look unrelated. I think this is #12633 or #12639. Good to merge or wait for those and then re-open this backport?

**Comment by pllim** [comment]
Let's wait... Just to be sure. Thanks for your patience!

**Comment by nstarman** [comment]
perhaps I should open a feature request... It would be great if meeseeksmachine backports were added to the same project as the original PR (if the original PR had a project). Do you think that would be possible or challenging to implement?

**Comment by pllim** [comment]
> Do you think that would be possible or challenging to implement?

Doesn't hurt to ask, though don't get too hopeful. https://github.com/MeeseeksBox/MeeseeksDev

Might be easier if you can figure out a way to program that into your project board. 🤷

**Comment by pllim** [comment]
Going to redo the backport. Thanks for your patience!

**Pull request closed without merging**
