### PR TITLE
Add __hash__ method to Time/TimeDelta

### LINKED ISSUE #7532: Make scalar Time hashable
PR #7531 needs a hashable scalar time in order to index a table with a Time column using the  `sortedcontainers` package.  This is intended as a replacement for `bintrees` which is no longer maintained.

A zero-order implementation to get started is below.  This doesn't address a difference in `location` (but maybe not needed anyway?).  The nominal requirement for hash is *"The only required property is that objects which compare equal have the same hash value"*.  Since time values with different scales can be equal, it isn't immediately obvious to me how to implement this.  In theory maybe transform to TAI and hash `(jd1, jd2)`.  This of course could be expensive and performance killing for table indexing.

Thoughts @mhvk?
```
diff --git a/astropy/time/core.py b/astropy/time/core.py
index c99f913..ee7571d 100644
--- a/astropy/time/core.py
+++ b/astropy/time/core.py
@@ -789,6 +789,11 @@ class Time(ShapedLikeNDArray):
         self._time.jd1[item] = value._time.jd1
         self._time.jd2[item] = value._time.jd2
 
+    def __hash__(self):
+        if self.ndim != 0:
+            raise TypeError("unhashable type: '{}'".format(self.__class__.__name__))
+        return hash((self.jd1, self.jd2, self.scale))
+
     def light_travel_time(self, skycoord, kind='barycentric', location=None, ephemeris=None):
         """Light travel time correction to the barycentre or heliocentre.

### PR DESCRIPTION
**Pull request by taldcroft**
Closes #7532 

To do:
- [x] Narrative docs update
- [x] Change log

### CODE REVIEW

**Comment by mhvk** [comment]
I think some hickup at anaconda caused the tests to ail. Closing and reopening to re-start all.

**Comment by mhvk** [comment]
Hmm, looks like circle-ci doesn't auto-restart on re-opening.

**Comment by bsipocz** [comment]
I've restarted the image test (@mhvk - if you're logged in to circleCI, you should be able to trigger the build with the dropdown on  the top right (e.g. "rerun job with ssh").

The html is know to be broken (#8915) and I'll fix it up later.

**Comment by bsipocz** [comment]
Thank you @taldcroft! and @mhvk for the review.

**Pull request merged**
