### PR TITLE
Fix ColDefs.change_ methods

### PR DESCRIPTION
**Pull request by embray**
The old PyFITS `ColDefs` class for representing a set of table columns has three methods, [`change_attrib`](http://docs.astropy.org/en/stable/io/fits/api/tables.html#astropy.io.fits.ColDefs.change_attrib), [`change_name`](http://docs.astropy.org/en/stable/io/fits/api/tables.html#astropy.io.fits.ColDefs.change_name), and [`change_unit`](http://docs.astropy.org/en/stable/io/fits/api/tables.html#astropy.io.fits.ColDefs.change_unit) that I fairly frequently get questions about--these should be mentioned in the FAQ.

They never really worked properly because although they can change the column objects in-place, they don't actually change the data in the table which is confusing.  They're from a time before PyFITS really had a thought out data model (and it still doesn't really, especially not for tables).  Anyways, using these methods only results in confusion, as do some of the other `ColDefs` methods.  They should all be marked deprecated, and documentation provided for how to perform various tasks for updating FITS tables.  This can serve as a first step to replacing the FITS table interface entirely.

**UPDATE:** A mentioned in some of the comments below, instead of deprecating these I finally went ahead and tried to fix them instead.  My feeling about this used to be that it was too much trouble to fix within the current interface, and that instead it should wait until the table interface is completely redone to use Astropy Table, and then the whole thing could be scrapped.  But on further thought it wasn't all that hard to fix, and the approach I've taken I think will prove useful in transitioning to Astropy Tables as well.

### CODE REVIEW

**Comment by embray** [comment]
I've attached a somewhat experimental fix for this issue.  I would like to hack at it a little more before merging, but I think the basic approach is sound.  This will also fix #2618 and #1539.

**Comment by embray** [comment]
It should be noted that this PR does not currently attempt to fix issues with the `ColDefs.add_col` and `ColDefs.del_col` methods.  It adds support for them within the new interface, but they still have more or less the same broken behavior as before.  I will try to address that as a piggy-back to this PR.

**Comment by embray** [comment]
Seems Numpy 1.6 has a bug with *pickling* dtypes that involve a zero-width field.  Investigating a workaround...

**Comment by embray** [comment]
Weird about the appveyor failures.  I can't think of anything specific to these changes that would cause that, and I can't seem to reproduce locally, though I haven't tried it with anaconda yet.

**Comment by embray** [comment]
Now I'm tracking another issue--maybe related?--that automodapi seems to get run twice, though the first time it's run on files with the filename extension in the docname (ex. "wcs/index.rst"), and then later a second time with just "wcs/index" without the extension as the docname...

**Comment by embray** [comment]
Aha! [This change](https://github.com/sphinx-doc/sphinx/commit/21b838454f4bb5b6a246b85cb2f521deb7552505) seems to be at the heart of the toctree generation for API items.  Specifically this: https://github.com/sphinx-doc/sphinx/commit/21b838454f4bb5b6a246b85cb2f521deb7552505#diff-afb0740c26016f8922e4fe3724b5e584R273

The `check_module` method that is called there checks whether the function or object really belongs directly to the module it's defined in.  So if we're documenting `astropy.config.get_config` as part of the `astropy.config` module, it breaks here because the actual fully-qualified name of that function is `astropy.config.configuration.get_config`.  This is an annoying regression though from our perspective.  I'll see if there's some way to bypass that.

**Comment by embray** [comment]
I added a comment about this in sphinx-doc/sphinx#1061.

**Comment by embray** [comment]
D'oh! Apparently I've been commenting in the wrong issue all this time.

**Comment by embray** [comment]
@astrofrog I don't know if I necessarily like being the assignee to my own pull requests though, at least not in all cases.  It means that nobody but me every reviews my code, and I miss things.  It also means that hardly anyone but me has taken the time to look at and understand the parts of the code I work on, and so I am becoming a single point of failure on them.  Not good.

**Comment by embray** [comment]
Nevermind, I can reproduce the Windows failure.  Not sure what I did before to think otherwise.

**Comment by astrofrog** [comment]
@embray - sorry, you are right - in these cases the secondary maintainer should likely be the assigned reviewer. Who should be the secondary reviewer for ``io.fits``? (by default - of course, others should look too)

**Comment by embray** [comment]
I have no idea...

**Comment by embray** [comment]
With bbef777 I think I've hopefully fixed the problems with this passing on Windows.

**Pull request merged**
