### PR TITLE
Fix December tick label in visualization/time.py

### LINKED ISSUE #11614: `time_support` fails for intervals of a few months if these include December
### Description

Plotting `Time` objects using `time_support` gives an error for intervals of a few months, when the ticks includes December:

`ValueError: month must be in 1..12`

### Steps to Reproduce

```python
import matplotlib.pyplot as plt
from astropy.time import Time
from astropy.visualization import time_support

plt.figure()
time_support(format='iso')
plt.plot(Time(['2015-11-22', '2016-02-22']))
plt.draw()
```

### System Details

Python 3.9.1 (default, Jan 28 2021, 20:35:40) 
[Clang 10.0.1 (clang-1001.0.46.4)]
Numpy 1.19.5
astropy 4.2
Scipy 1.6.0
Matplotlib 3.4.1

### PR DESCRIPTION
**Pull request by rikvl**
### Description

This pull request fixes a tick label problem in `visualization.time_support()` when plotting `Time` objects spanning a few months, when one of the tick labels fall in December.

Fixes #11614

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! Please add a change log; see https://github.com/astropy/astropy/blob/main/docs/changes/README.rst

**Review by larrybradley — COMMENTED** [review]
Many thanks, @rikvl.  Please add a `bugfix` changelog entry following the instructions posted by @pllim.

**Review by larrybradley — APPROVED** [review]

**Review by astrofrog — APPROVED** [review]
Looks good to me

**Comment by pllim** [comment]
Thanks, all!

**Pull request merged**
