### PR TITLE
added a fixed flag for parameter representation

### PR DESCRIPTION
**Pull request by wkerzendorf**
This makes it easies to see what parameters are fixed on the model. `<Model a=5.0 [f] b=3.0>`

@embray let me know if you think this is a useful addition.

### CODE REVIEW

**Comment by mhvk** [comment]
+1 to the idea, but would propose to just write `[fixed]` or maybe instead replace the equal sign with ` fixed at ` or ` := ` or ` @ ` or so.

**Comment by mdboom** [comment]
I like `:=` personally.

**Comment by wkerzendorf** [comment]
@mdboom @mhvk I'm happy to write `fixed`, but I find `:=` not clear what that means. As long as fixed is in the name, I don't care: What's your preference?

**Comment by mdboom** [comment]
I'm a little worried about `fixed` being too verbose, particularly in models with a large number of parameters.  At least in Boolean algebra, `:=` is "defined as", so I think it's a nice concise way to say it's fixed, but maybe that's just me.

**Comment by followthesheep** [comment]
Hi, I'm working on this with @wkerzendorf at the moment. I like the idea of being explicit to say [fixed]. As a new user to astropy modeling, it will be clearer for folks like me to understand what is going on. I'm not sure I would notice the notation := immediately.

**Comment by mdboom** [comment]
Ok.  At a minimum, we should use something other than square brackets, though.  That has a pretty explicit meaning in Python which isn't really what's intended here.  Parentheses would be better, IMHO.

**Comment by embray** [comment]
I'm not sure I'm necessarily happy with singling out the fixed constraint--there are other types of constraints too and even if you don't use them someone else does, so there's no reason to neglect them.

**Comment by embray** [comment]
Perhaps instead, for the `__repr__` you could just print any and all constraint dicts in the output.  For example, `<Model(a=1.0, b=2.0, fixed={'a': 1.0}>`  It's not as slick, but it's more in line with the philophy I've tried to follow with the `__repr__`.  With `__str__` on the other hand you can do a lot more, and that might be a better place for more verbose syntax like `a = 1.0 (fixed)`.

**Comment by mhvk** [comment]
:+1: on having the `repr` be as close as possible to what one could use to *reproduce* the model (that is what is stands for after all!). And also +1 to having `str` be different, and list `(fixed)` or `(tied)` as appropriate.

**Comment by wkerzendorf** [comment]
@embray okay, I then would say `Model(a=1.0, b=2.0; fixed=(a,))`. Is that good?

**Comment by astrofrog** [comment]
I'm not a fan of ``<Model(a=1.0, b=2.0, fixed={'a': 1.0}>`` since it's going to be harder to read for more complex models. Another option is something like ``<Model(b=2.0 d=5.4 | Fixed: a=1.0 c=4.5)>``, i.e. separate the variable from the fixed parameters.

**Comment by embray** [comment]
@astrofrog I don't think that will do much to improve readability significantly enough for "more complex" models given that it also introduces unfamiliar syntax. I think having something more structured in the `__str__` is fine. That's what it's for. 

I'm not an absolutist on "repr must be able to reconstruct the object" by any means. It's often not practical. But in the case of Model it's very easy to do that way, so I think there has to be a demonstrable benefit to not doing so. 

@wkerzendorf That looks fine. It's not exactly right *currently* but it would be if something like #3082 were done concurrently

**Comment by wkerzendorf** [comment]
@embray I guess you gave the wrong issue number this is about some fits macosx thing? 
So you like `Model(a=1.0, b=2.0; fixed=(a,))` or `Model(a=1.0 (fixed), b=2.0)`. 

@astrofrog the problem with this is - you loose parameter order, which is very essential for us. 

Maybe just to clarify and make sure we are all on the same page:
 - `fixed` is a fitter directive that instructs the fitter not to touch this value
 - I feel it is the strongest fitter directive and should be marked in the model representation (which does not have to contain all the information to reconstruct the model IMHO).

**Comment by embray** [comment]
@wkerzendorf Sorry, I was writing that on my phone.  Should have been #3028

**Comment by embray** [comment]
I would be probably happiest with `<Model(a=1.0, b=2.0, c=3.0, fixed=('a', 'c'))>` (for 'a' and 'c' as fixed parameters).

But I'm not rigid. I've wanted more feedback on the model `__str__` and `__repr__` for a long time and so am happy for suggestions for improving it.  And I agree that being able to easily see that some parameters are fixed is important.  But I still hold that if we're going to represent some constraints we should represent all constraints.  In fairness, some of them are trickier.  For example the `tied` constraint can be a function.  However, in most cases when it is a function it's a very simple `lambda` expression, and I'm thinking about ways that we could represent that nicely...

**Comment by wkerzendorf** [comment]
@embray maybe to show you and the others what we (@followthesheep and myself) are working on: http://starkit.readthedocs.org/en/latest/getting_started.html 

For us the two things that parameters need to have is `fixed` and `prior` (which is something we would love to have ;-) ) so the other things I'm not as passionate about  this. I'll change it that way and we can implement this. IF there are calls for adding tied and constraints I would add them then.

**Comment by embray** [comment]
Hmm, I'm really not okay with just implementing one and not the others.  But if you want to do just fixed I'm happy to take that and add my own PR for the others on top of yours.

**Comment by wkerzendorf** [comment]
But then you need to do `tied`, `bounds`, `constraints`, custom parameter parameters (meta :wink:).

**Comment by mhvk** [comment]
@wkerzendorf - I think `tied` is particularly important, as it, effectively, means this parameter is not free and will thus not be fitted at all.

**Comment by wkerzendorf** [comment]
@mhvk well how do you represent it - essentially it can be an arbitrary function?

**Comment by mhvk** [comment]
In `__str__`, it is easy, in `__repr__`, a temporary solution might be just to make a list as suggested for `fixed` above; it still tries to keep true to the idea that `eval(repr(model)) == model`, but while this will continue to fail if ties (or bounds, etc.) are present, it still gives the most important information of all, which is what are the free parameters in the fit.

Aside: would indeed be wonderful to have `bounds` just be a special case of a `prior`!

**Comment by wkerzendorf** [comment]
@mhvk agreed; I believe this is a useful self consistent addition that does not preclude to add any of the other things in the future. 

@mhvk exactly right !! that's what we are working on in #3784

**Comment by mhvk** [comment]
@wkerzendorf - sorry, not quite agreed (I think): I do agree we don't have to get this perfect, but at the same time we shouldn't give misleading information about which parameters are actually free (i.e., `ndof`). I.e., I agree with @embray that if we list `fixed`, we have to list `tied` as well.

My perhaps unclear suggestion for an easy way forward is that you duplicate what you have for `fixed` to `ties`, so that both give lists of parameters that are fixed/tied (if there are any). For ties, this will not be enough to reproduce the model, but that can be left to a future PR.

**Comment by wkerzendorf** [comment]
@mhvk what do you do with `bounds`, `min`, `max` should they also be represented.

**Comment by mhvk** [comment]
I think `tied` is essentially the same as `fixed`, in the simple sense that those parameters do not count in `ndof` any more, so if one is listed, the other should too (`fixed` in my mind is just a convenient shortcut for a tie of the form `lambda x: return value`). For parameters were you set some priors, the situation is different, so I feel less bad about not mentioning those.

**Comment by wkerzendorf** [comment]
Does everyone involved feel - that if this is implemented we can merge this PR?

**Comment by embray** [comment]
@wkerzendorf 
> But then you need to do `tied`, `bounds`, `constraints`

Note, "tied", "bound", and "fixed" are already all *examples of* constraints.  There is no separate constraints argument.  And yeah, meta would be good too.

**Comment by embray** [comment]
Also regarding tied my thinking was this: In many cases it's just a simple lambda expression, so I was thinking it would be easy enough to convert the lambda to a string, and that would be quite informative (we can probably drop `lambda args:` part, and just have the expression itself, like "amplitude + 1" or whatever).  *If* the tied constraint is a full *function*, which may be multiple lines long, we just list the fully-qualified name of the function.

> Aside: would indeed be wonderful to have bounds just be a special case of a prior!

Yup! That's what we suggested in the Leiden workshop as well.  Basically it should be an *error* to specify both prior and bounds simultaneously, but if prior is unspecified bounds acts as a simple uniform prior.

**Comment by embray** [comment]
Oh, and another thing we could do to improve `tied` representation:  Currently the function assigned to a `tied` constraint just takes a single argument: the entire model object.  However, in many cases at least a parameter is tied to a single other parameter.  In that case we could allow the `tied` function to specify which parameters it is tied to by using those parameter names as the argument names to the function, and introspecting to determine which parameter values to pass in, and which parameters the tied parameter is tied to.

This would be very similar to what I'm doing with the "unit specifiers" `input_units` and `output_units` over in #3852.  This way, even if the exact expression isn't represented, it at least would show which parameters are tied together.

**Pull request closed without merging**
