### PR TITLE
Remove unnecessary sort when defining __all__

### PR DESCRIPTION
**Pull request by larrybradley**
It is unnecessary to sort the entries in `__all__`.  I think this is a holdover from when the entries were not automatically sorted in the docs.

### CODE REVIEW

**Comment by pllim** [comment]
:+1:

**Comment by astrofrog** [comment]
:+1:

**Comment by saimn** [comment]
Parenthesis can be removed as well ;-)

**Comment by larrybradley** [comment]
Yes, of course.  Thanks for catching that, @saimn.  Done!

**Comment by astrofrog** [comment]
Thanks @larrybradley!

**Pull request merged**
