### PR TITLE
Fix behavior of scaled columns in binary table

### LINKED ISSUE #3921: Adding new rows to fits table with unsigned ints results in data change following write and readback
Following the logic of "Appending Tables" in the manual, I tried to add new rows to an existing fits file. Starting with [S.fits](https://drive.google.com/file/d/0B1o2SP_OlyGYV2ZnVS1vUHk2Nm8/view?usp=sharing):

```
In [1]: from astropy.io import fits as pf

In [2]: H=pf.open("S.fits",uint=True)

In [3]: H[1].data
Out[3]: 
FITS_rec([ (-1, '1970-01-01T00:00:00.000000', nan, 0, 0, 0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)], 
      dtype=[('OBT_TIME', '>i8'), ('UTC_TIME', 'S26'), ('MJD_TIME', '>f8'), ('HK_STAT_SID', '>i2'), ('HK_STAT_MODE', '>i2'), ('FixVal13', '>i2'), ('HK_STAT_FPM_POWER', 'u1'), ('HK_STAT_DAT_BUFFER_OVERFLOW', 'u1'), ('HK_STAT_SCU_MAIN_RED', 'u1'), ('HK_STAT_LAST_SPWLINK_ERROR', '>i2'), ('HK_STAT_LAST_ERROR_ID', '>i2'), ('HK_STAT_LAST_ERROR_FREQUENCY', '>i2'), ('HK_STAT_NUM_CMD_RECEIVED', '>i2'), ('HK_STAT_NUM_CMD_EXECUTED', '>i2'), ('HK_STAT_NUM_DATA_SENT', '>i2'), ('HK_STAT_SCU_PROC_DUTY_CYCLE', '>i2'), ('HK_STAT_SCU_NUM_AHB_ERROR', '>i2'), ('HK_STAT_SCU_NUM_AHB_CORRECTABLE_ERROR', '>i2'), ('HK_TEMP_SEM_SCU', '>i4'), ('HK_TEMP_SEM_PCU', '>i4')])

In [4]: Z=pf.BinTableHDU.from_columns(H[1].columns, nrows=10)

In [5]: for c in Z.data.names: Z.data[c][1:]=Z.data[c][0]

In [6]: Z.data
Out[6]: 
FITS_rec([ (-1, '1970-01-01T00:00:00.000000', nan, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0)], 
      dtype=[('OBT_TIME', '<i8'), ('UTC_TIME', 'S26'), ('MJD_TIME', '<f8'), ('HK_STAT_SID', '<i2'), ('HK_STAT_MODE', '<i2'), ('FixVal13', '<i2'), ('HK_STAT_FPM_POWER', 'u1'), ('HK_STAT_DAT_BUFFER_OVERFLOW', 'u1'), ('HK_STAT_SCU_MAIN_RED', 'u1'), ('HK_STAT_LAST_SPWLINK_ERROR', '<i2'), ('HK_STAT_LAST_ERROR_ID', '<i2'), ('HK_STAT_LAST_ERROR_FREQUENCY', '<i2'), ('HK_STAT_NUM_CMD_RECEIVED', '<i2'), ('HK_STAT_NUM_CMD_EXECUTED', '<i2'), ('HK_STAT_NUM_DATA_SENT', '<i2'), ('HK_STAT_SCU_PROC_DUTY_CYCLE', '<i2'), ('HK_STAT_SCU_NUM_AHB_ERROR', '<i2'), ('HK_STAT_SCU_NUM_AHB_CORRECTABLE_ERROR', '<i2'), ('HK_TEMP_SEM_SCU', '<i4'), ('HK_TEMP_SEM_PCU', '<i4')])

In [7]: H[1]=Z

In [8]: H.writeto("S2.fits")

In [9]: H.close()

In [10]: K=pf.open("S2.fits",uint=True)

In [11]: K[1].data
Out[11]: 
FITS_rec([ (-1, '1970-01-01T00:00:00.000000', nan, 0, 0, 0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0)], 
      dtype=[('OBT_TIME', '>i8'), ('UTC_TIME', 'S26'), ('MJD_TIME', '>f8'), ('HK_STAT_SID', '>i2'), ('HK_STAT_MODE', '>i2'), ('FixVal13', '>i2'), ('HK_STAT_FPM_POWER', 'u1'), ('HK_STAT_DAT_BUFFER_OVERFLOW', 'u1'), ('HK_STAT_SCU_MAIN_RED', 'u1'), ('HK_STAT_LAST_SPWLINK_ERROR', '>i2'), ('HK_STAT_LAST_ERROR_ID', '>i2'), ('HK_STAT_LAST_ERROR_FREQUENCY', '>i2'), ('HK_STAT_NUM_CMD_RECEIVED', '>i2'), ('HK_STAT_NUM_CMD_EXECUTED', '>i2'), ('HK_STAT_NUM_DATA_SENT', '>i2'), ('HK_STAT_SCU_PROC_DUTY_CYCLE', '>i2'), ('HK_STAT_SCU_NUM_AHB_ERROR', '>i2'), ('HK_STAT_SCU_NUM_AHB_CORRECTABLE_ERROR', '>i2'), ('HK_TEMP_SEM_SCU', '>i4'), ('HK_TEMP_SEM_PCU', '>i4')])
```

The produced file is available here: [S2.fits](https://drive.google.com/file/d/0B1o2SP_OlyGYbmtEYlRrbHFaeTQ/view?usp=sharing).

Or similarly:

```
In [17]: Z.writeto("S3.fits")

In [18]: K=pf.open("S3.fits",uint=True)

In [19]: K[1].data
Out[19]: 
FITS_rec([ (-1, '1970-01-01T00:00:00.000000', nan, 0, 0, 0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0),
       (-1, '1970-01-01T00:00:00.000000', nan, 0, 32768, 32768, -128.0, -128.0, -128.0, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 32768, 0, 0)], 
      dtype=[('OBT_TIME', '>i8'), ('UTC_TIME', 'S26'), ('MJD_TIME', '>f8'), ('HK_STAT_SID', '>i2'), ('HK_STAT_MODE', '>i2'), ('FixVal13', '>i2'), ('HK_STAT_FPM_POWER', 'u1'), ('HK_STAT_DAT_BUFFER_OVERFLOW', 'u1'), ('HK_STAT_SCU_MAIN_RED', 'u1'), ('HK_STAT_LAST_SPWLINK_ERROR', '>i2'), ('HK_STAT_LAST_ERROR_ID', '>i2'), ('HK_STAT_LAST_ERROR_FREQUENCY', '>i2'), ('HK_STAT_NUM_CMD_RECEIVED', '>i2'), ('HK_STAT_NUM_CMD_EXECUTED', '>i2'), ('HK_STAT_NUM_DATA_SENT', '>i2'), ('HK_STAT_SCU_PROC_DUTY_CYCLE', '>i2'), ('HK_STAT_SCU_NUM_AHB_ERROR', '>i2'), ('HK_STAT_SCU_NUM_AHB_CORRECTABLE_ERROR', '>i2'), ('HK_TEMP_SEM_SCU', '>i4'), ('HK_TEMP_SEM_PCU', '>i4')])
```

```
In [14]: astropy.__version__
Out[14]: u'1.1.dev12815'
```

### LINKED ISSUE #6887: Changes to integer column values with bzero set in opened fits tables are not written back to file
```python
# Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
import numpy as np
import astropy
from astropy.io import fits as pf
print (astropy.__version__ , np.__version__)
```

    2.0.2 1.13.3

```python
c1=pf.Column(name='c1',array=np.array([1],dtype='>i2'),format='1I',bscale = 1,bzero = 32768)
S=pf.HDUList([pf.PrimaryHDU(),pf.BinTableHDU.from_columns([c1])])
print("S=",S[1].data)
# Change value in memory
S[1].data['c1'][0]=2
print("S=",S[1].data)
print(S[1].columns)
S.writeto("a.fits")
S.close()
```
    S= [(1,)]
    S= [(2,)]
    ColDefs(
        name = 'c1'; format = '1I'; bscale = 1; bzero = 32768
    )

```python
X=pf.open("a.fits")
print("a.fits=",X[1].data)
print(X[1].columns)

# Change value in memory
X[1].data['c1'][0]=10
print("X=",X[1].data)

# Write back to file
X.writeto("b.fits")
X.close()

#Now check the file
print("b.fits=",pf.open("b.fits")[1].data)
```

    a.fits= [(     2,)]
    ColDefs(
        name = 'c1'; format = '1I'; bscale = 1; bzero = 32768
    )
    X= [(    10,)]
    b.fits= [(     2,)]

So if we read in a fits file with bzero set in one column that column can be changed in memory but this is not written back to file by HDUList.writeto(). In case of multiple columns, string and float column changes are written out properly. Without the bzero argument, changes are written out properly.

### PR DESCRIPTION
**Pull request by saimn**
Fix #6887.

Once a column with a tscale or tzero keyword is scaled, it was not marked as such. So if the column was modified and then saved, the old (unscaled) values when saved instead.

It seems that all what was missing was to put the `_physical_values` flag to True. 

While looking at old issues I found #4709 which is very similar, so I included these 2 commits. Sadly it is not enough to fix  #3921 (I still do not understand everything there :roll_eyes: )

Note: There is no 2.0.4 section in the changelog yet, so I used 2.0.3 for now.

### CODE REVIEW

**Comment by MSeifert04** [comment]
needs a rebase because of the conflict.

Also: Why is there a significant decrease in coverage? 😕

**Comment by bsipocz** [comment]
for changelog issue, no need to rebase now only when it's ready to be merged (more changes are expected with 2.0.3)

**Comment by saimn** [comment]
> Also: Why is there a significant decrease in coverage? :confused:

Hmm I think the code removal explains this (as it was probably well tested) ? roughly 40 lines / 100000 gives 0.04%

**Comment by bsipocz** [comment]
Another possibility is that the top of master changed with significant changes between opening this and the actual run of the coverage test.

**Comment by saimn** [comment]
Yes maybe, we can see when I rebase the branch.
Should I wait for 2.0.4 ? The fix in itself is quite straightforward I think, but the code removal can be more frightening. I'm also afraid of it :smile: but after looking at the code I think it's ok and it would be sad to miss an opportunity to simplify a bit the code.

**Comment by drdavella** [comment]
@saimn, this looks good to me (in as much as I can follow it). Just curious, but even though this doesn't fix #3921, is there currently a corresponding test that `xfails`? If not, do you understand the problem enough to add an `xfail` test to this PR?

**Comment by bsipocz** [comment]
2.0.3 is out, so this can be not rebased.

**Comment by saimn** [comment]
@drdavella - This [commit](https://github.com/astropy/astropy/pull/6956/commits/b672abbf70b606584041722b57ce58df16dc74fb) was meant to reproduce the issue, but it seems that it is not exactly the same as this test now pass but I can still reproduce the error described in #3921. But anyway I prefer to leave this for another round, I think it's better to have the test with the corresponding fix (or the opposite ;)).

Otherwise I rebased to be sure the changelog is there for 2.0.4.

**Comment by saimn** [comment]
ping @MSeifert04 @drdavella - is this fine for you ?

What's the policy for v3.0 inclusion now that it is branched ? It can go to v3.0.1 if needed, but it is "just" a bugfix.

**Comment by bsipocz** [comment]
@saimn - bugfixes can still go into 3.0.0, especially everything that goes into 2.0.4 should actually end up being in 3.0.0, too (unless 2.0.x specific, and we don't have that many of those).

**Comment by saimn** [comment]
@bsipocz - Ok great, so I just need someone to approve :wink: (ping @drdavella as you already had a look)

**Comment by saimn** [comment]
@drdavella @MSeifert04 - ping !

**Comment by drdavella** [comment]
@saimn I don't think you meant to close #3921 with this PR right? It looks like it will need to be reopened.

**Comment by saimn** [comment]
Thanks, good catch (I should be more careful when using "fix" in the issue description!).

**Comment by MSeifert04** [comment]
Thanks @saimn

**Pull request merged**
