### PR TITLE
TST: Add regression test for Issue 12706

### LINKED ISSUE #12687: TST: Unpin conditions in test_copy_vla
Follow-up of:

* #12682

Depends on:

* numpy/numpy#20699

Remove this pin and make sure CI does not fail for that test no more:

https://github.com/astropy/astropy/blob/3d522ebcbe6903326cb8b44e1ca970d206a4bd73/astropy/io/fits/tests/test_table.py#L2913-L2916

### LINKED ISSUE #12706: Astropy grouped table aggregation with columns of non-native endianness is broken in Numpy 1.22
### Description
With numpy 1.22, astropy fails to aggregate table columns of non-native endianness. This works with numpy 1.21.

### Expected behavior
With numpy 1.21.5:

```pycon
>>> import numpy as np
>>> from astropy.table import Table
>>> table = Table({'foo': np.arange(10, dtype='>f8')})
>>> table['bar'] = table['foo'] % 2
>>> table.group_by('bar').groups.aggregate(np.sum)
<Table length=2>
  foo     bar  
float64 float64
------- -------
   20.0     0.0
   25.0     1.0
```

### Actual behavior
With numpy 1.22.0:

```
>>> import numpy as np
>>> from astropy.table import Table
>>> table = Table({'foo': np.arange(10, dtype='>f8')})
>>> table['bar'] = table['foo'] % 2
>>> table.group_by('bar').groups.aggregate(np.sum)
WARNING: Cannot aggregate column 'foo' with type '>f8' [astropy.table.groups]
<Table length=2>
  bar  
float64
-------
    0.0
    1.0
```

### Steps to Reproduce
(see example code above)

### System Details
```pycon
>>> import platform; print(platform.platform())
macOS-11.6.2-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.8.12 (default, Nov 13 2021, 08:16:46) 
[Clang 12.0.5 (clang-1205.0.22.11)]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.22.0
>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 5.0
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.7.3
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.5.1
```

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to add a regression test. Might want to backport because we should also guard LTS against this creeping back in again.

Fixes #12706 and fixes #12687

### TODO

- [x] Do we need to pin numpy version? Only do it if it fails.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Great!

**Comment by mhvk** [comment]
Except of course that it fails: I think we'd want to do an `xfail` on numpy == 1.22.0 (probably need to define a `NUMPY_LT_1_22_1` for that...)

**Comment by pllim** [comment]
Hmm, I did a `skipif` instead of `xfail`. Do you want me to change it to `xfail`?

**Comment by pllim** [comment]
"Allowed failure" job failed with an unrelated socket timeout.

**Review by lpsinger — APPROVED** [review]

**Review by mhvk — APPROVED** [review]
Looks good! Given that we *know* 1.22 gives a failure, `skipif` is more logical - it is not as if the test will suddenly surprisingly succeed!

**Comment by pllim** [comment]
Manual backport done in #12719

**Pull request merged**
