### PR TITLE
fixed doc typos

### PR DESCRIPTION
**Pull request by johnnygreco**
I fixed 2 minor typos in the *Working with Angles* docs.

### CODE REVIEW

**Comment by johnnygreco** [comment]
Awesome, thanks Adrian!

**Comment by pllim** [comment]
Not sure how to milestone this. Is typo considered bug fix?

**Comment by larrybradley** [comment]
@pllim Yes, I put typos in the bug fix branch.

**Comment by pllim** [comment]
Ok merging. Thanks!

**Comment by bsipocz** [comment]
@pllim - Either way, both for typos and other docs changes. If it's not a clean backport I can easily remilestone for major release at release time.

**Pull request merged**
