### PR TITLE
Adding python 3.6 builds to travis

### PR DESCRIPTION
**Pull request by bsipocz**
Python 3.6 is out today, so we should add it to the matrix.

### CODE REVIEW

**Comment by astrofrog** [comment]
@bsipocz - I wonder if it might make more sense to update the default from 3.5 to 3.6 and add an explicit 3.5 build?

**Comment by bsipocz** [comment]
@astrofrog - Sounds like a good plan. We should anyway wait with this PR until conda provides python 3.6 and packages. A related question: should we change the version in appveyor, too?

**Comment by astrofrog** [comment]
@bsipocz - I would lean on the side of updating AppVeyor too

**Comment by mwcraig** [comment]
Python 3.6 is available on conda defaults now, along with the core packages (numpy, scipy, a few others). It will take them a couple weeks to build out the rest of the packages in defaults: https://groups.google.com/a/continuum.io/forum/m/?utm_medium=email&utm_source=footer#!msg/conda/QJenUjUWKYc/j2DdI9f6EAAJ

**Comment by bsipocz** [comment]
Thanks @mwcraig for the heads up. I've just force pushed this, so hopefully travis will work.

**Comment by mwcraig** [comment]
I've built 1.0.11, 1.2.2 and 1.3 on python 3.6 for astropy-ci-extras. Will move some of that to the astropy channel on Monday.

**Comment by mwcraig** [comment]
Still no h5py on python 3.6...

**Comment by astrofrog** [comment]
Nor Matplotlib. I think we'll need to be patient.

**Comment by bsipocz** [comment]
This PR also removes the sphinx version limitation (it was needed with <1.3 helpers, see https://github.com/astropy/astropy/pull/5568)

**Comment by bsipocz** [comment]
I've temporarily added conda-forge as a channel for the py3.6 builds to pick up the latest setuptools. Indeed it helped, and the weird error disappeared, but now there are other mpl related failures. 
cc @astrofrog @MSeifert04 

https://travis-ci.org/astropy/astropy/jobs/194574394

**Comment by astrofrog** [comment]
@bsipocz - can you rebase and try again without conda-forge? We really don't want to be using conda-forge for the CI, mixing conda-forge and defaults leads to all kinds of fun.

**Comment by bsipocz** [comment]
@astrofrog - Sure. I suspect it will still fail due to the old setuptools on defaults, and also due to the mpl issues.

**Comment by mhvk** [comment]
It actually seems to have worked, with one probably correct error for a `\s` escape sequence in a string (should this be a byte string at all? Maybe just a raw string?):
```
File "/home/travis/build/astropy/astropy/astropy/config/configuration.py", line 601

    content = re.sub(b'\njquery_url\s*=\s*[^\n]+', b'', content)
```

**Comment by bsipocz** [comment]
This PR now includes a temporary xfail for the windows version tests that are failing with np 1.12. They can be removed once #5797 is fixed.

**Comment by bsipocz** [comment]
:tada: this is all green now, we can start testing with python3.6!

**Comment by mhvk** [comment]
Fantastic! Looked over it once more and think all is OK, so merging!

**Pull request merged**
