### PR TITLE
Updated Cython version to >=0.19 in docs

### PR DESCRIPTION
**Pull request by aniketk21**
@astrofrog Updated Cython version number to >=0.19 in `docs/install.rst` #4705

### CODE REVIEW

**Comment by aniketk21** [comment]
Travis CI tests failed with the following error. What does it mean?
`Traceback (most recent call last):`
`File "/home/travis/miniconda/envs/test/bin/pip", line 6, in <module>
    sys.exit(pip.main())`
`File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')`
`File "/home/travis/miniconda/envs/test/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)`
`locale.Error: unsupported locale setting`

**Comment by bmorris3** [comment]
It looks to me like the travis job needs to be restarted.

**Comment by pllim** [comment]
Looks more like this needs to be rebased so it picks up the fix in #4717.

**Comment by eteq** [comment]
It'll be fine when merged, though, so I'll go ahead and merge it.  Thanks @aniketk21!

**Pull request merged**
