### PR TITLE
Update to WCSLIB 7.12

### LINKED ISSUE #13509: Incorrect behavior in vectorized `wcs.world_to_pixel()` with TPV
### Description

The `wcs.world_to_pixel()` function can give incorrect results when run in vectorized mode with TPV.

### Expected behavior

Results from vectorized mode are the same as in scalar mode.

### Actual behavior

In my vectorized test case, outputs are mostly bogus.

### Steps to Reproduce

Here is a reproduction case — apologies for the length:

```python
from astropy.coordinates import SkyCoord
from astropy import units as u
from astropy.wcs import WCS
import numpy as np

# Create a WCS with a base TAN projection
hdr = {
    "WCSAXES": 2,
    "CRPIX1": 9019.3448,
    "CRPIX2": 9822.9018,
    "PC1_1": -0.00116096,
    "PC1_2": 0.000330426,
    "PC2_1": 0.000330397,
    "PC2_2": 0.00116203,
    "CDELT1": 1.0,
    "CDELT2": 1.0,
    "CUNIT1": "deg",
    "CUNIT2": "deg",
    "CTYPE1": "RA---TAN",
    "CTYPE2": "DEC--TAN",
    "CRVAL1": 337.103834,
    "CRVAL2": 90.0,
    "EQUINOX": 2000.0,
}
wcs_tan = WCS(hdr)

# Create a WCS with TPV distortion terms
hdr.update(
    **{
        "CTYPE1": "RA---TPV",
        "CTYPE2": "DEC--TPV",
        "PV1_0": -0.004862344579,
        "PV1_1": 0.9988506351,
        "PV1_2": 0.0003631415552,
        "PV1_4": -0.000151807543,
        "PV1_5": 0.0003264940806,
        "PV1_6": 1.054162749e-05,
        "PV1_7": 3.71399551e-05,
        "PV1_8": -4.673290603e-06,
        "PV1_9": -8.221049725e-06,
        "PV1_10": -2.048430933e-05,
        "PV1_12": 3.850243018e-06,
        "PV1_13": -3.850788487e-06,
        "PV1_14": -4.402412681e-07,
        "PV1_15": -1.261618912e-06,
        "PV1_16": -3.483007815e-07,
        "PV1_17": -2.971533523e-07,
        "PV1_18": 1.807889219e-07,
        "PV1_19": -2.141983906e-07,
        "PV1_20": 1.168331168e-07,
        "PV1_21": 1.762917378e-07,
        "PV1_22": 1.134792701e-07,
        "PV2_0": -0.005101922485,
        "PV2_1": 1.000314578,
        "PV2_2": 0.0009117987251,
        "PV2_4": 5.178903105e-05,
        "PV2_5": -0.0001677371386,
        "PV2_6": 0.0003132549032,
        "PV2_7": -1.196471938e-05,
        "PV2_8": -2.031118482e-05,
        "PV2_9": 1.334272569e-05,
        "PV2_10": -1.92055231e-05,
        "PV2_12": -3.595935319e-07,
        "PV2_13": 1.634133749e-07,
        "PV2_14": -1.36746203e-06,
        "PV2_15": 1.684772597e-06,
        "PV2_16": -3.050997407e-06,
        "PV2_17": 8.867628883e-08,
        "PV2_18": 1.641951829e-07,
        "PV2_19": -6.17124982e-08,
        "PV2_20": -2.511534806e-08,
        "PV2_21": -5.634176609e-08,
        "PV2_22": 1.882567755e-07,
    }
)
wcs_tpv = WCS(hdr)

# Vector of lats and lons that demonstrate the problem
lats = np.linspace(1.0453819570955787, 1.2938789521827248, 256)
lons = np.linspace(3.7637488459848645, 4.709526042452718, 256)
INDEX = 230

def do_scalar(wcs):
    "Calculate the pixel coordinate of a particular position with scalar evaluation"
    c = SkyCoord(lons[INDEX] * u.rad, lats[INDEX] * u.rad, frame="icrs")
    idx = wcs.world_to_pixel(c)
    return (idx[0].item(), idx[1].item())

def do_vector(wcs):
    "Calculate the pixel coordinate of a particular pixel with vector evaluation"
    c = SkyCoord(lons * u.rad, lats * u.rad, frame="icrs")
    idx = wcs.world_to_pixel(c)
    return (idx[0][INDEX], idx[1][INDEX])

# Without distortions, results are consistent as you would hope:
print("TAN scalar:", do_scalar(wcs_tan))
print("TAN vector:", do_vector(wcs_tan))

# With distortions, results are not consistent:
print("TPV scalar:", do_scalar(wcs_tpv))
print("TPV vector:", do_vector(wcs_tpv))
```

Comparing the result of `wcs.world_to_pixel()` for the scalar versus vector inputs here, it looks like the 0'th element of the array is correct, but the rest are garbage. So, perhaps something is trying to vectorize but not actually initializing anything past the 0'th element?

**Update:** If I run the test repeatedly, the results from the vector-TPV case vary, although they are always around -1. So there is probably some uninitialized memory being read here.

### System Details

```
Linux-5.18.13-200.fc36.x86_64-x86_64-with-glibc2.35
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]
Numpy 1.23.1
pyerfa 2.0.0.1
astropy 5.1
Scipy 1.8.1
Matplotlib 3.5.2
```

CC @imbasimba

### PR DESCRIPTION
**Pull request by mcara**
### Description
This PR updates built-in WCSLIB distributed with `astropy`. From WCSLIB's changelog:

```
WCSLIB version 7.12 (2022/09/09)
--------------------------------

* C library

  - In wcsp2s() and wcss2p(), fixed handling of status returns from
    linp2x() and linx2p() relating to distortion functions, specifically
    with respect to setting the stat[] vector.  Reported by Sepideh
    Eskandarlou (via Mohammad Akhlaghi).

  - When extracting by axis type, wcssub() did not account for the
    possibility of time axes with -TAB or -LOG algorithm codes.
    Reported by Mihai Cara.
```

For a full list of changes, see [WCSLIB's CHANGELOG](https://github.com/mcara/astropy/blob/24e8730c63902d035cb9110eae2a9ebec12d8905/cextern/wcslib/CHANGES).

My hope is that second point addresses an issue the only reference to which is in this comment: https://github.com/astropy/astropy/issues/12095#issuecomment-1226296205

And the first point in the changelog above,
Fixes #13509

Thanks to @pkgw for providing Mark Calabretta with a very detailed description of the issue with C test.

### Checklist for package maintainer(s)
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Do the proposed changes need the code-style [fixed](https://docs.astropy.org/en/latest/development/workflow/maintainer_workflow.html#pre-commit_bot)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Needs a change log, right? Let me enable cron jobs too.

**Comment by mcara** [comment]
patience, my friend. see https://github.com/astropy/astropy/pull/12994#issuecomment-1080796592

**Review by olebole — APPROVED** [review]
That looks OK for me; the change seems unproblematic everywhere. I also uploaded the new version to Debian, and all dependent tests (inclusive Astropy) passed.

**Comment by mcara** [comment]
@olebole Thank you!

**Review by pllim — APPROVED** [review]
Everything is green now. Thanks!

**Pull request merged**
