### PR TITLE
WCSaxes fail when projection two PV WCSes onto each other

### PR DESCRIPTION
**Pull request by keflavich**
@astrofrog

PV WCSes, i.e., those with a single spatial/celestial dimension and a spectral
dimension, are a bit of a hack, but we want to support them.

If you try to use wcsaxes with these and give another wcs as the frame to transform to (e.g., for overlaying two projections), it fails:

```
from astropy.io import fits
from astropy import wcs
import pylab as pl

fh = fits.open('sourceI_Unknown_8_B6_robust0.5_diskpv_0.1.fits')
ww = wcs.WCS(fh[0].header)

fig = pl.figure(1)
ax = fig.add_axes([0.15, 0.1, 0.8, 0.8],projection=ww)
ax.get_transform(ww)
```
results in
```
Traceback (most recent call last):
  File "<ipython-input-9-fa8f33f06421>", line 1, in <module>
    ax.get_transform(ww)
  File "/Users/adam/repos/astropy/astropy/visualization/wcsaxes/core.py", line 465, in get_transform
    return self._get_transform_no_transdata(frame).inverted() + self.transData
  File "/Users/adam/repos/astropy/astropy/visualization/wcsaxes/core.py", line 477, in _get_transform_no_transdata
    coord_in = wcs_to_celestial_frame(self.wcs)
  File "/Users/adam/repos/astropy/astropy/wcs/utils.py", line 205, in wcs_to_celestial_frame
    raise ValueError("Could not determine celestial frame corresponding to "
ValueError: Could not determine celestial frame corresponding to the specified WCS object
```

This PR hacks around that by letting the frame transformation fail.  However, I
don't think this is the right thing to do, it's just a step in the ~~right~~
usable direction.

### CODE REVIEW

**Comment by astrofrog** [comment]
@keflavich - can you send me example files to replicate this?

**Comment by keflavich** [comment]
here's an example header:
```
SIMPLE  =                    T / conforms to FITS standard
BITPIX  =                  -64 / array data type
NAXIS   =                    2 / number of array dimensions
NAXIS1  =                   99
NAXIS2  =                   34
WCSAXES =                    2 / Number of coordinate axes
CRPIX1  =                  1.0 / Pixel coordinate of reference point
CRPIX2  =              -1244.0 / Pixel coordinate of reference point
CDELT1  =   2.222222222866E-06 / [deg] Coordinate increment at reference point
CDELT2  =     -3304.5976418118 / [m/s] Coordinate increment at reference point
CUNIT1  = 'deg'                / Units of coordinate increment and value
CUNIT2  = 'm/s'                / Units of coordinate increment and value
CTYPE1  = 'OFFSET'             / Coordinate type code
CTYPE2  = 'VRAD'               / Radio velocity (linear)
CRVAL1  =                  0.0 / [deg] Coordinate value at reference point
CRVAL2  =      4172742.2954657 / [m/s] Coordinate value at reference point
LONPOLE =                180.0 / [deg] Native longitude of celestial pole
LATPOLE =      -5.375172042341 / [deg] Native latitude of celestial pole
RESTFRQ =        88591264400.0 / [Hz] Line rest frequency
SPECSYS = 'LSRK'               / Reference frame of spectral coordinates
OBSGEO-X=       2225142.180269 / [m] ITRF observatory X-coordinate
OBSGEO-Y=      -5440307.370349 / [m] ITRF observatory Y-coordinate
OBSGEO-Z=      -2481029.851874 / [m] ITRF observatory Z-coordinate
MJD-OBS =      58020.379289722 / [d] MJD of observation matching DATE-OBS
DATE-OBS= '2017-09-24T09:06:10.631999' / ISO-8601 observation date matching MJD-
END
```

**Comment by astrofrog** [comment]
I'll take a look at this in the next few days - I'll keep this open since there isn't an associated issue.

**Comment by bsipocz** [comment]
@astrofrog - Is this still in the scope for 3.1?

**Comment by astrofrog** [comment]
No - this will be a bug fix anyway so not critical

**Comment by bsipocz** [comment]
OK. I've made a 3.1.1 milestone as well.

**Comment by astrofrog** [comment]
Let's wait until https://github.com/astropy/astropy/pull/8885 is implemented since that changes some of the relevant code.

**Comment by bsipocz** [comment]
> Let's wait until #8885 is implemented since that changes some of the relevant code.

sounds good. But after that is merged and this got rebased please remove the `keep-open` tag.

**Comment by bsipocz** [comment]
@astrofrog @keflavich - What's the status with this? Please rebase and remove the label if you aim it to land in 3.2.2 next week.

**Comment by bsipocz** [comment]
@keflavich or @astrofrog - could you have a look at this? It has the `keep-open` label for a while but may not even be relevant to keep open in the current form past APE14

**Comment by astrofrog** [comment]
The MWE here works well now with the latest version of astropy, so as @bsipocz said the APE 14 changes probably fixed this on their own.

**Pull request closed without merging**
