### PR TITLE
Start working on SkyOffsetFrame(origin, polar=True)

### PR DESCRIPTION
**Pull request by maxnoe**
This is to address #10783 

Here I add a `polar=True` attribute to the `SkyOffsetFrame` that will rotate the system so that the `origin` is at the northern pole and the default representation of the resulting coordinates is `PhysicsSphericalRepresentation` to directly have access to `theta`, and `phi`.

At the moment, this has a 90° rotation with what I'd like to see however....

```python

from astropy.coordinates import SkyCoord, SkyOffsetFrame, PhysicsSphericalRepresentation, Angle
import numpy as np
import astropy.units as u
import matplotlib.pyplot as plt

plt.rcParams['figure.constrained_layout.use'] = True


crab = SkyCoord.from_name("Crab")
zeta_tauri = SkyCoord.from_name("Zeta Tauri")
tauri_114 = SkyCoord.from_name("114 Tauri")


# and with polar=False (default, as previously)
offset_frame = SkyOffsetFrame(origin=crab)
crab_offset = crab.transform_to(offset_frame)
zeta_tauri_offset = zeta_tauri.transform_to(offset_frame)
tauri_114_offset = tauri_114.transform_to(offset_frame)


# and with polar=True (new)
polar_frame = SkyOffsetFrame(origin=crab, polar=True)
crab_polar = crab.transform_to(polar_frame)
zeta_tauri_polar = zeta_tauri.transform_to(polar_frame)
tauri_114_polar = tauri_114.transform_to(polar_frame)


theta_ticks = np.arange(0, 2, 0.25)

fig = plt.figure(figsize=(8, 4))

ax1 = fig.add_subplot(1, 2, 1)
ax1.set_aspect(1)


for s, label in zip([crab_offset, zeta_tauri_offset, tauri_114_offset], ['Crab', 'Zeta Tauri', '114 Tauri']):
    ax1.plot(s.lon.deg, s.lat.deg, 'o', label=label)

ax1.legend()
ax1.set_xlim(-2, 2)
ax1.set_ylim(-2, 2)
ax1.set_xlabel('offset lon / deg')
ax1.set_ylabel('offset lat / deg')

for theta in theta_ticks:
    ax1.add_artist(plt.Circle(xy=(0, 0), radius=theta, fill=False, linewidth=0.5, color='gray'))

for y1, y2 in [(-1, 1), (1, -1)]: 
    ax1.axline([-1, y1], [1, y2], color='gray', lw=0.5)


ax1.grid()
ax1.set_title('SkyOffsetFrame(origin=crab)')


ax2 = fig.add_subplot(1, 2, 2, projection='polar')
ax2.set_title('SkyOffsetFrame(origin=crab, polar=True)')


for s, label in zip([crab_polar, zeta_tauri_polar, tauri_114_polar], ['Crab', 'Zeta Tauri', '114 Tauri']):
    ax2.plot(s.phi.rad, s.theta.deg, 'o', label=label)

ax2.set_yticks(theta_ticks)
ax2.set_ylim(0, 2)
ax2.legend()
plt.show()
```

polar_offset

### CODE REVIEW

**Comment by maxnoe** [comment]
@mhvk Maybe you can have a look If I made an obvious mistake with the rotatation matrices?

**Comment by mhvk** [comment]
OK, will try to have look!

**Comment by maxnoe** [comment]
Ok, the rotation kwarg now also works as expected (the axis has to be `z` for the polar version).

Still there is a 90° rotation where I am not sure where this is coming from.... I now get what I want with passing `rotation=90°` to the offset frame, but I am still surprised that this is necessary...

**Comment by mhvk** [comment]
Moving this over from the issue and editing numbers...

Now had a look: I think the machinery looks really good! I'm actually somewhat impressed with our system that it ended up this (relatively) straightforward.

On the orientation/rotation: What exactly is the standard for where phi=0 is located and the direction it increases? For the equatorial version, I would normally expect the offset in latitude to go from bottom to top, as you have it in the drawing, but longitude from right to left, i.e., N up, E left.  I'd have thought that for the polar version, theta would be the angular offset from the source (i.e., the radii that you draw), while phi would be like a position angle, measured from N through E.

Or, perhaps more concretely, I'd guess that the coordinates of other objects relative to the origin would be the same as what you use in `spherical_offsets_by` and `directional_offset_to`. Thus, I'd expect 114 Tau, which is roughly to the W, to be at `phi~270` (or `-90`) and zeta tau at `phi~135`, which is `180-<angle-in-fig>`.

**Comment by maxnoe** [comment]
I'd hoped (or at least that was my naive goal for our Field of View coordinates) that using both variants of the skyoffsetframe would produce the same "image", e.g. that `phi` is the mathematical polar angle, starting at the lon axis going positive counter-clockwise. 

So that it is a more correct version but very close for small angles to `phi = np.arctan2(dlat, dlon)`

**Comment by maxnoe** [comment]
> Or, perhaps more concretely, I'd guess that the coordinates of other objects relative to the origin would be the same as what you use in spherical_offsets_by and directional_offset_to.

Yes, this makes sense. I'll check.

**Comment by maxnoe** [comment]
It does not really work, I think it is connected to the issue that the origin in my tests is not transformed to `theta=0, phi=0` but to `theta=0, phi=<something>`. Which is not really incorrect, since phi is degenerate at the pole, but it seems to affect the `position_angle`, which seems to be `origin.phi + other.phi`

**Comment by Cadair** [comment]
You might also want to look at: https://github.com/sunpy/sunpy/blob/main/sunpy/coordinates/offset_frame.py#L7

I think it's pretty similar to what you are doing here?

**Comment by maxnoe** [comment]
@Cadair Yes, indeed!

**Comment by mhvk** [comment]
I'm confused about "FOV LON should increase with decreasing OTHER LON" since I think this is not true for the current `SkyOffsetFrame`...

**Comment by maxnoe** [comment]
Yes, we would need add a sign in our own frame. This is from a data format specification,  and our implementation based on skyoffsetframe does not have it either. 


https://github.com/cta-observatory/ctapipe/issues/1843

**Pull request closed without merging**
