### PR TITLE
fix for maxiter argument to SLSQPLSQFitter

### LINKED ISSUE #3338: maxiter argument to SLSQPLSQFitter.__call__ broken
As pointed out in [this comment](https://github.com/astropy/astropy/pull/3305#issuecomment-70253326), calling an `SLSQPLSQFitter` instances with the optional `maxiter` keyword argument fails, although it is advertised to work in the docs.  This appears to be little more than a simple argument handling bug, and possibly affects other fitter classes as well.

### PR DESCRIPTION
**Pull request by nden**
fixes #3338

### CODE REVIEW

**Comment by embray** [comment]
Thanks.  Now that I look I don't think any of the other existing optimizers share this issue. I'm not sure if it's straightforward to write a test for this--is "maxiter" anywhere in the output fit info, or just the actual number of iterations?  Anyways, unless you can think of anything I don't think it's worth tying ourselves inside out for a test for this.  Just a changelog entry is needed.

**Comment by nden** [comment]
It's the number of iterations and by default it's 100. I tested it manually and don't think we need a test. The name for this argument for this optimizer in scipy is "iter" ("maxiter" for the others) so the rest of the optimizers don't have this problem.

**Comment by embray** [comment]
Right, I just wondered if there was some way to check if the scipy optimizer actually used it as the default max number of iterations (i.e. to ensure we're passing in the correct argument).  But I agree it's not crucial to have tests for.

**Comment by nden** [comment]
It's not that easy because what's reported is the actual number of iterations, not the requested maximum number. The easy test I can think of is to pass maxiter>100 and make sure it doesn't crash, which I did but I don;t think it's worth writing a test for this.

**Comment by embray** [comment]
That's what I figured.

**Comment by embray** [comment]
Merged manually in 9828969 in order to fix position of the changelog entry.

**Pull request closed without merging**
