### PR TITLE
Fixed segfault issue with empty quoted fields

### LINKED ISSUE #3407: table read failure with ascii.commented_header format
I have a file that looks like this:
```
# a b c d e f g h i j k l m n o
NGC14 108.13 -45.83 1.41 1.05 4.05E+20 12.8 T88 IB(s)m 10.0 2.4e+09 0.053 256 1.2e-14  ""  
NGC45 55.89 -80.67 4.26 2.95 2.24E+20 8.1 T92  SA(s)dm 8.0 3.8e+09 0.012 39 2.4e-15  ""  
NGC55 332.67 -75.74 16.18 2.81 1.72E+20 1.48 MM  SB(s)m 9.0 3.0e+09 0.076 57 1.6e-15  ""  
```
and I find that
```
from astropy.table import Table
test = Table.read('test',format='ascii')
```
works fine, while using `format='ascii.commented_header'` results in an ipython crash. This problem happens in astropy 1.0rc1 but *not* in 0.4.4. I'm using anaconda python under OS X 10.6.8.

### PR DESCRIPTION
**Pull request by mdmueller**
This should fix #3407.

### CODE REVIEW

**Comment by taldcroft** [comment]
@mdmueller - you don't actually need the CHANGES.rst entry since this fixes a bug that was only in dev.

Apart from that this looks OK.  @embray - did you want to have a look at this before merging?

**Comment by mdboom** [comment]
Makes sense to me.

**Comment by embray** [comment]
Thanks!  Glad I didn't have to spend any more time debugging that... :)

I'm going to manually merge and strip out the changelog entry.

**Comment by embray** [comment]
Merged in 8914e0e.  Thanks @mdmueller for the quick fix!

**Comment by mdmueller** [comment]
No problem!

**Pull request closed without merging**
