### PR TITLE
TST: fix compatibility issue with pytest dev (8.1)

### LINKED ISSUE #16016: TST: 9 failures in test_angles.py in devinfra job
Probably something changed again in pytest-dev . Just started seeing this today. I restarted a previously passing job on `main` and it fails now: https://github.com/astropy/astropy/actions/runs/7780284592/job/21375925091

All failures are similar in nature as this:

```
>       with pytest.warns(IllegalMinuteWarning):
astropy/coordinates/tests/test_angles.py:495: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
wrn = <warnings.WarningMessage object at 0x7fc1da718650>
    @staticmethod
    def _validate_message(wrn: Any) -> None:
        if not isinstance(msg := wrn.message.args[0], str):
>           raise TypeError(
                f"Warning message must be str, got {msg!r} (type {type(msg).__name__})"
            )
E           TypeError: Warning message must be str, got 60 (type int)
_pytest/recwarn.py:340: TypeError
```

```
FAILED coordinates/tests/test_angles.py::test_negative_sixty_hm - TypeError: Warning message must be str, got 60 (type int)
FAILED coordinates/tests/test_angles.py::test_plus_sixty_hm - TypeError: Warning message must be str, got 60 (type int)
FAILED coordinates/tests/test_angles.py::test_negative_fifty_nine_sixty_dms - TypeError: Warning message must be str, got 60 (type int)
FAILED coordinates/tests/test_angles.py::test_plus_fifty_nine_sixty_dms - TypeError: Warning message must be str, got 60 (type int)
FAILED coordinates/tests/test_angles.py::test_negative_sixty_dms - TypeError: Warning message must be str, got 60 (type int)
FAILED coordinates/tests/test_angles.py::test_plus_sixty_dms - TypeError: Warning message must be str, got 60 (type int)
FAILED coordinates/tests/test_angles.py::test_angle_to_is_angle - TypeError: Warning message must be str, got 60 (type int)
FAILED coordinates/tests/test_angles.py::test_angle_to_quantity - TypeError: Warning message must be str, got 60 (type int)
FAILED coordinates/tests/test_angles.py::test_angle_string - TypeError: Warning message must be str, got 60 (type int)
```

Caused by:

* https://github.com/pytest-dev/pytest/pull/11804

Because we have:

https://github.com/astropy/astropy/blob/102b37c9130090c40e4791e5953b688950ecc7d0/astropy/coordinates/angles/errors.py#L106-L117

Reported to:

* https://github.com/pytest-dev/pytest/issues/11954

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description

Fixes #16016

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
This is meant to fix `Extra CI`, so please apply the corresponding label. Thanks !

**Review by eerovaher — CHANGES_REQUESTED** [review]
At this point I am convinced that the bug is in `pytest`, not in `astropy`, and I don't think we should be adding boilerplate code as a workaround.

I am not closing this right now, but I am formally requesting changes to block merging.

**Comment by neutrinoceros** [comment]
Honestly I'm not getting it. I don't *mind* if the bug is actually in pytest, but I feel like I'm missing something. Could you please elaborate ?

**Comment by eerovaher** [comment]
I'm working on a pull request for `pytest` right now. It will have all the details.

**Comment by eerovaher** [comment]
The bug in `pytest` has been fixed, so no changes are needed in `astropy`.

**Comment by neutrinoceros** [comment]
thanks @eerovaher !

**Pull request closed without merging**
