### PR TITLE
TST: Fix parallel data download test for v2.x

### PR DESCRIPTION
**Pull request by pllim**
Backport straight to v2.x for #7575

### CODE REVIEW

**Comment by pllim** [comment]
p.s. Ignore `32bit_py2` build. Failure is unrelated.

**Comment by pllim** [comment]
@bsipocz , is this ok to merge?

**Comment by bsipocz** [comment]
@pllim - If it passes the tests then good to go. I need to restart the failing circleCI one though, as that's the only one that actually does parallel testing on python2...

**Comment by bsipocz** [comment]
@pllim - I'm afraid the failure is related:

```
........
=================================== FAILURES ===================================
__________________________ test_download_mirror_cache __________________________
[gw0] linux2 -- Python 2.7.15 /opt/python/cp27-cp27m/bin/python

    @pytest.mark.skipif(not HAS_PATHLIB and sys.platform.startswith('win'),
                        reason="URI incorrect for Windows without pathlib")
    def test_download_mirror_cache():
        from ..data import (_find_pkg_data_path, download_file, get_cached_urls,
                            _open_shelve)
    
        main_path = _find_pkg_data_path(os.path.join('data', 'dataurl'))
        mirror_path = _find_pkg_data_path(os.path.join('data', 'dataurl_mirror'))
    
        if HAS_PATHLIB:
            main_url = pathlib.Path(main_path).as_uri()
            mirror_url = pathlib.Path(mirror_path).as_uri()
        else:  # Falls back to brute force URI
            main_url = 'file://' + main_path
            mirror_url = 'file://' + mirror_path
    
        main_file = main_url + '/index.html'
        mirror_file = mirror_url + '/index.html'
    
        # "Download" files by rerouting URLs to local URIs.
        download_file(main_file, cache=True)
        download_file(mirror_file, cache=True)
    
        # Now test that download_file looks in mirror's cache before download.
        # https://github.com/astropy/astropy/issues/6982
        dldir, urlmapfn = _get_download_cache_locs()
        with _open_shelve(urlmapfn, True) as url2hash:
>           del url2hash[main_file]

astropy/utils/tests/test_data.py:105: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/python/cp27-cp27m/lib/python2.7/shelve.py:136: in __delitem__
    del self.dict[key]
/opt/python/cp27-cp27m/lib/python2.7/bsddb/__init__.py:288: in __delitem__
    _DeadlockWrap(wrapF)  # del self.db[key]
/opt/python/cp27-cp27m/lib/python2.7/bsddb/dbutils.py:68: in DeadlockWrap
    return function(*_args, **_kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def wrapF():
>       del self.db[key]
E       TypeError: String or Integer object expected for key, unicode found

/opt/python/cp27-cp27m/lib/python2.7/bsddb/__init__.py:287: TypeError
----------------------------- Captured stdout call -----------------------------
 [Done]
 [Done]
=============================== warnings summary ===============================
<undetermined location>
  [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
  Module already imported so cannot be rewritten: xdist
  Module already imported so cannot be rewritten: xdist
  Module already imported so cannot be rewritten: pytest_remotedata
  [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
  [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
  [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
  [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.

-- Docs: http://doc.pytest.org/en/latest/warnings.html
 1 failed, 12562 passed, 383 skipped, 69 xfailed, 1 xpassed, 8 warnings in 106.62 seconds 
Exited with code 1
```

**Comment by pllim** [comment]
:scream:  OK thx for alerting me to the failure. I'll have a look soon.

**Comment by pllim** [comment]
All tests pass now, so merging. Thanks for the review!

**Pull request merged**
