### PR TITLE
Let skyfield use a temporary directory for files it downloads.

### LINKED ISSUE #10133: TST: Still some leftover doctest outputs left
A reminder to investigate https://github.com/astropy/astropy/pull/9439#issuecomment-611770982 . These files not cleaned up after a remote data tests on Windows.

```
        Leap_Second.dat
        de421.bsp
        deltat.data
        deltat.preds
```

### PR DESCRIPTION
**Pull request by mhvk**
Alternative to #10140. fixes #10133.

### CODE REVIEW

**Comment by eteq** [comment]
Oh, but if implementing the test I suggested above is going to be a huge pain given that it's sort of deep in the testing machinery, I think it'd be ok to just get a comment here from @pllim or @jdavies-st that this fixes the underlying problem...

**Comment by pllim** [comment]
>  ensure the files are not left in

@eteq , I think that is out of scope for this PR. If it were to be done, it would be for the whole repo. Maybe like a `git status` check after a remote data job with all dependencies installed on CI or something like that.

**Comment by eteq** [comment]
Point taken @pllim.  Since you confirmed it's working I'll merge this as it stands.  If it re-surfaces we should think more about how to test it properly, but hopefully that won't happen.

**Comment by mhvk** [comment]
Thanks, @pllim, for IDing the culprit and figuring out a first solution!

**Pull request merged**
