### PR TITLE
switch isort to ruff

### LINKED ISSUE #14450: Switch isort to ruff
### What is the problem this feature will solve?

https://beta.ruff.rs/docs/settings/#isort

I believe ruff now has all the settings we need to port our isort configuration.

### Describe the desired outcome

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nstarman**
### Description

Fixes #14450

### CODE REVIEW

**Comment by nstarman** [comment]
@WilliamJamieson, ruff now has all the config options necessary for the isort migration.

**Comment by nstarman** [comment]
@WilliamJamieson @mhvk @pllim, should we correct `astropy` to `known-local-folder` instead of `known-first-party`? This will make a lot of edits, but I believe was a mistake we made when first implementing isort.

**Comment by mhvk** [comment]
Not quite sure what the difference is -- could you give an example?

But independently, maybe in a separate PR? The beauty of this one is that it is just changes in setup, no actual edits to code!

**Comment by nstarman** [comment]
It really just changes which sorting block to put `astropy` in. 

```
Stdlib

Third party

First party 

Local folder
```

**Comment by mhvk** [comment]
My tendency would be to put submodule stuff in "local folder" - partially as I wouldn't know what would constitute "first party" otherwise (I think of `erfa` more like `numpy` and our other explicit dependencies). But no strong opinion.

**Comment by pllim** [comment]
TBH, I am a little tired of seeing too many PRs making stylistic changes that has no functional change in such a short time. So, if changing the setting would cause another thousand-line diff, I would say no.

**Comment by pllim** [comment]
I'll let William do the honor to approve, as I have been pretty hands off in the isort/ruff campaign. Thanks!

**Review by WilliamJamieson — APPROVED** [review]
These changes are fine with me, please rebase before we merge.

**Pull request merged**
