### PR TITLE
ENH/BUG: improve support for `pathlib.Path` inputs in `iers`

### LINKED ISSUE #16929: BUG: `astropy.time.update_leap_seconds` doesn't warn for corrupt files passed as `pathlib.Path` objects
In #16060 and #16923, we find that `astropy/time.update_leap_seconds` doesn't behave correctly if passed a corrupt file as `Path` instead of `str`.
This is visible in `astropy/test/test_update_leap_second.py::test_auto_update_corrupt_file`, as applying the following patch
```patch
diff --git a/astropy/time/tests/test_update_leap_seconds.py b/astropy/time/tests/test_update_leap_seconds.py
index a1027a0755..45250147c3 100644
--- a/astropy/time/tests/test_update_leap_seconds.py
+++ b/astropy/time/tests/test_update_leap_seconds.py
@@ -58,7 +58,7 @@ class TestUpdateLeapSeconds:
             update_leap_seconds(["nonsense"])
 
     def test_auto_update_corrupt_file(self, tmp_path):
-        bad_file = str(tmp_path / "no_expiration")
+        bad_file = tmp_path / "no_expiration"
         with open(iers.IERS_LEAP_SECOND_FILE) as fh:
             lines = fh.readlines()
         with open(bad_file, "w") as fh:
```
leads to failing the test:
```
E   Failed: DID NOT WARN. No warnings of type (<class 'astropy.utils.exceptions.AstropyWarning'>,) matching the regex were emitted.
     Regex: ValueError.*did not find expiration
     Emitted warnings: [ AstropyWarning('leap-second auto-update failed due to the following exception: AttributeError("\'PosixPath\' object has no attribute \'decode\'")')].
```
(or in other words: a different warning is emitted first)

The issue doesn't appear to be trivial enough to be fixed directly in #16023 (which is meant as a simple refactor), but it should be done as a follow up.

There should ideally be more than one test exercising passing `Path` arguments to this function.

_Originally posted by @pllim in https://github.com/astropy/astropy/pull/16923#discussion_r1742578137_

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description

Ref:  #14893

fixes #16929

This relieves a specific pain point I encountered while working on #16928, and participates to unblock it.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

TODO:
- [x] add a test

### CODE REVIEW

**Comment by pllim** [comment]
This might naturally fix https://github.com/astropy/astropy/issues/16929 also but you should confirm.

**Review by mhvk — COMMENTED** [review]
This looks good, thanks! I do think we should have at least one test - fine to adjust one of the existing ones to pass in a path instead of a string.

**Comment by neutrinoceros** [comment]
> This might naturally fix https://github.com/astropy/astropy/issues/16929 also but you should confirm.

just checked, and it doesn't.

**Comment by neutrinoceros** [comment]
... but now it does ! The fix is actually orthogonal to the initial goal of this PR but it indeed felt related enough to be bundled with it. Let me know if you'd like me to split the PR instead.

**Comment by neutrinoceros** [comment]
> fine to adjust one of the existing ones to pass in a path instead of a string.

done ! I parametrized the only existing test using `IERS_B.read` directly.

**Review by astrofrog — APPROVED** [review]
This seems ok to me - thanks!

**Review by mhvk — APPROVED** [review]
Super, great that you could fix the leap seconds too!

**Pull request merged**
