### PR TITLE
Address useless comparisons in tests

### PR DESCRIPTION
**Pull request by eerovaher**
### Description

Many of the Ruff rules `astropy` is currently ignoring would be good to enforce, but they do not affect code correctness so it is not critical to address them quickly. The [Ruff rule B015](https://beta.ruff.rs/docs/rules/#flake8-bugbear-b), which checks for comparisons whose outcome is ignored, is different because the presence of useless comparisons in tests means that there can be code that is untested despite being executed during the tests.

Currently there are four kinds of useless comparisons in `astropy` tests:
 - invalid comparisons deliberately triggering an error, which Ruff should be told to ignore with a `noqa` comment,
 - comparisons the outcome of which should be asserted,
 - equality comparisons (`==`) that were actually supposed to be assignments (`=`),
 - complicated cases that require familiarity with the subpackage to resolve (see #14920).

The first three cases in the list are properly handled by this pull request. The few of complicated comparisons are ignored at the subpackage level for now, but they should be dealt with sooner rather than later because they might be hiding actual bugs.

### Approvals by subpackage
- [x] coordinates https://github.com/astropy/astropy/pull/14919#pullrequestreview-1465145969
- [x] cosmology https://github.com/astropy/astropy/pull/14919#pullrequestreview-1463358995
- [x] io.fits https://github.com/astropy/astropy/pull/14919#pullrequestreview-1465398952
- [x] modeling https://github.com/astropy/astropy/pull/14919#pullrequestreview-1465398952
- [x] table https://github.com/astropy/astropy/pull/14919#pullrequestreview-1463012793
- [x] time https://github.com/astropy/astropy/pull/14919#pullrequestreview-1463012793
- [x] timeseries https://github.com/astropy/astropy/pull/14919#pullrequestreview-1465398952
- [x] units https://github.com/astropy/astropy/pull/14919#pullrequestreview-1463358995
- [x] utils https://github.com/astropy/astropy/pull/14919#pullrequestreview-1465147712
- [x] wcs https://github.com/astropy/astropy/pull/14919#pullrequestreview-1465398952

### CODE REVIEW

**Review by taldcroft — APPROVED** [review]
Looks good to me for io.ascii, time, table. Nice to see a few catches of real mistakes.

**Comment by eerovaher** [comment]
I don't think we need to backport the mistakes I've fixed here because they were only mistakes in how the tests were written and the code they were testing works fine, as evidenced by the fact that I've only edited Ruff configuration and test code. However, it could well be that solutions for the mistakes in #14920, which I didn't know how to fix (quickly), will have to be backported.

**Review by mhvk — APPROVED** [review]
Coordinates looks good (editing top entry and ticking it).

**Review by mhvk — APPROVED** [review]
utils looks good too.

**Review by mhvk — APPROVED** [review]
Might as well approve `io.fits`, `modeling`, and `timeseries`, and `wcs` as well, so this can go in. Thanks, @eerovaher!

**Pull request merged**
