### PR TITLE
Refer to required version of ASDF in a consistent way

### PR DESCRIPTION
**Pull request by drdavella**

### CODE REVIEW

**Comment by eteq** [comment]
I'll try to check if this fixes the bug I brought up in slack...

**Comment by pllim** [comment]
Oh noes. I just saw @eteq 's reply right after merge. Opsie.

**Comment by eteq** [comment]
No biggie @pllim - I'll create an issue about this and just close it immediately if it is fixed. I suspect others might encounter the problem I saw, though, so the issue tracker should have something about the bug itself regardless.

**Comment by eteq** [comment]
See #8301 - this did indeed fix the problem I reported in slack.  Thanks @drdavella !

**Pull request merged**
