### PR TITLE
Correction to documentation of AltAz and HADec self transforms.

### PR DESCRIPTION
**Pull request by mkbrewer**
### Description

This is just a minor correction as the self transforms have evidently been moved.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
I don't grok the transform stuff and I see code in both files, so I'll summon the coordinates maintainers to review. Thanks!

**Comment by pllim** [comment]
p.s. If this needs backporting, please change the milestone and apply backport labels. Thanks!

**Comment by pllim** [comment]
@meeseeksdev backport to v5.0.x

**Comment by pllim** [comment]
Hmmm!

**Comment by mkbrewer** [comment]
Should I restore my branch until this is resolved?

**Comment by pllim** [comment]
It should not have mattered but I guess it does not hurt.

**Comment by pllim** [comment]
@meeseeksdev backport to v5.0.x

**Comment by Carreau** [comment]
Hum... 
```
401 Client Error: Unauthorized for url: https://api.github.com/repos/astropy/astropy/forks
```

I've restarted the bot, the fork requests is to verify that `https://github.com/meeseeksmachine/astropy` exists, I'm not sure why it would suddenly not have access.

**Comment by mkbrewer** [comment]
@plim Are we all set now?

**Comment by pllim** [comment]
@meeseeksdev backport to v5.0.x

@meeseeksdev backport to v5.1.x

**Comment by pllim** [comment]
Yay, works now. Thanks for the quick fix, @Carreau !

**Pull request merged**
