### PR TITLE
Backport PR #12535: ENH: fix compatibility with numpy 1.23

### PR DESCRIPTION
**Pull request by mhvk**
Manual backport, after solving small merge conflict. The instructions were super-useful!!!

### CODE REVIEW

**Comment by pllim** [comment]
Gonna do the close/open trick. I applied a special label just for you.

**Comment by pllim** [comment]
No need to run the CI again... I'll just merge.

**Comment by pllim** [comment]
Oh wait, the original CI didn't run, did it. I'll just let it run and revisit tomorrow. 😅

**Comment by mhvk** [comment]
Hmm, devdeps fails, but looking at it, it is some kind of spacing issue in docs, definitely unrelated to this PR.

**Comment by mhvk** [comment]
p.s. For `meeseeksdev`, maybe add a note that one should add the `skip-basebranch-check` label? (You may already have done it...)

**Comment by pllim** [comment]
I did but it requires you to read the template carefully... I don't know where to draw the line between having the template be complete vs readable.

https://raw.githubusercontent.com/astropy/astropy/main/.github/PULL_REQUEST_TEMPLATE.md

```md
<!-- READ THIS FOR MANUAL BACKPORT FROM A MAINTAINER:
Apply "skip-basebranch-check" label **before** you open the PR! -->
```

**Comment by pllim** [comment]
Yes, failures are unrelated. Merging. Thanks!

**Comment by pllim** [comment]
Alas, the bot isn't ours. The message is hardcoded at https://github.com/MeeseeksBox/MeeseeksDev/blob/a1c4a737d593ad776016a110b2c5ee655e30c9fd/meeseeksdev/meeseeksbox/commands.py#L756

**Comment by mhvk** [comment]
Ah, that makes sense! Anyway, only a very small nitpick - I like the system quite a lot!

**Pull request merged**
