### PR TITLE
Bounds check fix (now with test and changelog)

### LINKED ISSUE #4957: wcs bounds_check broken if called before the first wcs transformation
If `wcs.bounds_check` is called before the first coordinate transformation, regardless of its arguments, the output of the following transformations will be `NaN`. Performing a single transformation before calling it avoids the problem, and results in correct behavior. The example below illustrates this. Uncomment the commented line to go from broken to correct behavior:

    from astropy.wcs import WCS
    wcs = WCS(naxis=2)
    wcs.wcs.ctype = ["RA---CAR","DEC--CAR"]
    wcs.wcs.cdelt = [10,10]
    wcs.wcs.crval = [-90,90]
    wcs.wcs.crpix = [10,1]

    #wcs.wcs_pix2world(0,0,0)
    wcs.wcs.bounds_check(False, False)

    for i in range(40):
            x, y = i, 0
            ra, dec = wcs.wcs_pix2world(x,y,0)
            print "%2d %8.3f %8.3f %8.3f %8.3f" % (i, x, y, ra, dec)

With the first `wcs_pix2world` in place, this should print `NaN` for every output coordinate. After uncommenting, every line should be valid.

I guess that wcslib is not properly initialized before the first coordinate transformation is performed.

### PR DESCRIPTION
**Pull request by amaurea**
This is a new version of #4959 which adds a test and a changelog. I needed to switch to a new branch to disentangle this from another pull request, and I couldn't see how to update the previous pull request with a new branch, so here is a new one.

EDIT: Fixes #4957

### CODE REVIEW

**Comment by pllim** [comment]
@mcara , you have anything to say about this?

**Comment by mcara** [comment]
This is the same fix as in #4959 and so my opinion is the same as in https://github.com/astropy/astropy/pull/4959#issuecomment-220734947 - I think we should not create the illusion that the WCS object has been initialized. If users really want to combine `set()` with `bounds_check()` then `set()` should actually be used instead of `wcsprm_python2c()` which simply replaces NaNs with indefs.

CC: @nden

**Comment by amaurea** [comment]
@mcara: `wcsbchk` actually calls `wcsset` itself if necessary. However, `wccset` doesn't work if the struct is full of NaNs. That's why the python wrapper for `wcsset` calls `wcsprm_python2c()` before invoking `wcsset` itself. That's why simply adding `wcsprm_python2c()` to `bounds_check` works. What it doesn't do, though, is substitute the NaNs back again afterwards. So it looks to me like this approach will lead to indefs becoming visible to python code.

**Comment by mcara** [comment]
Oh, sorry. I just realized something which I missed at the beginning (my appologies @amaurea). I think @amaurea fix is OK (at the very least for now).

*I think* the problem here is that if WCS was not "set" (actually, if NaNs have not been replaced with indefs) before bounds check, then setting bounds sets something within the WCS to NaN instead of indefs and later a call to ``wcsprm_python2c()`` does not replace those "inner" NaNs with indefs. Possibly, ``wcsprm_fix_values()`` in ``https://github.com/astropy/astropy/blob/master/astropy/wcs/src/pyutil.c`` should have an extra ``value_fixer()`` to fix bounds.

**Comment by eteq** [comment]
Just to be entirely clear, @mcara - you are saying it's OK for this to go in as-is, right?  That is, you agree that #4959 is a bug as @amaurea describes it here, and therefore that this fixes it?

**Comment by mcara** [comment]
@eteq Yes, I believe that @amaurea PR fixes the problem.

**Comment by mcara** [comment]
@eteq Yes,  I believe the issue described by @amaurea is a bug but I do not have the knowledge of internal workings of WCSLib and so I do not know if there is a better,  more direct, fix. I suspect that there could be a better fix but @amaurea fix does the job. 

Thanks @amaurea!

**Comment by eteq** [comment]
Great, this is passing so I will move the changelog entry to 1.2 and merge it.

**Comment by eteq** [comment]
HAH!  I got you this time, @astrobot: in fact it *has* a changelog entry - it's just that the changelog points to #4957, which this PR fixes.  I knew I'd find a chink in your armor.  We are not yet ruled by robots! 

(@astrofrog - what do you think of this?  Should we put ``no-changelog-entry-needed`` for this kind of situation?  Or do you want to modify @astrobot to look for matching bug issues?)

**Comment by eteq** [comment]
backported to 1.2.x in 614e64ac7a8746bcafe96228ab3fcd537c1f77bd

**Comment by astrofrog** [comment]
@astrobot is correct actually - for all other PRs we always mention the PR number. If you want to mention the issue it fixes, that's fine, but we should also mention the actual PR number too (that's why @astrobot says *or pull request number missing*). If we don't, then it makes it harder to check for consistency.

**Comment by pllim** [comment]
Astrobot:1 
Erik: 0

**Comment by eteq** [comment]
@astrofrog - oh, ok, gotcha - clearly I didn't read that closely enough.  

@pllim - 😢  - guess I need to welcome our new @astrobot overlords...

**Pull request merged**
