### PR TITLE
Fix config dir typo in doc 

### PR DESCRIPTION
**Pull request by pllim**
While composing #6511, I noticed a typo in the directory name.

p.s. Not sure if doc typo needs backporting, but milestoning to 2.x anyway; Feel free to move milestone as needed.

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @pllim! PRs like this are absolutely fine for 2.0.x, they are always clean backports thus add basically no overhead, while keeping the docs cleaner and nicer for LST.

Merging as no need to wait for CI.

**Comment by saimn** [comment]
I think the previous sentence was more correct: when `$XDG_CONFIG_HOME` is not defined, many software put their config in `~/.config` by default. But there are also many others that put the config in `~/.<software>`, so maybe this sentence is not needed at all, it just adds confusion.

**Comment by pllim** [comment]
On my RHEL7 machine, it defaults to `~/.astropy/config`. I cannot find any `~/.config/astropy` although `~/.config` does exist and populated with other stuff.

**Comment by pllim** [comment]
@saimn , feel free to submit a follow-up if you think this is inaccurate.

**Comment by saimn** [comment]
@pllim - Understood, but the note you modified is about the *behavior of most Linux applications*. The paragraph just above mention that the default for Astropy is `$HOME/.astropy/config`. That's why I think that the note is confusing and could be removed. (I can submit a PR for this later if this makes sense)

**Comment by pllim** [comment]
@saimn , sure, please do. The note was indeed confusing because it was not the behavior I actually observed for Astropy.

**Pull request merged**
