### PR TITLE
Remove deprecated utils.timer and utils.misc.InheritDocstrings

### LINKED ISSUE #9024: MNT: Remove deprecated InheritDocstrings
`astropy.utils.misc.InheritDocstrings` were deprecated in 4.0 (#8881) and should be removed after a reasonable deprecation period (after 4.2?). This is a follow up of #7167.

### LINKED ISSUE #9050: MNT: Remove deprecated utils.timer module
This is a follow up of #8898. `astropy.utils.timer` was deprecated in `astropy` 4.0 release (#9038) and moved to `astroquery` 0.4.0 (astropy/astroquery#1508). After a reasonable deprecation period (`astropy` 4.2?), `astropy.utils.timer` can be removed completely.

Also un-ignore the deprecation warning added to `setup.cfg` in #7928.

p.s. Don't forget to also remove the static image in `docs/_static`.

### LINKED ISSUE #10847: [4.1RC2] test_timer failed on s390x
### Description

After uploading a (mainly unchanged) release to Debian, our s390x build failed with the following test failure:
```
__________________________________ test_timer __________________________________

    @pytest.mark.filterwarnings("ignore")
    def test_timer():
        """Test function timer."""
        from astropy.utils.timer import RunTimePredictor
        p = RunTimePredictor(func_to_time)
    
        # --- These must run before data points are introduced. ---
    
        with pytest.raises(ValueError):
            p.do_fit()
    
        with pytest.raises(RuntimeError):
            p.predict_time(100)
    
        # --- These must run next to set up data points. ---
    
        p.time_func([2.02, 2.04, 2.1, 'a', 2.3])
        p.time_func(2.2)  # Test OrderedDict
    
        assert p._funcname == 'func_to_time'
        assert p._cache_bad == ['a']
    
        k = list(p.results.keys())
        v = list(p.results.values())
        np.testing.assert_array_equal(k, [2.02, 2.04, 2.1, 2.3, 2.2])
        np.testing.assert_allclose(v, [0.1, 0.2, 0.5, 1.5, 1.0])
    
        # --- These should only run once baseline is established. ---
    
        with pytest.raises(ModelsError):
            a = p.do_fit(model='foo')
    
        with pytest.raises(ModelsError):
            a = p.do_fit(fitter='foo')
    
        a = p.do_fit()
    
        assert p._power == 1
    
        # Perfect slope is 5, with 10% uncertainty
>       assert 4.5 <= a[1] <= 5.5
E       assert 4.5 <= 3.2149869047170583

astropy/utils/tests/test_timer.py:75: AssertionError
```
Since the changes are far away from the test (#10765, skipping `test_wcsapi_extension`) I would guess this is due to some unreliable timings on the build machine, therefore not really problematic. I will just disable this one for the 4.2 build.

### Expected behavior

The test is expected to succeed

### Actual behavior

Test fails.

### Steps to Reproduce
Probably this failure is rare and not simply to reproduce.

### PR DESCRIPTION
**Pull request by sashank27**
### Description

This pull request is to remove the `utils.timer` and `utils.misc. InheritDocstrings` module as they were expected to be removed after the passing of their deprecation period (i.e. after 4.0)

Fixes #9024
Fixes #9050
EDIT: Close #10847

### CODE REVIEW

**Comment by pllim** [comment]
Thanks, but I think it is a bit too soon for this yet.

**Comment by sashank27** [comment]
In the original issues, this removal was planned for 4.2

**Comment by pllim** [comment]
I mentioned "4.2?" with a question mark. 😅

**Comment by embray** [comment]
Unless that's changed, I think the usual deprecation period is two minor releases.

**Comment by pllim** [comment]
Hard for me to remember which is major and which is minor for `astropy` because it doesn't follow strict semver.

**Comment by pllim** [comment]
Let's keep this open. We do want to remove them eventually, just not sure when.

**Comment by pllim** [comment]
Thanks for your patience, @sashank27 ! I rebased to remove conflict and added change log. I think this is ready for 4.3, but let's see what other maintainers say.

**Review by embray — APPROVED** [review]

**Pull request merged**
