### PR TITLE
Remove licenses that aren't needed anymore

### PR DESCRIPTION
**Pull request by astrofrog**
It turns out quite a few licenses weren't needed anymore:

* ``FUTURES_LICENSE.rst``: we used to bundle concurrent.futures for Python 2 but don't anymore
* ``NUMPY_LICENSE.rst``: it looks like the content of ``stride_tricks.py`` and ``multiarray.py`` has been removed since this was for old Numpy versions.
* ``PYTEST_LICENSE.rst``: we no longer bundle pytest
* ``SIX_LICENSE.rst``: we no longer bundle six
* ``SPHINXECT_LICENSES.rst``: we no longer bundle numpydoc
* ``SYMPY.rst`` - this was for the output checker which is now in pytest-doctestplus

@mhvk - are we safe to remove the Numpy license?

@drdavella - we need to include the SYMPY.rst license in pytest-doctestplus

I wonder whether as a policy, when including one or two files from another project we should just put the license at the top of the source code rather than having decoupled license files? This would avoid a buildup of obsolete licenses like this.

cc @namurphy

### CODE REVIEW

**Comment by bsipocz** [comment]
Most of these changes seems to be 3.0 or prior. Should we backport this to 3.0.0, right?

**Comment by astrofrog** [comment]
@bsipocz - I think so but I would like to get confirmation from @mhvk about the Numpy license

**Comment by mhvk** [comment]
@astrofrog - following your suggestion, how about moving the numpy license to `utils/compat/numpy/`? If we remove it now, the next time we have a compatibility issue, we have to remember to add it back...

**Comment by astrofrog** [comment]
@mhvk - ok that makes sense, but since not including licenses in ``licenses`` will be a policy change, I'd like to do that in a separate PR (and can move the other licenses at the same time) and we can decide if we want that.

This way the current PR is ready to go for 3.0

**Comment by mhvk** [comment]
Yes, that is fair enough. And maybe we want to get rid of `utils/compat/numpy` altogether...

**Pull request merged**
