### PR TITLE
Updated bundled py.test to 2.8.3

### PR DESCRIPTION
**Pull request by astrofrog**
This updates the bundled py.test to 2.8.3 and fixes the issue reported by @bsipocz: https://github.com/astropy/astropy/issues/3499

The easiest way to reproduce that original issue is:

```python
python -c 'from astropy import test; test("modeling"); test("modeling")'
```

However, there are still some other (unrelated) errors in the second run:

```python
...
Platform: Darwin-12.5.0-x86_64-i386-64bit

Executable: /Users/tom/miniconda3/envs/production/bin/python

Full Python Version: 
3.4.3 |Continuum Analytics, Inc.| (default, Oct 20 2015, 14:27:51) 
[GCC 4.2.1 (Apple Inc. build 5577)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.10.1
Scipy: 0.16.0
Matplotlib: 1.5.0
h5py: 2.5.0
...
========================================================================================== FAILURES ==========================================================================================
______________________________________________________________________________ test_inherit_constraints[model0] ______________________________________________________________________________

model = <CompoundModel11(amplitude_0=1.0, mean_0=0.0, stddev_0=1.0, amplitude_1=1.0, mean_1=0.0, stddev_1=1.0)>

    @pytest.mark.parametrize('model',
            [Gaussian1D(bounds={'stddev': (0, 0.3)}, fixed={'mean': True}) +
                Gaussian1D(fixed={'mean': True}),
             (_ConstraintsTestA + _ConstraintsTestB)()])
    def test_inherit_constraints(model):
        """
        Various tests for copying of constraint values between compound models and
        their members.
    
        There are two versions of this test: One where a compound model is created
        from two model instances, and another where a compound model is created
        from two model classes that have default constraints set on some of their
        parameters.
    
        Regression test for https://github.com/astropy/astropy/issues/3481
        """
    
        # Lots of assertions in this test as there are multiple interfaces to
        # parameter constraints
    
        assert 'stddev_0' in model.bounds
>       assert model.bounds['stddev_0'] == (0, 0.3)
E       assert (0.1, 0.5) == (0, 0.3)
E         At index 0 diff: 0.1 != 0
E         Use -v to get the full diff

miniconda3/envs/production/lib/python3.4/site-packages/astropy-1.1.dev14144-py3.4-macosx-10.5-x86_64.egg/astropy/modeling/tests/test_compound.py:759: AssertionError
______________________________________________________________________________ test_inherit_constraints[model1] ______________________________________________________________________________

model = <CompoundModel12(stddev_0=0.0, mean_0=0.0, mean_1=0.0)>

    @pytest.mark.parametrize('model',
            [Gaussian1D(bounds={'stddev': (0, 0.3)}, fixed={'mean': True}) +
                Gaussian1D(fixed={'mean': True}),
             (_ConstraintsTestA + _ConstraintsTestB)()])
    def test_inherit_constraints(model):
        """
        Various tests for copying of constraint values between compound models and
        their members.
    
        There are two versions of this test: One where a compound model is created
        from two model instances, and another where a compound model is created
        from two model classes that have default constraints set on some of their
        parameters.
    
        Regression test for https://github.com/astropy/astropy/issues/3481
        """
    
        # Lots of assertions in this test as there are multiple interfaces to
        # parameter constraints
    
        assert 'stddev_0' in model.bounds
>       assert model.bounds['stddev_0'] == (0, 0.3)
E       assert (0.1, 0.5) == (0, 0.3)
E         At index 0 diff: 0.1 != 0
E         Use -v to get the full diff

miniconda3/envs/production/lib/python3.4/site-packages/astropy-1.1.dev14144-py3.4-macosx-10.5-x86_64.egg/astropy/modeling/tests/test_compound.py:759: AssertionError
===================================================================== 2 failed, 486 passed, 34 skipped in 31.85 seconds ======================================================================
```

@embray @nden - it looks like there must be some internal state that gets preserved between runs?

Note also that ``--genscript`` has been deprecated in py.test:

https://github.com/pytest-dev/pytest/pull/884

So we may want to consider actually **removing** the bundled version and simply requiring py.test to be installed in order to run the tests. We could always consider this to be the last upgrade of the bundled version, and next time something breaks and requires a more recent py.test, we can then remove it?

### CODE REVIEW

**Comment by astrofrog** [comment]
Also, this is **not** 1.1-critical so should not be backported and should not hold up the final release.

**Comment by bsipocz** [comment]
thanks @astrofrog, i'll try this out to see how much of those extra 25 fails go away :)

**Comment by embray** [comment]
Well whatever the case this should be mentioned in the changelog for *some* release.

**Comment by embray** [comment]
(Or more specifically, should be explicitly targetted for a release.)

**Comment by bsipocz** [comment]
@astrofrog - When I run the full test suite twice with this PR, I still see 29 fails and 2 errors.

**Comment by astrofrog** [comment]
Yeah, this is very much a work in progress - it actually creates more failures than it fixes. I don't have time to investigate that this week, so if someone would like to take this over, please feel free to (but this is not 1.1 critical and there is no actual bug in the astropy code)

**Comment by astrofrog** [comment]
@embray - could you review the changes to the pytest plugins since I think you are familiar with them?

@bsipocz - can you check if this fixes your original issue?

**Comment by bsipocz** [comment]
@astrofrog - Nope, it still fails even with your minimal example above (with the same failures).

**Comment by astrofrog** [comment]
There are still some failures that occur when the tests are run twice, but I've opened a separate issue for those: https://github.com/astropy/astropy/issues/4444 - in the mean time, it would be good to merge this PR once it passes, since it contains some fixes that are needed if testing affiliated packages with a recent version of ``py.test`` (the plugins need to include the updates).

**Comment by astrofrog** [comment]
@embray @eteq - this fixes most issues with running the tests twice. There are still a couple related to warnings, but can we go ahead and merge this in the mean time, since it is already an improvement? (and fixes #3499 and #4256)

**Comment by astrofrog** [comment]
The remaining failures are due to the fact that if you run the tests twice, the tests that ensure the deprecation warnings are raised (e.g. ``test_import_warning`` in various ``utils`` modules) don't appear the second time. However, ``resetwarnings`` is not the right approach since it resets all warning filters too. What's the best way to just make sure that the warning is raised a second time?

**Comment by eteq** [comment]
Agreed that it makes sense to merge this now.  I have a thought about the no-warnings-second-time problem that I'm going to investigate, but if I can't make it work I'll make an issue so that we can investigate it later.

There's some question here about backporting... My feeling is that this should only get backported if it actually fixes failures in the 1.0.x or 1.1.x - am I understanding right from the above that this fixes failures from double-invocation, but that it still runs fine on the standard ``python setup.py test``? Or is #4256 also happening with py3.5 on the older versions?

**Pull request merged**
