### PR TITLE
Correct Ci definition

### PR DESCRIPTION
**Pull request by registerrier**
Change defintion to  Ci = Bq * 3.7e10  instead of  Ci =  Bq / 3.7e10

### CODE REVIEW

**Comment by mhvk** [comment]
Ouch! Thanks for catching that. Could you add an entry in `CHANGES.rst` in the bug-fix section for 1.0? @astrofrog - is that section correct? Obviously would be nice to have in 1.2 as well...

**Comment by registerrier** [comment]
I added bug fix entry for v1.0.11 in CHANGE.rst

**Comment by astrofrog** [comment]
@registerrier - thanks! There is now a test failure that is due to an example in the documentation that needs updating:

```
316   >>> u.Hz.find_equivalent_units()
Differences (unified diff with -expected +actual):
    @@ -1,6 +1,6 @@
    -  Primary name | Unit definition | Aliases
    +  Primary name | Unit definition | Aliases
     [
       Bq           | 1 / s           | becquerel    ,
    -  Ci           | 2.7027e-11 / s  | curie        ,
    +  Ci           | 3.7e+10 / s     | curie        ,
       Hz           | 1 / s           | Hertz, hertz ,
     ]
```

in ``docs/units/equivalencies.rst``. Can you change 2.7027e-11 to 3.7e+10 in that example?

**Comment by astrofrog** [comment]
Thanks @registerrier!

**Pull request merged**
