### PR TITLE
Bug in u.quantity_decorator when using **kwargs

### PR DESCRIPTION
**Pull request by Cadair**
So the following code breaks the `u.quantity_decorator`:

```python
In [2]: import astropy.units as u

In [4]: @u.quantity_input(a=u.deg)
   ...: def funct(a, **kwargs):
   ...:     pass
   ...: 

In [5]: funct(1 * u.deg)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-5fb4e89adcc1> in <module>()
----> 1 funct(1 * u.deg)

/Users/ireland/sunpy/sunpy/util/unit_decorators.pyc in wrapper(*func_args, **func_kwargs)
     81 
     82                 # Get the value of this parameter (argument to new function)
---> 83                 arg = bound_args.arguments[param.name]
     84 
     85                 # Get target unit, either from decotrator kwargs or annotations

KeyError: 'kwargs'
```

I have written a test which demos this bug, but as yet have not yet come up with a fix.

ping @embray @mhvk @astrofrog

### CODE REVIEW

**Comment by embray** [comment]
I should add, it looks like this only happens *specifically* if no additional keyword arguments are specified (i.e. `kwargs == {}`), in which case it appears that it is not included in `bound_args.arguments`.  

We could fix this either by adding
```#python
if param.name not in bound_args.arguments:
    continue
```

or something like this at the beginning of the loop:

```#python
if param.kind in (Parameter.VAR_KEYWORD, Parameter.VAR_POSITIONAL):
    continue
```

since variable arguments are not supported by `quantity_input` as I understand it anyways.

**Comment by Cadair** [comment]
closes #3289.

@embray I added your second fix as it seemed less-catchally. I wonder if we should mention in the docs that `*args` and `**kwargs` can not be validated in the original function signature?

**Comment by embray** [comment]
That *might* be worth fixing, if we want to be able to support arguments in `quantity_input` that can only be supplied to the function via a var kwargs.  Otherwise I agree it should be clarified that the wrapped function should provide any quantity-like arguments explicitly in their call signature.

**Comment by Cadair** [comment]
@embray for now I just added a comment to the docstring about it.

**Comment by Cadair** [comment]
Final Review?

**Comment by embray** [comment]
Looks good--thanks!

**Pull request merged**
