### PR TITLE
BUG: Fix deprecated_renamed_argument not issuing warning when deprecated keyword with no new_name called as positional argument

### LINKED ISSUE #9914: deprecated_renamed_argument fails for a removed keyword (not solved: when it is called as positional argument)
**UPDATE:** It is still unsolved for when function below is called as `myfunc(1, 200)`.

<hr/>

`deprecated_renamed_argument` allows one to deprecate a removed keyword argument.  However, when doing so, the deprecated keyword cannot be set.  It is always given its default value:

```python
>>> from astropy.utils.decorators import deprecated_renamed_argument

>>> @deprecated_renamed_argument('b', None, '4.1')
>>> def myfunc(a, b=3):
>>>     print(a, b)
>>>     return

>>> myfunc(1, b=200)
1 3
WARNING: AstropyDeprecationWarning: "b" was deprecated in version 4.1 and will be removed in a future version.  [warnings]
```

The deprecated keyword value can be changed from the default if it is used as a positional argument, but in that case the deprecation warning is not raised:

```python
>>> myfunc(1, 200)
1 200
```

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address the remaining bug where if a keyword is deprecated using `deprecated_renamed_argument` without a replacement (`new_name=None`) and then it is *called* as a positional argument instead, no deprecation warning would show.

Fixes #9914

### CODE REVIEW

**Comment by bsipocz** [comment]
This all looks good, but I think there are still some issues around with the decorator. E.g, the test case `test(x=1, dummy=10)` should raise the error as the default `relax=False` is used, yet the warning is issued instead.

**Comment by pllim** [comment]
Hmm, thanks for checking. I'll investigate when I get a chance (later today or tomorrow).

**Comment by bsipocz** [comment]
OK, so let's have this in as it fixes issues already and do a follow-up for anything else.

**Comment by bsipocz** [comment]
Thanks @pllim!

**Comment by larrybradley** [comment]
Thanks, @pllim!

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/pull/9985#issuecomment-604546053 -- @bsipocz , the docstring says "relax" only applies when both old and new names are given. In the case where there is no new name, I think ignoring relax is the right thing to do. Otherwise, raising an error is effectively removing the old argument when you only want to deprecate. Do you agree?

```
    relax : bool or list/tuple thereof, optional
        If ``False`` a ``TypeError`` is raised if both ``new_name`` and
        ``old_name`` are given.  If ``True`` the value for ``new_name`` is used
        and a Warning is issued.
        Default is ``False``.
```

**Comment by bsipocz** [comment]
Yeah, you're right. My issue was that I worked with the assumption that `dummy` is the new arg name, but it's not: https://github.com/astropy/astropy/blob/master/astropy/utils/tests/test_decorators.py#L477

I'm terribly sorry for the noise.

**Comment by pllim** [comment]
No worries! 😃

**Pull request merged**
