### PR TITLE
TST: Update codecov workflow

### LINKED ISSUE #13192: TST: Coverage report upload failed
Same problem as spacetelescope/jdaviz#1277 

```
[...] ['error'] None of the following appear to exist as files: ./coverage.xml
[...] ['error'] There was an error running the uploader: Error while cleaning paths. No paths matched existing files!
```

@rosteen investigated this and concluded something is funky with the latest  [codecov uploader v0.2.0](https://github.com/codecov/uploader/releases/tag/v0.2.0) tagged about 8 days ago (at the time of original post). He inquired upstream at https://community.codecov.com/t/files-not-found-with-uploader-v0-2-0/3601 .

Until this is fixed, we basically do not have coverage check in the CI. If coverage is important to your PR, please run it locally for now.

### PR DESCRIPTION
**Pull request by pllim**
Patch similar to spacetelescope/jdaviz#1294 except we already use v3.

### Description

This pull request is to update codecov workflow in a similar manner as spacetelescope/jdaviz#1294 (except we already use v3).

Close #13192

xref codecov/uploader#750

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
`codecov/project Failing after 1s — 91.64% (-0.03%) compared to f2f44aa`

Yay, coverage is back. The stats might be wonky because it stopped running for a bit.

**Review by saimn — APPROVED** [review]
Yay, thanks @pllim !

**Comment by pllim** [comment]
@meeseeksdev backport to v5.0.x

**Comment by pllim** [comment]
@meeseeksdev backport to v5.1.x

**Pull request merged**
