### PR TITLE
Let Pandas Series work as redshift inputs

### LINKED ISSUE #15576: FLRW.luminosity_distance returns unexpected type
### Description

When calling `FLRM.luminosity_distance` with an instance of `pandas.Series` as the input, the output is another `pandas.Series` rather than an instance of `astropy.units.Quantity`. This is inconsistent with other similar methods, such as `comoving_distance` or `comoving_volume`.

### Expected behavior

`FLRM.luminosity_distance` should return an instance of `astropy.units.Quantity`.

### How to Reproduce

1. Install `astropy`, `scipy` and `pandas` using `conda`
2. Run the code snippet below and check the types of the outputs

```python
from astropy.cosmology import WMAP9 as cosmo
import pandas as pd
z = pd.Series([1, 2])
dl = cosmo.luminosity_distance(z)
print(type(dl))
dc = cosmo.comoving_distance(z)
print(type(dc))
vc = cosmo.comoving_volume(z)
print(type(vc))
```

On my system, this outputs

```
<class 'pandas.core.series.Series'>
<class 'astropy.units.quantity.Quantity'>
<class 'astropy.units.quantity.Quantity'>
```

### Versions

```
Linux-3.10.0-1160.71.1.el7.x86_64-x86_64-with-glibc2.17
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
astropy 5.3.4
Numpy 1.26.0
pyerfa 2.0.0.1
Scipy 1.11.3
# Matplotlib is not installed
```

### PR DESCRIPTION
**Pull request by nstarman**
Fixes #15576 

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by nstarman** [comment]
Ping @mhvk for what this ended up looking like in `aszarr`.

**Comment by mhvk** [comment]
Yes, makes sense. Still wish pandas just behaved better so this wouldn't be necessary. But as I don't use it much myself, I'm not likely to make a PR myself. Plus practicality can beat purity...

**Review by mhvk — APPROVED** [review]
Still slightly doubtful about the special-casing, but given that, the implementation looks nice, so approving.

**Comment by pllim** [comment]
Thanks!

**Pull request merged**
