### PR TITLE
added thomson scattering cross section to si units

### PR DESCRIPTION
**Pull request by dannygoldstein**
Self-explanatory.

### CODE REVIEW

**Comment by pllim** [comment]
1. Why 0.6652458734e-28 and not 6.652458734e-29?
2. Add a change log.

**Comment by mdboom** [comment]
Needs an entry in CHANGES.rst

**Comment by dannygoldstein** [comment]
1. Using the exact value of sigma_T as it appears [here](http://physics.nist.gov/cgi-bin/cuu/Value?sigmae).
2. Done.

**Comment by pllim** [comment]
Okay, I don't see anything controversial here. :+1: to merging when tests pass.

**Comment by embray** [comment]
Certainly no problem with adding this.  Though it makes me think there are countless other constants we could be adding easily.  I'm almost tempted to make the constants module into just a big text file, from which constants can be lazy-loaded on-demand (so that when you just need one of them it's not necessary to create Constant objects for *all* of them).

**Comment by mhvk** [comment]
Since this looks all OK, I was about to merge this, but then I wondered about internal consistency, since the thomson cross-section can be calculated from constants we have already:
```
n [3]: 0.6652458734e-28*u.m**2 - 8*np.pi/3.*(c.alpha*c.hbar/c.m_e/c.c)**2
Out[3]: <Quantity 9.45122676949322e-38 m2>
```
Fortunately, the result is consistent!

It does beg the question, though, on what to calculate and what to store (e.g., we don't have the radiation constant `a` but do have the stefan-boltzmann constant).

Anyway, this is probably best done in another issue...

**Comment by mhvk** [comment]
See #3843 for the broader issues raised here.

**Pull request merged**
