### PR TITLE
Revise incorrect equation docs in Sersic2D class

### LINKED ISSUE #10150: Error in documentation for Sersic2D
### Description

The equation 

Γ(2𝑛)=2𝛾(𝑏𝑛,2𝑛)
on 

https://docs.astropy.org/en/latest/api/astropy.modeling.functional_models.Sersic2D.html

is incorrect.  It should be Γ(2𝑛)=2𝛾(2n,𝑏𝑛).  

EDIT: Changed provided URL to point to `latest`.

### PR DESCRIPTION
**Pull request by allardbrain**
### Description

This pull request revises an incorrect equation in the docstring of the `Sersic2D` class. The correct equation is given on this web page:
http://ned.ipac.caltech.edu/level5/March05/Graham/Graham2.html

Screen Shot 2020-04-16 at 9 55 22 PM

Fixes #10150

### CODE REVIEW

**Comment by allardbrain** [comment]
I don't have the domain expertise required to double-check that the code in the `Sersic2D` class matches the new form of the equation. Could someone please let me know if the code was wrong as well, or was it just the docstring? Thank you!

**Comment by allardbrain** [comment]
I read through the changelog guidelines and this small docstring change doesn't seem to warrant a changelog entry. Please let me know if I'm wrong about that and I'll create one.

**Comment by pllim** [comment]
Thanks, @allardbrain ! 

Indeed, this does not need a change log. Unfortunately, you would need to squash your commits to get rid of the second merge commit.

Tip: You can add `[skip travis]` to your commit message since this patch only affects the documentation and we build the doc on CircleCI, not Travis CI.

**Comment by allardbrain** [comment]
Thanks @pllim, I will squash the commits tonight, skip the Travis check and push again 👍🏻

**Comment by eteq** [comment]
I had a quick look at the function itself and I can confirm that the answer in the *code* is the correct order. 

(As an example, if you do `scipy.special.gammainccinv(2*4, 0.5)` or `scipy.special.gammainccinv(2*1, 0.5)` following https://github.com/astropy/astropy/pull/10162/files#diff-8a9d1102e6dde5801e75446ee9be6144R2447,  you get the same answers for b_4 and b_1 as http://ned.ipac.caltech.edu/level5/March05/Graham/Graham2.html shows right under equation (4).)

**Comment by pllim** [comment]
@eteq , since you already did a due diligence of checking literature, do you want the honor of approving the PR if it looks fine by you? Thanks!

**Comment by allardbrain** [comment]
Hi @pllim I'm having a hard time working through the mess I made from a failed attempt to squash the commits and re-push. Is there any problem if I close this PR and submit a cleaner version?

**Comment by pllim** [comment]
@allardbrain , usually if possible, we prefer to stick with the same PR to keep all the comments/reviews in one place. Are you not able to do the following? If not, I'll be glad to help over at Astropy Slack ([see this link](https://www.astropy.org/help.html)).

1. Make a backup branch, just in case.
2. The following steps assuming your git history still has 2 commits like I see here.
3. `git rebase -i HEAD~2` (Follow instructions that pop up. Squash the second commit. Save and exit editor. Modify your commit message. Save and exit again.)
4. `git fetch upstream master` (or whatever you name the remote that points to this repo)
5. `git rebase upstream/master`
6. `git log` (make sure your branch now is only one commit beyond `upstream/master`)
7. `git status` (just in case)
8. If everything looks good: `git push -f origin master`

p.s. For future reference, please refrain from making PRs off your fork's `master` branch.

**Comment by allardbrain** [comment]
Hi @pllim and thanks very much for the detailed instructions. Sorry about this. I have some free time tonight and just sat down at the computer to try to sort this out. I'll reach out via Slack if needed, and will update here as well.

**Comment by bsipocz** [comment]
@allardbrain - feel free to ping me too on slack if needed, I'm in the same timezone as you :)

**Comment by allardbrain** [comment]
. . . definitely did not intend to close this. 

I think I cleaned most of the git mess up following some instructions sent via Slack by @pllim. I have a feature branch in my fork of astropy at `allardbrain/issue-10150-error-in-docs-for-sersic2D` that now contains only 1 commit (the one-line change).

What I did before was merge that feature branch into `allardbrain/master`, and then submitted the PR without squashing the 1 feature commit and the 1 merge commit. Turns out I should have squashed at that time. So, I'm going to stop here and wait for confirmation on next steps.

Do I merge my feature branch into my master branch, squash the commits, and then re-submit my master branch to this PR in order to reopen the PR?

Whew, I think the end is in sight... I can't even tell you how much I appreciate your patience with me!

**Comment by allardbrain** [comment]
@bsipocz Thank you! I will definitely remember that! I think I'm most of the way there now. (fingers crossed)

**Comment by bsipocz** [comment]
OK, so the workflow is that you have your feature branch, and open the PR to astropy/master from that branch, rather than to your own master branch (we even suggest to delete your master, as it's more a trailing branch than real master: https://docs.astropy.org/en/stable/development/workflow/development_workflow.html#delete-master).

I've just double checked, but unfortunately it seems that there is no way to change the branch for a PR. 
So there are two ways, one is to push/cherry-pick that commit to your master branch. (e.g. locally go to `issue-10150-error-in-docs-for-sersic2D` and then

`git push allardbrain HEAD:master` and then reopen this PR with the button at the bottom.

This is pretty hacky, so I would just say to go ahead and open a new PR, but now from your feature branch. As it's not super fresh any more, it won't pop up automatically on github any more, but you can select it manually:

https://github.com/astropy/astropy --> "New pull request" button --> " compare across forks" link --> select your fork from the "head repository" dropdown, and the branch from the "compare" dropdown.

It should now list the one commit, etc.

Doing the dropdown will end up generating this following link:

(https://github.com/astropy/astropy/compare/master...allardbrain:issue-10150-error-in-docs-for-sersic2D?expand=1)

**Comment by allardbrain** [comment]
Many thanks for your guidance, @bsipocz. I just re-submitted the PR for the issue (and re-read the contributing guidelines twice!!) I appreciate your patience.

**Pull request closed without merging**
