### PR TITLE
Update bundled WCSLIB to version 7.7

### LINKED ISSUE #11941: ANN: New WCSLIB 7.7 released
New WCSLIB release found.

Version: 7.7 (2021/07/12)

#### Change log

WCSLIB version 7.7 (2021/07/12)
-------------------------------

* C library

  - In disfree() and disset(), removed potential for double invokation
    of free() on allocated memory.  Reported by Cyril Richard.

  - In wcsutil_fptr2str(), fixed a bug reported by Ralf Palsa (with fix)
    that caused it to be overly enthusiastic in stripping leading zeroes
    off addresses of function pointers.

  - In wcspcx(), replaced variable length arrays will allocated memory
    (portability issue).  Reported by Mihai Cara with patch.

  - Fixed buglets in wcsbth() and linsize() uncovered by gcc 11.1.0.

  - Quelled inconsequential compiler warnings from gcc 11.1.0 concerning
    wcsmix() (function prototype in wcs.h), wcstrim(), wcseulexe(),
    wcsulex(), and wcsutrne().

  - Defined _POSIX_C_SOURCE appropriately in tprj2.c and tspc.c to get
    the function prototype etc. for nanosleep() from time.h.

* Fortran wrappers

  - Quelled numerous inconsequential compiler warnings from gfortran
    11.1.0.

  - Fixed minor bugs uncovered by gfortran 11.1.0 in test programs tdis2
    and ttab3.

* Utilities

  - Moved 'tofits' from ./C/test/ into the utilities directory as it's
    generally useful, and added usage (converted to man page).

    Also made it a bit smarter in dealing with ISO/IEC 8859 and UTF-8
    encoded byte streams, in particular translating non-breaking spaces
    into ordinary spaces.

* Installation

  - Two patches for configure.ac provided by Mos� Giordano:
    1. makes it possible to build the Windows library using the MinGW
       cross-compiler,
    2. makes the soname of the MacOSX library consistent with other
       Unix systems.

(For complete change log information, see https://www.atnf.csiro.au/people/mcalabre/WCS/CHANGES .)

### PR DESCRIPTION
**Pull request by dhomeier**
Fixes #11941 (EDIT: Removed quotes for proper linking.)

Sources pulled in unmodified from ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-7.7.tar.bz2

> WCSLIB version 7.7 (2021/07/12)
-------------------------------
>
> * C library
>
>  - In disfree() and disset(), removed potential for double invokation
    of free() on allocated memory.  Reported by Cyril Richard.
>
>  - In wcsutil_fptr2str(), fixed a bug reported by Ralf Palsa (with fix)
    that caused it to be overly enthusiastic in stripping leading zeroes
    off addresses of function pointers.
>
>  - In wcspcx(), replaced variable length arrays will allocated memory
    (portability issue).  Reported by Mihai Cara with patch.
>
>  - Fixed buglets in wcsbth() and linsize() uncovered by gcc 11.1.0.
>
>  - Quelled inconsequential compiler warnings from gcc 11.1.0 concerning
    wcsmix() (function prototype in wcs.h), wcstrim(), wcseulexe(),
    wcsulex(), and wcsutrne().
>
>  - Defined _POSIX_C_SOURCE appropriately in tprj2.c and tspc.c to get
    the function prototype etc. for nanosleep() from time.h.

And probably inconsequential:

> * Fortran wrappers
>
>  - Quelled numerous inconsequential compiler warnings from gfortran
    11.1.0.
>
>  - Fixed minor bugs uncovered by gfortran 11.1.0 in test programs tdis2
    and ttab3.
>
> * Utilities
>
>  - Moved 'tofits' from ./C/test/ into the utilities directory as it's
    generally useful, and added usage (converted to man page).
>
>    Also made it a bit smarter in dealing with ISO/IEC 8859 and UTF-8
    encoded byte streams, in particular translating non-breaking spaces
    into ordinary spaces.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Do we backport wcslib updates? I am guessing no...

**Comment by nden** [comment]
@pllim No, we don't. This will go in 5.0.

**Review by nden — APPROVED** [review]
LGTM. Thanks!

**Review by mcara — APPROVED** [review]
LGTM

**Review by mcara — CHANGES_REQUESTED** [review]
Actually, I believe you have something wrong with astropy version tag. When I install it - it says `astropy 0.1dev`

**Comment by mcara** [comment]
```
Successfully installed astropy-0.1.dev31689+g60ea08e
```
Probably this is without consequences. Going to approve this PR...

**Review by mcara — APPROVED** [review]

**Comment by pllim** [comment]
> astropy-0.1.dev31689+g60ea08e

Where do you see this? If it happens in your local checkout, remember to run `git fetch upstream --tags` before installing.

**Comment by dhomeier** [comment]
Thanks, also looks to me like there is some update with the tags missing locally. I remember at one point I believe VERSION_MAJOR > 4 was not recognised, but CI has 5.0.dev566+gd945846e1 as well.

**Comment by mcara** [comment]
@pllim `git fetch upstream --tags` suggestion solved the issue for me.

**Comment by mcara** [comment]
Thanks @dhomeier !

**Pull request merged**
