### PR TITLE
Fix wcsapi doctest failure with remote data

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address doctest failure in `wcsapi` as follows:

```
________________________ [doctest] docs/wcs/wcsapi.rst _________________________
139     <SkyCoord (FK5: equinox=2000.0): (ra, dec) in deg
140         [(266.97242993, -29.42584415), (266.97084321, -29.42723968)]>
141 
142 Similarly, we can transform astropy objects back - we can test this by creating
143 Galactic coordinates and these will automatically be converted::
144 
145     >>> from astropy.coordinates import SkyCoord
146     >>> coord = SkyCoord('00h00m00s +00d00m00s', frame='galactic')
147     >>> pixels = wcs.world_to_pixel(coord)  # doctest: +REMOTE_DATA
148     >>> pixels  # doctest: +REMOTE_DATA
Expected:
    [array(356.85179997), array(357.45340331)]
Got:
    (array(356.85179997), array(357.45340331))
.../docs/wcs/wcsapi.rst:148: DocTestFailure
```

Probably caused by #9678

**Note to reviewer: Check remote data test job that is allowed to fail.**

### CODE REVIEW

**Comment by bsipocz** [comment]
there is more where this was coming from

**Comment by pllim** [comment]
Oh, dear! Should have done a local test run. My bad.

**Comment by bsipocz** [comment]
Thanks @pllim!

**Comment by pllim** [comment]
All passed now.

**Pull request merged**
