### PR TITLE
Add Jinja2 to setup_requires since it is in fact required

### PR DESCRIPTION
**Pull request by embray**
We might also want to specify a minimum version?  I don't know if it much matters though since we're not requiring anything particularly fancy from Jinja2--any version from within the last several years probably ought to be good enough...

### CODE REVIEW

**Comment by embray** [comment]
This somehow resulted in coverage changes all over the place which doesn't make any sense.

**Comment by embray** [comment]
Rebased on master to include #4176

**Comment by matthew-brett** [comment]
I guess this isn't a big deal as long as there's nice error message.  The current Cython error message seems fine for the developer Cython dependency, for example.

**Comment by eteq** [comment]
@embray - I know this is an old issue... but is the content of it still relevant? I may be mistaken but it looks like the helpers machinery now does something for Cython so that it can be in setup_requires but still be installable if the cython is generated... am I reading that right?

(Similarly, @matthew-brett is asking about `jinja2` via #5090)

**Comment by embray** [comment]
@eteq Well, if I'm reading you right, yes I did some work in astropy_helpers some time ago to make it possible to use Cython with setup_requires.

So this is still relevant, because I think it's good to `setup_requires` Jinja2 and Cython, but *only* when building from the git repository.  The source tarball should already include all generated C sources, and thus not have these build requirements.

So what the setup.py needs is some way to check whether or not it's running out of the git repository (I think checking for `.git` should suffice) and only include `['Jinja2', 'Cython']` in `setup_requires` in that case.

**Comment by astrofrog** [comment]
> (I think checking for .git should suffice)

I'm not sure - what about if the user downloads a zip file of the repo from GitHub?

**Comment by bsipocz** [comment]
@astrofrog - I wonder how many users would run into that issue as the github zips are not the official releases, at least the docs points to use the source tarball from pypi.

**Comment by astrofrog** [comment]
@bsipocz - I guess what I mean is that some people might use the download zip functionality to get the latest developer version, in which case we should treat it as a developer not a stable version. Presumably we can just check the version number and see if there is a 'dev' in it?

**Comment by bsipocz** [comment]
Ahh, ok I see. They shouldn't do that, but even then your suggestion works. Check for either ``.git`` and ``dev`` in version to be safe?

**Comment by astrofrog** [comment]
@bsipocz - yes - if either dev or .git are present, we should assume it's a developer version and not a tarfile release.

**Comment by evertrol** [comment]
For the record: another use case I ran across where this is an issue is with `pip install git+https://github.com/astropy/astropy.git`. Looks like this PR will take care of that as well.
(My reason for installing from and using the current master is for bug-fixes; it's nicer than to work around them.)

**Comment by pllim** [comment]
This PR has been opened for 3 years and now there is a conflict. And since if user install dev version, then can just grab dependencies from `pip-requirements-dev`, I am closing this PR. Open a new one if someone else wants to pursue this.

**Pull request closed without merging**
