### PR TITLE
Allow passing of tuples for setting constraints on model parameters

### PR DESCRIPTION
**Pull request by anchitjain1234**
For #3028.

### CODE REVIEW

**Comment by anchitjain1234** [comment]
Please review.

**Comment by eteq** [comment]
@anchitjain1234 - this needs a changelog entry as it's a new feature.

@astrofrog or @nden or @embray - this looks good to me, do you agree it doesn't conflict with intended future plans (aside from the possibility of some of the major changes discussed at the pyastro16 conference)?

**Comment by anchitjain1234** [comment]
@eteq added changelog entry in New Features

**Comment by astrofrog** [comment]
@nden - I'm -0.5 on this change - doesn't it then make assumptions about the order of the parameters?

**Comment by nden** [comment]
@astrofrog Yes, this relies on the user supplying the constraints in the same order as the parameters, (e.g. by looking at `model.param_names`). So it doesn't add much convenience in the general case but requires supporting another interface. This may be a concern now that we are planning to use models with sherpa. (-0.75 from me.)

**Comment by bsipocz** [comment]
@astrofrog @nden - Have you changed your minds about this, or shall we close?

**Comment by bsipocz** [comment]
I'm closing this now due to the concerns above and inactivity.

**Comment by kakirastern** [comment]
Now that dictionaries are "order-preserving" or insertion-ordered in Python 3.6+, maybe it's time for a redux? Will follow up soon. 

Sources: 
1. [https://docs.python.org/3.6/whatsnew/3.6.html#new-dict-implementation](https://docs.python.org/3.6/whatsnew/3.6.html#new-dict-implementation)
2. [https://mail.python.org/pipermail/python-dev/2017-December/151283.html](https://mail.python.org/pipermail/python-dev/2017-December/151283.html)

**Comment by nden** [comment]
The next astropy release will still support python 3.5 accorindg to [this](https://github.com/astropy/astropy-APEs/blob/master/APE10.rst).

**Comment by kakirastern** [comment]
Thanks, @nden! I appreciate the heads-up. Reckon there must be some workaround available... (Maybe with the help of something like Python 3.x's `OrderedDict` to support the usual `dict` methods.) Will think about this some more soon.

**Comment by kakirastern** [comment]
Is this still wanted as a feature in `astropy`? If it is, I can try again to tackle the problem and open another PR again to add this to the code base. But I need concrete feedback.

**Comment by nden** [comment]
Hi @kakirastern! Sorry for not looking at the PR earlier - everything was on hold until the core was reworked.
I think this feature is still desirable as it will make model initialization simpler. Let's wait a couple of days to see if there are other opinions.

**Comment by kakirastern** [comment]
Hi @nden Thanks for the prompt response! No worries, I can wait until a more opportune time until the core has been reworked. I don't mind redoing everything again in order to add this feature to the code base.

**Pull request closed without merging**
