### PR TITLE
Define more parameter defaults for models

### PR DESCRIPTION
**Pull request by embray**
Since at least 0.4 (and I think earlier) it has been possible to define defaults for the parameter values on any model.  But only a tiny handful of the built-in models currently take advantage of this (the polynomial models in particular set all coefficients to 0 by default, so that only the required coefficients need to be provided on instantiation).

However, I think that many if not most of the built-in models could have sensible defaults for at least some of their parameters (for example most of the models with an "amplitude" parameter could have it default to 1).

Having more parameter defaults could also be very helpful for compound models, where it becomes necessary to provide a large number of parameter values on instantiation.  If more of those parameters had defaults it would make instantiating those models simpler (it is still always possible to update a model's parameters after it has been instantiated, which may be clearer in some cases anyways).

Models that could use defaults for some or all of their parameters include:

* [x] [`Gaussian1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L31)
* [x] [`GaussianAbsorption1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L121)
* [x] [`Gaussian2D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L171)
* [x] [`Shift`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L349)  (offsets=0?)
* [x] [`Scale`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L379) (factors=1?)
* [x] [`Redshift`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L405) (z=0?)
* [x] [`Sine1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L446)
* [x] [`Linear1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L492)
* [x] [`Lorentz1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L538)
* [x] [`Const1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L590)
* [x] [`Const2D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L630)
* [x] [`Disk2D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L663)
* [x] [`Ring2D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L713)
* [ ] [`Delta1D/2D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L779) (these need to be implemented, period--though how would these be useful outside integration?)
* [x] [`Box1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L793)
* [x] [`Box2D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L850)
* [x] [`Trapezoid1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L909)
* [x] [`Trapezoid2D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L959)
* [x] [`MexicanHat1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L1004)
* [x] [`MexicanHat2D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L1048)
* [x] [`AiryDisk2D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L1096)
* [x] [`Beta1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L1185)
* [x] [`Beta2D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/functional_models.py#L1241)
* [x] [`PowerLaw1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/powerlaws.py#L20)
* [x] [`BrokenPowerLaw1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/powerlaws.py#L73)
* [x] [`ExponentialCutoffPowerLaw1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/powerlaws.py#L141)
* [x] [`LogParabola1D`](https://github.com/astropy/astropy/blob/master/astropy/modeling/powerlaws.py#L200)
* [x] [`Pix2Sky_CYP`](https://github.com/astropy/astropy/blob/master/astropy/modeling/projections.py#L341)
* [x] [`Sky2Pix_CYP`](https://github.com/astropy/astropy/blob/master/astropy/modeling/projections.py#L381)
* [x] [`EulerAngleRotation`](https://github.com/astropy/astropy/blob/master/astropy/modeling/rotations.py#L33)

Above I've listed all models that have parameters without defaults.  I don't have experience with how all of these are used in practice so I don't know whether or not it makes sense to set defaults for all of them, or what those defaults would be.  There are others that I think are pretty obvious.

If you think it makes sense to, please add some defaults to the list either by editing this list or commenting below.

### CODE REVIEW

**Comment by astrofrog** [comment]
@embray - what is the status of this, shall we postpone until after 1.0?

**Comment by embray** [comment]
I'd actually like to include this if no one objects.

**Comment by embray** [comment]
Rebased this.  I think there were some decent arguments against this, but I also feel that the benefits outweigh the potential hazards.  I think if anyone wants to suggest better defaults for specific models they can do so as the need arises...

**Comment by mhvk** [comment]
@embray - looking at this again, I think I still prefer only allowing defaults for offsets, scales, and rotations, but I do now realise the case I was most worried about, where one starts to use quantities in models, is not a real worry: evaluating a model with unit-full parameters left to their unitless default will automatically raise `UnitsError`. Since with that the future is safe for the case I care about, I'm fine with merging this.

**Comment by embray** [comment]
Why would it necessarily raise a `UnitsError`?  Some cases might work, some might not.  Though you're more likely to get a result in the wrong units.

**Comment by mhvk** [comment]
I was thinking specifically about the case of `a*sin(2*np.pi*f*x)` where as long as `x` has, e.g., a unit of `s`, one would get a `UnitsError` in the evaluation, and similarly one would get an error if whatever is fitted had, say, a unit of `Jy`. True that it might not be quite fool-proof, but probably good enough.

**Comment by embray** [comment]
Right, I think on a certain level the goal is not to be 100% fool-proof.  If we claimed to be that would be more dangerous than if we didn't--people should still always check their results.

**Comment by embray** [comment]
Going once...   going twice....

**Comment by astrofrog** [comment]
@embray - looks good, feel free to merge!

**Comment by embray** [comment]
Will do. Just needs a changelog entry.

**Comment by astrofrog** [comment]
@embray - just a reminder that this is good to go modulo a changelog entry

**Comment by embray** [comment]
Added a changelog entry (and then quickly amended to add `[skip ci]`--woops)

**Pull request merged**
