### PR TITLE
Add function `cosmology_equal` 

### LINKED ISSUE #12781: equality comparison method on Cosmology
Method ``.is_equal`` (or something similar) that allows for equality comparison to include MetaData.

### PR DESCRIPTION
**Pull request by nstarman**
### Description

A new method ``is_equal`` is added to more extend Cosmology equality (by the
standard operator ``==``). ``is_equal`` allows for the metadata to be included
in the equality check and also adds the keyword argument ``format`` so that
any Python object that can be converted to a Cosmology may be checked for
equality.

Fixes #12781 

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by mhvk** [comment]
Just a random thought: would an `is_close` with tolerances be a broader, possibly more useful method? As is, it feels a little redundant, in being quite easy to do directly -- which suggests most people will just do it directly and never even know the method exists...

**Comment by nstarman** [comment]
> would an `is_close` with tolerances be a broader, possibly more useful method?

Yes, definitely. I very much want to add such a method. However, I don't actually know what "close" means for a cosmology.
Just consider ``Ode0`` versus ``Om0`` in $E(z) = \sqrt{\Omega_M(1+z)^3 + ... + \Omegą_\Lambda}$. Distance measures and other cosmological properties can be very sensitive to different parameter values. And what about including ``H0`` or dark energy parameters? I just don't know what a good distance metric is in the space of cosmological parameters.

**Comment by mhvk** [comment]
I guess somewhat naively I was thinking of just the parameters being close, but I guess more realistically it would have to be at least the evolution of the scale parameter being the same within some tolerance. Which would no longer be simple.

I'm still not convinced about the need for `is_equal` - apart perhaps for testing, but then why not have it as part of the test suite (like `np.testing.assert_array_equal`)?

**Comment by nstarman** [comment]
> I'm still not convinced about the need for `is_equal` - apart perhaps for testing, but then why not have it as part of the test suite (like `np.testing.assert_array_equal`)?

Testing was the original motivation, so moving ``is_equal`` to the test suite is fine by me. The ``format`` conversion is definitely nice, but I agree ``is_equal`` is much less useful than ``is_close``.

**Comment by nstarman** [comment]
Failure in https://dev.azure.com/astropy-project/astropy/_build/results?buildId=4080&view=logs&j=097319b1-31d0-56fb-5726-391666f05beb&t=4d95e143-bd9c-5299-d00f-22de2f2fac45 is real. And a little mystifying.

**Comment by nstarman** [comment]
@astropy/testing-infrastructure-maintainers, is there a way to look more deeply in the azure tests? I'm trying to diagnose a problem, but I don't have access to any x86 64bit machines.

**Comment by nstarman** [comment]
I'm going to wait until #12925 is in to fix this PR up.

**Comment by nstarman** [comment]
I'm closing this in favor of implementing equality in the context of ``array_ufunc`` numpy overrides.

**Pull request closed without merging**
