### PR TITLE
String-related fixes for FITS tables

### PR DESCRIPTION
**Pull request by embray**
This PR fixes a number of string-related issues with FITS tables, especially (but not limited to) Python 3.

This was originally motivated primarily by #3854, and does get all the existing io.fits tests passing when run with Numpy 1.10.  However, this required fixing a number of bugs that only started showing up in the tests with Numpy 1.10, but were in many cases real bugs in their own right.  It ended up making the most sense to fix them all together, since most of them were related.

* One thing particular to Numpy 1.10 is that the recarray class was changed so that string fields are no longer returned as `chararray` objects (just normal string arrays).  However, there are several areas in which pyfits, and subsequently `astropy.io.fits` still rely on the `chararray` class for its behavior of automatically rstripping strings returned from the array (this is relevant for FITS, which dictates that trailing spaces in strings should be ignored).  This ensures that `chararray` usage is preserved for now, for backwards compatibility, until another solution can be provided.

* This also fixes a bug which I have noted before, but can't for the life of me find an open issue for (I thought I made one, but maybe only mentioned this in comments somewhere...)  The bug is that when writing an Astropy `Table` out to FITS with `Table.write()`, if the table contained string columns those columns are most likely represented as unicode arrays on Python 3.  When writing to a FITS file the unicode was still converted properly to ASCII, but it kept the original width of the unicode arrays.  So for example a column of single character strings was written to FITS as a four character column.  Getting around this is a bit of a hack for now, and results in slower write times, but at least has the correct behavior.  All the more reason for a type of "ASCII only 'unicode'" array.

* Despite the above bullet point, this also improves performance of string writing  in some cases, in that it requires less memory for encoding unicode arrays as ASCII, due to a new `_ascii_encode` function which is improved over `np.char.encode` in that it can write to an existing output array.  This results in lower peak memory usage when writing out character arrays in some cases.

* Removed the unfortunate monkey-patching of the `chararray` class in Numpy >= 1.10, where the issue that prompted that patching is now fixed :grinning:

### CODE REVIEW

**Comment by embray** [comment]
Having Numpy 1.10 support is important, so I've added v1.0.6 as the milestone for this.  It would be nice to release v1.0.6 in conjunction with 1.1 so that both Astropy versions have Numpy 1.10 support concurrently.  Otherwise this can be fixed in Astropy 1.1 first, with a note in the v1.0.6 changelog that it will be fixed there too.

**Comment by astrofrog** [comment]
@embray - a simultaneous release would be nice, and to be honest this alone would be a good justification for 1.0.6.

**Comment by embray** [comment]
Yeah--there are some other things that could slip in to v1.0.6.  It's not a big deal to release it either way (at least as long as all the build issues I was having with 1.0.5 stay fixed...)

**Comment by mhvk** [comment]
@embray - had a look to the best of my ability, and think this is all OK. Nice to see you just using the proper way to view rather than my quick hack!

**Comment by embray** [comment]
@mhvk I actually did put in your version but it ended up making no difference--looks like i had already fixed all the issues related to that.

**Comment by embray** [comment]
Oops, causing a small issue on Numpy 1.9.  Should have that fixed in a jiffy...

**Comment by embray** [comment]
Ah, only occurs on Windows. That's why I missed it.

**Comment by mhvk** [comment]
Apart from the false positive for coverage, this looks all good. Thanks, @embray! (Not merging yet as I'm not quite sure whether others want to have a look, and how to do the transfer to 1.1.)

**Comment by embray** [comment]
Coverage did drop in one file in a relevant manner, but that's because it's code that's *normally* only run on Python 3.  It would be nice if we could collect coverage for Python 3 too.

I'm going to write one additional test that should cover that code on both Pythons.  Really I should have added such a test in the first place.

**Comment by astrofrog** [comment]
We could simply enable coverage testing on all builds - that's what I normally do in other packages, and I think it combines them all.

**Comment by embray** [comment]
Hmm. Coveralls thinks that the [`_ascii_encode`](https://github.com/astropy/astropy/pull/4228/files#diff-703b4b625a97b7b26058e3e859bfe8d8R1223) function still isn't being covered, and that's what I hoped *would* be tested by the test I added in 5224152 .  I'm somewhat bewildered how it could not be covered by that test so I'm going to try a few things locally first...

**Comment by embray** [comment]
Trying to figure out why that test wasn't covering the cases that I thought it was led me to discover something of a bug, which means in part that this fix isn't making the performance improvements it promises.

If this ends up holding things up for too long we can go ahead and merge, because in terms of overall behavior it's correct, and it does fix several bugs and fix Numpy 1.10 support which we need to get out ASAP.  But I want to spend a little more time on this...

**Comment by mhvk** [comment]
OK, hope you'll figure it out! And very nice to see numpy 1.10 supported!

**Comment by mhvk** [comment]
@embray - what do you think, shall we merge this as is, or do you think you'll have a solution ready very soon? I ask because we're now getting reports mentioning astropy tests are broken by numpy 1.10 (#4247)...

**Comment by embray** [comment]
I'm not *too* worried about such reports.  It's already been documented as a known issue so people who search ahead of time can find that.  Definitely want to spend some more time on this today.

**Comment by embray** [comment]
Huh. Strange about the latest test failures.  It worked locally.

Anyways, it turns out that what I really wanted to do to fix this all properly ended up going down a rabbit hole of everything that's wrong with the old FITS table implementation.  I've actually made some real progress on improving things there but it's going to take more time and I need to get this release out before I go on vacation.  So I'll get this last test fixed and then merge this.

**Comment by mhvk** [comment]
OK, sounds good.

**Comment by embray** [comment]
Okay, the test failure was really only on Python 2, which I sort of expected.  It doesn't actually fail on Python 3, but there was something wrong with the build where it ran the Python 3 tests on Python 2.  Hopefully that was just a temporary issue...we'll see...

**Comment by embray** [comment]
Trying to get the Windows build to run again...for some reason last time the Python 3 test ran fine, but the Python 2 test hanged for no apparent reason.

**Pull request merged**
