### PR TITLE
Add clarification note on CompoundModel

### LINKED ISSUE #13534: `CompoundModel` sub-model `setattr` issue
### Description

If you add a model to itself and make a new `CompoundModel`, `CompoundModel` does not seem to make copies of the input models before it "combines" them. This is because when you use:

```
setattr(compound_model, param_name, new_value)
```

The param for both models is changed for both instances of the sub-models even if they have different names (i.e "param_name_0" and "param_name_1"). 

### Expected behavior

Setting one param should not cause another to change. 

### Actual behavior

Setting one param in a compound model causes duplicated sub-models to change their params 

### Steps to Reproduce

```
from astropy.modeling import models

model = models.Gaussian1D()
compound_model = model + model
setattr(compound_model, 'mean_0', 10)
```

This will cause both `mean_0` and  `mean_1` to equal `10` though they were initialized to 0!

Please note that even doing the following is not exempt from this error, indicating the issue is not with the `setattr` call

```
compound_model.mean_0 = 10
```

### System Details

```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:06:46) [GCC 10.3.0]
Numpy 1.23.1
pyerfa 2.0.0.1
astropy 5.1
Scipy 1.9.0
Matplotlib 3.5.2
```

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

Adds clarification note to the `CompoundModel` documentation on how neither models nor their parameters are copied when creating a `CompoundModel`.

Fixes #13534

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
@robelgeda does the note added here clarify things for you?

**Review by perrygreenfield — APPROVED** [review]
Perfect.

**Review by pllim — COMMENTED** [review]
I'll defer to @robelgeda .

**Review by robelgeda — APPROVED** [review]
Thank you so much @WilliamJamieson !

**Pull request merged**
