### PR TITLE
Added doc on prefix under units 

### PR DESCRIPTION
**Pull request by ritwickdsouza**
@pllim I am submitting another pull request since i made changes to the master in the previous one, this one is from a branch. I am closing the previous pull request (#5648). References #5511

### CODE REVIEW

**Comment by ritwickdsouza** [comment]
Any changes which needs to be made for this PR ?

**Comment by pllim** [comment]
@ritwickdsouza , the failure is unrelated, so I think this is ready for review. The `units` maintainers, @mhvk and @adrn , will have decide whether to accept #5647 or this one.

**Comment by mhvk** [comment]
@ritwickdsouza - thanks for the PR. I had a comment about the text, but thought it was easier to just edit the file myself. As your PR did not seem to allow this, I just made a new one (#5683) that builds on your work (though with the three commits squashed together). I'll merge that if the tests pass, and close this PR now.
Thanks for the contribution!

**Comment by ritwickdsouza** [comment]
@mhvk Alright. :)

**Pull request closed without merging**
