### PR TITLE
Remove duplicate call to update_header

### PR DESCRIPTION
**Pull request by saimn**
See https://github.com/astropy/astropy/pull/5053/files#r66576117

I stumbled upon this while looking at #5559, `update_header` is called twice (it is called in the `.data` setter).

### CODE REVIEW

**Comment by bsipocz** [comment]
Is this backportable?

**Comment by saimn** [comment]
Most likely yes, it is just one line, and #5053 came in v1.2 so it should be fine to backport to 2.0.

**Comment by pllim** [comment]
Tests passed but :grimacing:

**Comment by pllim** [comment]
@saimn , you marked this as refactoring, not a bug. Generally speaking, we don't backport "refactoring". And if this is a bug, please update the labels and add a change log entry. Thanks!

**Comment by saimn** [comment]
@pllim - This is not a bug for me, there is no issue caused by this, so I'm fine with not backporting.

**Comment by MSeifert04** [comment]
I agree with the not-backporting. Just in case (this is io.fits after all) this has some weird edge cases where it breaks some code.

I think this is fine.

**Comment by pllim** [comment]
> I think this is fine.

@MSeifert04 , do you want to formalize it and hit "approve"? :smile:

**Comment by MSeifert04** [comment]
Maybe we could leave a bread-crump comment there that the data setter actually updates the header? This is completely optional, just to avoid potential confusion?!

**Comment by saimn** [comment]
I updated the comment just above.

>  just to avoid potential confusion?!

Maybe, but I love how the comment says that bitpix/bscale/bzero will be updated when setting the data, and just after it sets again those values in case they changed :grimacing:

**Comment by pllim** [comment]
:crossed_fingers: :crossed_fingers: :crossed_fingers:

**Pull request merged**
