### PR TITLE
Backport PR #11756 on branch v4.3.x (Fix install_requires and remove requires)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #11756: Fix install_requires and remove requires

### CODE REVIEW

**Comment by pllim** [comment]
@saimn , @bsipocz , @eteq , or @astrofrog -- Should we apply a special label, like using the `Manual backport` label, or is filtering by author here enough to smoke all the bot backport PRs out?

**Comment by pllim** [comment]
The RTD failure is probably because we didn't pin Sphinx in the release branches.

**Comment by embray** [comment]
I don't know that a special label is needed

> The RTD failure is probably because we didn't pin Sphinx in the release branches.

Shouldn't we?

**Comment by bsipocz** [comment]
Yes, the sphinx limit should go back, but of course this PR is the first backport. An experiment could be to make another backport for the sphinx, and see how easily can we make this one pass CI. I suppose we need to manually rebase this.

**Comment by bsipocz** [comment]
Re label: I think we need to recheck the logic of the release script. I would not call this `Manual backport` but something else, but I think it's best to figure out the logic whether to label before backport, or after successful backports during the infra call. 
Also, I wonder whether the changelog files are renamed during the backport? I think they should be, or at least also list the backport PR number not just the original.

**Comment by pllim** [comment]
Re: Sphinx pin -- I thought it would resolve itself with `sphinx` 4.0.2 but unfortunately not (astropy/sphinx-automodapi#130). I dunno if we should try to fix the sphinx problem or pin it. Pinning comes back and bites us some times. Choose your poison!

**Comment by eteq** [comment]
I'm going to merge this and take care of the sphinx pinning directly in v4.3.x .

**Pull request merged**
