### PR TITLE
fix bug with compound model inverse serialization

### PR DESCRIPTION
**Pull request by nden**
### Description

This pull request is to address a problem with serialization of compound models when only one of them has a custom inverse. In this case the inverse was not written to file.

```
m1 = Polynomial1D(1) & Polynomial1D(1)
m2 = Polynomial1D(1) & Polynomial1D(1)
m1.inverse = m2
m = Shift(1) & Shift(2) | m1
fa = AsdfFile()
fa.tree['model'] = m
fa.write_to('model.asdf')
f = asdf.open('model.asdf').tree['model'].inverse
>           raise NotImplementedError("Inverse function not provided")
E           NotImplementedError: Inverse function not provided

```

### CODE REVIEW

**Comment by pllim** [comment]
PEP 8:
```
astropy/io/misc/asdf/tags/transform/tests/test_transform.py:31:1: W293 blank line contains whitespace
astropy/io/misc/asdf/tags/transform/tests/test_transform.py:54:1: W293 blank line contains whitespace
```

**Comment by pllim** [comment]
cc @jdavies-st

**Comment by nden** [comment]
I am still looking into related issues - should not be merged yet.

**Comment by hbushouse** [comment]
This is a high-priority fix that's needed to support JWST DMS B7.4. Currently there are some WCS objects that contain compound models that are not serializing properly, with inverse transforms being absent in the serialized file. This obviously causes problems downstream when those corrupt data files are used as input to routines that need all the WCS transforms.

**Comment by jdavies-st** [comment]
I did some further testing of the `asdf` serialization with this branch, and it resolves all the issues we've been seeing.  👍

**Comment by nden** [comment]
Squashed commits and cancelled the jobs I can cancel. Merging. Thanks all!

**Pull request merged**
