### PR TITLE
Test docs on AppVeyor

### PR DESCRIPTION
**Pull request by MSeifert04**
Just a test regarding `build_docs` on AppVeyor.

### CODE REVIEW

**Comment by MSeifert04** [comment]
why is the only build that hasn't started AppVeyor 😞

**Comment by astrofrog** [comment]
@MSeifert04 - just for info you could do ``[skip travis]``

**Comment by MSeifert04** [comment]
@astrofrog I totally forgot that existed. 😅

**Comment by MSeifert04** [comment]
Hm, can I somehow remove the `conda` version pinning?

**Comment by bsipocz** [comment]
@MSeifert04 - Use the variable CONDA_VERSION

**Comment by MSeifert04** [comment]
Okay, also fails here. Gives even less output than my computer but the error message 

```
Sphinx Documentation subprocess failed with return code 3221226505
Command exited with code 1
```

seems to indicate it's not related to my computer. Puh 😅

**Comment by astrofrog** [comment]
Would it be worth adding this as a permanent build on AppVeyor? (which isn't usually a bottleneck these days)

**Comment by MSeifert04** [comment]
I'm not really sure, the one build with conda x.21 had several hundred warnings, the one with x.27 segfaulted and it takes quite a while (possibly making AppVeyor problematic again) and it relies on remote-data which makes it flaky.

**Comment by mingwandroid** [comment]
Any chance of testing with this new package?:

`conda update -c c3i_test2 libpng`

**Pull request closed without merging**
