### PR TITLE
Fix bug 12082 where can't set constants version

### LINKED ISSUE #12082: Cannot use older versions of constants
### Description
The documentation describes how to use an older set of physical constants. I tried to follow this example: https://github.com/astropy/astropy/blob/8f1ae4eb61aee209911234883e462fe0addffeca/docs/units/constants_versions.rst#L16-L21

### Actual behavior

This is what happens since d54a9a360042a8083583ce8ed62bb1adf6448ef7:
```python
>>> import astropy
>>> astropy.physical_constants.set('codata2010')
Traceback (most recent call last):
...
TypeError: set() takes 2 positional arguments but 3 were given
```

### Expected behavior 

This is how it worked in 169fd6e6ec17dfcb91ecee0525d96228556c97ca (the parent of d54a9a360042a8083583ce8ed62bb1adf6448ef7):
```python
>>> import astropy
>>> astropy.physical_constants.set('codata2010')
<ScienceState physical_constants: 'codata2010'>
```

I am not sure if d54a9a360042a8083583ce8ed62bb1adf6448ef7 introduced a bug or if it's the documentation that needs to be updated, but having a completely broken example in the docs is not good either way.

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

Fixes #12082

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Alas, I don't think we can test this in CI, now that I remember an old discussion on why that code was skipped in doctest. If someone else is reviewing, please test manually in a Python session. If not, hopefully I can get to this soon. Thanks for the quick fix!

Will need a change log.

**Comment by nstarman** [comment]
Hmm. now we need a test. Problem is that it requires a clean import of astropy, without the units module imported. @mhvk, do you have any monkeypatch magic that can do this?

**Comment by pllim** [comment]
Re: test -- See #8781

**Comment by nstarman** [comment]
Hmm. That's a whole can of worms

**Comment by nstarman** [comment]
re-pushed for changelog. Barring a test, which should maybe be punted yet again, 🤞, done?

**Review by mhvk — APPROVED** [review]
@nstarman - thanks for the quick fix! I think that sometimes we just have to live with not having an explicit test - and this seems particularly tricky to test: I guess it would need a specific importing of astropy just to test this example only. So, my sense is just to merge this as is! (I assume you checked that it worked locally!)

**Comment by nstarman** [comment]
Screen Shot 2021-08-18 at 17 25 22

**Pull request merged**
