### PR TITLE
MNT: improve bug report template (environment report)

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
Upstreaming the fixes I always end up doing manually on my bug reports.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by eerovaher** [comment]
Would it be a good idea to implement a little helper function in `astropy` so that the requested version information could be produced with a single function call?

**Comment by Cadair** [comment]
For what it's worth sunpy has this: https://github.com/sunpy/sunpy/blob/main/sunpy/util/sysinfo.py#L131

**Comment by neutrinoceros** [comment]
`pandas` has `pandas.show_versions()` and `numpy` has `numpy.show_runtime()`

**Review by pllim — APPROVED** [review]
Looks reasonable. Thanks!

**Comment by pllim** [comment]
Yes, dedicated function is out of scope here. And that in itself would probably invite debates as usual, so definitely open a new issue if you are interested to pursue it.

**Pull request merged**
