### PR TITLE
MNT: Remove deprecated pytest_plugins

### LINKED ISSUE #7782: Timeline for removal of deprecated astropy.tests.pytest_plugins
Importing from `astropy.tests.pytest_plugins` was officially deprecated in the 3.0 release, but has been maintained for backwards compatibility (see #6606 and specifically c16c2fa). 

However, the discussion on https://github.com/astropy/pytest-doctestplus/issues/22 seems to indicate that imports of the form `from astropy.tests import pytest_plugins` are definitively broken with recent versions of `pytest`.

This raises a question: should we move forward with the removal of the `astropy.tests.pytest_plugins` submodule earlier than we would for other deprecations?

cc @nicoddemus

### PR DESCRIPTION
**Pull request by pllim**
Fix #7782

It needs some consensus w.r.t. milestoning.

**TODO**

- [x] Add change log when milestone is decided.

### CODE REVIEW

**Comment by bsipocz** [comment]
Hmm, I lost track for the conclusion here. Should we remove the deprecation in 3.1 or wait until the next LTS? In either way I add the most conservative milestone now (not being in a milestone is dangerous, as we more likely overlook it), but feel free to move it closer.

**Comment by drdavella** [comment]
I think this needs to wait for the next LTS since it was only deprecated in 3.0.

**Comment by drdavella** [comment]
To provide an updated opinion: I'm okay with doing this ASAP since doing otherwise means we will be constrained to use `pytest<4.0` for quite a while. However, I don't want to move ahead with this unilaterally, so someone else should weigh in.

**Comment by pllim** [comment]
cc @astropy/coordinators @bsipocz

**Comment by bsipocz** [comment]
I'm 👎 on rushing this into 3.1 given that it will break any affiliated and other packages, and it would be nice to ship this when we already notified them some way rather that suddenly start braking them in RC2 right before the release.

I'm 👍 for 3.2 though.

**Comment by drdavella** [comment]
Sounds good to me.

**Comment by bsipocz** [comment]
I suggest to merge this next week so then we can play with the package updating scripts to clean up the mess it causes in downstream packages?

**Comment by pllim** [comment]
:crossed_fingers: :robot:

**Comment by pllim** [comment]
Shall we merge when CI passes, then? (The `mpldev` failure is unrelated)

**Comment by bsipocz** [comment]
Let's go on with this then. Ultimately we'll need to fix the mpldev issues, but that needs to be done separately anyway.

Thanks @pllim!

**Comment by pllim** [comment]
Yup, I am looking into the `mpldev` stuff right now.

**Comment by bsipocz** [comment]
ouch: https://travis-ci.org/astropy/astroquery/jobs/480031761#L4492

I suppose we now need to spend a bit of time to fix this for packages...

**Comment by pllim** [comment]
:scream:

**Comment by pllim** [comment]
Could possibly use `batchpr` to:

1. Find `conftest.py` file. A package could have multiple files defined at different directory levels.
2. In each `conftest.py`, find `astropy.tests.pytest_plugins`.
3. Replace it with `astropy.tests.display`.

:crossed_fingers:

**Comment by bsipocz** [comment]
@astropy/affiliated-package-maintainers - be aware of this, you may see failures like above (https://github.com/astropy/astropy/pull/7786#issuecomment-454515978) for which the fix is something like this: https://github.com/astropy/astroquery/pull/1334/commits/27f5c4d05f57b0e5871637ac4d936a64127007b4

**Pull request merged**
