### PR TITLE
Updating comments to clarify astropy.wcs examples in documentation 

### LINKED ISSUE #3840: Clarify WCS examples
In http://astropy.readthedocs.org/en/latest/wcs/index.html

``` python
# Some pixel coordinates of interest.
pixcrd = numpy.array([[0, 0], [24, 38], [45, 98]], numpy.float_)

# Convert pixel coordinates to world coordinates
# The second argument is "origin" -- in this case we're declaring we
# have 1-based (Fortran-like) coordinates.
world = w.wcs_pix2world(pixcrd, 1)
print(world)
```
1. Is pixel coordinate in the pairs of `[X, Y]` or `[Y, X]`?
2. Why is `origin` set to 1 when `pixcrd` is clearly 0-indexed? I would expect `origin=0` in that case.

### PR DESCRIPTION
**Pull request by kakirastern**
To replace the older PR #8375 due to rebasing. Would like a fresh start since the former PR had become rather messy. 

EDIT: Fix #3840

### CODE REVIEW

**Comment by kakirastern** [comment]
Hi @pllim. Sorry about the previous attempt at opening a PR #8375 to modify some comments to clarify some astropy `wcs` examples. I needed to rebase and squash so had to force push. But in doing so I also closed the PR. I found it much easier to open a new PR since I do not want to repeat my mistake after some consideration. Please check the new commits (only 2 this time for now). Hope you find them agreeable. (Also, hope you are okay with me opening this PR to clear things up.) My old development version was in the 2.x so it was rather outdated. I had installed it with the hope of contributing to the astropy community, but has not found the opportunity to until I discovered about GSoC not long ago. I fully intend to use the two PR's I have opened to learn as much as I can in preparation for the proposal write-up of GSoC 2019 as possible. Thanks so much for your guidance thus far, I truly appreciate it.

**Comment by kakirastern** [comment]
You are welcome, @pllim! It's been a pleasure learning so much from you as well as the other contributors. Sure, I will wait.

**Comment by MSeifert04** [comment]
> And the `dtype=np.float_` should be changed to `np.float`.

I wouldn't recommend that change. `np.float` really shouldn't be used since it's just a legacy alias for Pythons `float`. 

Following the Python guideline "explicit is better than implicit" I would recommend using `dtype=np.float64` here. I mean either `dtype=float`, `dtype=np.float_`, `dtype=np.float64`, or `np.double` would work here but we explicitly want 64bit floats here so we should be explicit, or not?

**Comment by kakirastern** [comment]
Hi @nden and @MSeifert04, I have followed your suggestions and have applied an explicit data type declaration for the NumPy array in each of the "from_file.py" and "programmatic.py" examples, in order to comply with Python best practices. If the commits pass the checks then I would prefer merging the changes now... I would like to open another PR to deal with the `origin` matter more thoroughly since I wanted to make sure both `all_pix2world(0, 0, 0)` and `all_pix2world(1, 1, 1)` really produce the same result.

**Comment by kakirastern** [comment]
Ran into a bit of problem and needed to rebase... Hope I have not done something erroneous accidentally. I am still a work-in-progress so please forgive me for any rookie error made in the trial-and-error process. I appreciate any comments or advice or suggestions that will help me to learn.

**Comment by kakirastern** [comment]
Hi @pllim, I am failing the codecov/project check for the commits and am not sure how to proceed. I tried rebasing, but am sure I did something wrong that needs fixing. Could you give me some hints as to what might have went wrong? (I have a feeling in the process of rebasing I have unwittingly undo some of the other commits essential for the project, say as compared to 62c73d8.)

**Comment by kakirastern** [comment]
Hi @nden and @pllim, problems fixed, as all checks have passed. Ready to merge now.

**Comment by pllim** [comment]
@kakirastern , for the sake of moving on, here is what I propose:

* You squash all commits into one.
* I'll merge this.
* I'll open a follow-up PR to address Nadia's concerns.

Does that sound good to you? I think you got the workflow by now, and you have addressed my original request those years ago. Thanks for your patience!

**Comment by kakirastern** [comment]
@pllim Yup, sounds good to me. Squashed all commits into one...

**Comment by nden** [comment]
@MSeifert04  OK, agreed. And thanks for the link.

@pllim :+1: for your plan. Not sure about the cov report.

**Comment by kakirastern** [comment]
@nden The codecov/project test has failed after I squashed all the commits together, but was passing before the squash...

**Comment by pllim** [comment]
I wouldn't worry about the codecov.

**Comment by pllim** [comment]
Thank you!

**Pull request merged**
