### PR TITLE
pin qt version

### PR DESCRIPTION
**Pull request by MSeifert04**
However this failed on my fork because of:

 `WARNING: intersphinx inventory 'http://docs.scipy.org/doc/numpy/objects.inv' not fetchable due to <class 'urllib.error.URLError'>: <urlopen error [Errno 111] Connection refused>`

Related to #5340

### CODE REVIEW

**Comment by astrofrog** [comment]
I merged #5348 instead since it included changes to AppVeyor, but thanks for this!

**Comment by MSeifert04** [comment]
@astrofrog Why should it be pinned on AppVeyor it wasn't failing there even with qt 5.6?

**Comment by astrofrog** [comment]
@MSeifert04 - you are right - my bad, I assumed that the Windows Qt builds for Qt5 hadn't been done yet and that once they were it would fail too, but I was wrong. Sorry about that!

**Comment by larrybradley** [comment]
The `appveyor` tests were failing for `photutils` without pinning `qt=4` (https://github.com/astropy/photutils/pull/426), which is why I added it.

**Pull request closed without merging**
