### PR TITLE
Test against asdf/master now that changes have been integrated upstream

### PR DESCRIPTION
**Pull request by drdavella**
This reverts the temporary change to the CI script that was made in #6904.

### CODE REVIEW

**Comment by pllim** [comment]
Is the CircleCI failure expected?
```
                        * The following required packages can not be built:
                        * freetype, png * Try installing freetype with `apt-
                        * get install libfreetype6-dev` * Try installing png
                        * with `apt-get install libpng12-dev`
error: Setup script exited with 1

./.run_docker_tests.sh returned exit code 1
```

**Comment by drdavella** [comment]
@pllim, no I think someone needs to restart the job if possible.

**Comment by saimn** [comment]
I saw the same error on CircleCI on the showtable PR, I think it's because of the new pytest-mpl dependency (mentioned in  #6942). CircleCI tries to build mpl from the sources.

**Comment by drdavella** [comment]
@saimn oh yuck. Maybe we need to reevaluate whether `pytest-mpl` should be packaged as part of `pytest-astropy` after all

**Pull request merged**
