### PR TITLE
Add auto completion for astropy.units

### LINKED ISSUE #13995: Auto completion for astropy.units not work in vscode
I work with vscode, and I rely heavily on the automatic completion function.
Automatic completion can avoid many typo, and give me a sense of security.  
However, astropy.units can't provide this function, so I need to reference the manual when I'm coding.  
I think it would be better to add declare for all available units in __init__.py. To maintain declaration and implementation consistency, a pre-commit hook will be helpful.

### PR DESCRIPTION
**Pull request by MengDanzz**
### Description

This pull request is to address auto completion for astropy.units

Fixes #13995
* Add `unit_completion.py` to `pre-commit` hook to generate units declaration in `astropy/units/__init__.py`
### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by pllim — CHANGES_REQUESTED** [review]
This solution will not work on Windows.

**Comment by MengDanzz** [comment]
Thanks for the suggestions above!
Therefore, I made these two changes：
1. Put the statement of automatic completion in a separate file, rather than directly append them after __init__.py
2. Remove the `os.system` bash calling, and all functions are implemented in pure python.

But the workflow seems to fail with error "No module named 'packaging'", what should I do to fix it?

**Comment by pllim** [comment]
I am still not sure about this: `+3,313 −0`

Let's hold off until we hear more from other devs. Thanks!

**Comment by dhomeier** [comment]
> But the workflow seems to fail with error "No module named 'packaging'", what should I do to fix it?

Might need to be added to `additional_dependencies`, but I have no idea why that worked with the previous commit.
There also seem to be some problems due to importing astropy directly in the source tree, so that might need to be setup differently; but @nstarman or @WilliamJamieson may know better what exactly is happening, and in what kind of environment, in the pre-commit.

But it would also be good to have someone familiar with VSCode look into whether all this is really needed to enable its autocompletion.

**Comment by MengDanzz** [comment]
There are three common IDE automatic completion methods:
1. Read variable values dynamically. It is suitable for Jpyter, Python and other REPL environments, but it is difficult to support writing scripts or pipelines.
2. AI completion based on text analysis of a large number of codes and repositories. This method is very effective, but it may not be accurate and reliable.
3. Static analysis based on type annotation. This approach may introduce additional code (type annotations), but it is the most reliable.
Therefore, I think it is necessary to add type annotations to support static analysis of IDEs.

**Comment by WilliamJamieson** [comment]
It looks like `astropy.units.autocompletion` is/can be generated automatically using `unit_completion.py`. If this is the case why don't we just generate this file during the install/wheel-building process? I know that one can have `setuptools_scm` generate a `version` file when installing a python package. Additionally, it would be really nice if generating/installing this file was optional during the package install (I have no idea if this is possible) because there are possible performance issues with importing a file like this at the `__init__.py` level (maybe we should measure this). These hints are only really useful when developing code using astropy and are not needed when running applications which use astropy.

**Comment by MengDanzz** [comment]
Good idea to generate this file during the install/wheel-building process. 
[There are no effect on running time](https://dev.to/idoazzz/pythons-type-annotations-the-best-of-both-types-worlds-52li) : 
> Python's interpreter will relate the Type Annotations as comments, so no effect on runtime.

**Comment by mhvk** [comment]
I'm with @dhomeier in feeling it is really not astropy's job to work around limitations of other tools, at least not to the level that the package starts including large files just for this purpose. Perhaps the information can be generated on-the-fly for people using VSCode? Would it be an idea to raise an issue with VSCode? Possibly they have a simple work-around.

Also, what was the answer to @dhomeier's question about whether there are issues with other astropy submodules? I can see that defining module members with `def_unit` is particularly tricky, but would be good to be sure that is the underlying problem.

**Comment by nstarman** [comment]
> There are three common IDE automatic completion methods:
> 
> 1. Read variable values dynamically. It is suitable for Jpyter, Python and other REPL environments, but it is difficult to support writing scripts or pipelines.

This is always convenient. As you say it has limitations. My VSCode autocomplete picks up on most things in ``units`` (even with GH CoPilot turned off).

> 2. AI completion based on text analysis of a large number of codes and repositories. This method is very effective, but it may not be accurate and reliable.

I use VSCode + GH CoPilot. I agree with your description.

> 3. Static analysis based on type annotation. This approach may introduce additional code (type annotations), but it is the most reliable.
>    Therefore, I think it is necessary to add type annotations to support static analysis of IDEs.

Agreed, but this is a massive endeavor. What we might consider is adding an ``__init__.pyi`` file with the full set of imports. This will have no runtime effect, but can be picked up by tools in VSCode.

**Pull request closed without merging**
