### PR TITLE
TST: Fix doctest failures

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to fix doctest failures caused by #10848

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Ah, the risk of the very careful `[ci skip]` that still ran on readthedocs and passed. So, clearly one shouldn't do that. Thanks for noticing and fixing so quickly!!

**Comment by pllim** [comment]
The RTD job only confirms that it can render into HTML without errors or warnings. It does not run any doctest. Hope this clarifies the matter!

**Comment by pllim** [comment]
Hmmm! Behavior change in numpy-dev . @mhvk , can you please advise?

```
122 Numpy array creation functions cannot be used to initialize Quantity
123 --------------------------------------------------------------------
124 Trying the following example will throw an UnitConversionError::
125 
126     >>> my_quantity = u.Quantity(1, u.m)
127     >>> np.full(10, my_quantity)  # doctest: +IGNORE_EXCEPTION_DETAIL
Expected:
    Traceback (most recent call last):
    ...
    UnitConversionError: 'm' (length) and '' (dimensionless) are not convertible
Got:
    array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
/home/travis/build/astropy/astropy/docs/known_issues.rst:127: DocTestFailure
```

**Comment by mhvk** [comment]
Wow, that's interesting/weird... I guess little choice but to `.. doctest-requires:: numpy<1.20` and adjust the text above, adding "on numpy before version 1.20 and ignore the unit in later versions:"

**Comment by mhvk** [comment]
Great, thanks so much! Hopefully it will now all pass...

**Review by eteq — APPROVED** [review]
LGTM too! Will merge as soon as the rest of the CI passes (just another few min looks like).

**Comment by pllim** [comment]
All green (even the numpy-dev job)!

**Comment by bsipocz** [comment]
Weirdly it doesn't cause a traceback on 1.16 on the LTS branch with 32bit 3.6, so I just go ahead and ignore the output as a workaround for that branch.

**Pull request merged**
