### PR TITLE
Move FrameAttribute classes into separate module

### PR DESCRIPTION
**Pull request by adrn**
In master, the `FrameAttribute` classes are all defined in the same module as `BaseCoordinateFrame`. When there was only one class, this wasn't too much extra code, but now there are a few subclasses and I think they deserve their own module. This shouldn't change anything about their functionality, just moves the location.

cc @eteq @mhvk

### CODE REVIEW

**Comment by taldcroft** [comment]
@adrn - I agree with refactoring these into a separate module, but still import them into `baseframe.py`.  As it stands this PR is an API break since something like `astropy.coordinates.baseframe.TimeFrameAttribute` is a public class.  

I would also propose doing the refactor but NOT change all the internal astropy references, in essence still defining `astropy.coordinates.baseframe` as the home of `FrameAttribute` classes even though they technically are defined in another module.  Refactoring doesn't need to be painful!  :smile:

**Comment by eteq** [comment]
Strictly speaking, `astropy.coordinates.baseframe.TimeFrameAttribute` is *not* a public class: `astropy.coordinates.TimeFrameAttribute` is what's [in the docs](http://docs.astropy.org/en/stable/api/astropy.coordinates.TimeFrameAttribute.html#astropy.coordinates.TimeFrameAttribute).  In general, our stance has been "if it's in the docs, it's public, otherwise, it's not". So by that argument the only canonical way to get a `TimeFrameAttribute` is via `astropy.coordinates`.

That said, if there's any examples of people actually using it from `baseframe`, I see @taldcroft's point that it's probably better to just accept that people are doing this... Do you know of any, @taldcroft? 

As for the *internal* imports, I'm pretty ambivalent.  @adrn has already put in the time in this refactor to use the new location, so I don't really see it as critical to back out the change.  Seems basically the same to me either way if we go with @taldcroft's suggestion to import it all back into `baseframe`.

**Comment by mhvk** [comment]
:+1: to the refactor. Just in case it makes the decision easier, yet another way to do the final organisation is to make `baseframe` a directory with both a `core` and an `attributes` file inside, and `__init__` importing from both. But probably not worth the hassle.

**Comment by taldcroft** [comment]
SunPy currently [imports TimeFrameAttribute from astropy.coordinates.baseframe](https://github.com/sunpy/sunpy/blob/e06df84dc225995806c3807603d758ea807ef923/sunpy/coordinates/frameattributes.py#L6).

If you look at the current astropy code in order to learn about advanced usage, these attributes are uniformly imported from from `baseframe`.  I think it is fair to say that advanced developer types (who are likely to write coordinates extensions) look at the code before the docs to figure out how to do things.  Also you have stuff like below that will lead people to import from `baseframe`:
```
In [3]: TimeFrameAttribute.__module__
Out[3]: 'astropy.coordinates.baseframe'
```

Conceptually I still think of `baseframe` as *the* module that contains the building blocks needed to construct `Frame` classes, which is why I recommended leaving most of the existing astropy code alone.  The idea from @mhvk is nice and clean.

But as a takeaway, even though there is indeed a formal public API, we should always strive to maintain the quasi-public API exposed via internal astropy code examples, especially for widely-used and mature packages like coordinates.

**Comment by adrn** [comment]
I imported the attributes back into baseframe. 

On the philosophical point, I agree that we should _strive_ to, but I don't think it's practical to guarantee future support for both high-level and undocumented code for a big package like astropy that _does still need to evolve_.

**Comment by eteq** [comment]
Ah, I see the practical point if Sunpy does, it @taldcroft. Looks like the last change @adrn made will keep the backwards-compatibility, so I think this is good to go and will merge.

On the philisophical side, I don't really agree that we should agree we're going to support users making use of the non-public API.  The whole point of having a public API is so that we *can* do refactors like this and not worry about it affecting the users.  If we don't maintain some discipline on that we have to continue making endless backwards-compatible changes and that becomes a convoluted mess.  That said, this is an easy one... and practicality beats purity™️.

**Comment by taldcroft** [comment]
Agreed that we shouldn't make the code convoluted.  Thanks for making the change.

**Pull request merged**
