### PR TITLE
BF: add jinja2 to install requires

### PR DESCRIPTION
**Pull request by matthew-brett**
Jinja2 necessary for distutils build.

### CODE REVIEW

**Comment by astrofrog** [comment]
See https://github.com/astropy/astropy/pull/3229 - jinja2 and cython are only required for developer versions, and should not be required for stable releases, so we need to conditionally add them to ``install_requires`` depending on whether this is a dev or stable version.

**Comment by eteq** [comment]
@matthew-brett - Just to clear things up: in https://github.com/astropy/astropy/pull/3229#issuecomment-225661812 are you saying you're OK with the status quo?  Or that you think a clearer message should appear about jinja2?  If the former, can we close this issue, and if the latter, can you update this to do that instead?

**Comment by eteq** [comment]
I'm going to go ahead and close this based on what I said above, but, @matthew-brett, if you think it still applies feel free to re-open it

**Comment by matthew-brett** [comment]
Sorry not to comment before - I still think a warning would be preferable, sorry I didn't get round to writing one, I was a bit intimidated by the problem of working out the situations when Cython / jinja2 will be needed.

**Pull request closed without merging**
