### PR TITLE
Include FITS header when updating ImageHDU extensions with convenience functions

### PR DESCRIPTION
**Pull request by MSeifert04**
This is similar to #6042 . I thought it wouldn't matter but it actually did matter in case of `fits.update`...

I will include the changelog entry later. :)

### CODE REVIEW

**Comment by MSeifert04** [comment]
Test failures _seem_ unrelated, is anything broken?

**Comment by saimn** [comment]
@MSeifert04 - It was indeed (#6059), it should be fine now if you rebase. Can you add the changelog by the same occasion ?

**Comment by pllim** [comment]
I didn't even know `fits.update()` existed. :joy:  Thanks for fixing this!

**Comment by MSeifert04** [comment]
Well, after #6042 I activly searched when the second `if` could fail. Not that I ever used `update` myself...

**Comment by pllim** [comment]
@MSeifert04 , did you check if the image example given in #5988 would still work with this? The trouble with FITS is fixing a bug sometimes introduces three more.

**Comment by MSeifert04** [comment]
I haven't done explicit checks because most other convenience methods just create a PrimaryHeader (with appropriate header) when `_makehdu` returns an `ImageHDU`. But the image example worked correctly:

```
from astropy.io import fits
import numpy as np

image = np.zeros((10,10),dtype=np.float)
fname='foo_image.fits'
h_in = fits.Header()
h_in['ANSWER']=(42.0,'LTU&E')
fits.writeto(fname,data=image,header=h_in,clobber=True)
h_out_image=fits.getheader(fname,ext=0)
```

gives

```
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -64 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                   10                                                  
NAXIS2  =                   10                                                  
ANSWER  =                 42.0 / LTU&E    
```

**Comment by bsipocz** [comment]
So, @pllim do you merge this once travis is green? And your 2 docs update, and then targets are met :)

**Comment by pllim** [comment]
Sure!

**Comment by pllim** [comment]
> And your 2 docs update

But... who is going to merge my doc updates?

**Comment by pllim** [comment]
coveralls seems to have been completed despite the status here: COVERAGE INCREASED (+0.02%) TO 84.345%

**Comment by MSeifert04** [comment]
Great, thanks for merging 👍

**Comment by pllim** [comment]
@bsipocz , just one more PR to achieve goal!

**Comment by bsipocz** [comment]
Brilliant, I'll try to go back to one of mine on the way back home. The
goal was set for the week, so I still have two days...

**Pull request merged**
