### PR TITLE
Fix string formatting for minimum_python_version

### PR DESCRIPTION
**Pull request by larrybradley**
Fixes installation docs, which currently look like this:

astropydocs

### CODE REVIEW

**Comment by pllim** [comment]
Whoops... My bad from #11076

**Comment by larrybradley** [comment]
Locally it looks fine.

**Comment by larrybradley** [comment]
Not sure why the RTD build is stuck, but if you click through to "View Docs" they built correctly.

**Review by pllim — APPROVED** [review]
Looks great, thanks! https://astropy--11243.org.readthedocs.build/en/11243/install.html

**Pull request merged**
