### PR TITLE
Remove deprecated register argument in astropy.units

### PR DESCRIPTION
**Pull request by astrofrog**
It looks like this was overdue for being removed (deprecated in 0.3)

### CODE REVIEW

**Comment by mhvk** [comment]
:+1:

**Comment by astrofrog** [comment]
@mhvk - this makes changes to things that were in stable releases, hence why it should be affects-release. The only time when you use affects-dev is if it is a bug introduced after a stable release.

**Comment by embray** [comment]
:+1:

**Comment by embray** [comment]
Right.  "Affects-release" is for user-visible changes between two (or more) releases.
If anyone can think of a clearer nomenclature for those labels I'm all for it.

**Comment by mhvk** [comment]
OK, looks good to me, merging!

**Pull request merged**
