### PR TITLE
Documentation for pre-defined models

### PR DESCRIPTION
**Pull request by karllark**
### Description

This pull request provides documentation of some pre-defined models in the astropy.modeling module. The overall goal is to make it easier to find the pre-defined models and understand what capabilities they provide. Prior to this, the API was the main (only?) way to find what pre-defined models existed.

### CODE REVIEW

**Comment by karllark** [comment]
Ready for review.

**Comment by nden** [comment]
@karllark This looks awesome! Thanks for taking the time to do it.

**Comment by nden** [comment]
One typo in `physical_models.rst`:
"The Drude1D model provides a model for the behavior of an **election** in a material "
`election` --> `electron`

You can use `[skip ci]`.

**Comment by nden** [comment]
Thanks @karllark ! @pllim The documentation changes in this PR are mostly code so merging now.

**Pull request merged**
