### PR TITLE
Apply `black` to `astropy.coordinates`

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

Apply `black` to `astropy.coordinates` according to the process laid out by [APE 20](https://github.com/astropy/astropy-APEs/blob/main/APE20.rst).

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
> It is however worth pointing out that the `angle_lextab.py` and `angle_parsetab.py` files are automatically generated and `black` shouldn't touch them at all.

I just excluded these from black, and re-generated the black changes

**Comment by eerovaher** [comment]
Simply not reviewing the two files would have been simple enough, but `black` really should not touch automatically generated files, so it's better to exclude them early in the process.

**Comment by eerovaher** [comment]
By default `black` is somewhat hesitant to touch strings. It doesn't merge short strings, split very long ones or remove unnecessary f-string declarations. However, it is possible to force `black` to do that:
```shell
$ black --skip-string-normalization --experimental-string-processing astropy/coordinates/
```
I simply ignored the deprecation warning. 

The number of edited lines was quite modest: `22 files changed, 238 insertions(+), 179 deletions(-)`. I went through the changes and I think they look better than what `black` had produced previously. Further improvements are still possible by converting `str.format()` expressions to f-strings.

**Comment by WilliamJamieson** [comment]
> Simply not reviewing the two files would have been simple enough, but `black` really should not touch automatically generated files, so it's better to exclude them early in the process.

Why are we tracking automatically generated files as part of astropy in the first place. IMOP, we should be creating these files during the install process or when we build the wheels.

**Comment by eerovaher** [comment]
> You are welcome to push a commit with these changes to this branch.

I already did.

**Comment by astrofrog** [comment]
> Why are we tracking automatically generated files as part of astropy in the first place. IMOP, we should be creating these files during the install process or when we build the wheels.

Historically I think this would have been more difficult as it would require another build-time dependency and these weren't consistently installed via setup_requires - but now we are using pyproject.toml it might be possible to try and auto-generate these at build-time. Worth the try after 5.2 is out? (and for now indeed we should exclude these files)

**Comment by astrofrog** [comment]
I am removing myself from review as I am not one of the maintainers and I already have reviewed a lot of other PRs

**Comment by mhvk** [comment]
See also #7177 on auto-generation. Though with newer versions of `ply`, they are not generated any more -- #13399.

**Comment by eerovaher** [comment]
I've gone through the diffs, but it will take me some more time to organize the changes I've made into sensible commits.

**Comment by WilliamJamieson** [comment]
> I've gone through the diffs, but it will take me some more time to organize the changes I've made into sensible commits.

If possible can you divide your commits into formatting changes and other refactoring changes

**Comment by eerovaher** [comment]
I have reviewed the changes `black` made and pushed my own updates here. There were a few cases where `black` resulted in very ugly code. Although in those cases the preceding code was not very good-looking either, I nonetheless decided to switch formatting off for the worst offenders and restore the pre-`black` code. I think those sections should be refactored, but the changes would be extensive enough that they would best done in a follow-up pull request, and the `# fmt: off/on` comments can be easily found with `git grep`.

**Comment by eteq** [comment]
FYI, I'm going to try to merge what I found when testing APE20 on coordinates with @eerovaher's changes, will push up a commit doing that in the next hour or two.

**Comment by eteq** [comment]
(I really think GitHub should consider putting the "Close with comment" button further away from the "comment" button...)

**Comment by WilliamJamieson** [comment]
> FYI, I'm going to try to merge what I found when testing APE20 on coordinates with @eerovaher's changes, will push up a commit doing that in the next hour or two.

Let me know if you want me to rebase this and/or fix the currently failing pre-commit check.

**Comment by eteq** [comment]
I just pushed up assorted changes - @eerovaher , I think you got most of the ones I had (but not all), but I found a few more.  I think between us we can call this all good though!

@WilliamJamieson, I think this is ready for a rebase and fix as you said.

I'm not sure exactly how much you plan to squash, but at least for this one I don't think we should, because some of these commits are "real changes" that were inspired by Black rather than just black formatting changes per se.

**Comment by WilliamJamieson** [comment]
> I'm not sure exactly how much you plan to squash, but at least for this one I don't think we should, because some of these commits are "real changes" that were inspired by Black rather than just black formatting changes per se.

The black changes have been squashed to two commits pure formatting/black related and then all the other "refactor" related changes. Is this sufficient?

**Comment by WilliamJamieson** [comment]
@eteq and @eerovaher I have done a few things to your changes:

1. Rebased them on `main` so there should not be any merge conflicts (for now at least).
2. Adjusted the history slightly so that `--skip-string-normalization` was temporally turned on for `pre-commit` so that `pre-commit` hooks would run and pass. I then ran `pre-commit` on each of your commits and made the necessary changes to have them pass (in a few cases this resulted in `pyupgrade` managing to upgrade some strings to f-strings automatically).
3. Added `[black]` and `[refactor]` tags to each of the commit messages (splitting a few commits into these categories). The `[black]` commits should be just be formatting changes (with some `pyupgrade` results sprinkled in), while the `[refactor]`  changes are actual code changes (actual changes to strings, changing variables, etc).

Note that I have preserved your change history (after rebase) in the `black/coordinates_original_history` branch in my fork if you have serious issues with what I have done.

Please review my `[black]` and `[refactor]` commit tags because during the squash process I will reorder the history so that all the `[black]` get squashed together into one commit followed by all the `[refactor]` commits squashed into a single commit. The `[black]` commit will eventually be added to the `.git-blame-ignore-revs` file.

If my changes are satisfactory and you do not see any additional changes that you would like to make, then this PR should be ready for string normalization. In this case, please move this PR to the "Ready for string normalization" column in https://github.com/orgs/astropy/projects/10. I will then apply string normalization and give you another chance to review the changes.

**Comment by eerovaher** [comment]
I think this is ready for string normalization.

**Comment by WilliamJamieson** [comment]
> I think this is ready for string normalization.

@eerovaher and @eteq I have normalized the strings. When you are happy with the results, please move this to the "Ready for Squash" column.

**Comment by eerovaher** [comment]
I see no reason not to proceed.

**Comment by WilliamJamieson** [comment]
@eerovaher and @eteq I have squashed this PR and marked it as "Ready for Merge". If you see any further things that need to be corrected please note that soon.

**Comment by astrofrog** [comment]
@eerovaher @eteq - are you happy for this to be merged?

**Review by eerovaher — APPROVED** [review]
Both @eteq and myself made changes to this pull request. I shouldn't review my own changes, but @eteq had a look at them and found them to be good (https://github.com/astropy/astropy/pull/13953#issuecomment-1312227731), and I can approve the changes @eteq made.

**Pull request merged**
