### PR TITLE
Fix Angle.to_string(format="latex") when using pgf with unicode-math

### PR DESCRIPTION
**Pull request by maxnoe**
See https://github.com/wspr/unicode-math/issues/448 for why it is a good idea anyway to always use `_{...}` or `^{...}` instead of relying the command can be used without braces.

### CODE REVIEW

**Comment by maxnoe** [comment]
Did I break that test in mpldev? I cannot really see the relation, but it is in a plot that uses wcsaxes

**Comment by maxnoe** [comment]
Docs failure also looks unrelated...

**Comment by pllim** [comment]
The failures should have been addressed already. Please rebase your changes against latest `upstream/main`. Thanks!

**Comment by maxnoe** [comment]
Great!

**Comment by maxnoe** [comment]
Ha, the main/master got me.

**Comment by pllim** [comment]
Thanks for your patience! I'll let subpackage maintainer(s) set the milestone.

**Comment by maxnoe** [comment]
I just didn't realize astropy also made the switch to main and started the branch using `git switch -c <name> upstream/master` which succeeded because I still had it lying around.

**Review by mhvk — APPROVED** [review]
To be honest, I'd write all those as `^{\rm h}`, but that's a bit off-topic... Definitely good to use braces for anything that is not a single character!

**Comment by mhvk** [comment]
I don't really think this needs a changelog entry: really, we're mostly future-proofing here (which is of course a very good thing to do!)

**Comment by mhvk** [comment]
@pllim - the bot doesn't seem to have quite realized I set the milestone...

**Comment by pllim** [comment]
Just ignore the milestone bot. It has gone rogue. I can't control it anymore. 🤖

**Comment by pllim** [comment]
@mhvk , feel free to merge if you think it is good to go!

**Comment by maxnoe** [comment]
`^{\rm h}`

```

! Class scrartcl Error: undefined old font command `\rm'.

See the scrartcl class documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.4 $5^{\rm
            h}$
? 
```

;)

**Comment by mhvk** [comment]
Ah, I guess it is not quite that latex compliant!

Anyway, ignoring the rogue bot, let's get this in!

**Pull request merged**
