### PR TITLE
Fix failures caused by ASDF test API change

### LINKED ISSUE #7088: Test failures with assert_roundtrip_tree (from asdf)
There is a bunch of new failures in the tests (example : https://travis-ci.org/astropy/astropy/jobs/330186208), which appears to be due to a change in the `assert_roundtrip_tree` imported from asdf. This is because of https://github.com/spacetelescope/asdf/commit/dd4f32f05c1d91417d0887ba6c1acaadc2a519e6 - ping @Cadair @drdavella 

```
    def test_table(tmpdir):
        data_rows = [(1, 2.0, 'x'),
                     (4, 5.0, 'y'),
                     (5, 8.2, 'z')]
        t = table.Table(rows=data_rows, names=('a', 'b', 'c'),
                        dtype=('i4', 'f8', 'S1'))
        t.columns['a'].description = 'RA'
        t.columns['a'].unit = 'degree'
        t.columns['a'].meta = {'foo': 'bar'}
        t.columns['c'].description = 'Some description of some sort'
    
        def asdf_check(ff):
            assert len(ff.blocks) == 3
    
>       helpers.assert_roundtrip_tree({'table': t}, tmpdir, asdf_check)
E       TypeError: assert_roundtrip_tree() takes 2 positional arguments but 3 were given
```

### PR DESCRIPTION
**Pull request by drdavella**
This fixes #7088.

### CODE REVIEW

**Comment by saimn** [comment]
Related issues on Travis seem to be solved, thanks @drdavella!

**Comment by drdavella** [comment]
It looks like this PR fixes the ASDF-related failures, as intended, but there are still some unrelated failures.

**Comment by saimn** [comment]
Yeah, there is an issue with the `sites.json` file (https://github.com/astropy/astropy-data/issues/36) and something with Numpy 1.14 and conda.

**Comment by bsipocz** [comment]
I'm merging this now as this is approved, and master already has those failing issues.

**Pull request merged**
