### PR TITLE
Add a new to_value method to Quantity.

### LINKED ISSUE #6125: Shortcut for Quantity q.to(unit).value?
First, is there a shorter way to do `q.to(unit).value` where `q` is a `Quantity`.

If not, could we make one?  For instance `as`?
```
q = 1 * u.m
q_km = q.as(u.km)
```

### PR DESCRIPTION
**Pull request by mhvk**
This returns the value of the quantity in the given unit.

@taldcroft: I ended up with `to_value` as I felt it was a bit more uniform (with `to_string`, etc.) and makes more sense without arguments (a form that needs to exist to make the property work, i.e., `q.to_value()` is obvious but `q.value_in()` is not). I also ended up not using it for `to`, as especially the scalar case is slowed down a little too much by first doing `value.item()` and then recreating an array in `_new_view`.

Fixes #6125

### CODE REVIEW

**Comment by taldcroft** [comment]
Doc and remote test fails appear unrelated.

**Comment by mhvk** [comment]
I've never understood `affects-*` too well...

Sadly, the documentation failure was real, but it made me realize I should ensure this works for `EarthLocation` as well, so it was good in that sense.

**Comment by bsipocz** [comment]
@mhvk - Basically both ``Affects-*`` labels are most useful to bugfixes (and bug reporting issues) and the sole purpose is to notify the person (and the script) whether that given bug was existed in a released version. If it was then it most probably needs to be backported, if not it will need to be on master only, and most probably won't need a changelog entry.

The other usecase for ``Affects-dev`` could be that it's an enhancement on a new feature in master, thus no changelog will be needed as the feature already has its entry.

**Comment by mhvk** [comment]
@adrn - `to_value` is faster (no needless creation of a new `Quantity` only to discard it immediately), so, yes, we should recommend that.  A quick `grep` shows only two instances in the documentation, but quite a lot of instances in the code...

**Comment by adrn** [comment]
@mhvk Hm, yea, I see 205 matches with `to\(.+\)\.value` -- how do you think we should handle replacing those?

**Comment by taldcroft** [comment]
@adrn - How about a post-merge PR to do this with a grep/replace?  This is one place where perl rocks: http://www.perlmonks.org/?node_id=608701

**Comment by bsipocz** [comment]
👍  to do the replaces separately (btw I would do it with sed, but I believe perl can do this, too).

**Comment by saimn** [comment]
Excellent news if this is faster !

**Comment by adrn** [comment]
OK sounds good. I've created an issue just so we don't forget. Tests are passing and doubly-approved, so merging now.

**Comment by bsipocz** [comment]
Would the performance enhancement resulted from this deserve a ``what's new`` entry? Maybe one entry that includes all the performance enhancements made in v2.0?

**Comment by mhvk** [comment]
In principle, yes, but I think that would at the minimum involve getting `asv` working again, so we can quantify what the improvement actually is!

**Comment by bsipocz** [comment]
Running it on a CI is really not an option? I expect the general trends to show up there even on travis, and maybe circle or appveyor would work better?

**Pull request merged**
