### PR TITLE
Allow data as explicit parameter to NDDataArray

### PR DESCRIPTION
**Pull request by evertrol**
This is a possible fix for issue #4620

### CODE REVIEW

**Comment by MSeifert04** [comment]
Looks good to me. It's more explicit than my suggestion :+1:

**Comment by mwcraig** [comment]
Finally taking a look at this. It would return NDData to its pre-1.1 state (not a bad thing necessarily), but looks like it is backwards compatible. I think the APE for `NDData` made the data argument required because `NDData` without data wasn't one of the envisioned use cases.

@jehturner @crawfordsm any comments? This would allow either of these:

```python
ndd = NDData([0, 1])
ndd = NDData(data=[0, 1])
```

If the consensus is that we should go this way I don't object.

**Comment by MSeifert04** [comment]
@mwcraig Actually `NDData` can already be used like that only `NDDataArray` couldn't because it assumed that `data` was always the first argument (which it doesn't need to be with NDData):

```
NDData(meta=OrderedDict(), data=[1,2,3])         # works
NDDataArray(meta=OrderedDict(), data=[1,2,3]) # IndexError 
```

**Comment by jehturner** [comment]
I hadn't noticed that this didn't work for `NDDataArray`. Indeed it seems anomalous to me if one can only specify a parameter without using its name, don't you think? So :+1: if this doesn't break anything.

Regarding `NDData` without `data` not being an envisioned use case, that's something I quickly ran into when trying to store bad pixel masks, which only have `flags` or `mask`, to keep all my data in the same type of object. I ended up putting an integer mask into the main `data` array instead of `flags`, which seems reasonable for something that's primarily a BPM, but I don't know whether that's consistent with expectations (it does make things more convoluted when trying to map my `NDData` instances to files on disk with an appropriate EXTNAME for each array attribute). The counterargument would be "why not just allow it?". Anyway, I digress.

@evertrol, you might want to be aware that there was some discussion at the Python in Astronomy meeting last week of the `NDData` API evolving a bit further to meet the needs of LSST. There should be another APE at some point.

**Comment by crawfordsm** [comment]
I have no objection to this as this looks backward compatible.   I've tried the PR against the ccdproc tests and nothing breaks.

As an aside, we potentially should think about setting up a testing infrastructure specifically for NDData PRs to make sure they don't break the major packages using them.

**Comment by mwcraig** [comment]
Merging (sorry for the delay)

**Comment by astrofrog** [comment]
@mwcraig - does this need a changelog entry?

**Comment by mwcraig** [comment]
Yes, it should. Do you want me to open a PR for that ?

**Comment by astrofrog** [comment]
@mwcraig - yes please! You can always open a PR to this branch if you like: https://github.com/astropy/astropy/pull/4880

**Comment by mwcraig** [comment]
@astrofrog -- done.

**Pull request merged**
