### PR TITLE
Removing know issue for old numpy and very old astropy

### LINKED ISSUE #6049: Remove old "known_issues" from docs
Lots of very old "known issues" listed in the docs

http://docs.astropy.org/en/latest/known_issues.html  (updated stable-->latest)

### PR DESCRIPTION
**Pull request by bsipocz**
This is to close #6049 

One is about numpy 1.6, the other is to upgrade from astropy 0.2 that is more than 4 years old.

### CODE REVIEW

**Comment by mhvk** [comment]
Looks good. I restarted the failed docs build just in case.

**Comment by bsipocz** [comment]
@mhvk - The rest of the known issues still seem relevant to me, but if you have a spare moment and can spot other ancient ones, please let me know (there is one for a rather old ipython, but since we don't have minimal requirement there, I think it can stay).

http://docs.astropy.org/en/latest/known_issues.html

**Comment by mhvk** [comment]
@bsipocz - I don't think it is this PR, but the failure seems real:
https://travis-ci.org/astropy/astropy/jobs/244692493#L5064

**Comment by bsipocz** [comment]
@mhvk - Yes, I'm looking at it, it's in master following the branching this morning. It's rather weird. 

(Also travis is doing the testing on the merge commit, thus the failurs in master can screw up PR testing, too)

**Pull request merged**
