### PR TITLE
Fix to ensure ImageNormalize clip is used in the __call__ method

### PR DESCRIPTION
**Pull request by larrybradley**
Currently the `ImageNormalize` `clip` keyword is ignored in the `__call__` method:

```python
>>> from astropy.visualization import ImageNormalize
>>> data = np.arange(5)
>>> norm = ImageNormalize(vmin=1, vmax=3)
>>> norm(data, clip=False)  # correct result
masked_array(data=[-0.5, 0.0, 0.5, 1.0, 1.5],
             mask=[False, False, False, False, False],
       fill_value=1e+20)

>>> norm(data, clip=True)  # wrong result (same result as clip=False)
masked_array(data=[-0.5, 0.0, 0.5, 1.0, 1.5],
             mask=[False, False, False, False, False],
       fill_value=1e+20)
```

With this PR:
```python
>>> norm(data, clip=True)  # correct result
masked_array(data=[0.0, 0.0, 0.5, 1.0, 1.0],
             mask=[False, False, False, False, False],
       fill_value=1e+20)
```

### CODE REVIEW

**Comment by larrybradley** [comment]
@pllim I think Delores has taken over astropy-bot!  🤖

**Comment by bsipocz** [comment]
Who is Dolores?

**Comment by bsipocz** [comment]
Thanks @larrybradley!

**Comment by larrybradley** [comment]
@bsipocz It's from Westworld:  https://westworld.fandom.com/wiki/Dolores_Abernathy

**Pull request merged**
