### PR TITLE
DOC: add README about building OSX wheels

### PR DESCRIPTION
**Pull request by matthew-brett**

### CODE REVIEW

**Comment by embray** [comment]
Thanks, these docs are nice to have.  Though I don't think this is exactly the place for it.

**Comment by embray** [comment]
There's an [astropy-wheels](https://github.com/astropy/astropy-wheels) repository that sort of fell out of use (if it was ever used at all) that I've been meaning to repurpose or revive for this purpose.  That might be a better place to put these instructions.

**Comment by matthew-brett** [comment]
Ah - you also have the MacPython/astropy-wheel repo.  I'm afraid I made that before I knew you had one with the same name.

It would be trivial to move the repo over to your org though.

I was thinking of the instructions as being useful for a release manager.  Where do those types of instructions go?

**Comment by embray** [comment]
https://github.com/astropy/astropy/blob/master/docs/development/releasing.rst

If you'd like to rework these instructions to fit somewhere logically into that page we could reopen this. That might be useful to have there, though I may want to tweak the details as we go along.

**Comment by matthew-brett** [comment]
I'm fine with whatever is useful.   For now, I moved the text to : https://github.com/MacPython/astropy-wheels/blob/master/README.rst .  Maybe the easiest would be to point to this README from the `releasing.rst` document?

**Comment by embray** [comment]
That would be fine.  It would be good for anyone doing a release to be aware of the process of building / releasing wheel builds.

**Pull request closed without merging**
