### PR TITLE
Backport PR #14193 on branch v5.2.x (Fix compat with Numpy 1.24)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #14193: Fix compat with Numpy 1.24

### CODE REVIEW

**Comment by pllim** [comment]
I don't understand the error with RTD and also the SHA error from scipy data file in FITS test.

**Comment by pllim** [comment]
Anyways, let's get this backported and worry about those later.

**Comment by saimn** [comment]
> I don't understand the error with RTD and also the SHA error from scipy data file in FITS test.

Hmm lots of new failures :grimacing: 
Scipy moved their data files to another repo and files now are downloaded on demand. It seems some recent change (https://github.com/scipy/dataset-ascent/pull/3 ?) broke their download checks.

**Comment by pllim** [comment]
Do we really need scipy external data for one FITS test? 😒

**Comment by saimn** [comment]
The test could be written differently but it's testing fits compressing and needs some not too unrealistic data.

**Pull request merged**
