### PR TITLE
Decreasing number of calls BaseColumn._array_finalize in MaskedColumn

### PR DESCRIPTION
**Pull request by himanshupathak21061998**
Fix: #6721
I managed upto this
```
In [2]: c = MaskedColumn([1,2], format='%d')
Finished array finalize (with copy attrs)

In [3]: c[:]
Out[3]: 
<MaskedColumn dtype='int64' format='%d' length=2>
1
2
```

But there are some errors like:
```
AttributeError: 'MaskedColumn' object has no attribute '_name'
```
Because of changing sub-class order. So, should I define these attribute inside `MaskedColumn`
please suggest

### CODE REVIEW

**Comment by pllim** [comment]
Failures are real.

**Comment by himanshupathak21061998** [comment]
> Failures are real.

Yes, I was not able to figure out. What to do next? I need some help here

**Comment by taldcroft** [comment]
@himanshupathak21061998 - thanks for looking into this tricky issue.  For me, I cannot offer much helpful advice without just digging into the problem deeply enough to probably solve it myself.  So I could review a working solution, but you may need to get there yourself unless @mhvk can jump in.

**Comment by mhvk** [comment]
@himanshupathak21061998 - this is tricky business. My main suggestion would be to try to do just one thing (e.g., the override of `data`) and see if for that the tests pass.

**Comment by himanshupathak21061998** [comment]
Thanks, @mhvk I would use this approach

**Comment by mhvk** [comment]
@himanshupathak21061998 - I was reminded of this because another PR (#6720), which needs it, is threatened with closure. When I looked at it, though, I realized that my original suggestion was unnecessarily complicated. Since this still was missing tests, I felt it would be easiest to just implement the change myself - see #8855.

I think it is simpler so will close this PR. But not without thanking you for taking it on! While not directly used, your effort definitely spurred us on to finally solve this problem. Thanks again!

**Comment by himanshupathak21061998** [comment]
Ok, I was just trying to solve but now I should try any other issue thanks for helping. I learned a lot because of this issue.

**Pull request closed without merging**
