### PR TITLE
WIP: Fix iteration inside wcslib

### PR DESCRIPTION
**Pull request by mdboom**
This is a fix for #3891, simply by reverting `sph.c` to an earlier version.  I think these changes were part of an attempt at optimization and not fixing any bug anyway.

We should wait and see what the official fix in wcslib will be (I've reported this to Mark Calabretta), but in the meantime, this provides us with an  alternative.

@olebole: This is a critical enough bug that you may want to apply it to the Debian package of wcslib 5.x if there is one already.

### CODE REVIEW

**Comment by olebole** [comment]
Thank you very much! I am currently however holding back wcslib-5.x (it is in experimental only) since I have no real pressure to upload, and I want to wait until it works with astropy.

**Comment by astrofrog** [comment]
@mdboom - thanks, I'm currently testing this in https://github.com/astrofrog/wcsaxes/pull/168

**Comment by embray** [comment]
Yikes, that's a bummer.  At least you tracked it down quickly.

**Comment by astrofrog** [comment]
Just to confirm, astrofrog/wcsaxes#168 passes again with these changes.

**Comment by cdeil** [comment]
+1 to merge this soon (now?)

**Comment by astrofrog** [comment]
@mdboom - when you said

> We should wait and see what the official fix in wcslib will be (I've reported this to Mark Calabretta), but in the meantime, this provides us with an alternative.

do you mean that we shouldn't merge this PR yet?

**Comment by mdboom** [comment]
There's a new release of wcslib today -- I will test it and either merge that one, or if that fails, merge this one.

**Comment by mdboom** [comment]
wcslib 5.7 introduces a number of other issues.  Merging this for now...

**Pull request merged**
