### PR TITLE
more explanation and a better example in the circular mean docstring

### PR DESCRIPTION
**Pull request by keflavich**

### CODE REVIEW

**Comment by keflavich** [comment]
This was an error I tried to quit out of when using hub on the command line; it didn't work.

I don't know what cirmean does, but it doesn't do what I thought it does.  I find the example unhelpful, but I can't provide a better one because I'm still clueless.

**Comment by mirca** [comment]
Hi @keflavich,

Assume that you have a set of ``n`` angles with respect to the ``x-axis``. Each angle uniquely maps a vector from the origin to the unit circle. Now, sum up those vectors. The angle of the resultant vector is precisely the output of ``astropy.stats.circmean``. Hope that helps :)

If you have time, please do submit a more helpful example 👍

**Comment by keflavich** [comment]
Thanks @mirca.  I was playing around with this further, and I still don't fully know when it is appropriate to use, but I think there should be an error catching case if the vectors sum to (nearly) zero.  e.g., 
`circmean([45,135,225,315]*u.deg)` should probably return NaN or raise an exception, since the average direction is undefined.  As is, I get a numerical result.

**Comment by mirca** [comment]
@keflavich Thanks for pointing this out, that's indeed an undesired behavior!

**Comment by mirca** [comment]
@keflavich Curiously, ``circmean`` function from R CircStats package is not aware of circular symmetric data either. But I still agree that we should raise a warning or something.

**Pull request closed without merging**
