### PR TITLE
#14818 Address ruff violations to rule C413 

### PR DESCRIPTION
**Pull request by hfcpeixoto**
This pull request is to address violations to Ruff's rule C413 listed explicitily in https://github.com/astropy/astropy/issues/14818. 

The sole violation still unadressed was present in submodule `io`.

The rule has been moved from `.ruff.toml` entirely.

This is part of a series of PRs split from https://github.com/astropy/astropy/pull/15239, following suggestions by @nstarman.

Solves part of issue #14818.
Is a followup of PR https://github.com/astropy/astropy/pull/15251.

### CODE REVIEW

**Review by nstarman — APPROVED** [review]
Thanks @hfcpeixoto! This also looks good to go.

**Comment by nstarman** [comment]
@hfcpeixoto did you mean to open this as a draft?

**Comment by hfcpeixoto** [comment]
@nstarman in fact yes, I wanted to wait for the CI runs to pass before opening the PR for review. I guess everything is fine now.

**Comment by pllim** [comment]
> did you mean to open this as a draft?

> I wanted to wait for the CI runs to pass before opening the PR for review

@nstarman , why does this look like the conversation that you and I just had in another PR that you opened? 😆

**Comment by pllim** [comment]
Thanks, all!

**Pull request merged**
