### PR TITLE
Modify JointFitter docs to allow doctesting

### PR DESCRIPTION
**Pull request by karllark**
### Description

This pull request updates the recent astropy modeling JointFitter documentation to allow the embedded code to be doctested.  In addition, the plot is now generated on-the-fly instead of a static plot.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by karllark** [comment]
Doctest failing as *scipy* is not found.  Hard to doctest JointFitter code if scipy is not installed.  Help requested.

**Comment by pllim** [comment]
@karllark , you can use `.. doctest-requires:: scipy`. Please see https://github.com/astropy/pytest-doctestplus and other similar examples in the codebase. Thanks!

**Comment by pllim** [comment]
Also might be relevant:

* #12448

**Comment by karllark** [comment]
> @karllark , you can use `.. doctest-requires:: scipy`. Please see https://github.com/astropy/pytest-doctestplus and other similar examples in the codebase. Thanks!

Thanks for this suggestion.  Added this and hoping this solves the problem.

I find it counter-intuitive that scipy is not there for the doctests, but is there for plotting when the docs are built.  Is it possible to add scipy to the doctests for the CI doctesting at least?  Would make sense to me at least regardless of the result of #12448.

**Review by nden — APPROVED** [review]
Thanks!

**Comment by pllim** [comment]
Thanks!

**Pull request merged**
