### PR TITLE
Fix indexing of fits.Header with Numpy integers

### LINKED ISSUE #11382: FITS header indexing should support numpy ints. Incorrect error type
### Description
Indexing an `astropy.io.fits.Header` using elements of an integer `numpy` array fails because `np.int64` is not `int`.

### Expected behavior
I would expect numpy integers to be treated/accepted as valid header indices.

### Actual behavior
Attempting to index a header using, i.e., `np.int64` raises `ValueError` which seems to be the wrong type of error to raise. I think it should have been `TypeError`.

### Steps to Reproduce

```python
In [1]: import numpy as np

In [2]: from astropy.io import fits

In [3]: hdr = fits.Header([('card1', 1), ('card2', 2)])

In [4]: hdr
Out[4]:
CARD1   =                    1
CARD2   =                    2

In [5]: hdr[np.int64(1)]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-f794962e8ec2> in <module>
----> 1 hdr[np.int64(1)]

~/virtualenv/py37/lib/python3.7/site-packages/astropy/io/fits/header.py in __getitem__(self, key)
    154             keyword = key
    155
--> 156         card = self._cards[self._cardindex(key)]
    157
    158         if card.field_specifier is not None and keyword == card.rawkeyword:

~/virtualenv/py37/lib/python3.7/site-packages/astropy/io/fits/header.py in _cardindex(self, key)
   1698         else:
   1699             raise ValueError(
-> 1700                 'Header indices must be either a string, a 2-tuple, or '
   1701                 'an integer.')
   1702

ValueError: Header indices must be either a string, a 2-tuple, or an integer.
```

I think that when an `isinstance` check fails the more natural error to raise is a `TypeError` instead of the `ValueError` - see https://github.com/astropy/astropy/blob/d971b1c48231d38665229d0d18b4245766b4b033/astropy/io/fits/header.py#L1708-L1730

### System Details
```
Darwin-19.6.0-x86_64-i386-64bit
Python 3.7.10 (default, Feb 26 2021, 10:16:00)
[Clang 10.0.0 ]
Numpy 1.20.1
astropy 4.2
Scipy 1.6.1
Matplotlib 3.3.4
```

### PR DESCRIPTION
**Pull request by saimn**
Fix #11382. cc @mcara

### CODE REVIEW

**Comment by mcara** [comment]
I think the fix is fine in allowing `numpy.int` types to be used for indexing. Just one question: should something like this be allowed: `hdulist[bool(1)]`? That is, should boolean types be allowed to be used as indices?

**Comment by saimn** [comment]
> should boolean types be allowed to be used as indices?

I would say no but Python boolean are integers so you can index a list with True/False, and the same for `Header`.

**Comment by pllim** [comment]
FWIW, I am also running the cron CI here, just in case. Please be on the lookout for failures for those jobs (except the unrelated ones we already know about).

**Review by mhvk — APPROVED** [review]
Looks good!

**Review by mcara — APPROVED** [review]

**Pull request merged**
