### PR TITLE
Port spectral-cube's FITS-WCS frame transformation utility into astropy.wcs

### PR DESCRIPTION
**Pull request by keflavich**
This PR brings the frame transformation code, implementing the [FITS
paper](http://adsabs.harvard.edu/abs/2006A%26A...446..747G), into astropy.wcs.
There might be some import cleanup, but this is known to work.

### CODE REVIEW

**Comment by keflavich** [comment]
cc @nmearl @astrofrog

**Comment by keflavich** [comment]
Also cc @saimn - you might want access to this in mpdaf

**Comment by pllim** [comment]
Failure is related.

**Comment by bsipocz** [comment]
ping @keflavich. Do you plan to finish this up for 3.2, or shall we remilestone?

**Comment by keflavich** [comment]
Push it back.  I don't remember where I left this.

**Pull request closed without merging**
