### PR TITLE
Set -e so errors fail benchmark build

### LINKED ISSUE #16671: Benchmark build is broken but still reports a green status
### Description

https://github.com/astropy/astropy/actions/runs/9792120669/job/27037295228?pr=16670#step:7:182

This is a double whammy, it's broken but it's still green.

### Expected behavior

_No response_

### How to Reproduce

_No response_

### Versions

_No response_

### PR DESCRIPTION
**Pull request by Cadair**
Fixes #16671

### CODE REVIEW

**Comment by pllim** [comment]
The RTD failures make no sense. Should have been fixed a while ago. Can you please rebase just to be sure?

**Comment by pllim** [comment]
Also why did it start failing? Pretty sure it used to work.

**Comment by Cadair** [comment]
yeah my fix didn't fix. I don't know if asv isn't throwing the right exit code or not, but :shrug: The fix for the issue is simple enough, figuring out why it isn't failing though seems more challenging.

**Comment by pllim** [comment]
So is the benchmark stuff fixed upstream? I cannot tell where that error is coming from. Can we close this without merge?

**Comment by pllim** [comment]
Is this related?

```
Couldn't load asv.plugins._mamba_helpers because
No module named 'libmambapy'
```

**Comment by pllim** [comment]
RTD failure is unrelated. I think I fixed it. Definitely need SQUASH AND MERGE.

**Comment by pllim** [comment]
Since I touched build requirements, gonna run wheel jobs too, just in case.

**Comment by astrofrog** [comment]
@pllim the fix to the build requirements looks good, but we still need to figure out how to catch asv errors in future right? Or is that fixed?

**Comment by pllim** [comment]
> still need to figure out how to catch asv errors in future right?

No, that isn't fixed. Stuart's `-xe` did not help. Any ideas?

**Comment by pllim** [comment]
Wow... unrelated but a little shocking if true.

```
| Change   | Before [dbdafb85]    | After [cab33dba]    |   Ratio | Benchmark (Parameter)          |
|----------|----------------------|---------------------|---------|--------------------------------|
| +        | 41.3±0.1μs           | 85.4±50μs           |    2.07 | units.time_quantity_times_unit |

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
Error: PERFORMANCE DECREASED.
```

**Comment by pllim** [comment]
The "performance decrease" might not be real. I don't see anything shocking at https://spacetelescope.github.io/bench/astropy-benchmarks/#units.time_quantity_times_unit

**Comment by pllim** [comment]
So should we merge this or wait for your investigation?

**Comment by astrofrog** [comment]
Might be superseded by https://github.com/astropy/astropy/pull/16705

**Comment by pllim** [comment]
Indeed. Thanks!

**Pull request closed without merging**
