### PR TITLE
WIP: Add wheel building and release on Travis CI

### PR DESCRIPTION
**Pull request by astrofrog**
*This is a work in progress of an alternative to https://github.com/astropy/astropy/pull/10719 - this PR tries to build the wheels on Travis*

### CODE REVIEW

**Comment by pllim** [comment]
Hmm...
```
  ERROR: Could not find a version that satisfies the requirement oldest-supported-numpy (from versions: none)
  ERROR: No matching distribution found for oldest-supported-numpy
  WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.
  You should consider upgrading via the '/opt/_internal/cpython-2.7.18-ucs2/bin/python -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/_internal/cpython-2.7.18-ucs2/bin/python /opt/_internal/cpython-2.7.18-ucs2/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-OL9qoH/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools setuptools_scm wheel cython==0.29.14 jinja2==2.10.3 oldest-supported-numpy extension-helpers Check the logs for full command output.
```

**Comment by pllim** [comment]
p.s. If this works, I think this would probably gain support from @bsipocz and @mhvk et al.

**Comment by astrofrog** [comment]
I know how to fix this, just need to find a minute to do so :)

**Comment by mhvk** [comment]
Looks very promising!! I couldn't really ask for a more minimal change in .yml :fireworks:

Which I guess goes to show that all the magic is in `cibuildwheel`, but that's only good, it means we can keep the discussion of how to build wheels separate from where to build them.

**Comment by Cadair** [comment]
Don't get too excited @mhvk it's not done yet. 

It's easy to call cibuildwheel to create the wheels, but you also have to do (at least) the following to have parity with what is completed in #10719:

* handle building the tarball
* handle combining all the artifacts into one place for the upload job
* auth with pypi
* upload to pypi
* support stripping dev version strings if you want nightlies, and handle alternative PyPI endpoints for nightlies.

**Comment by astrofrog** [comment]
@Cadair is correct that this will require more work, and in particular it's important we only upload all the wheels once they all pass to avoid incomplete releases. I'm happy to keep trying to fix it, but given my current time restrictions my work on this is very slow, and unless someone fixes astropy-wheels or we go with the solution in #10719 (or someone else wants to try and help get this working), the 4.1 release will continue to be delayed.

**Comment by pllim** [comment]
> 4.1 release will continue to be delayed

Can't we release 4.1 the old school way? Is this really a blocker?

**Comment by Cadair** [comment]
AFAIK the current wheel building infrastructure is broken.

**Comment by pllim** [comment]
Argh... As a compromise, perhaps we can merge in a fix that you have time to complete the fastest, and revisit infrastructure consolidation later? We already have gazillion infrastructure thingies, gazillion plus one is better than no release.

**Comment by bsipocz** [comment]
I don't feel it's fair calling it broken, when it's just rackspace that is gone?

 https://github.com/MacPython/astropy-wheels/issues/66

**Comment by astrofrog** [comment]
@bsipocz - yes indeed it's mainly that the uploading is broken and needs to be fixed, not the building itself. We 'just' need someone to fix it though and it was much faster for me to do #10719 (which took very little time as it was almost a copy/paste from other projects) which I thought was a pragmatic solution which also solves other issues such as the frustration of having a separate repo. The present PR though is a rabbit hole and I don't have time to work on it further for now.

**Comment by bsipocz** [comment]
Hmm, technically wheels are distributions, so there should be plenty of 'someone' available, according to the team page. (OK, i see this is somewhat unfair to point this out here, again, like a broken record).

**Comment by mhvk** [comment]
Hmm, like @pllim, I'm confused; is it just conda builds (for mac?) that are the hold-up? Or can the package also not be uploaded to pypi (building it on one's own machine if that's what it takes)?

Among the indeed very large number of people listed as "distribution coordinator", I note that two are for linux (Debian, Redhat), who quite reliably do their work after we call something a release (tagging it would probably suffice...). Could we perhaps move to a similar model for conda/mac/windows? It would be nice both to have responsibilities clearer and to decouple testing code on various platforms from actually packaging it.

Which probably means I should be clear that I have no objection whatsoever to azure pipelines being run if they are *not* integrated in our general testing framework (i.e., just used to package for platforms I do not care about ;-). Especially if that means we can have a release!

**Comment by bsipocz** [comment]
The name of macpython is misleading, it's the infrastructure to build all the wheels for pypi. The sdist and conda packaging are a separate questions. 

And if you go back and look, it's basically only one of the distributions who consistently participates in the release procedure, tests RCs and provide feedback, opens issues for all kinds of weird things surfacing due to all the exotic architecture, and contribute bug fixes.

**Comment by saimn** [comment]
Rackspace is just needed to put the wheels somewhere at the end of the build process, in order to download them and put them manually to PyPI, right ?
If help is needed, which was not clear until now ;), I would be happy to have a look. But I guess this means having access to the repo secrets, and same for Travis and AppVeyor (this should be the case based the Github permissions?). Who can create token on anaconda.org ?
Another option I have been using for mpdaf is to upload the wheels to the Github releases.

**Comment by saimn** [comment]
Maybe the "distribution coordinator" name is confusing, the people in this role are basically the people taking care of packaging in various distributions (Archlinux, Conda, Fedora, Debian, and I think Macports).

**Comment by astrofrog** [comment]
@saimn information about the secrets can be found at https://github.com/MacPython/astropy-wheels/issues/66 - but indeed if it becomes difficult to fix this quickly we could just easily upload to an s3 bucket of our own...

**Comment by astrofrog** [comment]
And yes we then just upload the wheels manually to PyPI

**Comment by astrofrog** [comment]
If we want to keep the astropy-wheels repo we should probably also move it under the astropy organisation otherwise it’s difficult for us to administrate and add new people...

**Comment by pllim** [comment]
Wow, when you sort this out, please make another chart to complement astropy/project#122 ; i.e., expanding the "Release extravaganza" box in a separate chart.

**Comment by astrofrog** [comment]
As a side note I think it’s quite problematic that we need to rely this much on a separate org for doing our releases which is why I’d like to build the wheels in house...

**Comment by mhvk** [comment]
@astrofrog - indeed, even while arguing that ideally we leave building to those who are interested in a given platform/architecture, I can very much see the argument for being independent of others... But mostly I think I've never really appreciated what is involved for a project that includes compiled code, so I better stop commenting!

**Comment by astrofrog** [comment]
I'm going to close this since #10719 was merged

**Pull request closed without merging**
