### PR TITLE
Handle ruff error PLW0602.

### PR DESCRIPTION
**Pull request by draghuram**
### Description

This pull request is to address ruff error PLW0602. See #15317 for related discussion. 

Fixes #<Issue Number>

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by nstarman** [comment]
Can you try rebasing on main and pushing again? The RTD error looks to be unrelated but we should confirm this.

**Review by nstarman — APPROVED** [review]
Thanks @draghuram. I can confirm by looking at https://github.com/astropy/astropy/blob/b9b552a68038f9513616364226a4f98f2c1e0b71/astropy/utils/data.py#L1777 that `_tempfilestodel` is not used in any way that requires it to be a global variable.

**Comment by pllim** [comment]
Does appending to a global list not require it to be declared so?

**Comment by draghuram** [comment]
> Does appending to a global list not require it to be declared so?

It doesn't. The only time you need to declare "global" is when the name is being assigned to.

**Comment by draghuram** [comment]
Thanks.

To clarify about empty commit, I did do rebase and force pushed the commit. For some reason, PR was not updated. Some other people faced same issue and one of the workarounds suggested was to push an empty commit. I should mention that this problem is very rare.

**Pull request merged**
