### PR TITLE
Change references to build_sphinx to build_docs

### PR DESCRIPTION
**Pull request by embray**
Following on from astropy/astropy-helpers#161, which added an alias to the `build_sphinx` command to simply `build_docs`, change references to `build_sphinx` in the documentation to the less cryptic-looking `build_docs`.

We shouldn't jump the gun on merging this PR yet.  For one, Astropy hasn't even updated the astropy-helpers submodule to point to a version that includes this alias.  And even once that happens this could be confusing for contributors working on older branches of astropy, or to contributors to affiliated packages that have not yet updated astropy-helpers (though I did add a note in the developer docs to try `build_sphinx` if `build_docs` doesn't work).

Just front-loading this PR so that it's ready for when we feel it's safe to make the switch.

### CODE REVIEW

**Comment by embray** [comment]
One of the travis builds failed for no particular reason.  We should really figure out how to get docs-only builds working in Travis, hmm...

**Comment by eteq** [comment]
:+1: from me - as you said the failure is a red herring so this is fine and I'll go ahead and merge.

**Comment by embray** [comment]
This wasn't supposed to be merged yet.  See the note:

> We shouldn't jump the gun on merging this PR yet. For one, Astropy hasn't even updated the astropy-helpers submodule to point to a version that includes this alias. And even once that happens this could be confusing for contributors working on older branches of astropy, or to contributors to affiliated packages that have not yet updated astropy-helpers

And the milestone: Future

**Comment by embray** [comment]
Not sure what to do--if others are fine with it I'll just leave it and mark it as v1.1.  Otherwise if more people agree it should be held off on I can revert.  I'm mostly fine either way, though I felt like it was better to wait on this.

**Pull request merged**
