### PR TITLE
Revert skipping doc tests that fail only on Windows Py 2.6

### LINKED ISSUE #3853: Problem with #doctest: +FLOAT_CMP on Windows Py 2.6 ?
PR #3731 at ed8a3e197bc7be3b0e13 failed only on Windows Py 2.6 with an exception in doc testing.  There were no other test failures on any platform / configuration.  I don't have a Windows platform to debug or try to reproduce.

Here is the log:

https://ci.appveyor.com/project/Astropy/astropy/build/1.0.1509/job/65hvtqa4x4h7m3b6

And the error at the end:

```
================================== FAILURES =================================== 
_________________________ [doctest] access_table.rst __________________________ 
_pytest.runner:137: in __init__ 
>   ??? 
_pytest.runner:124: in <lambda> 
>   ??? 
_pytest.main:161: in call_matching_hooks 
>   ??? 
_pytest.core:380: in pcall 
>   ??? 
_pytest.core:387: in _docall 
>   ??? 
_pytest.core:288: in execute 
>   ??? 
_pytest.runner:86: in pytest_runtest_call 
>   ??? 
astropy\tests\pytest_plugins.py:156: in runtest 
>           raise_on_error=True, verbose=False, encoding='utf-8') 
C:\conda\envs\test\lib\doctest.py:1973: in testfile 
>       runner.run(test) 
C:\conda\envs\test\lib\doctest.py:1736: in run 
>       r = DocTestRunner.run(self, test, compileflags, out, False) 
C:\conda\envs\test\lib\doctest.py:1391: in run 
>           return self.__run(test, compileflags, out) 
C:\conda\envs\test\lib\doctest.py:1269: in __run 
>               if check(example.want, got, self.optionflags): 
astropy\tests\output_checker.py:154: in check_output 
>           return self.normalize_floats(want, got, flags) 
astropy\tests\output_checker.py:117: in normalize_floats 
>           got = got % tuple(nw_) 
E           TypeError: a float is required 
 1 failed, 9031 passed, 111 skipped, 78 xfailed, 2 xpassed in 1118.24 seconds = 
Command exited with code 1
```

### PR DESCRIPTION
**Pull request by taldcroft**
This reverts commit 8c850ef5b3a8d3572ae56091c3e54456ced5ffcb.

Closes #3853.

### CODE REVIEW

**Comment by embray** [comment]
Looks like one of the re-enabled tests in `docs/table/access_table.rst` now fails.

**Comment by mhvk** [comment]
Might this be related one way or another with having `%6.3f` in the string to be looked at? Though no idea why it then would work fine for linux/mac.

**Comment by mhvk** [comment]
Since this didn't quite work yet, I removed the 'ready-for-final-review' label. However, I didn't have time to look into what exactly didn't work...

**Comment by taldcroft** [comment]
Closing, Py 2.6 is no longer supported.

**Pull request closed without merging**
