### PR TITLE
Really deprecate clobber keyword in FITS now

### LINKED ISSUE #5773: Remove pending for clobber in v2
This is a follow up of #5761, as discussed. This will reintroduce deprecation warnings, as in 1.3.0 but undone in 1.3.1 due to complains.

### PR DESCRIPTION
**Pull request by pllim**
Remove "pending" status introduced by #5761. Fix #5773.

Note: I canceled Travis CI on purpose to save resources (long queue). Check https://travis-ci.org/pllim/astropy/builds/242938845 for actual test result.

### CODE REVIEW

**Comment by bsipocz** [comment]
Adding the ``last-before-release``, with the same logic I mentioned for the analytic functions, namely that this is really a last-before-branching/RC1, so affiliates will run into issues within a bit shorter timerange.

**Comment by pllim** [comment]
Travis tests on my fork passed.

**Comment by bsipocz** [comment]
@pllim - Revisiting my arguments above, shall we just start merging these deprecations? So if any issue comes up, we get some extra time to fix it without delaying RC too much.

**Comment by pllim** [comment]
It is your call since you are doing the release. Personally I am okay with merging now. If people complain, they can pin to 1.3.3.

**Comment by bsipocz** [comment]
OK. Lets do this and the rest as well.

**Comment by saimn** [comment]
Thanks for taking care if this @pllim ! (I see only now your review request, sorry!)

**Comment by MSeifert04** [comment]
LGTM!

I'm on vacation until monday so I'm sorry I haven't seen this sooner. :(

**Pull request merged**
