### PR TITLE
Added subsampling to nddata.utils.extract_array

### PR DESCRIPTION
**Pull request by fred3m**
PSF photometry and other image reduction can require one to extract a subsampled array. The extract_array function has been modified to allow users to subdivide each pixel by a specified number of subpixels using scipy.interpolate. An option has also been added to allow the function to return the indices to the subsampled pixels.

If the user does not specify any of the new parameters, the behavior of the function is the same as before the changes.

### CODE REVIEW

**Comment by mwcraig** [comment]
Thanks, @fred3m, I should get a chance to look at this tomorrow.

**Comment by larrybradley** [comment]
@fred3m  My humble suggestion is that the subsampling belongs in a separate general-purpose function that operates on any arrays (not just "extracted" arrays).

**Comment by fred3m** [comment]
@larrybradley, I see your point but I still think that subsampling should be included in the extract_array function because the most likely use case is to extract a subsampled patch centered on an objects position (which is unlikely to be an exact array coordinate). Most of the machinery is in the extraction and determination of whether or not the patch is on the interior or edges of the image, not the interpolation, so I think it is important to include subsampling in array extraction. Subsampling an entire array is really a different (and much simpler) use case that could have it's own function if others had a desire for this feature but the machinery would be slightly different.

**Comment by mwcraig** [comment]
@fred3m -- sorry I dropped the ball on this. Did you want to work on this more? Should it be closed for now? Would you like me to do a review of what is here?

**Comment by fred3m** [comment]
It's up to you. I'm working on the LSST pipeline now so I'm not actively developing my pipeline anymore, which required this. But if other people would find it useful I'd be happy to clean up and implement this in astropy.

**Comment by mwcraig** [comment]
@fred3m -- I would like to get this in at some point but it won't make it for 1.3, unfortunately.

**Pull request closed without merging**
