### PR TITLE
Add get_moon function to astropy.coordinates using the erfa.plan94

### PR DESCRIPTION
**Pull request by sharadmirani**
Trying to replicate the `get_sun ` function to add the `get_moon` function using `erfa.plan94` to get the position and velocity of the Earth-Moon Barycenter.

### CODE REVIEW

**Comment by pllim** [comment]
@eteq , here is another implementation for the same topic as #4724. FYI.

**Comment by pllim** [comment]
This needs test and change log.

**Comment by sharadmirani** [comment]
I am trying to run the following test. The function is working fine for an array of times. But, since we are using the data for the EMB, the error gets magnified by a factor of (M<sub>earth</sub> / M<sub>moon</sub> + 1) = 82.25. Due to this, the position given by this `get_moon` function is quite inaccurate.

```
from astropy.coordinates import get_moon as gm
from astropy.time import Time

t = Time(["2016-03-27 11:30:00", "2016-03-27 17:00:00"])
moon_pos = gm(t)
print moon_pos
```

Output:
```
<SkyCoord (GCRS: obstime=['2016-03-27 11:30:00.000' '2016-03-27 17:00:00.000'],
obsgeoloc=[ 0.  0.  0.] m, 
obsgeovel=[ 0.  0.  0.] m / s): (ra, dec, distance) in (deg, deg, AU)
[(248.16744252, -20.41678509, 0.00381568),
 (250.1811754, -20.61313744, 0.00385118)]>
```

Thus, I am trying to find a better alternative in the `erfa` functions. Do you have any suggestions?

**Comment by mhvk** [comment]
@sharadmirani - I think for the moon there is a better approach using `erfa.faf03` being pursued in #4724. As I wrote on the mailing list, I think for this PR I would encourage you to change it to a `get_planet` function, as I think that would be very useful to have too.

**Comment by eteq** [comment]
@mhvk @sharadmirani Actually, I think this *might* be a better approach than #4724 - #4724 is not correct 

cc @bmorris3, as he has a partial (or maybe complete?) version of `get_moon` in astroplan - not the same implementation, but still useful for comparison.

**Comment by bmorris3** [comment]
The `get_moon` implementation in astroplan at present uses `pyephem`, and therefore won't be useful to this code review. 

However, I'm soon going to make a PR that uses `jplephem`. I need to refine the API a bit, but it's a working means of querying the DE430 JPL ephemerides. If `astropy` chooses to support the dependency on `jplephem`, then my PR will implement the moon and planets in a self-consistent way (but will it be consistent with the Sun/Earth reference frames as implemented in ERFA, I don't know).

**Comment by bsipocz** [comment]
This can be closed since #4890 is merged.

**Comment by mhvk** [comment]
Indeed, will close this. But thanks @sharadmirani for the trial; we'll also still get a version using `plan94`.

**Pull request closed without merging**
