### PR TITLE
Fix a bug that caused writing to FITS of Table objects that had index columns to fail

### PR DESCRIPTION
**Pull request by astrofrog**
Edit: THIS REQUIRES https://github.com/astropy/astropy/issues/9009, keep open while that is addressed.

Before this fix, the following failed:

```python
>>> from astropy.time import Time
>>> from astropy.table import Table
>>> time = Time(['2016-03-22T12:30:31', '2016-03-22T12:30:38', '2016-03-22T12:34:40'])
>>> table = Table()
>>> table['time'] = time
>>> table.add_index('time')
>>> table.write('test.fits', overwrite=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/table/table.py", line 2592, in write
    io_registry.write(self, *args, **kwargs)
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/io/registry.py", line 560, in write
    writer(data, *args, **kwargs)
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/io/fits/connect.py", line 388, in write_table_fits
    table_hdu = table_to_hdu(input, character_as_bytes=True)
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/io/fits/convenience.py", line 470, in table_to_hdu
    table, hdr = time_to_fits(table)
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/io/fits/fitstime.py", line 533, in time_to_fits
    newtable.replace_column(col.info.name, Column(jd12, unit='d'))
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/table/table.py", line 1796, in replace_column
    raise ValueError('cannot replace a table index column')
ValueError: cannot replace a table index column
```

The solution is to remove the index columns.

@taldcroft - is there a better way to just remove all indices from a table?

### CODE REVIEW

**Comment by saimn** [comment]
It would be more generic to handle this case in `Table.replace_column` instead of raising an error. Why not dropping the index there, maybe with a keyword or warning ?

**Comment by astrofrog** [comment]
@taldcroft - do you have any thoughts on this?

**Comment by astrofrog** [comment]
@saimn - on further thoughts, I guess my thinking is that Table has already made a choice to raise a clear exception in this case, and this PR fixes a bug in the FITS code that uses that. Changing the behavior in Table would actually be an API change. So I personally think we should just treat this as a bug fix and not modify Table.

**Comment by taldcroft** [comment]
This looks fine as a bug fix.  Ideally the right answer is to serialize the index so it round-trips, which would make generating the index more useful since it would persist.  In theory the machinery is mostly there, but it probably would not be trivial in the end.

**Comment by saimn** [comment]
@astrofrog - I can understand your reasoning, but for me it is a Table thing, not FITS or Time. Looking back in time, https://github.com/astropy/astropy/pull/4090#issuecomment-143805381 shows - I think - that there is no real reason for raising an error in this case. 
I don't know what would the good solution when replacing a column with an index (recreating all the indexes using this column may be tricky), but a simple solution could be to add a `drop_index` keyword, which would not change the default behavior.
And maybe another option would be to remove the use of `replace_colum`, I'm not sure if it is necessary here ? At least replacing it with `newtable[col.info.name] = jd12` does not cause a failure in the unit tests.

**Comment by saimn** [comment]
@taldcroft - the serialization is not the issue (it seems that indexes are dropped when writing tables to fits), the crash happens when using `replace_column` here:

https://github.com/astropy/astropy/blob/1a41c94c57e5c966e189049dab867da70bc2aa43/astropy/io/fits/fitstime.py#L527-L533

**Comment by astrofrog** [comment]
Ok let's delay this for now, I don't have time to work on it more for 3.1

**Comment by taldcroft** [comment]
From #8247, I think that for the current code one needs to make a copy of any columns that are indexed:
```
                # Make a light copy of table and clear any indices
                new_cols = []
                for col in tbl.itercols():
                    new_col = col_copy(col, copy_indices=False) if col.info.indices else col
                    new_cols.append(new_col)
                tbl = tbl.__class__(new_cols, copy=False)
```
See #8246.

The test for this should include ensuring that the original table was not changed (i.e. the indices dropped).  

Note that the problem with indices only occurs for mixins.  Doing a table copy with `copy_data=False` and then removing indices on the copy does not touch the original columns because `Column` copy is a new object with a new `info` (and indices) but a reference to the original data array.  But for mixin columns, the new table copy gets literally the same reference.  That's because right now there is no requirement that mixin columns know how to make a light copy of themselves (new metadata, original array data).

**Comment by taldcroft** [comment]
I re-opened this as I think that this approach is OK and fixes a real issue.

The only outstanding problem is the [comment above](https://github.com/astropy/astropy/pull/8077#issuecomment-445254906) that the current code actually corrupts the original table by removing indices on `newtable`.  That's basically a bug that I plan to fix in #9009.

**Comment by bsipocz** [comment]
@astrofrog - could you please rebase and address the comment to make it ready to be merged?

**Comment by taldcroft** [comment]
@bsipocz - I think you just missed that this would be best done by waiting on a fix for #9009, at which point the table copy (with `copy=False`) will do the right thing.  

However, there definitely should be a test that this operation does not corrupt the original table.  That will fail right now, but will start working once #9009 is fixed.

**Comment by bsipocz** [comment]
Oh, indeed. Then I add the keep-open here, as either that or a rebase that makes sure this doesn't get closed again when the bot runs next time.

**Comment by taldcroft** [comment]
@astrofrog et al. - I think should be good now, please review.  The crux lines of code depend on table improvements in 4.0-dev, so I don't recommend trying to backport.

**Comment by bsipocz** [comment]
@taldcroft - There are no more backports except critical fixes like the one we need for iers :)

**Comment by bsipocz** [comment]
@taldcroft - #9009 still seems to be relevant, is that not an issue for this any more?

**Comment by taldcroft** [comment]
#9009 is still relevant because it will make it possible to improve the implementation here to avoid making any copies.  Right now it does copy any mixin columns that have indices.  So I put in a breadcrumb in #9009 to come back here and have a look.

**Pull request merged**
