### PR TITLE
Refactor modeling to be stricter about Units

### PR DESCRIPTION
**Pull request by Cadair**
This PR is a work in progress attempt at resolving some of the issues faced in #6952 by being much stricter about what you can do with units on `Model`s.

The things this PR tries to accomplish are:

* Make the following properties not user writeable:
  - `input_units`
  - `output_units`
  - `input_units_allow_dimensionless`
  - `input_units_strict`

* Disallow the mixing of quantity and non-quantity parameters
```python
    g = Gaussian1D(mean=3 * u.m, stddev=3 * u.cm, amplitude=3)
    g(10*u.m)
```
is no longer allowed (errors on call not instantiation).

* Disallow the mixing of quantity and non-quantity arguments (to `__call__`).

* Disallow calling a model with or without Quantities if the model was created with or without parameters as quantites.

i.e both:
```python
    g = Gaussian1D(mean=3, stddev=3, amplitude=3)
    g(10*u.m)
```
and
```python
    g = Gaussian1D(mean=3 * u.m, stddev=3 * u.cm, amplitude=3 * u.J)
    g(10)
```
are invalid.

---

There are however, major issues with these rules and the way that default parameters are handled. Taking `Gaussian1D` as an example, it takes three parameters mean, stddev and amplitude. All of which have dimensionless defaults. As currently implemented the following now breaks:

```python
    g = Gaussian1D(mean=3 * u.m, stddev=3 * u.cm)
    g(10*u.m)
```
because this is equivalent to:
```python
    g = Gaussian1D(mean=3 * u.m, stddev=3 * u.cm, amplitude=1)
    g(10*u.m)
```

This means we need to decide on what we want the handling of:
```python
    g = Gaussian1D(mean=3 * u.m, stddev=3 * u.cm, amplitude=1)
    g(10*u.m)
```
to be, because as far as I can tell, there is no way to know if a parameter *has it's default value or has been explicitly set with that value*?

We could either:

1. Assume all dimensionless input is implicitly `u.Quantity(value, u.one)`.
2. Error and force the user to be explicit about what they mean.
3. Don't error at all and reduce this PR to just making properties read-only.

@astrofrog @nden

### CODE REVIEW

**Comment by pllim** [comment]
Please make sure this does not make creating compound models with units a pain. 😄

**Comment by Cadair** [comment]
@pllim the motivation is the opposite. In that there is a lot of flexibility in the current system, and it means that weird things happen, which makes the compound model code harder.

Also, the objective here is to get people to be more explicit about units, which I know some people think is "a pain". Do you have specific use cases in mind?

**Comment by pllim** [comment]
My use cases are all in `synphot`. When you think this is ready, I can take it for a spin over there. Thanks!

**Comment by astrofrog** [comment]
I think that automatically adding ``u.one`` units to dimensionless input makes sense.

**Comment by Cadair** [comment]
I have spent two days on this insanity at this point, I can see no sensible way of doing any of the following without breaking something serious:

* Raising expceptions on instantisation or call based on quantity-ness of parameters
* Defaulting Parameters to `u.one`.

I did manage to default all inputs to `u.one` in the case of mix and match quantities, so we could also error on this: https://github.com/Cadair/astropy/commit/48fc760b5bf19594dc6c2fbad5f2b13bd5fbfe95

**Comment by Cadair** [comment]
At this point, it would probably be easier just to enforce that all parameters, input and outputs have to be Quantity always 😆

**Comment by pllim** [comment]
>  input and outputs have to be Quantity always

:scream: 

Might not be a good idea. Some people might not want the overhead of `Quantity` handling.

**Comment by Cadair** [comment]
It's ok @pllim I was joking. 😄 

(We do that in SunPy though, you will use units and you will like it)

**Comment by perrygreenfield** [comment]
I guess I should mention that I am working on a large update to models (first to see if it works; I didn't want to get bogged down in discussions about whether this or that behavior or feature was right). I can summarize that elsewhere. My initial work was to change how parameters worked, and it turned out that the current implementation of compound models was essentially inconsistent with that, I folded in the new approach to compound models I had discussed with some. But in working with the unit unit [yes] tests I saw there were some problems with units and so started thinking about those (making no changes so far). 

But I'll take this as an opportunity to state my opinion on how units should work (as well as I understand them). This is often different than the current unit behavior or plans for unit behavior.

First, a general statement about priorities. To me, by far the most important use for units is convenience in use in evaluating models. [break to get my armor on] I would give support for units in fitting relatively low priority. In fact, I'd suggest dropping support for use with fitting. 

Here are some proposals for changing behavior of units in the current package:

At the parameter level:

I find the current raw_unit naming to be confusing. I'd suggest changing that to internal_unit. That is to say, unit is what the user supplies, internal_unit is the value in the unit system the Parameter expects (dealt with through the _setter and _getter methods. The model evaluation expects to use the internal_unit representation. Currently the most common use of this is conversion between degrees and radians (degrees for the user, radians internally). This is basically just a naming issue.

One thing I think should change is that it should not be possible to assign new units to a Parameter instance (E.g. this currently works:

   g = Gaussian1D(1 * u.J, 1 * u.m, 0.1 * u.m)

   g.amplitude = 2 * u.s
   g.mean = 2 * u.Jy
  
I can't see the justification for allowing this. If a model with different unit support is needed, make a new one, don't mutate an existing one. Seems like this is asking for trouble.

At the models level:

- input_units is not required (it can be None), but if it is supplied, output_units must be supplied (I'm suggesting that instead of returned_units for consistency with other uses of the name in the code). It cannot be changed once instantiated (the model code can override this if it wants if it knows that there is a direct relation between some parameters and the input).
- get rid of input_units_strict. Always convert to input_units
- get rid of input_units_dimensionless. Allowing this when units are expected is likely to cause many errors of usage. Just force people to be explicit with the inputs if input_units exists
- output_units can be changed after instantiation

Regarding enforcement of unit consistency. Basically I'm suggesting that there isn't any in instantiation. People should be free to mix parameters with units and those without (Gaussian1D is a good example where amplitude does not need to have units even if mean and stddev do. Likewise the user is free to define input_units or output_units to be inconsistent with the model and parameters. And they are free to provide Parameter units that are inconsistent. These sorts of errors will raise an exception on evaluation. We should provide tools in the classes or package to make it easy to identify what caused the error and where  it would have happened in a compound expression. I would like to avoid loading the code with lots of analysis about what is consistent (or unnecessary test evaluations) or be overly restrictive about what is permitted.

**Comment by pllim** [comment]
@perrygreenfield , that seems important, so I opened a new issue with it at #7220 . Thanks!

**Comment by nden** [comment]
Too many issues are raised here. To facilitate keeping track I'll attempt to split them in a sensible way (possibly in separate issues). 

Starting with the easiest one: please just comment with a thumbs up/down on renaming `raw_unit` to `internal_unit` and `_raw_value` to `_internal_value`.  Both are used internally only so this change does not affect any public functions.

@astrofrog @Cadair @pllim

**Comment by Cadair** [comment]
Can I suggest we move the conversation about the model level behaviour to #7210 as that PR has no interaction with Parameters, and I think it stands alone quite well.

@perrygreenfield I am going to respond to your "model level" comments over there, as the PR and your view don't align.

**Comment by nden** [comment]
Some more comments on this after a review of #7210, mostly for documenting purpose and to facilitate further discussions.

I think having `input_units_strict` in core.py is preferable to having each model which needs it deal with  quantity conversion on its own. 

#7020 made `input_units_strict` be not settable but it is still a dict so it's possible to change. If we make it a `namedtuple` we can make it truly immutable.
Also it needs better documentation including an example of when to set it to True. 

`input_units_allow_dimensionless`
This has effect only when `input_units_strict` is set to True. There are three possible cases.

- In some models we want to allow dimensionless input in some not.
Are there models like this? I can't think of any.

- Any time `input_units_strict` is set to True we want to allow dimensionless input.
This is the case most in line with the current implementation.

- We never want to allow dimensionless inputs.
This last case diverges from the current API the most. it's attractive because it makes everything explicit. And these two attributes are used mostly with rotations and projections where it's so easy to get the inputs in the wrong units. Also this puts burden on developers who use compound models without units as now they may be required to attach units to some models. An example is a chain of polynomial and rotation models.

If we ignore the first case for which I can't think of a use case, then I think `input_units_allow_dimensionless` may not be needed. Regardless of whether we choose 2 or 3 its current functionality can be handled when `input_units_strict` is dealt with in core.py.

**Comment by pllim** [comment]
> We never want to allow dimensionless inputs.

Wait a minute. This is *only* enforced when one of the inputs has units, right? I have use case where I handle units outside of `modeling`, so my inputs are all unitless (as far as models are concerned).

**Comment by nden** [comment]
@pllim It'd be only inforced for models which have `input_units_strict=True`. These are currently the rotations and projections.

**Pull request closed without merging**
