### PR TITLE
Enable MacOS X testing on Travis

### PR DESCRIPTION
**Pull request by astrofrog**
This is pending support for multi-OS being enabled by Travis on their side so this will fail for now.

Instead of adding a job, we could also simply randomly assign some builds to be OSX and some linux (from the existing ones)

### CODE REVIEW

**Comment by astrofrog** [comment]
**WIP - DO NOT MERGE**

**Comment by astrofrog** [comment]
Multi-OS support has now been enabled for Astropy, so I've rebased this.

**Comment by astrofrog** [comment]
@eteq - what do you think?

**Comment by eteq** [comment]
@astrofrog - I think this is overall a very good idea. However, given that this is creating the ``continuous-integration`` directory, I think now might be a good time to switch to a *completely* script-based build/install process.  That is, instead of having the complicated combination of different build steps in the ``.travis.yml``, instead have travis.yml just have the matrix and lines like ``source continuous-integration/travis/install_conda_$TRAVIS_OS_NAME.sh``.  This will of course require more work now, but I think it will make things generally more readable moving forward.

I would also suggest the change of ``continuous-integration``->``.continuous-integration``.  That way the root directory is a bit cleaner.

**Comment by eteq** [comment]
Oh, and I'm willing to take a shot at my suggestion sometime after the 1.0 release, if you don't think you have the time/interest to do that.

**Comment by astrofrog** [comment]
@eteq - just to check, would the scripts then use the environment variables to decide which dependencies to install? I'm all for making the setup simple though I think we want to make it clear how we are passing data from the ``.travis.yml`` files to set setup scripts.

**Comment by astrofrog** [comment]
@eteq - is this what you had in mind? (disclaimer, may not pass yet)

**Comment by eteq** [comment]
Yes, this is exactly what I was thinking, @astrofrog.  It all looks good to me except for one minor thing: I suggest you add a README to the ``.continuous-integration`` directory that just explains what it is.  I could imagine someone not knowing what that means and being thoroughly confused as to what that means.  

Other than that, I'm :+1:  to merge.  This makes it *so* much easier to follow what's going on  - very nice!

**Comment by astrofrog** [comment]
@eteq - done, let me know if you have any feedback on the README

**Comment by eteq** [comment]
Looks good, @astrofrog - did you want anyone else to review this, or is it ready to be merged?

**Comment by eteq** [comment]
I agree - nothing about it affects the actual released versions.  Merging now then!

**Pull request merged**
