### PR TITLE
Added a couple of known issues

### PR DESCRIPTION
**Pull request by astrofrog**
For https://github.com/astropy/astropy/issues/3415 and https://github.com/astropy/astropy/issues/2960#issuecomment-74178854

cc @embray @eteq @olebole @bsipocz

### CODE REVIEW

**Comment by eteq** [comment]
@astrofrog - this is fine, but while you're editing the known issues, can I suggest two other changes?:

1. Re-arrange the issues so that some of the more common installation issues are at the top.  Specifically, the conda/pip issue, and the locale issue.  Also, perhaps move some of the issues dealing with older versions further down? (esp. the Astropy v0.2 issue, but possibly also the py 2.6.x-specific  one)
2. Can you add a table-of-contents to the top?  I'm not entirely sure this will work, but a ``.. toctree:: `` directive pointing to the current file might be the way to go.  I realize this appears in the sidebar in the generated docs, but I think it might still be helpful to see it inline.

**Comment by astrofrog** [comment]
@eteq - done, and here's the current order (suggestions welcome):

screen shot 2015-02-18 at 10 02 33 am

**Comment by eteq** [comment]
Looks good to me, but one other minor change I'd like to suggest: "Local Errors" -> "Locale Errors in Mac OS X".

**Comment by Cadair** [comment]
@eteq I have seen the locale errors on Linux as well.

**Comment by astrofrog** [comment]
@Cadair - ok, fixed

**Comment by eteq** [comment]
This looks good now, so I'll go ahead and merge.

**Comment by eteq** [comment]
Backported to v1.0.x in fd33850f8e5c536ac94e5bd0ad1d3a379ec3c5c4

**Pull request merged**
