### PR TITLE
Fix Python 3.11 issue for pprint_include/exclude_names

### LINKED ISSUE #13637: Decide how to handle Python 3.11 table test failure
The [Python 3.11 failure in `test_pprint`](https://github.com/astropy/astropy/pull/13614#issuecomment-1241974434) is apparently due to a change in behavior for `OrderedDict.pop()` (presumably https://github.com/python/cpython/pull/27530). Prior to 3.11 this ends up calling the subclass `__delitem__`. With 3.11 this is no longer the case.
```
class mydict(OrderedDict):
    def __delitem__(self, key):
        print(f"Deleting {key}")
        super().__delitem__(key)


d = mydict()
d["a"] = 1
print(d.pop("a"))
```
In 3.11 this prints only `1` while in 3.8 you also see `Deleting a`.

There are a couple of ways to deal with this.
1. Change relevant instances of `t.columns.pop(key)` to `del t.columns[key]`. In those cases the popped value is not being used anyway so `pop` wasn't really needed.
2. Change the behavior of `pprint_include/exclude_names` so that when if a column is deleted then the include/exclude sets are NOT modified. Some people might consider the current behavior as an unexpected side effect of deleting a column. Changing this behavior would allow removing the [`Columns` class `__delitem__` method](https://github.com/astropy/astropy/blob/5b6619a6ea3428de71a628e6924038b1a872dfd4/astropy/table/table.py#L298) which exists only to handle the `pprint_include/exclude` names.

There are pros/cons for each strategy and I'm on the fence. Thoughts @mhvk or @nstarman ?

### PR DESCRIPTION
**Pull request by taldcroft**
### Description

This pull request is to the [Python 3.11 failure in `test_pprint`](https://github.com/astropy/astropy/pull/13614#issuecomment-1241974434) which is due to a change in behavior for `OrderedDict.pop()` (presumably https://github.com/python/cpython/pull/27530).

This PR restores the Python <= 3.10 behavior where removing a column ends up calling `TableColumns.__delitem__`.

I ran the astropy unit tests with Python 3.11-rc1 and the table tests passed. BTW, the Table tests took 21.8 sec with Python 3.8 and 8.3 sec with Python 3.11. Wow! I want.

Fixes #13637 

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Do the proposed changes need the code-style [fixed](https://docs.astropy.org/en/latest/development/workflow/maintainer_workflow.html#pre-commit_bot)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by taldcroft** [comment]
pre-commit.ci autofix

**Comment by Cadair** [comment]
I have merged this into #13614 to let it run in the CI as well fwiw.

**Review by pllim — APPROVED** [review]
Seems to fix the Python 3.11 errors over at Stuart's PR, so I am approving. Thanks!

**Comment by mhvk** [comment]
Belated approval... Makes sense to just try to fix the problem keeping the behaviour identical for now.

**Pull request merged**
