### PR TITLE
Add list of contributors for 1.1

### PR DESCRIPTION
**Pull request by astrofrog**

### CODE REVIEW

**Comment by Cadair** [comment]
+28 nice!

**Comment by mcara** [comment]
It would be nice to update the list on this page http://www.astropy.org/about.html#acknowledge too

**Comment by eteq** [comment]
Looks good - merging!  

@mcara  - in the past we generally update that page once the release is out the door.  Feel free to create an issue (better yet, a PR ;)  at https://github.com/astropy/astropy.github.com to make sure we remember to do this as soon as the v1.1 release is out

**Comment by embray** [comment]
Thanks and congrats to the new "Core Contributors" :dancer:

**Pull request merged**
