### PR TITLE
Backport PR #12622 and #12611 on branch v5.0.x (Add documentation on cosmology to model conversion)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #12622: Add documentation on cosmology to model conversion

### CODE REVIEW

**Comment by pllim** [comment]
Are you sure this should be backported?

`docs/modeling/physical_models.rst:298:Undefined substitution referenced: "Cosmology.to_format"`

**Comment by nstarman** [comment]
I don't think it's mandatory, but it would be nice. The feature is introduced in astropy v5.0.
I think the link failure is because the descriptors weren't being linked to properly, which was a separate issue.
Could I modify this to not be a "live" link, just ` ``Cosmology.to_format`` `?

**Comment by pllim** [comment]
But we don't have this problem in `main`. Hmm!

**Comment by nstarman** [comment]
https://github.com/astropy/astropy/blob/10eb5cb5aa819158150fdbb7d853d2ae736f38a2/astropy/cosmology/core.py#L65 shows it shouldn't error.

**Comment by nstarman** [comment]
So should I modify this to not be a "live" link, just ``Cosmology.to_format``?

**Comment by pllim** [comment]
The deeper mystery is why is it only failing on backport, not on `main`. Is there another patch that needs backporting for this to work?

**Comment by nstarman** [comment]
I thought it might be https://github.com/astropy/astropy/pull/11814, but that was merged for v5.0

**Comment by nstarman** [comment]
@pllim I found the commit that should be cherry-picked to make this work.
https://github.com/astropy/astropy/commit/55ead4528f65510e76113b2327cfb135cbc213a9

**Comment by pllim** [comment]
Hmm, ok. I think that will do instead of backporting all of #12611 . Thanks for investigating!

Do you know how to do that directly in this branch?

**Comment by nstarman** [comment]
I do not. I checked out this branch and cherry-picked the commit. But it won't let me push to upstream.

**Comment by pllim** [comment]
You don't push to upstream. You push to the author branch. Something like this:

`git push meeseeksmachine your_local_name:auto-backport-of-pr-12622-on-v5.0.x`

**Comment by pllim** [comment]
If you still need help, feel free to ping me but I may not reply immediately.

**Comment by nstarman** [comment]
@pllim, thanks for the offer of help. I'm getting an error message about invalid credentials. Do I not have write privileges to meeseeksmachine?

**Review by nstarman — APPROVED** [review]

**Comment by pllim** [comment]
Failures are unrelated. Thanks!

**Pull request merged**
