### PR TITLE
[DON'T MERGE] Test astropy against Travis-built python 3.6 (minimal dependencies)

### PR DESCRIPTION
**Pull request by MSeifert04**
Just to make sure #5631 isn't present in the development version. [skip appveyor]

### CODE REVIEW

**Comment by bsipocz** [comment]
@MSeifert04 - You may want to open a PR against #5642, so we'll be able to see straight away whether the fix passes.

**Comment by MSeifert04** [comment]
@bsipocz I just realized that matplotlib is avaiable on python 3.6 (windows at least) so it probably only requires a restart of #5642?

**Comment by bsipocz** [comment]
yes, that's why it got to the point of actual test failure. Without mpl it failed during the install steps.

**Comment by bsipocz** [comment]
oh, sorry I've just seen the PR you've opened. You don't need to run travis on your fork, as it's running on PRs on mine ;)

**Comment by MSeifert04** [comment]
> You don't need to run travis on your fork, as it's running on PRs on mine ;)

@bsipocz It was too much effort to disable it for that one PR 😄

**Comment by bsipocz** [comment]
Fair enough. Personally I prefer not to run CI twice on each and every commit I push, so usually keep the build on push option off.

**Pull request closed without merging**
