### PR TITLE
Deprecate and privatize Unit.get_converter

### PR DESCRIPTION
**Pull request by mdboom**
In response to #3456: Rather than making get_converter work with Quantities, since it's not really necessary for the end user anyway, best to just privatize it.

### CODE REVIEW

**Comment by mhvk** [comment]
Looks good to me.

**Comment by eteq** [comment]
:+1: assuming the tests pass

**Comment by eteq** [comment]
Tests passed, so I'm going to go ahead and merge.

**Comment by eteq** [comment]
backported to v1.0.x in ff831c4201633138b7a015abd11f91d0be5081c2

**Pull request merged**
