### PR TITLE
Keep "-SIP" in ctype when passed to wcslib

### PR DESCRIPTION
**Pull request by nden**
This is a fix for #4387. My understanding is that the presence of SIP coefficients in the header is the only thing that wcslib looks for in the header to determine whether to create a SIP distortion. It ignores `CTYPE` as well as `A_ORDER`, ...

`astropy.wcs` does SIP corrections in the wrapper, not in the core `wcslib`. So it must strip the coefficients from the header before passing it to `wcslib`. However, `CTYPE` should be kept unchanged.

### CODE REVIEW

**Comment by embray** [comment]
Another possibility would be to remove the `-SIP` from the `CTYPEn`, then restore them in the wrapper but after wcslib runs normally.  But if what you say is true--that wcslib is only looking for the coefficients--then this seems fine too.

**Comment by embray** [comment]
Assuming it passes this should be merged in before releasing v1.1.  I don't think we need to do a release candidate.  If it turns out this needs any more work we can do v1.1.1 quickly afterwards.

**Comment by eteq** [comment]
I agree that @embray's suggestion might be better if future wcslib versions change the behavior... But we can cross that bridge when we come to it, so this seems fine for now. 

I independently verified that I get the same answers on SIP-ified files with this as with master, so this seems safe enough - will merge and backport to 1.1.x

**Comment by eteq** [comment]
backported to v1.1.x in 247ecfcca4d34be7f383d4918ddc2aad3877258d

**Comment by astrofrog** [comment]
How does this relate to https://github.com/astropy/astropy/pull/3845? My impression there was that @mdboom said that WCSLib should not yet deal with the SIP distortion because it was dealt with on the Astropy side?

**Comment by nden** [comment]
@astrofrog Yes, the SIP distortion is still dealt with on the astropy side. The presence of SIP coefficients in the header triggers the SIP distortion in wcslib. We still remove the coefficients before passing the header to wcslib but keep the full CTYPE. We actually always have passed the ctypes with -SIP in them to wcslib and it ignores them. So this is still what @mdboom intended to do. 
I wish I had run the HST pipeline on this PR but unfortunately I've been trying to fix astropy build errors locally.

**Comment by embray** [comment]
If only FITS conventions had some kind of standard keyword indicating their use....
But apparently that's a silly idea.

**Pull request merged**
