### PR TITLE
Make the tabular environment configurable in latex reader/writer

### PR DESCRIPTION
**Pull request by keflavich**
This change will allow users to override "tabular", which is useful if you want to use
longtable, e.g.:

```
tbl.write('my.tex', latexdict={'tabulartype': 'longtable'})
```

which is good for tables that need to span multiple pages

### CODE REVIEW

**Comment by hamogu** [comment]
I think this is a very useful addition and I wonder now why I did not think of that when I wrote the original LaTeX Reader/Writer.
I looked over your code and noted that it still misses tests and that is does not apply this change to the Reader. I've been thinking a while how to treat the Reader properly. I see two possibilities: 

- We introduce the tablular_type as a keyword, the reader would look for that keyword and the guessing process could then cycle through the most common table types. 

- You turn https://github.com/astropy/astropy/blob/master/astropy/io/ascii/latex.py#L109 into a regexp that matches either "tabular" or "longtable" (or maybe a few more possibilities, although I don't know any more).

**Comment by keflavich** [comment]
@hamogu `tabular_type` as a keyword sounds like a good solution to me; if you want to PR onto this I'd welcome it.  Otherwise I'll get to this when I have time / remember...

**Comment by hamogu** [comment]
@keflavich Unfortunately, I don't think I'll find time for that any time soon. Sorry.

**Comment by bsipocz** [comment]
@keflavich @hamogu - I've run into this same issue of needing a longtable environment and cannot write out a suitable table from astropy without the need of later editing. 

What would be quite useful for me already is to have the option to generate a table without any tabular environment, e.g. by providing ``'no_header': True`` to the latexdict kwarg (and then I'll deal with the headers, etc in the main latex document independently from the data). Is that something you would find useful, too?

**Comment by hamogu** [comment]
@bsipocz 
How about:
```
In [7]: from astropy.table import Table

In [9]: import numpy as np

In [10]: t = Table(np.arange(5))

In [11]: t
Out[11]: 
<Table length=1>
 col0  col1  col2  col3  col4
int64 int64 int64 int64 int64
----- ----- ----- ----- -----
    0     1     2     3     4

In [12]: from astropy.io.ascii import latex

In [14]: import copy

In [16]: myformat = copy.copy(latex.latexdicts['AA'])

In [17]: myformat['tabletype'] = 'longtable'

In [18]: import sys

In [19]: t.write(sys.stdout, format='ascii.latex', latexdict=myformat)
\begin{longtable}
\begin{tabular}{ccccc}
\hline \hline
col0 & col1 & col2 & col3 & col4 \\
\hline
0 & 1 & 2 & 3 & 4 \\
\hline
\end{tabular}
\end{longtable}
```

**Comment by bsipocz** [comment]
@hamogu - isn't longtable a tabular env rather than a table? Anyway, it would still not cover my usecase as I really would like to keep only the data in a separate file that I input to the main document, but keep everything else in front of my eyes (caption, label, column names, etc).

**Comment by hamogu** [comment]
OK, googles some more. I've never actually used a longtable (if table are that long I've always been able to get away with electronic only data tables), and I'm a little confused now.
The example on https://texblog.org/2011/05/15/multi-page-tables-using-longtable/ indicates that  that longtable is table and tabular combined and it also seems to add different formatting commands

- \endfirsthead: Line(s) to appear as head of the table on the first page
- \endhead: Line(s) to appear at top of every page (except first)
- \endfoot: Last line(s) to appear at the bottom of every page (except last)
- \endlastfoot: Last line(s) to appear at the end of the table

On the other hand, this PR deals with that by just replacing the "tabular" in the normal existing LaTeX table writer. 

Thinking about it, it might be the easiest to have a new LatexLongtableWriter for these cases.

**Comment by bsipocz** [comment]
@hamogu - I think you're right about longtables. They are indeed confusing a bit and previously I cutted up tables manually (even the mnras guide suggest it), but that's even worse.

So rather than that taking over this PR and dig deep into the inner mess of longtable, how about having that ``no_header`` to just write out the very basic inner table? I probably could hack up something using only the basic ascii writer, but feeling safer to use the latex one. It's more like the writer part of https://github.com/astropy/astropy/issues/4295

**Comment by hamogu** [comment]
@bsipocz 
but your use case is probably much easier. It's already a two-liner in the existing framework, you just need to combine existing tools to get what you want. I just talked with @taldcroft yesterday about how the design of io.ascii is so complicated that there are probably only three people in the world who know it well enough to do that:

```
In [27] my_writer = ascii.basic.NoHeader()

In [28]: my_writer.data.splitter = latex.LatexSplitter()

In [29]: my_writer.write(t)
Out[29]: [u'0 & 1 & 2 & 3 & 4 \\\\']
```

Obviously ;-) , instead of playing with an instance of a Writer, you could also make that a new class and use all the metaclass fanciness to register that with the IORegistry:
```
 In [32]: class LaTexDataOnlyData(ascii.basic.NoHeaderData):
    ...:     splitter_class = latex.LatexSplitter

In [34]: class LatexDataOnly(ascii.NoHeader):
    ...:     data_class = LaTexDataOnlyData
    ...:     _format_name = 'latexdataonly'
    ...:     _description = 'Data of Latex Table only'
    ...:     

In [35]: t.write(sys.stdout, format='ascii.latexdataonly')
0 & 1 & 2 & 3 & 4 \\
```

So, can this be done easily with a few lines of code? Yes. Will people other than me or @taldcroft be able to discover that in a reasonable amount of time? No. But would it help to make this one of the possibilities we register with the IORegistry? I'm not sure. On the one hand this is obviously a feature someone (@bsipocz) was looking for, on the other hand, we already have more than a dozen different ascii formats registered and I worry that this can easily be too much. When the list of provided formates gets too long, people will stop reading. Maybe it'll be better to have a list with exmaples how how to construct this stuff?

**Comment by hamogu** [comment]
Note that no code or processing is required to put together the writer class, it's all kind of declarative just listing the components.

**Comment by bsipocz** [comment]
@hamogu - wow, this is brilliant and a prerfect solution for me. However I'm not sure what the best way to make this discoverable. Probably I would have stuck at the same place as now, trying to hack around the latexdict values.
Have you though about adding a gallery, here, too? I feel http://docs.astropy.org/en/stable/io/ascii/fixed_width_gallery.html is rather useful as it's quick to find whether the preferred format or anything similar is listed or not.

**Comment by keflavich** [comment]
👍 to putting that example in the gallery, but it still needs more explanation for me.  It looks like you were just writing out the table *data* without any of the surrounding latex usefulness?  Is that what @bsipocz was asking for?  That should definitely be made discoverable.

Is this PR still useful?  It's now fairly ancient and I didn't add any docs.  I don't even remember what I used it for.

**Comment by bsipocz** [comment]
@keflavich - Yes, I wanted exactly this, as I found it better to have all the surroundings directly in the paper rather than hidden away in the data file.

**Comment by hamogu** [comment]
@keflavich As it stands the PR is actually wrong, because longtable replaces the table *and* the tabular environments not just one of them. 

Yes, @bsipocz asked for write only the data, so it can be included into a LaTeX document with and "include" command, where the hand-written LaTeX document contains all the required environment setup, labels and captions. 

So, I suggest that you close this PR and I'll add a new issue referencing this discussion to add more docs.

**Comment by bsipocz** [comment]
Actually I think this PR can probably be used for longtables if one sets ``'tabletype': None`` in the latexdict.

**Comment by hamogu** [comment]
Are \endfirsthead, \endhead etc. not required for longtables? They don't get written in this PR, but they could. So I should not have said that this PR is "wrong" as it stands, only that it is "incomplete". Sorry.

**Pull request closed without merging**
