### PR TITLE
Add support for GZIP_2 compression

### PR DESCRIPTION
**Pull request by PaulPrice**
It's already supported in cfitsio, but had been overlooked in the
interface.

### CODE REVIEW

**Comment by PaulPrice** [comment]
I believe failed tests are due to external resources (e.g., data.astropy.org) being down at the time.

**Comment by eteq** [comment]
Thanks for contributing this, @PaulPrice! 

This looks promising, but it would help a lot to have a test for this case - if you can make a very small image that's GZIP_2'd, you can put it in `astropy/io/fits/tests/data`, and then put the test using it into e.g. `astropy/io/fits/tests/test_image.py` (or just a standalone `astropy/io/fits/tests/test_gzip2.py` or something if that's easier).

And while you're at it, can you add a changelog (`CHANGES.rst` in the repo root) entry for this as a "new feature" in `astropy.io.fits` for v3.0 ?

And I believe you are right about the one failing test but just re-started it to be sure.

**Comment by saimn** [comment]
:+1: for the test, you can probably add a line to the `parametrize` in `test_comp_image` [here](https://github.com/astropy/astropy/blob/master/astropy/io/fits/tests/test_image.py#L1152), it would test the creation of a compressed HDU as well.

**Comment by PaulPrice** [comment]
Added tests and updated `CHANGES.rst` for both commits, rebased against master.

**Comment by PaulPrice** [comment]
I see these commits are targeted for the 3.0 release. Any chance we can get them into a minor release of 2.0? While the first commit is a new feature (at least, for astropy), the second is a bug fix required to read certain images with appropriate precision.

**Comment by pllim** [comment]
> the second is a bug fix

Can the bug fix be in a separate PR or does it fix a bug in the first commit?

**Comment by PaulPrice** [comment]
The second commit is independent of the first; I'm happy to move it to a new PR. Should I still base it on master?

**Comment by pllim** [comment]
> Should I still base it on master?

Yes.That way, bug fix PR will go in 2.x and new feature will go in 3.0. Thanks!

**Comment by PaulPrice** [comment]
Dropped the second commit from this PR (it's now in #6492).

**Comment by PaulPrice** [comment]
(I'm not sure it's completely accurate to call this PR a "new feature" --- it's merely allowing use of a feature that was already present, so one might try to argue it's actually a bugfix? You may not agree, but I can hope....!)

**Comment by MSeifert04** [comment]
It's still a new feature. I don't know if one could argue that enabling a feature that hasn't been enabled before but present is a bugfix.

But that's just my point of view. I'll let the others decide.

**Comment by PaulPrice** [comment]
I'm not sure my argument is going to fly either, but it would be helpful if this went in sooner rather than later, as I'm hoping we can enable `GZIP_2` compression in the LSST stack (`GZIP_2` gives slightly better compression than `GZIP_1`) and if that were to happen I think it's important that astropy support it.

**Comment by pllim** [comment]
Strictly speaking, bug fix is fixing something that is broken. What is not there cannot be broken (yes, yes, borrowed from Game of Thrones). 🐙

**Comment by pllim** [comment]
As for LSST support, v3 is scheduled to be released in Jan 2018 (https://github.com/astropy/astropy/wiki/Release-Calendar); hopefully that is not too late? In the mean time, once this is merged, you can always use the "dev" version until v3 is released.

**Comment by bsipocz** [comment]
I'm neutral on the version it goes into. But @pllim is right about 3.0, for LSST you may be interested in switching to that when possible as I feel the cleanup of removing the support for old python versions will be great thing.

**Comment by MSeifert04** [comment]
except when you're using python 2.7 then astropy v.3 will be a nasty shock.

**Comment by PaulPrice** [comment]
Oh, I expect LSST will adopt astropy 3.0 once it's out (and we kill py2 ourselves), but we're going to produce lots of data products (e.g., HSC) in the mean time.

**Comment by saimn** [comment]
Thanks for having split the two commits! It looks like a new feature, but GZIP_2 support was already mentioned in the [class docstring](https://github.com/astropy/astropy/blob/master/astropy/io/fits/hdu/compressed.py#L428) so we could also consider this as a bug fix ;-). No strong preference on my side.

**Comment by pllim** [comment]
Looks like both maintainers are okay with moving the milestone to 2.0.2. (In that case, I apologize for making you split the commits into separate PRs but you don't need to undo them.)

What do you think, @bsipocz ? Should we change the milestone?

**Comment by bsipocz** [comment]
@pllim - Sure, I'm happy to backport anything like this if it was approved by the maintainers.

**Comment by pllim** [comment]
Okay, I moved the milestone to 2.0.2. @PaulPrice , please move your change log entry accordingly. I apologize for any inconvenience caused.

**Comment by PaulPrice** [comment]
Done. Thanks!

**Comment by saimn** [comment]
Thanks @PaulPrice ! And thanks @MSeifert04 for approving :wink: , merging then.

**Pull request merged**
