### PR TITLE
Merge InfoDescriptor class into DataInfo

### PR DESCRIPTION
**Pull request by taldcroft**
This implements the ideas that @embray proposed.

Unfortunately I started off from an old master and this has many merge conflicts.  I'll probably start over (rebase was a big mess), but just wanted to get this out there for comment.  Need to run now.

cc: @mhvk.

### CODE REVIEW

**Comment by embray** [comment]
Ah, okay. I tried seeing for myself if I could rebase it, but even after resolving the conflicts lots of stuff broke--I think I just don't understand all the differences between what's in master, and what's in the version this was based on.

Nevertheless, this seems like the right idea.  One other thing you might want to make sure is that no methods/attributes of the descriptors that won't work for the *unbound* version raise an `AttributeError` or something of the sort.

After our last discussion about this I also started thinking about how I might formalize this pattern in a generic implementation.  Maybe it would be helpful if I just did that?

**Comment by taldcroft** [comment]
> After our last discussion about this I also started thinking about how I might formalize this pattern in a generic implementation. Maybe it would be helpful if I just did that?

Since code freeze is just a few days away, I would suggest just opening an issue for it now and potentially having that pattern available for 1.2 development.  In the remaining time I want to focus on user-facing development where possible.

**Comment by taldcroft** [comment]
BTW I ended up basically re-doing all the changes by hand since the conflicts were too much.  Hopefully I won't ever forget to update my local master again.

**Comment by embray** [comment]
> Since code freeze is just a few days away

I don't think we should be too hasty about that: https://github.com/astropy/astropy/pulls?q=is%3Aopen+is%3Apr+milestone%3Av1.1.0

**Comment by taldcroft** [comment]
My understanding was that our benevolent coordinators plan to push a little harder on sticking to schedule this time around, with the understanding that a little slippage is inevitable.

In any case this PR is passing tests now, yay.  I don't think any changelog or doc updates are required.

**Comment by embray** [comment]
:+1:

**Pull request merged**
