### PR TITLE
Cosmo latex identify and cleanup

### PR DESCRIPTION
**Pull request by nstarman**
- Add autoidentification
- docstrings
- unregister 'latex' in favor of 'ascii.latex' (this is a new format that isn't yet in any released version)
- small cleanup

### CODE REVIEW

**Review by taldcroft — COMMENTED** [review]
Looks good and basically ready for approval.

The only question I have is that I couldn't find any rendered version of the updated `write_latex` docstring in the docs to review. 

Also, in the cosmology `Read, Write ...` section, there is no place that `ascii.latex` is explicitly mentioned so it isn't clear how the user will discover `format="ascii.latex"`.

**Comment by nstarman** [comment]
> The only question I have is that I couldn't find any rendered version of the updated `write_latex` docstring in the docs to review.

Yeah, the cosmology I/O docs need some work. This is being done in #15090.

> Also, in the cosmology `Read, Write ...` section, there is no place that `ascii.latex` is explicitly mentioned so it isn't clear how the user will discover `format="ascii.latex"`.

It should be in the list of write formats in the I/O table... If not #15090 will take of that!

**Review by taldcroft — APPROVED** [review]
Looks good!

**Comment by nstarman** [comment]
Thanks @taldcroft  for the reviews!

**Pull request merged**
