### PR TITLE
Update AppVeyor configuration to drop Python 2.6 support

### PR DESCRIPTION
**Pull request by astrofrog**
Also, always test against the latest stable Numpy version. This is the complementary PR to https://github.com/astropy/astropy/pull/4225.

cc @eteq @bsipocz

### CODE REVIEW

**Comment by bsipocz** [comment]
:+1: 
What about testing against 3.5 {rather than}/{and}  3.4?

**Comment by embray** [comment]
+1 for testing Python 3.5.

**Comment by mhvk** [comment]
Agreed, might as well test python 3.5

**Comment by astrofrog** [comment]
I've added Python 3.5, but should I remove 3.4? It looks like it takes 10 minutes per configuration, so it's now going to take around 30 minutes per build. Maybe that's ok? (I've noticed appveyor finishing before Travis these days)

**Comment by mhvk** [comment]
@astrofrog - I would remove 3.4; we're testing it on linux, so it really should be OK, and even if it doesn't save time, it does leave resources for others (and saves some little bit of power).

**Comment by astrofrog** [comment]
@embray - it looks like there are some FITS-related failures on Windows with Python 3.5 - any idea what those are due to?

**Comment by embray** [comment]
@astrofrog I believe all of them are due to #4342

**Comment by astrofrog** [comment]
@embray @mhvk @bsipocz - I've left 3.5 in as an allowed failure. Since this runs faster than Travis, I've left in 3.4 otherwise we have no indicator that 3.x is failing. Once 3.5 is unmarked as an allowed failure, we can remove 3.4.

**Comment by embray** [comment]
Maybe make a note in #4342 that that should be done as part of a fix for that issue.

**Comment by astrofrog** [comment]
I'll go ahead and merge this, and I've made a note in #4342

**Pull request merged**
