### PR TITLE
Add --slow option for tests

### PR DESCRIPTION
**Pull request by cdeil**
Some of the Astropy tests take > 10 seconds to execute and in my opinion should be skipped by default.

Specifically the tests in `astropy/coordinates/tests/accuracy` aren't really unit tests that need to be run all the time by every developer.

Here's the 10 slowest tests I find on my Macbook via

```
$ python setup.py test -a --durations=10
```

```
39.07s call     astropy/coordinates/tests/accuracy/test_fk4_no_e_fk5.py::test_fk4_no_e_fk5
28.15s call     astropy/coordinates/tests/accuracy/test_galactic_fk4.py::test_galactic_fk4
27.33s call     astropy/coordinates/tests/accuracy/test_icrs_fk5.py::test_icrs_no_e_fk5
12.40s call     astropy/io/fits/tests/test_image.py::TestImageFunctions::test_lossless_gzip_compression
4.81s call     astropy/io/fits/tests/test_table.py::TestTableFunctions::test_copy_vla
3.31s call     astropy/utils/tests/test_timer.py::test_timer
3.06s call     astropy/io/fits/tests/test_table.py::TestTableFunctions::test_getdata_vla
3.01s call     astropy/vo/samp/tests/test_hub_script.py::test_hub_script
2.75s call     astropy/io/fits/tests/test_table.py::TestTableFunctions::test_variable_length_columns
2.67s call     astropy/io/fits/tests/test_image.py::TestImageFunctions::test_open_scaled_in_update_mode_compressed
```

And for a Linux server I find these 10 tests to be the slowest:

```
41.56s call     astropy/coordinates/tests/accuracy/test_fk4_no_e_fk5.py::test_fk4_no_e_fk5
29.41s call     astropy/coordinates/tests/accuracy/test_galactic_fk4.py::test_galactic_fk4
28.80s call     astropy/coordinates/tests/accuracy/test_icrs_fk5.py::test_icrs_no_e_fk5
3.31s call     astropy/utils/tests/test_timer.py::test_timer
3.03s call     astropy/vo/samp/tests/test_hub_script.py::test_hub_script
2.34s call     astropy/convolution/tests/test_discretize.py::test_subpixel_gauss_2D
2.18s call     astropy/units/tests/test_units.py::test_compose_fractional_powers
2.17s call     astropy/units/tests/test_units.py::test_compose_fractional_powers
2.11s call     astropy/io/fits/tests/test_image.py::TestImageFunctions::test_open_scaled_in_update_mode_compressed
2.02s call     astropy/io/fits/tests/test_image.py::TestImageFunctions::test_open_scaled_in_update_mode
```

I found this documented method to add a [--runslow](http://pytest.org/latest/example/simple.html?highlight=mark%20slow#control-skipping-of-tests-according-to-command-line-option) option for `py.test`.
I'm not familar with the Astropy test runner, but it shouldn't be hard, so I'll try to put it in and add `pytest.mark.slow` to the `astropy/coordinates/tests/accuracy` tests.

### CODE REVIEW

**Comment by cdeil** [comment]
@aphearin asked for this feature again on `astropy-dev` today:
https://groups.google.com/forum/#!topic/astropy-dev/xghxhxseZFw

There were some concerns if this is useful enough to be included, and this got sidetracked a bit by discussions on performance issues in Astropy.
But looking back trough the comments it seems that there's a good chance this could get merged.
So I'll make a new PR against astropy-helpers with this functionality in the coming days and link to it from here.

**Comment by aphearin** [comment]
I'll follow this thread in the coming days in case there is some hangup. In case this can continues to get kicked down the road in astropy_helpers, it's no sweat, I'd just want to know how to make the necessary modifications within my own package (since my simple decorator solution failed). But of course if it gets implemented within the helpers, from my perspective that is ideal. Either way, thanks for the help @cdeil

**Comment by embray** [comment]
I didn't realize there was any objection to this.  I think it's useful to have.

**Comment by embray** [comment]
As for astropy-helpers maybe leave it alone.  This is good incentive for me to rework how options are added to the `./setup.py test` command so that it can be determined by what version of the astropy test runner a project is using, and doesn't have to be so tightly bound to it (there are already some improvements on that front in that it won't crash if you use mismatched versions, but it will be better if the command options are determined by introspection).

**Comment by cdeil** [comment]
> As for astropy-helpers maybe leave it alone. This is good incentive for me to rework ...

@embray Great! Please mention it here when you file an issue for astropy-helpers or make a PR.

**Comment by embray** [comment]
Yeah, I'll try to get that cleaned up today.  It's long overdue.

**Comment by aphearin** [comment]
Just checking on the status of the --slow feature. I've recently accumulated a large number of unavoidably slow tests in Halotools, and so this is increasingly a problem I either need to solve or devise a temporary workaround for. 

CC @cdeil , @embray

**Comment by embray** [comment]
I think this mostly just depends on me finishing #4020.  I think there's more work left for me to do there but I got sidetracked.

**Comment by aphearin** [comment]
Hey @embray - just checking on the status of this now that #4020 is merged. Did this slow-testing option get integrated into Astropy v1.0.5?

**Comment by embray** [comment]
No, and #4020 was only for Astropy 1.1 too.  But I'd be happy to try to get this integrated for 1.1...

**Comment by astrofrog** [comment]
Just a thought - if this goes ahead, the option should be either ``--run-slow`` or ``--skip-slow``, otherwise it's too ambiguous.

**Comment by embray** [comment]
Just for the record, as I pointed out to @aphearin it's super easy to add one's own custom markers with py.test https://pytest.org/latest/example/markers.html

One can then use the `-m` option for running only tests with that marker, or only tests without it.  Since our `setup.py` test doesn't support that option natively it has to be passed through to py.test using the `--args`, like `--args="-m 'not slow'"`.  

Or even more simply using the recipe this PR was originally based on: http://pytest.org/latest/example/simple.html?highlight=mark%20slow#control-skipping-of-tests-according-to-command-line-option  This version also makes it so that the "slow" tests are skipped by default.

There's no reason py.test recipes like this can't be used with the astropy test runner (if it doesn't work for some reason that's probably a bug on our end).  The only reason for this PR is to add an argument to the test runner to make it more convenient to enable slow tests (which I'm fine with doing, now that it's easier to keep the test runner and then `./setup.py test` command in sync).

**Comment by cdeil** [comment]
I'm closing this old PR.

@embray points out how to achieve the same thing directly with `pytest`, and I agree the value of re-exposing it as a `python setup.py test` option is limited.

On my machine, currently with Astropy master the tests run for 228.88 seconds and these are the slowest:
```
========================================================================= slowest 100 test durations =========================================================================
4.57s call     lib.macosx-10.12-x86_64-3.5/astropy/table/tests/test_mixin.py::test_io_ascii_write
4.18s call     lib.macosx-10.12-x86_64-3.5/astropy/units/tests/test_units.py::test_compose_fractional_powers
3.77s call     lib.macosx-10.12-x86_64-3.5/astropy/units/tests/test_units.py::test_compose_cgs_to_si[Bi]
3.60s call     lib.macosx-10.12-x86_64-3.5/astropy/units/tests/test_units.py::test_compose_cgs_to_si[Fr]
3.33s call     lib.macosx-10.12-x86_64-3.5/astropy/utils/tests/test_timer.py::test_timer
3.06s call     lib.macosx-10.12-x86_64-3.5/astropy/units/tests/test_units.py::test_compose_cgs_to_si[statA]
3.03s call     lib.macosx-10.12-x86_64-3.5/astropy/vo/samp/tests/test_hub.py::test_SAMPHubServer_run_repeated
3.02s call     lib.macosx-10.12-x86_64-3.5/astropy/vo/samp/tests/test_hub_script.py::test_hub_script
2.60s call     docs/units/decomposing_and_composing.rst
2.51s call     lib.macosx-10.12-x86_64-3.5/astropy/units/tests/test_units.py::test_complex_compose
2.44s call     lib.macosx-10.12-x86_64-3.5/astropy/io/fits/tests/test_image.py::TestCompressedImage::test_open_scaled_in_update_mode_compressed
2.25s call     lib.macosx-10.12-x86_64-3.5/astropy/wcs/tests/extension/test_extension.py::test_wcsapi_extension
2.06s call     lib.macosx-10.12-x86_64-3.5/astropy/io/fits/tests/test_image.py::TestImageFunctions::test_open_scaled_in_update_mode
1.76s call     lib.macosx-10.12-x86_64-3.5/astropy/coordinates/tests/test_angles.py::test_repr_latex
1.68s call     lib.macosx-10.12-x86_64-3.5/astropy/convolution/tests/test_discretize.py::test_subpixel_gauss_2D
1.66s call     lib.macosx-10.12-x86_64-3.5/astropy/io/ascii/tests/test_c_reader.py::test_many_columns[True]
1.41s call     lib.macosx-10.12-x86_64-3.5/astropy/table/tests/test_mixin.py::test_hstack[masked]
1.39s call     lib.macosx-10.12-x86_64-3.5/astropy/table/tests/test_mixin.py::test_hstack[unmasked]
1.31s call     lib.macosx-10.12-x86_64-3.5/astropy/table/tests/test_mixin.py::test_hstack[subclass]
1.17s call     lib.macosx-10.12-x86_64-3.5/astropy/io/ascii/tests/test_c_reader.py::test_many_columns[False]
1.13s call     lib.macosx-10.12-x86_64-3.5/astropy/table/tests/test_info.py::test_table_info_attributes[subclass]
1.12s call     lib.macosx-10.12-x86_64-3.5/astropy/table/tests/test_info.py::test_table_info_attributes[unmasked]
1.11s call     lib.macosx-10.12-x86_64-3.5/astropy/table/tests/test_mixin.py::test_join[masked]
1.11s call     lib.macosx-10.12-x86_64-3.5/astropy/table/tests/test_mixin.py::test_join[subclass]
1.09s call     lib.macosx-10.12-x86_64-3.5/astropy/table/tests/test_mixin.py::test_join[unmasked]
1.06s call     lib.macosx-10.12-x86_64-3.5/astropy/nddata/tests/test_nduncertainty.py::test_for_leak_with_uncertainty
1.01s call     lib.macosx-10.12-x86_64-3.5/astropy/vo/samp/tests/test_hub.py::test_SAMPHubServer_run
1.01s call     lib.macosx-10.12-x86_64-3.5/astropy/io/fits/tests/test_groups.py::TestGroupsFunctions::test_open_groups_in_update_mode
1.01s call     lib.macosx-10.12-x86_64-3.5/astropy/io/fits/tests/test_image.py::TestCompressedImage::test_open_comp_image_in_update_mode
1.00s call     lib.macosx-10.12-x86_64-3.5/astropy/io/fits/tests/test_image.py::TestCompressedImage::test_lossless_gzip_compression
```
Probably the Astropy tests could be made faster, my experience is that people very often choose test datasets that could be smaller and still test the exact same thing.
But nothing stands out particularly, so I won't go have a look now.

**Pull request closed without merging**
