### PR TITLE
Update CFITSIO to 3.470

### PR DESCRIPTION
**Pull request by MSeifert04**
Mostly meant as reminder that we probably should update CFITSIO because some of the compression has received features/bugfixes

### CODE REVIEW

**Comment by saimn** [comment]
Good idea, but why the WIP label ? We can already merge this I think ?

**Comment by MSeifert04** [comment]
I wasn't sure if it's too early to do the update, just in case there's another release before astropy 4.x comes out. 😅

**Comment by bsipocz** [comment]
> I wasn't sure if it's too early to do the update, just in case there's another release before astropy 4.x comes out.

That case we can do another update 🤷‍♀ 

I see enormous value in having updates early in the master branch, so any potential issues can surface as soon as possible rather than adding them along with the tons of new features around feature freeze.

**Comment by pllim** [comment]
:+1: to get it in sooner than later. Needs a change log.

**Comment by MSeifert04** [comment]
Tests passed, so I'm merging my own PR 😈

**Pull request merged**
