### PR TITLE
DOC: Update list of functions that lose units 

### LINKED ISSUE #10845: Complete list of functions that lose units
> you are right that we should add [`np.full`] to the known issues.  One similarly cannot do `np.zeros`, `np.ones`, and `np.empty`.

_Originally posted by @mhvk in https://github.com/astropy/astropy/issues/10836#issuecomment-707302194_

The list in question: https://docs.astropy.org/en/latest/known_issues.html#quantities-lose-their-units-with-some-operations

### PR DESCRIPTION
**Pull request by rpsfonseca**
### Description

This pull request is to address the missing functions on the list that details which operations lead to Quantities losing units.

Fixes #10845

### CODE REVIEW

**Review by mhvk — COMMENTED** [review]
@rpsfonseca - thanks! But these should not just be added, as the text just above notes the list is for "prior to astropy 4.0 and numpy 1.17". So, there should instead be a new header entry (maybe below this one is best), along the lines of "Numpy array creation functions cannot be used to initialize Quantity". For that, I'd include the explicit example with `np.full` that doesn't work (as it is the one most likely to surprise anyone)

**Comment by rpsfonseca** [comment]
@mhvk So you say to add a new section like [this one](https://github.com/astropy/astropy/blob/dc84fa5d62d0eb6b758d33859d65fb469add43ae/docs/known_issues.rst#quantities-lose-their-units-with-some-operations) with the title being the one you mentioned?

And the explicit example you also mention, is the one given by the author of #10836 ?

**Comment by mhvk** [comment]
@rpsfonseca - Yes to both!

**Review by mhvk — APPROVED** [review]
Thanks, looks good now!

**Comment by pllim** [comment]
Since the issue that this PR fixed was labeled as Hacktoberfest, I applied "hacktoberfest-accepted" label here. I am still not fulling understand how the new fest rules work... cc @astrojuanlu 

Thank you, all!

**Comment by astrojuanlu** [comment]
thanks @pllim ! I was about to do it myself :blush:

**Comment by pllim** [comment]
For future reference, please do not skip CI when there is real code in the docs. This caused real failures, which I am patching it over at #10874 . FYI.

**Comment by rpsfonseca** [comment]
Thank you for the help!
And sorry about skipping CI, I checked the CONTRIBUTING guide, and it mentioned that on documentation we could skip CI. But I will keep that in mind for future contributions.

**Comment by mhvk** [comment]
@rpsfonseca - no worries, when I reviewed I noticed the few checks but that `readthedocs` was done, and I also thought that was OK. Having been around, I should have known better...

Question: would you be willing to adjust the `CONTRIBUTING` guide, adding a line about not skipping if there are doctests? (And for that one we *can* actually skip CI!)

**Comment by pllim** [comment]
Perhaps this line in `CONTRIBUTING.md` confusing: `If your commit makes substantial changes to the documentation but no code changes` (... the key is "no code changes" but changing code in doc is basically code changes because we test it.)

I also added something in https://docs.astropy.org/en/latest/development/docguide.html#adding-a-git-commit .

If any of those could be less confusing, please feel free to propose changes as PR. Thanks!

**Comment by rpsfonseca** [comment]
@mhvk I'd love to help on that for sure!
@pllim Yes, that was the line the lead me into the "mistake".

I will look into that and propose a change and check your opinion.

**Comment by pllim** [comment]
@mhvk , @eteq and I just found out that the `UnitConversionError` doesn't happen in Numpy 1.16.x, as with in Numpy 1.20.x. Is this expected? We dropped Numpy 1.16 on `master` but still tests against it on older branches.

```python
>>> import numpy as np
>>> import astropy
>>> from astropy import units as u
>>> np.__version__
'1.16.5'
>>> astropy.__version__
'4.0.3'
>>> x = 1. * u.m
>>> np.full(10, x)
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```

**Comment by mhvk** [comment]
@pllim - I think 1.16 just completely ignored the unit, without even realizing it.
But I guess that means the text of the docs is still not quite right...

**Comment by pllim** [comment]
> that means the text of the docs is still not quite right

We dropped numpy 1.16 in #10664 , so it is non-issue for `master` but for the sake of making the release out, Erik and I decided to just skip that doctest in 4.0.x and 4.1.x branches.

**Comment by rpsfonseca** [comment]
Sorry for taking this long, but I opened a PR to address the confusing tips on `CONTRIBUTING.md`, as we talked about.

**Pull request merged**
