### PR TITLE
Add legend to Ripley's K plot

### PR DESCRIPTION
**Pull request by Gabriel-p**
### Description

Very small change, simply add a legend box to the plot.

### CODE REVIEW

**Comment by pllim** [comment]
Unfortunately, this PR is opened against the wrong branch. Please open PR against `master`, not `stable`. Thanks!

**Comment by Gabriel-p** [comment]
I see that @bsipocz changed the base branch, I assume that means there's no need to submit again against the stable branch then?

**Comment by pllim** [comment]
We both tried, but changing the base caused the PR to pull in a lot of unrelated commits.

**Comment by bsipocz** [comment]
> to submit again against the stable branch then

just to reiterate: no PRs should be made against the `stable` branch at any point, all should be against the `master` branch. The should have been template text coming up when you opened the PR, if you have any suggestion on how to change that text to make this clear in there, please open a PR for it, too. (The template certainly points to the contributing documentation, I suppose that link might just not be prominent enough)

**Comment by Gabriel-p** [comment]
Yes sorry, I meant against the `master` branch.

On how i came to edit the `stable` branch, it's because I opened it directly from the docs and that's the branch that is used there by default (i.e., I did not manually select the branch):

DeepinScreenshot_Seleccionar área_20200429160039

It is true that the `CONTRIBUTING.md` file mentions opening against the `master` branch, sorry I missed it. I'll close this one and open a new one properly.

**Comment by pllim** [comment]
Yeah, the edit on GitHub thingy is a known issue and unfortunately cannot be fixed here, so we're still waiting for RTD to do something about it. We apologize for any inconvenience caused and thank you for your continued patience and contribution!

**Pull request closed without merging**
