### PR TITLE
DOC: Ignore fitter warning in new model example

### LINKED ISSUE #17285: DOC: Non-fatal warning about "The fit may be unsuccessful"
For a while, we were plagued by these warnings in the log, making debugging a pain. Then they were exorcised in https://github.com/astropy/astropy/pull/12788 . Now I see one is creeping back in. We should get rid of it before it multiplies again like tribbles.

```
reading sources... [ 90%] modeling/new-model
WARNING: The fit may be unsuccessful; check: 
    The maximum number of function evaluations is exceeded. [astropy.modeling.fitting]
reading sources... [ 90%] modeling/parallel-fitting
```

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address new fitting warning that probably crept in after https://github.com/astropy/astropy/pull/16983

Fixes #17285

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by saimn** [comment]
The fit is not looking great (https://docs.astropy.org/en/latest/modeling/new-model.html#basic-custom-models), might be better to give a better initial solution (the goal here is not to show that a fit can fail if initial solution is bad ;)).

**Comment by pllim** [comment]
@larrybradley and/or @astrofrog , what would be the cleanest way to give initial solution as @saimn suggested above?

**Comment by larrybradley** [comment]
You can avoid the warning and get a better fit by using a `m_init` with parameters that are closer to the true values (defined in `m_ref`.  Do you want to open a PR?

**Comment by larrybradley** [comment]
Reducing the noise level will also help.

**Comment by pllim** [comment]
> Do you want me to open a PR?

Sure. Thanks!

**Comment by pllim** [comment]
Closing in favor of https://github.com/astropy/astropy/pull/17293 . Thanks, all!

**Pull request closed without merging**
