### PR TITLE
Fixed determination of tick labels for all-sky images when coord_wrap < 360

### PR DESCRIPTION
**Pull request by astrofrog**
This fixes a bug that caused labels on WCSAxes plots for all-sky images to not appear correctly in cases where coord_wrap < 360. Image from the regression test (the four top axes have coord_wrap=360, the bottom four 180, and each row has a different crval1):

**Before**

before

**After**

after

Note that there are still some issues illustrated in the top four axes when the tick spacing is not a divisor of 360 but this is actually an issue that's been around since the start and will require some more work to fix. I will open an issue for that.

### CODE REVIEW

**Comment by Cadair** [comment]
Thanks @astrofrog

**Comment by bsipocz** [comment]
This looks to me, but will wait @Cadair to approve before merging.

**Comment by pllim** [comment]
I merged it already... :grimacing:

**Comment by bsipocz** [comment]
Hmm, there were no comments on here at all when I commented 🤷‍♀  I suppose the JS stopped working when my internet was gone for most of the day (and while this tab was already been open).

**Pull request merged**
