### PR TITLE
TST: Skip bayesian_info_criterion_lsq doctest

### LINKED ISSUE #9657: [3.2.3] bayesian_info_criterion_lsq failure with ARM64
On Debian, we are currently on the transition to Python 3.8. With this, almost all tests succeed on all platforms, except the following which happens on PowerPC 64 bit and Arm64 (both little endian):
```
171     >>> g_init = models.Gaussian1D(amplitude=1., mean=0, stddev=1.)
172     >>> fit_g = fitting.LevMarLSQFitter()
173     >>> g = fit_g(g_init, x, y)
174     >>> # Compute the mean squared errors
175     >>> ssr_t = np.sum((t(x) - y)*(t(x) - y))
176     >>> ssr_g = np.sum((g(x) - y)*(g(x) - y))
177     >>> # Compute the bics
178     >>> bic_t = bayesian_info_criterion_lsq(ssr_t, 4, x.shape[0])
179     >>> bic_g = bayesian_info_criterion_lsq(ssr_g, 3, x.shape[0])
180     >>> bic_t - bic_g # doctest: +FLOAT_CMP
Expected:
    30.644474706065466
Got:
    31.11155402550662

/<<PKGBUILDDIR>>/.pybuild/cpython3_3.8/build/astropy/stats/info_theory.py:180: DocTestFailure
```
Full build log [here](https://buildd.debian.org/status/fetch.php?pkg=astropy&arch=arm64&ver=3.2.3-2&stamp=1574459158&raw=0). With Python 3.7, these tests succeeded.
Python is  3.8.0.
BTW, Travis offers as Beta builds on arm64, powerpc64 and s390x. arm64 and s390x may be worthwile test environments for astropy: arm64 because of the usage in small devices (Raspberry), and s390x because it is big endian.

### PR DESCRIPTION
**Pull request by pllim**
to avoid failure due to slightly different result in
arm64 and big-endian s390x CI jobs.

### Description

This pull request is an alternative to #10923

Fix #9657
Close #10923

### CODE REVIEW

**Comment by bsipocz** [comment]
I would prefer this workaround than the other one. Ideally, we would just stip the exotic archs that it runs into issues, but afaik that is not possible.

**Comment by pllim** [comment]
Technically, we could skip certain arch but the doc would look real ugly.

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
Yeah, keep it as is then. Checking on the numerical accuracy is also done in the tests, so no need to make it ugly for the docs.

**Review by mhvk — APPROVED** [review]
Yes, better like this! Thanks!

**Comment by pllim** [comment]
Thanks for the reviews!

**Pull request merged**
