### PR TITLE
Make sure we include the .rst templates from astropy-helpers in the astropy tar file

### PR DESCRIPTION
**Pull request by astrofrog**
Fixes https://github.com/astropy/astropy/issues/6322 and 2.0-critical

### CODE REVIEW

**Comment by bsipocz** [comment]
Should this change also be added to the package template? I guess it's not critical as affiliates are not supposed to build any docs from the helpers, but it probably won't hurt to have it.

**Comment by bsipocz** [comment]
This is also a serious issue for all the affiliates, too, so I'll open mass PRs to fix it.

Building the docs from sdist isn't in the release docs, so no wonder it wasn't spotted when the first package was released with the new helpers (astroquery 0.3.6).

That being said, I don't think many of the users will notice, I doubt a big crowd are downloading the sdist and try to build the docs locally, except e.g. packagers.

**Comment by astrofrog** [comment]
I really should finish up my mini-package that can auto-open PRs to many affiliated packages to make specific fixes...

**Comment by bsipocz** [comment]
I have some hacky scripts already :)

**Pull request merged**
