### PR TITLE
Add alternate unit path in frame initializer 

### PR DESCRIPTION
**Pull request by eteq**
This PR is a tweak to the machinery for initializing frame objects based on a discussion with @Cadair  about a rather obscure SunPy use case.  There's a coordinate system that uses a different lat/lon convention, and he has a custom representation (and unit representation) for this.  This PR makes it so that custom unit representations actually get called even if it isn't a `SphericalRepresentation`.

This *shouldn't* actually change anything in the public API (hence the no-changelog-entry-needed). The idea is that we can test this in 3.0 via SunPy (which is using the `_unit_representation` trick anyway) and perhaps move towards it being a more public feature in the future.  So I've slated it for v3.0 as it then gets the "testing" in SunPy now.

### CODE REVIEW

**Comment by Cadair** [comment]
This looks like it fixes one of the two issues I found while messing around with this, [this](https://github.com/astropy/astropy/compare/master...Cadair:reversePhysicsSpherical#diff-7ebe72c3813e25748324999215da4af5R1281) is the other one.

I will do a proper review on this later.

**Comment by Cadair** [comment]
@eteq I am interested in why you did this with the double `try` statement, my version in #7163 just checks for the existence of `_unit_representation` which feels like it would be faster. Am I missing something?

**Comment by eteq** [comment]
@Cadair - because it seemed the fastest way to do it without the side-effects.  But I think your #7163 works just as well/better.  Let me try porting my test to that and make sure it works, but in that case I think you're right that's better.

**Comment by eteq** [comment]
@Cadair - actually I remember now.  This is necessary vs your solution because your solution breaks things if something has a unit representation and the "distance-like" thing is not called `distance`.  E.g. the PhysicsSphericalRepresentation doesn't work.  This `try` approach works around that because it doesn't rely on `distance` being hard-coded.

I think the solution is to combine your second fix with this one, though.  Will do that in a moment.

**Comment by eteq** [comment]
I think I've integrated your work from #7163, @Cadair, and gotten this passing. If this looks good to you we can merge this and close #7163.

**Pull request merged**
