### PR TITLE
WCSAxes: Fix the allowed types for set_major_formatter()

### PR DESCRIPTION
**Pull request by ayshih**
### Description

The docstring for `CoordinateHelper.set_major_formatter()` claims that the method can accept a matplotlib `Formatter` instance, but that input type simply raises a `NotImplementedError`, and has done so for the past 11 years.  How to implement support for a matplotlib `Formatter` instance is non-obvious, so it makes sense that this aspirational claim has never been made real.  This PR fixes the docstring, but retains the aspiration as a TODO comment for some enterprising developer in the future.

I don't know whether a changelog entry is even warranted here.

Fixes #<Issue Number>

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by neutrinoceros — APPROVED** [review]

**Review by astrofrog — APPROVED** [review]
Thanks for catching this!

**Comment by pllim** [comment]
If it is a bug to be backported, you sure we don't need a change log, @astrofrog ?

**Comment by astrofrog** [comment]
It's technically a documentation bug, this doesn't change any behavior. I still don't think we need a changelog entry.

**Comment by pllim** [comment]
I think you forgot the backport label

@meeseeksdev backport to v6.1.x

**Pull request merged**
