### PR TITLE
A possible fix for None differential type

### LINKED ISSUE #8021: Apparent Breaking change in coordinates
Fulfilling my purpose as the coordinates canary I have the following issue for you!

Importing sunpy coordinates is broken with astropy master, it seems that having `None` as a differential type somewhere along the line is no longer allowed? I assume this is not a deliberate API change?

```
$ python -c "import sunpy.coordinates"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/stuart/Git/DKIST/sunpy/sunpy/coordinates/__init__.py", line 6, in <module>
    from .ephemeris import *
  File "/home/stuart/Git/DKIST/sunpy/sunpy/coordinates/ephemeris.py", line 106, in <module>
    get_earth(_time_first_rotation).hcrs.cartesian.transform(_SUN_DETILT_MATRIX) \
  File "/home/stuart/Git/DKIST/sunpy/sunpy/coordinates/ephemeris.py", line 73, in get_earth
    earth = SkyCoord(0*u.deg, earth.lat, earth.radius, frame=earth)
  File "/home/stuart/Git/astropy/astropy/coordinates/sky_coordinate.py", line 259, in __init__
    frame_cls, frame_kwargs = _get_frame_without_data(args, kwargs)
  File "/home/stuart/Git/astropy/astropy/coordinates/sky_coordinate.py", line 1791, in _get_frame_without_data
    kwargs.pop('differential_type'))
  File "/home/stuart/Git/astropy/astropy/coordinates/baseframe.py", line 79, in _get_diff_cls
    value, list(r.DIFFERENTIAL_CLASSES)))
ValueError: Differential is None but must be a BaseDifferential class or one of the string aliases ['cartesian', 'unitspherical', 'spherical', 'unitsphericalcoslat', 'sphericalcoslat', 'radial', 'physicsspherical', 'cylindrical']
```

It seems to have been introduced by this commit (according to bisect):
https://github.com/astropy/astropy/commit/c912dbd378ed376f4beb13d3605cb1101df2a45c

ping @adrn @eteq

### PR DESCRIPTION
**Pull request by Cadair**
This appears to fix #8021 for me. 

I have no idea if this is a *good* fix for the problem :stuck_out_tongue:

### CODE REVIEW

**Comment by bsipocz** [comment]
@Cadair - Can you add a regression test?

**Comment by bsipocz** [comment]
This looks like an easy merge, but still lacks of a test and approval. @Cadair - could you add the former, @eteq or @adrn the latter?

**Comment by adrn** [comment]
I agree with @mhvk and implemented his suggestion in #8082. 

@Cadair : please try that out and see if it is indeed a fix?

**Comment by bsipocz** [comment]
Ohh, apparently I've got to #8082 before this and didn't see you were waiting for @Cadair's feedback. Anyway, now that one is in, so I'm closing this PR. Please reopen if there is an issue with the other one.

**Pull request closed without merging**
