### PR TITLE
Public-scope cosmology units module

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

Maybe fixes RTD stuff in #12709

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Maybe I can cherry-pick this to my other PR as a temporary commit to test the theory...

**Review by pllim — CHANGES_REQUESTED** [review]
Does not seem to work. See the RTD failure over at #12709 (https://readthedocs.org/api/v2/build/15732384.txt): `docs/units/equivalencies.rst:522: WARNING: py:obj reference target not found: astropy.cosmology.units.redshift`

To test this here, maybe add a dummy reference to `astropy.cosmology.units.redshift` somewhere in the docs and see for yourself?

**Comment by nstarman** [comment]
I still think this should be merged and backported, regardless of whether it fixes the docs issue.
It was an oversight to not properly put ``units`` in the top mainspace.

**Comment by mhvk** [comment]
That makes sense, though I guess one question is why there is an `__all__` at all in `__init__` - ideally, one has nothing imported that should not be in that `__all__` anyway...

**Comment by nstarman** [comment]
A good point. Currently it's necessary because of the registrations that happen when `io` is imported. But when #12490 is working and I adopt it for Cosmology, then it shouldn't be necessary.

**Review by mhvk — COMMENTED** [review]
OK, sounds like we should just get this in for now, then.

**Review by mhvk — APPROVED** [review]

**Comment by mhvk** [comment]
@pllim - can you remove your "changes requested" since this PR now has a different purpose?

**Comment by pllim** [comment]
I still don't quite get it. I don't need this patch anymore, so why not just wait for #12490 ?

**Comment by mhvk** [comment]
@nstarman - I thought you wanted to backport this? Or can we indeed just wait?

**Comment by nstarman** [comment]
We *can* wait, but I have no clue when #12490 will get in. In my mind this is a very minor bug.
Some configurations of IPython limit the user to looking at public API when tab-competing (https://ipython.readthedocs.io/en/stable/config/options/terminal.html#configtrait-IPCompleter.limit_to__all__)  and ``cosmology.units`` is public. So I wouldn't mind getting this in now to correct the oversight and backporting better solutions as they arise.

**Comment by pllim** [comment]
This is technically API change more than bug fix IMHO, but I'll let the subpackage maintainers decide.

**Comment by mhvk** [comment]
I think it was an oversight to not have `units` in `__all__`, likely just because it is unusual to have `__all__` at all. Since this only will affect interactive usage, I think it is OK to backport. Let's get it in!

**Pull request merged**
