### PR TITLE
TST: Accept socket warning for now in test_data_noastropy_fallback

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to add in logic to account for 2 extra warnings sometimes in `test_data_noastropy_fallback` so it won't fail.

Is this acceptable for now, @aarchiba ?

Also see #9619 and #10686

Follow up of  #10437 and #10671

### CODE REVIEW

**Comment by eteq** [comment]
@pllim - can you clarify if this actually appears in some cases "live", or is it only appearing in the test suite?

Put another way: is this a 4.1 blocker, or more of a test suite cleanup? (I've gotten lost in the cross-linkings to other issues).

**Comment by pllim** [comment]
I have seen the socket warning "live" but I couldn't trace it down. Either way, not a blocker for release. Feel free to remilestone.

**Review by eteq — APPROVED** [review]
I'm good with this as it stands but I wonder if it might be safer to not assume the socket warnings are between the two other warnings?  I *think* I've seen it on CI in a different order...

**Comment by pllim** [comment]
Hmm... if the warning order is non-deterministic, I'll have to rewrite the logic. Don't merge yet.

**Comment by pllim** [comment]
Getting unrelated errors. I will rebase, just in case.

**Comment by pllim** [comment]
Thanks for the help and the review, @eteq !

**Pull request merged**
