### PR TITLE
Refactor common code in `KingProjectedAnalytic1D`

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

When reviewing the `black` changes in #13960 I noticed that the `KingProjectedAnalytic1D` model could use some refactoring. Initially these changes were part of #13960 but It was decided that the model code refactors should be part of separate PRs like this one.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Let me know if I should add a changelog to this. The effectively executes the same, I just refactored shared code bits into common functions.

**Comment by pllim** [comment]
Was this the one with performance discussions or was that something else? I couldn't keep track.

If user will not see any difference, there is no need for change log. Thanks!

**Comment by WilliamJamieson** [comment]
> Was this the one with performance discussions or was that something else? I couldn't keep track.

Not really, it was just pointed out as going to far for the `black` changes during that discussion.

**Review by nden — APPROVED** [review]
The refactoring looks good. The failure seems to be unrelated.

I wonder about the change in use of `staticmethod`. Previously `evaluate` was a static method. Making it an instance method could be visible from a user perspective. Since the two new functions are also declared as static methods, there's no need to remove the `staticmethod` decorator from `evaluate` and `fit_deriv`. Since this is such an unlikely use I think it's OK to merge but thought I'll point it out.

**Comment by pllim** [comment]
@eerovaher , what is the `black` label for?

**Comment by eerovaher** [comment]
In the January dev telecon it was decided that follow-up pull requests refactoring code that stood out during the `black` campaign but required non-trivial rewriting should also receive the `black` label.

**Pull request merged**
