### PR TITLE
Update lombscargle.rst to indicate units are required for autopower

### LINKED ISSUE #10960: Using LombScargle with units crashes when calling autopower()
### Description

The LombScargle fails to compute ```autpower``` if Times and y values have been passed as ```Quantity``` to ```LombScargle``` . I'm using astropy Version: 4.1 and numpy Version: 1.18.1. See the snippet below
### Code

```python
window_ls = LombScargle(data["Time"] * u.s, np.ones(data["Time"].shape) * u.ct / u.s, fit_mean=False, nterms=1, center_data=False)
frequency_window, power_window = window_ls.autopower(minimum_frequency=minimum_frequency,
                                                         maximum_frequency=0, samples_per_peak=5)
```

### Error
```
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 727, in to_value
    scale = self.unit._to(unit)
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 951, in _to
    f"'{self!r}' is not a scaled version of '{other!r}'")
astropy.units.core.UnitConversionError: 'Unit("s")' is not a scaled version of 'Unit(dimensionless)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 1080, in __int__
    return int(self.to_value(dimensionless_unscaled))
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 730, in to_value
    value = self._to_value(unit, equivalencies)
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 661, in _to_value
    equivalencies=equivalencies)
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 987, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 918, in _get_converter
    raise exc
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 904, in _get_converter
    self, other, self._normalize_equivalencies(equivalencies))
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 888, in _apply_equivalencies
    unit_str, other_str))
astropy.units.core.UnitConversionError: 's' (time) and '' (dimensionless) are not convertible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/agurpide/scripts/swift_scripts/lomb_scargle.py", line 190, in <module>
    samples_per_peak=samples_per_peak)
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/timeseries/periodograms/lombscargle/core.py", line 306, in autopower
    maximum_frequency=maximum_frequency)
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/timeseries/periodograms/lombscargle/core.py", line 249, in autofrequency
    Nf = 1 + int(np.round((maximum_frequency - minimum_frequency) / df))
  File "/home/agurpide/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 1082, in __int__
    raise TypeError('only dimensionless scalar quantities can be '
TypeError: only dimensionless scalar quantities can be converted to Python scalars
```
### Problem
in astropy.timeseries.periodograms.lombscargle.core.py
```
        df = 1.0 / baseline / samples_per_peak

        if minimum_frequency is None:
            minimum_frequency = 0.5 * df

        if maximum_frequency is None:
            avg_nyquist = 0.5 * n_samples / baseline
            maximum_frequency = nyquist_factor * avg_nyquist

        Nf = 1 + int(np.round((maximum_frequency - minimum_frequency) / df))
```
The problem I believe is that while ```df``` is a ```Quantity```, ```maximum_frequency``` and ```minimum_frequency``` are not and thus it crashes. Perhaps a solution could be to allow ```autopower``` to accept ```minimum_frequency``` and ```maximum_frequency``` as ```Quantity``` too.

### PR DESCRIPTION
**Pull request by pkopparla**
### Description

This pull request is to address issue: https://github.com/astropy/astropy/issues/10960
Added a line saying units must be added to arguments of LombScargle.autopower() if units exist for arguments of LombScargle().  

Fixes #10960

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! Need to fix doc warnings:

```
.../docs/timeseries/lombscargle.rst:135: WARNING: py:obj reference target not found: minimum_frequency
.../docs/timeseries/lombscargle.rst:135: WARNING: py:obj reference target not found: maximum_frequency
```

**Comment by pkopparla** [comment]
Hi Lim,
I just changed the formatting to avoid the warning but I'm not sure if it worked. Where should I check to see if that warning still pops-up? Sorry, quite new to this.

**Comment by pkopparla** [comment]
@pllim Great, thank you! Do I need to do anything else? Or do I just leave it as is and it will be included or not when the next release version is finalized?

**Comment by pllim** [comment]
@pkopparla , please hold until a review happens. Thanks!

**Review by mhvk — COMMENTED** [review]
Thanks for the contribution. I think this is not quite in the right place, as I don't think it will be found easily if people run into an error. Instead, as suggested in https://github.com/astropy/astropy/issues/10960#issuecomment-717970473, it may be best to edit the docstring of autopower itself (displayed at https://docs.astropy.org/en/latest/api/astropy.timeseries.LombScargle.html#astropy.timeseries.LombScargle.autopower), which right now states that those frequencies should be `float`, where in reality it depends on the input. Maybe 
```
float or `~astropy.units.Quantity`, optional
 ... Should be `~astropy.units.Quantity` if the frequencies are quantities.
```
(not quite happy with that phrasing...)

**Comment by pkopparla** [comment]
@mhvk I added your comment to the docstring of autopower. Does this look ok?

**Review by mhvk — APPROVED** [review]
Yes, that's good. Thanks!

**Pull request merged**
