### PR TITLE
Fix fits test needing write permission

### LINKED ISSUE #7479: Unit test tries to write to installed library directory
This is a re-incarnation of #7201: 

One `astropy.io.fits` unittest tries to write to a file in the installed library. This fails if one tries to run the test suite without write access to them, f.e. as an ordinary user for a system wide installation.

This makes the [continuous integration test](https://ci.debian.net/packages/a/astropy/unstable/amd64/) of Astropy in Debian fail. From the [test log](https://ci.debian.net/data/autopkgtest/unstable/amd64/a/astropy/313486/log.gz):
```
___________________ TestFileFunctions.test_open_file_handle ____________________

self = <astropy.io.fits.tests.test_core.TestFileFunctions object at 0x7f5ef3304b00>

    def test_open_file_handle(self):
        # Make sure we can open a FITS file from an open file handle
        with open(self.data('test0.fits'), 'rb') as handle:
            with fits.open(handle) as fitsfile:
                pass
    
        with open(self.temp('temp.fits'), 'wb') as handle:
            with fits.open(handle, mode='ostream') as fitsfile:
                pass
    
        # Opening without explicitly specifying binary mode should fail
        with pytest.raises(ValueError):
            with open(self.data('test0.fits')) as handle:
                with fits.open(handle) as fitsfile:
                    pass
    
        # All of these read modes should fail
        for mode in ['r', 'rt', 'r+', 'rt+', 'a', 'at', 'a+', 'at+']:
            with pytest.raises(ValueError):
>               with open(self.data('test0.fits'), mode=mode) as handle:
E               PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/astropy/io/fits/tests/data/test0.fits'

/usr/lib/python3/dist-packages/astropy/io/fits/tests/test_core.py:613: PermissionError
```
Pinging @mangalagb (who was so keen to fix #7201) to have a look here as well?

### PR DESCRIPTION
**Pull request by saimn**
Fix #7479, using the temp directory when write permission is needed.

### CODE REVIEW

**Comment by MSeifert04** [comment]
Lgtm.

Just out of Interest is there a way to test these on travis?

**Comment by MSeifert04** [comment]
Another question: I think i wrote files in the doctests. Are these ok?

**Comment by saimn** [comment]
> Just out of Interest is there a way to test these on travis?

Probably, but it is maybe not so easy to do correctly (to get this working on all platforms, the best option could be to create a read-only directory in the temp directory). But what really needs to be tested ? I mean, opening a file with read-write permission on a read-only filesystem will fail for sure, is there really something useful to test here?

> Another question: I think i wrote files in the doctests. Are these ok?

Good question, I guess those files are written to a temp directory (otherwise you would see them with "git status").

**Comment by saimn** [comment]
> I thought along the lines of simulating the environment which triggered the issue.

I don't see an *issue*, just a test assuming something that is not always true. Testing the environment in the unit test does not mean that this could not happen in another test, the only real solution would be to make the install directory read-only, if this is something that we want to enforce.

> It seems like it is a recurring Problem.

The previous case was slightly different, the test was really creating a new file in the data directory, before removing it.

**Pull request merged**
