### PR TITLE
Unify section header characters (fixes #328)

### LINKED ISSUE #328: Unify section header characters
This is a placeholder if someone has the desire to unify the section header characters throughout the astropy docs to use the same ordering, which is now standardized as `* = - ^ " + : ~`.

I wrote a quick script to determine all unique sets of character orders used in the RST section headers.  I _think_ it works, but this was fast without too much test.  It's here in this gist: https://gist.github.com/3208992.

Upshot: for astropy RST files in docs/ the sets we use are:

```
  % find . -name "*.rst" | xargs ./header_chars.py
  ...  # bunch of files and their section orderings
  #*=
  *=-"
  *=-^"
  -^".
  -^">
  =-^"
  =-`
```

You can find which files correspond to a particular set with (e.g.):

```
  % find . -name "*.rst" | xargs ./header_chars.py | grep '=-`'
  ./wcs/history.rst =-`
  =-`
```

It's probably not much work to take this script and extend to actually do the fixing.

### PR DESCRIPTION
**Pull request by helenst**
Adapted the original header_chars.py gist to make a replacement script. https://gist.github.com/helenst/18f403584a0e7edb3c0e

### CODE REVIEW

**Comment by helenst** [comment]
Yes, it's easy for me to re-run the script on whatever docs are current at the time this goes in. I think the best thing is to rebase / recreate the branch at that point. It'll also involve a PR to astropy_helpers - I'm adding a sphinx ext to check for out of sequence headers when the docs build.

It's just about ready now... @embray @astrofrog @eteq please ping me whenever you'd like this.

**Comment by astrofrog** [comment]
@helenst - all the other changes for 1.0 are now done, so feel free to update this PR when you have time - thanks!

**Comment by astrofrog** [comment]
I'm going to remove the milestone since while this would be nice, it is not 'release-critical'

**Comment by bsipocz** [comment]
@helenst - Are you interested in wrapping this up? I'm afraid there are tons of changes since, so probably rerunning the script on master and force pushing it back to this branch would be the least painful way to do it. 
Also more importantly, could you add the modified script to the astropy-tools repo (https://github.com/astropy/astropy-tools)?

**Comment by helenst** [comment]
@bsipocz Absolutely! :) I guess it's been a while and a lot's changed - will try and find some time to get my head back into this and update the PR.

**Comment by helenst** [comment]
Hmm - I just created a new branch and forgot to commit the result of my new script run before force pushing, which seemed to make GitHub close this off. I'll try again with an actual commit and see if that helps. :smile:

**Comment by bsipocz** [comment]
There is a valid sphinx failure due to title level inconsistency in ``astropy/nddata/utils``, could you please check and revise the script as needed?
https://travis-ci.org/astropy/astropy/jobs/222538582#L3388

**Comment by bsipocz** [comment]
Closing as #6057 overrides this. Thanks @helenst for your work on it. Your commit from this PR is moved over to the new PR to preserve the credit for your contribution.

**Pull request closed without merging**
