### PR TITLE
Correct two minor problems with `io.fits` documentation

### PR DESCRIPTION
**Pull request by cgobat**
### Description

This pull request addresses some minor errors in FITS-related documentation:
- Pairs of backticks and quotation marks in the docstring for `_BaseHDU.writeto()` were not all closed/consistent, which led to odd/improper formatting when rendered in markdown.
- `np.arange(x)` called with no additional arguments creates an array from `0(.0)` to `x(.0)`, not `x.9`.

---

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Good catch, thanks!

**Comment by pllim** [comment]
I restarted RTD to pick up a new upstream release. 🤞

**Comment by pllim** [comment]
Oh, great, it is sphinx-gallery now.

**Comment by cgobat** [comment]
Of course! Thanks for the rapid review and merge!

**Comment by pllim** [comment]
No worries. Gotta balance out the universe sometimes. Can't have all the PRs sit for a few years. 😉

**Pull request merged**
