### PR TITLE
Fast str / repr for Time/TimeDelta objects

### LINKED ISSUE #5846: Time __repr__ slow for large time arrays when format is 'iso'
The following example illustrates a performance issue:

```
In [10]: x = np.arange(1e7)

In [14]: time = Time(x, format='unix')

In [20]: time.format = 'iso'

In [21]: time
Out[21]: # hangs for a while before showing the result
```

I think the issue is that the strings are being prepared for ALL times even though the repr ends up showing only the first/last few. This could be optimized.

### PR DESCRIPTION
**Pull request by taldcroft**
### Description

This pull request is to address the slow `str` / `repr` for Time objects highlighted in #5846 and #13549 (dup).

This is a WIP. The strategy here is basically replicating the behavior of the np.ndarray repr for Time objects so that the potentially-expensive operation of making str representations of the values is only done for the ones that are actually output.

@mhvk - I couldn't think of a clever way to use the numpy repr functionality itself so I went down the path of re-implementing it. But before I write tests maybe you have an idea?

This implementation handles N-d arrays in a way that is reasonably close to numpy native output (at least in spirit but not down to every last character).

My main question is about scope. This PR now overrides numpy formatting for all TimeBase objects regardless of format. I thought about splitting out string-based formats but I was thinking maybe some numeric formats could also be expensive to compute.

Fixes #5846

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by taldcroft** [comment]
@astrofrog @theXYZT - please give this a try!

**Comment by taldcroft** [comment]
It's worth noting that in its current form this is definitely much slower than current main to generate the repr of a Time object that is NOT huge. That's because it ends up making up to 1000 Time objects. So that might need some thought.

**Comment by mhvk** [comment]
@taldcroft - I had only a quick look but think this approach makes the most sense. In principle, it should be possible to use the `np.array2string` machinery, but I don't think it would be less code (e.g., see `np.ma.core.MaskedArray.__repr__` or our own `utils.masked.function_helpers.MaskedFormat`), and I think it would rely on getting other numpy functions to work too (effectively, I think the standard approach is to make a smaller array with only the pieces that are shown and then typesetting that). Overall, my sense would be to proceed with this and just improve it later.

**Comment by taldcroft** [comment]
@mvhk - I had previously thought about the smaller-version-of-the-array approach before, and for some reason I thought it wouldn't work out. But coming back to that idea, it seems like it might work. Here's the idea:
- First check if the size > threshold (`np.get_printoptions()['threshold']`). If small then just print the whole array like now.
- Make a new smaller version of the array with no dimension larger than `2 * edge_items + 1`. This is filled with the start and end edge items plus 1 in the middle (which numpy will replace with `...`).
- In a print_options context manager with `threshold = 1` print the new smaller version.

Can you think of any obvious problems with this?

**Comment by mhvk** [comment]
No, I think it should work. I mostly wondered about creating the smaller array, but thinking more, with `info._new_like` this really is not that difficult!

**Comment by taldcroft** [comment]
I got excited that it could be basically a one-liner when I noticed this works:
```
>>> dims = [8, 2, 8]
>>> dx = np.arange(np.prod(dims)).reshape(dims) 
>>> tm = Time('2020-01-01') + dx * u.day

>>> print(np.array2string(tm, formatter={'all': lambda x: x.value}), threshold=10, edgeitems=2)
```
But then I did a test with a huge array and sadly numpy seems to be calling the formatting function on every element. That doesn't quite make sense to me, but for now I have a new implementation which is coming.

**Comment by taldcroft** [comment]
Superceded by #13555.

**Pull request closed without merging**
