### PR TITLE
Additional spectral density equivalencies

### PR DESCRIPTION
**Pull request by astrofrog**
This implements some of the spectral density equivalencies described in #440. I/We still need to add conversion to/from ``photons s^-1 [area^-1] spectralunit^-1``, and optionally including conversions where the spectral unit is energy rather than wavelength or frequency.

@eteq - feel free to add some of these if you want, as I probably won't be able to do it this week. I don't think it's 0.2 crucial though.

### CODE REVIEW

**Comment by mhvk** [comment]
@astrofrog - in the spirit of the mailing list discussion, I assigned this to myself. Looking at the PR, there really seem to be two parts, one somewhat reworking the units core, the other rewriting the equivalencies. It is probably the former that prevents merging, since the equivalency part of `core.py` has been changed.  Would it be an idea to split this PR in two pieces?

**Comment by astrofrog** [comment]
@mhvk - looking back on this, I think that we should *not* add equivalencies for fnu -> nu*fnu (see https://github.com/astropy/astropy/pull/692#issuecomment-12802323). The user can do that themselves. However, I think what might still be useful is the conversion including photons. I'll look into that.

Also, I'm not sure if @mdboom went ahead and merged 6d496f5  manually (can try and check later)

**Comment by astrofrog** [comment]
The photon equivalencies were added by @pllim in https://github.com/astropy/astropy/pull/1560 - so this issue is now moot :)

**Comment by pllim** [comment]
I like it when I read things like this on a Monday! :)

**Pull request closed without merging**
