### PR TITLE
Fixing consistency of default values of table.operations

### PR DESCRIPTION
**Pull request by bsipocz**
@taldcroft - I wonder whether you mind to change the default ``join_type``-s, so that all of the private and public [vh]stack functions have the same?

### CODE REVIEW

**Comment by embray** [comment]
Oh I see, this is just a documentation fix, right?

**Comment by bsipocz** [comment]
@embray - Yes, but I would wait for @taldcroft's answer and if he gives the green light include those non-doc changes, too.

**Comment by taldcroft** [comment]
Oh dear, yes there seems to be an excessive variety of default values (and inconsistencies) in the methods and docstrings.

It would be fine to change the default keyword parameter values in the private methods `_vstack` and `_hstack`.  For the two public methods the defaults need to stay at `outer`.  Thus changing all the documentation and the private method defaults to `outer` would be great.  I notice that in your initial commit you were putting the `_vstack` default to `inner`.  Was there a reason?

**Comment by bsipocz** [comment]
@taldcroft - In the original commit I've just updated the docstring to show what the actual default is. I'll update everything to be ``outer`` in a new commit.

**Comment by taldcroft** [comment]
This looks good @bsipocz, thanks!  As a fix to incorrect docstrings, and change of defaults in non-public methods, I think no update to the change log is warranted.  @embray?

**Comment by embray** [comment]
:+1:

**Pull request merged**
