### PR TITLE
EXP: Test Revert "Revert "Updating spinner API, keeping enum""

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to see if Spinner is the culprit for the RTD time out in #11772 .

### CODE REVIEW

**Comment by pllim** [comment]
No timeout here but got an error from the doc build below, so at least one example Python script being rendered is calling the spinner, which would explain the timeout.

```
...
Successfully installed PyYAML-5.4.1 asdf-2.8.0 astropy-4.3.dev1604+gd34897500 astropy-sphinx-theme-1.1 attrs-21.2.0 backcall-0.2.0 beautifulsoup4-4.9.3 bleach-3.3.0 bottleneck-1.3.2 click-8.0.1 click-default-group-1.2.2 cloudpickle-1.6.0 cycler-0.10.0 dask-2021.5.0 decorator-5.0.9 docutils-0.16 fsspec-2021.5.0 h5py-3.2.1 html5lib-1.1 importlib-resources-5.1.4 incremental-21.3.0 iniconfig-1.1.1 ipython-7.23.1 ipython-genutils-0.2.0 jedi-0.18.0 jmespath-0.10.0 jplephem-2.15 jsonschema-3.2.0 kiwisolver-1.3.1 locket-0.2.1 matplotlib-3.4.2 matplotlib-inline-0.1.2 mpmath-1.2.1 numpy-1.20.3 numpydoc-1.1.0 pandas-1.2.4 parso-0.8.2 partd-1.2.0 pexpect-4.8.0 pickleshare-0.7.5 pillow-8.2.0 pluggy-0.13.1 prompt-toolkit-3.0.18 ptyprocess-0.7.0 py-1.10.0 pyerfa-2.0.0 pyrsistent-0.17.3 pytest-6.2.4 python-dateutil-2.8.1 scipy-1.6.3 semantic-version-2.8.5 sortedcontainers-2.4.0 soupsieve-2.2.1 sphinx-3.5.4 sphinx-astropy-1.3 sphinx-automodapi-0.13 sphinx-changelog-1.1.1 sphinx-gallery-0.9.0 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-2.0.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 toml-0.10.2 toolz-0.11.1 towncrier-21.3.0 traitlets-5.0.5 wcwidth-0.2.5 webencodings-0.5.1 zipp-3.4.1
...
WARNING: /home/docs/checkouts/readthedocs.org/user_builds/astropy/checkouts/11779/examples/coordinates/plot_obs-planning.py failed to execute correctly: Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/checkouts/11779/examples/coordinates/plot_obs-planning.py", line 58, in <module>
    m33 = SkyCoord.from_name('M33')
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/astropy/coordinates/sky_coordinate.py", line 2054, in from_name
    icrs_coord = get_icrs_coordinates(name, parse, cache=cache)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/astropy/coordinates/name_resolve.py", line 164, in get_icrs_coordinates
    download_file(url, cache=cache, show_progress=False))
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/astropy/utils/data.py", line 1357, in download_file
    f_name = _download_file_from_source(
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/astropy/utils/data.py", line 1194, in _download_file_from_source
    p.update(bytes_read)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/astropy/utils/console.py", line 1036, in update
    self._obj.update(value)
AttributeError: 'nullcontext' object has no attribute 'update'


Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx/events.py", line 111, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx_gallery/gen_gallery.py", line 454, in generate_gallery_rst
    generate_dir_rst(src_dir, target_dir, gallery_conf,
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 381, in generate_dir_rst
    intro, title, cost = generate_file_rst(
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 862, in generate_file_rst
    output_blocks, time_elapsed = execute_script(script_blocks,
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 784, in execute_script
    output_blocks.append(execute_code_block(
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 622, in execute_code_block
    except_rst = handle_exception(sys.exc_info(), src_file, script_vars,
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 608, in execute_code_block
    mem_max, _ = gallery_conf['call_memory'](
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx_gallery/gen_gallery.py", line 205, in call_memory
    return 0., func()
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 516, in __call__
    exec(self.code, self.fake_main.__dict__)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/checkouts/11779/examples/coordinates/plot_obs-planning.py", line 58, in <module>
    m33 = SkyCoord.from_name('M33')
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/astropy/coordinates/sky_coordinate.py", line 2054, in from_name
    icrs_coord = get_icrs_coordinates(name, parse, cache=cache)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/astropy/coordinates/name_resolve.py", line 164, in get_icrs_coordinates
    download_file(url, cache=cache, show_progress=False))
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/astropy/utils/data.py", line 1357, in download_file
    f_name = _download_file_from_source(
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/astropy/utils/data.py", line 1194, in _download_file_from_source
    p.update(bytes_read)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/astropy/utils/console.py", line 1036, in update
    self._obj.update(value)
AttributeError: 'nullcontext' object has no attribute 'update'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx/application.py", line 278, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx/application.py", line 337, in _init_builder
    self.events.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/11779/lib/python3.8/site-packages/sphinx/events.py", line 119, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function generate_gallery_rst at 0x7ff9e6b0f700> for event 'builder-inited' threw an exception (exception: 'nullcontext' object has no attribute 'update')

Extension error (sphinx_gallery.gen_gallery):
Handler <function generate_gallery_rst at 0x7ff9e6b0f700> for event 'builder-inited' threw an exception (exception: 'nullcontext' object has no attribute 'update')
```

**Comment by pllim** [comment]
Maybe this script shouldn't try to access remote data every run. No reason why we can't hardcode M33 location, right, @adrn ?

https://github.com/astropy/astropy/blob/3f30432d079e6fc07cbcb0d29437f76e33027a1b/examples/coordinates/plot_obs-planning.py#L58

**Comment by adrn** [comment]
I like that the example demonstrates the `.from_name()` classmethod here, but probably not worth the demonstration at the expense of remote data headaches...

**Comment by pllim** [comment]
Well... must be something else. Just the `from_name` fix isn't enough.

**Comment by embray** [comment]
I don't get it, isn't this a duplicate of #11772?

**Comment by embray** [comment]
Oh, I missed where the data module used `ProgressBarOrSpinner`.  That might reveal the problem then...

**Comment by embray** [comment]
> Maybe this script shouldn't try to access remote data every run. No reason why we can't hardcode M33 location, right, @adrn ?

I think it's fine.  It's just revealing the actual bug.

**Comment by embray** [comment]
I have a fix over in #11772.  I'm really sorry, this mess is all my fault.  I never should have approved the original PR as it was.

**Comment by pllim** [comment]
No worries. Glad you found the actual problem. Thanks!

**Pull request closed without merging**
