### PR TITLE
WIP: testing module importability without optional dependencies

### PR DESCRIPTION
**Pull request by bsipocz**
DO NOT MERGE

To close https://github.com/astropy/astropy/issues/7939

Locally it doesn't pass, but we can discuss what is OK to be skipped for these tests and what needs fixing.

### CODE REVIEW

**Comment by pllim** [comment]
Is it just me, or Travis CI not showing up?

**Comment by bsipocz** [comment]
the yaml file is messed up atm, I'm trying to multitask fix it. Also note that this points to my fork ci-helpers, so do not merge in any case.

**Comment by bsipocz** [comment]
this is failing horridly due to all kind of unrelated numpy issues, but if you into the travis details this build is the only relevant here:

https://travis-ci.org/astropy/astropy/jobs/445288366

**Comment by pllim** [comment]
https://travis-ci.org/astropy/astropy/builds/449134809 reported `ImportError` on 18 modules but it is unclear why. Some of those don't look like they have `pytest` dependencies...?

**Comment by pllim** [comment]
Looks like the error messages are collected but not reported:

https://github.com/bsipocz/ci-helpers/blob/e89474b49305123ebdddb994d45aeeb65b8619dd/utils/import_submodules.py#L61

**Comment by bsipocz** [comment]
@pllim - I tried the other way, but there are so many that it seemed a bit useless to print all as an error, but it's not at all a preference, I'm happy to change the script.

Also, I'm not exactly sure why numpy is picked up from the compatibility module, the stuff it reports is not even in there.

**Comment by pllim** [comment]
I *think* the recursive import is *too* recursive? For example, maybe when the module does `from numpy import ...`, it goes into `numpy` and so on.

**Comment by pllim** [comment]
p.s. Can probably exclude things like `setup_package.py` from import test. Not sure why `wcsaxes` failed though.

**Comment by bsipocz** [comment]
@pllim - I've hacked a bit more on the ci-helpers side, and also added a few more files/modules here to skip. 
There are still a few failures around, but probably nothing surprising in that io.misc.asdf is not importable when asdf is not installed ;)
(though I don't yet know what's the issue with utils.xml).

**Comment by bsipocz** [comment]
(the `wcsaxes` import issues is due to the fact that it uses `pytest` to skip the module being tested when there is no mpl installed. However, for this tests, we remove pytest, too).

**Comment by bsipocz** [comment]
OK, so I suppose this now needs to be added to one of the pipelines, e.g. on circleCI. What do you think @astrofrog?

(as well as fix the remaining failures)

**Comment by astrofrog** [comment]
I would add this to Travis unless there is a good reason to add it to CircleCI. Instead of using wget, could you use urlretrieve in a ``python -c`` call so that it works on all platforms?

**Comment by bsipocz** [comment]
My only reason for circleCI was that this ideally could live in a pipeline. First run this, then install the test dependencies without the need to rebuild astropy.

I can certainly factor out wget, but didn't think we want to run it in other platforms. Arguably the script would work, but I haven't tested it on windows.

**Comment by astrofrog** [comment]
So coming back to this, I wonder whether actually having https://github.com/astropy/astropy/pull/10358 is sufficient? Essentially the doctest collection triggers an import of every module and will complain if an import doesn't work, and also is able to take into account special cases as specified in the ``setup.cfg``. So maybe we have accidentally solved this issue and don't need an additional set of tests?

**Pull request closed without merging**
