### PR TITLE
asdftypes is deprecated, use asdf.types

### PR DESCRIPTION
**Pull request by nden**
@drdavella Can this go in the 3.1 release?
Is astropy tested with asdf and if so which version?

### CODE REVIEW

**Comment by bsipocz** [comment]
> Is astropy tested with asdf and if so which version?

It is tested with pip installing the latest release from PyPI.

**Comment by drdavella** [comment]
If people are okay with getting this into 3.1, I can try to make an ASDF release sometime tomorrow or Weds at the latest.

**Comment by bsipocz** [comment]
@drdavella - Added the milestone, please ping me on slack when you're down with the release.

**Comment by drdavella** [comment]
ASDF 2.3 is now available. It will be necessary to update the requirements in the CI configs and also in the `importorskip`s.

@nden let me know if you want me to just push these changes directly to your branch.

**Comment by bsipocz** [comment]
@eteq @astrofrog - Even though this has missed RC2, I suppose it's OK to include it in the final 3.1 release?

**Comment by astrofrog** [comment]
That's fine by me

**Comment by drdavella** [comment]
Thanks @nden!

**Pull request merged**
