### PR TITLE
OSX 10.6 build compatibility

### PR DESCRIPTION
**Pull request by jhunkeler**
Apple GCC 4.2.1 has neither `no-unused-result` or `no-unused-but-set-variable` compiler flags. The presence of these are causing our nightly builds to fail.

### CODE REVIEW

**Comment by pllim** [comment]
c/c @embray, @eteq, @astrofrog

**Comment by nden** [comment]
This has come up in the past and is due to an old compiler.

**Comment by pllim** [comment]
@nden, what was the past resolution?

**Comment by nden** [comment]
I believe this is a local configuration issue, just mentioning it here to avoid duplicate work but Joe should confirm this when he gets a chance.

**Comment by embray** [comment]
Right, this has come up before.  As I explained last time it came up I don't mind applying this patch, but would prefer to see users update their compilers, as this is very old.  On OSX that might not be as easy though.

In the long-term a compiler version check might be nice.

**Comment by eteq** [comment]
@jhunkeler - but this will cause the warnings to *appear* on newer compilers, right?  Perhaps you can add a check for the particular version of gcc (or OS X 10.6 if it seems too difficult to get at the compiler) and only remove it for that case?

**Comment by embray** [comment]
The warnings aren't that important either way.  In gcc 4.4 and up, unrecognized `-Wno-` flags are ignored.  I would like to have a utility (or set of utilities) in astropy-helpers that can parse the actual gcc version (where applicable) and not bother adding most `-Wno-` flags for older gcc versions.  

As I said, these flags aren't that important in the first place since I'm just trying to cut down on compilation noise, and the code being compiled with them is from a third-party project where I may not be able to just get all the warnings fixed directly.  I'd like to keep the warning suppressions in general but it's no harm to drop them on older compiler versions.

**Comment by nden** [comment]
@embray Any reason NOT to merge this?

**Comment by nden** [comment]
@embray This is holding up local builds. Would be nice to resolve it.

**Comment by astrofrog** [comment]
I think @embray's preference would be that these are only conditionally dropped on old compiler versions. But if it's holding up builds and needs an urgent fix, then I think we can merge it and open an issue to conditionally add them back.

**Comment by embray** [comment]
Yeah, I'll just open a separate issue to add compiler version checking. This already mostly exists in astropy-helpers but could use a little more work...

**Pull request merged**
