### PR TITLE
Replace OrderedDict with dict in nddata module

### PR DESCRIPTION
**Pull request by felipekhouri**
### Description

Following the discussion in issue #10888, this Pull Request is to replace the usage of `OrderedDict` with `dict` in the `nddata` module. This change is motivated by the fact that, starting from Python 3.7, the standard dictionary (`dict`) maintains the order of elements, rendering `OrderedDict` unnecessary.

I have made the necessary replacements and ensured that all functionalities continue to work as expected. Additionally, I have updated the tests to reflect this change.

Fixes one of #10888 tasks.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by felipekhouri** [comment]
pre-commit.ci autofix

**Comment by pllim** [comment]
Thanks! I cannot decide if this needs a change log or not, so deferring to subpackage maintainers.

**Comment by bmorris3** [comment]
I'd say it does not need a changelog.

**Comment by felipekhouri** [comment]
I don't know why the RTD check failed. Am I missing something? @pllim

**Review by bmorris3 — APPROVED** [review]
Looks good. I believe the rtd failure is unrelated.

**Comment by pllim** [comment]
Yup, RTD failure was caused by scipy doc SSL cert, which has been fixed upstream since. Thanks, merging!

**Pull request merged**
