### PR TITLE
Fix format units for solar positions

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by pllim** [comment]
What's the intended milestone? Does it need a change log?

**Comment by Cadair** [comment]
@bsipocz has it right, it's an affects-dev it's a small mistake in #9275

**Comment by pllim** [comment]
Ah, okay, you introduce the bug and then proceed to fix it. You sure you not trying to jack up the Hacktoberfest count? 😉

**Comment by bsipocz** [comment]
@Cadair - this has real looking failures

**Pull request merged**
