### PR TITLE
Split out compressed header conversions into separate file

### PR DESCRIPTION
**Pull request by astrofrog**
*This builds on https://github.com/astropy/astropy/pull/15141 and should be rebased once it is merged - not ready for review until then since many unrelated changes.*

A lot of code in ``CompImageHDU`` relates to converting between image and compressed headers, and this can be factored out into two helper functions in a separate file. This helps further simplify the main ``compressed.py`` file which is then 'only' 1060 lines. Having these functions split out in this way helps make the code more approachable and will also help simplify the diff when I propose the main refactoring of ``CompImageHDU``.

There are no API changes for users here.

### CODE REVIEW

**Comment by saimn** [comment]
Need a rebase :)

**Review by saimn — APPROVED** [review]
Looks good to me.

**Comment by saimn** [comment]
@astrofrog - Maybe the content of `_tiled_compression/` could also be moved in `compressed/` ?

**Comment by pllim** [comment]
You forgot milestone. I added for you. FYI.

**Comment by saimn** [comment]
Oops, thanks @pllim :)

**Pull request merged**
