### PR TITLE
Remove trailing references to astropy's own ErfaWarning

### LINKED ISSUE #10648: TST: apply_space_motion no longer emits ErfaWarning in remote data/dev job
Example log: https://travis-ci.org/github/astropy/astropy/jobs/717518434 (first 2 failures)

```
____________________________ test_regression_10092 _____________________________
    def test_regression_10092():
        """
        Check that we still get a proper motion even for SkyCoords without distance
        """
        c = SkyCoord(l=10*u.degree, b=45*u.degree,
                     pm_l_cosb=34*u.mas/u.yr, pm_b=-117*u.mas/u.yr,
                     frame='galactic',
                     obstime=Time('1988-12-18 05:11:23.5'))
    
        with pytest.warns(ErfaWarning, match='ERFA function "pmsafe" yielded .*'):
            # expect ErfaWarning here
>           newc = c.apply_space_motion(dt=10*u.year)
E           Failed: DID NOT WARN. No warnings of type (<class 'erfa.core.ErfaWarning'>,) matching ('ERFA function "pmsafe" yielded .*') was emitted. The list of emitted warnings is: [ErfaWarning('ERFA function \'pmsafe\' yielded 1 of "distance overridden (Note 6)"')].
../../.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/coordinates/tests/test_regression.py:641: Failed
___________________________ test_apply_space_motion ____________________________
    def test_apply_space_motion():
        # use this 12 year period because it's a multiple of 4 to avoid the quirks
        # of leap years while having 2 leap seconds in it
        t1 = Time('2000-01-01T00:00')
        t2 = Time('2012-01-01T00:00')
    
        # Check a very simple case first:
        frame = ICRS(ra=10.*u.deg, dec=0*u.deg,
                     distance=10.*u.pc,
                     pm_ra_cosdec=0.1*u.deg/u.yr,
                     pm_dec=0*u.mas/u.yr,
                     radial_velocity=0*u.km/u.s)
    
        # Cases that should work (just testing input for now):
        c1 = SkyCoord(frame, obstime=t1, pressure=101*u.kPa)
        with pytest.warns(ErfaWarning, match='ERFA function "pmsafe" yielded .*'):
            # warning raised due to high PM chosen above
            applied1 = c1.apply_space_motion(new_obstime=t2)
>           applied2 = c1.apply_space_motion(dt=12*u.year)
E           Failed: DID NOT WARN. No warnings of type (<class 'erfa.core.ErfaWarning'>,) matching ('ERFA function "pmsafe" yielded .*') was emitted. The list of emitted warnings is: [ErfaWarning('ERFA function \'pmsafe\' yielded 1 of "distance overridden (Note 6)"'), ErfaWarning('ERFA function \'pmsafe\' yielded 1 of "distance overridden (Note 6)"')].
../../.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/coordinates/tests/test_sky_coord.py:1613: Failed
```

If the warning is no longer emitted on purpose, `pytest.warns` needs to be removed. Otherwise, if a warning is expected, this is a symptom of a bug.

### PR DESCRIPTION
**Pull request by StuartLittlefair**
### Description

Since moving to a standalone pyerfa package, some references to ErfaWarning from astropy.utils.exceptions remained.

This removes them, hopefully fixes #10648

### CODE REVIEW

**Comment by pllim** [comment]
I'll milestone this same as #10329 then. Thanks! 🤞

**Comment by pllim** [comment]
Didn't fix it. Now that you mention `pyerfa` is external, I think they modified the message too. That would explain why it only shows up on dev job. Might need some regex magic to consolidate the differences between stable and dev.

```
E           Failed: DID NOT WARN. No warnings of type (<class 'erfa.core.ErfaWarning'>,) matching ('ERFA function "pmsafe" yielded .*') was emitted. The list of emitted warnings is: [ErfaWarning('ERFA function \'pmsafe\' yielded 1 of "distance overridden (Note 6)"'), ErfaWarning('ERFA function \'pmsafe\' yielded 1 of "distance overridden (Note 6)"')].
```

**Comment by StuartLittlefair** [comment]
Damn. I’ll dig into this later - out climbing now...

**Comment by mhvk** [comment]
@StuartLittlefair, @pllim - thanks so much for noticing/fixing, and apologies for not doing it myself! I think it should be possible to get the warnings caught, even if it is just with a more tailored `regex`.

Otherwise, main comment is a total nitpick: to move the `erfa` imports out of the ones for astropy, instead together with `numpy`.

p.s. Also feel free to just assign it to me, i.e., let me deal with my own sloppiness...

**Comment by pllim** [comment]
I'll let you two coordinate how to proceed. Marten could push to this branch. He can also open a PR to this fork's branch. He can also open alternate PR with cherry-pick from this PR. Or he could offer code suggestion via PR review feature. 😸

**Comment by StuartLittlefair** [comment]
@mhvk happy to finish this up, but would like your opinion on how to proceed: the issue is indeed that the warning msg in erfa has changed recently thanks to https://github.com/liberfa/pyerfa/commit/00c3334bc2c41bc7bbaedd6afdc02dad357d2c7e

I would have thought the best thing to do is to push a commit to PyERFA changing that line to 

```python
warnings.warn('ERFA function "{}" yielded {}'.format(func_name, wmsg), ErfaWarning)
```

so that the warning message is unchanged...

**Comment by mhvk** [comment]
@StuartLittlefair - oops, that was certainly an unintended side effect of cleanup! I'll change it back at `pyerfa`.

**Pull request merged**
