### PR TITLE
Added Planetary Physical Parameters

### PR DESCRIPTION
**Pull request by Dolgalad**
### Description

This pull request is to address missing planetary constants : mass and equatorial radius of the following planets and dwarf planets and enable using these constants as units.
Values taken from : https://ssd.jpl.nasa.gov/planets/phys_par.html

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Hello and thanks! Unfortunately a few things are still needed:

* tests need to be fixed
* are new tests needed?
* make sure you check to see if this needs to be added to other versions of constants
* documentation needs to be added
* a change log
* a what's new entry

**Comment by Dolgalad** [comment]
I'm having trouble understanding the correct way to implement tests for constants and the associated units. Checking that the object attributes are set an not empty seems natural, but I also see that the value of the reference is checked against it's expected value. 
I feel reluctant to test each reference value.

**Comment by pllim** [comment]
For unit tests, maybe test against a small but representative subset for your implementation, see examples in https://github.com/astropy/astropy/tree/main/astropy/constants/tests .

We also run doctest, so if you write testable snippets in the documentation (prepend with `>>>`), those will be tested too. Please see `docs/constants/index.rst`.

For general development guidelines, please see https://docs.astropy.org/en/latest/#developer-documentation .

Hope this helps!

**Comment by mhvk** [comment]
@Dolgalad - thanks for the PR! We need to be careful here, though: the current IAU constants also define some of these (e.g., `R_earth`; these come from https://iopscience.iop.org/article/10.3847/0004-6256/152/2/41). If we go with this, we'd need some way to chose between the values.

I also wonder a bit more generally whether these planetary values belong in the core astropy package: these numbers would seem useful almost exclusively to people working on solar system planets and hence might be more appropriate in a domain-specific (astropy-affiliated) package. Let me ping co-maintainer @stargaser for his opinion.

**Comment by stargaser** [comment]
I am inclined towards placing these values in a separate domain-specific affiliated package.

**Pull request closed without merging**
