### PR TITLE
Fix Gaussian convolution description

### PR DESCRIPTION
**Pull request by larrybradley**
### Description

This PR corrects the description of the mean position resulting from the convolution of two Gaussians.  It also adds color and a legend to the corresponding plot.

New:

compound-models-2

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by pllim — COMMENTED** [review]
Do we want to make it more accessible to color-blind audience by also using different line styles?

**Comment by larrybradley** [comment]
I thought the default `matplotlib` color cycler (since 2.0) was already colorblind friendy.

**Comment by pllim** [comment]
I am not color-blind, so I will just have to trust you on this one. Thanks for the clarification!

**Comment by pllim** [comment]
Used to be recommended too in case people print in black and white, but I guess printer is kinda obsolete nowadays. Let's get this in then.

**Review by pllim — APPROVED** [review]

**Comment by pllim** [comment]
For future reference, as a maintainer, you should be able to add the appropriate backport label as well when you set the milestone to be backported. Thanks!

**Pull request merged**
