### PR TITLE
Fix image vertical orientation in fits2bitmap script

### LINKED ISSUE #6841: Vertical image orientation flip in fits2bitmap
I find that `fits2bitmap` results in images that have the output vertical orientation flipped wrt. how the FITS image appears by default in DS9.

@larrybradley - Is this on purpose or by accident? Change orientation to match?

To reproduce:
```
wget http://data.astropy.org/tutorials/FITS-images/HorseHead.fits
fits2bitmap HorseHead.fits
```
With `ds9 HorseHead.fits` the horsie is looking up:
ds9

With `open HorseHead.png`, i.e. the `fits2bitmap` output, the horsie is looking down:
fits2bitmap

### PR DESCRIPTION
**Pull request by larrybradley**
Fixes #6841.

Thanks for reporting this, @cdeil!

### CODE REVIEW

**Comment by larrybradley** [comment]
`circle-ci` is failing because of the "Downloading" line returned by a doctest.  What's currently the best way to fix this?

```
195     >>> lf = AltAz(location=EarthLocation.of_site('greenwich'),
Expected nothing
Got:
    Downloading http://data.astropy.org/coordinates/sites.json [Done]
```

@bsipocz, @astrofrog, @drdavella

**Comment by larrybradley** [comment]
I suppose this should go in after https://github.com/astropy/astropy/pull/6840.

**Comment by cdeil** [comment]
@larrybradley - Thank you!

The fix and test look good to me.

**Comment by bsipocz** [comment]
@larrybradley - the temporary fix has been merged

**Comment by larrybradley** [comment]
Thanks, @bsipocz.  I've rebased on master.

**Pull request merged**
