### PR TITLE
Added inline comment about MaskedArrayFutureWarning

### PR DESCRIPTION
**Pull request by pllim**
Address https://github.com/astropy/astropy/issues/6285#issuecomment-311288174

Also see #6261 

If v2.0.1 is not a reasonable milestone for this, feel free to re-milestone.

### CODE REVIEW

**Comment by pllim** [comment]
I set the commit to skip CIs, but now the status of the PR is stuck at "some checks haven’t completed yet" and "required statuses must pass before merging"...

**Comment by bsipocz** [comment]
@pllim - The master branch is now protected, meaning there should be passing CIs for it.

cc @astrofrog

**Comment by pllim** [comment]
So `[ci skip]` is no longer an option?

**Comment by bsipocz** [comment]
We need to see how the experiment goes, but yes, it's not an option for now, at least not for the last commit in a PR.

**Comment by pllim** [comment]
Hmm, okay, I'll re-write the commit. Thank you for the info.

**Comment by bsipocz** [comment]
@pllim - Docs stuff like this can still go into the actual 2.0 release so feel free to milestone to 2.0 where it's sensible. If a PR is not finished by the time of doing the release, I can always remilestone them to 2.0.1

**Comment by bsipocz** [comment]
This seems sensible, so merging. 

We need to make sure though to regularly check the codebase for github links like this to spot obsolete workarounds.

**Comment by pllim** [comment]
For this particular one, it is officially an issue for the future as #6285.

**Pull request merged**
