### PR TITLE
Need import_array with Cython 3.0

### PR DESCRIPTION
**Pull request by saimn**
Fix compilation with Cython 3.0a11 
(see https://github.com/astropy/astropy/pull/14035#issuecomment-1327902857)

### Description

This pull request is to address ...

Fixes #<Issue Number>

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by astrofrog** [comment]
This looks good for now - though I wonder if we can just get rid of the references to Numpy in the C code since we wrap it with Cython and aren't dealing with Numpy arrays at the C level. As far as I can see this is only used to define the dtype which should basically always be the same?

**Comment by astrofrog** [comment]
Marking as needing backport to LTS even though that will fail for now, just so I don't forget to do it later manually.

**Review by astrofrog — APPROVED** [review]

**Comment by saimn** [comment]
The conflict is because I did the backport of #14035 manually and it's not merged yet: #14045
We can backport this one after, or I can cherry pick the commit in the other backport.

**Comment by saimn** [comment]
> As far as I can see this is only used to define the dtype which should basically always be the same?

Yes, I think at the C level Numpy is only used to define the array type to `npy_float64`. We could use `double` instead. 
However we need Numpy in the Cython wrapper to access the pointer to the data array. Unless there is some feature I missed I couldn't use memory views because the arrays passed to Cython can be 1d, 2d or 3d, and with memory views the number of dimensions must be specified.

**Comment by pllim** [comment]
@meeseeksdev backport to v5.0.x

**Comment by pllim** [comment]
For future reference, when you apply `backport-to-v5.0.x` label, please also update the milestone to match, so our sanity check will not break our minds. Thanks!

**Pull request merged**
