### PR TITLE
`names_from_data` block is only run when `names` is None. Addresses #6408

### PR DESCRIPTION
**Pull request by tomr-stargazer**
Addresses #6408 

Not tested.

### CODE REVIEW

**Comment by pllim** [comment]
The test failures are real, so your changes broke something else.

Also, the part of code that you are touching has not changed for 3 years according to `git blame`. It was added in #3011 by @taldcroft . What Astropy version were you using before when the inhomogeneous `dict` last worked?

**Comment by taldcroft** [comment]
@tomr-stargazer - I can confirm that the same behavior is present all the way back in astropy 0.4.  So I am a little confused that this ever worked for you.  You must have been doing something slightly different.

**Comment by taldcroft** [comment]
@tomr-stargazer - what would probably be a better direction on this would be to implement support for missing values.  I.e. if there are missing values in any rows then return an appropriate masked array instead of raising an exception.

**Comment by tomr-stargazer** [comment]
@taldcroft Ah - gotcha. I'll investigate this a little further when I have time, but will close the issue for now and just do a workaround on my end. Thanks for looking into it and I apologize for the trouble.

**Pull request closed without merging**
