### PR TITLE
Fixed typo in "units/decorators.py"

### PR DESCRIPTION
**Pull request by dklaes**
See also issue #3999 .

"astropy/units/decorators.py":
- Changed order of error message output.

### CODE REVIEW

**Comment by dklaes** [comment]
It looks like the tests failed because the 'correct solutions' for the tests imply the 'wrong' order. Before I continue here, I'd like to hear an opinion if I should contiue here.

**Comment by mdboom** [comment]
I'm certainly in favor of this change.  I think it's find to update the tests to match in this case.

**Comment by Cadair** [comment]
:+1:

**Comment by embray** [comment]
Congrats on issue #4000!

**Comment by pllim** [comment]
:scream:

**Comment by mhvk** [comment]
Looks all OK, so merging.

**Comment by mhvk** [comment]
@embray - while this PR passed all tests, it is failing the merge in master for python 2.6 with errors in `io.fits` -- my guess is because of problems with `--open-files` that are not related to this PR -- see https://travis-ci.org/astropy/astropy/jobs/73214105 (I restarted twice already, and it seems reproduceable).

**Pull request merged**
