### PR TITLE
[DO NOT MERGE] Test all with s390

### PR DESCRIPTION
**Pull request by mhvk**
Check whether we can do the `*tab.py` regeneration as part of the `s390` run, aiming to mimic Debian installation. Logically, eventually one would do this with `use_system_libraries`, but cannot do that yet since `erfa` needs updating (#9654)

EDIT: with `use_system_libraries`, one could remove some stuff but needs to add (see https://packages.debian.org/source/unstable/astropy)
```
# rm -rf cextern
libcfitsio-dev liberfa-dev libexpat1-dev wcslib-dev
# rm -rf astropy/extern (or rather replace with imports).
python3-configobj libjs-jquery-datatables libjs-mathjax python3-ply
# rm -rf astropy_helpers
python3-astropy-helpers
```
For docs, one would also need
```
python3-sphinx-astropy
```

### CODE REVIEW

**Comment by bsipocz** [comment]
I think this can safely closed now as the s390x test has been added a while ago now.

**Comment by mhvk** [comment]
It was not quite the same thing, but I agree, there's really not that much need to try to test everything on `s390`.

**Comment by bsipocz** [comment]
@mhvk - oh, I'm sorry then to close it. Please do reopen and resurrect the part we can still use from here.

**Comment by mhvk** [comment]
No, don't worry, I think this was overkill anyway...

**Pull request closed without merging**
