### PR TITLE
Add example of CCDData

### LINKED ISSUE #9043: Add example of reading a FITS image using `CCDData` to the FITS documentation
I do not think we currently mention `CCDData.read` in the documentation for `io.fits` even though there several advantages to opening images that way.

At a minimum inserting an example at https://astropy.readthedocs.io/en/stable/io/fits/index.html#working-with-image-data would be helpful, along with a brief explanation of when to use the lower-level `fits.io` and when to use `CCDData`.

### PR DESCRIPTION
**Pull request by TanviPooranmal**
### Description

This pull request closes #9043

 
CCDData is mentioned in the documentation with a brief explanation.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer who merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Thank you, but why use `.. topic` over the normal sub-heading?

**Comment by mtanvi19** [comment]
I have removed the ``..topic``. Thank you for pointing out (I am new to OSS :)).

**Comment by saimn** [comment]
Thanks for the PR. However this page is already quite long so I would prefer a more concise way, just mentioning what is CCDData with a sentence and referring to its documentation (with a link to https://docs.astropy.org/en/stable/nddata/index.html#reading-and-writing). Maybe within a `.. note::` block.

**Comment by TanviPooranmal** [comment]
@saimn Please check the updated PR.

**Comment by saimn** [comment]
@TanviPooranmal - a rebase is needed to fix most of the doc warnings, except one (fixing the reference to `CCDData`).

**Pull request merged**
