### PR TITLE
MAINT: remove duplicated calculation of number of points

### PR DESCRIPTION
**Pull request by mhvk**
This pull request is to remove a duplicated call I happened to notice.

### CODE REVIEW

**Review by neutrinoceros — APPROVED** [review]
looks like this crept in with #14341
Thanks !

**Comment by pllim** [comment]
Looks like a bug to me. We should backport. Good catch. Thanks! p.s. Introduced in https://github.com/astropy/astropy/pull/14341

@meeseeksdev backport to v7.0.x

**Comment by mhvk** [comment]
Sure, fine to backport! Though not really a bug, just a waste of time to calculate the same thing twice!

**Comment by pllim** [comment]
Performance bug. 😉

**Pull request merged**
