### PR TITLE
Some changes in convolve_fft docs

### LINKED ISSUE #8426: convolve_fft defaults and documentation
I've just been trying to run some code that I haven't used for a year or two, when I had an older version of astropy installed (I'm now running 2.0.10). It was giving very strange results and I eventually managed to track this done to convolve_fft. I found that if I change my `convolve_fft(image,psf)` to `convolve_fft(image,psf,nan_treatment='fill',normalize_kernel=False)` I could then reproduce the results I was getting previously. I take it the defaults were changed at some point, presumably related to #926. Can I suggest that it would make debugging old code much easier if changes that break backwards compatibility, such as this, are noted in the documentation? I'm thinking of something along the lines of http://docs.astropy.org/en/v2.0.x/io/fits/api/files.html#writeto where it clearly states 'Changed in version 1.3: overwrite replaces the deprecated clobber argument.'

The examples also need to be completely rewritten as they were clearly written using the old defaults. For instance, the second one `convolve_fft([1, np.nan, 3], [1, 1, 1])` now gives the result `array([0.5, 2. , 1.5])`.

### PR DESCRIPTION
**Pull request by himanshupathak21061998**
To FIX  #8426
I used astropy version -3.0.4 . Please suggest me if anything is wrong

### CODE REVIEW

**Comment by pllim** [comment]
1. Please read through the contributing guide first: http://www.astropy.org/contribute.html
2. Please make sure the changes you made are actually being tested on the CI.

**Comment by bsipocz** [comment]
> I used astropy version -3.0.4

for any development work, please use the developer version rather than a half year old one.

**Comment by himanshupathak21061998** [comment]
@bsipocz I tested it with astropy development version and got same results. So, no changes needed

**Comment by taldcroft** [comment]
From the original issue, doesn't this need to have the `__doctest_skip__` removed?  And why was that doc skip there in the first place?

**Comment by bsipocz** [comment]
@taldcroft - according to the comment back from 2013: "Disabling all doctests in this module until a better way of handling warnings in doctests can be determined".

**Comment by himanshupathak21061998** [comment]
@taldcroft as @bsipocz mentioned we need handle all warnings before removing 
`__doctest_skip__` Thats why

**Pull request closed without merging**
