### PR TITLE
Upgrade wcslib to 5.2

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by mdboom** [comment]
Fixes #3559.

**Comment by stargaser** [comment]
Wow, this is terrific news! @mdboom do you need help with testing?

**Comment by mdboom** [comment]
Sure.  Check it out and try it out on your data (particularly stuff with TPV).  Let me know how it goes.  It would be nice to add a TPV test here as well.

**Comment by stargaser** [comment]
@mdboom I've been in touch with Mark Calabretta and he explained what he's doing and what he's planning in the near future (header parser). He also sent me a link to the not-yet-public v5.2 for evaluation purposes -- I'd like to try some of his utility programs which are stripped out of the version in Astropy.

Do you expect this pull request will need to wait on a possible v5.3? How much time do I have for testing -- is there a target date for v1.1.0 of Astropy?

**Comment by mdboom** [comment]
This pull request will have to wait until at least a release that Mark hasn't declared as beta, so that it will work with wcslib's in the wild and in Debian packages etc.  So that's at least 5.3.  But it sounds like we're honing in that -- I didn't find any bugs in 5.2 that are revealed by astropy, so that's promising.

The current target date for astropy 1.1 is July 23, 2015 (and, of source, is only approximate).

**Comment by mdboom** [comment]
Closing -- this is not ready to merge.  wcslib now handles SIP, so we need to stop handling SIP ourself or it is essentially double-applied.

**Comment by embray** [comment]
D'oh!

**Comment by olebole** [comment]
@mdboom in the astropy 1.1 release notes, could you mention the maximal wcslib version that can be used (probably 5.3.1, right)? For Debian, I will not upload wcslib >= 5.4 to unstable until it is supported by astropy.
Does astropy-1.0 play nicely with the wcslib >=5, <= 5.3.1?

**Comment by mdboom** [comment]
@olebole: I have included information about supported versions in #3751 (not yet applied).  The supported versions are 4.24 to 5.3.1.  A warning is raised if a FITS file with SIP keywords is loaded and astropy is linked against wcslib 5.4.  If I can implement proper wcslib 5.4 support before astropy 1.1 I will do that, but in the meantime #3751 represents the easy things we can do for now.

**Pull request closed without merging**
