### PR TITLE
Updating uncertainty doc in Constants Class to add "absolute"

### LINKED ISSUE #10102: Unclear docs for uncertainty argument to Constant
`astropy.constants.Constant` has an `uncertainty` parameter, which is documented as

> The known uncertainty in this constant’s value.

It isn't clear whether this is a relative or absolute uncertainty however; this should be clarified in the docs.

### PR DESCRIPTION
**Pull request by cosmicoder**
### Description

This pull request is to address issue #10102 to add the keyword "absolute" to the description of the type of uncertainty in the docs as a clarification.

Fixes #10102

### CODE REVIEW

**Comment by cosmicoder** [comment]
Will this require a Changelog entry? If so how can I do that?

**Comment by pllim** [comment]
Thanks! No change log needed.

cc @dstansby

**Comment by cosmicoder** [comment]
Who will be reviewing this for a final merge?

**Comment by pllim** [comment]
@cosmicoder , preferably an approval from `constants` and/or `units` maintainers, whom had been tagged to review. I don't see any problem with the PR but extra pairs of eyes never hurt. Thanks for your patience.

**Review by stargaser — APPROVED** [review]
Looks good to me. Sorry I missed the original request for review.

**Review by dstansby — APPROVED** [review]

**Pull request merged**
