### PR TITLE
Remove arguments for super (trivial cases)

### PR DESCRIPTION
**Pull request by MSeifert04**
This removes the arguments for `super` for the trivial cases (first argument the class and the second argument the argument to be bound). 

There are still dozens of places where removing the arguments could change the behavior. I didn't want to touch those, most looked like copy&paste mistakes but some seemed genuine. Probably better to do that later on a per-subpackage basis.

### CODE REVIEW

**Comment by mhvk** [comment]
Looks good to me too. Thanks for the cleanup!

**Comment by MSeifert04** [comment]
can this be merged?

**Comment by bsipocz** [comment]
While it looks good, I'm running through the diff one more time, and then will hit the button.

**Comment by bsipocz** [comment]
Thanks @MSeifert04 for this cleanup!

**Pull request merged**
