### PR TITLE
Accepting mask when creating new column from a list of masked arrays

### LINKED ISSUE #8977: Mask discarded when creating new column from a list of masked arrays
Populating a new column in a masked table using a list of masked arrays results in the mask being discarded:

```pycon
>>> from astropy.table import Table
>>> import numpy as np
>>> t = Table([{'a': np.arange(3)} for _ in range(10)], masked=True)
>>> t['b'] = [np.ma.masked_all(3) for _ in range(10)]
>>> t
<Table masked=True length=10>
a [3]                     b [3]                   
int64                    float64                  
------ -------------------------------------------
0 .. 2                               0.0 .. 1e-323
0 .. 2                               0.0 .. 1e-323
0 .. 2                               0.0 .. 1e-323
0 .. 2                               0.0 .. 1e-323
0 .. 2                               0.0 .. 1e-323
0 .. 2                               0.0 .. 1e-323
0 .. 2                               0.0 .. 1e-323
0 .. 2            3.105036184601418e+231 .. 1e-323
0 .. 2 3.105036184601418e+231 .. 2.2363587243e-314
0 .. 2  3.105036184601418e+231 .. 2.144207845e-314
```

On the other hand, if we cast the list to a masked array, the list is preserved:

```pycon
>>> t = Table([{'a': np.arange(3)} for _ in range(10)], masked=True)
>>> t['b'] = np.ma.asarray([np.ma.masked_all(3) for _ in range(10)])
>>> t
<Table masked=True length=10>
a [3]   b [3]  
int64  float64 
------ --------
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
```

The mask should be preserved in both cases.

### PR DESCRIPTION
**Pull request by himanshupathak21061998**
Try to Solve: #8977 
Now  MaskedColumn can be created using a list of maksed_array.

```
In [3]: t['b'] =[np.ma.masked_all(3) for _ in range(10)]

In [4]: t
Out[4]: 
<Table masked=True length=10>
a [3]   b [3]  
int64  float64 
------ --------
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
0 .. 2 -- .. --
```

EDIT: Fix #8977

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! I milestoned this to 4.0 since the issue itself was milestoned so. I'll let @taldcroft review this and decide if a change log is necessary.

cc @lpsinger

**Comment by himanshupathak21061998** [comment]
I think, 4.0 is right. Maybe changelog update is not required for this one. you're welcome @pllim

**Comment by taldcroft** [comment]
@himanshupathak21061998 - thanks for taking a crack at this.  Your solution addresses the problem in #8977, but I realized that it goes deeper because initializing a table from the list of masked arrays is also failing.  I had to do a more core change in #9048 to fix both problems at once.  I would have made suggestions to you but I really had no idea how to do this without doing it because the changes are slightly subtle.

**Comment by himanshupathak21061998** [comment]
Yes, #9048 is a better solution for this. I closed this PR.

**Pull request closed without merging**
