### PR TITLE
Added a mirror for the astropy data repository

### PR DESCRIPTION
**Pull request by astrofrog**
In view of the STScI server being down this weekend, this seems like a good time to add a config item for a mirror for data.astropy.org :) While doing this, I realized that in the remote-data plugin, I need to actually read the URLs from the astropy.utils.data config not hard-code URLs....

### CODE REVIEW

**Comment by astrofrog** [comment]
I'll finish this up tomorrow morning. I need to figure out whether the dataurl config item can be changed to a list at this point (or if config items even support list inputs)

**Comment by eteq** [comment]
@astrofrog - if you look at `vo/validator/__init__.p y` you'll see an example of a list config item (for the same purpose, actually!)

Also, I'm realizing a downside of this: the caching machinery will double-cache these files because they have different URLs :( I don't think there's an easy fix for that, although a long-term solution might be too add a `mirror` option to the caching stuff. (It would treat the main URL as the cache name, but the mirror as the download location if not cached)

**Comment by bsipocz** [comment]
@astrofrog - Would be nice to have this in the next release. Could you rebase to get the changelog moved to 2.0?

**Comment by pllim** [comment]
@bsipocz , I moved the change log for as requested.

@eteq , as for making the config item from a string to a list, it would require some aliasing and deprecation warning, which is more work. I think we can re-consider that if we have more than one mirrors. Otherwise, this looks sufficient for now (despite some code duplication).

**Comment by bsipocz** [comment]
Thanks @pllim!

**Pull request merged**
