### PR TITLE
Update cfitsio to 4.2.0

### LINKED ISSUE #14015: Upstream release of dependency: cfitsio
Cross-posting from https://github.com/spacetelescope/hstcal/issues/576

This is a message from an automated system that monitors `cfitsio` releases.

Version 4.2.0 - Nov 2022
  
  - This release includes patches to security vulnerabilities.  We
    strongly encourage this upgrade, particularly for those running 
    CFITSIO in web accessible applications.
    
  - Fix to fits_read_key function, which was failing to properly read
    keywords declared type TUINT on compilers where sizeof(int) =
    sizeof(long).

  - Added new functions fits_read_cols and fits_write_cols to efficiently 
    read or write multiple columns in a single function call

  - Added new function fits_copy_selrows to copy only selected rows, such
    as the selected rows returned by fits_find_rows

  - Added new calculator functions ERF(X), ERFC(X) and GAMMA(X), which are
    mathematical special functions of the same name

  - Added new calculator function GTIFIND() which reports which GTI row
    brackets a given time sample

  - Added new calculator functions which operate upon vector table
    values NAXIS(V), NAXES(V,n), ELEMENTNUM(V) and AXISELEM(V,n),
    and ARRAY(X,d) which promotes scalar X to a vector or array
    with given dimensions.

  - The CFITSIO histogramming code now handles binning by any
    arbitrary calculator expression rather than just a column name.
    Both the binned columns as well as the optional weights may be
    calculator expressions, enclosed in parentheses.  

  - Binning of vector columns or expressions is now supported, as long
    as all binned inputs (as well as the optional weighting) have the
    same vector dimensions.  Binning of variable-length columns remains
    unsupported.

  - A bug that caused histogram weights from columns that are null values
    to be tallied along with non-null values has been fixed.

  - The CFITSIO calculator and histogramming functionality is now
    fully reentrant and does not require multithreading interlocks.

  - A long-standing segmentation fault bug in the histogramming code
    related to binning any value using the "reciprocal" /XXXX notation
    has been fixed.
    
  - Added mutex locks for thread safety in ftgiou and ftfiou.
  
  - Added several Fortran wrappers to support image read/write when
    'fpixel' and 'nelements' are 8-byte integers.
    
  - Fixed bug which was adding spaces to some cases of long string key
    value output.

(For complete changelog information, consult the package changelog file in cfitsio/doc/changes.txt)

  **NOTE: This release introduces a SONAME change from 9 to 10.**

### PR DESCRIPTION
**Pull request by saimn**
Also, update the bundled zlib to 1.2.13

Fix #14015

### Description

This pull request is to address ...

Fixes #<Issue Number>

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Don't want this for 5.2?

**Comment by saimn** [comment]
> Don't want this for 5.2?

Yeah probably better to backport, but I don't want to block the release.

So it seems  `FF_NO_UNISTD_H` has been replaced with  `YY_NO_UNISTD_H` ... should be fixed now.

But we have another problem now:
```
Traceback:
../astropy/astropy/test-sdist/lib/python3.11/site-packages/astropy/convolution/convolve.py:28: in <module>
    _convolve = load_library("_convolve", LIBRARY_PATH)
../astropy/astropy/test-sdist/lib/python3.11/site-packages/numpy/ctypeslib.py:137: in load_library
    from numpy.distutils.misc_util import get_shared_lib_extension
../astropy/astropy/test-sdist/lib/python3.11/site-packages/numpy/distutils/__init__.py:26: in <module>
    from . import ccompiler
../astropy/astropy/test-sdist/lib/python3.11/site-packages/numpy/distutils/ccompiler.py:20: in <module>
    from numpy.distutils import log
../astropy/astropy/test-sdist/lib/python3.11/site-packages/numpy/distutils/log.py:4: in <module>
    from distutils.log import Log as old_Log
E   ImportError: cannot import name 'Log' from 'distutils.log' (/home/runner/work/astropy/astropy/test-sdist/lib/python3.11/site-packages/setuptools/_distutils/log.py)
```

I think due to setuptools v65.6.0, released 2 days ago with https://github.com/pypa/distutils/pull/183.
For now I guess we can pin setuptools, but with the removal of distutils in Python 3.12 it's time to find a way to replace our use of `numpy.distutils`.

**Comment by saimn** [comment]
Also ref https://github.com/numpy/numpy/issues/22623

**Comment by Cadair** [comment]
> it's time to find a way to replace our use of numpy.ctypeslib

Out of interest are we using this for anything other than cfitsio?

**Comment by saimn** [comment]
It concerns only `convolution`, not `io.fits`. I should have opened a dedicated issue but it was late ;). See  #14025

**Comment by pllim** [comment]
I am not sure if we can release anyway until we have a fix for https://github.com/astropy/astropy/issues/14025 ?

**Comment by saimn** [comment]
Rebased on main, tests are passing except one new issue with numpy-dev.

**Comment by pllim** [comment]
Has this been addressed elsewhere? Looks like it is `io.ascii` overflow thingy again, @taldcroft / @hamogu / @dhomeier .

`AttributeError: module 'numpy' has no attribute 'str'`

**Comment by pllim** [comment]
Do we dare to backport to v5.0.x?

I am going to throw in the cron jobs too, just in case.

**Comment by astrofrog** [comment]
Looks like this is ready to go and the CI failures are unrelated. I will go ahead and merge this and include in 5.2, but don't think we should backport to LTS?

**Review by astrofrog — APPROVED** [review]

**Comment by hamogu** [comment]
They are not very specific about what has changed, but the following note form the release notes indicates that this might be a candidate for backporting, if it can be done with a reasonable level of effort:

> This release includes patches to security vulnerabilities. We
> strongly encourage this upgrade, particularly for those running
> CFITSIO in web accessible applications.

While I don't have a concrete example, it's not inconceivable that a web application that uses astropy might rely on an LTS release. Our LTS policy calls out "critical" security issues as something that we will backport (https://docs.astropy.org/en/stable/lts_policy.html). cfitsio does not use the word "critical" in their description, but "strongly encourage" sounds pretty close to "critical" to me. I'm not experienced enough in the classification system of security vulnerabilities to know the exact definition of "critical", but if this backports cleanly, it might be easier to just do that backport then to decide if the backport is absolutely needed.

Of course, it's easy to say that for me, since I'm not the person doing the backporting...

**Comment by pllim** [comment]
@meeseeksdev backport to v5.0.x

**Comment by pllim** [comment]
Huh, what do you know... auto backport works.

**Pull request merged**
