### PR TITLE
Change orientation to match ds9

### LINKED ISSUE #5611: Flip output of make_rgb_lupton by default
At the moment, when using the ``filename`` option of ``make_rgb_lupton``, the PNG/JPEG output files are flipped the wrong way vertically (@cdeil and @parejkoj started discussing this in https://github.com/astropy/astropy/pull/5535#issuecomment-267145197). FITS files are stored with the bottom-left origin pixels first, and other formats typically put the top right origin first. At the moment, if I open PNG/JPEG output in any viewer, the output is flipped compared to the original FITS files in any FITS viewer.

We should fix the default before 1.3 IMO.

### PR DESCRIPTION
**Pull request by parejkoj**
This should fix #5611

### CODE REVIEW

**Comment by parejkoj** [comment]
circleCI failed with a docker pull problem?

**Comment by astrofrog** [comment]
The docker issue must be transient - think we just have to wait it out (well, we shouldn't wait for it for PRs that are otherwise ready)

**Comment by parejkoj** [comment]
@cdeil originally reported this: this branch works for me for both jpeg and png, but he said png didn't work for him when he tried it?

**Comment by eteq** [comment]
I'm also seeing the same orientation for png and jpeg... perhaps this is a matplotlib quirk?  I'm going to go ahead and merge this as it's definitely better, but @cdeil, if you continue to see this maybe open a separate issue?

**Comment by eteq** [comment]
backported to v1.3.x in c09a9254a8f0082666ca1d3a12ffd82d8ec30975

**Comment by cdeil** [comment]
Just to follow up on an earlier comment I made when I reported this issue.

For me, the `origin="lower"` option to MPL imsave doesn't work with MPL 2.0.0rc2.
I've filed an issue in their tracker here: https://github.com/matplotlib/matplotlib/issues/7656

**Pull request merged**
