### PR TITLE
Unlinking fits2bitmap in changelog (as it caused docs build failure)

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by mhvk** [comment]
See duplicate in #4519 - either one will do!

**Comment by bsipocz** [comment]
There are some more warnings, but #4515 should fix those.

**Comment by eteq** [comment]
Looks good and straightforward, so I'm merging.  Thanks to both @bsipocz and @saimn - we're all winners here ;)

**Comment by eteq** [comment]
backported to v1.1.x in bf523cd557c90c14225c6cd67a07931c1c8c8efe

**Comment by embray** [comment]
Related to this, I just noticed that in http://docs.astropy.org/en/stable/development/workflow/development_workflow.html#add-a-changelog-entry the example of how to write a changelog entry uses single-backticks, when it should use double (and maybe should explicitly say to always use double for the changelog).

I had hoped one day to fix that as a special case for changelog rendering, but I haven't gotten around to it.  Pretty low priority.

**Pull request merged**
