### PR TITLE
Add support for "complex" bounding boxes.

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

Often one ends of with models for images with many slices have a dependency on that slice. These models can be extremely complex, being comprised of ~100 models, which are nearly identical for all slices, but have different bounding boxes for each slice. The bounding box calculations for each slice can become expensive if there is a need to run the model multiple times. For this reason, it is useful to be able to bind a "complex" bounding box to the model, which can select the "correct" bounding box based on a slice argument.

In this pull request, I introduce a `ComplexBoundingBox` which essentially is a dictionary of bounding boxes with keys given by the slice values. Then `Model` and `CompoundModel` were modified so that they can use this complex bounding box when the need arises. Moreover, the interface `bind_complex_bounding_box` was added to facilitate the easy creation and adding of a complex bounding box to any existing model.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Tagging @nden and @perrygreenfield for comment.

**Comment by pllim** [comment]
Is this fully backward compatible. Will this break people's custom models downstream?

**Comment by WilliamJamieson** [comment]
> Is this fully backward compatible. Will this break people's custom models downstream?

@plim I do not think this would break people's custom models. It seems to pass all the jwst and gwcs tests in addition to the astropy tests.

**Comment by nden** [comment]
Superseded by #11942

**Pull request closed without merging**
