### PR TITLE
Update bundled WCSLIB to v7.3

### PR DESCRIPTION
**Pull request by mcara**
This PR updates bundled WCSLIB to version 7.3. This update partially fixes https://github.com/astropy/astropy/issues/10397 but the

> WARNING: FITSFixedWarning: 'datfix' made the change ...

is still there on the second pass. With a small workaround (a separate PR) this warning could be quieted.

CC: @nden @astrofrog

### CODE REVIEW

**Comment by nden** [comment]
The failure in nddata is caused by turning the benign warning into an exception. The PR catching the warning should precede this one.

**Comment by nden** [comment]
@pllim wcslib 7.2 was included in 4.0.2 and I think this needs to go there too since there are no new features, only bug fixes.

**Comment by mcara** [comment]
The other PR that fixes the `datfix` warning for `DATEREF` is https://github.com/astropy/astropy/pull/10440

**Comment by mcara** [comment]
The other PR that fixes the `datfix` warning for `DATEREF` is https://github.com/astropy/astropy/pull/10440

Together with current PR, these two fix #10397

**Comment by nden** [comment]
Note: This will need to be included in 4.1.

**Pull request merged**
