### PR TITLE
Fix parametrization of test_asymmetric_kernel()

### PR DESCRIPTION
**Pull request by jamienoss**
Introduced in #6267

Signed-off-by: James Noss <jnoss@stsci.edu>

### CODE REVIEW

**Comment by keflavich** [comment]
This was introduced in #6267.

I think this is the wrong fix.  The correct thing to do is replace `convolve` with `convfunc` on line
https://github.com/jamienoss/astropy/blob/c00a7cfc78d0e35bfacbfd2cf730799a359cfa3e/astropy/convolution/tests/test_convolve.py#L779

The failure to do that in #6267 was an oversight that could hypothetically mean we are missing some important edge cases (though we think that `convolve_fft` was never affected by asymmetric kernel issues)

**Comment by jamienoss** [comment]
@keflavich 

> This was introduced in #6267.

Yep, sorry, I didn't pay proper attention to the summary.

>I think this is the wrong fix. The correct thing to do is replace convolve with convfunc on line
https://github.com/jamienoss/astropy/blob/c00a7cfc78d0e35bfacbfd2cf730799a359cfa3e/astropy/convolution/tests/test_convolve.py#L779

This is what I originally did and then changed it to as is when I looked at the original PR. The rationale being the context of the original PR in that no changes to ``convolve_fft()`` were made at all, not one. Introducing this FFT test within your original PR is effectively code smuggling, leaving the more contextual correct change to remove the test of ``convolve_fft()`` from ``test_convolve.py``.

However, by making my change I have reduced the test coverage as this test doesn't exist in ``test_convolve_fft.py``. I think the better option is to add it there. In fact, I'm working on removing this crossover altogether ([in this branch](https://github.com/astropy/astropy/compare/master...jamienoss:remove_fft_test_from_test_convolve.py)) and I was just about to close this PR and open a new one that contained both along with a 3rd (that I'm just about to write) that dedupes the tests between the two by having the test classes in ``test_convolve_fft.py`` inherit those from ``test_convolve.py`` and just add any on-overlapping.

**Comment by jamienoss** [comment]
Closing and moving to... (will update when opened).

**Comment by keflavich** [comment]
I didn't follow all that.  Indeed, in #6267, there were no changes to `convolve_fft`, and none were intended.  We wanted to increase the coverage by testing *both* `convolve`, which had a bug, and `convolve_fft`, which didn't, using asymmetric kernels. 

'code smuggling' is a new term for me; what does it mean?  (I definitely want to use it as it sounds awesome...).  

From your last paragraph - which I'm not sure I got fully - I get the impression that maybe the problem you're noting is that there are tests of both `convolve` and `convolve_fft` within `test_convolve.py`, even though it appears that `test_convolve.py` and `test_convolve_fft.py` are distinct codes?  I guess you're right, it makes more sense to have these be completely separated so that you can easily see, when running py.test, which function is actually failing.  Is that what you meant?  If so, I support the changes.

**Comment by jamienoss** [comment]
@keflavich 

>From your last paragraph - which I'm not sure I got fully - I get the impression that maybe the problem you're noting is that there are tests of both convolve and convolve_fft within test_convolve.py, even though it appears that test_convolve.py and test_convolve_fft.py are distinct codes? I guess you're right, it makes more sense to have these be completely separated so that you can easily see, when running py.test, which function is actually failing. Is that what you meant? If so, I support the changes.

Bingo!

> 'code smuggling' is a new term for me; what does it mean? (I definitely want to use it as it sounds awesome...).

I know, it's awesome, right.
"Code Smuggling" is where you introduced code that is not contextually encapsulated by the semantics of a given PR. It can make bug hunting more difficult as the git logs/history are poluted by the smuggled code. Say the smuggled code was actually in ``convolve_fft()`` itself, and turns out to be a regression, but the PR is all about ``convolve()``. I find out that I have a bug in ``convolve_fft()`` but am not sure where, I could  start by looking/searching the git log for any merged PRs relevant to the FFT version, I will not find any as the regression was actualy smuggled.

**Comment by keflavich** [comment]
Thanks for the clarification.  It turns out I'm a prolific code smuggler, but mostly out of laziness.  I generally try to avoid that in astropy, though.

Anyway, I'll review (will update when opened) when it is opened.

**Comment by jamienoss** [comment]
@adamginsburg Hey, I decided to reopen this. I have quite a lot of open & unmerged PRs and didn't want this to get lost and forgotten about with other refactorings. Think it's best to deal with individually.

**Comment by jamienoss** [comment]
@keflavich good to merge?

**Comment by jamienoss** [comment]
@keflavich cheers.

**Pull request merged**
