### PR TITLE
Use a single mmap per file

### PR DESCRIPTION
**Pull request by embray**
We've had some users running into trouble when accessing all HDUs of several different files simultaneously (on systems with strangely low file access limits), such that they hit their OS-allowed limit for open file handles in a process.

I've been wanting to address this issue for a long time as part of a more comprehensive overhaul of I/O handling in the `io.fits` module, which would also include caching of file objects and FITS headers.  

But the file handle thing in particular has really gotten to be a problem for some users, and I think I can improve that significantly by caching a single mmap instance (probably attached to the `_File` object) which HDUs can use to access their data, rather than creating one mmap per HDU.

So this will at least reduce the file handle usage proportional to the average number of HDUs per simultaneously-read file.

### CODE REVIEW

**Comment by embray** [comment]
The attached fixes should take care of this.  I'm a little nervous about the `sys.getrefcount()` shenanigans, but I think the approach is a conservative one--the mmap is only automatically closed if I can be really really sure it's only referenced from a few places.  If it might still be referenced from somewhere else, it stays open.

This actually sort of takes case of the use case for #3962 implicitly, without adding any new options or anything else that a user must perform manually.  It turns out it was actually [already the case](https://github.com/astropy/astropy/blob/master/astropy/io/fits/hdu/base.py#L773) that I was deleting `hdu.data` attributes that may hold onto a mmap reference when closing an HDUList, and that any further attempt to access `hdu.data` after the file is closed would result in an I/O error.  This PR preserves that behavior (while still allowing HDUs to share a single mmap).

What was not the case previously, and which the HDU does not attempt to fix, is that if the user already created a separate reference to the array, like `my_data = hdu.data`, then the mmap would not be closed because there is still a reference the data array as the `my_data` variable, and it holds on to the open mmap reference.  It turns out we absolutely do *not* want to force that mmap closed, as #3962 seems to suggest, because any further attempt to use the data in that array will result in a segfault (that should be handled better from Numpy's end though...)

So this PR just makes sure that all HDUs can share a single mmap of the file, and that that mmap is closed when the file is closed, so long as there are no references to it still hanging around after the file is closed.

**Comment by embray** [comment]
For the reasons explained above, once this passes and is merged I would suggest closing #3962, since it turns out closing a mmap is a bad idea if it's used as the buffer for any numpy arrays.

**Comment by embray** [comment]
One test failed on Numpy 1.6.  I'm rerunning it but it could be a legitimate fail.  Will see if I can reproduce as well.

**Comment by mdboom** [comment]
This makes me wonder: If closing the file discovers that there are still references around to the mmap -- could it register a weakref callback to close the mmap when all the references go away?  (Or does that happen automatically anyway -- i.e. the mmap's `__del__` (or the C equivalent) call close?)

**Comment by embray** [comment]
Yes, it already gets closed automatically in its `__del__`.  This is just making sure it also gets closed if its *only* reference is the one from the `_File` object.

**Comment by mdboom** [comment]
Got it.  That makes sense.

**Comment by embray** [comment]
It occurs to me now, this will still only improve file handle usage in code that opens each file only once with `fits.open`, as opposed to some code that's out there using functions like `fits.getdata` for each HDU, which will result in creating new `_File` instances in each case, and in turn new `mmap` objects for each HDU.

So I'll be curious to see how much this fix really improves the issue.

The larger fix that I've been wanting to make is to just use a single mmap for all HDUList instances that access the same file (at least when read-only), and to also cache the headers of files so they don't have to be re-read between read-only access.

**Pull request merged**
