### PR TITLE
Added converters for all new trigonometric models

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

Add asdf converter support for `Cosine1D`, `Tangent1D`, `ArcSine1D`, `ArcCosine1D`, and `ArcTangent1D` models.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] ~Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?~
- [ ] ~Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).~
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] ~Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?~
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] ~At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.~

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
The failure in the oldest supported version of all dependencies is because only the latest version of `asdf` includes the schemas needed to support these converters.

Are there any objections to bumping the oldest supported version of `asdf` from `2.9.2` to `2.10.0`?

**Comment by pllim** [comment]
> bumping the oldest supported version

Does this bump need to be backported? I guess if it is only because of this PR, it does not have to be backported?

**Comment by WilliamJamieson** [comment]
> > bumping the oldest supported version
> 
> Does this bump need to be backported? I guess if it is only because of this PR, it does not have to be backported?

This should not be back-ported.

**Comment by pllim** [comment]
> This should not be back-ported.

In that case, I have no objection from a bugfix backward compatibility standpoint. Thanks for the clarification!

**Review by eslavich — APPROVED** [review]
LGTM

**Pull request merged**
