### PR TITLE
Renamed ignored to suppress

### PR DESCRIPTION
**Pull request by pllim**
As suggested by @embray in [this comment](https://github.com/astropy/astropy/pull/4977#issuecomment-222103333), I replaced `ignored` context manager with `suppress` to be consistent with renaming in Python 3 itself (see https://bugs.python.org/issue19266).

### CODE REVIEW

**Comment by astrofrog** [comment]
@pllim - this needs rebasing. Also, this will break any imports by affiliated packages, so can you make sure you preserve backward-compatibility?

**Comment by pllim** [comment]
I thought about backward-compatibility but looks like Python didn't do that on their side, so I didn't either. I can add it here if you want.

**Comment by astrofrog** [comment]
@pllim - I would feel more comfortable having backward-compatibility at least for one version. Also, make sure you add a changelog entry.

**Comment by pllim** [comment]
@astrofrog , it already has a changelog entry (I wouldn't dare incur the wrath of astrobot). I added `ignored` back in. It now does this:

```python
In [3]: with ignored(OSError):
   ...:     os.remove('adadadas')
   ...:     
WARNING: AstropyDeprecationWarning: The ignored function is deprecated and may be removed in a future version.
        Use suppress instead. [astropy.utils.decorators]
```

**Comment by eteq** [comment]
Looks good to me now that it has the deprecation warning!

**Comment by pllim** [comment]
Yay, no complains from bot! :muscle:

**Pull request merged**
