### PR TITLE
Use double quotes in test command for wheel building/testing

### PR DESCRIPTION
**Pull request by astrofrog**
Possible alternative to https://github.com/astropy/astropy/pull/15125

Close #15125 

Pre-requisite for https://github.com/astropy/astropy/issues/15123

### CODE REVIEW

**Comment by pllim** [comment]
This just brings back the old bug that @dhomeier fixed because OpenAstronomy workflow is silently not running the tests. Look at https://github.com/astropy/astropy/actions/runs/5772457471/job/15647458437?pr=15133 carefully. No tests are run and that is why it is passing.

We cannot really do this until https://github.com/OpenAstronomy/github-actions-workflows/pull/144 is merged and deployed (assuming it works).

**Review by pllim — CHANGES_REQUESTED** [review]
Needs https://github.com/OpenAstronomy/github-actions-workflows/pull/144

**Comment by astrofrog** [comment]
Ah yes of course - I'm just adding a temporary commit to see if https://github.com/OpenAstronomy/github-actions-workflows/pull/144 does indeed fix things here.

**Comment by astrofrog** [comment]
@pllim - https://github.com/OpenAstronomy/github-actions-workflows/pull/144 seems to work, so I've now merged that PR and will tag a new version of the workflow tomorrow (if no objections), then I will update this PR.

**Comment by astrofrog** [comment]
@pllim - this is ready for review. Note that single quotes still don't work properly in test commands hence why this is necessary.

**Review by Cadair — APPROVED** [review]

**Comment by astrofrog** [comment]
@pllim this is using the 'new' v1

**Review by pllim — APPROVED** [review]
OK the tests are not a lie anymore. Thanks!

**Comment by astrofrog** [comment]
@MeeseeksDev backport to v5.0.x

**Comment by astrofrog** [comment]
@MeeseeksDev backport to v5.3.x

**Pull request merged**
