### PR TITLE
TST: fix a test for windows+numpy1

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
Follow up to #16766 and #16775

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Weird that our oldest deps job didn't fail in the other PR if it is a problem.

**Comment by pllim** [comment]
Oh wait... We don't run oldest deps on Windows. Never mind.

**Review by pllim — APPROVED** [review]
Thanks!

**Comment by pllim** [comment]
I can merge when you think it is ready to be taken out of draft.

**Comment by saimn** [comment]
> Oh wait... We don't run oldest deps on Windows. Never mind.

Ah good point, I was wondering the same thing.

**Pull request merged**
