### PR TITLE
Removed OrderedDict from tests

### PR DESCRIPTION
**Pull request by marcellonascif**
### Description

This pull request removes OrderedDict from file "runner" in tests.
The OrderedDict is normal dictionary now.

Fixes part of #10888

### CODE REVIEW

**Review by pllim — APPROVED** [review]
I think this is uncontroversial. Thanks!

**Comment by marcellonascif** [comment]
thank you @pllim for merging this! ❤️

**Comment by pllim** [comment]
Thank YOU for contributing! 😸

**Comment by marcellonascif** [comment]
@pllim I think that pinning this PR on the initial comment of the issue would be a good idea. Is it right?

**Comment by pllim** [comment]
Yes, thanks for the reminder!

**Pull request merged**
