### PR TITLE
Reduce excess units/dimensions in Lorentz1D, Voigt1D

### PR DESCRIPTION
**Pull request by dhomeier**
### Description

This pull request is to port the fix for non-cancelling equivalent, but different, units on calling some `physical_models` with different parameter units as described in https://github.com/astropy/astropy/pull/11123#issuecomment-802150538 .
That would cause failures with older numpy versions in one case, but still can result in odd return data having units like `<Quantity 1.98019802 Angstrom2 Jy / nm2>` in the remaining cases.

This is moving @embray's fix for the LTS from the built-in complex error function to its wrapper. The main point in favour of this option is probably that it will also reduce the input `z` when using the alternative `scipy.special.wofz` method.

Extended one test in `test_models_evaluate_with_units` to check the dimensionally of the returned units and ensure no "excess", mutually cancelling units are added.

### CODE REVIEW

**Comment by dhomeier** [comment]
> Looks like there are some new code not covered by test.
> 
That was actually what the modified `test_models_evaluate_with_units` is intended to test. Otherwise I have no idea how codecov thinks an internal variable like `s` should be tested...

> Also, is this a follow up of a specific PR?

As mentioned in the description, #11123 insofar as it brings the back port forward again to the 4.3 branch, so to speak (and will cover possible failures when using `Voigt1D(method='scipy')`) – otherwise it is probably primarily of "cosmetic" relevance to 4.3.

**Comment by pllim** [comment]
@dhomeier , is it fair to say that this is a direct follow-up of #11177 , which is milestoned to 4.0.5 (and as you pointed out, already backported to 4.0.x)? If so, does that mean this needs to go into 4.2.1 too?

**Comment by dhomeier** [comment]
> @dhomeier , is it fair to say that this is a direct follow-up of #11177 , 

Not strictly, since the excess units also pop up with the old approximation; however they only produce numerically wrong result when using the new `_hum2zpf16c` with legacy numpy versions, therefore this was already fixed in 41614dc.

> which is milestoned to 4.0.5 (and as you pointed out, already backported to 4.0.x)? If so, does that mean this needs to go into 4.2.1 too?

Technically this was intended as a "forward-port" of 41614dc to 4.2.1 only; the scipy case seems to work correctly with quantities, although I have not tested with anything older than scipy 1.1.0, so it remains mostly a cosmetic issue.
Although, if resulting quantities are in turn passed to an old numpy version they might trigger the same errors, so it should be safer to have this in 4.0.5 as well.

**Comment by dhomeier** [comment]
I have changed the test to an exact unit match now; I think `Linear1D`, `PowerLaw1D` and `ExponentialCutoffPowerLaw1D`, which did not pass this originally, were simply using a different unit in `'evaluation'` for convenience.
Generally it seems reasonable for a model that has an `amplitude`-type parameter (`intercept` in the case of `Linear1D`) to expect the return values to be in the same unit, and all the models tested here follow that convention.

**Comment by pllim** [comment]
I tentatively changed the milestone to 4.2.1 but @eteq is free to move it as needed.

**Comment by dhomeier** [comment]
Added a second instance of the `Voigt1D` tests using the scipy implementation, also testing a more critical parameter domain (close to where the McLean approximation turns negative).

**Comment by dhomeier** [comment]
So `test_scipy_registered` depends on `scipy.special` functions having never been called on a quantity before?
That's relatively easily worked around here, since we only need the scalar value, but still looks like an extremely precarious test setup (also, the test will always fail when called a second time...)!

**Comment by dhomeier** [comment]
@nden @perrygreenfield @embray – I've rebased to get rid of a readthedocs failure.

**Pull request closed without merging**
