### PR TITLE
fix earth location info

### LINKED ISSUE #10591: IndexError when accessing EarthLocation.info
### Description

EarthLocation info display is broken on current master

### Expected behavior

display the site info

### Steps to Reproduce

```python
from astropy.coordinates import EarthLocation

keck = EarthLocation.of_site('Keck Observatory')
keck.info
```
Produces the following exception
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hannes/work/repos/astropy/astropy/utils/data_info.py", line 488, in __repr__
    self.__call__(out=out)
  File "/home/hannes/work/repos/astropy/astropy/utils/data_info.py", line 472, in __call__
    info['length'] = len(dat)
  File "/home/hannes/work/repos/astropy/astropy/coordinates/earth.py", line 799, in __len__
    raise IndexError('0-d EarthLocation arrays cannot be indexed')
IndexError: 0-d EarthLocation arrays cannot be indexed
```

### System Details

```
>>> import platform; print(platform.platform())
Linux-4.15.0-111-generic-x86_64-with-Ubuntu-18.04-bionic
>>> import sys; print("Python", sys.version)
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.20.0.dev0+2ccfd79
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.2.dev434+gd1e34fb0c
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.5.1
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.2.1.post2723+g89fa0e43b
```

### PR DESCRIPTION
**Pull request by astromancer**
### Description

Fixes #10591 

```python
from astropy.coordinates import EarthLocation

keck = EarthLocation.of_site('Keck Observatory')
keck.info
```

Now produces the site info
```
name = W. M. Keck Observatory
dtype = void192
unit = m
class = EarthLocation
```

### CODE REVIEW

**Comment by mhvk** [comment]
Thanks, that's a nice simple fix! But could you add a test? (in `test_earth.py`). Also an entry in the changelog (under bug fixes in 4.0.2).

**Comment by mhvk** [comment]
@astromancer - This looks good but the failures are real: the test does need to be marked `@pytest.mark.remote_data(source="astropy")` since it accesses the internet, and you'd need to fix the pep8 errors.

While you do that, could you rebase and squash the commits?

Also, one suggestion (feel free to ignore): since this makes the `.info` quite nice, how about giving the output in the docstring of `of_site` (it already shows `.info.meta`, which is good too, so perhaps just before that)?

**Comment by astromancer** [comment]
OK. Re decorating the test: I thought that using the 'greenwich' example would not need internet access since 
```
    If a site cannot be found in the registry (i.e., an internet
    connection is not available), it will fall back on a built-in list,
    In the future, this bundled list might include a version-controlled
    list of canonical observatories extracted from the online version,
    but it currently only contains the Greenwich Royal Observatory as an
    example case.
```
from `EarthLocation.of_site` docs.

**Comment by mhvk** [comment]
@astromancer - yes, that makes sense, but it may be that it still tries to connect. cc @pllim who tried to make sure these things didn't happen (but I vaguely recall `of_site` was a particular problem).

**Comment by pllim** [comment]
I forgot what I did now but I think what you need is in #10304 ?

**Comment by mhvk** [comment]
@astromancer - if it is easy to get something to work following the above hint, do so, but if not, I think it is absolutely fine to just mark the test as `remote_data`.

**Comment by mhvk** [comment]
The code now looks all OK, but unfortunately the doctest fails:
```
346         >>> keck.info  # doctest: +REMOTE_DATA
Differences (unified diff with -expected +actual):
    @@ -3,2 +3,4 @@
     unit = m
     class = EarthLocation
    +n_bad = 0
    +<BLANKLINE>
```

See https://travis-ci.org/github/astropy/astropy/jobs/712153720 (the other failure is unrelated)

**Comment by astromancer** [comment]
@mhvk This looks all good now, do i still need to rebase?

**Comment by mhvk** [comment]
@astromancer - generally I like single commits, but I think we've been through enough here, and 2 is fine too! So, I'll merge. Thanks for sticking with it, adding all the extras to the super-small and good fix you started with!

**Pull request merged**
