### PR TITLE
Set max line length for PEP 8 check

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is mainly for my own sanity when I edit files in this repo. But I think it will benefit others as well who have set up their IDE to do on-the-fly PEP 8 check.

### CODE REVIEW

**Comment by bsipocz** [comment]
We decided on 100 on the coordination meeting, or in PR comments around that time, if I recall correctly.

**Comment by pllim** [comment]
Ops, did we? My bad. I'll update the number.

**Comment by bsipocz** [comment]
Yes, but I can't find any written docs about it, besides this one line, that certainly refers to the discussions we were having f2f: https://github.com/astropy/astropy/pull/9772#pullrequestreview-332096701

**Comment by bsipocz** [comment]
I'm OK with this, but let's have @saimn to say something as he is clearly not happy with the change.

**Comment by saimn** [comment]
120 seems a lot, that's half more than what I usually use ;), but I guess I can leave with 100.

**Comment by bsipocz** [comment]
OK, let's move forward then. You can certainly keep doing 80 long lines, but now we have more leverage to cut back the long, 120 long ones to something manageable.

**Comment by bsipocz** [comment]
thanks @pllim!

**Pull request merged**
