### PR TITLE
EXP: Pin pytest-openfiles in old deps job

### LINKED ISSUE #10160: TST: py36-test-oldestdeps failing with timeout exceeded
### Description

CI of `master` and PRs are blocked by failure in the `py36-test-oldestdeps` job in Travis CI. Due to the way stages are set, a bunch of tests are not run because of that.

The fact that it started happening on `master` after #10123 was merged might be a pure coincidence, as the CI was green on that PR before merge. I also see the same failures in completely unrelated PRs like #10152. 

If this is a problem upstream at Travis, hopefully it would fix itself soon. If not soon enough, maybe we should start considering seriously to move away from Travis sooner than later.

If this is a problem with our "old dependencies" setting, then it needs to be identified and updated.

https://github.com/astropy/astropy/blob/d91f4441ee45f406efa3a470fa092392b806190d/.travis.yml#L85-L94

https://github.com/astropy/astropy/blob/d91f4441ee45f406efa3a470fa092392b806190d/tox.ini#L63-L68

### Expected behavior

Tests to pass.

### Actual behavior

```
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
cachedir: .tox/py36-test-oldestdeps/.pytest_cache
Running tests with Astropy version 4.1.dev981+gd91f4441e.
Running tests in astropy docs.
Date: 2020-04-16T19:55:12
Platform: Linux-4.15.0-1028-gcp-x86_64-with-debian-stretch-sid
Executable: /home/travis/build/astropy/astropy/.tox/py36-test-oldestdeps/bin/python
Full Python Version: 
3.6.7 (default, Nov 28 2018, 13:38:24) 
[GCC 5.4.0 20160609]
encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15
Package versions: 
Numpy: 1.16.6
Scipy: 0.18.1
Matplotlib: 2.1.2
h5py: not available
Pandas: not available
Using Astropy options: remote_data: none.
rootdir: /home/travis/build/astropy/astropy, inifile: setup.cfg
plugins: cov-2.8.1, forked-1.1.3, hypothesis-5.9.1, arraydiff-0.3, filter-subpackage-0.1.1, remotedata-0.3.2, doctestplus-0.5.0, astropy-header-0.1.2, xdist-1.31.0, asdf-2.4.2, openfiles-0.5.0
collected 14784 items / 26 skipped / 14758 selected          
...
../../.tox/py36-test-oldestdeps/lib/python3.6/site-packages/astropy/units/tests/test_format.py . [ 73%]
.............................
The job exceeded the maximum time limit for jobs, and has been terminated.
```

Example log on `master` branch: https://travis-ci.org/github/astropy/astropy/jobs/675907677

Log of last good run: https://travis-ci.org/github/astropy/astropy/jobs/675455523

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address Travis CI failure related to old dependencies.

Fixes #10160

**Note to reviewer:** Please also check remote data job on Travis CI that is allowed to fail.

### CODE REVIEW

**Comment by pllim** [comment]
Aha, so it is `pytest-openfiles`! (Looking at you, @astrofrog ! 😉 )

I will do a force push and let the whole suit runs.

**Comment by bsipocz** [comment]
Maybe add a comment that we pin this as otherwise it's causing stalling not because it's a minimum requirement.

**Comment by astrofrog** [comment]
I'll investigate on Monday, but please feel free to merge this once ready!

**Comment by pllim** [comment]
Need an approval to merge.

**Comment by bsipocz** [comment]
sorry @pllim for the delay

**Comment by bsipocz** [comment]
I did this version limit manually on the LTS branch as we don't do tox there.

**Pull request merged**
