### PR TITLE
[Temp fix] Pin PyYAML<5.1 until we fix the tests

### PR DESCRIPTION
**Pull request by pllim**
Stop gap for #8498 so CI is green until we have a chance to update the tests themselves.

Since this is supposed to be temporary, I didn't assign any milestones, but feel free to add a milestone if you want.

### CODE REVIEW

**Comment by pllim** [comment]
Probably can ignore codecov's complain. Travis is green, except for a transient failure that is unrelated in dev, which is allowed to fail anyway.

**Comment by bsipocz** [comment]
Let's get this in then. I don't milestone for backport, hopefully a fix will be around before I need to release again.

**Comment by bsipocz** [comment]
Thanks @pllim!

**Comment by pllim** [comment]
I dug into the `table` code but it is not obvious to me exactly where to insert the incantation for backward compatible `pyyaml` behavior. And also, maybe we don't even want to do that, but to just update the tests? Maybe @taldcroft knows.

**Pull request merged**
