### PR TITLE
Fix direct convolution issue #6264

### PR DESCRIPTION
**Pull request by keflavich**
Direct convolution has been incorrectly implemented from day one.  Instead of implementing convolution,

   (F*G)(t) = Sum[f(x) * g(t-x)]

it implemented something backwards:

   (F*G)(t) = Sum[f(x) * g(x)]

We never noticed before because all of our tests used symmetric kernels, and
for symmetric kernels the above two equations are equivalent.

convolve_fft was never affected by this issue.

EDIT: link to #6264

### CODE REVIEW

**Comment by keflavich** [comment]
@mirca any chance you could add some more tests here?  Maybe add some tests like you were doing that `np.convolve` or `scipy.signal.convolve` match astropy for non-NaN cases?

**Comment by mirca** [comment]
@keflavich sure!

**Comment by mirca** [comment]
Travis is happy and looks like circle-ci errors are unrelated? =)

**Comment by bsipocz** [comment]
I'm sorry to say, but CircleCI failure looks related:

```

=================================== FAILURES ===================================
_______________________ test_convolution_consistency[3] ________________________

ndims = 3

    @pytest.mark.parametrize('ndims', (1,2,3))
    def test_convolution_consistency(ndims):
    
        np.random.seed(0)
        array = np.random.randn(*([3]*ndims))
        np.random.seed(0)
        kernel = np.random.rand(*([3]*ndims))
    
        conv_f = convolve_fft(array, kernel, boundary='fill')
        conv_d = convolve(array, kernel, boundary='fill')
    
>       assert_array_almost_equal_nulp(conv_f, conv_d, 10)
E       AssertionError: X and Y are not equal to 10 ULP (max is 25)

astropy/convolution/tests/test_convolve.py:733: AssertionError
=============================== warnings summary ===============================
```

**Comment by mirca** [comment]
=(

**Comment by astrofrog** [comment]
25 ULP is still pretty good - (CircleCI is 32-bit btw)

**Comment by astrofrog** [comment]
Btw this should be rebased later to remove the merge commits

**Comment by keflavich** [comment]
@astrofrog - could you do one more sanity-check review of the cython edits?

Increasing the nULP threshold solved the circle-ci problem.  This is ready to merge given approval by @astrofrog.

**Comment by bsipocz** [comment]
@keflavich - this will definitely need a changelog entry

**Pull request merged**
