### PR TITLE
TST: Fix Sphinx warning for test runner

### LINKED ISSUE #10473: TST: html-docs job failing on CircleCI
Not sure when it started but now I see something like this on `master` and also in my PR(s). RTD can build fine though but its log also shows similar warning.

```
Warning, treated as error:
 
autodoc: failed to import method '__call__' from module 'keyword'; the following exception was raised:
 
Traceback (most recent call last):
 
  File "/home/circleci/project/.tox/build_docs/lib/python3.7/site-packages/sphinx/util/inspect.py", line 323, in safe_getattr
 
    return getattr(obj, name, *defargs)
 
AttributeError: module 'keyword' has no attribute '__call__'
 

 
During handling of the above exception, another exception occurred:
 

 
Traceback (most recent call last):
 
  File "/home/circleci/project/.tox/build_docs/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 71, in import_object
 
    obj = attrgetter(obj, attrname)
 
  File "/home/circleci/project/.tox/build_docs/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 246, in get_attr
 
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
 
  File "/home/circleci/project/.tox/build_docs/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 2059, in autodoc_attrgetter
 
    return safe_getattr(obj, name, *defargs)
 
  File "/home/circleci/project/.tox/build_docs/lib/python3.7/site-packages/sphinx/util/inspect.py", line 339, in safe_getattr
 
    raise AttributeError(name)
 
AttributeError: __call__
```

Maybe some clue from RTD log:
```
/home/docs/checkouts/readthedocs.org/user_builds/astropy/checkouts/latest/docs/api/astropy.tests.runner.keyword.rst:14:<autosummary>:1: WARNING: py:obj reference target not found: astropy.tests.runner.keyword.__call__
```

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address Sphinx warning that started showing up when generating `automodapi` for `astropy.tests.runner`.

Fixes #10473

### CODE REVIEW

**Comment by pllim** [comment]
Maybe the correct fix is really to make `sphinx-automodapi` be compatible with Sphinx 3.1.0 but I don't have time to do that. This will have to do for now, so PRs CI don't get blocked.

**Comment by pllim** [comment]
The new rendering is "uglier" but at least CI is green now:

https://71027-2081289-gh.circle-artifacts.com/0/docs/_build/html/testhelpers.html

Compared to:

https://docs.astropy.org/en/v4.0.1/testhelpers.html

**Comment by pllim** [comment]
Thanks, @mhvk ! Follow-up issue is at #10478

**Comment by mhvk** [comment]
Thanks!

**Pull request merged**
