### PR TITLE
Compound model fitting example not too impressive 

### PR DESCRIPTION
**Pull request by embray**
In the intro to the modeling docs there is a new section introducing the compound model feature:

http://docs.astropy.org/en/latest/modeling/index.html#compound-models

It includes an example of fitting a compound model, but the plot of the fit does not demonstrate such a great fit. This is weird, because when I run that example locally (including when building the docs) the fit looks pretty great. So I'm not sure what the difference is here. It could have something to do with the SciPy  version, or possibly just the random seed used. In any case, it would be nice to try to figure out where it's going wrong and to tweak the example.

### CODE REVIEW

**Comment by embray** [comment]
@cdeil I made the same suggestion in c42121a; I think the best solution would actually be to set better initial guesses.  But for now I'm going with the solution I have--if someone else wants to provide something better later (where someone else could also be me, in the future) that's fine too.

**Comment by embray** [comment]
(Which is to say, I've spent too much time fussing with this as it is :)

**Comment by astrofrog** [comment]
Sounds good, I'm all for pragmatic solutions at this stage :+1:

**Comment by cdeil** [comment]
Agreed it's not worth spending time on this and having to debug it with old `numpy` and `scipy` versions.

Like @embray said the issue is that this fit example has bad starting parameters ... it puts both fits at `x=0` but one is located at `x=0.5`.

Here's the one-line change that would make the fit converge reliably ... put the second peak near it's true location `x=0.5`:
```python
gg_init = models.Gaussian1D(1, 0, 0.1) + models.Gaussian1D(2, 0.5, 0.1)
```

**Comment by embray** [comment]
@cdeil I'll go ahead and make that change.  Might as well promote good practice in fitting.

**Comment by astrofrog** [comment]
Thanks!

**Pull request merged**
