### PR TITLE
Fix SkyOffsetFrame wrap angle for data stored as non-spherical repres…

### PR DESCRIPTION
**Pull request by Jerry-Ma**
…entation.

### Description

It is observed that when a coordinate in SkyOffsetFrame is created with data of non-spherical data representation type (e.g., cartesian), the `lon` values does not wrap correctly around 180 degree.
 
This pull request is to address this issue by following the discussion and information in #7462.

### CODE REVIEW

**Comment by Jerry-Ma** [comment]
@mhvk 

Please let me know where to put the change log for this.

**Comment by pllim** [comment]
Since original issue is a bug, I have milestoned it to 4.0.2. Thanks!

**Comment by bsipocz** [comment]
Indeed, the failure is unrelated and has been worked around in master since.

 However, it would be nice to have a full green CI before merging, so could you please rebase @Jerry-Ma? Alternatively I'm happy to do it for this PR.

**Comment by Jerry-Ma** [comment]
@bsipocz  Just did it.

**Comment by mhvk** [comment]
Thanks! Merging...

**Pull request merged**
