### PR TITLE
Add coverage to minimal dependency test

### PR DESCRIPTION
**Pull request by nstarman**
Also add coverage report to minimal dependency test.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Thanks, I'll have a look next week but people who are more familiar with codecov are welcome to review too!

**Comment by dhomeier** [comment]
Same here!

**Comment by astrofrog** [comment]
Just to check, what is the motivation for this? Ideally we would measure coverage on all jobs but we don't for performance reasons as it adds a significant overhead. I'm curious what we gain by adding it to this job?

**Comment by pllim** [comment]
There was confusion when a test that only runs in a minimal dependency setting gets reported as not covered even though there is a test.

**Comment by dhomeier** [comment]
https://github.com/astropy/astropy/pull/12192#discussion_r715812239

**Comment by astrofrog** [comment]
Ok thanks for the background! Maybe a comment should be added in the CI config to explain this.

Is the addition of -clocale needed? If not, maybe just add -cov?

**Comment by nstarman** [comment]
I think the ``clocale`` can be removed, at least https://github.com/astropy/astropy/pull/12192#discussion_r715812239 does not require it.

**Comment by nstarman** [comment]
> Maybe a comment should be added in the CI config to explain this.

Done. Added a short note about running tests without scipy.

**Review by pllim — APPROVED** [review]
LGTM. Let's deploy and see what happens.

**Comment by dhomeier** [comment]
Does not look like the overhead is all that large – only a few minutes difference in testing times, at most.
I am a bit puzzled by the `py38-test-alldeps` job BTW, which is running with `--open-args`, but contrary to the comments does not seem to take any longer to run either.
By comparison, running `astropy.test(open_files=True)` locally takes over 1 hour compared to ~10 min without – or is that just another macOS thingy?

**Comment by pllim** [comment]
Wow, an hour! I am not sure... I don't think I ever tried to run `open_files=True` with the astropy test runner. I can try it on other OSes when I get the chance.

**Comment by pllim** [comment]
Yup, I see 1.5 hours on Linux. Must be the overhead of checking for dangling file pointers in the test runner. I don't see it being stuck on any one job. Not sure what we can do about that.

`17767 passed, 201 skipped, 66 xfailed in 5241.37s (1:27:21)`

**Pull request merged**
