### PR TITLE
MNT: Unpin numpy<2 in build requirements

### LINKED ISSUE #15493: TST: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core
DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.umath.

### PR DESCRIPTION
**Pull request by pllim**
Blocked by?

* https://github.com/liberfa/pyerfa/pull/121

Related:

* https://github.com/numpy/numpy/pull/24943
* #15506

### Description

This pull request is to unpin `numpy<2` from build requirements.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
pre-commit.ci autofix

**Comment by pllim** [comment]
I don't understand why it is still complaining about `numpy.core.multiarray`. I thought I replaced them all. That line does import a C-extension that I am not familiar with. @mhvk ?

```
.../astropy/time/formats.py:17: in <module>
    from . import _parse_times, conf, utils
E   ImportError: numpy.core.multiarray failed to import
```

**Comment by bsipocz** [comment]
Have you tried to a `git clean` first and then rebuilding astropy before running pytest?

**Comment by pllim** [comment]
I thought I did. But still, you can see the same error in the devdeps job here, just a different traceback. I cannot make sense of it.

**Comment by bsipocz** [comment]
I can't reproduce any of it locally as there seems to be a problem with the osx wheel and it's picking up a few days old version for me.

**Comment by pllim** [comment]
Well, it is not scipy...

```
astropy @ file:///.../astropy-6.0.dev869%2Bg554d5efea9.tar.gz#sha256=c7c858a0087b5b1e81d3a43b9b055645a538f04a895c94d4b8e1f1970ce3f8ae
astropy-iers-data==0.2023.10.16.0.30.26
attrs==23.1.0
coverage==7.3.2
execnet==2.0.2
hypothesis==6.88.1
iniconfig==2.0.0
numpy==2.0.0.dev0
packaging==23.2
pluggy==1.3.0
pyerfa @ git+https://github.com/liberfa/pyerfa.git@1903739c3e971938c4b4e0e4994d3e3f6039ba71
pytest==7.4.2
pytest-arraydiff==0.5.0
pytest-astropy==0.11.0
pytest-astropy-header==0.2.2
pytest-cov==4.1.0
pytest-doctestplus==1.0.0
pytest-filter-subpackage==0.1.2
pytest-mock==3.11.1
pytest-remotedata==0.4.1
pytest-xdist==3.3.1
PyYAML==6.0.1
setuptools==68.2.2
sortedcontainers==2.4.0
```

**Comment by ngoldbaum** [comment]
ping @mtsokol any idea what's going wrong here? It seems like `import_array()` is failing on import inside of astropy's C extensions.

**Comment by ngoldbaum** [comment]
I'm not able to reproduce this in a fresh clone of astropy, perhaps there's some build caching that's confusing things? Do the CI jobs do fresh clones or e.g. `git clean -fxd` between runs?

**Comment by mtsokol** [comment]
Thanks for ping - I will inspect it.

**Comment by mhvk** [comment]
Super quickly, `_parse_times` creates a gufunc, so links to the numpy library. What is strange though is that `stats/src/fast_sigma_clip` also creates a gufunc, so I'd have thought that would fail too... The corresponding `setup_package` look basically the same. Also, `wcs` only does `import_array()` (not also `import_ufunc()`), so that must be the problem. 
...
An old file somehow lingering around seems reasonabe...

**Comment by pllim** [comment]
I am not familiar with Actions internal but you would think it does a fresh install of the code under test every time... 🤔 

I was able to reproduce it locally on WSL2 on Windows 10 but was getting different traceback. See https://github.com/astropy/astropy/pull/15495#issuecomment-1766861257

**Comment by pllim** [comment]
(I can try again locally tomorrow if this remains a mystery. I am working on something different now. Thanks for looking into this!)

**Comment by mhvk** [comment]
Maybe `ccache`??

**Comment by ngoldbaum** [comment]
I can reproduce this running tox locally, I'm going to file a numpy bug once I figure out how to trigger it outside of astropy.

**Comment by mhvk** [comment]
Great! Possibly, the part in `time` may be easiest to separate out `astropy/time/setup_package.py` and the source files in `astropy/time/src`.

**Comment by ngoldbaum** [comment]
I think what's happening is *erfa* is failing to completely import, because astropy's tox setup is turning warnings into errors, and erfa currently triggers the `np.core` warning:

```
In [1]: from erfa import ErfaError, ErfaWarning
/home/nathan/.pyenv/versions/3.10.9-debug/lib/python3.10/site-packages/erfa/version.py:25: DeprecationWarning: numpy.core._multiarray_umath is deprecated and has been renamed to numpy._core._multiarray_umath. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core._multiarray_umath._ARRAY_API.
  from . import ufunc
```

We can certainly make this more nice on the numpy side and let `_ARRAY_API` and `_UFUNC_API` import without a warning. The only reason people are accessing that is via `import_array()` and they probably don't have any control over fixing that easily, especially if it happens in a transitive dependency.

**Comment by pllim** [comment]
From erfa? But where? I cannot find where it is actually using deprecated numpy stuff... @mhvk ?

Thanks for the investigation, @ngoldbaum !

**Comment by mhvk** [comment]
Thanks for the sleuthing! I think indeed it would be good to fix this on the numpy side, since it should really not warn if one is using C code linked to the numpy libraries, possibly via dependencies. It may be enough to just special-case `multiarray` and `umath` -- it is not likely that people are importing that on the python side!

**Comment by ngoldbaum** [comment]
I think what's happening is erfa is doing `import_array()` and `import_ufunc()` in C code. The versions of these functions in NumPy 1.x access things in `numpy.core._multiarray_umath`, and if you're using e.g. a wheel that will be problematic since it was likely compiled against older numpy and the old paths are hardcoded in the binary.

I'm not totally sure what's happening in astropy's CI, since erfa is being built against numpy 2.0 (I think?), but regardless the fix is the same and we need to make accessing the attributes that `import_array` and `import_ufunc` need never generate warnings or errors when accessed from `np.core` since as we saw here it's not a very helpful thing to warn on and generates confusing CI breakage.

**Comment by ngoldbaum** [comment]
> it is not likely that people are importing that on the python side!

You'd think so, alas... 

https://github.com/search?q=%22from+numpy.core.multiarray%22&type=code
https://github.com/search?q=%22from+numpy.core._multiarray_umath%22&type=code

**Comment by mhvk** [comment]
With your numpy PR, this PR passes! (well, at least it passes `pytest -P time`, which doesn't pass without your numpy PR). Thanks!

**Comment by pllim** [comment]
> I'm not totally sure what's happening in astropy's CI, since erfa is being built against numpy 2.0 (I think?)

Ah... no. Maybe that's why. Following astropy's recipe, I did a `numpy>=1.25,<2` pin on the build requirements there. 😅 

https://github.com/liberfa/pyerfa/blob/1903739c3e971938c4b4e0e4994d3e3f6039ba71/pyproject.toml#L6

**Comment by pllim** [comment]
So, technically this PR should be ready, so I took it out of draft. But I cannot prove that it fixes numpy-dev compatibility until https://github.com/numpy/numpy/pull/24943 is merged and put into the numpy "nightly" wheel.

And I cannot tell how useful our own dev wheel is even if we merge this right now, until the upstream issue is fixed.

@bsipocz , since you asked for a new astropy dev wheel, what do you think?

**Comment by bsipocz** [comment]
@pllim - getting the dev wheel out fast is not important, I don't have any PRs ready to go in that are blocked by it. I really just ping you about this as a heads up knowing it's just gone in and likely cause problems. 

However, I cannot help not to note that the upper limiting rightfully bit back, just as expected. 

> Ah... no. Maybe that's why. Following astropy's recipe, I did a numpy>=1.25,<2 pin on the build requirements there.

**Comment by seberg** [comment]
> Following astropy's recipe, I did a numpy>=1.25,<2 pin on the build requirements there.

Can't you just remove the `<2` pin?  Not saying it has to be part of this PR.  Forgiving this in NumPy achieves little to nothing.
Unless, that is, you argue that NumPy just isn't allowed to do any ABI breaks, because even the mildest ABI breaks (which we already have) in principle require us to force you to compile against 2.x eventually.
(And yes, that means everyone has to ensure they compiling nightlies against 2.x, which might mean a slightly rocky adoption.)

I guess the upper version is just incorrect for the dev version where you assume you are compatible with any upcoming NumPy version?  Although it is correct for any release that would be cut right now (although some may argue whether it is also helpful).

**Comment by pllim** [comment]
Does unpinning `numpy<2` in the *build* requirements do anything? Is it smart enough to pick up nightly wheels without more setup? Is it smart enough to not use unstable numpy at release? I am not a Python packaging expert.

**Comment by pllim** [comment]
Also, now I remember that @astrofrog and @saimn wanted the `numpy<2` pin, so maybe they can comment.

https://github.com/astropy/astropy/pull/14949#discussion_r1230601818

**Comment by mhvk** [comment]
I have never quite understood the pinning, but we were just following https://github.com/numpy/numpy/issues/24300
> 1. If you rely on the NumPy C API (e.g. via direct use in C/C++, or via Cython code that uses NumPy), please add a numpy<2.0 requirement in your package's dependency metadata. Rationale: the NumPy C ABI will change in 2.0, so any compiled extension modules that rely on NumPy are likely to break, they need to be recompiled.

I think the above recommendation did not consider dependencies that have C code too.

Independently, we should ensure we compile against numpy-dev in our numpy-dev builds! Don't we?! ping @astrofrog as our python build system expert...

**Comment by pllim** [comment]
Turning this back to draft because I think I also need to pull in pyerfa that pulls in numpy-dev?

**Comment by seberg** [comment]
> Does unpinning numpy<2 in the build requirements do anything?

I am not 100% sure, but I would expect it is?  Since you are using `PIP_EXTRA_INDEX_URL`.  You also would need to do so for `pyerfa`, but it seems enough to do it in the repository, since you are pulling that in with pip directly.
(Using `--no-built-isolation` would also work, but I would assume that pre-releases can be picked up at the built step )

**Comment by seberg** [comment]
> I think the above recommendation did not consider dependencies that have C code too.

I think the problem about the recommendation is that it applies to *release versions*.  But we are all testing pre-release versions where the pin is clearly wrong.  We must operate under the assumption that things work with the 2.0 pre-release.

Maybe it would make sense to specifying `<2.0.rc`, to explicitly allow NumPy nightlies?!

**Comment by pllim** [comment]
Gah, as @saimn pointed out, `tox` hides the build log, so I cannot see what happened there but what I have so far does not seem to do any difference.

**Comment by pllim** [comment]
Well, I don't have much time to deep dive into build stuff this week, so... I might open an alternate PR later with the original `core -> _core` patch + warning ignore and see. Stay tuned!

**Comment by pllim** [comment]
Oh wait, it is `ImportError`, not a warning... 😩

**Comment by mhvk** [comment]
I added
```
    # Ignore numpy 2.0 warning
    "ignore:numpy.core._multiarray_umath is deprecated:DeprecationWarning"
```
and then the test worked again.

**Comment by pllim** [comment]
No matter how hard we try here, won't we still be bitten by other stuff upstream until the whole ecosystem follows suit? I mean, are we affected by this?

* https://github.com/scipy/scipy/pull/19275

**Comment by seberg** [comment]
@pllim what is going on i sthat pip refuses to build against pre-releases like this.  We need to add `PIP_PRE=1` to allow that.  I guess that is what the `>0.0.dev0` does, but I tries adding `<2.0.0.rc9` and I don't think that worked.  Maybe changing requires to include the dev would work.  Or disabling build isolation...

**Comment by pllim** [comment]
I rebased and changed the scopy/title of this PR. Though depending on how  #15506 evolves, this might be obsolete soon. Thank you everyone for the very useful discussions!

**Comment by pllim** [comment]
@astrofrog , do we still need this?

**Comment by astrofrog** [comment]
I don't think so, I think we want to keep it pinned for now in pyproject.toml

**Pull request closed without merging**
