### PR TITLE
TST: skip a docstring-focused test when running in Python's optimized mode

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
ref #17472

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by eerovaher** [comment]
What is the purpose of the change here? If you are running the tests at an optimization level that discards docstrings then you are also running at an optimization level that discards `assert` statements, so trying to access the docstrings can't cause problems.

**Review by mhvk — APPROVED** [review]
I guess this means the docstring creation itself was secure against optimization? That's nice to know!

**Comment by mhvk** [comment]
@eerovaher - `pytest` assert are not affected by optimization - another bit of `pytest` magic - it rewrites the `assert` upon import of the test module - https://docs.pytest.org/en/stable/announce/release-2.1.0.html and https://docs.pytest.org/en/stable/how-to/assert.html#assert-details. (Discovered this in https://github.com/numpy/numpy/pull/27868)

**Comment by neutrinoceros** [comment]
> pytest assert are not affected by optimization 

yes. I'm only addressing actual issues that I discover while actually running pytest with `PYTHONOPTIMIZE=2`, I'm not trying to guess what could be wrong.

**Comment by eerovaher** [comment]
I can't run the tests with optimizations at all (with `pytest` 8.3.2) 
```
$ PYTHONOPTIMIZE=1 pytest astropy/time/tests/test_sidereal.py
Traceback (most recent call last):
  ...
pytest.PytestConfigWarning: assertions not in test modules or plugins will be ignored because
assert statements are not executed by the underlying Python interpreter (are you using python -O?)
```

**Comment by neutrinoceros** [comment]
yes, one also needs to ignore this specific warning in pytest's configuration, which is annoying to do since you also have to know what builtin warning type `PytestConfigWarning` derives from.
I use this patch to run tests:
```patch
diff --git a/pyproject.toml b/pyproject.toml
index b2dea87895..985b3ef455 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -221,6 +221,7 @@ filterwarnings = [
     "error",
     "ignore:unclosed <socket:ResourceWarning",
     "ignore:unclosed <ssl.SSLSocket:ResourceWarning",
+    "ignore:assertions not in test modules or plugins will be ignored:UserWarning"
 ]
 doctest_norecursedirs = [
     "*/setup_package.py",
```

**Pull request merged**
