### PR TITLE
Workflow for self-assigning issues

### PR DESCRIPTION
**Pull request by sugatoray**
With this workflow, repository members will be able to self-assign the issues by just commenting `#self-assign` in the issues on GitHub.

Closes #14085.

### Description

This pull request is to address ...

Fixes #<Issue Number>

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by taldcroft** [comment]
Hi @sugatoray - thanks for the contribution! 

I'm just wondering whether we really need this action when there is a obvious and easily accessible method built into the GitHub issue page:
image

**Comment by pllim** [comment]
Auto self-assign does not really fit with our existing workflow here, so I would propose we not accept this.

Thank you anyway for your contribution!

**Comment by sugatoray** [comment]
Hi @taldcroft and @pllim ,

It seems that if you are not an existing member already, you cannot assign an issue to yourself now. 

image

The workflow allows anyone to make a comment in the issue and get it assigned. This reduces one more administrative item on the repository maintainers' part as well. 

Thank you, for your feedback and consideration.

**Comment by pllim** [comment]
We don't really use the "assignee" field for anything though.

**Comment by sugatoray** [comment]
If this seems not necessary, it is understandable if you would not like to add it to the repository. :)

**Comment by pllim** [comment]
@sugatoray , if you are interested in fixing an existing issue, it is best to discuss your idea in one of these [communication channels](https://www.astropy.org/help). And if the fix is trivial, go ahead and open a pull request. Assigning an issue to someone does not really mean anything because we have no way to enforce that the assignee actually should do the work. Thank you very much for your interest!

**Pull request closed without merging**
