### PR TITLE
Promote MplQuantityConverter to a public object

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR promotes the contents of `astropy.visualization.units.quantity_support()` to module-level objects, so that they are independently referenceable. The motivation is mainly to allow customisation of the `MplQuantityConverter` via sub-classing.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
I should add, the specific motivation for this change is to expose a method to include equivalencies in the unit conversions, as required for angles-as-dimensionless-units conversions (rad/s -> Hz) [[1]], so if there's a simpler method to do that, I would be happy to implement that instead of the currently proposed change.

[1]: http://docs.astropy.org/en/stable/units/equivalencies.html#angles-as-dimensionless-units

**Comment by duncanmmacleod** [comment]
I see now that the tests are failing because `matplotlib` isn't a dependency, which is probably why `MplQuantityConverter` wasn't exposed as a public object in the first place.

At a first glance there are many ways to get around this, the simplest being a `try/except` clause on the mpl import:

```python
try:
    from matplotlib import units
except ImportError:
    pass
else:
    class MplQuantityConverter(...)
    ...
```

**Comment by bsipocz** [comment]
@duncanmmacleod - Our usual approach is to skip in the tests with a try/except but not in the code when an optional dependency is not installed, see the other tests of this module.

**Comment by duncanmmacleod** [comment]
@bsipocz, because `astropy.visualization.units` is imported with `*` in `astropy.units.__init__` lots of things are failing without `matplotlib` because they can't import _anything_ from `astropy.visualization`. So, the solution requires more than just a `skipif` for this module's tests, unfortunately.

**Comment by saimn** [comment]
The tricky point is the class that inherits from Matplotlib, for this you can define a stub class if the import fails, class with should raise the ImportError when it is instantiated. There is an other case like this in https://github.com/astropy/astropy/blob/master/astropy/visualization/mpl_normalize.py#L15-L27

**Comment by mhvk** [comment]
@duncanmmacleod - I wonder if there isn't indeed an easier method than subclassing: ideally, if you work within a `with u.add_enabled_equivalencies(...)` context, this would "just work". Can you give an example that does not work?

**Comment by duncanmmacleod** [comment]
@mhvk, I don't think I was aware of the option of using `add_enabled_equivalencies` as a contextmanager. That might solve my issue totally, I will confirm, and if so, will close this ticket.

**Comment by larrybradley** [comment]
@duncanmmacleod Did using the `add_enabled_equivalencies` context manager solve your issue?

**Pull request closed without merging**
