### PR TITLE
[pytest] section in setup.cfg files is deprecated, using [tool:pytest] instead.

### PR DESCRIPTION
**Pull request by mohanagr**
Bug fixed in version 3.0.0 of Pytest
### Reference: pytest-dev/pytest#567

*Maintainer edit:*
- [ ] Need to add change log when v3.0 section is available.

### CODE REVIEW

**Comment by pllim** [comment]
This is deliberately not done because Astropy still supports pytest 2.x, and cannot be done until Astropy bumps minversion of pytest to 3.x.

**Comment by pllim** [comment]
However, I don't know if we should close this out, or keep it open till Astropy can merge. @bsipocz , @astrofrog ?

**Comment by mhvk** [comment]
Should this perhaps be for astropy 3.0?

**Comment by adrn** [comment]
Is there a way then to hide the pytest warning? I don't like that now I get a yellow bar even when the tests run successfully!

image

**Comment by pllim** [comment]
> Is there a way then to hide the pytest warning?

Not that I know of. If it really bothers you, you can downgrade your pytest to 2.8.

**Comment by mhvk** [comment]
in principle, it seems one should be able to add a hook `pytest_logwarning` but I haven't been able to figure out how to use it to actually remove the warning. I also find it quite annoying and don't want to downgrade pytest just for this.

**Comment by bsipocz** [comment]
Thanks @mohanagr for doing this PR. This has been basically done in a separate PR, so I'm closing.

**Pull request closed without merging**
