### PR TITLE
fix variable names in example snippet (docs)

### PR DESCRIPTION
**Pull request by bramblescramble**
I found a couple of typos in a code snippet in the documentation. Since it was a pretty simple fix, I figured I'd open a pull request right away, without opening an issue. I hope this is ok. :)

### CODE REVIEW

**Comment by pllim** [comment]
Thanks. Unfortunately, seems to be a duplicate of #8491 , which is currently stuck awaiting resolution in #8412.

**Comment by SG004** [comment]
> Thanks. Unfortunately, seems to be a duplicate of #8491 , which is currently stuck awaiting resolution in #8412.

#8412 is just waiting for approval, it is all green.

**Comment by bsipocz** [comment]
@bramblescramble - Thank you very much for the contribution. This is a tricky example that tripped over quite a few people recently. It reuses variables from the top of the section, following the whole narrative along they all should work out of the box:

http://docs.astropy.org/en/stable/coordinates/matchsep.html#matching-catalogs

If you have ideas how to make this setup clear in the documentation please let us know (either a PR with the suggestion or an issue is more than welcome).

**Comment by bsipocz** [comment]
Never mind my stupid comment above. I was way too involved in the details of #8412 and didn't read careful enough. These are indeed typos. However https://github.com/astropy/astropy/pull/8491 has a fix for it already, so I'm going ahead and merge that one instead.

**Pull request closed without merging**
