### PR TITLE
Possible fixes for Spline test fails due to floats.

### LINKED ISSUE #12403: [5.0RC1] exact double comparison in test_spline.py, exposed by Debian/ppc64el
### Description

Some tests in `astropy/modeling/tests/test_spline.py` compare doubles by equal, which not always works. Specifically on the PowerPC 64 Little Endian architecture on Debian, this gives failures

### Expected behavior

Tests should pass :-)

### Actual behavior
```
_________________ TestSpline1D.test_interpolate_fitter[2-None] _________________

self = <astropy.modeling.tests.test_spline.TestSpline1D object at 0x7ffeb53a7a90>
w = None, k = 2

    @pytest.mark.parametrize('w', wieght_tests)
    @pytest.mark.parametrize('k', degree_tests)
    def test_interpolate_fitter(self, w, k):
[...]
        assert (fit_spl.t == spline._eval_args[0]).all()
        assert (fit_spl.c == spline._eval_args[1]).all()
        assert (fitter.fit_info['spline']._eval_args[0] == spline._eval_args[0]).all()
        assert (fitter.fit_info['spline']._eval_args[1] == spline._eval_args[1]).all()
    
        assert spline.get_residual() == fitter.fit_info['resid'] == 0
>       assert (fit_spl(self.x) == spline(self.x)).all()
E       assert False
E        +  where False = <built-in method all of numpy.ndarray object at 0x7ffeb52a9030>()
E        +    where <built-in method all of numpy.ndarray object at 0x7ffeb52a9030> = array([ 0.073...  0.05145015]) == array([ 0.073...  0.05145015])
E             Use -v to get the full diff.all
```
The same happens on `test_smoothing_fitter` (line 1207) and `test_exact_knots_fitter` (line 1267), all fails several times for different parameters.

[Full build log](https://buildd.debian.org/status/fetch.php?pkg=astropy&arch=ppc64el&ver=5.0%7Erc1-1&stamp=1636027474&raw=0)

### Steps to Reproduce

This happens when running on PowerPC 64 bit little endian. 

### System Details

platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
Matplotlib: 3.3.4
Freetype: 2.11.0

Running tests with Astropy version 5.0-rc1.
Running tests in .pybuild/cpython3_3.9/build.

Date: 2021-11-04T11:57:20

Platform: Linux-5.10.0-9-powerpc64le-ppc64le-with-glibc2.32

Executable: /usr/bin/python3.9

Full Python Version: 
3.9.7 (default, Sep 24 2021, 09:43:00) 
[GCC 10.3.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.19.5
Scipy: 1.7.1
Matplotlib: 3.3.4
h5py: 3.3.0
Pandas: not available
PyERFA: 2.0.0
Cython: 0.29.24
Scikit-image: not available
asdf: not available
pyarrow: not available

Using Astropy options: remote_data: none.

ARCH_ON_CI: undefined
IS_CRON: undefined

rootdir: /<<PKGBUILDDIR>>, configfile: setup.cfg
plugins: mpl-0.11, remotedata-0.3.2, openfiles-0.5.0, mock-3.6.1, filter-subpackage-0.1.1, doctestplus-0.11.0, cov-3.0.0, astropy-header-0.1.2, arraydiff-0.3, hypothesis-5.43.3

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

This PR is to address the double precision comparison fails documented by issue #12403.

Fixes #12403

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Requesting @olebole for review. Please let us know when the spline tests start passing for your environment.

**Comment by olebole** [comment]
Still doesn't work, as the next code line has the same problem:
```
    def check_spline_fit(self, fit_spl, spline, fitter, atol_fit, atol_truth):
        """Check the spline fit"""
        assert_equal(fit_spl.t, spline._eval_args[0])
        assert_equal(fit_spl.c, spline._eval_args[1])
        assert_equal(fitter.fit_info['spline']._eval_args[0], spline._eval_args[0])
        assert_equal(fitter.fit_info['spline']._eval_args[1],  spline._eval_args[1])
    
        assert_equal(spline.get_residual(), fitter.fit_info['resid'])
    
        assert_allclose(fit_spl(self.x), spline(self.x))
>       assert_equal(fit_spl(self.x), fitter.fit_info['spline'](self.x))
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 11 / 50 (22%)
E       Max absolute difference: 1.11022302e-16
E       Max relative difference: 1.94971928e-15
E        x: array([ 0.07397 ,  0.01739 , -0.01106 , -0.029133, -0.146018, -0.068643,
E              -0.040157,  0.115846,  0.051235, -0.149042,  0.075156,  0.026541,
E               0.028369,  0.198834,  0.294563,  0.351544,  0.254555,  0.399325,...
E        y: array([ 0.07397 ,  0.01739 , -0.01106 , -0.029133, -0.146018, -0.068643,
E              -0.040157,  0.115846,  0.051235, -0.149042,  0.075156,  0.026541,
E               0.028369,  0.198834,  0.294563,  0.351544,  0.254555,  0.399325,...

astropy/modeling/tests/test_spline.py:1143: AssertionError
```
(on the other places as well). [Full build log](https://buildd.debian.org/status/fetch.php?pkg=astropy&arch=ppc64el&ver=5.0%7Erc1-4&stamp=1636124625&raw=0)

**Comment by WilliamJamieson** [comment]
@olebole, okay that convinces me that it is some sort of strange floating point thing. In the latest push converted all the floating point comparisons to `assert_allclose`. That _should_ fix the bug.

**Comment by olebole** [comment]
I can confirm that this works now. Build log [here](https://buildd.debian.org/status/fetch.php?pkg=astropy&arch=ppc64el&ver=5.0%7Erc1-5&stamp=1636130318&raw=0). Thank you for the fix!

**Review by nden — APPROVED** [review]

**Pull request merged**
