### PR TITLE
Update cfitsio v3.48

### LINKED ISSUE #10252: Upstream release of dependency: cfitsio
### Description

This is a message from an automated system that monitors `cfitsio` releases.

Version 3.48 - Mar 2020

  - Now can handle parentheses in path names rather than automatically
    interpreting them as output file specifiers.  

  - Fixed bug in imcompress.c that wasn't properly handling conversion
    between float and double types when reading from a gzip compressed
    float or double image.
    
  - Fixed bug that was preventing use of bracket and parentheses symbols
    in pathnames when opening multiple READWRITE files, even when 
    requesting no-extended-syntax usage. *This fix necessitates a 
    library interface version number change.
    
  - Fixed bug in ffmnhd / fits_movnam_hdu to properly handle wildcard
    syntax.

  - Fixed bug in fits_open_extlist to handle filename[EXT] syntax
    properly.  The hdutype parameter may now be null.  More documentaion
    for this function is in cfitsio.tex.

  - Added new function fits_copy_hdutab to create a new table with the same
    structure as an existing table.

  - fits_copy_col / ffcpcl handles long long integer data types more
    natively to prevent precision loss.

  - histo.c routines now recognize integer columns that have been scaled by
    TSCALn keywords and may be closer to floating point type.
                   
  - Added backward compatibility for very old Rice compressed files which
    were not using the ZVAL2 keyword in the way that later became standard.

  - Change made to cfitsio.pc.in to prevent forcing downstream libraries
    to link against cfitsio's dependencies when using pkgconfig.

(For complete changelog information, consult the package changelog file in cfitsio/doc/changes.txt)

  **NOTE: This release introduces a SONAME change from 8 to 9.**

### Additional context

Reposting from spacetelescope/hstcal#476 . Thanks to @rendinam .

https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes.txt

### PR DESCRIPTION
**Pull request by saimn**
Closes #10252.

### CODE REVIEW

**Comment by pllim** [comment]
Thank you, @saimn !

**Comment by bsipocz** [comment]
Excellent. Is there any api breakage? Should I backport? (we certainly backported wcslib updates, I can dig up whether there was precedent for cfitsio or not, too).

**Comment by saimn** [comment]
I think there is nothing in there that really concerns us since we use only the tile compression. But it's better to stay up-to-date. So backporting does not seem necessary for now.

**Comment by bsipocz** [comment]
My question is more along the line of whether there is anything against the backport. It's just life easier with less divergence, as it may happen the next update has to be backported (e.g. 3.43 and 3.44 had to be backported to previous LTS versions).

**Comment by bsipocz** [comment]
CI is all OK, so I'm merging. Thanks @saimn!

**Comment by saimn** [comment]
@bsipocz - Nothing against the backport, and yes it can be useful if in the future there is another version to backport with a more critical fix.

**Pull request merged**
