### PR TITLE
Add tool to search affiliated packages on github

### PR DESCRIPTION
**Pull request by mdboom**
In trying to answer some questions about the usage of the configuration package among affiliated packages, I found this tool to be pretty useful.

```
./astropy_grep_affiliated ConfigItem
```

opens the following URL:

https://github.com/search?q=repo%3Aastropy%2Fspecutils+repo%3Aastropy%2Fastroquery+repo%3Aastropy%2Fphotutils+repo%3Aeteq%2Fastropysics+repo%3Aejeschke%2Fg+repo%3AastroML%2Fast+repo%3Aweaverba137%2Fpydl+repo%3Aaplpy%2Faplpy+repo%3Agammapy%2Fgammapy+repo%3Aastropy%2Fccdproc+repo%3Asncosmo%2Fsnc+repo%3Aspacetelescope%2Fim+ConfigItem&type=Code

Thought it might be useful...  wasn't exactly sure where to put it, so put it under a new `devtools` directory.  I could also just share it as a gist if it doesn't belong in the repo.

### CODE REVIEW

**Comment by astrofrog** [comment]
Nice! I think this should go in:

https://github.com/astropy/astropy-tools

which is precisely for this kind of script. Thanks!

**Comment by mdboom** [comment]
Closed in favor of astropy/astropy-tools#2

**Comment by embray** [comment]
HMMM I'm tempted to either reopen this PR, or at least open a new issue, because I think something like this could still be very useful to have in Astropy.  For that matter it could search the Astropy docs as well..

In other words, from the Python prompt as soon as I need a thing it would be awesome to search the docs for Astropy and any/all affiliated packages to see what comes up.

**Comment by astrofrog** [comment]
I don't think there's any reason to have it in the core package for now though. But there's also no reason we can't make astropy-tools installable to provide command-line scripts anywhere, for convenience.

**Pull request closed without merging**
