### PR TITLE
Update image.py

### PR DESCRIPTION
**Pull request by mittimithai**
I get   Get TypeError: Cannot cast ufunc add output from dtype('int32') to dtype('uint16') with casting rule 'same_kind'                                     
with my newer numpy:
 self.data += -_zero     

I think it is safe to update to:
self.data += self.data.dtype.type(-_zero)

### CODE REVIEW

**Comment by pllim** [comment]
@mittimithai , could you please give a standalone code snippet that could reproduce your reported error? Thanks.

**Comment by mittimithai** [comment]
I should've been more verbose.  I got the error in trying to get lxnstack (that uses astropy) working on my machine.  This seems to be a new convention in [numpy](http://docs.scipy.org/doc/numpy-dev/release.html):

"Default casting for inplace operations has changed to 'same_kind'. For instance, if n is an array of integers, and f is an array of floats, then n += f will result in a TypeError, whereas in previous Numpy versions the floats would be silently cast to ints. In the unlikely case that the example code is not an actual bug, it can be updated in a backward compatible way by rewriting it as np.add(n, f, out=n, casting='unsafe'). The old 'unsafe' default has been deprecated since Numpy 1.7."

It seems that negative values can end up in "zero", so you can replicate the error with the following snippet (my numpy is 1.10.4_0 installed from macports):

import numpy as np
a=np.uint16([1,2,6,5])
a+=np.int32(-1)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast ufunc add output from dtype('int32') to dtype('uint16') with casting rule 'same_kind'

**Comment by pllim** [comment]
@mittimithai , thanks for the clarification. However, casting -1 brute-force to `uint16` changes it to 65535. Is that really what you want? Perhaps it is best to raise error since unsigned int does not handle negative values?

```python
>>> _zero
-1
>>> data.dtype.type(_zero)
65535
```

Also, I think rebasing your PR to the latest master might get rid of the AppVeyor failure.

**Comment by mittimithai** [comment]
My solution indeed may not be correct after tracing through the code(though it appears to work).  The error is triggered from lxnstack when opens a canon raw CR2 file and tries to convert it to FITS with astropy.

I put the the longer trace below, lnxnstack fills 'data' with type 'uint16' and then eventually applies 'scale' with a destination data type of 'int16'.  The add happens before the conversion of 'data' to the new type.  The conversion should happen *before* zeroing and scaling, the zero and the scale factor should be constructed to be the same type as 'data'.  I am not sure if that will introduce a problem with NaN handling.

Would the best thing to do be to close this pull request and open a new one that moves the conversion above the scaling?

File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lxnstack/utils.py", line 1953, in _imwrite_fits_
    outbits)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lxnstack/utils.py", line 1983, in _get_fits_hdl
    hdu.scale('int16', bzero=32768)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/hdu/image.py", line 384, in scale
    bzero=bzero, blank=None)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/hdu/image.py", line 443, in _scale_internal
    self.data += -_zero
TypeError: Cannot cast ufunc add output from dtype('int32') to dtype('uint16') with casting rule 'same_kind'

**Comment by pllim** [comment]
Superseded by #4783

**Pull request closed without merging**
