### PR TITLE
Make fitting_parallel.py private to make sure function parallel_fit_dask is imported from astropy.modeling.fitting

### PR DESCRIPTION
**Pull request by astrofrog**
Although we haven't really reached a consensus on the public API APE, we might as well make this new file private by default since it isn't meant to be used directly.

### Blocked by

* https://github.com/astropy/sphinx-automodapi/pull/190

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by pllim — DISMISSED** [review]
Note to self: First added in https://github.com/astropy/astropy/pull/16696 also milestoned to v7.0.0 ,  so this is changing an unreleased feature and does not need change log.

**Comment by pllim** [comment]
Broke RTD

`WARNING: py:func reference target not found: astropy.modeling.fitting.parallel_fit_dask`

**Comment by pllim** [comment]
pre-commit.ci autofix

**Comment by astrofrog** [comment]
Huh, any idea why this would have broken RTD?

**Comment by pllim** [comment]
The ref does not exist anymore because module is private?

**Comment by astrofrog** [comment]
But the ref is pointing to the fitting.py file not parallel_fitting.py, so it should be fine?

**Comment by pllim** [comment]
I am not the one you have to convince...

**Comment by neutrinoceros** [comment]
Could you try explicitly re-exporting it ?
```patch
diff --git a/astropy/modeling/fitting.py b/astropy/modeling/fitting.py
index 40f0bac01d..dee76ed6ce 100644
--- a/astropy/modeling/fitting.py
+++ b/astropy/modeling/fitting.py
@@ -33,7 +33,7 @@ import numpy as np
 from astropy.units import Quantity
 from astropy.utils.exceptions import AstropyUserWarning
 
-from ._fitting_parallel import parallel_fit_dask
+from ._fitting_parallel import parallel_fit_dask as parallel_fit_dask  # noqa: PLC0414
 from .optimizers import DEFAULT_ACC, DEFAULT_EPS, DEFAULT_MAXITER, SLSQP, Simplex
 from .spline import (
     SplineExactKnotsFitter,
```

**Comment by nstarman** [comment]
This may be a configuration issue? I think Sphinx needs something like:

```
.. automodule:: fitting
   :members:
   :undoc-members:
   :show-inheritance:
```

```
# Automatically document members imported in modules
autodoc_default_options = {
    'members': True,
    'imported-members': True,  # Include imported members
    'undoc-members': True,  # Include members w/out docstrings
    'show-inheritance': True,
}
```

**Comment by astrofrog** [comment]
I think the solution has to be different here because we are using sphinx-automodapi which lists the individual classes and functions. We usually don't have this issue when we import up one level, I think this is because it is a 'sideways' import. I wonder if it is a bug in sphinx-automodapi's smart_resolver, will investigate.

**Comment by astrofrog** [comment]
Working on it in https://github.com/astropy/sphinx-automodapi/pull/190

**Comment by astrofrog** [comment]
Ok so https://github.com/astropy/sphinx-automodapi/pull/190 should fix this, would appreciate some reviews of that PR, then I can release a new version of sphinx-automodapi and try it here.

**Comment by astrofrog** [comment]
Triggering a new build to pick up sphinx-automodapi v0.18.0

**Review by Cadair — APPROVED** [review]

**Pull request merged**
