### PR TITLE
TST: test LombScargle for integer inputs

### PR DESCRIPTION
**Pull request by jakevdp**
cf. discussion at #4950

### CODE REVIEW

**Comment by jakevdp** [comment]
This might fail on 32-bit machines without the fix from #4950. It depends on the particular architectures that the CI systems use.

**Comment by bsipocz** [comment]
@jakevdp - Afaik we don't have any 32bit CI, but usually do 32bit test runs for the release candidates.

**Comment by jakevdp** [comment]
Tests are failing due to integer casting. I'm going to rebase on master now that #4950 is merged.

**Comment by pllim** [comment]
I cancelled the failing Travis build. FYI.

**Comment by pllim** [comment]
Marking this as 1.2 since it is closely related to the other PR also marked for 1.2.

**Comment by jakevdp** [comment]
Tests pass with the #4950 fix!

**Comment by mhvk** [comment]
Looks good. @astrofrog - I don't want to make work for you, but it seems this would also be a good addition to 1.2 -- not as much a bug-fix, but rather as a bug-preventer! If you agree, feel free to merge.

**Comment by astrofrog** [comment]
:+1:

**Pull request merged**
