### PR TITLE
Changing pep8 tool to pycodestyle

### PR DESCRIPTION
**Pull request by bsipocz**
They had recently changed the name, and however there is a cooling down deprecation period, it's worth changing this now (rather than getting the warnings).

We also use ``pytest-pep8``, but it's not yet updated.

### CODE REVIEW

**Comment by bsipocz** [comment]
Could someone restart this travis?

**Comment by mwcraig** [comment]
The failing builds have been restarted.

**Comment by bsipocz** [comment]
OK, this was failing due to https://github.com/PyCQA/pycodestyle/issues/550, but now should pass.

**Comment by bsipocz** [comment]
Could someone please restart the failing build once again? Now it should really pass.

**Comment by mwcraig** [comment]
Done

Thanks,
Matt Craig

**Comment by mhvk** [comment]
@bsipocz - this looks good to me!

For travis, I thought runs can be restarted both by the committer and by someone with push privilege. Is this not true? (You may need to register with travis; I don't recall any more what the process was... cc @astrofrog).

**Comment by bsipocz** [comment]
@mhvk - Yes, that would be logical workflow, but it doesn't work for me like that. I can cancel builds, not only mine, but cannot restart the builds.

**Comment by astrofrog** [comment]
@bsipocz - sorry for not merging that sooner, can you rebase?

**Comment by bsipocz** [comment]
Np, rebased now.

**Comment by astrofrog** [comment]
@bsipocz - thanks!

**Comment by astrofrog** [comment]
(Travis failure unrelated, due to sesame being down)

**Comment by astrofrog** [comment]
Haha @astrobot, I win 👻

**Pull request merged**
