### PR TITLE
Use `np.random.default_rng()` in code examples

### PR DESCRIPTION
**Pull request by eerovaher**
### Description

[The recommended way of generating random numbers in `numpy` is through `np.random.default_rng()`](https://numpy.org/doc/stable/reference/random/index.html#quick-start). All code examples in the narrative documentation now follow this recommendation.

That `default_rng()` is now indeed used in all the code examples can be verified as follows:
```shell
git grep -e np.random --and --not -e np.random.default_rng -- docs
```
The output of the above command consists of three lines. One is a comment and the others setup for doctests.

The first commit of this pull request is cherry-picked from #12669.

### Approval by subpackages

- [ ] convolution
- [x] coordinates
- [x] modeling
- [ ] nddata
- [x] stats
- [ ] timeseries
- [x] uncertainty
- [x] units
- [ ] visualization

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by mhvk** [comment]
Yes, good idea to split out the completely uncontroversial part of #12669 - I'm still not sold on having to pass on random number generators, but the changes here to usage are all great.

**Review by WilliamJamieson — APPROVED** [review]
Modeling related changes look good.

**Review by adrn — APPROVED** [review]
Coordinates, stats, units, uncertainty changes look good to me -- thanks @eerovaher

**Comment by eerovaher** [comment]
I had some trouble getting one of the doctests to pass the Windows and 32-bit tests because of a printed dtype, but its sorted out now and this pull request is ready for final review.

**Comment by pllim** [comment]
There are enough approvals, so I am merging. Thanks!

Though, I am not sure about clean backports but let's see... 🤞

**Comment by pllim** [comment]
@eerovaher , do you want to manually backport this to 5.0.x or should we move the milestone?

**Comment by eerovaher** [comment]
I will backport manually. If NumPy says that `default_rng()` is the way to generate random numbers then we shouldn't be telling people otherwise.

**Pull request merged**
