### PR TITLE
Support ASDF serialization of tables with mixin columns

### PR DESCRIPTION
**Pull request by drdavella**
While #8261 implemented a table reader/writer for ASDF, this PR allows tables with all valid column mixins to be serialized.

### CODE REVIEW

**Comment by drdavella** [comment]
The failure on 32-bit circleci seems to be unrelated.

**Comment by taldcroft** [comment]
@drdavella - I haven't the expertise (and/or time) to really review all the implementation details, but about testing I wonder if you considered re-using the testing code for `io.ascii.ecsv` (which is also somewhat replicated for FITS and HDF5).  It's ugly code (my standards go down for testing code), but it's there and does the end-to-end testing.

https://github.com/astropy/astropy/blob/867ec9df33f2f2ace62031ab94f4f643a535a02e/astropy/io/ascii/tests/test_ecsv.py#L257

`test_ecsv_mixins_per_column()` and perhaps also `test_ecsv_mixins_as_one()` would be the main test functions to start from.

Anyway, just an idea.

**Comment by drdavella** [comment]
@taldcroft I did actually get specific test cases from that code, but I didn't reuse any of the infrastructure. Maybe it's worth revisiting to see if I can refactor things, though.

**Comment by eteq** [comment]
I think I'm OK with getting this through based on @astrofrog's comment, so I'm going to go ahead and hit the button.

**Comment by bsipocz** [comment]
I'm going ahead and merge this then.

Thank you @drdavella!

**Pull request merged**
