### PR TITLE
Include 3-d list for full coverage of list init code

### PR DESCRIPTION
**Pull request by taldcroft**
### Description

This is a follow-up to #10636 since I noticed the inline code coverage comment that [one line of the code](https://github.com/astropy/astropy/pull/10636/files#diff-30ea8400f76ea2c3dfd24787113276f6R248) there was not tested. Indeed that was correct and this PR adds a 3-d list that will now test that line.

### CODE REVIEW

**Comment by taldcroft** [comment]
This is a pretty trivial change - anybody watching could review.  @pllim, @mhvk?

**Comment by taldcroft** [comment]
Yes, the inline comment by codecov actually made me see the problem. Previously I was just uniformly ignoring it.

**Comment by taldcroft** [comment]
What I want to know is if codecov will give me a gold star for fixing a coverage problem.

**Comment by mhvk** [comment]
That in-line comment does indeed seem nice - at least one knows it is related to one's own PR!

**Pull request merged**
