### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by lpsinger**
- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Review by nstarman — APPROVED** [review]
Thanks!

**Review by mhvk — APPROVED** [review]
Thanks! That has been there since 4.2...

**Comment by mhvk** [comment]
Rerunning a timed-out test, but put on auto-merge, so hopefully things will just work. Felt it was not worth backporting since 6.0 is going to be out quite soon (and the code does work).

**Comment by pllim** [comment]
Might as well backport if auto is possible. Thanks!

@meeseeksdev backport to v5.0.x

@meeseeksdev backport to v5.3.x

**Pull request merged**
