### PR TITLE
io.ascii inconsistency in expected exception classes

### PR DESCRIPTION
**Pull request by taldcroft**
The list of allowed or expected exception classes in the io.ascii guess process is initially:
```
        except (core.InconsistentTableError, ValueError, TypeError, AttributeError,
                core.OptionalTableImportError, core.ParameterError, cparser.CParserError) as err:
```
But then if everything fails there is a last-gasp try using the original read_kwargs without strict name checking, and there the exception list is:
```
        except (core.InconsistentTableError, ValueError, ImportError,
                core.OptionalTableImportError, core.ParameterError, cparser.CParserError) as err:
```
These should just be factored out into one common list.

This came up in a question on the astropy list where trying to read a CDS file resulted in an uncaught TypeError exception being raised:
```
/data/baffin/tom/git/astropy/astropy/io/ascii/ui.py in _guess(table, read_kwargs, format, fast_reader)
    433         # Failed all guesses, try the original read_kwargs without column requirements
    434         try:
--> 435             reader = get_reader(**read_kwargs)
    436             dat = reader.read(table)
    437             _read_trace.append({'kwargs': read_kwargs,

/data/baffin/tom/git/astropy/astropy/io/ascii/ui.py in get_reader(Reader, Inputter, Outputter, **kwargs)
    162     if Reader is None:
    163         Reader = basic.Basic
--> 164     reader = core._get_reader(Reader, Inputter=Inputter, Outputter=Outputter, **kwargs)
    165     return reader
    166 

/data/baffin/tom/git/astropy/astropy/io/ascii/core.py in _get_reader(Reader, Inputter, Outputter, **kwargs)
   1239         del kwargs['fast_reader'] # ignore fast_reader parameter for slow readers
   1240     reader_kwargs = dict([k, v] for k, v in kwargs.items() if k not in extra_reader_pars)
-> 1241     reader = Reader(**reader_kwargs)
   1242 
   1243     if Inputter is not None:

TypeError: __init__() got an unexpected keyword argument 'readme'
```
We had a discussion once about why we should not just do `except Exception as err`, but I can't remember the answer.  This list of exception classes is already pretty broad and can certainly be hiding bugs (like the one fixed in #4115).  Do you remember @hamogu?

### CODE REVIEW

**Comment by taldcroft** [comment]
Code attached.

**Comment by hamogu** [comment]
Looks fine to me and can be merged.

**Comment by taldcroft** [comment]
I suppose there should be a bug-fix entry in the change log for 1.1.1 (even if this is pretty obscure).  There is no 1.1.1 section in CHANGES.rst, so I will probably just let this one sit until 1.1 is out and a 1.1.1 section appears.

**Comment by bsipocz** [comment]
@taldcroft - Cannot finished bugfixes still be backported to 1.1.0?

**Comment by taldcroft** [comment]
@hamogu - In theory yes, but at this point I would think that applies more to critical bugs that have been discovered in beta testing.  At least that is my understanding.

**Comment by taldcroft** [comment]
We need a decision for which version from people working on the release -- @astrofrog, @embray, @eteq?

**Comment by embray** [comment]
If this is just a bug fix we can still put in it in v1.1.0.

**Comment by taldcroft** [comment]
@embray - excellent, I updated the milestone and merged.

**Comment by eteq** [comment]
Backported to v1.1.x in cb68d8d

Also, @taldcroft, should this also be backported to v1.0.x?  It's labeled "affects-release", so I'm guessing yes?

**Comment by taldcroft** [comment]
@eteq - that's correct, thanks.

**Pull request merged**
