### PR TITLE
WIP: move parameters to ECSV

### PR DESCRIPTION
**Pull request by nstarman**
### Description

Why ECSV: units, metadata, lists of cosmologies.

Blocked by #11559

### CODE REVIEW

**Comment by embray** [comment]
I think we should just add pyyaml as a dependency for Astropy.  We can discuss this further on the mailing list, but I've raised the point in the past that we should not be quite so conservative about adding new dependencies, especially if they are simple (and already very commonly installed) ones like pyyaml.

**Comment by taldcroft** [comment]
About making YAML a strict dependency, from my own perspective having spent so much time writing YAML-dependent code, I'm generally in favor. But it would definitely need to be discussed in the mailing list with some assurance that this doesn't open the floodgates.

Related:
- In #11528 @eteq has continued his years-long effort to get units put into different ASCII formats, and I have continued to push back arguing that ECSV is just better and should be the one way to communicate units in ECSV.
- In #11569, I have narrative doc updates in work that will more prominently emphasize ECSV as the recommended ASCII format for most applications.

... and I realize now this is completely OT, sorry. @embray maybe you should open an issue about YAML?

**Comment by mhvk** [comment]
Agreed - `pyyaml` is now so useful for round-tripping meta-data (not just in ECSV, even) that that on its own makes a good case. And then we can ensure that here things are in YAML too, reusing some of the machinery (e.g., how to represent quantities).

**Comment by nstarman** [comment]
Thanks for advocating for this @embray . As per my discussion in #11517 with @taldcroft , I was disappointed to learn that Astropy can't use ECSV files within it's own codebase.
I'm going to mark this as WIP and draft while this is discussed, because if pyyaml becomes a dependency, I think ECSV would be the preferred storage format for Cosmologies (with JSON and other file formats as allowed options).
Also, I've been reading through the read/write method implementation on Table, and I think this PR should be done after a similar read/write method is implemented on Cosmology.
Much of the code here would be rendered irrelevant by 1) ECSV and 2) read/write.

**Pull request closed without merging**
