### PR TITLE
Change `BoundingBox` to `ModelBoundingBox`

### PR DESCRIPTION
**Pull request by WilliamJamieson**
### Description

The astropy regions coordinated package also has a very different "BoundingBox" class (https://astropy-regions.readthedocs.io/en/stable/api/regions.BoundingBox.html). The regions package will eventually be merged into astropy core as a new astropy.regions subpackage.  Having two different classes in the core package with the same name isn't ideal. Therefore, it has been suggested that `modeling` rename it's `BoundingBox` class to `ModelBoundingBox`, while regions rename it's `BoundingBox` class to `RegionBoundingBox`.  This PR accomplishes this requested renaming for the `modeling` subpackage.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Tagging @nden and @perrygreenfield for review.

**Review by nden — APPROVED** [review]

**Comment by nden** [comment]
This change was requested by the `regions` package maintainers. I think the failures are unrelated. 
@astrofrog Does it need a backport log?

**Comment by astrofrog** [comment]
This should be labelled as backport-v5.0.x and no changelog entry needed

**Comment by larrybradley** [comment]
Thanks, @WilliamJamieson and @nden! 

For consistency, should `CompoundBoundingBox` also be renamed to `CompoundModelBoundingBox`?

**Comment by pllim** [comment]
Wait a minute... Did you just renamed a public-facing class without even a deprecation or change log?

**Comment by nden** [comment]
No, this hasn't been released before.

**Comment by pllim** [comment]
Ah, okay. Thanks for the clarification! 😌

**Pull request merged**
