### PR TITLE
Simple ascii module for reading very large files. NOT INTENDED FOR ACCEPTANCE AS IS.

### PR DESCRIPTION
**Pull request by aphearin**
@taldcroft , @hamogu , @astrofrog , @eteq - here's a simple reader I wrote for handling very large datasets. This entirely suits my needs for halotools, but as it is written this is not intended to be accepted for use in astropy, because there is some glaring room for improvement in terms of integrating the functionality of existing astropy reader tools, particularly type detection and header processing. 

## Summary of strategy:
Data rows are read line-by-line with a FOR loop over fileobj.readline().strip().split(). I implement very simple, user-defined row- and column-wise cuts on a line-by-line basis, so that memory usage is more or less optimally minimal. The user must specify by hand which columns are desired, and optionally a variable number of max/min-based cuts on a set of columns, and the output is a structured numpy array. 

### Cons:
1) I have not integrated the existing astropy tools for detecting the format of the data, mostly because I couldn't figure out how to hook into this in short order. 
2) Does almost nothing to process the header (see above).
3) Asks a lot more of the user than the other astropy ascii readers, particularly specifying format and column numbers and names by hand. 
4) Makes a hard assumption that the data does not change format throughout the file. 

(1) and (2) will require non-trivial changes to the code, but are not "fundamental" cons. (3) and (4), on the other hand, are basically inextricable from this algorithm. Given that this module is exclusively intended to read in very large datasets, both assumptions seem fine to me.

### Pros:
1) Very fast. Sucks in 0.5-2Gb of ASCII per minute.
2) Memory efficient. The user only needs enough memory to hold the *cut* catalog, no more. 
3) Scalable, due to being based on readline(). It runs without complaint on an 11Gb file on my laptop, for example, which is more RAM than I have. 

### Performance Notes:
I have a cythonized version, which only runs ~10% faster. The basic speed is due to the use of tuple appends, which python seems to be optimized for. I have also tried pre-allocating an empty numpy array with dtype=object, and find no difference in speed. In some simple profiling that I've done, I couldn't find any obvious ways to improve speed.

### CODE REVIEW

**Comment by taldcroft** [comment]
@aphearin - sorry for the delayed response...

This looks like a good pathfinder for this idea, but as you mentioned it really should integrate more with the existing `io.ascii` infrastructure.  In particular this essentially re-implements the basic process of reading and parsing chunks of the file.  By doing that you lose the `io.ascii` API (e.g. selecting different columns, type detection, etc) and the speed of the fast C-based reader.

As for the C-based reader, the idea would be to start with the full read() API and then limit it as needed by disallowing certain keywords that are not implemented (for whatever reason).

One other point about this implementation is the hardwired strategy of applying cuts in order to limit the final data size.  This is not as general as the original suggestion to use a generator to return the table one chunk at a time.  For instance you might want to collect statistics / histograms for the entire table, or whatever.  So the idea is a streaming interface that the user can then process as needed.  We could also implement the cut strategy on top of this as one option.

**Comment by aphearin** [comment]
@taldcroft - yes, I mostly intended for this PR to illustrate the idea of making row- and column-wise cuts on a line-by-line basis so that catalogs can be loaded even when the uncut version would require more than the available memory.

**Comment by taldcroft** [comment]
@aphearin - I suspect that doing the filtering (or cuts) one line at a time will be significantly slower than reading a chunk and then doing a few numpy-based filters.  Making boolean masks is incredibly cheap and fast.

**Comment by aphearin** [comment]
Yeah, putting it that way I think this must be true. Good point.

**Pull request closed without merging**
